### ISSUE TITLE
Unsatisfiable constraint when no explicit package version given

### ISSUE THREAD

**Issue by SteVwonder** [spack/spack#10000]
Installing `flux-core` with an explicit version (i.e., `flux-core@0.9.0`, `flux-core@0.10.0`, `flux-core@master`) works perfectly.  Attempting to install without an explicit version (i.e., `spack install flux-core`) fails when spack cannot seem to satisfy the lua dependency.  It appears as though the concretizer just grabs tha latest version of lua (5.3.X) and then some other verification pass realizes that this doesn't meet the specification for the latest version of flux-core (flux-core@0.10.0 and lua@5.1:5.2.99).

My guess is that this is either:
A) improper specification of dependencies in the flux-core package
B) a bug in the concretizer

Flux's lua dependency specification currently looks like:
```python
    depends_on("lua", type=('build', 'run', 'link'))
    depends_on("lua@5.1:5.1.99", when="@0.1.0:0.9.0")
    depends_on("lua@5.1:5.2.99", when="@0.10.0:,master")
```

Does the `when` argument only apply when a user explicitly adds that variant/customization in the command?

### Steps to reproduce the issue & Error Message

```console
$ spack -d install flux-core
<snip some lines about reading configs and getting locks>
--------------------------------
flux-core

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    lua@5.3.4%gcc@8.2.0 arch=linux-rhel7-x86_64 
        ^ncurses@6.1%gcc@8.2.0~symlinks~termlib arch=linux-rhel7-x86_64 
            ^pkgconf@1.5.4%gcc@8.2.0 arch=linux-rhel7-x86_64 
        ^readline@7.0%gcc@8.2.0 arch=linux-rhel7-x86_64 
        ^unzip@6.0%gcc@8.2.0 arch=linux-rhel7-x86_64 


while trying to concretize the partial spec:

    flux-core@0.10.0%gcc@8.2.0~cuda~docs arch=linux-rhel7-x86_64 
        ^czmq@4.1.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^autoconf@2.69%gcc@8.2.0 arch=linux-rhel7-x86_64 
                ^m4@1.4.18%gcc@8.2.0+sigsegv arch=linux-rhel7-x86_64 
                    ^libsigsegv
                ^perl@5.26.2%gcc@8.2.0+cpanm+shared+threads arch=linux-rhel7-x86_64 
                    ^gdbm@1.18.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
                        ^readline@7.0%gcc@8.2.0 arch=linux-rhel7-x86_64 
                            ^ncurses@6.1%gcc@8.2.0~symlinks~termlib arch=linux-rhel7-x86_64 
                                ^pkgconf@1.5.4%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^automake@1.16.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^libtool@2.4.6%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^libuuid@1.0.3%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^zeromq@4.2.5%gcc@8.2.0+libsodium arch=linux-rhel7-x86_64 
                ^libsodium
        ^hwloc@1.11.9%gcc@8.2.0~cairo~cuda+libxml2+pci+shared arch=linux-rhel7-x86_64 
            ^libpciaccess
                ^util-macros
            ^libxml2
                ^xz
                ^zlib@1.2.11%gcc@8.2.0+optimize+pic+shared arch=linux-rhel7-x86_64 
            ^numactl
        ^jansson@2.9%gcc@8.2.0 build_type=RelWithDebInfo +shared arch=linux-rhel7-x86_64 
            ^cmake@3.13.0%gcc@8.2.0~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel7-x86_64 
                ^openssl@1.1.1%gcc@8.2.0+systemcerts arch=linux-rhel7-x86_64 
        ^lua-luaposix@33.4.0%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^lua@5.3.4%gcc@8.2.0 arch=linux-rhel7-x86_64 
                ^unzip@6.0%gcc@8.2.0 arch=linux-rhel7-x86_64 
        ^munge@0.5.13%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^libgcrypt@1.8.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
                ^libgpg-error@1.27%gcc@8.2.0 arch=linux-rhel7-x86_64 
        ^python@2.7.15%gcc@8.2.0+dbm~optimizations+pic+pythoncmd+shared~tk~ucs4 arch=linux-rhel7-x86_64 
            ^bzip2@1.0.6%gcc@8.2.0+shared arch=linux-rhel7-x86_64 
                ^diffutils@3.6%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^sqlite@3.25.3%gcc@8.2.0~functions arch=linux-rhel7-x86_64 


flux-core requires lua version 5.1:5.2.99, but spec asked for 5.3.4
Traceback (most recent call last):
  File "/g/g0/herbein1/Repositories/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/g/g0/herbein1/Repositories/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/g/g0/herbein1/Repositories/spack/lib/spack/spack/cmd/spec.py", line 72, in spec
    spec.concretize()
  File "/g/g0/herbein1/Repositories/spack/lib/spack/spack/spec.py", line 1865, in concretize
    user_spec_deps=user_spec_deps),
  File "/g/g0/herbein1/Repositories/spack/lib/spack/spack/spec.py", line 2288, in normalize
    visited, all_spec_deps, provider_index, tests)
  File "/g/g0/herbein1/Repositories/spack/lib/spack/spack/spec.py", line 2227, in _normalize_helper
    dep, visited, spec_deps, provider_index, tests)
  File "/g/g0/herbein1/Repositories/spack/lib/spack/spack/spec.py", line 2168, in _merge_dependency
    changed |= spec_deps[dep.name].constrain(dep)
  File "/g/g0/herbein1/Repositories/spack/lib/spack/spack/spec.py", line 2361, in constrain
    raise UnsatisfiableVersionSpecError(self.versions, other.versions)
spack.spec.UnsatisfiableVersionSpecError: An unsatisfiable version constraint has been detected for spec:
<snip repeated spec>
```

### Information on your system

This includes:

 1. TOSS3 system at LLNL

**Comment by healther** [comment]
That is a known shortcoming of the current concretiser, for now we need to provide it with enough hints such that it succeeds. Last I heard was that the new one was supposed to be merged in September (which obviously didn't happen), but maybe @scheibelp knows more

**Comment by alalazo** [comment]
@SteVwonder @tgamblin Are we giving away a mug or something for the 10k issue / PR ? :laughing:

**Comment by healther** [comment]
Or maybe a new concretizer? :angel:

**Comment by SteVwonder** [comment]
> Are we giving away a mug or something for the 10k issue

:laughing: I'll gladly accept and cherish any and all free spack merch sent my way

> or now we need to provide it with enough hints such that it succeeds

Do you have any suggested hints or previous examples that I can look at?

Although not perfect, I suppose I could add version constraints to the `when`-less lua under the assumption that v0.10 is being used when no explicit flux-core version is provided.  Specifically:
```python
    depends_on("lua@5.1:5.2.99", type=('build', 'run', 'link'))
    depends_on("lua@5.1:5.1.99", when="@0.1.0:0.9.0")
    depends_on("lua@5.1:5.2.99", when="@0.10.0:,master")
```
Thoughts?

**Comment by healther** [comment]
For us we have added a number of entries in `etc/spack/packages.yaml`, so in your case you could add a 
```
packages:
  lua:
    version: [5.1.x]
```
That should make it prefer a compatible lua version. The problem occurs because the concretiser has to autocompletes things when it does not yet know enough and then does not backtrack far enough.

**Comment by SteVwonder** [comment]
That would work for me specifically, but we are pushing spack as a good, general way to install and use flux.  So having `spack install flux-core` work "out-of-the-box" is really important to us.  I'm hoping to come up with a solution (even if its a bit hacky) that would work for anyone that clones spack.

Is there a way to provide hints from within the `package.py`?  Maybe the flux package could inspect the spec to determine if an explicit version was given, and if not, set the lua version constraints (i.e., a hint).

> The problem occurs because the concretiser has to autocompletes things when it does not yet know enough and then does not backtrack far enough.

This is the part I don't quite grok.  Does the concretiser start by autocompleting the root package and working its way down?  If so, it would start by setting flux-core to @0.10.0, then when it goes to select the version for lua, it should be able to apply the flux-core@0.10.0 specific constraints (i.e., lua 5.1.X-5.2.X).  Since that doesn't happen, I'm guessing the concretizer starts at the leaves of the dependency tree and works it's way to the root?  Is there a way to set/change the backtracking depth?

**Comment by healther** [comment]
> Is there a way to set/change the backtracking depth?

Afaik, only by providing annotations. Or directly changing the implementation, but I assume that is kind of out of scope ;)

>  I'm hoping to come up with a solution (even if its a bit hacky) that would work for anyone that clones spack.

Iirc the problem only appears with `when`-restricted dependencies, so you could probably remove one of the cases (and the corresponding versions), but that kind of defeats one of the reasons for using spack in the first place...

> That would work for me specifically, but we are pushing spack as a good, general way to install and use flux. So having spack install flux-core work "out-of-the-box" is really important 

I'm not sure if this is a correct statement (yet) with the current state of the concretiser. I _think_ the only way to guarantee that is to not have any restrictions in the dependency settings, but you'll probably catch most bad cases with avoiding `when` clauses
