### ISSUE TITLE
spack find not working as expected when passed specs

### ISSUE THREAD

**Issue by labeln** [spack/spack#10019]
I ran `spack find gromacs ^plumed` to identify gromacs installations built against plumed and found that it unexpectedly returned all installations without regard to a plumed dependency.  I was able to reproduce this behavior with `openmpi`; it is not related to gromacs specifically. 

### Steps to reproduce the issue

Demonstrated with openmpi but I expect any app with at least two builds that have different dependencies could be used. Note that only the first openmpi package has a libfabric or slurm dependency.  

```console
$ spack find --deps -l openmpi
==> 2 installed packages
-- linux-rhel7-x86_64 / gcc@8.2.0 -------------------------------
s7t5pip    openmpi@3.1.3
l5rah2h        ^hwloc@1.11.9
qcb7t3u            ^libpciaccess@0.13.5
5nj33dj            ^libxml2@2.9.8
bcielpo                ^xz@5.2.4
hyog4nv                ^zlib@1.2.11
gv3qat4            ^numactl@2.0.11
5tma6et        ^libfabric@1.6.1
4grmoxm        ^slurm@17.11.8

bpu3gjm    openmpi@3.1.3
l5rah2h        ^hwloc@1.11.9
qcb7t3u            ^libpciaccess@0.13.5
5nj33dj            ^libxml2@2.9.8
bcielpo                ^xz@5.2.4
hyog4nv                ^zlib@1.2.11
gv3qat4            ^numactl@2.0.11


$ spack find -l openmpi ^libfabric
==> 2 installed packages
-- linux-rhel7-x86_64 / gcc@8.2.0 -------------------------------
s7t5pip openmpi@3.1.3  bpu3gjm openmpi@3.1.3


$ spack find -l openmpi ^slurm
==> 2 installed packages
-- linux-rhel7-x86_64 / gcc@8.2.0 -------------------------------
s7t5pip openmpi@3.1.3  bpu3gjm openmpi@3.1.3


```

### Information on your system

I am using spack 0.12.0 on RHEL 7.5.

**Comment by citibeth** [comment]
Why are you using Spack find?  If you're trying to build a script that will find / load / something installed packages, then that will be problematic; because `spack find` is non-deterministic.  It's a decent command-line tool, but definitely not robust.

**Comment by labeln** [comment]
I use `spack find` on the command line.  I noticed the oddity described above when trying to identify all packages with a certain dependency.  I have since learned via the spack channel of other ways to query that information.  @tgamblin pointed out that the behavior I described was a bug, though, so i opened this report to document it.

**Comment by alalazo** [comment]
Confirmed this bug working with Spack at ffdde40f56d48c18ca9c45b0599221ef1dab40a2
