### ISSUE TITLE
Problem pinning jdk version in packages.yaml

### ISSUE THREAD

**Issue by hartzell** [spack/spack#10027]
I'm having trouble pinning a version of the jdk in packages.yaml.  I've been away awhile, so something might have changed that I've missed, but I *can* specify a version for e.g. `gnutls` and have it be used in a `spack spec` (e.g. for emacs +tls).

But, if I specify a version of the JDK it doesn't seem to be used:

### Steps to reproduce the issue

```console
[ghartzell@bifx1n03 spack]$ cat etc/spack/packages.yaml
packages:
  jdk:
    version: ['1.8.0_141-b15']
[ghartzell@bifx1n03 spack]$ spack spec picard
Input spec
--------------------------------
picard

Concretized
--------------------------------
picard@2.18.3%gcc@5.5.0 arch=linux-centos7-x86_64
    ^jdk@11.0.1%gcc@5.5.0 arch=linux-centos7-x86_64
...
```

Am I missing something obvious, or ....

**THANKS**

**Comment by hartzell** [comment]
I suspect this is the same problem as #7950 and #1371 and others.

Any suggested workarounds?

**Comment by citibeth** [comment]
Don't forget #7970...

**Comment by alalazo** [comment]
Seems solved by `clingo`:
```console
$ cat ~/.spack/packages.yaml
packages:
  all:
    providers:
      java: [jdk]
  jdk:
    version: ['1.8.0_141-b15']
$ spack spec picard 
Input spec
--------------------------------
picard

Concretized
--------------------------------
picard@2.26.2%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
    ^jdk@1.8.0_141-b15%gcc@9.4.0 arch=linux-ubuntu20.04-icelake

```
