### ISSUE TITLE
Installation issue: gcc@7.2.0

### ISSUE THREAD

**Issue by jameshclrk** [spack/spack#10035]
### Steps to reproduce the issue

```console
$ spack install gcc@7.2.0
...
>> 29760    /apps/spack/var/spack/stage/gcc-7.2.0-bcsmtl56t3etoswkauritld6bzfnjfzx/gcc-7.2.0/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cc:157:10: fatal error: sys/ustat.h: No such file or directory
     29761     #include <sys/ustat.h>
     29762              ^~~~~~~~~~~~~
     29763    compilation terminated.
...
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux glados 4.18.16-300.fc29.x86_64 #1 SMP Sat Oct 20 23:24:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    Fedora release 29 (Twenty Nine)
``` 

### Additional information

This issue is with the system glibc (2.28).
Broken versions are releases before 7.4.0 (Except 6.5.0 where I believe the fix was backported)

I have attached the patched used in the GCC 6.4.0 Arch Linux user repo package.

[glibc2.28-ustat.patch.txt](https://github.com/spack/spack/files/2652903/glibc2.28-ustat.patch.txt)

I'm not sure if **all** the releases are broken, I think the required addition to the `package.py` is:
```
patch('glibc2.28-ustat.patch', when='@4:6.4,7:7.3')
```

I can submit a pull request if this looks correct

**Comment by adamjstewart** [comment]
> I can submit a pull request if this looks correct

Please do. We've been seeing a lot of GCC 7 build errors lately.
