### ISSUE TITLE
spack env <spec> bash

### ISSUE THREAD

**Issue by balay** [spack/spack#10132]
I'm attempting to use `spack env <spec> bash` as mentioned in:

https://github.com/spack/spack/issues/6051
```
$ spack stage <spec>
$ spack cd <spec>
$ spack env <spec> bash
```
But this doesn't work for me anymore.
```
balay@thetalogin6:~/spack> export SPACK_ROOT=$HOME/spack
balay@thetalogin6:~/spack> source $SPACK_ROOT/share/spack/setup-env.sh
balay@thetalogin6:~> spack env petsc bash
usage: spack env [-h] SUBCOMMAND ...
spack env: error: argument SUBCOMMAND: invalid choice: 'petsc' choose from:
    activate  create  deactivate  list  loads  ls  remove  rm  st  status

balay@thetalogin6:~>
```
Any suggestions on  how to correctly use this feature?
[None of the 'SUBCOMMAND' options look apporpriate here]
Thanks,

**Comment by pramodk** [comment]
`spack env` is not renamed to `spack build_env`

**Comment by wscullin** [comment]
I believe @pramodk meant `spack env` has been renamed to `spack build-env`. The previous `spack env` now is used for spack environments.
