### ISSUE TITLE
Compiler added multiple times to configuration

### ISSUE THREAD

**Issue by alalazo** [spack/spack#10191]
Using `develop` at ec2c5e5b0dfbbf5d70d0ccca91da4e8c149642fc I noticed that the `clang` compiler  I have installed in my system gets added multiple times to the configuration.

### Steps to reproduce the issue
Install `clang-6.0` from the `llvm-toolchain-6.0` repository (Ubuntu 18.04). Then from a clean checkout of Spack:
```console
$ spack compiler add
==> Added 3 new compilers to /home/mculpo/.spack/linux/compilers.yaml
    gcc@8.2.0  gcc@7.3.0  clang@6.0.1-svn334776-1~exp1~20181018152737.116
==> Compilers are defined in the following files:
    /home/mculpo/.spack/linux/compilers.yaml

$ spack compiler list
==> Available compilers
-- clang ubuntu18.04-x86_64 -------------------------------------
clang@6.0.1-svn334776-1

-- gcc ubuntu18.04-x86_64 ---------------------------------------
gcc@8.2.0  gcc@7.3.0

$ spack compiler add
==> Added 1 new compiler to /home/mculpo/.spack/linux/compilers.yaml
    clang@6.0.1-svn334776-1~exp1~20181018152737.116
==> Compilers are defined in the following files:
    /home/mculpo/.spack/linux/compilers.yaml

$ spack compiler list
==> Available compilers
-- clang ubuntu18.04-x86_64 -------------------------------------
clang@6.0.1-svn334776-1  clang@6.0.1-svn334776-1

-- gcc ubuntu18.04-x86_64 ---------------------------------------
gcc@8.2.0  gcc@7.3.0
```

### Error Message
No error messages, just every time I run:
```console
$ spack compiler add
```
`clang` gets added one more time to the configuration. The same doesn't happen for `gcc`.

### Information on your system

I am working on `Ubuntu 18.04` and the bug is triggered by the compilers in this package (which must be installed):
```console
$ dpkg -s clang-6.0
Package: clang-6.0
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 35732
Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
Architecture: amd64
Source: llvm-toolchain-6.0
Version: 1:6.0.1~svn334776-1~exp1~20181018152737.116
Provides: c++-compiler, c-compiler, objc-compiler
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.4), libjsoncpp1 (>= 1.7.4), libllvm6.0 (>= 1:6.0~svn298832-1~), libstdc++6 (>= 5.2), libstdc++-7-dev, libgcc-7-dev, libobjc-7-dev, libclang-common-6.0-dev (= 1:6.0.1~svn334776-1~exp1~20181018152737.116), libclang1-6.0 (= 1:6.0.1~svn334776-1~exp1~20181018152737.116), libc6-dev, binutils
Recommends: llvm-6.0-dev, python, libomp-dev
Suggests: gnustep, gnustep-devel, clang-6.0-doc
Description: C, C++ and Objective-C compiler
 Clang project is a C, C++, Objective C and Objective C++ front-end
 based on the LLVM compiler. Its goal is to offer a replacement to the
 GNU Compiler Collection (GCC).
 .
 Clang implements all of the ISO C++ 1998, 11 and 14 standards and also
 provides most of the support of C++17.
Homepage: https://www.llvm.org/
```

**Comment by alalazo** [comment]
The issue is due to the output of:
```console
$ clang-6.0 --version
clang version 6.0.1-svn334776-1~exp1~20181018152737.116 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
which makes Spack deduce the compiler's version to be:
```
6.0.1-svn334776-1~exp1~20181018152737.116
```
Whenever this version is read from `compilers.yaml` and passed to `autospec`, the parser truncates it to:
```
6.0.1-svn334776-1
```
possibly because `~` is understood to introduce a variant. **I'll submit a fix to `clang` that will result in deducing version 6.0.1 for this particular case**.

**Comment by alalazo** [comment]
@tgamblin @scheibelp @becker33 @adamjstewart Besides #10316, do you think we should do something to allow using reserved characters like `~` in the versions or maybe report an error if they are detected? Right now this case seems not to be treated at all.

**Comment by tgamblin** [comment]
@alalazo: I am loathe to introduce `~` as a valid version character because it's going to really screw up spec parsing.  I also think this is the only case I've ever seen of someone doing this.

What I would do is have `default_version` in `compilers/clang.py` replace the ~'s with `-` or `_` so that the suffix is included in the version for the compiler.
