### ISSUE TITLE
xsltproc bug causes gdk-pixbuf build to fail

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#10222]
I'm trying to install `gdk-pixbuf`, but a bug in our `libxslt` installation causes `xsltproc` to crash. libxslt itself successfully installs and passes all unit tests, but you can see the same error in the build log.

### Steps to reproduce the issue

```console
$ spack install libxslt
```

### Platform and user environment

```commandline
$ uname -a 
Darwin Vesuvius 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
``` 

Also reproduced on Cray CNL5 (Blue Waters).

### Additional information

I see the following error message in the `libxslt` build log, and in the `gdk-pixbuf` build log when it crashes:
```
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
/Users/Adam/spack/var/spack/stage/libxslt-1.1.32-3h3g4g23xwxg5t43vp3rsz44tajrgu6u/libxslt-1.1.32/doc/xsltproc.xml:8: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
]>
  ^
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
error
xsltParseStylesheetFile : cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
compilation error: file /Users/Adam/spack/var/spack/stage/libxslt-1.1.32-3h3g4g23xwxg5t43vp3rsz44tajrgu6u/libxslt-1.1.32/doc/xsltproc.xml line 10 element refentry
xsltParseStylesheetProcess : document is not a stylesheet
make[1]: [xsltproc.1] Error 5 (ignored)
```
I sent a message to the libxslt developers, but never heard back. Has anyone ever seen this before or know of a fix? I have a feeling that `libxml2` and/or `libxslt` should depend on `docbook-xml` and/or `docbook-xsl`, but I'm not confident these packages are being installed correctly. The Homebrew recipes are much more complicated.

**Comment by hartzell** [comment]
`libxslt` installed for me w/out any trouble (same-ish setup as @odoublewen).

I do see the same error w/ `gdk-pixbuf`

```
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
```

Digging.....

**Comment by hartzell** [comment]
Well, *that* was fun.  Wow, Meson.... There's nothing I wanted to do more than [dig into Yet Another Build System](https://xkcd.com/927/).  And to get to dig into XML and XSL at the same time.  Wow.

Thank goodness it's past six.  There's a :cocktail: with my name on it....

**Comment by odoublewen** [comment]
@hartzell scholar and a gentleman!
