### ISSUE TITLE
`spack config edit` in Environments

### ISSUE THREAD

**Issue by citibeth** [spack/spack#10248]
The command `spack -e myenv config edit` edits the main YAML files, not the environment yaml files.

The installation instructions for jdk on macOS contain clear instructions on what to do, which conclude with:

```
    $ spack config edit packages

and adding entries for each installation:

    packages:
        jdk:
            paths:
                jdk@10.0.1_10:    /path/to/jdk/Home
                jdk@1.7.0_45-b18: /path/to/jdk/Home
            buildable: False
```

For an environment-using user, these instructions don't make sense.  `spack config edit` should be fixed so these instructions do work.

### Steps to reproduce the issue

```console
$ spack env create myenv
$ spack -e myenv config edit packages
```

**Comment by alalazo** [comment]
Closing as outdated. As of 9ab21024e26ab0394475d957a0ca2c5246cce35d:
```console
$ spack -e myenv config edit packages
```
open the environment `spack.yaml`, which seems correct.
