### ISSUE TITLE
Installation issue: petsc4py ^python@3:

### ISSUE THREAD

**Issue by benzwick** [spack/spack#10256]
The following (from https://github.com/spack/spack/issues/275#issuecomment-166987195) allows a user to install python 2 and 3 versions of packages, e.g.
```
$ spack install py-scipy
$ spack install py-scipy ^python@3:
```
installs python 2 and 3 versions of scipy.

But the same approach fails to install a python 3 version of petsc4py:
```
$ spack install py-petsc4py ^python@3:
==> Error: An unsatisfiable version constraint has been detected for spec:

    python@3.4:
        ^bzip2
            ^diffutils
        ^ncurses
            ^pkgconfig
        ^openssl
            ^perl@5.14.0:
                ^gdbm
                    ^readline
            ^zlib
        ^sqlite


while trying to concretize the partial spec:

    petsc+mpi
        ^blas
        ^lapack
        ^mpi


petsc requires python version 2.6:2.8, but spec asked for 3.4:
```
The problem is that petsc can only be built using python 2 but petsc4py obviously requires python 3 as requested. Perhaps there is a bug where petsc's build only python dependency:
```
    depends_on('python@2.6:2.8', type='build')
```
is propagated outside of just the build environment?

EDIT: I guess I didn't search hard enough as this seems to be a known issue:
- https://github.com/spack/spack/pull/7926
- https://github.com/spack/spack/pull/2548
- https://github.com/spack/spack/pull/8018

**Comment by balay** [comment]
If you wish to make progress wrt this build - you can hack the above and use:
```
depends_on('python@2.6:2.8,3.4:', type='build')
```
Even if petsc configure is run with python3 - it will internally check - and look for and use /usr/bin/python2. i.e the hack will work as long as you have python2 in PATH.

python3 support is now in petsc@develop. So will add a PR for that..

Note: until petsc4py@3.10.1 is released - you might want to use:
```
spack install py-petsc4py ^python@3 ^petsc@3.10.2
```

**Comment by balay** [comment]
https://github.com/spack/spack/pull/10380
