### ISSUE TITLE
Perl base, extendable naming extensions like python

### ISSUE THREAD

**Issue by 23skdu** [spack/spack#10275]
so when i install python modules for versions other than my system default, it will append the python version to the end, to make it clear what version of python it is linked to.
Like so:
   py-alabaster/0.7.10-py3.5.2
   py-alabaster/0.7.10-py3.6.0
   py-alabaster/0.7.10                             (D)

Perl doesn't do that.
If i install perl-5.24.1, all the extensions will insist on that version, and trying to compile a second perl with all the extensions, it fails to write new lua files appended with the perl version.

is there some way to force this?

**Comment by 23skdu** [comment]
so can i add this to my packages yml to force this? 

suffixes:
+X: x-windows
^python@3.5.2: py3.5.2
^python@3.6.0: py3.6.0

**Comment by 23skdu** [comment]
nevermind. i need to do this in modules.yaml
i guess i can force this, but so far, spack has been handling this for me,
i didn't know i must explicitly set it, 
causes all sorts of issues if not.

**Comment by adamjstewart** [comment]
Yes, if you want the same behavior for Perl as you currently have for Python, just add more `suffixes` to the list in `modules.yaml`. For example:
```yaml
suffixes:
  ^perl@5.24.1: perl5.24.1
```
> i guess i can force this, but so far, spack has been handling this for me, i didn't know i must explicitly set it

These settings aren't built into Spack by default, so either you are using a fork of Spack with different settings or someone else is administering your Spack settings. You can run `spack config blame modules` to find out which file is adding these lines.

**Comment by 23skdu** [comment]
it IS an inherited config, and @hartzell gave me a hint, just by making a comment. and it cleared up the mystery of where it's pulling it in from,  lol.
thanks for the hint george 👍
