### ISSUE TITLE
Lmod Core packages

### ISSUE THREAD

**Issue by mforde84** [spack/spack#10317]
This is presumable already available in Spack. I'm just having a hard time understanding how to implement it. So I apologize ahead of time if this isn't an appropriate ticket. However, I have a use case which is relevant to Core packages in lmod that I want to get your advice on.

Say I want to treat singularity or java-jdk as a core module. I figured out how to do that using white / black listing in the modules.yaml.

In the case of singularity, I want to move singularity images to a desired location within the lmod software stack, then generate a lua files underneath the core singularity which simply points to the container path. Idea being that I could organize singularity files under a hierarchical lmod structure. The issue is I'm not clear on how I can just move the file or generate an appropriate lua file using spack as the methods all appear to be oriented around autoreconf and actual builds. I guess I need the flexibility to do essentially less than that. I can do it manually, but once I update or delete the lmod tree, I lose my manually generated lua files. 

Similarly for java-jdk. I want to take a build directory or even a compiled jar file, place it into a location with within the software stack for java-jdk and generate a lua file that just references the location of the file or root folder.

**Comment by hartzell** [comment]
@mforde -- Can you explain a bit about what you mean by "*software stack*" in these to bits?

> I want to move singularity images to a desired location within the lmod software stack, then generate a lua files underneath the core singularity which simply points to the container path.

and

> I want to take a build directory or even a compiled jar file, place it into a location with within the software stack for java-jdk

Lmod's  "*core*" concept seems to be about separating incompatible, but similar things, e.g. libraries compiled with `gcc@4.8.5` from those compiled with `gcc@8.2.0`; or things built to use one BLAS provider *vs.* another (I'm on shaky ground here though...).  Are you building images for e.g. different versions of singularity?

Are you using Spack to build the Singularity images?  If so, then I'd expect them to land in their own subdir underneath `opt/...` alongside everything else.  Then you might/should be able to parallel the [lapack example in the modules tutorial](https://spack.readthedocs.io/en/latest/tutorial_modules.html#add-lapack-to-the-hierarchy) and get it to behave.

**Comment by mforde** [comment]
@hartzell Wrong tag, I think you wanted @mforde84

**Comment by mforde84** [comment]
Maybe I can simplify the use case. By software stack, we can mean just some precompiled binary.

Say I wanted to generate a separate Core for this binary that would act as sort of a catch all for these types of redistributions, then I just simply wanted to move the binary to a new hierachical location referenced by the the custom lmod core.


e.g.,

Say I have a precompiled binary thats tar-zipped, and located ~/Downloads/software_name_v1.tar.gz. So I need to generate a custom Core for this since it's not compiled locally. Let's call it "custom". Essentially I'd just like to use a spack template to unzip the archive, and move the binary to an appropriate location while generate a lua file pointing to a path:


```
Core
--custom
---pecompiled.lua
Modulefiles
--custom
----precompiled
------software_name
--------1.0.0.lua
Software
--custom
----precompiled
------software_name
--------1.0.0
----------export $PATH=`pwd`:$PATH
```

**Comment by mforde84** [comment]
I haven't tested yet, but would something like this be kosher:



```
# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack import *


class Binary_file(Package):
    """precompiled software."""

    homepage = ""
    url      = "~/Downloads/1.0.0.tar.gz"

    def install(self, spec, prefix):
        with working_dir('bin'):
            mkdirp(prefix.bin)
            source = self.prefix + "/binary_file"
            destination = prefix.bin
            os.rename(source, destination)
        #also say it comes with linked libraries or c headers, how should i handle these?
        with working_dir('include'):
            mkdirp(prefix.include)
            source = self.prefix
            destination = prefix.include
            os.rename(source, destination)
        with working_dir('lib'):
            mkdirp(prefix.include)
            source = self.prefix
            destination = prefix.include
            os.rename(source, destination)
```

**Comment by healther** [comment]
The following should work (in your install method):
```
install_tree('.', prefix)
```
or if there is more than the three directories and you only want these three directories
```
install_tree('bin', prefix.bin)
install_tree('include', prefix.include)
install_tree('lib', prefix.lib)
```
But yeah essentially you have the right idea

**Comment by mforde84** [comment]
Thanks, one more quick question.

How to handle environmental variables within the packages.py. Doe the install_tree function automatically generate these paths? Is there a manual way to set or append/prepend a particular path?

Thanks.
M

**Comment by hartzell** [comment]
I think that you'll end up writing a different package for each of the binaries you want to install, rather than a generic BinaryFile package.  Each of those different packages could inherit from a base package if you'd like.  Lots of examples in the tree.

You can use `setup_environment` (`run_env` in particular) to describe things that you want to push into the end users' environments.  Grep around the tree, lots of examples.  It's documented in [the module file support](https://spack.readthedocs.io/en/latest/module_file_support.html?highlight=dependent#override-api-calls-in-package-py) docs.

Also **highly** recommend grinding through [the modules tutorial](https://spack.readthedocs.io/en/latest/tutorial_modules.html).

**Comment by mforde84** [comment]
Thanks guys. I'll dig deeper. :)

**Comment by hartzell** [comment]
Please follow up and let us know what you end up with!

**Comment by alalazo** [comment]
@mforde84 
> I think that you'll end up writing a different package for each of the binaries you want to install, rather than a generic BinaryFile package. Each of those different packages could inherit from a base package if you'd like. Lots of examples in the tree.

I know I am coming late to this discussion, but for what is worth we use exactly the approach @hartzell described to generate module files for third party software. 

You might want to have a look at how to [hook external packages into Spack](https://spack.readthedocs.io/en/latest/tutorial_configuration.html#external-packages) too (sometimes you can't just copy binaries, but you need to go through some installation wizard or similar - at that point it's easier imo to install the software manually and hook it into Spack via `packages.yaml`).

**Comment by mforde84** [comment]
Yea, I ended up seeing this for the sentieon-genomics package

Quick follow up on this though. Say I build the package locally then decide to hook it into spack, I'd like to build it with whatever dependencies are available within spack. E.g., say I want to build it with a zlib that's in spack as opposed to the default system. I understand that in the packages.py, I can set these this dependancy with depends(), however when I actually build it outside of spack I would need to manually set the appropriate LD_LIBRARY_PATH and CFLAGS to the appropriate $SPACK_ROOT/path/to/depend/lib. Correct?
