### ISSUE TITLE
SSL is Useful/Required for All Python Versions

### ISSUE THREAD

**Issue by citibeth** [spack/spack#10330]
The `python` package states (incorrectly):
```
    # https://docs.python.org/3/whatsnew/3.7.html#build-changes
    depends_on("libffi", when="@3.7:")
    depends_on("openssl@1.0.2:", when="@3.7:")
```

This is based on an incorrect reading of the build-changes for Python 3.7.  In fact, OpenSSL is desired/used by many Python versions, probably going back to Python2.  It is required to access anything SSL over the network; and is also required by Spack itself.  See here, for example, in my build log for `python@3.6` where it tried (an failed) to find/build appropriate SSL support:
```
...
Python build finished successfully!
The necessary bits to build these optional modules were not found:
_ssl                  ossaudiodev           spwd               
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
atexit                pwd                   time               

Failed to build these modules:
_lzma                                                          

running build_scripts
...
```

**Comment by adamjstewart** [comment]
All versions of `python` depend on `openssl`, not just `python@3.7:`. See https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py#L86
