### ISSUE TITLE
Installation issue: diffutils

### ISSUE THREAD

**Issue by grahamlopez** [spack/spack#10346]
'make' needs to be added as a dependency to the diffutils package.

---

### Steps to reproduce the issue

```console
$ spack install diffutils
config.status: error: in `/home/ubuntu/diffutils-3.6':                                                            
config.status: error: Something went wrong bootstrapping makefile fragments    
    for automatic dependency tracking.  Try re-running configure with the            
    '--disable-dependency-tracking' option to at least be able to build                                                                 
    the package (albeit without support for automatic dependency tracking).                                                             
See `config.log' for more details 
```

### Platform and user environment

Please report your OS here:
```console
$ uname -a 
Linux spack 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 18.04.1 LTS
```

### Additional information

This message happens when `make` is not installed on the machine. `sudo apt install make` fixes the error and the build succeeds.

**Comment by grahamlopez** [comment]
That is correct; no make at all.
Spack happily works without make on the machine. I agree that it should be obvious that make is required to build many packages, but having an easier indication of this would be very helpful; the above error message is not obvious. Since Spack seems intent on building the world anyway (e.g. it builds things like 'binutils' and 'tar' which are arguably as/more fundamentally necessary than 'make'), it seems like 'make' should be treated similarly (?)

**Comment by grahamlopez** [comment]
As I've been playing around a little bit more, I recognize that `spack install automake` also depends on a 'make' command being available. Maybe this something to consider in the context of `spack bootstrap`?

**Comment by adamjstewart** [comment]
`automake` doesn't provide a `make` executable, it generates Makefiles. `gmake` provides the `make` executable, but also depends on one already existing. For bootstrapping purposes, `bmake` is the only `make` provider that will work without an existing `make` installation. Since every `MakefilePackage`, `AutotoolsPackage`, `CMakePackage`, `MesonPackage`, and `QMakePackage` requires `make` to be installed, I would consider `make` to be a dependency of Spack.

**Comment by grahamlopez** [comment]
Yeah, you're right about `automake`; I was typing too fast.

If `make` is considered to be a dependency of Spack itself, then I would suggest stating that somewhere so that new users like me don't have to spend time tracking down build failures. Maybe list it at the top of https://spack.readthedocs.io/en/latest/getting_started.html. Even better would be to output a message similar to what is done when Spack can't find any compilers.
