### ISSUE TITLE
Package cannot depend on python@2.7

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#1035]
A lot of Python packages depend on Python 2.7 and/or Python 3.4. If you explicitly say `depends_on('python@2.7')`, it tries to build _exactly_ 2.7 and fails. We should prob make this work.

**Comment by adamjstewart** [comment]
A current workaround is to use `depends_on('python@2.7:2.8')`

**Comment by mathstuf** [comment]
Problem is that `depends_on('foo')` is currently mutually exclusive from `extends('foo')`. Having `extends` strip the version and use it for the `depends_on`, but not the entry in `extendees` would probably be a solution. I'm not familiar enough with the extension logic to know if that's enough though.

**Comment by adamjstewart** [comment]
Does this problem not apply to `extends('python@2.7')` and `depends_on('python@2.7')`?

**Comment by mathstuf** [comment]
I think it applies to that as well. The implementation of `extends` currently calls `_depends_on`, so you'll get at least a `DuplicateDependencyError` at some point. From the docs:

```rst
.. note::

   You can call *either* ``depends_on`` or ``extends`` on any one
   package, but not both.  For example you cannot both
   ``depends_on('python')`` and ``extends(python)`` in the same
   package.  ``extends`` implies ``depends_on``.
```

**Comment by adamjstewart** [comment]
Ah, I see what you're saying. The mutual exclusivity is a problem for your solution, not the cause of the original problem. Gotcha.

**Comment by citibeth** [comment]
Really?  I seem to be doing this just fine.  See the icebin/package.py (unfortunately cannot be added to Spack until PR #543 is merged):

```
from spack import *

class Icebin(CMakePackage):
    """Regridding/Coupling library for GCM + Ice Sheet Model"""

    homepage = "https://github.com/citibeth/icebin"
    url         = "https://github.com/citibeth/icebin/tarball/v0.1.0"

    version('0.1.4', '5c8ecd778255f2972c0caa3a9f5d82ea')
    version('0.1.3', '98d9b28ef8f8a145a7eed2cb1e92e7e4')
    version('0.1.2', '68673158b46b6e88aea6bc4595444adb')
    version('0.1.1', '986b8b51a2564f9c52156a11642e596c')
    version('0.1.0', '1c2769a0cb3531e4086b885dc7a6fd27')

    variant('everytrace', default=False, description='Report errors through Everytrace (requires Everytrace)')
    variant('python', default=True, description='Build Python extension (requires Python, Numpy)')
    variant('gridgen', default=True, description='Build grid generators (requires CGAL, GMP, MPFR)')
    variant('coupler', default=True, description='Build the GCM coupler (requires MPI)')
    variant('pism', default=False, description='Build coupling link with PISM (requires PISM, PETSc)')

    extends('python', when='+python')

    depends_on('everytrace', when='+everytrace')

    depends_on('python@3:', when='+python')
    depends_on('py-cython', when='+python')
    depends_on('py-numpy', when='+python')

    depends_on('cgal', when='+gridgen')
    depends_on('gmp', when='+gridgen')
    depends_on('mpfr', when='+gridgen')

    depends_on('mpi', when='+coupler')
    depends_on('pism~python', when='+coupler+pism')
    depends_on('petsc', when='+coupler+pism')

    depends_on('boost+filesystem+date_time')
    depends_on('blitz')
    depends_on('netcdf-cxx4')
    depends_on('ibmisc+proj+blitz+netcdf+boost+udunits2+python')
    depends_on('proj')
    depends_on('eigen')


    # Build dependencies
    depends_on('cmake')
    depends_on('doxygen')

    def configure_args(self):
        spec = self.spec
        return [
            '-DUSE_EVERYTRACE=%s' % ('YES' if '+everytrace' in spec else 'NO'),
            '-DBUILD_PYTHON=%s' % ('YES' if '+python' in spec else 'NO'),
            '-DBUILD_GRIDGEN=%s' % ('YES' if '+gridgen' in spec else 'NO'),
            '-DBUILD_COUPLER=%s' % ('YES' if '+coupler' in spec else 'NO'),
            '-DUSE_PISM=%s' % ('YES' if '+pism' in spec else 'NO')]

    def setup_environment(self, spack_env, env):
        """Add <prefix>/bin to the module; this is not the default if we
        extend python."""
        env.prepend_path('PATH', join_path(self.prefix, 'bin'))
```

**Comment by tgamblin** [comment]
@citibeth: you've got `@3:` which is more like the workaround.  The issue I think @adamjstewart has is that `depends_on('python@2.7')` doesn't match, say, `python@2.7.11`.

**Comment by adamjstewart** [comment]
@tgamblin: Yes, that's why I opened the PR. But what @citibeth is saying is that icebin can `depends_on('python')` and `extends('python')` at the same time. Which definitely surprises me. Maybe it's because one has a version constraint and the other doesn't? I've def tried this before and had it raise an error message saying I can't depends_on and extends Python at the same time.

**Comment by citibeth** [comment]
@adamjstewart I've added two things to the manual, looking for your thoughts:

1. Sharing your workaround:
```
"""""""""""""""""""
Dependency Formulas
"""""""""""""""""""

This section shows how to write appropriate ``depends_on()``
declarations for some common cases.

* Python 2 only: ``depends_on('python@:2.8')``
* Python 2.7 only: ``depends_on('python@2.7:2.8')``
* Python 3 only: ``depends_on('python@3:')``
```

2. Combining ``extends()`` and ``depends_on()``.  I've been doing this, but am I right that we're not sure if it's legal?  If not, what's the correct way?  Barring any changes, I'm adding to the manual:
```
Some packages produce a Python extension, but are only compatible with
Python 3, or with Python 2.  In those cases, a ``depends_on()``
declaration should be made in addition to the ``extends()`
declaration:

.. code-block:: python

   class Icebin(Package):
       extends('python', when='+python')
       depends_on('python@3:', when='+python')
```

**Comment by adamjstewart** [comment]
Those workarounds look good. In terms of legality, I thought there was some code in place that explicitly prevented you from doing this, but apparently not. The documentation on extends says not to combine it with depends_on as extends implies depends_on. It could be that combining extends and depends_on only works if depends_on is version specific. Ideally, if things were working correctly, you could specify anything you would in depends_on when using extends, but that functionality seems to be broken. I don't have any problems with documenting your use of extends and depends_on together until extends is fixed.

**Comment by eschnett** [comment]
The use of the Python version `2.8` is confusing. I believe the lines above are only correct since we know that there will not be a Python 2.8. I suggest using `2.999` and `2.7.999` instead, respectively, so that readers who are unaware of Python versions will "naively" understand how to carve out version number intervals for their own packages.

**Comment by adamjstewart** [comment]
Hey, I've never actually tried this, but what if we did `python@2.7:2.7`? Does that do anything?

**Comment by eschnett** [comment]
@adamjstewart I believe this will actually try to use that exact version, which does not exist. I at least know there are currently cases where this does not resolve to `2.7.12`, which it should.

**Comment by adamjstewart** [comment]
Oh well. We should really try to fix this one day. It works for compilers. `%gcc@5` will resolve to `%gcc@5.1.0` if that is the only GCC 5 available.

**Comment by citibeth** [comment]
I just tried it; it produced `python@2.7`, which is not a real version
number.

I don't think this is a big problem with Spack.  There IS an idiomatic way
to do things, even if that way is a little strange-looking at first.

**Comment by eschnett** [comment]
Should we -- in the mean time -- fix the packages to not use `python@2` since it doesn't actually work?

**Comment by citibeth** [comment]
Sounds like the right approach to me.

**Comment by alalazo** [comment]
duplicates #921

**Comment by adamjstewart** [comment]
Closing this as a duplicate of #921
