### ISSUE TITLE
PYTHONPATH must include installation directory

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#1036]
I'm trying to install py-iminuit, which I'm working on a package for, but it fails with the following error:

```
TEST FAILED: /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-iminuit-1.2-cp2mvhi2hmkxxya5hhmq3plzkoar6c7r/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-iminuit-1.2-cp2mvhi2hmkxxya5hhmq3plzkoar6c7r/lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-cython-0.23.5-cpnjauarbt4asqv2jixnbhoaxzxtqnze/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-matplotlib-1.4.3-m7w7su6vlayokqgzj7tmadxrn3omyzqg/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-dateutil-2.5.2-tnhd7ke3wntxskmyqnhzuoshaef5xqtq/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-setuptools-20.7.0-ximunmokiogzszdg2xl6azd67g4x6ooh/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-six-1.10.0-mnj5r5qtaoaql64weituixzpnwkdq4qj/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-funcsigs-0.4-wiiyrkibhhk7mbopqy2bt4gzzmaccq2x/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-mock-1.3.0-kpfgtcedqyuu5b4t5dm6lr7eyabuymc2/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-pbr-1.8.1-q23eqxzg2kle6pzev7dj6ujmbusnupvw/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-nose-1.3.7-vm457qch3abnvhy76wc4a6eltoswbiph/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-numpy-1.11.0-tduopn7ynp5tmzljhqy7ncgjxtfc4zau/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-pyparsing-2.0.3-a6kohzoukgxopv57e5t53ejz3ifkhk74/lib/python2.7/site-packages:/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-6.1.0/py-pytz-2016.3-npnc3eug3zky2j6skgjg4xizkanijpfn/lib/python2.7/site-packages'

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
```

It seems that we need to add the installation directory to PYTHONPATH before installation. I could hack it for this package pretty easily, but is there a way to do this for all Python modules?

**Comment by adamjstewart** [comment]
This package also complains that the installation directory doesn't exist yet. Maybe it's just really cranky.

**Comment by lee218llnl** [comment]
We've seen this issue before and I thought we resolved it. This was a while ago, so I don't remember what causes it or what the solution was. Can you post your package.py so I can try to reproduce the issue? Maybe that'll help jog my memory.

**Comment by adamjstewart** [comment]
```python
from spack import *


class PyIminuit(Package):
    """Interactive IPython-Friendly Minimizer based on SEAL Minuit2."""

    homepage = "https://pypi.python.org/pypi/iminuit"
    url      = "https://pypi.python.org/packages/c9/fd/87931ec898e16557b8f6ae6e576743d00ca085c1cb4eb4673d8f4b02ac20/iminuit-1.2.tar.gz"

    version('1.2', '4701ec472cae42015e26251703e6e984')

    # Required dependencies
    extends('python@2.7:2.8,3.4:')
    depends_on('py-setuptools')

    # Optional dependencies
    depends_on('py-numpy')
    depends_on('py-matplotlib')

    def install(self, spec, prefix):
        site_packages = '{0}/lib/python{1}/site-packages'.format(
            prefix, spec['python'].version.up_to(2))

        # site-packages directory must already exist
        mkdirp(site_packages)

        # PYTHONPATH must include site-packages directory
        env['PYTHONPATH'] += ':{0}'.format(site_packages)

        python('setup.py', 'install', '--prefix={0}'.format(prefix))
```

If you leave out the site-packages stuff in `install()`, you should be able to recreate the problem.

**Comment by adamjstewart** [comment]
Just to clarify, when I said it complains that the installation directory doesn't exist, I meant the site-packages directory, which is a subdirectory of the installation directory.

**Comment by mathstuf** [comment]
There's the `--single-version-externally-managed` flag we could pass to skip this error.

**Comment by adamjstewart** [comment]
This problem is also occurring for me for py-matplotlib@1.5.1 now. That makes it slightly more serious since that's a popular package.

**Comment by lee218llnl** [comment]
@mathstuf is right, you can change your setup line to:

python('setup.py', 'install', '--single-version-externally-managed', '--root=/', '--prefix={0}'.format(prefix))

Note you also need the "--root=/" option. 

I'm pretty sure I've seen this issue before, but don't remember the context (it might not have been w.r.t. Spack). @tgamblin do you recall seeing this issue before?

**Comment by adamjstewart** [comment]
py-h5py is now requiring me to do this as well. Adding both of the options that @lee218llnl suggested seems to solve the problem, although it might be more ideal if we can do something outside of the packages themselves since so many of them are requiring this. We obviously can't add these options outside of the package, but we could create these installation directories and add them to PYTHONPATH before installation.

**Comment by adamjstewart** [comment]
py-astropy too. Is no one else seeing this?

**Comment by adamjstewart** [comment]
And py-sncosmo, which I'm adding.

**Comment by mathstuf** [comment]
I wonder if it is due to using setuptools versus distutils?

**Comment by lee218llnl** [comment]
@adamjstewart I think part of the problem is because you "extends('python@2.7:2.8,3.4:')" instead of just "extends('python'). I'm tracing the roots of this, but ultimately Spack thinks that the former does not extend the python package, which prevents the destination site-packages directory from being added to PYTHONPATH

**Comment by adamjstewart** [comment]
See #1034. I think the problem might be that the Python I was installing to also happened to be the Python that I was running Spack with. I'm going to try uninstalling and reinstalling everything.

**Comment by adamjstewart** [comment]
Alright, everything is finally copacetic. I was trying to install with the same Python package that I was installing to, so that was a problem. I also had never-ending trouble when trying to specify the versions for Python extensions, so I stopped doing that. I also accidentally deleted the py-astropy installation without deactivating it first, so I had to delete the binaries, egg, and remove it from extensions.yaml.

I have no idea which of these things was causing which problem, but I also don't care anymore. It's Friday :smiley:

**Comment by lee218llnl** [comment]
ha ha, couldn't resist adding a reaction. FWIW, I think it's the version specification.

**Comment by adamjstewart** [comment]
Yeah, I think you're right. It works sometimes (`spack spec`, `spack install`) but not others (`spack activate`). I also feel like it made `spack spec` very slow. It's troubling, because a lot of Python packages only work on specific versions of Python, so I would love to be able to specify which. But Spack just can't handle it at the moment.

**Comment by mathstuf** [comment]
I wonder if `extends` could use the version for its `depends_on`, but not the other parts.

**Comment by pramodk** [comment]
>  I was trying to install with the same Python package that I was installing to, so that was a problem. 

@adamjstewart : I am having same trouble. I am using `/usr/bin/python` for running spack and trying to install some other python packages/extensions. Isn't this supported?

**Comment by adamjstewart** [comment]
@pramodk You're using `/usr/bin/python` as an external package and trying to install Python modules with it? We should support it, but that doesn't necessarily mean it works. Aside from rebuilding something that is already installed on your system, is there any reason you can't install a new Python with Spack?

**Comment by pramodk** [comment]
> you're using /usr/bin/python as an external package and trying to install Python modules with it?

 Yes!

> We should support it, but that doesn't necessarily mean it works.

didn't work, got errors similar to yours : 

```
..............
You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting)
...............
```

> Aside from rebuilding something that is already installed on your system, is there any reason you can't install a new Python with Spack?

no specific reason, I will install python from spack.

**Comment by healther** [comment]
Isn't this solved since we now use `--single-version-externally-managed` by default?

**Comment by adamjstewart** [comment]
I'm not able to reproduce this anymore, so I think it must be fixed.
