### ISSUE TITLE
Switch cmake/package.py to use fast configure --parallel=<N> instead of slow bootstrap

### ISSUE THREAD

**Issue by bartlettroscoe** [spack/spack#10385]
**snl-atdm-issue**

@tgamblin was mentioning me to me how slow it was to build CMake because the checks in 'bootstrap' are so slow.  When we build CMake, we don't use 'bootstrap', we use 'configure' with the --parallel option.  For example, to configure and build Cmake correctly, you have to do:

```
$ mkdir build/
$ cd build/
$ env  CXXFLAGS=-O3 CFLAGS=-O3 \
   ../<cmake_src_dir>/configure --parallel=32 --prefix=<install_dir>
$ make -j32
$ make install
```

That builds pretty fast.

It is **critical** to set `CXXFLAGS=-O3 CFLAGS=-O3` when you configure or you will get a `-O0` build of CMake!

**Comment by haampie** [comment]
This is implemented in the meantime... still very slow.

Edit, you were right about the CXXFLAGS & CFLAGS!
