### ISSUE TITLE
Provide mechanism for identifying a package's license

### ISSUE THREAD

**Issue by rhc54** [spack/spack#10450]
*Please add a concise summary of your suggestion here.*
Software packages that can be built by Spack have their own licenses. It would be nice to have a way of providing that license information in the corresponding Spack package script.

### Rationale
Users who build against a given package are impacted by the license governing that software. It would be more convenient if Spack could include that information, along with a simple command line method for reporting it, so that users don't have to track it down on the package's web site.

*Is your feature request related to a problem? Please describe it!*
There is a potential that users could mistakenly assume that a package built by Spack was under the 
Spack license, and inadvertently link their software to a package that has implications for its distribution.

### Description
I believe one could add a simply line similar to the current identifier:
```
SPDX-License-Identifier: (Apache-2.0 OR MIT)
```
that identifies the underlying package's license. A Python script could perhaps scrape that information for printout when requested by a user, or some other mechanism employed.

**Comment by ax3l** [comment]
Great suggestion, other package managers such as conda-forge include the package's software-license as well. Maybe we should just define a member in packages for it, naming the SPDX license identifier.

**Comment by alalazo** [comment]
License directive was added in Spack v0.21 https://github.com/spack/spack/commit/65d3221a9c436e77af9e802e543c71bd702ff4e2
