### ISSUE TITLE
dyninst fails to install on F29

### ISSUE THREAD

**Issue by woodard** [spack/spack#10486]
Dyninst fails to install within spack even though building from source from the git repo is fine.
[spack-build.out.gz](https://github.com/spack/spack/files/2818187/spack-build.out.gz)

==> Installing dyninst
==> Searching for binary cache of dyninst
==> Warning: No Spack mirrors are currently configured
==> No binary for dyninst found: installing from source
==> Using cached archive: /home/ben/Work/spack/var/spack/cache/dyninst/dyninst-10.0.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> Staging archive: /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst-10.0.0.tar.gz
==> Created stage in /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt
==> No patches needed for dyninst
==> Building dyninst [CMakePackage]
==> Executing phase: 'cmake'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

8 errors found in build log:
     1588    [ 47%] Building CXX object parseAPI/CMakeFiles/parseAPI.dir/__/dataflowAPI/rose/util/Message.C.o
     1589    cd /tmp/ben/spack-stage/spack-stage-VToZK9/dyninst/spack-build/parseAPI && /home/ben/Work/spack/lib/spack/env/gcc/
             g++  -DBOOST_ALL_NO_LIB=1 -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DDATAFLOW_LIB -DDYNINST_LITTLE_ENDIAN -DPARSE
             R_LIB -DUSE_PARSE_API -DWITHOUT_SYMLITE -DWITH_SYMTAB_API -Darch_64bit -Darch_x86_64 -Dbug_force_terminate_failure
              -Dbug_syscall_changepc_rewind -Dcap_32_64 -Dcap_async_events -Dcap_binary_rewriter -Dcap_dwarf -Dcap_dynamic_heap
              -Dcap_fixpoint_gen -Dcap_liveness -Dcap_mutatee_traps -Dcap_noaddr_gen -Dcap_ptrace -Dcap_registers -Dcap_stack_m
             ods -Dcap_stripped_binaries -Dcap_thread_db -Dcap_threads -Dcap_tramp_liveness -Dos_linux -DparseAPI_EXPORTS -Dx86
             _64_unknown_linux2_4 -I/home/ben/Work/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.1/elfutils-0.175-w4suym4uptazi
             hho63hpg2atssedvpbe/include -I/home/ben/Work/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.1/boost-1.69.0-lvb5vdpp
             tyikvetiuzkur2uaukuwrm37/include -I/tmp/ben/spack-stage/spack-stage-VToZK9/dyninst/spack-build -I/tmp/ben/spack-st
             age/spack-stage-VToZK9/dyninst/spack-build/common/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbt
             pvxd2rhgpb33j36wdjm7oplt/dyninst/common/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb
             33j36wdjm7oplt/dyninst/dataflowAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36
             wdjm7oplt/dyninst/dyninstAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7o
             plt/dyninst/instructionAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7opl
             t/dyninst/parseAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dynins
             t/patchAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/procco
             ntrol/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/stackwalk/h
              -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/symtabAPI/h -I/hom
             e/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dwarf/h -I/home/ben/Work/
             spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/elf/h -I/home/ben/Work/spack/var/spa
             ck/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/symlite/h -I/home/ben/Work/spack/var/spack/stage/
             dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti
             4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/external -I/home/ben/Work/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.1/int
             el-tbb-2019.2-spudoqkew7t3ksutocox6zc5lf6ycamr/include -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4
             pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/parseAPI/src  -std=c++11  -fvisibility=hidden -fvisibility-inlines-hidden -W -
             Wall -Wpointer-arith -Wcast-qual -Woverloaded-virtual -Wcast-align -Wno-non-template-friend -Wno-unused-local-type
             defs -Wno-deprecated-declarations -O2 -g  -fPIC   -fopenmp -w -o CMakeFiles/parseAPI.dir/__/dataflowAPI/rose/util/
             Message.C.o -c /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/datafl
             owAPI/rose/util/Message.C
     1590    [ 47%] Building CXX object parseAPI/CMakeFiles/parseAPI.dir/__/dataflowAPI/rose/util/Sawyer.C.o
     1591    cd /tmp/ben/spack-stage/spack-stage-VToZK9/dyninst/spack-build/parseAPI && /home/ben/Work/spack/lib/spack/env/gcc/
             g++  -DBOOST_ALL_NO_LIB=1 -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DDATAFLOW_LIB -DDYNINST_LITTLE_ENDIAN -DPARSE
             R_LIB -DUSE_PARSE_API -DWITHOUT_SYMLITE -DWITH_SYMTAB_API -Darch_64bit -Darch_x86_64 -Dbug_force_terminate_failure
              -Dbug_syscall_changepc_rewind -Dcap_32_64 -Dcap_async_events -Dcap_binary_rewriter -Dcap_dwarf -Dcap_dynamic_heap
              -Dcap_fixpoint_gen -Dcap_liveness -Dcap_mutatee_traps -Dcap_noaddr_gen -Dcap_ptrace -Dcap_registers -Dcap_stack_m
             ods -Dcap_stripped_binaries -Dcap_thread_db -Dcap_threads -Dcap_tramp_liveness -Dos_linux -DparseAPI_EXPORTS -Dx86
             _64_unknown_linux2_4 -I/home/ben/Work/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.1/elfutils-0.175-w4suym4uptazi
             hho63hpg2atssedvpbe/include -I/home/ben/Work/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.1/boost-1.69.0-lvb5vdpp
             tyikvetiuzkur2uaukuwrm37/include -I/tmp/ben/spack-stage/spack-stage-VToZK9/dyninst/spack-build -I/tmp/ben/spack-st
             age/spack-stage-VToZK9/dyninst/spack-build/common/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbt
             pvxd2rhgpb33j36wdjm7oplt/dyninst/common/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb
             33j36wdjm7oplt/dyninst/dataflowAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36
             wdjm7oplt/dyninst/dyninstAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7o
             plt/dyninst/instructionAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7opl
             t/dyninst/parseAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dynins
             t/patchAPI/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/procco
             ntrol/h -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/stackwalk/h
              -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/symtabAPI/h -I/hom
             e/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dwarf/h -I/home/ben/Work/
             spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/elf/h -I/home/ben/Work/spack/var/spa
             ck/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/symlite/h -I/home/ben/Work/spack/var/spack/stage/
             dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti
             4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/external -I/home/ben/Work/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.1/int
             el-tbb-2019.2-spudoqkew7t3ksutocox6zc5lf6ycamr/include -I/home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4
             pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/parseAPI/src  -std=c++11  -fvisibility=hidden -fvisibility-inlines-hidden -W -
             Wall -Wpointer-arith -Wcast-qual -Woverloaded-virtual -Wcast-align -Wno-non-template-friend -Wno-unused-local-type
             defs -Wno-deprecated-declarations -O2 -g  -fPIC   -fopenmp -w -o CMakeFiles/parseAPI.dir/__/dataflowAPI/rose/util/
             Sawyer.C.o -c /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflo
             wAPI/rose/util/Sawyer.C
     1592    In file included from /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst
             /dataflowAPI/rose/util/Assert.C:9:
     1593    /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflowAPI/rose/util
             /Message.h: In member function 'bool Sawyer::Message::ColorSpec::isDefault() const':
  >> 1594    /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflowAPI/rose/util
             /Message.h:389:96: error: cannot convert 'boost::logic::tribool' to 'bool' in return
     1595         bool isDefault() const { return COLOR_DEFAULT==foreground && COLOR_DEFAULT==background && !bold; }
     1596                                                                                                    ^~~~
  >> 1597    make[2]: *** [parseAPI/CMakeFiles/parseAPI.dir/build.make:742: parseAPI/CMakeFiles/parseAPI.dir/__/dataflowAPI/ros
             e/util/Assert.C.o] Error 1
     1598    make[2]: *** Waiting for unfinished jobs....
     1599    In file included from /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst
             /dataflowAPI/rose/util/Message.C:8:
     1600    /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflowAPI/rose/util
             /Message.h: In member function 'bool Sawyer::Message::ColorSpec::isDefault() const':
  >> 1601    /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflowAPI/rose/util
             /Message.h:389:96: error: cannot convert 'boost::logic::tribool' to 'bool' in return
     1602         bool isDefault() const { return COLOR_DEFAULT==foreground && COLOR_DEFAULT==background && !bold; }
     1603                                                                                                    ^~~~
     1604    /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflowAPI/rose/util
             /Message.C: In member function 'void Sawyer::Message::StreamBuf::bake()':
  >> 1605    /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflowAPI/rose/util
             /Message.C:1126:42: error: cannot convert 'boost::logic::tribool' to 'bool' in assignment
     1606                 anyUnbuffered_ = !bi->second.isBuffered;
     1607                                              ^~~~~~~~~~
     1608    In file included from /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst
             /dataflowAPI/rose/util/Sawyer.C:9:
     1609    /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflowAPI/rose/util
             /Message.h: In member function 'bool Sawyer::Message::ColorSpec::isDefault() const':
  >> 1610    /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/dataflowAPI/rose/util
             /Message.h:389:96: error: cannot convert 'boost::logic::tribool' to 'bool' in return
     1611         bool isDefault() const { return COLOR_DEFAULT==foreground && COLOR_DEFAULT==background && !bold; }
     1612                                                                                                    ^~~~
  >> 1613    make[2]: *** [parseAPI/CMakeFiles/parseAPI.dir/build.make:768: parseAPI/CMakeFiles/parseAPI.dir/__/dataflowAPI/ros
             e/util/Sawyer.C.o] Error 1
  >> 1614    make[2]: *** [parseAPI/CMakeFiles/parseAPI.dir/build.make:755: parseAPI/CMakeFiles/parseAPI.dir/__/dataflowAPI/ros
             e/util/Message.C.o] Error 1
     1615    make[2]: Leaving directory '/tmp/ben/spack-stage/spack-stage-VToZK9/dyninst/spack-build'
  >> 1616    make[1]: *** [CMakeFiles/Makefile2:1090: parseAPI/CMakeFiles/parseAPI.dir/all] Error 2
     1617    make[1]: Leaving directory '/tmp/ben/spack-stage/spack-stage-VToZK9/dyninst/spack-build'
     1618    make: *** [Makefile:133: all] Error 2

See build log for details:
  /home/ben/Work/spack/var/spack/stage/dyninst-10.0.0-emti4pbtpvxd2rhgpb33j36wdjm7oplt/dyninst/spack-build.out

**Comment by woodard** [comment]
This was done with a fresh clone of spack with no custom packages or local packages satisfying dependencies. It does pull in quite a few things though.

[ben@Mustang spack]$ bin/spack find
==> 47 installed packages
-- linux-fedora29-x86_64 / gcc@8.2.1 ----------------------------
autoconf@2.69    diffutils@3.7     hwloc@1.11.11     libiconv@1.15        lzma@4.32.7  numactl@2.0.12  rhash@1.3.5
automake@1.16.1  elfutils@0.175    hypre@2.15.1      libpciaccess@0.13.5  lzo@2.09     openblas@0.3.5  tar@1.30
binutils@2.31.1  elfutils@0.175    intel-tbb@2019.2  libsigsegv@2.11      m4@1.4.18    openmpi@3.1.3   util-macros@1.19.1
boost@1.69.0     expat@2.2.5       laghos@2.0        libtool@2.4.6        metis@5.1.0  openssl@1.1.1   xz@5.2.4
bzip2@1.0.6      gdbm@1.18.1       libarchive@3.3.2  libuv@1.25.0         mfem@3.4.0   perl@5.26.2     zlib@1.2.11
cmake@3.13.3     gettext@0.19.8.1  libbsd@0.9.1      libxml2@2.9.8        ncurses@6.1  pkgconf@1.5.4
curl@7.60.0      gmp@6.1.2         libiberty@2.31.1  lz4@1.8.1.2          nettle@3.4   readline@7.0

It looks like the problem may be with boost and so a work around may be to use a local dependency for that.

**Comment by woodard** [comment]
Building with the following packages.yaml allows dyninst to build successfully:

packages:
  boost:
    paths:
      boost@1.66.0%gcc@8.2.1 arch=linux-fedora29-x86_64: /usr/lib64/

**Comment by citibeth** [comment]
Should a version restriction for `boost` be added to `dyninst/package.py`?

**Comment by woodard** [comment]
I’d suggest some more detailed empirical testing. It looks like something that could be a minor bug in dyninst. If it is a version incompatibility, I bet either Sasha or Xaixhiu could quickly fix it and so it may be that 10.0.0 needs boost <1.66 or whatever but 10.0.1 (for example) doesn’t have that limitation.

**Comment by citibeth** [comment]
> I’d suggest some more detailed empirical testing. 

@woodard???  Spack is more like a "software installation commune" than a product to magically install software.  If Spack installs 100 packages and works for 99 of them, then it's saved you a lot of effort.  If you can figure out how to fix the recipe on the last 1 package and contribute back, then this will make someone else's life easier.

**Comment by citibeth** [comment]
I added @adamjstewart as a requested reviewer for #10454.  Normally these kinds of PRs get reviewed and merged pretty quickly.  No problem with submitting another PR once Dyninst comes out with 10.1.

**Comment by woodard** [comment]
Thanks mark. It sounds like his patch is the right way to go until 10.1 where it can be dropped.

**Comment by citibeth** [comment]
It can only be dropped if nobody wants to run 10.0

**Comment by scheibelp** [comment]
Closed by https://github.com/spack/spack/pull/10454. Feel free to reopen if the problem persists.
