### ISSUE TITLE
lua build isn't using rpath to link ncurses on clang or intel compilers

### ISSUE THREAD

**Issue by cyrush** [spack/spack#1048]
using spack to build lua, the lua executable doesn't run when built with clang, or intel compilers.

The issue is with ncurses, which is being lined with -L and -l. I know spack does rpath magic in the compiler wrappers, but the rpath magic doesn't appear to work for the lua build. 

Here is some more info:

Looking at the build line for lua:

```
         'MYLDFLAGS=-L%s -L%s ' % (
             spec['readline'].prefix.lib,
             spec['ncurses'].prefix.lib),
         'MYLIBS=-lncurses',
```

and an older one  (this is the one we actually built with)

```
    make('INSTALL_TOP=%s' % prefix,
         'MYLDFLAGS=-L%s -lncurses' % spec['ncurses'].prefix.lib,
         target)
```

Here is an example of the error we get when trying to run lua built with intel:

../spack/opt/spack/chaos_5_x86_64_ib/intel-15.0.187/lua-5.1.5-rfr5m5nbtre7gkouhvst6waau6mi5qvl/bin/lua
../spack/opt/spack/chaos_5_x86_64_ib/intel-15.0.187/lua-5.1.5-rfr5m5nbtre7gkouhvst6waau6mi5qvl/bin/lua: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory

Here are the ldd calls for the lua bins built with clang and intel:

surface86>:ldd .../spack/opt/spack/chaos_5_x86_64_ib/intel-15.0.187/lua-5.1.5-rfr5m5nbtre7gkouhvst6waau6mi5qvl/bin/lua
    linux-vdso.so.1 =>  (0x00002aaaaaacb000)
    libncurses.so.6 => not found
    libm.so.6 => /lib64/libm.so.6 (0x00002aaaaaccd000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaaf51000)
    libreadline.so.6 => /lib64/libreadline.so.6 (0x00002aaaab155000)
    libhistory.so.6 => /usr/lib64/libhistory.so.6 (0x00002aaaab399000)
    libc.so.6 => /lib64/libc.so.6 (0x00002aaaab5a1000)
    /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
    libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00002aaaab935000)

surface86> ldd ../spack/opt/spack/chaos_5_x86_64_ib/clang-3.5.0/lua-5.1.5-bwdki5a4w3r6zn3sydcxkstccezfmgys/bin/lua 
    linux-vdso.so.1 =>  (0x00002aaaaaacb000)
    libncurses.so.6 => not found
    libm.so.6 => /lib64/libm.so.6 (0x00002aaaaaccd000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaaf51000)
    libreadline.so.6 => /lib64/libreadline.so.6 (0x00002aaaab155000)
    libhistory.so.6 => /usr/lib64/libhistory.so.6 (0x00002aaaab399000)
    libc.so.6 => /lib64/libc.so.6 (0x00002aaaab5a1000)
    /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
    libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00002aaaab935000)

and here is an ldd for a lua install built with gcc -- which works. 
(you can see the full path is embedded)

surface86@cyrush:ldd ../spack/opt/spack/chaos_5_x86_64_ib/gcc-4.9.3/lua-5.1.5-axspkephlc7v6bqv5jnxcx4ronj57cd4/bin/lua
    linux-vdso.so.1 =>  (0x00002aaaaaacb000)
    libncurses.so.6 => {FULL_PATH}/spack/opt/spack/chaos_5_x86_64_ib/gcc-4.9.3/ncurses-6.0-ghvns4xykjcblstayazsihjaemwvpbhq/lib/libncurses.so.6 (0x00002aaaaaccd000)
    libm.so.6 => /lib64/libm.so.6 (0x00002aaaaaf74000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaab1f8000)
    libreadline.so.6 => {FULL_PATH}/spack/opt/spack/chaos_5_x86_64_ib/gcc-4.9.3/readline-6.3-q7yywgagvkriovs6ofvlv74cunn5fmnm/lib/libreadline.so.6 (0x00002aaaab3fd000)
    libhistory.so.6 => {FULL_PATH}/spack/opt/spack/chaos_5_x86_64_ib/gcc-4.9.3/readline-6.3-q7yywgagvkriovs6ofvlv74cunn5fmnm/lib/libhistory.so.6 (0x00002aaaab643000)
    libc.so.6 => /lib64/libc.so.6 (0x00002aaaab84c000)
    /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)

**Comment by alalazo** [comment]
Closing this since it doesn't seem to be an issue anymore:
```console
$ spack --version
0.14.0-142-f38620e5e

$ ldd /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/lua-5.3.5-t7lh6zfmagx3n7ewu6ds26wcfex75q2w/bin/lua
	linux-vdso.so.1 (0x00007ffe92f1f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8742b62000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f874295e000)
	libreadline.so.8 => /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/readline-8.0-umxj2ubbehijji6klo6dvf2kyhrtroqt/lib/libreadline.so.8 (0x00007f874270e000)
	libncursesw.so.6 => /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/ncurses-6.1-nfltiu4foeoykdha5iz3x6wr23wwglz4/lib/libncursesw.so.6 (0x00007f87424dc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f87420eb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8742f00000)
	libtinfow.so.6 => /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/ncurses-6.1-nfltiu4foeoykdha5iz3x6wr23wwglz4/lib/libtinfow.so.6 (0x00007f8741ead000)

$ objdump -x /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/lua-5.3.5-t7lh6zfmagx3n7ewu6ds26wcfex75q2w/bin/lua | grep RPATH
  RPATH                /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/lua-5.3.5-t7lh6zfmagx3n7ewu6ds26wcfex75q2w/lib:/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/lua-5.3.5-t7lh6zfmagx3n7ewu6ds26wcfex75q2w/lib64:/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/readline-8.0-umxj2ubbehijji6klo6dvf2kyhrtroqt/lib:/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.0/ncurses-6.1-nfltiu4foeoykdha5iz3x6wr23wwglz4/lib
```
