### ISSUE TITLE
NumPy: dynamic module does not define module export function (PyInit_multiarray)

### ISSUE THREAD

**Issue by floli** [spack/spack#10498]
On a Ubuntu 16.04 machine, I git cloned spack and installed the `py-numpy` package, which went fine.

```
% spack find
==> 14 installed packages
-- linux-ubuntu16.04-x86_64 / gcc@5.4.0 -------------------------
bzip2@1.0.6  diffutils@3.7  gdbm@1.18.1  ncurses@6.1  openblas@0.3.5  openssl@1.1.1  perl@5.26.2  pkgconf@1.5.4  py-numpy@1.15.2  py-setuptools@40.4.3  python@2.7.15  readline@7.0  sqlite@3.26.0  zlib@1.2.11
```

but when I try to import it, it fails:
```
% python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/home/lindnefn/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/py-numpy-1.15.2-6lbvjlvob62ttz23e2dqmy4sgs7zi4ii/lib/python2.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dynamic module does not define module export function (PyInit_multiarray)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lindnefn/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/py-numpy-1.15.2-6lbvjlvob62ttz23e2dqmy4sgs7zi4ii/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/lindnefn/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/py-numpy-1.15.2-6lbvjlvob62ttz23e2dqmy4sgs7zi4ii/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/lindnefn/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/py-numpy-1.15.2-6lbvjlvob62ttz23e2dqmy4sgs7zi4ii/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/lindnefn/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/py-numpy-1.15.2-6lbvjlvob62ttz23e2dqmy4sgs7zi4ii/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/lindnefn/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/py-numpy-1.15.2-6lbvjlvob62ttz23e2dqmy4sgs7zi4ii/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dynamic module does not define module export function (PyInit_multiarray)
```

Thanks!

**Comment by scheibelp** [comment]
There's a few things going on here:

* When you invoke `python3`, you are not using Spack's python. The output of `spack find` suggests that you built `py-numpy` with python 2.7.15 
* If you want to run the Spack-built py-numpy, you'll want to make sure that you're using Spack's Python and Spack's numpy. There's at least a couple ways to do this:
  * Create a view (`spack view soft --help`) with py-numpy, and add the view's bin directory to your `PATH`
  * Load the Spack-created modules for `py-numpy`, depending on the configuration, you can generate module files that load transitive dependencies automatically. See: https://spack.readthedocs.io/en/latest/tutorial_modules.html#module-files
  * You can also create an environment (https://spack.readthedocs.io/en/latest/tutorial_environments.html#environments-spack-yaml-and-spack-lock) to generate a module loading script without having to do module customization

Feel free to reopen if this doesn't help.

**Comment by floli** [comment]
Oh ok. I thought that spack automatically takes newest available python when building. How can I make spack use python3? And set it as a default?

Sorry, if this is a trivial questions, but I was really trying to google it and find in the documentation, without any success.

Thanks!

**Comment by scheibelp** [comment]
> Oh ok. I thought that spack automatically takes newest available python when building.

That's the default for every package built, but Spack's python package specifically selects an earlier version.

> How can I make spack use python3? And set it as a default?

To be clear there's a difference between *use*, and *build*. To prefer building python3 you can use the syntax you have above, you can edit a configuration file (see: https://spack.readthedocs.io/en/latest/build_settings.html#concretization-preferences)

Note that from Spack's perspective, it's better to use the Python built for Numpy, rather than focus on using Python3. As far as how to update your PATH/PYTHONPATH to use numpy and python, https://github.com/spack/spack/issues/10498#issuecomment-459832912 explained a few ways to do it.

> Somewhere, I found:
> `% spack install py-numpy ^python3.7.0`
> `==> Error: Package png not found.`

This appears to be a separate issue: could you file a new issue and include more details (those requested at https://github.com/spack/spack/issues/new?labels=bug&template=bug_report.md)?

**Comment by floli** [comment]
> Note that from Spack's perspective, it's better to use the Python built for Numpy, rather than focus on using Python3. As far as how to update your PATH/PYTHONPATH to use numpy and python, #10498 (comment) explained a few ways to do it.

Sorry, I don't really get what you mean by "it's better to use the Python built for Numpy, rather than focus on using Python3". 
Are you suggesting I should use python 2.7 spack built for me instead of requiring python 3. Sorry, won't work, my scripts rely on python 3 features. Or did I misunderstood you?

>  This appears to be a separate issue: could you file a new issue and include more details (those requested at https://github.com/spack/spack/issues/new?labels=bug&template=bug_report.md)?
Done: https://github.com/spack/spack/issues/10544

**Comment by scheibelp** [comment]
> Are you suggesting I should use python 2.7 spack built for me instead of requiring python 3. Sorry, won't work

Not quite: I am suggesting that you need to make Spack build Numpy *with Python3*. It likely won't work if you use Spack to build Numpy with Python2 and then try to use the Spack-built Numpy with the system Python3. When you tell Spack to build something like

`spack install py-numpy`

Spack will determine all of the dependencies itself, with no regard for what is installed on the system (although you can change that by adding config to `packages.yaml`). You can see this if you do `spack spec`. Spack tries to ensure that each Spack-built package uses only Spack-built dependencies, and specifically the ones that it decided on at the time of install (the dependencies can change between invocations of `spack install`).

**Comment by floli** [comment]
Ok, now that #10544 has been sorted out and it turned out to be an error on may site, due to shell expansion of `^`, get back here.

I am perfectly fine with Spack building as much as the software stack itself as it wants. I still find the decision of the py-numpy package to use an older version of python very surprising.

Building with `spack spec py-numpy "^python@3.7.2"` now works. Note the `"` for my zsh ;-)

But:

Though it said it built pyython 3.7.2:
```
==> Installing python
==> Searching for binary cache of python
==> Warning: No Spack mirrors are currently configured
==> No binary for python found: installing from source
==> Fetching http://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
######################################################################## 100.0%
==> Staging archive: /home/lindnefn/spack/var/spack/stage/python-3.7.2-kl3hknd6fxuz6v7c47echpyf2xt5kl3b/Python-3.7.2.tgz
==> Created stage in /home/lindnefn/spack/var/spack/stage/python-3.7.2-kl3hknd6fxuz6v7c47echpyf2xt5kl3b
==> Applied patch /home/lindnefn/spack/var/spack/repos/builtin/packages/python/ncurses.patch
==> Ran patch() for python
==> Building python [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
[...] deleted some warnings about shebang patching
==> Successfully installed python
  Fetch: 0.98s.  Build: 4m 17.63s.  Total: 4m 18.62s.
[+] /home/lindnefn/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-8.1.0/python-3.7.2-kl3hknd6fxuz6v7c47echpyf2xt5kl3b
```

```
% ./spack/bin/spack-python 
Spack version 0.12.1
Python 2.7.12, Linux x86_64
```
Ok, I just found the python 3 in `~/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-8.1.0/python-3.7.2-kl3hknd6fxuz6v7c47echpyf2xt5kl3b/bin`.

And managed to get into the path using `module load python-3.7.2-gcc-8.1.0-kl3hknd`.

So, it seems I am settled so far.

Thanks for your help!
