### ISSUE TITLE
Question:   Automated way to find spack module file for a package?

### ISSUE THREAD

**Issue by jgalarowicz** [spack/spack#10541]
Hi all,

Our group is working on continuous integration (CI) and wondering if there is a "spack" method for finding the module file for a package.   The scenario would be that one phase of the CI would build the package or packages with spack, the test phase would need to load the spack module(s) and run tests.  Is there an automated way to find the module file for the package built in the previous build phase?  We could list all the module files and search for the package and use shell commands to parse out the module file names, but that doesn't seem very elegant, but maybe necessary.   Is there a suggested or better way?  I thought I would ask before trying to implement something.

Thanks,
Jim G.

**Comment by jgalarowicz** [comment]
Is the answer spack environments?

**Comment by jrood-nrel** [comment]
You can use something like this:
```
$ spack module tcl find curl %gcc
gcc-7.3.0/curl/7.60.0
```
However, if you are testing using Spack, I would recommend using `spack load` to load the module you need. Also, Spack uses rpath, so you typically only need to load modules in which you need the package's `bin` directory in your path. I am actually giving a talk on testing using Spack at a conference soon. If you want to look at the Spack commands I use for testing, I have a script here that might answer some of your questions. It's probably a little more than you asked for though: https://github.com/Exawind/build-test/blob/master/test-scripts/test-nalu-wind.sh

**Comment by jgalarowicz** [comment]
@jrood-nrel  Thanks!  I will take a look!   Appreciate your info!

**Comment by healther** [comment]
You will need to be a bit careful with `spack load` as it does a load of "everything that matches" rather than "at most one that matches". But in general `spack load` should do what you are looking for

**Comment by jgalarowicz** [comment]
Closing issue.   I now have a way to do what I was asking about.  Thanks!
