### ISSUE TITLE
Install packages on an offline system

### ISSUE THREAD

**Issue by floli** [spack/spack#10571]
Hello,
I try to use Spack on the SuperMUC HPC system. Unfortunately, the systems blocks outgoing internet connection. How can I use spack in such an environment?

My idea would be create a list of packages to be downloaded, do the download on another machine and then compile the packages. However, I found nothing about that on the documentation or on the internet.

Thanks!

**Comment by davydden** [comment]
Have you seen [Mirrors](https://spack.readthedocs.io/en/latest/mirrors.html)?

**Comment by floli** [comment]
Ok, downloading all packages is somewhat too much. Is there a possibility get all required packages required for e.g. cmake and put these in a file, so that I can use them with `spack mirror create --file specs.txt`?

**Comment by davydden** [comment]
> downloading all packages is somewhat too much

you should not need to, as far as I can see [spack mirror create](https://spack.readthedocs.io/en/latest/mirrors.html#spack-mirror-create) will only download what is require for provided list of packages.

**Comment by davydden** [comment]
there are also [mirror files](https://spack.readthedocs.io/en/latest/mirrors.html#mirror-files) if you have a large list of packages you need.

**Comment by floli** [comment]
This only downloads the packages I explicitly listed in the `specs.txt`:

```
% echo cmake > specs.txt
% spack mirror create --file specs.txt
==> Adding package cmake@3.13.4 to mirror
[...]
  Archive stats:
    0    already present
    1    added
    0    failed to fetch.
```
My question is, how can I create a list of needed packages (dependencies) to build a package on a system?

Basically, what `spec spec cmake` prints in a format that `mirror create` can understand.

Thanks!
