### ISSUE TITLE
Installation issue: cmake

### ISSUE THREAD

**Issue by floli** [spack/spack#10574]
### Steps to reproduce the issue

```console
> spack -d install -j 1 cmake
 error found in build log:
     953    [ 99%] Built target pseudo_cpplint
     954    [ 99%] Built target pseudo_tidy
     955    [100%] Built target pseudo_cppcheck
     956    [100%] Built target foo
     957    Install the project...
     958    bin/cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by bin/cmake)
  >> 959    make: *** [install] Error 1

See build log for details:
  /gpfs/work/pn56se/di29veb4/software/spack/var/spack/stage/cmake-3.13.4-d7wsnjfuyw62okivfnlvsotdpzo366m5/cmake-3.13.4/spack-build.out
Traceback (most recent call last):
  File "/gpfs/work/pn56se/di29veb4/software/spack/lib/spack/spack/build_environment.py", line 731, in child_process
    return_value = function()
  File "/gpfs/work/pn56se/di29veb4/software/spack/lib/spack/spack/package.py", line 1491, in build_process
    phase(self.spec, self.prefix)
  File "/gpfs/work/pn56se/di29veb4/software/spack/lib/spack/spack/package.py", line 101, in phase_wrapper
    phase(spec, prefix)
  File "/gpfs/work/pn56se/di29veb4/software/spack/var/spack/repos/builtin/packages/cmake/package.py", line 145, in install
  File "/gpfs/work/pn56se/di29veb4/software/spack/lib/spack/spack/build_environment.py", line 127, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/gpfs/work/pn56se/di29veb4/software/spack/lib/spack/spack/util/executable.py", line 188, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' 'install'

```

### Platform and user environment
```commandline
> uname -a
Linux login23 3.0.101-108.77-default #1 SMP Mon Oct 1 13:13:39 UTC 2018 (4733e02) x86_64 x86_64 x86_64 GNU/Linux

> lsb_release -d
Description:    SUSE Linux Enterprise Server 11 (x86_64)
``` 
- `packages.yaml`: not modified
- `compilers.yaml`: not modifiert

to the issue

### Additional information

Rebuilding the package with the following options:
```console
$ spack -d install -j 1 cmake
```
[spack-cc-cmake-d7wsnjf.in.log](https://github.com/spack/spack/files/2856649/spack-cc-cmake-d7wsnjf.in.log)
[spack-cc-cmake-d7wsnjf.out.log](https://github.com/spack/spack/files/2856650/spack-cc-cmake-d7wsnjf.out.log)

**Comment by mwkrentel** [comment]
I think I've seen this error before.  From your debug output, your C++
compiler is:

```
/lrz/mnt/sys.x86_64/compilers/gcc/6.3/bin/g++
```

That's from a module, right?  But the error message mentions
`/libstdc++.so.6` from /usr/lib64.

```
958  bin/cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found
```

This says that spack isn't using the right C++ lib directory for the
compiler in /lrz/mnt/sys.x86_64.

Check the gcc@6.3 entry in your compilers.yaml file.  The `modules:`
field needs to include the module(s) for this compiler.  For example,
on a Cray machine (theta) with a module for gcc/7.3.0, I have:

```
- compiler:
    modules:
    - PrgEnv-gnu
    - gcc/7.3.0
    spec: gcc@7.3.0
    ...
```

After you fill in the `modules:` field, then it should work.  It would
also work if you loaded the module and ran `spack install --dirty`
(which doesn't erase your environment).  But the compilers.yaml
solution is better.

This is an easy mistake to make, so I added a note in the docs for
`spack compiler find`.

https://spack.readthedocs.io/en/latest/getting_started.html#spack-compiler-find

Btw, it would be nice if spack added the modules: field automatically,
but it doesn't.  I don't know how hard that might be.

I asked about that in #9376, but it didn't get any traction.

**Comment by mwkrentel** [comment]
@floli So, was my theory correct?
If you fill in the `modules:` field does it work?

Is there anything else to do here, or can this be closed?

**Comment by floli** [comment]
Not sure what I am doing. I tried to create a `compilers.yaml`, but spack doesn't like it:
```
> cat ~/.spack/compilers.yaml 
compilers:
  - compiler:
      modules:
        - gcc/6
```
What is same name I also load with `module load gcc/6`.
```
> spack compiler list
==> Warning: /home/hpc/xxx/yyy/.spack/compilers.yaml in out of date compilers format. Moved to /home/hpc/xxx/yyy/.spack/_old_compilers.yaml. Spack automatically generate a compilers config file 
==> Available compilers
-- gcc sles11-x86_64 --------------------------------------------
gcc@6.3.0  gcc@4.3.4  gcc@4.3

-- intel sles11-x86_64 ------------------------------------------
```
When using the format from https://spack.readthedocs.io/en/latest/getting_started.html#compilers-requiring-modules 
```
compilers:
  - compiler:
      modules: [gcc/6]
      spec: gcc@6.3.0
```
I get the same message.

`spack compiler info gcc@6.3.0` returns `modules = []`.

Thanks!

**Comment by floli** [comment]
Not sure what I am doing. I tried to create a `compilers.yaml`, but spack doesn't like it:
```
> cat ~/.spack/compilers.yaml 
compilers:
  - compiler:
      modules:
        - gcc/6
```
What is same name I also load with `module load gcc/6`.
```
> spack compiler list
==> Warning: /home/hpc/xxx/yyy/.spack/compilers.yaml in out of date compilers format. Moved to /home/hpc/xxx/yyy/.spack/_old_compilers.yaml. Spack automatically generate a compilers config file 
==> Available compilers
-- gcc sles11-x86_64 --------------------------------------------
gcc@6.3.0  gcc@4.3.4  gcc@4.3

-- intel sles11-x86_64 ------------------------------------------
```
When using the format from https://spack.readthedocs.io/en/latest/getting_started.html#compilers-requiring-modules 
```
compilers:
  - compiler:
      modules: [gcc/6]
      spec: gcc@6.3.0
```
I get the same message.

`spack compiler info gcc@6.3.0` returns `modules = []`.

Thanks!

**Comment by mwkrentel** [comment]
Is that your entire `compilers.yaml` file?  No paths?

Don't try to write `compilers.yaml` from scratch.  Let spack create it.
You only need to edit small pieces.

I suggest: remove (or rename) `compilers.yaml`, load the `gcc/6`
module, and run `spack compiler find`.

If the module is loaded and gcc is on your path, then spack should
find it (and fill in paths).  Then, edit just the `modules:` field for
that compiler.  If the compiler requires more than one module (like
`PrgEnv`), then use commas inside `[]` or else multiple lines with `-`.
For example:

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - GCC/6.4.0
    operating_system: rhel7
    paths:
      cc: /opt/apps/software/Core/GCCcore/6.4.0/bin/gcc
      cxx: /opt/apps/software/Core/GCCcore/6.4.0/bin/g++
      f77: /opt/apps/software/Core/GCCcore/6.4.0/bin/gfortran
      fc: /opt/apps/software/Core/GCCcore/6.4.0/bin/gfortran
    spec: gcc@6.4.0
    target: ppc64le
```

You can check your work with `spack compiler info gcc`.  If you have
it right, it should report the same module name as `module avail` or
`module list`.

If that doesn't work, then I'm probably out of ideas.

**Comment by floli** [comment]
Thanks! I was just unsure about which `compilers.yaml` to modify. I think I got it right now... but:
```
> spack install cmake
==> Installing diffutils
==> Searching for binary cache of diffutils
==> Finding buildcaches in /home/hpc/pn56se/di29veb4/work/spack-mirror-2019-02-27//build_cache
==> No binary for diffutils found: installing from source
==> Warning: Could not detect module function from bash. Trying to detect modulecmd from `which`
==> Error: ModuleError: Spack requires modulecmd or a defined module function. Make sure modulecmd is in your path or the function "module" is defined in your bash environment.

/gpfs/work/pn56se/di29veb4/software/spack/lib/spack/spack/build_environment.py:787, in child_process:
        784            tb_string = traceback.format_exc()
        785
        786            # build up some context from the offending package so we can
  >>    787            # show that, too.
        788            package_context = get_package_context(tb)
        789
        790            build_log = None
```

`set` shows me that a `module` shell function is defined:

```
module () 
{ 
    moduleraw $* 2>&1
}
moduleraw () 
{ 
    eval `/usr/bin/tclsh $MODULE_BIN/modulecmd.tcl bash $*`
}
```
Just `module` from the command line also works.

Any more ideas?

Thanks!

**Comment by mwkrentel** [comment]
At least it's a different error.  :-)

I'm still reasonably confident that the `modules:` field is the
correct solution to your original problem.  I've seen this error
before and that's the right solution.

It looks like spack doesn't understand your system's version of
modules.  Unfortunately, this is not something that I know much about.

I can only offer one thing to try.  Spack has a package for
`environment-modules`.  You could install that and then run the spack
version of modules.

```
cd /path/to/environment-modules-xxxxxxx/Modules/init
. ./bash
```

That's overkill and shouldn't be necessary, but at least spack should
understand its own version of modules.

But as for why spack doesn't understand the module system on your
machine, I don't know.  All I can suggest is to read spack readthedocs
and try asking on the spack slack channel.

**Comment by floli** [comment]
I have created a new issue, as the original question was answered. Thanks again for your help!
