### ISSUE TITLE
Installation issue: petsc with python3

### ISSUE THREAD

**Issue by burgreen** [spack/spack#10581]
### Steps to reproduce the issue

I manually modified the petsc/package.py to depend on python >= 3.4.

```console
$ spack install petsc
... # ImportError: No module named site.
```
The problem is the last official release of PETsc does not support Python3.

However, a Python3 compatible version of PETsc will be released soon.

In the meantime, the current master branch of PETsc is Python3 compatible.

So, right or wrong, good practice or not, I downloaded a ZIP archive of the current PETsc git repo and used that as a repeatible, checksummable archive. 

This unofficial petsc archive installed fine with Python-3.7.2.

**Comment by citibeth** [comment]
Same as #10256
