### ISSUE TITLE
spec._libs_default_handler(descriptor, spec, cls)  duplicates default libs() in Package?

### ISSUE THREAD

**Issue by davydden** [spack/spack#10612]
There is a `_libs_default_handler` in spec.py which is 

> Default handler when looking for the 'libs' attribute.

but is not this exactly what we do by-default in `Package::libs()`? IMO the two should be combined to avoid code duplication.

**Comment by alalazo** [comment]
I can't find `Package.libs` anywhere (which is what I expect). The `libs` attribute in `Spec`:

https://github.com/spack/spack/blob/75487dca4437eb80ae0d9b81a2972cea6584af06/lib/spack/spack/spec.py#L865-L868

should be an instance of the `ForwardQueryToPackage` descriptor

https://github.com/spack/spack/blob/75487dca4437eb80ae0d9b81a2972cea6584af06/lib/spack/spack/spec.py#L743-L744

Am I missing something?

**Comment by davydden** [comment]
ah, I confused myself. I thought this is specified somewhere in the base class. sorry for the noice @alalazo

**Comment by alalazo** [comment]
No worries.
