### ISSUE TITLE
GCC package assumes availability of `-static-libstdc++`

### ISSUE THREAD

**Issue by trws** [spack/spack#1062]
Ancient versions of gcc, those before 4.5.0, do not have support for the `-static-libstdc++` flag, and are apparently still in common use for some reason.  It would be useful to clean this up in the gcc package if we can find a good way to locate the correct static libstdc++ and link it directly.

**Comment by adamjstewart** [comment]
> Ancient versions of gcc, those before 4.5.0, do not have support for the `-static-libstdc++` flag

We could edit the package to only use that flag for versions >= 4.5.0.

>  It would be useful to clean this up in the gcc package if we can find a good way to locate the correct static libstdc++ and link it directly.

What do you mean by this?

**Comment by trws** [comment]
I mean that the bootstrap portion is using the static libstdc++ to resolve which libstdc++ is picked up, which is pretty important.  If we can't use the flag, then we have to locate the correct libstdc++ to use and specify it manually, which is rather less straightforward.

**Comment by alalazo** [comment]
@trws I am going to close this one as inactive. Feel free to reopen if still relevant.
