### ISSUE TITLE
py-scipy: Ran out of Threads

### ISSUE THREAD

**Issue by citibeth** [spack/spack#10627]
I'm building `py-scipy` (gcc-5.3.0 environment) on a shared supercomputer login node.  To speed things up, SciPy builds in parallel using `make_jobs` jobs (not sure where the `make_jobs` symbol comes from):
```
        # Build in parallel
        # Known problems with Python 3.5+
        # https://github.com/spack/spack/issues/7927
        # https://github.com/scipy/scipy/issues/7112
        if not spec.satisfies('^python@3.5:'):
            args.extend(['-j', str(make_jobs)])
```

This is failing for me because I'm running of threads.  Most likely, the supercomputer admin set a limit on number of threads that's less than the number of processors, to prevent people from hogging the machine.  I couldn't find any thread limit in `ulimit -a`, but I'm willing to be its somewhere on this system.

### Steps to reproduce the issue

```console
$ spack install py-scipy ^python@3.5.2
```

### Error Message

```
RuntimeError: can't start new thread
```

### Information on your system

SuSE11.  Shared supercomputer, probably has resource limits set by the administrator.

### Proposed Solution (please comment)

We don't want to add a variant to change the degree of parallelism of the build, because that has nothing to do with the final result.  Can we find a way for the user to set `make_jobs` when launching Spack?  Or does such a way already exist?

[py-scipy.txt](https://github.com/spack/spack/files/2871255/py-scipy.txt)

**Comment by scheibelp** [comment]
> SciPy builds in parallel using make_jobs jobs (not sure where the make_jobs symbol comes from)

That is automatically defined when you pass `-j` to `spack install`, like `spack install -j 2 py-scipy`

The `-j` arg is documented at https://spack.readthedocs.io/en/latest/command_index.html#spack-install although the exposure of this setting via the `make_jobs` module variable is not.

**Comment by mwkrentel** [comment]
You can also set this in config.yaml with the name `build_jobs`.

I've never really liked that the default make jobs is all available
hardware threads.  For a single machine with 4 or 8 cores and one
user, this makes sense.

But for a shared front end with several dozen cores and 50 users, this
is not the right choice, IMO.  For example, on a power8 machine at
Rice with 48 cores and 4x HT, spack happily ran `make -j 192`.  The
admins had to reboot the box to clean up the mess.

Perhaps a sliding scale with a cap would make sense.  Up to 8, use all
cores, then start to back off with a cap of 16 or 20.  That's just the
default, you can always write `-j 64` if that's appropriate for your
machine.

IMO, it's just too easy to make a mistake like this.

**Comment by healther** [comment]
> IMO, it's just too easy to make a mistake like this.

I'd argue it's a badly configured cluster if a normal user can screw it up, but unfortunately these are far more often than well administered ones. So I'm very much in favour of some "sensible" scaling or if people are against it prompting the user in a "are you REALLY sure this is a good idea" sense

**Comment by ptooley** [comment]
It is not a badly configured HPC if the machine policy is to build on worker nodes.  I regularly use a couple of HPCs where the login nodes are for job submission and data transfer only.  In this case there are a dedicated pool of nodes for interactive use intended for building, data analysis etc.

If there is a screwup here it is on the part of spack for making poor assumptions.  The most sensible default IMO is to use a single core, and point the user to documentation explaining *both* the --jobs option and the need to check the machine policies for where they should build and what is considered fair use.

**Comment by mwkrentel** [comment]
@citibeth Is there anything more to do here, or should this be closed?

Spack has the tools to set the number of jobs, and it is up to the
user to use an appropriate value.  So, this is not really a bug.

**Comment by citibeth** [comment]
It can be closed.  Setting `-j 1` is not the solution, because that would slow down lots and lots of things.  The real problem here turned out to be that SciPy and Numpy don't work with parallel build on Python 3.5+ (see #8003).  Apparently I'd already figured that out and fixed it.  But apparently the issue bit me again this time around, even though I'm using Python 3.5+ and it should have not even tried to build parallel.  I forget the resolution, but the solution ultimately didn't involve changing SciPy or Numpy, or using `-j`.
