### ISSUE TITLE
==> Warning: A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'

### ISSUE THREAD

**Issue by roblatham00** [spack/spack#10626]
*Explain, in a clear and concise way, the command you ran and the result you were trying to achieve.
Example: "I ran Spack find to list all the installed packages and..."*

When I install packages with Spack (e.g. libfabric) I get the  message in the subject:

==> Warning: A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.

It sure seems like pkg-config is ignoring a dependency, because libfabirc fails to build  with the classic "i silently failed to find an important header" error message:

```
prov/psm2/src/version.h:69:35: error: dereferencing pointer to incomplete type 'struct psm2_mq_req_user'
```

Is the CPATH warning spurious or something I should investigate further?  I was surprised to learn pkg-config is deprecated but lots of stuff I use still uses it!

**Comment by michaelkuhn** [comment]
#10644 should fix this warning and the related pkgconf/pkg-config problems. Please give it a try.

BTW: Only pkg-config is deprecated, pkgconf is not. Both provide a pkg-config binary and should be 100% compatible. The naming is sadly a bit confusing.

**Comment by alalazo** [comment]
Closing as this seems a question (and was answered)
