### ISSUE TITLE
Installation issue : PGI 18.10

### ISSUE THREAD

**Issue by schoonovernumerics** [spack/spack#10641]
When attempting to install PGI 18.10, installation fails due to "incorrect" sha256sum. 
```
==> Installing pgi
==> Searching for binary cache of pgi
==> Finding buildcaches in /apps/spack-mirror/build_cache
==> No binary for pgi found: installing from source
==> Warning: A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> Fetching file:///apps/spack-mirror/pgi/pgi-18.10.tar.gz
######################################################################## 100.0%
==> Error: ChecksumError: sha256 checksum failed for /apps/spack/var/spack/stage/pgi-18.10-oypleqype33fcx6lqlgix43vgpbnfolu/pgilinux-2018-1810-x86_64.tar.gz
    Expected 4cc24b1c7c7a1e4b3a72f3dc3318367fe75502f93585997f2cdd0c8cc7616fd7 but got 4b3ff83d2a13de6001bed599246eff8e63ef711b8952d4a9ee12efd666b3e326
```

Note that the MD5sum reported on PGI's community edition download site ( https://www.pgroup.com/support/download_community.php?file=pgi-community-linux-x64 ) is 
```
0e1598c05aa8faeb84e351c0f68274c3
```
![screenshot from 2019-02-18 18-07-11](https://user-images.githubusercontent.com/11430768/52983368-16b51800-33a8-11e9-846f-db350e03c17c.png)

The md5sum of my download is
```console
$ md5sum /apps/spack-mirror/pgi/pgi-18.10.tar.gz 
0e1598c05aa8faeb84e351c0f68274c3  /apps/spack-mirror/pgi/pgi-18.10.tar.gz
```
I suspect the sha256sum in spack's PGI package file for 18.10 is incorrect.

---

### Steps to reproduce the issue

1.  Download PGI Community Edition from https://www.pgroup.com/support/download_community.php?file=pgi-community-linux-x64
2. Setup [install-directory]/spack/etc/spack/mirrors.yaml, e.g. add
```
mirrors:
  local_filesystem: file:///apps/spack-mirror
```
3. Put pgi compilers tarball under `/apps/spack-mirror/pgi/pgi-18.10.tar.gz
4. Attempt to install pgi-18.10
```console
$ spack install pgi@18.10
```
### Platform and user environment

Please report your OS here:
```commandline
$ uname -a
Linux fluid-cloud-login1 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:    CentOS Linux release 7.6.1810 (Core) 
```

**Comment by Rombur** [comment]
I think that this [PR](https://github.com/spack/spack/pull/10588) should fix your problem

**Comment by weijianwen** [comment]
@schoonovernumerics does this issue persist when updating Spack to the latest version?

**Comment by weijianwen** [comment]
I cannot reproduce this issue on latest Spack. I close this issue since it has been inactive for long. Feel free to reopen it if necessary.
