### ISSUE TITLE
tcl module refresh fails for package proj (installed as dep of gdal)

### ISSUE THREAD

**Issue by JaroslavHron** [spack/spack#10649]
### Steps to reproduce the issue
* fresh spack clone
* install package gdal with its dependece proj
```console
$ spack install gdal
```
* install seems ok

### Error Message

* on module refresh, spack just reports a warning but the module file for `proj` package is not created
* the warning message is strange since it complains about missing stage dir...

```console
$ spack module tcl refresh proj
==> You are about to regenerate tcl module files for:

-- linux-ubuntu16.04-x86_64 / gcc@5.4.0 -------------------------
tym5zkx proj@5.0.1

==> Do you want to proceed? [y/n] y
==> Regenerating tcl module files
==> Warning: Could not write module file [/usr/local/pkg/temp/spack/share/spack/modules/linux-ubuntu16.04-x86_64/proj-5.0.1-gcc-5.4.0-tym5zkx]
==> Warning: 	--> [Errno 2] No such file or directory: '/usr/local/pkg/temp/spack/var/spack/stage/proj-5.0.1-tym5zkxbywyt2pcq33232zgpokq6gwrj' <--
```

### Information on your system

* which platform you are using: linux-ubuntu16.04-x86_64

**Comment by michaelkuhn** [comment]
#11084 should fix this problem. Could you please give it a try?
