### ISSUE TITLE
Remove lock info from `spack --debug` by default?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#10656]
`spack --debug` is invaluable for getting stack traces when things go wrong.  However, it also produces a lot of extra debugging printout that might not even be relevant anymore.  Stuff like:

```
==> READ LOCK: /gpfsm/dnb53/rpfische/spack7/opt/spack/.spack-db/prefix_lock[4996285069150612422:1] [Released]
==> WRITE LOCK: /gpfsm/dnb53/rpfische/spack7/opt/spack/.spack-db/prefix_lock[3796603063533368696:1] [Acquiring]
==> WRITE LOCK: /gpfsm/dnb53/rpfische/spack7/opt/spack/.spack-db/prefix_lock[3796603063533368696:1] [Acquired]
==> WRITE LOCK: /gpfsm/dnb53/rpfische/spack7/opt/spack/.spack-db/prefix_lock[3796603063533368696:1] [Released]
```
Would it be possible to either:
 1. Clean up the output produced by `spack --debug`
 2. Add a different command-line flag or configuration that causes Spack to produce stacktraces without accompanying debug output?

**Comment by tgamblin** [comment]
Fixed by #17546.
