### ISSUE TITLE
Policy on MD5-SHA256 Checksum Conversions

### ISSUE THREAD

**Issue by citibeth** [spack/spack#10664]
@adamjstewart @tgamblin @scheibelp 

I've noticed an increasing number of PRs that convert MD5 to SHA256 hashes.  I understand the reason behind this, and that we need to move in that direction.  However, I am concerned that the *way* we are doing this opens us up to security problems.

The purpose of the hash is to ensure that the versions of a package a *user* downloads is the same as the version seen by the package *author*.  As long as nobody has noticed a problem with that version for a while, it's probably good.

Suppose someone gains illicit access to an upstream package's Git repo.  They could then create a modified version of that package; however, Spack's checksums would find that and reject it.  This works because checksums don't change, and we don't change the checksums in Spack packages.  Any PR that involves a checksum change is potentially suspicious, and deserves extra scrutiny.

That's how things were.  But now we live in a universe where any MD5 checksum can be changed to SHA256 with zero scrutiny.  It's a HUGE opportunity to insert malicious code into Spack.

To address this issue, I believe we should do as follows:

1. Don't accept PRs that change existing checksums.

2. Hack up a script that goes over all packages, downloads all tarballs, re-does checksums, and then edits in the new checksum.  (@adamjstewart ???).  I think such a script would be successful, and probably even fun to do.  Then a TRUSTED person runs the script, checks things over, submits the PR and gets it merged.

**Comment by healther** [comment]
I was meaning to write up that script, but didn't find the time to do it until now. The part regarding downloading and checking the hashes should probably be run from Travis for all new version PRs anyways

**Comment by citibeth** [comment]
I like that idea, in theory.  Unfortunately I'm not in a position to make
it happen.

**Comment by tgamblin** [comment]
@scheibelp is working on adding a feature to mirror *all* of Spack quickly, so that we can deploy the long-wanted source mirror.  Once we have that, a mass sha256 conversion should be pretty easy.  Assigning this to him.

**Comment by alalazo** [comment]
Closing, since this was addressed in 64bdc325 and earlier commits.
