### ISSUE TITLE
[Beginner][Absolute Beginner] How do i use a C++-Library that was added through Spack?

### ISSUE THREAD

**Issue by ClmnsRck** [spack/spack#10669]
As some of the Users here call them selfs beginners and talk about things i never heard of, please keep in mind, that i probably wouldnt even qualify as an beginner. 

I installed Blitz++ with Spack and no errors were thrown. Now i would like to use this package. The thing is, `g++` doesnt pick up blitz on my System. Do i have to link it somehow? Do i have to address the library in my compiler-call? `#include <blitz/array.h>` is not recognized.

**Comment by ClmnsRck** [comment]
While i am at it: How do i keep the command `spack` from disappearing in the Terminal? I followed the tutorial, but some steps i did'nt really understand(i still executed every command)

**Comment by scheibelp** [comment]
Hi @ClmnsRck I think the tutorial needs a section specifically on using Spack packages. https://github.com/spack/spack/issues/3295 has some tips on environments (and also brings up this issue), and you can also use the `spack view` command to create a directory of merged Spack packages (analogous to `/usr/`, with a `bin/` directory etc.)

Not sure what you mean by https://github.com/spack/spack/issues/10669#issuecomment-466014407 - if you have a series of commands that reproduces this, could you add them here?
