### ISSUE TITLE
Installation issue: <netgen>

### ISSUE THREAD

**Issue by behroozkarami** [spack/spack#10698]
Installation issue: <netgen>

The install breaks down when trying to fetch netgen:
Installing netgen

==> No binary for netgen found: installing from source
==> Fetching http://gigenet.dl.sourceforge.net/project/netgen-mesher/netgen-mesher/5.3/netgen-5.3.1.tar.gz

curl: (7) Failed to connect to gigenet.dl.sourceforge.net port 80: Connection refused
==> Fetching from http://gigenet.dl.sourceforge.net/project/netgen-mesher/netgen-mesher/5.3/netgen-5.3.1.tar.gz failed.
==> Error: FetchError: All fetchers failed for netgen-5.3.1-fxostpbpelllydkeut3m3uvvmzwjdae6

/home/..../spack/package.py:961, in do_fetch:
        958                raise FetchError("Will not fetch %s" %
        959                                 self.spec.format('$_$@'), ck_msg)
        960
  >>    961        self.stage.create()
        962        self.stage.fetch(mirror_only)
        963        self._fetch_time = time.time() - start_time
        964

I know the correct URL, I mean I am able to download it from  sourceforge.net manually.
I don't know how to tell Spack (if that's a solution!) where to find the package.
What can I do about it?
Thanks

**Comment by oehlrich9** [comment]
I can confirm this error. Is there any workaround?

**Comment by behroozkarami** [comment]
Yes it is solved.
command: spack edit netgent
provides access to the file where the URL could be modified.
We entered a new URL to fetching netgen and it worked.
