### ISSUE TITLE
Download cacert.pem with curl

### ISSUE THREAD

**Issue by eschnett** [spack/spack#1069]
The `curl` web site offers a file `cacert.pem` for download. Spack should download and install it with `curl`. This prevents problems where HPC systems are outdated and don't keep their certificate lists updated.

**Comment by adamjstewart** [comment]
@mlawsonca I wonder if this would solve your problem.

**Comment by becker33** [comment]
Closing this issue -- the curl spec `curl tls=openssl ^openssl certs=mozilla` downloads the ca certs (and is the default for curl on linux).
