### ISSUE TITLE
Error SPACK_DEPENDENCIES when running spack setup

### ISSUE THREAD

**Issue by cedricchevalier19** [spack/spack#10714]
I am following the developer workflow to install my product dependencies and before generating spconfig.py, I got this error : ==> Error: 'SPACK_DEPENDENCIES'

### Steps to reproduce the issue

```console
$ spack setup parmetis
...
```

### Origin

It seems this bug is related to 8ca384875efffbcee1881db9fdef4399e74add50.

**Comment by haampie** [comment]
I'm getting the same problem after 20 minutes of compiling :(

**Comment by cedricchevalier19** [comment]
Fixed by #10715
