### ISSUE TITLE
./spack install libelf

### ISSUE THREAD

**Issue by arunsoman1234** [spack/spack#10757]
I am getting following error while installing the application
spack/bin$ ./spack install libelf
==> Installing libelf
==> Searching for binary cache of libelf
==> Warning: No Spack mirrors are currently configured
==> No binary for libelf found: installing from source
==> Fetching http://www.mr511.de/software/libelf-0.8.13.tar.gz
######################################################################### 100.0%
curl: (6) Could not resolve host: leere.seite
==> Fetching from http://www.mr511.de/software/libelf-0.8.13.tar.gz failed.
==> Error: FetchError: All fetchers failed for libelf-0.8.13-rblqbdguqwodihmkricvfsli2yzolkot

/home/arun/Documents/spack/lib/spack/spack/package.py:961, in do_fetch:
        958                raise FetchError("Will not fetch %s" %
        959                                 self.spec.format('$_$@'), ck_msg)
        960
  >>    961        self.stage.create()
        962        self.stage.fetch(mirror_only)
        963        self._fetch_time = time.time() - start_time
        964

---

### Steps to reproduce the issue

```console
$ spack install <spec> # Fill in the exact spec you are using
... # and the relevant part of the error message
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux nuvolari 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 18.04.1 LTS
``` 
and, if relevant, post or attach:

- `packages.yaml`
- `compilers.yaml`

to the issue

### Additional information

Sometimes the issue benefits from additional details. In these cases there are
a few things we can suggest doing. First of all, you can post the full output of:
```console
$ spack spec --install-status <spec>
...
```
to show people whether Spack installed a faulty software or if it was not able to
build it at all. 

If your build didn't make it past the configure stage, Spack as also commands to parse 
logs and report error and warning messages:
```console
$ spack log-parse --show=errors,warnings <file-to-parse>
```
You might want to run this command on the `config.log` or any other similar file
found in the stage directory: 
```console
$ spack location -s <spec>
```
In case in `config.log` there are other settings that you think might be the cause 
of the build failure, you can consider attaching the file to this issue.

Rebuilding the package with the following options:
```console
$ spack -d install -j 1 <spec>
...
```
will provide additional debug information. After the failure you will find two files in the current directory:

1. `spack-cc-<spec>.in`, which contains details on the command given in input 
    to Spack's compiler wrapper  
1. `spack-cc-<spec>.out`, which contains the command used to compile / link the 
    failed object after Spack's compiler wrapper did its processing 

You can post or attach those files to provide maintainers with more information on what
is causing the failure.

**Comment by ClmnsRck** [comment]
I have the same error and would really like to know, what is wrong and how to fix it.

**Comment by citibeth** [comment]
@ClmnsRck Thelibelf download is broken. Try manually downloading from here to see that:
https://directory.fsf.org/wiki/Libelf

The solution in these cases is usually to find the same tarball from a well-known Linux distro source, and change the package.py file to use it. As long as the checksum is the same, it's all OK.

Maybe try slackware:
http://ftp.slackware.com/pub/gsb/gsb64-2.30_slackware64-13.1/source/l/libelf/

**Comment by mwkrentel** [comment]
@arunsoman1234  @ClmnsRck  @citibeth 
It seems the old libelf project has been abandoned and their web site
doesn't exist anymore.  I submitted PR #10815 to move the url to
fossies.org.  It should be merged within a few days.

fossies archives old, open-source tar files.  For example, the final
bzip2 tar file is also there.

Any active project that uses libelf should migrate to elfutils.  But
I'd like to keep libelf alive for a while longer.  Older versions of
other packages, comparison with elfutils, etc.
