### ISSUE TITLE
Spack only shows non-existing module files

### ISSUE THREAD

**Issue by pat-s** [spack/spack#10783]
I removed all packages and modules installed with `gcc@7.4.0` using `spack uninstall -a %gcc@7.4.0` and removing and regenerating the modules with

```
spack modules tcl rm -y
spack modules tcl refresh -y
```

Using `spack find` I can see the actual installed packages

```sh
==> 171 installed packages
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
autoconf@2.69    gcc@7.3.0    gmp@6.1.2  libsigsegv@2.11  m4@1.4.18  mpfr@3.1.6   perl@5.26.2    readline@7.0
automake@1.16.1  gdbm@1.18.1  isl@0.18   libtool@2.4.6    mpc@1.1.0  ncurses@6.1  pkgconf@1.5.4  zlib@1.2.11

-- linux-centos7-x86_64 / gcc@7.3.0 -----------------------------
at-spi2-atk@2.26.2         gmake@4.2.1                   libvterm@681       pcre@8.42
at-spi2-core@2.28.0        gmp@6.1.2                     libx11@1.6.7       perl@5.26.2
atk@2.30.0                 gobject-introspection@1.56.1  libxau@1.0.8       perl-xml-parser@2.44
autoconf@2.69              gobject-introspection@1.56.1  libxcb@1.13        pixman@0.38.0
automake@1.16.1            gobject-introspection@1.56.1  libxdamage@1.1.4   pkgconf@1.5.4
binutils@2.31.1            gperf@3.0.4                   libxdmcp@1.1.2     presentproto@1.0
bison@3.0.5                gtkplus@3.20.10               libxext@1.3.3      proj@5.0.1

```

However, when I run `module avail` I see only all the outdated gcc@7.4.0 modules (which do not even exist anymore) and the new ones from gcc@7.3.0 do not appear there.

How can I fix this? Do I need to clean a cache or something?

```sh
module avail

---------------------------------- /opt/spack/share/spack/modules/linux-centos7-x86_64 ----------------------------------
   at-spi2-atk-2.26.2-gcc-7.4.0-m2zwuiq              libuv-1.25.0-gcc-7.4.0-uhlsfdh
   at-spi2-atk-2.26.2-gcc-7.4.0-xvgvhyw              libvterm-681-gcc-7.4.0-kcp3kdh
   at-spi2-core-2.28.0-gcc-7.4.0-3rp2xce             libx11-1.6.7-gcc-7.4.0-x2yopo3
   at-spi2-core-2.28.0-gcc-7.4.0-mvdiwuv             libxau-1.0.8-gcc-7.4.0-vfq3u2p
   atk-2.30.0-gcc-7.4.0-3nzam73                      libxcb-1.13-gcc-7.4.0-3lnuly4
   atk-2.30.0-gcc-7.4.0-4ohpljb                     
```

I even tried setting some options in `modules.yaml` but without effect:

```sh
modules:
      tcl:
          blacklist:
              - '%gcc@4.8.5'
              - '%gcc@7.4.0'
          whitelist:
              - 'gcc@7.3.0'
          blacklist_implicits: true
          all:
             filter:
                 environment_blacklist: ['CPATH', 'LIBRARY_PATH']
```

**Comment by alalazo** [comment]
The [--delete-tree](https://spack.readthedocs.io/en/latest/tutorial_modules.html#prevent-some-module-files-from-being-generated) option of refresh should do what you want:
```console
$ spack module tcl refresh --help
usage: spack module tcl refresh [-hy] [--delete-tree] ...

positional arguments:
  constraint        constraint to select a subset of installed packages

optional arguments:
  -h, --help        show this help message and exit
  --delete-tree     delete the module file tree before refresh
  -y, --yes-to-all  assume "yes" is the answer to every confirmation request
```

That said, uninstalling packages should have triggered module file removal so that should be investigated.

**Comment by alalazo** [comment]
Did you blacklisted `%gcc@7.4.0` in `modules.yaml` before uninstalling software built with GCC 7.4.0 ?

**Comment by pat-s** [comment]
> Did you blacklist %gcc@7.4.0 in modules.yaml before uninstalling software built with GCC 7.4.0 ?

I can't tell anymore. Also the issue went away over night. I even might have used `--delete-tree`. I do not know what I did exactly but now the "ghost" modules do not appear anymore...

**Comment by alalazo** [comment]
> Also the issue went away over night.

:scream: Looks like a cache from your module system then?

**Comment by pat-s** [comment]
> scream Looks like a cache from your module system then?

;) yeah probably. Well idk if there is some automatic cache cleaning going on in Spack? The day of the issue I tried various commands to solve it but couldn't..
