### ISSUE TITLE
py-pip: no module names pkg_resources

### ISSUE THREAD

**Issue by pat-s** [spack/spack#10784]
When trying to use `pip` from a user that did not install the package `py-pip` (and only sources the Spack setup file) I get the following error when trying to install a package with `pip` (before `spack load py-pip` was called):

```sh
Traceback (most recent call last):
  File "/opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/py-pip-19.0.3-u76cust5siazb77mkwx7ks7i77qai6f3/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Doing this with the user how installed `py-pip' works. I only see such a clash for `pip` and no other package. Is there any way to solve this?

**Comment by adamjstewart** [comment]
This missing module is provided by the `py-setuptools` package. Whenever you load the `py-pip` package, you also need to load `py-setuptools`.

**Comment by pat-s** [comment]
I cannot load `py-setuptools` even though I have installed it. 

I refreshed the `tcl` modules with `spack module refresh tcl -y` but I keep getting

```
==> Error: Even though py-setuptools@40.8.0%gcc@7.3.0 arch=linux-centos7-x86_64  ^bzip2@1.0.6%gcc@7.3.0+shared arch=linux-centos7-x86_64  ^expat@2.2.5%gcc@7.3.0+libbsd arch=linux-centos7-x86_64  ^gdbm@1.18.1%gcc@7.3.0 arch=linux-centos7-x86_64  ^libbsd@0.9.1%gcc@7.3.0 arch=linux-centos7-x86_64  ^libffi@3.2.1%gcc@7.3.0 arch=linux-centos7-x86_64  ^ncurses@6.1%gcc@7.3.0~symlinks~termlib arch=linux-centos7-x86_64  ^openssl@1.1.1a%gcc@7.3.0+systemcerts arch=linux-centos7-x86_64  ^python@2.7.15%gcc@7.3.0+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter~ucs4~uuid+zlib arch=linux-centos7-x86_64  ^readline@7.0%gcc@7.3.0 arch=linux-centos7-x86_64  ^sqlite@3.26.0%gcc@7.3.0~functions arch=linux-centos7-x86_64  ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos7-x86_64 is installed, no tcl module has been generated for it.
```

The same happens if I try to load it via `spack py-setuptools`. I also tried `spack module tcl loads --dependencies py-pip` without success (the command finished without error).

In the end I used `pip` from system python to upgrade `setuptools` and then continue using `pip` from Spack. Is something wrong in my config or is this behavior spack related?

**Comment by pat-s** [comment]
The loading problem of `pysetuptools` orginiated in the issue that no tcl module could be generated because the package was not marked explicitly. It was rather installed as a dep of `py-pyp`.

To overcome this, do `spack install py-setuptools` and then `spack module tcl refresh  -y`. After that, it is listed under `module avail` and can be loaded via `spack load py-setuptools`. Then `pip` installations will work..
