### ISSUE TITLE
Python package.py changes regarding variant 'tk' conflict with existing Python package installation

### ISSUE THREAD

**Issue by phxyz12** [spack/spack#10793]
I tried to lookup a spec for py-pip using an already installed package of python@3.6.5. Spack terminates with an error "error 'tk'" which seems to originate from changes made to the python package.py file very recently.

### Steps to reproduce the issue

```console
$ spack spec -I py-pip@19.0.3 ^/<hash of python@3.6.5 package installed some weeks ago>.
```

### Error Message

```console
[swadm@build01 spack]$ spack spec -I py-pip@19.0.3 ^/v7dcicw
Input spec
--------------------------------
 -   py-pip@19.0.3
[+]      ^python@3.6.5%gcc@7.3.0+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd+shared~tk~ucs4 arch=linux-centos7-x86_64 
[+]          ^bzip2@1.0.6%gcc@7.3.0+shared arch=linux-centos7-x86_64 
[+]          ^gdbm@1.14.1%gcc@7.3.0 arch=linux-centos7-x86_64 
[+]              ^readline@7.0%gcc@7.3.0 arch=linux-centos7-x86_64 
[+]                  ^ncurses@6.1%gcc@7.3.0~symlinks~termlib arch=linux-centos7-x86_64 
[+]          ^openssl@1.0.2o%gcc@7.3.0+systemcerts arch=linux-centos7-x86_64 
[+]              ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos7-x86_64 
[+]          ^sqlite@3.23.1%gcc@7.3.0~functions arch=linux-centos7-x86_64 

Concretized
--------------------------------
==> Error: 'tk'
```

### Information on your system

CentOS 7.5 on x86_64
Spack repo updated to latest version (git pull on March 6th)

When I compare the older package.py file for Python with the current one, I see that a spec switch for a variant 'tk' has been renamed from 'tk' to 'tkinter'. Now I cannot install any Python-dependent package using the installed Python because the updated Python package.py is "incompatible" with the installed spec.

-----

**Comment by citibeth** [comment]
> I see that a spec switch for a variant 'tk' has been renamed from 'tk' to 'tkinter'.

Where do you see this?  In my snooping around, it looks like the variant is called `tk`, and has been now for 2 years:

https://github.com/spack/spack/blame/4ecb465a366de3f722aeb1525b22c0d22aefceae/var/spack/repos/builtin/packages/python/package.py

> Now I cannot install any Python-dependent package using the installed Python because

I don't think it's practical at this time to ask that changes to packages remain backwards compatible. 
 When I upgrade Spack, I just rebuild everything.  This only takes a few hours, even though I have 100 packages to build.  Spack is good at rebuilding stuff.

**Comment by phxyz12** [comment]
The variant has not been renamed, it is still named 'tk' as you say. It's the parameter you can use to activate/deactivate it, that has changed:

depends_on('tk', when='+tkinter')

This is now e.g. +tkinter and has been +tk. It looks to me like this causes the error.

**Comment by citibeth** [comment]
Thank you.  Yes I agree this is a bug.  See #10833, which should fix it (for now).  Do you know how to use #10833 in your code, even before it is merged into *develop*?

**Comment by citibeth** [comment]
A re-examination of this issue has convinced me that this problem is due to a variant being renamed, but the installed package uses the old variant name.  I would like to close this issue --- because it would take less time to just re-install one's environment with a newly built Python, than it has for me to research this issue and come to the wrong conclusion.  I repeat what I said earlier:


> I don't think it's practical at this time to ask that changes to packages remain backwards compatible.
When I upgrade Spack, I just rebuild everything. This only takes a few hours, even though I have 100 packages to build. Spack is good at rebuilding stuff.
