### ISSUE TITLE
Pkg-config could not be found for flux-core & flux-sched

### ISSUE THREAD

**Issue by paulbry** [spack/spack#10809]
### Steps to reproduce the issue

In an instance without the pkgconfig package installed:

```console
$ spack install flux-sched
...
==> Installing flux-core
...
==> Error: ProcessError: Command exited with status 1:
    '/home/pbryant/spack/var/spack/stage/flux-core-0.11.0-uzzgmt25bbhsskgt4ncxxgqn46dzzdyx/flux-core-0.11.0/configure' '--prefix=/home/pbryant/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/flux-core-0.11.0-uzzgmt25bbhsskgt4ncxxgqn46dzzdyx' '--enable-pylint=no' '--disable-docs'

2 errors found in build log:
     214    checking for Lua header version... 5.2
     215    checking if Lua header version matches 5.2... yes
     216    checking if LUA_VERSION is defined... yes
     217    checking for library containing exp... none required
     218    checking for library containing dlopen... -ldl
     219    checking for library containing lua_load... -llua5.2
  >> 220    checking for ZMQ... configure: error: in `/tmp/pbryant/spack-stage/spack-stage-3YWrU2/
            flux-core-0.11.0/spack-build':
  >> 221    configure: error: The pkg-config script could not be found or is too old.  Make sure i
            t
     222    is in your PATH or set the PKG_CONFIG environment variable to the full
     223    path to pkg-config.
     224    
     225    Alternatively, you may set the environment variables ZMQ_CFLAGS
     226    and ZMQ_LIBS to avoid the need to call pkg-config.
     227    See the pkg-config man page for more details.
```

### Platform and user environment
I attempted the installation on:

```commandline
$ uname -a 
Linux debian-dev 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
$ lsb_release -d
Description:	Debian GNU/Linux 9.8 (stretch)
``` 

This is done with that latest version of Spack:

```commandline
$ spack --version
0.12.1
```

I've had similar behavior occurs on different systems with similarly minimal environments.
For instance with 'py-setuptools' the `unzip` but I realize in that case it's a core component and something I should have previously installed the package or install / use via Spack.

### Additional information

The issue will only occur if the environment Flux is being installed on lacks the `pkgconfig` package. I found that it is corrected by adding the `depends_on("pkgconfig")` to both 'flux-core/package.py` and `flux-sched/package.py`. I'm not sure if this is an acceptable solution or if their is a more preferred way.

**Comment by lee218llnl** [comment]
@paulbry, you can try adding depends_on(pkg-config) to flux-ched and flux-core as in #11036

**Comment by paulbry** [comment]
@lee218llnl Thanks, I wasn't sure if that was a the preferred solution at the time.

**Comment by lee218llnl** [comment]
@paulbry one slight update, please use "pkgconfig" instead of "pkg-config". The former is the virtual package, while the later is a specific implementation of the former.
