### ISSUE TITLE
util-linux provides libuuid

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#10812]
The standalone libuuid package only has an old 1.0.3 version. It looks like libuuid is now provided by util-linux (https://github.com/karelzak/util-linux). There is at least one package (psm) that should change its dependency from libuuid to util-linux to fix. Others currently depend on libuuid too:

bash-4.2$ grep libuuid -nr var/spack/repos/builtin/packages/*/package.py | grep depends_on
var/spack/repos/builtin/packages/cdo/package.py:68:    depends_on('libuuid')
var/spack/repos/builtin/packages/czmq/package.py:22:    depends_on("libuuid")
var/spack/repos/builtin/packages/davix/package.py:22:    depends_on('libuuid')
var/spack/repos/builtin/packages/dia/package.py:24:    depends_on('libuuid')
var/spack/repos/builtin/packages/flux-sched/package.py:33:    depends_on("libuuid")
var/spack/repos/builtin/packages/gaudi/package.py:30:    depends_on('libuuid')
var/spack/repos/builtin/packages/psm/package.py:21:    depends_on('libuuid')
var/spack/repos/builtin/packages/python/package.py:119:    depends_on('libuuid', when='+uuid')
var/spack/repos/builtin/packages/task/package.py:19:    depends_on('libuuid')
var/spack/repos/builtin/packages/taskd/package.py:17:    depends_on('libuuid')
var/spack/repos/builtin/packages/xeus/package.py:32:    depends_on('libuuid')

Any suggestions on the best path forward for updating libuuid/util-linux? Should be make util-linux a provider of libuuid?

Note that I created #10811 to fix the build of util-linux itself.

**Comment by lee218llnl** [comment]
@tgamblin @adamjstewart @michaelkuhn it looks like you are the contributers to the util-linux package. Let me know if you have any suggestions. I am playing with the packages that depend on libuuid and seeing if they build when switched to util-linux. So far it's looking good, but I'm hitting a few snags not related to libuuid/util-linux.

**Comment by carns** [comment]
I'm not sure if this issue is still active or not, but I found it while searching to make sure I didn't open a duplicate issue.  Spack actually has three separate packages providing different versions of libuuid now: "uuid", "libuuid", and "util-linux".  They refer to different versions/copies of the code that can be found at http://ftp.ossp.org/pkg/lib/uuid/, https://sourceforge.net/projects/libuuid/, and https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/.   Of the three the last one (the libuuid embedded in util-linux) appears to be the only one that has been updated in the last several years.

I suspect that the last one is the correct one to be using now, but I haven't experimented with this beyond discovering there are 3 different versions floating around.

**Comment by carns** [comment]
I just started to experiment with having packages that need libuuid depend on util-linux, and there is an immediate gotcha that util-linux depends on Python 2.7.  I don't particularly want to bring Python 2 along for the ride to get a few uuid functions.

**Comment by carns** [comment]
I just started to experiment with having packages that need libuuid depend on util-linux, and there is an immediate gotcha that util-linux depends on Python 2.7.  I don't particularly want to bring Python 2 along for the ride to get a few uuid functions.

**Comment by carns** [comment]
I just started to experiment with having packages that need libuuid depend on util-linux, and there is an immediate gotcha in that util-linux depends on Python 2.7.  I don't particularly want to bring Python 2 along for the ride to get a few uuid functions.

**Comment by adamjstewart** [comment]
We should create a virtual dependency for this.

**Comment by michaelkuhn** [comment]
I gave this a try in #18322, let me know what you think. I had to extract libuuid into a separate util-linux-uuid package to make the concretizer happy, though.
