### ISSUE TITLE
Weird shell dependency:  Spack and SELinux and patch

### ISSUE THREAD

**Issue by lisalenorelowe** [spack/spack#10849]
Please let me know if you have ever heard of this problem, or have any clue of what I can do to figure this one out:

Our HPC's default shell is tcsh.  Spack only works for us if we set our default path to bash.  I have already installed some software by just temporarily changing to bash and it has probably saved me 6 months worth of work in just one week, but that is sort of an embarrassing hack on our part.  I get an selinux error, but it does not create any record of that in the system error logs.  

Here is the main error.  It is during an attempt to install netcdf-fortran, just the first package that I tried.  Below that is the output of the entire install attempt that includes the pieces that were successful:
```console
==> Created stage in /myhome/spack/var/spack/stage/m4-1.4.18-hhsvnbbpgbjmyko773df2mzmp5knybru
/usr/bin/patch: setting attribute security.selinux for security.selinux: Permission denied
==> Patch /myhome/spack/var/spack/repos/builtin/packages/m4/secure_snprintf.patch failed.
==> Error: ProcessError: Command exited with status 2:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/myhome/spack/var/spack/repos/builtin/packages/m4/secure_snprintf.patch' '-d' '.'
```
Here is from the beginning:
```console
$ ./spack install netcdf-fortran
==> Installing libsigsegv
==> Searching for binary cache of libsigsegv
==> Warning: No Spack mirrors are currently configured
==> No binary for libsigsegv found: installing from source
==> Warning: A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> Fetching https://ftpmirror.gnu.org/libsigsegv/libsigsegv-2.11.tar.gz
######################################################################## 100.0%
==> Staging archive: /myhome/spack/var/spack/stage/libsigsegv-2.11-qpmaxx6z62df4s4hwyehdwptv6kmrfhf/libsigsegv-2.11.tar.gz
==> Created stage in /myhome/spack/var/spack/stage/libsigsegv-2.11-qpmaxx6z62df4s4hwyehdwptv6kmrfhf
==> No patches needed for libsigsegv
==> Building libsigsegv [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed libsigsegv
  Fetch: 0.89s.  Build: 11.22s.  Total: 12.11s.
[+] /myhome/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/libsigsegv-2.11-qpmaxx6z62df4s4hwyehdwptv6kmrfhf
==> Installing m4
==> Searching for binary cache of m4
==> Warning: No Spack mirrors are currently configured
==> No binary for m4 found: installing from source
==> Warning: A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> Fetching https://ftpmirror.gnu.org/m4/m4-1.4.18.tar.gz
######################################################################## 100.0%
==> Fetching https://src.fedoraproject.org/rpms/m4/raw/5d147168d4b93f38a4833f5dd1d650ad88af5a8a/f/m4-1.4.18-glibc-change-work-around.patch
######################################################################## 100.0%
==> Staging archive: /myhome/spack/var/spack/stage/m4-1.4.18-hhsvnbbpgbjmyko773df2mzmp5knybru/m4-1.4.18.tar.gz
==> Created stage in /myhome/spack/var/spack/stage/m4-1.4.18-hhsvnbbpgbjmyko773df2mzmp5knybru
/usr/bin/patch: setting attribute security.selinux for security.selinux: Permission denied
==> Patch /myhome/spack/var/spack/repos/builtin/packages/m4/secure_snprintf.patch failed.
==> Error: ProcessError: Command exited with status 2:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/myhome/spack/var/spack/repos/builtin/packages/m4/secure_snprintf.patch' '-d' '.'
```

**Comment by adamjstewart** [comment]
> Our HPC's default shell is tcsh. Spack only works for us if we set our default path to bash. I have already installed some software by just temporarily changing to bash and it has probably saved me 6 months worth of work in just one week, but that is sort of an embarrassing hack on our part.

Can you open an issue for this? This is definitely something we should be able to fix.

Unfortunately I don't know anything about the selinux error. You could try running `spack --debug patch m4` to get more debugging info.

**Comment by lisalenorelowe** [comment]
Hi Adam,

I almost forgot I opened this.

This was not Spack at all.  It turns out that in bash, the TMP directory was set to a place on NFS and in tcsh the TMP directory was set to a place on GPFS. 

For a first fix, we just told users to set TMP in alternate place, but since they should really store those temporary files to scratch, the sys admin did have to do something such that 'patch' had permissions to the scratch directory (in GPFS).  I don't understand the details, and I'm not even sure I'm explaining it correctly.

So I think this might be a useful piece of information to know for users - especially ones like me - who don't understand the sys admin side of things: there are selinux settings that don't allow 'patch' and other protected commands on certain files or directory paths.  It happens sometimes for Conda as well, when users set the temp directories in different places then what we now recommend.

**Comment by adamjstewart** [comment]
You can also set the default build directory in `config.yaml`

**Comment by lisalenorelowe** [comment]
Okay, thanks!
