### ISSUE TITLE
Hash of package changes if order of patch hashes in list changes

### ISSUE THREAD

**Issue by gartung** [spack/spack#10852]
I generate a spec.yaml for boost with 

spack spec -y boost+graph+iostreams+filesystem+system+thread+program_options >boost1.yaml

I clear all spack caches with

spack clean -a

I generated a spec.yaml for boost again with 

spack spec -y boost+graph+iostreams+filesystem+system+thread+program_options >boost2.yaml

The hashes of the two specs are different. Comparing them I determined the difference was the order of patch hashes stored in a list

```
diff boost*.yaml
58d57
<     - 2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199
60a60
>     - 2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199
72c72
<     hash: go6d7dfnbtdnl2bv45naafq7h2x6ueje
---
>     hash: pqyhzermfudo5gosxm4ecu4ruubahaet


spec:								spec:
- boost:							- boost:
    version: 1.69.0						    version: 1.69.0
    arch:							    arch:
      platform: linux						      platform: linux
      platform_os: scientific7					      platform_os: scientific7
      target: x86_64						      target: x86_64
    compiler:							    compiler:
      name: gcc							      name: gcc
      version: 4.8.5						      version: 4.8.5
    namespace: builtin						    namespace: builtin
    parameters:							    parameters:
      atomic: true						      atomic: true
      chrono: true						      chrono: true
      clanglibcpp: false					      clanglibcpp: false
      cxxstd: default						      cxxstd: default
      date_time: true						      date_time: true
      debug: false						      debug: false
      exception: true						      exception: true
      fiber: true						      fiber: true
      filesystem: true						      filesystem: true
      graph: true						      graph: true
      icu: false						      icu: false
      iostreams: true						      iostreams: true
      locale: true						      locale: true
      log: true							      log: true
      math: true						      math: true
      mpi: false						      mpi: false
      multithreaded: true					      multithreaded: true
      numpy: false						      numpy: false
      patches:							      patches:
      - 2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c687	      - 2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c687
      - 3a83d907043708218325c35ffc318fd6d6cfd78ba89a78f2c7001	      - 3a83d907043708218325c35ffc318fd6d6cfd78ba89a78f2c7001
      - 607b0772dec1287c9084ae3b36ee32bff945a2fe5e608823ed47a	      - 607b0772dec1287c9084ae3b36ee32bff945a2fe5e608823ed47a
      pic: false						      pic: false
      program_options: true					      program_options: true
      python: false						      python: false
      random: true						      random: true
      regex: true						      regex: true
      serialization: true					      serialization: true
      shared: true						      shared: true
      signals: true						      signals: true
      singlethreaded: false					      singlethreaded: false
      system: true						      system: true
      taggedlayout: false					      taggedlayout: false
      test: true						      test: true
      thread: true						      thread: true
      timer: true						      timer: true
      versionedlayout: false					      versionedlayout: false
      wave: true						      wave: true
      cflags: []						      cflags: []
      cppflags: []						      cppflags: []
      cxxflags: []						      cxxflags: []
      fflags: []						      fflags: []
      ldflags: []						      ldflags: []
      ldlibs: []						      ldlibs: []
    patches:							    patches:
    - 2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d <
    - 3a83d907043708218325c35ffc318fd6d6cfd78ba89a78f2c70013c	    - 3a83d907043708218325c35ffc318fd6d6cfd78ba89a78f2c70013c
    - 607b0772dec1287c9084ae3b36ee32bff945a2fe5e608823ed47a1e	    - 607b0772dec1287c9084ae3b36ee32bff945a2fe5e608823ed47a1e
							      >	    - 2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d
    dependencies:						    dependencies:
      bzip2:							      bzip2:
        hash: bahpjbtlwajqv6us2jfhrcgzynq5afod			        hash: bahpjbtlwajqv6us2jfhrcgzynq5afod
        type:							        type:
        - build							        - build
        - link							        - link
      zlib:							      zlib:
        hash: xnr7i4uunkorx7eg3a3ymdkendvaghkz			        hash: xnr7i4uunkorx7eg3a3ymdkendvaghkz
        type:							        type:
        - build							        - build
        - link							        - link
    hash: go6d7dfnbtdnl2bv45naafq7h2x6ueje		      |	    hash: pqyhzermfudo5gosxm4ecu4ruubahaet
- bzip2:							- bzip2:
    version: 1.0.6						    version: 1.0.6
    arch:							    arch:
      platform: linux						      platform: linux
      platform_os: scientific7					      platform_os: scientific7
      target: x86_64						      target: x86_64
    compiler:							    compiler:
      name: gcc							      name: gcc
      version: 4.8.5						      version: 4.8.5
    namespace: builtin						    namespace: builtin
    parameters:							    parameters:
      shared: true						      shared: true
      cflags: []						      cflags: []
      cppflags: []						      cppflags: []
      cxxflags: []						      cxxflags: []
      fflags: []						      fflags: []
      ldflags: []						      ldflags: []
      ldlibs: []						      ldlibs: []
    hash: bahpjbtlwajqv6us2jfhrcgzynq5afod			    hash: bahpjbtlwajqv6us2jfhrcgzynq5afod
- zlib:								- zlib:
    version: 1.2.11						    version: 1.2.11
    arch:							    arch:
      platform: linux						      platform: linux
      platform_os: scientific7					      platform_os: scientific7
      target: x86_64						      target: x86_64
    compiler:							    compiler:
      name: gcc							      name: gcc
      version: 4.8.5						      version: 4.8.5
    namespace: builtin						    namespace: builtin
    parameters:							    parameters:
      optimize: true						      optimize: true
      pic: true							      pic: true
      shared: true						      shared: true
      cflags: []						      cflags: []
      cppflags: []						      cppflags: []
      cxxflags: []						      cxxflags: []
      fflags: []						      fflags: []
      ldflags: []						      ldflags: []
      ldlibs: []						      ldlibs: []
    hash: xnr7i4uunkorx7eg3a3ymdkendvaghkz			    hash: xnr7i4uunkorx7eg3a3ymdkendvaghkz
```

**Comment by gartung** [comment]
@tgamblin This is with the head of develop.

**Comment by gartung** [comment]
Apparently list.dedupe does not preserve order here
https://github.com/spack/spack/blob/802dc4a03a4bb86cf42ff7f60915c1dabbbe31a9/lib/spack/spack/spec.py#L1970

Could be addressed by some of the comments in this search
https://www.google.com/search?client=safari&rls=en&ei=tMKGXJ7WKKefjgT8vbC4Aw&q=python+dedupe+list+preserve+order&oq=python+dedupe+list+preserve+order&gs_l=psy-ab.3..0j0i22i30.2511.6878..7018...0.0..0.116.1269.13j2......0....1..gws-wiz.......0i71.B1mcB5D-Nm4

**Comment by gartung** [comment]
Previous comment was incorrect. Next idea is that the patch cache json file in not preserving order.
https://github.com/spack/spack/blob/1450fe72fabc0dd9929f97ecb899120468280d2b/lib/spack/spack/util/spack_json.py#L22

This link found by searching google with "json dumps preserve order" suggests a way to preserve order in a json file

https://medium.com/@ty0h/preserving-json-object-keys-order-in-javascript-python-and-go-language-170eaae0de03

**Comment by gartung** [comment]
@tgamblin 
My working thesis is that the patches list order depends on the order of patches in the cache. The order of the patches list changes the full_hash.

https://github.com/spack/spack/blob/1450fe72fabc0dd9929f97ecb899120468280d2b/lib/spack/spack/util/spack_json.py#L18

The order in which json is written to file in not ordered. The option 'sort_keys': True should be added at the line above. 

https://stackoverflow.com/questions/10844064/items-in-json-object-are-out-of-order-using-json-dumps/23820416

**Comment by gartung** [comment]
Making this change breaks the spec tests for ordering.

**Comment by gartung** [comment]
https://github.com/spack/spack/pull/10869
Maybe this is the solution.

**Comment by gartung** [comment]
It seems to be caused by clearing the patch cache. I hit this because I am changing patches without changing the patch file name. I have to run 'spack clean -m' often.

**Comment by scheibelp** [comment]
To make sure: does `spack clean -m` resolve the issue for you? (not that you should have to do it, but I am checking if that works)

**Comment by gartung** [comment]
Actually that seems to create the problem because the patch cache is regenerated and is not always in the same order. This seems to impact the order of the patches list in the spec, but only every once in a while.

**Comment by gartung** [comment]
Yes rebuilding the cache fixes the problem of the checksum not matching, but introduces the problem described here. It was observed in the boost package which has 3 patched applied by default which yields 3!=6 permutations on the value of full_hash.

**Comment by scheibelp** [comment]
To check, are you using Python 3?

**Comment by gartung** [comment]
No. RHEL7 clone with python 2.7.

**Comment by gartung** [comment]
Further detail. I built a stack of packages with boost as a low level dependency. After building boost, I build one software stack depending on it. I started building another sofware stack depending on it and I had to clear the cache because of updated patch checksums. Suddenly boost and part of the first software stack was rebuilding. I tracked it down to the difference shown above in the boost spec's written into the .spack subdir of each boost install.

**Comment by scheibelp** [comment]
I think this and https://github.com/spack/spack/issues/10851 have the same cause: namely packages which include multiple patches with differing `when` conditions (patches with the same `when` condition will occur in the same order WRT one another, while patches with differing `when` conditions will have an unstable order). I don't think this is related to the patch cache.

I anticipate having a PR ready for dealing with these two issues tomorrow.

**Comment by gartung** [comment]
Additional information:
One package specifies dependency on boost with no explicit variants so it picks defaults.
Another package specifies dependency on boost with explicit variants that are on by default but in a different order than in the boost package definition.
