### ISSUE TITLE
Alternate Download Locations

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1090]
Sometimes, sites hosting software can go down. And this can throw a monkey wrench into an install.  One solution to this (in the works, I believe) is to cache tarballs.  Another approach, is for Spack to allow for more than one way to download a tarball.  Spack would then try all the alternates until it finds one that works.

Without that, we end up with things like PR #1089

**Comment by tgamblin** [comment]
Like mirrors? http://software.llnl.gov/spack/mirrors.html

You can host a mirror on a web server, in the file system, etc.

**Comment by citibeth** [comment]
The mirror functionality as it is right now isn't quite what I want.
Setting up a mirror is heavy-weight because it downloads a zillion versions
of a zillion packages, most of which I will never use.  Mirrors are good
for central Spack site admins, but not for most of us.

I need a cache; that is, a mirror that fills up gradually, as you download
packages anyway.

But for those of us who didn't forsee setting up a cache --- I'm suggesting
Spack allows for more than one URL when downloading.  More specifically:

1. Allow url_for_version() to optionally return a list of URLs, and Spack
would try all of them in order.
2. When doing version(url=...), allow it to be list as well as a simple
string.

**Comment by davydden** [comment]
I agree with @citibeth that providing alternative url to download within a package is a good idea, see for example this recent issue of similar kind https://github.com/LLNL/spack/issues/990.

**Comment by mwilliammyers** [comment]
I think there are at least two things that @citibeth is proposing (correct me if I am wrong) and I think they are both excellent ideas; I have been wanting both of them since I started using spack. 

1. Specify a list of "official", for lack of a better term, mirrors in a package's `package.py` that spack would try in a predefined order until one was successfully downloaded.
2. A self updating mirror (but really a cache). 
   - I really like specifically creating mirrors and adding a single package or packages from a file to the mirror. 
   - I also think it would be equally useful to make the mirror more cache like i.e. when I download a package it doesn't just stage the package but it also adds it to a local cache/mirror on the filesystem. Maybe you could also configure it with a `cache_downloads=True` in a config file or maybe packages are only cached if you already have a mirror setup etc. ? 
   - On the clusters I work with, we always cache our downloads so creating a cache manually can sometimes be cumbersome but at other times very helpful. But I think the proposed idea of a cache would almost always be helpful in our use case.

**Comment by citibeth** [comment]
Yes exactly

**Comment by tgamblin** [comment]
(2) is done at least -- see #579.

For (1), what about the package-scope `url` property?  Should that be allowed to be a list as well?

**Comment by citibeth** [comment]
Yes, I think so. url property, url_for_version, etc --- all could be a list.

**Comment by adamjstewart** [comment]
This may be unrelated but a similar problem I've seen is with licensed software that contains a different download/checksum depending on the OS. I think it would be useful to be able to handle multiple checksums for the same version. Ideally, the syntax would look something like:
```python
version('1.2.3', 'superlongchecksum', arch='darwin')
version('1.2.3', 'anotherlongchecksum', arch='linux')
```
or something like that, integrating the new arch support. Maybe url_for_version could return a different URL depending on the arch.

**Comment by tgamblin** [comment]
@adamjstewart: for consistency I think that should just be a `when=` clause, like for other directives, and *that* could allow lists.  I nasty messes of URLs at the top of some files but I don't see much of a way around it and I think this feature is vey useful.

**Comment by mwilliammyers** [comment]
I still contend that if you have mirror(s) configured, the downloads should be cached to your mirror(s) instead of the cache (or both). Is that not a good idea? It just makes maintaining a mirror all that much easier and less cumbersome...

**Comment by tgamblin** [comment]
@mwilliammyers: what if the mirror is not a `file:///` URL but an `https://` URL?  Then you can't really cache it there.  Also you might have a mirror that is not writable by you.

@scheibelp's local caching support merged last night (#579) builds a local mirror in `var/spack/cache`.  It gets populated with each archive you download.  This has the advantage of not assuming that you can write to an arbitrary mirror, but it builds a mirror that you own.  You can then take that directory and copy it to use as a Spack mirror elsewhere, too.  Is this what you want?

**Comment by mwilliammyers** [comment]
@tgamblin Yeah, I guess I was assuming that if you created the mirror than you should have write privileges, but I guess someone who didn't create it could be using spack... And I guess I was thinking that when you cached something it would somehow magically know to `rsync` or something it over to your remote server.  In short I didn't think those through... When you create a mirror will it first look in spack's cache for the packages to create/update the mirror? As in, are the mechanisms when downloading/staging a file the same as creating/updating a mirror in terms of how the cache is used? If they are, which I would assume they are, then that is what I originally was thinking of, in my head anyway.

**Comment by tgamblin** [comment]
I believe this is true -- the mirror is actually implemented at the level of the fetch strategy, so before fetching any URL, the mirror is checked.  @scheibelp can confirm.

**Comment by mwilliammyers** [comment]
So when you make a mirror the cache is not checked? At least with my testing that seems to be the case...

**Comment by tgamblin** [comment]
@mwilliammyers: that should not be the case.  @scheibelp: can you take a look at this?

**Comment by scheibelp** [comment]
cache is checked as part of executing Stage.fetch

mirror.create appears to retrieve the fetcher from the Stage vs. calling Stage.fetch

So this behavior makes sense - although it may be undesirable.

**Comment by tgamblin** [comment]
I think it would be really good to grab the tarballs from the local cache when creating a mirror, as well.

**Comment by citibeth** [comment]
On Wed, Jun 29, 2016 at 6:01 PM, mwilliammyers <notifications@github.com>
wrote:

> I still contend that if you have mirror(s) configured, the downloads
> should be cached to your mirror(s) instead of the cache (or both). Is that
> not a good idea? It just makes maintaining a mirror all that much easier
> and less cumbersome...
>
It is a bad idea:

Mirrors are useful for (among other things) proprietary software.  If you
have a tarball that can't be auto-downloaded... manually set up a mirror,
manually put the proprietary tarball in it, and point Spack to use that
mirror.  Then everything "just works".  The result is you end up with one
"manual" mirror full of precious tarballs you spent hours painstakingly
assembling.  The last thing you want is for Spack to write into that
directory, or delete it.

OTOH, regular Spack mirrors are not precious, and can be blown away if
needed, with only minor consequences.  Same thing for the Spack cache.

I do think it makes sense to use the same underlying infrastructure for
mirrors and  caches, at least for the part that reads them: they are both
sets of tarballs that are fetched from.

**Comment by tgamblin** [comment]
This is (finally) done!
