### ISSUE TITLE
Lmod with Flat Naming Scheme

### ISSUE THREAD

**Issue by shahzebsiddiqui** [spack/spack#10946]
spack supports Flat Naming Scheme when ``tcl`` is 
selected which will generate tcl modules. When spack use ``lmod`` it will generate Hierarchical Modules. There is no way to select Flat Naming Scheme when using lmod

### Rationale

Many HPC sites make use of lmod and Flat Naming Scheme is much easier to manage then 
Hierarchical Modules due to many module trees due to compiler, mpi, numerical libs. Even if there is many modules it is easier to find modules using ``module spider`` rather than trying to 
have user to hunt down the compiler, mpi to find the appropriate software. 

Hierarchical Module becomes hard to manage for administrator when there is multiple combination of **compiler * mpi * numlibs**

### Description

Please have support for Flat Naming Scheme when using lmod. According to https://spack.readthedocs.io/en/latest/module_file_support.html#module-file-customization the default template for lmod defined is implemented in https://github.com/spack/spack/blob/develop/lib/spack/spack/modules/lmod.py. 

### Additional information
*Add any other context about the feature request here.*

-----

If you want to ask a question about the tool (how to use it, what it can currently do, etc.), try the `#general` channel on our Slack first. We have a welcoming community and chances are you'll get your reply faster and without opening an issue.

Other than that, thanks for taking the time to contribute to Spack!

**Comment by alalazo** [comment]
Spack generates a flat layout for TCL module files. Lmod as a tool can be installed by Spack and supports reading TCL. Therefore one can generate a flat TCL layout and use lmod with it. Closing as this doesn't seem an issue, but feel free to reopen if you think otherwise.
