### ISSUE TITLE
Installation issue: intel-parallel-studio@cluster.2019.0 invalid COMPONENTS in silent.cfg

### ISSUE THREAD

**Issue by svenevs** [spack/spack#10958]
### Steps to reproduce the issue

**Note**: I'm not interested in jumping back down the rabbit hole on intel.  It's quite possible that the invalid components list is restricted to 2019.0.  I'm raising the issue to show a seemingly valid patch (but impossible for me to confirm given the second problem), and explain to anybody who may find this how to at least bypass it.

AKA: nbd to me if this gets closed / labelled #wontfix...I'm certainly not going to fix it.  I wish intel would stop changing everything on us.

### 1. Initial install fails due to lack of double quotes

```
==> [2019-03-21-05:03:00.327941] './install.sh' '--silent' 'silent.cfg'
--------------------------------------------------------------------------------                                                                             
Please select at least one component before you continue.
--------------------------------------------------------------------------------                                                                             
```
> [From OSX docs](https://software.intel.com/en-us/articles/silent-installation-guide-for-intel-parallel-studio-xe-composer-edition-for-os-x), but still relevant
>
> `COMPONENTS=<pattern>` allows the user to specify which components to install.  The components vary by compiler version and package.  **The components should be enclosed in double-quotes and semi-colon separated.**

This patch should be valid and works for me insofar as getting past this first one.

```diff
--- a/lib/spack/spack/build_systems/intel.py
+++ b/lib/spack/spack/build_systems/intel.py
@@ -1129,7 +1129,9 @@ class IntelPackage(PackageBase):
 
         # NB: .cfg files generated with the "--duplicate filename" option have
         # the COMPONENTS string begin with a separator - do not worry about it.
-        components_joined = ';'.join(self._filtered_components)
+        # COMPONENTS should be specified in double quotes, but no other args in
+        # silent.cfg should have them.
+        components_joined = '"{0}"'.format(';'.join(self._filtered_components))
         nonrpm_db_dir = os.path.join(prefix, 'nonrpm-db')
 
         config_draft = {
```

### 2. Spack generates an invalid component list

Putting them in double quotes, the installer will then produce unrecognized components.

```console
sven:~/Desktop/spack (fixes/from_sourcing_file)> cat /home/sven/Desktop/spack/var/spack/stage/intel-parallel-studio-cluster.2019.0-ibtu6qtngp3oon2jnt7krtb6wxto7ank/parallel_studio_xe_2019_cluster_edition/spack-build.out
...
==> [2019-03-21-05:09:25.478496] './install.sh' '--silent' 'silent.cfg'
COMPONENTS parameter in silent configuration file contains invalid values:

"intel-mkl-cluster__x86_64;intel-gdb-cdt-source__noarch"
--------------------------------------------------------------------------------
sven:~/Desktop/spack (fixes/from_sourcing_file)> /home/sven/Desktop/spack/var/spack/stage/intel-parallel-studio-cluster.2019.0-ibtu6qtngp3oon2jnt7krtb6wxto7ank/parallel_studio_xe_2019_cluster_edition/install.sh --list_components | grep mkl-cluster
intel-mkl-cluster-c__noarch, version: 2019.0
intel-mkl-cluster-f__noarch, version: 2019.0
```

So I'm actually just setting `components_joined = 'ALL'` to subdue it.  And setting all relevant variants to on.  As in this is my `packages.yaml` here:

```yaml
packages:
  intel-parallel-studio:
    version: [cluster.2019.0]
    variants: +advisor+clck+daal+gdb~ilp64+inspector+ipp+itac+mkl+mpi~newdtags+rpath+shared+tbb threads=none +vtune
```

Since for ALL it's going to try and install everything, even though e.g., this isn't a cluster.  (NOTE: the same issue if I turn off the variants that are invalid for my computer, leading me to believe this issue is likely specific to the 2019 versions).

However, what we do see here is that maybe spack should be trying to populate the potential component list by querying `install.sh --list_components`.  That would require some parsing (e.g., keep lines that have `version:` in them, then split on `,`).  But then we'd have to be able to actually map things back to the spack variants...which doesn't sound very fun.

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux pandora 4.18.16-300.fc29.x86_64 #1 SMP Sat Oct 20 23:24:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# $ lsb_release -d
# Description:	Ubuntu 18.04.1 LTS
$ rpm -E %fedora
29
```

**Comment by weijianwen** [comment]
This issue has been resolved by deleting `~/intel` directory before installation. Thaks for #9713  .

**Comment by weijianwen** [comment]
@svenevs does this issue persist when updating Spack to the latest version? I found that generated `silent.cfg` using `COMPONENTS=ALL` to install all available componets. According to Intel documents, this usage is valid since Intel 2016 to 2019.

**Comment by victoryang00** [comment]
not applicable for 2020

**Comment by adamjstewart** [comment]
Could one of you take a look at #15393, seems to be the same problem.

**Comment by svenevs** [comment]
Closing as no longer relevant / outdated.
