### ISSUE TITLE
incompatabilities with intel compilers installed to a system path

### ISSUE THREAD

**Issue by mforde84** [spack/spack#11038]
Hi,

I have a new environment which has Intel compilers installed to a system path that I dont have permissions to write to.

    [fordemx@iforgehn4 defaults]$ spack compilers
    ....
    -- intel rhel6-x86_64 -------------------------------------------
    intel@12.0.4
    [fordemx@iforgehn4 defaults]$ which icc
    /usr/local/intel/bin/icc

I'd like to use this as a core with lmod, however since it wasn't compiled by spack, it doesn't generate a luafile for Core. Is there as way I can generate a lua for this specific installation of icc and which loads the appropriate env variables for a working spack env? I say this because I've run into some issues compiling say ncurses with the system installed version of icc as it complains about unwritable system paths eg.,: 

    /sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission 
                 denied

**Comment by lee218llnl** [comment]
@mforde84 Any idea why ldconfig is being invoked. Can you provide more output i.e., perhaps run `spack --debug install ncurses%intel` and attach the ouptut and the spack-build.out

**Comment by lee218llnl** [comment]
I just test built ncurses with our system-install intel compilers. I see the same ldconfig error, but the build completes OK for me. Are you sure ldconfig is the error that is breaking the build?

**Comment by mforde84** [comment]
thanks for response. ill check a little later today.

**Comment by mforde84** [comment]
`==> [2019-03-29-12:16:03.809731] Error: ProcessError: Command exited with status 2:
    'make' '-j40' 'install'

7 errors found in build log:
     4334    ld: total time in link: 0.059990
     4335    ld: data size 26857024
     4336    cd /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-gckr7
             yf43h4wsr4f5dr7qtz4qbi56fuj/lib && (ln -s -f libncurses.so.6.1 libncurses.so.6; ln -s -f l
             ibncurses.so.6 libncurses.so; )
     4337    linking libncurses.so.6.1 to libcurses.so
     4338    cd /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-gckr7
             yf43h4wsr4f5dr7qtz4qbi56fuj/lib && (ln -s -f libncurses.so.6.1 libcurses.so; )
     4339    test -z "" && /sbin/ldconfig
  >> 4340    /sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
     4341    Makefile:873: recipe for target '/projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/
             intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libncurses.so.6.1' failed
     4342    make[1]: [/projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.
             1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libncurses.so.6.1] Error 1 (ignored)
     4343    installing ../lib/libncurses.a as /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64
             /intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libncurses.a
     4344    /usr/bin/install -c -m 644 ../lib/libncurses.a /projects/abv/GRC/spackroot/opt/spack/linux
             -rhel6-x86_64/intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libncurses.a
     4345    linking libcurses.a to libncurses.a
     4346    (cd /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-gckr
             7yf43h4wsr4f5dr7qtz4qbi56fuj/lib && ln -s -f libncurses.a libcurses.a; )

     ...

     4376    ld: data size 19582528
     4377    cd ../lib && (ln -s -f libpanel.so.6.1 libpanel.so.6; ln -s -f libpanel.so.6 libpanel.so; 
             )
     4378    ld: total time in link: 0.036993
     4379    ld: data size 8023616
     4380    cd /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-gckr7
             yf43h4wsr4f5dr7qtz4qbi56fuj/lib && (ln -s -f libpanel.so.6.1 libpanel.so.6; ln -s -f libpa
             nel.so.6 libpanel.so; )
     4381    test -z "" && /sbin/ldconfig
  >> 4382    /sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
     4383    Makefile:305: recipe for target '/projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/
             intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libpanel.so.6.1' failed
     4384    make[1]: [/projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.
             1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libpanel.so.6.1] Error 1 (ignored)
     4385    installing ../lib/libpanel.a as /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/i
             ntel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libpanel.a
     4386    /usr/bin/install -c -m 644 ../lib/libpanel.a /projects/abv/GRC/spackroot/opt/spack/linux-r
             hel6-x86_64/intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libpanel.a
     4387    ranlib /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-g
             ckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libpanel.a
     4388    installing ../lib/libpanel_g.a as /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64
             /intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libpanel_g.a

     ...

     4400    ld: data size 11865664
     4401    cd ../lib && (ln -s -f libmenu.so.6.1 libmenu.so.6; ln -s -f libmenu.so.6 libmenu.so; )
     4402    ld: total time in link: 0.037993
     4403    ld: data size 9936448
     4404    cd /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-gckr7
             yf43h4wsr4f5dr7qtz4qbi56fuj/lib && (ln -s -f libmenu.so.6.1 libmenu.so.6; ln -s -f libmenu
             .so.6 libmenu.so; )
     4405    test -z "" && /sbin/ldconfig
  >> 4406    /sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
     4407    Makefile:347: recipe for target '/projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/
             intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libmenu.so.6.1' failed
     4408    make[1]: [/projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.
             1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libmenu.so.6.1] Error 1 (ignored)
     4409    installing ../lib/libmenu.a as /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/in
             tel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libmenu.a
     4410    /usr/bin/install -c -m 644 ../lib/libmenu.a /projects/abv/GRC/spackroot/opt/spack/linux-rh
             el6-x86_64/intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libmenu.a
     4411    ranlib /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-g
             ckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libmenu.a
     4412    installing ../lib/libmenu_g.a as /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/
             intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libmenu_g.a

     ...

     4425    ld: data size 21827136
     4426    cd ../lib && (ln -s -f libform.so.6.1 libform.so.6; ln -s -f libform.so.6 libform.so; )
     4427    ld: total time in link: 0.038993
     4428    ld: data size 9313856
     4429    cd /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-gckr7
             yf43h4wsr4f5dr7qtz4qbi56fuj/lib && (ln -s -f libform.so.6.1 libform.so.6; ln -s -f libform
             .so.6 libform.so; )
     4430    test -z "" && /sbin/ldconfig
  >> 4431    /sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
     4432    Makefile:387: recipe for target '/projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/
             intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libform.so.6.1' failed
     4433    make[1]: [/projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.
             1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libform.so.6.1] Error 1 (ignored)
     4434    installing ../lib/libform.a as /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/in
             tel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libform.a
     4435    /usr/bin/install -c -m 644 ../lib/libform.a /projects/abv/GRC/spackroot/opt/spack/linux-rh
             el6-x86_64/intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libform.a
     4436    ranlib /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.4/ncurses-6.1-g
             ckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libform.a
     4437    installing ../lib/libform_g.a as /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/
             intel-12.0.4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/lib/libform_g.a

     ...

     4467    	using
     4468    		tic -x
     4469    	If you have ncurses 4.2 applications, you should read the INSTALL
     4470    	document, and install the terminfo without the -x option.
     4471    
     4472    installing panel.pc
  >> 4473    tic: error while loading shared libraries: libimf.so: cannot open shared object file: No s
             uch file or directory
     4474    ? tic could not build /projects/abv/GRC/spackroot/opt/spack/linux-rhel6-x86_64/intel-12.0.
             4/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/share/terminfo
     4475    Makefile:89: recipe for target 'install.data' failed
  >> 4476    make[1]: *** [install.data] Error 1
     4477    make[1]: Leaving directory '/tmp/fordemx/spack-stage/spack-stage-K5WyAc/ncurses-6.1/build_
             ncurses/misc'
     4478    Makefile:113: recipe for target 'install' failed
  >> 4479    make: *** [install] Error 2

See build log for details:
  /projects/abv/GRC/spackroot/var/spack/stage/ncurses-6.1-gckr7yf43h4wsr4f5dr7qtz4qbi56fuj/spack-build.out
Traceback (most recent call last):
  File "/projects/abv/GRC/spackroot/lib/spack/spack/build_environment.py", line 767, in child_process
    return_value = function()
  File "/projects/abv/GRC/spackroot/lib/spack/spack/package.py", line 1540, in build_process
    phase(self.spec, self.prefix)
  File "/projects/abv/GRC/spackroot/lib/spack/spack/package.py", line 102, in phase_wrapper
    phase(spec, prefix)
  File "/projects/abv/GRC/spackroot/var/spack/repos/builtin/packages/ncurses/package.py", line 82, in install
    with working_dir('build_ncursesw'):
  File "/projects/abv/GRC/spackroot/lib/spack/spack/build_environment.py", line 130, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/projects/abv/GRC/spackroot/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 2:
    'make' '-j40' 'install'
`

**Comment by mforde84** [comment]
I thought it was related to an unwritable path.

seems to be some discussion:
#3017
#8315

**Comment by mforde84** [comment]
i presume this may be related as well to the intel version, as its all the way back at v12.

**Comment by mforde84** [comment]
sorry i havent really had much exposure to the intel side of things

**Comment by lee218llnl** [comment]
oh wow, I didn't pay close enough attention to see you're running Intel 12! Do you have something more recent available?

**Comment by lee218llnl** [comment]
Did you try adding extra_rpaths to the compilers.yaml file to the directory that contains libimf.so?

**Comment by mforde84** [comment]
yea lol. its an oldie. let me try the latter.

**Comment by alalazo** [comment]
@mforde84 Any update to this issue?

**Comment by alalazo** [comment]
Closing this as stale (no reply since https://github.com/spack/spack/issues/11038#issuecomment-585636950)
