### ISSUE TITLE
Installation issue: GCC does not build on macOS 10.14.4

### ISSUE THREAD

**Issue by eschnett** [spack/spack#11042]
After upgrading to macOS 10.14.4, GCC 8.3.0 does not build any more. The issue is unrelated to Spack; even a vanilla GCC fails to install.

[This](https://apple.stackexchange.com/questions/355049/compilation-error-with-mojave-error-atomic-does-not-name-a-type/355103#355103) is a description of the error message. The underlying problem is that a macOS header file uses the `_Atomic` keyword for C++ code, although this is only a C keyword. The proper work-around is probably adding a "fixinclude" for GCC. [This](https://gist.github.com/eschnett/f912c6b791e29c83477575017271db16) describes the respective patch that is necessary. [This](https://github.com/eschnett/spack/commit/d9f16b6e9a38ab1a3cd78f1746e9fc8495b9f63e) is a commit for my Spack branch that can likely be cherry-picked. (I plan to open a pull request for this unless someone else beats me to it.)

**Comment by davydden** [comment]
I had that issues yesterday.  https://github.com/spack/spack/pull/11040 solved it for me, together with wiping out `/usr/include` and CLT.

**Comment by zbeekman** [comment]
Official GCC bug tracker for this issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89864

Fixes are present in Homebrew for 5,6,7,8.

**Comment by becker33** [comment]
@eschnett I'm closing this on @davydden's report that it's solved by #11040, which I just merged. If you still experience the bug after updating to include #11040 let me know.
