### ISSUE TITLE
Changing the commit ID for a version does not invalidate tarball cache

### ISSUE THREAD

**Issue by jjwilke** [spack/spack#11069]
Working off commit 03d39ed34cfab7008232678c8dd2ba5103a569e6

I had to update a variant to a new git commit ID to work around a bug, but spack fetched the variant from the local cache with a tarball built from the previous commit ID. This lead to a confusing silent error where the same commit ID (and same bug) got rebuilt. If not already done, the cache name should be based on a commit ID to avoid accidentally building an old commit.

**Comment by citibeth** [comment]
Can you be more specific about what you did?  What was the Spack command that failed?  What was the state of the relevant config files, repos, etc?  What was the source code of the Spack package in question?  Sorry, I just don't know what "I had to update a variant to a new git commit ID" means.

**Comment by jjwilke** [comment]
Not many relevant config files, other than a compilers.yaml pointing to a system gcc 7.2.0. I have my own version of trilinos.py with:
````
version('ifpack-optimization', commit='A', git='X')
````
I then built with 
````
spack install trilinos@ifpack-optimization %gcc@7.2.0
````

Keeping the same version label, I updated the commit:
````
version('ifpack-optimization', commit='B', git='X')
````
Instead of going back out to git to checkout the repo at the new commit, it found a cached tarball, unzipped it, and used that source code - which was the wrong commit.  It seems that when looking for cached versions of the source code, only the version label and not the commit ID is being used.

Thanks for looking at this.

**Comment by citibeth** [comment]
OK... so this contradicts a fundamental principle of Spack  (and open
source software in general): That two tarballs of the same version are the
same.  This problem happens from time to time, for example:

1. I release version 1.2.0 of my package and post a tarball.
2. One hour later, I discover there was an error.  So I change the tarball,
but leave it posted on my website as version 1.2.0

Bad, bad, bad.  Your example is essentially replicating the same problem.
Spack is assuming that if you use the (Spack) version number
'ifpack-optimization' for a package today, then the tarball downloaded for
that version will always be the same (unless the version is called
"develop").  I suppose that Spack could be smarter here to make its
decision based on the git commit / tarball URL of the version, rather than
your package's self-reported version.

Can you use a version called "develop" for your purposes here?   That would
likely solve the problem you're facing.  Or use real version numbers that
don't change.

**Comment by jjwilke** [comment]
We are setting up a series of performance regressions across a bunch of not-formally-released commits and want to automate builds with Spack. The versions here are "timestamps" for progression of the code.

It was not my original intent to change commits on versions. These are intended to be fixed.
It speaks to a general debate around Spack being _too_ helpful leading to strange implicit behavior.  
I would much rather have Spack NOT cache tarballs of git checkouts than cache them and use the wrong ones.

If it's clear in the docs then I guess user error and my fault.  A versioned tarball release, though, is much more "fixed" than a version based on a commit.

**Comment by citibeth** [comment]
Could there be a spack option to not cache or use cached tarballs?  That
would fix it.

For now you could do the poor mans approach of deleting the cache directory
each time before you run spack.

**Comment by jjwilke** [comment]
Yeah, I guess the concern is more that no one accidentally does this in the future. Since I know the issue, I can just clear my cache when I need to. Preferably the tarball name (or something) would use the commit and then see the cache is invalid.

Thanks again.

**Comment by jjwilke** [comment]
UPDATED: Okay, fooled me twice so shame on me : )

This problem also applies to patches. I created a new version, which failed to build requiring a patch for a minor problem. It seems the tarball is created "post-patch"? I had a cached version of the tarball which got rebuilt _without_ the new patch.

This one is actually more concerning that the commit change. If I add a new patch to a version I think that should definitely invalidate anything in the cache for that version.

**Comment by jjwilke** [comment]
I stumbled across in the `GitFetchStrategy` class while reading code:
````
    @property
    def cachable(self):
        return bool(self.commit or self.tag)
````
I assume this means that specific branches are not cached (should not assume that master is the same the next day). The philosophy that a version label should never change seems a bit inconsistent here. If I specify `branch = master`, I still have to give that a version name (probably `master`). I'm probably bike-shedding. 

It does not appear that the git repo itself is tarballed - just the source. Would a better strategy be for commit, tag, and branch fetch strategies to untar the cached git repo then do a checkout? If you're already on the the expected commit/tag/branch, no-op. Otherwise, you pull a small diff to get up to date. This would avoid the dangers of caching, particularly for commit fetch strategy

**Comment by alalazo** [comment]
I think we can close this, since Spack supports git versions of the form:
```
foo@commit-hash=known-version
```
The commit hash can be specified on the command line, while the known version is used to determine the recipe used to build that hash. Feel free to reopen if you disagree with this.
