### ISSUE TITLE
Spack uses too many processes by default and runs out of memory

### ISSUE THREAD

**Issue by jjwilke** [spack/spack#11072]
Related to #327. I know there was a lot of discussion about it in the previous issue.

Rather than just a performance optimization, this actually causes builds to fail.
Too many processes active at once leads to very strange gcc 'internal compiler error' messages. I *think* this is gcc running out of memory, but have not been able to confirm. 

By default, Spack spins up 160 make jobs, which very quickly burns the available memory (C++ compilations involving Trilinos). Lowering the number of make jobs makes the compiler errors go away.

I believe this should be fairly easy to fix because of the use of the compiler wrapper. The compiler wrapper could check available memory on the node upon exiting with an error. If the available memory is very low, this would be a "non-fatal error" and would trigger a reduction in the number of make jobs.

The notion of a "non-fatal error" that can be diagnosed and fixed might be useful in general if there are other situations like this that might arise.

*make -> error
*diagnose and fix
*make (pick up where left off)

**Comment by healther** [comment]
You can manually limit the amount of parallelism by doing `spack install -j20 yourpackage`, or do that setting in your `config.yaml` file via the option `build_jobs: 20`

**Comment by jjwilke** [comment]
Yes, that what was I did to get it to work for now. More generally, though, this would be a very strange error for a "non-expert." Almost all of our codes are going to involve memory-intensive C++ builds. Users will very quickly give up on Spack if they get bizarre errors - particularly non-deterministic ones.

**Comment by mwkrentel** [comment]
In #10627, I suggested setting the default by some kind of sliding
scale.  Up to 8, use all cores, then start to back off with a cap of
16 or 20.

My point is that for machines with >> 100 cores (or hardware threads),
then all available cores is not a good default.  In my case, I
accidentally brought down a power8 with 48 cores and 4x HT when spack
ran `-j 192`.  It's just too easy to make a mistake like this.

Of course, this is only the default.  A user can always write `-j 64`
if that's appropriate for your machine.

**Comment by citibeth** [comment]
I agree.  I don't know of any packages for which 160-way builds are significantly faster than 20-way builds.  Would someone like to submit a PR for the backoff feature?  Then we'd have max 20 (or so), unless overridden by `-j`.

**Comment by ptooley** [comment]
I think that spack is still an outlier compared to all other build tools that people would have come across and the default should be to use 1 make job.  In general tools don't parallelise builds unless they are asked too, and changing the defaults is a much simpler solution than adding extra code to try to create some kind of pseudo-intelligent solution.

**Comment by jjwilke** [comment]
I have had the same problem with Ninja, which parallelizes by default (I think). But then it uses TOO many processes.  I agree that fewer is a better default. I guess a counterargument would be some recent build tools are parallelizing by default.  I like "slow and successful" as a better default than "fast and failed."

**Comment by citibeth** [comment]
I think spack should just limit to 20 jobs by default.  This should work on
99% of systems where it currently does not.  Let’s not overthink this one.

**Comment by jjwilke** [comment]
Agreed. I like 20 better than 1.

**Comment by ptooley** [comment]
So how does that look?  spack uses ``num_cores if num_cores <= 20 else 20`` cores.  Presumably this adds a second configuration variable of ``max_jobs`` or similar?

**Comment by citibeth** [comment]
> So how does that look?

Fine by me.  Just remember that there are REAL and VIRTUAL cores these days.  My guess is Spack should base its -j on the number of virtual cores.

@alalazo  Thanks for tackling this one!
