### ISSUE TITLE
[question] How do I access build environment variables?

### ISSUE THREAD

**Issue by vsoch** [spack/spack#11074]
For example, I would want to know:

 - $GOPATH used when GoLang is installed
 - some envar to point me to the directory where my configuration is going on, e.g. ` /tmp/vanessa/spack-stage/spack-stage-0tjsd1js/singularity-3.1.0`
 - how to get the version of the current software being installed from spec / self or prefix (I inspected the objects but am not sure what function / variable is correct).

Thanks!

**Comment by vsoch** [comment]
Also, is there some kind of cache maintained during building? How do I clear it?

**Comment by adamjstewart** [comment]
> $GOPATH used when GoLang is installed

Inside a `package.py`, you can use `env['GOPATH']` or `os.environ['GOPATH']`. Post-installation, these values are stored in `<prefix>/.spack/build.env`

> some envar to point me to the directory where my configuration is going on

`self.build_directory`

> how to get the version of the current software being installed

`self.version`. This is a `Version()` object, but you can convert it to a string if you want.

> is there some kind of cache maintained during building?

Yes, if the build fails, the build cache remains in place so you can examine the build log. If the build succeeds, the build cache is automatically deleted. You can run `spack clean` to clear all build caches.

**Comment by vsoch** [comment]
Perfecto! I'll try these out.

**Comment by adamjstewart** [comment]
Yes, you should add a package for any dependency that isn't already in Spack. Back in the day this was more common than it is now. Nowadays most dependencies are already in Spack.

As far as reviewing goes, it's easier to review and merge a PR when it only involves one package. But if one of your new packages depends on another new package, it is fine to submit both packages in a single PR.

**Comment by vsoch** [comment]
okay I'll give a crack at each package separately. Apologies in advance for not knowing what I'm doing :)

**Comment by adamjstewart** [comment]
No worries, we love to see contributions from new users! Ping me on your PR if it sits for more than a week without a review. And don't worry about submitting a work-in-progress PR if you have any more questions about the best way to do something.

If you haven't found it already, https://spack.readthedocs.io/en/latest/packaging_guide.html is incredibly helpful for new users and provides tips for different situations that might arise when writing a new package. Also, https://spack.readthedocs.io/en/latest/build_systems.html provides more details for specific build systems. Let me know if you have any other questions that aren't already documented.

Welcome to the Spack community!

**Comment by vsoch** [comment]
Thank you! Just submit my first https://github.com/spack/spack/pull/11077

**Comment by vsoch** [comment]
Thanks @adamjstewart my questions are answered here - I'll open another PR if I run into more issues! Thanks for your speedy help and links to the docs!
