### ISSUE TITLE
Installation issue: charmpp 

### ISSUE THREAD

**Issue by hongyx11** [spack/spack#11125]
Charmpp install failed because of MPI

I just want to install charmpp but encounter the MPI problem, it's g++ and -lmpi problem, I think g++ needs to use -lmpi_cxx library, weird.

```console
$ spack location -s charmpp

/home/hongy0a/Github/spack/var/spack/stage/charmpp-6.9.0-klaagpebpcsooek3pzxsgwcl5exbdyxl
```

### Steps to reproduce the issue

```console
$ spack install charmpp backend=mpi +pthreads
```
### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux buraq 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 16.04.6 LTS
``` 

### Additional information

Sometimes the issue benefits from additional details. In these cases there are
a few things we can suggest doing. First of all, you can post the full output of:
```console
$ spack spec --install-status charmpp

Input spec
--------------------------------
 -   charmpp

Concretized
--------------------------------
 -   charmpp@6.9.0%gcc@5.5.0 backend=netlrts build-target=LIBS ~cuda~omp~papi+production~pthreads+shared+smp~syncft~tcp~tracing arch=linux-ubuntu16.04-x86_64

```
to show people whether Spack installed a faulty software or if it was not able to
build it at all. 

If your build didn't make it past the configure stage, Spack as also commands to parse 
logs and report error and warning messages:
```console
$ spack log-parse --show=errors,warnings <file-to-parse>

```
15 errors
5 warnings
     83      make[1]: Entering directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp'
     84      autoreconf
     85      autoheader
  >> 86      automake: warning: am_libhwloc_embedded_la_rpath was already defined in condition TRUE, which includes condition !HWLOC_BUILD_STANDALONE ...
     87      configure.ac:2803: ... 'am_libhwloc_embedded_la_rpath' previously defined here
     88      ./configure --disable-controlpoint --disable-tracing --disable-tracing-commthread --disable-charmdebug --disable-replay --disable-error-checking --disable-stats
  >> 89      Error checking is disabled
     90      AMPI error checking is enabled
     91      Statistics collection is disabled
     92      Charm tracing is disabled

     ...

     878     if [ 0 -gt 0 ]; then	make -f Makefile_windows;\
     879     else make -f Makefile_default;	fi
     880     make[2]: Entering directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/boost-contex
             t'
  >> 881     make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
     882     ../../bin/charmc -c jump_x86_64_sysv_elf_gas.S
     883     ../bin/charmc  -optimize -production  -build-shared -DCMK_NOT_USE_CONVERSE=1 ccs-client.c
     884     ar: creating ../lib/libldb-rand.a

     ...

     1070    make[1]: Entering directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/libs/ck-libs
             /metis'
     1071    make -C GKlib all;
     1072    make[2]: Entering directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/libs/ck-libs
             /metis'
  >> 1073    make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
     1074    ../../../../../bin/charmc -I. -I../GKlib -optimize -production  -build-shared    -c -o b64.o b64.c
     1075    ../bin/charmc  -optimize -production  -build-shared -I.   -c -o EveryLB.o EveryLB.C
     1076    ../bin/charmc  -optimize -production  -build-shared -o ../lib/libck.a trace-common.o tracec.o tracef.o init.o register.o qd.o ck.o msgalloc.o ckfutures.o ckIgetCont
             rol.o debug-message.o debug-charm.o ckcallback.o cklocation.o ckmulticast.o ckarrayoptions.o ckarray.o ckreduction.o ckrdma.o waitqd.o LBDatabase.o MetaBalancer.o w
             eakTest.o treeTest.o forestTest.o readmodel.o lbdb.o lbdbf.o ckobjQ.o LBAgent.o LBProfit.o ckcheckpoint.o ckmemcheckpoint.o ckevacuation.o ckmessagelogging.o ckcaus
             almlog.o ckobjid.o LBDBManager.o LBComm.o LBObj.o LBMachineUtil.o CentralPredictor.o BaseLB.o CentralLB.o HybridBaseLB.o NborBaseLB.o DistBaseLB.o ckgraphTemp.o ckg
             raph.o LButil.o RefinerTemp.o Refiner.o RefinerApprox.o manager.o RefinerComm.o bitvecset.o ckset.o ckheap.o CommLBHeap.o NullLB.o LBSimulation.o modifyScheduler.o
             charmProjections.o cktiming.o ckbitvector.o pathHistory.o controlPoints.o arrayRedistributor.o cp_effects.o trace-controlPoints.o mpi-interoperate.o ckregex.o sdag.
             o

     ...

     1345    make[2]: Leaving directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/libs/ck-libs/
             metis/GKlib'
     1346    make -C libmetis all;
     1347    make[2]: Entering directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/libs/ck-libs
             /metis'
  >> 1348    make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
     1349    ../../../../../bin/charmc -I. -I../GKlib -optimize -production  -build-shared    -c -o auxapi.o auxapi.c
     1350    ../../../../../bin/charmc -I. -I../GKlib -optimize -production  -build-shared    -c -o balance.o balance.c
     1351    ../../../../../bin/charmc -I. -I../GKlib -optimize -production  -build-shared    -c -o bucketsort.o bucketsort.c

     ...

     1798    checking if darray and subarray constructors are defined in the MPI implementation... no
     1799    checking for weak symbol support... no
     1800    checking whether file locks work with NFS... no
  >> 1801    Warning: File locks do not work with NFS.  See the Installation and
     1802    users manual for instructions on fixing this
     1803    checking for strerror()... no
     1804    checking for sys_errlist... no
     1805    checking if a simple MPI program compiles and links... /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi
             5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o): In function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
  >> 1806    mpi-interoperate.C:(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x15): undefined reference to `ompi_mpi_cxx_op_inte
             rcept'
     1807    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o): In fu
             nction `MPI::Intracomm::Clone() const':
  >> 1808    mpi-interoperate.C:(.text._ZNK3MPI9Intracomm5CloneEv[_ZNK3MPI9Intracomm5CloneEv]+0x2a): undefined reference to `MPI::Comm::Comm()'
     1809    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o): In fu
             nction `MPI::Graphcomm::Clone() const':
  >> 1810    mpi-interoperate.C:(.text._ZNK3MPI9Graphcomm5CloneEv[_ZNK3MPI9Graphcomm5CloneEv]+0x25): undefined reference to `MPI::Comm::Comm()'
     1811    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o): In fu
             nction `MPI::Cartcomm::Sub(bool const*) const':
  >> 1812    mpi-interoperate.C:(.text._ZNK3MPI8Cartcomm3SubEPKb[_ZNK3MPI8Cartcomm3SubEPKb]+0x7d): undefined reference to `MPI::Comm::Comm()'
     1813    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o): In fu
             nction `MPI::Intracomm::Create_graph(int, int const*, int const*, bool) const':
  >> 1814    mpi-interoperate.C:(.text._ZNK3MPI9Intracomm12Create_graphEiPKiS2_b[_ZNK3MPI9Intracomm12Create_graphEiPKiS2_b]+0x29): undefined reference to `MPI::Comm::Comm()'
     1815    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o): In fu
             nction `MPI::Cartcomm::Clone() const':
  >> 1816    mpi-interoperate.C:(.text._ZNK3MPI8Cartcomm5CloneEv[_ZNK3MPI8Cartcomm5CloneEv]+0x25): undefined reference to `MPI::Comm::Comm()'
     1817    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o):mpi-in
             teroperate.C:(.text._ZNK3MPI9Intracomm11Create_cartEiPKiPKbb[_ZNK3MPI9Intracomm11Create_cartEiPKiPKbb]+0x87): more undefined references to `MPI::Comm::Comm()' follo
             w
  >> 1818    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o):(.data
             .rel.ro._ZTVN3MPI8DatatypeE[_ZTVN3MPI8DatatypeE]+0x78): undefined reference to `MPI::Datatype::Free()'
  >> 1819    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/../lib/libck.a(mpi-interoperate.o):(.data
             .rel.ro._ZTVN3MPI3WinE[_ZTVN3MPI3WinE]+0x48): undefined reference to `MPI::Win::Free()'
  >> 1820    collect2: error: ld returned 1 exit status
  >> 1821    Fatal Error by charmc in directory /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/libs/c
             k-libs/ampi/romio
     1822       Command g++ -rdynamic -D_REENTRANT -O -O2 -L/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/openmpi-3.1.3-4web3zmys3nj6icwky2r6jw2y67oot5
             2/lib -fPIC mpitest.o moduleinit16896.o -L/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin
             /../lib -lmoduletcharm -lmoduleampi -lmoduletcharmmain /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi
             5mivvoppc/lib/libmoduleampi.a -lampi-compat -lckmain -lck -lmemory-default -lthreads-default -lconv-machine -lconv-core -ltmgr -lconv-util -lconv-partition -lhwloc_
             embedded -lm -lmemory-default -lthreads-default -lldb-rand -lconv-ldb -lpthread -lckqt -lckqt -lpthread -ldl -lmoduletcharmmain -lmoduleampi -lmoduletcharm -ltcharm
             -compat -lmoduleNDMeshStreamer -lmodulecompletion -lmpi -lz -lm /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyz
             dncizzumi5mivvoppc/bin/../lib/conv-static.o -o conftest returned error code 1
     1823    charmc exiting...
     1824

     ...

     1827    *# MPI implementation, the include path for mpi.h, and the MPI library to link
     1828    /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/bin/ampicc -optimize -production -build-share
             d  -O -I/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/include -o conftest mpitest.c /home/h
             ongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/lib/libmoduleampi.a
     1829    Makefile:47: recipe for target '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/lib/libampiro
             mio.a' failed
  >> 1830    make[3]: *** [/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/lib/libampiromio.a] Error 1
     1831    make[3]: Leaving directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/libs/ck-libs/
             ampi'
     1832    Makefile:19: recipe for target 'ampi' failed
  >> 1833    make[2]: *** [ampi] Error 2
     1834    make[2]: Leaving directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/libs/ck-libs'
     1835    Makefile:9: recipe for target 'charmlibs' failed
  >> 1836    make[1]: *** [charmlibs] Error 2
     1837    make[1]: Leaving directory '/home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp/libs'
     1838    Makefile:727: recipe for target 'CHARMLIBS' failed
  >> 1839    make: *** [CHARMLIBS] Error 2
     1840    -------------------------------------------------
     1841    Charm++ NOT BUILT. Either cd into /home/hongy0a/Github/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/charmpp-6.9.0-onicsqnegfzkyzdncizzumi5mivvoppc/tmp and try
     1842    to resolve the problems yourself, visit

**Comment by phanousk** [comment]
For the record, this has been perhaps closed because current git master of charmpp builds and gets installed succesfully.
