### ISSUE TITLE
remove unneeded implicit packages

### ISSUE THREAD

**Issue by modkin** [spack/spack#11139]
It would be nice to have the ability to remove all implicit packages that are not needed anymore since the explicit package that requested them is already uninstalled

### Rationale

This would be really helpful to keep the list of installed packages tidy and save memory space

### Description

I could image extending the `spack clean` command to support such an action.
But also introducing a new command like `spack reclaim` (inspired by macports) would be an option.

**Comment by alalazo** [comment]
Duplicate of #4382

Is that what you mean?

**Comment by modkin** [comment]
Yes indeed its a duplicate. I did some searching but could not find that issue. 

Thank you

**Comment by alalazo** [comment]
@modkin No worries! Be sure to give a thumbs up or something on the other issue, so we can keep track somehow of the request :slightly_smiling_face:
