### ISSUE TITLE
per-user settings require security hole when staging builds 

### ISSUE THREAD

**Issue by frankwillmore** [spack/spack#11163]
I’m trying to override a setting (build-stage) for a regular user outside of a system spack installation (installed as a service user ‘spack’) with the intent of the user having builds staged to ~/.spack/var/spack/stage. 

My ~/.spack/config.yaml seting looks like this:  
```
build_stage:
     - ~/.spack/var/spack/stage
```

And the system install: $spack/etc/spack/defaults/config.yaml looks like this:
 ```
build_stage:
   - $tempdir
   - $spack/var/spack/stage
```

The intent is to allow per-user overriding of the build stage via ~/.spack/config.yaml settings, thus enabling individual users to leverage the system spack to build and deploy packages in their own storage space.

However, instead of simply staging as requested, spack attempts to generate a symbolic link from the user's staging area into the system-wide staging area at ```$spack/var/spack/stage.```

Individual users do not and should not have access to write to  ```$spack/var/spack/stage``` and thus, when a user attempts to build, spack attempts to generate a sym link here and fails.

### Information on your system

Cray XC-40 / ALCF theta

**Comment by citibeth** [comment]
Does #8772 address your issue?

**Comment by frankwillmore** [comment]
It does not.

#8772 addresses issues of maintaining the database and module system with a similar setup.

Our concern is much simpler. When a user attempts to use the upstream spack installation, overriding the staging area on a per-user basis, spack attempts to create a symbolic link from the upstream staging area to the user-specified area. 

We consider this a security risk because it requires the upstream staging area to be writeable by all users.  **It's not acceptable to us for any system area to be writeable by all users**.  We set permissions as follows:
```willmore@thetalogin1:~$ ls ~spack/spack-dev/var/spack/stage/ -ld
drwxrwxr-x 2 spack software 20480 May  6 19:55 /soft/spack/spack-dev/var/spack/stage/
```

We would request a way to disable the writing of the symbolic link. 

To clarify our setup a bit, our spack installation is owned by a service user, spack. Users in the 'software' group are allowed to install to the system area. All users are allowed to use the upstream installation to build and install to their own area, based on settings in their ~/.spack. 

Right now, it's not possible for users to use the upstream install without opening this security hole.

**Comment by citibeth** [comment]
I believe it's possible to tell where to put the staging area in some YAML
config file???

**Comment by frankwillmore** [comment]
Yes. As I mention above, the per-user config.yaml specifies where the build is to be staged and this behaves as expected:
```
build_stage:
     - ~/.spack/var/spack/stage
```

However, there is the erroneous link being added to the upstream staging area, e.g.:
```
lrwxrwxrwx 1 willmore users 68 Apr 12 19:41 /soft/spack/spack-dev/var/spack/stage/zlib-1.2.11-ajxhsmrlv2kvicpk3gdckgrroxr45mdl -> /home/willmore/.spack/var/spack/stage/spack-stage/spack-stage-UMrNRh
```

The fix would be for spack to simply not write this link.

**Comment by citibeth** [comment]
Sounds simple enough but I do t know the ramifications of that change.  Can
you open an issue or pull request?

**Comment by adamjstewart** [comment]
Hey @frankwillmore! Let me see if I understand your issue correctly. You have a single Spack clone in a system location that every user can use, but you don't give users write access to the directory where Spack currently adds symlinks. From what I understand, you have 3 types of users:

- `spack` user who can do anything
- `software` group who can install but can't modify Spack itself
- everyone else, who has no permission to change anything

Is this correct? Do you also override the install location? Or do you only give users access to the install directory?

I don't know much about this particular section of code, but I don't know of any reason why the symlink is necessary. Maybe @scheibelp or @tgamblin can comment?

**Comment by becker33** [comment]
@frankwillmore @adamjstewart Those symlinks were designed to give users an entrypoint to inspect the stage directories, rather than having them show up in seemingly random places in tmp. They predate the `spack location` and `spack cd` commands that also give users options to inspect those paths, and IIRC also predate the `spack clean` option to remove those files.

@tgamblin was discussing changing this just yesterday or the day before at ISC. I don't think it would require much beyond just not creating those links, but we should probably bring Todd in on this since he clearly has an idea what he wants to do with that.

**Comment by frankwillmore** [comment]
@adamjstewart 
> Is this correct? Do you also override the install location? Or do you only give users access to the install directory?
Above points are correct.
I override the install location in ~/.spack/config.yaml with:
```install_tree: ~/.spack/opt/spack``` 
and the build stage with 
```  build_stage:
    - ~/.spack/var/spack/stage ```
but of course it doesn't get to the install as it fails for the non-privileged user staging the build. 

@becker33 I tried commenting out the line of python that generates the sym link, hoping this was merely a convenience to the user as described, but this was not sufficient. Perhaps spack is following the generated sym link, and not the provided value of ```build_stage```? 

This is part of ECP work at Argonne LCF and the one thing keeping us from making our spack setup broadly available to users.

**Comment by tgamblin** [comment]
Assigning this to @tldahlgren.
