### ISSUE TITLE
sourcing setup-env.csh takes 10 seconds

### ISSUE THREAD

**Issue by Char-Aznable** [spack/spack#11228]
For some reasons, I have to install spack on a NFS and sourcing the setup-env.csh takes too long. I have to wait for 10 sec every time I open a new terminal. Is there way around this?

**Comment by healther** [comment]
Depending on which features of spack you are using, you can try to stick with directly using the binary `bin/spack` rather than the shell command `spack`

**Comment by Char-Aznable** [comment]
What features are compromised by not sourcing the script?

**Comment by Char-Aznable** [comment]
related to https://github.com/spack/spack/issues/7355

**Comment by healther** [comment]
`bin/spack install <spec>` works for us without sourcing (used in CI jobs). But anything that I'm doing manually I'm doing with a sourced shell, so I don't really know.

**Comment by alalazo** [comment]
I just tried on a system at UO, using `csh`:
```console
$ time source share/spack/setup-env.csh
0.581u 0.144s 0:03.58 20.1%	0+0k 27392+14464io 0pf+0w
```
A few seconds overall, but not as bad as it used to be.
