### ISSUE TITLE
create a uniform way to access cmake build tool (make vs ninja)

### ISSUE THREAD

**Issue by svenevs** [spack/spack#11227]
The LLVM package has some raw `make(...)` calls, which will error if I set my cmake generator to `Ninja`.  I want to create a uniform way of enabling all cmake packages to have access to the underlying build tool generically so that raw `make(...)` calls can be patched consistently as they are discovered.

I propose we call it `self.build_tool` and set it up somewhere in `cmake.py`.  I need guidance as to where exactly in `cmake.py` is appropriate for this to get created.  Something like

```py
if self.generator == 'Unix Makefiles':
    build_tool = inspect.getmodule(self).make
elif self.generator == 'Ninja':
    build_tool = inspect.getmodule(self).ninja
setattr(self, 'build_tool', build_tool)
```

So that in the LLVM package I can do

```diff
- make('install-LLVMTableGen')
+ self.build_tool('install-LLVMTableGen')
```

### Steps to reproduce the issue

Set the CMake generator to `'Ninja'`, because all the cool kids are doing it.

https://github.com/spack/spack/blob/3f50dcf6d91192253af320aaf72fcb13d307e137/lib/spack/spack/build_systems/cmake.py#L90

Then try and build `llvm`.  You will hit this code, which will fail because we generated for Ninja, not Make.

https://github.com/spack/spack/blob/eb7c79720de66cc7b74ac0c6a1ce1d44ee670cd5/var/spack/repos/builtin/packages/llvm/package.py#L693-L701

**Comment by alalazo** [comment]
> So that in the LLVM package I can do [...]

I think a uniform way already exists, and is accessible by CMake command line:
```console
$ cmake --build <dir> --target install-LLVMSupport
```
which should translate to:
```python
cmake('--build', self.build_directory, '--target', 'install-LLVMSupport')
```
Documentation [here](https://cmake.org/cmake/help/v3.14/manual/cmake.1.html#build-a-project). Can you check if it works?

**Comment by svenevs** [comment]
This will work, I forgot that you don't need to `cd` to the build directory for `cmake --build`.

Should this remain serial or should I set `-j`?

**Comment by svenevs** [comment]
Closing as stale

https://github.com/spack/spack/blob/d64de54ebe83853694e30e562b7f9edc996ccd2d/var/spack/repos/builtin/packages/llvm/package.py#L32

LLVM now sets `ninja` as the generator.  The package overwrites `generator`, if spack decides to enable users to choose their own cmake generator then packages can be unified.
