### ISSUE TITLE
static builds on cray system might link against libgfortran.so

### ISSUE THREAD

**Issue by azrael417** [spack/spack#1126]
I tried building glog and protobuf in static mode using spack with gcc. While doing this manually works pretty well (module load PrgEnv-gnu, module load gcc/5.3.0, ./configure --enable-static --disable-shared), doing this from within space fails. The reason is the following:

/bin/sh ../libtool --tag=CXX   --mode=link /global/u2/t/tkurth/MODULES/spack/lib/spack/env/gcc/g++  -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG   -o protoc google/protobuf/compiler/main.o  libprotobuf.la libprotoc.la 
libtool: link: /global/u2/t/tkurth/MODULES/spack/lib/spack/env/gcc/g++ -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -o protoc google/protobuf/compiler/main.o  ./.libs/libprotobuf.a ./.libs/libprotoc.a /tmp/tkurth/spack-stage/spack-stage-cPOrCh/protobuf/src/.libs/libprotobuf.a /opt/gcc/5.3.0/snos/lib/../lib64/libgfortran.so /opt/gcc/5.3.0/snos/lib/../lib64/libquadmath.so /opt/gcc/5.3.0/snos/lib/../lib64/libstdc++.so -lm -Wl,-rpath -Wl,/opt/gcc/5.3.0/snos/lib/../lib64 -Wl,-rpath -Wl,/opt/gcc/5.3.0/snos/lib/../lib64
/usr/bin/ld: attempted static link of dynamic object `/opt/gcc/5.3.0/snos/lib/../lib64/libgfortran.so'
collect2: error: ld returned 1 exit status

So it tries to link against a dynamic library, which should fail in a static build. Apparently, there is something in addition what cray does, which is not done by spack.

**Comment by azrael417** [comment]
I think that the spack wrapper does ignore -Wl,--as-needed. This is how it tries to link:
`libtool: link: /global/u2/t/tkurth/MODULES/spack/lib/spack/env/gcc/g++ -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-omit-frame-pointer -Wl,--eh-frame-hdr -o logging_unittest src/logging_unittest-
logging_unittest.o  ./.libs/libglog.a /opt/gcc/5.3.0/snos/lib/../lib64/libgfortran.so /opt/gcc/5.3.0/snos/lib/../lib64/libquadmath.so /opt/gcc/5.3.0/snos/lib/../lib64/libstdc++.so -lpthread`
therefore, it links c++/c compiled code with libgfortran (among others). I think, that the compiler does not know how to deal with this when -static is defined, whereas it knows how to deal with libstdc++.so. This is how it should look like:
`libtool: link: ( cd ".libs" && rm -f "libglog.la" && ln -s "../libglog.la" "libglog.la" )
g++ -DHAVE_CONFIG_H -I. -I./src  -I./src  -pthread     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -g -O2 -MT src/logging_unittest-logging_unittest.o -MD -MP -MF src/.deps/logging_unittest-logging_unittest.Tpo -c -o src/logging_unittest-logging_unittest.o `test -f 'src/logging_unittest.cc' || echo './'`src/logging_unittest.cc`

**Comment by alalazo** [comment]
Is this still the case?

**Comment by alalazo** [comment]
Closing as there's been no reply in a few months.
