### ISSUE TITLE
Use Pipenv for Python package interdependencies

### ISSUE THREAD

**Issue by sethrj** [spack/spack#11279]
Use a native Python package system's dependency graph rather than Spack's for python packages.

### Rationale

Currently, all Python packages require explicitly defined `depends_on` inside of spack. For each version of a package, the dependencies (both names and versions) _should_ be identical to those specified in the `setup.py` script or `Pipfile`.  However, this is rarely the case because the dependencies change with each version of the script and it's hard to guarantee that the `package.py` is kept up to date.

Furthermore, using a native Python package manager would enable a *much* more agile Python environment, where it's easier to install and manage new packages and new versions of packages.

----

As an example of the problems with the current system: the `py-pint` package has the dependency
```python
depends_on('py-setuptools', type='build')
```
whereas it needs
```python
depends_on('py-setuptools', type=('build', 'run'))
```
The current setup results in a hard-to-debug runtime error:
```console
$ module load py-pint
$ python -c 'import pint'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/rnsdhpc/code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/py-pint-0.8.1-pp2zt23fpjleh2daxepjxoyypiv3uidc/lib/python3.7/site-packages/pint/__init__.py", line 17, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
since it's not immediately obvious *which* spack package provides `pkg_resources`. 

Other python-related issues I've encountered:
- `py-sphinx` fails at runtime because of an upstream `py-requests` library missing dependencies. 
- `py-matplotlib` fails during build because its default version is Python 3-only and that constraint wasn't mirrored in Spack's package (and even when it is, the concretization algorithm doesn't automatically select the right version when requesting `^python@2.7`)
- `py-jupyter-lab` is unavailable
- Fixing a dependency in a Spack Python package requires rebuilding, reinstalling, and regenerating modules for everything downstream, even though they're only run-time dependencies.

### Description

Python-based dependencies for packages would be treated by Spack differently from other dependencies. Instead of requiring upstream modules to load at runtime, each non-Python package would have an independent virtual environment in its install directory. Its `PYTHONPATH` would be set to that one directory during build and installation, and the Python packages' dependencies wouldn't be propagated downstream. This of course has some of the same niceties and drawbacks of `spack activate`.

### Additional information

See some discussion on https://github.com/spack/spack/issues/2065 on pip and spack.

**Comment by alalazo** [comment]
Related issue #1249 proposing a different solution

**Comment by sethrj** [comment]
Yep that's very much along the same line of thought.

**Comment by sethrj** [comment]
I'm going to close this as `wontfix`. I can't find the exact mention, but one person made the point that `pip` won't work for cases without external internet connections but the spack python packages *will* work because they can be mirrored.

**Comment by hartzell** [comment]
Just noticed this while searching for something else.

FWIW, I played with this back in PR https://github.com/spack/spack/pull/8364 (virtualenv instead of pipenv).

I'm pretty sure that it would be possible to use resources to pull down all of the pip files into the cache, stage them into something appropriate, and then point pip at them locally.
