### ISSUE TITLE
Installation issue: py-numpy with intel

### ISSUE THREAD

**Issue by HGab** [spack/spack#11289]
### Steps to reproduce the issue

```console
$ spack install py-numpy@1.16.2%intel@18.0.4 ^intel-mkl@2018.4.274%intel@18.0.4
... 
==> Error: InstallError: Cannot find a BLACS library for the given MPI.

....../spack/lib/spack/spack/build_systems/intel.py:798, in scalapack_libs:
        795            blacs_lib = 'libmkl_blacs_intelmpi'
        796        elif '^mpt' in spec_root:
        797            blacs_lib = 'libmkl_blacs_sgimpt'
  >>    798        else:
        799            raise_lib_error('Cannot find a BLACS library for the given MPI.')
        800
        801        int_suff = '_' + self.intel64_int_suffix

```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux login5.occigen 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:	Red Hat Enterprise Linux Server release 7.5 (Maipo)
``` 

### Additional information
We are on "develop" branch, the build was working correctly in "0.12.0".

This seems to fail because in libs() function from spack/lib/spack/spack/build_systems/intel.py there are the following lines:

```
if '+mkl' in self.spec or self.provides('scalapack'):
            result = self.scalapack_libs + result

```

Which will add scalapack_libs if one depend on mkl.

Or py-numpy does depend on mkl, but not on MPI, which explains why this line fails once it calls the scalapack_libs function.

**Comment by DarylGrunau** [comment]
I am hitting the same error through a slightly more convoluted path: my blas and lapack provider is intel-mkl.  My pure python code ultimately depends on py-numpy and thereby raises the same exception when I attempt to build/install.
