### ISSUE TITLE
 I tried to build mongodb, it can generate bin files, but I donot how can I copy the bin files to target?

### ISSUE THREAD

**Issue by luxianjun** [spack/spack#11296]
=> scons is already installed in /home/lxj/spack/opt/spack/linux-rhel7-aarch64/gcc-7.2.0/scons-3.0.4-covqrmskqdwvuazaslejnpby52j3jagy
==> Installing mongo
==> Searching for binary cache of mongo
==> Finding buildcaches in /mirror/build_cache
==> No binary for mongo found: installing from source
==> Using cached archive: /home/lxj/spack/var/spack/cache/mongo/mongo-4.0.6.tar.gz
==> Staging archive: /home/lxj/spack/var/spack/stage/mongo-4.0.6-fwfp4raufhtgcz3gkok4xpykbo56zzbq/r4.0.6.tar.gz
==> Created stage in /home/lxj/spack/var/spack/stage/mongo-4.0.6-fwfp4raufhtgcz3gkok4xpykbo56zzbq
==> No patches needed for mongo
==> Building mongo [SConsPackage]
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Error: InstallError: Install failed for mongo.  Nothing was installed!

/home/lxj/spack/lib/spack/spack/package.py:1774, in sanity_check_prefix:
       1771        installed.difference_update(
       1772            spack.store.layout.hidden_file_paths)
       1773        if not installed:
  >>   1774            raise InstallError(
       1775                "Install failed for %s.  Nothing was installed!" % self.name)

See build log for details:
  /home/lxj/spack/var/spack/stage/mongo-4.0.6-fwfp4raufhtgcz3gkok4xpykbo56zzbq/spack-build.out

**Comment by luxianjun** [comment]
package.py:
   # Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

# ----------------------------------------------------------------------------
# If you submit this package back to Spack as a pull request,
# please first remove this boilerplate and all FIXME comments.
#
# This is a template package file for Spack.  We've put "FIXME"
# next to all the things you'll want to change. Once you've handled
# them, you can save this file and test your package like this:
#
#     spack install mongo
#
# You can edit this file again by typing:
#
#     spack edit mongo
#
# See the Spack documentation for more information on packaging.
# ----------------------------------------------------------------------------

from spack import *


class Mongo(SConsPackage):
    """FIXME: Put a proper description of your package here."""

    # FIXME: Add a proper url for your package's homepage here.
    homepage = "http://www.example.com"
    url      = "https://github.com/mongodb/mongo/archive/r4.0.6.tar.gz"

    #version('4.1.10',     sha256='b6e0cd151f95728276a02a9b0d86a1582b1b30d5763fd6b5c0e1a0c488e7bc67')
    #version('4.0.9',      sha256='746a29345dca7538440d676412c9e0e6ae1507fa19fa59113616edfa85e501b5')
    #version('4.0.8',      sha256='22446721638cfe7e0520138b80c19d2005ded7c950c4da7fd86aa1f00a0bd108')
    #version('4.0.7',      
    sha256='cb42d440bc4a4d1b6f1fb35d36dd8c9ac6474b89ca3b47497c9eccff5e66abb5')
    version('4.0.6',      sha256='5db85f06b2a0b2ae393339a4aed1366928aaef2b46c7c32826fa87c3217dc6f7')
    version('3.6.12',     sha256='5d6e99edbea4395c5de18fead0db882cac87ee3c8eb4ad446d91c33ab91cd175')

    variant('languages',
        default='c,c++,fortran',
        values=('ada', 'brig', 'c', 'c++', 'fortran',
                'go', 'java', 'jit', 'lto', 'objc', 'obj-c++'),
        multi=True,
        description='Compilers and runtime libraries to build')

    # FIXME: Add dependencies if required.
    #depends_on('foo')

    depends_on('gcc@7.3.0', when='@4.0.6')
    depends_on('gmp@6.1.0', when='@4.0.6')
    depends_on('isl', when='@4.0.6')
    depends_on('mpc@1.0.3', when='@4.0.6')
    depends_on('mpfr@3.1.4', when='@4.0.6')

    depends_on('py-pip@8.1.2', when='@4.0.6')
    depends_on('py-pyyaml', when='@4.0.6')
    #depends_on('py-typing@3.6.1', when='@4.0.6')
    depends_on('py-typing', when='@4.0.6')
    depends_on('py-cheetah', when='@4.0.6')


    depends_on('python@2.7.16', when='@4.0.6')


    depends_on('curl')
    #depends_on('libcurl-devel')

   #def url_for_version(self, version):
   #    url = "https://github.com/mongodb/mongo/archive/r{0}.tar.gz"
   #   return url.format(version.up_to(2), version)


    def build_args(self, spec, prefix):
        # FIXME: Add arguments to pass to build.
        # FIXME: If not needed delete this functiona
        args = [
                'MONGO_VERSION=4.0.6',
                '--prefix=/opt/mongo',
                '--disable-warnings-as-errors',
                'CFLAGS="-march=armv8-a+crc -mtune=generic"',
                'CFLAGS="-march=armv8-a+crc"',
                ]
        return args

Has anyone encountered the same problem? Could anyone help me to solve it? thanks

**Comment by luxianjun** [comment]
Has anyone encountered the same problem?
from spack import *

class Mongo(SConsPackage):
"""FIXME: Put a proper description of your package here."""

# FIXME: Add a proper url for your package's homepage here.
homepage = "http://www.example.com"
url      = "https://github.com/mongodb/mongo/archive/r4.0.6.tar.gz"

#version('4.1.10',     sha256='b6e0cd151f95728276a02a9b0d86a1582b1b30d5763fd6b5c0e1a0c488e7bc67')
#version('4.0.9',      sha256='746a29345dca7538440d676412c9e0e6ae1507fa19fa59113616edfa85e501b5')
#version('4.0.8',      sha256='22446721638cfe7e0520138b80c19d2005ded7c950c4da7fd86aa1f00a0bd108')
#version('4.0.7',      
sha256='cb42d440bc4a4d1b6f1fb35d36dd8c9ac6474b89ca3b47497c9eccff5e66abb5')
version('4.0.6',      sha256='5db85f06b2a0b2ae393339a4aed1366928aaef2b46c7c32826fa87c3217dc6f7')
version('3.6.12',     sha256='5d6e99edbea4395c5de18fead0db882cac87ee3c8eb4ad446d91c33ab91cd175')

variant('languages',
    default='c,c++,fortran',
    values=('ada', 'brig', 'c', 'c++', 'fortran',
            'go', 'java', 'jit', 'lto', 'objc', 'obj-c++'),
    multi=True,
    description='Compilers and runtime libraries to build')

# FIXME: Add dependencies if required.
#depends_on('foo')

depends_on('gcc@7.3.0', when='@4.0.6')
depends_on('gmp@6.1.0', when='@4.0.6')
depends_on('isl', when='@4.0.6')
depends_on('mpc@1.0.3', when='@4.0.6')
depends_on('mpfr@3.1.4', when='@4.0.6')

depends_on('py-pip@8.1.2', when='@4.0.6')
depends_on('py-pyyaml', when='@4.0.6')
#depends_on('py-typing@3.6.1', when='@4.0.6')
depends_on('py-typing', when='@4.0.6')
depends_on('py-cheetah', when='@4.0.6')


depends_on('python@2.7.16', when='@4.0.6')


depends_on('curl')
#depends_on('libcurl-devel')
#def url_for_version(self, version):

def build_args(self, spec, prefix):
    # FIXME: Add arguments to pass to build.
    # FIXME: If not needed delete this functiona
    args = [
            'MONGO_VERSION=4.0.6',
            '--prefix=/opt/mongo',
            '--disable-warnings-as-errors',
            'CFLAGS="-march=armv8-a+crc -mtune=generic"',
            'CFLAGS="-march=armv8-a+crc"',
            ]
    return args
Has anyone encountered the same problem? Could anyone help me to solve it? thanks

**Comment by luxianjun** [comment]
it`s my package.py:

from spack import *

class Mongo(SConsPackage):
    homepage = "http://www.example.com"
    url      = "https://github.com/mongodb/mongo/archive/r4.0.6.tar.gz"

    version('4.0.6',      sha256='5db85f06b2a0b2ae393339a4aed1366928aaef2b46c7c32826fa87c3217dc6f7')
    version('3.6.12',     sha256='5d6e99edbea4395c5de18fead0db882cac87ee3c8eb4ad446d91c33ab91cd175')

    variant('languages',
        default='c,c++,fortran',
        values=('ada', 'brig', 'c', 'c++', 'fortran',
                'go', 'java', 'jit', 'lto', 'objc', 'obj-c++'),
        multi=True,
        description='Compilers and runtime libraries to build')

    depends_on('gcc@7.3.0', when='@4.0.6')
    depends_on('gmp@6.1.0', when='@4.0.6')
    depends_on('isl', when='@4.0.6')
    depends_on('mpc@1.0.3', when='@4.0.6')
    depends_on('mpfr@3.1.4', when='@4.0.6')

    depends_on('py-pip@8.1.2', when='@4.0.6')
    depends_on('py-pyyaml', when='@4.0.6')
    #depends_on('py-typing@3.6.1', when='@4.0.6')
    depends_on('py-typing', when='@4.0.6')
    depends_on('py-cheetah', when='@4.0.6')

    depends_on('python@2.7.16', when='@4.0.6')
    depends_on('curl')
    #depends_on('libcurl-devel')

   #   return url.format(version.up_to(2), version)
   def build_args(self, spec, prefix):
        # FIXME: Add arguments to pass to build.
        # FIXME: If not needed delete this functiona
        args = [
                'MONGO_VERSION=4.0.6',
                '--prefix=/opt/mongo',
                '--disable-warnings-as-errors',
                'CFLAGS="-march=armv8-a+crc -mtune=generic"',
                'CFLAGS="-march=armv8-a+crc"',
                ]
        return args

Has anyone encountered the same problem? Could anyone help me to solve it? thanks

**Comment by luxianjun** [comment]
py-typing module exited, and it has been install, bu it can not be find ,  Could anyone kown why ?

**Comment by luxianjun** [comment]
root@node2:/# spack install mongo
==> libsigsegv is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/libsigsegv-2.11-r7zq45mhrn7i7ug32hhtsepxlf4t5udp
==> m4 is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/m4-1.4.18-4ur2ba425yubm3ldgh6rdu7oxwh4ingm
==> pkgconf is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/pkgconf-1.6.0-vhukgk4lqvt6ywkbomtkr2jlqi5zh5ik
==> ncurses is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/ncurses-6.1-3fnmbrjatybf6ldwwycr4g7qrpvqavxi
==> readline is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/readline-7.0-45n7wb2guel756l6azpekig3cardrnwz
==> gdbm is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/gdbm-1.18.1-m2iq4ank4gleauov33afbwz5yogr3ngg
==> perl is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/perl-5.26.2-durhzxuft552vk2cd7i4illnqiuydcsz
==> autoconf is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/autoconf-2.69-qvdsjsffkborptmcky7bqc5h6wvogfmd
==> automake is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/automake-1.16.1-g4dht3sb2ifsmp4pyxx5hskn5g5utalb
==> libtool is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/libtool-2.4.6-xxtgv3falddwsyipbyl4cibxcpw73ihe
==> gmp is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/gmp-6.1.0-tanojcaiufufbrrcgewkh2qps53qxu5y
==> isl is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/isl-0.16.1-gwnsvb3useki6gwa5nno2cqrqf2pfqgk
==> mpfr is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/mpfr-3.1.4-ug6ntk3wblsne6tzpagxytayqxfuv6i7
==> mpc is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/mpc-1.0.3-lekx7nhu4p6vrpolnc554lr2wxi3367t
==> zlib is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/zlib-1.2.11-fezrv2gsmbj4ojbhbvhtmupsg6y5lnrq
==> gcc is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/gcc-7.3.0-c4sek5slamdnjfj7cd5z24bccc7yz3sy
==> diffutils is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/diffutils-3.7-273jc2s7gylk4ndudqgnpj5efqycm34o
==> bzip2 is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/bzip2-1.0.6-wx7wtwzoczly7v5ijrpmenbpfbupdsqb
==> libbsd is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/libbsd-0.9.1-e3dhr4usugw73slmosd3rdt3rhmhvmnn
==> expat is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/expat-2.2.5-tphelsglls33ooztflcqngyq32bi4rh5
==> libffi is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/libffi-3.2.1-q47evhaio2mos65cqi527v4a36tpbjoy
==> openssl is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/openssl-1.1.1b-vctymoe4smbbiohpjbk6kvq6pxo5bxja
==> sqlite is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/sqlite-3.26.0-o4zvhqvbuos6ul7lgiiwq3pfbac2eeev
==> python is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/python-2.7.16-mi7vlcvg7kkeoyobk2uiii4d5pb4jwpc
==> py-cheetah is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/py-cheetah-2.3.0-v4ilgjh6hgm3ie4s7e7oiuhny4l4xmac
==> py-pyyaml is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/py-pyyaml-5.1-kakon5uupvcisgwpghcidbtvg7gkf7cd
==> py-typing is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/py-typing-3.6.1-e5tgn4lltvs56l5kgttctmngsdx47qbh
==> py-setuptools is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/py-setuptools-40.8.0-x4frekuod7j7u7k3yqnwxxm35qojmk5x
==> scons is already installed in /home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/scons-3.0.4-mqnoyiw3ai2c4zxmzqzkeidvdqkyow55
==> Installing mongo
==> Searching for binary cache of mongo
==> Warning: No Spack mirrors are currently configured
==> No binary for mongo found: installing from source
==> Using cached archive: /home/lxj/spack_prj/var/spack/cache/mongo/mongo-4.0.6.tar.gz
==> Staging archive: /home/lxj/spack_prj/var/spack/stage/mongo-4.0.6-2hbnfenibyjxvpkwbkecpzwp7f2vr6x3/r4.0.6.tar.gz
==> Created stage in /home/lxj/spack_prj/var/spack/stage/mongo-4.0.6-2hbnfenibyjxvpkwbkecpzwp7f2vr6x3
==> No patches needed for mongo
==> Building mongo [SConsPackage]
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'scons' '-j64' 'MONGO_VERSION=4.0.6' '--prefix=/opt/mongo' '--disable-warnings-as-errors' 'CFLAGS="-march=armv8-a+crc -mtune=generic"' 'CFLAGS="-march=armv8-a+crc"'
See build log for details:
  /home/lxj/spack_prj/var/spack/stage/mongo-4.0.6-2hbnfenibyjxvpkwbkecpzwp7f2vr6x3/spack-build.out

**Comment by luxianjun** [comment]
root@node2:/home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/py-pyyaml-5.1-kakon5uupvcisgwpghcidbtvg7gkf7cd/lib/python2.7/site-packages/yaml# ls
__init__.py   composer.pyc     dumper.py   emitter.pyc  events.py   loader.pyc  parser.py   reader.pyc       resolver.py   scanner.pyc     tokens.py   yaml.pyc
__init__.pyc  constructor.py   dumper.pyc  error.py     events.pyc  nodes.py    parser.pyc  representer.py   resolver.pyc  serializer.py   tokens.pyc
composer.py   constructor.pyc  emitter.py  error.pyc    loader.py   nodes.pyc   reader.py   representer.pyc  scanner.py    serializer.pyc  yaml.py

I think the 'yaml' module already exists, but spack can't find it.

**Comment by luxianjun** [comment]
/home/lxj/spack_prj/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.3.0/python-2.7.16-mi7vlcvg7kkeoyobk2uiii4d5pb4jwpc/bin/python src/mongo/db/auth/generate_action_types.py src/mongo/db/auth/action_types.txt build/opt/mongo/db/auth/action_type.h build/opt/mongo/db/auth/action_type.cpp
Traceback (most recent call last):
  File "buildscripts/idl/idlc.py", line 38, in <module>
    import idl.compiler
  File "/tmp/root/spack-stage/spack-stage-ZypgnL/mongo-r4.0.6/buildscripts/idl/idl/compiler.py", line 42, in <module>
    from . import binder
  File "/tmp/root/spack-stage/spack-stage-ZypgnL/mongo-r4.0.6/buildscripts/idl/idl/binder.py", line 36, in <module>
    from . import ast
  File "/tmp/root/spack-stage/spack-stage-ZypgnL/mongo-r4.0.6/buildscripts/idl/idl/ast.py", line 42, in <module>
    from . import errors
  File "/tmp/root/spack-stage/spack-stage-ZypgnL/mongo-r4.0.6/buildscripts/idl/idl/errors.py", line 41, in <module>
    from yaml import nodes
### **ImportError: No module named yaml**
Traceback (most recent call last):
  File "buildscripts/idl/idlc.py", line 38, in <module>
    import idl.compiler
  File "/tmp/root/spack-stage/spack-stage-ZypgnL/mongo-r4.0.6/buildscripts/idl/idl/compiler.py", line 42, in <module>
    from . import binder
  File "/tmp/root/spack-stage/spack-stage-ZypgnL/mongo-r4.0.6/buildscripts/idl/idl/binder.py", line 36, in <module>
    from . import ast
  File "/tmp/root/spack-stage/spack-stage-ZypgnL/mongo-r4.0.6/buildscripts/idl/idl/ast.py", line 42, in <module>
    from . import errors
  File "/tmp/root/spack-stage/spack-stage-ZypgnL/mongo-r4.0.6/buildscripts/idl/idl/errors.py", line 41, in <module>
    from yaml import nodes
### **ImportError: No module named yaml**

**Comment by luxianjun** [comment]
my package.py
from spack import *

class Mongo(SConsPackage):
    """FIXME: Put a proper description of your package here."""

    # FIXME: Add a proper url for your package's homepage here.
    homepage = "https://github.com/mongodb/mongo"
    url      = "https://github.com/mongodb/mongo/archive/r4.0.6.tar.gz"

    version('4.0.6',      sha256='5db85f06b2a0b2ae393339a4aed1366928aaef2b46c7c32826fa87c3217dc6f7')
    version('3.6.12',     sha256='5d6e99edbea4395c5de18fead0db882cac87ee3c8eb4ad446d91c33ab91cd175')

    variant('languages',
        default='c,c++,fortran',
        values=('ada', 'brig', 'c', 'c++', 'fortran',
                'go', 'java', 'jit', 'lto', 'objc', 'obj-c++'),
        multi=True,
        description='Compilers and runtime libraries to build')

    # FIXME: Add dependencies if required.
    depends_on('gmp@6.1.0', when='@4.0.6')
    depends_on('isl@0.16.1', when='@4.0.6')
    depends_on('mpc@1.0.3', when='@4.0.6')
    depends_on('mpfr@3.1.4', when='@4.0.6')
    depends_on('gcc@7.3.0', when='@4.0.6')

    depends_on('py-pyyaml', when='@4.0.6:', type=('build', 'run'))
    depends_on('py-typing@3.6.1', when='@4.0.6:', type=('build', 'run'))
    depends_on('py-cheetah', when='@4.0.6:' , type=('build','run'))

    depends_on('python@2.7.16', when='@4.0.6')

    #depends_on('py-pip')

    #depends_on('curl')
    #depends_on('libcurl-dev')

    def build_args(self, spec, prefix):
        args = [
                'MONGO_VERSION=4.0.6',
                '--prefix=/opt/mongo',
                '--disable-warnings-as-errors',
                'CFLAGS="-march=armv8-a+crc -mtune=generic"',
                'CFLAGS="-march=armv8-a+crc"',
                ]
        return args

**Comment by luxianjun** [comment]
Because the mongo depends on the 'yaml' need operation 'python setup.py install'. So at the same time I modify the py-pyyaml.py, But no effect.

from spack import *


class PyPyyaml(PythonPackage):
    """FIXME: Put a proper description of your package here."""

    # FIXME: Add a proper url for your package's homepage here.
    homepage = "http://pyyaml.org/wiki/PyYAML"
    url      ="http://pyyaml.org/download/pyyaml/PyYAML-3.11.tar.gz"

    import_modules = ['yaml']

    version('5.1',  sha256='436bc774ecf7c103814098159fbb84c2715d25980175292c648f2da143909f95')
    version('3.13', sha256='3ef3092145e9b70e3ddd2c7ad59bdd0252a94dfe3949721633e41344de00a6bf')
    version('3.12', sha256='592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab')
    version('3.11', sha256='c36c938a872e5ff494938b33b14aaa156cb439ec67548fcab3535bb78b0846e8')
    version('3.10', sha256='e713da45c96ca53a3a8b48140d4120374db622df16ab71759c9ceb5b8d46fe7c')
    version('3.09', sha256='30076d51387cca35d461c8b36408de189d31f17e44d45cd2200bbd2d02f555c1')
    version('3.08', sha256='24b08038259c81e2c349a5601a5682b7e4e5167d1db7af576cf2b32c6b59412f')
    version('3.07', sha256='c9d1aee39968b4d1b397d18d3f1307e58b968df28cbf045d0b2097a93ade80cb')
    version('3.06', sha256='8fdc65554131bef72265afa0781f61dcced0066b9fb4eddc22364d0bc68017e9')
    version('3.05', sha256='27b69bf6f1452e8f41577646ddfe78f9528a437409927d5d543bc97d75e27a03')

    # FIXME: Add dependencies if required.
    # depends_on('py-setuptools', type='build')
    # depends_on('py-foo',        type=('build', 'run'))

    def install(self, spec, prefix):
        python = which('python')
        python('setup.py', 'install', '--prefix={0}'.format(prefix))

Could anyone help me how to solve it? Thanks!

**Comment by luxianjun** [comment]
the bin files:

[root@master /]# find -name mongo
./home/lxj/spack/var/spack/repos/builtin/packages/mongo
./home/lxj/spack/var/spack/cache/mongo
find: ‘./proc/58199’: No such file or directory
./tmp/root/spack-stage/spack-stage-hoj7x2/mongo-r4.0.6/site_scons/mongo
./tmp/root/spack-stage/spack-stage-hoj7x2/mongo-r4.0.6/src/mongo
./tmp/root/spack-stage/spack-stage-hoj7x2/mongo-r4.0.6/build/opt/mongo
./tmp/root/spack-stage/spack-stage-yUanW_/mongo-r4.0.6/site_scons/mongo
./tmp/root/spack-stage/spack-stage-yUanW_/mongo-r4.0.6/src/mongo
./tmp/root/spack-stage/spack-stage-yUanW_/mongo-r4.0.6/build/opt/mongo
./tmp/root/spack-stage/spack-stage-yUanW_/mongo-r4.0.6/build/opt/mongo/mongo
./tmp/root/spack-stage/spack-stage-yUanW_/mongo-r4.0.6/build/install/bin/mongo
./usr/local/mongo
./usr/local/mongo/site_scons/mongo
./usr/local/mongo/src/mongo
./usr/local/mongo/src/third_party/mozjs-60/mongo_sources/mongo
./usr/local/ltp/testcases/kernel/fs/mongo
[root@master /]# cd ./tmp/root/spack-stage/spack-stage-yUanW_/mongo-r4.0.6/build/install/bin/mongo
-bash: cd: ./tmp/root/spack-stage/spack-stage-yUanW_/mongo-r4.0.6/build/install/bin/mongo: Not a directory
[root@master /]# cd ./tmp/root/spack-stage/spack-stage-yUanW_/mongo-r4.0.6/build/install/bin/
[root@master bin]# ls -l
total 1943320
-rwxr-xr-x 1 root root       5792 4月  29 20:39 install_compass
-rwxr-xr-x 1 root root  372179368 4月  29 20:40 mongo
-rwxr-xr-x 1 root root 1079187320 4月  29 20:40 mongod
-rwxr-xr-x 1 root root  538577808 4月  29 20:40 mongos

**Comment by luxianjun** [comment]
my package.py is :
class Mongo(SConsPackage):
    """FIXME: Put a proper description of your package here."""

    # FIXME: Add a proper url for your package's homepage here.
    homepage = "https://github.com/mongodb/mongo"
    url      = "https://github.com/mongodb/mongo/archive/r4.0.6.tar.gz"

    #version('4.1.10',     sha256='b6e0cd151f95728276a02a9b0d86a1582b1b30d5763fd6b5c0e1a0c488e7bc67')
    #version('4.0.9',      sha256='746a29345dca7538440d676412c9e0e6ae1507fa19fa59113616edfa85e501b5')
    #version('4.0.8',      sha256='22446721638cfe7e0520138b80c19d2005ded7c950c4da7fd86aa1f00a0bd108')
    #version('4.0.7',      sha256='cb42d440bc4a4d1b6f1fb35d36dd8c9ac6474b89ca3b47497c9eccff5e66abb5')
    version('4.0.6',      sha256='5db85f06b2a0b2ae393339a4aed1366928aaef2b46c7c32826fa87c3217dc6f7')
    version('3.6.12',     sha256='5d6e99edbea4395c5de18fead0db882cac87ee3c8eb4ad446d91c33ab91cd175')

    variant('languages',
        default='c,c++,fortran',
        values=('ada', 'brig', 'c', 'c++', 'fortran',
                'go', 'java', 'jit', 'lto', 'objc', 'obj-c++'),
        multi=True,
        description='Compilers and runtime libraries to build')

    # FIXME: Add dependencies if required.

    depends_on('gmp@6.1.0', when='@4.0.6')
    depends_on('isl@0.16.1', when='@4.0.6')
    depends_on('mpc@1.0.3', when='@4.0.6')
    depends_on('mpfr@3.1.4', when='@4.0.6')
    depends_on('gcc@7.3.0', when='@4.0.6')

    depends_on('py-pyyaml', when='@4.0.6:', type=('build', 'run'))
    depends_on('py-typing', when='@4.0.6:', type=('build', 'run'))
    depends_on('py-cheetah', when='@4.0.6:' , type=('build','run'))

    depends_on('python@2.7.16', when='@4.0.6')

    def build_args(self, spec, prefix):
        # FIXME: Add arguments to pass to build.
        # FIXME: If not needed delete this functiona
        args = [
                'MONGO_VERSION=4.0.6',
                '--prefix=/opt/mongo',
                '--disable-warnings-as-errors',
                'CFLAGS="-march=armv8-a+crc -mtune=generic"',
                'CFLAGS="-march=armv8-a+crc"',
                ]
        return args

    def install_args(self, spec, prefix):
        args = [
                'MONGO_VERSION=4.0.6',
                '--disable-warnings-as-errors',
                'CCFLAGS="-march=armv8-a+crc"'
               ]
        return args

**Comment by luxianjun** [comment]
Could anyone help me to solve it? Thanks!

**Comment by scheibelp** [comment]
Hi @luxianjun 

Your package definition specifies `--prefix=/opt/mongo` in the `install_args` function. Spack complains (`Error: InstallError: Install failed for mongo. Nothing was installed!`) because it expects the package to be installed to the prefix that it chooses. Specifically, it expects that the package is installed to the location supplied by the `prefix` argument that is passed into the `install_args` function.

Would it be possible to try setting `'--prefix={0}'.format(prefix)'` instead?

**Comment by luxianjun** [comment]
@scheibelp   I modified it after using the method you said then it made it better. thanks very much!

    def build_args(self, spec, prefix):
        # FIXME: Add arguments to pass to build.
        # FIXME: If not needed delete this functiona
        args = [
               'MONGO_VERSION=4.0.6',
               '--disable-warnings-as-errors',
               'CFLAGS="-march=armv8-a+crc -mtune=generic"',
               'CFLAGS="-march=armv8-a+crc"',
               ]
        return args

    def install_args(self, spec, prefix):
        args = [
                '--prefix={0}'.format(prefix),
                'MONGO_VERSION=4.0.6',
                '--disable-warnings-as-errors',
                'CCFLAGS="-march=armv8-a+crc"'
               ]
        return args

**Comment by scheibelp** [comment]
Glad to hear it - you're welcome!
