### ISSUE TITLE
Install issue: quantum-espresso+epw

### ISSUE THREAD

**Issue by difey** [spack/spack#11298]
### Steps to reproduce the issue

```console
$ spack install quantum-espresso +epw %gcc@5.4.0 ^openmpi+pmi fabrics=verbs schedulers=slurm
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux mu07.pi.sjtu.edu.cn 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	CentOS Linux release 7.5.1804 (Core)
``` 

### Additional information

spec output:
```console
$ spack spec quantum-espresso +epw %gcc@5.4.0 ^openmpi+pmi fabrics=verbs
Input spec
--------------------------------
quantum-espresso%gcc@5.4.0+epw
    ^openmpi fabrics=verbs +pmi

Concretized
--------------------------------
quantum-espresso@6.3%gcc@5.4.0~elpa+epw hdf5=none +mpi~openmp patches=b776890d008e16cca28c31299c62f47de0ba606b900b17cbc27c041f45e564ca,bc8c5b8523156cee002d97dab42a5976dffae20605da485a427b902a236d7e6b +scalapack arch=linux-centos7-x86_64
    ^fftw@3.3.8%gcc@5.4.0+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2 arch=linux-centos7-x86_64
        ^openmpi@3.1.4%gcc@5.4.0~cuda+cxx_exceptions fabrics=verbs ~java~legacylaunchers~memchecker+pmi schedulers=auto ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64
            ^hwloc@1.11.11%gcc@5.4.0~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-x86_64
                ^libpciaccess@0.13.5%gcc@5.4.0 arch=linux-centos7-x86_64
                    ^libtool@2.4.2%gcc@5.4.0 arch=linux-centos7-x86_64
                    ^pkgconf@1.6.0%gcc@5.4.0 arch=linux-centos7-x86_64
                    ^util-macros@1.19.1%gcc@5.4.0 arch=linux-centos7-x86_64
                ^libxml2@2.9.8%gcc@5.4.0~python arch=linux-centos7-x86_64
                    ^libiconv@1.15%gcc@5.4.0 arch=linux-centos7-x86_64
                    ^xz@5.2.4%gcc@5.4.0 arch=linux-centos7-x86_64
                    ^zlib@1.2.11%gcc@5.4.0+optimize+pic+shared arch=linux-centos7-x86_64
                ^numactl@2.0.12%gcc@5.4.0 arch=linux-centos7-x86_64
                    ^autoconf@2.69%gcc@5.4.0 arch=linux-centos7-x86_64
                    ^automake@1.13.4%gcc@5.4.0 arch=linux-centos7-x86_64
                    ^m4@1.4.16%gcc@5.4.0 patches=c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e +sigsegv arch=linux-centos7-x86_64
    ^netlib-scalapack@2.0.2%gcc@5.4.0 build_type=RelWithDebInfo patches=22ebf4e3d5a6356cd6086ea65bfdf30f9d0a2038136127590cd269d15bdb03af,e8f30dd1f26e523dfb552f8d7b8ad26ac88fc0c8d72e3d4f9a9717a3383e0b33 ~pic+shared arch=linux-centos7-x86_64
        ^cmake@2.8.12.2%gcc@5.4.0~doc+ncurses+openssl~ownlibs~qt arch=linux-centos7-x86_64
        ^openblas@0.3.5%gcc@5.4.0 cpu_target=auto ~ilp64+pic+shared threads=none ~virtual_machine arch=linux-centos7-x86_64
```

The version without epw works fine.
```console
$ spack install quantum-espresso +epw %gcc@5.4.0 ^openmpi+pmi fabrics=verbs schedulers=slurm
```

The error log is below: 
```console
==> Error: ProcessError: Command exited with status 2:
    'make' 'all' 'epw'

7 errors found in build log:
     5275    
     5276    gzip: ../archive/wannier90-2.1.0.tar.gz: not in gzip format
     5277    tar: This does not look like a tar archive
     5278    tar: Exiting with failure status due to previous errors
     5279    *** Unable to download http://www.wannier.org/code/wannier90-2.1.0.tar.gz.
     5280    *** Verify that the url is correct.
  >> 5281    make[4]: *** [uncompress-w90] Error 1
     5282    make[4]: Leaving directory `/lustre/home/acct-hpc/hpcwj/spack/var/spack/stage/quantum-espresso-6.3-cuuc5qjzzer2slen7s4d6vrapaw3
             7t26/q-e-qe-6.3/install'
  >> 5283    make[3]: *** [w90] Error 1
     5284    make[3]: Leaving directory `/lustre/home/acct-hpc/hpcwj/spack/var/spack/stage/quantum-espresso-6.3-cuuc5qjzzer2slen7s4d6vrapaw3
             7t26/q-e-qe-6.3'
  >> 5285    /bin/sh: line 0: cd: wannier90-2.1.0/: No such file or directory
     5286    make[3]: Entering directory `/lustre/home/acct-hpc/hpcwj/spack/var/spack/stage/quantum-espresso-6.3-cuuc5qjzzer2slen7s4d6vrapaw
             37t26/q-e-qe-6.3'
  >> 5287    make[3]: *** No rule to make target `lib'.  Stop.
     5288    make[3]: Leaving directory `/lustre/home/acct-hpc/hpcwj/spack/var/spack/stage/quantum-espresso-6.3-cuuc5qjzzer2slen7s4d6vrapaw3
             7t26/q-e-qe-6.3'
  >> 5289    make[2]: *** [wannier] Error 2
     5290    make[2]: Leaving directory `/lustre/home/acct-hpc/hpcwj/spack/var/spack/stage/quantum-espresso-6.3-cuuc5qjzzer2slen7s4d6vrapaw3
             7t26/q-e-qe-6.3/EPW/src'
  >> 5291    make[1]: *** [epw] Error 2
     5292    make[1]: Leaving directory `/lustre/home/acct-hpc/hpcwj/spack/var/spack/stage/quantum-espresso-6.3-cuuc5qjzzer2slen7s4d6vrapaw3
             7t26/q-e-qe-6.3/EPW'
  >> 5293    make: *** [epw] Error 1

```

**Comment by flxmr** [comment]
the QE-build-process want's to download wannier90, but won't find it. As http://www.wannier.org/code/wannier90-2.1.0.tar.gz works fine for me, I guess it's just an issue of your governments "internet". One should probably add the tag "cn-firewall-error"

**Comment by difey** [comment]
@flxmr Actually I have found wannier90 in the archive directory.  The error seems like gzip can not decompress the  wannier90-2.1.0.tar.gz. I have tried to decompress the file, but failed.
```console
$ gzip -d wannier90-2.1.0.tar.gz 
gzip: wannier90-2.1.0.tar.gz: not in gzip format
```
 Any idea to fix that?

**Comment by flxmr** [comment]
This is a problem of QE, which expects a gzipped-tar, when the source apparently only yields a plain tar. You should rewrite the portion of the Makefile/install.sh of QE, then produce a patch and add it to the package.py "patch("patchname", when='@5.4.0 +epw')"  https://github.com/QEF/q-e/blob/7d5cebcf1250114756b88c6064ebe82e6f8fd835/install/install_utils

**Comment by difey** [comment]
6.4 works. The reason is wannier90 package is bad.

Thanks

`$ spack install quantum-espresso@6.4 +epw %gcc@5.4.0 ^openmpi+pmi fabrics=verbs schedulers=slurm`

**Comment by shunido** [comment]
Hello
does anyone know how to install it usuing slack and scheduler is pbs pro ? 
I was able to install it without specifying shcedulers but after runnig it shows this : 

 Program PWSCF v.7.1 starts on  5Jan2023 at 23: 8:10

     This program is part of the open-source Quantum ESPRESSO suite
     for quantum simulation of materials; please cite
         "P. Giannozzi et al., J. Phys.:Condens. Matter 21 395502 (2009);
         "P. Giannozzi et al., J. Phys.:Condens. Matter 29 465901 (2017);
         "P. Giannozzi et al., J. Chem. Phys. 152 154105 (2020);
          URL http://www.quantum-espresso.org",
     in publications or presentations arising from this work. More details at
     http://www.quantum-espresso.org/quote

     Parallel version (MPI & OpenMP), running on       4 processor cores
     Number of MPI processes:                 2
     Threads/MPI process:                     2

     MPI processes distributed on     1 nodes
     250230 MiB available memory on the printing compute node when the environment starts

     Waiting for input...
     Reading input from standard input

     Current dimensions of program PWSCF are:
     Max number of different atomic species (ntypx) = 10
     Max number of k-points (npk) =  40000
     Max angular momentum in pseudopotentials (lmaxx) =  4

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine readpp (1):
     file ./Ge.pbe-n-kjpaw_psl.1.0.0.UPF not found
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

     stopping ...

**Comment by Jila66** [comment]
Hi
You must download the UPF file and put it the pseudo loacation.
