### ISSUE TITLE
Installation sucessful but spack install result in InstallError: exception

### ISSUE THREAD

**Issue by vkallesh** [spack/spack#11308]
### Summary
I ran spack install, below observations were seen:

1) spack install is not installing to default location of spack/opt path (when make('install') entry under package.py) instead failing with permission error while installing /usr/ path  - Which is not not right

2) If install prefix option is given then Installation sucessful but spack install output result in InstallError: exception

Note: I passed local mirror code path as input for spack create command

Expected Result
install package under spack/opt/... directory

Actual Result
==> Error: InstallError: Install failed for blis.  Nothing was installed!

/home/spack_user/GP/spack/lib/spack/spack/package.py:1774, in sanity_check_prefix:
       1771        installed.difference_update(
       1772            spack.store.layout.hidden_file_paths)
       1773        if not installed:
  >>   1774            raise InstallError(
       1775                "Install failed for %s.  Nothing was installed!" % self.name)

### Steps to reproduce the issue

```console
$ spack create -t generic -f file:///home/amd/spack-mirror-2019-04-21/blis/blis_0.5.2.tar.gz

$ spack install blis@0.5.2 %gcc@7.3.0
...
```

### Error Message

If Spack reported an error, provide the error message. If it did not report an error
but the output appears incorrect, provide the incorrect output. If there was no error
message and no output but the result is incorrect, describe how it does not match
what you expect. To provide more information you might re-run the commands with 
the additional -d/--stacktrace flags:
```console
$ spack -d --stacktrace install blis@0.5.2 %gcc@7.3.0

lib/spack/spack/package.py:1534 ==> [2019-04-26-19:08:11.565849] Executing phase: 'install'
lib/spack/llnl/util/lock.py:334 ==> [2019-04-26-19:08:21.988505] WRITE LOCK: /home/spack_user/GP/spack/opt/spack/.spack-db/prefix_lock[2403057116419638959:1] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-04-26-19:08:21.988762] WRITE LOCK: /home/spack_user/GP/spack/var/spack/stage/.lock[3669865094975467777:1] [Released]
lib/spack/spack/error.py:55 ==> [2019-04-26-19:08:21.990850] Error: InstallError: Install failed for blis.  Nothing was installed!

/home/spack_user/GP/spack/lib/spack/spack/package.py:1774, in sanity_check_prefix:
       1771        installed.difference_update(
       1772            spack.store.layout.hidden_file_paths)
       1773        if not installed:
  >>   1774            raise InstallError(
       1775                "Install failed for %s.  Nothing was installed!" % self.name)

See build log for details:
  /home/spack_user/GP/spack/var/spack/stage/blis-0.5.2-ikzl63sokwgv7jkzwrakhqauyuznh267/spack-build.out
Traceback (most recent call last):
  File "/home/spack_user/GP/spack/lib/spack/spack/build_environment.py", line 767, in child_process
    return_value = function()
  File "/home/spack_user/GP/spack/lib/spack/spack/package.py", line 1539, in build_process
    phase(self.spec, self.prefix)
  File "/home/spack_user/GP/spack/lib/spack/spack/package.py", line 106, in phase_wrapper
    callback(instance)
  File "/home/spack_user/GP/spack/lib/spack/spack/package.py", line 1775, in sanity_check_prefix
    "Install failed for %s.  Nothing was installed!" % self.name)
InstallError: Install failed for blis.  Nothing was installed!

...
```
that activate the full debug output. 

### Information on your system

This includes:

 1. which platform you are using
spack_user@trukvm23p10:~$ uname -a
Linux trukvm23p10 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
spack_user@trukvm23p10:~$

 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)
Source code path: https://github.com/amd/blis

package.py contents:
from spack import *

class Blis(Package):
    """blis package"""

    # FIXME: Add a proper url for your package's homepage here.
    homepage = "http://www.example.com"
    url      = "file:///home/spack_user/spack_mirror/blis/blis_0.5.2.tar.gz"

    version('0.5.2', sha256='a796642c355271a1f03493adf1aa71a0e7111214f5d861488b6afa6cae64d72c')

    # FIXME: Add dependencies if required.
    # depends_on('foo')

    def install(self, spec, prefix):
        # FIXME: Unknown build system
        configure('--prefix=/home/spack_user/GP/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/blis-0.5.2-a796642c355271a1f03493adf1aa71a0e7111214f5d861488b6afa6cae64d72c','CFLAGS=-Wno-error=maybe-uninitialized', ' auto')
        make()
        make('install')

-----

We encourage you to try, as much as possible, to reduce your problem to the minimal example that still reproduces the issue. That would help us a lot in fixing it quickly and effectively!

If you want to ask a question about the tool (how to use it, what it can currently do, etc.), try the `#general` channel on our Slack first. We have a welcoming community and chances are you'll get your reply faster and without opening an issue.

Other than that, thanks for taking the time to contribute to Spack!

**Comment by citibeth** [comment]
Looks like you had Spack auto-create a package and then tried to install immediately.  That could fail for any number of reasons.  The most common reason would be missing dependencies; but BLIS doesn't seem to have any.  In any case, there's something wrong going on inside the BLIS build.

You should find the `spack_build.out` file, rename it to `.txt` and post it here; that should contain important clues.

You might also review BLIS build instructions, make sure the Spack recipe is doing the same thing, even try installing it manually (in a sample location):
https://github.com/flame/blis/blob/master/docs/BuildSystem.md

**Comment by scheibelp** [comment]
`configure('--prefix=/home/spack_user/GP/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/blis-0.5.2-a796642c355271a1f03493adf1aa71a0e7111214f5d861488b6afa6cae64d72c','CFLAGS=-Wno-error=maybe-uninitialized', ' auto')`

Did Spack generate that? I could see this being the source of the error, you'll generally always want this line to set `--prefix` to the Spack-chosen prefix:

`configure('--prefix={0}'.format(prefix), 'CFLAGS=...')`

**Comment by alalazo** [comment]
Closing as stale (no answer given to https://github.com/spack/spack/issues/11308#issuecomment-513412865) Feel free to open a new issue if the problem still occurs.
