### ISSUE TITLE
Infinite recursion when installing from binary cache

### ISSUE THREAD

**Issue by alalazo** [spack/spack#11341]
If I add a binary mirror with the `patchelf` executable packaged as a binary Spack enters an infinite recursion when trying to install specs - I assume `patchelf` needs `patchelf` to relocate itself. Must be on a system with no available `patchelf`.

### Steps to reproduce the issue

```console
$ # Create a trusted signature
$ spack gpg create --export public.key <Your name> <Your e-mail>
$ spack gpg trust public.key

$ # Create the relevant binary packages
$ spack install zlib
$ spack install patchelf
$ mkdir mirror
$ spack buildcache create -d $(pwd)/mirror zlib
$ spack buildcache create -d $(pwd)/mirror patchelf

$ # Reinstall specs from binary packages
$ spack mirror add bugrepo $(pwd)/mirror
$ spack uninstall -ay
$ spack install zlib
```

### Error Message

```console
$ spack install zlib
==> Installing zlib
==> Searching for binary cache of zlib
==> Finding buildcaches in /mirror/build_cache
==> Finding buildcaches in /home/mculpo/tmp/cscs-software-management/mirror/build_cache
==> Installing zlib from binary cache
==> Already downloaded /home/mculpo/tmp/cscs-software-management/spack/var/spack/stage/build_cache/linux-ubuntu18.04-x86_64-gcc-8.2.0-zlib-1.2.11-ivqu252fvh7r5iar6zwx4fmeoxiykln7.spack
==> Relocating package from
  /home/mculpo/tmp/cscs-software-management/spack/opt/spack to /home/mculpo/tmp/cscs-software-management/spack/opt/spack.
==> Installing patchelf
==> Searching for binary cache of patchelf
[...]
==> Installing patchelf
==> Searching for binary cache of patchelf
==> Installing patchelf from binary cache
==> Already downloaded /home/mculpo/tmp/cscs-software-management/spack/var/spack/stage/build_cache/linux-ubuntu18.04-x86_64-gcc-8.2.0-patchelf-0.9-5ux5vemei3v356shntc5ipq73joriolw.spack
gpg: Signature made gio 02 mag 2019 08:40:34 CEST
gpg:                using RSA key A361C8BC7A344C7E281C41BA957053A1C033DBA0
gpg: Good signature from "Massimiliano Culpo (Key used to sign packages for the Software Management Course) <massimiliano.culpo@epfl.ch>" [ultimate]
==> Relocating package from
  /home/mculpo/tmp/cscs-software-management/spack/opt/spack to /home/mculpo/tmp/cscs-software-management/spack/opt/spack.
==> Error: maximum recursion depth exceeded while calling a Python object
```

### Information on your system

The only relevant information is that the system must not have a `patchelf` executable available.

**Comment by gartung** [comment]
Is this the head of develop?

**Comment by gartung** [comment]
Patchelf was never intended to be installed from cache.

**Comment by alalazo** [comment]
> Patchelf was never intended to be installed from cache.

@gartung I know, but we should enforce that *if* Spack builds it it will build it from source. It's 2a1ba0e1420e10037903e3cfd4c8344b40761670 so pretty much head of develop.

**Comment by gartung** [comment]
Proposed temporary fix is here
https://github.com/spack/spack/pull/11343
Long term there should be a way to skip if the spec name is patchelf.

**Comment by alalazo** [comment]
@gartung Is it worth resurrecting #7237 (have a way to say that we can't create binary packages for something) or is it an overshoot in your opinion?

**Comment by gartung** [comment]
@alalazo Did you ever come up with an implementation? I may need to work on a few things with buildcache. I need to add the headerpad max flag to the compile flags for macOS so that the current buildaches on the S3 mirror can be relocated.

**Comment by gartung** [comment]
@tgamblin, I need to fix a few things with buildcache. I need to add the headerpad max flag to the compile flags for macOS so that the current buildaches on the S3 mirror can be relocated.

**Comment by alalazo** [comment]
@gartung No, it was closed on the assumption that it was not necessary as we could automate the logic? Trying to reconstruct the discussion, see https://github.com/spack/spack/issues/7237#issuecomment-371013762 . 

If having a simple marker at the package level that basically says "always build this package from sources" is considered useful I can work on that after mid May. Let me know.

**Comment by gartung** [comment]
@alalazo Adding the simple marker would be great. I could then filter on the marker when creating buildcaches.

**Comment by gartung** [comment]
The infinite recursion should be fixed by https://github.com/spack/spack/pull/11343

**Comment by alalazo** [comment]
@gartung Thanks!
