### ISSUE TITLE
Installation issue: paraview with osmesa and python

### ISSUE THREAD

**Issue by DarylGrunau** [spack/spack#11398]
### Steps to reproduce the issue

```console
$ spack install paraview+osmesa+python
==> Error: An unsatisfiable version constraint has been detected for spec:

    python@2.7:2.8
        ^pkgconfig@0.9.0:


while trying to concretize the partial spec:

    mesa+osmesa
        ^expat
        ^py-mako@0.8.0:
            ^py-markupsafe@0.9.2:
                ^py-setuptools
                    ^python@2.7:2.8
                        ^pkgconfig@0.9.0:


mesa requires python version 3:, but spec asked for 2.7:2.8
```

### Platform and user environment

```commandline
$ uname -a 
Linux vc-fey.localdomain 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.6.1810 (Core)
``` 

### Additional information
This install conflict was introduced by commit 9f848205e431c

**Comment by jrood-nrel** [comment]
I'm seeing some problems due to this meson stuff as well. Also seemingly related to this, `gtkplus` seems to have needlessly been added to some things, which depends on `libepoxy` which then depends on `llvm` of all things. So if I try to install `image-magick`, it builds many unnecessary dependencies. I'm going to install Paraview today with the latest Spack, so I expect to have problems and I will report them.

**Comment by jrood-nrel** [comment]
One more note, I think this is due to the preferred version of Python still 2.7.16, so `spack install paraview+osmesa+python ^python@3.7.3` might fix the concretization.

**Comment by DarylGrunau** [comment]
In fact Paraview seems to dislike python@3.7.3 - I'm getting further with python@3.6.8 ...

**Comment by jrood-nrel** [comment]
Oh no, I'm currently trying to build it with python 3.7.3. I removed all the Python 2 constraints in the Paraview package to test it.

**Comment by DarylGrunau** [comment]
My test environment is: python@3.6.8, mesa@19.0.3 and paraview@5.5.2.  The PV build gets to ~50% and dies on target vtkProbeOpenGLVersion with a bunch of unresolved symbols that are satisfied by libGL.  I commented out that target and the build proceeds to ~80% and likewise dies.  Working on fixing up CMakeList.txt files to try to link in this (now missing?) dependency.  I'm not clear why the change to newer mesa and/or python would introduce this type of error ...

**Comment by jrood-nrel** [comment]
I'm using paraview@5.6.0 and I'm seeing errors with VTK and MPI4py. I noticed this seems to indicate Python 3.7.1 should be fine with paraview@5.6.0 https://www.paraview.org/Wiki/ParaView_Release_Notes#Python_3.7.1_now_supported

**Comment by DarylGrunau** [comment]
Yep, those errors with MPI4py were why I backed off to the latest python@3.6.x.

**Comment by jrood-nrel** [comment]
I decided to just try the master branch:
```
    git      = 'https://github.com/Kitware/ParaView.git'
    
    version('5.6.0', branch='master', submodules=True)
    #version('5.6.0', sha256='cb8c4d752ad9805c74b4a08f8ae6e83402c3f11e38b274dba171b99bb6ac2460')
```
Now I think I'm up to the point of getting the missing GL symbols you are seeing.

**Comment by jrood-nrel** [comment]
I'm trying this now https://github.com/spack/spack/pull/11400

**Comment by chuckatkins** [comment]
While python 3 should work, the unsatisfiable version issue is from python 3 being a build-only deep for mesa which spack doesn't effectively separate.  You should be able to do a two step install via:
```
spack install mesa+osmesa
spack install paraview+osmesa+python
```
That will let osmesa use python3 as a build-only deep and paraview use python2 as a build+run dep without the unsatisfiable version issue.

**Comment by chuckatkins** [comment]
@opadron you were seeing a similar issue with vtk weren't you?

**Comment by jrood-nrel** [comment]
Working around the Python issue is fairly simple by using Paraview master, or Python 3.6, but these missing OpenGL symbols are much more difficult to track down.

**Comment by opadron** [comment]
@chuckatkins yeah, I was also running into missing GL symbols when building VTK with osmesa.

We've pushed changes that we are expecting to resolve those issues, although I haven't yet had the chance to retry my VTK builds.  I'll follow up on this thread once I've tried rebuilding VTK.

**Comment by chuckatkins** [comment]
@jrood-nrel the mpi4py issue seems to be a problem with using VTK's vendored mpi4py.  #11432 should have fixed that.

**Comment by opadron** [comment]
So, I retried building VTK and I am also (still) running into link-time issues involving missing symbols.  In my case, it looks like libGL is not being linked at all.  `libGLEW` and `libOSMesa` are there (from spack's `glew` and `mesa` packages, respectively), but `libGL` from `mesa` is not there, and I believe it should be.

Caveat 1: I'm trying this with a modified `package.py` for `VTK`.  [Here](https://gist.github.com/opadron/458ebeb535d3373c17043ef12fbbef44) is the version I am currently working with.

Caveat 2: I'm trying to build with the follow spec:
```
vtk @8.0.1    %gcc @8  +osmesa ~mpi
  ^netcdf                      ~mpi
  ^mesa                +osmesa      swr=avx,avx2
  ^llvm                ~all_targets
```

**Comment by jrood-nrel** [comment]
Here is what I'm seeing with the old mesa that worked for me in Paraview and the new one:
```
$ ls /software/2019-05-08/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/mesa-19.0.3-paqqmqxzhccq4tsh7goza7njk4rth5pr/lib/
libglapi.so    libglapi.so.0.0.0  libGL.so.1      libOSMesa.so    libOSMesa.so.8.0.0  libswrSKX.so.0      pkgconfig
libglapi.so.0  libGL.so           libGL.so.1.5.0  libOSMesa.so.8  libswrSKX.so        libswrSKX.so.0.0.0
$ ls /software/2019-01-10/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mesa-18.1.2-nnj2azqonwar5evbhzt2mlril4rin6fe/lib/
libglapi.la    libglapi.so.0.0.0  libGLESv1_CM.so.1      libGLESv2.so        libGL.la    libGL.so.1.5.0  libOSMesa.so.8
libglapi.so    libGLESv1_CM.la    libGLESv1_CM.so.1.1.0  libGLESv2.so.2      libGL.so    libOSMesa.la    libOSMesa.so.8.0.0
libglapi.so.0  libGLESv1_CM.so    libGLESv2.la           libGLESv2.so.2.0.0  libGL.so.1  libOSMesa.so    pkgconfig
```
It looks like I'm missing GLES, which probably doesn't matter, but I am missing `libGL.la` which I'm not sure if that matters if `libtool` is doing something with it.

**Comment by chuckatkins** [comment]
@jrood-nrel @opadron I think I've tracked this down to a mesa issue upstream, I'll iterate and update spack as soon as possible once I work it out with the mesa maintainers.

**Comment by chuckatkins** [comment]
@jrood-nrel can you see if #11518 fixes your OSMesa issue please?

**Comment by jrood-nrel** [comment]
Sure! I will try to find time today. Thanks for working on this.

**Comment by chuckatkins** [comment]
Didn't mean to close this.  I'll wait until the resolution is confirmed but the folks here affected.

**Comment by opadron** [comment]
Works for me! :+1:  VTK finally builds and links without any problems! :tada:

**Comment by DarylGrunau** [comment]
I don't think this issue should be closed until my original issue is resolved.  In particular, the Paraview spec needs to relax its requirement on python@2:2.8, line 40.  I'm glad to champion the PR to Spack but would like your/community agreement on what the change should look like.  In my (so modified) environment I, too, have been able to build out Paraview and use it successfully in our code's regression tests.  My test stack looks like this: mesa@19.0.4, python@3.6.8, paraview@5.5.2+osmesa.  Note that Paraview (this version at least) still fails to build under python@3.7.3.

As a proposed change to the Paraview spec, would you be supportive of the following:

\-     depends_on('python@2:2.8', when='+python')

\+    depends_on('python@2:2.8', when='+python~osmesa')
\+    depends_on('python@3:3.99', when='+python+osmesa')

**Comment by DarylGrunau** [comment]
Or perhaps:

\+    depends_on('python@2:2.8', when='+python~osmesa')
\+    depends_on('python@3:3.6', when='+python+osmesa')

due to Paraview build failures under Python 3.7

**Comment by chuckatkins** [comment]
@DarylGrunau I agree, I don't want the issue closed until the various install problems are resolved.  Some of that is happening automatically because of different pr's referring the issue as fixing some aspect of it.  I'll try to make sure this stays open as those get merged and re-open as necessary until we can confirm all issues are fully resolved.

The python 3.7 failure I believe was an incompatibility with VTK's vendored mpi4py and should have been fixed by #11432.

@danlipsa is currently working on the complexities of updating the spec for ParaView >= 5.6.0 to be exclusively python >= 3, see #11485

**Comment by DarylGrunau** [comment]
I left a comment on PR #11485.  @danlipsa's proposed changes do not entirely fix this issue.

**Comment by danlipsa** [comment]
@DarylGrunau So you tried to build with my branch? What are the errors you are seeing now. Thanks!

**Comment by DarylGrunau** [comment]
I inserted your proposed dependency into my local spack recipe for Paraview:

       depends_on('python@2.7:2.8', when='@:5.5+python', type=('build', 'link', 'run'))

and attempted to concretize with 'spack spec paraview'.  I get the same error as I initially report at the first post of this issue because I'm trying to build paraview@5.5.2+osmesa+python.

**Comment by danlipsa** [comment]
You'll have to use the whole recipe. There are other changes besides that.

**Comment by danlipsa** [comment]
In particular I go around this spack issue: https://github.com/spack/spack/issues/11531

**Comment by DarylGrunau** [comment]
Ok, downloading both your paraview and catalyst package.py files and putting them in place:

    % spack spec paraview
    Input spec
    --------------------------------
    paraview

    Concretized
    --------------------------------
    ==> Error: An unsatisfiable version constraint has been detected for spec:

    python@2.7:2.8
        ^pkg-config@0.27.1%gcc@7.4.0+internal_glib arch=linux-centos7-x86_64


    while trying to concretize the partial spec:

    mesa+osmesa
        ^expat@2.2.5%gcc@7.4.0+libbsd arch=linux-centos7-x86_64
            ^libbsd
        ^flex
            ^bison
                ^diffutils
                ^help2man
                    ^gettext@0.19.8.1%gcc@7.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-x86_64
                    ^perl@5.14.0:
                        ^gdbm
                            ^readline
                                ^ncurses
                                    ^pkg-config@0.27.1%gcc@7.4.0+internal_glib arch=linux-centos7-x86_64
                ^m4@1.4.16%gcc@7.4.0+sigsegv arch=linux-centos7-x86_64
        ^py-mako@0.8.0:
            ^py-markupsafe@0.9.2:
                ^py-setuptools
                    ^python@2.7:2.8


    mesa requires python version 3:, but spec asked for 2.7:2.8

**Comment by jrood-nrel** [comment]
I was able to test Paraview with the fixes to `mesa` and it worked for me. I am using Python 3.7.3 with the external py-mpi4py fix. I just removed the Python 3 and Matplotlib version dependencies in `paraview`. However it doesn't solve the Python 2 issue for older versions of Paraview.

**Comment by danlipsa** [comment]
@DarylGrunau Can you switch to my branch and try it that way. There may be other fixes to packages and / or spack itself. Not sure what branch you are on.

@jrood-nrel What is the command that did not work for you. What is the error you are getting? Thanks.

**Comment by jrood-nrel** [comment]
I just did this:

**Comment by DarylGrunau** [comment]
% git remote -v
    origin  https://github.com/danlipsa/spack.git (fetch)
    origin  https://github.com/danlipsa/spack.git (push)

    % git branch
      develop
    * use_python3

    % spack spec paraview@5.5.2+osmesa+python
    Input spec
    --------------------------------
    paraview

    Concretized
    --------------------------------
    ==> Error: An unsatisfiable version constraint has been detected for spec:

    python@2.7:2.8
        ^pkg-config@0.27.1%gcc@7.4.0+internal_glib arch=linux-centos7-x86_64


    while trying to concretize the partial spec:

    mesa+osmesa
        ^expat@2.2.5%gcc@7.4.0+libbsd arch=linux-centos7-x86_64
            ^libbsd
        ^flex
            ^bison
                ^diffutils
                ^help2man
                    ^gettext@0.19.8.1%gcc@7.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-x86_64
                    ^perl@5.14.0:
                        ^gdbm
                            ^readline
                                ^ncurses
                                    ^pkg-config@0.27.1%gcc@7.4.0+internal_glib arch=linux-centos7-x86_64
                ^m4@1.4.16%gcc@7.4.0+sigsegv arch=linux-centos7-x86_64
        ^py-mako@0.8.0:
            ^py-markupsafe@0.9.2:
                ^py-setuptools
                    ^python@2.7:2.8


    mesa requires python version 3:, but spec asked for 2.7:2.8

**Comment by chuckatkins** [comment]
This is due to an issue with the concretizer not being able to separate the build vs run dependencies throughout the dependency graph.  Python 3 is a build only dep of mesa so a workaround is to first explicitly install mess and then paraview.  Spack should then be able to evaluate the python2 build dep for paraview and only have to consider the runtime deps of the already installed mess which doesn't include python 3.

**Comment by baberlevi** [comment]
related to #11537

**Comment by DarylGrunau** [comment]
@chuckatkins, @danlipsa using Dan's "use_python3" branch, I get errors when I issue (being explicit about the specs):

  1. spack install mesa@19.0.4+osmesa                                # this succeeds with no problems!
  2. spack install paraview@5.5.2+python+osmesa             # this fails with my initial issue message

If I substitute paraview@5.6.0 above, everything succeeds (NB we /cannot/ use this version!!!).  Would either of you be willing to try a downrev paraview version in your spec you can see the problem (you don't even need to 'spack install', just 'spack spec')?  @adamjstewart would you comment about the concretization assertions being made in this issue's conversation thread?

**Comment by adamjstewart** [comment]
@tgamblin @scheibelp would know more about the concretizer than I would.

**Comment by chuckatkins** [comment]
I believe this is fixed by #11153 which brings in a "legacy" mesa package based on the older autotools build.

**Comment by opadron** [comment]
@chuckatkins did you mean #11553?

**Comment by chuckatkins** [comment]
@DarylGrunau #11595 just restored the older autotools build while keeping the package restructuring.  Can you check that it resolves the issue for you please?

**Comment by chuckatkins** [comment]
Ping?  Is this resolved in the current `develop` for you now that mesa has been rolled back to autotools?

**Comment by DarylGrunau** [comment]
Sorry for the delay (out on travel).  I'm happy to say with everyone's work here this issue has been resolved - thank you **_so_** much!  Closing ...
