### ISSUE TITLE
libxsmm-1.11: libxsmmf.pc contains relative incdir instead of absolute one and points to staging

### ISSUE THREAD

**Issue by dev-zero** [spack/spack#11413]
I've installed libxsmm-1.11 and ended up with the following `libxsmmf.pc` file:

```
Name: libxsmm/f
Description: LIBXSMM for Fortran
URL: https://github.com/hfp/libxsmm
Version: 1.11.0

prefix=/tmp/tiziano/spack-stage/spack-stage-GBJeMX/libxsmm-1.11
includedir=include
libdir=lib

Requires: libxsmm
Cflags: -I${includedir}
Libs: -L${libdir} -lxsmmf
```

yielding two problems:

* referencing in `prefix` the staging area instead of the final installation path
* `includedir` containing only a relative path instead of the full path

### Steps to reproduce the issue

```console
$ spack install libxsmm+no-header-only
```

@hfp any ideas?

**Comment by hfp** [comment]
This is fixed in v1.12, which is scheduled for today.

**Comment by hfp** [comment]
PR https://github.com/spack/spack/pull/11414

**Comment by scheibelp** [comment]
#11414 has now been merged so I will close this as fixed. Please reopen if the issue persists.

Thanks @hfp!
