### ISSUE TITLE
Broken edge case for caching

### ISSUE THREAD

**Issue by scheibelp** [spack/spack#1143]
This was introduced by my PR #579 (now merged)

If a URL resource was at one time identifiable with a digest, and then the digest was removed from package.py without changing the version, and the resource was altered (i.e. by the maintainer), the caching logic will mistakenly use the old resource from the cache. 

To be clear as long as there is not a transition from a version having an associated digest to having no digest, there will not be a problem. Changing digests will not be an issue.

This is fairly specific and there are no existing examples of this that I know of, so this isn't my immediate priority but I want to have a PR fix in the next week.

**Comment by tgamblin** [comment]
I was actually wondering about this when I merged but it seemed like something that was rare and could be fixed later.  Note that I also added `spack purge --cache` and `spack purge --all` options that will just blow away the download cache, to save space or to fix things like this.

**Comment by tgamblin** [comment]
PS: Thanks for implementing caching!  Also did you see Elizabeth's request for docs?

**Comment by mwilliammyers** [comment]
@tgamblin @scheibelp It would be handy to have an option to blow away only really old cached files (or input a time range or something like that)... Homebrew does that and I thought it was pretty handy.

**Comment by tgamblin** [comment]
@mwilliammyers What about a max cache size and continuous removal of least recently used things that exceed that limit?

**Comment by mwilliammyers** [comment]
@tgamblin I like that even more than Homebrew's implementation.

**Comment by adamjstewart** [comment]
@tgamblin another nice config option would be to only keep the most recent version of a downloaded package.

**Comment by citibeth** [comment]
I believe we should focus on making Spack work properly when it has checksums to verify against.  A rare edge case where the users was running in "unsafe" mode somehow doesn't bother me.

**Comment by alalazo** [comment]
@scheibelp Is this edge-case behavior still to be implemented?

**Comment by adamjstewart** [comment]
No response from @scheibelp so I'm guessing this is no longer an issue, reopen if I'm wrong.
