### ISSUE TITLE
"Too Many" New Packages / Updated Versions

### ISSUE THREAD

**Issue by citibeth** [spack/spack#11433]
@tgamblin 
We are drowning in new-package and version-update PRs.  I suggest we recruit more volunteers to process these routine PRs and get them merged quickly.  I'm happy to volunteer for that (but I believe we need more than just one new recruit for this job; it shouldn't be a big burden on anyone).

**Comment by chuckatkins** [comment]
I'll take on some.  I'm keeping my merges restricted in scope to IO and vViz packages but I'm happy to help pick up the slack on PRs outside of that for trivial things things like new version updates.

**Comment by tgamblin** [comment]
@citibeth: if you want to volunteer that's great -- we can make that happen.  Join Slack and I'll put you in the maintainers channel and get you set up.

We are also getting new staff here, and one of the things on the todo list is better triage.

**Comment by tgamblin** [comment]
closing as we've added @citibeth to help out
