### ISSUE TITLE
Abstract out the Repo Interface

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1147]
Create an API that allows new repo types to be added to the Spack core codebase.  The goal would be to eventually allow for all of GitHub to act as one repo.  It's not clear that the current API would fully support that.  But for now, the idea is to create and define the API as things currently stand; and then change it if needed.

@DavidPoliakoff @tgamblin @alalazo

**Comment by alalazo** [comment]
Relates to #1136

**Comment by alalazo** [comment]
Closing as stale since a while. Feel free to reopen if you feel the discussion should be pushed further on this topic.
