### ISSUE TITLE
Cannot source share/spack/setup-env.csh on SLES15 - CLE7

### ISSUE THREAD

**Issue by jhnlvsq** [spack/spack#11507]
Spack’s setup-env.sh breaks on Thunder using CLE7 due to the SLES15 update. 

 

The problem is that SUSE has updated their /etc/profile to specifically catch when the --norc command line parameter is used, and now /etc/profile won't source anything else.  On trinity, it goes on to source /etc/bash.bashrc because it doesn't care about the --norc command line option. When Trinity upgrades, this will break there, too.

Here is the conditional that causes this to break from /etc/profile: if test -z "$_SOURCED_FOR_SSH" -a "$norc" != true ; then

It used to be just if test -z "$_SOURCED_FOR_SSH" ; then

**Comment by alalazo** [comment]
Cannot reproduce with:
```console
$ docker run -it --rm registry.suse.com/bci/bci-base:15.3
```
and Spack at 4c2531d5fbc2022dd144d1c59dd6faa7ce2c9607

Within the image, installing `tcsh`, `git` and `python` I can source `setup-env.csh`:
```console
029006a6b5c4:/spack # tcsh
domainname: Command not found.
cannot stat /var/run/utmp.  Please "unset watch".
029006a6b5c4 /spack# source share/spack/setup-env.csh
029006a6b5c4 /spack# which spack
spack: 	 aliased to set _sp_args = (!*); source $_spack_share_dir/csh/spack.csh
029006a6b5c4 /spack# exit
```
Feel free to reopen if this is till an issue.
