### ISSUE TITLE
Running Spack as Root

### ISSUE THREAD

**Issue by citibeth** [spack/spack#11519]
Spack is not meant to run as root; but it also does not check either.  Running as root will break some common builds, causing hard-to-discern errors.  I don't think this is something we want to support; so we should prohibit it instead.  See #11396

### Steps to reproduce the issue

```console
$ sudo spack install tar
```

### Error Message

```
490 checking whether mknod can create fifo without root privileges...
configure: error: in /tmp/root/spack-stage/spack-stage-QZVi3T/tar-1 .30': 491 configure: error: you should not run configure as root (set FORCE_U NSAFE_CONFIGURE=1 in environment to bypass this check) 492 See config.log' for more details
```

### Suggested Solution

When Spack launches, check if it is being run as root.  If so, quit immediately, telling users to run under regular user accounts.

**Comment by baberlevi** [comment]
I run it as root 99% of the time, and it's fine. I set the FORCE_UNSAFE_CONFIGURE flag, that's really the only issue I've run into.  I'd prefer to not prohibit root, but a warning seems reasonable.

**Comment by citibeth** [comment]
On Mon, May 20, 2019 at 2:21 PM Levi Baber <notifications@github.com> wrote:

> I run it as root 99% of the time, and it's fine.
>

Thanks for the report.  My one question is... WHY?

**Comment by baberlevi** [comment]
Expected that question :)

1. Often building in a container (singularity or podman) and in the container, I'm root
2. We currently do our builds on a vm as root, and then distribute the modules & application tree to the clusters via nsf or rsync
3. It's been easier for some things like building singularity which need setuid

**Comment by healther** [comment]
We also did run spack as root for some time (not sure if we are still doing so). At least for container builds it makes things "simpler", that being said: It would be good to have spack force the user to consciously doing that (something like `--tolerate-root`?)

**Comment by alalazo** [comment]
Just leaving my opinion here for the record: being able to run as root might be needed or helpful in a few cases (e.g. `likwid` or `singularity`), so while we should not promote using Spack always as root we should also ensure we could do that if needed.

**Comment by citibeth** [comment]
Thanks for the feeback!  it sounds like running as `root` in a container is not the security risk that running as `root` would be on a "normal" system.  I think the `--tolerate-root` concept, along with an error message without it, would be helpful.  Then we can make Spack do `FORCE_UNSAFE_CONFIG` on its own, rather than relying on the root-using user to do that stuff.

**Comment by ax3l** [comment]
It's even documented here by me :)
https://spack.readthedocs.io/en/latest/workflows.html#using-spack-to-create-docker-images

**Comment by gmfricke** [comment]
What is the suggested method for sysadmins like me install system wide spack packages without sudo or root on our HPC clusters?

**Comment by citibeth** [comment]
Run Spack as a user of your choice; making sure permissions are set in
.bashrc so the resulting files are world readable.  Spack is intended to be
run in user space, not root.

**Comment by hartzell** [comment]
@gmfricke -- we built (using a non-root "service" account) our packages using Jenkins in a directory that was mounted from a shared NFS server.  Other machines in the cluster mounted that filesystem, which avoided any distribution/reinstallation issues.

**Comment by citibeth** [comment]
@ax3l What do you know... suddenly I need to build docker containers with Spack, and your directions are super helpful!

**Comment by ax3l** [comment]
@citibeth hurray, glad to hear that :)
