### ISSUE TITLE
Transitive build-only dependencies of already installed dependencies are not ignored.

### ISSUE THREAD

**Issue by chuckatkins** [spack/spack#11542]
Maybe difficult to describe in words, but a simple example should suffice.  Package A depends on package B which depends on package C.
```
foo1 <--bld-- foo2 <--bld-- foo3
```
Running `spack install foo2` will first check and install `foo3`, which is correct.  At that point, `spack install foo1` should only require `foo2`.  But it does not, it still evaluates `foo3` as a dependency.  This is especially problematic when the transitive dependencies conflict with each other:

```
foo1 <--bld-- foo2 <--bld-- foo3 <--bld-- bar@2:
   \
     <--bld-- bar@:1
```
Just trying to install `foo1` fails because of a `bar` version conflict.  Even though they don't need to be loaded at the same time, they still can't be evaluated together in the same dag.  This is already a known issue.  The workaround up until recently (I don't know exactly when), has been to explicitly install `foo2` which in turn will install `foo3` which uses `bar@2` as a build dependency.  Then when installing `foo1`, the only dependencies needed are `bar@1` and `foo2` since `foo2` is already installed and has no run or link dependencies.  This seems to no longer work and when installing `foo1`, `foo2`, `foo3`, `bar@1`, and `bar@2` all get evaluated, which of course creates a version conflict for `bar`.

### Steps to reproduce the issue

This can be easily seen with the `mesa-glu` package, who's only dependency is `gl`, which is provided by `mesa`.

```console
$ spack install mesa
...
$ spack install mesa-glu
...
==> cmake is already installed in 
...
==> ninja is already installed in 
...
==> meson is already installed in 
...
==> mesa is already installed in 
==> Installing mesa-glu
...
```

In this case, `cmake`, `ninja`, and `meson` clearly are not required in any way by the `mesa-glu` autotools package.  They're build-only dependencies several hops down the DAG that shouldn't ever need to be evaluated when installing the top level `mesa-glu` package..

**Comment by chuckatkins** [comment]
#11541 is another instance of this same problem.

**Comment by scheibelp** [comment]
@chuckatkins in these cases, if you do

`spack install foo2`

followed by 

`spack install foo1 ^/hash-of-foo2`

do you get the result you are looking for? In terms of https://github.com/spack/spack/issues/11537#issuecomment-495203819, that would be like installing mesa first, then installing a dependent package like `spack install foo ^/hash-of-mesa`

Spack usually does not consider installed packages when doing concretization, so I'm having trouble imagining when https://github.com/spack/spack/issues/11537#issuecomment-495384789 would have worked (if you have a notion, could you let me know?). However, the hash syntax above may resolve this issue.

**Comment by tgamblin** [comment]
@chuckatkins: suffice it to say this is a bug and I'm working on it, but it may still be a few weeks before I have a fix. Can you please keep this up to date with issues you have so I can follow along?

**Comment by tgamblin** [comment]
@chuckatkins: in the meantime did you try the workaround that @scheibelp mentioned here? 

https://github.com/spack/spack/issues/11542#issuecomment-496643555

**Comment by danlipsa** [comment]
@tgamblin I tried your workaround for my issue https://github.com/spack/spack/issues/11541
It does not seem to work:
```console
[~/projects/spack (use_python3 %)]$ spack install mesa
==> mesa is already installed in /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/mesa-19.0.4-acwgz3k7oyys2hwatxext5oa3njbzkmt

[~/projects/spack (use_python3 %)]$ spack install paraview@5.5.2+python^/acwgz3k
==> Error: An unsatisfiable version constraint has been detected for spec:

    python@2.7.16%gcc@7.3.0+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter~ucs4~uuid+zlib arch=linux-ubuntu18.04-x86_64


while trying to concretize the partial spec:

    mesa@19.0.4%gcc@7.3.0 buildtype=release +glx+llvm+opengl~opengles+osmesa patches=f238e06512a8666f99962a1eb19a4eb204b2bb36356c1157cceca2fc55e2ef9b swr=none arch=linux-ubuntu18.04-x86_64
        ^expat@2.2.5%gcc@7.3.0+libbsd arch=linux-ubuntu18.04-x86_64
            ^libbsd@0.9.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64


mesa requires python version 3:, but spec asked for 2.7.16
```

**Comment by scheibelp** [comment]
Thanks for trying that out @danlipsa! I checked into it more and unfortunately I can confirm that referring to the dependency by hash won't work in this case. I was going to spec out how to address this over the next couple days but may not be able to complete a PR for it until 6/11.

**Comment by scheibelp** [comment]
This should be addressed by #11594 (this supports `spack install` referring to installed dependencies by hash as described in https://github.com/spack/spack/issues/11542#issuecomment-496643555)

**Comment by chuckatkins** [comment]
@scheibelp #11594 is a workaround for the issue, but it's still present.  Unless you explicitly specify to resolve a dependency from an installed hash, spack will use an already installed dependency and still evaluate it's build deps.  So while #11594 gives you a was to manually work around the problem, which is certainly helpful, I don't think this should be closed until it works without manual intervention.

**Comment by scheibelp** [comment]
@chuckatkins I agree that the issue has not been resolved in the ideal manner. However, I think it would make sense to open a new issue which phrases this as a feature request. 

This was introduced in the context of https://github.com/spack/spack/issues/11537#issuecomment-495384789 which was stated as a regression of prior observed behavior. I did not see how Spack could have supported what you stated. To generally support the request made in this issue description, the concretizer will have to be updated.

One could update the labels and description of this PR accordingly, but IMO it is useful by itself and it would be better to open a related feature request.
