### ISSUE TITLE
spack seem to mix build and run dependencies

### ISSUE THREAD

**Issue by danlipsa** [spack/spack#11541]
I am trying to install paraview with python2 and mesa from:
https://github.com/spack/spack/pull/11485

The first command installs paraview with mesa and python3 and that works OK.

The second command, which tries to install paraview with mesa and python2,  complains that meson, the build system for mesa, needs python3.

However, mesa is already installed at that point by the first command so it should not need meson. Also, meson is only a build dependency for mesa it does need to interfer with python used in paraview.

```console
[~/projects/spack (use_python3)]$ spack install paraview+osmesa+python
==> paraview is already installed in /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/paraview-5.6.0-3jelinu57glruradq74wp72swlaooxx6
[~/projects/spack (use_python3)]$ 

[~/projects/spack (use_python3)]$ spack spec paraview@5.5.2+osmesa+python
Input spec
--------------------------------
paraview@5.5.2+osmesa+python

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    python@2.7:2.8
        ^pkgconfig@0.9.0:


while trying to concretize the partial spec:

    meson@0.45:


meson requires python version 3:, but spec asked for 2.7:2.8

```

**Comment by scheibelp** [comment]
This should be addressed by #11594 (this supports `spack install` referring to installed dependencies by hash as described in https://github.com/spack/spack/issues/11542#issuecomment-496643555)
