### ISSUE TITLE
Spack-Conda Integration

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1155]
@tgamblin  @scheibelp 

Here are specs for a poposed Spack-Conda Integration.  Comments/suggestions appreciated!

General idea: Spack will be used to produce a set of Conda recipes, from a set of Conda recipe templates.  Each Conda recipe is fully qualified and has fixed dependencies (aka EasyBuild).  Conda will be used downstream to actually build and distribute the software in question.
1. There are three repos here:
   1. Conda template repo: A set of templates that are used to produce final versioned Conda recipes.
   2. Spack repo: A set of `package.py` files, etc, corresponding to the Conda templates.
   3. Destination Conda repo: The fully specified Conda packages to be generated.  This is like the Spack install tree.  The recipes in the Spack package will create files in the destination Condo repo.
2. The Conda template repo should be auto-generatable from a standard Conda repo: basically, identify places in the `yaml` files that need to have templated items in them.  This auto-generation does not have to be the first step.
3. The Spack repo should be (almost) auto-generatable from the Conda tempalte repo.  But users will have to manually add information about virtual dependencies.
4. The build process for packages in the Spack repo will simply fill in appropriate info in the Conda template, and produce a final Conda package.
   1. Spack has its own idea of how the destination file tree is structured.  That will need to be modified so it can write into a Conda-format tree.

**Comment by scheibelp** [comment]
Some questions:

* Is there a desire to make packages which can be updated in place or was the full combinatorics of spack desired?
* If full combinatorics are desired, how do conda users find the appropriate conda package if for example they want to install gcc?

> Conda will be used downstream to actually build and distribute the software in question.

In the case of building rpms with #1154 the rpm spec calls the "spack install" command which allows using logic from package.py files. Is there a reason a similar approach wouldn't be desired for conda (or am I mistaken and you plan to have conda use spack)? The main concern I have here is translating the package.py logic to something that doesn't use Spack.

>The Conda template repo should be auto-generatable from a standard Conda repo: basically, identify places in the yaml files that need to have templated items in them.

Is this about identifying spots in conda's yaml files or Spack's yaml files?

Also why start with an existing conda repo? Why not generate a new conda repo from scratch?

> Spack has its own idea of how the destination file tree is structured. That will need to be modified so it can write into a Conda-format tree.

#631 modifications to cmd/install.py may be useful for this: in the case of rpm packages it was desired to configure the path from the root up to {bin, lib, etc.}

**Comment by alalazo** [comment]
Closing as stale for the last 3 years and a half. Feel free to reopen if there's desire to continue the discussion.
