### ISSUE TITLE
Send output of spack list to a pager

### ISSUE THREAD

**Issue by alalazo** [spack/spack#11554]
The output of `spack list` should be sent to a pager if it doesn't fit on the screen.

### Rationale

The `spack list` command can produce much more output than what fits on a screen and it is inconvenient to scroll up for 20 secs. to search what you're looking for. It would be much better if  the output is sent to a pager when long enough.

### Description

Compute in some way if the output fits in the current screen, send the output to a pager if not. We might add a feature similar to [echo_via_pager](https://click.palletsprojects.com/en/7.x/api/#click.echo_via_pager) in `llnl.util.tty`.

### Additional information

We can consider using the same feature for other commands like `spack find`, `spack spec` or similar.

**Comment by hartzell** [comment]
One the one hand, I don't find piping to a pager to be a problem, or to `tail -50` or ....  On the other hand, I've become used to `git log` firing up a pager for me, so ...

If you do this, you should ensure that if it's not going to a tty (e.g. if it's going to a pipe) that things still work.

**Comment by alalazo** [comment]
Not a lot of traction and very minor, so closing.
