### ISSUE TITLE
CPATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH and CMake

### ISSUE THREAD

**Issue by jrood-nrel** [spack/spack#11555]
So I had a recent issue with CMake 3.14.x where the `include_directories(SYSTEM <paths>)` was not suppressing warnings from "system" headers. It turns out this is a change in behavior in CMake and it has to do with Spack setting `CPATH` in the modules I was loading. It looks like `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH` are the equivalent of `-isystem` where `CPATH` is the equivalent of `-I`. So with this issue I am just curious if `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH` should be used instead of `CPATH` in the future? I think @scheibelp was dealing with `CPATH` issues in the past. Also the CMake issue regarding this is here: https://gitlab.kitware.com/cmake/cmake/issues/19291

**Comment by bvanessen** [comment]
@tgamblin @becker33 @scheibelp We are hitting this issue in LBANN as well when building with cub.
