### ISSUE TITLE
Openmpi : pbs/tm support

### ISSUE THREAD

**Issue by navdeeprana** [spack/spack#11569]
@bebosudo Has opened an issue [#10542](https://github.com/spack/spack/issues/10542) and provided a solution in the pull request [#10620](https://github.com/spack/spack/pull/10620) which is still open.

Reopening for visibility.

**Comment by scheibelp** [comment]
I'm going to reopen #10542 and close this. In the future, feel free to reopen issues if you don't think they are resolved
