### ISSUE TITLE
I cannot access https://ftpmirror.gnu.org/libsigsegv,   Has anyone encountered the same problem?

### ISSUE THREAD

**Issue by luxianjun** [spack/spack#11670]
[root@localhost local]# spack install gcc@7.2.0
==> Installing libsigsegv
==> Searching for binary cache of libsigsegv
==> Warning: No Spack mirrors are currently configured
==> No binary for libsigsegv found: installing from source
==> Fetching https://ftpmirror.gnu.org/libsigsegv/libsigsegv-2.11.tar.gz

curl: (7) Failed to connect to 2001:470:142:5::200: Network is unreachable
==> Fetching from https://ftpmirror.gnu.org/libsigsegv/libsigsegv-2.11.tar.gz failed.
==> Error: FetchError: All fetchers failed for libsigsegv-2.11-ffbkn4mcatukmrlxxphdbtomhcjpozlc

/usr/local/spack/lib/spack/spack/package.py:999, in do_fetch:
        996                raise FetchError("Will not fetch %s" %
        997                                 self.spec.format('{name}{@version}'), ck_msg)
        998
  >>    999        self.stage.create()
       1000        self.stage.fetch(mirror_only)
       1001        self._fetch_time = time.time() - start_time
       1002

**Comment by ax3l** [comment]
Yes, from time-to-time, gnu.org is not reachable for me as well.
If you need those packages often, you can cache them via a [source code mirror](https://spack.readthedocs.io/en/latest/mirrors.html) in Spack.

From what I have heard, it's also planned to provide public mirrors some time soon.
