### ISSUE TITLE
spack unable to find an lmod loaded compiler

### ISSUE THREAD

**Issue by adrienbernede** [spack/spack#11678]
### Steps to reproduce the issue

I noticed a change of behavior of the following scenario between spack@v0.12.1 and spack@develop :
 
```console
$ module load gcc/8.1.0
$ spack compiler find
```

### The problem

On "release" tag v0.12.1, the compiler is found, on the develop branch, it isn’t.

### System information 

The issue occurs on a supercomputer using lmod mechanism for modules.

**Comment by scheibelp** [comment]
@alalazo FYI (although I can look into this if you prefer)

Bisect is implicating https://github.com/spack/spack/pull/10190 (https://github.com/spack/spack/commit/6d56d4545472ddff1cdc0e8fd49d8260428a141e)

I'm not sure why that would cause an error yet.

**Comment by alalazo** [comment]
@adrienbernede @scheibelp I'll have a look at this today, thanks for the report

**Comment by adrienbernede** [comment]
I confirm that the problem is now solved.

Thank you
