### ISSUE TITLE
Intel compiler detection reports build number as part of version starting with v19.0.0

### ISSUE THREAD

**Issue by glennpj** [spack/spack#11695]
When using the `spack compiler add` command for the Intel compiler there is a mismatch between the package version and the compiler entry. For example, the package version is 19.0.3 but the compiler entry has a spec value of 19.0.3.199. This causes issues with the lmod module layout as well as other breakage.

### Steps to reproduce the issue

```console
$ spack versions -s intel
==> Safe versions (already checksummed):
  19.0.3  18.0.4  18.0.1  17.0.6  17.0.3  17.0.0  16.0.2
  19.0.1  18.0.3  18.0.0  17.0.5  17.0.2  16.0.4  15.0.6
  19.0.0  18.0.2  17.0.7  17.0.4  17.0.1  16.0.3  15.0.1
$ spack install intel@19.0.3
$ module load intel/19.0.3
$ spack compiler add --scope=site
==> Added 1 new compiler to /opt/packages/gpjohnsn/opt/ssoft/spack/etc/spack/compilers.yaml
    intel@19.0.3.199
==> Compilers are defined in the following files:
    /opt/packages/gpjohnsn/opt/ssoft/spack/etc/spack/compilers.yaml
...
```

### Information on your system
linux-centos7-x86_64

**Comment by phanousk** [comment]
There is maybe a more serious problem with intel-parallel-studio which may be concerned to this one. Reproducible by these steps:
1) fresh installation of Spack (git clone, no modifications)
2) follow the instructions here: https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#installing-intel-tools-within-spack for installation of intel-parallel-studio@cluster
3) follow the instructions here: https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#selecting-libraries-to-satisfy-virtual-packages (the ones for a cluster version)
4) spack spec abinit %intel@19 (or any other package possibly using blas and lapack)

result:
 ```
#spack spec abinit %intel@19
Input spec
--------------------------------
abinit%intel@19
Concretized
--------------------------------
==> Error: Conflicts in concretized spec "abinit@8.10.3%intel@19~hdf5+mpi+openmp+scalapack 
arch=linux-debian9-x86_64/ptd55xr"
List of matching conflicts for spec:
  intel-parallel-studio@professional.2019.3%intel@19 cflags="-msse4.2 -axAVX,CORE-AVX2" cxxflags="-msse4.2 -axAVX,CORE-AVX2" fflags="-msse4.2 -axAVX,CORE-AVX2" 
  ~advisor~clck+daal~gdb~ilp64~inspector+ipp~itac+mkl+mpi~newdtags+rpath+shared+tbb threads=openmp ~vtune arch=linux-debian9-x86_64
1. "+mpi" conflicts with "intel-parallel-studio@professional.0:professional.9999"
```

There is no such a mention of  intel-parallel-studio@professional version in config files, we are trying to use a cluster version. A quick workaround is to delete all lines with another versions than a cluster from package.py of intel-parallel-studio from a builtin repo (using some local repo with simplified versions list have no effect). Which leads perhaps either to fault of the conflicts code in that package.py or its interpetation from Spack.

**Comment by becker33** [comment]
@phanousk I believe these issues are unrelated, could you please create a separate bug report for yours?

**Comment by becker33** [comment]
The intel compiler reports a build number as part of its version. The release of a given version only has one build number as far as I can tell. Version detection for the intel compiler should omit the build number.

**Comment by phanousk** [comment]
> @phanousk I believe these issues are unrelated, could you please create a separate bug report for yours?

OK

**Comment by glennpj** [comment]
Pinging to see if this can get any attention. I noticed issues with a hierarchical module layout due to this version issue. I do not currently use a hierarchical layout so I am not sure if this is still problematic.

**Comment by glennpj** [comment]
Closing this as it is fairly old at this point.
