### ISSUE TITLE
stuck defunct editor after interactive license installation

### ISSUE THREAD

**Issue by anderbubble** [spack/spack#11691]
Installing packages that require a license file (seen with intel and pgi packages today) appear to hang forever after the license file is supplied interactively during installation. Re-starting installation with the license file already in place works.

### Steps to reproduce the issue

```console
$ spack install pgi@19.4 %gcc@4.8.5
```

### Error Message

```console
joan5896  95984  95849  0 08:51 pts/25   00:00:00          \_ python /curc/sw/spack-experimental/bin/spack install pgi@19.4 %gcc@4.8.5
joan5896  96013  95984  5 08:51 pts/25   00:00:08              \_ [vim] <defunct>
```

### Information on your system

Running on RHEL7.6

Using spack develop, 3ce90741a3dd82b22139f82a555e0158c796c169

**Comment by cnelson3** [comment]
I'm getting a similar issue whilst trying to install intel-parallel-studio 2019

**Comment by cnelson3** [comment]
@anderbubble have you installed the intel libraries previously yourself?  I found that when one installs the intel-parallel-studio suite, it creates a directory (~/intel)  in your home space, which if deleted, allows the installation to proceed.... I'm not entirely sure of the purpose of the directory created the installation process, but it seems to work OK without said directory.

**Comment by tgamblin** [comment]
@lee218llnl: do you mind looking at this one?  I think I've seen you report things in the past w.r.t. the `~/.intel` directory.  I'm not nearly as well versed in the compiler installation process.

**Comment by lee218llnl** [comment]
I agree with @anderbubble regarding Intel, but that doesn't explain PGI. I haven't seen issues before with PGI. It would help to see where it's hung up (i.e., a stack trace or strace output).

**Comment by anderbubble** [comment]
I'm going to be messing around with spack this weekend; I'll see if I can
replicate it for you.

~jonathon

**Comment by lee218llnl** [comment]
I just tried PGI and I can see a defunct and unkillable vim process after I enter the license info and quit vim. The spack python process is stuck in parent_pipe.recv() in build_environment.py. I will try to debug this a bit further.

**Comment by lee218llnl** [comment]
@tgamblin I suspect https://github.com/spack/spack/commit/0aed3bcea676a9df4a5c1c26a9a5ca7151d85215#diff-166d683c7a71bbff2ddc6c37ecab16b1 may be contributing to this. I don't understand the interactions well enough at this point to figure out the exact issue, but I imagine that you would have more insight.

**Comment by lee218llnl** [comment]
I have confirmed that if I hijack the licensing.py code to force the use of Spack's Executable() instead of the default execv, then the installation process continues after I exit the editor. I can submit a PR if this seems like the proper solution, but I'm not sure if something more is more fundamentally wrong with the sited commit to the editor.py code.

**Comment by lee218llnl** [comment]
@anderbubble As far as I can see #11968 fixes this, so I will close out this issue. Feel free to reopen it if you find otherwise. Also let me know if you get a chance to verify the fix for yourself (note you would have to pull the develop branch and remove your etc/spack/licenses directory to test).
