### ISSUE TITLE
Installation issue: pkgconf

### ISSUE THREAD

**Issue by mayrmt** [spack/spack#11771]
### Steps to reproduce the issue

```console
$ spack install pkgconf
==> Installing pkgconf
==> Searching for binary cache of pkgconf
==> Warning: No Spack mirrors are currently configured
==> No binary for pkgconf found: installing from source
==> Fetching http://distfiles.dereferenced.org/pkgconf/pkgconf-1.6.0.tar.xz

curl: (6) Could not resolve host: distfiles.dereferenced.org
==> Fetching from http://distfiles.dereferenced.org/pkgconf/pkgconf-1.6.0.tar.xz failed.
==> Error: FetchError: All fetchers failed for pkgconf-1.6.0-v4yrfswprkxnyfhnagk37yyjkskahyj5

<spack_root_directory>/lib/spack/spack/package.py:965, in do_fetch:
        962                raise FetchError("Will not fetch %s" %
        963                                 self.spec.format('$_$@'), ck_msg)
        964
  >>    965        self.stage.create()
        966        self.stage.fetch(mirror_only)
        967        self._fetch_time = time.time() - start_time
        968
```

I also tried to get download the `tar`-file using `wget`, which also couldn't resolve the host.

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux theseus 4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 16.04.6 LTS
``` 
and, if relevant, post or attach:

- `packages.yaml`: default settings
- `compilers.yaml`:
   `spack compilers` lists
    ```
    ==> Available compilers
    -- gcc ubuntu16.04-x86_64 ---------------------------------------
    gcc@5.4.0
    ```

### Additional information

Sometimes the issue benefits from additional details. In these cases there are
a few things we can suggest doing. First of all, you can post the full output of:
```console
$ spack spec --install-status <spec>
Input spec
--------------------------------
 -   pkgconf

Concretized
--------------------------------
 -   pkgconf@1.6.0%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 
```
to show people whether Spack installed a faulty software or if it was not able to
build it at all. 

### Related issues
There are two other issues (#6932, #8037)on the installation of `pkgconf`. I checked them. Based on their description, they are not related to this one.

**Comment by simo-tuomisto** [comment]
Encountered the same error. It seems that the site that provides the source code ([http://distfiles.dereferenced.org](http://distfiles.dereferenced.org)) is down.

**Comment by simo-tuomisto** [comment]
As a temporary measure I downloaded the source from [https://sources.voidlinux.org/pkgconf-1.6.0/pkgconf-1.6.0.tar.xz](https://sources.voidlinux.org/pkgconf-1.6.0/pkgconf-1.6.0.tar.xz) to `$spack/var/spack/cache/pkgconf` and installation went through.

**Comment by scheibelp** [comment]
This appears to have been a temporary error: the official download site for `pkgconf` is now back up again so I consider this resolved.

**Comment by mayrmt** [comment]
Thanks! I can also confirm that it works again.

**Comment by ReinhardPrix** [comment]
it's down again apparantly

**Comment by steo85it** [comment]
It's down again ... I downloaded a tarball from https://git.sr.ht/~kaniini/pkgconf/archive/pkgconf-1.6.3.tar.gz and put it in $spack/var/spack/cache/pkgconf as suggested above, but spack install does not seem to care (i.e., it tries to access the web url and fails). Suggestions? Thanks!

**Comment by scheibelp** [comment]
Does Spack complain about the resource when it is downloaded? Is it possible that the checksum didn't match Spack's expectation (`61f0b31b0d5ea0e...`)

**Comment by steo85it** [comment]
ah, good point! The url is up again, but that's a possible cause. Just to know, anyway, what I did should have worked (eventually by specifying some checksum=False option)?
