### ISSUE TITLE
llvm and fenics packages are named incorrectly by `spack install`

### ISSUE THREAD

**Issue by dmringo** [spack/spack#11789]
I tried to install `llvm`, but spack tries to install it as `flang-driver` (one of the resources of the `llvm` package).  A similar thing happens with `fenics`, being installed as `ffc`.  I haven't yet noticed any problems that result from this -- `clang` as provided by `llvm@8.0.0` seems to work fine when used via `spack load` in simple tests.  [I wrote a comment on the PR](https://github.com/spack/spack/pull/11568#issuecomment-501849962) that seems to have introduced it, and I'm copying some of that text inline here:

Trying to install either package (suggest using `--fake` to speed things up if you want to test this) will show `llvm` installing as `flang-driver` and `fenics` installing as `ffc`.  I've tested this out on a Mac laptop, in a Fedora 30 docker container and on a CentOS 7 machine.  `git bisect` led me to 87e6cb9f7 being the commit that changed this.

It seems that in both cases, if you load the package via `Repo.get` in a spack python shell, the `Package.name` path introduced in #11568 is not touched.  The only thing I can see in common between the two package definitions is that they use resources dicts that have keys that match the incorrect name.  I don't think any other packages are affected (tested by comparing `name` and `_name` across all packages in the builtin repo).

### Steps to reproduce the issue

Either command below should reproduce with a fresh spack clone

```console
$ spack install llvm
$ spack install fenics
...
```

### Error Message

I'm not sure if it's considered an error, really.  The relevant output from `spack install llvm` looks something like this:

```console
==> Installing flang-driver
==> Searching for binary cache of flang-driver
==> Warning: No Spack mirrors are currently configured
==> No binary for flang-driver found: installing from source
==> Building flang-driver [CMakePackage]
==> Successfully installed flang-driver
```

### Information on your system

Tested on:
- Fedora 30 docker image with python = 2.7.16 and python3 = 3.7.3
- CentOS7 with python = 2.7.15 and python3 = 3.4.9
- MacOS Mojave python = 2.7.10 and python3 = 3.7.3

most recently at d21bec996

**Comment by michaelkuhn** [comment]
I am hitting the same bug. The package still gets installed into the correct prefix.

It seems that this is due to the loops of the form `for name, ...:`, which override the package name. I have created a PR to fix this (#11879).
