### ISSUE TITLE
Update repo topics

### ISSUE THREAD

**Issue by hauten** [spack/spack#11791]
A new page on the LLNL software portal (https://software.llnl.gov/radiuss/) will soon dynamically pull in RADIUSS repos. To achieve this, we need RADIUSS-related repos outside the LLNL org to be tagged with relevant topics. See https://github.com/LLNL/llnl.github.io/issues/17, https://github.com/LLNL/llnl.github.io/issues/151, & https://github.com/LLNL/llnl.github.io/blob/new-home-page/radiuss/README.md for additional context.

For Spack, please add `build-tools` and `radiuss`.

**Comment by citibeth** [comment]
I don't know what you're asking for.  @scheibelp @tgamblin @lee218llnl ???

**Comment by hauten** [comment]
@tgamblin took care of it, no worries! I'll close the issue.
