### ISSUE TITLE
In Package.install: can I `install` whole directories rather than individual files?

### ISSUE THREAD

**Issue by xguse** [spack/spack#11802]
I have a VERY simple tarball that contains the following subdirs: `bin`, `data`, `lib`. Everything is compiled and required links are included in `lib`. I "just" need to move these dirs to the corresponding `prefix.bin`, `prefix.data`, `prefix.lib` locations.

Here is my `install` def:

```python
    def install(self, spec, prefix):
        mkdir(prefix.lib)
        mkdir(prefix.bin)
        mkdir(prefix.data)

        install("lib", prefix)
        install("bin", prefix)
        install("data", prefix)
```

I am being told that `install` fails bc they are dirs. Is there any way to copy the hundreds of files and subdirectories to `prefix` without a line for each file?

**Comment by chissg** [comment]
On 6/20/19 4:20 PM, Gus Dunn wrote:

I have a VERY simple tarball that contains the following subdirs: bin, data, lib. Everything is compiled and required links are included in lib. I "just" need to move these dirs to the corresponding prefix.bin, prefix.data, prefix.lib locations.

Here is my install def:

    def install(self, spec, prefix):
        mkdir(prefix.lib)
        mkdir(prefix.bin)
        mkdir(prefix.data)

        install("lib", prefix)
        install("bin", prefix)
        install("data", prefix)

I am being told that install fails bc they are dirs. Is there any way to copy the hundreds of files and subdirectories to prefix without a line for each file?

install_tree(<source-tree-top>, <dest>).

Best,

Chris.

**Comment by adamjstewart** [comment]
https://spack.readthedocs.io/en/latest/llnl.util.html#llnl.util.filesystem.install_tree

You can use:
```python
install_tree('bin', prefix.bin)
```
Spack will automatically create the destination directory for you if it does not already exist.
