### ISSUE TITLE
`spack load`: Don't conflict if only one env module exists

### ISSUE THREAD

**Issue by pat-s** [spack/spack#11815]
Maybe this already exists but I cannot find something.

If I have multiple variants of the same library installed but there is only an env module for only one

- then I would like to have no conflicts when calling `spack load <library>`
- load the variant that has the env module

Libraries without env modules are installed as make deps only anyways.
And I would like to be able loading libs by their name instead of every time using the hash just because there is another variant installed as a make dep.

**Comment by citibeth** [comment]
Try putting the stuff in a Spack Environment, then run `spack env loads -r` to generate a script of `module load` commands.  That is the ONLY guaranteed way to build a package and then load the same package you just built.  And it is what we should be moving toward, IMHO.

**Comment by alalazo** [comment]
Closing since `spack load` doesn't depend on module files anymore see #14062.
