### ISSUE TITLE
Spack Environments, Views and Python?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#11822]
I built a Python stack in a Spack Environment with view.  Then the command
```
<spack-view>/bin/python -c numpy
```
Does not work.  Of course it doesn't work; because `$PYTHONPATH` is not set.  OTOH, loading an environment by loading 100 modules (`spack env loads -r`) does set `$PYTHONPATH` and DOES work.

What is the recommended way to USE a Spack view, along with all the proper environment variables, once it is created?  Does Spack give any support / help on this front; e.g. by creating a module or to load to access the view?  Simply symlinking a bunch of files together is only half the job.

**Comment by healther** [comment]
There was some discussion that there should a module be generated, not sure if that was merged though. For our deployed system we use singularity containers, where the apps are setting the relevant environment variables. For manual use we provide bash functions (probably not enough for your case)
```
# prepend path to environment variable
prepend_path() {
  # $1: name of environment variable
  # $2: path
  local envvar="$1"
  local path_to_add=$(echo "$2" | sed -e 's/[]\/$*.^|[]/\\&/g')
  local cleanenv=$(eval "echo \$$envvar" | sed -e "s/$path_to_add:\\?//g")
  eval "export ${envvar}=${path_to_add}:${cleanenv}"
}

prepend_root() {
  # $1: root path to export
  local rootpath="$1"
  prepend_path PATH "$rootpath/bin"
  prepend_path LD_LIBRARY_PATH "$rootpath/lib"
  prepend_path MANPATH "$rootpath/share/man"
  prepend_path PYTHONPATH "$rootpath/lib/python2.7/site-packages"
}
```

**Comment by scheibelp** [comment]
> I built a Python stack in a Spack Environment with view. Then the command
> `<spack-view>/bin/python -c numpy`
> Does not work. Of course it doesn't work;

I'd be interested to know the sequence of environment creation/`spack add`/`spack install` commands you dispatched, because it is my intent that this *does* work: views are supposed to add Python in a way such that Python libraries which are symlinked in will be automatically loaded by the Python instance added to the view. There may be exceptions (i.e. gaps in the logic which intends to make this possible) but it should generally work.

At least one exception to this rule is packages which do not inherit from `PythonPackage` but have a Python library (e.g. installing something to a package-specific `site-packages...` directory). The `STAT` package is an example (see: https://github.com/spack/spack/issues/11698); in that specific case converting it to a `PythonPackage` may be the appropriate way to deal with the issue.

**Comment by ajw1980** [comment]
I also do the same as @healther and created a view and then create a custom module that sets PATH and PYTHONPATH for the view. I tried without PYTHONPATH, but there was at least one python module that didn't work when I left it off. I don't remember which one at this time. It would seem like a nice feature for a file system view to create a module to set a user's environment up to use that view.

One other problem is that is somewhat difficult to get a python view to not become over broad once you have a bunch of python modules. I want to limit the view to only python and not bring in the gcc, binutils, llvm, tcl, tar, etc. that were extra dependencies into the users environment. I end up manually creating the view with something like this:

spack -e python3-view view -d no symlink -i viewdir $(spack -e python3-view find -l | grep '[a-z0-9] py | awk '{print "/"$1}')

I see there are select and exclude options in the environment view definition, but it doesn't seem like it is possible to specify something like that.

**Comment by citibeth** [comment]
I think the question has been answered, so closing this thread.  I feel that Views aren't quite "there" yet because, although they symlink everything together, they don't take the user across the finish line in terms of making it work in their shell.  In the future, I think a module to load a View, and a module to load an Environment (without first symlinking it into a view), would be super.
