### ISSUE TITLE
Unwanted Views Even After `spack env create`.

### ISSUE THREAD

**Issue by citibeth** [spack/spack#11820]
@scheibelp 
Now that environments automatically have views attached to them (#11182)... how do I turn it off on an environment I already created?

To be more clear... I'm creating an environment by creating a directory in `environments/` and adding a `spack.yaml` file.  Then I use:
```
spack -e <myenv> concretize
spack -e <myenv> install
```

At that point, Spack decides to attach a view to my environment (which I don't want).  I never used `spack env create`, so I never got to tell Spack to NOT attach a view.  How does one change this setting *after* the environment is created? (and delete the corresponding view)?

**Comment by glennpj** [comment]
You can set the `view` parameter to `false` in the environment's `spack.yaml` file.
```yaml
spack:
  view: false
...
```
If that parameter already exists in the file it will point to the view directory. If it does not already exist then the default view directory is used, which is located in the `.spack-env/view` directory within the environment directory.

**Comment by citibeth** [comment]
Thanks for the tip.

@scheibelp  I think I will classify this as a bug.  If you *already have* an view (eg a `spack.yaml` file) and you didn't tell it where to create a view, then Spack is saying: "You didn't ask for a view, but I'll make one for you anyway in some random location I choose."  That's counter-intuitive; and breaks things that previously worked.

The behavior should be: if `spack.yaml` doesn't have `spack/view` specified for whatever reason --- either it was hand-created, or it's legacy --- then Spack shouldn't create a view!  (This would not change the behavior of `spack env create`, which was decided should create `spack.yaml` files with a view, by default.

**Comment by glennpj** [comment]
I agree with @citibeth , absence of the `view` parameter should be equal to `view: false`. I would add that when creating an environment with `spack env create` the `view` parameter in `spack.yaml` should be populated with the chosen path.

**Comment by citibeth** [comment]
In my case, I didn't use `spack env create`.

**Comment by scheibelp** [comment]
I think these are interesting arguments, but IMO this is a case of two opposing but valid perspectives. Perhaps things need to be better documented, but as long as the config is available to give the user what they want, I'm not inclined to classify this as a bug.

@citibeth 

>  If you already have an view (eg a spack.yaml file)

I'm not sure how having a `spack.yaml` implies you are explicitly managing a view

> ... and you didn't tell it where to create a view, then Spack is saying: "You didn't ask for a view, but I'll make one for you anyway in some random location I choose." That's counter-intuitive; and breaks things that previously worked.

I don't immediately see why the fact that this doesn't always work is a compelling reason to disable it by default. It may be that we should make the view management more lenient.

> The behavior should be: if spack.yaml doesn't have spack/view specified for whatever reason --- either it was hand-created, or it's legacy --- then Spack shouldn't create a view!

* For legacy environments, we explicitly decided we'd like to automatically add the view support
* For hand-created environments, IMO specifying `view: False` is sufficient, perhaps that should be better-documented

@glennpj 

> I would add that when creating an environment with spack env create, and not specifying a view path, the view parameter in spack.yaml should be populated with the default path.

I think this would make it harder to package an environment directory into e.g. a tarball and then share it with someone. As of now, you can simply copy/paste the environment to reuse it. If the default env path were explicitly recorded, I think a command would have to be added to reset it when copying the env.

**Comment by glennpj** [comment]
@scheibelp 
In the default case the view is in the environment directory so I think a relative path could be used. The main thing is to get the `view` parameter in the `spack.yaml` file so that it is visible to the end user. The real problem is when the view directory is set outside of the environment directory, ie.,
`spack env create --with-view /some/where/on/the/filesystem`
That would make the environment less portable, but as you say, there could be an option to override that  setting. In any event, I think it would be beneficial to have the `view` parameter visible in the `spack.yaml` file for all cases.

**Comment by citibeth** [comment]
Another problem is, EVEN AFTER Spack has re-written your `spack.yaml` file, it doesn't add `view: true` to it.  So you have to be *completely in the know* and add `view: false` all on your own.  This is not good human engineering in the end.

**Comment by citibeth** [comment]
Also I got this error when I tried `view:false`:
```
spack.config.ConfigFormatError: /home2/rpfische/spack7/var/spack/environments/entgvsd-gibbs/spack.yaml:6: Additional properties are not allowed ('view' was unexpected)
```
My `spack.yaml` is:
```
spack:
  view: false
  include:
#    - ../configs/beauregard.yaml      # Highest precedence
    - ../configs/gissversions.yaml
    - ../configs/centos7.yaml          # Lowest precedence

  # add package specs to the `specs` list
  specs:
  - setup: []
    spec: cmake
  - setup: []
    spec: netcdf-fortran
  - setup: []
    spec: ncview
  - setup: []
    spec: nco
...
```

**Comment by alalazo** [comment]
The behavior seems to be clearly documented [here](https://spack.readthedocs.io/en/latest/environments.html#environment-managed-views), so I'll be closing this issue. Feel free to submit a new proposal if you think the default value for `view` should be changed.
