### ISSUE TITLE
Export Spack API

### ISSUE THREAD

**Issue by citibeth** [spack/spack#11824]
@tgamblin said:
 > Currently, folks... have a lot of **bash** scripts built around Spack that are very complicated. 

IMHO, serious scripting with Spack should be done in Python, not Bash.  I think we might benefit from exporting a Spack API that people can write Python scripts to.  I think I've already done it a bit here and there; but making it standardized and available to the public; and pushing its use; might be beneficial.

**Comment by tgamblin** [comment]
Duplicates #11385.

This is something we want to do, but we haven't gotten around to it yet.  Releasing on PyPI would require restructuring the Spack distro in ways we don't currently have cycles to think about.

In the meantime, you can already script Spack by using spack-python:

```python
#!/usr/bin/env spack-python

import spack

# ... write stuff ...
```

Or by using [spack extensions](https://github.com/spack/spack/pull/8612), #8612.

The Spack API is also [documented here](https://spack.readthedocs.io/en/latest/spack.html).

**Comment by citibeth** [comment]
@tgamblin I think that `spack-python` does the trick here, along with the docs.

I think it sounds a lot easier than Spack extensions #8612.  I don't know how this has to do with #11385; nor do I think that releasing on PyPI is really the thing here.
