### ISSUE TITLE
Add help on variant matching to documentation (if it's not already there)

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1184]
Consider the text for inclusion:

No.  All the specs that exist at package build time are present on the package -- that's a prerequisite for concreteness.  This is intentional so that we can match variants properly -- concretization needs to know whether an install either a) had a variant enabled, b) had it disabled, or c) did not _know_ about that variant at build time.  Case (c) is important because if some _future_ build asks for +ucs4 or -ucs4, we know we have to rebuild.

There should be no issue with the matching here.  The spec 'python' will match either of these.  If you do this:

depends_on('python')

That means your package would be happy with any python build.  If you say this:

depends_on('python~ucs4')
or
depends_on('python+ucs4')

You're asking for one where ucs4 is guaranteed to be disabled/enabled.

**Comment by alalazo** [comment]
I don't think we should document this. This is essentially an issue that asks for a new concretizer that could take into account what's already installed before resolving constraints in dependencies. I would close it as we have many variations of the same request in other issues .Feel free to click the close button if you agree (just going through old issues and checking what can be closed with small effort)
