### ISSUE TITLE
Cray detect method doesn't work on Cori

### ISSUE THREAD

**Issue by mamelara** [spack/spack#1191]
We should probably think of a new way to find out whether we are on a Cray or not. I think on Cori /opt/cray/craype doesn't exist. Instead it's /opt/cray/pe. Quick fix is just to check /opt/cray but that still leaves the issue of whether we're on a Cray XC, Cray XK, etc.

**Comment by robertdfrench** [comment]
What are your thoughts on https://github.com/LLNL/spack/pull/1073?

**Comment by mamelara** [comment]
I've been looking at some of the Cray docs to see if there are any differences. It seems to be mostly hardware differences between Cray XC and Cray XT/XE/XK. Not sure how reliable that would be but we could look at proc/cpuinfo and also see if there is a /opt/cray file.

If we see an Intel Xeon processor for front-end then we could say we're on a Cray XC. If it's an AMD then we're likely on an Cray XT/XE/XK (not sure how we can differentiate between these).

http://www.serc.iisc.in/facilities/wp-content/uploads/2015/08/Cray_Programming_Environment_User_Guide.pdf

I think how EB gets around it is through release dates of software? I took a cursory look at one of their papers and I think that's what they mentioned.

**Comment by alalazo** [comment]
Any update?

**Comment by mamelara** [comment]
I think this is already resolved, but the case with targets mentioned above is something to still work on.

**Comment by tgamblin** [comment]
Fixed by #11906, if not earlier.
