### ISSUE TITLE
MPICH configured with pmi=pmi not working with SLURM

### ISSUE THREAD

**Issue by tamaradanceva** [spack/spack#11925]
Hi,

I have installed Openmpi correctly and I managed to run jobs. I need to install MPICH for another application. I install MPICH with:

```console
 spack install mpich pmi=pmi slurm=True
```
The installation is successful, however, when I run a job with srun -N 4 in the simplest case for hello world, it results in:

I am 0 of 1, on host ip-172-31-52-167
I am 0 of 1, on host ip-172-31-49-194
I am 0 of 1, on host ip-172-31-56-170
I am 0 of 1, on host ip-172-31-52-220

instead of the following wtih openmpi

I am 2 of 4, on host ip-172-31-52-167
I am 1 of 4, on host ip-172-31-49-194
I am 0 of 4, on host ip-172-31-56-170
I am 3 of 4, on host ip-172-31-52-220

My packages.yaml looks like this:

packages:
  slurm:
    paths:
      slurm@16.05.3: /opt/slurm/
    buildable: False

Kind regards,
Tamara

**Comment by tgamblin** [comment]
@tamaradanceva: Do you know how your SLURM instance is configured?  For example, ours are configured like this:

```
$ srun --mpi=list
srun: MPI types are...
srun: pmi2
srun: none
srun: openmpi
```

In this configuration, I believe you'd need to build `mpich` with `pmi=pmi2`.  Is `pmi` enabled for your SLURM instance?

**Comment by tamaradanceva** [comment]
Hi, it works with pmi2, and I have pmi enabled. The Openmpi installation works with pmi by default, Slurm also takes pmi as default. Thank you very much.
