### ISSUE TITLE
Excessive library search times

### ISSUE THREAD

**Issue by tjfulle** [spack/spack#11929]
Per recommendations, in #2067, the system lapack/blas are marked as external packages:

```
$ cat packages.yaml
packages:
  all:
    providers:
      blas: netlib-lapack
      lapack: netlib-lapack
  netlib-lapack:
    paths: 
      netlib-lapack@system: /usr
    version: [system]
    buildable: False
```

Now, in some package file I have:

```
$ cat package.py
...
   blas_libs = spec['blas'].libs.joined(';')
```

The call to `spec['blas'].libs` eventually makes its way to [`find`](https://github.com/spack/spack/blob/develop/lib/spack/llnl/util/filesystem.py#L1392) which calls [`_find_recursive`](https://github.com/spack/spack/blob/develop/lib/spack/llnl/util/filesystem.py#L881).  `_find_recursive` walks the entire `root` directory, which in this case is `/usr`.    For systems that have an enormous number of files/directories in the root directory this call can take an excessive amount of time.  In one test I ran, this call talk in excess of 30 minutes (at which point I stopped the installation).

Clearly, it should not take tens of minutes to find the `blas` libraries!

Perhaps some kind of `hint` keyword can be propagated down to `_find_recursive` so that `find_libraries` searches only `/usr/lib/` and `/usr/lib64` (in this example)

**Comment by scheibelp** [comment]
> Perhaps some kind of hint keyword can be propagated down to _find_recursive so that find_libraries searches only /usr/lib/ and /usr/lib64 (in this example)

Spack's current logic is to first search `lib/` and `lib64/` under the provided prefix, and it only tries recursively searching relative to the root if the libraries are not found in either of those directories. Or at least that's the intent: as a sanity check do you know for sure if the libraries you need are in `lib/` or `lib64/`?

**Comment by tjfulle** [comment]
Thanks @scheibelp , yes the libraries are in `/usr/lib64` (symlinking `/usr/lib64` to `/opt/fake/blas/lib64` and setting `paths: alas: /opt/fake/blas` fixes the issue).

When a package's `.libs` property is queried, spack indeed looks in `<prefix>/lib`, `<prefix>/lib64`, and `<prefix>`, in that order.  See the function `_default_libs_handler` in `spec.py`.  But, for lapack/blas, this is not the case.  A query of the `.libs` property goes through a long series of calls and eventually ends up at `packages/netlib-lapack/package.py::blas_libs` (also `lapack_libs`), which calls `find_libraries` directly with the spec's prefix with `recursive=True`.  In this case, the package is external and the prefix is `/usr` (as recommended in spack's documentation), so spack looks for the lapack/blas libs in `/usr` which can take tens of minutes if `/usr` is large.

**Comment by tjfulle** [comment]
Adopting a search function similar to that of `spec.py::_default_libs_handler` in `netlib-lapack/package.py::blas_libs` (and `lapack_libs`), namely:

```python
       for dirname in (self.prefix.lib, self.prefix.lib64, self.prefix):
            libs = find_libraries(libraries, root=self.prefix, shared=shared, recursive=True)
            if libs:
                return libs
```

seems to fix the issue.

**Comment by tjfulle** [comment]
@scheibelp see PR #11958
