### ISSUE TITLE
IOError generated when using system modules that were built by another spack install

### ISSUE THREAD

**Issue by sayerhs** [spack/spack#11955]
On ORNL Summit, I am attempting to build some packages that use CMake (e.g., `netlib-lapack`). I have a `packages.yaml` file that specifies that Spack should use the CMake provided by system module. When I attempt to do this I get the following error. It appears that the package was built correctly, but errored out when Spack attempted to look into the paths where the original CMake module was installed (by system admins using Spack). The expected behavior is that Spack shouldn't expect any `.spack` files in a system provided module, and shouldn't fail if those files are missing. 

```
==> Installing netlib-lapack
==> Searching for binary cache of netlib-lapack
==> Warning: No Spack mirrors are currently configured
==> No binary for netlib-lapack found: installing from source
==> Using cached archive: /ccs/home/sayerhs/.spack/downloads/netlib-lapack/netlib-lapack-3.8.0.tar.gz
==> Staging archive: /autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-blue/spack/var/spack/stage/netlib-lapack-3.8.0-4oglinka2peibr4p66nu4vo3s3oebyjt/lapack-3.8.0.tar.gz
==> Created stage in /autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-blue/spack/var/spack/stage/netlib-lapack-3.8.0-4oglinka2peibr4p66nu4vo3s3oebyjt
==> Applied patch /autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-blue/spack/var/spack/repos/builtin/packages/netlib-lapack/undefined_declarations.patch
==> Applied patch /autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-blue/spack/var/spack/repos/builtin/packages/netlib-lapack/testing.patch
==> Ran patch() for netlib-lapack
==> Building netlib-lapack [CMakePackage]
==> Executing phase: 'cmake'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Error: IOError: [Errno 2] No such file or directory: '/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/cmake-3.14.2-3zkrrk4chuq6wfhvxpmen2gzdpaoiorw/.spack/repos/builtin/packages/cmake/'

/autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-blue/spack/lib/spack/spack/package.py:1790, in log:
       1787                    err.write(errors.getvalue())
       1788                tty.warn('Errors occurred when archiving files.\n\t'
       1789                         'See: {0}'.format(error_file))
  >>   1790
       1791        dump_packages(self.spec, packages_dir)
```

### Steps to reproduce the issue

```yaml
# custom packages.yaml
packages:
  all:
    compiler:
      - gcc@7.4.0
      - xl@16.1
    modules: {}
    paths: {}
    providers:
      blas:
        - netlib-lapack
      lapack:
        - netlib-lapack
      mpi:
        - spectrum-mpi
    version: []
    variants: +mpi build_type=Release
  spectrum-mpi:
    version: [10.3.0]
    buildable: false
    modules:
      spectrum-mpi@10.3.0: spectrum-mpi/10.3.0.0-20190419
    paths: {}
    providers: {}
    compiler: []
  cuda:
    version: [10.1.105]
    buildable: false
    modules:
      cuda@10.1.105: cuda/10.1.105
  cmake:
    version: [3.14.2]
    buildable: false
    modules:
      cmake@3.14.2: cmake/3.14.2
```

``` console
$ spack install netlib-lapack
```

### Information on your system

This includes:

 1. ORNL Summit system
 2. GCC 7.4.0 compiler

**Comment by jrood-nrel** [comment]
@mpbelhorn Would you have information that would help us regarding this?

**Comment by becker33** [comment]
I'd really appreciate whatever insight you have into this @mpbelhorn. I was not able to reproduce it on the Summit/Sierra-style testbeds at LLNL, although that was with cmake@3.14.5 and gcc@7.3.1 due to what's available on the system.

**Comment by becker33** [comment]
@sayerhs does this occur with any modules other than cmake?

**Comment by sayerhs** [comment]
@becker33 No, this only happens on Summit with `cmake/3.14.2` spack package. This error doesn't occur with the other `cmake` modules installed on Summit. Poking into the the directories, I notice that on Summit `cmake/3.14.2` doesn't have a `cmake` directory within `.spack/repos/builtin/packages` while the other `cmake` builds have that directory.

**Comment by roblatham00** [comment]
I am seeing this on Summit as well.  My workaround was to not use system cmake (which is itself a spack package but one built/maintained by ORNL).  If I let my spack build cmake, the problem (for me, rma-tools) goes away.  You are not alone, @sayerhs , even if i have no answers for you.

**Comment by sayerhs** [comment]
@roblatham00 Sorry, I should have reported here that I ended up doing the same thing as you did... build my own CMake instead of using system provided build.

**Comment by roblatham00** [comment]
Wait, why is this closed?
