### ISSUE TITLE
conflicting intel-parallel-studio versions

### ISSUE THREAD

**Issue by phanousk** [spack/spack#11950]
There is an issue with confliction parallel-studio versions. Reproducible by these steps:
1) fresh installation of Spack (git clone, no modifications)
2) follow the instructions here to install intel-parallel-studio@cluster.2019.4: https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#installing-intel-tools-within-spack for installation of intel-parallel-studio@cluster
3) follow the instructions here: https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#selecting-libraries-to-satisfy-virtual-packages (the ones for a cluster version)
4) spack spec abinit %intel@19 (or any other package possibly using blas and lapack)

result:
 ```
#spack spec abinit %intel@19
Input spec
--------------------------------
abinit%intel@19
Concretized
--------------------------------
==> Error: Conflicts in concretized spec "abinit@8.10.3%intel@19~hdf5+mpi+openmp+scalapack 
arch=linux-debian9-x86_64/ptd55xr"
List of matching conflicts for spec:
  intel-parallel-studio@professional.2019.3%intel@19 cflags="-msse4.2 -axAVX,CORE-AVX2" cxxflags="-msse4.2 -axAVX,CORE-AVX2" fflags="-msse4.2 -axAVX,CORE-AVX2" 
  ~advisor~clck+daal~gdb~ilp64~inspector+ipp~itac+mkl+mpi~newdtags+rpath+shared+tbb threads=openmp ~vtune arch=linux-debian9-x86_64
1. "+mpi" conflicts with "intel-parallel-studio@professional.0:professional.9999"
```

There is no such a mention of  intel-parallel-studio@professional version in config files, we are trying to use a cluster version. A quick workaround is to delete all lines with another versions than a cluster from package.py of intel-parallel-studio from a builtin repo (using some local repo with simplified versions list have no effect). This is perhaps either due fault of the conflicts code in that package.py or its interpetation from Spack.

**Comment by greglucas** [comment]
I was running into the same issue with the cluster version installed and wondering why it was looking for 'profesional ...' It turns out all of the compiler links were registered/found by Spack, but the extra tools packages weren't. I missed the 'special step' listed on the intel installation page:
https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#integrating-external-libraries

Updating the file ~/.spack/packages.yaml with
```
packages:
  paths:
    intel-parallel-studio@cluster.version +mkl+mpi+ipp+tbb+daal: /path/to/intel
  buildable: False
```
seems to solve that version issue.

**Comment by alalazo** [comment]
Closing as it seems the error message is legit according to the recipe provided by Spack, which contains:

https://github.com/spack/spack/blob/c0032a366091c112fb68d521d137344497f7ff8b/var/spack/repos/builtin/packages/intel-parallel-studio/package.py#L200

The conflict should not happen if you use `intel@cluster.X.Y`. Feel free to reopen if I misunderstood the issue.
