### ISSUE TITLE
Incomplete computation of installed dependents

### ISSUE THREAD

**Issue by alalazo** [spack/spack#11983]
Follow-up of https://github.com/spack/spack/issues/3690#issuecomment-510020811. Basically everything that relies on computing dependents is broken when a spec has more than one dependent with the same name.

### Steps to reproduce the issue
The issue can be reproduced with e.g. Spack at d3be42fccaabbdc71c03da0886214b31a29921e5. Let's start by installing 2 different versions of `hdf5` depending on the same `zlib`:
```console
$ spack install --fake hdf5~mpi+fortran hdf5~mpi~fortran
```
Let's then check that they actually both depend on the same `zlib` and they have different hashes:
```console
$ spack find -ld hdf5
==> 2 installed packages
-- linux-ubuntu18.04-x86_64 / gcc@9.0.1 -------------------------
xyhss36    hdf5@1.10.5
tn4qvs7        ^zlib@1.2.11

4f3j7km    hdf5@1.10.5
tn4qvs7        ^zlib@1.2.11
```
Asking which are the installed dependents of `zlib` will give the wrong answer an **skip one of the two specs**:
```console
$ spack dependents -i zlib
==> Dependents of zlib@1.2.11%gcc@9.0.1/tn4qvs7
-- linux-ubuntu18.04-x86_64 / gcc@9.0.1 -------------------------
xyhss36 hdf5@1.10.5
```
This is ultimately due to how dependents are computed in `spack.spec.Spec`:

https://github.com/spack/spack/blob/c2de2558b6423711e3b2cdbaaca1c0b0dfb61757/lib/spack/spack/spec.py#L1063-L1072

by constructing a map **from the package name** to the branch connecting it to the current spec. When there is more than one dependent with the same name only the last dependent added will be recorded.

This might be fine if we are working on a single tree DAG (where we are ensured there's at most one spec with the same name), but it is not if we are analyzing the entire DAG of all the installed applications. For instance the method:

https://github.com/spack/spack/blob/d3be42fccaabbdc71c03da0886214b31a29921e5/lib/spack/spack/database.py#L878-L911

will return wrong results when we ask to analyze in the `parents` direction.

### Error Message

There's no error message, just the information on dependents of an installed spec is computed wrongly. This lead for instance to issues like #3690 or #5637.

### Information on your system

The platform is not relevant for this bug.

**Comment by scheibelp** [comment]
I have reclassified this to medium impact because I don't know of this affecting commands other than `spack dependents`. You fixed the primary resulting issue from this bug in https://github.com/spack/spack/pull/11977.

Feel free to undo that if you disagree.

**Comment by tldahlgren** [comment]
I wonder if this issue is the reason the distributed builds cannot using the DAG hash as part of the `unique_id` as described in https://github.com/spack/spack/pull/13100#discussion_r371997910?

**Comment by scheibelp** [comment]
@aweits mentioned they would be looking into this (I was going to assign them but currently can't, probably on account of Github config)
