### ISSUE TITLE
Allow request for 'only dependencies' within a spack.yaml file

### ISSUE THREAD

**Issue by wspear** [spack/spack#12003]
Currently the functionality of 'spack install --only dependencies ...' is provided only on the command line. It would be handy to have the ability to be able to request dependencies only for a package in the specs list of a spack.yaml file.

Currently my workaround is to manually obtain a list of dependencies and write that into the specs list, or perform the 'spack install --only' operation on the command line after building the other specs in the environment.

**Comment by alalazo** [comment]
Can you comment a bit more on the use case for this? Is it for development purposes (if so you might want to check out #15256)?

**Comment by wspear** [comment]
Yes, we wanted to be able to provide the development environment for an application but not install the application itself. I believe #15256 will cover this case.
