### ISSUE TITLE
Warning: No Spack mirrors are currently configured

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#12010]
Can we get rid of this warning message (at least until Spack mirrors are commonplace)?
```console
==> Installing foo
==> Searching for binary cache of foo
==> Warning: No Spack mirrors are currently configured
==> No binary for foo found: installing from source
```
### Steps to reproduce the issue

```console
$ spack install foo
```

**Comment by scheibelp** [comment]
I'll skip the triage step and say I think this could be resolved by making the mirrors warning a debug-level message.
