### ISSUE TITLE
Split Clang and Apple Clang into separate compilers

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#12011]
We should consider splitting Clang and Apple Clang into separate compilers, like `%clang` and `%apple`.

### Rationale

I'm trying to build the latest version of `scikit-learn`, which recently added an OpenMP dependency. Apple Clang currently does not come with OpenMP support by default, so I need to add a dependency on `llvm-openmp`. However, there is currently no way to check whether Clang or Apple Clang are in use via the spec.

Several other packages need to know whether we are using Clang or Apple Clang:

- fftw
- hpgmg
- libceed
- m4
- openblas
- py-scikit-learn
- qt
- sundials
- valgrind
- vtk
- xios
- yaml-cpp

### Description

The only current workaround is to use the following spec:
```python
when='%clang platform=darwin'
```
However, this does not work if you install Clang yourself on macOS.

@davydden

**Comment by sethrj** [comment]
Maybe one way to allow for the openmp requirement would be for *variants* to be stored as part of the compiler spec. This might allow `%clang+openmp` to be specified as a requirement; and to get rid of the (as far as I can tell, basically unused) `provides('golang')` in GCC by replacing a requirement with `%gcc+languages=go`. Apple's external compiler would be of course stored as the variant `clang~openmp`.

See https://github.com/spack/spack/issues/954 and https://github.com/spack/spack/issues/896 .

**Comment by adamjstewart** [comment]
@sethrj that solves one problem, but it doesn't solve the problem that Apple Clang and LLVM Clang are versioned differently. I believe CMake separates Clang and AppleClang too.

**Comment by sethrj** [comment]
That's very true, I wasn't thinking about the versioning... 😒

**Comment by alalazo** [comment]
Treating suffixes for a dashed version of a compiler as a completely new branch seems to cause more problems than it solves in `archspec` a.k.a. `llnl/util/cpu.py`. So I would be for doing this at some point, maybe during the refactoring of compilers as dependencies @tgamblin @becker33 @scheibelp @tldahlgren

**Comment by alalazo** [comment]
Reporting here the comment from #16967 by @adrienbernede 

> I would like to complete this with a related "bug" on MacOS (darwin-mojave-skylake), with Spack 0.14.2-1313-0086c4754:
>
> With clang@10.0.0-apple already configured (by autodetection), Spack won’t detect vanilla llvm 10.0.0 installed with Homebrew even when provided with the installation location.
Commenting Apple Clang config results in successful detection of LLVM Clang.
>
> Although both are the same version I would expect Spack to make the difference. This issue would solve that.

**Comment by alalazo** [comment]
ARM compilers based on LLVM are called `arm`. Would `apple` do as a name to be consistent? Or should we change both to `arm-clang` and `apple-clang`?
