### ISSUE TITLE
Error when adding package to environment

### ISSUE THREAD

**Issue by pat-s** [spack/spack#12052]
Removing the directory and retrying does not help.

```sh
spack add libpng
==> Adding libpng to environment paper2
==> Updating view at /opt/spack/var/spack/environments/paper2/.spack-env/view
==> Error: [Errno 17] File exists
```

**Comment by scheibelp** [comment]
Could you rerun the command with `--stacktrace -d` like `spack --stacktrace -d add libpng` and add the full output here?

> Removing the directory and retrying does not help.

To make sure, do you mean removing `/opt/spack/var/spack/environments/paper2/.spack-env/view` doesn't work?

Some other questions:

* Are you using the view associated with your environment?
* Do you have any special configuration in `packages.yaml`?
* Could you print the results of `spack find` when the environment is active (which you can determine with `spack env status`)?

**Comment by alalazo** [comment]
@pat-s

**Comment by pat-s** [comment]
After updating Spack I cannot reproduce it anymore.
