### ISSUE TITLE
Bzip2 package has bad url: Returns Code 410

### ISSUE THREAD

**Issue by 23skdu** [spack/spack#12066]
Trying to bootstrap a new build, and it's breaking after pulling a fresh copy of Spack,
because the url in the bzip2 package is bad;

# curl -sI https://fossies.org/linux/misc/bzip2-1.0.6.tar.gz
HTTP/1.1 410 Gone
Date: Fri, 19 Jul 2019 17:34:13 GMT
Server: Apache
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15768000
Content-Length: 2126
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Type: text/html

**Comment by adamjstewart** [comment]
#12017 updated the URL to a new location. You should update your Spack instance.
