### ISSUE TITLE
New Oracle Licensing Terms

### ISSUE THREAD

**Issue by citibeth** [spack/spack#12073]
`spack install java` now fails with:
```
==> Fetching https://download.oracle.com/otn-pub/java/jdk/12.0.1+12/69cfe15208a647278a19ef0990eea691/jdk-12.0.1_linux-x64_bin.tar.gz
#################################################################################### 100.0% -=O=-#   #    #    #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
```

This is because Oracle just changed license terms.  You now need OpenJDK.  ALL version URLs in our current Spack package need to be changed:

https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html

Has anyone else seen this yet?

**Comment by mwkrentel** [comment]
For me, two and only two of the spack jdk versions do still fetch
cleanly.  Don't know why.

```
jdk-1.8.0_131-b11.tar.gz
jdk-1.8.0_141-b15.tar.gz
```

I have a package (hpcviewer) that still needs Java specifically at
version 8.  (It's an Eclipse thing, don't ask.)

So, please don't get rid of the jdk package.  Even in the worst case,
where all versions require a manual download, you can still download
them and put them into a mirror.  But it may come to that.

**Comment by adamjstewart** [comment]
According to @Hironori-Yamaji, the package still works fine, it's just that Oracle likes to take away older builds. See #12081. 

I wonder if they keep the latest stable version of each major release? Maybe we could ensure that we always have the latest stable version and set the most recent one to `preferred=True`? That way users can still add newer versions even if they'll disappear eventually.

**Comment by citibeth** [comment]
I've created an `openjdk` package, which downloads OpenJDK from Oracle's recommended site.  It's basically the `jdk` package, minus the donwload rigamerole.  I'll submit it soon; and suggest that we make it the default provider for `java`.

**Comment by adamjstewart** [comment]
It looks like there has already been work on `openjdk` in the past:
#2622, #9861, #10446

According to https://github.com/spack/spack/pull/9861#issuecomment-439262167:

> > How do `jdk` and `openjdk` differ? Should `openjdk` be the default `java` provider?
>
> I think there's still a place for jdk (the oracle closed source java implementation), but openjdk (an entirely opensource jdk implementation) currently only has version 11.0.1 out so It's not a great replacement for earlier versions of java. It looks like they're aiming to have at least an updated version of jdk8 available similarly at some point.

**Comment by citibeth** [comment]
I ran into this because `spack install r` bombed out.  I'd advocate for a
Spack in which such a command does "just work": either by defaulting to
OpenJDK, or by removing Java as a default dependency from R.

**Comment by adamjstewart** [comment]
I would personally be fine with defaulting to `openjdk`. It looks like that's what Homebrew does.

**Comment by citibeth** [comment]
So... what do we change for that?

**Comment by citibeth** [comment]
OK I found it.
