### ISSUE TITLE
Intel compiler fails to install

### ISSUE THREAD

**Issue by glennpj** [spack/spack#12085]
Installation of the intel compiler fails when trying to generate the `tcl` module. According to `git bisect` this is due to commit 2fe1ecbaa2f87bc3f11f73ee41828ea5b9a6b3d5, #10753.
The error produced is:
```console
==> Error: TypeError: string indices must be integers, not str

/opt/ssoft/spack/lib/spack/spack/build_systems/intel.py:1030, in setup_environment:
       1027        # I am not sure about earlier versions.
       1028        # if sys.platform == 'darwin':
       1029        #     args = ()
  >>   1030
       1031        run_env.extend(EnvironmentModifications.from_sourcing_file(f, *args))
```

**Comment by alalazo** [comment]
@glennpj I'll have a look asap, as it seems something @svenevs already reported in https://github.com/spack/spack/pull/10753#issuecomment-475212313 I wasn't able to reproduce it, but I wonder if I missed to clean my configuration files properly and that hid the problem.

**Comment by carns** [comment]
I'm hitting this problem too in a slightly different case: when installing intel-mpi on a system where the intel compiler is already installed.  I was able to narrow it down to the same commit as well.

In my case the error looks like this:

```
[carns@beboplogin2 spack ((2fe1ecb...))]$ spack install intel-mpi
==> intel-mpi@2017.3 : has external module in intel-mpi/2017.3-dfphq6k
==> intel-mpi@2017.3 : is actually installed in /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3-dfphq6kavje2olnichisvjjndtridrok/compilers_and_libraries_2017.4.196/linux/mpi/intel64
==> intel-mpi@2017.3 : generating module file
==> Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      source /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3-dfphq6kavje2olnichisvjjndtridrok/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin/mpivars.sh intel64 &> /dev/null && python -c "import os, json; print(json.dumps(dict(os.environ)))"
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
==> Error: string indices must be integers, not str
```

I can trigger the same error if I attempt to install intel-mpi from scratch, but in the above example I'm trying to use an intel-mpi that's already present on the system by putting this in my packages.yaml:

```
    intel-mpi:
        modules:
            intel-mpi@2017.3%gcc@7.3.0: intel-mpi/2017.3-dfphq6k
        buildable: False
```

This works fine with older git revisions.

**Comment by alalazo** [comment]
I was able to reproduce the same error as @svenevs on one of our clusters. I'll try to fix this by the day.

**Comment by alalazo** [comment]
@glennpj @carns Can you confirm that #12116 solves the issue?

**Comment by glennpj** [comment]
@alalazo I can confirm that #12116 fixes the issue for me.

Thanks.

**Comment by carns** [comment]
I'm late to the party, but I can confirm the problem is fixed now as well (testing current origin/develop after the PR merge).  Thanks for the prompt fix @alalazo .
