### ISSUE TITLE
Module file not created during install when exclude_implicits is enabled

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [spack/spack#12105]
Spack can be configured to avoid generating module files for implicitly installed products (i.e. dependencies which have been installed automatically):
```yaml
modules:
  tcl:
    blacklist_implicits: true
```

However there is a bug in this feature which prevents the module files to be created during `spack install` for explicitly installed products. If a refresh is later triggered with `spack module tcl refresh`, the module file is correctly generated.

### Steps to reproduce the issue

```console
$ spack install zlib@1.2.11
...
$ module avail zlib
$ spack module tcl refresh -y zlib
...
$ module avail zlib
zlib/1.2.11
```

### Technical info on the issue

As far as I can tell the problem is caused by an incorrect order of operations in this part of the code:
https://github.com/spack/spack/blob/0bff0c2d0d99e49dad723acad3ea37172972edaf/lib/spack/spack/package.py#L1674-L1685

Unfortunately, the module file generation is triggered in the `build_process` function before the product is actually registered in the DB:
https://github.com/spack/spack/blob/0bff0c2d0d99e49dad723acad3ea37172972edaf/lib/spack/spack/package.py#L1633-L1634

I would have happily contributed a fix for this issue but I feel like it might be non-trivial. The hooks must run before the staging folder is destroyed and I am not sure whether the registration in the DB can happen in the forked subprocess.

**Comment by mamelara** [comment]
I've seen this happen as well

**Comment by ghost** [comment]
I've also seen this happen in 0.16.

**Comment by sebhinck** [comment]
This is still a problem in 0.17.1.

**Comment by Obihoernchen** [comment]
And in 0.18.0, too.

**Comment by anselmic** [comment]
0.19.0 as well.
