### ISSUE TITLE
Installation issue: Qt 4 on macOS

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#12139]
I'm unable to build Qt 4 on macOS. Qt 5 built fine.

### Steps to reproduce the issue

```console
$ spack install qt@:4 platform=darwin
...
  >> 287     Undefined symbols for architecture i386:
     288       "_CFArrayCreate", referenced from:
     289           macList(QList<QVariant> const&) in qsettings_mac.o
     290       "_CFArrayGetCount", referenced from:
     291           qtValue(void const*) in qsettings_mac.o
     292           QMacSettingsPrivate::children(QString const&, QSettingsPrivate::ChildSpec) const in qsettings_mac.o
     293           QMacSettingsPrivate::sync() in qsettings_mac.o

     ...

     1201      "_vsnprintf", referenced from:
     1202          qvsnprintf(char*, unsigned long, char const*, char*) in qvsnprintf.o
     1203          qsnprintf(char*, unsigned long, char const*, ...) in qvsnprintf.o
     1204      "_write$UNIX2003", referenced from:
     1205          QFSFileEnginePrivate::writeFdFh(char const*, long long) in qfsfileengine.o
     1206    ld: symbol(s) not found for architecture i386
  >> 1207    clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 1208    make: *** [/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-KDjE7V/spack-src/bin/qmake] Error 1
```
It's interesting that it detects the architecture as i386 instead of x86_64.

### Platform

```commandline
$ uname -a 
Darwin Vesuvius 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/3433475/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/3433476/spack-build-env.txt)

@davydden you helped me last time I had problems building Qt on macOS. Any thoughts?

EDIT: Also note that if you run Spack with Python 3, you'll need #12138 to get `qt` to work. These error logs were produced using the current package and Python 2.

**Comment by davydden** [comment]
Last time i tried was with qt5 and I had to help it a bit https://github.com/spack/spack/pull/11172. Have not tried qt4 (

**Comment by sethrj** [comment]
@adamjstewart I've got a pending PR for this: https://github.com/spack/spack/pull/10944

Long story short: it takes a *lot* of patching.
