### ISSUE TITLE
Move Spack tutorial to a separate ReadTheDocs site

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#12156]
@hauten 

The [Spack tutorial](https://spack.readthedocs.io/en/latest/tutorial.html) is currently hosted as part of the main Spack Documentation at [spack.readthedocs.io](https://spack.readthedocs.io).  Move it to its own site at [spack-tutorial.readthedocs.io](https://spack-tutorial.readthedocs.io) and link to that site from the main documentation.

### Rationale

We want to be able to version the Spack tutorial separately from Spack.  For example, there should be a version of the Spack tutorial for SC16, SC17, SC18, and SC19.  Some of these are half-day tutorials, some are full day, and some are targeted slightly differently from others.  If someone wants to host a tutorial of their own, they should be able to find the materials that best match their event.

However, the tutorial is currently versioned with Spack releases, and we only really show the latest version of the tutorial [on the tutorial page](https://spack.readthedocs.io/en/latest/tutorial.html).  People can't easily browse past tutorials -- only past Spack releases.  We also host the slides for the tutorial separately from the tutorial (we put them on spack.io), to avoid adding large files to the mainline Spack repository.  They could just be bundled with the tutorial if it were a separate repo.

### Description

- [x] Create a new `spack-tutorial` repo in the [spack organization](https://github.com/spack).
- [x] Pull the tutorial out of the main Spack repo but [keep its history intact](https://help.github.com/en/articles/splitting-a-subfolder-out-into-a-new-repository), and putit in the new repository. This may be tricky but we can start by just pulling all the docs directory out and work from there.
- [x] Refactor the new repo so that it's just the tutorial.
- [x] Set up a new readthedocs.org instance for `spack-tutorial`
- [x] Get the `spack-tutorial` repo showing up on readthedocs.
- [ ] Tag past instances of the tutorial so that they show up as "versions" on readthedocs.

### Additional information
We may also need to add a new `localized-tutorial` repo to complement [localized-docs](https://github.com/spack/localized-docs), but the tutorial isn't translated yet so we can hold off.

**Comment by bartlettroscoe** [comment]
Based on that reasoning, all of the Spack documentation should be versioned with the version of Spack, no?  The easiest way to do that is to just have the documentation in the same git repos (or use a multi-repo tool to keep them synced up).

**Comment by tgamblin** [comment]
@bartlettroscoe: all the Spack documentation IS versioned with Spack, including the tutorial.  We want to move the tutorial to a separate site that has versions by instance.  Thoughts?

**Comment by adamjstewart** [comment]
One downside of this move is that a PR that changes the API will have to be split into two PRs, one to `spack` and another to `spack-tutorial`. This may lead to people failing to update the tutorials, aside from the few times per year when we update them.

One alternative to this PR would be to add tags for tutorials (sc19, pearc19) to the main Spack repo. That way, you can still select a particular version of the docs/tutorials.

Not saying I'm opposed to this proposition, just playing devil's advocate.

**Comment by alalazo** [comment]
@adamjstewart What if we automate the procedure we are currently performing manually? Each tutorial should have an associated container image with:
- A specific branch or tag of Spack already installed
- A test script performing the basic operations we'll show during the tutorial itself.

A CI pipeline on  `spack-tutorial` for e.g. its `develop` branch could be then:

1. Update the container image if there was an update on `spack/develop`
2. Run the tutorial test script within the image and post the result

If, besides being run on every PR, we set this pipeline to run daily for `develop` then we'll catch quite soon a change in Spack that will break the tutorial.
