### ISSUE TITLE
--config-scope incompatible with environments

### ISSUE THREAD

**Issue by tjfulle** [spack/spack#12228]
If an environment is loaded, `--config-scope` is silently ignored.

If config scopes are intended to be incompatible with environments, an error should be raised when attempting to pass `--config-scope` to spack if an environment is activated.

### Details

In `lib/spack/spack/main.py`, `spack.config.command_line_scopes` is set equal to any config scopes passed by the `--config-scope` option.  However, this is done **after** activated environments are looked for.  In the process of looking for an activated environment, the `spack.config.config` singleton is instantiated, so later setting of `spack.config.command_line_scopes` has no effect and are, thus, ignored.

### Motivation

I have several environments that all depend on the same dozen or so external packages.  I don't want to duplicate the `packages` specification in every environment.  The external packages are shared by a group of developers, so it is more convenient for each to set the config scope to the shared directory containing `packages.yaml` than each duplicated the file in their `~/.spack`.

This is another use case where having `~/.spack` relocatable (#11919) would be convenient.  Sure, `--config-scope` could work (though it is broken as of now), but setting an environment variable to point to the user's config directory would be more convenient.

### Quick fix

Move the setting of command line scopes **before** looking for activated environments:

```
diff --git a/lib/spack/spack/main.py b/lib/spack/spack/main.py
index 05c1706..b4ca7df 100644
--- a/lib/spack/spack/main.py
+++ b/lib/spack/spack/main.py
@@ -628,16 +628,16 @@ def main(argv=None):
     parser.add_argument('command', nargs=argparse.REMAINDER)
     args, unknown = parser.parse_known_args(argv)

+    # make spack.config aware of any command line configuration scopes
+    if args.config_scopes:
+        spack.config.command_line_scopes = args.config_scopes
+
     # activate an environment if one was specified on the command line
     if not args.no_env:
         env = ev.find_environment(args)
         if env:
             ev.activate(env, args.use_env_repo)

-    # make spack.config aware of any command line configuration scopes
-    if args.config_scopes:
-        spack.config.command_line_scopes = args.config_scopes
-
     if args.print_shell_vars:
         print_setup_info(*args.print_shell_vars.split(','))
         return 0
```

**Comment by ChristianTackeGSI** [comment]
Hi,

I can confirm
* the problem described
* the patch above fixes it.

We're affected by this issue. I am a Python developer and want to help getting a fix into spack.

What can I do to help?

**Comment by ChristianTackeGSI** [comment]
@tjfulle :

could you post your patch as a pull request?
It works very well for us and fixes the issue.

If you don't want to, I can do it too?

**Comment by citibeth** [comment]
Environments have a config scope built-in.  The idea is they are supposed to be self-contained, that they "just work."  Having external config scops would seem to defeat the purpose here.

**Comment by ChristianTackeGSI** [comment]
First, to repeat the original poster:

> If config scopes are intended to be incompatible with environments, an error should be raised when attempting to pass `--config-scope` to spack if an environment is activated.

That said, I would still advocate for being able to layer things. Things might have different sources (people maintaining them, etc) and users might want to "mix and match".

Having a more powerful include feature (see #16454) would simplify things somewhat, because then authors could provide "defintions"-files that people include in their final environment files, where they then can "mix and match" and use include to also reference the needed config files.
