### ISSUE TITLE
QGIS package discussion

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#12281]
This is an issue to discuss creation of QGIS package file.

**Comment by Sinan81** [comment]
#12280

**Comment by rrobinson-RMS** [comment]
Hi,

is this actually working ? Has anyone compiled from it ?

I get several errors in the spec stage but manage to get past, but compilations seems to immediately error. Can provide more details if it is meant to be working.

Thanks Roger

**Comment by Sinan81** [comment]
What platform are you compiling at? It compiles just fine on any Linux.

**Comment by Sinan81** [comment]
I think it would be best if you can create a new issue ticket and ping me there.

**Comment by Sinan81** [comment]
By the way, Spack concretizer is not perfect yet. So, you will need to give it a few hints so that it concretizes:
```
spack install qgis ^gdal@2.4.2 ^ncurses+termlib ^mesa~llvm ^proj@5.2.0 ^libgeotiff@1.4.3 ^netcdf-c+mpi ^py-pyproj@1.9.6 ^python@3.7.4
```
Above `mesa~llvm` is optional (unless if you're using and old gcc.) it enables you avoid building llvm which takes quite some time.

**Comment by rrobinson-RMS** [comment]
Hi there, thanks for the hints. 

Still having some problems. Will post a ticket later.
Im using CentOS7 with Intel-Ivybridge Processes.

Which compiler should I be using ? I currently have gcc ~7.5 and gcc4.8.5 (ie CentOS7 default).

Thanks
Roger

**Comment by Sinan81** [comment]
So far, I compiled QGIS with gcc 4.8.5, 7.4.0, and 8.2.0

**Comment by Sinan81** [comment]
I am also usually compiling it on Centos7

**Comment by Sinan81** [comment]
Last time I compiled it was 1.5 months ago or so I think. I will give it a try again today or so.

**Comment by Sinan81** [comment]
just cloned latest spack, and built QGIS without problems. I cam curious what errors you're getting.

**Comment by rrobinson-RMS** [comment]
So I re-cloned spack and made sure it only had access to gcc 4.8.5 and it fails to build qt/5.14.2 which was happening before will try and get you logs.

**Comment by Sinan81** [comment]
I know for a fact latest llvm won't build with gcc 4.8.5. So, I would suggest you try building qt with `^mesa~llvm` option.

**Comment by rrobinson-RMS** [comment]
yes I did which gcc compiling on ?

**Comment by Sinan81** [comment]
I recently compiled qt (as a dependency of qgis) with gcc@4.8.5. Let's take this discussion to a new issue. There are quite a few qt spack package maintainers which can help more.

**Comment by Sinan81** [comment]
Also, in my case qt won't build with gcc@4.8.5:
```
             optrq3ikcx6a34k5ql42c4r45il/spack-src/qtbase/config.tests/x86_simd/main.cpp
  >> 201     > g++: error: unrecognized command line option '-mavx512f'
  >> 202     > gmake: *** [main.o] Error 1
```
I think the reason is that spack is optimizing the build for skylake (although initially it says it will optimize it for haswell since that's the best gcc@4.8.5 can support). I think previously I built latest qt with gcc@4.8.5 for a generic x86_64 arch.

**Comment by Sinan81** [comment]
Also, it seems qt@5.13 is last version that supports gcc@4.8  as shown in the "Generic Linux" section.

https://doc.qt.io/archives/qt-5.13/supported-platforms.html

https://doc.qt.io/qt-5.14/supported-platforms.html

**Comment by rrobinson-RMS** [comment]
Hi Im coming back to this, what is the latest recommended install line for CentOS7 ?

**Comment by Sinan81** [comment]
There has been minor improvements to qgis and qt since your last communication. However, it seems there is also a minor regression:
```
sbulut@ws-067 /mnt/local/spack (develop) 
$ spack spec qgis ^gdal@2.4.2 ^proj@5.2.0 ^libgeotiff@1.4.3 ^netcdf-c+mpi ^py-pyproj@1.9.6
Input spec
--------------------------------
qgis
    ^gdal@2.4.2
    ^libgeotiff@1.4.3
    ^netcdf-c+mpi
    ^proj@5.2.0
    ^py-pyproj@1.9.6

Concretized
--------------------------------
==> Error: Package 'libglvnd-fe' not found.
```
This is a very minor issue, that should be sorted out today or so. I will be creating a ticket for it.

**Comment by Sinan81** [comment]
It turns out one needs to specify a gl provider to avoid this bug. See the discussion at https://github.com/spack/spack/issues/17512
So, you should be able to install qgis with the following command:
```
spack install qgis ^gdal@2.4.2 ^proj@5.2.0 ^libgeotiff@1.4.3 ^py-pyproj@1.9.6 ^mesa+opengl
```
Afterwards, you can play around with the constrains like proj version etc to get the installation spec suit your needs. Once, dependency concretization is perfected in Spack, all you need to do will be `spack install qgis`. But for now we need to provide some hints to spack
If default compiler in Spack is gcc@4.8.5, then you might need to add a few more hints:
```
spack install qgis ^gdal@2.4.2 ^proj@5.2.0 ^libgeotiff@1.4.3 ^py-pyproj@1.9.6 ^mesa+opengl ^llvm@7.1.0  ^qt@5.13.1 %gcc@4.8.5 ^icu4c@66.1
```

**Comment by Sinan81** [comment]
it seems a dependency of qgis, py-psycopg2, won't build with latest python. Hence you might want to constrain python version. For example, `^python@3.7.8`

**Comment by Sinan81** [comment]
I just built qgis and all its dependencies from scratch via the following command on spack v0.15.4 checkout with gcc@8.3.0 
```
spack install qgis ^gdal@2.4.2 ^proj@5.2.0 ^libgeotiff@1.4.3 ^py-pyproj@1.9.6 ^hdf5+hl ^python@3.7.4 ^mesa~llvm ^py-pyqt5+qsci_api
```

**Comment by rrobinson-RMS** [comment]
Ok Trying from a fresh install CentOS7 with gcc 8.3.0.

Im not sure what you mean by spack v0.15.4 checkout. This doesnt seem to work for me.

[hpcadmin@ukvmlx-head-05 spack_Oct_2020]$ git checkout releases/v0.15.4
error: pathspec 'releases/v0.15.4' did not match any file(s) known to git.

I've tried 0.15 but get this error.

[hpcadmin@ukvmlx-head-05 spack_Oct_2020]$ git checkout releases/v0.15
Already on 'releases/v0.15'
[hpcadmin@ukvmlx-head-05 spack_Oct_2020]$ git branch
  develop
* releases/v0.15
[hpcadmin@ukvmlx-head-05 spack_Oct_2020]$ git branch -a | grep 15
* releases/v0.15
  remotes/origin/releases/v0.15
[hpcadmin@ukvmlx-head-05 spack_Oct_2020]$ spack install qgis ^gdal@2.4.2 ^proj@5.2.0 ^libgeotiff@1.4.3 ^py-pyproj@1.9.6 ^hdf5+hl ^python@3.7.4 ^mesa~llvm ^py-pyqt5+qsci_api
==> Error: Package 'flexiblas' not found.


So I've gone back to develop which is proceeding.

[hpcadmin@ukvmlx-head-05 spack_Oct_2020]$ git checkout develop
Switched to branch 'develop'                                                                                                                                                                                       
[hpcadmin@ukvmlx-head-05 spack_Oct_2020]$ spack install qgis ^gdal@2.4.2 ^proj@5.2.0 ^libgeotiff@1.4.3 ^py-pyproj@1.9.6 ^hdf5+hl ^python@3.7.4 ^mesa~llvm ^py-pyqt5+qsci_api                                
==> Installing libiconv                                                                                                                                                                                            
==> No binary for libiconv found: installing from source                                                                                                                                                           
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/e6/e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04.tar.gz                                                 

I've been trying various things over the summer ie gcc 7.5. But it always seems to fail on some dependency or another. Still not managed to compile qgis 3+ from the command line either.

Something always fails. Thinking I might need to set up some CentOS8 boxes.

**Comment by rrobinson-RMS** [comment]
Worked fine until this bit. Was close to getting most dependencies installed.


```
==> Installing harfbuzz
==> No binary for harfbuzz found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/66/6648a571a27f186e47094121f0095e1b809e918b3037c630c7f38ffad86e3035.tar.xz
######################################################################## 100.0%
==> harfbuzz: Executing phase: 'autoreconf'
==> harfbuzz: Executing phase: 'configure'
==> Error: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/mnt/opt/Centos7/hpc/spack/spack_Oct_2020/var/spack/repos/builtin/packages/harfbuzz/package.py:48, in configure_args:
         45        # disable building of gtk-doc files following #9771
         46        args.append('--disable-gtk-doc-html')
         47        true = which('true')
        48        args.append('CXXFLAGS={0}'.format(self.compiler.cxx11_flag))
         49        args.append('GTKDOC_CHECK={0}'.format(true))
         50        args.append('GTKDOC_CHECK_PATH={0}'.format(true))
         51        args.append('GTKDOC_MKPDF={0}'.format(true))
```

**Comment by Sinan81** [comment]
Can you do, the following and try again

```
cd /path/to/spack
git checkout v0.15.4
```

**Comment by Sinan81** [comment]
just saw your comment above regarding v0.15.4. In order to prevent  `flexiblas` error, you might want o start with a fresh `~/.spack` folder.

**Comment by Sinan81** [comment]
@rrobinson-RMS The build error you mention is above is unrelated to QGIS, so I strongly recommend you open an new issue for this build error, as well as others, so that the Spack team can help you.

That being said I think there might be  a couple of reasons why you often experience such build errors while building QGIS from scratch:

- qgis has a lot of dependencies: ~150 packages
- using develop branch of Spack as opposed to releases might lead to weird build errors as expected.

I will be again closing this issue. Please open a new one, and reference this issue in it. That way Spack developers will also be able to help you.
