### ISSUE TITLE
cmake fails to build on summit with gcc compilers

### ISSUE THREAD

**Issue by danlipsa** [spack/spack#12285]
<pre>
[danlipsa@login3.summit spack]$ spack install cmake
==> pkgconf is already installed in /autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/pkgconf-1.6.1-znpunnixizfbyadqx3e2iysu3rerjswe
==> ncurses is already installed in /autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/ncurses-6.1-z6zsfbukgxfvuh6ex2h6w36r4at7zvtn
==> readline is already installed in /autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/readline-7.0-mnwhp6dwqeg7xr3g4j6ysruecozpvpyq
==> gdbm is already installed in /autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/gdbm-1.18.1-hvpojhibkekkkeivdokpuxtm4ag3vhi7
==> perl is already installed in /autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/perl-5.26.2-hq4it4cb7lki4uxl2w4ksj64477mq4wh
==> zlib is already installed in /autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/zlib-1.2.11-fvgnqf6k3ffhltldndu7pmntzvoyfsk4
==> openssl is already installed in /autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/openssl-1.1.1b-xsrenwttzknubrjgcyvn4emuysiyyzku
==> Installing cmake
==> Searching for binary cache of cmake
==> Warning: No Spack mirrors are currently configured
==> No binary for cmake found: installing from source
==> Using cached archive: /autofs/nccs-svm1_home1/danlipsa/projects/spack/var/spack/cache/cmake/cmake-3.15.1.tar.gz
==> Staging archive: /autofs/nccs-svm1_home1/danlipsa/projects/spack/var/spack/stage/cmake-3.15.1-j7qi3b5yu3zein4nja7h3iowyy235rrn/cmake-3.15.1.tar.gz
==> Created stage in /autofs/nccs-svm1_home1/danlipsa/projects/spack/var/spack/stage/cmake-3.15.1-j7qi3b5yu3zein4nja7h3iowyy235rrn
==> No patches needed for cmake
==> Building cmake [Package]
==> Executing phase: 'bootstrap'
==> Error: ProcessError: Command exited with status 11:
    './bootstrap' '--prefix=/autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/cmake-3.15.1-j7qi3b5yu3zein4nja7h3iowyy235rrn' '--parallel=16' '--no-system-libs' '--no-qt-gui' '--' '-DCMAKE_USE_OPENSSL=True'

1 error found in build log:
     230    /autofs/nccs-svm1_home1/danlipsa/projects/spack/lib/spack/env/gcc/g
            cc           -I/tmp/danlipsa/spack-stage/spack-stage-weJTOH/spack-s
            rc/Bootstrap.cmk   -I/tmp/danlipsa/spack-stage/spack-stage-weJTOH/s
            pack-src/Source   -I/tmp/danlipsa/spack-stage/spack-stage-weJTOH/sp
            ack-src/Source/LexerParser   -I/tmp/danlipsa/spack-stage/spack-stag
            e-weJTOH/spack-src/Utilities  -DCMAKE_BOOTSTRAP -D_GNU_SOURCE -I/tm
            p/danlipsa/spack-stage/spack-stage-weJTOH/spack-src/Utilities/cmlib
            uv/include -I/tmp/danlipsa/spack-stage/spack-stage-weJTOH/spack-src
            /Utilities/cmlibuv/src/unix -I/tmp/danlipsa/spack-stage/spack-stage
            -weJTOH/spack-src/Utilities/cmlibuv/src -c /tmp/danlipsa/spack-stag
            e/spack-stage-weJTOH/spack-src/Utilities/cmlibuv/src/unix/signal.c 
            -o uv-src-unix-signal.c.o
     231    /autofs/nccs-svm1_home1/danlipsa/projects/spack/lib/spack/env/gcc/g
            cc           -I/tmp/danlipsa/spack-stage/spack-stage-weJTOH/spack-s
            rc/Bootstrap.cmk   -I/tmp/danlipsa/spack-stage/spack-stage-weJTOH/s
            pack-src/Source   -I/tmp/danlipsa/spack-stage/spack-stage-weJTOH/sp
            ack-src/Source/LexerParser   -I/tmp/danlipsa/spack-stage/spack-stag
            e-weJTOH/spack-src/Utilities  -DCMAKE_BOOTSTRAP -D_GNU_SOURCE -I/tm
            p/danlipsa/spack-stage/spack-stage-weJTOH/spack-src/Utilities/cmlib
            uv/include -I/tmp/danlipsa/spack-stage/spack-stage-weJTOH/spack-src
            /Utilities/cmlibuv/src/unix -I/tmp/danlipsa/spack-stage/spack-stage
            -weJTOH/spack-src/Utilities/cmlibuv/src -c /tmp/danlipsa/spack-stag
            e/spack-stage-weJTOH/spack-src/Utilities/cmlibuv/src/unix/stream.c 
            -o uv-src-unix-stream.c.o
     232    /autofs/nccs-svm1_home1/danlipsa/projects/spack/lib/spack/env/gcc/g
            ++   -std=gnu++11      -I/tmp/danlipsa/spack-stage/spack-stage-weJT
            OH/spack-src/Bootstrap.cmk   -I/tmp/danlipsa/spack-stage/spack-stag
            e-weJTOH/spack-src/Source   -I/tmp/danlipsa/spack-stage/spack-stage
            -weJTOH/spack-src/Source/LexerParser   -I/tmp/danlipsa/spack-stage/
            spack-stage-weJTOH/spack-src/Utilities  cmAddCustomCommandCommand.o
             cmAddCustomTargetCommand.o cmAddDefinitionsCommand.o cmAddDependen
            ciesCommand.o cmAddExecutableCommand.o cmAddLibraryCommand.o cmAddS
            ubDirectoryCommand.o cmAddTestCommand.o cmArgumentParser.o cmBreakC
            ommand.o cmBuildCommand.o cmCMakeMinimumRequired.o cmCMakePolicyCom
            mand.o cmCPackPropertiesGenerator.o cmCacheManager.o cmCommand.o cm
            CommandArgumentParserHelper.o cmCommands.o cmCommonTargetGenerator.
            o cmComputeComponentGraph.o cmComputeLinkDepends.o cmComputeLinkInf
            ormation.o cmComputeTargetDepends.o cmConditionEvaluator.o cmConfig
            ureFileCommand.o cmContinueCommand.o cmCoreTryCompile.o cmCreateTes
            tSourceList.o cmCustomCommand.o cmCustomCommandGenerator.o cmDefine
            PropertyCommand.o cmDefinitions.o cmDepends.o cmDependsC.o cmDisall
            owedCommand.o cmDocumentationFormatter.o cmEnableLanguageCommand.o 
            cmEnableTestingCommand.o cmExecProgramCommand.o cmExecuteProcessCom
            mand.o cmExpandedCommandArgument.o cmExportBuildFileGenerator.o cmE
            xportFileGenerator.o cmExportInstallFileGenerator.o cmExportSet.o c
            mExportSetMap.o cmExportTryCompileFileGenerator.o cmExprParserHelpe
            r.o cmExternalMakefileProjectGenerator.o cmFileCommand.o cmFileCopi
            er.o cmFileInstaller.o cmFileTime.o cmFileTimeCache.o cmFileTimes.o
             cmFindBase.o cmFindCommon.o cmFindFileCommand.o cmFindLibraryComma
            nd.o cmFindPackageCommand.o cmFindPathCommand.o cmFindProgramComman
            d.o cmForEachCommand.o cmFunctionCommand.o cmFSPermissions.o cmGene
            ratedFileStream.o cmGeneratorExpression.o cmGeneratorExpressionCont
            ext.o cmGeneratorExpressionDAGChecker.o cmGeneratorExpressionEvalua
            tionFile.o cmGeneratorExpressionEvaluator.o cmGeneratorExpressionLe
            xer.o cmGeneratorExpressionNode.o cmGeneratorExpressionParser.o cmG
            eneratorTarget.o cmGetCMakePropertyCommand.o cmGetDirectoryProperty
            Command.o cmGetFilenameComponentCommand.o cmGetPipes.o cmGetPropert
            yCommand.o cmGetSourceFilePropertyCommand.o cmGetTargetPropertyComm
            and.o cmGetTestPropertyCommand.o cmGlobalCommonGenerator.o cmGlobal
            Generator.o cmGlobalUnixMakefileGenerator3.o cmGlobVerificationMana
            ger.o cmHexFileConverter.o cmIfCommand.o cmIncludeCommand.o cmInclu
            deGuardCommand.o cmIncludeDirectoryCommand.o cmIncludeRegularExpres
            sionCommand.o cmInstallCommand.o cmInstallCommandArguments.o cmInst
            allDirectoryGenerator.o cmInstallExportGenerator.o cmInstallFilesCo
            mmand.o cmInstallFilesGenerator.o cmInstallGenerator.o cmInstallScr
            iptGenerator.o cmInstallSubdirectoryGenerator.o cmInstallTargetGene
            rator.o cmInstallTargetsCommand.o cmInstalledFile.o cmLinkDirectori
            esCommand.o cmLinkItem.o cmLinkLineComputer.o cmLinkLineDeviceCompu
            ter.o cmListCommand.o cmListFileCache.o cmLocalCommonGenerator.o cm
            LocalGenerator.o cmLocalUnixMakefileGenerator3.o cmMSVC60LinkLineCo
            mputer.o cmMacroCommand.o cmMakeDirectoryCommand.o cmMakefile.o cmM
            akefileExecutableTargetGenerator.o cmMakefileLibraryTargetGenerator
            .o cmMakefileTargetGenerator.o cmMakefileUtilityTargetGenerator.o c
            mMarkAsAdvancedCommand.o cmMathCommand.o cmMessageCommand.o cmMesse
            nger.o cmNewLineStyle.o cmOSXBundleGenerator.o cmOptionCommand.o cm
            OrderDirectories.o cmOutputConverter.o cmParseArgumentsCommand.o cm
            PathLabel.o cmPolicies.o cmProcessOutput.o cmProjectCommand.o cmPro
            perty.o cmPropertyDefinition.o cmPropertyDefinitionMap.o cmProperty
            Map.o cmReturnCommand.o cmRulePlaceholderExpander.o cmScriptGenerat
            or.o cmSearchPath.o cmSeparateArgumentsCommand.o cmSetCommand.o cmS
            etDirectoryPropertiesCommand.o cmSetPropertyCommand.o cmSetSourceFi
            lesPropertiesCommand.o cmSetTargetPropertiesCommand.o cmSetTestsPro
            pertiesCommand.o cmSiteNameCommand.o cmSourceFile.o cmSourceFileLoc
            ation.o cmState.o cmStateDirectory.o cmStateSnapshot.o cmStringRepl
            aceHelper.o cmStringCommand.o cmSubdirCommand.o cmSystemTools.o cmT
            arget.o cmTargetCompileDefinitionsCommand.o cmTargetCompileFeatures
            Command.o cmTargetCompileOptionsCommand.o cmTargetIncludeDirectorie
            sCommand.o cmTargetLinkLibrariesCommand.o cmTargetPropCommandBase.o
             cmTargetPropertyComputer.o cmTargetSourcesCommand.o cmTest.o cmTes
            tGenerator.o cmTimestamp.o cmTryCompileCommand.o cmTryRunCommand.o 
            cmUnexpectedCommand.o cmUnsetCommand.o cmUVHandlePtr.o cmUVProcessC
            hain.o cmVersion.o cmWhileCommand.o cmWorkingDirectory.o cmake.o cm
            akemain.o cmcmd.o cm_string_view.o cmCommandArgumentLexer.o cmComma
            ndArgumentParser.o cmExprLexer.o cmExprParser.o cmListFileLexer.o D
            irectory.o EncodingCXX.o FStream.o Glob.o RegularExpression.o Syste
            mTools.o EncodingC.o ProcessUNIX.o String.o System.o Terminal.o uv-
            src-strscpy.c.o uv-src-timer.c.o uv-src-uv-common.c.o uv-src-unix-c
            make-bootstrap.c.o uv-src-unix-core.c.o uv-src-unix-fs.c.o uv-src-u
            nix-loop.c.o uv-src-unix-loop-watcher.c.o uv-src-unix-no-fsevents.c
            .o uv-src-unix-pipe.c.o uv-src-unix-poll.c.o uv-src-unix-posix-hrti
            me.c.o uv-src-unix-posix-poll.c.o uv-src-unix-process.c.o uv-src-un
            ix-signal.c.o uv-src-unix-stream.c.o  -ldl -lrt -o cmake
     233    /tmp/danlipsa/spack-stage/spack-stage-weJTOH/spack-src/Bootstrap.cm
            k/cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not fo
            und (required by /tmp/danlipsa/spack-stage/spack-stage-weJTOH/spack
            -src/Bootstrap.cmk/cmake)
     234    /tmp/danlipsa/spack-stage/spack-stage-weJTOH/spack-src/Bootstrap.cm
            k/cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not fo
            und (required by /tmp/danlipsa/spack-stage/spack-stage-weJTOH/spack
            -src/Bootstrap.cmk/cmake)
     235    ---------------------------------------------
  >> 236    Error when bootstrapping CMake:
     237    Problem while running initial CMake
     238    ---------------------------------------------

See build log for details:
  /autofs/nccs-svm1_home1/danlipsa/projects/spack/var/spack/stage/cmake-3.15.1-j7qi3b5yu3zein4nja7h3iowyy235rrn/spack-build-out.txt

[danlipsa@login3.summit spack]$ spack compiler list
==> Available compilers
-- gcc rhel7-ppc64le --------------------------------------------
gcc@6.4.0  gcc@4.8.5
[danlipsa@login3.summit spack]$ module -t list
hsi/5.0.2.p5
xalt/1.1.3
lsf-tools/2.0
darshan-runtime/3.1.7
DefApps
gcc/6.4.0
spectrum-mpi/10.3.0.1-20190611
</pre>

**Comment by danlipsa** [comment]
@chuckatkins Any suggestions? Thanks!

**Comment by chuckatkins** [comment]
The linker error for missing symbols usually comes up when you don't have the compiler module loaded before hand.  Spack should load the module for the compiler so I'm not sure why that doesn't seem to be happening.  Can you try manually loading the module for gcc-6.4.0 and then try building again?

**Comment by danlipsa** [comment]
@chuckatkins They seem to be loaded. Look at the end I have a 'module -t list' command executed that lists gcc/6.4.0

**Comment by danlipsa** [comment]
Strangely, if I run this from the files left by spack it finishes without errors.
<pre>
[danlipsa@login3.summit spack]$ cd /autofs/nccs-svm1_home1/danlipsa/projects/spack/var/spack/stage/cmake-3.15.1-j7qi3b5yu3zein4nja7h3iowyy235rrn/ 
[danlipsa@login3.summit cmake-3.15.1-j7qi3b5yu3zein4nja7h3iowyy235rrn]$ . spack-build-env.txt 
[danlipsa@login3.summit spack-src]$ './bootstrap' '--prefix=/autofs/nccs-svm1_home1/danlipsa/projects/spack/opt/spack/linux-rhel7-ppc64le/gcc-6.4.0/cmake-3.15.1-j7qi3b5yu3zein4nja7h3iowyy235rrn' '--parallel=16' '--no-system-libs' '--no-qt-gui' '--' '-DCMAKE_USE_OPENSSL=True'
</pre>

**Comment by mwkrentel** [comment]
@danlipsa Here's a wild a crazy question that just might work.
What does this report?

```
spack compiler info gcc
```

**Comment by danlipsa** [comment]
<pre>
[danlipsa@login3.summit ~]$ spack compiler info gcc
gcc@4.8.5:
	paths:
		cc = /usr/bin/gcc
		cxx = /usr/bin/g++
		f77 = /usr/bin/gfortran
		fc = /usr/bin/gfortran
	modules  = []
	operating system  = rhel7
gcc@6.4.0:
	paths:
		cc = /sw/summit/gcc/6.4.0/bin/gcc
		cxx = /sw/summit/gcc/6.4.0/bin/g++
		f77 = /sw/summit/gcc/6.4.0/bin/gfortran
		fc = /sw/summit/gcc/6.4.0/bin/gfortran
	modules  = []
	operating system  = rhel7
</pre>

**Comment by chuckatkins** [comment]
It looks like the compiler configuration for spack isn't loading the necessary module, i.e. `modules = []`.  Try adding the module to the spack compiler configuration.

**Comment by danlipsa** [comment]
YES! Thanks Chuck! Indeed, this solved it. Should I leave this as a bug?

**Comment by chuckatkins** [comment]
It can be closed.  It's certainly not a cmake bug.  If anything, it's an issues with proper compiler detection, but not auto-detecting the modules to load is a known issue.  It is, however, covered in the Getting Started portion of the docs, https://spack.readthedocs.io/en/latest/getting_started.html#compilers-requiring-modules, it's just often overlooked.

**Comment by mwkrentel** [comment]
@tgamblin See, it's reports like this that make me want to nag you
about spack automatically filling in the `modules:` field in
`compilers.yaml`.  Spack does this on Cray, but not elsewhere.

Technically, this is pilot error, but it's a very easy mistake to
make.

I've asked about this before in #9376 and #10790, but they didn't get
any traction.

@chuckatkins The suggestion about loading the module is only half the
story.  It didn't work because spack install erases all of your
modules.  You have to load the module(s) and run `spack install --dirty`
which probably would work.

`--dirty` should never be necessary.  But if `--dirty` works when
clean doesn't, that's a dead giveaway that you're missing a module
specification.

@danlipsa The good news is that you only have to fix this once.  This
sort of problem affects many packages, not just cmake.  But once
you've fixed it, then all packages are fixed, at least for that compiler.
