### ISSUE TITLE
spack concretize reorganizes spack.yaml

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#12313]
The way Spack Environments were explained to me was that if you maintained a project on GitHub, you could add a `spack.yaml` file to your repo that lists its dependencies. Then you could clone the project, cd into the directory, and run `spack install` or `spack concretize; spack install` to install all of its dependencies. However, `spack concretize` appears to modify `spack.yaml`, a file which is likely to be under version control. No other Spack command that I know of reorganizes your configuration files, and `spack concretize` certainly shouldn't either.

### Steps to reproduce the issue

```console
$ cat spack.yaml
spack:
  specs:
  - 'gdal+python'
  - 'python@3:+sqlite3'
  - 'py-earthengine-api'
  - 'py-flake8'
  - 'py-matplotlib'
  - 'py-numpy'
  - 'py-pandas'
  - 'py-pytest@3.9:'
  - 'py-scikit-learn'
  - 'py-scipy@0.14:'
  - 'py-tables'
  - 'py-torch@0.4:'
  - 'py-torchvision'
$ spack concretize
...
$ cat spack.yaml
spack:
  specs:
  - gdal+python
  - python@3:+sqlite3
  - py-earthengine-api
  - py-flake8
  - py-matplotlib
  - py-numpy
  - py-pandas
  - 'py-pytest@3.9:'
  - py-scikit-learn
  - 'py-scipy@0.14:'
  - py-tables
  - 'py-torch@0.4:'
  - py-torchvision
  config: {}
  mirrors: {}
  modules:
    enable: []
  packages: {}
  repos: []
  upstreams: {}
  definitions: []
  view:
    default:
      root: /Users/Adam/Documents/UIUC/Research/Crops/crop_classification/.spack-env/view
      projections: {}
```
Removing quotes on specs containing `:` is one thing, but adding a root that is computer-specific makes it possible to maintain this file under version control.

@tgamblin @citibeth

**Comment by citibeth** [comment]
I agree, this is not nice.  Actually, I maintain a Spack fork on GitHub,
and the environments I use are maintained as `spack.yaml` files within it.

**Comment by alalazo** [comment]
I stumbled on that too, and was about to open an issue. I don't think Spack should modify `spack.yaml` when producing `spack.lock`. It's a very weird use case to:
- Write manually your `spack.yaml`
- Concretize and produce `spack.lock`
- Find out that `spack.yaml` has been rewritten and new attributes have been added to it

**Comment by scheibelp** [comment]
Ultimately we decided `spack.yaml` could be modified by Spack. For example that `spack add` can add specs. Would it be annoying to maintain a separate copy (e.g. if you want to regenerate the environment from scratch)? We could also add options to copy the `spack.yaml` file and manage it separately.

Overall I can generally agree that this may not be desirable, but if @citibeth @adamjstewart @alalazo you could mention the use cases you have which this interferes with I think that would help us figure out how to address it.

> No other Spack command that I know of reorganizes your configuration files, and spack concretize certainly shouldn't either.

Most commands can modify `compilers.yaml`, and generally Spack isn't shy about reaching into any configuration file as long as it lives in a scope that it is aware of, but your point stands that this isn't necessarily desirable behavior for `spack.yaml`.

**Comment by adamjstewart** [comment]
> if @citibeth @adamjstewart @alalazo you could mention the use cases you have which this interferes with I think that would help us figure out how to address it.

My use case is as follows. I have a GitHub repo for a research project I'm working on. This project depends on several Python and C libraries that I would like to install with Spack. I check a `spack.yaml` file into my Git repo and then I can clone and `spack install` and go. The issue with Spack modifying `spack.yaml` is that it is often under version control. 

Yes, commands like `spack compiler add` modify `compilers.yaml`, but this is expected. I would not expect `spack install` to modify `spack.yaml`. Honestly, I would be fine with Spack modifying `spack.yaml` as long as it didn't specify a computer-specific `root` inside. Because of that, the file is impossible to version control and share across multiple computers.

**Comment by alalazo** [comment]
@scheibelp Commands like `spack add` are meant to modify `spack.yaml`, so it's absolutely fine to do it. What is unexpected is that `spack concretize` and `spack install`, that are meant to take `spack.yaml` as input, end up overwriting it.

**Comment by citibeth** [comment]
My use case is similar to @adamjstewart's.  In my case, I maintain a fork of Spack, and I put my environments in that fork as `spack.yaml` files:

https://github.com/citibeth/spack/tree/efischer/giss2/var/spack/environments

When I want to build the environment (from scratch), I do something like:
```
git pull
spack -e myenv concretize -f
spack -e myenv install
spack -e myenv env loads
```

Obviously, automatically overwriting files under version control is a bad idea.  When combined with Docker, it created some additional annoyances.  I ran something like the above in one Docker script to install the environment.  That prevented any future `git pull` commands on my Spack fork because `spack.yaml` had been changed.  In order to `git pull`, I first had to `git stash`.  But that had its own problems because the in-Docker-container git did not have proper usernames set up for that kind of stuff.  All in all, a big headache.

**Comment by tgamblin** [comment]
> Ultimately we decided spack.yaml could be modified by Spack. For example that spack add can add specs. Would it be annoying to maintain a separate copy (e.g. if you want to regenerate the environment from scratch)? We could also add options to copy the spack.yaml file and manage it separately.

This misses the point.  We want spack environments to be usable via the command line, yes, and there are commands like `spack add` and `spack remove` that need to add things to lists in the file.  I think their changes should be minimal as well (which is why we used ruamel to modify the file instead of `pyyaml`).

However, this issue is about `spack concretize` and `spack install` which shouldn't have to touch `spack.yaml` at all.  They should just do their job and write `spack.lock`.

**Comment by tgamblin** [comment]
Oh looks like @alalazo already said the same thing 😄

**Comment by citibeth** [comment]
To put in in a wider context, `spack edit` edits `package.py` files.  But
that doesn't mean that Spack can auto-edit those files whenever it feels
like it.

>

**Comment by scheibelp** [comment]
I appreciate the responses and I think they clarify a few things:

* https://github.com/spack/spack/issues/12313#issuecomment-519651718 is ok with *some* automatic edits to `spack.yaml` but not hardcoded paths etc. which are totally wrong for version control
* https://github.com/spack/spack/issues/12313#issuecomment-519996564 appears to be totally against all modifications to `spack.yaml` that are not from commands like `spack add` (the analog to explicit configuration editing commands like `spack repo add`)

The first is absolutely avoidable and I 100% agree with it (and is probably simple to fix). The second may require more significant editing (but would be necessary if we want to avoid the concerns brought up in the second point). In other words perhaps this can be distilled into a set of requirements and those requirements addressed with separate PRs.

**Comment by tgamblin** [comment]
@scheibelp: I think we really want both of these.  I think it's worth making issues for them.
