### ISSUE TITLE
Issue with spack on Tianhe-2 supercomputer in China

### ISSUE THREAD

**Issue by hongjianweng** [spack/spack#12355]
When I try to use spack to install netcdf on our own servers and Tianhe-2 supercomputer, it shows that the servers cannot resolve  Spack mirrors. I think it may be because of the network of servers. I also contacted with the engineer of Tianhe-2, he told me that they directly install library instead of using spack which is not very useful because of the complexity of supercomputer cluster. 

The errors are as follows:

h 
[blsc407@lon12%tianhe2-B ~]$ spack install netcdf-fortran 
==> Installing libsigsegv
==> Searching for binary cache of libsigsegv
==> Warning: No Spack mirrors are currently configured
==> No binary for libsigsegv found: installing from source
==> Fetching https://ftpmirror.gnu.org/libsigsegv/libsigsegv-2.11.tar.gz
curl: (6) Couldn't resolve host 'ftpmirror.gnu.org'
==> Fetching from https://ftpmirror.gnu.org/libsigsegv/libsigsegv-2.11.tar.gz failed.
==> Error: FetchError: All fetchers failed for libsigsegv-2.11-xqiyghtlms7lwgexu3wh7zdtbw6lnytl

/PARA/blsc407/spack-develop/lib/spack/spack/package.py:1051, in do_fetch:
       1048                raise FetchError("Will not fetch %s" %
       1049                                 self.spec.format('{name}{@version}'), ck_msg)
       1050
  >>   1051        self.stage.create()
       1052        self.stage.fetch(mirror_only)
       1053        self._fetch_time = time.time() - start_time

**Comment by ax3l** [comment]
Hi @hongjianweng,

from similar reports, it looks like your internet access on that machine is routed to some kind of proxy. Maybe correspond with your local sysadmin to set the proxy for `curl` (`$HOME/.curlrc`) and `git` (`$HOME/.gitconfig`) properly? It's looking very much like a general network issue.

**Comment by scheibelp** [comment]
> curl: (6) Couldn't resolve host 'ftpmirror.gnu.org'

I agree with https://github.com/spack/spack/issues/12355#issuecomment-520046885. Can you reach this site outside of Spack from your machine?

**Comment by tgamblin** [comment]
Closing this as I think it's an issue with machine connectivity to the internet.  Please reopen if setting a proxy or using `spack mirror` doesn't work!
