### ISSUE TITLE
`spack pkg` command and tests fail for git < 1.8.5

### ISSUE THREAD

**Issue by chissg** [spack/spack#12448]
The implementation of the `spack pkg` command assumes one is working in an environment with a git >= 1.8.5, as the `-C` option is used for all invocations of the `git` command. Associated tests also fail, see `spack test cmd/pkg`:

```console
$ spack test cmd/pkg
...
E                                  ProcessError: Command exited with status 129:
E                                      '/usr/bin/git' '-C' '/tmp/pytest-of-greenc/pytest-52/mock_pkg_git_repo0/builtin.mock/packages' 'ls-tree' '--name-only' 'HEAD^^'

../util/executable.py:189: ProcessError
-------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

On a standard `Scientific7` (or `RHEL7`) system, the version of git available is `1.8.3.1`. On `RHEL6` (still in extensive use in HEP), it is `1.7.1`.

A reasonable solution might be to test for the version and fall back on a function wrapper to the git `Executable` that invokes it with the current directory corresponding to the desired `path`.

**Comment by adamjstewart** [comment]
We can also skip the tests if an old version of git is detected. But then `spack pkg` won't work for all users... @tgamblin

**Comment by chissg** [comment]
@adamjstewart Note that this is not really a "general test" issue, but that the underlying functionality is dependent upon a feature of an external command (`git`) that may not always be present. This issue does have implications for specific test results, but I don't think it fits into the category of, "General test capability(ies)."
