### ISSUE TITLE
Installation of Valgrind +MPI with Intel Using Auto Dispatch Variant

### ISSUE THREAD

**Issue by kmanalo** [spack/spack#12469]
This is probably targeted for @glennpj or others with better awareness of `-ax<vectorization>` for auto dispatch.

Is there a way to disable `-ax<option>` while building tools like Valgrind, after setting building Intel compilers with `auto_dispatch=COMMON_AVX512`?

My workaround is to remove the added lines to the matching `{icpc,icc,ifort}.cfg` files.

### Steps to reproduce the issue

An example spec looks something like this where I really have `intel` in place of `intel-parallel-studio`

```
valgrind@3.15.0 %intel@18.0.5 ^mvapich2@2.3.1
```

This is consistent across Intel 18 and 19 latest compilers, where in my case I had `-axCOMMON-AVX512` appended to the aforementioned `cfg` files.

### Error Message

```
  >> 5870    /usr/local/pace-apps/temp/spack/var/0.12/stage/kmanalo3/spack-stag
             e/spack-stage-fBlVLy/spack-src/coregrind/m_wordfm.c:706: undefined
              reference to `__intel_cpu_feature_indicator'
  >> 5871    /usr/local/pace-apps/temp/spack/var/0.12/stage/kmanalo3/spack-stag
             e/spack-stage-fBlVLy/spack-src/coregrind/m_wordfm.c:706: undefined
              reference to `__intel_cpu_feature_indicator'
  >> 5872    /usr/local/pace-apps/temp/spack/var/0.12/stage/kmanalo3/spack-stag
             e/spack-stage-fBlVLy/spack-src/coregrind/m_wordfm.c:706: undefined
              reference to `__intel_cpu_features_init'
```

These are typical errors.

### Information on your system

`linux_x86_64`
Cascade Lake systems
RHEL7.6

**Comment by glennpj** [comment]
@kmanalo I think there are two ways to do it.

1. Pass cflags to the spec
```spack install valgrind cflags='-axOFF'```

1. Install an instance of the compiler with no auto dispatch options and set that up in your compilers.yaml file with a different spec name, ie., intel@19.0.4_base
This has the advantage of having spack keep track of packages built with that compiler.

**Comment by kmanalo** [comment]
Thanks @glennpj I'll give 1 a try first!  We do use the technique present in 2, but for a different reason.
