### ISSUE TITLE
Multiple users of spack on a system broken (permissions errors)

### ISSUE THREAD

**Issue by steffen-AEI** [spack/spack#12485]
Today, I cloned spack (default branch "develop") into ~/SPACK, and went through the usual steps.

I failed very early, with neither "spack bootstrap" nor "spack install $package" working.

*Explain, in a clear and concise way, the command you ran and the result you were trying to achieve.
Example: "I ran Spack find to list all the installed packages and..."*

### Steps to reproduce the issue

```console
[myname@ac922 ~]$ . ~/SPACK/share/spack/setup-env.sh
[myname@ac922 ~]$ spack bootstrap
==> Installing environment-modules@4.3.0%gcc@4.8.5~X arch=linux-rhel7-ppc64le ^tcl@8.6.8%gcc@4.8.5 arch=linux-rhel7-ppc64le ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-rhel7-ppc64le to satisfy requirement for environment-modules
==> Installing zlib
==> Searching for binary cache of zlib
==> Warning: No Spack mirrors are currently configured
==> No binary for zlib found: installing from source
==> Error: StageError: No accessible stage paths in:
    ['$tempdir/spack-stage']

/home/myname/SPACK/lib/spack/spack/package.py:753, in _make_root_stage:
        750            dynamic_fetcher = fs.from_list_url(self)
        751            return [dynamic_fetcher] if dynamic_fetcher else []
        752
  >>    753        stage = Stage(fetcher, mirror_path=mp, name=stage_name, path=self.path,
        754                      search_fn=download_search)
        755        return stage


==> Error: No accessible stage paths in:
Traceback (most recent call last):
  File "/home/myname/SPACK/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/home/myname/SPACK/lib/spack/spack/main.py", line 701, in main
    e.die()  # gracefully die on any SpackErrors
  File "/home/myname/SPACK/lib/spack/spack/error.py", line 74, in die
    self.print_context()
  File "/home/myname/SPACK/lib/spack/spack/error.py", line 57, in print_context
    sys.stderr.write(self.long_message)
TypeError: expected a character buffer object
[myname@ac922 ~]$ spack install screen
==> Error: No accessible stage paths in:
Traceback (most recent call last):
  File "/home/myname/SPACK/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/home/myname/SPACK/lib/spack/spack/main.py", line 701, in main
    e.die()  # gracefully die on any SpackErrors
  File "/home/myname/SPACK/lib/spack/spack/error.py", line 74, in die
    self.print_context()
  File "/home/myname/SPACK/lib/spack/spack/error.py", line 57, in print_context
    sys.stderr.write(self.long_message)
TypeError: expected a character buffer object
```

### Error Message

(included above)

```console
$ spack -d --stacktrace install screen
lib/spack/spack/config.py:684 ==> [2019-08-20-17:25:04.194732] Reading config file /home/myname/SPACK/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-08-20-17:25:04.210065] Reading config file /home/myname/SPACK/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-08-20-17:25:04.215119] Reading config file /home/myname/SPACK/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:98 ==> [2019-08-20-17:25:04.242894] Imported install from built-in commands
lib/spack/spack/cmd/__init__.py:98 ==> [2019-08-20-17:25:04.244661] Imported install from built-in commands
lib/spack/spack/config.py:684 ==> [2019-08-20-17:25:04.256966] Reading config file /home/myname/SPACK/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:684 ==> [2019-08-20-17:25:04.329868] Reading config file /home/myname/SPACK/etc/spack/defaults/packages.yaml
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.358382] READ LOCK: /home/myname/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.358814] READ LOCK: /home/myname/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.360267] READ LOCK: /home/myname/.spack/cache/tags/.builtin-index.json.lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.363832] READ LOCK: /home/myname/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.364240] READ LOCK: /home/myname/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.388318] READ LOCK: /home/myname/.spack/cache/patches/.builtin-index.json.lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.392465] READ LOCK: /home/myname/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.392874] READ LOCK: /home/myname/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.433396] READ LOCK: /home/myname/.spack/cache/providers/.builtin-index.json.lock[0:0] [Released]
lib/spack/spack/config.py:684 ==> [2019-08-20-17:25:04.455639] Reading config file /home/myname/.spack/linux/compilers.yaml
lib/spack/spack/database.py:214 ==> [2019-08-20-17:25:04.497466] DATABASE LOCK TIMEOUT: 120s
lib/spack/spack/database.py:218 ==> [2019-08-20-17:25:04.497742] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.498639] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.498978] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.499402] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.499798] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.500166] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.500611] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.501073] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.501445] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.501897] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.503410] WRITE LOCK: /home/myname/SPACK/opt/spack/.spack-db/prefix_lock[8654365307056604415:1] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.503748] WRITE LOCK: /home/myname/SPACK/opt/spack/.spack-db/prefix_lock[8654365307056604415:1] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.504055] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.504405] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.504846] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.505166] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.505530] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.505986] READ LOCK: /home/myname/SPACK/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-08-20-17:25:04.510727] WRITE LOCK: /home/myname/SPACK/opt/spack/.spack-db/prefix_lock[8654365307056604415:1] [Released]
lib/spack/spack/main.py:700 ==> [2019-08-20-17:25:04.529440] StageError: No accessible stage paths in:
    ['$tempdir/spack-stage']
lib/spack/spack/error.py:55 ==> [2019-08-20-17:25:04.530285] Error: No accessible stage paths in:
Traceback (most recent call last):
  File "/home/myname/SPACK/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/home/myname/SPACK/lib/spack/spack/main.py", line 701, in main
    e.die()  # gracefully die on any SpackErrors
  File "/home/myname/SPACK/lib/spack/spack/error.py", line 74, in die
    self.print_context()
  File "/home/myname/SPACK/lib/spack/spack/error.py", line 57, in print_context
    sys.stderr.write(self.long_message)
TypeError: expected a character buffer object
```

### Information on your system

POWER9 (ppc64le), first SPACK setup

Any advice is welcome!

**Comment by scheibelp** [comment]
Hi @steffen-AEI, could you try https://github.com/spack/spack/pull/12492?

I think the issue on your system is that the temp directory is not editable by you, but unfortunately the error message which would inform you of that is currently broken (a Spack bug). #12492 will not fix your issue but will confirm that Spack cannot find a temporary directory that you have write permissions for. With that PR it should now say something like:

```
Error: no accessible stage paths in:
<the temp dir it tried to use>
```

If you think you *can* write to this directory, then we should update Spack to understand that. If in fact you cannot write to that directory, you can point Spack to a location that you do have write access to (I'll add that information if this is the case).

**Comment by steffen-AEI** [comment]
Since v0.12 (there's no 0.12.1 release branch, nor anything newer) works: what would be the directory to create/change permissions of?

After another git pull, commit 3b115ff is now on top of the log, but still
```
==> Error: No accessible stage paths in:
Traceback (most recent call last):
[...]
TypeError: expected a character buffer object
```

For now, I'll take the 0.12 version, doctor a recent bzip2 and singularity in, and try to proceed, but that cannot be the last word.

**Comment by mwkrentel** [comment]
Yes, I agree that somewhere you need to add a `user` component to the
tempdir path.

You expect `/tmp` to have mode 1777 and so you can create directories
there.  But `/tmp/spack-stage` does not.  It already exists and is
owned by another user, so this has become a race condition.  It works
for the first user and fails for the other N-1.

Also, I strongly recommend re-adding something like
`$spack/var/spack/stage` as above as a fallback.

**Comment by scheibelp** [comment]
Thanks for running that!

Adding `$user` will resolve this, but we intend that Spack will do this automatically for you. We are looking into fixing this so that you don't have to edit `config.yaml`.

**Comment by tldahlgren** [comment]
> Yes, I agree that somewhere you need to add a `user` component to the
> tempdir path.
>

As I mentioned in my response to your comment on #12495 , staging *should* be adding `$user` to `$tempdir/spack-stage` when `$user` is not already a node in `$tempdir` assuming it is the "first accessible" `build_stage`.

Unfortunately, if there is only one `build_stage` entry with a path that exists but is not accessible, the current code will raise a `StageError` complaining `No accessible stage paths...`.  So I assume you're N-1 other users are getting this error for `/tmp/spack-stage`, correct?

FWIW/ Configuration settings, such as`build_stage`, can be overridden by creating a `$HOME/.spack/config.yaml` file with custom options.

> You expect `/tmp` to have mode 1777 and so you can create directories
> there. But `/tmp/spack-stage` does not. It already exists and is
> owned by another user, so this has become a race condition. It works
> for the first user and fails for the other N-1.
> 

Permissions are another matter.

- What are the permissions on `/tmp`?
- What is the hash for the commit you are using?  (https://github.com/spack/spack/commit/3b115fffb132ee3a247079e8b6043c33707d20c5 should resolve the permissions issue)


> Also, I strongly recommend re-adding something like
> `$spack/var/spack/stage` as above as a fallback.

I was told to only provide the one path with the expectations that users would override the setting as needed.  At issue is the fact that some sites have security concerns with sharing `$spack/var/spack/stage`.

**Comment by tldahlgren** [comment]
> _Update3: in `etc/spack/default/config.yaml` I'm now using_
> 
> ```
>   build_stage:
>   #  - $tempdir/spack-stage
>     - $tempdir/$user/spack-stage
>     - $tempdir/spack-stage-$user
>     - $spack/var/spack/stage
> ```
> 
> _which should be safe for all and provide a fallback to the old stage path._

I've been discussing this option with Todd (tgamblin).

As I mentioned above, you can customize your configuration settings with a `config.yaml` file in `etc/spack/config.yaml` or `$HOME/.spack/config.yaml` (see https://spack.readthedocs.io/en/latest/config_yaml.html#config-yaml).

**Comment by mwkrentel** [comment]
IMO, the guiding principle here should be robustness.  For experienced
users who want to set it to something specific for their system, they
can.  That's not a problem.

But for novice users or even experienced users who don't care where
the build stage is, it should "just work."  And that's where I think
the current setting comes up short.  For **many** users, you have to
know what this is and set it manually or else nothing works.

Here, robustness means, test that you can write to the directory, add
$user if needed, and if you can't write to the directory, then go to
the next option.

So sure, fix the error message, write better documentation, that's all
good.  But the more important issue is that it should "just work."

> So I assume you're N-1 other users are getting this error for
> /tmp/spack-stage, correct?

Yes, and I'm one of the N-1.  (My office mate is the 1. :-)

> What are the permissions on /tmp?

/tmp is 1777, and /tmp/spack-stage is 755, but it's owned by a
different user, so I can't write to it and I can't reset the
permissions.

What I meant by permissions was just that the expectation is that you
can probably write to $tempdir, but not to $tempdir/spack-stage.

> What is the hash for the commit you are using? (3b115ff should
> resolve the permissions issue)

I'm at 77e4e3d87e, so two revs past 3b115fffb13.

> I was told to only provide the one path with the expectations that
> users would override the setting as needed. At issue is the fact
> that some sites have security concerns with sharing
> $spack/var/spack/stage.

Would it help the security concerns if you put a $user in there
somewhere?

I still suggest there should be some kind of a fallback, since the
alternative is to let it fail.

**Comment by steffen-AEI** [comment]
> As I mentioned in my response to your comment on #12495 , staging _should_ be adding `$user` to `$tempdir/spack-stage` when `$user` is not already a node in `$tempdir` assuming it is the "first accessible" `build_stage`.

That's what I had suggested above ;) - first try /tmp/$user/spack-stage (might resolve setup issues with /tmp itself), then /tmp/spack-stage-$user (needs 1777 permissions), fall back to old $spack/var/spack/stage (should be safe with old single-user setups). Redundancy is good, although this isn't absolutely failsafe (something like tempnam() should be though).

> Unfortunately, if there is only one `build_stage` entry with a path that exists but is not accessible, the current code will raise a `StageError` complaining `No accessible stage paths...`. So I assume you're N-1 other users are getting this error for `/tmp/spack-stage`, correct?

Correct, even for N=2.

> FWIW. Configuration settings, such as`build_stage`, can be overridden by creating a `$HOME/.spack/config.yaml` file with custom options.

Users don't expect this to be necessary when coming from an older git checkout.
Since this change was made in a central place, it should be fixed in that place.

> > You expect `/tmp` to have mode 1777 and so you can create directories
> Permissions are another matter.

tempnam() and friends have some expectations, but any well-administered system should yield.

>     * What are the permissions on `/tmp`?

Sufficient to create stuff there that doesn't exist yet and is owned by someone else ;)

>     * What is the hash for the commit you are using?  ([3b115ff](https://github.com/spack/spack/commit/3b115fffb132ee3a247079e8b6043c33707d20c5) should resolve the permissions issue)

A /tmp/spack-stage owned by someone else cannot be fixed by this.

> > Also, I strongly recommend re-adding something like
> > `$spack/var/spack/stage` as above as a fallback.
> 
> I was told to only provide the one path with the expectations that users would override the setting as needed. At issue is the fact that some sites have security concerns with sharing `$spack/var/spack/stage`.

If it isn't shared it isn't available as a staging path, and it's the last fallback option. If we get this far and fail something else is already broken...

**Comment by steffen-AEI** [comment]
> > _Update3: in `etc/spack/default/config.yaml` I'm now using_
[...]
> > _which should be safe for all and provide a fallback to the old stage path._
> I've been discussing this option with Todd (tgamblin).
> As I mentioned above, you can customize your configuration settings with a `config.yaml` file in `etc/spack/config.yaml` or `$HOME/.spack/config.yaml` (see https://spack.readthedocs.io/en/latest/config_yaml.html#config-yaml).

@tldahlgren Tamara,
you're asking to let each and every user create/change her config.yaml - to accommodate breakage that wasn't their fault? Please have a second look. They may not even be aware of others keeping their own copy of Spack, and never had to.

If there's something inherently wrong with my suggestion I'd like to learn about my mistakes.

**Comment by tldahlgren** [comment]
> > As I mentioned in my response to your comment on #12495 , staging _should_ be adding `$user` to `$tempdir/spack-stage` when `$user` is not already a node in `$tempdir` assuming it is the "first accessible" `build_stage`.
> 
> That's what I had suggested above ;) - first try /tmp/$user/spack-stage (might resolve setup issues with /tmp itself), then /tmp/spack-stage-$user (needs 1777 permissions), fall back to old $spack/var/spack/stage (should be safe with old single-user setups). Redundancy is good, although this isn't absolutely failsafe (something like tempnam() should be though).
> 

What I meant was that `$user` is automatically being appended -- behind the scenes if you will -- to the first accessible directory from `config:build_path` if `$user` does not appear as a node in the directory path.  Unfortunately, elevating `spack-stage` above `$user` when `$tempdir` is not 

I actually do understand your point and we have been discussing it here at LLNL.  One concern raised wrt restoring a backup is a repeat of the issue raised in #11163.

**Comment by tldahlgren** [comment]
> Would it help the security concerns if you put a $user in there
> somewhere?

The value of `$user` was implicitly appended to `config:build_stage` if it did not already appear in the selected path.  The unfortunate side-effect that you've found is the problem of ownership when the directory is first created.

I am working on moving `$user` higher in the directory tree and addressing permissions per discussion at LLNL (see #12516).  

> 
> I still suggest there should be some kind of a fallback, since the
> alternative is to let it fail.

I understand and will raise the issue internally again.

**Comment by tldahlgren** [comment]
> > > _Update3: in `etc/spack/default/config.yaml` I'm now using_
> > > [...]
> > > _which should be safe for all and provide a fallback to the old stage path._
> > > I've been discussing this option with Todd (tgamblin).
> > > As I mentioned above, you can customize your configuration settings with a `config.yaml` file in `etc/spack/config.yaml` or `$HOME/.spack/config.yaml` (see https://spack.readthedocs.io/en/latest/config_yaml.html#config-yaml).
> 
> @tldahlgren Tamara,
> you're asking to let each and every user create/change her config.yaml - to accommodate breakage that wasn't their fault? Please have a second look. They may not even be aware of others keeping their own copy of Spack, and never had to.

I do understand your point.  @tgamblin Thoughts?

**Comment by steffen-AEI** [comment]
@tgamblin,
> What I meant was that `$user` is automatically being appended -- behind the scenes if you will -- 

Things happening *automatically, behind the scenes* are always sources of confusion - unless the config setting (and documentation) are changed to reflect that the given values are **not** the paths to be used.
(If this setting was handled in a different manner depending on whether it comes from a global config or a user-specific one this would add even more confusion.)

Keep it simple, and don't surprise users by doing things that aren't obvious (and aren't documented very well). Adding $user as a second level (#12516) is a start, but why not add more fall-back entries to the default config, to cover the case where $tempdir/$user fails?
