### ISSUE TITLE
File conflicts can occur in views if the conflicting packages do not cause concretization errors

### ISSUE THREAD

**Issue by ChrisTX** [spack/spack#12482]
I've noticed some unexpected behavior if an environment (or rather its view) contains two packages that have file conflicts, but do not conflict themselves. More specifically, `metis` and `scotch^+metis` both provide `include/metis.h` but do not conflict otherwise - it's perfectly possible  to add both to an environment and install it, without Spack complaining at all.

However, the files are _not_ directly compatible and while METIS' `metis.h` should be useable with `scotchmetis` (that's the recommended way by Scotch), the converse is not true and SCOTCH's `metis.h` does not contain all functions METIS offers, rendering METIS impaired.

Additionally, if you remove `scotch` from the environment afterwards, the conflicting files will be deleted and any install command afterwards will error like this:
```
===> Error: /mypathtospack/var/spack/environments/myenv/.spack-env/include/metis.h is not a link tree!
```
This seems to be a result of spack assuming that these files should exist if `metis` were installed properly. The situation is identical between `parmetis` and `spack` with their respective overlap.

Repro:
```
spack env create myenv
spack env activate myenv
spack add metis parmetis scotch
spack install
```

**Comment by haampie** [comment]
I'm closing this as "won't fix".

1. file-file conflicts are ignored for a long time now in views, as Spack would be unusable if they were fatal errors.
2. The `metis.h` topologically closest to the root of the DAG (or env root) gets linked, which is guaranteed since #42350. 

That means we link `metis.h` from `scotch` not `metis` without warning or error.
