### ISSUE TITLE
Ruby: Support rubygems coming with ruby package

### ISSUE THREAD

**Issue by Try2Code** [spack/spack#12505]
*Rubygems is not working after installing ruby with spack*

### Rationale

rubygems is the built-in package manager just like pip for python. It comes with with den ruby package because it is part of the official ruby tarball. 

### Description

Usually the rubygems command ```gem``` i used to install packages into system directories of below ```$HOME```. This does not work with the ruby package of spack, because only the spack compiler wrappers are build into ruby's ```RbConfig::CONFIG``` module. This contains information about how ruby is build in order be able to build C-extensions for ruby. 

For plain ruby modules from rubygems.org the package management with ```gem``` works. But when it comes to extensions which need compiling, it fails. I test command is
```
gem install narray --user
```

### Additional information

The build-context varables of Ruby can be checked with
```
ruby -e 'puts RbConfig::CONFIG'
```

gem is important to working with ruby packages - so making this work will help ruby-related development based on spack.

**Comment by tgamblin** [comment]
@Try2Code: I think you can make this work by patching `RbConfig::CONFIG` the way we already patch our MPI compiler wrappers.  Essentially, you'd need to add a line like this one to the `RbConfig:CONFIG` module:

* [var/spack/repos/builtin/packages/mpich/package.py:70](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mpich/package.py#L70)

The implementation of that function is here:

* [lib/spack/spack/mixins.py:118](https://github.com/spack/spack/blob/develop/lib/spack/spack/mixins.py#L118)

Basically that looks for the spack compiler wrappers in a file, and replaces them with paths to the real compilers.  The Python package [does something similar here](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py#L493).

The other thing you might consider (and I am not sure that it is necessary with Ruby) is that for Python, at least, we copy the interpreter executable into the environment's view prefix.  I am not sure what Ruby's requirements are for working properly in a virtualenv, but for Python we have to do that to fool Ruby into thinking it lives in the environment.

If you get this working, can you submit a PR?  I agree that this is important.

**Comment by Try2Code** [comment]
Ok, i will give it a try. Never worked with environments, yet. But getting the ruby package working would be helpful. I will post here in case of further questions

cheers

**Comment by adamjstewart** [comment]
Also note that #3127 added preliminary support for a `RubyPackage` base class/build system. If you use Ruby for a lot of your work and would like to revive that PR, I can help.

**Comment by Try2Code** [comment]
ok @adamjstewart  - so this package class would be a replacement for gem? or only for un-packaged code?

**Comment by adamjstewart** [comment]
I don't know much about Ruby, so I'll answer in the form of Python. The `PythonPackage` base class doesn't replace `pip`, it just offers a way to build Python packages from source code. We still have a `py-pip` package that can be installed alongside Python to use separately from Spack, but the primary mechanism of installing Python packages in Spack is the `PythonPackage` base class.

**Comment by Try2Code** [comment]
alright  - btw: I couldn't make py-pip work. it gives an error after installing and loading
```
spack load py-pip
pip search cdo
Traceback (most recent call last):
  File "/mnt/lustre01/work/k20200/sw/spack/opt/spack/linux-rhel6-x86_64/gcc-8.3.0-works/py-pip-19.0.3-5gkpx5glyh42aeo4cu46xy3oy2vz6gze/bin/pip", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

or did I do something wrong here?

**Comment by adamjstewart** [comment]
@Try2Code Unfortunately, Python packages don't have RPATH. In order to use them, you either run `spack activate` or `spack view` or `spack env` to symlink them into a single directory, or module load all of the dependencies so that they appear in your `PYTHONPATH`. In this case, the missing dependency is `py-setuptools`.

**Comment by Try2Code** [comment]
I added ```filter_compiler_wrappers()``` to the ruby package, but reinstalling didn't help. still get this
```
"/home/ram/src/tools/spack/lib/spack/env/gcc/gcc -o conftest -I/home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0/ruby-2.6.2-llyga4qkwjy5yelvkwejpaplekbbqm7b/include/ruby-2.6.0/x86_64-linux -I/home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0/ruby-2.6.2-llyga4qkwjy5yelvkwejpaplekbbqm7b/include/ruby-2.6.0/ruby/backward -I/home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0/ruby-2.6.2-llyga4qkwjy5yelvkwejpaplekbbqm7b/include/ruby-2.6.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable conftest.c  -L. -L/home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0/ruby-2.6.2-llyga4qkwjy5yelvkwejpaplekbbqm7b/lib -Wl,-rpath,/home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0/ruby-2.6.2-llyga4qkwjy5yelvkwejpaplekbbqm7b/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0/ruby-2.6.2-llyga4qkwjy5yelvkwejpaplekbbqm7b/lib -L/home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0/ruby-2.6.2-llyga4qkwjy5yelvkwejpaplekbbqm7b/lib -lruby-static -lz -lpthread -lrt -lrt -lgmp -ldl -lcrypt -lm   -lm   -lc"
/home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0/ruby-2.6.2-llyga4qkwjy5yelvkwejpaplekbbqm7b/lib/ruby/2.6.0/mkmf.rb:406: warning: Insecure world writable dir /home/ram/src/tools/spack/opt/spack/linux-antergos-x86_64/gcc-9.1.0 in PATH, mode 040777
Spack compiler must be run from Spack! Input 'SPACK_ENV_PATH' is missing.
```
