### ISSUE TITLE
Installation issue: nag

### ISSUE THREAD

**Issue by ThemosTsikas** [spack/spack#12500]
The NAG Fortran Compiler gets updated on NAG's website periodically. The URL does not change but the checksum becomes out of date. The current checksum is 
"74573f87274dc2a55918dcd2d14ede95"
for Build 6223 of Version 6.2 This needs to be inserted in 
var/spack/repos/builtin/packages/nag/package.py

### Steps to reproduce the issue

```console
$ spack install nag 
==> Installing nag
==> Searching for binary cache of nag
==> Warning: No Spack mirrors are currently configured
==> No binary for nag found: installing from source
==> Fetching http://www.nag.com/downloads/impl/npl6a62na_amd64.tgz
######################################################################## 100.0%
==> Error: ChecksumError: md5 checksum failed for /tmp/spack-stage/themos/nag-6.2-edayunzvim5q77acjkqfl5kxpk6o4ape/npl6a62na_amd64.tgz
    Expected 8b119cc3296969bbd68b781f625de272 but got 74573f87274dc2a55918dcd2d14ede95

/home/nag/skylake/themos/spack/lib/spack/spack/package.py:1059, in do_fetch:
       1056        self.stage.fetch(mirror_only)
       1057        self._fetch_time = time.time() - start_time
       1058
  >>   1059        if checksum and self.version in self.versions:
       1060            self.stage.check()
       1061
       1062        self.stage.cache_local()


```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux skylake.nag.co.uk 4.11.3-200.fc25.x86_64 #1 SMP Thu May 25 19:03:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by adamjstewart** [comment]
Hi @ThemosTsikas, do you work for NAG? I think I remember you helping me out with some NAG issues in Spack a couple years ago.

> The URL does not change but the checksum becomes out of date.

Is there any way NAG could not do that? It makes checksums rather useless if there is no guarantee that they will stay the same. Most software packages increment the minor or patch version number when there are changes.

**Comment by ThemosTsikas** [comment]
Yes, I do. I have passed your request on.

**Comment by ThemosTsikas** [comment]
I am afraid we cannot change the process due to other commitments. But what I will do is make it part of the update process to alert spack (via raising an Issue) whenever a 64-bit Linux compiler is updated on our website. Seeing as nobody had reported this since November 2018 when the last change was made, I can only assume that it's not widely used.

**Comment by adamjstewart** [comment]
Closing as the checksums for NAG are currently correct, and according to @ThemosTsikas someone from NAG will let us know when the checksums change.

**Comment by ThemosTsikas** [comment]
New Release 7.0 of the NAG Fortran Compiler 

https://www.nag.com/downloads/impl/npl6a70na_amd64.tgz

**Comment by adamjstewart** [comment]
@ThemosTsikas would you like to submit a PR? Should be a simple one-line change.
