### ISSUE TITLE
Error: [Errno 37] No locks available

### ISSUE THREAD

**Issue by Liampowe** [spack/spack#12501]
When trying spack load <app> I am getting this error. 
Error: [Errno 37] No locks available

I tried 
rm `find . -name '*lock'`
Which I found mentioned in another thread, but that still did not work.

Thank you for any help.

**Comment by tgamblin** [comment]
I suspect you are running on an NFS mount that does not support locking.

You could try running on a filesystem that *does* support locking, or you can look at the `locks` setting in `config.yaml`.  You can either set that to `false` or run with `spack -L ...` to disable locks.

Please feel free to reopen if this doesn't address your issue.
