### ISSUE TITLE
Request to mention that you can uninstall package by hash

### ISSUE THREAD

**Issue by ejcjason** [spack/spack#12527]
Request to mention that you can use hashes in `spack uninstall -h` and `Error: You can either:`.

### Rationale
I happened to have created multiple modules, and I hope to delete one of them, but failed like this: 
```
$ spack uninstall openmpi
==> Error: openmpi@1.10.7%gcc@4.8.5~cuda matches multiple packages:

    -- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
    26w2v3w openmpi@1.10.7%gcc ~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt
    f4cgywb openmpi@1.10.7%gcc ~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt
==> Error: You can either:
    a) use a more specific spec, or
    b) use `spack uninstall --all` to uninstall ALL matching specs.
```
After searching for a while, I found the solution in #2199 to use hash. Although, the problem was solved, I really think the last sentence in this [comment](https://github.com/spack/spack/issues/2199#issuecomment-265968123) should be considered again.

### Description
Sometimes newbies make mistakes to create duplicated spack modules, but there is no hint for them to use the harsh to uninstall the specific package. Thus, it could be helpful to mention that you can use hashes in `spack uninstall -h` and `Error: You can either:`

**Comment by RobertRosca** [comment]
Oh, hey @ejcjason , didn't even realise you made this issue :smile: 

I did a PR to mention this in the error, so now it says:

```
You can either:
    a) use a more specific spec, or
    b) specify the package by its hash (e.g. `spack uninstall /hash`), or
    c) use `spack uninstall --all` to uninstall ALL matching specs
```

Which clears it up a bit.

**Comment by JunCEEE** [comment]
Hey @RobertRosca it's also a surprise that it's you who did the PR! I have almost forgotten about this issue. 
Thanks!
