### ISSUE TITLE
Installation issue: font-util

### ISSUE THREAD

**Issue by mamelara** [spack/spack#12547]
Font-util attempts to install in /etc/fonts which leads to a Permission Denied error.
### Steps to reproduce the issue

```console
$ spack install font-util arch=cray-sles15-x86_64 
[Long output]
==> [2019-08-23-10:24:39.452544] 'make' '-j16' 'install'
make[1]: Entering directory '/tmp/mamelara/font-util-1.3.1-m42cqclndhgbcpu2secxqlsxh2v3hlie/spack-src/font-bh-ttf/font-bh-ttf-1.0.3'
make[1]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/etc/fonts/conf.avail'
 /usr/bin/mkdir -p '/global/u2/m/mamelara/CLE7/spack/opt/spack/cray-sles15-x86_64/gcc-8.2.0/font-util-1.3.1-m42cqclndhgbcpu2secxqlsxh2v3hlie/share/fonts/X11/TTF'
 /usr/bin/install -c -m 644 42-luxi-mono.conf '/etc/fonts/conf.avail'
 /usr/bin/install -c -m 644 luximbi.ttf luximb.ttf luximri.ttf luximr.ttf luxirbi.ttf luxirb.ttf luxirri.ttf luxirr.ttf luxisbi.ttf luxisb.ttf luxisri.ttf luxisr.ttf '/global/u2/m/mamelara/CLE7/spack/opt/spack/cray-sles15-x86_64/gcc-8.2.0/font-util-1.3.1-m42cqclndhgbcpu2secxqlsxh2v3hlie/share/fonts/X11/TTF'
/usr/bin/install: cannot create regular file '/etc/fonts/conf.avail/42-luxi-mono.conf': Permission denied
make[1]: *** [Makefile:378: install-dist_availconfigDATA] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/mamelara/font-util-1.3.1-m42cqclndhgbcpu2secxqlsxh2v3hlie/spack-src/font-bh-ttf/font-bh-ttf-1.0.3'
make: *** [Makefile:589: install-am] Error 2
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'install'

1 error found in build log:
     12253    make[1]: Entering directory '/tmp/mamelara/font-util-1.3.1-m42cqclndhgbcpu2secxqlsxh2v3hlie/spack-src/font-bh-ttf/font-bh-ttf-1.0.3'
     12254    make[1]: Nothing to be done for 'install-exec-am'.
     12255     /usr/bin/mkdir -p '/etc/fonts/conf.avail'
     12256     /usr/bin/mkdir -p '/global/u2/m/mamelara/CLE7/spack/opt/spack/cray-sles15-x86_64/gcc-8.2.0/font-util-1.3.1-m42cqclndhgbcpu2secxqlsxh2v3hlie/share/fonts/X11/TTF'
     12257     /usr/bin/install -c -m 644 42-luxi-mono.conf '/etc/fonts/conf.avail'
     12258     /usr/bin/install -c -m 644 luximbi.ttf luximb.ttf luximri.ttf luximr.ttf luxirbi.ttf luxirb.ttf luxirri.ttf luxirr.ttf luxisbi.ttf luxisb.ttf luxisri.ttf luxisr.ttf '/global/u2/m/mamelara/CLE7/spack/opt/spack/cray-sles15-x86_64/gcc-8.2.0/f
              ont-util-1.3.1-m42cqclndhgbcpu2secxqlsxh2v3hlie/share/fonts/X11/TTF'
  >> 12259    /usr/bin/install: cannot create regular file '/etc/fonts/conf.avail/42-luxi-mono.conf': Permission denied
```

### Platform and user environment

Please report your OS here:
Cray XC40 Cori
SLES15 
GCC-8.2.0

**Comment by tgamblin** [comment]
@mamelara: did you figure out what is causing this?  I think you need to either patch `font-util` or modify the package.

**Comment by KineticTheory** [comment]
This particular permissions issue seems to stem from the `font-bh-ttf` font resource.  At least for me, removing this font from the list allows `font-util` to install.  

```diff
--- a/var/spack/repos/builtin/packages/font-util/package.py
+++ b/var/spack/repos/builtin/packages/font-util/package.py
@@ -41,7 +41,7 @@ class FontUtil(AutotoolsPackage):
         ['font-arabic-misc', '1.0.3', '918457df65ef93f09969c6ab01071789'],
         ['font-bh-100dpi', '1.0.3', '09e63a5608000531179e1ab068a35878'],
         ['font-bh-75dpi', '1.0.3', '88fec4ebc4a265684bff3abdd066f14f'],
-        ['font-bh-ttf', '1.0.3', '4ce741ec4edaa11cd38988d355a7578b'],
+        # ['font-bh-ttf', '1.0.3', '4ce741ec4edaa11cd38988d355a7578b'],
         ['font-bh-type1', '1.0.3', '62d4e8f782a6a0658784072a5df5ac98'],
         ['font-bh-lucidatypewriter-100dpi', '1.0.3',
          '5f716f54e497fb4ec1bb3a5d650ac6f7'],
```

A better fix is to understand why this font creates a permission problem. I don't understand Linux fonts so I don't really know how to track this down further.

**Comment by tgamblin** [comment]
@hartzell: do you have any font wisdom you can share on this one?

**Comment by mamelara** [comment]
Any update on this? The newer version doesn't seem to fix the issue

**Comment by KineticTheory** [comment]
_font-util_ is still broken for me.  I have the [diff listed above](https://github.com/spack/spack/issues/12547#issuecomment-541776004) in all of my spack directories so I can keep working.

**Comment by mamelara** [comment]
The diff helped. Thanks

**Comment by hainest** [comment]
I just encountered this today on cori@NERSC and theta@ALCF. There is a circular dependency between `font-util` and `fontconfig` when `font-util` builds `font-bh-ttf` which is why @KineticTheory's patch works. I see the following output from `font-util`'s `configure`:

	checking for root directory for font files... /gpfs/mira-home/thaines/ecp/spack/opt/spack/cray-cnl6-x86_64/gcc-8.3.0/font-util-1.3.2-4e6gr6ywc6gltssoedpgaz5jcirchb2k/share/fonts/X11
	checking for directory for TTF files... ${FONTROOTDIR}/TTF
	checking for fc-cache... /usr/bin/fc-cache
	checking for mkfontdir... /gpfs/mira-home/thaines/ecp/spack/opt/spack/cray-cnl6-x86_64/gcc-8.3.0/mkfontdir-1.0.7-dmoxuw2lhyu7plc7ounynthdrxdbz4xq/bin/mkfontdir
	checking for mkfontscale... /gpfs/mira-home/thaines/ecp/spack/opt/spack/cray-cnl6-x86_64/gcc-8.3.0/mkfontscale-1.1.2-s7bgmwyyacgyvcq3g53h3cf5uwebrppz/bin/mkfontscale
	checking for fontconfig's configuration directory... /etc/fonts

That last one is the system's fontconfig, not the spack one. However, fontconfig hasn't been installed yet because we are building it's dependency!  `font-bh-ttf` has a configure option `--with-fc-confdir=DIR` that we could use to fix this, but I don't know if spack can pass configure options to dependencies. @tgamblin Is this possible?

The only reason `fontconfig` depends upon `font-util` is to point to a default font directory whenever the config is broken. From the commit message (c01f78e51538f75c4cec6f696df4f129ea43d18d, Dec 2016), however,

    This commit makes the fontconfig package depend on the font-util package...
    Before this change, plots drawn by R have bounding boxes where font
    glyphs should be.  After this change fonts appear as expected.

it appears this dependency cannot be broken from the `fontconfig` side.

From the `font-util` side, this dependency was explicit when its package was introduced (6dc8bbc, Oct 2016) and then turned into a resource by e49c101 in June 2019. I have no idea if that had any effect on the concretizer's ability to handle this circular dependency issue, but it is just a couple months before this issue was submitted.

I'm not sure if I've answered more questions that I've raised!

**Comment by DavidPoliakoff** [comment]
This is still broken for me. There are three resolutions

1. Fix font-util
2. Make ruby not depend indirectly on font-util
3. Use the diff above

I'm using the diff above, thanks @KineticTheory

**Comment by mdorier** [comment]
I also have the same issue on Theta. The diff above fixes it.

**Comment by novosirj** [comment]
It's worth noting that R ultimately depends on this package, I guess via cairo and fontconfig (at least two other sites have run into it this way). It seems to me that this is likely to break a lot of different installs.

**Comment by mcuma** [comment]
FYI, I just now also ran into this bug and removed it with the diff above.

**Comment by 0xDBFB7** [comment]
Minor note, but I now got an error

> ==> Error: invalid values for variant "fonts" in package "font-util": ['font-bh-ttf']

on commenting out via the diff above. I also had to comment out the two references to font-bh-ttf that have been now added later in the package.py.

**Comment by 0xDBFB7** [comment]
Minor note, I just had a similar issue but also with all the font-*-cyrillic entries. As a workaround I applied the diff above, and commented out all references to cyrillic fonts in the package.py (including the `conflicts` checks added later in the file!)


```
  >> 12885    configure.ac:35: installing './compile'
     12886    autoreconf: Leaving directory `.'
     12887    ==> [2023-05-29-23:30:50.633817] './configure' '--prefix=/home/arthurdent/spack/opt/spack/linux-debian9-zen/gcc-9.4.0/font-util-1.4.0-mojv7wcnp2ku5fbuzft5zxlnklxt3444'
     12888    checking for a BSD-compatible install... /usr/bin/install -c
     12889    checking whether build environment is sane... yes
     12890    checking for a thread-safe mkdir -p... /bin/mkdir -p
     12891    checking for gawk... gawk

     ...

     13046     /usr/bin/install -c -m 644 crox4tb.pcf.gz crox4t.pcf.gz crox4tbo.pcf.gz crox4to.pcf.gz crox5hb.pcf.gz crox5h.pcf.gz crox5hbo.pcf.gz crox5ho.pcf.gz crox5tb.pcf.gz crox5t.pcf.gz crox5tbo.pcf.gz cro
              x5to.pcf.gz crox6hb.pcf.gz crox6h.pcf.gz crox6hbo.pcf.gz crox6ho.pcf.gz crox6tb.pcf.gz crox6t.pcf.gz crox6tbo.pcf.gz crox6to.pcf.gz koi10x16b.pcf.gz koi10x20.pcf.gz koi6x10.pcf.gz koinil2.pcf.gz '
              /home/arthurdent/spack/opt/spack/linux-debian9-zen/gcc-9.4.0/font-util-1.4.0-mojv7wcnp2ku5fbuzft5zxlnklxt3444/share/fonts/X11/cyrillic'
     13047    make  install-data-hook
     13048    make[2]: Entering directory '/tmp/arthurdent/spack-stage/spack-stage-font-util-1.4.0-mojv7wcnp2ku5fbuzft5zxlnklxt3444/spack-src/font-cronyx-cyrillic/font-cronyx-cyrillic-1.0.3'
     13049    /home/arthurdent/spack/opt/spack/linux-debian9-zen/gcc-9.4.0/mkfontdir-1.0.7-bidxwurnrpce6m4mrlzrkk27blw7a5rn/bin/mkfontdir /home/arthurdent/spack/opt/spack/linux-debian9-zen/gcc-9.4.0/font-util-1
              .4.0-mojv7wcnp2ku5fbuzft5zxlnklxt3444/share/fonts/X11/cyrillic
     13050    /home/arthurdent/Programs/miniconda/bin/fc-cache /home/arthurdent/spack/opt/spack/linux-debian9-zen/gcc-9.4.0/font-util-1.4.0-mojv7wcnp2ku5fbuzft5zxlnklxt3444/share/fonts/X11/cyrillic
     13051    /home/arthurdent/spack/opt/spack/linux-debian9-zen/gcc-9.4.0/font-util-1.4.0-mojv7wcnp2ku5fbuzft5zxlnklxt3444/share/fonts/X11/cyrillic: failed to write cache
  >> 13052    make[2]: *** [Makefile:756: install-data-hook] Error 1
     13053    make[2]: Leaving directory '/tmp/arthurdent/spack-stage/spack-stage-font-util-1.4.0-mojv7wcnp2ku5fbuzft5zxlnklxt3444/spack-src/font-cronyx-cyrillic/font-cronyx-cyrillic-1.0.3'
  >> 13054    make[1]: *** [Makefile:682: install-data-am] Error 2
     13055    make[1]: Leaving directory '/tmp/arthurdent/spack-stage/spack-stage-font-util-1.4.0-mojv7wcnp2ku5fbuzft5zxlnklxt3444/spack-src/font-cronyx-cyrillic/font-cronyx-cyrillic-1.0.3'
  >> 13056    make: *** [Makefile:633: install-am] Error 2

```
