### ISSUE TITLE
Add triage label to all non-feature GitHub issues

### ISSUE THREAD

**Issue by omsai** [spack/spack#12583]
In working towards alerting package maintainers about issues relating to their packages, we can have a triage team look at new non-feature issues to identify the spack packages, etc.

The ad-hoc way in which new issues are currently triaged is by checking for issues with no comments and which have no label assigned.

A better way than looking at the number of comments would be using the existing "triage" label per this slack discussion:
https://spackpm.slack.com/archives/C5VL7V81G/p1566834844172000
...and the issue templates can additionally set the "triage" label by default to non-feature issues.

We might also consider renaming "triage" to "needs-triage" to more clearly state the intention of the label as explained in the discussion linked.

PR incoming.

**Comment by alalazo** [comment]
Solved in a little bit less invasive way in #15234 All the reported bugs have a `triage` label applied automatically. Feel free to reopen if this is not satisfactory and you want to continue the discussion.
