### ISSUE TITLE
Implement views based on phantom packages

### ISSUE THREAD

**Issue by eschnett** [spack/spack#1260]
The packages in view are very much like the set of dependencies of a package, except that that package itself doesn't install anything. To ensure that the packages that form a view are consistent, one can begin with describing a set of dependencies, and then let Spack's concretization algorithm resolve them to decide which packages should be part of a view.

This will ensure that all packages in a view are consistent with each other, and can be combined with each other at will. No packages will be missing since Spack adds necessary dependencies automatically. The dependency resolution and concretization mechanism exists already, and there is a priori no reason why the view-conflict-resolution algorithm should use a different set of rules than the concretization algorithm.

Currently, views are managed by manually adding and removing packages. That is a bit tedious and brittle. Having a `view.yaml` file that lists the dependencies might be preferable in the long term. For example, I want to be able to create very similar views on all the HPC systems I am using.

(Unsurprisingly, I am currently using a private phantom package for this that uses many `depends_on` statements.)

**Comment by alalazo** [comment]
Closing as inactive in the last year, and probably outdated by the environments proposal.
