### ISSUE TITLE
Spack Environment Forgets what was in it

### ISSUE THREAD

**Issue by citibeth** [spack/spack#12606]
When you `spack -e <myenv> install one-package`, in some ways the environment "forgets" what else was installed in it.

### Steps to reproduce the issue

```
spack -e myenv install
spack -e myenv env loads -r    # Produces a loads file in the env directory with many entries
spack -e myenv install xz
spack -e myenv env loads -r    # Produces very short loads file
```

Later on, I made it "remember" with:
```
spack -e myenv install
```
(which installed nothing, but did go over everything again.  For some reason it re-concretized too, even though I did not ask it to).

After that, I got `spack env loads` files with many extra/repeated entries.

**Comment by scheibelp** [comment]
For me the following sequence works fine:

```
spack env create test1
spack -e test1 add m4
spack -e test1 install
spack -e test1 env loads -r
spack -e test1 install bzip2
spack -e test1 env loads -r # contains the new and old specs
```

As a sanity check, are you executing these commands in a folder with a `spack.yaml`? Or have you had another Spack environment activated when running these commands (that *shouldn't* be a problem but could be causing issues).

**Comment by citibeth** [comment]
On Fri, Aug 30, 2019 at 5:40 PM Peter Scheibel <notifications@github.com>
wrote:

> For me the following sequence works fine:
>
> spack env create test1
> spack -e test1 add m4
> spack -e test1 install
> spack -e test1 env loads -r
> spack -e test1 install bzip2
> spack -e test1 env loads -r # contains the new and old specs
>
> As a sanity check, are you executing these commands in a folder with a
> spack.yaml?
>

yes


> Or have you had another Spack environment activated when running these
> commands (that *shouldn't* be a problem but could be causing issues).
>

Now that Spack auto-activates environments without my consent, I have no
idea.  I certainly don't want to activate any environments.

-- Elizabeth

**Comment by alalazo** [comment]
Reading through the issue it seems it was unreproducible, so closing it. Feel free to undo if I am wrong about that.
