### ISSUE TITLE
feature: Sanity check on values of install_tree and build_state values in config.yaml

### ISSUE THREAD

**Issue by naromero77** [spack/spack#12633]
*Please add a concise summary of your suggestion here.*
There should be a check that the `install_tree` directory is not a subdirectory of `build_stage` in config.yaml.

Otherwise, by typing:
`spack clean`

All your packages are blown away.

### Rationale

*Is your feature request related to a problem? Please describe it!*

It was an oversight on my part, but I set-up `config.yaml` as follows:
[naromero@naromero-desktop ~]$ more ~/.spack/config.yaml
'''
config:
    build_jobs: 12
    install_tree: /sandbox/$user/opt/spack
    build_stage:
    - /sandbox/$user
'''

### Description

*Describe the solution you'd like and the alternatives you have considered.*

If Spack is to be used in a production environment, there should be some sanity check or at least a warning to prevent this.

### Additional information
*Add any other context about the feature request here.*

@becker33 You may find this funny. I had a cron job running for weeks tests that the two Spack packages that I maintain build properly. At some point, I introduced `spack clean` and stuff was disappearing every day. I thought I was going insane.

For sure, consider this low priority. I submit a github issue to make sure the developers are aware that this could happen accidentally and can be a cause for potential confusion.

-----

If you want to ask a question about the tool (how to use it, what it can currently do, etc.), try the `#general` channel on our Slack first. We have a welcoming community and chances are you'll get your reply faster and without opening an issue.

Other than that, thanks for taking the time to contribute to Spack!

**Comment by naromero77** [comment]
@tldahlgren Yes, if `spack clean` only subdirectories with a hash (or are .lock) that would be enough to close this issue. Is this https://github.com/spack/spack/pull/12516 stalled or does it just need to get merged in?

**Comment by tldahlgren** [comment]
I think it's close.  I have some feedback to address, such documentation.

**Comment by tldahlgren** [comment]
@naromero77 #12516 has been merged.

Note that there is a follow up (#12733  ) that changes the naming convention for stage directories to prepend `spack-` so that `spack clean` can blow away `build_stage` subdirectories starting with `spack-` instead of the hash.

Would this change still work for you?

**Comment by naromero77** [comment]
yes, we can close this issue. Thanks for pinging me.
