### ISSUE TITLE
external packages: spack finds wrong prefix for cuda from module on Cori

### ISSUE THREAD

**Issue by mwkrentel** [spack/spack#12650]
I'm seeing a problem where spack finds the wrong prefix for a cuda
module.  IMO, this has to be either a bug with the module entry or
else a bug in how spack reads the module, and I'm asking for a ruling.

This is on cori at NERSC, a Cray machine with GPUs on some compute
nodes.  I created a dummy package that just adds a few dependencies
and has a trivial install() method that prints the `spec[...].prefix`
for the packages.

```
class Mypack(Package):
    ...
    depends_on('cmake')
    depends_on('cuda')

    def install(self, spec, prefix):
        print 'cmake =  {0}'.format(spec['cmake'].prefix)
        print 'cuda =   {0}'.format(spec['cuda'].prefix)
	...
```

I added `modules:` entries in `packages.yaml` for cmake, cuda, etc.

```
cmake:
  modules:
    cmake@3.14.4:  cmake/3.14.4

cuda:
  modules:
    cuda@10.1.168:  cuda/10.1.168
```

Most of the prefixes make sense, but the cuda prefix is `/usr` which
is not correct.

```
cmake =  /global/common/sw/cray/cnl7/haswell/cmake/3.14.4/gcc/8.2.0/2hef55n
cuda =   /usr
jdk =    /global/common/cori_cle7/software/jdk/1.8.0_202
papi =   /opt/cray/pe/papi/5.7.0.1
```

I'm expecting `spec['cuda'].prefix` to be `/usr/common/software/cuda/10.1.168`,
not `/usr`.

Cori uses TCL modules and the cuda module has:

```
$ module show cuda/10.1.168
-------------------------------------------------------------------
/usr/common/software/modulefiles/cuda/10.1.168:

conflict         cuda 
module-whatis    CUDA is a parallel computing platform and programming model developed by NVIDIA
                 for general computing on graphical processing unit (GPU). 
setenv           CUDA_VERSION 10.1.168 
setenv           CUDNN_VERSION 7.6.2 
setenv           CUDA_ROOT /usr/common/software/cuda/10.1.168 
setenv           CUDA_HOME /usr/common/software/cuda/10.1.168 
setenv           CUDA_PATH /usr/common/software/cuda/10.1.168 
prepend-path     LD_LIBRARY_PATH /usr/lib64 
prepend-path     LD_LIBRARY_PATH /usr/common/software/cuda/10.1.168/lib64 
prepend-path     PATH /usr/common/software/cuda/10.1.168/bin 
prepend-path     PATH /usr/common/software/cuda/10.1.168/NsightCompute-2019.3.1.2 
prepend-path     PATH /usr/common/software/cuda/10.1.168/NsightSystems-linux-public-2019.3.6.30-e2e891f/Host-x86_64/ 
prepend-path     PATH /usr/common/software/cuda/10.1.168/NsightSystems-linux-public-2019.3.6.30-e2e891f/Target-x86_64/x86_64 
prepend-path     MANPATH /usr/common/software/cuda/10.1.168/doc/man 
prepend-path     CMAKE_PREFIX_PATH /usr/common/software/cuda/10.1.168 
-------------------------------------------------------------------
```

It's not TCL modules in general.  The other modules on cori are TCL
and they seem to work.

It's not just this one cuda module.  There are 5 cuda modules on cori,
older and newer.  The others also report /usr.

It's not cuda in general.  I tried other cuda modules on other
systems, including summit at ORNL, and they work.  But those are LMOD
modules.

It seems to be just cuda on cori at NERSC.  At least, I haven't found
another pattern.

Cori has separate FE/BE arch types.  Same problem for either arch.

I'm not blocked.  I can change `modules:` to `paths:` and get the
right prefix.  But this is supposed to work, right?

This is with a recent spack clone: 02bb1d5ec618 on Aug 27.

Anyway, I'm seeking a ruling if this a problem with the module entry
or in how spack reads the module.  But let's try not to have each side
blame the other.  :-)

ping @mamelara who seems to be in the intersection of spack and NERSC.

**Comment by becker33** [comment]
@mwkrentel I can tell you exactly why this is happening. The problem is the heuristics we use to extract paths from the modules will find the first command affecting `LD_LIBRARY_PATH` and detect `/usr` as the prefix.

I'm not quite sure what the best change to the heuristic is. We detect based on `LD_LIBRARY_PATH`, `CRAY_LD_LIBRARY_PATH`, `<pkg>_DIR`, `PATH`, and additions of `-L` or `-rpath` flags. Maybe we should add `<pkg>_ROOT` and `MANPATH`, and instead of taking the first path we detect use the path we detect the most times? Do you think that's a sufficient heuristic to avoid this coming up in the future?

**Comment by becker33** [comment]
@mwkrentel can you confirm that #12693 resolves your issue?

**Comment by mwkrentel** [comment]
> can you confirm that #12693 resolves your issue?

Yes, for this example, your patch produces the right answer:
`/usr/common/software/cuda/10.1.168`

Thanks!

**Comment by mwkrentel** [comment]
@becker33 As for heuristics, I also don't know a clear "best" answer.
Some observations:

1. When writing heuristics, you want to be very careful not to "fix"
the rules for one case and end up breaking another case that used to
work.

2. `/usr` is an unusual place to put a module.  I could understand
`/usr/local/<package>`, but `/usr` should be suspicious.

3. In the above `cuda/10.1.168` example, there are many values that
would give the right answer and a few (or one) that give the wrong
answer.  So, the question is how to separate the signal from the
noise.

Maybe try some kind of a voting or points system.  Pick some 5-10
module variables that, if set, each vote for one or more answer.

In the cuda example, `CUDA_ROOT`, `CUDA_HOME` and `CUDA_PATH` all have
one just one path, so they each vote for `/usr/common/software/cuda/10.1.168`,
which happens to be the right answer.  (Or maybe these three are
really three ways of saying the same thing, so maybe they count
as 1 vote combined.)

`LD_LIBRARY_PATH` has two paths (so 1/2 vote each).

`PATH` is probably special because it may be common to add multiple
directories.  But in this case, the least common ancestor is the right
answer.

`MANPATH` (properly clipped) and `CMAKE_PREFIX_PATH` each have one
value and one vote each.

So in this example, the vote is 6.5 for `/usr/common/software/cuda/10.1.168`
and 0.5 for `/usr`.  That's what you hope for, a lopsided score.

Maybe something like that could separate the signal from the noise.

Btw, I guess this file is where spack picks the answer?
`lib/spack/spack/util/module_cmd.py`

**Comment by becker33** [comment]
@mwkrentel what you've described is fairly similar to what I did in the PR. I gave each line of the module a vote, instead of each variable. Each line gets to cast its vote if it matches one of several patterns that suggest it is a path to the package.

Actually, saying each line gets a vote is slightly misleading. Many of the patterns check for colon-delimited lists. If a line has several colon-delimited entries, it gets a vote for each of them.

The different patterns have different clipping rules, as you mentioned

We could look into doing a more sophisticated vote, but I don't think it will be necessary. As you point out, we expect the vote totals to be lopsided.

You are correct about where the magic happens. If you look at #12693 you can see the new heuristic.

**Comment by mwkrentel** [comment]
@becker33 Oh, sorry, I didn't mean to steal your idea.  I just looked
and the module and thought, "A person can look at this and clearly get
the right answer, so how I describe that as an algorithm."

**Comment by becker33** [comment]
Oh no worries at all. I think if more issues come up here it would be worth considering your idea of discounting the votes of some lines based on how clear a signal they give (A line with multiple paths is less of a signal, etc).
