### ISSUE TITLE
Installation issue: cp2k

### ISSUE THREAD

**Issue by solalito** [spack/spack#12701]
### Steps to reproduce the issue

```console
$ spack install cp2k # Fill in the exact spec you are using
... (lots of packages being installed)
==> Installing libxc
==> Searching for binary cache of libxc
==> Warning: No Spack mirrors are currently configured
==> No binary for libxc found: installing from source
==> Fetching http://www.tddft.org/programs/octopus/down.php?file=libxc/4.3.2/libxc-4.3.2.tar.gz

curl: (7) Failed connect to www.tddft.org:80; No route to host
==> Fetching from http://www.tddft.org/programs/octopus/down.php?file=libxc/4.3.2/libxc-4.3.2.tar.gz failed.
==> Error: FetchError: All fetchers failed for libxc-4.3.2-q2c7jlxasl4gim7nve7c4wtex3xgowc6

/root/usr/spack/lib/spack/spack/package.py:1061, in do_fetch:
       1058                raise FetchError("Will not fetch %s" %
       1059                                 self.spec.format('{name}{@version}'), ck_msg)
       1060
  >>   1061        self.stage.create()
       1062        self.stage.fetch(mirror_only)
       1063        self._fetch_time = time.time() - start_time
       1064
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux arthemis.localdomain 5.0.10-1.el7.elrepo.x86_64 #1 SMP Sat Apr 27 08:40:16 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
``` 

### Additional information

The website hosting the libxc library is down as it is often the case (see https://github.com/pyscf/pyscf/issues/51). 

### Steps to fix (or hack?) it

I was actually able to install cp2k but the solution is not elegant at all. Note that I am a new spack user and therefore something much simpler may be available. Anyway, I thought of posting the solution either way.

I was able to find different websites hosting libxc. However, cp2k requires libxc version 4.0.3 or newer. I was only able to find it here:
`git clone https://github.com/dgasmith/libxc.git`

Issue is spack needs a url with the actual tarball to download it using wget. Therefore, here are the steps to follow:

- Download an older version of libxc: `wget http://www.sunqm.net/pyscf/files/src/libxc-3.0.1.tar.gz`

- Obtain its sha256: `sha256sum libxc-3.0.1.tar.gz`

- Go into `$YOUR_SPACK_DIR/spack/var/spack/repos/builtin/packages/libxc/package.py` and replace the homepage, url variables as well as the version number - choose 4.0.3 - and its sha256 sum so that it downloads from the link above. Also replace the website in the "if" statements

- Run spack install cp2k ==> It will install libxc correctly then other packages. Once it gets to building cp2k, you will get an error saying cp2k requires libxc 4.0.3 or sooner

- Download the newer libxc (doesn't matter where): `git clone https://github.com/dgasmith/libxc.git`

- Install `autoreconf -i && ./configure --prefix=$HOME/tmp && make && make install`

- Find where spack installed the libxc libraries and delete everything: (dir will be something like this `$YOUR_SPACK_DIR/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/libxc-4.0.3-linbltlqag7mrzgh57avdqd37tvftbmg/{bin,lib,include}`)

- Replace those directories with the freshly installed one from git: `cp -r $HOME/tmp/* $YOUR_SPACK_DIR/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/libxc-4.0.3-linbltlqag7mrzgh57avdqd37tvftbmg/`

- `spack install cp2k` will work :)

**Comment by adamjstewart** [comment]
You might be able to find newer versions at https://gitlab.com/libxc/libxc

**Comment by glennpj** [comment]
I created a local libxc package that uses the sources from github. If it looks like the www.tddft.org site will continue to be problematic I could work up a PR to start using sources from there for libxc.

**Comment by dev-zero** [comment]
ok, but this is not about CP2K. Either solved by https://github.com/spack/spack/pull/13471 if tddft.org is online again or will be solved by https://github.com/spack/spack/pull/13579

**Comment by kmanalo** [comment]
Good to close then? I was not seeing the issue with a recent build of libxc and cp2k.

**Comment by alalazo** [comment]
> Good to close then? I was not seeing the issue with a recent build of libxc and cp2k.

Closing the issue. If there's any additional mirror for `libxc` and/or `cp2k` feel free to post it here. Once #13881 is merged we might add them to strengthen the download.
