### ISSUE TITLE
Spack Environments does not set all env vars during activation

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#12731]
When I run `spack env activate ...`, Spack automatically adds all of my packages to my `PATH`, but it doesn't set all environment variables. In particular, when I build `gdal+java+mdb`, it adds a lot of Java dependencies to the environment. These dependencies cannot be found unless `CLASSPATH` is set. I could hack Spack Environments to set `CLASSPATH`, but it would be more robust and predictable if Spack Environments set the same env vars that were written to module files.

@zchen105

**Comment by tgamblin** [comment]
@becker33 and I talked about this one today.

**Comment by Sinan81** [comment]
@adamjstewart is there an alternative to environments that 100% works? I wonder if a meta package would work

**Comment by adamjstewart** [comment]
The alternative is to install environment modules and `module load` all the packages you need.

**Comment by Sinan81** [comment]
Is there a simple way to make sure that all packages are compatible with each  other (concretize together?) as in environment modules?
