### ISSUE TITLE
spack build HPCTOOLKIT & STAT error

### ISSUE THREAD

**Issue by akkbook** [spack/spack#12883]
Hello,
I followed the instruction "Installing HPCTOOLKIT & STAT tools within Spack" installed error.. Here are what I tried. Would you give me some advice? Thanks!

### Platform and user environment
OS：Redhat 7.2
Linux gos 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mwkrentel** [comment]
@akkbook You have a very old spack recipe for hpctoolkit.  I removed
hpctoolkit-externals back in Nov 2018.

I have current directions for installing hpctoolkit via spack at:

http://hpctoolkit.org/software-instructions.html

**Comment by akkbook** [comment]
Thank you for your advice.

**Comment by mwkrentel** [comment]
Btw, stat fails for the same reason, you have an out of date spack
recipe.  Bzip2 moved to sourceware.org a few months ago and then was
dropped from fossies.

This was fixed in spack in mid July in d7b76df5ac2.

**Comment by akkbook** [comment]
Thanks.

**Comment by mwkrentel** [comment]
@akkbook  Have you tried a more recent version of spack?
There's no bug here and you may as well close this issue.
