### ISSUE TITLE
Difference in behavior between running configure with Spacks build-env and how Spack configures software

### ISSUE THREAD

**Issue by DavidPoliakoff** [spack/spack#12888]
I'm trying Spack on a new system, and am running into a bewildering error. I try

`spack install zlib%gcc@7.2.0`

And somewhere in configure I get your standard broken GCC messages

```
  /home/projects/x86-64/binutils/2.30.0/lib/../x86_64-pc-linux-gnu/bin/ld: cannot find crtbeginS.o: No such file or directory
  /home/projects/x86-64/binutils/2.30.0/lib/../x86_64-pc-linux-gnu/bin/ld: cannot find -lgcc
  /home/projects/x86-64/binutils/2.30.0/lib/../x86_64-pc-linux-gnu/bin/ld: cannot find -lgcc
```

I tried two things to reproduce this, (1) configuring with that GCC, which works, and (2) sourcing the spack-build.env file, and running the same configure line Spack did, which also works. (Side note: whoever made spack produce the `spack-build.env` file is awesome, that's a great feature).

The only other information I have is that when running with --stacktrace -d I see

```
.../src/spack/lib/spack/spack/build_environment.py:689 ==> [2019-09-20-10:02:25.656839] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
```

I'm not really sure what other information would help, I'm on one of our testbeds (Blake) which I could probably get somebody an account on if necessary, but if somebody could walk me through next debugging steps in a situation like this I'd appreciate it.

Thanks for reading/trying to help!

**Comment by DavidPoliakoff** [comment]
@becker33 is helping me out in Slack. Turns out a good way to debug in this situation is

`spack build-env zlib%gcc@7.2.0 bash; spack cd zlib%gcc@7.2.0`

**Comment by DavidPoliakoff** [comment]
Okay, in my specific instance, apparently two things are happening

When wrapped by spack, gcc can't find libgcc and crtbegin.o (and crtend.o). Adding the path to cflags and cxxflags fixes it. (Maybe the dependent modifying my cflags as seen in the trace is why this happens?). To be specific, modifying ~/.spack/[arch]/compilers.yaml and adding

```
"cflags" : "-L/usr/lib/gcc/x86_64-redhat-linux/4.8.3/ -B/usr/lib/gcc/x86_64-redhat-linux/4.8.3/",
       "cxxflags" : "-L/usr/lib/gcc/x86_64-redhat-linux/4.8.3/ -B/usr/lib/gcc/x86_64-redhat-linux/4.8.3/"
```

Under the `flags` field fixes this. If you can't find your equivalent path, do (with an unwrapped gcc)

`strace -f -e open gcc -lgcc (some_source_file) 2>&1 | grep libgcc`

And you should see where that library is located. @becker33 , my situation is fixed, but we don't know why Spack requires the specification of flags the underlying compiler doesn't. Do we want to close this bug?

**Comment by DavidPoliakoff** [comment]
@becker33 caught it, turns out that compiler relies on a module to automatically work. Instead of modifying `flags` in that instance, you modify `modules`

**Comment by mwkrentel** [comment]
@DavidPoliakoff  So, you didn't fill in the `modules:` field in the
`compilers.yaml` entry for gcc@7.2.0?   Was that the problem?

@becker33  @tgamblin  See, this is where if `spack compiler find`
filled this in automatically, then this sort of problem wouldn't
happen.

This is just too easy a mistake to make and a very easy mistake to
overlook when reporting "bugs".

Nag, nag, :-)

**Comment by becker33** [comment]
@mwkrentel #11989, and yes, that's precisely what the bug was.
