### ISSUE TITLE
`buildcache list` does not show all binaries from target family

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#12935]
On RHEL7, I have Spack installed packages built with GCC 4.8.5 and also 7.3.0. The ones built with GCC 4.8.5 are tagged `haswell`, the ones built with 7.3.0 are tagged `broadwell`. I have created binaries of ALL these packages and put them in a mirror. `spack buildcache list` only shows me the binaries tagged `broadwell` even though I'm running it on the exact same machine where the packages were originally built.

**Comment by becker33** [comment]
Note: This is due to lines 613 and 630 in `lib/spack/spack/binary_distribution.py`

It will take slightly more work to come up with a solution.
