### ISSUE TITLE
spack does not report error when compiler is missing

### ISSUE THREAD

**Issue by martyitz** [spack/spack#12945]
I went to clean up my aging installs, and deleted all the files.  I did not
update `~/.spack/linux/compilers.yaml`, so it still pointed to  several compilers that
no longer existed.

I went to do various installs, and they all failed with errors that did not indicate
the problem was with the compiler.  I think spack should report an error like:

```
    gcc@7.3.0 specified in ~/.spack/linux/compilers.yaml does not exist
```

**Comment by tgamblin** [comment]
Thanks @martyitz!

**Comment by tgamblin** [comment]
It would be pretty easy to do a quick check before we start the build to see whether the chosen compiler still exists.  I would rather not do a check on all compilers at startup, as it'll increase our already slow (due to Python modules) startup time

**Comment by martyitz** [comment]
I agree.  No need to check the compilers that are not about to be used.

**Comment by michaelkuhn** [comment]
There is actually code for this but it is not working, see #9845 (probably needs a rebase and some smaller changes).
