### ISSUE TITLE
cannot specify multiple cflags on the command line

### ISSUE THREAD

**Issue by carns** [spack/spack#12951]
In the current origin/develop version of spack (presently e6cae97), I cannot figure out how to specify multiple cflags on the command line.

### Steps to reproduce the issue

```console
$ spack spec coreutils cflags="-g -fno-omit-frame-pointer"
```

### Error Message

```console
Input spec
--------------------------------
coreutils cflags="-g" ~fno-omit-frame-pointer

Concretized
--------------------------------
==> Error: Package coreutils has no variant fno-omit-frame-pointer!
```

If I check out revision a940ff34d and run the same command, then it works as expected:

```console
Input spec
--------------------------------
coreutils cflags="-g -fno-omit-frame-pointer" 

Concretized
--------------------------------
coreutils@8.29%gcc@8.3.0 cflags="-g -fno-omit-frame-pointer"  arch=linux-ubuntu19.04-x86_64
```

It appears as though the argument encapsulated with quotation marks are being split when they were not before.  Is there a different way to escape or group things like this now?

### Information on your system

Ubuntu 19.04

I don't believe the packages.yaml or package I am installing matters.  I just use coreutils as an example because it is simple in terms of dependencies.

**Comment by carns** [comment]
Anyone have an idea for a workaround?  This gets more problematic for debugging as origin/develop (and all of its package updates) diverges further from the working revision of spack.

**Comment by alalazo** [comment]
@carns Saw this issue right now. I need to investigate in which commit this broke, but apparently you can work around it by escaping spaces in your `cflags`:
```console
$ spack spec coreutils cflags="-g\ -fno-omit-frame-pointer"
Input spec
--------------------------------
coreutils cflags="-g -fno-omit-frame-pointer" 

Concretized
--------------------------------
coreutils@8.29%gcc@9.0.1 cflags="-g -fno-omit-frame-pointer"  arch=linux-ubuntu18.04-broadwell
```

**Comment by alalazo** [comment]
It seems this broke after merging #3206. Will investigate further on the issue.
