### ISSUE TITLE
.spack/compilers.yaml is now .spack/<os>/compilers.yaml

### ISSUE THREAD

**Issue by woodard** [spack/spack#12967]
simple doc fix
https://spack.readthedocs.io/en/latest/getting_started.html?highlight=compiler%20flags#manual-compiler-configuration

references ~/.spack/compilers.yaml now it appears to be ~/.spack/linux/compilers.yaml

**Comment by adamjstewart** [comment]
Technically, it's a bit more complicated than this. By default, Spack puts compilers in `~/.spack/<os>/compilers.yaml`, but there are several other accepted [configuration scopes](https://spack.readthedocs.io/en/latest/configuration.html#configuration-scopes). But I think it's a good idea to change the docs to reference the default location. Care to submit a PR? If not I can submit one for you.
