### ISSUE TITLE
`spack clean -s` doesn't clean stage dirs

### ISSUE THREAD

**Issue by hartzell** [spack/spack#13006]
I'm working on a mac, running OSX 10.13.6, with a git tree that's at `cfc17e95062a8d974bd95b881070199ffcb343f9`.

I believe that `spack clean -s` should clean up the staging dirs created by `spack stage <package>` but it doesn't seem to.

Might be "problem exists between keyboard and chair", but thought I'd check.

If it's a bug, I'll go hunting.  If not, I'll get more coffee.

```
$ ./bin/spack stage git-lfs
==> Fetching https://github.com/git-lfs/git-lfs/archive/v2.8.0.tar.gz
######################################################################## 100.0%
==> Staging archive: /var/folders/st/vgtczy7j31xgkh9npzh_rg6c0000gn/T/hartzell/spack-stage/git-lfs-2.8.0-cdow5we7ypqz3kqos6xab2tymj32qexo/v2.8.0.tar.gz
==> Created stage in /var/folders/st/vgtczy7j31xgkh9npzh_rg6c0000gn/T/hartzell/spack-stage/git-lfs-2.8.0-cdow5we7ypqz3kqos6xab2tymj32qexo
$ ls /var/folders/st/vgtczy7j31xgkh9npzh_rg6c0000gn/T/hartzell/spack-stage/git-lfs-2.8.0-cdow5we7ypqz3kqos6xab2tymj32qexo
spack-src	v2.8.0.tar.gz
$ ./bin/spack clean -s
==> Removing all temporary build stages
$ ls /var/folders/st/vgtczy7j31xgkh9npzh_rg6c0000gn/T/hartzell/spack-stage/git-lfs-2.8.0-cdow5we7ypqz3kqos6xab2tymj32qexo
spack-src	v2.8.0.tar.gz
$ ./bin/spack clean -a
==> Removing all temporary build stages
==> Removing cached downloads
==> Removing cached information on repositories
==> Removing python cache files
$ ls /var/folders/st/vgtczy7j31xgkh9npzh_rg6c0000gn/T/hartzell/spack-stage/git-lfs-2.8.0-cdow5we7ypqz3kqos6xab2tymj32qexo
spack-src	v2.8.0.tar.gz
$
```

**Comment by adamjstewart** [comment]
I can reproduce this bug on macOS 10.14.6 when running Spack with both Python 2 and 3.

**Comment by adamjstewart** [comment]
@tldahlgren was the last person to work on stages in #12072, she might be able to track down the problem.

**Comment by tldahlgren** [comment]
I am able to reproduce it as well.

**Comment by tldahlgren** [comment]
@hartzell @adamjstewart Can you confirm that #12733 resolves this issue for you?  (It removes the stage directory for me.)

**Comment by alalazo** [comment]
@tldahlgren I can confirm that #12733 resolves this issue for me too (stage dirs get deleted after `spack clean -s`).
