### ISSUE TITLE
Error building r with target=x86_64

### ISSUE THREAD

**Issue by pat-s** [spack/spack#13072]
Scenario:

- Frontend node arch is `linux-centos7-zen`. 
- Some compute nodes are on `linux-centos7-x86_64`

When building formula `r` on the frontend using `target=x86_64` (to get it running on the computes) everything builds. However, when trying to build the same formula directly on the computes (which the spack dir shared via NFS to the nodes) I get

```sh
     51    checking for gcc... /opt/spack/lib/spack/env/gcc/gcc
     52    checking whether the C compiler works... no
  >> 53    configure: error: in `/tmp/patrick/r-3.6.1-wjtv4kc2vxt4vtdwxjgab4er6wfnfsbv/spack-src':
  >> 54    configure: error: C compiler cannot create executables
     55    See `config.log' for more details
```

- [build log](https://transfer.sh/O0q25/spack-build-out.txt)
- I'm on c8c795e7dbde22dc47c9ae285a4dd59004b115b1 
- On the "frontend" I do `spack install r target=x86_64`
- On the node I do `spack install r` (defaults to arch=x86_64)

#### Why do I want to build the formula on the computes directly?
Currently when loading the x86_64 env module (which was built on the frontend) and executing the binary on the computes, I receive segfaults on the computes. I wanted to see if building the formula directly on the computes might solves this due to "better" support for the arch and cpu of the computes.

**Comment by alalazo** [comment]
Can you edit your description to add more details? Stating which commit you are on or showing the minimum set of commands that reproduce your issue or attaching the config.log could help debugging the issue.

**Comment by pat-s** [comment]
@alalazo Updated

**Comment by alalazo** [comment]
I don't see any `configure error` in the build log above :thinking: In any case, changing the issue tag from `bug` to `build-error`.

**Comment by pat-s** [comment]
@alalazo added the config.log to the first post.

**Comment by pat-s** [comment]
Updated to ea4f9ebbde50ae3606a6d8955512bc1b54299c51, issue persists.

**Comment by alalazo** [comment]
Changed the title to sound less alarming: I just built an entire stack of software using `target=x86_64` with a spec matrix :slightly_smiling_face:

**Comment by pat-s** [comment]
Hm. The problem for me is not even just `r`, any formula that needs some `gcc` compiling fails with that error (even when using the system compiler gcc@4.8.5).

If I build `x86_64` on the main node (which has actually `arch = zen`) everything is fine. 
Could it be related to the fact that the Spack Root is shared via NFS to the machines that show the problems?

**Comment by pat-s** [comment]
With 71eaffa46b1a64249b410f5222b537b37ff4c032 the issue persists.

**Comment by pat-s** [comment]
Don't know what I changed right now but now it works.. 🙄
