### ISSUE TITLE
Add microarchitecture specific flags for LLVM compilers

### ISSUE THREAD

**Issue by alalazo** [spack/spack#13104]
As a user I want to have microarchitecture specific flags injected for LLVM compilers so that I would compile by default code that is optimized for the target of the installation.

### Rationale

We already support this feature for GCC since #3206 and need to extend the capability to other compilers as well

### Description
What needs to be done is carefully reviewing docs and man pages, and encode in [this file](https://github.com/spack/spack/blob/develop/lib/spack/llnl/util/cpu/microarchitectures.json) the information found.

### Additional information
A non exhaustive list of pages we might want to consult:
- Docs linked in the official [Download page](https://releases.llvm.org/download.html)

We also need to check what will be the Fortran support for clang and if `flang` is compatible with all of the `-march` flags.

**Comment by adamjstewart** [comment]
@alalazo would this change require #12011?

**Comment by alalazo** [comment]
I wouldn't say it requires that, but they are related. Currently we could probably distinguish the two by the version suffix.

**Comment by alalazo** [comment]
The optimization flags for LLVM seem to be of the form:
```
-march=<family> -mcpu=<microarchitecture>
```
more info on the assembler [doc page](https://llvm.org/docs/CommandGuide/llc.html).

**Comment by adamjstewart** [comment]
Damn, LLVM + GCC is very common, especially on macOS. Maybe it's time we figure out a better way to handle mixed compiler support.
