### ISSUE TITLE
python3 breaks filter_file in papi package

### ISSUE THREAD

**Issue by mwkrentel** [spack/spack#13101]
The recent change to `bin/spack` to prefer python3 breaks packages
that have trouble with python3 on systems that have both python
versions 2 and 3.

```
commit 97980a8f94e0c3f868dc071a24c299d05b017de5 (HEAD)
Author: Todd Gamblin <tgamblin@llnl.gov>
Date:   Sat Sep 28 20:59:02 2019 -0700

    prefer Python 3 to Python 2 for running Spack
```

This is on a single node x86_64 workstation, Fedora 26, gcc 7.3.1.
`/usr/bin` has both python (2.7.15) and python3 (3.6.5).

Spack install papi hangs in `filter_file` at:

```
$ spack spec papi
papi@5.7.0%gcc@7.3.1 arch=linux-fedora26-westmere

$ spack install -v papi
...
==> [2019-10-08-22:44:20.061799] FILTER FILE: ./linux-bgq.h [replacing "\<malloc\.h\>"]
==> [2019-10-08-22:44:20.062630] FILTER FILE: ./freebsd.c [replacing "\<malloc\.h\>"]
==> [2019-10-08-22:44:20.066617] FILTER FILE: ./x86_cpuid_info.c [replacing "\<malloc\.h\>"]
```

This goes back to Feb 2018 in #7358.  But now it's more serious
because it's harder to avoid python3.  I noticed this with papi, but
there are other packages that use `filter_file`.

I normally include this in `packages.yaml`, but it fails both with and
without this.

```
packages:
  python:
    paths:
      python@2.7.15:  /usr
    buildable: False
```

I don't really know a satisfactory workaround, except to revert to the
last working commit or else hack `packages.py` to remove `filter_file`.

ping @tgamblin and @alalazo

**Comment by alalazo** [comment]
Can you check if #12765 fixes your issue?

**Comment by mwkrentel** [comment]
@alalazo Sorry, I found the old issue, but somehow I missed your
patch.

Anyway, yes, it does fix my problem.  Thanks!
