### ISSUE TITLE
Uninstall specific architecture

### ISSUE THREAD

**Issue by mrzv** [spack/spack#13111]
I'd like to uninstall all packages for a specific architecture. I just upgraded macOS from Mojave to Catalina, installed a number of new packages under Catalina, and now the old Mojave packages are getting in the way. Ideally, I'd like to just say `spack uninstall arch=darwin-mojave-x86_64` and get rid of all of them. I imagine a similar option would be helpful for removing everything built with a specific compiler version.

**Comment by alalazo** [comment]
You should be able to do that already by using the following command:
```console
$ spack uninstall -a os=mojave
```
Sidenote: while double checking for your answer I discovered an issue with targets using the same syntax in which the constraint was not respected correctly:
```console
$ spack uninstall -a target=x86_64
==> The following packages will be uninstalled:

    -- linux-ubuntu18.04-broadwell / gcc@9.2.0 ----------------------
    i3egwym hdf5@1.10.5%gcc ~cxx~debug~fortran~hl~mpi+pic+shared~szip~threadsafe  fmavkvd zlib@1.2.11%gcc +optimize+pic+shared

    -- linux-ubuntu18.04-haswell / gcc@9.2.0 ------------------------
    myrpqhu zlib@1.2.11%gcc +optimize+pic+shared

    -- linux-ubuntu18.04-x86_64 / gcc@9.0.1 -------------------------
    n55rsnw environment-modules@4.3.1%gcc ~X  msczui7 tcl@8.6.8%gcc   tn4qvs7 zlib@1.2.11%gcc +optimize+pic+shared

```
Above one should just uninstall `x86_64`, not `haswell` and `broadwell`. There's a fix for that in the PR linked above.

**Comment by mrzv** [comment]
Ah, great. I didn't know you could specify it this way. How about a compiler? In your example, if I wanted to remove anything under `gcc@9.0.1`, but not `gcc@9.2.0`, is there a way to communicate this to spack?

**Comment by adamjstewart** [comment]
Yep, just do:
```console
$ spack uninstall -a %gcc@9.0.1
```
Anything you can do with a spec can be used to specify which packages to uninstall. See:
```console
$ spack help --spec
```

**Comment by mrzv** [comment]
`spack help --spec` is very helpful. I wish I could find it before. Is it somewhere in the online docs?

**Comment by adamjstewart** [comment]
There is various info scattered throughout the docs on specs, but no specific mention of `spack help --spec`.

**Comment by adamjstewart** [comment]
@mrzv I'm glad to see I'm not the only one adventurous enough to make the upgrade to Catalina! By any chance, have you managed to get GCC to install? That's the only package I've had problems with so far.

**Comment by mrzv** [comment]
@adamjstewart I haven't tried to install GCC from spack. Actually, I don't know that I've ever tried to install a compiler through spack.

The only real problem I've had on Catalina is that not a single version of perl seems to build, and oddly perl is a dependency for virtually every package. My solution was to tell spack to use perl from `/usr/local` (from Homebrew) and to forget about installing its own. That solved everything.

**Comment by adamjstewart** [comment]
Really? Perl built just fine for me. I just updated the package to add a new version though.

**Comment by mrzv** [comment]
Yeah, I realized later that I should have manually updated it to 5.30.0, but by then I was using the Homebrew version.
