### ISSUE TITLE
Refactoring FLANG out of main LLVM package

### ISSUE THREAD

**Issue by naromero77** [spack/spack#13117]
This occurs on Ubuntu 18.04 TLS with Spack develop branch.

I believe this line:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/llvm/package.py#L593-595

causes an unintentional conflict with GCC@8: and llvm@flang-20180921. Error message is show below.

The easiest way to fix this is to have `flang` appear as a suffix instead of a prefix. Then you would have:
```
>>> Version("20180921-flang") < Version(5)
False
```
The other possibility is to have flang for LLVM be a variant instead of a version number.

```
(base) [naromero@naromero-desktop ~]$ spack spec flang
Input spec
--------------------------------
flang
Concretized
--------------------------------
==> Error: Conflicts in concretized spec "flang@20180921%gcc@8.3.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-westmere/ddlkqug"
List of matching conflicts for spec:
    llvm@flang-20180921%gcc@8.3.0~all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb~omp_tsan+polly~python~shared_libs arch=linux-ubuntu18.04-westmere
        ^binutils@2.32%gcc@8.3.0+gold~headers~libiberty+nls~plugins arch=linux-ubuntu18.04-westmere
            ^gettext@0.19.8.1%gcc@8.3.0+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-ubuntu18.04-westmere
                ^bzip2@1.0.8%gcc@8.3.0+shared arch=linux-ubuntu18.04-westmere
                    ^diffutils@3.7%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
                        ^libiconv@1.15%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
                ^libxml2@2.9.9%gcc@8.3.0~python arch=linux-ubuntu18.04-westmere
                    ^pkgconf@1.6.1%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
                    ^xz@5.2.4%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
                    ^zlib@1.2.11%gcc@8.3.0+optimize+pic+shared arch=linux-ubuntu18.04-westmere
                ^ncurses@6.1%gcc@8.3.0~symlinks~termlib arch=linux-ubuntu18.04-westmere
                ^tar@1.31%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
        ^cmake@3.15.3%gcc@8.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-westmere
            ^openssl@1.1.1c%gcc@8.3.0+systemcerts arch=linux-ubuntu18.04-westmere
                ^perl@5.26.2%gcc@8.3.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-ubuntu18.04-westmere
                    ^gdbm@1.18.1%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
                        ^readline@7.0%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
        ^gmp@6.1.2%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
            ^autoconf@2.69%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
                ^m4@1.4.18%gcc@8.3.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-ubuntu18.04-westmere
                    ^libsigsegv@2.11%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
            ^automake@1.16.1%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
            ^libtool@2.4.6%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
        ^isl@0.19%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
        ^libedit@3.1-20170329%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
        ^perl-data-dumper@2.173%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
        ^python@2.7.16%gcc@8.3.0+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-ubuntu18.04-westmere
            ^expat@2.2.5%gcc@8.3.0+libbsd arch=linux-ubuntu18.04-westmere
                ^libbsd@0.9.1%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
            ^libffi@3.2.1%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
            ^sqlite@3.29.0%gcc@8.3.0~column_metadata+fts~functions~rtree arch=linux-ubuntu18.04-westmere
        ^swig@4.0.0%gcc@8.3.0 arch=linux-ubuntu18.04-westmere
            ^pcre@8.42%gcc@8.3.0~jit+multibyte+utf arch=linux-ubuntu18.04-westmere
1. "%gcc@8:" conflicts with "llvm@:5"
```

**Comment by naromero77** [comment]
@tinlun @nazavode @scheibelp @alalazo

**Comment by nazavode** [comment]
Replying b/c I've been `git blame`-d: overhauling `flang` versions to fix the semantics of version operators looks like the most sensible approach to me while the `variant` way doesn't sound like it would fit (completely different repos between upstream and `flang`, for instance).

As a side note: `flang` has been put on a dead track and a complete rewrite from scratch is supposed to supersede it in Q1 2020 (more info [here](https://github.com/flang-compiler/flang/wiki)). Given this, and taking into account this specific issue, putting the `spack` support for `flang` on a dead track too could be doable if it helps streamlining the package pointing to upstream `llvm`.

**Comment by naromero77** [comment]
@nazavode Right, `f18` will supersede `flang` in 2020.

I still think that `flang` will get used for a while, so it would be totally worth it to fix the semantics of version operators. 

If the git repos are completely different, would it make more sense to have a complete separate Spack package llvm-flang? Or would that lead to too much duplication?

**Comment by nazavode** [comment]
> If the git repos are completely different, would it make more sense to have a complete separate Spack package llvm-flang? Or would that lead to too much duplication?

Given that spack already has a separate package for `f18` and `flang` is (probably) going to turn into a stale codebase in the long run (so the `flang`-related code would slowly become a relic inside the `llvm` package), this sounds like the most reasonable solution to me. I'm not a spack maintainer tho, better to ping someone here (@alalazo).

**Comment by naromero77** [comment]
I am very agnostic about the solution. Fixing the semantics of the version operator is fine with me. I am not so familiar with all these packages, so I am hoping you are willing to fix it @nazavode

**Comment by naromero77** [comment]
@nazavode I wanted to ping you again since its been a week. If we are in agreement on the fix (semantics), I can make an attempt to fix this if you are too busy to address it in the near future.

**Comment by naromero77** [comment]
@nazavode @alalazo @adamjstewart 

I am looking through llvm Spack package which the flang Spack depends (specified through a unique version system).

Now that I am reading @nazavode comments more carefully. I think it would make more sense to move the llvm-flang fork (buried in the Spack LLVM package) into its own Spack package, calling llvm-flang. The problem is that llvm-flang uses a different version system than llvm and may even have different variants. Also, looking through all the code in the LLVM package makes me wonder how much of it applies to the LLVM-FLANG fork. (I do see some places where there are exclusions).

My proposal would be to excise LLVM-FLANG stuff in the LLVM Spack package into its own LLVM-FLANG Spack package. This refactorization would make it much easier to eliminate the problematic versioning present in flang Spack package. Introduce variants as needed, e.g. there are target offload capabilities for the NVidia GPU that should get added. If LLVM-FLANG fork ever gets merged upstream, (I think its unlikely at this point), we can update the dependency.

Eventually `f18` will take over the world, but in the mean time it would be desirable to keep `flang` around an up to date.

I would like to get some buy in before I attempt this. Its a fair amount of work to get the refactorization into a seperate Spack package done.

**Comment by homerdin** [comment]
Moving forward the main LLVM development is (as of last week during the Dev Meeting)on GitHub using the mono-repo (all llvm projects live side-by-side).  If you factor out the FLANG parts of the LLVM Spackage we can also factor out the rest of the resource logic in the LLVM Spackage (https://github.com/spack/spack/pull/11392).

Once f18 moves upstream, for the mono-repo all that will be needed is a to add `flang` to the `ENABLE_PROJECTS` list.

**Comment by naromero77** [comment]
@trws After taking a look at this with @homerdin and looking at where `flang` and `f18` is headed, I want to change/amend my earlier proposition. Here is what I propose:
`llvm-flang` : does not exist now and there is no need to increase complexity by creating it. both `flang` and `f18` now appear to be using *different* forks of `llvm.` According to the last ECP timeline that I have, at least for `f18`, the `llvm` changes should get upstream in CY2020 (not earlier than the end of Q1). 
`pgmath` : no other package uses it and it should just get absorbed into `flang` package

To drive home what I am proposing:
`flang` : Absorb the flang specific bits from the `llvm` package into this package. `pgmath` and the other components would get added as a `resource`. In other words, there is `flang` package that uses `resource` to compile all its components. Whether this is short lived, or long-term solution is TBD.
`f18` : Similar to the solution for the `flang` package except that it will most likely be a short-lived solution. I know that that Pat Cormick (LANL) is working on a monorepo version of `f18`, but PGI has not started using it yet.

**Comment by trws** [comment]
That seems reasonable.  I'd expect f18 to become part of the main llvm package at some point in 2020, but it sounds great for the current situation.

**Comment by naromero77** [comment]
@trws I spent about two full days trying to get a self-contained `flang` package, unfortunately I did not manage to get this working. @homerdin even gave me some pointers today and I thought I was making some progress, but ultimately I couldn't make it happen.

The problem is that Flang compiler depends on the Flang-fork of LLVM being already built (a sequentially dependence). I also can't just drop the Flang compiler in as a project and have it built in a single instance of Cmake. Perhaps some CMake wizard could figure it out. I did not explore hacking a `post-install` method into the Spack package because those are not pretty solutions and would be hard to maintain.

Here are some options: 
1. Do nothing, but live with the Flang stuff hacked into the main LLVM package.
2. Excise the Flang stuff out of the main LLVM package and create an LLVM-flang package. This was the original idea I had proposed.

Option 2., would make the main LLVM package a lot cleaner but would introduce a second LLVM package, call it: LLVM-flang package. 

Let me know what you think.

**Comment by naromero77** [comment]
@trws @homerdin 

Any additional feedback for me?

Again, to summarize. I think the quickest fix is to pull the flang stuff out of the main LLVM package and create a LLVM-flang package. I looked at f18 package as well, it just uses the plain vanilla LLVM package -- since its really only a front-end at the moment.

What will be the lifetime of the LLVM-flang package? Not sure, but hopefully not super long. f18 will hopefully be deployed in production by sometime in 2020 which would make flang obsolescent. In the mean time, just getting those extra `if spec = '+flang'` out of the main LLVM package would make it easier to maintain the package.

I am also OK with just leaving things `AS IS`, since it seems to work.

**Comment by trws** [comment]
I'd lean toward Option 2 personally, and just create the llvm-flang package.  It's not awesome, but it is actually a partially incompatible fork, so I think it's more appropriate that way anyway.

**Comment by naromero77** [comment]
@adamjstewart Actually, we closed this prematurely.

@homerdin I am hoping that you can delete the `flang` stuff from the main `llvm` package. 

Then we can close this issue.
