### ISSUE TITLE
F18 install method fails

### ISSUE THREAD

**Issue by naromero77** [spack/spack#13118]
@certik @alalazo 

The error occurs on Ubuntu 18.04 TLS.

Just do:
`spack install f18%gcc`

At the very end, you get this error:
```
==> Executing phase: 'install'
==> Error: FileNotFoundError: [Errno 2] No such file or directory: 'spack-build/tools/f18/bin/f18'

/nfs/gce/projects/naromero-workspace/spack/var/spack/repos/builtin/packages/f18/package.py:23, in install:
         21    def install(self, spec, prefix):
         22        mkdirp(prefix.bin)
  >>     23        install("spack-build/tools/f18/bin/f18", prefix.bin)

See build log for details:
  /scratch/naromero/tmp/spack-stage/f18-develop-2phe4xzmxxvbladdut5yrmw4ic6btf5j/spack-build-out.txt
```

So `f18` is build correctly, but the install command gives an error. This is because the bin subdirectory does not exist in the Spack *target* subdirectory.

As an example, I used the `install_tree` command for one of my Spack packages:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/qmcpack/package.py#L347

**Comment by certik** [comment]
@naromero77 thanks for reporting it. Would you mind sending a PR that fixes it for you? That would be a big help.
