### ISSUE TITLE
specify preinstalled numpy in ~/.spack/packages.yaml

### ISSUE THREAD

**Issue by balay** [spack/spack#13190]
Most python installs already have numpy installed.  However spack attempts to build it [when there is a py-numpy dependency]

What this the correct way
to specify numpy in ~/.spack/packages.yaml so that one can reuse both pre-installed python and nympy [and perhaps other python modules]

**Comment by adamjstewart** [comment]
You would use the same installation prefix that you used for Python when you specify the path to the external numpy library. Same for all other Python packages.

**Comment by balay** [comment]
Thanks! I have the following in .spack/packages.yaml

```
  python:
    paths:
      python@3.6.6: /usr
    buildable: False
  py-numpy:
   paths:
    py-numpy@1.12.1: /usr
    buildable: False

```
And get the following:

```
bash-4.2$ spack spec py-libensemble
==> Warning: specifying a "dotkit" module root has no effect [support for dotkit module files has been dropped]
Input spec
--------------------------------
py-libensemble

Concretized
--------------------------------
py-libensemble@0.5.2%intel@18.0.2 cflags="-O3 -fp-model fast -xMIC-AVX512" cxxflags="-O3 -fp-model fast -xMIC-AVX512" fflags="-O3 -fp-model fast -xMIC-AVX512" ~mpi~nlopt~petsc4py~scipy arch=linux-centos7-mic_knl
    ^py-numpy@1.12.1%intel@18.0.2 cflags="-O3 -fp-model fast -xMIC-AVX512" cxxflags="-O3 -fp-model fast -xMIC-AVX512" fflags="-O3 -fp-model fast -xMIC-AVX512" +blas+lapack arch=linux-centos7-mic_knl
    ^py-setuptools@41.0.1%intel@18.0.2 cflags="-O3 -fp-model fast -xMIC-AVX512" cxxflags="-O3 -fp-model fast -xMIC-AVX512" fflags="-O3 -fp-model fast -xMIC-AVX512"  arch=linux-centos7-mic_knl
        ^python@3.6.6%intel@18.0.2 cflags="-O3 -fp-model fast -xMIC-AVX512" cxxflags="-O3 -fp-model fast -xMIC-AVX512" fflags="-O3 -fp-model fast -xMIC-AVX512" +bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-centos7-mic_knl

bash-4.2$ spack install py-libensemble
==> Warning: specifying a "dotkit" module root has no effect [support for dotkit module files has been dropped]
==> py-numpy@1.12.1 : externally installed in /usr
==> py-numpy@1.12.1 : generating module file
==> Error: 'No spec with name blas in py-numpy@1.12.1%intel@18.0.2 cflags="-O3 -fp-model fast -xMIC-AVX512" cxxflags="-O3 -fp-model fast -xMIC-AVX512" fflags="-O3 -fp-model fast -xMIC-AVX512" +blas+lapack arch=linux-centos7-mic_knl'
bash-4.2$ 
```

Any idea what this erorr means or how to overcome it?

**Comment by adamjstewart** [comment]
@balay This bug will be fixed by @alalazo's #11115, although I think I can hack the package to fix it in the meantime. Also see #9149. The issue is that currently, Spack calls `setup_environment` twice; once to set up the build environment, and again to set up the run environment (module files). In the numpy package, I try to see which BLAS/LAPACK library has been chosen in order to set environment variables that control the build. But since your package is external, its dependencies aren't present in the spec. Let me see if I can hack it.

**Comment by balay** [comment]
Thanks. For now - I have a workaround - but curious about the correct usage. Glad there is a fix.

here is a related issue - I guess with mixing build stuff with run stuff..

Instead of `python@3.6.6: /usr` - if I use `python@3.6.8: /usr` [this is the correct version of the installed python package]

```
bash-4.2$ spack spec py-libensemble
==> Warning: specifying a "dotkit" module root has no effect [support for dotkit module files has been dropped]
Input spec
--------------------------------
py-libensemble

Concretized
--------------------------------
==> Error: Conflicts in concretized spec "py-libensemble@0.5.2%intel@18.0.2~mpi~nlopt~petsc4py~scipy arch=linux-centos7-mic_knl/rzsdmw5"

List of matching conflicts for spec:

    python@3.6.8%intel@18.0.2 cflags="-O3 -fp-model fast -xMIC-AVX512" cxxflags="-O3 -fp-model fast -xMIC-AVX512" fflags="-O3 -fp-model fast -xMIC-AVX512" +bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-centos7-mic_knl

1. "%intel" conflicts with "python@3.6.7:"

bash-4.2$ 
```

Part of the reason for this is - installing py-libensemble for knl - is best with intel compilers - but then - python doesn't play well with intel compilers.

My workaround is: <without numpy in ~/.spack/packages.yaml>

```
spack install -j48 xsdk%intel@18.0.2~precice~butterflypack ^py-numpy%gcc@8.1.0
```
And I'm getting into different type of python issues on different machines [just working around them for now. for ex: using system python on OSX with both clang and brew-gcc has different issues - but I got some workarround for that aswell]

cc: @shuds13

**Comment by adamjstewart** [comment]
Yes, your workarounds of either lying about the Python version or specifying `foo%intel ^python%gcc` are both valid. I really wish we could get newer versions of Python to build with Intel though. That's a strong reason that #10319 hasn't been merged yet.

**Comment by adamjstewart** [comment]
@balay did you have any other issues using an external Python installation, or can we close this issue?

**Comment by balay** [comment]
sure we can close this. thanks!
