### ISSUE TITLE
Spack failing after loading python

### ISSUE THREAD

**Issue by mdorier** [spack/spack#13210]
I'm on a Debian 10 machine, which has python 2.7.16 installed in system directories.
I have installed Python 3.7.4 through Spack. As soon as I load this package (or if it is loaded as part of a `spack load -r` of another package) the next spack commands I issue fail. For example, `spack load` gives me `==> Error: Unknown command: module` (even though the module command is available on the command line). `spack` gives me a Python stack trace leading up to `ModuleNotFoundError: No module named '_ssl'`.

I have seen this happen also on Theta, with different error messages.

Maybe the fix would be to use some environment variables that, if set, specifies which Python (and Python home) should be used to execute spack, regardless of whether another Python is loaded.

**Comment by alalazo** [comment]
> I have installed Python 3.7.4 through Spack [...] gives me a Python stack trace leading up to ModuleNotFoundError: No module named '_ssl'.

Can you check your build logs and see if there were errors when compiling Python's standard libraries?

**Comment by mdorier** [comment]
Unfortunately I don't have the logs anymore. You think Python didn't find OpenSSL and silently skipped it? (entirely possible)

**Comment by alalazo** [comment]
> Unfortunately I don't have the logs anymore. You think Python didn't find OpenSSL and silently skipped it? (entirely possible)

Asking because it happened so many times to me... Python build will happily proceed without part of the standard library. If that's the case you'll find warnings in the logs.

**Comment by alalazo** [comment]
> Unfortunately I don't have the logs anymore.

Maybe you already know it, but if you still have that Python installed the logs are copied in one of `<prefix>/.spack` subfolders so that you can still inspect them.

**Comment by mdorier** [comment]
Thanks, I didn't know. I can indeed see the following in the logs:

```
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
```

That could be the problem on my Debian machine. On Theta it's a different error, though, when loading python. I'll update the issue when I get the chance.

**Comment by mdorier** [comment]
I can confirm that reinstalling Python made things work on my Debian machine. The problem was cause by the fact that I had told spack (through packages.yaml) that I have openssl installed on the system (since `openssl version` returned me something), but I actually had only the program, not the library and headers, hence Python wasn't building with SSL support.

I'm going to close this particular issue and reopen one with the specific problem I have on Theta.

**Comment by mgnisia** [comment]
After facing this issue as well: I wanted to share my solution for the python version `3.5.0`. Here the problem was that it requires a openssl version of 1. If you install with spack with the latest version it doesn't work. If you define this dependency the `_ssl` problem was fixed.
`spack install python@3.5.0 ^openssl@1.0.2t`
