### ISSUE TITLE
Build error: GCC 9.2.0 on Catalina

### ISSUE THREAD

**Issue by healther** [spack/spack#13232]
### Steps to reproduce the issue

```console
$ spack install gcc
... 
  >> 586650    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:443:34: error: expected declaration speci
               fiers before '__OSX_AVAILABLE_STARTING'
     586651      443 | int     getiopolicy_np(int, int) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_2_0);
     586652          |   
[and similar stuff]
```

### Platform and user environment

Please report your OS here:
```commandline
healther@MacBook-Air spack % uname -a
Darwin MacBook-Air.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
``` 

This seems to be a partially known issue for example [gnu bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90835#c12), and [stackexchange](https://apple.stackexchange.com/questions/372305/compiling-gcc-on-catalina) with a proposed solution essentially ending up patching system headers like [here](https://solarianprogrammer.com/2019/10/12/compiling-gcc-macos/). We should probably follow [homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb)s approach, where they apply this [patch](https://raw.githubusercontent.com/Homebrew/formula-patches/b8b8e65e/gcc/9.2.0-catalina.patch). However I'm not sure whether the bugzilla report should be taken as an indication that upstream gcc will fix things...

**Comment by healther** [comment]
I have a test build running right now, will open a PR when it's done

**Comment by adamjstewart** [comment]
#13202

**Comment by healther** [comment]
Do you mind separating the patch part out of that PR? This (should?) break all builds of gcc right now and the `disable-bootstrap` part at least requires consideration

**Comment by adamjstewart** [comment]
Fair enough, I may just take out the bootstrapping thing for now and leave that for a separate PR.
