### ISSUE TITLE
How other can use created package 

### ISSUE THREAD

**Issue by SheraLee** [spack/spack#13264]
I am pretty new to Spack, I am not sure if what I am asking about makes sense.

I have written the python.py for our package, and I can install our package properly for myself. I want to share it with my teammates, but not sure how should we do it. For now, I just ask them to call `spack create ` and then copy-paste my python.py into the auto formed one. I wonder if there is a better way to do it?

Thanks a lot!

**Comment by adamjstewart** [comment]
@SheraLee The best way is to submit a pull request here, then not only your team but thousands of other users can use your package! See https://spack.readthedocs.io/en/latest/contribution_guide.html for details.

**Comment by SheraLee** [comment]
Thank you for your reply! Since we are still testing our package, is there any we can share the package privately?

**Comment by adamjstewart** [comment]
You can create a shared repository containing the packages you want available to your team: https://spack.readthedocs.io/en/latest/repositories.html

**Comment by tgamblin** [comment]
@SheraLee: you can also give your teammates access to your Spack branch before you submit the PR.  That may be easier.

**Comment by SheraLee** [comment]
Thank you so much! You guys are really helpful! As a college student without much experience, I really appreciate it a lot!
