### ISSUE TITLE
setup-env.sh finds wrong architecture on theta

### ISSUE THREAD

**Issue by shuds13** [spack/spack#13388]
When I run $SPACK_ROOT/share/spack/setup-env.sh on Theta:

It is trying to append this to my modules MODULEPATH:

    $SPACK_ROOT/share/spack/modules/cray-cnl6-x86_64

But the spack created modules are in

    $SPACK_ROOT/share/spack/modules/cray-cnl6-mic_knl

Seems like a cross-compilation issue. However, spack spec manages to find cray-cnl6-mic_knl
when run in same environment.

If I manually add the correct path to my MODULEPATH it works:

    export MODULEPATH=$SPACK_ROOT/share/spack/modules/cray-cnl6-mic_knl:$MODULEPATH

I can now spack load (or module load). Eg:

    spack load py-libensemble

**Comment by frankwillmore** [comment]
I've just reproduced essentially the same behavior on nersc. I have builds for three architectures, but only the module for the 'default' architecture can be loaded. I don't know if this is by design. This is for a pristine spack installation in user space on cori: 
```willmore@cori10:~> spack load ncurses
==> Error: the constraint '['ncurses']' matches multiple packages:
	mq3xd2q ncurses@6.1%gcc@8.3.0~symlinks~termlib arch=cray-cnl7-haswell
	35bgr5t ncurses@6.1%gcc@8.3.0~symlinks~termlib arch=cray-cnl7-mic_knl
	ode64k7 ncurses@6.1%gcc@7.4.1~symlinks~termlib arch=linux-sles15-x86_64

==> Error: In this context exactly **one** match is needed: please specify your constraints better.

willmore@cori10:~> spack load ncurses /ode
ModuleCmd_Load.c(244):ERROR:105: Unable to locate a modulefile for 'ncurses-6.1-gcc-7.4.1-ode64k7'
willmore@cori10:~> spack load ncurses /35b
ModuleCmd_Load.c(244):ERROR:105: Unable to locate a modulefile for 'ncurses-6.1-gcc-8.3.0-35bgr5t'
willmore@cori10:~> spack load ncurses /mq3x
willmore@cori10:~> 
```

**Comment by frankwillmore** [comment]
@shuds13 I'm curious why you have a cray-cnl6-mic_knl architecture specified? There should only be cray-cnl6-mic_knl or linux-sles12-x86_64 on theta, unless you tinkered with some other settings?

**Comment by shuds13** [comment]
To clarify this, my build is for cray-cnl6-mic_knl. I'm not sure where cray-cnl6-x86_64 comes from, but the setup-env.sh is pre-pending this to my module path instead of cray-cnl6-mic_knl.

**Comment by shuds13** [comment]
My modules are:

Currently Loaded Modulefiles:
  1) modules/3.2.11.1                                 13) dvs/2.7_2.2.120-6.0.7.1_12.5__g74cb2cc4
  2) intel/18.0.0.128                                 14) alps/6.6.43-6.0.7.1_5.51__ga796da32.ari
  3) craype-network-aries                             15) rca/2.2.18-6.0.7.1_5.52__g2aa4f39.ari
  4) craype/2.5.15                                    16) atp/2.1.3
  5) cray-libsci/18.07.1                              17) perftools-base/7.0.4
  6) udreg/2.3.2-6.0.7.1_5.15__g5196236.ari           18) PrgEnv-intel/6.0.4
  7) ugni/6.0.14.0-6.0.7.1_3.15__gea11d3d.ari         19) craype-mic-knl
  8) pmi/5.0.14                                       20) cray-mpich/7.7.3
  9) dmapp/7.1.1-6.0.7.1_6.6__g45d1b37.ari            21) nompirun/nompirun
 10) gni-headers/5.0.12.0-6.0.7.1_3.13__g3b1768f.ari  22) darshan/3.1.5
 11) xpmem/2.2.15-6.0.7.1_5.13__g7549d06.ari          23) trackdeps
 12) job/2.2.3-6.0.7.1_5.48__g6c4e934.ari             24) xalt

**Comment by alalazo** [comment]
:cry: https://www.alcf.anl.gov/news/theta-supercomputer-set-retire-look-back-its-impact-science-argonne-and-beyond I guess this issue is no more relevant
