### ISSUE TITLE
gcc: build issue on aarch64

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#13398]
Spack is failing to build gcc on ARM systems using our side-installed gcc compilers:

[lee218@ulna2:spack-gcc-arm]$ ./bin/spack install --keep-stage gcc@9.2.0%gcc@7.3 

...

  >> 10226    /tmp/lee218/spack-stage/spack-stage-gcc-9.2.0-fm7js2yexc7zo54qv54
              jjanbxft5jorq/spack-src/spack-build/./gcc/cc1: error while loadin
              g shared libraries: libisl.so.19: cannot open shared object file:
               No such file or directory

On our ARM systems, the side-installed gcc compiler (i.e., /opt/rh/devtoolset-7/root/bin/gcc ) hardcodes LD as /opt/rh/devtoolset-7/root/usr/libexec/gcc/aarch64-redhat-linux/7/ld. This is found by configure when running gcc -print-prog-name=ld:
 
[lee218@ulna2:spack-src]$ /opt/rh/devtoolset-7/root/bin/gcc -print-prog-name=ld
/opt/rh/devtoolset-7/root/usr/libexec/gcc/aarch64-redhat-linux/7/ld
 
Effectively, this finds anything in the in th/opt/rh/devtoolset-7/root/usr/libexec/gcc/aarch64-redhat-linux/7 directory and will print the full path, otherwise, it will just echo the “-print-prog-name” value:
 
[lee218@ulna2:spack-src]$ /opt/rh/devtoolset-7/root/bin/gcc -print-prog-name=blahblahblah
blahblahblah
 
With most of our other gcc builds (on x86 systems, /usr/bin/gcc on x86 and arm, spack-built gcc, etc.), the search directory does not contain ld and thus the command just prints “ld” and effectively uses Spack’s wrapper and gets the necessary rpaths for libisl.so.

This method of finding ld is in gcc's configure script, so one solution may be to add a patch that modifies the configure script to avoid using the full-path ld and just use ld instead. I'm not sure if there are any unintended consequences. It's also not clear to me at this point whether other configure scripts do similar things and thus merits a more general solution.

**Comment by tgamblin** [comment]
Moving this to 0.14 and assigning to @becker33.  We need to fix this but it won't be in for 0.13.2.

**Comment by eugeneswalker** [comment]
Do we think this will still make it in for 0.14?

**Comment by becker33** [comment]
@lee218llnl can you confirm #17280 resolves this issue? I have tested it building `gcc@9.3.0 %gcc@7.3.0` on ulna.llnl.gov

**Comment by lee218llnl** [comment]
This worked for me too.
