### ISSUE TITLE
gcc builds fail for C++ projects

### ISSUE THREAD

**Issue by michaelkuhn** [spack/spack#13391]
It looks like #13202 introduced a libiconv dependency for gcc. This makes C++ builds fail for me with error messages such as these (in this case, cmake bootstrapping):
```
../opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/gcc-9.2.0-7kzpeggfu32layxcv6rzunmef5ah7uwv/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib64/libstdc++.so: undefined reference to `libiconv'
```
It looks like the binaries are correctly linked against libiconv but libstdc++ is not.

cc @adamjstewart

**Comment by adamjstewart** [comment]
Hmm, that’s odd. I only added the libiconv dependency because I noticed the build was picking up my system libiconv. If it’s problematic, we can remove it.

**Comment by michaelkuhn** [comment]
Without the libiconv dependency, gcc seems to pick the symbols from glibc for me (that's on Linux, though). I found a few references to this bug but no fixes (always seems to happen if libiconv is not available in a system prefix). Have you checked whether libstdc++ is actually linked against/using Spack's libiconv in your case?

**Comment by adamjstewart** [comment]
It looks like none of my libraries link to `libiconv`, only the compiler binaries.

**Comment by michaelkuhn** [comment]
> It looks like none of my libraries link to `libiconv`, only the compiler binaries.

Same for me. Does your libstdc++ still try to use the symbols (`readelf -s .../lib64/libstdc++.so | grep iconv`)?

**Comment by adamjstewart** [comment]
`libstdc++` doesn't try to use symbols:
```console
$ otool -l lib/libstdc++.dylib | grep iconv
```
but `gcc` does:
```console
$ otool -l bin/gcc | grep iconv
         name /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/libiconv-1.16-gj3jnj46xug7rpjxwaepe6uwx35jdphz/lib/libiconv.2.dylib (offset 24)
```
