### ISSUE TITLE
Installation issue: fenics fails to configure due to missing py-ply

### ISSUE THREAD

**Issue by davydden** [spack/spack#13397]
### Steps to reproduce the issue

```console
$ spack install fenics%gcc@9.2.0~parmetis ^python@3.8.0 ^cmake@3.15.4
```

### Platform and user environment

Please report your OS here:
```
$ lsb_release -d
Description:	CentOS Linux release 7.6.1810 (Core)
```

### Additional information

I tried activating `spack activate py-ply` the `ply` package before installing, but CMake is still unhappy...

**Comment by adamjstewart** [comment]
Can you try this again on develop? The entire fenics ecosystem has been completely rewritten in Spack.
