### ISSUE TITLE
netCDF-C bump to 4.7.2

### ISSUE THREAD

**Issue by yellowhat** [spack/spack#13414]
Hi,
building netCDF 4.7.0 I got this bug: https://github.com/Unidata/netcdf-c/issues/1408.
Forcing spack to build the 4.7.2 version, solved the problem for me.
So I would like to ask if it is possible to bump netCDF to 4.7.2.

Thanks

---

### Steps to reproduce the issue

```console
$ spack install netcdf
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux vmTest01 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
CentOS 7.7
```

**Comment by adamjstewart** [comment]
Of course! Want to submit a pull request?

**Comment by yellowhat** [comment]
I do not have a modification ready.
Can you do it?
