### ISSUE TITLE
No easy update for kahip

### ISSUE THREAD

**Issue by olesenm** [spack/spack#13466]
I would like to get the kahip package updated to the most recent version (2.11), but there are a few issues with this AFAICT:

- project has moved to using CMake instead of Scons
- project now distributed via github instead of the Karlsruhe site.

The new distribution location can be addressed with some url_for_version magic, but I don't quickly see a simple means of changing to CMake whilst still maintaining the older kahip 2.00 package.

@adamjstewart

**Comment by adamjstewart** [comment]
Yes, this is one of the more complicated things Spack doesn't have great support for. What I've done in the past is to switch the base class to `Package` and manually implement the `install` method for each build system. You can then add a `@when('@1.2.3:')` to the newer `install` method. See https://github.com/spack/spack/pull/12941#issuecomment-538105434 for a list of packages that have had to do this already. I added `kahip` to this list.

**Comment by adamjstewart** [comment]
I finally got around to documenting this! Can you see if #25174 does a good job of explaining how to support multiple build systems? If anything is unclear, let me know and I'll try to improve the docs.
