### ISSUE TITLE
`spack load` broken for multi-architecture deployments by #10975

### ISSUE THREAD

**Issue by obreitwi** [spack/spack#13501]
In order to accommodate all places where our spack install is used, we compile all packages for an older target (`sandybridge`). Systems which have a newer micro architecture (e.g., `ivybridge`) fail to load the module command because #10975 tries to load the installed `environment-modules` package for the current target architecture only, not falling back to compatible older ones.

**Comment by healther** [comment]
@scheibelp @ajw1980

**Comment by alalazo** [comment]
Adding another detail. The `environment-modules` above has been installed with:
```console
$ spack bootstrap
```

**Comment by obreitwi** [comment]
> Adding another detail. The `environment-modules` above has been installed with:
> 
> ```
> $ spack bootstrap
> ```

`spack bootstrap` defaults to installing `environment-modules` for the current system's architecture, which we want to avoid because the system on which spack is installing is newer than some systems that spack will be used on. So we install the environment modules with a custom older target.

We are currently in the process of merging [2cd8003](https://github.com/electronicvisions/spack/tree/sandbox/breitwieser/upstream_merge_base_7) into [our branch](https://github.com/electronicvisions/spack/tree/visionary), but #12431 along with changes regarding  [micro-architectures](https://github.com/spack/spack/commit/3c4322bf1abb7af691179434652188b64e90e4dc) make things rather time consuming.

The minimal example would be
1. install `environment-modules` for an older target than the current system is on (i.e. `sandybridge` on an `ivybridge` system)
2. try to source `share/spack/setup-env.sh`
3. observe that the `module` command is missing due to the fact that #10975 only wants to load for the current architecture and hence `_sp_module_prefix` will be set to `not installed` despite `environment-modules` being installed

I'll get back to you with a complete log.

**Comment by alalazo** [comment]
> spack bootstrap defaults to installing environment-modules for the current system's architecture, which we want to avoid because the system on which spack is installing is newer than some systems that spack will be used on. So we install the environment modules with a custom older target.

Nope. On `develop` it installs for `x86_64` which is the common denominator.

**Comment by alalazo** [comment]
Duplicate of #13073

**Comment by alalazo** [comment]
@obreitwi If I am not mistaken this has been solved in #13105

**Comment by obreitwi** [comment]
> @obreitwi If I am not mistaken this has been solved in #13105

It sure looks like it, thank you! I'll only get to test it once we do the next upstream merge (right now we've reverted #10975 as we only have one `environment-modules`). If any issues should arise I will reopen…
