### ISSUE TITLE
GCC 7.2.0 and CMake 3.15.4 built with Spack 0.13.0 breaks CMake detection of C++14 support

### ISSUE THREAD

**Issue by bartlettroscoe** [spack/spack#13550]
CC: @fryeguy52, @bradking

Tag: snl-atdm-issue

After upgrading spack to version 0.13.0, cmake 3.15.4 + g++ 7.2.0, both built with spack, can not enable C++14 support using CMake code like:

```
target_compile_features(${DETECTION_LIBRARY} INTERFACE cxx_std_14)
```

**Comment by bartlettroscoe** [comment]
I lost many hours debugging this.  This upgrade of Spack 0.13.0 has been nightmare.

**Comment by bartlettroscoe** [comment]
The breaking commit was 0fb563f3d9f944f25f3badbf91d53754ef075aaa.  I will post a PR to fix this.

**Comment by bartlettroscoe** [comment]
Shoot, removing  '`-with-pkgversion=Spack GCC` to put back the standard g++ version:

```
$ which g++
/home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/gcc-7.2.0-6qrvkfmcwnwc5ilcl6ta4mndeguu5oon/bin/g++

$ g++ --version
g++ (GCC) 7.2.0
```

did not fix the problem with CMake 3.15.4 detecting C++14 support.

I will try putting the gcc/package.py file back exactly the way it was in our prior version of spack and see if that fixes the problem.

**Comment by adamjstewart** [comment]
@bartlettroscoe Sorry for all the trouble you went through! I would be surprised if `--with-pkgversion` was the issue, as [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb#L59) and Anaconda also hack this in the same way we do. Let me know if you figure out which change is causing the issue.

**Comment by bartlettroscoe** [comment]
Looks like the problem may be with cmake 3.15.4 (or at least the spack build of cmake 3.15.4).

When I reverted gcc/package.py to our prior version, cmake 3.15.4 still could not correctly detect C++14 support (and set `-std=gnu++14`).  I then used some older cmake versions 3.12.2 and 3.13.4 and both of them correctly detected C++14 support with gcc 7.2.0 and set `-std=gnu++14`.

I am now rebuilding building/installing gcc@7.2.0 with the Spack v0.13.0 version of gcc/package.py and several versions of CMake and will experiment to see if any of these cmake versions work.

**Comment by alalazo** [comment]
> Looks like the problem may be with cmake 3.15.4 (or at least the spack build of cmake 3.15.4).

@bartlettroscoe Can you briefly update the description to be consistent with the latest diagnosis of the issue?

**Comment by bartlettroscoe** [comment]
> Can you briefly update the description to be consistent with the latest diagnosis of the issue?

@alalazo, I have updated it.  And sorry to jump to conclusions.

It is just that I have been working through issues for over a week now trying to upgrade Spack  (see `snl-atdm` issues over the last couple of weeks)  and this was one that looked like is was going to kill the upgrade (or any future upgrade of Spack).

I will report back the final outcome.

**Comment by bartlettroscoe** [comment]
I think that I have verified that the problem is indeed with CMake 3.15.4 and not with how Spack is building GCC 7.2.0 with v0.13.0.  I have put back gcc/packages.py and I downgraded to CMake 3.14.5 and now it CMake correctly detect C++14 support and puts `-std=gnu++14` on the compile line.  The only changes in our version of Spack (on our branch 'snl-atdm') compared to 0.13.0 are in the files:

```
$ git diff --name-status HEAD --not v0.13.0 
A       var/spack/repos/builtin/packages/cgns/CGNS-sandia.patch
M       var/spack/repos/builtin/packages/cgns/package.py
M       var/spack/repos/builtin/packages/llvm/package.py
```

Therefore, the builds of CMake and GCC are exactly as they are with Spack 0.13.0.

I have reported this regression in CMake 3.15.4 in:

* https://gitlab.kitware.com/cmake/cmake/issues/19917

Closing this issue as invalid.

Sorry for jumping to the conclusion that this was a problem with how Spack builds GCC.  (I had initially forgotten that I had also upgraded CMake when I was working on upgrading Spack to 0.13.0 or I would have not posted this issue in the first place.)

**Comment by bradking** [comment]
GCC 7.2 **defaults to C++14 mode** and does not need any `-std=` flag for it.  Using CMake 3.15.x it is not expected that `cxx_std_14` will cause an explicit `-std=gnu++14` flag to be added to the command line because the compiler already operates in that mode.
