### ISSUE TITLE
spack extensions behavior when no extendable package is specified

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#1356]
If you run `spack extensions` with no extendable package, it prints an error message telling you that a package spec is required. It would be nice if Spack also printed a list of installed extendable packages to choose from.

**Comment by alalazo** [comment]
I am having a look at this command, which I never used. In some sense, it seems quite similar to `spack providers`. Would it make sense to show by default all the possible extensions, and have a flag to restrict to installed packages?

**Comment by adamjstewart** [comment]
That would make sense. I also have a similar issue open for `spack providers`.
