### ISSUE TITLE
Default the microarchitecture to the most generic one

### ISSUE THREAD

**Issue by jounathaen** [spack/spack#13678]
We have a heterogeneous cluster with Intel and AMD machines. spack detects the architecture (`linux-centos7-zen` and `linux-centos7-skylake_avx512`) and automatically compiles the packages with the corresponding  target. But this results in the packages not being compatible to the other architecture in the cluster. At least, the module path is not compatible. Previously, the microarchitecture was simply `linux-centos7-x86_64`.

In my oppinion, the default for target should be the smallest common denominator. So in this example `target=x86_64` instead of `zen`.
Is there a possibility to disable the automatic microarchitecture specification or set a default?

**Comment by alalazo** [comment]
You can configure your preferences for targets (and all the other options) in `packages.yaml`. In your case:
```yaml
packages:
  all:
    target: ['x86_64']
```
should do the trick. The [docs are here](https://spack.readthedocs.io/en/latest/build_settings.html#concretization-preferences) for later reference. Let me know if this answers your question.

**Comment by jounathaen** [comment]
Thanks for the fast response, this does the trick! :+1: :tada: 
(my opinion about defaulting this persists, but I'm happy now :wink: )

**Comment by alalazo** [comment]
> (my opinion about defaulting this persists, but I'm happy now)

The default has been chosen so that Spack optimizes for the host architecture (or for a best match if an old compiler is used). Closing this as it seems there's no further issue, but feel free to reopen if you disagree.
