### ISSUE TITLE
Patch naming conflicts

### ISSUE THREAD

**Issue by Paul-Ferrell** [spack/spack#13788]
When a package defines a set of patches, if the name of the patch file (the last element of the URL) is the same across multiple patches they will clobber each other when fetched. 

I'm a bit surprised this hasn't been found before, as Spack downloads all patches if you mirror even a single version. 

### Steps to reproduce the issue

```console
# Check the mirror directory, and find only one copy of all_patches, when there should be 7. 
$ spack mirror -d <my_mirror> mpfr

### Errors
This causes spack to throw 'invalid hash' errors when trying to use these patches, as the patch downloaded first is the one available (rather than the version you happen to be trying to build).
```

**Comment by scheibelp** [comment]
This is fixed by https://github.com/spack/spack/pull/13789 (which has been merged) - thanks for reporting the bug as well as writing the fix!
