### ISSUE TITLE
Installing package (ack) modifies files in _source-cache

### ISSUE THREAD

**Issue by obreitwi** [spack/spack#13824]
On the latest commit (9a6a19d464f31d301fb333c5110042f9ead5d501), installing `ack` modifies its install file in the `_source-cache`.

## Steps to reproduce:

In a clean git repository:
```console
$ spack fetch -D ack
[...]

$ head -n 1 var/spack/cache/_source-cache/archive/fd/fd0617585b88517a3d41d3d206c1dc38058c57b90dfd88c278049a41aeb5be38
#!/usr/bin/env perl

$ spack install ack
[...]

$ head -n 1 var/spack/cache/_source-cache/archive/fd/fd0617585b88517a3d41d3d206c1dc38058c57b90dfd88c278049a41aeb5be38
#!/path/to/local/repo/of/spack/opt/spack/linux-archrolling-skylake/gcc-9.2.0/perl-5.30.0-glhysleiayklpn7q76zpgc3grihti4j6/bin/perl
```

I do not know if there are other packages where this is an issue. We use a static download cache for fresh spack installations and `ack` was the first package to suddenly fail  to install (after moving from [this commit](https://github.com/electronicvisions/spack/tree/sandbox/breitwieser/upstream_merge_base_7) to [that](https://github.com/electronicvisions/spack/tree/sandbox/breitwieser/upstream_merge_base_8)). I verified that the issue persists in `develop` until [now](https://github.com/spack/spack/commit/9a6a19d464f31d301fb333c5110042f9ead5d501).

I suspect that is related to the reorganization of the download cache in 4af448724f4f933b5306c4cdd2f7522d64dc8719.

**Comment by adamjstewart** [comment]
I'm not sure I understand. Since `perl` is currently a build/link dependency (it should actually be a build/run dependency), Spack will force you to reinstall `ack` whenever `perl` is reinstalled, correct? So it should be fine to hardcode the installation directory of `perl`, and is actually necessary if the system perl is inadequate.

**Comment by obreitwi** [comment]
> Spack will force you to reinstall `ack` whenever `perl` is reinstalled, correct? So it should be fine to hardcode the installation directory of `perl`, and is actually necessary if the system perl is inadequate.

Yes, hardcoding the path to the perl binary in the ack install directory (under `opt/spack/…`) is totally fine and expected.

The error here is that the perl path gets hardcoded into the file residing in the download cache (under `var/cache/…`) because the script in question gets modified before it is installed (i.e. copied) to the install directory. This causes a possible next install (with another perl version B) to fail because the original shebang line (`#!/usr/bin/perl`) was already replaced with the path to version A.

The download cache should always contain the "raw" files as if they had just been downloaded.

As the `ack`-package is rather old and we have not experienced the issue until [recently](https://github.com/spack/spack/issues/13824#issue-526751289), it might be caused by a recent change with how source files are treated in the "staging" area during installation and the source cache is organised. Unfortunately, I have not dug deeper yet.

In my opinion it should not be possible to modify the source files in any spack-provided way (e.g., `filter_file` as was the case here).
