### ISSUE TITLE
cuda: how to add non x86_64 versions without breaking the whole world

### ISSUE THREAD

**Issue by nazavode** [spack/spack#13827]
While trying to install `cuda@10.2.89` on `ppc64le` (not yet in spack, installer for the current `10.1` [is broken](https://devtalk.nvidia.com/default/topic/1063995/cuda-setup-and-installation/cuda-10-1-243-10-1-update-2-ppc64le-run-file-installation-issue/)), I stumbled upon the same issue we faced when dealing with another binary package in #11198: the current `cuda` package is implicitly `linux-x86_64` only, and trying to install it on other OS/arch ends up in really obscure errors. While waiting for #11206 to be worked on, I'm here to ask what would be the most acceptable way to add `cuda` installers for `ppc64le` given the tools spack currently provides.

Adopting the same pattern we used in #11198 would end up in something like this:

```python
version('10.2.89-ppc64le',
        sha256='5227774fcb8b10bd2d8714f0a716a75d7a2df240a9f2a49beb76710b1c0fc619',
        expand=False,
        url='http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux_ppc64le.run')
```

What do you think about a provisional solution like this? Do you folks foresee some possible issue that would break everyone's `cuda` stuff (e.g.: as there is no way to constrain `x86_64` versions to `x86_64` platforms only, the reverse is also true)?

**Comment by adamjstewart** [comment]
I would be fine with a change like this. See the `cudnn` package for another example where we do this. This is a perfectly fine workaround until we get better support for `when` parameters in the `version` directive. We should do the same thing for `jdk` so we can finally install Java on macOS.

**Comment by mwkrentel** [comment]
Are the version numbers the same across platforms?  That is, is there
a 10.2.89 for x86_64 and 10.2.89 for ppc64le, etc?

Look at what I did for the hpcviewer package.  There, we have binary
files for x86_64, ppc64 and ppc64le.

One thing is: the `version()`, `variant()`, etc commands are all
executable.  So, you can use the python `platform.machine()` command
to decide what `version()` commands you want to run.

The point is that pure python code is outside of and before the spack
concretization, so it's legal to do this.

I would prefer something like that and not have the platform mixed in
with the name.

Btw, if the URLs have enough of a pattern, you can use
`url_for_version()` to compute them, which may be easier that writing
out the full URL every time.

**Comment by nazavode** [comment]
Thanks for the hints folks. @mwkrentel while looking at your `hpcviewer` TIL that:

> *Class definitions are executable statements.* 
> From [here](https://docs.python.org/3.5/reference/compound_stmts.html#class-definitions).

Never underestimate Python's (unwanted) design side effects I guess :)

@adamjstewart what do you think about something like `hpcviewer`? Do you think it could be valuable over the straightforward workaround we were considering?

**Comment by mwkrentel** [comment]
IMHO, yes, yes, yes!

AFAIK, the python `platform.machine()` is the closest workaround you
can do now until the spack `when()` is implemented.  Plus, it has the
advantage that the interface (version names) won't change when a
better solution comes along.

If you put `ppc64le` in the version name, then you force packages that
depend on cuda to do awkward things like:

```
depends_on('cuda@10.2.89' + platform.machine())
```

**Comment by adamjstewart** [comment]
Yes, the `hpcviewer` example looks great! Feel free to update other packages like `cudnn` to use this syntax. There are some cases where we would need more detail than is available in `platform.machine`, but this is fine for these simple packages.

**Comment by alalazo** [comment]
@mwkrentel @adamjstewart In general, if you use `platform` you can't install for other targets than host - so I wouldn't consider it a good practice. If you are on an `x86_64` machine:
```console
spack install target=power8 <spec>%<cross-compiler>
```
will still install software for `x86_64` despite the request for `power8`. This will prevent the use of the recipe where e.g. the front-end has a different architecture than the back-end. Or am I missing some trivial workaround?

**Comment by mwkrentel** [comment]
> In general, if you use platform you can't install for other targets
> than host - so I wouldn't consider it a good practice.

@alalazo Ok, fair enough.  The `platform.machine` solution won't work
for a cross compile.

So, what does work?  Fundamentally, you need to compute the url and
sha sum from the spack `target`.  Does spack have the machinery for
this?

AFAIK, the spack `target` is determined at concretization time and the
package class with `version` has to happen before that.  It's tempting
to want to make the target a `variant`, but you run into the same
timing problem.

**Comment by alalazo** [comment]
> So, what does work? Fundamentally, you need to compute the url and sha sum from the spack target. Does spack have the machinery for this?

Not right now. What could be worth trying (I'll look into that) is extending the version directive. At concretization time Spack needs to know:
1. Which target you want to compile for 
2. That a given version exists

It doesn't need to know that the version that has been selected is mapped to a `url`+`sha256` - that information is used later when Spack fetches the package.

I understand that what you propose is a work-around for the time being, what I wanted to say is that it shouldn't be advertized as an idiomatic way to do things - and probably it should have a `FIXME` or `TODO` next to it when it's used in packages to remind that further action needs to be taken at a later point.
