### ISSUE TITLE
Circular dependency in libxml2 causes recursion error when global variant set

### ISSUE THREAD

**Issue by mclarsen** [spack/spack#13846]
Reproducer:

`spack spec hwloc ^libxml2+python` or replace `hwloc` with any other package that depends on `libxml2`

```
bash-4.2$ ./bin/spack spec conduit ^libxml2+python
Input spec
--------------------------------
conduit

Concretized
--------------------------------
==> Error: maximum recursion depth exceeded while calling a Python object
```
Core issue:
 `libxml2` depends on `python` which depends on `libxml2` through `gettext`. 

@becker33

**Comment by becker33** [comment]
Edited for a simpler reproducer.
