### ISSUE TITLE
Eigen project is moving

### ISSUE THREAD

**Issue by citibeth** [spack/spack#13890]
The Eigen project is moving from Bitbucket to GitLab, and its Spack recipe will have to be updated accordingly.  See announcement below.

> Dear all,
> 
> following the decision of Bitbucket.org to delete all mercurial repositories next spring, we decided to migrate to a git repository hosted on gitlab.com. We also decided to take this opportunity to migrate our self hosted bugzilla instance to gitlab.com. Both migrations are scheduled on the 4th of December, starting at 8:00 UTC, and the new project:
> 
> https://gitlab.com/libeigen/eigen
> 
> will be made public once the migration is completed.
> 
> Details on the migration process:
> 
> - Our bugzilla (https://eigen.tuxfamily.org/bz/) will be made read only; all entries, comments and attachments will be transferred to gitlab.com while keeping the same bug IDs.
> 
> - https://bitbucket.org/eigen/eigen will be unavailable and replaced by an empty project pointing to https://gitlab.com/libeigen/eigen
> 
> - The old mercurial repository will still be readable on eigen.tuxfamily.org but with no updates.
> 
> - Existing pull-requests will be archived as static pages hosted on eigen.tuxfamily.org
> 
> - The official git mirror (https://github.com/eigenteam/eigen-git-mirror) will be kept as it is for a few months with no updates until we eventually replace it by an empty project pointing to https://gitlab.com/libeigen/eigen. (it cannot be synchronised because of hash differences)
> 
> Cheers,
> Gael
>

**Comment by a-jp** [comment]
I am a new user.  I am now encountering this issue as Spack cannot pull from bitbucket as per:

```terminal
==> No binary for eigen found: installing from source
==> Fetching https://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2

curl: (22) The requested URL returned error: 401 Unauthorized
==> Fetching from https://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 failed.
==> Error: FetchError: All fetchers failed for spack-stage-eigen-3.3.7-rnuwo2wk73rcr3eqk7howzsna35i4ech

/opt/spack_toolchain/spack/lib/spack/spack/package.py:1079, in do_fetch:
       1076                raise FetchError("Will not fetch %s" %
       1077                                 self.spec.format('{name}{@version}'), ck_msg)
       1078
  >>   1079        self.stage.create()
       1080        self.stage.fetch(mirror_only)
       1081        self._fetch_time = time.time() - start_time
       1082
```

I have downloaded the tar.bz2 from the GitHub mirror.  Can I ask, how do I issue a spack install command point to a local tar file?
Thanks,
Andy

**Comment by citibeth** [comment]
Can you update to the new URL in the `package.py` file, test that it works for you, and submit it as a PR?  That would be super!

Note the following additional news just came through on the Eigen email list:
```The critical steps of the migration are done. I've thus made public the new repo:

https://gitlab.com/libeigen/eigen

I've also re-opened the deprecated mercurial repo on bitbucket so that people can smoothly migrate their clones, links, etc.

Please report any outdated links and mercurial/bitbucket references you'll find. I'm already aware of some pages on our wiki, like:
- http://eigen.tuxfamily.org/index.php?title=Developer%27s_Corner
- http://eigen.tuxfamily.org/index.php?title=Mercurial

Any help on updating those old documentations will be greatly appreciated!
```

**Comment by a-jp** [comment]
The fact they have re-opened fixed that problem.  I can confirm it also bust CANTERA as that has Eigen as a dependancy.  I'm about 36 hours new to spack, happy to help, where is that package.py downloaded onto my machine?  Is it only downloaded once I issue `spack install eigen` or is it always there?
