### ISSUE TITLE
CUDA package details based on architecture

### ISSUE THREAD

**Issue by LudovicEnault** [spack/spack#13899]
Hi There,
The current cuda package.py is written only for x86_64 architecture. I would like to add ppc64le, however, there is currently no switch based on the architecture.
What is the best way to differentiate "version" based on the architecture ?
```
    version('10.2.89',
            '3d816c583759efa8567a92c1a2af90db',
            expand=False,
            url="http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux.run")
    version('10.2.89',
            'ecb6af432e64bc10e7a18cd6bd4be62f',
            expand=False,
            url="http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux_ppc64le.run")

```

In addition, the checksum used is sha256sum in the existing file, while the list provided by nvidia is md5sum. With md5sum, people could just check the content of package.py vs what is provided on nvidia website, that would add a security check.

Ludo

**Comment by alalazo** [comment]
Duplicate of #13827

**Comment by LudovicEnault** [comment]
Sorry, closing.
