### ISSUE TITLE
racon: wrong path generated in install phase

### ISSUE THREAD

**Issue by phxyz12** [spack/spack#13900]
Hi

I tired to install package racon but is fails in the install phase. Spack comlains about a non-existing file/folder on a path that has been generated wrong - most likely by Spack itself.

### Steps to reproduce the issue

```console
$ spack install -v racon%gcc@7.3.0 target=x86_64 ^python@3.6.5
```

### Error Message

```console
==> Executing phase: 'install'
==> [2019-11-26-16:36:13.988573] Installing spack-build/bin to /cfs/software/spack/linux-centos7-x86_64/gcc-7.3.0/racon-1.3.2-bnlynnveyuymp2pcnlfrcdnqcgrbwzuu/bin
==> Error: IOError: [Errno 2] No such file or directory: '/tmp/swadm/spack-stage/spack-stage-racon-1.3.2-bnlynnveyuymp2pcnlfrcdnqcgrbwzuu/spack-src/spack-build/bin/'

/data/swadm/spack/v0.13/spack/var/spack/repos/builtin/packages/racon/package.py:33, in install:
         32    def install(self, spec, prefix):
  >>     33        install_tree('spack-build/bin', prefix.bin)
         34        install_tree('spack-build/lib', prefix.lib)

See build log for details:
  /tmp/swadm/spack-stage/spack-stage-racon-1.3.2-bnlynnveyuymp2pcnlfrcdnqcgrbwzuu/spack-build-out.txt
Traceback (most recent call last):
  File "/data/swadm/spack/v0.13/spack/lib/spack/spack/build_environment.py", line 806, in child_process
    return_value = function()
  File "/data/swadm/spack/v0.13/spack/lib/spack/spack/package.py", line 1713, in build_process
    phase(self.spec, self.prefix)
  File "/data/swadm/spack/v0.13/spack/lib/spack/spack/package.py", line 111, in phase_wrapper
    phase(spec, prefix)
  File "/data/swadm/spack/v0.13/spack/var/spack/repos/builtin/packages/racon/package.py", line 34, in install
    install_tree('spack-build/lib', prefix.lib)
  File "/data/swadm/spack/v0.13/spack/lib/spack/llnl/util/filesystem.py", line 479, in install_tree
    copy_tree(src, dest, symlinks=symlinks, ignore=ignore, _permissions=True)
  File "/data/swadm/spack/v0.13/spack/lib/spack/llnl/util/filesystem.py", line 460, in copy_tree
    shutil.copyfile(s, d)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/swadm/spack-stage/spack-stage-racon-1.3.2-bnlynnveyuymp2pcnlfrcdnqcgrbwzuu/spack-src/spack-build/bin/'

```
As you an see, in the error line there is a constructed path including this part:

/spack-src/spack-build/

This does not exist, the two folders "spack-src" and "spack-build" coexist in the same directory, they are not nested.

### Information on your system

This includes:

1. Platform:
Linux build02.hpc.zhaw.ch 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

2. Spack version: 0.13.1

3. any relevant configuration detail --> see attachments

[spack-cc-racon-bnlynnv.out.log](https://github.com/spack/spack/files/3892675/spack-cc-racon-bnlynnv.out.log)

[spack-cc-racon-bnlynnv.in.log](https://github.com/spack/spack/files/3892676/spack-cc-racon-bnlynnv.in.log)

[config-files.tar.gz](https://github.com/spack/spack/files/3892686/config-files.tar.gz)

[spack-build-out.txt.gz](https://github.com/spack/spack/files/3892693/spack-build-out.txt.gz)

**Comment by phxyz12** [comment]
Update: Found the part that causes the problem. Might not be a bug:

The racon package.py file contains a def install(self, spec, prefix) section. In here, there are two calls to install_tree():
```
install_tree('spack-build/bin', prefix.bin)
install_tree('spack-build/lib', prefix.lib)
```
The first parameter in these calls is evaluated in copy_tree in filesystems.py. The conversion to an absolute path in there results in the variable abs_src. This variable then holds the wrong path displayed in the error message above. So the absolute path that is resolved, is wrong.

I do not understand enough about the install_tree() function. Maybe the package.py calls of install_tree() are just wrong. When I replace 'spack-build/bin' in there by '../spack-build/bin' (and same for the 2nd entry), the install of racon works fine. So I don't know if this is a bug in Spack or just an error in the package description. But I need to mention, that I successfully installed this package with the exact same package.py file a couple of months ago with an older version of Spack. Then, it worked with install_tree('spack-build/bin', prefix.bin) and 
install_tree('spack-build/lib', prefix.lib). So this indicates that something might have changed in how Spack behaves.

**Comment by tldahlgren** [comment]
I was able to reproduce this problem on an LC machine after installing gcc@7.3.0.

**Comment by tldahlgren** [comment]
FYI.  The `racon` package was modified in PR `#14529` to no longer override the `install` method.

**Comment by alalazo** [comment]
Can't reproduce anymore. @phxyz12 @tldahlgren Is this still an issue or can it be closed?
