### ISSUE TITLE
Spack-Built Python Lacks SSL Support

### ISSUE THREAD

**Issue by citibeth** [spack/spack#13902]
@adamjstewart 

The following program raises an exception when run with Spack-built Python 3.5; but not with the System Python.
```
python3 -c 'import requests; print(requests.get("https://portal.nccs.nasa.gov/datashare/").content)'
```

This seems to be related to #10335, in which it was claimed:

>  Python 3.7 requires OpenSSL 1.0.2+. At least on macOS 10.14.2, the version
>  of LibreSSL is too old to build Python's ssl module. While this PR
>  doesn't change the required version of OpenSSL, it does add unit tests to
>  ensure that spack install --test=root ***@***.***:+ssl crashes if the
>  required version of OpenSSL is not found.

However... it looks to me like Python needs OpenSSL for ALL versions, not just `@3.7:`.  Any thoughts on how to resolve this?

Here's a bit more on the issue in general:
https://joshspicer.com/python37-ssl-issue

**Comment by adamjstewart** [comment]
Spack's Python package _does_ depend on OpenSSL for all versions. Do you have OpenSSL listed in your `packages.yaml` as an external package? I don't think macOS comes with OpenSSL, only LibreSSL, which hasn't been tested with our Python package.

**Comment by adamjstewart** [comment]
Could be related to https://bugs.python.org/issue34028, but I'd need to see your build log.

**Comment by citibeth** [comment]
See attached build log and spec.yaml.  Looks like OpenSSL is being included as a dependency.  The mystery deepens... I'm building on CentOS 7.

[spec.yaml.txt](https://github.com/spack/spack/files/3893581/spec.yaml.txt)
[build.out.txt](https://github.com/spack/spack/files/3893585/build.out.txt)

**Comment by citibeth** [comment]
Yes could be.  I see lots of X509 errors in build.out.txt.

**Comment by adamjstewart** [comment]
Yeah, I don't see anything wrong with the Spack package, I think there must be a bug in CPython. I would try filing a bug report there. Are you able to reproduce the problem with Python 3.6 or 3.7?
