### ISSUE TITLE
Spack installed compiler gets found in the wrong folder

### ISSUE THREAD

**Issue by calewis** [spack/spack#13917]
I installed gcc 9.2.0 with spack and it added it as a compiler, but it found it in the wrong folder, making it unusable for subsequent builds. The compiler was installed in spack/opt/spack/linux-ubuntu16.04-broadwell/... but was found in spack/opt/spack/linux-ubuntu16.04-x86_64/...

### Steps to reproduce the issue

```console
$ spack install gcc
```

### Information on your system

Ubuntu 16.04 using the default system compiler of gcc 5.4.0, when compiling there was a warning that the built in compiler didn't support the latest arch flags, so it was using broadwell instead.  Perhaps this was a missed corner case. 

tagging @becker33

**Comment by alalazo** [comment]
Can you report how you registered the compiler? The command:
```command
$ spack install gcc
```
will just install `gcc` and will not register it as a new compiler automatically.

**Comment by calewis** [comment]
I am no longer using spack so you can close this if you want to, but from what I recall I just modified my list of compilers and went on my way. I don't know how to reproduce this issue again.
