### ISSUE TITLE
Extends Python with External Python

### ISSUE THREAD

**Issue by ax3l** [spack/spack#13955]
My colleague @ldamorim and I are currently trying to install packages that declare `extends('python')` and use an external, macOS Catalina Python 3.7.3 in `package.yaml`. 

Since this method tries to install into the python install directory, which in the case of a system-provided install does require root access and will fail. We wonder how workflows and good policies would look like for users that want to re-use their system-wide python.

Regarding the [actual intentions](https://github.com/spack/spack/issues/5559#issuecomment-333598324) of `extends('python')` one could potentially achieve the same user-level functionality (auto-load an extension when the base package is loaded) without modifying the base package python but instead by setting environment variables in user-controlled paths, similar to `pip`'s `--user` option.

Alternatively, being able to mark an external package in `packages.yaml` as "read-only" and discarding/warning on all `extends()` could be a possible hack to get going?

Any opinions or recommendations?

**Comment by LDAmorim** [comment]
Thanks for this issue @ax3l.
An option similar to pip's `--user` flag would work well I think.

I created and used a `etc/spack/packages.yaml` file with the content:
```console
packages:
    python:
        paths:
            python@3.7.3: /usr
```

**Comment by adamjstewart** [comment]
> Since this method tries to install into the python install directory

That's not exactly true. Extensions _allow_ you to symlink into the Python install directory using `spack activate`, but by default they install into their own install prefix. The issue here is that the `python` package has some extra logic to keep track of distutils vars that is run by `setup_dependent_package`. This logic tries to write a file to the Python install prefix, although it looks like it's wrapped in a try-except, so I'm not sure what's going on. Can you post the error message you get with `spack -d`?

**Comment by LDAmorim** [comment]
When running:
```console
install openpmd-api +python` ^python@3.7.3
```
with the line starting with `extends(python)` in `var/spack/repos/builtin/packages/openpmd-api/package.py` commented out and with clang set up with `~/.spack/darwin/compilers.yaml` including:
```console
      f77: .../spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/gcc-9.2.0-exw25ccpcwqlkcvuwn266kvwqzxbyelp/bin/gfortran
      fc: .../spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/gcc-9.2.0-exw25ccpcwqlkcvuwn266kvwqzxbyelp/bin/gfortran
```
led to the same error (shown below), but from the other packages.

```console
==> Installing py-setuptools
==> Searching for binary cache of py-setuptools
==> Warning: No Spack mirrors are currently configured
==> No binary for py-setuptools found: installing from source
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check clang@11.0.0-apple for further details]
==> Using cached archive: /Users/LDianaAmorim/Documents/opt/spack/var/spack/cache/_source-cache/archive/7e/7eae782ccf36b790c21bde7d86a4f303a441cd77036b25c559a602cf5186ce4d.zip
==> Staging archive: /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-py-setuptools-41.4.0-wf3sirq5x4t7tabwlhjsdpf6go4ipfuo/setuptools-41.4.0.zip
==> Created stage in /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-py-setuptools-41.4.0-wf3sirq5x4t7tabwlhjsdpf6go4ipfuo
==> No patches needed for py-setuptools
==> Building py-setuptools [PythonPackage]
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/python3' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/py-setuptools-41.4.0-wf3sirq5x4t7tabwlhjsdpf6go4ipfuo' '--single-version-externally-managed' '--root=/'

1 error found in build log:
     110    ==> [2019-12-02-12:57:56.536031] '/usr/bin/python3' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/User
            s/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/py-setuptools-41.4.0-w
            f3sirq5x4t7tabwlhjsdpf6go4ipfuo' '--single-version-externally-managed' '--root=/'
     111    running install
     112    running build
     113    running build_py
     114    running install_lib
     115    copying build/lib/easy_install.py -> /Library/Python/3.7/site-packages
  >> 116    error: could not create '/Library/Python/3.7/site-packages/easy_install.py': Permission denied
```

Installing it without `-python` allowed the successful installation of openPMD.

**Comment by adamjstewart** [comment]
I think this problem is specific to setuptools, not a Spack problem. Let's see what the developers have to say.

**Comment by LDAmorim** [comment]
Thanks @adamjstewart.
Yes, also the error I encountered in `py-mpi4py` (https://github.com/spack/spack/issues/13738) was during the installation of `py-setuptools` (I will expand the error message there to make it clearer).
So lets see what they will say about how to fix it.

**Comment by adamjstewart** [comment]
I'm going to close this since this is an issue in setuptools, not an issue in Spack. We can track this issue in https://github.com/pypa/setuptools/issues/1930.
