### ISSUE TITLE
variable length version numbers don't obey a linear order

### ISSUE THREAD

**Issue by mwkrentel** [spack/spack#13961]
This is a spinoff of #8957.  But I think this is small and separate
and a clear bug.  I'm hoping this can be prioritized and fixed before
waiting for the full solution in #8957.

TBB has multiple-length version numbers: 2018, 2018.1, 2019, 2019.1,
etc.  There are patches that apply to :2019.4, 2019.5:, etc.

I tried `spack install intel-tbb @2019` and the concretizer picks rev
exactly 2019, not 2019.8. (This much is correct.)  The problem (for
writing `package.py` files) is that 2019 satisfies both of these:

```
patch(..., when='@2019.6:')
patch(..., when='@:2019.2')
```

So, rev 2019 is both >= 2019.6 and <= 2019.2.

This makes it impossible to use version ranges for any package that
has variable-length versions. There is no valid order where this makes
sense.  I'm guessing there are probably several packages with broken
version ranges that don't know it.

IMO, this is a clear bug, seperate from how you want to interpret
`when='@2019'` (the essence of #8957).

@adamjstewart diagnosed this in #8957 as:

```
I'm starting to get a better understanding of this most recent
bug. ver('2019') is a Version object and ver('2019.1:') is a
VersionRange object. In order to compare these two types of objects,
we coerce Version('2019') into VersionRange('2019:2019'). Thus,
2019.1: overlaps with 2019:2019.
```

So, maybe this problem can be fixed by redoing the comparisson: don't
test for overlap between two VersionRange objects.  Instead, test if a
single Version is a member of a VersionRange.

Anyway, I think this is small and isolated and maybe can be fixed
without waiting for a full solution on how to interpret shortened
version names.

@scheibelp Would you like to self-assign?
@tgamblin for nagging.  :-)

**Comment by scheibelp** [comment]
It turns out this is primarily a problem for patches: their checks during concretization were not strict enough. This should be addressed by #13989

**Comment by mwkrentel** [comment]
I agree, this is fixed in #13989.
Thanks!

**Comment by mwkrentel** [comment]
@scheibelp Could you reopen this issue for me?  I can't seem to find a
link to click on for that.

I found another case where the treatment of short version numbers is
broken.  `self.spec.satisfies('@...')`

Use the latest version of intel-tbb with your patch from #13989.
Patch `package.py` for two lines.  The `tbb_cmakeConfig.patch` and
`tbb_config_generator.cmake` should actually start at 2017.7, not
2017.0.  (They don't exist before 2017.7.)

```
diff --git a/var/spack/repos/builtin/packages/intel-tbb/package.py b/var/spack/repos/builtin/packages/intel-tbb/package.py
index 115f980e6..04a8fcf9c 100644
--- a/var/spack/repos/builtin/packages/intel-tbb/package.py
+++ b/var/spack/repos/builtin/packages/intel-tbb/package.py
@@ -100,7 +100,7 @@ class IntelTbb(Package):
     # Can't use '@2019.5:' because 2019.5 <= 2019 <= 2019.99.  wtf!?
     patch("tbb_cmakeConfig-2019.5.patch", level=0,
           when='@2019.5,2019.6,2019.7,2019.8')
-    patch("tbb_cmakeConfig.patch", level=0, when='@2017.0:2019.4')
+    patch("tbb_cmakeConfig.patch", level=0, when='@2017.7:2019.4')
 
     # Some very old systems don't support transactional memory.
     patch("disable-tm.patch", when='~tm')
@@ -197,7 +197,7 @@ def install(self, spec, prefix):
             for f in fs:
                 install(f, prefix.lib)
 
-        if self.spec.satisfies('@2017.0:'):
+        if self.spec.satisfies('@2017.7:'):
             # Generate and install the CMake Config file.
             cmake_args = ('-DTBB_ROOT={0}'.format(prefix),
                           '-DTBB_OS={0}'.format(platform.system()),
```

Then, try installing 2017.1 and 2017.  2017.1 succeeds, as it should.
But 2017 fails because `self.spec.satisfies('@2017.7:')` succeeds and
so it tries to run `tbb_config_generator.cmake`, which doesn't exist.
Of course, 2017 should not match `@2017.7:`

```
==> Building intel-tbb [Package]
==> Executing phase: 'install'
==> Error: FileNotFoundError: [Errno 2] No such file or directory:
'/home/krentel/tbb/myspack/build-stage/spack-stage-intel-tbb-2017-3ue47i7i3gah6bzuipmwclclbay6ovl5/spack-src/cmake'

/home/krentel/tbb/myspack/var/spack/repos/builtin/packages/intel-tbb/package.py:206, in install:
        203                          '-DTBB_OS={0}'.format(platform.system()),
        204                          '-P',
        205                          'tbb_config_generator.cmake')
  >>    206            with working_dir(join_path(self.stage.source_path, 'cmake')):
        207                inspect.getmodule(self).cmake(*cmake_args)

See build log for details:
  /home/krentel/tbb/myspack/build-stage/spack-stage-intel-tbb-2017-3ue47i7i3gah6bzuipmwclclbay6ovl5/spack-build-out.txt
```

**Comment by scheibelp** [comment]
If you replace 

```
if self.spec.satisfies('@2017.7:'):
```

with

```
if self.spec.satisfies('@2017.7:', strict=True):
```

does that resolve https://github.com/spack/spack/issues/13961#issuecomment-562672413?

**Comment by mwkrentel** [comment]
Yes, with `strict=True` the test now evaluates the way I expect it
should, that is, 2017 does NOT satisfy `@2017.7:`

Is this something that you can fix globally, or do I need to use the
workaround everywhere we have shortened names?

At least I can get back to fixing intel-tbb.  There are several old
revs that don't build cleanly for reasons related to but not exactly
this issue.

Thanks!

**Comment by scheibelp** [comment]
> Is this something that you can fix globally, or do I need to use the workaround everywhere we have shortened names?

It's possible we could provide a module function `satisfies` to the Package which is always strict, since I think that's what package writers generally intend. I'd have to review use of that function to make sure though. This would still require editing individual packages: `Spec.satisfies` will not likely change its API since for the concretizer at least there are uses for both `strict=False` and `strict=True`.

Overall I'm inclined to treat this as a documentation issue: we should clarify what the user needs to call in their package file (https://spack.readthedocs.io/en/latest/packaging_guide.html). If you agree, I think a new, more-targeted issue should be opened and this one closed (which I can do).

**Comment by mwkrentel** [comment]
> Overall I'm inclined to treat this as a documentation issue: we
> should clarify what the user needs to call in their package file

Yeah, I'm ok with that.  You can close this and open a docs issue.

As described in #8957, the whole issue of matching version ranges is
complicated.  This is not really covered in read-the-docs, so if you
want to write something, I'd suggest creating a whole subsection on
version matching that covers patch(), depends_on(), when, satisfies,
etc.

If you do that, ping me.  I'll want to make sure that all the cases I
bumped into are covered.

There's one corner case left (involving versions `x` and `x.0`) for
which there is no good solution.  Other than that, I think I have
sufficient tools to describe version ranges.

Btw, I grep'd through the package files and found only two other
packages that use `strict=True`: openmpi and python.
