### ISSUE TITLE
cuda: g++ finds C++ std headers shipped by cuda sdk instead of its own libstdc++

### ISSUE THREAD

**Issue by nazavode** [spack/spack#13969]
While trying to build *standard C++ sources (no device code)* with Spack's own `g++` wrapper from within a package's `build-env` that depends on `cuda`, C++ standard headers (e.g.: `vector`) vendored by the `cuda` SDK are found by `g++` before its own `libstdc++`, breaking any trivial compilation that involves C++ standard headers. 

### Steps to reproduce the issue

Any package depending on `cuda` fits the purpose, I've been able to reproduce the issue with a bogus `package.py` like this:

```python
from spack import *

class Nvtest(Package):
    version('0')
    depends_on('cuda')
```

The `test.cpp` source I'm trying to compile uses just one standard header and is as simple as possible:

```cpp
#include <vector>

int main() {
    std::vector<int> v;
}
```

Actual steps:

```console
$ spack install gcc@8.3.0
$ spack compiler add $(spack location -i gcc@8.3.0)
$ spack install cuda%gcc@8.3.0
$ spack build-env nvtest%gcc@8.3.0 -- g++ test.cpp
In file included from /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4e
o6j6y/include/cuda/std/detail/libcxx/include/stdlib.h:93,
                 from /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4e
o6j6y/include/cuda/std/detail/libcxx/include/cstdlib:86,
                 from /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4e
o6j6y/include/cuda/std/detail/libcxx/include/exception:81,
                 from /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4e
o6j6y/include/cuda/std/detail/libcxx/include/typeinfo:60,
                 from /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4e
o6j6y/include/cuda/std/detail/libcxx/include/memory:653,
                 from /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4e
o6j6y/include/cuda/std/detail/libcxx/include/algorithm:643,
                 from /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4e
o6j6y/include/cuda/std/detail/libcxx/include/__bit_reference:15,
                 from /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4e
o6j6y/include/cuda/std/detail/libcxx/include/vector:274,
                 from main.cpp:1:
/spack/opt/spack/linux-centos7-power8le/gcc-4.8.5/gcc-8.3.0-kvs4zwy3ojuvmc43h4yf364ie2zy5gtk/include/c++/8.3.0/s
tdlib.h:38:12: error: 'std::abort' has not been declared
 using std::abort;
# lots of similar errors omitted
```

The same behaviour is observed for both `gcc@9.2.0` (**not supported** by `cuda@10.2.89`) and system-shipped `gcc@4.8.5` (**supported** by `cuda@10.2.89`).

I think that the issue stems from this:

```console
$ spack build-env nvtest%gcc@8.3.0 | grep SPACK_INCLUDE_DIRS
SPACK_INCLUDE_DIRS=/spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4eo6j6y/include:/spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4eo6j6y/include/cuda/std/detail/libcxx/include
```

The frontend confirms the inclusion search order:

```console
$ spack build-env nvtest%gcc@8.3.0 -- g++ -E -v -
Reading specs from /spack/opt/spack/linux-centos7-power8le/gcc-4.8.5/gcc-8.3.0-kvs4zwy3ojuvmc43h4yf364ie2zy5gtk/lib/gcc/powerpc64le-unknown-linux-gnu/8.3.0/specs
#include "..." search starts here:
#include <...> search starts here:
 /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4eo6j6y/include
 /spack/opt/spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4eo6j6y/include/cuda/std/detail/libcxx/include
 /spack/opt/spack/linux-centos7-power8le/gcc-4.8.5/gcc-8.3.0-kvs4zwy3ojuvmc43h4yf364ie2zy5gtk/lib/gcc/powerpc64le-unknown-linux-gnu/8.3.0/include
 /usr/local/include
 /spack/opt/spack/linux-centos7-power8le/gcc-4.8.5/gcc-8.3.0-kvs4zwy3ojuvmc43h4yf364ie2zy5gtk/include
 /spack/opt/spack/linux-centos7-power8le/gcc-4.8.5/gcc-8.3.0-kvs4zwy3ojuvmc43h4yf364ie2zy5gtk/lib/gcc/powerpc64le-unknown-linux-gnu/8.3.0/include-fixed
 /usr/include
End of search list.
```

While `<cuda>/include` provides SDK's own headers, `<cuda>/include/cuda/std/detail/libcxx/include` pulls in standard headers provided by a vendored implementation of the C++ standard library. The fact that a path component is called `/detail/` makes me think that it should be treated as an implementation detail (as is usually done in C++ code bases) and not explicitly injected in the inclusion search space.

**Comment by nazavode** [comment]
In the meantime, `git bisect` pointed me to 9c10b80591fec2cf391c97f8f53040c3429dbdec (merged in #13819) that looks like the culprit.

**Comment by ax3l** [comment]
Lol, I'll have to write invoices to Nvidia if I become the Spack CUDA guy ;)

Joking aside, thank you for reporting. CUDA 10.2 introduced libcu++ which tries to provide more and more stdlib functionality for the device over the next releases.

As you already found correctly, the implementation details of `include/cuda/std/detail/libcxx/include` should definitely *not* be part of the public include path. Only `<cuda>/include/` should be there.

**Comment by nazavode** [comment]
@ax3l thanks for looking into this. I tried to check what [this call](https://github.com/spack/spack/blob/ba87a7f53a4bc57446295833cb0f71e978ccb9fc/var/spack/repos/builtin/packages/cuda/package.py#L108-L109) scrapes out of `cuda` prefix and it looks like it is interested only in libraries:

```python
def libs(self):
        libs = find_libraries('libcuda', root=self.prefix, shared=True,
                              recursive=True)
        # libs contains:
        # /spack/linux-centos7-power8le/gcc-8.3.0/cuda-10.2.89-zamew7asat3psayj22opj5xnm4eo6j6y/targets/ppc64le-linux/lib/stubs/libcuda.so
```

It looks like there is some other component that is doing the same scraping but for headers...

**Comment by ax3l** [comment]
Ok, let me quick-fix this by keeping 10.1 the default version.

**Comment by ax3l** [comment]
Hm, for some reason the `pkg.spec["cuda@10.2.89%gcc@8.3.0 arch=linux-ubuntu18.04-skylake"].headers.directories` in `src/spack/lib/spack/spack/build_environment.py` during `set_build_environment_variables` includes these includes...

**Comment by nazavode** [comment]
> I think this behavior in Spack's `build_environment.py`/`spec.py` is generally dangerous. (C/C++ facade headers et al. and detail includes are very common.)

This is scary. This means that any random `config.h` or similar stuff arbitrarily deep in *private* include directories is going to fight for the same inclusion directive (unless the inclusions are prefixed with some path component) :cry: 

@ax3l thanks for thinking about viable fixes, in my (poor) understanding of Spack internals the current situation is a recipe for breaking random builds.

> As another quick-fix/work-around we could adjust the regex include_regex = re.compile(r'(.*)(\binclude\b)(.*)') in lib/spack/llnl/util/filesystem.py class HeaderList to only math the first occuring include/ in a path.

This sounds good to me, really conservative, it will probably break builds that right now are working fine only *by chance*.

**Comment by ax3l** [comment]
That's just the quick-fix, we consider just adding `<prefix>/include/` as a breaking change and letting all packages that use non-unix default paths add those manually via the package's `headers` property.
