### ISSUE TITLE
Inconsistency in environment defaults creates package conflicts in view

### ISSUE THREAD

**Issue by sethrj** [spack/spack#13963]
By default, environments are created with `view: true`, generating a tree with all the combined packages. However, the default is *also* to concretize packages separately, potentially leading to multiple versions of the same package. Consequently, the default options will easily generate errors with very simple environments, depending on package defaults.

I believe the default should be to concretize requirements together; or failing that to *not* generate a view.

### Steps to reproduce the issue

Take the example of installing HDF5, which has a default of `~fortran`, and Silo, which by default requires HDF5.

```console
$ spack env create test
$ spack env activate test
$ spack add hdf5+fortran+hl~mpi
$ spack add silo~mpi
$ spack concretize -f
$ spack install
```

### Error Message

```console
==> Updating view at /rnsdhpc/code/spack/var/spack/environments/test/.spack-env/view
==> Error: [/rnsdhpc/code/spack/var/spack/environments/test/.spack-env/view] Package conflict detected:
   (Linked) hdf5@1.10.5%clang@11.0.0-apple~cxx~debug+fortran+hl~mpi+pic+shared~szip~threadsafe arch=darwin-mojave-x86_64/zrrs2ar
(Specified) hdf5@1.10.5%clang@11.0.0-apple~cxx~debug~fortran~hl~mpi+pic+shared~szip~threadsafe arch=darwin-mojave-x86_64/q2msaaj
==> Installing environment test
==> hdf5 is already installed in /rnsdhpc/code/spack/opt/spack2/clang/hdf5/zrrs2ar
==> silo is already installed in /rnsdhpc/code/spack/opt/spack2/clang/silo/voajwje
==> Updating view at /rnsdhpc/code/spack/var/spack/environments/test/.spack-env/view
==> Error: [/rnsdhpc/code/spack/var/spack/environments/test/.spack-env/view] Package conflict detected:
   (Linked) hdf5@1.10.5%clang@11.0.0-apple~cxx~debug+fortran+hl~mpi+pic+shared~szip~threadsafe arch=darwin-mojave-x86_64/zrrs2ar
(Specified) hdf5@1.10.5%clang@11.0.0-apple~cxx~debug~fortran~hl~mpi+pic+shared~szip~threadsafe arch=darwin-mojave-x86_64/q2msaaj
```

### Information on your system

I'm running on a mac, and for the purposes of this test I removed my `packages.yaml` file.

**Comment by david8dixon** [comment]
I am experimenting with environments as well - hitting the same issue... Any resolution on this? What about a temporary workaround?

**Comment by dzhang-b** [comment]
Has the same problems using spack environment.

spack.yaml
```
 spack:
   specs:
     - boost@1.67.0
     - thrift@0.11.0
   view: true
``` 

spack install -> Error out on conflict dependencies.

Current workaround: set view to false;

**Comment by alalazo** [comment]
Default options changed a while ago. Now a default environment looks like:
```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: []
  view: true
  concretizer:
    unify: true
```
