### ISSUE TITLE
No way to build ParaView with python/3.4.x?

### ISSUE THREAD

**Issue by EthanS94** [spack/spack#13985]
@chuckatkins @danlipsa 

### Steps to reproduce the issue

```console
$ spack install spack install paraview@5.7.0%gcc@7.4.0 build_type=Release +mpi~opengl2+osmesa +plugins+python3 ^cmake@3.15.3 ^openssl@1.0.2o ^libbsd@0.9.1 ^hdf5@1.10.2 ^m4@1.4.18 ^netcdf-c@4.7.1 ^python@3.4 
==> Error: An unsatisfiable version constraint has been detected for spec:

    python@3.4
        ^gettext
        ^pkgconfig@0.9.0:


while trying to concretize the partial spec:

    py-matplotlib@3:


py-matplotlib requires python version 3.5:, but spec asked for 3.4
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux sn364.localdomain 3.10.0-1062.1.1.1chaos.ch6.x86_64 #1 SMP Wed Sep 4 16:09:20 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Red Hat Enterprise Linux Server release 7.7 (Maipo)
``` 

Can the package.py file be changed to allow building paraview with python 3.4? I believe the latest matplotlib version supported with python 3.4 is 2.2.4...

**Comment by chuckatkins** [comment]
You can use an older version of matplotlib, `< 3`.  Looking at the package file for py-matplotlib it looks like `< 3` can use python 3.4.  I think the version constraint on `py-matplotlib>=3` was put in to make the spack concretizer happy, but it's really an artificial dependency as paraview can use 2 or 3.  I'm walking through the dependency chain now though and it goes pretty deep with version conflicts.  At the moment if I drop the version constraint on py-matplotlib then I can get pretty far with: `paraview@5.7 +mpi+osmesa+plugins+python3 ^python@3.4 ^py-numpy@1.15.4 ^py-matplotlib@2.2.3`.  Still working through some of the sub-dependecies though.

**Comment by chuckatkins** [comment]
Okay, so with the addition of #13999 and #14000 you should be able to use the following spec:
```
paraview@5.7.0 build_type=Release +mpi+osmesa+plugins+python3 ^cmake@3.15.3 ^openssl@1.0.2o ^libbsd@0.9.1 ^hdf5@1.10.2 ^m4@1.4.18 ^netcdf-c@4.7.1 ^python@3.4 ^py-numpy@1.15.4 ^py-matplotlib@2.2.3 ^py-pillow@5.4.1
```
The addition of `^py-numpy@1.15.4 ^py-matplotlib@2.2.3 ^py-pillow@5.4.1` is necessary to help the concretizer find the right dependency versions that are compatible with 3.4

**Comment by chuckatkins** [comment]
Note that I dropped the "build-error" label because the issue arrises in the package concretization and errors out well before anything tries to get built.

**Comment by chuckatkins** [comment]
@EthanS94 both PRs have been merged to master now.  Please update and try it out to see if you can effectively resolve the spec with python 3.4.

**Comment by EthanS94** [comment]
@chuckatkins I was able to resolve that spec. Thanks!
