### ISSUE TITLE
Installation issue: gromacs

### ISSUE THREAD

**Issue by awacha** [spack/spack#14020]
### Steps to reproduce the issue

```console
$ spack install gromacs@2018.8
... 
==> Error: ChecksumError: sha256 checksum failed for /tmp/wachaandras/spack-stage/spack-stage-gromacs-2018.8-wo2lu6rdjzxevcype5dfruyeafvwbcsk/gromacs-2018.8.tar.gz
    Expected 3776923415df4bc78869d7f387c834141fdcda930b2e75be979dc59ecfa6ebec but got 776923415df4bc78869d7f387c834141fdcda930b2e75be979dc59ecfa6ebecf

/opt/spack/lib/spack/spack/package.py:1083, in do_fetch:
       1080        self.stage.fetch(mirror_only)
       1081        self._fetch_time = time.time() - start_time
       1082
  >>   1083        if checksum and self.version in self.versions:
       1084            self.stage.check()
       1085
       1086        self.stage.cache_local()

```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux guinier.guinier 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux
$ lsb_release -d
Description:	Arch Linux
``` 

### Additional information

It seems that the sha256sum in the package.py file is incorrect:
In package.py:
'3776923415df4bc78869d7f387c834141fdcda930b2e75be979dc59ecfa6ebec'

Manually computed from the tarball downloaded directly from gromacs.org:
'776923415df4bc78869d7f387c834141fdcda930b2e75be979dc59ecfa6ebecf'

Fixing the package.py file should solve the problem.

**Comment by adamjstewart** [comment]
I'm seeing the same error. Can you contact the gromacs developers and ask them about the checksum change, just to make sure they weren't hacked? Don't want another repeat of: https://github.com/Homebrew/homebrew-cask/issues/33536

**Comment by awacha** [comment]
For me it seems that this is only a copy-paste error: if you remove the first character ('3') of the checksum in package.py and add 'f' at the end, you get the upstream one. I don't know how difficult would it be for an attacker to make such a convincing fake. I'll contact the developers nevertheless.

**Comment by junghans** [comment]
I have no idea, but:
```
$ spack checksum gromacs 2018.8
==> Found 1 version of gromacs:
  
  2018.8  http://ftp.gromacs.org/gromacs/gromacs-2018.8.tar.gz

==> How many would you like to checksum? (default is 1, q to abort) 
==> Downloading...
==> Fetching http://ftp.gromacs.org/gromacs/gromacs-2018.8.tar.gz
################################################################################################################################ 100.0%
==> Checksummed 1 version of gromacs:

    version('2018.8', sha256='776923415df4bc78869d7f387c834141fdcda930b2e75be979dc59ecfa6ebecf')

```

So it seems the there are a typo in the checksum.

The md5sum is 12fe6c41c1ed76ed8227c6d37c465ff4 which agrees with http://manual.gromacs.org/documentation/2018.8/download.html

**Comment by hseara** [comment]
Sorry for the typo.

**Comment by awacha** [comment]
Dear @hseara, @marvinbernhardt, @junghans and @adamjstewart,

Thank you all for your comments and the fix.

**Comment by acmnpv** [comment]
> I have no idea, but:
> 
> ```
> $ spack checksum gromacs 2018.8
> ==> Found 1 version of gromacs:
>   
>   2018.8  http://ftp.gromacs.org/gromacs/gromacs-2018.8.tar.gz
> 
> ==> How many would you like to checksum? (default is 1, q to abort) 
> ==> Downloading...
> ==> Fetching http://ftp.gromacs.org/gromacs/gromacs-2018.8.tar.gz
> ################################################################################################################################ 100.0%
> ==> Checksummed 1 version of gromacs:
> 
>     version('2018.8', sha256='776923415df4bc78869d7f387c834141fdcda930b2e75be979dc59ecfa6ebecf')
> ```
> 
> So it seems the there are a typo in the checksum.
> 
> The md5sum is 12fe6c41c1ed76ed8227c6d37c465ff4 which agrees with http://manual.gromacs.org/documentation/2018.8/download.html

@junghans thanks for checking, I also just triple checked this.
From 2020 there is going to be an additional check that the source files have not been modified
