### ISSUE TITLE
Bazel Java requirement

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#14058]
I was trying to build py-tensorflow and it was failing along the way when trying to build bazel. I was getting a java out of memory error:

The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space
	at com.sun.tools.javac.code.Scope$ImportScope.makeEntry(Scope.java:530)
	at com.sun.tools.javac.code.Scope.enter(Scope.java:220)
	at com.sun.tools.javac.comp.MemberEnter$4.importFrom(MemberEnter.java:326)
	at com.sun.tools.javac.comp.MemberEnter$4.run(MemberEnter.java:334)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:143)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.main.JavaCompiler.enterTreesIfNeeded(JavaCompiler.java:965)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1242)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)

This happened when trying to build against openjdk@1.8.0. I did some tinkering and found that if I removed the restriction of depending on java@8, that I was able to get bazel@0.26.1 to build with openjdk@11.0.2. I can submit a PR to such effect, but I would rather consult with folks to see if there really is a java@8 dependency or if that dependency is isolated to particular versions of bazel.

**Comment by adamjstewart** [comment]
The reason for the `java@8` dependency is https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-unix-prereq:

> JDK 8. You must install version 8 of the JDK. Versions other than 8 are not supported.

I agree, I've managed to install Bazel with newer versions of JDK as well. I would open an issue with the Bazel developers to better understand the OOM error, @healther encountered the exact same problem: https://github.com/bazelbuild/bazel/issues/new

Personally, I've had better luck with `jdk` than `openjdk` if that helps.

**Comment by s-sajid-ali** [comment]
The fetchers for jdk are broken on develop. 

```
[sajid@xrmlite spack]$ git log -1
commit 3cd6ca02d2d58c42d6864b25ed5e4479557eaa8c (HEAD -> develop, upstream/develop, origin/develop, origin/HEAD)
Author: iarspider <iarspider@gmail.com>
Date:   Wed Dec 11 00:34:50 2019 +0100

    Fix json-c package (#14087)

    * Fix json-c package

    * Fix PEP-8

    * Update package.py

    * Update package.py
[sajid@xrmlite spack]$ spack install jdk@1.8.0_231-b11%gcc@9.2.0
==> Installing jdk
==> Searching for binary cache of jdk
==> No binary for jdk found: installing from source
==> Fetching https://download.oracle.com/otn/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz
################################################################################################################################################################ 100.0%################################################################################################################################################################ 100.0%==> Warning: The contents of the archive look like HTML.  Either the URL you are trying to use does not exist or you have an internet gateway issue.  You can remove the bad archive using 'spack clean <package>', then try again using the correct URL.
==> Error: ChecksumError: sha256 checksum failed for /tmp/sajid/spack-stage/spack-stage-jdk-1.8.0_231-b11-3ymu66b4agiqqvwqmvt6cc5sffzu6d2t/jdk-8u231-linux-x64.tar.gz
    Expected a011584a2c9378bf70c6903ef5fbf101b30b08937441dc2ec67932fb3620b2cf but got febd55e91cc277096f0c9670bba0085503b982c59df48bd5aa673be2bad545cc

/home/sajid/packages/spack/lib/spack/spack/package.py:1083, in do_fetch:
       1080        self.stage.fetch(mirror_only)
       1081        self._fetch_time = time.time() - start_time
       1082
  >>   1083        if checksum and self.version in self.versions:
       1084            self.stage.check()
       1085
       1086        self.stage.cache_local()
```

I've gotten around with using a hash I found somewhere on the internet and using the URL specified in [this post](https://stackoverflow.com/questions/56650812/how-to-install-oraclejdk8-through-docker-file-in-ubuntu) instead of what spack uses.

**Comment by healther** [comment]
If unrestricting the java dependency works for both oracle and openjdk, I'd propose we do that. Reality should beat documentation if both are in disagreement. I didn't find the time to dig deeper but when I'm getting back to it I'll try that one out.

@adamjstewart did you test with oracle's JDK? I'm not sure if I even have access to it

**Comment by adamjstewart** [comment]
I only got Oracle JDK working. JDK is no longer available for download with the hacks we have in the JDK package, I had to create an account, log in, manually download the tarball, and place it in my mirror.

**Comment by svenevs** [comment]
> Reality should beat documentation if both are in disagreement.

:slightly_smiling_face:

AFAICT the docs are out of date.  Unclear, it seems they support Java 10 and 11 [as of `bazel@0.28.0`](https://github.com/bazelbuild/bazel/issues/6245#issuecomment-501649882)?  I don't understand enough about bazel or java to really know what the different components they were asking for were.  

But is there a way to make this `depends_on('java', type=('build', 'run'))`?  I don't get the version number ranges for `spack providers java`, but right now `bazel` has a hard dependency on `jdk`.  It seems like the default provider for `java` is `openjdk` (???), so for things like `py-tensorflow` the `jdk` thing is an unnecessary road block.  I was able to get `0.26.1` to build for tensorflow using `java` rather than `jdk`, it ended up using `openjdk` 11.

So I guess if there's no way to get valid virtual dependency version numbers for `java` in order, I'd rather just make `depends_on('java', ...)` be the thing in bazel.  It seems to be successful with later `openjdk` for people (myself included).
