### ISSUE TITLE
--yes-to-all automatically adds the --no-checksum flag OR is documented to not do so

### ISSUE THREAD

**Issue by nicholas-sly** [spack/spack#14097]
### Rationale

Running an installation with the `--yes-to-all` flag enabled will still result in yes/no questions requiring user input if Spack has to fetch a package that doesn't have a checksum.  

### Description

Option 1: Implicitly enable the `--no-checksum` flag when the `--yes-to-all` flag has been set and specify that this will happen in the `spack install --help` description.

Option 2: Explicitly state in the `spack install --help` description for the `--yes-to-all` flag that this does NOT set the `--no-checksum` flag and that user input will still be required if a package without a checksum is included in the spec.

**Comment by tgamblin** [comment]
Closed by #18367.
