### ISSUE TITLE
Installation issue: cairo

### ISSUE THREAD

**Issue by samcom12** [spack/spack#14112]
$ spack install cairo

### Platform and user environment

$ uname -a 
Linux login06 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Error-

font-variations.c:31:10: fatal error: ft2build.h: No such file or d
            irectory
     965     #include <ft2build.h>
     966              ^~~~~~~~~~~~
     967    compilation terminated.
  >> 968    make[4]: *** [cairo_test_suite-font-variations.o] Error 1
     969    make[4]: *** Waiting for unfinished jobs....
     970    make[4]: Leaving directory `/tmp/samir/spack-stage/spack-stage-cair
            o-1.16.0-z6seiwte5e2ntboq3csrw7hnesqimsm7/spack-src/test'
  >> 971    make[3]: *** [all-recursive] Error 1
     972    make[3]: Leaving directory `/tmp/samir/spack-stage/spack-stage-cair
            o-1.16.0-z6seiwte5e2ntboq3csrw7hnesqimsm7/spack-src/test'
  >> 973    make[2]: *** [all] Error 2

**Comment by jasonfenglu** [comment]
You can try to build it with freetype.

**Comment by pat-s** [comment]
Worked for me: `spack install cairo +X +ft`
