### ISSUE TITLE
compiling pyqt5@5.13.1

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#14121]
pyqt5 is of type "SipPackage". sippackage class currently downloads sip@4.19.18 as resource, however, py-pyqt5@5.13.1 requires sip@4.19.19 and otherwise yields a build error. I am wondering how different versions of sip resource can be downloaded depending of pyqt version.

@adamjstewart

**Comment by Sinan81** [comment]
we did something similar with Qscintilla resource in  pyqt5 package, however that didn't seem to be applicable in this case.

**Comment by adamjstewart** [comment]
I don't know of any way to do this. If we update `SipPackage` to download `sip@4.19.19` will that break any other packages? If not, we'll need to remove the resource from `SipPackage` and add it to every package that extends it.

**Comment by Sinan81** [comment]
compiling pyqt5@4.13.0 with sip@4.19.19 fails. so, it seems things are breaking.

**Comment by iarspider** [comment]
There is a way to avoid creating a copy of `sip` for every package that depends on it. Just adding these two lines to both `sip/__init__.py` and `<package>/__init__.py` solves the problem:
```
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

**Comment by Sinan81** [comment]
@adamjstewart Do I understand it correctly that in order to implement the above suggestion by iarspider, py-sip should be a dependency of PyQt5, hence downloading sip package within SipPackage build system should be discontinued? (Also, do think we can apply the above trick to PyQt+Qsci case?)

@iarspider Thanks again for the above tip. If you would like to submit a PR for it, please go ahead. Or else I will take care of it.

**Comment by iarspider** [comment]
@Sinan81 We can repurpose SipPackage type to just apply this fix, but I don't know if this can be done.

**Comment by Sinan81** [comment]
@iarspider Anything under spack is editable. The file is located under `spack/lib/spack/spack/build_systems/sip.py` and can be edited via: `spack edit --build-system sip`

**Comment by Sinan81** [comment]
@iarspider please let me if my comments above doesn't make sense, and if you meant something else when you said ".. I don't know if this can be done"

**Comment by iarspider** [comment]
@Sinan81 I meant "I don't know if one can do a patch step in build system recipe, or this needs to be done inside package recipe".

**Comment by Sinan81** [comment]
you are right, patching the build system doesn't make sense.

**Comment by Sinan81** [comment]
I will be looking into resolving this issue once and for all in the following days. I think first thing I will try is to
- convert PyQt5 to a python package from SipPackage
- add py-sip depedency to PyQt5
- implement @iarspider 's suggestion to `py-sip/.../__init__.py` and `pyqt5/.../__init__.py`

@iarspider @adamjstewart Do you think this makes sense?

**Comment by iarspider** [comment]
@Sinan81 LGTM. Probably we can even drop the `SipPackage` build system?

**Comment by Sinan81** [comment]
At first glance, extend_path didn't seem to work. @iarspider I will push a branch soon, so that you can also give it a try. Basically what I did was I kept the SipPackage class (since it has a lot of useful things in it) but removed the privite sip module installation. 

Also, in order to make sure I understand extend_path thing, I will create a hello world example.

**Comment by Sinan81** [comment]
I take it back. Actually it seems to work for the most part if I create a PyQt5 folder under py-sip installation, symlink sip.so, and  put extend_path thing there as well as in pyqt5 installation. Below, note how python is **not** complaining that PyQt5.sip is not found 
```bash
sbulut@ws-067 /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-sip-4.19.18-oq24pxub6x7mward6e7c2dnq2eury74k/lib/python3.7/site-packages/PyQt5 (pyqt_try_extend_path) 
$ ll
total 8
-rw-rw-r--. 1 sbulut sbulut   75 Feb 27 15:37 __init__.py
drwxrwsr-x. 2 sbulut sbulut 4096 Feb 27 15:37 __pycache__
lrwxrwxrwx. 1 sbulut sbulut   15 Feb 27 15:36 sipconfig.py -> ../sipconfig.py
lrwxrwxrwx. 1 sbulut sbulut   18 Feb 27 15:36 sipdistutils.py -> ../sipdistutils.py
lrwxrwxrwx. 1 sbulut sbulut   10 Feb 27 15:36 sip.pyi -> ../sip.pyi
lrwxrwxrwx. 1 sbulut sbulut    9 Feb 27 15:36 sip.so -> ../sip.so
sbulut@ws-067 /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-sip-4.19.18-oq24pxub6x7mward6e7c2dnq2eury74k/lib/python3.7/site-packages/PyQt5 (pyqt_try_extend_path) 
$ more __init__.py 
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
sbulut@ws-067 /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-sip-4.19.18-oq24pxub6x7mward6e7c2dnq2eury74k/lib/python3.7/site-packages/PyQt5 (pyqt_try_extend_path) 
$ paths | grep pyqt5
/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-pyqt5-5.13.0-yzhwikovlapdedhcawkl3puq7i3bnzqt/bin
sbulut@ws-067 /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-sip-4.19.18-oq24pxub6x7mward6e7c2dnq2eury74k/lib/python3.7/site-packages/PyQt5 (pyqt_try_extend_path) 
$ cd /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-pyqt5-5.13.0-yzhwikovlapdedhcawkl3puq7i3bnzqt/lib/python3.7/site-packages/PyQt5
sbulut@ws-067 /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-pyqt5-5.13.0-yzhwikovlapdedhcawkl3puq7i3bnzqt/lib/python3.7/site-packages/PyQt5 (pyqt_try_extend_path) 
$ ls
__init__.py               _QOpenGLFunctions_2_1.so       QtDesigner.so   QtMultimedia.pyi         QtNetwork.so       QtPrintSupport.pyi  QtQuickWidgets.so    Qt.so       QtWebChannel.pyi  QtX11Extras.so
__pycache__               _QOpenGLFunctions_4_1_Core.so  QtGui.pyi       QtMultimedia.so          QtNfc.pyi          QtPrintSupport.so   QtRemoteObjects.pyi  QtSql.pyi   QtWebChannel.so   QtXmlPatterns.pyi
pylupdate_main.py         QtBluetooth.pyi                QtGui.so        QtMultimediaWidgets.pyi  QtNfc.so           QtQml.pyi           QtRemoteObjects.so   QtSql.so    QtWebSockets.pyi  QtXmlPatterns.so
pylupdate.so              QtBluetooth.so                 QtHelp.pyi      QtMultimediaWidgets.so   QtOpenGL.pyi       QtQml.so            QtSensors.pyi        QtSvg.pyi   QtWebSockets.so   QtXml.pyi
pyrcc_main.py             QtCore.pyi                     QtHelp.so       QtNetworkAuth.pyi        QtOpenGL.so        QtQuick.pyi         QtSensors.so         QtSvg.so    QtWidgets.pyi     QtXml.so
pyrcc.so                  QtCore.so                      QtLocation.pyi  QtNetworkAuth.so         QtPositioning.pyi  QtQuick.so          QtSerialPort.pyi     QtTest.pyi  QtWidgets.so      uic
_QOpenGLFunctions_2_0.so  QtDesigner.pyi                 QtLocation.so   QtNetwork.pyi            QtPositioning.so   QtQuickWidgets.pyi  QtSerialPort.so      QtTest.so   QtX11Extras.pyi
sbulut@ws-067 /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-pyqt5-5.13.0-yzhwikovlapdedhcawkl3puq7i3bnzqt/lib/python3.7/site-packages/PyQt5 (pyqt_try_extend_path) 
$ more __init__.py 
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
sbulut@ws-067 /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-pyqt5-5.13.0-yzhwikovlapdedhcawkl3puq7i3bnzqt/lib/python3.7/site-packages/PyQt5 (pyqt_try_extend_path) 
$ python
Python 3.7.6 (default, Feb 24 2020, 01:11:03) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
>>> from PyQt5 import QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: PyCapsule_GetPointer called with incorrect name
>>> 
```
but now we're getting the above ValueError, I don't think this error showed in in the previous setup.

**Comment by adamjstewart** [comment]
> Actually it seems to work for the most part if I create a PyQt5 folder under py-sip installation

We should try to avoid packages writing to other packages' installation prefixes. It makes it hard to uninstall/reinstall since not everything will be uninstalled.

**Comment by Sinan81** [comment]
> > Actually it seems to work for the most part if I create a PyQt5 folder under py-sip installation
> 
> We should try to avoid packages writing to other packages' installation prefixes. It makes it hard to uninstall/reinstall since not everything will be uninstalled.

I totally agree Adam. If this thing works, that certainly won't be the case. it is just that in py-sip site-packages dir we create an empty folder named PyQt5, and put symlinks of all the stuff under py-sip site-packages there. It will work with **every** PyQt5 installation
```
cd ..../py-sip-4.19.18-oq24pxub6x7mward6e7c2dnq2eury74k/lib/python3.7/site-package
tree
.
├── __init__.py
├── PyQt5
│   ├── __init__.py
│   ├── sipconfig.py -> ../sipconfig.py
│   ├── sipdistutils.py -> ../sipdistutils.py
│   ├── sip.pyi -> ../sip.pyi
│   └── sip.so -> ../sip.so
├── sip-4.19.18.dist-info
│   ├── INSTALLER
│   ├── METADATA
│   └── RECORD
├── sipconfig.py
├── sipdistutils.py
├── sip.pyi
└── sip.so
 ```

**Comment by Sinan81** [comment]
Here is the branch I am using to test this idea:
https://github.com/Sinan81/spack/tree/try_extend_path_as_pyqt_sip_fix
It would be great if you can give it a try. Basically what I did is to disable building private sip module in Sip build system and also set up extend_path stuff in py-sip and py-pyqt5
```diff
commit 7e30adccea393fb2a1cf971ec04650c00c3ce0be
Author: Sinan81 <sbulut@3vgeomatics.com>
Date:   Thu Feb 27 19:47:58 2020 -0800

    try extend path to solve PyQt5.sip not found issue

diff --git a/var/spack/repos/builtin/packages/py-pyqt5/package.py b/var/spack/repos/builtin/packages/py-pyqt5/package.py
index f70461a..dd1287d 100644
--- a/var/spack/repos/builtin/packages/py-pyqt5/package.py
+++ b/var/spack/repos/builtin/packages/py-pyqt5/package.py
@@ -36,6 +36,7 @@ class PyPyqt5(SIPPackage):
     depends_on('qt@5:+opengl')
     depends_on('python@2.6:', type=('build', 'run'))
     depends_on('py-enum34', type=('build', 'run'), when='^python@:3.3')
+    depends_on('py-sip', type=('build', 'run'))
 
     depends_on('qscintilla', when='+qsci')
 
@@ -100,3 +101,13 @@ def make_qsci(self):
                 makefile.filter(r'\$\(INSTALL_ROOT\)', '')
 
                 make('install')
+
+    @run_after('install')
+    def extend_path_setup(self):
+        with working_dir(site_packages_dir):
+
+            f = open('./PyQt5/__init__.py', 'a')
+            f.write('from pkgutil import extend_path\n')
+            f.write('__path__ = extend_path(__path__, __name__)\n')
+            f.close()
+
diff --git a/var/spack/repos/builtin/packages/py-sip/package.py b/var/spack/repos/builtin/packages/py-sip/package.py
index 09c6b74..311ea4e 100644
--- a/var/spack/repos/builtin/packages/py-sip/package.py
+++ b/var/spack/repos/builtin/packages/py-sip/package.py
@@ -53,3 +53,16 @@ def build(self, spec, prefix):
 
     def install(self, spec, prefix):
         make('install')
+
+    @run_after('install')
+    def extend_path_setup(self):
+        with working_dir(site_packages_dir):
+            mkdirp('PyQt5')
+            ln = which('ln')
+            ln('sip.so','./PyQt5/sip.so')
+
+            f = open('./PyQt5/__init__.py', 'w')
+            f.write('from pkgutil import extend_path\n')
+            f.write('__path__ = extend_path(__path__, __name__)\n')
+            f.close()
+
```

**Comment by Sinan81** [comment]
related to #12388

**Comment by Sinan81** [comment]
Actually, no need to create PyQt5 dir manually, we just need to set the module variant correctly:
```
...
depends_on('py-sip module=PyQt5.sip')
...
```

**Comment by iarspider** [comment]
LGTM. More or less the same as we do in SPI:
```
  CONFIGURE_COMMAND  ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/qt5.conf qt.conf
            COMMAND  ${python_fwk_command} configure.py
                                               -b <INSTALL_DIR>/bin
                                               -d <INSTALL_DIR>/lib/python${Python_config_version_twodigit}/site-packages
                                               -q ${Qt5_home}/bin/qmake
                                               -v <INSTALL_DIR>/share/sip/PyQt5
                                               --stubsdir=<INSTALL_DIR>/lib/python${Python_config_version_twodigit}/site-packages/PyQt5
                                               --designer-plugindir <INSTALL_DIR>/plugins/designer
                                               --qml-plugindir <INSTALL_DIR>/plugins/PyQt5
                                               --sip ${sip_home}/bin/sip
                                               --sip-incdir ${sip_home}/include/python${Python_config_version_twodigit}
                                               --verbose --confirm-license
  INSTALL_COMMAND ${MAKE} -j1 install
```

With `qt5.conf` (generated before building):
```
[Paths]
Prefix=${Qt5_home}
```

**Comment by Sinan81** [comment]
It seems once we do 'py-sip module=PyQt5.sip', it works!

**Comment by adamjstewart** [comment]
It's a shame we need a separate `py-sip` installation for each SIPPackage. Is it possible to build both `py-pyqt5` and `py-pyqt4` and load both packages in the environment? Or does that break Python's `PYTHONPATH` library finding if `sip` is in there twice?

**Comment by Sinan81** [comment]
I think building both should be possible. Will give it a try today

**Comment by Sinan81** [comment]
But why not treat `py-sip` like any other dependency and build twice with `module=PyQt5` and `module=PyQt5`?

**Comment by adamjstewart** [comment]
The issue is whether Python can find both if there are multiple sip directories, or if it only finds the first

**Comment by Sinan81** [comment]
Note to self: "extend_path" trick should also enable us to move building of QScintilla python bindingsstuff from py-pyqtX package to back to qscintilla package.

**Comment by Sinan81** [comment]
> It's a shame we need a separate `py-sip` installation for each SIPPackage. Is it possible to build both `py-pyqt5` and `py-pyqt4` and load both packages in the environment? Or does that break Python's `PYTHONPATH` library finding if `sip` is in there twice?

I am wondering the following answers your questions:
```
sbulut@ws-067 /mnt/local/spack (try_extend_path_as_pyqt_sip_fix) 
$ env | grep pythonpath | sed 's/:/\n/g'
PYTHONPATH=/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-sip-4.19.18-giggdgmkyncirajjn2bargptzkfsldxy/lib/python3.7/site-packages
/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-pyqt4-4.12.3-kwqkmuiax33xmqfyqwanr7t2tckzee65/lib/python3.7/site-packages
/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-sip-4.19.18-giggdgmkyncirajjn2bargptzkfsldxy/lib/python3.7/site-packages
/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-sip-4.19.18-shc42xd2jp3xnw6wanywykmgdwwsqtu7/lib/python3.7/site-packages
/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-pyqt5-5.13.0-x7ptbi3n4hwpf4t7anbzhb6fcgi37k6y/lib/python3.7/site-packages
/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/py-sip-4.19.18-shc42xd2jp3xnw6wanywykmgdwwsqtu7/lib/python3.7/site-packages
sbulut@ws-067 /mnt/local/spack (try_extend_path_as_pyqt_sip_fix) 
$ python
Python 3.7.6 (default, Mar  1 2020, 20:12:05) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sip'
>>> import PyQt5.sip
>>> import PyQt4.sip
>>> 
```
Note that above `import sip` fails as expected since we set `module=PyQtX.sip` in py-sip build (where X is 4 or 5)
