### ISSUE TITLE
debian packaging: install target

### ISSUE THREAD

**Issue by alexmyczko** [spack/spack#14130]
*Please add a concise summary of your suggestion here.*

Could spack have some form of install target, where it gets installed on the system for all users?
like `install bin/spack /usr/bin/` and so on?

*Is your feature request related to a problem? Please describe it!*

I'd like to provide spack to all multi-user machines, system-wide, preferably having
it in an official Debian package.

*Describe the solution you'd like and the alternatives you have considered.*

Having a Makefile or CMakefile or python3 setup.py to install the spack software, would
be perfect.

**Comment by adamjstewart** [comment]
Hi @alexmyczko 

Just to clarify, are you trying to install _spack_ to `/usr` or trying to get Spack to install _other packages_ to `/usr`? Spack supports both.

To install _spack_ to `/usr`, use `spack clone /usr`

To install _other packages_ to `/usr` using Spack, see #13083 or https://spack.readthedocs.io/en/latest/config_yaml.html#install-tree

You may also be interested in [Spack Chains](https://spack.readthedocs.io/en/latest/chain.html), which allow a single root installation of Spack to be used by user copies of Spack. This way, sys admins can install a base set of packages, and users can reuse them.

There has been some discussion about releasing Spack on PyPI with a `setup.py` in #1385, but I think we decided that Spack isn't stable enough yet.

**Comment by alexmyczko** [comment]
Hi @adamjstewart

I want to actually create a Debian package of the spack software, and install that.

So could I just have a spack dir, clone it to $DESTDIR/usr, and have it in a tar, unpack it to another host to / (root) and it'd be /usr/bin/spack for the binary and the rest is also somewhere. And it'd work?

**Comment by adamjstewart** [comment]
Yep, Spack is written almost entirely in Python, so relocating it is easy and doesn't break anything. The file hierarchy follows the usual UNIX standard of bin/lib/share/etc and has subdirectories for Spack so that prevent interference with other software.

**Comment by alexmyczko** [comment]
I actually wanted to use spack with spack install boost@1.54.0, however it keeps failing, after that I'd also need pcl@1.7.0 however that doesn't exist, so back to user install the classic --prefix way... I'll see if I can get a working spack debian package built though

**Comment by adamjstewart** [comment]
If you're having problems building boost, please open an issue for that with the exact error message and hopefully someone can fix it.

Adding new packages to Spack is simple and easy, and we have a ton of documentation on it if you're interested:

- [Package Creation Tutorial](https://spack-tutorial.readthedocs.io/en/latest/tutorial_packaging.html)
- [Contribution Guide](https://spack.readthedocs.io/en/latest/contribution_guide.html)
- [Packaging Guide](https://spack.readthedocs.io/en/latest/packaging_guide.html)
- [Build Systems](https://spack.readthedocs.io/en/latest/build_systems.html)

**Comment by tgamblin** [comment]
If you're looking to install Spack as a Debian package, then #11871 is likely how you would want it to work.  We have that slated for 0.14

**Comment by adamjstewart** [comment]
> after that I'd also need pcl@1.7.0 however that doesn't exist, so back to user install the classic --prefix way... 

FWIW, I wrote a simple PCL package in #20933

**Comment by alexmyczko** [comment]
https://repology.org/project/spack/versions ok if they can do it i can do it as well...

**Comment by alexmyczko** [comment]
Current state of packaging looks like this:
https://mentors.debian.net/package/spack/

Could something be done with future source tarball releases for:
`source-contains-autogenerated-gperf-data: var/spack/repos/builtin/packages/gcc/gcc-backport.patch`
`source-contains-prebuilt-binary: var/spack/repos/builtin/packages/patchelf/test/hello`

**Comment by alexmyczko** [comment]
Meanwhile I've got 0.20 as .deb http://sid.ethz.ch/debian/spack/ and after installation, I run `spack list` and it shows me a lot of letters followed by: `==> 7179 packages`. that's not looking bad

**Comment by alexmyczko** [comment]
actually it looks surprisingly well:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036754
http://bananas.debian.net/debian/spack/
https://salsa.debian.org/debian/spack

**Comment by alexmyczko** [comment]
For completeness, you can find the latest packaging effort at https://salsa.debian.org/debian/spack
