### ISSUE TITLE
spack create failed if there's any num in package name like "kkkk123ccc"

### ISSUE THREAD

**Issue by darmac** [spack/spack#14168]
The cmd "spack create" will change to "spack checksum" if some num in package name.

### Steps to reproduce the issue

```console
$ spack create kkkk123ccc
```

### Error Message
```console
==> This looks like a URL for kkkk
==> Found 1 version of kkkk:

  123ccc  kkkk123ccc

==> How many would you like to checksum? (default is 1, q to abort)
```

**Comment by adamjstewart** [comment]
`spack create` takes a URL, not a package name. You can try `spack create -n kkkk123ccc`

**Comment by darmac** [comment]
got it.
