### ISSUE TITLE
Installation issue: skilion-onedrive due to dmd not in $PATH

### ISSUE THREAD

**Issue by weijianwen** [spack/spack#14191]
### Steps to reproduce the issue

```console
$ spack install skilion-onedrive %gcc@4.8.5
...
1 error found in build log:
     4     ==> [2019-12-17-13:13:31.845228] FILTER FILE: src/sqlite.d [replacing "std.c.stdlib"]
     5     ==> Executing phase: 'build'
     6     ==> [2019-12-17-13:13:31.846711] 'make' '-j6' 'onedrive' 'DESTDIR=/lustre/home/acct-hpc/hpc-jianwen/opt/cascadelake/linux-ce
           ntos7-haswell/gcc-4.8.5/skilion-onedrive-1.1.1-ohthifmfl67taullatpi2dixgilfs4bs' 'PREFIX=/'
     7     echo 1.1.1 >version
     8     dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedr
           ive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
     9     make: dmd: Command not found
  >> 10    make: *** [onedrive] Error 127
...
$ tail /tmp/hpc-jianwen/spack-stage-skilion-onedrive-1.1.1-ohthifmfl67taullatpi2dixgilfs4bs/spack-build-out.txt
make: dmd: Command not found
make: *** [onedrive] Error 127
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.5.1804 (Core)
``` 

`dmd` (the reference compiler for D programming language) has been installed as dependency, located in `~/opt/cascadelake/linux-centos7-haswell/gcc-4.8.5/dmd-2.081.1-2gzzuz4ut26pj4l7om4k7lejm2r5ty6s/linux/bin64/dmd`. Location `linux/bin64` has been added to PATH in `dmd` package via:

```
run_env.prepend_path('PATH', self.prefix.linux.bin64)
```

It seems that Spack isn't aware of this when loading dmd as a dependency when building 
skilion-onedrive.

**Comment by adamjstewart** [comment]
See #14198.

The problem is that `setup_run_environment`  is only used to generate module files, it isn't run for dependent packages.

**Comment by weijianwen** [comment]
@adamjstewart 

Adding `setup_dependent_build_environment(self, env)` as #14198  results in the following errror. Should it be `setup_dependent_build_environment(self, env, dependent_spec)`?


```
...
==> Installing skilion-onedrive
==> Searching for binary cache of skilion-onedrive
==> Finding buildcaches at http://spack.pi.sjtu.edu.cn/mirror/build_cache
==> No binary for skilion-onedrive found: installing from source
==> Error: TypeError: setup_dependent_build_environment() takes 2 positional arguments but 3 were given

/lustre/home/acct-hpc/hpc-jianwen/spack/lib/spack/spack/build_environment.py:823, in child_process:
        820            tb_string = traceback.format_exc()
        821
        822            # build up some context from the offending package so we can
  >>    823            # show that, too.
        824            package_context = get_package_context(tb)
        825
        826            build_log = None
```

**Comment by adamjstewart** [comment]
Fixed, can you try again?

**Comment by abraunegg** [comment]
@weijianwen, @adamjstewart 
> Installation issue: skilion-onedrive due to dmd not in $PATH

The 'skilion' code appears to have been abandoned and contains many issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive
