### ISSUE TITLE
Installation Issue: cmake @ 3.15.5 checksum error

### ISSUE THREAD

**Issue by coreyjadams** [spack/spack#14216]
I get a checksum error when building packages that require cmake:

$ spack stage cmake@3.15.5
==> Using cached archive: /gpfs/mira-home/cadams/Cooley/spack/var/spack/cache/_source-cache/archive/fb/fbdd7cef15c0ced06bb13024bfda0ecc0dedbcaaaa6b8a5d368c75255243beb4.tar.gz
==> Fetching https://gitlab.kitware.com/cmake/cmake/merge_requests/4075.patch
######################################################################## 100.0%
==> Error: sha256 checksum failed for /tmp/cadams/spack-stage/spack-stage-3ngsa7kj/4075.patch
Expected 3387faf4a71efe81c0fa17410b270ca7d352081ac88d2322df3da9bb6a6a3f2d but got 001736d791957225aadfc416b0cef915e8c8dcc04765b8e0fcbebf6058a05560

This was triggered when I tried to install py-torch with 
$ spack install py-torch^intel-mkl ^cuda@10.1   %gcc@6.3.0

I am trying again with 
$ spack install py-torch^intel-mkl ^cuda@10.1 ^cmake@3.15.1  %gcc@6.3.0
to see if cmake builds, since I see there was an open and closed issue regarding cmake 3.15.1.

Please report your OS here:
Linux cc015 3.10.0-957.27.2.el7.x86_64 #1 SMP Tue Jul 9 16:53:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:	Red Hat Enterprise Linux Server release 7.7 (Maipo)

Is there something I need to do to get the checksums to work?

**Comment by adamjstewart** [comment]
Yay, another person using Spack to install PyTorch!

The checksum error you found was fixed in #14125. You can either make that change locally yourself, or update to the latest develop version of Spack.
