### ISSUE TITLE
Buildcache Create fails for Package with External Dependency

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#14233]
Spack version: v0.13.2

I am trying to generate a cached binary of hdf5, where hdf5 depends on the external package spectrum-mpi.

```
$> spack buildcache create -afr --key <key> --no-deps <hdf5-hash>
==> creating binary cache file for package hdf5@1.10.5%gcc@7.4.0~cxx~debug~fortran~hl+mpi patches=b61e2f058964ad85be6ee5ecea10080bf79e73f83ff88d1fa4b602d00209da9c +pic+shared~szip~threadsafe arch=linux-rhel7-power9le
==> Warning: Can't extrapolate a URL for version 16.01.0001.0003 because package spectrum-mpi defines no URLs
$>
```

At this point, no binary is created.

Spectrum-mpi is defined as an external in my active Spack environment:
```
spack.yaml
---
spack:
  packages:
    spectrum-mpi:
      buildable: false
      modules:
        spectrum-mpi@16.01.0001.0003: spectrum-mpi/10.3.0.0-20190419
...
```

@becker33 @gartung

**Comment by gartung** [comment]
@eugeneswalker can you also make a comment where you note the change you tried.

**Comment by gartung** [comment]
@scottwittenburg You added the total package hash correct?

**Comment by gartung** [comment]
This is where the bug originates.

**Comment by scottwittenburg** [comment]
> @scottwittenburg You added the total package hash correct?

@gartung I added the package full hash into the `spec.yaml` file that gets written upon buildcache creation, if that's what you mean.  Is that related to this issue?

**Comment by eugeneswalker** [comment]
The problem originates when calling `spec.full_hash()` on hdf5 from within `build_tarball()` in `binary_distribution.py`. When trying to calculate the full_hash for hdf5, `to_node_dict()` gets invoked for the external package `spectrum-mpi`, which on lines 1522-1523 of `spec.py` calls `spec.package.content_hash()` and ultimately causes the problem.
```
#spec.py
def to_node_dict(self, hash=ht.dag_hash):
  ...
  if hash.package_hash: # line 1522
    d['package_hash'] = self.package.content_hash()
  ...
```
I was able to get `buildcache create` to finish and generate output which I could use for install using this temporary fix:
```
#spec.py
def to_node_dict(self, hash=ht.dag_hash):
  ...
  if *not self.external* and hash.package_hash:
    d['package_hash'] = self.package.content_hash()
  ...
```
... but this does not seem like a long-term solution.
@gartung

**Comment by scottwittenburg** [comment]
I see, thanks for the explanation @eugeneswalker.  In some way I'm glad you're running into this, as a fix will be required before we can properly support external packages in pipelines too.

@tgamblin

**Comment by gartung** [comment]
My guess is this line triggers the error
https://github.com/spack/spack/blob/af249d3cf6617cd635ed7aa54dddd83d7eb09cef/lib/spack/spack/package.py#L1257

**Comment by gartung** [comment]
So the actual error comes from here
https://github.com/spack/spack/blob/0592c580302ca8edf6f404d046d2e670a69bba6e/lib/spack/spack/fetch_strategy.py#L1238

**Comment by gartung** [comment]
This is in _extrapolate which is called from here
https://github.com/spack/spack/blob/af249d3cf6617cd635ed7aa54dddd83d7eb09cef/lib/spack/spack/fetch_strategy.py#L1271

**Comment by gartung** [comment]
My proposed solution is #14237

**Comment by eugeneswalker** [comment]
Any chance this will be addressed in 0.14.0 release? @tgamblin @becker33 @scottwittenburg

**Comment by eugeneswalker** [comment]
I believe this has been resolved.

**Comment by scottwittenburg** [comment]
@opadron This bears a striking resemblance to what you were just showing me with the `opengl` package, I think.  While external packages are currently supported in pipelines, it may be that this kind of "no-source, no-version, external-only" package is not included.
