### ISSUE TITLE
py-meep does not properly find MPI

### ISSUE THREAD

**Issue by becker33** [spack/spack#1427]
As @adamjstewart wrote in his PR:

"""

I don't think this actually works. The package is linked to MPI properly:

$ ldd py-meep-1.4.2-ikjdpnikleqeaxvncnag37bhhdnfafoj/lib/python2.7/site-packages/_meep_mpi.so 
...
    libmpi.so.20 => /blues/gpfs/home/software/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-6.1.0/openmpi-2.0.0-tapt7aozvnpq4m7tf7cbsa5zefy4kc6s/lib/libmpi.so.20 (0x00002b0cbd86b000)
...

but when I import it:

$ python
Python 2.7.12 (default, Jul 21 2016, 15:23:03) 
[GCC 6.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import meep_mpi
> > > Neither libmpi.so.0 nor libmpi.so found. Fatal error.
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/soft/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.12-hfkksvc2jgtlvkjagr33k6khrnj7yfqt/lib/python2.7/site-packages/meep_mpi.py", line 5088, in <module>
> > >     raise e
> > > OSError: libmpi.so: cannot open shared object file: No such file or directory

it can't find MPI.

By the way, if I add MPI to my LD_LIBRARY_PATH, py-meep finds it, so I don't think this problem should hold up the PR.

"""

SPACK packages should not rely on LD_LIBRARY_PATH

**Comment by davydden** [comment]
> SPACK packages should not rely on LD_LIBRARY_PATH

:+1:

**Comment by alalazo** [comment]
Is this one still an issue?

**Comment by adamjstewart** [comment]
I don’t think anyone has updated `py-python-meep` since I first created the package, so it’s still likely an issue. But I would be fine with closing the issue since no one uses the package anyway.

**Comment by alalazo** [comment]
@adamjstewart I'll go on and close this. I think if anybody has an issue with `py-meep` he'll be more likely to reopen than to look here anyhow.
