### ISSUE TITLE
Debug Output Minus Lock Messages

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#14293]
Could we segregate lock related debug-messages from other debug output?

It'd be nice to use the `-d` flag and not be overwhelmed with lock acquired/released/etc messages when you're just trying to find out why something isn't working.

**Comment by adamjstewart** [comment]
#14263 removed a lot of locking messages from Spack Environments. Is there anywhere else you see excessive locking messages? This could be another place where we can make a performance improvement.

**Comment by eugeneswalker** [comment]
I see what you're saying about reduced lock-related debug messages during standard spack install. I was working off of `v0.13.3` and I think the copious lock-related debug messages had to do with the initial examination of `.spec.yaml` files from the buildcache. Can you think of a reason why there would be locking/unlocking of the Spack database just by reading from a remote buildcache? Is this expected?

**Comment by adamjstewart** [comment]
@tgamblin @gartung can you take a look at this?

**Comment by tgamblin** [comment]
@eugeneswalker: can you give us some example output of what you are seeing?

**Comment by eugeneswalker** [comment]
This is using the head of develop as of ~ 11am this morning (6c957b6b6). I cleaned the Spack environment: `spack clean -a`.

And then, here is the output of running
```
spack install ./zlib.spec.yaml
```

[install.log](https://github.com/spack/spack/files/4006068/install.log)

**Comment by gartung** [comment]
You csan always turn off locking in config.yaml.

**Comment by gartung** [comment]
Installing using a spec.yaml is not finding the corresponding buildcache?

**Comment by eugeneswalker** [comment]
@gartung I'm sorry, I don't understand what you are asking in regards to not finding the corresponding buildcache when installing from `spec.yaml`

**Comment by gartung** [comment]
I was trying to understand what you were trying to debug and if buildcaches were involved.

**Comment by eugeneswalker** [comment]
@gartung The real question is the one that started this whole thread, which is: can we do anything about segregating lock related debug messages from other debug output? Perhaps multiple levels of verbosity where lock messages are excluded in one level and included in a higher level of verbosity, or perhaps a specific flag for including lock-related messages in the debug output? Except for maybe one or two times where I've encountered an issue that actually had to do with a lock-related issues, almost every time I use the debug flag it is to drill down on something not lock related, and having copious lock messages is distracting. It's not a big deal ultimately, but I thought it was worth raising this question as others may feel similarly.

**Comment by adamjstewart** [comment]
For most commands, Spack should only need to acquire a lock on the database a single time. If it's doing that more than once (thousands of times in your case and in #14259), then there is a significant performance overhead that can be avoided. In the case of #14263, cutting down on those locks and a few other hacks caused `spack install` to work 34x faster for Environments. In my opinion, we shouldn't remove these locking debug messages, but use them to figure out where we can make Spack faster. @eugeneswalker would your problem be solved if Spack only acquired a single lock instead of thousands of locks?

**Comment by eugeneswalker** [comment]
@adamjstewart If we could have the same Spack functionality using a single or just-a-few lock cycles where there are now many lock cycles, that seems like it'd be a big win beyond just eliminating the copious lock messages from the debug output, which was the original motivation for this feature request!

**Comment by eugeneswalker** [comment]
Can we revisit this? My `spack -d` pipeline logs are totally overwhelmed by these messages.

```
==> [2020-04-08-14:24:08.361375, 58] read locking [2218455483560831207:1]: timeout None sec
==> [2020-04-08-14:24:08.361430, 58] READ LOCK (ncurses): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/prefix_failures[2218455483560831207:1] [Acquired at 14:24:08.361414] 
==> [2020-04-08-14:24:08.361461, 58] READ LOCK (ncurses): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/prefix_failures[2218455483560831207:1] [Releasing] 
==> [2020-04-08-14:24:08.361512, 58] READ LOCK (ncurses): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/prefix_failures[2218455483560831207:1] [Released at 14:24:08.361499] 
==> [2020-04-08-14:24:08.361556, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Acquiring] 
==> [2020-04-08-14:24:08.361645, 58] read locking [0:0]: timeout 3 sec
==> [2020-04-08-14:24:08.361690, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Acquired at 14:24:08.361677] 
==> [2020-04-08-14:24:08.361768, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Releasing] 
==> [2020-04-08-14:24:08.361819, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Released at 14:24:08.361807] 
==> [2020-04-08-14:24:08.361866, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Acquiring] 
==> [2020-04-08-14:24:08.361953, 58] read locking [0:0]: timeout 3 sec
==> [2020-04-08-14:24:08.361997, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Acquired at 14:24:08.361984] 
==> [2020-04-08-14:24:08.362071, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Releasing] 
==> [2020-04-08-14:24:08.362131, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Released at 14:24:08.362118] 
==> [2020-04-08-14:24:08.369780, 58] READ LOCK (readline): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/prefix_failures[1541299813521930655:1] [Acquiring] 
==> [2020-04-08-14:24:08.369906, 58] read locking [1541299813521930655:1]: timeout None sec
==> [2020-04-08-14:24:08.369959, 58] READ LOCK (readline): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/prefix_failures[1541299813521930655:1] [Acquired at 14:24:08.369944] 
==> [2020-04-08-14:24:08.369989, 58] READ LOCK (readline): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/prefix_failures[1541299813521930655:1] [Releasing] 
==> [2020-04-08-14:24:08.370039, 58] READ LOCK (readline): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/prefix_failures[1541299813521930655:1] [Released at 14:24:08.370026] 
==> [2020-04-08-14:24:08.370082, 58] READ LOCK (database): /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Acquiring] 
```

@tldahlgren

**Comment by adamjstewart** [comment]
Yes, the parallel build support added a lot of additional locking requirements. @eugeneswalker why do you need to run Spack in debug mode?

**Comment by eugeneswalker** [comment]
I'm trying to build ~240 packages x 5 operating systems on both ppc64le and x86_64 as part of an automated build pipeline, with dependencies installed from build cache (when available). At that scale, installations are bound to fail and the cause is not always evident in spack-build-out.txt. I'd rather have more context than less in my automated pipeline logs. That said, I cannot remember a single time any install failure I experienced was traced to a lock issue, but there have been many times where the non-lock debug output was helpful in getting to a root cause. That's a situation where the useful debug output is buried in a sea of mostly, if not entirely unhelpful, lock messages. It's so disproportionate. Just my five cents.

**Comment by tldahlgren** [comment]
A number of those log debug messages were supposed to be at the verbose level and should still be tagged with comments in the code.  They were changed to debug because they broke a number of tests that parsed the output.

Addressing this has come up in a recent meeting so it's priority is "bubbling up".
