### ISSUE TITLE
Installation issue: intel-mpi@2019.6.154%gcc@9.2.0 

### ISSUE THREAD

**Issue by mkiernan** [spack/spack#14321]
Looks like the URL for intel-mpi 2019.6 is incorrect. 

Also, is there any particular reason why the 2019.5.281 version has been skipped ?

spack install intel-mpi@2019.6.154%gcc@9.2.0
==> Installing intel-mpi
==> Searching for binary cache of intel-mpi
==> No binary for intel-mpi found: installing from source
==> Fetching http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16120/l_mpi_2019.6.154.tgz
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16120/l_mpi_2019.6.154.tgz
    URL http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16120/l_mpi_2019.6.154.tgz was not found!
==> Fetching from http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16120/l_mpi_2019.6.154.tgz failed.
==> Error: FetchError: All fetchers failed for spack-stage-intel-mpi-2019.6.154-vkmf2q2jbqucj5fupebl3cmf6o652iw4

/shared/home/mk/azure-spack/spack/lib/spack/spack/package.py:1110, in do_fetch:
       1107                raise FetchError("Will not fetch %s" %
       1108                                 self.spec.format('{name}{@version}'), ck_msg)
       1109
  >>   1110        self.stage.create()
       1111        self.stage.fetch(mirror_only)
       1112        self._fetch_time = time.time() - start_time
       1113

**Comment by adamjstewart** [comment]
This release is no longer present in the `intel-mpi` package, you should use a different release. If you have problems downloading any of the other releases let me know.

**Comment by LuisSalbey** [comment]
I'm having problem installing intel-mpi@2019.10.317

spack install intel-mpi@2019.10.317
==> Installing intel-mpi-2019.10.317-4ss2iw6eg4bqt6jrlt5dqiyhh6yi3ugs
==> No binary for intel-mpi-2019.10.317-4ss2iw6eg4bqt6jrlt5dqiyhh6yi3ugs found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/28/28e1b615e63d2170a99feedc75e3b0c5a7e1a07dcdaf0a4181831b07817a5346.tgz
==> No patches needed for intel-mpi
==> intel-mpi: Executing phase: 'configure'
==> intel-mpi: Executing phase: 'install'
==> Error: InstallError: Install failed for intel-mpi.  Nothing was installed!

/spack/lib/spack/spack/package.py:1957, in sanity_check_prefix:
       1954        installed.difference_update(
       1955            spack.store.layout.hidden_file_paths)
       1956        if not installed:
  >>   1957            raise InstallError(
       1958                "Install failed for %s.  Nothing was installed!" % self.name)

See build log for details:
  /tmp/root/spack-stage/spack-stage-intel-mpi-2019.10.317-4ss2iw6eg4bqt6jrlt5dqiyhh6yi3ugs/spack-build-out.txt

any help would be appreciated.

Thanks.

**Comment by LuisSalbey** [comment]
spack --version
0.16.2-4335-c24413a530
