### ISSUE TITLE
Upgrade to MacOS Catalina

### ISSUE THREAD

**Issue by jlconlin** [spack/spack#14407]
I upgraded my Mac to MacOS Catalina (10.15) and Spack stopped working due to the `module` command not being found. I tried to reinstall Spack and reinstall tmux, but it didn't change anything. (Note, this isn't unique to tmux, my other installations also didn't work with the same error message.)

### Steps to reproduce the issue
1. Upgrade from MacOS Mojave to MacOS Catalina
```console

$ spack load ...
-bash: module: command not found
```

### Error Message
 
As shown above, I get the error: `module: command not found`. 
If Spack reported an error, provide the error message. If it did not report an error
but the output appears incorrect, provide the incorrect output. If there was no error
message and no output but the result is incorrect, describe how it does not match
what you expect. To provide more information you might re-run the commands with 
the additional -d/--stacktrace flags:
```console
$ spack -d --stacktrace load tmux
lib/spack/spack/config.py:683 ==> [2020-01-06-16:48:57.091950] Reading config file /Users/jlconlin/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:683 ==> [2020-01-06-16:48:57.100733] Reading config file /Users/jlconlin/spack/etc/spack/defaults/darwin/modules.yaml
lib/spack/spack/config.py:683 ==> [2020-01-06-16:48:57.104597] Reading config file /Users/jlconlin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:683 ==> [2020-01-06-16:48:57.116660] Reading config file /Users/jlconlin/.spack/config.yaml
lib/spack/spack/cmd/__init__.py:98 ==> [2020-01-06-16:48:57.122577] Imported module from built-in commands
lib/spack/spack/cmd/__init__.py:98 ==> [2020-01-06-16:48:57.133432] Imported module from built-in commands
lib/spack/spack/database.py:214 ==> [2020-01-06-16:48:57.152617] DATABASE LOCK TIMEOUT: 120s
lib/spack/spack/database.py:218 ==> [2020-01-06-16:48:57.153285] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/llnl/util/lock.py:334 ==> [2020-01-06-16:48:57.154775] READ LOCK: /Users/jlconlin/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2020-01-06-16:48:57.155778] READ LOCK: /Users/jlconlin/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/spack/config.py:683 ==> [2020-01-06-16:48:57.185369] Reading config file /Users/jlconlin/spack/etc/spack/defaults/repos.yaml
lib/spack/llnl/util/lock.py:334 ==> [2020-01-06-16:48:57.392742] READ LOCK: /Users/jlconlin/spack/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2020-01-06-16:48:57.405821] READ LOCK: /Users/jlconlin/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2020-01-06-16:48:57.406916] READ LOCK: /Users/jlconlin/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2020-01-06-16:48:57.424567] READ LOCK: /Users/jlconlin/spack/opt/spack/.spack-db/lock[0:0] [Released]
-bash: module: command not found
```

### Information on your system

This includes:

 1. which platform you are using
     MacOS Catalina (10.15.2)
 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)

~/.spack/darwin/compilers.yaml
```yaml
compilers:
- compiler:
    spec: clang@10.0.0-apple
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77:
      fc:
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

**Comment by adamjstewart** [comment]
Do you have modules installed? If not, you can install it with Spack. If it was installed on your previous OS, it probably won't work after the upgrade. For what it's worth, #14062 will remove the `modules` requirement for `spack load`.

**Comment by jlconlin** [comment]
So I did have `environment-modules` installed previously (although I don't recall installing it myself.) I just installed it with spack version 0.13.3 and I get a similar error message of `-bash: /bin-modulecmd: No such file or directory`.

I'm not sure what #14062 entails as far as no needing the module command/package. Do I still load packages with `spack load` like I did in the past? In any event, I'm still stuck on getting this to work.

**Comment by adamjstewart** [comment]
I believe you need to source a script that adds the `module` function to your environment, or add `prefix.bin` to your `PATH` so we can find `modulecmd`. @becker33 @alalazo would be more familiar with this than me.

**Comment by jlconlin** [comment]
I was sourcing a script: `source $SPACK_ROOT/share/spack/setup-env.sh`. I had the same setup (i.e., ~/.bashrc file) as before. I just moved that line to later in the setup and now things seem to work. I do have to update everything to work with the new machine, but I can take care of that.

**Comment by adamjstewart** [comment]
@jlconlin great! I'm also using Spack on macOS Catalina without any problems (although I'm not using modules), so let me know if you encounter any other issues!

**Comment by jlconlin** [comment]
I don't know if I'm using modules or not. I simply say `spack load ...`. I don't really care how it's done under the hood. Should I?

**Comment by adamjstewart** [comment]
Currently, `spack load` is a wrapper around `module load`. Once #14062 is merged (probably soon), `spack load` will still work the way you expect but won't need environment-modules installed anymore.
