### ISSUE TITLE
tests: test_patchelf_is_relocatable fails on LLNL/Quartz

### ISSUE THREAD

**Issue by tldahlgren** [spack/spack#14402]
The ``test_patchelf_is_relocatable`` test fails on LLNL's Quartz since `patchelf` is a bash script wrapper, not an executable as required by the test.

Perhaps ``is_binary`` should be checking the subtype from ``mime_type`` and declaring binary if it is ``x-shellscript``?

### Steps to reproduce the issue

```console
$ spack test -k test_patchelf_is_relocatable
...
```

### Error Message

```console
_________________________ test_patchelf_is_relocatable _________________________

    @pytest.mark.requires_executables(
        'patchelf', 'strings', 'file'
    )
    def test_patchelf_is_relocatable():
        patchelf = spack.relocate.get_patchelf()
>       assert spack.relocate.is_binary(patchelf)
E       AssertionError: assert False
E        +  where False = <function is_binary at 0x2aaab19c62f0>('/usr/tce/bin/patchelf')
E        +    where <function is_binary at 0x2aaab19c62f0> = <module 'spack.relocate' from '$HOME/spack/clean/spack/lib/spack/spack/relocate.py'>.is_binary
E        +      where <module 'spack.relocate' from '$HOME/spack/clean/spack/lib/spack/spack/relocate.py'> = spack.relocate

relocate.py:68: AssertionError
...
```

### Information on your system

Running on LLNL's Quartz, where ``/usr/tce/packages/patchelf/patchelf-0.8/bin/patchelf`` symlinks ultimately to a bash script that uses `exec`.

**Comment by gartung** [comment]
@alalazo This is an unexpected case where `which patchelf` returns a wrapper script(?).
Patchelf installed by spack is a binary.

**Comment by gartung** [comment]
Probably just need to remove the assert.

**Comment by tgamblin** [comment]
I think @gartung is correct.

@lee218llnl @becker33: is the `patchelf` script at LC something that's there for TCE to make sure pipelines work?

**Comment by LRWeber** [comment]
`patchelf` is "A small utility to modify the dynamic linker and RPATH of ELF executables."
We have a few packages that rely on it, typically as part of their build process.

**Comment by tgamblin** [comment]
@LRWeber: yes, spack relies on it too. We’re just wondering why LC’s is a wrapper and not a binary.

**Comment by LRWeber** [comment]
Ah, I understand the question now.
The wrapper script on the TCE installation is there for usage tracking. We have similar wrappers on most of the vis tools there.

**Comment by adamjstewart** [comment]
I'm experiencing this same test failure on macOS. The first `patchelf` in my `PATH` is a symlink in a Spack Environment. If I instead switch my `PATH` so that the actual installation prefix comes first, the tests pass.

**Comment by tgamblin** [comment]
We should just assert that it is executable, not that it is a binary.

**Comment by tldahlgren** [comment]
> We should just assert that it is executable, not that it is a binary.

Okay.  Should be a quick fix.
