### ISSUE TITLE
`spack.config.override()` prepends to lists rather than replacing

### ISSUE THREAD

**Issue by chissg** [spack/spack#14416]
Given the case where a list configuration item is specified in YAML (`config.yaml`, say):
```YAML
...
extensions:
  - /my/path/to/extension
```
and a test overrides that item, _viz_:
```Python
    with spack.config.override('config:extensions', ['/my/path/to/extension-1', '/my/path/to/extension-2']):
        ...
```
Then the actual value of `config:extensions` inside the overridden context as returned by `spack.config.get()` is:
```Python
['/my/path/to/extension-1', '/my/path/to/extension-2', '/my/path/to/extension']
```
rather than the expected:
```Python
['/my/path/to/extension-1', '/my/path/to/extension-2']
```

I would expect higher priority scopes to replace lists rather than prepend to them, at least as a default behavior. Is this intended, and what is the use case?

**Comment by chissg** [comment]
Created following a conversation on [Slack#General](https://spackpm.slack.com/archives/C5W7NKZJT/p1578346978172300) with @tgamblin and @tldahlgren .

**Comment by chissg** [comment]
@tldahlgren Per your question:
```console
==> Warning: [1] config.scopes.values() = odict_values([<InternalConfigScope: _builtin>, <ConfigScope: defaults: /Users/greenc/work/cet-is/sources/spack-test/etc/spack/defaults>, <ConfigScope: defaults/test: /Users/greenc/work/cet-is/sources/spack-test/etc/spack/defaults/test>, <ConfigScope: system: /etc/spack>, <ConfigScope: system/test: /etc/spack/test>, <ConfigScope: site: /Users/greenc/work/cet-is/sources/spack-test/etc/spack>, <ConfigScope: site/test: /Users/greenc/work/cet-is/sources/spack-test/etc/spack/test>, <ConfigScope: user: /Users/greenc/.spack>, <ConfigScope: user/test: /Users/greenc/.spack/test>, <InternalConfigScope: overrides-0>, <InternalConfigScope: command_line>])
```
Note that the `command_line` scope is always highest priority. `overrides-0` is directly below that, as one would expect.

**Comment by tgamblin** [comment]
what happens if you do with `spack.config.override('config:extensions:')`?  Does that make the top-level config completely replace lower-level ones?  We have the (heretofore somewhat inconsistently supported) `::` syntax for this -- it'd be cool if we could use it here.

**Comment by chissg** [comment]
@tgamblin I receive a `KeyError` in `spack.config.set()`

**Comment by tldahlgren** [comment]
> what happens if you do with `spack.config.override('config:extensions:')` (note the colon)? Does that make the top-level config completely replace lower-level ones? We have the (heretofore somewhat inconsistently supported) `::` syntax for this -- it'd be cool if we could use it here.

@tgamblin Did you mean try ask @chissg to try `spack.config.override('config:extensions::')` (i.e., end in a double-colon)?

**Comment by chissg** [comment]
@tldahlgren 's suggestion results in the same `KeyError`. Adding a `:` or `::` to a `spack.config.get()` call results in the error:
```console
E           AttributeError: 'CommentedSeq' object has no attribute 'get'
```
in both cases.

**Comment by tldahlgren** [comment]
@chissg  Interesting.  Thanks for checking.

Note: A `Configuration` object's `get` method uses its `get_config` method, which does use the  `_merge_yaml` function for `dict` entries per comments:

```Config file authors can optionally end any attribute in a dict with `::` instead of `:`, and the key will override that of the parent instead of merging.```

IIUC this is the preferred approach to resolve this issue.

**Comment by chissg** [comment]
@tldahlgren  One would have to add this functionality for lists in `_merge_yaml()`, but it would seem also that `config.set()` would need to understand the `::` notation (the current use of `split()` is insufficient) and create the relevant keys as `syaml.syaml_str` entities with the `override` attribute set (rather than simple strings) in order to allow the override functionality to be triggered. Is there anything else I'm missing?
