### ISSUE TITLE
The download cache directory for buildcache is not cleared by 'spack clean -a' as expected.

### ISSUE THREAD

**Issue by gartung** [spack/spack#14428]
The download cache directory for buildcache files used to be created in 
$spack/var/spack/stage 
and would be cleared by
spack clean -a
Now the download cache directory for buildcache files is create in
/tmp/$user/spack-stage/build_cache
and is not cleared by
spack clean -a

The spack clean command should be updated to remove this directory perhaps with a -b option.

Only the existence of the .spack file  in the download cache directory is checked when deciding to download a .spack file so the directory needs to be cleaned out if a newer .spack files is available on the mirror.

**Comment by gartung** [comment]
@eugeneswalker you can add any additional details if you like.

**Comment by eugeneswalker** [comment]
@gartung do you know if it is possible right now to manually specify what directory these files are staged in via a configuration file or CLI opt?

**Comment by gartung** [comment]
I know @scottwittenburg  or @opadron added some code to deal with S3 uploads. Maybe they can comment.

**Comment by opadron** [comment]
I don't think moving the staging area from `$spack/var/spack/stage` to `/tmp/$user/spack-stage/build_cache` was something we did while adding the S3 features.

@eugeneswalker see [here](https://spack.readthedocs.io/en/latest/config_yaml.html#config-yaml) for details on setting the stage directory.

**Comment by gartung** [comment]
@opadron Thanks. I was thinking of configuring the directory where buildcaches are created to use some other name thatn build_cache.

**Comment by opadron** [comment]
Oh I see.  I understand that this is done for all buildcaches so that a single directory, `x` can serve as the root for both a source mirror (`$x`) and a build cache (`$x/build_cache`).  The `build_cache` subdirectory is effectively a part of the buildcache API.
