### ISSUE TITLE
Question/RFE: Where to control compiler options

### ISSUE THREAD

**Issue by mkiernan** [spack/spack#14459]
I would like to be able to specify compiler flags on a per package basis depending on the underlying architecture. 

For example, I want to turn on avx512 for a particular package like quantum-espresso if I'm building on skylake, but I don't want that option if I'm building on zen, and I don't want the underlying QE dependencies to use avx512 either. 

I can do that on the "spack install" command line, but it's tedious/verbose to do do this for many packages. Ideally there would be a way to specify this in the packages.yaml file like you can with (conditional) variants. 

Apologies in advance if I'm missing something but I can't see a way to achieve this as a generalization other than setting global options via the "flags" in compiler.yaml. Is there any existing way to encode this in the configuration to set default flags conditionally per package other than explicitly on the install command line ?

If the functionality doesn't exist, may I log this as an RFE please ?

**Comment by glennpj** [comment]
With a recent develop branch this would be handled by the microarchitecture checking code. The current released version of spack will also have that but I am not sure if all of the packages take advantage of that yet. The microarchitecture code will set the CPU feature flags based on the build machine and the compiler used. The documentation can be found here:
[Support for specific microarchitectures
](https://spack.readthedocs.io/en/latest/basic_usage.html#support-for-specific-microarchitectures)

**Comment by alalazo** [comment]
This was already answered, so closing
