### ISSUE TITLE
Installation issue: magma (review gcc/cuda conflicts)

### ISSUE THREAD

**Issue by jthies** [spack/spack#14465]
I think the "conflicts" in the magma/package.py should be reviewed, afaik cuda 9 works fine with gcc 7? And what about cuda 10? And - isn't this kind of stuff handled by the CudaPackage?

**Comment by adamjstewart** [comment]
@Sinan81 can you take a look at this? Sounds like the exact same fix as you did in #13959.

**Comment by Sinan81** [comment]
Sure!
