### ISSUE TITLE
spack.binary_distribution.get_specs() should accept an arch filter option

### ISSUE THREAD

**Issue by gartung** [spack/spack#14466]
`spack install` command  calls spack.package.try_install_from_binary_cache() which calls spack.binary_distribution.get_specs(). 

spack.binary_distribution.get_specs() was modified in 
https://github.com/spack/spack/pull/13002
to allow listing and installing buildcaches for macOS on a linux host.

In the case where a mirror contains buildcaches for multiple OSes the spack install command can spend more time downloading all of the specs from the build_cache directory than it takes to install the buildcache. The is especially true when using pipelines and the buildcache download directory is cleared between steps.

I will modify the get_specs() command to accept a filter option and pass the current OS as the filter option when get_specs() is called from spack.package.try_install_from_binary_cache()

**Comment by eugeneswalker** [comment]
This will make a big difference for the E4S team at UO. Our cache currently has ~2400 packages split among 2 architectures * 5 different operating systems, and we are pretty much only building with gcc@7.3.0 right now . We plan to build out for aarch and cover more compilers, which means the problem will only get worse with time. Right now it can take longer than 5 minutes just to fetch the .spec.yamls when we first connect a spack instance to our mirror, as it downloads for ALL OS-ARCH combinations. This also results in ~20MB of .spec.yaml's in /tmp/<user>/spack-stage. 
@tgamblin @gartung

**Comment by gartung** [comment]
I merged #14467 to develop.

**Comment by gartung** [comment]
Re-opening as my "fix" caused a breakage.

**Comment by gartung** [comment]
Close with https://github.com/spack/spack/pull/14639
