### ISSUE TITLE
test_patchelf_is_relocatable fails on macOS

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#14470]
The `test_patchelf_is_relocatable` test from `relocate.py` fails on macOS.

### Steps to reproduce the issue

```console
$ spack test relocate.py::test_patchelf_is_relocatable
```

### Error Message

```console
$ spack test relocate.py::test_patchelf_is_relocatable
============================================= test session starts ==============================================
platform darwin -- Python 3.7.4, pytest-3.2.5, py-1.4.34, pluggy-0.4.0
rootdir: /Users/Adam/spack/lib/spack/spack/test, inifile: pytest.ini
plugins: mock-1.11.1, cov-2.8.1
collected 1 item                                                                                                

relocate.py F
=========================================== short test summary info ============================================
FAIL relocate.py::test_patchelf_is_relocatable

========================================== slowest 20 test durations ===========================================
0.09s setup    relocate.py::test_patchelf_is_relocatable
0.01s call     relocate.py::test_patchelf_is_relocatable
0.00s teardown relocate.py::test_patchelf_is_relocatable
=================================================== FAILURES ===================================================
_________________________________________ test_patchelf_is_relocatable _________________________________________

    @pytest.mark.requires_executables(
        'patchelf', 'strings', 'file'
    )
    def test_patchelf_is_relocatable():
        patchelf = spack.relocate.get_patchelf()
>       assert spack.relocate.is_binary(patchelf)
E       AssertionError: assert False
E        +  where False = <function is_binary at 0x10f442320>('/Users/Adam/.spack/darwin/.spack-env/view/bin/patchelf')
E        +    where <function is_binary at 0x10f442320> = <module 'spack.relocate' from '/Users/Adam/spack/lib/spack/spack/relocate.py'>.is_binary
E        +      where <module 'spack.relocate' from '/Users/Adam/spack/lib/spack/spack/relocate.py'> = spack.relocate

relocate.py:68: AssertionError
=========================================== 1 failed in 0.27 seconds ===========================================
```

### Information on your system

1. macOS 10.15.2
2. patchelf 0.10 is installed via Spack and is in the `PATH`

---

@gartung is this a test that we should skip on macOS? There are other tests in `relocate.py` that are skipped due to "implementation for MacOS still missing".

**Comment by adamjstewart** [comment]
@gartung Another question you might be able to answer. I have `gnupg@2.2.17` installed with Spack on macOS. The `cmd/gpg.py` tests are skipped on my laptop because `gnupg2` isn't installed. `gnupg` provides a `gpg` command, but not a `gpg2` command. Do we need to add a Spack package for `gnupg2`, or is `gnupg` equivalent?

**Comment by adamjstewart** [comment]
Also reported here: https://github.com/spack/spack/issues/14362#issuecomment-571356140

Closing as a duplicate of #14402

**Comment by gartung** [comment]
> @gartung Another question you might be able to answer. I have `gnupg@2.2.17` installed with Spack on macOS. The `cmd/gpg.py` tests are skipped on my laptop because `gnupg2` isn't installed. `gnupg` provides a `gpg` command, but not a `gpg2` command. Do we need to add a Spack package for `gnupg2`, or is `gnupg` equivalent?

There is already a spack package for gnupg which provides gpg2.

**Comment by adamjstewart** [comment]
Gnupg provides gpg, not gpg2, at least on macOS.

**Comment by gartung** [comment]
That is true of the homebrew package. I haven't tried building gnupg on macOS recently.

**Comment by gartung** [comment]
I verified that the spack gnupg package produces bin/gpg but not bin/gpg2
