### ISSUE TITLE
headers of python packages not listed in CPATH

### ISSUE THREAD

**Issue by mdorier** [spack/spack#14513]
When installed, Python packages have the typical structure with `include`, `lib`, and `bin` folders. When loaded by spack, their `include` directory is added to the CPATH environment  variable. Most python packages do not expose C headers. However, python packages that do have headers will often install them in `include/pythonX` (where X is the python version), rather than in `include` (for instance on my machine with Python 3.6.8 they are installed in `include/python3.6m`). Hence any code that requires these headers will need to `#include <python3.6m/path/to/the/header.h>` (so we should know ahead of time the python version) instead of simply `#include <path/to/the/header.h>`, OR it should figure out the header path by a means other than simply relying on CPATH.

It would be good, when loading a Python package, that its `include/pythonX` also be added to CPATH (with X being replaced appropriately).

**Comment by mdorier** [comment]
@adamjstewart I have updated my spack installation after this PR was merged, and retried, but it doesn't seem to work. I have a Python package in a personal namespace, called `py-tmci`, and if I load it and look at the content of CPATH, I get this:

```
/gpfs/mira-home/mdorier/flamestore/spack/opt/spack/cray-cnl6-mic_knl/gcc-7.3.0/py-tmci-develop-cmq6apdjkw2wimdhkxsarvcwueuyxdx4/include:/soft/interpreters/python/3.6/intel/2019.3.075/include/python3.6m:/soft/interpreters/python/3.6/intel/2019.3.075/include
```
`python3.6m` is added only to Python's include path, not to the package's include path.

Is there something to add in the package itself?

**Comment by mdorier** [comment]
I have the impression that the PR adds the include path for python itself, not for python packages. Maybe my issue wasn't clear (the confusion being that by "python package" I meant "python library", like numpy, etc., not the spack package that installs python).

**Comment by adamjstewart** [comment]
@mdorier taking a look at this again. We now have an easy way to do what you want to do. Should this be done:

1. at build time for all dependencies (`setup_dependent_build_environment`)
2. at run-time for a specific package (`setup_dependent_run_environment`)
3. recursively for all dependencies of dependencies

We currently do all three for `PYTHONPATH`, but I'm not sure if all three are needed for `CPATH`.

**Comment by adamjstewart** [comment]
> However, python packages that do have headers will often install them in `include/pythonX`

Can you give examples of this? Just about every Python library I know of installs header files to `lib/pythonX.Y/site-packages`, not `include/pythonX.Y`. This includes libraries like numpy, pybind11, xgboost, pandas, pytorch, and pythran.

**Comment by zakkg3** [comment]
`ln -s /usr/include/python3.6m/ /usr/include/3.11`
