### ISSUE TITLE
Build dependencies are not listed as installed packages in environments

### ISSUE THREAD

**Issue by paulbry** [spack/spack#14512]
When working with an activate environment only run/link dependencies are shown when listing installed packages.

### Steps to reproduce the issue

Though I originally noticed this issue when installing `llvm` it can be much easier to reproduce with several small packages.  Using a newly created environment:

```console
$ spack env status
==> Using spack.yaml in current directory: /var/tmp/spack-paul/var/spack/environments/test-find
$ spack install bzip2
...
$ spack find
==> In environment test-find
==> Root specs
bzip2

==> 1 installed package
-- linux-centos7-haswell / gcc@9.1.0 ----------------------------
bzip2@1.0.8
$ spack install libxml2
...
$ spack find
==> In environment test-find
==> Root specs
bzip2   libxml2

==> 5 installed packages
-- linux-centos7-haswell / gcc@9.1.0 ----------------------------
bzip2@1.0.8  libiconv@1.16  libxml2@2.9.9  xz@5.2.4  zlib@1.2.11
```

In the case of `bzip2` there is only a single build dependency, `diffutils`. And with `libxml2` the only build (only) dependency is `pkgconfig` which does no appear. It should be noted that in both cases all dependencies where accounted for in the spec and installed.

### Information on your system

When testing I did a `git clone` and use the most recent commit (e7add79cba27b161eb54b86d6212623c9069ef70).

[spack.lock.zip](https://github.com/spack/spack/files/4064014/spack.lock.zip)

**Comment by alalazo** [comment]
> When working with an activate environment only run/link dependencies are shown when listing installed packages.

Feature, not bug :slightly_smiling_face: Pure `build` dependencies are not needed at runtime, so they're not shown in the environment unless explicitly present as root specs. This behavior is particularly relevant when you add binary caches to the mix: if you have binary caches already built for the application or library you are interested in you don't need to install any build dependency.

**Comment by paulbry** [comment]
That makes sense, thanks for clarifying.
