### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by jwillenbring** [spack/spack#14515]
*Explain, in a clear and concise way, the command you ran and the result you were trying to achieve.

I am trying to install and use Spack on a CentOS 7 machines. I followed the instructions listed on the webpage to get started and ran into issues. I have used Spack on other machines and never run into this. I wonder if there is a missing dependence on this machine, but I am not getting useful debugging info.

### Steps to reproduce the issue

The first two command complete cleanly, but the third (and any other spack install <package> I have tried), results in an error. The error is the same in every case.

```console
git clone https://github.com/spack/spack.git
. spack/share/spack/setup-env.sh
spack install hdf5
```

### Error Message

```console
==> Error: 'NoneType' object has no attribute 'version'
```

### Information on your system

 1. CentOS 7
 2. Minimal configuration (new server)
 3. Python 2.7.5

I suspect this is something simple, but I have not been able to pin it down. I tried this on another machine just to see if I could reproduce it and I could not. I suspect it is something lacking in the default configuration. Spack is often very good about that and gives very straight-forward error messages. For example, recently it told me that I needed to install patch.

**Comment by alalazo** [comment]
Can you post the output of:
```
spack -d install hdf5
```
?

**Comment by jwillenbring** [comment]
Thank you for your reply.

```console
# spack -d install hdf5
==> [2020-01-15-11:55:13.046461] Imported install from built-in commands
==> [2020-01-15-11:55:13.049437] Reading config file /home/trilinos/install/spack/etc/spack/defaults/config.yaml
==> [2020-01-15-11:55:13.069041] Imported install from built-in commands
==> [2020-01-15-11:55:13.072164] Reading config file /home/trilinos/install/spack/etc/spack/defaults/repos.yaml
==> [2020-01-15-11:55:13.114500] Reading config file /home/trilinos/install/spack/etc/spack/defaults/packages.yaml
==> [2020-01-15-11:55:13.129086] READ LOCK: /home/trilinos/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquiring]
==> [2020-01-15-11:55:13.129220] READ LOCK: /home/trilinos/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquired]
==> [2020-01-15-11:55:13.129516] READ LOCK: /home/trilinos/.spack/cache/tags/.builtin-index.json.lock[0:0] [Released]
==> [2020-01-15-11:55:13.131484] READ LOCK: /home/trilinos/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquiring]
==> [2020-01-15-11:55:13.131589] READ LOCK: /home/trilinos/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquired]
==> [2020-01-15-11:55:13.142773] READ LOCK: /home/trilinos/.spack/cache/patches/.builtin-index.json.lock[0:0] [Released]
==> [2020-01-15-11:55:13.144977] READ LOCK: /home/trilinos/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquiring]
==> [2020-01-15-11:55:13.145097] READ LOCK: /home/trilinos/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquired]
==> [2020-01-15-11:55:13.160975] READ LOCK: /home/trilinos/.spack/cache/providers/.builtin-index.json.lock[0:0] [Released]
error: cannot open Packages database in /var/lib/rpm
Traceback (most recent call last):
  File "/home/trilinos/install/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/home/trilinos/install/spack/lib/spack/spack/main.py", line 711, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/trilinos/install/spack/lib/spack/spack/main.py", line 456, in _invoke_command
    return_val = command(parser, args)
  File "/home/trilinos/install/spack/lib/spack/spack/cmd/install.py", line 306, in install
    args.package, concretize=True, tests=tests)
  File "/home/trilinos/install/spack/lib/spack/spack/cmd/__init__.py", line 144, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/trilinos/install/spack/lib/spack/spack/spec.py", line 2140, in concretize
    self._concretize_helper(concretizer))
  File "/home/trilinos/install/spack/lib/spack/spack/spec.py", line 1966, in _concretize_helper
    concretizer, presets, visited
  File "/home/trilinos/install/spack/lib/spack/spack/spec.py", line 1979, in _concretize_helper
    concretizer.adjust_target(self),
  File "/home/trilinos/install/spack/lib/spack/spack/concretize.py", line 514, in adjust_target
    return next(self._adjust_target_answer_generator)
  File "/home/trilinos/install/spack/lib/spack/spack/concretize.py", line 507, in _make_only_one_call
    yield self._adjust_target(spec)
  File "/home/trilinos/install/spack/lib/spack/spack/concretize.py", line 549, in _adjust_target
    current_target.optimization_flags(spec.compiler)
  File "/home/trilinos/install/spack/lib/spack/spack/architecture.py", line 209, in optimization_flags
    compiler_version = compiler.version
AttributeError: 'NoneType' object has no attribute 'version'
```

**Comment by adamjstewart** [comment]
What's the output of `spack config get compilers`?

**Comment by jwillenbring** [comment]
```console
# spack config get compilers
compilers:
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77:
      fc:
    operating_system: ''
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8.5
```

**Comment by alalazo** [comment]
@jwillenbring The `operating_system` attribute looks suspicious and is probably cause of trouble (even though we could definitely do better with error messages in this case). Next output requested:
```console
$ spack arch
``` 
:slightly_smiling_face:

**Comment by jwillenbring** [comment]
OK, so we might be getting on the right track

```console
# spack arch
linux--skylake_avx512
```

```console
# cat /etc/os-release
cat: /etc/os-release: No such file or directory
```

However, using a different user on the same system, one that I was also able to use to install something simple through Spack now, I got

```console
# cat /etc/os-release
NAME="CloudLinux"
VERSION="7.7 (Valery Bykovsky)"
ID="cloudlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="7.7"
PRETTY_NAME="CloudLinux 7.7 (Valery Bykovsky)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:cloudlinux:cloudlinux:7.7:GA:server"
HOME_URL="https://www.cloudlinux.com/"
BUG_REPORT_URL="https://www.cloudlinux.com/support"
```

So I am going to try to ping the sysadmins to see why the first user cannot see this file. I did not use sudo or anything for the second user.

**Comment by jwillenbring** [comment]
OK, so the issue is that the user I am trying to use for the spack installation does not have admin privileges on the machine. On this machine, admin is needed to see that file. Any advice?

**Comment by scheibelp** [comment]
`spack arch` makes use of 3rd-party library to do detection, and that library uses `/etc/os-release`; the library is vendored in `lib/spack/external/distro.py`. Generally I think modifying the vendored libs is best avoided and I'm not sure how we would anyhow, so I think the best approach is to figure out how to tell Spack what the OS is.

I think the most-reasonable short term solution is manual: if you explicitly specify the arch (including the OS) in `spack spec`/`spack install` etc. then it shouldn't need to call out to the 3rd-party library to determine this info. You could add some config to `packages.yaml` to avoid specifying this on the command line:

```
packages:
  all:
    arch=linux-rhel7-x86_64
```

(since you're doing this manually it's not required, but you may want to replace "rhel7" with the actual OS for sanity purposes)

You would also have to update your `compilers.yaml` file to fill in the appropriate OS.

Could you mention whether that works for you?

**Comment by alalazo** [comment]
We have a workaround for this, and am not sure we want to deal with systems that prevent `/etc/os-release` to be read :worried:
