### ISSUE TITLE
Installation issue: py-protobuf

### ISSUE THREAD

**Issue by rblake-llnl** [spack/spack#14528]
### Steps to reproduce the issue

```console
$ spack install py-protobuf@3.11.0+cpp^protobuf@3.7.1 

     79    /usr/WS2/blake14/spack/lib/spack/env/gcc/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I. -I../src -I/usr/WS2/bla
           ke14/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/python-3.7.2-hjq7r62afhtjaulxqp47ncqzcebi5xis/include/python3.7m -c google/protobuf/pyext/repeate
           d_composite_container.cc -o build/temp.linux-x86_64-3.7/google/protobuf/pyext/repeated_composite_container.o -Wno-write-strings -Wno-invalid-offseto
           f -Wno-sign-compare -Wno-unused-variable -std=c++11
  >> 80    google/protobuf/pyext/repeated_composite_container.cc:49:10: fatal error: google/protobuf/stubs/map_util.h: No such file or directory
     81     #include <google/protobuf/stubs/map_util.h>
     82              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     83    compilation terminated.
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux 3.10.0 SMP x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Red Hat Enterprise Linux Server release 7.7 (Maipo)
``` 

### Additional information

Reading the source, the py-protobuf is trying to read a header file that doesn't exist in that version of protobuf.  This implies that the two packages are linked somehow.

Reading the equivalent debian packages, it seems py-protobuf and protobuf come from the same [source package](https://packages.debian.org/source/sid/protobuf).  Does this imply that protobuf and py-protobuf should be merged?

**Comment by scheibelp** [comment]
> Does this imply that protobuf and py-protobuf should be merged?

Generally not: there are several instances of `foo` and `py-foo` packages; there are also instances of packages that have a `+python` variant (generally that's if the package builds the Python libs itself though).

My guess is that `py-protobuf` needs to constrain itself to use a specific version of `protobuf` that contains the needed header. If you leave the `protobuf` version unconstrained does the install complete? Perhaps that is not helpful if you need those specific versions (in which case: I'm curious if there's a reason you were expecting them to work together).

**Comment by scheibelp** [comment]
@rblake-llnl have to had a chance to look into this?

**Comment by rblake-llnl** [comment]
- I encountered this issue when I tried to install py-protobuf, after having previously setup protobuf months ago in the same spack environment.  This means that, by default, installing py-protobuf has incorrect dependencies.
- The spack dependencies for these packages do not require that these version numbers be identical. IIRC they don't even have the same enumeration of versions in both spack packages.
- I talked to @becker33 about this, and he suggested that possibly something could be added to make py-protobuf version depend on specific versions of protobuf.  If the packages are kept separate, such a situation requires manually enumerating all possible versions and keeping them in sync between the packages.
- I went through the commit history of the repo, and protobuf/ py-protobuf should only work together if they have the same version number exactly.  
- In debian, the package for protobuf also builds the python package, just as you described.
- The python source package for py-protobuf in pip is what you get when running the "make python" or equivalent package in the protobuf package.

**Comment by adamjstewart** [comment]
@rblake-llnl is this still an issue on develop?

**Comment by rblake-llnl** [comment]
(Just got back from vacation)

Yes, from my reading of the packages nothing has been fixed in develop yet.  

I went through the `protobuf` source code and confirmed that `py-protobuf` and `protobuf` have to be at the same version numbers to avoid linking/compiling errors.  

The easiest way to fix this might be to somehow access the `protobuf` package class, somehow extract all the version numbers, and then add explicit dependencies for `py-protobuf`, something like:

```
    for version in protobuf_versions:
        depends_on('protobuf@{}'.format(version), when='@{}'.format(version))
```

I don't think that `protobuf-c` has the same problem.

I also might look into removing the +cpp clause here in ```py-protobuf```:
```
    @when('+cpp')
    def setup_build_environment(self, env):
        protobuf_dir = self.spec['protobuf'].libs.directories[0]
        env.prepend_path('LIBRARY_PATH', protobuf_dir)
```

I'd need to dig into the py-protobuf make system, but I'm curious what it does by default for `~cpp`.  Does it build it's own protobuf? Does it use whatever it can find installed on the system? If the answer is yes to either of these, I don't think that's desired behavior from spack's point of view.

**Comment by rblake-llnl** [comment]
Another solution might be to have the protobuf package to add a +python option, and just have py-protobuf be a do-nothing class that depends on protobuf+python.

**Comment by adamjstewart** [comment]
The matching versions thing is definitely easy to solve (I don't know of a way to extract this automatically, we would have to explicitly list them). Don't know much about your other questions though.

**Comment by adamjstewart** [comment]
Just checking back in on this. Should we make `py-protobuf` always depend on `protobuf` in order to ensure that the versions match?

**Comment by rblake-llnl** [comment]
That would be good. I've been fixing it manually by pinning the versions of protobuf manually for the last two years.

protobuf and py-protobuf should always be linked to compatible versions. IIRC it has gotten more complicated with some of the new protobuf numbering schemes.
