### ISSUE TITLE
patchelf trying to relocate static binaries when installing from buildcache

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#14541]
I'm trying to install `pdt` from buildcache and I get this message:

```
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
==> Error: Command exited with status 1: '/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/patchelf-0.10-jsttikjc3pizbwk5sa3rr7ywhacgboyy/bin/patchelf' '--print-rpath' '/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/pdt-3.25.1-qn7v7q63nj4dxruluce7m2bqk4xatel2/x86_64/bin/taucpdisp'
```

Should there be some sort of check to prevent patchelf from trying to relocate static binaries?

**Comment by adamjstewart** [comment]
@gartung

**Comment by gartung** [comment]
@eugeneswalker what does `file -b -h /spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/pdt-3.25.1-qn7v7q63nj4dxruluce7m2bqk4xatel2/x86_64/bin/taucpdisp' report as the file type?

**Comment by gartung** [comment]
Correction run
`file -b -h --mime-type /spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/pdt-3.25.1-qn7v7q63nj4dxruluce7m2bqk4xatel2/x86_64/bin/taucpdisp'

**Comment by gartung** [comment]
From the path I would assume that taucpdisp is an executable not a static library. 
That should be a non-fatal error. I just print it for info.

https://github.com/spack/spack/blob/7a61d1dbd1b7c16f65c03aab28619d581b28fe7c/lib/spack/spack/relocate.py#L103

**Comment by gartung** [comment]
If that is causing your pipeline to abort because it see the word Error I can remove the printing of the error message.

**Comment by gartung** [comment]
There is no way to know _apriori_ that an executable is linked fully static
https://github.com/spack/spack/blob/7a61d1dbd1b7c16f65c03aab28619d581b28fe7c/lib/spack/spack/relocate.py#L702

**Comment by eugeneswalker** [comment]
pipeline running fine, not causing aborts, just been seeing the message thought it was a problem. thanks!
