### ISSUE TITLE
spack env create myenv spack.yaml -- broken?

### ISSUE THREAD

**Issue by odoublewen** [spack/spack#14554]
I have been using Spack happily for a few years now, and today I decided to try out spack  environments, which are new to me.  I'm not sure if this issue is a bug report or just a request to improve the documentation.

I want to be able to create and environment, install some software, and then copy the `spack.yaml` and/or `spack.lock` files to another system, and reproducibly build the same environment.

I'm starting from a clean slate:
```shell
$ git clone https://github.com/spack/spack.git
$ export SPACK_ROOT="$(pwd)/spack"
$ source "${SPACK_ROOT}/share/spack/setup-env.sh"
```

Here is my simple `spack.yaml`
```yaml
spack:
  specs:
    - python@3.7.6
    - bwa@0.7.17
    - flash@1.2.11
    - fastqc@0.11.7
    - py-multiqc@1.7
    - rabbitmq@3.6.15
    - postgresql@11.2
  view: true
```

The [docs](https://spack.readthedocs.io/en/latest/environments.html#creating-a-named-environment) say:

> Spack Environments can also be created from either a `spack.yaml` manifest or a `spack.lock` lockfile. To create an Environment from a `spack.yaml` manifest:
> ```
> $ spack env create myenv spack.yaml
> ```
> To create an Environment from a spack.lock lockfile:
> ```
> $ spack env create myenv spack.lock
> ```

Based on this, I assume the `spack env create myenv spack.yaml` will create an environment named `myenv`, copy the spec (or lock) file into it, **and install the packages**.  However, when I try it, all that happens is:

```
$ spack env create myenv spack.yaml 
==> Updating view at /home/user/spack/var/spack/environments/myenv/.spack-env/view
==> Created environment 'myenv' in /home/user/spack/var/spack/environments/myenv
```

This takes less than 1 second, and nothing is installed.  I get exactly the same behavior when I try using the `spack.lock` file.

Am I misunderstanding the point of this command?  Is there a follow-on command to get All the Things installed?  If so, perhaps this should be added to the above documentation.  Apologies in advance if I am being dense and missing something.

BTW, I notice that the path `/home/user/spack/var/spack/environments/myenv` (where spack claimed it was "updating view") does not contain any `.spack-env` dir.  All that is there is a copy of the yaml file:
```
ls -a /home/user/spack/var/spack/environments/myenv/
.  ..  spack.yaml
```

I am using spack at the current HEAD of develop:  cacd57d3401c48490870df2a9c1b7ab51d0e5065

**Comment by adamjstewart** [comment]
`spack env create` _creates_ an environment, to install it run `spack install`. You may also need to _activate_ the environment in-between, but I don't use Spack Environments this way so I'm not sure.

**Comment by odoublewen** [comment]
(Aha -- now I am remembering, I did try that last night, but got an error, so I thought I must be doing something wrong.  (As an aside, I am offering a small PR to add this small detail to the Environment docs, for folks like me who need a little hand-holding :)  Thanks @adamjstewart for that.

Now, about that error -- I think I did find some kind of obscure bug.  Here's what happens when I tried to do it last night:

```
$ source "${SPACK_ROOT}/share/spack/setup-env.sh"
$ spack env create myenv /path/to/my/spack.yaml"
$ spack env activate myenv
$ spack install -v
==> Installing environment myenv
==> Installing libiconv
==> Searching for binary cache of libiconv
==> No binary for libiconv found: installing from source
==> Error: [Errno 22] Invalid argument: '/net/foobar.abcd.stuffdev.net/ifs/stuff/home/username/myenv/spack/opt/spack/linux-ubuntu18.04-sandybridge'
```

I had to obfuscate the last line there, because the path is a network drive (NFS I think) that contains company identifying info.   On a hunch, today, when I read your reply, I tried again but this time I did it in `/tmp` (so, not on the network drive).  Exactly the same sequence of commands, and it works fine.

Not sure if this has to do with the length of the path (I doubt it) or the fact that it is a NFS drive, or the way the path is symlinked:

```
$ echo $HOME
/stuff/home/username
$ ls -l /stuff
lrwxrwxrwx 1 root root 40 Jul 26 20:01 /stuff -> /net/foobar.abcd.stuffdev.net/ifs/stuff
```

The weird thing is that the environment creation, activation, and package install works find if I do it all as command line actions (i.e., not using the yaml/lock files). 

I'll keep playing around with it and report back any findings.

**Comment by odoublewen** [comment]
Actually, the error I am encountering doesn't seem to be due to spack env at all.  Some weird interaction with the network filesystem and spack.  If/when I can isolate the error I'll open a new issue.  Feel free to close this one and please consider my small contribution to the docs, it would have made things clearer for me.  Thanks.

**Comment by hartzell** [comment]
It's a different error, but I wonder if you're tripping on something similar to this issue describing problems [setting the `setgid` bit on directories](https://github.com/spack/spack/issues/14425), with a pending PR #14479?

Based on things I've heard, I think that your `.../ifs/...` directory is served by an Isilon, which has a wide range of knobs that might control such things
