### ISSUE TITLE
zsh unit tests failing on develop

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#14560]
The `zsh` unit tests are failing on develop. If you look at https://travis-ci.org/spack/spack/jobs/639262160, you'll see:
```
Testing setup-env.sh with zsh5
---------------------------------
'which spack' succeeds ... SUCCESS

...

Testing activate and deactivate together
---------------------------------
Testing 'spack env activate spack_test_env'
'SPACK_ENV' is set ... SUCCESS
Testing 'spack env deactivate'
'SPACK_ENV' is not set ... FAIL
SPACK_ENV was set:
    SPACK_ENV
Testing 'spack env activate spack_test_env'
'SPACK_ENV' is set ... SUCCESS
Testing 'despacktivate'
'SPACK_ENV' is not set ... FAIL
SPACK_ENV was set:
    SPACK_ENV
Testing 'spack env activate --prompt spack_test_env'
'SPACK_ENV' is set ... SUCCESS
'SPACK_OLD_PS1' is set ... SUCCESS
Testing 'despacktivate'
'SPACK_ENV' is not set ... FAIL
SPACK_ENV was set:
    SPACK_ENV
'SPACK_OLD_PS1' is not set ... FAIL
SPACK_OLD_PS1 was set:
    SPACK_OLD_PS1
Removing test environment before exiting.
==> Error: No environment is currently active.
==> Successfully removed environment 'spack_test_env'
Cleanup
---------------------------------
Removing test packages before exiting.
==> Successfully uninstalled b@1.0%gcc@4.8 arch=linux-ubuntu14.04-haswell/wvu3a4j
==> Successfully uninstalled a@2.0%gcc@4.8+bvv foo=bar foobar=bar arch=linux-ubuntu14.04-haswell/nv64iat
44 tests succeeded.
4 tests failed.
FAIL
```
I think part of the problem is that we are detecting the shell as `zsh5`, not `zsh`. Also, the unit tests are failing, but Travis passes, and I'm not sure why.  We have `bash -e` in the shebang, so it _should_ exit immediately with the proper exit code if one of the commands fails.

@tgamblin

**Comment by adamjstewart** [comment]
@alalazo it looks like #13950 introduced the `zsh` -> `zsh5` change. We're now incorrectly determining the name of the shell in Spack for zsh, which means checks like `if [ "$_sp_shell" = zsh ]` in `setup-env.sh` won't work properly. See the difference between https://travis-ci.org/spack/spack/jobs/625762709 and https://travis-ci.org/spack/spack/jobs/625972037 to confirm this.

Unfortunately, this didn't introduce the failing zsh unit tests, they were failing before this. Still trying to understand why that is the case.

As for why a failing shell script test didn't cause the Travis tests to fail, we could try an explicit `set -e` instead of using `-e` in the shebang.

**Comment by adamjstewart** [comment]
> As for why a failing shell script test didn't cause the Travis tests to fail, we could try an explicit set -e instead of using -e in the shebang.

Tried this locally, and both should be equivalent, at least for Bash 5. I'm not sure why this doesn't fail. We explicitly set the exit code in `test-framework.sh` upon exit. I wonder if there's a bug in that logic.

**Comment by alalazo** [comment]
>  We're now incorrectly determining the name of the shell in Spack for zsh, which means checks like if [ "$_sp_shell" = zsh ] in setup-env.sh won't work properly. 

Would it be a viable solution to substitute those checks with something like:
```shell
if [ -z "${_sp_shell##*zsh*}" ]
```
? Hopefully checking if `zsh` is in `_sp_shell` is not too fragile...

**Comment by adamjstewart** [comment]
The problem is that other files use `$_sp_shell` to determine things like tab completion file extension. I think it would be better to strip any numbers from the procfs shell name. Or move procfs detection below BASH_NAME and ZSH_NAME.

**Comment by adamjstewart** [comment]
> Unfortunately, this didn't introduce the failing zsh unit tests, they were failing before this. Still trying to understand why that is the case.

Unfortunately, these tests have never passed for zsh ever since @tgamblin introduced them in #11942, see: https://travis-ci.org/spack/spack/jobs/560820464?utm_medium=notification&utm_source=github_status

**Comment by becker33** [comment]
These tests no longer fail.
