### ISSUE TITLE
build issues with py-torch

### ISSUE THREAD

**Issue by glennpj** [spack/spack#14576]
There are a few issues with building py-torch. 

1. The package recipe sets `+mkldnn` by default and depends on `intel-mkl-dnn`. However, the build actually builds the in-tree mkldnn
```
[265/2458] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_postgemm_gru.cpp.o
[292/2458] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_postgemm_gru_lbr.cpp.o
[313/2458] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_postgemm_lstm.cpp.o
[524/2458] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_postgemm_rnn.cpp.o
[905/2458] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/rnn_utils.cpp.o
[986/2458] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_rnn.cpp.o
[994/2458] Linking CXX static library lib/libmkldnn.a
```
2. When `~caffe2` is set, `BUILD_CAFFE2_MOBILE` is still set to ON. This may be okay but not sure if that was the intent of the caffe2 variant.
3. The build fails when `+caffe2` is set.
```console
3 errors found in build log:
     2312     #warning "host_defines.h is an internal header file and must not be used directly.  This file will be removed in a
             future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
     2313      ^~~~~~~
     2314    /opt/packages/gpjohnsn/apps/linux-centos7-broadwell/gcc-8.3.0/eigen-3.3.7-byl22ahrj5dv4lmcxzh3iudtqor3q24k/include/e
             igen3/Eigen/src/Core/arch/CUDA/Half.h(302): warning: calling a __host__ function from a __host__ __device__ function
              is not allowed
     2315
     2316    /opt/packages/gpjohnsn/apps/linux-centos7-broadwell/gcc-8.3.0/eigen-3.3.7-byl22ahrj5dv4lmcxzh3iudtqor3q24k/include/e
             igen3/Eigen/src/Core/arch/CUDA/Half.h(305): warning: calling a __host__ function from a __host__ __device__ function
              is not allowed
     2317
  >> 2318    /opt/packages/gpjohnsn/apps/linux-centos7-broadwell/gcc-8.3.0/eigen-3.3.7-byl22ahrj5dv4lmcxzh3iudtqor3q24k/include/e
             igen3/Eigen/src/Core/arch/CUDA/PacketMathHalf.h(233): error: no suitable conversion function from "__half" to "unsig
             ned short" exists
     2319
  >> 2320    /opt/packages/gpjohnsn/apps/linux-centos7-broadwell/gcc-8.3.0/eigen-3.3.7-byl22ahrj5dv4lmcxzh3iudtqor3q24k/include/e
             igen3/Eigen/src/Core/arch/CUDA/PacketMathHalf.h(267): error: no suitable conversion function from "__half" to "unsig
             ned short" exists
     2321
     2322    2 errors detected in the compilation of "/tmp/tmpxft_0000c7f1_00000000-13_rsqrt_op.compute_35.cpp1.ii".
  >> 2323    CMake Error at torch_generated_rsqrt_op.cu.o.Release.cmake:281 (message):
     2324      Error generating file
     2325      /dev/shm/gpjohnsn/spack-stage-py-torch-1.4.0-23jvdwla5padn5pcam62k6rzovczeyhe/spack-src/build/caffe2/CMakeFiles/to
             rch.dir/operators/./torch_generated_rsqrt_op.cu.o
     2326
     2327
     2328    [1082/2458] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/operators/torch_generated_resize_3d_op.cu.o
     2329    [1083/2458] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorIndex
             .cu.o 
```

---

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux argon-build.hpc 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.5.1804 (Core)
```

**Comment by adamjstewart** [comment]
1. Yes, this is a known issue with `py-torch`, we need to find a way to use external installations of packages instead of vendored copies or downloading dependencies
2. The `py-torch` package doesn't set that variant, should it?
3. This looks like a `py-torch` bug, not a Spack bug. You're probably better off reporting it to them.

**Comment by glennpj** [comment]
1. Should we depend on intel-mkl-dnn if it is not actually used?
2. There is a `caffe2` variant for the operators
```
variant('caffe2', default=False, description='Enables Caffe2 operators build') 
```
It is not clear whether that should cover BUILD_CAFFE2_MOBILE as well. From your comment, I guess not.

**Comment by glennpj** [comment]
For 3, you are probably right. I know this spack package was recently updated so thought it could be my environment. In any event, it likely makes sense to mark building with `caffe2` as broken as it takes a significant amount of time compiling before it fails.

**Comment by adamjstewart** [comment]
1. In theory, no, but I would consider the fact that we aren't linking to an external `intel-mkl-dnn` to be the bug, not that we have an extra unneeded dependency
2. I'm not sure either, depends on if you want to add an extra variant
3. I've never built/needed `py-torch+caffe2` before so I'm fine with that

**Comment by glennpj** [comment]
For mkldn, it does not look like a bug but rather intentional. From `.../spack-src/cmake/Modules/FindMKLDNN.cmake`
```
SET(IDEEP_ROOT "${PROJECT_SOURCE_DIR}/third_party/ideep")
SET(MKLDNN_ROOT "${IDEEP_ROOT}/mkl-dnn")
```
Also, MKLDNN_HOME is not a variable that is used since version 0.4.1.

For caffe2, the package needs to set TORCH_CUDA_ARCH_LIST with values from the cuda_arch variant. I am getting ready to work up a PR to fix building caffe2 but I am not sure what to do about mkldnn. That is still a variant but it does not depend on the spack package, I am guessing since version 0.4.1.

**Comment by glennpj** [comment]
I think the best course is to put constraints for mkldnn to reflect what I am seeing.
