### ISSUE TITLE
Installation issue: pdt

### ISSUE THREAD

**Issue by khuck** [spack/spack#14588]
### Steps to reproduce the issue

```console
$ spack install pdt%gcc@7.3.0
```
PDT will install fine, but later TAU will fail to build because PDT defaulted to XL compliers on ppc64le.

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux cyclops 4.14.0-115.10.1.el7a.ppc64le #1 SMP Wed Jun 26 09:32:17 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
$ lsb_release -d
Description:	Red Hat Enterprise Linux Server release 7.6 (Maipo)
``` 

### Additional information

I have a patch for this issue, will submit a PR subsequently...

**Comment by scheibelp** [comment]
Thanks for reporting the bug and also fixing it!
