### ISSUE TITLE
Spack install gpgme bug

### ISSUE THREAD

**Issue by audreystott** [spack/spack#14605]
While installing gpgme for charliecloud+builder, I ran into the following error for gpgme:

gpg: can't connect to the agent: File name too long

### Steps to reproduce the issue

```console
$ spack install gpgme
$ spack install charliecloud+builder
```

### Error Message

If Spack reported an error, provide the error message. If it did not report an error
but the output appears incorrect, provide the incorrect output. If there was no error
message and no output but the result is incorrect, describe how it does not match
what you expect. To provide more information you might re-run the commands with 
the additional -d/--stacktrace flags:
```console
$ spack -d --stacktrace install gpgme
```
that activate the full debug output. 

gpg: can't connect to the agent: File name too long

### Information on your system

This includes:

 1. Platform: SUSE Linux Enterprise Server 12 SP3

**Comment by scheibelp** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847206 suggests that `GNUPGHOME` needs to be shorter. If you can include the output when running with `spack -d...` that might help me figure out how that could be achieved.

**Comment by audreystott** [comment]
Hi Peter, thanks for your reply. Here's the part of the output log where it starts to show the errors: 

make[1]: Leaving directory '/tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/src'
Making all in tests
make[1]: Entering directory '/tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests'
Making all in gpg
make[2]: Entering directory '/tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests/gpg'
echo no-force-v3-sigs > ./gpg.conf
echo pinentry-program /tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests/gpg/pinentry > ./gpg-agent.conf
GNUPGHOME=/tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests/gpg LC_ALL=C GPG_AGENT_INFO= top_srcdir=../.. gpgconf --kill all
echo disable-scdaemon >> ./gpg-agent.conf
/usr/bin/mkdir -p ./private-keys-v1.d
for k in 13CD0F3BDF24BE53FE192D62F18737256FF6E4FD 76F7E2B35832976B50A27A282D9B87E44577EB66 A0747D5F9425E6664F4FFBEED20FBCA79FDED2BD 13CBE3758AFE42B5E5E2AE4CED27AFA455E3F87F 7A030357C0F253A5BBCD282FFC4E521B37558F5C; do \
          cp ./$k private-keys-v1.d/$k.key; \
        done
echo x > ./gpg-sample.stamp
GNUPGHOME=/tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests/gpg LC_ALL=C GPG_AGENT_INFO= top_srcdir=../.. gpg --batch --no-permission-warning \
               --import ./pubdemo.asc
gpg: keybox '/tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests/gpg/pubring.kbx' created
gpg: /tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests/gpg/trustdb.gpg: trustdb created
gpg: key 2D727CC768697734: public key "Alfa Test (demo key) <alfa@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key FE180B1DA9E3B0B2: public key "Bob (demo key)" imported
gpg: can't connect to the agent: File name too long
gpg: key 413F4AF31AFDAB6C: public key "Charlie Test (demo key) <charlie@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key EBA9F240EB9DC9E6: public key "Delta Test (demo key) <delta@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 318C1FAEFAEF6D1B: public key "Echelon (demo key)" imported
gpg: can't connect to the agent: File name too long
gpg: key D4BF57F37372E243: public key "Foxtrot Test (demo key) <foxtrot@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 168410A48FC282E6: public key "Golf Test (demo key) <golf@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 13DB965534C6E3F1: public key "Hotel Test (demo key) <hotel@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 1FE8FC6F04259677: public key "India Test (demo key) <india@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 0C820C71D2699313: public key "Juliet Test (demo key) <juliet@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key AD1B0FAD43C2D0C7: public key "Kilo Test (demo key) <kilo@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 37CAB51FB79103F8: public key "Lima Test (demo key) <lima@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key BE794852BE5CF886: public key "Mallory (demo key)" imported
gpg: can't connect to the agent: File name too long
gpg: key 25B00FD430CEC684: public key "November Test (demo key) <november@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 5F6356BA6D9732AC: public key "Oscar Test (demo key) <oscar@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 5D15E01D3FF13206: public key "Papa test (demo key) <papa@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 1C67EC133C661C84: public key "Quebec Test (demo key) <quebec@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 3BDBEDB1777FBED3: public key "Romeo Test (demo key) <romeo@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key A5E67F7FA3AE3EA1: public key "Sierra Test (demo key) <sierra@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 58CB9A4C85A81F38: public key "Tango Test (demo key) <tango@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key A94C0F75653244D6: public key "Uniform Test (demo key) <uniform@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 47AF4B6961F04784: public key "Victor Test (demo key) <victor@example.org>" imported
gpg: can't connect to the agent: File name too long
gpg: key DEF0F7B8EC67DBDE: public key "Whisky Test (demo key) <whisky@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 8979A6C5567FB34A: public key "XRay Test (demo key) <xray@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 9EEF34CD4B11B25F: public key "Yankee Test (demo key) <yankee@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: key 6BC4778054ACD246: public key "Zulu Test (demo key) <zulu@example.net>" imported
gpg: can't connect to the agent: File name too long
gpg: Total number processed: 26
gpg:               imported: 26
Makefile:1107: recipe for target 'pubring-stamp' failed
make[2]: *** [pubring-stamp] Error 2
make[2]: Leaving directory '/tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests/gpg'
Makefile:694: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/astott/spack-stage/spack-stage-gpgme-1.12.0-drfghcow7tgyo2vml2rjsdfdog27hfqh/spack-src/tests'
Makefile:520: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by nicholas-sly** [comment]
I've also encountered this issue when trying to build Charliecloud+builder inside of a base centos:7 container.  As a short-term patch, installing the bzip2 package using yum and pointing Spack at that has worked.  As a long-term solution, I'm working on getting the lbzip2 package into working condition (should be finished), and then working on propagating this up to gpgme as dependencies (WIP).  I'll create a merge request and mark it as a work-in-progress to reference this issue.

**Comment by audreystott** [comment]
Thanks Nicholas. I have used the WIP fix by @j-ogas [here](https://github.com/hpc/charliecloud/pull/636), and can confirm it is working for me on SUSE Linux. Will check in later again after the long-term solution is done. For now happy that Charliecloud can be installed via Spack :)
