### ISSUE TITLE
Compiling with a specific version of GCC

### ISSUE THREAD

**Issue by azukaitis** [spack/spack#14656]
I am trying to create a spack package.py for my application that depends on a specific version of gcc.  When it goes to configure, it uses the system install of gcc and not the spack depends_on compiler.  I'm working off of devel spack.  

```
from spack import *
class Foo(CMakePackage):
depends_on('gcc@6.4.0')
```

## other notes
The gcc@6.4.0 I am using was built with at system gcc 8.3.0.  The gcc@6.4.0 is in my compilers.yaml file.

**Comment by scheibelp** [comment]
> I am trying to create a spack package.py for my application that depends on a specific version of gcc.

I assume by this that you mean you only want to build this package with `gcc@6.4.0`. This is currently not possible to express with dependency constraints; the `depends_on` constraint doesn't affect what compiler you build with other than that Spack typically tries to build a package and its dependencies using the same compiler.

There is a `conflicts` statement that can be used to express some compiler constraints but not to the degree you desire here: for example you can say `conflicts("%intel")` to express that the package cannot be built with the Intel compiler, but you can't add a single constraint that requires building with a single compiler and no other (Spack doesn't have an inverse operator in the expression syntax).

As of now, if you want to build your package specifically with `gcc@8.3.0` you will have to either express this on the command line (`spack install foo%gcc@8.3.0`) or update the package configuration in `packages.yaml` (see the config sections in the docs). If you want to prevent other users from attempting to build with a compiler other than `gcc@6.4.0` you can check these traits in your `Package.install` method and throw an error (which is semantically similar to the `conflicts` statement provided by Spack).

**Comment by scheibelp** [comment]
@azukaitis is https://github.com/spack/spack/issues/14656#issuecomment-579534096 sufficient information to resolve your issue?
