### ISSUE TITLE
Installation issue: suite-sparse@5.6.0 %gcc@7.4.0 linux-ubuntu18.04-x86_64

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#14654]
I'm attaching the concrete `spec.yaml` for the precise version of `suite-sparse` that failed to build (I had to add a `.txt` extension before GitHub would upload it).  I'm also attaching the spack build output and environment for complete details.  

But to summarize the issue:

```
/builds/scott/spack-tutorial-container/spack/lib/spack/env/gcc/gcc -O3 -fPIC -fno-common -fexceptions   -O3 -fexceptions -fPIC  -I../../include -o amd_simple amd_simple.c -L/builds/scott/spack-tutorial-container/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/suite-sp
arse-5.6.0-f252hznmnfusgiezet6mjihe7jyl7u33/lib -L../../lib -lamd -lsuitesparseconfig -lm -lrt -Wl,-rpath=/builds/scott/spack-tutorial-container/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/suite-sparse-5.6.0-f252hznmnfusgiezet6mjihe7jyl7u33/lib
./amd_demo > my_amd_demo.out
./amd_demo: error while loading shared libraries: libamd.so.2: cannot open shared object file: No such file or directory
Makefile:30: recipe for target 'amd_demo' failed
make[2]: *** [amd_demo] Error 127
make[2]: *** Waiting for unfinished jobs....
```

For the  time being, I have preferred version `5.3.0` as it builds on the same system without any problems.

Please let me know if I can provide more information.

[spack-build-out.txt](https://github.com/spack/spack/files/4124398/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/4124399/spack-build-env.txt)
[suite-sparse.yml.txt](https://github.com/spack/spack/files/4124410/suite-sparse.yml.txt)

**Comment by scottwittenburg** [comment]
@becker33 @eugeneswalker @opadron I filed this issue following our discussion on slack earlier today.  If you know who's primarily responsible for maintaining this package, please feel free to ping them.

**Comment by paulbry** [comment]
I've experience the same issue with `%gcc@8.3.0`

**Comment by alalazo** [comment]
Verified a similar behavior. Maybe relates to #10313

**Comment by eugeneswalker** [comment]
I'm seeing this also, with `suite-sparse@5.6.0` and gcc@7.4.0 on tip of develop as of 12-Feb-2020

**Comment by balay** [comment]
I'm seeing this issue on multiple builds Appears to be triggered by #14547

`^suite-sparse@5.3.0` is my fallback

**Comment by eugeneswalker** [comment]
@mathsen  - can you help with this? any ideas? Also see similar issue: https://github.com/spack/spack/issues/15184
