### ISSUE TITLE
spack: remote build install failure

### ISSUE THREAD

**Issue by hainest** [spack/spack#14715]
I'm doing builds of many packages on Lassen@LLNL, so I'm using the batch partition to not overburden the login node and also to be able to use all cores to do the builds more quickly. However, the packages that are installed while running on the batch node are not reflected in the Spack repo on the head node even though the build node uses the Spack repo from the head node to do its work.

    $ git log --oneline -1
        412c33611 (HEAD -> develop, origin/develop, origin/HEAD) boost: Add versions 1.71.0 and 1.72.0, use Clang toolset on Darwin (#14678)

    $ spack compiler list
        ==> Available compilers
        -- clang rhel7-ppc64le ------------------------------------------
        clang@8.0.1

        -- gcc rhel7-ppc64le --------------------------------------------
        gcc@7.3.1  gcc@4.9.3  gcc@4.8.5

        -- xl rhel7-ppc64le ---------------------------------------------
        xl@16.1

        -- xl_r rhel7-ppc64le -------------------------------------------
        xl_r@16.1

    $ cat build.sh
        #!/bin/bash
        # This is abbreviated for simplicity
        source spack/share/spack/setup-env.sh
        $HOME/spack/bin/spack -d install -v -j32 -y tau %gcc@7.3.1 >tau.gcc.log 2>&1

    $ bsub -nnodes 1 -q pbatch -W "00:30" sh ./build.sh

The intallation log shows

    ==> [2020-01-31-16:09:11.912103] Successfully installed tau
      Fetch: 0.54s.  Build: 35.81s.  Total: 36.35s.
    [+] /usr/WS1/haines8/ecp/spack/opt/spack/linux-rhel7-power9le/gcc-7.3.1/tau-2.28.2-eeu6pilexjv24535jac2bfjnggz7ceca

Indeed, from the login node, I see

    $ ll /usr/WS1/haines8/ecp/spack/opt/spack/linux-rhel7-power9le/gcc-7.3.1/tau-2.28.2-eeu6pilexjv24535jac2bfjnggz7ceca/bin/taucc
      -rwxr-xr-x 1 haines8 haines8 7010 Jan 31 16:08 /usr/WS1/haines8/ecp/spack/opt/spack/linux-rhel7-power9le/gcc-7.3.1/tau-2.28.2-eeu6pilexjv24535jac2bfjnggz7ceca/bin/taucc

So tau installed correctly and is available in the Spack repo on the login node. Yet

    $ spack find
        ==> 33 installed packages
        -- linux-rhel7-power9le / gcc@7.3.1 -----------------------------
        autoconf@2.69    diffutils@3.7     libiconv@1.16        libunwind@2018.10.12  otf2@2.2            xerces-c@3.2.2
        automake@1.16.1  elfutils@0.178    libpciaccess@0.13.5  libxml2@2.9.9         perl@5.30.0         xz@5.2.4
        binutils@2.32    gdbm@1.18.1       libpfm4@4.10.1       m4@1.4.18             pkgconf@1.6.3       zlib@1.2.11
        boost@1.70.0     gettext@0.20.1    libsigsegv@2.12      ncurses@6.1           readline@8.0
        bzip2@1.0.8      hwloc@1.11.11     libtool@2.4.6        numactl@2.0.12        tar@1.32
        cmake@3.16.1     intel-tbb@2019.8  libunwind@1.2.1      openssl@1.1.1d        util-macros@1.19.1

finds no Tau or its installed dependencies.

I've tried other packages with similar results, so it's not an issue specific to Tau.

**Comment by alalazo** [comment]
@hainest Which version of Spack are you using? Also, did you try:
```console
$ spack reindex
```
to see if there were synchronization issues when writing to the JSON DB?

**Comment by hainest** [comment]
>Which version of Spack are you using?

The HEAD was 412c33611. I've since updated to 4accc7840, but no change in behavior.

> Also, did you try: `$ spack reindex` to see if there were synchronization issues when writing to the JSON DB?

I meant to include that in my original post. I checked the database, and there were two installations of tau in there. I manually deleted them, and ran the installation again.

	$ grep -inw tau spack/opt/spack/.spack-db/index.json 

	$ spack find tau
	    ==> No package matches the query: tau

	$ find spack/opt/spack -name "tau*" -type d 

There is definitely no tau installed.

	$ bsub -nnodes 1 -q pbatch -W "00:30" sh ./build.sh

	The log file says

	  ==> [2020-02-04-12:54:12.068481] Successfully installed tau
		Fetch: 0.41s.  Build: 33.68s.  Total: 34.09s.
	  [+] /usr/WS1/haines8/ecp/spack/opt/spack/linux-rhel7-power9le/gcc-7.3.1/tau-2.28.2-eeu6pilexjv24535jac2bfjnggz7ceca

	$ spack find tau
	  ==> No package matches the query: tau

	$ find spack/opt/spack -name "tau*" -type d
	    spack/opt/spack/linux-rhel7-power9le/gcc-7.3.1/tau-2.28.2-eeu6pilexjv24535jac2bfjnggz7ceca
	    * snip *

	$ grep -inw tau spack/opt/spack/.spack-db/index.json 
	    3707:     "tau": {
	    3814:    "path": "/usr/WS1/haines8/ecp/spack/opt/spack/linux-rhel7-power9le/gcc-7.3.1/tau-2.28.2-eeu6pilexjv24535jac2bfjnggz7ceca",

Tau is definitely installed now, but `spack find` can't see it.

	$ spack reindex

	$ spack find tau
	    ==> No package matches the query: tau

	$ grep -inw tau spack/opt/spack/.spack-db/index.json 
	    3707:     "tau": {
	    3814:    "path": "/usr/WS1/haines8/ecp/spack/opt/spack/linux-rhel7-power9le/gcc-7.3.1/tau-2.28.2-eeu6pilexjv24535jac2bfjnggz7ceca",

Reindexing the database has no effect.

**Comment by scheibelp** [comment]
I want to check: this isn't actually distributed is it? It looks like there is one instance of `build.sh` running (and the parallelism comes from `-j`).

**Comment by hainest** [comment]
@scheibelp Yes, the build happens on a single node under parallel make jobs. That node is not the same machine where the Spack repo exists, though they are on a shared file system. I wasn't sure how Spack differentiates between distributed and remote builds, so I labelled it as both. I can update the title, if that would make the issue clearer.

**Comment by scheibelp** [comment]
Thanks yes I think it would make it clearer (I updated the title myself but feel free to edit it further if you think it could be more clear): there is only one instance of Spack running so there shouldn't be any synchronization issue.

**Comment by hainest** [comment]
Using the current HEAD of develop (77fc458d29) and `spack clean`, this is no longer an issue. Closing.
