### ISSUE TITLE
Spack should either show the location of the newly created build cache, or throw error when no -d option

### ISSUE THREAD

**Issue by adamryczkowski** [spack/spack#14719]
It took me over 15 minutes of wasted time to try to find what on Earth happened when I wanted to add a build cache on an existing mirror server using the other, most powerful box.

```
git clone --depth 1 https://github.com/spack/spack
. spack/share/spack/setup-env.sh 
spack bootstrap
spack gpg init
spack gpg create adam adam@mail.com
spack mirror add custom-mirror file://mnt/spack-mirror
spack buildcache create  zlib  #Intention is to write to the /mnt/spack-mirror - the share is mounted rw.
```

It turnes out, that the `zlib` got created in the **local** directory hidden in the arbitrary `build_cache` subfolder. 

Please, consider my experience and modify the `spack buildcache create` option validation :-)

   *   *   *
  
I use spack `0.13.3-935-0c0aba57` on Ubuntu 18.04.4 64 bit

**Comment by alalazo** [comment]
> It took me over 15 minutes of wasted time [ ... ]

The `spack buildcache create` help shows a `-d` flag to select the output directory:
```console
$ spack buildcache create -h
usage: spack buildcache create [-hrfua] [-k key] [-d directory]
                               [--no-rebuild-index] [-y SPEC_YAML] [--no-deps]
                               ...

positional arguments:
  specs                 one or more package specs

optional arguments:
  -h, --help            show this help message and exit
  -r, --rel             make all rpaths relative before creating tarballs.
  -f, --force           overwrite tarball if it exists.
  -u, --unsigned        create unsigned buildcache tarballs for testing
  -a, --allow-root      allow install root string in binary files after RPATH substitution
  -k key, --key key     Key for signing.
  -d directory, --directory directory
                        directory in which to save the tarballs.
  --no-rebuild-index    skip rebuilding index after building package(s)
  -y SPEC_YAML, --spec-yaml SPEC_YAML
                        Create buildcache entry for spec from yaml file
  --no-deps             Create buildcache entry wo/ dependencies
```
That said I think it would be nice to be able to refer to mirrors by name, instead of having to point to their directories explicitly.

**Comment by adamryczkowski** [comment]
Yes, I know that. What took me by surprise is that when no `-d` is given, spack silently creates a folder `build_cache` in the current directory. 

I don't state it is a major bug - it is an issue with ergonomics. Spack usually does not touch the current directory, so when it does, I would expect it to state that explicitely with a message "The module <name> was added to  the  cache in <full path>".

**Comment by tgamblin** [comment]
This is pretty easy to do -- the build cache commands are a bit rougher than some of our others.  We should look into cleaning this up by 0.15, if not earlier.

**Comment by gartung** [comment]
Thanks for the feedback. It was an ad-hoc choice at the time it was implemented and can certainly  be improved.

**Comment by gartung** [comment]
Would it be sufficient to add the output dir to this message?
https://github.com/spack/spack/blob/f2aca86502eded1500489cd13799d8826e6fc9d2/lib/spack/spack/cmd/buildcache.py#L363

**Comment by gartung** [comment]
There was a message telling you where the file is being written to but it got demoted to a debug message
https://github.com/spack/spack/blob/f2aca86502eded1500489cd13799d8826e6fc9d2/lib/spack/spack/cmd/buildcache.py#L360

**Comment by gartung** [comment]
Somebody else complained that buildcache was too verbose so this message got demoted. 
Everybody has an opinion and no one can agree.

**Comment by gartung** [comment]
https://github.com/spack/spack/pull/15090

**Comment by alalazo** [comment]
@gartung My two cents on how I think the cli could be made more user friendly while respecting both user requests:
```console
$ spack buildcache create [options] mirror-name-or-path [specs...]
```
Basically I would remove the `-d` option in favor of a positional argument that could either be a path or the name of a mirror known to Spack. In that way you don't have to show the debug output to tell the user where the binary cache has been created since you forced him to be explicit about that (so it would be fine if it stays as a debug level output). Pinging @opadron since I believe he's working on the `spack mirror` command and I think the two commands should sync with each other.

**Comment by adamryczkowski** [comment]
I like what @alalazo proposed: the creation of the buildcache is a key thing that the `spack buildcache create` and silently proposing the location is misleading. 

By analogy, the solution looks like if `zip` command, when compressing files, would proposed an archive name `my_archive.zip` if user forgot to specify it explicitely.

**Comment by gartung** [comment]
Take a look at #15090. Spack buildcache create with die with a message to specify the output directory with the -d option. I do not know how to distinguish between a missing first positional argument and the remainder which can be specs of hashes.

**Comment by opadron** [comment]
So, the `-d` argument already accepts a named mirror if one is configured.  Unfortunately, the "directory" and "-d" parts were inherited from when only mirrors on local filesystem was a thing and the docs didn't get updated to specify that.

The default behavior of working on $CWD was also inherited, though a default of `$spack/var/spack/cache` is used for many of the other buildcache and mirror commands.  We might also want to review those defaults and consider changing them.

**Comment by alalazo** [comment]
> I do not know how to distinguish between a missing first positional argument and the remainder which can be specs of hashes.

@opadron @gartung I can have a look at how to do it if you agree with the intent. I can also try to modify both `spack mirror` and `spack buildcache`. I think the cli would be better, the only thing we need to consider is that this will not be backward compatible with the current set of flags.

**Comment by opadron** [comment]
@alalazo have a look at the latest iteration (#15090).  I think we're close to a solution that eliminates a lot of potential confusion, while also being backwards compatible!
