### ISSUE TITLE
No way to export a gpg key created with spack gpg create

### ISSUE THREAD

**Issue by adamryczkowski** [spack/spack#14721]
In order to use the signed buildcache I need to import the public key of the server somehow. I can't simply do `spack gpg trust file://mnt/spack-mirror` because for some unexplained in the documentation reason `spack buildcache create` does not put the public key there, even though it uses the corresponding private key to sign the packages it writes.

`spack gpg export` would work, if it exported the public key, not the private.

edit:
I have to add that `gpg` itself with its default keyring is unaware of any of the spack keys, so using for that purpose is far from obvious. `gpg --list-secret-keys` returns nothing.

   *   *   *
  
I use spack `0.13.3-935-0c0aba57` on Ubuntu 18.04.4 64 bit

**Comment by adamryczkowski** [comment]
OK. I tried to run the `spack gpg export` anyway in a hope that it would also export the public key together with the private one. 

To my surprise

```
spack gpg export adam.pub
```

wrote the **public key** and **no private key**!!! 


For the record:

```
$ $ spack gpg --help
usage: spack gpg [-h] SUBCOMMAND ...

handle GPG actions for spack

positional arguments:
  SUBCOMMAND  GPG sub-commands
    verify    verify a signed package
    trust     add a key to the keyring
    untrust   remove a key from the keyring
    sign      sign a package
    create    create a new key
    list      list keys available in the keyring
    init      add the default keys to the keyring
    export    export a secret key

optional arguments:
  -h, --help  show this help message and exit
```

and then

```
$ spack gpg export --help
usage: spack gpg export [-h] location [keys [keys ...]]

positional arguments:
  location    where to export keys
  keys        the keys to export; all secret keys if unspecified

optional arguments:
  -h, --help  show this help message and exit
```

As it can be seen you consistently claim that you do export the *private* key. WTF? Why the documentation is misleading on this? Am I missing something?

**Comment by gartung** [comment]
Afaik only the public portion of the key is exported.

**Comment by gartung** [comment]
You would not want to export your private key.

**Comment by gartung** [comment]
If you want to reuse the private key you need to copy the contents of spack/opt/spack/gpg to a new spack install. You can also use GNUPGHOME=$spack/opt/spack.gpg gpg2 and the correct options to output the private key.

**Comment by gartung** [comment]
@scheibelp Is anything I said incorrect?

**Comment by frankwillmore** [comment]
I'm hitting the same issue when trying to read from buildcache. I can export a package successfully and sign it with ```spack gpg sign``` but when I uninstall the package and try to re-install from buildcache, it fails as:

```
gpg: Can't check signature: No public key
==> Error: Command exited with status 2:
'/usr/bin/gpg2' '--verify' '/tmp/tmp60x97gxw/cray-cnl6-mic_knl-intel-19.0.5.281-spack-dummy-package-master-yrf4hqg5u4eaviw64y3dj7zgn5b6esze.spec.yaml.asc' '/tmp/tmp60x97gxw/cray-cnl6-mic_knl-intel-19.0.5.281-spack-dummy-package-master-yrf4hqg5u4eaviw64y3dj7zgn5b6esze.spec.yaml'
```
If spack is generating a key pair, what do I need to be doing so that it can find its public key?
