### ISSUE TITLE
Environments view remembers non-existing / temporary package

### ISSUE THREAD

**Issue by davydden** [spack/spack#14725]
I have a problem with `view` in envrionments. I was adding a new package and activating/de-activating my environment. I ended up NOT needing the new package. 
But somewhere environment "remembers" that this package exists, so if I switch branches I try to use the environment without the package being available as a part of Spack I get an error"

```
==> Error: Package 'foo' not found
```

`spack reindex` does not help, I tried to remove the corresponding folder from `.spack-env` inside `spack/var/spack/environments/<bar>/` but this does not solve the issue either.

Right now I can only work with my environment if I disable view: `view: false`.

**Comment by scheibelp** [comment]
@davydden can you include the output with `spack -d ... (whatever command you ran to get this error)`?

> I tried to remove the corresponding folder from `.spack-env` inside `spack/var/spack/environments/<bar>/` but this does not solve the issue either.

Which directories did you remove? Was it all of `.spack-env`? I would suspect you may need to manually remove the view to avoid the error, but if you already did that and are still encountering errors that would be good to know.

**Comment by davydden** [comment]
@scheibelp can't reproduce the issue anymore, strange...
