### ISSUE TITLE
externally defined roots are not defined in environments

### ISSUE THREAD

**Issue by bvanessen** [spack/spack#14743]
*Explain, in a clear and concise way, the command you ran and the result you were trying to achieve.

When creating a spack environment if I have an externally defined root such as cmake, it does not show up in the view that is subsequently created.  While it can be created in multiple ways, I encountered this with the PR https://github.com/LLNL/lbann/pull/1414.

Note that @becker33 I gave you a spack.yaml file that has this problem.

### Steps to reproduce the issue

```console
$ spack create env lbann-dev spack.yaml
$ spack activate -p lbann-dev
$ which cmake
...
```

### Error Message

The output of 

```console
$ which cmake
```

points to the system cmake, not the externally defined cmake.

### Information on your system

This includes:

 1. LLNL LC Pascal
 2. spack.yaml file given to @becker33 

-----

We encourage you to try, as much as possible, to reduce your problem to the minimal example that still reproduces the issue. That would help us a lot in fixing it quickly and effectively!

If you want to ask a question about the tool (how to use it, what it can currently do, etc.), try the `#general` channel on our Slack first. We have a welcoming community and chances are you'll get your reply faster and without opening an issue.

Other than that, thanks for taking the time to contribute to Spack!

**Comment by scheibelp** [comment]
Does the `packages.yaml` entry for CMake contain a `paths` entry, or a `modules` entry? Views universally skip adding external packages. That logic could possibly be relaxed to only exclude external packages from the view if they are located in system paths; that fix wouldn't be useful if in your case CMake was exposed via a module file.

**Comment by bvanessen** [comment]
It uses a paths field.

**Comment by scheibelp** [comment]
Would you be able to add here what the `paths` entry looks like for CMake? 

I think this is related to https://github.com/spack/spack/issues/14797

**Comment by scheibelp** [comment]
https://github.com/spack/spack/pull/15475 (WIP) may address this

**Comment by bvanessen** [comment]
```
    cmake::                                                                                                                                                                                                                                                                                                                                                               
      buildable: True                                                                                                                                                                                                                                                                                                                                                     
      variants: ~openssl ~ncurses                                                                                                                                                                                                                                                                                                                                         
      version: [3.14.5]                                                                                                                                                                                                                                                                                                                                                   
      paths:                                                                                                                                                                                                                                                                                                                                                              
        cmake@3.14.5 arch=linux-rhel7-broadwell:  /usr/tce/packages/cmake/cmake-3.14.5
```
