### ISSUE TITLE
mesa > python > ncurses~termlib but mesa > llvm > ncurses+termlib

### ISSUE THREAD

**Issue by danlipsa** [spack/spack#14793]
<pre>
[~/projects/spack (develop *$%=)]$ spack spec mesa
Input spec
--------------------------------
mesa

Concretized
--------------------------------
==> Error: An unsatisfiable variant constraint has been detected for spec:

    ncurses@6.1%gcc@7.4.0~symlinks~termlib arch=linux-ubuntu18.04-broadwell
        ^pkgconf@1.6.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell

while trying to concretize the partial spec:

    llvm@6:
        ^cmake@3.4.3:
        ^perl-data-dumper
            ^perl@5.30.1%gcc@7.4.0+cpanm+shared+threads arch=linux-ubuntu18.04-broadwell
                ^gdbm@1.18.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                    ^readline@8.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                        ^ncurses@6.1%gcc@7.4.0~symlinks~termlib arch=linux-ubuntu18.04-broadwell
                            ^pkgconf@1.6.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell

llvm requires ncurses variant +termlib, but spec asked for ~termlib
</pre>

This was caused by
https://github.com/spack/spack/pull/14561
The fix would be to change llvm/pakage.py and and depend on ncurses not ncurses+termlib.
If termlib is really needed, the ncourses/package.py should be changed to make termlib variant True.

**Comment by danlipsa** [comment]
@glennpj Seems your merge created this error. Do you really need ncurses+termlib? If that is true, we can change ncourses/package.py

**Comment by glennpj** [comment]
Well, llvm links to libtinfo, which is provided by `ncurses+termlib`. It seems there are two blockers.
```console
$ spack spec mesa
Input spec
--------------------------------
mesa

Concretized
--------------------------------
==> Warning: gcc@4.8.5 cannot build optimized binaries for "broadwell". Using best target possible: "haswell"
==> Error: An unsatisfiable variant constraint has been detected for spec:

    gettext@0.20.1%gcc@4.8.5+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-haswell
        ^bzip2
            ^diffutils@3.7%gcc@4.8.5 arch=linux-centos7-haswell
                ^libiconv@1.16%gcc@4.8.5 arch=linux-centos7-haswell
        ^libxml2@2.9.9%gcc@4.8.5~python arch=linux-centos7-haswell
            ^pkgconf@1.6.3%gcc@4.8.5 arch=linux-centos7-haswell
            ^xz@5.2.4%gcc@4.8.5 arch=linux-centos7-haswell
            ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-haswell
        ^ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-centos7-haswell
        ^tar


while trying to concretize the partial spec:

    python@3.7.6%gcc@4.8.5+bz2+ctypes+dbm~debug~libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-centos7-haswell
        ^pkgconf@1.6.3%gcc@4.8.5 arch=linux-centos7-haswell


python requires gettext variant ~libxml2, but spec asked for +libxml2
```
Then,
```console
$ spack spec mesa ^gettext~libxml2
Input spec
--------------------------------
mesa
    ^gettext~libxml2

Concretized
--------------------------------
==> Warning: gcc@4.8.5 cannot build optimized binaries for "broadwell". Using best target possible: "haswell"
==> Error: An unsatisfiable variant constraint has been detected for spec:

    ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-centos7-haswell
        ^pkgconf@1.6.3%gcc@4.8.5 arch=linux-centos7-haswell


while trying to concretize the partial spec:

    llvm@6:
        ^cmake@3.4.3:
        ^perl-data-dumper
            ^perl@5.30.1%gcc@4.8.5+cpanm+shared+threads arch=linux-centos7-haswell
                ^gdbm@1.18.1%gcc@4.8.5 arch=linux-centos7-haswell
                    ^readline@8.0%gcc@4.8.5 arch=linux-centos7-haswell
                        ^ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-centos7-haswell
                            ^pkgconf@1.6.3%gcc@4.8.5 arch=linux-centos7-haswell


llvm requires ncurses variant +termlib, but spec asked for ~termlib
```
That could be solved by adding `^ncurses+termlib`. However, I am of the opinion that the ncurses termlib variant should default to `True` in order to ensure that libtinfo is present. So, yes, I think changing the termlib variant in ncurses is best.

**Comment by danlipsa** [comment]
A potential fix
https://github.com/spack/spack/pull/14853

**Comment by sethrj** [comment]
Aha, that explains it. I ran into a related issue today and was pissed: I installed two large toolchain environments; one which had llvm, one which didn't. The one without llvm installed an entirely different but essentially equivalent software stack, the only difference being that very low level  change to the `ncurses` default.

**Comment by danlipsa** [comment]
@chuckatkins FYI

**Comment by danlipsa** [comment]
@scheibelp Any progress on this issue? Thanks!

**Comment by scheibelp** [comment]
I'm checking into merging https://github.com/spack/spack/pull/15039. For now, does https://github.com/spack/spack/issues/14793#issuecomment-583083147 resolve the problem for you (i.e. add `^ncurses+termlib` on the command line when working with `mesa`)?

**Comment by danlipsa** [comment]
@scheibelp Thanks! Yes, adding ^ncurses+termlib does solve the problem when working with mesa.

**Comment by scheibelp** [comment]
The immediate issue should be addressed by merging https://github.com/spack/spack/pull/15039. And other issues track this problem more generally. So I will close this for the time being. Feel free to reopen if it comes up again (e.g. if the default variants shift around for some reason).
