### ISSUE TITLE
mesa > python > gettext~libxml2 but mesa > gettext+libxml2

### ISSUE THREAD

**Issue by danlipsa** [spack/spack#14792]
<pre>
[~/projects/spack (develop $%=)]$ spack spec mesa
Input spec
--------------------------------
mesa

Concretized
--------------------------------
==> Error: An unsatisfiable variant constraint has been detected for spec:

    gettext@0.20.1%gcc@7.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu18.04-broadwell
        ^bzip2
            ^diffutils@3.7%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^libiconv@1.16%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libxml2@2.9.9%gcc@7.4.0~python arch=linux-ubuntu18.04-broadwell
            ^pkgconf@1.6.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^xz@5.2.4%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^zlib@1.2.11%gcc@7.4.0+optimize+pic+shared arch=linux-ubuntu18.04-broadwell
        ^ncurses@6.1%gcc@7.4.0~symlinks~termlib arch=linux-ubuntu18.04-broadwell
        ^tar

while trying to concretize the partial spec:

    python@3.7.6%gcc@7.4.0+bz2+ctypes+dbm~debug~libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-ubuntu18.04-broadwell
        ^pkgconf@1.6.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell

python requires gettext variant ~libxml2, but spec asked for +libxml2
</pre>

I use > to mean "depends on"

I think this was triggered by
https://github.com/spack/spack/pull/13847
The fix would be to change the libxml2 variant to True in python/package.py

**Comment by danlipsa** [comment]
@becker33 seems your merge triggered this error.

**Comment by danlipsa** [comment]
@chuckatkins FYI

**Comment by adamjstewart** [comment]
This is affecting other packages as well:
```console
$ spack spec gdal
Input spec
--------------------------------
gdal

Concretized
--------------------------------
==> Warning: clang@11.0.0-apple cannot build optimized binaries for "ivybridge". Using best target possible: "x86_64"
==> Error: An unsatisfiable variant constraint has been detected for spec:

    gettext@0.20.1%clang@11.0.0-apple+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-catalina-x86_64


while trying to concretize the partial spec:

    python@3.7.6%clang@11.0.0-apple+bz2+ctypes+dbm~debug~libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline~shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=darwin-catalina-x86_64
        ^pkgconf@1.6.3%clang@11.0.0-apple arch=darwin-catalina-x86_64


python requires gettext variant ~libxml2, but spec asked for +libxml2
```
Because of this, I can't concretize my entire environment.

**Comment by adamjstewart** [comment]
The quickest workaround so far is to change the `gettext` `libxml2` variant to default to False, but this will break all packages that require `gettext+libxml2`.
