### ISSUE TITLE
Spack compilers are not found when target architecture is microarchitecture

### ISSUE THREAD

**Issue by bvanessen** [spack/spack#14798]
In a spack environment I included a compiler definition and used the microarchitecture target broadwell and spack was unable to find it.  Replacing it with x86_64 allowed it to work.  Seems like the target cannot be a specific microarchitecture.

### Steps to reproduce the issue

create an environment, add a compiler block, and use a target=broadwell

### Error Message

Spack will fail to find the compiler

### Information on your system

This includes:

 1. LLNL LC pascal

**Comment by alalazo** [comment]
Duplicate of #13733

**Comment by alalazo** [comment]
See https://github.com/spack/spack/issues/13733#issuecomment-554231180 Would the same solution be fine with you?

**Comment by bvanessen** [comment]
@alalazo Yes an improved error message would be sufficient.
