### ISSUE TITLE
Activating spack environment does not put CUDA_TOOLKIT_ROOT_DIR in user environment

### ISSUE THREAD

**Issue by bvanessen** [spack/spack#14804]
Trying to use spack dev-build lbann@develop.  Activated environment to provide dependencies and the environment does not setup CUDA_TOOLKIT_ROOT_DIR.

**Comment by scheibelp** [comment]
Apologies for taking a while to get to this.

Environments, when activated, should run `setup_run_environment` for each package. It does not appear that `CUDA_TOOLKIT_ROOT_DIR` is currently set in such a function - would you be able to implement that?

**Comment by bvanessen** [comment]
Sure, I can do that.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by bvanessen** [comment]
To the best of my knowledge setting those environment variables in the spack recipe does not work for cuda.  Perhaps this is because it is an external package?
