### ISSUE TITLE
boost : list of libraries not updated

### ISSUE THREAD

**Issue by alalazo** [spack/spack#1486]
Currently in `boost/package.py` we specify manually every library we want to build. This means that whenever we update the version number we also need to update the list of libraries / variants to be consistent with boost release notes.

Building `boost@1.61` with all the variants but `graph` set to `True` gives : 

```
Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : not building
    - context                  : not building
    - coroutine                : not building
    - coroutine2               : not building
    - date_time                : building
    - exception                : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : building
    - locale                   : building
    - log                      : building
    - math                     : building
    - metaparse                : not building
    - mpi                      : building
    - program_options          : building
    - python                   : building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - signals                  : building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : building
```

meaning that in the last versions of `boost` we missed to update the list of libraries we need to build.

**Comment by alalazo** [comment]
@scheibelp @tgamblin What was the reason to introduce all the variants in `boost`? The reason I ask is that I am trying to introduce the support for new libraries, but I cannot do it with variants because they will depend on the version of boost itself. 

In addition some of the older versions seem broken:
```console
==> './bootstrap.sh' '--prefix=/home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/boost-1.46.0-yoyrsp5lu56hrpktvmvhyxmiiltcborz' '--with-toolset=gcc' '--with-libraries=random,wave,serialization,mpi,iostreams,regex,date_time,thread,system,timer,signals,python,program_options,filesystem,test,math,graph_parallel' '--with-python=/home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/python-2.7.12-h6iqtoljz4kmhy2fonmyeoetvh5cgtok/bin/python'
Building Boost.Jam with toolset gcc... tools/build/v2/engine/src/bin.linuxx86_64/bjam
Detecting Python version... 2.7
Detecting Python root... /home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/python-2.7.12-h6iqtoljz4kmhy2fonmyeoetvh5cgtok
Unicode/ICU support for Boost.Regex?... not found.
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./bjam
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./bjam --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/boost-build2/doc/html/index.html

==> './bjam' '--clean'
error: wrong library name 'timer' in the --with-<library> option.
```
Do you think the `boost` package needs an overall review? How would you like to proceed with the library updates?

@davydden just pinged you in case you are interested in the subject (`boost` is a dependency of `dealii`)

**Comment by adamjstewart** [comment]
My experience with depending on boost is that certain applications require certain boost libraries. For example, you can't build `cgal` without `boost+thread+system`. So we'll either need to build all options, or provide a variant for each.

The versioning problem is annoying. Could we create a dictionary like:
```python
boost_libs = {
    'atomic': '1.53.0:',
    'chrono': '1.47.0:',
    ...
}
```
Then we can loop through the keys to create the variants (like we were previously doing), and also loop through the activated variants to make sure that their version constraints are met. We should probably raise an error message if a variant is activated but not available in that version. Although that might cause problems for the variants enabled by default.

Alternatively, it would be awesome if variants could take a `when='1.47.0:'` keyword.

**Comment by alalazo** [comment]
> Then we can loop through the keys to create the variants (like we were previously doing), and also loop through the activated variants to make sure that their version constraints are met. We should probably raise an error message if a variant is activated but not available in that version. Although that might cause problems for the variants enabled by default.

That's what I was doing, but I stopped because it feels like an hack and it will increase the list of variants over time for every version.

**Comment by adamjstewart** [comment]
It would probably be a lot of work, but in the long run the best option might be adding `when=` to `variant()`. Certain versions provide certain variants (libraries). The hard part will be concretization of something like `boost+thread`. How will you look up what versions of boost provide the `+thread` variant?

**Comment by davydden** [comment]
Having 'when' with variants was mentioned Todd at other thread about Trilinos.

As for boost, I think it does the right thing by providing variants for each module. Otherwise we would have to build all of them which is: (I) time consuming (ii) more fragile (iii) would bring extra dependencies like Python/MPI, that may not be desired or even break concretization in theory. I believe Trilinos should follow the same route as applications often don't depend on the whole Trilinos, but only on a few packages it provides. The issue would be the same in that variants change based on version.

**Comment by adamjstewart** [comment]
@hainest maybe you can take a look at this old boost issue?

**Comment by hainest** [comment]
@adamjstewart This came up when we added the Container library. I'm not sure what the best solution is, but I'll look into it again when I get some time.

**Comment by alalazo** [comment]
This can now be solved with `conditional` variant values.
