### ISSUE TITLE
Transparent build caches? (a la Macports binary packages)

### ISSUE THREAD

**Issue by cesss** [spack/spack#14894]
I'm wondering if it would be easy to implement a new behaviour for build caches so that you don't explicitly ask for a build cache, but spack tries to use it if available, or otherwise builds the source, installs it, and creates a build cache for future uses.

Of course this implies that when you ask to install a package, spack would first search if there's already a build cache for the exact variant/compiler/architecture/etc that you are asking in the install command. If there is one, use it. Otherwise, build (similar behaviour to Macports).

Another consequence is that these build caches should't include any dependency: you would always have a different build cache for each dependency, so installing a package would first install the build caches for its dependencies (if they are available).

The goal I'm trying to achieve is to save bandwidth when `rsync-ing` disks across machines that run the same OS and have the same hardware. Performing a `rsync` of the whole root with all the installed packages is way overkill, at least for the hardware we use. However, if I could `rsync` just the build caches, it would be great: When you install a package in one computer, a build cache is automatically created, and it's stored in a directory that will be `rsync-ed` across all the machines (the actual installation is done in a directory outside the `rsync-ed` area). Then when another computer tries to install the same package with the same options, it finds its cache (together for the caches for all dependencies if available), and extracts the cache instead of building.

Another potential and powerful use of this feature would be backing up the installation of old package versions: When you uninstall an old version, you could first archive it just in case you might need it again in the future and you wish to save the build time. 

Would this imply a lot of work in the current spack code? 

_Note: I'm implying these "build caches" (or better "binary packages" because they would be per-package) would be **for local use only within a machine farm**. I'm not thinking in world wide web distribution of binary packages, as this would require lots of binary compatibility checking that falls outside of spack's scope. Moreover, in my case I wouldn't even need RPATH substitution because all machines in the farm install packages on the same paths_

**Comment by cesss** [comment]
I'm afraid I misread the build caches documentation, because they do exactly what I was asking for (except for their automatic creation after installing a package, but I can live with that). I understood that build caches make a bundle of everything, including dependencies, but they do a different cache file for each package, which is what I need. And they are even transparent in respect with installation of packages. So, what I was asking is already implemented. Shame on me! 😞 (but I'm actually happy because of how powerful is spack, and because this feature I needed is already implemented!

**Comment by alalazo** [comment]
> except for their automatic creation after installing a package

:point_up: That was indeed why I marked the issue as "feature" and "proposal" :slightly_smiling_face:

**Comment by tgamblin** [comment]
@cesss: you might also like [pipelines](https://spack.readthedocs.io/en/latest/pipelines.html) for building your caches :)

**Comment by cesss** [comment]
@tgamblin and @alalazo Thanks a lot!! I'll investigate pipelines!!
