### ISSUE TITLE
Installation issue: mpfr

### ISSUE THREAD

**Issue by tylerjereddy** [spack/spack#14901]
`spack install mpfr` fails pretty broadly across various versions at the moment. I noticed this when trying to build `gcc` with spack.

The traceback is below the fold:

<details>

```
==> Installing mpfr
==> Searching for binary cache of mpfr
==> No binary for mpfr found: installing from source
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check clang@11.0.0-apple for further details]
==> Fetching https://ftpmirror.gnu.org/mpfr/mpfr-4.0.2.tar.bz2
####################################################################################################### 100.0%
==> Fetching https://www.mpfr.org/mpfr-4.0.2/allpatches
-=O=-          #      #      #       #                                                                       
curl: (28) Connection timed out after 10000 milliseconds
==> Failed to fetch file from URL: https://www.mpfr.org/mpfr-4.0.2/allpatches
    Curl failed with error 28
==> Fetching from https://www.mpfr.org/mpfr-4.0.2/allpatches failed.
==> Error: FetchError: All fetchers failed for spack-stage-w5dovhkj

/Users/treddy/github_projects/spack/lib/spack/spack/package.py:1119, in do_fetch:
       1116
       1117        self.stage.cache_local()
       1118
  >>   1119        for patch in self.spec.patches:
       1120            patch.fetch()
       1121            if patch.cache():
       1122                patch.cache().cache_local()
```

</details>

This is because the `mpfr` patches site/website is not always reliable.

Might be worth considering a fallback like homebrew uses: https://github.com/Homebrew/legacy-homebrew/issues/12371

Naturally, reproducing this issue is a function of the `mpfr` site being up or down.

**Comment by cpraveen** [comment]
I faced this issue also.

Now I am not able to install mumps because their website is not accessible. Actually, I have the mumps tar file with me. Previously I would copy this to spack/var/spack/cache/mumps directory and continue installation. It seems source files are no longer saved in such simple directory structure and I dont know to use the available source file rather than downloading it from the internet.

**Comment by scheibelp** [comment]
> It seems source files are no longer saved in such simple directory structure and I dont know how to use the available source file rather than downloading it from the internet.

Spack itself doesn't choose to store files in a simple location in the cache anymore, but it will recognize a file stored at e.g. `var/spack/cache/mumps/mumps-<version>.tar.gz`

**Comment by cpraveen** [comment]
@scheibelp  Great, thanks a lot for this info, it works. This has saved me time so many times.

**Comment by adamjstewart** [comment]
Spack supports fallbacks/mirrors for `urls` thanks to @alalazo, see #13881. @alalazo does this work for patches as well?

**Comment by alalazo** [comment]
@adamjstewart No, it doesn't currently work for patches.

**Comment by adamjstewart** [comment]
Spack now has an official mirror, so users rarely access the original website unless a new version is being added. Patches are also contained in this mirror. I think it's safe to close this issue.
