### ISSUE TITLE
Specifying more than one operating_system in the same compilers.yaml entry

### ISSUE THREAD

**Issue by cesss** [spack/spack#14927]
For convenience, I'm using the same configuration files for two Macs that run a different MacOS version (one with Sierra, the other with High Sierra, but apart from that they are identical from spack's point of view: same compilers installed, same everything installed). Generated executables are exactly the same on both machines (exactly same compilers -custom build-, exactly same MacOS SDK, and exactly same ${MACOSX_DEPLOYMENT_TARGET} (ie: 10.12).

In fact, spack generates exactly the same `compilers.yaml` file on both machines, with the only difference that in one you see "sierra" for the `operating_system` entry, and in the other you see "highsierra".

Now, can I use the same `compilers.yaml` file for both machines? Apparently, `operating_system` will allow only one string, according to the schema. But is there any "dumb tag" that will allow both sierra and highsierra, or maybe even all MacOS versions? Or can I disable the `operating_system` entry in some way? If possible to disable, would it have any consequence on built packages?

**Comment by alalazo** [comment]
Did you try merging the two `compilers.yaml` into a single file? Is that not working?

**Comment by cesss** [comment]
Yes, thanks, it seems to work!!

BTW, have you ever seen an error like this when executing `spack compiler info` on some compiler?

```
cesss$ spack compiler info clang@8.1.0-apple
clang@8.1.0-apple:
	paths:
		cc = /usr/bin/clang
		cxx = /usr/bin/clang++
		f77 = None
		fc = None
==> Error: 'set'
```

What does `==> Error: 'set'` mean? The interesting thing is that it happens for one compiler only, and that it's in a `compilers.yaml` file generated by `spack`, before my modifications.

**Comment by alalazo** [comment]
@cesss Can you show the output of:
```console
$ spack -d compiler info
```
?

**Comment by cesss** [comment]
Sure!

```
cesss$ spack -d compiler info clang@8.1.0-apple
==> [2020-02-13-15:26:35.826934] Imported compiler from built-in commands
==> [2020-02-13-15:26:35.829337] Imported compiler from built-in commands
==> [2020-02-13-15:26:35.830055] Reading config file /Users/cesss/.spack/darwin/compilers.yaml
clang@8.1.0-apple:
	paths:
		cc = /usr/bin/clang
		cxx = /usr/bin/clang++
		f77 = None
		fc = None
==> [2020-02-13-15:26:35.845718] Reading config file /Users/cesss/spack/etc/spack/defaults/config.yaml
==> [2020-02-13-15:26:35.856527] Reading config file /Users/cesss/.spack/darwin/config.yaml
Traceback (most recent call last):
  File "/Users/cesss/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/Users/cesss/spack/lib/spack/spack/main.py", line 754, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/cesss/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/Users/cesss/lib/spack/spack/cmd/compiler.py", line 182, in compiler
    action[args.compiler_command](args)
  File "/Users/cesss/spack/lib/spack/spack/cmd/compiler.py", line 145, in compiler_info
    if len(c.environment['set']) != 0:
  File "/Users/cesss/spack/lib/spack/external/ruamel/yaml/comments.py", line 426, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'set'
```

BTW, this is not the compiler I'm going to use, but the one from Xcode... however this error puzzles me...

**Comment by alalazo** [comment]
Next commands:
```console
$ cat /Users/cesss/.spack/darwin/config.yaml
$ cat /Users/cesss/.spack/darwin/compilers.yaml
```
It seems there's something wrong with the `environment` attribute missing a `set` key, either in the code or in the config.

**Comment by cesss** [comment]
I deleted my `config.yaml` so I'm now using the default, and the error and output is the same, so we can rule `config.yaml` out of being the cause. 

This is the `compilers.yaml` that triggers such error (generated by spack):

```
compilers:
- compiler:
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77:
      fc:
    operating_system: sierra
    target: x86_64
    modules: []
    environment:
      unset: []
    extra_rpaths: []
    flags: {}
    spec: clang@8.1.0-apple
- compiler:
    paths:
      cc:
      cxx:
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    operating_system: sierra
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@6.3.0
- compiler:
    paths:
      cc: /Users/cesss/MacOSX10.12-llvm7.0.0-x86_64/LLVM/7.0.0/bin/clang
      cxx: /Users/cesss/MacOSX10.12-llvm7.0.0-x86_64/LLVM/7.0.0/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    operating_system: sierra
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    spec: clang@7.0.0

```

This happens on High Sierra. I can try if it also happens on Sierra, later.

**Comment by cesss** [comment]
BTW, I checked I'm back on default config by issuing `spack config get config` and seeing tha actually I'm back to defaults

**Comment by alalazo** [comment]
@cess Confirmed the behavior you see, that's definitely a bug.

**Comment by cesss** [comment]
Thanks a lot, @alalazo !!

BTW, is it possible to use environment variables in `compilers.yaml` ? (It's for the --isysroot compile flag, because I have environment variables pointing to the MacOS SDKs) I tried but they are not resolved. I used the same syntax as in `config.yaml` (ie: ${VARIABLE} ) and they are substituted there, but apparently they are not resolved in `compilers.yaml`.

To make it more clear, these variables are not substituted:

```
[a line from compilers.yaml]
    flags:
      cflags: -isysroot ${MY_MACOS_SDK} -mmacosx-version-min=${MY_MACOSX_DEPLOYMENT_TARGET}

```

**Comment by cesss** [comment]
Back the original topic, I believe I need some way of telling spack that the compilers and flags I'm specifying generate binaries for `sierra` and not for the actual MacOS version being run, and therefore, packages should take `sierra` in their name, regardless the actual system.

Consider it a sort of cross-compiling if you wish, but I need some way of enforcing that all my packages are built (and named) in this way.

An ugly trick would be to modify [mac_os.py](https://github.com/spack/spack/blob/4af630308619afb40b1de89d1f7bac0f57b70a38/lib/spack/spack/operating_systems/mac_os.py) so that all the MacOS versions I use return `sierra` for their name, but obviously this is a really ugly workaround. Cannot I modify the target os for installs?

**Comment by cesss** [comment]
Thanks a lot @alalazo and @adamjstewart for such a quick fix!!

Regarding the initial topic of this question, I'm going to open a new issue because it's better not to mix so many different things in the same place 😃
