### ISSUE TITLE
gzip build failure because "build_directory = 'spack-build'" is needed

### ISSUE THREAD

**Issue by cesss** [spack/spack#15017]
Just like happened in other related issues, like https://github.com/spack/spack/issues/3387 , the **gzip** package also needs `build_directory = 'spack-build'` to be added into its package file, or otherwise GNUmakefile will point to itself.

Not that I needed **gzip**, but I was installing **Qt**, which depends on **libmng**, which depends on gzip, which makes me wonder if nobody is installing **Qt** nowadays... strange because **Paraview** needs it.

**Comment by adamjstewart** [comment]
Fixed by #14994
