### ISSUE TITLE
Qt doesn't build on MacOS

### ISSUE THREAD

**Issue by cesss** [spack/spack#15018]
I tried to install several Qt versions on MacOS and all of them failed, because of different reasons. Most of the times, `qmake` is built, but then it's like if the configuration failed: It cannot find libpng, libjpeg, it even tries to include a SDL header (!!) and even `<linux/videodev2.h>`

BTW, there's an early error because of the patch for overflow with Intel compilers: I'm using LLVM but anyway this patch is thrown anyway, and then it fails when patching 5.14 with the latest patch available (5.12). This was easy to overcome (just comment out the Intel patches, as I'm not using that compiler).

There was one version (I think it was 5.7.1) that was almost there: None of the weird errors mentioned above took place, but then there's a compilation error because of some datatypes not defined (I guess some incompatibility from that version to the system headers I have).

I even tried the fork by [davydden](https://github.com/davydden/spack/tree/25d9f48454c48f8a4214f2cbc75abdc35c57310e/var/spack/repos/builtin/packages/qt) because it seemed to be at a MacOS-fixed point in history, but it also failed with the configuration errors above.

Is there any version that I didn't try and that it's known to work on MacOS?

**Comment by glennpj** [comment]
> BTW, there's an early error because of the patch for overflow with Intel compilers: I'm using LLVM but anyway this patch is thrown anyway, and then it fails when patching 5.14 with the latest patch available (5.12). This was easy to overcome (just comment out the Intel patches, as I'm not using that compiler).

That patch was submitted upstream so it is probably included in 5.14. The patch line in spack could be changed to 

```
patch('qt5_12-intel-overflow.patch', when='@5.12:5.13')
```

**Comment by sethrj** [comment]
@cesss can you please submit the full spec for your installation attempt, full system version, and full error log?

**Comment by sethrj** [comment]
@glennpj per [the discussion on the qt bug report](https://bugreports.qt.io/browse/QTBUG-81248) it looks like this will be needed through 5.14.0 .

**Comment by glennpj** [comment]
Yes, it looks that way. It was merged in the 5.14 branch and looks like 5.14.1 should have it. That version was released on January 27, 2020.

**Comment by sethrj** [comment]
@cesss This was closed automatically because #15025 fixed the patch issue, but please reopen if you will fill out the bug report template.
