### ISSUE TITLE
Installation issue: openfoam-org with PGI compiler

### ISSUE THREAD

**Issue by samcom12** [spack/spack#15037]
---

### Steps to reproduce the issue

```console
$ spack install openfoam-org %pgi 
... ==> Error: Conflicts in concretized spec "openfoam-org@7%pgi@19.4~float32~int64~metis patches=73103e6b1bdbf3b1e0d517cbbd11562e98c6e9464df5f43e5125e9a5b457d1c5,ecfa93afa8900f583a23c179db7cf0dc066828a9fd872e061164f21301c2a222 +source arch=linux-centos7-skylake_avx512/twrspf5"
List of matching conflicts for spec:

    libpciaccess@0.13.5%pgi@19.4 arch=linux-centos7-skylake_avx512
        ^libtool@2.4.6%pgi@19.4 arch=linux-centos7-skylake_avx512
            ^m4@1.4.18%pgi@19.4 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-centos7-skylake_avx512
                ^libsigsegv@2.12%pgi@19.4 arch=linux-centos7-skylake_avx512
        ^pkgconf@1.6.3%pgi@19.4 arch=linux-centos7-skylake_avx512
        ^util-macros@1.19.1%pgi@19.4 arch=linux-centos7-skylake_avx512

1. "%pgi" conflicts with "libpciaccess"
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux login1.iitbhu.ac.in 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
``` 

- `packages.yaml`
- `compilers.yaml`
compiler:
    paths:
      cc: /opt/ohpc/pub/pgi_2019/linux86-64-llvm/19.4/bin/pgcc
      cxx: /opt/ohpc/pub/pgi_2019/linux86-64-llvm/19.4/bin/pgc++
      f77: /opt/ohpc/pub/pgi_2019/linux86-64-llvm/19.4/bin/pgfortran
      fc: /opt/ohpc/pub/pgi_2019/linux86-64-llvm/19.4/bin/pgfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@19.4
### Additional information
Any alternative for using pgi compiler to build openfoam-org?

**Comment by adamjstewart** [comment]
> Any alternative for using pgi compiler to build openfoam-org?

You can do:
```console
$ spack install openfoam-org %pgi ^libpciaccess %gcc
```
See https://spack.readthedocs.io/en/latest/getting_started.html#pgi

You should also be able to permanently configure this in your `packages.yaml`. Let me know if you have any other questions.
