### ISSUE TITLE
spack install paraview+python3 prints: Error: 'Call' object has no attribute 'id'

### ISSUE THREAD

**Issue by danlipsa** [spack/spack#15079]
spack spec works fine.

@chuckatkins FYI

<pre>
~/projects/spack (develop $%=)]$ spack install paraview+python3
==> Warning: Missing a source id for opengl@4.5.0
==> Error: 'Call' object has no attribute 'id'
[~/projects/spack (develop $%=)]$ spack spec paraview+python3
Input spec
--------------------------------
paraview+python3

Concretized
--------------------------------
paraview@5.7.0%gcc@7.4.0 build_type=RelWithDebInfo ~cuda cuda_arch=none ~examples~hdf5+mpi+opengl2~osmesa+plugins~python+python3~qt+shared arch=linux-ubuntu18.04-broadwell
    ^bzip2@1.0.8%gcc@7.4.0+shared arch=linux-ubuntu18.04-broadwell
        ^diffutils@3.7%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^libiconv@1.16%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^cmake@3.16.2%gcc@7.4.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-broadwell
        ^ncurses@6.1%gcc@7.4.0~symlinks~termlib arch=linux-ubuntu18.04-broadwell
            ^pkgconf@1.6.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^openssl@1.1.1d%gcc@7.4.0+systemcerts arch=linux-ubuntu18.04-broadwell
            ^perl@5.30.1%gcc@7.4.0+cpanm+shared+threads arch=linux-ubuntu18.04-broadwell
                ^gdbm@1.18.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                    ^readline@8.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^zlib@1.2.11%gcc@7.4.0+optimize+pic+shared arch=linux-ubuntu18.04-broadwell
    ^expat@2.2.9%gcc@7.4.0+libbsd arch=linux-ubuntu18.04-broadwell
        ^libbsd@0.10.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^freetype@2.10.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libpng@1.6.37%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^libjpeg-turbo@2.0.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^nasm@2.14.02%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^libtiff@4.0.10%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^xz@5.2.4%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^libxml2@2.9.9%gcc@7.4.0~python arch=linux-ubuntu18.04-broadwell
    ^libxt@1.1.5%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^kbproto@1.0.7%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^util-macros@1.19.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libice@1.0.9%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^xproto@7.0.31%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^xtrans@1.3.5%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libsm@1.2.2%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libx11@1.6.7%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^inputproto@2.3.2%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^libxcb@1.13%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^libpthread-stubs@0.4%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^libxau@1.0.8%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^libxdmcp@1.1.2%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^xcb-proto@1.13%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^xextproto@7.3.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^mpich@3.3.2%gcc@7.4.0 device=ch3 +hydra netmod=tcp +pci pmi=pmi +romio~slurm~verbs+wrapperrpath arch=linux-ubuntu18.04-broadwell
        ^findutils@4.6.0%gcc@7.4.0 patches=84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e,bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2 arch=linux-ubuntu18.04-broadwell
            ^autoconf@2.69%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^m4@1.4.18%gcc@7.4.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-ubuntu18.04-broadwell
                    ^libsigsegv@2.12%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^automake@1.16.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^libtool@2.4.6%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^texinfo@6.5%gcc@7.4.0 patches=12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a,1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1 arch=linux-ubuntu18.04-broadwell
        ^libpciaccess@0.13.5%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^netcdf-c@4.7.3%gcc@7.4.0~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+pic+shared arch=linux-ubuntu18.04-broadwell
        ^hdf5@1.10.6%gcc@7.4.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu18.04-broadwell
    ^opengl@4.5.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^py-matplotlib@3.1.3%gcc@7.4.0~animation backend=agg +image~latex~movies arch=linux-ubuntu18.04-broadwell
        ^py-cycler@0.10.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^py-setuptools@41.4.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^python@3.7.6%gcc@7.4.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-ubuntu18.04-broadwell
                    ^gettext@0.20.1%gcc@7.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu18.04-broadwell
                        ^tar@1.32%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                    ^libffi@3.2.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                    ^sqlite@3.30.1%gcc@7.4.0~column_metadata+fts~functions~rtree arch=linux-ubuntu18.04-broadwell
            ^py-six@1.12.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^py-kiwisolver@1.1.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^py-numpy@1.18.1%gcc@7.4.0+blas+lapack arch=linux-ubuntu18.04-broadwell
            ^openblas@0.3.8%gcc@7.4.0~consistentFPCSR~ilp64+pic+shared threads=none arch=linux-ubuntu18.04-broadwell
            ^py-cython@0.29.14%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^py-pillow@7.0.0%gcc@7.4.0~freetype~jpeg2000~lcms~tiff~webp~webpmux arch=linux-ubuntu18.04-broadwell
        ^py-pyparsing@2.4.2%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^py-python-dateutil@2.8.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^py-setuptools-scm@3.3.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^py-mpi4py@3.0.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
</pre>

**Comment by tldahlgren** [comment]
I tried to reproduce this issue in one of my clones but I get an unsatisfiability error using either  command:

```
==> Error: An unsatisfiable variant constraint has been detected for spec:

    ncurses@6.1%gcc@7.3.0~symlinks~termlib arch=linux-rhel7-broadwell
        ^pkgconf@1.6.3%gcc@7.3.0 arch=linux-rhel7-broadwell


while trying to concretize the partial spec:

    llvm@6:
        ^cmake@3.16.2%gcc@7.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel7-broadwell
            ^ncurses@6.1%gcc@7.3.0~symlinks~termlib arch=linux-rhel7-broadwell
                ^pkgconf@1.6.3%gcc@7.3.0 arch=linux-rhel7-broadwell
            ^openssl@1.1.1d%gcc@7.3.0+systemcerts arch=linux-rhel7-broadwell
                ^perl@5.30.1%gcc@7.3.0+cpanm+shared+threads arch=linux-rhel7-broadwell
                    ^gdbm@1.18.1%gcc@7.3.0 arch=linux-rhel7-broadwell
                        ^readline@8.0%gcc@7.3.0 arch=linux-rhel7-broadwell
                ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-rhel7-broadwell
        ^perl-data-dumper


llvm requires ncurses variant +termlib, but spec asked for ~termlib
```

However, that error is easy to trace since it only appears in one location; namely, `content_hash` of `package.py` where the following comment is in the code:

```
            # TODO? in cases where a digest or source_id isn't available,
            # should this attempt to download the source and set one? This
            # probably only happens for source repositories which are
            # referenced by branch name rather than tag or commit ID.
```.

**Comment by danlipsa** [comment]
Yes, that is another issue that is being worked on.
https://github.com/spack/spack/issues/14793
You can fix that temporarily with:
<pre>
diff --git a/var/spack/repos/builtin/packages/ncurses/package.py b/var/spack/repos/builtin/packages/ncurses/package.py
index 7b9b67b93..bee4fd655 100644
--- a/var/spack/repos/builtin/packages/ncurses/package.py
+++ b/var/spack/repos/builtin/packages/ncurses/package.py
@@ -26,7 +26,7 @@ class Ncurses(AutotoolsPackage, GNUMirrorPackage):
 
     variant('symlinks', default=False,
             description='Enables symlinks. Needed on AFS filesystem.')
-    variant('termlib', default=False,
+    variant('termlib', default=True,
             description='Enables termlib needs for gnutls in emacs.')
 
     depends_on('pkgconfig', type='build')
</pre>

**Comment by tldahlgren** [comment]
The error you are reporting is easy to trace since it only appears in one location; namely, `content_hash` of `package.py` where the following comment is in the code:

```
            # TODO? in cases where a digest or source_id isn't available,
            # should this attempt to download the source and set one? This
            # probably only happens for source repositories which are
            # referenced by branch name rather than tag or commit ID.
```

Built-in `opengl*` packages are only place holders for hardware vendor OpenGL libraries so how is the fetcher determined in your case?

**Comment by danlipsa** [comment]
Sorry, I don't know what the fetcher is. Anyway, the same error happens if I specify osmesa instead of using the hardware OpenGL.
<pre>
[~/projects/spack (develop *$%=)]$ spack install paraview+python3+osmesa
==> Error: 'Call' object has no attribute 'id'
</pre>

**Comment by tldahlgren** [comment]
> Yes, that is another issue that is being worked on.
> #14793
> You can fix that temporarily with:
> 
> diff --git a/var/spack/repos/builtin/packages/ncurses/package.py b/var/spack/repos/builtin/packages/ncurses/package.py
> index 7b9b67b93..bee4fd655 100644
> --- a/var/spack/repos/builtin/packages/ncurses/package.py
> +++ b/var/spack/repos/builtin/packages/ncurses/package.py
> @@ -26,7 +26,7 @@ class Ncurses(AutotoolsPackage, GNUMirrorPackage):
>  
>      variant('symlinks', default=False,
>              description='Enables symlinks. Needed on AFS filesystem.')
> -    variant('termlib', default=False,
> +    variant('termlib', default=True,
>              description='Enables termlib needs for gnutls in emacs.')
>  
>      depends_on('pkgconfig', type='build')

Thanks!  I am now able to reproduce the results you are seeing with both commands.

**Comment by tldahlgren** [comment]
@danlipsa Can you try the fix here to see if it helps you?  

(BTW How long does this take to build? I'm trying to decide if I should let it continue.)

**Comment by danlipsa** [comment]
It takes a while to build. :smile: An hour or two paraview + all dependencies. But I have everything built already.
Yes 
https://github.com/spack/spack/pull/15093
seems to have fixed it. I only get a warning now
<pre>
[~/projects/spack (develop *$%<)]$ spack install paraview@develop+python3+mpi+osmesa~opengl2^mpich
==> Warning: Missing a source id for paraview@develop
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libiconv-1.16-usdemrtvncmk7l2jzten6ea45dv2nz6q
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/pkgconf-1.6.3-hizdr2swzfvxhrjho4kp5fe2phz6gxyz
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/zlib-1.2.11-w4ulfwd3tv3reuna2m7n5vrwgqt26y2y
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libbsd-0.10.0-26bdonv7biope5qw76hbey33ztt4htdh
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/nasm-2.14.02-6pkxjyg5tuq5fmagtuxkh4cadybh7n7e
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/xz-5.2.4-rvjllro5mxsf3kvoyaslsfhw7qqnk7hm
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libsigsegv-2.12-z2znauycylcirgumcqcstn3aa3mtt7sl
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/util-macros-1.19.1-brzcykdshghgf2h3lwsxrhw3ybkjxm5o
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libpthread-stubs-0.4-kspj5lzgugsl5bhizl4xz2c3bjnqrmew
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/xcb-proto-1.13-pfp6nuajor4gjyilpqjnk2pxcf3j36zl
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libffi-3.2.1-fbfozbpj3c73movivx5et5gj74zxbca7
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/pcre-8.43-cf3uqi5ho4h3c35bv6a7dlpmwiurrbkl
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/openblas-0.3.8-alqybwpugn7uissgohff3prmiimkq22k
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/tar-1.32-zehefztapxgxtr2fqglna2nspazalxw7
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/diffutils-3.7-uesuzz5l3ltpsvf2zxbquh4ax3bvkzfg
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/ncurses-6.1-gakuvlf454pzkyuav36mgezfwb7d6zux
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libpng-1.6.37-dokylqugaragaseniy4e3exflsprcs3j
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/expat-2.2.9-27gwfql572rk2jjc3tk2rqa2mtcm6doh
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libxml2-2.9.9-4ytnkxi3rnuftul75sd55kshsavbtdgy
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/m4-1.4.18-nc4tzctzgwsz6c3sbj27w7pswrnitxvj
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/xtrans-1.3.5-6lnvu7beimee672jvbfe5vnlwtsge6j5
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/inputproto-2.3.2-ltxn3zlkjn7m5ykp2sqolmfsumycbmz6
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/kbproto-1.0.7-x24u23oxc3uywdeglr46ettnmzbfkso2
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/xproto-7.0.31-dtfcg3didugdcvpzwzi7d5hudp7fygg2
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/xextproto-7.3.0-m7fglwsf3phktr5y46mzvztwkcfnq4r2
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/glproto-1.4.17-iumdnx5u7c4oawm42sr4hj5k2hcqmt7q
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/swig-4.0.0-s7ga3grrpwpjiawsp65g7pw45llvp7m4
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/bzip2-1.0.8-5uxmra2k5kvy3f5xsh5me4rfhy4y5qqy
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/readline-8.0-v5rtbbe24gvctpmeqo3sf6sgrbatdcb5
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libedit-3.1-20191231-bsath7ioxibqjxi5gc6r55zcsszemp26
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libtool-2.4.6-voyrordd5pog4breswwoliyiqroy7fhg
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libxdmcp-1.1.2-7jmghqdtn64hfbntftfsdpmwfohnsgen
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libxau-1.0.8-vfsmlnvieq26eukhmri2x37rh573s24h
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/freetype-2.10.1-l4p27w6zmeqcku52svlzkcvg3ujyghpg
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/gettext-0.20.1-kf5mqnln35vir4xqbmvb3wqe36hxz6bc
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/gdbm-1.18.1-ofsjnndaesu4qzwnk7pkhw2mw6khfhxd
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/sqlite-3.30.1-2pzifaype2cgss2kyixo2qpbnowstrtv
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libpciaccess-0.13.5-poce4nztxwghiyqyctqgmumt776rbl63
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libxcb-1.13-kth4oara7yrycfp6mtmwkzzdf4ocfmlx
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/binutils-2.33.1-toewwa5cgatafua57pkv3vzkbf7ddtvd
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/perl-5.30.1-wwfv7k5j5rk6xmzeaj3m7ocoduqwea6f
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/openssl-1.1.1d-4dxhkwjctaxizmiotm7tpwh7vh6fioyn
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/texinfo-6.5-rvlchxwozl6sjpe5imykjw5vgtqoofvu
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/autoconf-2.69-vcum4zgnpdvk6j6mxpu7vqd3juidkgrt
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/perl-data-dumper-2.173-6zqlxbjnci4moof5izvfkaf7woswv6yz
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libx11-1.6.7-aqown32sa7uf5i6gukhqae2xeinf2bzp
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/help2man-1.47.11-r2l4g4g2u7trnf7ylth7ulw7e5bwkmgo
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/python-3.7.6-kz7e4q3qf4qhrsdi5oyyvo2ahrkaqhmi
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/cmake-3.16.2-tcgwu5p7fjtzgvmnvtbsk55j4alrpyvo
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/automake-1.16.1-fjcfcdm4mywp74vgn2mt5z32e6elzvb6
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libxext-1.3.3-pcbgnrd4vfczzhfpjbyo44jelgvsidem
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/bison-3.4.2-2md6646tyaiqb5vw4swsdxb255h3y7g7
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-setuptools-41.4.0-kmia5stvhpgqgoropqsvjync3ugirkb2
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-six-1.12.0-csaqs5fdax4xciwlwzylsqwmuukbjcaq
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libjpeg-turbo-2.0.3-a3pw6reezhty7uexzmx64uramyjphgp2
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/llvm-9.0.1-2ljh3yfpqglwpnzrbsf7p7skaubvm5p6
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/findutils-4.6.0-7rpnh7wmlz3rxfzos5ho3id6p4megal6
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-markupsafe-1.1.1-4lgdlbwbycbqr6nce5uwjpl7gj6bmzqm
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-setuptools-scm-3.3.3-bi2o5bfm6r3t3krh3h4is4vrqi4qe2si
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-kiwisolver-1.1.0-utnefyqkio66kfwgynfwjbpfjqwyddsw
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-pyparsing-2.4.2-cfzd47ohpdswnrwflxiw3yozrgh7t2ip
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-cython-0.29.14-c4n7myemrpbz2y44vxtorbpbhjpf57fb
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-cycler-0.10.0-ukq6mpyhszza4cyw44g2a5c6ceauo44u
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/libtiff-4.0.10-63kjokbiknxyrgiwj4r5xyqtgnzj7upx
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-pillow-7.0.0-22fq7kd5dqcuiopgvs6k7wiy5ahdar6c
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/mpich-3.3.2-lghtpnz3lylqdzptbujh24abgbk3zdnd
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/flex-2.6.4-psrvr7hm7r24qms3uojgzjbqpceh2ycu
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-mako-1.0.4-tsj24tjq2jvqgpshqy63uawcrkg4vyuq
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-python-dateutil-2.8.0-nqsbun6dyvxholqdb3662vgbv26mzo6l
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-numpy-1.18.1-pp423ooilole7lrss67ehtivbhs7boya
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/hdf5-1.10.6-wnllkzy3pek3ya7jil4vmspyok24b5d2
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-mpi4py-3.0.3-4rwjeo5ldpqrudxgfykuikyb5ye2xepa
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/mesa-18.3.6-fd2om4hnpqfdmcqytawj5net7mahblo5
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/py-matplotlib-3.1.3-mbbiszyxqzy577bpz6dr2u32l6dmcmjx
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/netcdf-c-4.7.3-cpmn5yeqhi3reqafqnafgezivlguahzg
[+] /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/paraview-develop-loelgkmqwkii3asdzzuus75xqhyrotvx
</pre>

**Comment by tldahlgren** [comment]
> It takes a while to build. 😄 An hour or two paraview + all dependencies. But I have everything built already.
> Yes
> #15093
> seems to have fixed it. I only get a warning now
> 
> [~/projects/spack (develop *$%<)]$ spack install paraview@develop+python3+mpi+osmesa~opengl2^mpich
> ==> Warning: Missing a source id for paraview@develop

Great.  I didn't see that warning.  I'll have to check the output.  ( I have 'debug' turned on so there's a lot of information scrolling by.)

Thanks for your quick response.
