### ISSUE TITLE
Spack needs integration tests

### ISSUE THREAD

**Issue by eschnett** [spack/spack#1507]
Spack has self tests, and these are fine, and I'm sure these are useful. But what I miss are full system tests, where a new version of Spack is checked out, a non-trivial set of packages are built, and various Spack commands are run on the install. I've implemented a Bash script that does this https://raw.githubusercontent.com/eschnett/spack-test/master/spacktest-ubuntu16.sh, along the lines of:
- clone Spack
- build GCC
- point Spack to this GCC
- build a set of "important" HPC packages (HDF5, MPI, OpenBLAS, Python)
- run some simple tests on these packages
- build a set of tools (git, lmod, rsync)
- run some simple tests with these tools

My plan is to submit issues (and/or put work-arounds into my script) until things work. Then we can run the script once a day, and every time it succeeds, we tag the respective Spack checkout as "good". Every time it doesn't, there's a bug report.

**Comment by davydden** [comment]
good idea, i would also also add `trilinos`, which takes some time but is equally important to `petsc`. Otherwise the set of packages looks good to my needs.

**Comment by tgamblin** [comment]
This is great.  Can we add this as another thing in the Travis build matrix?  I thought the gcc build was too long to run there, which is why I've been working on getting testing set up in AWS, but if a test like this will not exceed any Travis limits I think it would be good to put in the usual suite.

One more general thing that would be nice to add: figuring out whether particular tests need to run based on the changes in a PR.  This test likely doesn't need to run for changes to packages that are not in the dep graph of gcc, git, Python, MPI, etc.  It wouldn't be too hard to add a Spack command to figure that out, so that this would only run for relevant package changes and for changes to the core.  Thoughts?

**Comment by eschnett** [comment]
This test doesn't work in Travis; it takes too much time. Maybe we can downscale it by removing the expensive real-world packages, and keep the Spack tests at the end, and then add it to Travis.

I've just added a Dockerfile that allows me to run this test on a beefy workstation locally.

**Comment by tgamblin** [comment]
Do you have timings for each of the package installs on your workstation?  I'd like to get a sense of how long this would take.  In AWS, with bottom-up parallel builds, where each package is farmed out to a node, I think we could make this type of thing fairly quick. Also depending on the node type, we could get more parallelism out of each individual build.

**Comment by adamjstewart** [comment]
I think the current `spack test` checks are sufficient when the core Spack libraries are modified, but they don't make a lot of sense when package.py files are modified. I think Travis should automatically build each package when it is modified. How do others feel about this?

**Comment by eschnett** [comment]
I don't have timings yet. I ran it yesterday on my laptop in a VM, which is quite a bit slower. I also had to do many (manual) restarts to find work-arounds for various problems. I am collecting timings now.

**Comment by eschnett** [comment]
@adamjstewart No, I don't think the current `spack test` is good enough. There are many problems that it doesn't catch. There are quite a few issues open that arguably should have been caught by self tests; I assume they haven't because the current self-tests don't reach the complexity of a real-world package dependency graph.
- aborting a build can break the Spack database (`spack reindex` reports invalid ref counts)
- `'spack load' doesn't work because paths are truncated
- `spack view symlink` doesn't create symlinks for symlinks
- cannot uninstall packages by hash
- spack tries to install `python@2` as dependency, and fails

Some of these are simply due to missing tests (that, I'm sure, will be added once the bugs are fixed), but others -- e.g. the `reindex` issue -- probably would have been caught by more extensive testing. Maybe adding more tests manually is a solution, maybe we need to add fuzz testing by automatically generating a set of interdependent packages and versions and presenting them to Spack a million times, and sometimes randomly aborting Spack. However, a real-world installation (even if the build takes hours) will also test Spack's core.

**Comment by tgamblin** [comment]
@eschnett: if you have the build output, it should have timings in it.

**Comment by adamjstewart** [comment]
Sorry, when I meant that `spack test` was sufficient, I didn't mean it was perfect :laughing: 

A real-world installation could also be used to test Spack, but I don't see how it would catch any of these problems better than a mock test. The last two bugs in particular would be really easy to add mock tests for that don't take an hour to build. I don't see an easy way to test for the reindex bug, but maybe you have something in mind.

When a package.py is modified, I agree that it requires a real-world installation. But if none of those are touched, I think mock tests would be preferable.

**Comment by tgamblin** [comment]
@eschnett: I think most of these are test coverage issues, but real-world integration tests help increase coverage.

FYI: you can go to the [coveralls site](https://coveralls.io/github/LLNL/spack?branch=develop) you can actually see which lines in which files are not covered by the current tests.  I think it understates the coverage in some places (the package build, for instance) because Spack calls `fork()` and it doesn't look like coveralls follows it, but it does provide a good starting point.  I am happy to accept patches that add more tests so that the missing stuff gets covered.

**Comment by tgamblin** [comment]
@adamjstewart: it might not catch the problems better than a mock test would, if the mock test were implemented, but integration tests are an easy way to put together a real-world use case, which will often reveal new problems.  I think this is something we can use to _make_ new mock tests.

Also, the core is still in enough of a state of change that I think it's worth running at least the packages @eschnett has here for changes to the Spack core.  When we modify things like the build environment and compiler wrappers, I don't have a lot of confidence in my changes without running  a few builds manually right now, and I'd really like automated testing so I can just fire and forget.

**Comment by sknigh** [comment]
I don't have output, but I know it takes about 5.5 hours to build this stack in a VM with 12 cores. I usually run this overnight when I merge Spack into my local fork or make a change to one of my own packages. I can run produce some timings from my next run if anyone is interested.

autoconf
automake
boost
cmake@2.8.10.2
cmake@3.5.2
cuda
datamash
gcc@4.9.2~binutils
gcc@5.3.0~binutils
gcc@6.1.0~binutils
jdk
go
libhio
libtool
openmpi
parallel
python@2.7.11
python@3.5.1
ruby
cgns
trilinos (my own version)
R + about half of of the R libraries
Several of my own packages, may take up 30 min

I haven't been able to specify multiple specs per 'spack install' so a lot of time is spent redundantly concretizing the dependency dag. I also notice that most build systems don't effectively utilize CPU parallelism, instead spending a lot of time in serial linker steps, or corners of the build tree where the work can span more than a couple cores.

@tgamblin farming each package to a node may be faster, but it doesn't scale well in terms of resources from my experience, since large packages share a mountain of common dependencies.

**Comment by tgamblin** [comment]
@sknigh: thanks!

RE: Locking: we'd lock things at the package level *within* the DAG (with a lock in $prefix/.spack) so one package would benefit from others' dependencies.  This would require a shared file system like we have on LLNL clusters.  I believe Amazon has a similar capability, but I haven't sorted the details for that, or whether it would support fcntl locks like NFS or Lustre.

Do you know how much time is spent concretizing and whether it is helped by the recent PR for faster virtuals?  I'd be surprised if it was a significant chunk of 5.5 hours but would definitely want to know.

**Comment by sknigh** [comment]
@tgamblin It may DAG resolution itself. I notice spack CLI becomes sluggish when the number of installations increases, which results in spack hanging between invocation and printing progress. I can throw together a script to quantify this tonight.

**Comment by adamjstewart** [comment]
@sknigh I observed the same thing. With over 500 packages installed, a simple `spack activate` or `spack uninstall` of a Python package could take over 2 minutes.

**Comment by tgamblin** [comment]
@sknigh: that would be great.  We can try to speed that up.  If you do this, can you tar up all the $prefix/.spack directories in your install tree and attach them to another issue?  That would let me test with your install tree.

**Comment by tgamblin** [comment]
@adamjstewart: any chance you can  send me your .spack directories too?  I have accounts at ALCF if it need to stay private.

**Comment by eschnett** [comment]
Instead of installing packages individually, I find it more convenient to create a single meta-package that has all the other packages as dependencies, and then install that meta-package. This also has the advantage that all the dependencies are automatically compatible with each other. The time that Spack needs to resolve dependencies is negligible.

There are some issues if the install is interrupted; it might e.g. be necessary to manually remove a half-written directory, and such interruptions are more frequent than I'd like (downloads failing for various reasons, and sometimes spurious build problems due to race conditions in makefiles).

**Comment by eschnett** [comment]
So I build some packages. I need to fetch them ahead of time, retrying if there is a failure, because downloading is apparently too brittle.

The problem now: A `spack reindex` after installing the packages fails. The error is
```
+ spack reindex
Traceback (most recent call last):
  File "/home/spacktest/spacktest/spack/bin/spack", line 184, in <module>
    main()
  File "/home/spacktest/spacktest/spack/bin/spack", line 161, in main
    return_val = command(parser, args)
  File "/home/spacktest/spacktest/spack/lib/spack/spack/cmd/reindex.py", line 31, in reindex
    spack.installed_db.reindex(spack.install_layout)
  File "/home/spacktest/spacktest/spack/lib/spack/spack/database.py", line 322, in reindex
    self._check_ref_counts()
  File "/home/spacktest/spacktest/spack/lib/spack/spack/database.py", line 354, in _check_ref_counts
    (key, found, expected, self._index_path))
AssertionError: Invalid ref_count: ypftppxj6v5u2xojmmem4zy2z7o4w2dz: 0 (expected 1), in DB /home/spacktest/spacktest/spack/opt/spack/.spack-db/index.yaml
```

Everything is stored in a Docker image. What data do you need to track down the problem?

**Comment by eschnett** [comment]
The first round of integration tests succeeded. [Here](https://github.com/eschnett/spack-test/blob/master/ISSUES.md) is a list of the issues I am encountering.

**Comment by ax3l** [comment]
Would it help to add a status-page as in [conda forge](https://conda-forge.github.io/), too? So one could see at a glance which package (recipes) are currently tested/broken.

**Comment by eschnett** [comment]
The way I set up the integration tests doesn't really allow for a per-package status, as I'm installing all packages at once. I'm doing this since this is the real-world case I want to test -- I want to end up with a set of packages that are all compatible with each other.

I have a page [ISSUES.md](https://github.com/eschnett/spack-test/blob/master/ISSUES.md) where I manually list all the issues I've encountered, including their Spack issue numbers.

So far, Spack managed to go through the test (with all problematic steps disabled!) just once. After that, Qthreads broke, and it took a few days to get that fixed; then I enabled a few new packages (Tau and friends, and Trilinos) that don't build (didn't investigate that yet). Then a few builds failed because certain packages didn't download -- those are usually spurious problems that go away, so I'm just retrying.

I'm running the test again; if it succeeds, I'll update the list of issues, and I'll also post the complete build log somewhere.

**Comment by davydden** [comment]
@eschnett You might want to add links to you ISSUES.md file, i.e. 

```
Might be related to [LLNL/spack#1487](https://github.com/LLNL/spack/issues/1487)
```

because currently there are no links to the corresponding pages.

> PETSc and Trilinos require hypre ~internal-superlu, but Spack's dependency resolution does not choose this variant. Instead, Spack aborts with an error.

i did not see this issue when building `dealii` which uses both petsc and trilinos.

**Comment by alalazo** [comment]
Can we close this, now that we build `hypre` as part of Travis tests?

**Comment by alalazo** [comment]
relates to #2917

**Comment by alalazo** [comment]
Closing since we have support for [CI pipelines](https://spack.readthedocs.io/en/latest/pipelines.html). Public dashboards, binary packages are also expected at a later point. Feel free to reopen if you disagree.
