### ISSUE TITLE
Installation issue: libsm

### ISSUE THREAD

**Issue by sethrj** [spack/spack#15082]
### Steps to reproduce the issue

```console
$ spack install libsm
```
fails to build with the error:
```
sm_genid.c:101:11: fatal error: uuid/uuid.h: No such file or directory
 # include <uuid/uuid.h>
           ^~~~~~~~~~~~~
compilation terminated.
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux emmet 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Wed Nov 27 01:11:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.1 (Ootpa)
``` 

### Additional information

Libuuid installs `include/uuid.h`, although on some platforms I've seen `/usr/include/uuid/uuid.h`.

```
$ spack spec libsm
Input spec
--------------------------------
libsm

Concretized
--------------------------------
libsm@1.2.2%gcc@8.3.1 arch=linux-rhel8-haswell
    ^libice@1.0.9%gcc@8.3.1 arch=linux-rhel8-haswell
        ^pkgconf@1.6.3%gcc@8.3.1 arch=linux-rhel8-haswell
        ^util-macros@1.19.1%gcc@8.3.1 arch=linux-rhel8-haswell
        ^xproto@7.0.31%gcc@8.3.1 arch=linux-rhel8-haswell
        ^xtrans@1.3.5%gcc@8.3.1 arch=linux-rhel8-haswell
    ^uuid@1.6.2%gcc@8.3.1 arch=linux-rhel8-haswell
```

**Comment by adamjstewart** [comment]
Try adding a dependency on `libuuid`

**Comment by sethrj** [comment]
@adamjstewart This was after adding the libuuid dependency: as I wrote, libuuid installs directly to `include/uuid.h`, *not* to `include/uuid/uuid.h` as `libsm` seems to require.

I don't have time to debug this right now, so I'm working around it by disabling X11 support for the downstream package (ROOT) that required this. I thought it would be good to catalog the issue for the next time I (or someone else) hit this error.

**Comment by sethrj** [comment]
Mainly I don't want to figure out *how* `libsm` works on any platform, unless it's just that most systems install to that subdirectory.

**Comment by KineticTheory** [comment]
I ran into a similar issue today while trying to build _visit_.  In my case _visit_ indrectly depends on _libsm_, but _libsm_ had undefined symbols that are satisfied by _libuuid_.  Adding `depends_on('libuuid') fixed this for me.  I'll submit a PR shortly.

**Comment by sethrj** [comment]
Sadly this is still failing for me when linking against `qt@4.8.7` -- perhaps because it's using the system `libsm` instead of a spack-provided one. Trying that now.

**Comment by sethrj** [comment]
Sorry, to be clear: libsm isn't failing; it's code downstream of qt that's failing.

[Commented without scrolling back up to the top 😬 ]

**Comment by sethrj** [comment]
Annnd adding the missing dependency to qt fixes everything. Yay!

**Comment by ikitayama** [comment]
Hi, I am still seeing this as of this writing, can someone open this up again? Loading libuuid does not help.

**Comment by sethrj** [comment]
@ikitayama If your concretization/build error/platform is different, can you open a new issue that links to this one?

**Comment by ikitayama** [comment]
On Fugaku login node I see:
```
$ spack spec libsm
Input spec
--------------------------------
libsm

Concretized
--------------------------------
libsm@1.2.3%gcc@10.2.0 arch=linux-rhel8-cascadelake
    ^libice@1.0.9%gcc@10.2.0 arch=linux-rhel8-cascadelake
        ^pkgconf@1.7.3%gcc@10.2.0 arch=linux-rhel8-cascadelake
        ^util-macros@1.19.1%gcc@10.2.0 arch=linux-rhel8-cascadelake
        ^xproto@7.0.31%gcc@10.2.0 arch=linux-rhel8-cascadelake
        ^xtrans@1.3.5%gcc@10.2.0 arch=linux-rhel8-cascadelake
    ^libuuid@1.0.3%gcc@10.2.0 arch=linux-rhel8-cascadelake
    ^uuid@1.6.2%gcc@10.2.0 arch=linux-rhel8-cascadelake
```
