### ISSUE TITLE
Packaging Guide incorrectly shows CMakePackage using configure_args. 

### ISSUE THREAD

**Issue by frobnitzem** [spack/spack#15098]
The package creation documentation for `CMakePackage`-s incorrectly shows `configure_args()`, when it should use `cmake_args()`.

The relevant code block appears in this section:
https://spack.readthedocs.io/en/latest/packaging_guide.html#cmakepackage

This leads to `spack install` silently discarding all build options.

**Comment by adamjstewart** [comment]
Thanks for the bug report, this will be fixed by #15102 

For the record, those docs are pretty useless. Take a look at https://spack.readthedocs.io/en/latest/build_systems/cmakepackage.html if you're trying to write a CMakePackage.
