### ISSUE TITLE
separate spack installations for different processor architectures

### ISSUE THREAD

**Issue by cjlegg** [spack/spack#15120]
I would like to have separate spack installations to hold packages for different processor architectures (which are on different machines) but where both processors use the same network file share . I know it is supposed to be possible for them to share one spack installation but one system (an aarch54) is a bit slow and has corrupted the installation a couple of times. 

I have tried cloning spack into a different directory ("armspack") but it spack on first opertation creates the auxiliary directory ".spack". My other installation (for Intel processors) would also want to use ".spack". Can I in fact control the name of this auxiliary directory? I cannot find a setting for it.

**Comment by alalazo** [comment]
It's not clear to me what you want to achieve. Do you want to install software in different roots (so different JSON DBs) depending on your architecture while still using a single Spack instance? If so why not using two different checkouts of Spack?

**Comment by cjlegg** [comment]
Good Morning Massimiliano

I did try two different checkouts of spack but they both wanted to create ~/.spack, which would then have been shared between the two. Presumably that would have caused errors.

I have now worked around this by redefining $HOME on one of the systems. That seems not to have caused any other problems outside spack for that system.

I wanted to have separate spack installations because one of the two systems has very slow access to the network share and was crashing while running spack and corrupting things.

Regards
James

**Comment by alalazo** [comment]
> I did try two different checkouts of spack but they both wanted to create ~/.spack, which would then have been shared between the two. Presumably that would have caused errors.

Ah ok, now I get it - the default user scope of our configuration files is getting in the way. We have a hierarchical management of configuration (see [here](https://spack.readthedocs.io/en/latest/configuration.html#configuration-scopes) for details) but to make a long story short: you can make it work even without doing hacks on your systems. Just place a `config.yaml` file with custom location for the `install_tree`:
```yaml
config:
  install_tree: /your/custom/folder
```
in each of the checkout under the "site" configuration scope. To do this:
```console
$ spack config --scope site edit config
```
Once you're done you can check the actual configuration by:
```console
$ spack config blame config
```
and check the line setting `install_tree`. Hope this helps.

**Comment by cjlegg** [comment]
Hi Massimiliano

Not yet sure that that will work.

First – do we agree what a “checkout” means? I think it means the result of

git clone https://github.com/spack/spack.git <spack-directory>
cd <spack-directory>
git checkout git checkout releases/v0.13

I have two of these with different values of <spack-directory>, one for each type of system, which have different processors.

I can see that I should change settings in the site config file because those are located in those two different <spack-directory>.

However, when I look in the defaults config.yaml, I find:

  install_tree: $spack/opt/spack

where $spack is the same thing as the <spack-directory> above and so I will be getting two different install trees, without having to change this setting.

The clash between the two systems that I saw is that they want to create the same ~/.spack hidden directory (there is a dot between the ‘/’ and the ‘s’). Looking in the defaults config file there are two uses of ~/.spack :

~/.spack/stage is one of the entries for build_stage
misc_cache: ~/.spack/cache

Those could be modified in the two site config files to have different values for “.spack”

However at the top of the defaults config file there is a comment:

# Per-user settings (overrides default and site settings):
#   ~/.spack/config.yaml

This suggests that ~/.spack is hard coded for the location of the user settings. This is not a problem since if I am the user I can make sure I leave this blank or check that the settings in there work for both spack installations.

Also, my ~/.spack contains two folders ‘cache’ and ‘linux’ but I cannot see a default setting for where a directory called ‘linux’ would go. That would not be covered by changing the values ~/.spack/stage and ~/.spack/cache in the site config file. The linux folder contains the compilers.yaml file – this file would be shared between my two installations – I have tried including complier entries for both systems in the same file but with different target values (the compiler paths are accidentally the same) but one system errored, I think complaining about a value [] – can’t remember which line. Anyway I need to control where the user compilers.yaml file is put, which would be easiest by telling spack to use another value for ~/.spack

Or have I misunderstood?

Regards
James

**Comment by alalazo** [comment]
> Anyway I need to control where the user compilers.yaml file is put, which would be easiest by telling spack to use another value for ~/.spack

There are issues already open for `~/.spack` since it is a nasty "global" setting scope that can cause  failures on heterogeneous clusters. I don't see why `compilers.yaml` should be an issue here (it supports compilers for different architectures) but that said, delete your `compilers.yaml` file in `~/.spack` and from each of your Spack instances run:
```console
$ spack compiler find --scope=site
==> Added 13 new compilers to /home/culpo/PycharmProjects/spack/etc/spack/compilers.yaml
    gcc@9.0.1  gcc@7.4.0  gcc@5.5.0  clang@9.0.0  clang@7.0.0  clang@5.0.1  clang@3.9.1
    gcc@8.3.0  gcc@6.5.0  gcc@4.8    clang@8.0.0  clang@6.0.1  clang@4.0.1
==> Compilers are defined in the following files:
    /home/culpo/PycharmProjects/spack/etc/spack/compilers.yaml
```
As you can see the compiler configuration file is created in the "site" scope within the Spack instance and not in the higher priority "user" scope.

**Comment by cjlegg** [comment]
Thanks

That looks like it will solve my current problem! I will keep a look out for the ~./spack global setting being resolved.

Regards
James

**Comment by alalazo** [comment]
Feel free to close the issue if there are no further questions :slightly_smiling_face:

**Comment by cjlegg** [comment]
Closing - problem reduced to the issue of the the location of the ~/.spack being a global fixed value, which is addressed in other issue threads
