### ISSUE TITLE
Strange Travis.CI error for tar.bz2 files

### ISSUE THREAD

**Issue by Mentors4EDU** [spack/spack#15137]
Hi, for pull requests when I tried having the download URL in the package.py file as a link to a tar.bz2 file, it gave me an error in the Travis.CI  build saying unable to recognize a tar file, when I changed the link to a tar.gz file of the same source and everything, it was able to pass that check. In the readthedocs documentation, it uses a tar.bz2 file as an example of the archive fetched with the `spack create` command. This seems to be a problem with Travis.CI, but I'm wondering if there is a fix in the Travis.CI config that may fix this? Anyways, just something I wanted to divert your attention to because lots of new packages may have the Travis CI check failed for that particular reason.

**Comment by adamjstewart** [comment]
Can you point me to an example so I can see the error message?

Travis CI fails sometimes for mysterious reasons, completely unrelated to the content of the PR. I suspect that is the case here.

**Comment by adamjstewart** [comment]
If you're talking about [this error message](https://travis-ci.org/spack/spack/jobs/653144551?utm_medium=notification&utm_source=github_status), I think that's a transient error unrelated to your PR, although I've never seen this specific transient error before.

**Comment by Mentors4EDU** [comment]
I was referring to that error message, the strange thing is it doesn't exist when I change the file format to tar.gz.  Maybe it is just a unique use case.

**Comment by adamjstewart** [comment]
Nah, there are hundreds of packages in Spack that use tar.bz2, that shouldn’t be the issue. Can you open a new PR to test my theory out?

**Comment by Mentors4EDU** [comment]
Okay, I will create a new test pull request when I get on my laptop to test your theory out and let you know by commenting on this issue

**Comment by Mentors4EDU** [comment]
Hey just tested via this [build](https://travis-ci.org/spack/spack/builds/653243734) and pull request #15142, looks like you are right, the 2nd build was just the unlucky build in which travis.cli failed check for some dubious or transient reason.
