### ISSUE TITLE
The latest versions in the qt package do not build with the default variant of ~opengl

### ISSUE THREAD

**Issue by glennpj** [spack/spack#15140]
Building qt with version 5.14.0 and 5.14.1 fails when using the default variants.
```console
$ spack spec qt
Input spec
--------------------------------
qt

Concretized
--------------------------------
qt@5.14.1%gcc@9.1.0~dbus~examples~framework freetype=spack ~gtk~opengl patches=7f34d48d2faaa108dc3fcc47187af1ccd1d37ee0f931b42597b820f03a99864c ~phonon+shared+sql+ssl+tools~webkit arch=linux-centos7-broadwell
```
```console
$ spack install qt
...
Project ERROR: Unknown module(s) in QT: openglextensions
make[2]: *** [sub-render-make_first-ordered] Error 3
make[2]: Leaving directory `/dev/shm/gpjohnsn/spack-stage-qt-5.14.1-cnekp76zrea4huo5umgj2yz7vhkd33m2/spack-src/qtquick3d/src'
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory `/dev/shm/gpjohnsn/spack-stage-qt-5.14.1-cnekp76zrea4huo5umgj2yz7vhkd33m2/spack-src/qtquick3d'
make: *** [module-qtquick3d-make_first] Error 2
make: *** Waiting for unfinished jobs....
```
If `+opengl` is set then it builds fine. The previous version, 5.13.1 builds fine with both `~opengl` and `+opengl`.

**Comment by rubendibattista** [comment]
I'm also hitting a build error with `qt`. 
```
/home2/softmassot/spack2/linux-centos7-x86_64/gcc-9.2.0/qt-5.14.1-l4d5zetpw4u4hzozwm5scojrcz5ukkmu/bin/qhelpgenerator: symbol lookup error: /home2/softmassot/spack2/linux-centos7-x86_64/gcc-9.2.0/qt-5.14.1-l4d5zetpw4u4hzozwm5scojrcz5ukkmu/plugins/sqldrivers/libqsqlite.so: undefined symbol: sqlite3_column_table_name16
```

@glennpj  The part of the log you posted is not relevant. The real error should be a bit before. Can you attach the log, maybe?

**Comment by glennpj** [comment]
@rubendibattista I am not sure why you say the part of the log that I posted is irrelevant. That is the error that causes the build to abort. As I said, setting `+opengl` works fine so there seems to be something amiss with regard to opengl.

[spack-build-out.txt](https://github.com/spack/spack/files/4236709/spack-build-out.txt)

**Comment by rubendibattista** [comment]
@glennpj sorry, I said that because I'm dumb. It's clearly very relevant, I missed the first line. 👍

Thanks for the log.

**Comment by sethrj** [comment]
Now starting to build to see what's up:
```
 qt@5.14.1%gcc@8.3.0~dbus~examples~framework freetype=spack ~gtk~opengl patches=7f34d48d2faaa108dc3fcc47187af1ccd1d37ee0f931b42597b820f03a99864c ~phonon+shared+sql+ssl+tools~webkit arch=linux-rhel7-skylake_avx512
```

**Comment by sethrj** [comment]
Yeah, this is clearly because the QT maintainers can't test every possible combination of disabling things, and some unintentional dependencies have crept in between packages. I think that adding `-skip qtquick3d` will fix this; testing now.
