### ISSUE TITLE
Remove 'spack bootstrap' from the commands

### ISSUE THREAD

**Issue by alalazo** [spack/spack#15145]
As a Spack maintainer I want to remove the `spack bootstrap` command (outdated since #14062) so that I could reduce the amount of boilerplate code in the project.

### Rationale

The `spack bootstrap` command was used to "Bootstrap packages needed for spack to run smoothly" and in reality it has always just installed `environment-modules~X`. Since #14062 shell integration  doesn't require `environment-modules` anymore making the command outdated. I would  therefore remove that command from the code base.

### Description

Just remove the command and any test / package associated only with it.

### Additional information

Opening the issue to check what is the consensus towards this.

**Comment by adamjstewart** [comment]
@tgamblin how are we going to handle Spack installation once it depends on clingo? Will the `spack bootstrap` command be repurposed for this?

**Comment by tgamblin** [comment]
This should happen.  For Clingo (or Z3) I don't think we can expect people to run a command to install them -- I expect that to work more like how we handle `patchelf` (or, ideally, better)

**Comment by tgamblin** [comment]
I put this in for 0.15.
