### ISSUE TITLE
Spack continues installing packages after failure

### ISSUE THREAD

**Issue by wortiz** [spack/spack#15182]
After a build failed spack will print out "Skipping build of ... since ... failed" but will continue building other packages

This occurs with KeyboardInterrupt as well

### Steps to reproduce the issue

```console
$ spack install package
(Send interrupt e.g. Ctrl-C)
...
```

### Error Message

```
 $ spack install git
==> 29647: Installing libsigsegv
==> Fetching https://ftpmirror.gnu.org/libsigsegv/libsigsegv-2.12.tar.gz
################################################################################# 100.0%
==> Staging archive: /tmp/wortiz/spack-stage/spack-stage-libsigsegv-2.12-yo4g77w4jxsh46lj4pdo3oo6szee7bjk/libsigsegv-2.12.tar.gz
==> Created stage in /tmp/wortiz/spack-stage/spack-stage-libsigsegv-2.12-yo4g77w4jxsh46lj4pdo3oo6szee7bjk
==> No patches needed for libsigsegv
==> 29647: libsigsegv: Building libsigsegv [AutotoolsPackage]
==> 29647: libsigsegv: Executing phase: 'autoreconf'
==> 29647: libsigsegv: Executing phase: 'configure'
==> Error: Exception occurred in writer daemon!
==> Error: Failed to install libsigsegv due to KeyboardInterrupt: 
Traceback (most recent call last):
  File "/home/wortiz/spack/lib/spack/llnl/util/tty/log.py", line 434, in _writer_daemon
    rlist, _, _ = select.select(istreams, [], [])
KeyboardInterrupt
==> Warning: Skipping build of m4 since libsigsegv failed
==> Warning: Skipping build of git since m4 failed
==> Warning: Skipping build of autoconf since m4 failed
==> Warning: Skipping build of automake since autoconf failed
==> Warning: Skipping build of libtool since m4 failed
==> 29647: Installing pkgconf
==> Fetching http://distfiles.dereferenced.org/pkgconf/pkgconf-1.6.3.tar.xz
################################################################################# 100.0%
==> Staging archive: /tmp/wortiz/spack-stage/spack-stage-pkgconf-1.6.3-wyezssuqshd4wismk2i4s6ppx3lilnqc/pkgconf-1.6.3.tar.xz
==> Created stage in /tmp/wortiz/spack-stage/spack-stage-pkgconf-1.6.3-wyezssuqshd4wismk2i4s6ppx3lilnqc
==> No patches needed for pkgconf
```

### Information on your system

Ubuntu 18.04
 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)

packages.yaml
```
packages:
  parmetis:
    variants: build_type=Release
  trilinos:
    variants: +teko+superlu-dist+chaco build_type=Release
  superlu-dist:
    variants: build_type=Release
  all:
    compiler: [gcc]
    providers:
      mpi: [mpich, openmpi]
      blas: [openblas, intel-mkl]
      lapack: [openblas, intel-mkl]
```

**Comment by tldahlgren** [comment]
The intention behind the recent addition of distributed build support was "best effort" installation of dependencies across the DAG should there be a failure.

@tgamblin Given this request, should we reconsider the process for `KeyboardInterrupt`s?

**Comment by srinathv** [comment]
I second the need to halt all builds with Ctrl-C

**Comment by tgamblin** [comment]
@tldahlgren: `Ctrl-C` on a single `spack install` shoudl really halt everything, so yes we should propagate that to children.

I'm not sure how that changed -- I must've missed that the new installer logic does not halt on `Ctrl-C`.  I think we should do two things:

1. Fix `Ctrl-C`
2. Have an option like this for `spack install`:
    ```
    --fail=fast     stop all builds if any build fails (default is best effort)
    ```

Thoughts?

**Comment by tldahlgren** [comment]
> @tldahlgren: `Ctrl-C` on a single `spack install` shoudl really halt everything, so yes we should propagate that to children.

I did not distinguish `Ctrl-C` from other errors coming from the build but this should be an easy fix (that I was just about to take a look at).

> 
> I'm not sure how that changed -- I must've missed that the new installer logic does not halt on `Ctrl-C`. I think we should do two things:
> 
>     1. Fix `Ctrl-C`
> 
>     2. Have an option like this for `spack install`:
>        ```
>        --fail=fast     stop all builds if any build fails (default is best effort)
>        ```
> 
> 
> Thoughts?

I like the idea of the fail fast option. Calling it out like this helps document the capability.

**Comment by tldahlgren** [comment]
> > 
> > 2. Have an option like this for `spack install`:
> >    ```
> >    --fail=fast     stop all builds if any build fails (default is best effort)
> 
> I like the idea of the fail fast option. Calling it out like this helps document the capability.

@tgamblin I assume this should apply whether the current or another process is building the package.  That is, if we detect that another process has marked the build of a dependency as failed, then the current process -- that specified this option -- should terminate.  Is that correct?

**Comment by tldahlgren** [comment]
> > @tldahlgren: `Ctrl-C` on a single `spack install` shoudl really halt everything, so yes we should propagate that to children.
> 
> I did not distinguish `Ctrl-C` from other errors coming from the build but this should be an easy fix (that I was just about to take a look at).

I should point out that two `ctrl-c`'s in a row will terminate a build using `develop`, e.g.,:
```
==> Error: Failed to install unzip due to KeyboardInterrupt: 
==> Error: Installation of lua failed.  Review log for details
```
