### ISSUE TITLE
spack install package only fails

### ISSUE THREAD

**Issue by tldahlgren** [spack/spack#15196]
This issue was reported on slack earlier today by scottwittenburg.  The problem occurs during their two-pass install process:

```
spack install --cache-only --only dependencies <path-to-spec.yaml>
spack install --no-cache --only package <path-to-spec.yaml>
```

which results in :

```
==> [2020-02-24-21:20:30.689327, 754] Error: Detected uninstalled dependencies for ncurses: {'pkgconf'}
==> [2020-02-24-21:20:30.689430, 754] InstallError: Cannot proceed with ncurses: 1 uninstalled dependency: pkgconf
==> [2020-02-24-21:20:30.689467, 754] Error: Cannot proceed with ncurses: 1 uninstalled dependency: pkgconf
```

This issue can be reproduced by attempting ``spack install --only package <spec>`` for any package.

**Comment by scottwittenburg** [comment]
Thanks @tldahlgren 😄 Though is it true that the package has to have uninstalled dependencies for this error to happen?  In my case, I'm pretty sure the dependencies are installed.  I'll double check though.

**Comment by tldahlgren** [comment]
> Thanks @tldahlgren 😄 Though is it true that the package has to have uninstalled dependencies for this error to happen? In my case, I'm pretty sure the dependencies are installed. I'll double check though.

Thanks for catching that misstatement.  My mind was still in "unit test creation" mode when I wrote that comment.  I've since corrected the description.
