### ISSUE TITLE
paraview rhel 8 qt build error

### ISSUE THREAD

**Issue by schrummy14** [spack/spack#15207]
Error in qt 5.14 while trying to build paraview on rhel 8. Strangest error goes to failing to find 
#include <windows.system.h>

Any ideas are greatly appreciated. 

### Steps to reproduce the issue

```console
$ spack install -j4 paraview@5.6.2+qt+python3 ^mesa~llvm ^python@3.6.8

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux myPC 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Wed Nov 27 01:11:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
Description:	Red Hat Enterprise Linux release 8.1 (Ootpa)
``` 
Install status:
[install-status.txt](https://github.com/spack/spack/files/4250530/install-status.txt)

### Additional information
Rebuilding the package with the following options:
```console
$ spack -d install -j 1 <spec>
...
```
will provide additional debug information. After the failure you will find two files in the current directory:

1. 
[spack-cc-qt-p5hlomy.in.log](https://github.com/spack/spack/files/4250641/spack-cc-qt-p5hlomy.in.log)
 
2.
[spack-cc-qt-p5hlomy.out.log](https://github.com/spack/spack/files/4250643/spack-cc-qt-p5hlomy.out.log)

**Comment by sethrj** [comment]
@schrummy14 Can you send the full `spack-build-out.txt` file? The files you send just show what Spack's compiler wrappers are doing, not the output from QT.

**Comment by sethrj** [comment]
@schrummy14 I just successfully installed QT@5+opengl:
```
-- linux-rhel8-haswell / gcc@8.3.1 ------------------------------
qt@5.14.1~dbus~examples~framework freetype=spack ~gtk+opengl patches=7f34d48d2faaa108dc3fcc47187af1ccd1d37ee0f931b42597b820f03a99864c ~phonon+shared+sql+ssl+tools~webkit
    double-conversion@2.0.1 build_type=RelWithDebInfo
    fontconfig@2.13.1
        font-util@1.3.2 fonts=encodings,font-adobe-100dpi,font-adobe-75dpi,font-adobe-utopia-100dpi,font-adobe-utopia-75dpi,font-adobe-utopia-type1,font-alias,font-arabic-misc,font-bh-100dpi,font-bh-75dpi,font-bh-lucidatypewriter-100dpi,font-bh-lucidatypewriter-75dpi,font-bh-ttf,font-bh-type1,font-bitstream-100dpi,font-bitstream-75dpi,font-bitstream-speedo,font-bitstream-type1,font-cronyx-cyrillic,font-cursor-misc,font-daewoo-misc,font-dec-misc,font-ibm-type1,font-isas-misc,font-jis-misc,font-micro-misc,font-misc-cyrillic,font-misc-ethiopic,font-misc-meltho,font-misc-misc,font-mutt-misc,font-schumacher-misc,font-screen-cyrillic,font-sun-misc,font-winitzki-cyrillic,font-xfree86-type1
        freetype@2.10.1
            bzip2@1.0.8+shared
            libpng@1.6.37
                zlib@1.2.11+optimize+pic+shared
        libuuid@1.0.3
        libxml2@2.9.9~python
            libiconv@1.16
            xz@5.2.4
    glib@2.56.3~libmount patches=c325997b72a205ad1638bb3e3ba0e5b73e3d32ce63b2d0d3282f3e3a2ff4663c tracing=none
        gettext@0.20.1+bzip2+curses+git~libunistring+libxml2+tar+xz
            ncurses@6.1~symlinks+termlib
            tar@1.32
        libffi@3.2.1
        pcre@8.43~jit+multibyte+utf
        perl@5.30.1+cpanm+shared+threads
            gdbm@1.18.1
                readline@8.0
        python@3.7.6+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib
            expat@2.2.9+libbsd
                libbsd@0.10.0
            openssl@1.1.1d+systemcerts
            sqlite@3.30.1~column_metadata+fts~functions~rtree
    harfbuzz@2.3.1~graphite2
        cairo@1.16.0~X~fc~ft~gobject patches=7c4da77767fe9feb03f8051def0832f0c67f99162913275cfa127a88df19cf51 ~pdf~png~svg
            pixman@0.38.4
        icu4c@65.1 cxxstd=11
    libjpeg-turbo@2.0.3
    libmng@2.0.3 build_type=RelWithDebInfo
        lcms@2.9
            libtiff@4.0.10
    libx11@1.6.7
        kbproto@1.0.7
        libxcb@1.13
            libpthread-stubs@0.4
            libxau@1.0.8
                xproto@7.0.31
            libxdmcp@1.1.2
        xextproto@7.3.0
    libxext@1.3.3
    libxkbcommon@0.8.2
        util-macros@1.19.1
        xkbdata@1.0.1
    libxrender@0.9.10
        renderproto@0.11.1
    mesa@18.3.6+glx+llvm+opengl~opengles+osmesa patches=55a5611ca9fcbe8324c4d68a07b338134954ff12c5b122dc78ff376f012a1414 swr=none
        llvm@9.0.1~all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb~omp_tsan patches=332fe65f78b2b4a242045ec2394eee8db631fbcbe27b0016d5e5c859e34f47af +polly~python~shared_libs
            binutils@2.33.1+gold~headers~libiberty+nls~plugins
            libedit@3.1-20191231
            swig@4.0.0
    pcre2@10.31+multibyte
    xcb-util-image@0.4.0
        xcb-util@0.4.0
    xcb-util-keysyms@0.4.0
    xcb-util-renderutil@0.3.9
    xcb-util-wm@0.4.1
```

**Comment by schrummy14** [comment]
Here are the full files
[spack-build-env.txt](https://github.com/spack/spack/files/4251727/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4251728/spack-build-out.txt)

I see that you were able to do this using llvm to compile mesa. Is there a way not to do it this way.
I am trying to only use gcc compilers and I ran into a giant hickup that was caused my installing mesa with llvm enabled.

**Comment by sethrj** [comment]
@schrummy14 The only build error in your file is from `ld` (the previous "errors" are just QT's configure testing your system):
```
/usr/bin/ld: /home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/double-conversion-2.0.1-pian5hmpgsn5ozarzkv5ekdjphxlz3k6/lib/libdouble-conversion.a(bignum.cc.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/double-conversion-2.0.1-pian5hmpgsn5ozarzkv5ekdjphxlz3k6/lib/libdouble-conversion.a(bignum.cc.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/double-conversion-2.0.1-pian5hmpgsn5ozarzkv5ekdjphxlz3k6/lib/libdouble-conversion.a(double-conversion.cc.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/double-conversion-2.0.1-pian5hmpgsn5ozarzkv5ekdjphxlz3k6/lib/libdouble-conversion.a(double-conversion.cc.o): unable to initialize decompress status for section .debug_info
/home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/double-conversion-2.0.1-pian5hmpgsn5ozarzkv5ekdjphxlz3k6/lib/libdouble-conversion.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1199: ../../lib/libQt5Core.so.5.14.1] Error 1
```

Maybe it's a problem with your system's `ld`? Mine is:
```
$ /usr/bin/ld --version
GNU ld version 2.30-58.el8_1.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by sethrj** [comment]
Actually this is looking like it is indeed an error with your installation of binutils: [other people have similar errors due to an incompatibility between specific versions of libelf and binutuils](https://bbs.archlinux.org/viewtopic.php?id=242682)

**Comment by schrummy14** [comment]
Here is mine.
$ /usr/bin/ld --version
GNU ld version 2.30-58.el8
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

**Comment by sethrj** [comment]
@schrummy14 It looks like my (working) version is a more patched version of the one you have. I recommend using `dnf` to update your system toolchain and completely reinstall spack (or possibly just reinstall double-conversion if you feel lucky). This is almost certainly not an issue with QT.

**Comment by schrummy14** [comment]
Thank you for the help, I will try that and get back.

I did try reinstalling binutils but the same version was installed...

**Comment by schrummy14** [comment]
That did the trick to get QT to install. 
The Paraview build failed again but it failed on Paraview. I am running it to get debug info to investigate further. 

Thank you

**Comment by schrummy14** [comment]
... I do not like doing this but the Paraview build failed due to the following:
/home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/qt-5.14.1-p5hlomyuhbezq22wgag5vfwrjokpr73e/bin/qhelpgenerator: symbol lookup error: /home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/qt-5.14.1-p5hlomyuhbezq22wgag5vfwrjokpr73e/plugins/sqldrivers/libqsqlite.so: undefined symbol: sqlite3_column_table_name16

I think this is an issue with documentation building but I do not know for sure...

**Comment by sethrj** [comment]
Could you search for similar errors and open a new issue since this is about paraview and SQLite, not qt? Thanks!

**Comment by schrummy14** [comment]
Will do
