### ISSUE TITLE
sqlite look up table error while building Paraview

### ISSUE THREAD

**Issue by schrummy14** [spack/spack#15248]
### Steps to reproduce the issue
```console
$ spack install -j1 paraview@5.6.2+qt+python3 ^mesa~llvm ^python@3.6.8
... # and the relevant part of the error 
/home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/qt-5.14.1-p5hlomyuhbezq22wgag5vfwrjokpr73e/bin/qhelpgenerator: symbol lookup error: /home/mschramm/spack/opt/spack/linux-rhel8-broadwell/gcc-8.3.1/qt-5.14.1-p5hlomyuhbezq22wgag5vfwrjokpr73e/plugins/sqldrivers/libqsqlite.so: undefined symbol: sqlite3_column_table_name16
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux mschramm-precision-tower-5810.ae.iastate.edu 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Wed Nov 27 01:11:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
```

files:
[spack-build-out.tar.gz](https://github.com/spack/spack/files/4261996/spack-build-out.tar.gz)
[spack-build-env.tar.gz](https://github.com/spack/spack/files/4261997/spack-build-env.tar.gz)

**Comment by schrummy14** [comment]
Going to the sqldriver that is trying to be accessed and running:
`$ nm -D libqsqlite.so | grep sqlite3_column_table_name16`
allows me to see that the symbol is there.

**Comment by glennpj** [comment]
Try building with ^sqlite+column_metadata in the spec.

**Comment by adamjstewart** [comment]
@chuckatkins @danlipsa can you take a look at this? The `paraview` package contains:
```python
    # depends_on('sqlite') # external version not supported                     
```
but I wonder if we can hack things to make this work and add a dependency on `sqlite+column_metadata` as @glennpj suggests.

**Comment by schrummy14** [comment]
That did the trick. Thank you.
