### ISSUE TITLE
Spack spec for WRF and CFS

### ISSUE THREAD

**Issue by samcom12** [spack/spack#15246]
Can you please add spec for WRF and CFS ?

WRF link - https://github.com/wrf-model/WRF.git
CFS link - http://cfs.ncep.noaa.gov/cfsv2/cfsv2_source.tar.gz

Will appreciate your efforts in this regard :)

**Comment by tz-rrze** [comment]
there has already been some work on WRF; cf. #9851

**Comment by adamjstewart** [comment]
As always, contributions are always welcome 😄 

WRF is known to be a bit of a nightmare to package. I would start with other package managers like Easybuild that have WRF packaged already and try to convert their recipe to a Spack recipe.

**Comment by tz-rrze** [comment]
@g-mathias don't you have a proven WRF recipe in your local spack?
