### ISSUE TITLE
Issues fetching boost 

### ISSUE THREAD

**Issue by ikalash** [spack/spack#15280]
I am having issues installing boost using spack.  It seems there is an issue with the URL from which it attempts to fetch the package - please see below.  When I try to access 

https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2

I get a message that says "Forbidden!".  I tried this on a number of machines/browsers and it is always the same error.  I am building using the command: ``spack --insecure install --dirty --keep-stage boost``. 

```
==> 3278179: Installing boost
==> Fetching https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
#=#=-#   #                                                                                       
curl: (22) The requested URL returned error: 403 Forbidden
==> Failed to fetch file from URL: https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
    URL https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2 was not found!
==> Fetching from https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2 failed.
```

**Comment by adamjstewart** [comment]
@hainest

**Comment by ikalash** [comment]
Looks like if I change the following lines: https://github.com/spack/spack/issues/15280 by replacing them with the url in line 217, the boost checkout works fine.

**Comment by hainest** [comment]
@ikalash I'm not able to reproduce using 73f7301. 403 errors are often transient. Could you try again? If you are still getting the error with Spack, could you try fetching the tarball with wget?

**Comment by ikalash** [comment]
@hainest : I just tried it again and it works.  I wonder if the page was down or something like this over the weekend.  Anyway, closing the issue.
