### ISSUE TITLE
Installation issue: Paraview 5.4.2 cannot copy directory because it doesn't exist

### ISSUE THREAD

**Issue by schrummy14** [spack/spack#15320]
### Spack version
```console
$ spack --version
0.14.0-20-8d8925c72
```

### Steps to reproduce the issue

```console
spack install -j1 paraview@5.4.1+qt+python ^mesa~llvm ^python@2.7.16 ^sqlite+column_metadata ^py-pillow@6.2.2 ^qt@4.8.7 ^openssl@1.0.2t
# Error copying directory from "/tmp/mschramm/spack-stage/spack-stage-paraview-5.4.1-5s2xenpzmoqgqoxndanklslzr7iai6rl/spack-src/Plugins/StreamLinesRepresentatio
              n/doc" to "/tmp/mschramm/spack-stage/spack-stage-paraview-5.4.1-5s2xenpzmoqgqoxndanklslzr7iai6rl/spack-build/Plugins/StreamLinesRepresentation/doc"
```
### Platform and user environment

<!-- Please report your OS here:
```commandline
$ uname -a 
Linux mschramm-precision-tower-5810.ae.iastate.edu 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Wed Nov 27 01:11:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Red Hat Enterprise Linux release 8.1 (Ootpa)
``` 

[spack-build-out.zip](https://github.com/spack/spack/files/4287707/spack-build-out.zip)

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by luigi-calori** [comment]
I remember to have seen it while building in october.
had a patch but did not go for a PR as there were other issues , look at
https://github.com/RemoteConnectionManager/spack/commit/2788e8b67b8d0f983720c9fd8fba485e56f5bee2

**Comment by schrummy14** [comment]
Thanks, I have altered the patch to work with 5.4 and am currently rebuilding.

**Comment by luigi-calori** [comment]
In case it is working (if you have issues, in the same branch there is another commit I had to apply) It would be good to have a proper PR

**Comment by schrummy14** [comment]
The patch worked for me.
