### ISSUE TITLE
How to use rpc.h in libtirpc?

### ISSUE THREAD

**Issue by darmac** [spack/spack#15368]
I have a spack MakefilePackage which will use rpc.h in libtirpc.
I can add depends_on('libtirpc') in the package.py, but how can I use the rpc.h without changing Makefile? Is there any common rules for this situation?

**Comment by alalazo** [comment]
I think you have at least two options:
- Inject flags from the package, see [here](https://spack.readthedocs.io/en/latest/packaging_guide.html#compiler-flags)
- Set `CPATH` in `setup_build_environment` from the package

**Comment by darmac** [comment]
Got it , I'll try it.

**Comment by darmac** [comment]
@alalazo  and there is another question here:
I want to use `libblkid` in spack package util-linux, but my developed package configure can't find it.
I tried add `--with-libraries=<util-linux/lib/>` to `./configure` param, but it seems can not work.
Is there any suggestion to allow me add my own library path?
