### ISSUE TITLE
spack ci tests halt with preference list prompt

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#15366]
Spack's unit tests halt whenever they get to anything testing `ci.py` or `cmd/ci.py` and display the following prompt:
```
cmd/ci.py ......
Set preference list to:
     Cipher: AES256, AES192, AES, 3DES
     Digest: SHA512, SHA384, SHA256, SHA224, SHA1
     Compression: ZLIB, ZIP, Uncompressed
     Features: MDC, Keyserver no-modify
Really update the preferences? (y/N) 
```
This happens several times throughout a complete `spack test` run.

### Spack version

```console
$ spack --version
0.14.0-160-6f8d1b41d0
```

### Steps to reproduce the issue

```console
$ spack test lib/spack/spack/test/ci.py
$ spack test lib/spack/spack/test/cmd/ci.py
```

### Information on your system

macOS 10.15.3
Python 3.7.6
gpg 2.2.19

```console
$ gpg --version
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/Adam/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB
```

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by scottwittenburg** [comment]
@adamjstewart I have an older OSX (`10.13.6`) and a slightly newer gpg (`2.2.19`), and I've checked out the commit you referenced, but I cannot reproduce the problem.  Has it reared its head on Travis or Github Actions to your knowledge?

At first glance I assume it's related to something I'm doing in the ci tests related to trusting or using keys, but I'm not sure what I'm doing in there that's too different from what's being tested in the gpg module.  I'll take a look though.

**Comment by adamjstewart** [comment]
It hasn’t occurred on Travis or GitHub Actions as far as I know. Let me know if you want me to try anything, I’m surprised no one else can reproduce this.

**Comment by scottwittenburg** [comment]
@adamjstewart Thanks, as I think of things for you to try, I'll ping you here.  To start with, do you have any keys you've trusted in the spack you use when running the tests?

```
spack gpg list
```

**Comment by adamjstewart** [comment]
> do you have any keys you've trusted in the spack you use when running the tests?

Nope.

**Comment by adamjstewart** [comment]
If I remove `gpg` from my `PATH`, the specific test that's causing the failure, `ci.py::test_import_signing_key`, is skipped and the error does not occur. I wonder if the issue is that I never bothered to set up GPG after installing it. Let me try that.

**Comment by adamjstewart** [comment]
It turns out my GPG installation was completely broken, the Spack `gnupg` package was missing a dependency on `pinentry`. After fixing that, GPG seems to be working just fine. I'm able to create keys and sign git commits. 

However, this bug is still present. I've updated to GPG 2.2.19 and I can still reproduce this.

**Comment by adamjstewart** [comment]
Some related issues:

https://github.com/davejoyce/versioned-ids/issues/18
https://lists.gnupg.org/pipermail/gnupg-users/2005-February/024938.html

I wonder if the key we use during unit tests has conflicting preferences? Maybe my `gpg` doesn't support one of the settings? I updated the initial issue comment with the output of `gpg --version` which shows the supported algorithms/hashes/ciphers.

@scottwittenburg Can you try installing `gnupg` with Spack (you'll want to be on develop) and see if you can reproduce the issue with a Spack-installed gpg?

**Comment by adamjstewart** [comment]
No longer able to reproduce this issue.
