### ISSUE TITLE
spack prints spec that is not reusable ( CMakePackage + ~variant )

### ISSUE THREAD

**Issue by adrienbernede** [spack/spack#15362]
Running `spack spec` for a **CMake package** where a **variant is deactivated**, Spack prints a spec that is not reusable:

### Spack version
Tested on develop and 13.2

### Steps to reproduce the issue

```console
$ spack spec h5cpp~mpi
h5cpp@1.10.4-5%clang@10.0.0-apple build_type=RelWithDebInfo ~mpi arch=darwin-mojave-x86_64
...
$ spack spec h5cpp@1.10.4-5%clang@10.0.0-apple build_type=RelWithDebInfo ~mpi arch=darwin-mojave-x86_64
zsh: no such user or named directory: mpi
...
```

### Error Message

This doesn’t generate an error in Spack itself. 

### Information on your system

Default Spack configuration on MacOS, with zsh.

### Comments

The problem is mainly that Spack generates a spec using `~variant` after a whitespace. This seems to happen only with CMake packages, mainly because those have a `build_type` variant that comes first.

Solutions could be to reorder the variants attache `~variant` to the spec, or use `-` instead of `~`.

**Comment by adrienbernede** [comment]
@scheibelp @becker33 I would appreciate if you could have a look at this one.

**Comment by sethrj** [comment]
I think this is particular to using `zsh` as opposed to the more common `bash`, which passes through nonexistent user directories `~nonexistent` rather than erroring out. Of course, if a system has a user named `mpi` or `cuda`, then even `bash` users will be out of luck :)

**Comment by adrienbernede** [comment]
@sethrj good to know!
I’ll stick with my beloved zsh :), which is be the default on MacOS Catalina, by the way.

**Comment by becker33** [comment]
I thought the default on MacOS Catalina was dash, not zsh.

I believe that you can eliminate this error by defining an appropriate function named `zsh_directory_name` that returns whatever its input is. See the zsh manual chapter 14.7.1 here: http://zsh.sourceforge.net/Doc/Release/Expansion.html#Dynamic-named-directories

**Comment by adrienbernede** [comment]
[Here](https://support.apple.com/en-us/HT208050) is the reference for the default shell on catalina (for new users).

Per [spack documentation](https://spack.readthedocs.io/en/latest/basic_usage.html#variants) I was expecting this issue to be considered a bug in Spack, isn’t it?
