### ISSUE TITLE
Openblas 0.2.20 and lower won't build in Spack-0.14.0

### ISSUE THREAD

**Issue by amaji** [spack/spack#15385]
I am trying to build openblas 0.2.20 with Spack 0.14 and it is failing with the following error (any gcc/intel compiler, Intel haswell/skylake, CentOS7):
```
8245    x86_64: invalid option -- 'r'
     8246    x86_64: Try `x86_64 --help' for more information.
  >> 8247    make[2]: *** [../../libopenblas_haswellp-r0.2.20.a] Error 1
     8248    make[2]: Leaving directory `/tmp/amaji/spack-stage-openblas-0.2.20-jlc5tqmg57npedtcykkilsizxroxa55f/spack-src/la
             pack-netlib/SRC'
  >> 8249    make[1]: *** [lapacklib] Error 2
     8250    make[1]: Leaving directory `/tmp/amaji/spack-stage-openblas-0.2.20-jlc5tqmg57npedtcykkilsizxroxa55f/spack-src/la
             pack-netlib'
  >> 8251    make: *** [netlib] Error 2
```
The Make arguments passed by Spack are:
```
==> [2020-03-04-15:13:34.969668, 34009] 'make' 'CC=/scratch/rice/a/amaji/spack-test-20200303/framework/spack/lib/spack/env/gcc/gcc' 'FC=/scratch/rice/a/amaji/spack-test-20200303/framework/spack/lib/spack/env/gcc/gfortran' 'MAKE_NO_J=1' 'ARCH=x86_64' 'TARGET=HASWELL' 'USE_OPENMP=1' 'USE_THREAD=1' 'libs' 'netlib' 'shared'
```
I suspect, in older Openblas there is no `ARCH=x86_64` argument. This is forcing use of `x86_64 -ru` instead of `ar -ru` like this:
```
x86_64 -ru ../../libopenblas_haswellp-r0.2.20.a sbdsvdx.o spotrf2.o sgetrf2.o sgbbrd.o sgbcon.o sgbequ.o sgbrfs.o sgbsv.o sgbsvx.o sgbtf2.o sgbtrf.o sgbtrs.o sgebak.o sgebal.o sgebd2.o sgebrd.o sgecon.o sgeequ.o sgees.o sgeesx.o sgeev.o sgeevx.o sgehd2.o sgehrd.o sgelq2.o sgelqf.o sgels.o sgelsd.o sgelss.o sgelsy.o sgeql2.o sgeqlf.o sgeqp3.o sgeqr2.o sgeqr2p.o sgeqrf.o sgeqrfp.o sgerfs.o sgerq2.o sgerqf.o sgesc2.o .........
```
If I remove `ARCH=x86_64` from the make arguments, things build fine. I suspect the following commit introduced this behavior.
https://github.com/spack/spack/commit/ca6e75c9f678ecf603354531cfec68ab4a121def

Can you please take a look and fix this? Openblas 0.2.20 was building fine in Spack 0.13.x. 

On an unrelated issue, 
I patched the Openblas package in my custom_packages directory and installed it with spack. 
```
$ spack find -lp openblas@0.2.20 %gcc@4.8.5
==> 1 installed package
-- linux-centos7-haswell / gcc@4.8.5 ----------------------------
ouzv3uh openblas@0.2.20  /scratch/rice/a/amaji/spack-test-20200303/apps/openblas/0.2.20-gcc-4.8.5-ouzv3uh
```
If I try to install openblas again spack detects the previous install.
```
$ spack install openblas@0.2.20 %gcc@4.8.5
[+] /scratch/rice/a/amaji/spack-test-20200303/apps/openblas/0.2.20-gcc-4.8.5-ouzv3uh
```
But if Spack is trying to install a package that depends on `openblas@0.2.20` such as `r` (same variant and everything) it tries to reinstall openblas. Even weirder thing is that it is ignoring my `custom_packages` definition of openblas package and trying to use the openblas from `var/spack/repos/builtin` and fails again! This may be somewhat related to the concretization bug https://github.com/spack/spack/issues/15384

Am I missing something? Why does Spack use different openblas package definitions (custom_packages vs. builtin) for explicit install vs. implicit install?

**Comment by adamjstewart** [comment]
@sethrj @alalazo

**Comment by sethrj** [comment]
@amaji I just took a deep dive into openblas and found that older versions (which download netlib lapack 3.4.1) have a bug in their makefile system. The "ARCH" argument is correct, but somehow netlib is using it in place of `ar`.

I can disable the ARCH argument for older openblas versions, but what on earth requires an old version of openblas?

**Comment by amaji** [comment]
@sethrj thanks for looking into this .. maybe a makefile patch will help (or just omit the ARCH flag) .. we mostly need it for backward compatibility .. we are currently supporting openblas 0.2.20 in our older clusters (and they will live another couple of years).

**Comment by amaji** [comment]
@sethrj I am also seeing issues with Openblas@0.3.8 and intel compilers (intel@16 through intel@19). The spec I am trying to install is this:
```
$ spack spec openblas@0.3.8 %intel@17.0.1
Input spec
--------------------------------
openblas@0.3.8%intel@17.0.1

Concretized
--------------------------------
applying patches
openblas@0.3.8%intel@17.0.1~consistentFPCSR~ilp64 patches=00230a6b2bc50d7722d4aad49c0c06091176910b942cd51980b345e2935300b0 +pic+shared threads=openmp arch=linux-centos7-haswell
```
My intel compiler is provided by:
```
intel-parallel-studio@cluster.2017.1%intel +advisor auto_dispatch=none +clck+daal+gdb~ilp64+inspector+ipp+itac+mkl~mpi~newdtags+rpath+shared+tbb threads=openmp +vtune
```
Error message:
```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'CC=/scratch/rice/a/amaji/spack-test-20200303/framework/spack/lib/spack/env/intel/icc' 'FC=/scratch/rice/a/amaji/spack-test-20200303/framework/spack/lib/spack/env/intel/ifort' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'TARGET=HASWELL' 'USE_OPENMP=1' 'USE_THREAD=1' 'libs' 'netlib' 'shared'

3 errors found in build log:
     6994    make[1]: Entering directory `/tmp/amaji/spack-stage-openblas-0.3.8-7232a4ywdmlyb4wkvawgrguzycfa3kai/spack-src/exports'
     6995    perl ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 > linktest.c
     6996    /scratch/rice/a/amaji/spack-test-20200303/framework/spack/lib/spack/env/intel/ifort -O2 -fopenmp -fPIC  -shared -o ../libopenblas_haswellp-r0.3.8.so \
     6997    -Wl,--whole-archive ../libopenblas_haswellp-r0.3.8.a -Wl,--no-whole-archive \
     6998    -Wl,-soname,libopenblas.so.0 -lm -lpthread -lm -lpthread
     6999    /scratch/rice/a/amaji/spack-test-20200303/framework/spack/lib/spack/env/intel/icc -O2 -DMAX_STACK_ALLOC=2048 -wd981 -fopenmp -DF_INTERFACE_INTEL -fPIC -DSMP_SERVER -DUSE
             _OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=40 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.8\" -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AF
             FINITY -I..  -w -o linktest linktest.c ../libopenblas_haswellp-r0.3.8.so -L/scratch/rice/a/amaji/spack-test-20200303/apps/intel-parallel-studio/cluster.2017.1-intel-17.0
             .1-2off4ih/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/ -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../
             ../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/usr/lib/gcc/x86_64-redh
             at-linux/4.8.5/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib  -lifport -lifcoremt -limf -lsvml -lm -lipgo -lirc -lpthread -lsvml -lc -lirc_s -ldl -lc  -lifcore && e
             cho OK.
  >> 7000    ../libopenblas_haswellp-r0.3.8.so: undefined reference to `xerbl_'
  >> 7001    make[1]: *** [../libopenblas_haswellp-r0.3.8.so] Error 1
     7002    make[1]: Leaving directory `/tmp/amaji/spack-stage-openblas-0.3.8-7232a4ywdmlyb4wkvawgrguzycfa3kai/spack-src/exports'
  >> 7003    make: *** [shared] Error 2
```
Installation works fine with all gcc compilers.  

Openblas@0.3.7 is building fine with both compilers.

**Comment by sethrj** [comment]
@amaji Will do. I hit the same `xerbl_` error on intel 18 but wasn't able to find an obvious immediate cause (like you, v0.3.7 worked for me). If you'll open up an issue on the [openblas issue tracker](https://github.com/xianyi/OpenBLAS/issues) I'll add an appropriate `conflicts(` statement and link to your issue while I'm patching openblas to correctly install 0.20.

**Comment by sethrj** [comment]
For historical note: I also got the same `xerbl_` link error with openblas@0.3.9 and intel@14.0.4 . I'm going to add:
```python
    conflicts('%intel', when='@0.3.8:')
```

**Comment by sethrj** [comment]
BTW the missing `xerbl_` is also referenced here: https://github.com/xianyi/OpenBLAS/issues/2386#issuecomment-582096592

which may be an issue with intel being picky about fixed-line form: https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/842494

Bingo! Commit 375b1875c8c1d1d59d1bb6f2c227e6da12563faf in OpenBLAS updates LAPACK to  3.9.0, which includes a  new file `sorhr_col.f`, which contains the line
```fortran
      EXTERNAL           SCOPY, SLAORHR_COL_GETRFNP, SSCAL, STRSM, XERBLA
```
and the `A` is in column 73. Thanks to Doctor Fortran (@sblionel) for the tipoff on the lapack failure.

**Comment by sethrj** [comment]
This will need to be patched in Spack for OpenBLAS 0.3.8 and 0.3.9, and an patch probably submitted to upstream openblas, *and* a patch submitted to  https://github.com/Reference-LAPACK/lapack/issues. I've created an issue on lapack: https://github.com/Reference-LAPACK/lapack/issues/394 and am testing a patch for the intel now.

**Comment by amaji** [comment]
@sethrj thanks for the fix! Impressive detective work with lapack-3.9.

**Comment by amaji** [comment]
@sethrj Any thoughts on the second part of my question `Why does Spack use different openblas package definitions (custom_packages vs. builtin) for explicit install vs. implicit install?`

I am seeing this with Spack-0.14.

**Comment by sethrj** [comment]
@amaji I'm afraid I don't understand your `custom_packages` question :\

**Comment by amaji** [comment]
@sethrj let me describe my setup. Since, openblas-0.2.20 was failing to build, I decided to customize the package. I copied the openblas package from `var/spack/packages/builtin/packages` to a `custom_packages/packages` directory and added `custom_packages` to my repos.yaml. Edited `openblas/package.py` to explicitly disbale `ARCH=x86_64` from make args.

Now, I could install openblas-0.2.20 with all compilers. 
```
$ spack find -lp openblas@0.2.20 %gcc@4.8.5
==> 1 installed package
-- linux-centos7-haswell / gcc@4.8.5 ----------------------------
ouzv3uh openblas@0.2.20  /scratch/rice/a/amaji/spack-test-20200303/apps/openblas/0.2.20-gcc-4.8.5-ouzv3uh
```
If I try to install openblas explicitly, Spack detects it is installed:
```
$ spack install openblas@0.2.20 %gcc@4.8.5
[+] /scratch/rice/a/amaji/spack-test-20200303/apps/openblas/0.2.20-gcc-4.8.5-ouzv3uh
```
In the same terminal, if I try to install any package that depends_on openblas@0.2.20 (for example, esmf/gmt/octave etc.), Spack tries to reinstall openblas. Please see https://github.com/spack/spack/issues/15384#issuecomment-597179743 for an example spec.

But during the installation of openblas **as a dependency** (of gmt or octave), Spack decides to use the builtin (`var/spack/repos/builtin/packages/openblas`) definition of Openblas and fails to install. I cannot figure out why it ignores my repos.yaml and the custom definition of Openblas package there.

**Comment by sethrj** [comment]
In your `repos.yaml` does `custom_packages` precede or follow the `builtin`  repo? It might be an ordering with that. Honestly I would be surprised if what you're trying to do worked in the first place... and if you'd like to pursue it, I think it would be good to open a separate issue at this point since the openblas issue has been resolved. 😄

**Comment by amaji** [comment]
@sethrj thanks! I'll open another issue.
