### ISSUE TITLE
gromacs-2020 fails to build with cmake>3.15.2 and openmpi

### ISSUE THREAD

**Issue by tz-rrze** [spack/spack#15408]
Gromacs version 2020 fails to build with cmake>3.15.2 and openmpi.
The error message is ``g++: error: unrecognized command line option '-fexceptions -pthread'; did you mean '-fexceptions'`` and is due to cmake adding compiler arguments with quotes.
A similar issue has been reported in #15097.

### Spack version
0.14.0-165-146589e

### Additional information

There seem to be three options to deal with the issue:

1. ignore as the Gromacs developers fixed the issue in version 2020.1; #15399 is the PR to upgrade the Gromacs version in Spack
2. include the upstream fix (https://github.com/gromacs/gromacs/commit/7d0829a3cbc3d3bbb8e0bb7e6d104e2d2165336f) in Spack for Gromacs-2020 as patch
3. add ``conflicts('cmake@3.15.3:' when='@2020')`` or similarly ``depends_on('cmake@:3.15.2', when='@2020')``

@junghans, @marvinbernhardt: what do you prefer? In case of 2. or 3. I could provide a PR.

**Comment by junghans** [comment]
Let's do 1.!
