### ISSUE TITLE
Installation issue: llvm 

### ISSUE THREAD

**Issue by LDAmorim** [spack/spack#15410]
Hi all,
Sorry for this probably very basic issue/question, but when trying to install `py-jupyter` package I get a sort of an error in the sub-package `llvm`.
In the cmake phase it breaks and asks for a password (my computer login one doesn't work).
I tried to look at the corresponding llvm package.py file, but I can't understand which part is calling for sudo/password.
Below is the end of the output related to this issue.
Do you know what password it is requesting or have any suggestion on how I can fix this issue?

### Spack version

```console
$ spack --version
0.14.0-124-1757ec9ea
```

### Steps to reproduce the issue

```console
$ spack install llvm
...
==> 69923: Installing llvm
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check clang@11.0.0-apple for further details]
==> Using cached archive: /Users/LDianaAmorim/Documents/opt/spack/var/spack/cache/_source-cache/archive/be/be7b034641a5fda51ffca7f5d840b1a768737779f75f7c4fd18fe2d37820289a.tar.gz
==> Staging archive: /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-llvm-9.0.1-uyfmfxzkm7btiwyyqpcjd77zizuoajz3/llvmorg-9.0.1.tar.gz
==> Created stage in /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-llvm-9.0.1-uyfmfxzkm7btiwyyqpcjd77zizuoajz3
missing header for unified diff at line 3 of patch
==> Applied patch /Users/LDianaAmorim/Documents/opt/spack/var/spack/repos/builtin/packages/llvm/constexpr_longdouble_9.0.patch
==> 69923: llvm: Building llvm [CMakePackage]
==> 69923: llvm: Executing phase: 'cmake'
Password:
```

### Platform and user environment

```commandline
$ uname -a 
Darwin LDianaAmorim-M30.dhcp.lbnl.us 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
``` 
and, if relevant, post or attach:

- packages.yaml
```python
packages:
  all:
    providers:
      mpi: [mpich, openmpi]
```

- compilers.yaml
```python
compilers:
- compiler:
    spec: clang@11.0.0-apple
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/gcc-9.2.0-exw25ccpcwqlkcvuwn266kvwqzxbyelp/bin/gfortran
      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/gcc-9.2.0-exw25ccpcwqlkcvuwn266kvwqzxbyelp/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment:
      unset: []
    extra_rpaths: []
- compiler:
    spec: gcc@9.2.0
    paths:
      cc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/gcc-9.2.0-exw25ccpcwqlkcvuwn266kvwqzxbyelp/bin/gcc
      cxx: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/gcc-9.2.0-exw25ccpcwqlkcvuwn266kvwqzxbyelp/bin/g++
      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/gcc-9.2.0-exw25ccpcwqlkcvuwn266kvwqzxbyelp/bin/gfortran
      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/gcc-9.2.0-exw25ccpcwqlkcvuwn266kvwqzxbyelp/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

**Comment by s-sajid-ali** [comment]
Could you post the build logs that would be available at the temporary build stage ? Specifically the file `/var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-llvm-9.0.1-uyfmfxzkm7btiwyyqpcjd77zizuoajz3/spack-build-out.txt` which would hopefully give more information as to what's happening. 

If this directory is unavailable (removed during spack clean), could you post the output of :
`spack -d install -v llvm`

**Comment by LDAmorim** [comment]
Hi @s-sajid-ali,
Thank you for your reply and sorry for getting back to you so late.
I just tried updating Xcode and re-installing spack and trying again and the issue persists.
Below are the files in the folder you mentioned  (sorry I didn't include them with the original issue message).
[spack-build-out.txt](https://github.com/spack/spack/files/4325748/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/4325749/spack-configure-args.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/4325746/spack-build-env.txt)
Thanks

**Comment by s-sajid-ali** [comment]
Looks like [this step](https://github.com/spack/spack/blob/f2a13af43e505495473354f258e216ebb4632d43/var/spack/repos/builtin/packages/llvm/package.py#L151) is failing. It is trying to run [this script](https://github.com/llvm-mirror/lldb/blob/master/scripts/macos-setup-codesign.sh) which requires assumes root access. 

This logic was introduced recently in https://github.com/spack/spack/pull/15169, hence pinging @sethrj for help. Is this related to https://github.com/spack/spack/issues/4432#issuecomment-306579763 ? 

No worries about missing the build logs or late replies, feel free to post issues and ask for help!

**Comment by LDAmorim** [comment]
Thank you for your help @s-sajid-ali !
Oh I had tried to edit the `llvm` package.py file to see if anywhere there it requested root access.
Next time I'll look into the package repo too.
Thanks

**Comment by s-sajid-ali** [comment]
Just to clarify, `spack` is able to install any package to a location where the user has write access to. This allows a user to build packages of their choice on a cluster where they don't necessarily have root access without having to rely upon sysadmins. While one can run `spack` as root, it's never assumed that the person running `spack` has root privileges. From my experience I'd say that this case is probably an outlier.

PS : There is a (very) small set of packages that however do need root privilege; policies for handling of these are still being discuss and developed (see https://github.com/spack/spack/issues/4432, https://github.com/spack/spack/pull/9521 and possibly https://github.com/spack/spack/issues/11519 for some related discussion).
