### ISSUE TITLE
openmpi and cxx 

### ISSUE THREAD

**Issue by azukaitis** [spack/spack#15465]
What is the reasoning for turning on the cxx wrappers always when openmpi has turned them off by default?  This should be off by default... and enabled via a variant?

From the openmpi/package.py:
        if spec.satisfies('@2.0:'):
            # for Open-MPI 2.0:, C++ bindings are disabled by default.
            config_args.extend(['--enable-mpi-cxx'])

### Spack version

```console
$ spack --version
0.14.0-206-e916a9424
```

**Comment by adamjstewart** [comment]
> This should be off by default

I think a lot of Spack users use MPI for C++ libraries, so it makes sense for the default to be on.

> and enabled via a variant?

We can certainly add a variant for this if you want. Are you experiencing any problems with the C++ build?

@hppritcha may have some opinions on this.

**Comment by azukaitis** [comment]
I might be... I'm currently having some issues with boost+openmpi+intel19
and havent quite figured out what was going on.  I was just reading and saw
that openmpi had disabled the cxx extensions by default and thought it was
quite odd that spack was setting them on by default.

**Comment by wortiz** [comment]
> I think a lot of Spack users use MPI for C++ libraries, so it makes sense for the default to be on.

Don't most major packages use the C bindings, I thought c++ bindings had been deprecated a long time ago

>We can certainly add a variant for this if you want. Are you experiencing any problems with the C++ build?

I think by default the openmpi c++ bindings throw a bunch of warnings on newer gcc's and it is hard to use isystem in mpi wrappers for the mpi headers
