### ISSUE TITLE
ncurses: #15039 caused build regressions in R

### ISSUE THREAD

**Issue by hainest** [spack/spack#15486]
From the current HEAD of develop (14441e00d), #15039 somehow caused the `readline` includes to no longer be available when building R- even though the package is definitely installed. I have a feeling this may not be the only package affected, but it's the only place I've seen this happen.

See also the discussion in #14793.

    $ spack find r
        ==> No package matches the query: r

    $ spack install r
        <snip>
        [+] /home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/readline-8.0-ad6ojvpe37rlzu4lx6lgzngka2qhzpge
        <snip>
        ==> 581: Installing r
        ==> Using cached archive: /home/tim/ecp-builds/spack/var/spack/cache/_source-cache/archive/89/89302990d8e8add536e12125ec591d6951022cf8475861b3690bc8bf1cefaa8f.tar.gz
        ==> Staging archive: /tmp/tim/spack-stage/spack-stage-r-3.6.3-wnvww3cpvjdfhfn6cteeo2ez2x6ftq64/R-3.6.3.tar.gz
        ==> Created stage in /tmp/tim/spack-stage/spack-stage-r-3.6.3-wnvww3cpvjdfhfn6cteeo2ez2x6ftq64
        ==> No patches needed for r
        ==> 581: r: Building r [AutotoolsPackage]
        ==> 581: r: Executing phase: 'autoreconf'
        ==> 581: r: Executing phase: 'configure'
        ==> Error: ProcessError: Command exited with status 1:
        '/tmp/tim/spack-stage/spack-stage-r-3.6.3-wnvww3cpvjdfhfn6cteeo2ez2x6ftq64/spack-src/configure' '--prefix=/home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/r-3.6.3-wnvww3cpvjdfhfn6cteeo2ez2x6ftq64' '--libdir=/home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/r-3.6.3-wnvww3cpvjdfhfn6cteeo2ez2x6ftq64/rlib' '--enable-R-shlib' '--enable-BLAS-shlib' '--enable-R-framework=no' '--without-recommended-packages' '--with-tcl-config=/home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/tcl-8.6.8-myrvskltrenepkvaifd3eekcq6ufw5rk/lib/tclConfig.sh' 'LDFLAGS=-L/home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/r-3.6.3-wnvww3cpvjdfhfn6cteeo2ez2x6ftq64/rlib/R/lib -Wl,-rpath,/home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/r-3.6.3-wnvww3cpvjdfhfn6cteeo2ez2x6ftq64/rlib/R/lib' '--without-x'

        1 error found in build log:
        180    checking readline/readline.h usability... yes
        181    checking readline/readline.h presence... yes
        182    checking for readline/readline.h... yes
        183    checking for rl_callback_read_char in -lreadline... no
        184    checking for main in -lncurses... yes
        185    checking for rl_callback_read_char in -lreadline... no
        >> 186    configure: error: --with-readline=yes (default) and headers/libs are not available

        See build log for details:
        /tmp/tim/spack-stage/spack-stage-r-3.6.3-wnvww3cpvjdfhfn6cteeo2ez2x6ftq64/spack-build-out.txt

After rebasing out 578e8031.

    $ spack install r
        <snip>
        [+] /home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/readline-8.0-gjaibnkerwm2eodvlsubh3fggkpt4qgt
        <snip>
        ==> 7629: Installing r
        ==> Using cached archive: /home/tim/ecp-builds/spack/var/spack/cache/_source-cache/archive/89/89302990d8e8add536e12125ec591d6951022cf8475861b3690bc8bf1cefaa8f.tar.gz
        ==> Staging archive: /tmp/tim/spack-stage/spack-stage-r-3.6.3-b2utg34ant33d5aebkem4ouk3jdh4pt2/R-3.6.3.tar.gz
        ==> Created stage in /tmp/tim/spack-stage/spack-stage-r-3.6.3-b2utg34ant33d5aebkem4ouk3jdh4pt2
        ==> No patches needed for r
        ==> 7629: r: Building r [AutotoolsPackage]
        ==> 7629: r: Executing phase: 'autoreconf'
        ==> 7629: r: Executing phase: 'configure'
        ==> 7629: r: Executing phase: 'build'
        ==> 7629: r: Executing phase: 'install'
        ==> 7629: r: Successfully installed r
        Fetch: 0.07s.  Build: 2m 19.07s.  Total: 2m 19.14s.
        [+] /home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/r-3.6.3-b2utg34ant33d5aebkem4ouk3jdh4pt2

**Comment by hainest** [comment]
After a bit of poking around, I found that

    spack install r%clang

installs without errors on the HEAD of `develop`, but

    spack install r%gcc

does not- even when each install is done a fresh clone. That seemed to me to be possibly a concretization issue. However, the only difference between having 15039 and not is

    ^perl@5.30.1%gcc@8.3.0+cpanm+shared+threads arch=linux-ubuntu19.04-skylake
        ^gdbm@1.18.1%gcc@8.3.0 arch=linux-ubuntu19.04-skylake
        ^readline@8.0%gcc@8.3.0 arch=linux-ubuntu19.04-skylake
    -       ^ncurses@6.2%gcc@8.3.0~symlinks+termlib arch=linux-ubuntu19.04-skylake
    +       ^ncurses@6.2%gcc@8.3.0~symlinks~termlib arch=linux-ubuntu19.04-skylake
        ^pkgconf@1.6.3%gcc@8.3.0 arch=linux-ubuntu19.04-skylake

which is exactly the change in 15039 and nothing more. I'm not sure where to go from here. I'm not familiar enough with the innards of spack to give an educated guess as to where to look next.

@sethrj @glennpj @scheibelp Do you have any thoughts on why a small change in ncurses is having such an adverse effect here?

**Comment by glennpj** [comment]
@hainest I am not seeing this behavior on a CentOS-7 system. I wonder if your Ubuntu system is picking up system libraries. For the successful build of R, what is the output of the following command:
```console
$ ldd $(spack find -p r | tail -n +3 | awk '{print $2}')/rlib/R/bin/exec/R | egrep 'readline|ncurses|tinfo'
```

**Comment by hainest** [comment]
@glennpj All three libraries are pointing to the correct spack install:

    libreadline.so.8 => /home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/clang-8.0.0/readline-8.0-thh5ebze4id5urlcv2aw6wr6e3cryap3/lib/libreadline.so.8 (0x00007fe405b52000)
    libncursesw.so.6 => /home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/clang-8.0.0/ncurses-6.2-kiutj4p3exsdhxmtejlk5wlefmnsaq6a/lib/libncursesw.so.6 (0x00007fe4052f8000)
    libtinfow.so.6 => /home/tim/ecp-builds/spack/opt/spack/linux-ubuntu19.04-skylake/clang-8.0.0/ncurses-6.2-kiutj4p3exsdhxmtejlk5wlefmnsaq6a/lib/libtinfow.so.6 (0x00007fe403623000)

**Comment by scheibelp** [comment]
> Do you have any thoughts on why a small change in ncurses is having such an adverse effect here?

My first thought is that `r` isn't looking for the symbols it needs in `libtinfo` - as mentioned in https://github.com/spack/spack/commit/578e8031ce80b9dc66c197495be6ffe764868702 some packages need to be updated because `+termlib` splits out symbols from `libcurses`

What confuses me is that your build is complaining about missing symbols from `libreadline`

If you rerun the build with `spack -d install...`, that will output files like `spack-cc-r-<7-character-hash>.out.log` which contains the compiler invocations that the Spack wrappers dispatch: can you include the last several lines of that file here? In particular I'm curious about the test relating to `rl_callback_read_char` (this will probably be one of the last lines in that Spack-generated `.out` file).

If this continues, we can see if this can be addressed by instantiating the build environment that Spack compiles `r` in (e.g. using `spack stage r; spack build-env bash`).

**Comment by hainest** [comment]
@scheibelp This was the next thing I looked at after I tracked down the offending commit. Both the gcc and clang builds use the linker search paths added in #11957, but only the gcc variant fails. I had tried tweaking the `package.py` to explicitly include the libraries in `spec['readline'].prefix`, but it had no effect. I had assumed I was chasing a red herring, but I see now I should have included those details.

Here are the logs from

    spack/bin/spack -d install -v -j8 -y r %gcc@8.3.0 >r.gcc@8.3.0.log 2>&1

[r.gcc@8.3.0.log](https://github.com/spack/spack/files/4372947/r.gcc%408.3.0.log)
[spack-cc-r-bw2rt6l.in.log](https://github.com/spack/spack/files/4372948/spack-cc-r-bw2rt6l.in.log)
[spack-cc-r-bw2rt6l.out.log](https://github.com/spack/spack/files/4372949/spack-cc-r-bw2rt6l.out.log)

**Comment by scottwittenburg** [comment]
I just tried to run a spack pipeline with an environment containing only `r-rminer` compiled with `gcc@7.5.0`, and I ran into the same configure error as in the OP.  This pipeline was targeted at the `spack/ubuntu-bionic` docker container and was using a fairly recent develop as the base.  The top commit is:

```
commit 605b7b5d23968d80dc1b045babc4866db8792f58
Author: Fabian Brandt <fabbrandt@gmail.com>
Date:   Mon Mar 30 15:17:21 2020 +0200

    New package: libnetworkit (#15714)
    
    * New package libnetworkit
    
    * Fixed artificial dependency restriction
```

I've attached the pipeline log as well as the spack build output file as additional sources of information.  I can create a new issue if this is not the same problem.

[pipeline_log (62).txt](https://github.com/spack/spack/files/4447048/pipeline_log.62.txt)
[spack-build-out (5).txt](https://github.com/spack/spack/files/4447053/spack-build-out.5.txt)

**Comment by hainest** [comment]
@scottwittenburg From your build log, it is the same error I had. Could you verify the library locations from @glennpj's [comment](https://github.com/spack/spack/issues/15486#issuecomment-602247314)? Your failure was on Ubuntu, as well, so it seems this may be OS-specific.

**Comment by scottwittenburg** [comment]
@hainest I don't have a successful install of 'r', and from the linked comment, it seems that's the starting point.  Aside from that, reproducing those pipeline builds outside the pipeline environment takes a little time, but if you think it's useful I'll try to find time to do that today or tomorrow.

**Comment by glennpj** [comment]
What happens with 
```
spack install r ^ncurses~termlib
```

**Comment by hainest** [comment]
@scottwittenburg Oh, sorry, I should have mentioned that was using my [clang build](https://github.com/spack/spack/issues/15486#issuecomment-601984838). No worries, if you don't have time to re-run it. It's good to have a second data point just to confirm it's not just me doing something crazy in my environment.

**Comment by hainest** [comment]
@glennpj `spack install r ^ncurses~termlib` builds without error on my system. I don't have a way of testing that the resulting installation works correctly, though.

**Comment by hainest** [comment]
This is no longer an issue as of `develop@5d999d0e4f`.
