### ISSUE TITLE
Wrong normalised path with external Intel MPI 

### ISSUE THREAD

**Issue by ilbiondo** [spack/spack#15540]
I have Intel MPI defined as an external package:

```
  intel-mpi:
    buildable: False
    paths:
      intel-mpi@2019.6.166 %intel@19.1.0.166:  /dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/intel64
```

When trying to install a package using Intel MPI the MPICC path (and others) are incorrect:

```
$ spack -d build-env fftw%intel | grep impi
..
..
I_MPI_ROOT=/dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/intel64/compilers_and_libraries/linux/mpi
MPICC=/dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/intel64/compilers_and_libraries/linux/mpi/intel64/bin/mpiicc
MPICXX=/dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/intel64/compilers_and_libraries/linux/mpi/intel64/bin/mpiicpc
MPIF77=/dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/intel64/compilers_and_libraries/linux/mpi/intel64/bin/mpiifort
MPIF90=/dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/intel64/compilers_and_libraries/linux/mpi/intel64/bin/mpiifort
```

The correct path is `/dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/intel64/bin` so without the additional `compilers_and_libraries/linux/mpi/intel64`

The additional path is provided by 
```
def normalize_path(self, component_path, component_suite_dir=None,
                       relative=False):
```
From /build_systems/intel.py 

This is with

```
$ spack --version
0.13.3-1338-36017d8
```

**Comment by JulienLoiseau** [comment]
Hi, 

I am encountring the same issue trying to use intel compiler: 

Error : 
The CMAKE_C_COMPILER:
     7     
     8         [...]intel-clusterstudio/2019.4.070/impi/2019.4.243/intel64/compilers_and_libraries/linux/mpi/intel64/bin/mpiicc
     9     
     10      is not a full path to an existing compiler tool.

The path is wrong, there is an additional: /compilers_and_libraries/linux/mpi/intel64/

Using spack --version: 
0.14.1-365-7b4354b

**Comment by ilbiondo** [comment]
Setting the external path to the base Intel install seems to help a bit:

```
  intel-mpi:
    buildable: False
    paths:
      intel-mpi@2019.6.166 %intel@19.1.0.166:  /dcsrsoft/spack/external/intel/2020.0
```

We now see the correct paths for MPICC and the libraries:

```
$ spack build-env fftw%intel^intel-mpi | grep MPI
..
MPICC=/dcsrsoft/spack/external/intel/2020.0/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpiicc
MPICXX=/dcsrsoft/spack/external/intel/2020.0/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpiicpc
MPIF77=/dcsrsoft/spack/external/intel/2020.0/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpiifort
MPIF90=/dcsrsoft/spack/external/intel/2020.0/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpiifort
```

However, there is still work to be done as, for example `fftw%intel^intel-mpi` fails with:

```
1 error found in build log:
     84    checking for ranlib... (cached) ranlib
     85    checking for ocamlbuild... no
     86    checking for mpicc... /dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/compilers_and_libraries/linux/mpi/intel64/bin/mpiicc
     87    checking for MPI_Init... no
     88    checking for MPI_Init in -lmpi... no
     89    checking for MPI_Init in -lmpich... no
  >> 90    configure: error: could not find mpi library for --enable-mpi
```

Module creation is still broken thanks to the path still being wrong:

```
==> Warning: Could not write module file [/dcsrsoft/spack/meleze/v2/share/spack/lmod/E5v1-IB/linux-centos7-x86_64/intel/19.1.0.166/intel-mpi/2019.6.166.lua]
==> Warning:  --> Trying to source non-existing file: /dcsrsoft/spack/external/intel/2020.0/impi/2019.6.166/compilers_and_libraries/linux/mpi/intel64/bin/mpivars.sh <--
```

Either of the following would be correct:

 - `compilers_and_libraries/linux/mpi/intel64/bin/mpivars.sh`
 - `impi/2019.6.166/intel64/bin/mpivars.sh`

But we still see the strange combination 

 - `impi/2019.6.166/compilers_and_libraries/linux/mpi/intel64/bin/mpivars.sh`

**Comment by ilbiondo** [comment]
I think this can be closed - the ongoing error was due to the old path still being present in the Spack database. `spack reindex`managed to purge it successfully.

The following definition seems to work:

```
  intel-mpi:
    buildable: False
    paths:
      intel-mpi@2019.6.166 %intel@19.1.0.166:  /dcsrsoft/spack/external/intel/2020.0
```

With a clean database:

```
$ spack install intel-mpi
==> intel-mpi@2019.6.166 : externally installed in /dcsrsoft/spack/external/intel/2020.0
==> intel-mpi@2019.6.166 : generating module file
==> Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      source /dcsrsoft/spack/external/intel/2020.0/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpivars.sh intel64 &> /dev/null && python3 -c "import os, json; print(json.dumps(dict(os.environ)))"
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
==> intel-mpi@2019.6.166 : registering into DB
```

I can now compile MPI codes correctly including the FFTW example given above.

It would probably be a good idea to update the documentation for the Intel packages to make it clear that if they are installed externally then the path needs to be the root of the parallel studio package and not the directory where one actually finds the components.

**Comment by alalazo** [comment]
> It would probably be a good idea to update the documentation for the Intel packages to make it clear that if they are installed externally then the path needs to be the root of the parallel studio package and not the directory where one actually finds the components.

That would be an awesome idea for #15848 !

**Comment by giordano** [comment]
I'm experiencing a similar issue.  In an environment I have
```yaml
    intel-mpi:
      externals:
      - spec: intel-mpi@2018.1.163
        prefix: /tessfs1/sw/Intel/impi/2018.1.163/intel64
      buildable: false
```
`mpicc` is in `/tessfs1/sw/Intel/impi/2018.1.163/intel64/bin/mpicc` (basically `prefix + bin/mpicc`, it should be easy to guess?), but
```console
$ spack build-env fftw^intel-mpi | grep MPICC
MPICC=/tessfs1/sw/Intel/impi/2018.1.163/intel64/compilers_and_libraries/linux/mpi/intel64/bin/mpicc
```
which is completely wrong and it points to a non-existing path.  The suggesting above to change the prefix to `/tessfs1/sw/Intel/impi/2018.1.163` doesn't help at all for me.
