### ISSUE TITLE
bolt build fails on ppc64le

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#15550]
Package `bolt` is not building on `Ubuntu 18.04` for `ppc64le`. Likewise, not building for `CentOS 7` and `RHEL 7` for `ppc64le`. Using Spack @ develop (commit 958f26073efe340d5 from 18-March-2020). It is a `power8` host.

```
$> spack install bolt%gcc@7.3.0 target=ppc64le
# fails with a verbose error, see full build log below
# looks like scoping errors involving KMP_ macros, but I don't know
```

Full build log:  [bolt-ppc64le-build-log.txt](https://github.com/spack/spack/files/4350618/bolt-ppc64le-build-log.txt)

@shintaro-iwasaki @raffenet

**Comment by shintaro-iwasaki** [comment]
Thank you. It might be a problem of BOLT. I will investigate this issue and fix it soon.

**Comment by shintaro-iwasaki** [comment]
We fixed this issue in the master branch of BOLT (the exact bug found in your `bolt-ppc64le-build-log.txt`). I confirmed that, although the compiler is GCC 4.8, BOLT (`bolt@master`) can be compiled via Spack on a POWER 9 platform.

Note that this fix has not been tagged yet, so you need to specify a master branch (`master`) for compilation. This fix will be included in the next release, which I believe should happen this month.

Thank you for reporting an issue! @eugeneswalker

**Comment by tldahlgren** [comment]
> We fixed this issue in the master branch of BOLT (the exact bug found in your `bolt-ppc64le-build-log.txt`). I confirmed that, although the compiler is GCC 4.8, BOLT (`bolt@master`) can be compiled via Spack on a POWER 9 platform.
> 
> Note that this fix has not been tagged yet, so you need to specify a master branch (`master`) for compilation. This fix will be included in the next release, which I believe should happen this month.
> 
> Thank you for reporting an issue! @eugeneswalker

That's wonderful news.  Thanks!
