### ISSUE TITLE
Best Practices for Building in Remote Compute Environment?

### ISSUE THREAD

**Issue by xjrc** [spack/spack#15552]
Are there any best practices for using Spack to build software in environments that deploy high-load compute tasks to non-local nodes? This is a very common workflow for developers at LLNL as our supercomputers have separate node partitions for interactive and compute jobs, and I imagine this working environment is similar for other sites with scientific computing resources.

Ideally, I'd like to launch Spack from an interactive node and then have the high-load tasks (e.g. anything that needs a subprocess like `configure`, `make`, etc.) deployed to a compute node. My primary motivator for this cross-node workflow is to maintain the helpful color-coded reporting that comes with a purely interactive environment (this color-coding is lost when executing purely compute runs) while delegating the majority of the heavy lifting to the compute nodes. That being said, the urgency of my need is relatively low, but I'm still curious if anyone has gone through the effort of enabling this more nuanced behavior (or, even better, if Spack somehow supports it natively)!

Thanks in advance for any help or advice you may be able to provide!

**Comment by hainest** [comment]
>Are there any best practices for using Spack to build software in environments that deploy high-load compute tasks to non-local nodes?

In my experience, it doesn't work correctly (cf #14715) using an interactive batch-style workflow. I would be very interested to hear if anyone at LLNL has been able to get it to work.

>Ideally, I'd like to launch Spack from an interactive node and then have the high-load tasks (e.g. anything that needs a subprocess like configure, make, etc.) deployed to a compute node.

To my knowledge, you can't do this. Spack assumes that the compute resource is the same machine that you launched `spack` from. Internally, it uses Pythons shell execution libraries to kick off each stage of a build.

>My primary motivator for this cross-node workflow is to maintain the helpful color-coded reporting that comes with a purely interactive environment (this color-coding is lost when executing purely compute runs) while delegating the majority of the heavy lifting to the compute nodes.

Which colorized text are you interested in? You can see the fully-colorized reports from the build log using `spack log-parse --show=errors,warnings FILE`.

**Comment by xjrc** [comment]
Thanks for the information @hainest! I'm happy to hear that I'm not the only one grappling with this issue. The fact that you've had interactive batch-style build failures makes me wonder about this problem even more, though. I haven't encountered any errors by executing builds with `srun -n1 -N1 --exclusive /path/to/spack install -jXX ...`, but I will certainly log any that I may find at #14715. In the meantime, it seems like I'll be able to get by with outputting my install logs and using `spack log-parse` to colorize them, so thank you for the advice!

**Comment by scheibelp** [comment]
Note that as of https://github.com/spack/spack/pull/13100 you should be able to run `spack install foo` command multiple times in parallel (e.g. `srun -n2 -N1 /path/to/spack install -jxx ...`, and if `foo` is a DAG of packages, then the different installation processes should coordinate and attempt to install multiple dependencies in parallel.

That doesn't resolve your point about how cross-node management would allow for better terminal output. Also, if you encounter issues like in https://github.com/spack/spack/issues/14715 it would be great to know (if multiple users are having an issue, then it becomes more apparent that the issue is with Spack).

**Comment by xjrc** [comment]
I'm very glad to hear that the parallel package build feature has rolled around, @scheibelp; I'll have to give it a spin during my next big environment install! Also, I've been working with off-node builds for another day or so now and I've yet to encounter any issues like #14175, but I'll continue to be vigilant.

As it seems like the state of the art currently is to just run `spack` via `srun` and colorize the output with `spack log-parse --show=errors,warnings FILE`, I consider this issue to be resolved for the time being. Should Spack ever be extended to include cross-node management, we can update this issue and/or the Spack documentation accordingly.

Thanks again, @hainest and @scheibelp!
