### ISSUE TITLE
binary cache: configuration option to download/push all dependencies including build/test

### ISSUE THREAD

**Issue by mc-allen** [spack/spack#15574]
### Rationale

By default, spack does not push build/test dependencies into build mirrors, and doesn't download the same dependencies from the build mirror cache. For use cases that are primarily development oriented, i.e. using spack dev-build or build-env, this is counterproductive as the developers want to be able to bootstrap an environment with the exact toolchains and dependencies that are needed, without making assumptions about prior configuration. The ability to construct a completely isolated and self-contained development environment is key to reproducibility and scaling development across large numbers of developers.

### Description

A change is proposed to add config flag that would configure spack to install all dependencies into an environment, including build/test, and to push the same dependencies up to the cache.

In a spack.yaml, this might look like

```yaml
  config:
    install_deptypes: [all]
    install_missing_compilers: true
```

The effect would be that when ```spack install``` is run, spack would attempt to fetch the specified dependencies in install_deptypes from the remote buildcache. Similarly, when ```spack buildcache create <spec>``` is invoked, all the specified dependencies would be installed to the remote buildcache. If "all" is specified, the full set of build/link/test/run dependencies would be packaged and pushed.

**Comment by rblake-llnl** [comment]
+1 to this request.  

Right now when I use a buildcache and an environment, spack rebuilds build dependencies for items in the buildcache.  This doesn't make any sense.  

Either 

* spack should push the build/test dependencies for a package to the buildcache so they can be pulled by downstream users without having to recompile perl again.  This would increase the sizes of the build cache.
*  spack shouldn't require the build dependencies for things pulled from a build cache. This might mean an environment is missing things like perl if pulled from a buildcache versus built from source.

**Comment by rblake-llnl** [comment]
I have a script from @haampie that does what I need within an environment:

```
for ii in $(spack find --format "yyy {version} /{hash}" | grep -v -E "^(develop|master)" | grep 'yyy' | awk '{ print $3 }'); 
do 
  if spack buildcache check --rebuild-on-error --mirror-url MY_URL -s $ii; 
  then 
    true; 
  else 
    spack buildcache create -af -d MY_URL --only=package $ii; 
  fi; 
done
```

**Comment by haampie** [comment]
`spack buildcache push` pushes build deps now, unless `--without-build-dependencies`.
