### ISSUE TITLE
buildcache keys: fetching key from cache takes absurd amount of time

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#15640]
Trying to fetch a key from a build cache takes an absurd amount of time, if the cache has a significant number of packages:

```
$> spack mirror add e4s https://instinct.nic.uoregon.edu:8083/e4s
$> spack buildcache keys -it
.....
many many minutes of waiting before key is retrieved
```

Since the keys are listed under `index.html` with extension `.key` -- it makes no sense why this operation would depend, in any significant way, on the number of packages in the cache.

Using Spack @ develop (commit 5df9dd2b48)

**Comment by gartung** [comment]
Yes. This is the spidering of all of the links in index.html to find the entry with *.key or *.pub. Your case of an index.html with 1000's of entries shows that the spidering function does not scale.

**Comment by gartung** [comment]
As we discussed the only way to avoid this is to download the public key manually and use `spack gpg trust key` directly.

**Comment by eugeneswalker** [comment]
> As we discussed the only way to avoid this is to download the public key manually and use `spack gpg trust key` directly.

My intention here is just to raise the issue publicly, because it makes zero sense to be spidering an entire build cache to find files with `.key` extension when those files are specifically enumerated in an index document. Perhaps I am wrong, and this is in fact the way people want `buildcache keys` to behave.

**Comment by gartung** [comment]
@eugeneswalker I think I found the problem and this is the fix:
https://github.com/spack/spack/pull/15727

**Comment by gartung** [comment]
When I changed from spidering the build_cache directory for key files to spidering build_cache/index.hrml I set depth=1 which made it read all of the files linked. By setting depth=0 only index.html is read but the link could point to a file that was removed. It will be faster but it might error out.
