### ISSUE TITLE
Non-Safe Installs

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1566]
I noticed the following code in`concretize.py`, with no obvious way to turn it off.  I consider this a security hazard: Spack should refuse by default to install unsafe code (i.e. anything it doesn't have a checksum for).

```
        else:
            # We don't know of any SAFE versions that match the given
            # spec.  Grab the spec's versions and grab the highest
            # *non-open* part of the range of versions it specifies.
            # Someone else can raise an error if this happens,
            # e.g. when we go to fetch it and don't know how.  But it
            # *might* work.
            if not spec.versions or spec.versions == VersionList([':']):
                raise NoValidVersionError(spec)
            else:
                last = spec.versions[-1]
                if isinstance(last, VersionRange):
                    if last.end:
                        spec.versions = ver([last.end])
                    else:
                        spec.versions = ver([last.start])
                else:
                    spec.versions = ver([last])
```

I'm not going to submit a PR right now because I think the issue is bigger than just this code.  But I do think this code should be eliminated; and it's an issue we should be thinking about more comprehensively.

**Comment by adamjstewart** [comment]
I disagree. The way that things currently work, if you try to fetch a version that Spack does not know about, you see:
```
$ spack fetch zlib@5
==> Warning: There is no checksum on file to fetch zlib@5 safely.
==>   Fetch anyway? [y/N]
```
If you respond with "no" (the default), you see:
```
==> Error: Will not fetch zlib@5
Add a checksum or use --no-checksum to skip this check.
```
Giving users the ability to download an unknown version isn't any more of a security risk than providing the `spack fetch --no-checksum` option. As long as Spack doesn't do this silently, I don't see a problem with it.

**Comment by alalazo** [comment]
I agree with @adamjstewart . Reopen if you still consider this a strong security problem.

**Comment by citibeth** [comment]
I do consider it a serious security problem.  However, so far nobody has
done anything about it.
