### ISSUE TITLE
cuda@10.2.89 conflicts for Intel 19.0 are incorrect

### ISSUE THREAD

**Issue by naromero77** [spack/spack#15712]
@psychocoderHPC This commit https://github.com/spack/spack/commit/9c10b80591fec2cf391c97f8f53040c3429dbdec#diff-25617eab209908525fc69e80febde144

broke support for the Intel 19.0 compiler.

CUDA 10.2.89 does in fact work with the Intel 19.0 compiler.
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

Intel 19.0 compiler support started with CUDA 10.1.x
https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-linux/index.html 

The conflicts statement are inclusive with the arguments which at times makes it difficult to express the CUDA conflicts. But basically this line:
https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/cuda.py#L143

say Intel Compiler 19.0 does not work with the CUDA 10.2.89.

One easy fix is to change the line to:
```
conflicts('%intel@19.0:', when='+cuda ^cuda@:10.0.130')
```

or even less verbose:
```
conflicts('%intel@19.0:', when='+cuda ^cuda@:10.0')
```
https://docs.nvidia.com/cuda/archive/10.0/cuda-installation-guide-linux/index.html

**Comment by psychocoderHPC** [comment]
@naromero77 Coud you please provide the second solution as pull request.

CC-ing: @ax3l

**Comment by naromero77** [comment]
will take care of it over the weekend

**Comment by adamjstewart** [comment]
Also pinging @svenevs in case he has anything to add

**Comment by svenevs** [comment]
This looks correct to me, I currently use 19.0 with CUDA 10.2. Thanks @naromero77!

**Comment by ax3l** [comment]
Fix opened in #15764

**Comment by naromero77** [comment]
Thanks -- I was busy most of the weekend. Will take a look shortly.

**Comment by naromero77** [comment]
@ax3l Its working for me thanks. We can close this issue as soon as https://github.com/spack/spack/pull/15764 is merged in.

**Comment by adamjstewart** [comment]
@naromero77 way ahead of you 😝
