### ISSUE TITLE
how to support sse2neon package file for aarch64 paltform

### ISSUE THREAD

**Issue by darmac** [spack/spack#15725]
We found some other package need include `SSE2NEON.h` just as racon pacakge( https://github.com/spack/spack/pull/14529 )
And it's hard for each package by using `SSE2NEON.h` as a patch file (almost 2800+ lines).
So, I want to add a sse2neon pacakge without any compile flow and just supporting a `SSE2NEON.h` file. Then some other packages can depends_on that package.
Is that OK?

PS: [sse2neon repo](https://github.com/jratcliff63367/sse2neon)

**Comment by jserv** [comment]
This issue should be no longer valid since `SSE2NEON` package is merged.
