### ISSUE TITLE
NAMD Build Error

### ISSUE THREAD

**Issue by thomasbrTTU** [spack/spack#15739]
Not sure if there is a new stable version of NAMD that completely builds. Is there a spack command which will update the package.py file for a particular spec. Any help would he greatly appreciated. 

Thanks

### Spack version
```console
$ spack --version
0.13.3
```

### Steps to reproduce the issue

```console
$ spack install namd
==> Installing namd
==> Searching for binary cache of namd
==> No binary for namd found: installing from source
==> Fetching file:///root/NAMD_2.13_Source.tar.gz
curl: (37) Couldn't open file /root/NAMD_2.13_Source.tar.gz
==> Failed to fetch file from URL: file:///root/NAMD_2.13_Source.tar.gz
    Curl failed with error 37
==> Fetching from file:///root/NAMD_2.13_Source.tar.gz failed.
==> Error: FetchError: All fetchers failed for spack-stage-namd-2.13-twrima2abppekvmqimvdbxovki5qlgdu

/root/spack/lib/spack/spack/package.py:1110, in do_fetch:
       1107                raise FetchError("Will not fetch %s" %
       1108                                 self.spec.format('{name}{@version}'), ck_msg)
       1109
  >>   1110        self.stage.create()
       1111        self.stage.fetch(mirror_only)
       1112        self._fetch_time = time.time() - start_time
       1113
```

### Platform and user environment
```commandline
$ uname -a 
Linux nocona-test.hpcc.ttu.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linuxx86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.7.1908 (Core)
``` 

### Additional information
```console
$ spack spec --install-status namd
Input spec
--------------------------------
 -   namd

Concretized
--------------------------------
==> Warning: gcc@8.3.0 cannot build optimized binaries for "zen2". Using best target possible: "zen"
 -   namd@2.13%gcc@8.3.0 fftw=3 interface=none arch=linux-centos7-zen
[+]      ^charmpp@6.9.0%gcc@8.3.0 backend=netlrts build-target=LIBS ~cuda~omp~papi+production~pthreads+shared+smp~syncft~tcp~tracing arch=linux-centos7-zen
[+]      ^fftw@3.3.8%gcc@8.3.0+mpi~openmp~pfft_patches precision=double,float arch=linux-centos7-zen
```Build is failing when it can't fin the NAMD 
```console
$ spack location -s namd
==> Warning: gcc@8.3.0 cannot build optimized binaries for "zen2". Using best target possible: "zen"
/tmp/root/spack-stage/spack-stage-namd-2.13-twrima2abppekvmqimvdbxovki5qlgdu
```
### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
The error message you see is because there is no way to automatically download NAMD. You need to go to the homepage and download it yourself manually. If the tarball is in your current directory, or in a Spack mirror, Spack will detect it and install it.

**Comment by thomasbrTTU** [comment]
Thanks that addressed the error. Later in the build it is encountering a segmentation fault. Tried to look at the source code but not clear what line in the get_go_force2() function. Should I submit a full bug report as a different issue (see bottom of output). Attached is the log file.
[spack-build-out.txt](https://github.com/spack/spack/files/4403112/spack-build-out.txt)


Here is the build error.

==> Warning: gcc@8.3.0 cannot build optimized binaries for "zen2". Using best target possible: "zen"
==> charmpp is already installed in /root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth
==> fftw is already installed in /root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel
==> Installing namd
==> Searching for binary cache of namd
==> No binary for namd found: installing from source
==> Using cached archive: /root/spack/var/spack/cache/_source-cache/archive/9e/9e3323ed856e36e34d5c17a7b0341e38.tar.gz
==> Staging archive: /tmp/root/spack-stage/spack-stage-namd-2.13-twrima2abppekvmqimvdbxovki5qlgdu/NAMD_2.13_Source.tar.gz
==> Created stage in /tmp/root/spack-stage/spack-stage-namd-2.13-twrima2abppekvmqimvdbxovki5qlgdu
==> No patches needed for namd
==> Building namd [MakefilePackage]
==> Executing phase: 'edit'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

3 errors found in build log:
     416    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/LdbCoordinator
            .o -c src/LdbCoordinator.C
     417    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/LJTable.o -c s
            rc/LJTable.C
     418    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/Measure.o -c s
            rc/Measure.C
     419    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/MGridforcePara
            ms.o -c src/MGridforceParams.C
     420    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/MStream.o -c s
            rc/MStream.C
     421    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/MigrateAtomsMs
            g.o -c src/MigrateAtomsMsg.C
  >> 422    src/colvarproxy_namd.C:482:6: error: no declaration matches 'void colvarproxy_namd::init_tcl_pointers()'
     423     void colvarproxy_namd::init_tcl_pointers()
     424          ^~~~~~~~~~~~~~~~
     425    src/colvarproxy_namd.C:482:6: note: no functions named 'void colvarproxy_namd::init_tcl_pointers()'
     426    In file included from src/colvarproxy_namd.C:30:
     427    src/colvarproxy_namd.h:33:7: note: 'class colvarproxy_namd' defined here
     428     class colvarproxy_namd : public colvarproxy, public GlobalMaster {
     429           ^~~~~~~~~~~~~~~~
     430    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/Molecule.o -c
            src/Molecule.C
     431    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/Molecule2.o -c
             src/Molecule2.C
     432    /root/spack/opt/spack/linux-centos7-zen/gcc-6.5.0/gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/bin/g++ -std=c++11 -I/root/spack/opt/spack/lin
            ux-centos7-zen/gcc-8.3.0/charmpp-6.9.0-om3qirpxaqyczmvgoqh34ob4e3nkjdth//include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvar
            s/src -DSTATIC_PLUGIN   -I/root/spack/opt/spack/linux-centos7-zen/gcc-8.3.0/fftw-3.3.8-ggdaglzgidzxp6nidetp3ivloabhkyel/include -DNAMD_FFTW
             -DNAMD_FFTW_3     -DNAMD_VERSION=\"2.13\" -DNAMD_PLATFORM=\"linux-x86_64\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTR
            EE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -m64 -O3 -fexpensive-optimizations -ffast-math -o obj/GoMolecule.o -
            c src/GoMolecule.C
  >> 433    make: *** [obj/colvarproxy_namd.o] Error 1
     434    make: *** Waiting for unfinished jobs....
     435    during GIMPLE pass: recip
     436    src/GoMolecule.C: In member function 'BigReal Molecule::get_go_force2(BigReal, BigReal, BigReal, int, int, BigReal*, BigReal*) const':
     437    src/GoMolecule.C:1456:9: internal compiler error: Segmentation fault
     438     BigReal Molecule::get_go_force2(BigReal x,
     439             ^~~~~~~~

     ...

     446    0xc74966 execute
     447        /tmp/root/spack-stage/spack-stage-gcc-8.3.0-4s3urbs3nu7zamysywhff7u4sq6u66fd/spack-src/gcc/tree-ssa-math-opts.c:733
     448    Please submit a full bug report,
     449    with preprocessed source if appropriate.
     450    Please include the complete backtrace with any bug report.
     451    See <https://github.com/spack/spack/issues> for instructions.
  >> 452    make: *** [obj/GoMolecule.o] Error 1

**Comment by s-sajid-ali** [comment]
There are two errors here :

[1] Internal compiler error while compiling a cxx source. This is outside the scope of spack, you could try lowering the optimization flags or use a different compiler. 

[2] Build system error causing the compiler to complain about cxx declarations. You can try building with https://github.com/spack/spack/pull/15666/ ? I remember encountering many errors for 2.13 that I fixed for a recent develop version, I can't guarantee that it will fix this particular issue but it might be worth trying.
