### ISSUE TITLE
Installation issue: netcdf-c older versions no longer hosted on mirror site

### ISSUE THREAD

**Issue by carsonwoods** [spack/spack#15752]
### Spack version
0.14.1

### Steps to reproduce the issue

```console
$ spack install netcdf-c@4.6.2
==> 35562: Installing netcdf-c
==> Fetching https://www.gfd-dennou.org/arch/netcdf/unidata-mirror/netcdf-c-4.6.2.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: https://www.gfd-dennou.org/arch/netcdf/unidata-mirror/netcdf-c-4.6.2.tar.gz
    URL https://www.gfd-dennou.org/arch/netcdf/unidata-mirror/netcdf-c-4.6.2.tar.gz was not found!
==> Fetching from https://www.gfd-dennou.org/arch/netcdf/unidata-mirror/netcdf-c-4.6.2.tar.gz failed.
==> Error: FetchError: All fetchers failed for spack-stage-netcdf-c-4.6.2-k35zgwrkyyiqm76qbly72fh3u3gxov6c
```
### Additional information
The issue is stemming from the mirror site https://www.gfd-dennou.org/arch/netcdf/unidata-mirror no longer hosting some of the older packages of netcdf. These packages are still hosted on netcdf's github page. I'm really opening this issue to suggest a change of the primary download url for netcdf-c to the official github releases page for the project.

**Comment by adamjstewart** [comment]
This will be fixed by #15641

**Comment by alalazo** [comment]
Closing, since this has been solved by NetCDF maintainers and the mirror site is up again:
```console
$ spack fetch netcdf-c@4.6.2
[...]
==> Fetching from file:///home/culpo/spack-resources/mirrors/sources/_source-cache/archive/c3/c37525981167b3cd82d32e1afa3022afb94e59287db5f116c57f5ed4d9c6a638.tar.gz failed.
==> Fetching https://www.gfd-dennou.org/arch/netcdf/unidata-mirror/netcdf-c-4.6.2.tar.gz
######################################################################## 100,0%
```
See discussion in #15641

**Comment by dazzag24** [comment]
The entire https://www.gfd-dennou.org site seems to be having issues today.  I've just manually edited the spack/0.14.2/spack/var/spack/repos/builtin/packages/netcdf-c/package.py file to point to the ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-c-4.7.3.tar.gz link instead as a temporary workaround
