### ISSUE TITLE
Installation issue: CUDA package create a folder in /usr/local

### ISSUE THREAD

**Issue by SimeonEhrig** [spack/spack#15797]
When I install a cuda package, spack install it into `/usr/local' as well.

### Spack version

```console
$ spack --version
0.14.1-449-a4b3edd68
```

### Steps to reproduce the issue

```console
$ ls /usr/local
bin etc games include lib man sbin share src
$ spack install cuda@9.0.176
... # tested with cuda@9.0.176 and cuda@10.2.89
... # maybe other cuda version has the same problem
$ ls /usr/local
bin cuda etc games include lib man sbin share src
$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

### Platform and user environment

```commandline
$ uname -a 
Linux fwk394 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 18.04.4 LTS
``` 

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@ax3l @svenevs

**Comment by ax3l** [comment]
Hard to imagine, since I am installing CUDA as non-root.

Simeon, can you provide more details where this is happening? Some container partitioning executed as root? What exactly gets installed into `/usr/local`?

**Comment by SimeonEhrig** [comment]
I get this behavior when I install CUDA via Spack while building a container image (Docker and Singularity). During the build time,the user is (fake-)root. I have also tested an installation as normal user and can confirm that this only happen with root permissions.

I also noticed that `/usr/local/cuda` is just a symlink to the last installed CUDA version, which was installed by spack.

``` bash
ls -al /usr/local/
# ...
lrwxrwxrwx  1 root root  137 Apr  2 06:57 cuda -> /opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/cuda-9.1.85-6mp2t7dfp3dnsjwoogf2f426kvqll3vf
# ...
```

**Comment by alalazo** [comment]
@SimeonEhrig Slightly OT, but if you are building a container image for some CUDA application you might consider trying `spack containerize` + #15028 If you build an image with Spack starting from  some CUDA devel image you can:
- Use that image as a starting point in the build stage 
- Employ instead a CUDA base in the final stage

It requires a bit of configuration but in the end you'll obtain a much slimmer image than installing everything via the `cuda` spack package. You can check an example use-case in my [personal Dockerhub repository](https://hub.docker.com/repository/docker/alalazo/gromacs) where I pushed a `gromacs+cuda` image of just 189MB. 

Feel free to ping me here or on Slack if you'd like to have more details.

**Comment by SimeonEhrig** [comment]
@alalazo Thanks for the information. I will check if we can use it for our case, because our use case is a little bit special. We want to use container for the CI and development and execution of our software [Alpaka](https://github.com/ComputationalRadiationPhysics/alpaka). Apaka is an abstraction library which allows to implement an algorithm one time and execute it on different accelerators like CPUs and GPUs. Therefore we have a large build matrix with different gcc, clang, nvcc, clang+CUDA, ect. versions. If we want to build a container for each test case, we get hundreds of them. So we decided to build a container for each compiler containing different versions of it. For example, a container contains `CMake`, different versions of `Boost` and different versions of `CUDA`. Another container replaces `CUDA` with `gcc`. On top of it, we need `Docker` for the CI and `Singularity` for HPC systems. In solving this requirement we use the Python library [hpccm](https://github.com/NVIDIA/hpc-container-maker). Maybe we can replace hpccm with `spack containerize`.

**Comment by ax3l** [comment]
The interactive installer actually asks if one wants to install those symlinks in the system root. Let's see if we can find a flag that we can pass to the `--silent` install...

**Comment by ax3l** [comment]
Reported as Nvidia Bug no. 2927680

**Comment by alalazo** [comment]
Thanks @ax3l!

 @SimeonEhrig Can we close the issue or should we wait for the resolution of the bug reported above?

**Comment by SimeonEhrig** [comment]
We can close it.
