### ISSUE TITLE
Uninstalling software does not remove module file

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#15813]
When I `spack uninstall` something, the module file created by Spack is left behind. This leads to a lot of broken module files laying around that other users can accidentally try to use.

### Spack version

```console
$ spack --version
0.14.1-434-67e081392
```

### Steps to reproduce the issue

```console
$ spack install foo
$ spack uninstall foo
$ ls share/spack/modules
```

### Information on your system

My `modules.yaml`:
```yaml
modules:
    enable::
        # Only generate TCL environment module files
        - tcl
    tcl:
        # Ignore compiler and compiler version in module file name
        naming_scheme: '${PACKAGE}/${VERSION}'
        # Automatically load modules for Java and Python dependencies
        ^java:
              autoload: 'direct'
        ^python:
              autoload: 'direct'
```
I also have the following local modification to Spack that may be the cause of the issue, I'm not sure:
```diff
diff --git a/lib/spack/spack/modules/common.py b/lib/spack/spack/modules/common.py
index 8dee443eb..567b6e8c3 100644
--- a/lib/spack/spack/modules/common.py
+++ b/lib/spack/spack/modules/common.py
@@ -557,7 +557,7 @@ def use_name(self):
         name = os.path.join(*parts)
         # Add optional suffixes based on constraints
         path_elements = [name] + self.conf.suffixes
-        return '-'.join(path_elements)
+        return '/'.join(path_elements)
 
     @property
     def filename(self):
```

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I can't reproduce this on:

* **Spack:** 0.14.2-1262-edd075a5e
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-broadwell

Here's what I tried:
```console
$ tree share/spack/modules
share/spack/modules [error opening dir]

0 directories, 0 files

$ spack find
==> 0 installed packages

$ spack install zlib
==> 8857: Installing zlib
[ ... ]
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/zlib-1.2.11-os3djb57dqdzhaqsl2n7iefz3gwombyi

$ tree share/spack/modules
share/spack/modules
└── linux-ubuntu18.04-broadwell
    └── zlib-1.2.11-gcc-9.0.1-os3djb5

1 directory, 1 file

$ spack uninstall -ay
==> Successfully uninstalled zlib@1.2.11%gcc@9.0.1+optimize+pic+shared arch=linux-ubuntu18.04-broadwell/os3djb5

$ tree share/spack/modules
share/spack/modules [error opening dir]

0 directories, 0 files
```

**Comment by alalazo** [comment]
The situation doesn't change if I try to customize the naming scheme using:
```yaml
modules:
  tcl:
    projections:
      all: '{name}/{version}'
```
Marking this issue as unreproducible for now, feel free to remove the tag if there's a reproducer I missed.

**Comment by becker33** [comment]
@adamjstewart are you still able to reproduce this issue?

**Comment by adamjstewart** [comment]
I don't have time to try to reproduce this right now. Tbh, I don't even use modules anymore, Spack Environments is all I need. I'll close this and we can reopen if anyone else stumbles on the same problem.
