### ISSUE TITLE
intel@18.0.4 installs binaries that report 18.0.5

### ISSUE THREAD

**Issue by anderbubble** [spack/spack#15811]
The intel package @18.0.4 installs binaries that report version 18.0.5. I noticed this when `spack compiler find` pulled them in as 18.0.5.

### Spack version

```console
$ spack --version
0.14.1-454-146bc60
```

### Steps to reproduce the issue

```console
$ spack install intel@18.0.4
$ $(spack location -i intel@18.0.4)/bin/icc --version
icc (ICC) 18.0.5 20180823
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
```

### Information on your system

RHEL7.6

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
@anderbubble The `url` for the `intel@18.0.4` package seems to point to a tarball that contains "update4" in the name. Can you check if this is the case? I'm wondering if the issue is with upstream rather than Spack.

**Comment by anderbubble** [comment]
@alalazo are you just asking me to confirm for sure that the tar that says "update4" really does contain a binary that reports version 18.0.5?

**Comment by alalazo** [comment]
@anderbubble Sorry, for not being clear. I already checked that, what I'm not sure about is if it is a typo in our package or Intel's fault for having bumped patch version wrongly. Do you have any idea if "parallel_studio_xe_2018_update4" maps to 18.0.4 or if it's some weird numbering scheme that Intel adopts and the compiler version of `"2018_update4" is thus unrelated?

**Comment by alalazo** [comment]
@anderbubble Nevermind, I found [this](https://software.intel.com/en-us/articles/intel-compiler-and-composer-update-version-numbers-to-compiler-version-number-mapping) (thanks @rmsds ) which sounds weird but somehow doesn't surprise me :sweat: It seems Intel passed from `18.0.3` in update 3 to `18.0.5` in update 4. I'll be submitting a PR soon.
