### ISSUE TITLE
Installation issue: hwloc

### ISSUE THREAD

**Issue by hainest** [spack/spack#15836]
On cori@NERSC and theta@ALCF, #7483 introduced a build regression.

    if '@2.0.0:' in self.spec:
        args.append('--enable-netloc')

netloc requires MPI, yet `hwloc` does not have an MPI dependency because it is commonly depended upon by MPI implementations (e.g., OpenMPI and at least one version of mpich- #15302).

Here is the debug log:

[tau.gcc@8.3.0.log](https://github.com/spack/spack/files/4423263/tau.gcc%408.3.0.log)

The relevant part is

	make[2]: Entering directory '/tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi'
		CC       netloc_rank_order.o
		CC       netloc_mpi_find_hosts-netloc_mpi_find_hosts.o
		CCLD     netloc_rank_order
		CCLD     netloc_mpi_find_hosts
	/usr/bin/ld: netloc_mpi_find_hosts-netloc_mpi_find_hosts.o: in function `main':
	/tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:40: undefined reference to `MPI_Init'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:42: undefined reference to `MPI_Comm_rank'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:43: undefined reference to `MPI_Comm_size'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:48: undefined reference to `MPI_Abort'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:57: undefined reference to `MPI_Get_processor_name'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:157: undefined reference to `MPI_Send'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:159: undefined reference to `MPI_Send'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:162: undefined reference to `MPI_Recv'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:223: undefined reference to `MPI_Finalize'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:93: undefined reference to `MPI_Recv'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:99: undefined reference to `MPI_Recv'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:116: undefined reference to `MPI_Send'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:112: undefined reference to `MPI_Send'
	/usr/bin/ld: /tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/utils/netloc/mpi/netloc_mpi_find_hosts.c:65: undefined reference to `MPI_Abort'
	collect2: error: ld returned 1 exit status

The detailed compilation logs:
[spack-cc-hwloc-naj47dq.in.log](https://github.com/spack/spack/files/4423287/spack-cc-hwloc-naj47dq.in.log)
[spack-cc-hwloc-naj47dq.out.log](https://github.com/spack/spack/files/4423288/spack-cc-hwloc-naj47dq.out.log)

Unsurprisingly, the compiler link directories don't include an MPI source:

	cc
	-g
	-O2
	-o
	.libs/netloc_mpi_find_hosts
	netloc_mpi_find_hosts-netloc_mpi_find_hosts.o
	../../../netloc/.libs/libnetloc.so
	-L/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libpciaccess-0.13.5-3w47xhqx6yyf25w3xl6la7qmeswp2mx5/lib
	-L/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libxml2-2.9.9-ys6suob3jslml7w6bfgovhytvicsiuey/lib
	-L/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/xz-5.2.5-v6hllz4ig7jsyb4wjkdtpaejcmuniv77/lib
	-L/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/zlib-1.2.11-opn2xungd3hfytvpnj5h6yt6bandexht/lib
	-L/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libiconv-1.16-uwyfaltarblqnu3opnriickfqwku234g/lib
	/tmp/thaines/spack-stage/spack-stage-hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/spack-src/hwloc/.libs/libhwloc.so
	../../../hwloc/.libs/libhwloc.so
	/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libpciaccess-0.13.5-3w47xhqx6yyf25w3xl6la7qmeswp2mx5/lib/libpciaccess.so
	/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libxml2-2.9.9-ys6suob3jslml7w6bfgovhytvicsiuey/lib/libxml2.so
	-ldl
	-lz
	/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/xz-5.2.5-v6hllz4ig7jsyb4wjkdtpaejcmuniv77/lib/liblzma.so
	-lpthread
	/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libiconv-1.16-uwyfaltarblqnu3opnriickfqwku234g/lib/libiconv.so
	-lm
	-pthread
	-Wl,-rpath
	-Wl,/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/hwloc-2.1.0-naj47dqjmbfpkol3dkjwrdtfz6xsv7qy/lib
	-Wl,-rpath
	-Wl,/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libpciaccess-0.13.5-3w47xhqx6yyf25w3xl6la7qmeswp2mx5/lib
	-Wl,-rpath
	-Wl,/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libxml2-2.9.9-ys6suob3jslml7w6bfgovhytvicsiuey/lib
	-Wl,-rpath
	-Wl,/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/xz-5.2.5-v6hllz4ig7jsyb4wjkdtpaejcmuniv77/lib
	-Wl,-rpath
	-Wl,/global/cscratch1/sd/thaines/spack/opt/spack/cray-cnl7-haswell/gcc-8.3.0/libiconv-1.16-uwyfaltarblqnu3opnriickfqwku234g/lib

I do not have an MPI module loaded

	$ module list
	Currently Loaded Modulefiles:
	1) modules/3.2.11.4                                 17) job/2.2.4-7.0.1.1_3.31__g36b56f4.ari
	2) nsg/1.2.0                                        18) dvs/2.12_2.2.151-7.0.1.1_5.33__g7eb5e703
	3) altd/2.0                                         19) alps/6.6.57-7.0.1.1_5.5__g1b735148.ari
	4) darshan/3.1.7                                    20) rca/2.2.20-7.0.1.1_4.37__g8e3fb5b.ari
	5) cray-mpich/7.7.10                                21) atp/2.1.3
	6) craype-haswell                                   22) PrgEnv-gnu/6.0.5
	7) craype-hugepages2M                               23) llvm/9.0.1
	8) craype-network-aries                             24) gcc/8.3.0
	9) craype/2.6.2                                     25) git/2.21.0
	10) cray-libsci/19.06.1                              26) cray-python/3.7.3.2
	11) udreg/2.3.2-7.0.1.1_3.26__g8175d3d.ari           27) boost-1.70.0-gcc-8.3.0-c7og6c2
	12) ugni/6.0.14.0-7.0.1.1_7.29__ge78e5b0.ari         28) cmake-3.16.5-gcc-8.3.0-rfdshcr
	13) pmi/5.0.14                                       29) elfutils-0.178-gcc-8.3.0-juylyy7
	14) dmapp/7.1.1-7.0.1.1_4.39__g38cf134.ari           30) intel-tbb-2020.1-gcc-8.3.0-wrxfw5i
	15) gni-headers/5.0.12.0-7.0.1.1_6.24__g3b1768f.ari  31) nano-4.4-gcc-8.3.0-kwiutcn
	16) xpmem/2.2.20-7.0.1.1_4.6__g0475745.ari           32) perl-5.30.1-gcc-8.3.0-d6sik3t

---
### Spack version
    $ spack --version
        0.14.1-411-5f308daf0

    $ git branch -v
        develop c3c057f2b package: update flit and py-pyelftools versions (#15817)

### Steps to reproduce the issue

    $ spack install hwloc@2.1.0%gcc@8.3.0~cairo~cuda~gl+libxml2~nvml+pci+shared

NB: This is the variant used by `tau` which is what I was actually installing.

### Platform and user environment

    $ uname -a
        Linux cori04 4.12.14-150.47-default #1 SMP Wed Dec 18 15:05:52 UTC 2019 (8162e25) x86_64 x86_64 x86_64 GNU/Linux

    $ lsb_release -d
        Description:	SUSE Linux Enterprise Server 15

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by hainest** [comment]
@scheibelp  I just noticed you assigned this to yourself. I am currently testing the following patch that just creates a `netloc` variant; It isn't complete as it doesn't tell the concretizer it depends on MPI because I couldn't get that to work. Thoughts?

    diff --git a/var/spack/repos/builtin/packages/hwloc/package.py b/var/spack/repos/builtin/packages/hwloc/package.py
    index 2b7968a..0d33b04 100644
    --- a/var/spack/repos/builtin/packages/hwloc/package.py
    +++ b/var/spack/repos/builtin/packages/hwloc/package.py
    @@ -57,6 +57,14 @@ class Hwloc(AutotoolsPackage):
             default=False,
             description='Enable the Cairo back-end of hwloc\'s lstopo command'
         )
    +    variant(
    +        'netloc',
    +        default=False,
    +        description="Enable netloc [requires MPI]"
    +    )
    +    
    +    # netloc isn't available until version 2.0.0
    +    conflicts('+netloc', when="@:1.99.99")
     
         depends_on('pkgconfig', type='build')
         depends_on('m4', type='build', when='@master')
    @@ -81,7 +89,7 @@ def configure_args(self):
                 # (Alternatively, we could require OpenCL as dependency.)
                 "--disable-opencl",
             ]
    -        if '@2.0.0:' in self.spec:
    +        if '+netloc' in self.spec:
                 args.append('--enable-netloc')
     
             args.extend(self.enable_or_disable('cairo'))

**Comment by scheibelp** [comment]
Hi @hainest I think a variant is the correct way to go (and setting `False` as the default it also a good idea since it means that MPI implementations which need hwloc won't get "caught in a loop"). 

You can conditionally add MPI as a dependency in the following manner:

```
depends_on('mpi', when='+netloc') # referring to the new variant you added
```

does that work for you?

**Comment by hainest** [comment]
@scheibelp That was the first one I tried, but it gives the error

    $ spack spec hwloc+netloc
    Input spec
    --------------------------------
    hwloc+netloc

    Concretized
    --------------------------------
    ==> Error: 2.1.0 does not satisfy 1.11.11

This is because openmpi explicitly depends on `hwloc@1.11.11` because it doesn't support the 2.0 interface.

    $ spack spec openmpi
    Input spec
    --------------------------------
    openmpi

    Concretized
    --------------------------------
    openmpi@3.1.5%gcc@8.3.0~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-linuxmint18-piledriver
        ^hwloc@1.11.11%gcc@8.3.0~cairo~cuda~gl+libxml2~netloc~nvml+pci+shared arch=linux-linuxmint18-piledriver

**Comment by scheibelp** [comment]
Ideally Spack could pick another MPI provider automatically, but it is picking the OpenMPI one, users would have to choose something like:

```
spack spec hwloc+netloc ^mpich
```

in any case, it is not an issue with the `depends_on` clause you added, but rather with Spack. It would be fine to add it and I could address https://github.com/spack/spack/issues/15836#issuecomment-611879445 later (assuming specifying the MPI provider dependency in `spack spec` works for you).

**Comment by hainest** [comment]
I checked all of the other mpi providers, and it works with them all except fujitsu-mpi, mpt, and spectrum-mpi. The error message is always like

    $ spack spec hwloc+netloc ^fujitsu-mpi
    Input spec
    --------------------------------
    hwloc+netloc
        ^fujitsu-mpi

    Concretized
    --------------------------------
    ==> Error: There are no valid versions for fujitsu-mpi that match ':'

I'm assuming that's not much of a problem as those are vendor-provided, and I don't have them installed on my system.

**Comment by scheibelp** [comment]
> I'm assuming that's not much of a problem as those are vendor-provided

Yes: that's fine. Thanks for adding the PR! I'll be looking at it today or on Tuesday
