### ISSUE TITLE
module: command not found under AMD-based Arch with environment-modules installed on confusing dual arch 

### ISSUE THREAD

**Issue by DeeDiveT** [spack/spack#15843]
Hello, I'm trying to install [some applications](https://exawind-builder.readthedocs.io/) which use spack as package manage tool.
In the installation script of that application, it needs `module` command. Also, I find command module could be shipped with spack bootstrap(spack install environment-modules.
However, it seems that when I execute spack bootstrap, it installs dependencies in another arch, namely 

    $ spack find
    ==> 35 installed packages
    -- linux-ubuntu18.04-x86_64 / gcc@7.5.0 -------------------------
    environment-modules@4.4.1  tcl@8.6.8  zlib@1.2.11
    -- linux-ubuntu18.04-zen / gcc@7.5.0 ----------------------------
    autoconf@2.69    hwloc@1.11.11        ncurses@6.0             pkgconf@1.6.3
    automake@1.16.2  hypre@develop        netcdf-c@4.7.3          readline@8.0
    boost@1.68.0     libiconv@1.16        netlib-lapack@3.8.0     superlu@4.3
    bzip2@1.0.6      libpciaccess@0.13.5  numactl@2.0.12          tcl@8.6.8
    cmake@3.16.2     libsigsegv@2.12      openmpi@3.1.5           util-macros@1.19.1
    diffutils@3.7    libtool@2.4.6        openssl@1.1.1d          xz@5.2.5
    gdbm@1.18.1      libxml2@2.9.8        parallel-netcdf@1.12.1  yaml-cpp@0.6.2
    hdf5@1.10.4      m4@1.4.18            perl@5.30.1             zlib@1.2.11

This is different from `spack install` which will install on linux-ubuntu18.04-zen by default.  This causes even I can have command module in command interface, the script still cannot find the module command. 

I'm fully aware of similar previous issues, but i didn't find a solution after looking through all of them carefully, is there anyone could help me?

Millions of thanks in advance.

### Spack version

```console
$ spack --version
0.14.1-474-144557e94
```

### Error Message

module: command not found

### Information on your system

Ubuntu 18.04

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
The old `spack bootstrap` has been removed, and now the same command is used to bootstrap Spack binary dependencies (like `clingo`). That said, one can find any prefix with:
```console
$ spack find -p environment-modules
```
Within the prefix `environment-modules` has some scripts that need to be sourced.
