### ISSUE TITLE
Improve the error message when the database version is not what is expected

### ISSUE THREAD

**Issue by eschnett** [spack/spack#1585]
After a `git pull`, Spack tells me

```
$ spack install bliss %gcc@4.9.3
==> Error: Expected database version 0.9.1 but found version 0.9.2
```

I have no idea where this error comes from or how to remedy it. Spack should output more context; e.g. a file or directory name would already make a world of difference, or the name of the database software/package that produces this error, etc.

**Comment by eschnett** [comment]
Note: I found a file `opt/spack/.spack-db/index.yaml` that contains a line `version: 0.9.2` that might be relevant.

**Comment by adamjstewart** [comment]
That's strange. The current version of Spack is 0.9.1 on the latest development branch.

**Comment by alalazo** [comment]
Error message has been improved in cdc2ebee9018cc4cf067d73f269628901a8d4487
