### ISSUE TITLE
Spack breaking when installing Python in an environment

### ISSUE THREAD

**Issue by mdorier** [spack/spack#15884]
Spack breaks when installing an environment that contains python + a package that fails to build.

### Steps to reproduce the issue

Assume that you have a package "somepackage" that fails to build with spack (in my case this was a one my own python packages that would fail in the setup.py script for some reasons). Do the following to break spack:

```console
$ spack env create myenv
$ spack env activate myenv
$ spack add python
$ spack add somepackage
$ spack install # this will install everything (including python) up to somepackage, which will fail to install, as expected
```
After this series of commands, all spack commands will fail with a RuntimeError from python indicating:
```
RuntimeError: Unable to locate python command in /projects/spack/var/spack/environments/myenv/.spack-env/view/bin
```

**Comment by adamjstewart** [comment]
I experienced this exact same problem, although I was struggling to figure out exactly how to reproduce it. The workaround I've found for now is to `rm -rf .spack-env spack.lock` and start over. You won't have to re-install anything, just re-concretize and re-symlink.

**Comment by mdorier** [comment]
Yes, I figured out this solution too, though it still requires to log out and log back in to your machine (or open a new terminal if it's your laptop).

The problem is, I had this happen in the middle of a CI job that tries to build about 20 packages, reporting which ones failed to build and which ones didn't. You can imagine how puzzled I was that everytime this particular package that required python failed to build, all the subsequent packages failed as well (simply because the spack command would no longer work).

**Comment by alalazo** [comment]
[Another case](https://groups.google.com/forum/#!topic/spack/RBzLouf-vGA) of a user hit by this
