### ISSUE TITLE
Proposal: procedure to deprecate old versions of software

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#15896]
We need an official procedure for removing old versions of software.

### Rationale

There are many reasons to remove old versions of software:
1. Security vulnerabilities (most serious reason)
2. Changing build systems that increase package complexity
3. Changing dependencies/patches/resources/flags that increase package complexity
4. Maintainer/developer inability/unwillingness to support old versions
5. No longer available for download (right to be forgotten)

At the same time, there are many reasons to keep old versions of software:
1. Reproducibility
2. Requirements for older packages (e.g. some packages still rely on Qt 3)

Until LLNL hosts their own source/binary mirror that we can get download statistics from, we have no way of knowing whether or not old versions of software are actually in use. In the past, I've simply removed old versions, but I've gotten in trouble for doing this from users who still relied on that software.

### Description

I propose the addition of the following syntax:
```python
version('1.2.3', sha256='...', deprecated=True)
```
This is similar to the existing `preferred=True` parameter. For this parameter, I propose the following behavior:
1. `spack info` will only list non-deprecated versions (or add a "deprecated" tag)
2. `spack install` (and other commands that fetch) will print a `tty.warn` with the following behavior:
   ```console
   ==> Warning: This version is deprecated and may be removed in a future Spack release.
   ==>   Fetch anyway? [y/N] y
   ==> Fetching deprecated version.
     If you are willing to be a maintainer for this version of the package, submit a PR to remove `deprecated=True`.
   ```
   ```console
   ==> Warning: This version is deprecated and may be removed in a future Spack release.
   ==>   Fetch anyway? [y/N] n
   ==> Error: Will not fetch package@version
     If you are willing to be a maintainer for this version of the package, submit a PR to remove `deprecated=True`.
   ```
   This is analogous to how fetching versions without checksums currently works. We can add a `--deprecated` flag similar to `--no-checksum` for preserving the ability to do automated builds.

This provides a means for warning users that old versions are no longer supported. If anyone complains that they still need this software, they should volunteer themselves to be package "maintainers" and remove the `deprecated=True` flag. If no one complains for a full release cycle, we can remove these versions from the package. If we want to be really explicit, we can add `deprecated=False` for things like Qt 3 which are required for older software.

### Additional information

Some PRs like #15420 help to mitigate this issue, but if we instead deprecate old versions and see if anyone uses them, we may find that legacy packages aren't needed most of the time. Once LLNL hosts their own source/binary mirror, we can at least tell how many people will be impacted, but we will still need a way of herding users to newer versions once the concretizer takes into account already-installed software. Even if older versions are still in use, I believe package maintainers/developers should have the right to stop supporting old versions of their software if no one else is willing to maintain it.

Another question worth discussing is if we want a way to deprecate entire packages (for example, when a duplicate package exists, or a package is renamed). By deprecating an entire package, we can prevent breaking changes from being merged until after a full release cycle. We can do this by either adding `deprecated=True` to every version, or adding `deprecated = True` as a package-level variable.

@alalazo @tgamblin @scheibelp

**Comment by ChristianTackeGSI** [comment]
I like this idea.
One wish: There should be a `--deprecated` option to `find`, so that one can check, if one has installed deprecated versions/packages.
Maybe even the same option for `uninstall` to remove the deprecated things?
