### ISSUE TITLE
Document `Version` methods

### ISSUE THREAD

**Issue by eschnett** [spack/spack#1590]
The methods `concrete`, `dashed`, `highest`, `intersection`, `is_successor`, `lowest`, `overlaps`, `underscored`, `union` are not documented.

**Comment by citibeth** [comment]
Git blame says it's probably best if @tgamblin documents these methods in the API docs.

**Comment by adamjstewart** [comment]
`dashed` and `underscored` are now documented:
http://spack.readthedocs.io/en/latest/packaging_guide.html#version-urls

Some of the other methods are documented in the API Docs:
http://spack.readthedocs.io/en/latest/spack.html#spack.version.Version
but I don't think I've ever used any of them. They are mostly used internally. Do you see a need to document any of these? I agree that they should at least have docstrings.

**Comment by alalazo** [comment]
The methods that are more frequently used in packages have docstrings since a while now. Closing this, but feel free to reopen (or submit a PR) if you feel some still need better documentation.
