### ISSUE TITLE
Installation issue: openfoam-org v7

### ISSUE THREAD

**Issue by orliac** [spack/spack#15946]
Note: `spack debug report` fails:

> usage: spack debug [-h] SUBCOMMAND ...
> spack debug: error: argument SUBCOMMAND: invalid choice: 'report' choose from:
>     create-db-tarball

```console
$ uname -a
Linux login1.wally.unil.ch 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ spack -V
0.13.3-1359-09dfbf9
```

### Steps to reproduce the issue
```console
$ spack install openfoam-org@7 %gcc@8.3.0
$ spack load openfoam-org@7 %gcc@8.3.0
$ decomposePar 
decomposePar: error while loading shared libraries: libmetisDecomp.so: cannot open shared object file: No such file or directory
```
Note: the library can be found in the lib/dummy directory but likely should be considered when not asking for the variant "metis" (which works fine btw)

### Information on your system
[spack-db.master.09dfbf9.2020-04-08-130820.tar.gz](https://github.com/spack/spack/files/4450089/spack-db.master.09dfbf9.2020-04-08-130820.tar.gz)
[spack-build-env.txt](https://github.com/spack/spack/files/4450098/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4450099/spack-build-out.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
I was able to reproduce this error. #15949 seems to fix the issue for me.

**Comment by adamjstewart** [comment]
Pinging @olesenm

**Comment by olesenm** [comment]
I don't have much time for this one at the moment, but the fix (symmetric with the `openfoam` package seems to make sense. Following up on environment discussions on #15949.
