### ISSUE TITLE
Question: How to tell spack to use bzip2 and zlib from system?

### ISSUE THREAD

**Issue by dennisklein** [spack/spack#15970]
With the current `develop` branch (5320268033570d93d40b431fc4d93893572bac0b) I get:

```
$ spack spec fairlogger@1.5.0+pretty
Input spec
--------------------------------
fairlogger@1.5.0+pretty

Concretized
--------------------------------
fairlogger@1.5.0%gcc@9.2.1 build_type=RelWithDebInfo cxxstd=default +pretty arch=linux-fedora31-skylake
    ^boost@1.72.0%gcc@9.2.1+atomic+chrono~clanglibcpp~container~context~coroutine cxxstd=98 +date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout visibility=hidden +wave arch=linux-fedora31-skylake
        ^bzip2@1.0.8%gcc@9.2.1+shared arch=linux-fedora31-skylake
            ^diffutils@3.7%gcc@9.2.1 arch=linux-fedora31-skylake
                ^libiconv@1.16%gcc@9.2.1 arch=linux-fedora31-skylake
        ^zlib@1.2.11%gcc@9.2.1+optimize+pic+shared arch=linux-fedora31-skylake
    ^cmake@3.17.0%gcc@9.2.1~doc+ncurses+openssl+ownlibs~qt arch=linux-fedora31-skylake
        ^ncurses@6.2%gcc@9.2.1~symlinks+termlib arch=linux-fedora31-skylake
            ^pkgconf@1.6.3%gcc@9.2.1 arch=linux-fedora31-skylake
        ^openssl@1.1.1f%gcc@9.2.1+systemcerts arch=linux-fedora31-skylake
            ^perl@5.30.1%gcc@9.2.1+cpanm+shared+threads arch=linux-fedora31-skylake
                ^gdbm@1.18.1%gcc@9.2.1 arch=linux-fedora31-skylake
                    ^readline@8.0%gcc@9.2.1 arch=linux-fedora31-skylake
```

Now marking several packages to be picked up from the system
```
$ cat ~/.spack/packages.yaml
packages:
  bzip2:
    paths:
      bzip2 os=fedora31: /usr
  cmake:
    paths:
      cmake os=fedora31: /usr
  zlib:
    paths:
      zlib os=fedora31: /usr
```
results in
```
$ spack spec fairlogger@1.5.0+pretty
Input spec
--------------------------------
fairlogger@1.5.0+pretty

Concretized
--------------------------------
fairlogger@1.5.0%gcc@9.2.1 build_type=RelWithDebInfo cxxstd=default +pretty arch=linux-fedora31-skylake
    ^boost@1.72.0%gcc@9.2.1+atomic+chrono~clanglibcpp~container~context~coroutine cxxstd=98 +date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout visibility=hidden +wave arch=linux-fedora31-skylake
        ^bzip2@1.0.8%gcc@9.2.1+shared arch=linux-fedora31-skylake
            ^diffutils@3.7%gcc@9.2.1 arch=linux-fedora31-skylake
                ^libiconv@1.16%gcc@9.2.1 arch=linux-fedora31-skylake
        ^zlib@1.2.11%gcc@9.2.1+optimize+pic+shared arch=linux-fedora31-skylake
    ^cmake@3.17.0%gcc@9.2.1~doc+ncurses+openssl+ownlibs~qt arch=linux-fedora31-skylake
```

Somehow this only works for `cmake`. However, tweaking the `packages.yaml` to be explicit about the target, achieves my goal:

```
$ cat ~/.spack/packages.yaml
packages:
  bzip2:
    paths:
      bzip2 os=fedora31 target=skylake: /usr
  cmake:
    paths:
      cmake os=fedora31: /usr
  zlib:
    paths:
      zlib os=fedora31 target=skylake: /usr
```
```
$ spack spec fairlogger@1.5.0+pretty
Input spec
--------------------------------
fairlogger@1.5.0+pretty

Concretized
--------------------------------
fairlogger@1.5.0%gcc@9.2.1 build_type=RelWithDebInfo cxxstd=default +pretty arch=linux-fedora31-skylake
    ^boost@1.72.0%gcc@9.2.1+atomic+chrono~clanglibcpp~container~context~coroutine cxxstd=98 +date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout visibility=hidden +wave arch=linux-fedora31-skylake
        ^bzip2@1.0.8%gcc@9.2.1+shared arch=linux-fedora31-skylake
        ^zlib@1.2.11%gcc@9.2.1+optimize+pic+shared arch=linux-fedora31-skylake
    ^cmake@3.17.0%gcc@9.2.1~doc+ncurses+openssl+ownlibs~qt arch=linux-fedora31-skylake
```
```
$ spack install fairlogger@1.5.0+pretty
==> bzip2@1.0.8 : externally installed in /usr
==> bzip2@1.0.8 : generating module file
==> bzip2@1.0.8 : registering into DB
[+] /usr
==> zlib@1.2.11 : externally installed in /usr
==> zlib@1.2.11 : generating module file
==> zlib@1.2.11 : registering into DB
[+] /usr
==> cmake@3.17.0 : externally installed in /usr
==> cmake@3.17.0 : generating module file
==> cmake@3.17.0 : registering into DB
[+] /usr
==> 2093636: Installing boost
(...)
```

*  Why do I need to be explicit about the target for `bzip2` and `zlib` and not for `cmake` (dependency type?)?
*  If this is not a bug, how can I mark `bzip2` and `zlib` external without being explicit about the target?

**Comment by dennisklein** [comment]
Not specifying the any or the arch fields, also works:

```
$ cat ~/.spack/packages.yaml
packages:
  bzip2:
    paths:
      bzip2: /usr
  cmake:
    paths:
      cmake: /usr
  zlib:
    paths:
      zlib: /usr
```

Unfortunately, I eventually have to provide different paths depending on the os field.

**Comment by dennisklein** [comment]
- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
* **Spack:** 0.14.1-579-532026803
* **Python**: 3.7.6
* **Platform**: linux-fedora31-skylake
- [x] I have searched the issues of this repo for half an hour and did not find a duplicate ;)

**Comment by adamjstewart** [comment]
A couple of things to note about this behavior:

1. `spack spec` will not reflect any changes when adding external packages until the package has been registered in the database via `spack install`
2. Spack may choose to install a newer version of a package even if an external package is present, unless you add `buildable: False` to your `packages.yaml`
3. I wouldn't recommend adding external packages without any version specification, I've had problems with this in the past

The behavior you're seeing seems pretty weird, but might be at least partially explained by 1, if not 2.

**Comment by dennisklein** [comment]
> 2. Spack may choose to install a newer version of a package even if an external package is present, unless you add buildable: False to your packages.yaml

In general, for our use case, we want this behavior, so `buildable: False` is not an option for us. Unless: Can I use it platform/os-dependent?

> 3. I wouldn't recommend adding external packages without any version specification, I've had problems with this in the past

I agree, meanwhile I found also that spack will also log wrong version numbers that are supposedly taken from external (if no version is specified in `packages.yaml`).

**Comment by adamjstewart** [comment]
> Can I use it platform/os-dependent?

It can be platform-dependent (by putting things in `linux/packages.yaml` and `darwin/packages.yaml`) but not OS-dependent. Also see #3508 for another bug you might encounter if you are dealing with multiple OSes. Multiple platforms should work fine though.

**Comment by dennisklein** [comment]
> Also see #3508 for another bug you might encounter if you are dealing with multiple OSes.

Thanks for the headsup, this will likely affect me, too. Will look into it. I definitely want a working solution going also for multiple OSes.
