### ISSUE TITLE
checksum does not use url created in url_for

### ISSUE THREAD

**Issue by jacobmerson** [spack/spack#15985]
spack checksum does not use the `url_for` function to look for versions that may be located at different urls

### Steps to reproduce the issue
Create test package
```python
from spack.spec import ConflictsInSpecError


yaml_cpp_tests_libcxx_error_msg = 'yaml-cpp tests incompatible with libc++'


class TestPackage(CMakePackage):
    """A YAML parser and emitter in C++"""

    homepage = "https://github.com/jbeder/yaml-cpp"
    #url      = "https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.5.3.tar.gz"
    git      = "https://github.com/jbeder/yaml-cpp.git"

    def url_for_version(self, version):
        url = "https://github.com/jbeder/yaml-cpp/archive/{0}-{1}.tar.gz"
        if version < Version('0.5.3'):
            return url.format('release',version)
        else:
            return url.format('yaml-cpp',version)
```
```console
$ spack checksum test-package
Error: Could not find any versions for test-package
```

### Error Message

```console
$ spack --debug --stacktrace checksum test-package
lib/spack/spack/cmd/__init__.py:102 ==> [2020-04-09-21:17:37.863469, 19046] Imported checksum from built-in commands
lib/spack/spack/cmd/__init__.py:102 ==> [2020-04-09-21:17:37.864401, 19046] Imported checksum from built-in commands
lib/spack/spack/config.py:727 ==> [2020-04-09-21:17:37.866602, 19046] Reading config file /lore/mersoj/spack/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:727 ==> [2020-04-09-21:17:37.868508, 19046] Reading config file /users/mersoj/.spack/linux/repos.yaml
lib/spack/spack/cmd/checksum.py:56 ==> [2020-04-09-21:17:37.961179, 19046] Error: Could not find any versions for test-package
lib/spack/spack/config.py:727 ==> [2020-04-09-21:17:37.961651, 19046] Reading config file /lore/mersoj/spack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:727 ==> [2020-04-09-21:17:37.978666, 19046] Reading config file /users/mersoj/.spack/config.yaml
Traceback (most recent call last):
  File "/lore/mersoj/spack/spack/lib/spack/spack/main.py", line 763, in main
    return _invoke_command(command, parser, args, unknown)
  File "/lore/mersoj/spack/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/lore/mersoj/spack/spack/lib/spack/spack/cmd/checksum.py", line 56, in checksum
    tty.die("Could not find any versions for {0}".format(pkg.name))
  File "/lore/mersoj/spack/spack/lib/spack/llnl/util/tty/__init__.py", line 227, in die
    sys.exit(1)
SystemExit: 1
```

### Information on your system
* **Spack:** 0.14.1-589-0c0c666
* **Python:** 2.7.5
* **Platform:** linux-rhel7-skylake

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
I'm not sure if I would consider this to be a bug, as this was never the intended purpose of `url_for_version`. `url_for_version` is a programmatic method of finding a URL given a version number. `url` and `list_url` are the only variables used to search for new versions. I'm not opposed to changing this, but I'm curious how you think this should work? Either way, it would require a significant refactoring to unify them.

**Comment by jacobmerson** [comment]
I think I understand the logic behind only using the url for finding the tarballs to checksum...the url should point to the most recent tarball path, and the most used case is to checksum the most recently added packages.

I ran into this when I was modifying a package to include older releases which were needed upstream. My thought was I could add the `url_for` function, checksum the old versions I wanted and be on my way...

As a naive user, my thought with the `url_for` function is that it essentially should create a "list" of urls that are relevant to the package. So, I expected that when I run checksum it would give me a list of all of the versions which can be found with the (version appropriate) urls generated in `url_for`

Since the `spack checksum` command is mostly a convenience function anyways, I don't see this as a critical issue, however it was surprising behavior, and made me concerned that I was using `url_for` incorrectly.

**Comment by adamjstewart** [comment]
There is also a new `urls` variable intended for a list of source mirrors. I don’t think checksum supports that but maybe it could.
