### ISSUE TITLE
Installation issue: petsc  (package iconv not found)

### ISSUE THREAD

**Issue by tartarini** [spack/spack#16035]
@jedbrown @BarrySmith @balay 

I have tried to install petsc with the instructions below and I get the error "Error: Package 'iconv' not found."

I installed libiconv with spack but it didn't solve.

### Steps to reproduce the issue

```console
$ spack install petsc@3.10.0

# same with:

$ spack install petsc@3.10.0 %gcc@8.2.0

```

### Information on your system

* **Spack:** 0.14.1
* **Python:** 3.8.0
* **Platform:** linux-centos7-skylake_avx512

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by balay** [comment]
Likely there was an error with attaching logs. Can you retry? or just copy/paste `spack spec petsc@3.10.0`

icov is not a direct dependency of petsc.

**Comment by balay** [comment]
I see its a dependency of openmpi and mpich. I don't know what issues you are encountering - you can likely avoid `libiconv` with

```
spack install petsc@3.10.0 ^mpich~libxml2
```
And we recommend using latest petsc - that would be petsc-3.13. If for some reason - you have to use petsc-3.10 - suggest using the version with bug fixes - i.e `3.10.5`

**Comment by adamjstewart** [comment]
You should be able to fix this by running `spack clean -m`

**Comment by RemiLacroix-IDRIS** [comment]
> You should be able to fix this by running `spack clean -m`

Worked for me!

**Comment by lmdm-lanl** [comment]
@adamjstewart Sheesh...thank you google search!  I just hit this error with a version of spack from 2020.08.12 (short hash 25a0d89).  Installing a dependency set for intel, then switched to gnu and got this error.  I'm fighting a constant battle with developers trying to get them to be ok with using spack...getting nutty errors like this does not help.

**Comment by adamjstewart** [comment]
Yeah, I have no idea what causes this bug. Not even sure who to ping. Maybe @tgamblin?
