### ISSUE TITLE
Sandbox install() from the Internet

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1655]
We've discussed before why the `install()` method shouldn't be accessing the Internet.  Reasons include:
1. Doesn't work from machines without Internet access.
2. Messes up Spack's tarball caching.
3. Obscures missing dependencies (eg, some packages auto-download from PyPI)
4. Can result in software that's installed in weird ways (eg, auto-downloaded packages are invisible to Spack).

Is there a way Spack can run the install() method in a sandbox that lacks Internet access?

**Comment by tgamblin** [comment]
This is certainly possible.  I _believe_ we could fork the build process with TCP wrappers to block any internet access.  We could also start a container and wall things off that way, but oh wait this is HPC we can't assume containers.

To do the `tcpwrapper` thing, we'd have to rework how fetch is done -- currently the build process does fetching, and you'd want that to happen _before_ it is forked.  That might be a good idea anyway  (#1645).  One day, we'd need to think about how distributed builds (which don't exist yet), would work (i.e., who does the fetching?)

**Comment by citibeth** [comment]
> One day, we'd need to think about how distributed builds (which don't
exist yet), would work (i.e., who does the fetching?)

And interesting question.  If it's not too much of a bottleneck, maybe the
root process can do the fetching, then fire off the distributed builds.  If
it's cached, it will only be done once.


​

**Comment by tgamblin** [comment]
Well, with the locking in #1562, anyone could technically do the fetching and wait for it to complete if someone else is already doing it.  It's clear that you'd like to have things get pre-fetched while builds are happening, and there is an interesting scheduling problem w.r.t. having idle nodes in the DAG do pre-fetches for soon-to-be-executed nodes.

**Comment by citibeth** [comment]
> there is an interesting scheduling problem w.r.t. having idle nodes in
the DAG do pre-fetches for soon-to-be-executed nodes.

Fetching takes almost no CPU time, so I don't see why we should allocate an
idle node to do it.  We'd just as well assign fetching to currently-running
build nodes.

**Comment by tgamblin** [comment]
Which is yet another way to do it.  Building is I/O bound, so I am not sure which would be better.  Also, hard to tell which will take longer: the fetch or the build.   I suspect I'd start out with the root just doing smart prefetching for upcoming builds.

**Comment by citibeth** [comment]
On our system, I believe that Slurm jobs do not have Internet access.
Therefore, the root would need to do all the fetching.

**Comment by alalazo** [comment]
Just looking at old issues. In #7204 I was trying to address this, so to add my two cents, I think the answer to:

> Is there a way Spack can run the install() method in a sandbox that lacks Internet access?

is "Yes, using a docker container started with the `--net none` option".

**Comment by alalazo** [comment]
Closing this one, since:
```console
docker run -it --rm --net=none spack/ubuntu-bionic
```
will do exactly that. One can map a mirror into the image and test a recipe to see if it access the network. Feel free to reopen if the intent was different than just testing packages to know if they access network at install time.
