### ISSUE TITLE
Can Spack produce a `spack` module?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1661]
This self-referential bootstrap would be really nice, so users don't have to manually add spack to their $PATH.

**Comment by citibeth** [comment]
@tgamblin

**Comment by tgamblin** [comment]
It could, although that is the point of `setup-env.sh`... How would you get everything that is in `setup-env.sh` into a module?

**Comment by citibeth** [comment]
Good point.  On a related topic, I'm looking at the text below.  When would
a user want to add Spack to the PATH, and when woudl they want to source
setup-env.sh?  I hate to give two ways to do something with no guidance of
which way to choose.

-- Elizabeth

We'll assume that the
full path to this directory is in the ``SPACK_ROOT`` environment
variable.  Add ``$SPACK_ROOT/bin`` to your path and you're ready to
go:

.. code-block:: sh

   $ export PATH=$SPACK_ROOT/bin:$PATH
   $ spack install libelf

For a richer experience, use Spack's `shell support
<http://software.llnl.gov/spack/basic_usage.html#environment-modules>`_:

.. code-block:: sh

   # For bash users
   $ . $SPACK_ROOT/share/spack/setup-env.sh

   # For tcsh or csh users (note you must set SPACK_ROOT)
   $ setenv SPACK_ROOT /path/to/spack
   $ source $SPACK_ROOT/share/spack/setup-env.csh

This automatically adds Spack to your ``PATH``.

**Comment by tgamblin** [comment]
Generally they want to source the file.  You can run spack without sourcing, but you lose some command line functionality like `spack cd` and `spack load`.

**Comment by citibeth** [comment]
Are there any cases where they can't source the file?

**Comment by citibeth** [comment]
Do you need a working modules system to source the file?

**Comment by tgamblin** [comment]
No.
