### ISSUE TITLE
Testing Integrity of Spack repo

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1735]
@adamjstewart to improve our CI infrastructure further...  Test that the target of each depends_on() declaration can be found in the repo; and that all variants in the depends_on() declarations actually exist.

**Comment by adamjstewart** [comment]
Yeah, I was going to add package-specific testing that would catch stuff like that. @tgamblin Are you opposed to package-specific testing or just the installation part?

**Comment by tgamblin** [comment]
@adamjstewart: Nope.  There is already a `package_sanity` test that you could add this to.  It tests all the builtin packages to make sure they can be imported.  This constructs `Specs` for arguments to `depends_on` but does not check that packages exist (you can make a spec for a nonexistent package, but you can't concretize it).  Look at the `validate_names` method on `Spec` in `spec.py`.  I think you could base your check on that.  The difference would be that your test would check static information (defined in package class metadata) whereas that checks dynamic information (i.e. dependencies that are actually on the Spec).

**Comment by alalazo** [comment]
This won't run under CI, but relates to #5982
