### ISSUE TITLE
Format sources automatically

### ISSUE THREAD

**Issue by eschnett** [spack/spack#1743]
Instead of asking people to re-format their source code, there could be a script that uses e.g. autoopep8 to reformat the source code. I have made good experiences with automatically formatting source code in C++, as it removes much tedium from my workflow, pull request responses, email discussions, etc.

**Comment by alalazo** [comment]
If I could I would vote +10 to this :smile: Actually what we agreed with @tgamblin and @trws back in an old discussion was to use `autopep8` over `yapf` (but I honestly don't know how official that guideline was). 

We could enforce this practice adding a test that basically checks if the files that were changed in a PR are a fixed point under an `autopep8` transformation. This will really require everybody to use the same tool to solve style issues.

**Comment by trws** [comment]
For what it's worth, I use autopep8 to make the process easier, but it doesn't do all of the transformations necessary to pass the current flake8 checks.

**Comment by alalazo** [comment]
We should definitely go with [black](https://pypi.org/project/black/)!

**Comment by trws** [comment]
Having now used it on flux for a while, I wholeheartedly support the use of black for formatting any python project.  No knobs to argue over, and small diffs.

**Comment by tgamblin** [comment]
I've been using black on [LLNL/hatchet](https://github.com/LLNL/hatchet) and I think we'll end up switching to it.  I would like to first have CI in place to actually push blackened commits on top of submissions that do not use Black -- otherwise it'll be an obstacle to contributing.

**Comment by hartzell** [comment]
I'd love to see this.  Perhaps instead of having the CI do it "someone" (sorry, hands tied at the moment) could add `spack black` (now who's shaving a yak?).

**Comment by alalazo** [comment]
@hartzell I can take a stab at it if there's agreement. What stopped us so far is that `black` doesn't grant compatibility with Python 2.6.

**Comment by becker33** [comment]
Closed by #24718
