### ISSUE TITLE
Split Spack into Multiple Repos?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1773]
This thread is to discuss the splitting of Spack into multiple repos: one for core Spack, one for the packages.  Continuation of discussion in #1696

**Comment by citibeth** [comment]
From @davydden:

@ax3l : see https://groups.google.com/forum/?fromgroups#!topic/spack/zGs-0RKz3_U that includes a discussion about splitting of Spack into separate repositories.

**Comment by mwilliammyers** [comment]
Both Homebrew and Linuxbrew made this same split 6ish months ago. I really like the idea.

**Comment by hartzell** [comment]
I'd like to be able to set up a repository for private (corporate) packages without having to maintain them in the `var/spack/repos/builtin/packages/` directory of a fork of Spack that tracks development.

That way I can use the same neurons to manage them that I use for all of the OSS stuff.

I could also use it like I use my [personal homebrew tap](https://github.com/hartzell/homebrew-hartzell), a place to keep half-baked ideas and things like tidy-markdown [that the homebrew team doesn't want to include](https://github.com/Homebrew/legacy-homebrew/issues/50167).

**Comment by tgamblin** [comment]
You can do this already:

```bash
spack repo create myrepo
spack repo add ./myrepo
spack create -r myrepo <URL>
spack edit -r myrepo <package name>
etc.
```

`spack list` shows all packages from all registered repos.

Currently Spack won't fetch a repo (e.g. from github) -- the repo has to be in the local filesystem.

**Comment by tgamblin** [comment]
I like the idea of splitting spack into repos, but I am not sure it's going to happen soon.  If we do this, there should be a set of core packages (just like homebrew has a set of core packages).

How does Homebrew manage dependencies between taps?

**Comment by hartzell** [comment]
> You can do this already:

Excellent!  I'm happy to fetch it myself.

**Comment by tgamblin** [comment]
It'll hopefully be more like taps one day!

**Comment by mwilliammyers** [comment]
> How does Homebrew manage dependencies between taps?

Instead of doing `depends_on llvm` they do `depends_on <owner>/<repo>/llvm`. See: [this](https://github.com/Homebrew/homebrew-dupes/blob/00df450f28f23aa1013564889d11440ab80b36a5/openssh.rb#L24) for an example.

**Comment by citibeth** [comment]
Can anyone articulate the benefits to be obtained by splitting the codebase into multiple git repos?  Because I can think of many drawbacks:

1. It's hard to certify which versions of the core Spack will work with which versions of package Spack.

2. It makes life harder for Spack contributors.  Now there are two GitHub repos to watch, to look at issues on, to push, etc.

3. It makes it harder to install and use Spack (now with two Git clones, plus you have to somehow link them together).

So anyway... what are the benefits?  Having 1000 `package.py` files is not a big problem for a modern Linux system.

**Comment by hartzell** [comment]
@citibeth -- I mentioned my reasons for wanting multiple repos earlier in the post: private things and stuff that the community won't agree to put into the One True Repo.  @tgamblin pointed out that I can already do what I want; I have yet to find a chance to play with it.

The Changelog podcast, [episode #223](https://changelog.com/podcast/223) interviewed Mike McQuaid, lead dev on the Homebrew project.  He covered some of the pluses and minuses of breaking out the repositories from the core and for having multiple repos.  Core vs. recipes seems to be about loose coupling and the multiple repos were about my reasons plus letting other groups work the kinks out of ideas and/or prove them worthy before they made it into the "real" repos.  I'm not doing it justice, it's worth a listen.

**Comment by ax3l** [comment]
> Can anyone articulate the benefits to be obtained by splitting the codebase into multiple git repos?

The main benefit I see is that we could do extensive CI for packages contributed by the community, in a similar way as [conda-forge](https://conda-forge.github.io/) does it.

We are not splitting the "code base" in that sense, but the build recipes / spack packages. I totally agree, that we need a stable package class "API" for that.

But since I think we live in a moving eco-system, we could just add a `schema_version` member to each `Package` class which can be increased with major.minor style notation as soon as changes appear to it between spack releases. That would be similar to how file libraries (hdf5, adios, netcdf) document their "internal" file format version (in our case a "package format version"), which increases independent of individual release versions as soon as it is changed.

Versioning could be as simple as: "major change" = not backwards compatible, "minor change" = backwards compatible.

**Comment by alalazo** [comment]
Closing as stale. I think the points in this discussion have been well received by core developers, but  feel free to reopen if you think there are other facets of splitting the Spack repository to discuss.

**Comment by ian-bertolacci** [comment]
I think this is worth keeping open.
I opened a duplicate issue ( #17062 ) :
> Spack, the package manager, and the collection of spack modules, which are managed using spack, should be developed in separate git repositories.
> 
> This repository is trying to version control 3 different processes:
> 
> The development of a sophisticated package manager
> The curation of a default package collection
> The maintenance of individual packages in the default collection
> While these processes are intertwined in certain aspects, they have distinct development and release cycles.
> The spack package manager has its development and release cycle, and the software inside a package its own individual development release cycle.
> Having all of these processes in one version control system tangles these cycles together in a user-unfriendly way.
> 
> For example:
> Yesterday, I wanted to install hpctoolkit.
> I'm new to spack, so I download the latest release of spack (v.0.14.2 at the time), and went on installing hpctoolkit, only to run into this issue with intel-tbb not having the correct sha.
> This issue is described in #16825 and resolved in 16f104a, but that commit isn't part of the v0.14.2 release.
> 
> Now what?
> 
> Do I just clone the head of the develop branch? (But what if spack is broken at develop->HEAD?)
> Do I keep v0.14.2 and cherry-pick the fixing commit? (But what if that commit depends on other commits?)
> 
> Because the development of spack, the curated default package collection, and the maintenance of the package itself are all tied together in git, we've exchanged a package manager problem for a version control problem (a potentially tricky one as well).
> 
> This could be avoided (and probably eliminated) if the development of spack and the curation of the default package collection (and possibly the maintenance of each package) were each separate git repositories.
> 
> Now, when a user download the latest release version of spack, it would first clone the latest release version of the default package collection repository, which could be much newer than the software.
> Because the two are separate, an update to, or addition of, a package do not require getting the latest commit of the spack software repository, eliminating any concerns I might have as a user regarding the safety and stability of the package management software
> This could also make adoption on managed systems much more viable, as users no longer have to bug system admins to update spack (to a potentially unsafe version) in order to get the most recent package definitions.
> 
> For my example, this would never have been an issue, because there's no longer a way for a package definition to be "behind".
> When spack checks for the package repo for package definitions, it would always have the most recent, most correct version of a package definition, without ever having to update or upgrade the actual spack software.
> 
> Additionally, from an organizational perspective, it seems like separated repositories would be better for you as project developers:
> 
> Issues and pull requests for packages and the software would be in totally separate locations, resulting in less "clutter" and more accurate search results (such as when looking for a previous solution to an issue or making sure I am not submitting a duplicate issue).
> Maintainers of either repo only have to ensure that their stuff is in good state (except maybe when spack has API breaking changes).
> Faster release cycles for both repositories, as a broken package would not impede the release of a new, stable version of spack, and vice-versa.
> It seems like there is already a lot of infrastructure in place to enable this.
> I can already create and maintain my own personal local repositories, why not extend that to allow urls (specifically git-urls), and have the url to the separate default package collection repository be an entry in the default repos.yaml file?
> 
> Thoughts?

It was commented that splitting the packages and spack into different repositories would not have prevented the intel-tbb checksum problems, which is true but also not what I had the issue with:

> > it would NOT solve the intel-tbb problem
> 
> I know that it would not have solved the underlying problem with the checksums, but it would have prevented the issue I had, which was that the package definition was updated and corrected, but using that package definition required updating the entire spack repository, and the spack software itself.
> 
> And I think that what you've said is a good demonstration of why these should be separate repositories.
> The maintenance of a package definition is its own separate software development process from the development and maintenance of the software that manages installations of those packages.
> 
> As software (and the way that software is 'presented', I gess, to the world) changes, so must the package definitions.
> But that has no (or at most very occasional) impact on the development of the package manager.
> The maintenance of a package definition is more tied to the maintenance of the software that package installs, than it is to the package management software.
> 
> Similarly, the package manager has no impact on the software, and hopefully no or only occasional impact on the package definitions.
> 
> The package definition and the package manager are weakly interacting, but by putting them into the same git repository we've strongly tied them together in version control history, which causes the problem I was describing.

**Comment by DiegoMagdaleno** [comment]
I agree with the comment above, it would be more proficient to start splitting Spack, right now you have issues for Spack itself and packages that don't build.

Homebrew worked like Spack before, and they decided to split because of this issue.

**Comment by adamjstewart** [comment]
I would love to be able to split them, especially the issues and PRs, but at the moment Spack isn't very stable. Just a few days ago I merged a PR that updated every Python package in Spack. If you tried to install those new package recipes on any previous version of Spack, they wouldn't work. This still happens all the time. See #18376 and #20610 for recent examples.

P.S. Once Spack _is_ stable, I would love to have separate repos for different languages, such as a `spack-python` repo where I could maintain all the Python packages. It would be helpful if we could also include the base class in this repo.

**Comment by alalazo** [comment]
@DiegoMagdaleno To add on what @adamjstewart is saying, Spack is still changing APIs and underlying "model" of the software specs if you are using `develop`. If there's a need for stability you can use any major release, e.g. v0.16.X, since there we only backport changes that won't require a rebuild / reconfiguration of an already installed stack.

> P.S. Once Spack is stable, I would love to have separate repos for different languages, such as a spack-python repo where I could maintain all the Python packages. It would be helpful if we could also include the base class in this repo.

Did we ever check (as a theoretical exercise) how many cross-references between repos we would have if we split this way? I think there would be many if we do a naive splitting of every `py-*` package into a new repo. To be clear I mean packages in `builtin` that depends on a language-specific repo and vice-versa.

**Comment by adamjstewart** [comment]
@alalazo here is the answer to your question.

Number of non-Python packages that Python packages depend on:
```console
$ sed -nE "s/^ +depends_on..([A-Za-z0-9-]+).*$/\1/p" py-*/package.py | egrep -v '^(py-|python|pil)' | sort | uniq | wc -l
     215
```
Number of Python packages that non-Python packages depend on:
```console
$ shopt -s extglob && sed -nE "s/^ +depends_on..(py-[A-Za-z0-9-]+).*$/\1/p" !(py-*)/package.py | sort | uniq | wc -l
     139
```

**Comment by tldahlgren** [comment]
Re-closing in favor of a newer discussion in #47480
