### ISSUE TITLE
Updated set of patches in spec file not detected

### ISSUE THREAD

**Issue by eschnett** [spack/spack#180]
I added a new patch to a spec file and re-ran `spack install`. The previous build had failed, and the leftovers were still present on disk. Spack did not re-apply the patches, and thus didn't detect the new, additional patch.

Spack should detect changes to the Python class (e.g. via a hash, or via storing the Python script in the install directory), and should re-patch packages if there are changes.

**Comment by mathstuf** [comment]
Well, it actually needs to start from scratch because the old patches may not exist anymore to unapply to the extracted tree.

**Comment by tgamblin** [comment]
Hashing package.py (and associated patches) is coming.

**Comment by alalazo** [comment]
Patches are now treated like MV variants, and thus they enter the hashing mechanism. Should we consider this one closed?
