### ISSUE TITLE
use Version class to store OS version

### ISSUE THREAD

**Issue by davydden** [spack/spack#1814]
subj.

`OperatingSystem` is initialized with a `name` and `version`. I think it make sense to pass `version` into a `Version` object used for packages so that package developers could write conditionals which include OS version like `self.spec.os_version < Version('10.10')` where `os_version` is an instance of `Version` object for OS.

**Comment by davydden** [comment]
btw `spack/operating_systems/__init__.py` is empty.

**Comment by davydden** [comment]
probably should be somewhere in `self.spec.architecture`, still don't know how to get to the version...

**Comment by davydden** [comment]
ok, here it is `spec.architecture.platform_os.version`. This returns `10.12` on macOS Sierra, as it should.

**Comment by adamjstewart** [comment]
We should also probably start using `spec.architecture.<whatever>` to determine whether or not we are on macOS or Linux.

**Comment by davydden** [comment]
yeap, `if 'darwin' in self.spec.architecture` is already used in a few places.

**Comment by davydden** [comment]
I would say we need to aggregate `Version` class in `OperatingSystem` with probably a few extra functions to do comparisons like `self.when(@xyz:)`. In other words, let's use what is already used for versions in packages.

@tgamblin thoughts?

At the moment, `spec.architecture.platform_os.version` is a simple string, which is fine for equality comparison, but nothing else, really.

**Comment by alalazo** [comment]
Closing this issue since the discussion is stale and `Version` has a lot of features that are cut on the way packages (not operating systems) needs to be modeled. Feel free to reopen if you disagree or think the proposal needs further discussion.
