### ISSUE TITLE
Core dump when trying to build glib

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#1819]
When trying to build glib on my laptop (Fedora 24), I'm getting a core dump immediately after it starts make:

```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Current thread 0x00007f87fe9ce700 (most recent call first):
../libtool: line 1766: 13376 Aborted                 (core dumped) dtrace -G -s glib_probes.d -fPIC -DPIC -o .libs/glib_probes.o
```

Any suggestions?

**Comment by JavierCVilla** [comment]
@adamjstewart Did you manage solve this? 

I have realized a similar error, not core dumped, but importError module. What I've seen is that when `python` is installed before `glib`, the latter fails. However, when I install firstly `glib` it works. My hunch is that may be related with the change of the `PYTHONHOME` by the new installed python but I'm still checking it.

Is it your case that you install `python` before `glib`?

**Comment by adamjstewart** [comment]
Honestly, I'm not even sure when I ran into this problem. I never fixed it, but I was able to get past it or avoid it somehow. Maybe I didn't need glib anymore?

**Comment by jgalarowicz** [comment]
@adamjstewart @tgamblin @schulzm I am stuck with problems building glib.  I hope it is alright to piggyback on this issue - it looks like this information fits here?  If I build flex and bison first, then try to build glib, then the glib build fails.  Martin S was able to build glib on cab.llnl.gov if, in openspeedshop/package.py, he commented out the depends_on clauses for flex and bison.  I am not able to do that on my laptop or cab.llnl.gov.   I can build it if I do: spack install glib, without having flex and bison installed.  (I'm not sure which one is the one that triggers the glib build failure.

Here are the details:
[jeg@localhost packages]$ spack install glib
==> Installing glib
==> pcre is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/pcre-8.39-3tuc3fit4kgwe7sju66lz7hjrrcygqfn
==> zlib is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/zlib-1.2.8-jq4jxiutop5swxooi25tkhk7b6l6nngu
==> Installing gettext
==> ncurses is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/ncurses-6.0-cmihjppun2bijb3mpzzbwhpzb77nl3x4
==> Installing libxml2
==> xz is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/xz-5.2.2-2rpz56zrwvpbzp4z5kvijzafckkks6jb
==> zlib is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/zlib-1.2.8-jq4jxiutop5swxooi25tkhk7b6l6nngu
==> pkg-config is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/pkg-config-0.29.1-vssk36ly2g3exjoozghgo6lpuempqzp4
==> Using cached archive: /home/jeg/spack/var/spack/cache/libxml2/libxml2-2.9.4.tar.gz
==> Staging archive: /home/jeg/spack/var/spack/stage/libxml2-2.9.4-fji4ayfbm4vk7nxtbua3ess77zjzgcgh/libxml2-2.9.4.tar.gz
==> Created stage in /home/jeg/spack/var/spack/stage/libxml2-2.9.4-fji4ayfbm4vk7nxtbua3ess77zjzgcgh
==> No patches needed for libxml2
==> Building libxml2 [Package]
==> Executing phase : 'install'
==> Successfully installed libxml2
  Fetch: 0.30s.  Build: 48.41s.  Total: 48.72s.
[+] /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/libxml2-2.9.4-fji4ayfbm4vk7nxtbua3ess77zjzgcgh
==> bzip2 is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/bzip2-1.0.6-wft34zy45lb2e6or45uq7nwdkjjknt2j
==> xz is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/xz-5.2.2-2rpz56zrwvpbzp4z5kvijzafckkks6jb
==> tar is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/tar-1.29-fdltl55mkqcdck2u7vxx76iyl6r3udwb
==> Using cached archive: /home/jeg/spack/var/spack/cache/gettext/gettext-0.19.8.1.tar.xz
==> Staging archive: /home/jeg/spack/var/spack/stage/gettext-0.19.8.1-h6jggoongfux3lpa5t4svejyakh2guze/gettext-0.19.8.1.tar.xz
==> Created stage in /home/jeg/spack/var/spack/stage/gettext-0.19.8.1-h6jggoongfux3lpa5t4svejyakh2guze
==> No patches needed for gettext
==> Building gettext [Package]
==> Executing phase : 'install'
==> Successfully installed gettext
  Fetch: 0.09s.  Build: 2m 35.20s.  Total: 2m 35.29s.
[+] /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/gettext-0.19.8.1-h6jggoongfux3lpa5t4svejyakh2guze
==> automake is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/automake-1.15-6at5ba6sqminp63zdojxy3cek7tyur32
==> libtool is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/libtool-2.4.6-gtrjk5mxuuii47p3wi5j5pkrajh72lto
==> libffi is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/libffi-3.2.1-c3bcrbwq6t4te4ibyyfryyofzms7scfc
==> autoconf is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/autoconf-2.69-on75dtgk5eeuqtyihtbue6mjla7bmlub
==> pkg-config is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/pkg-config-0.29.1-vssk36ly2g3exjoozghgo6lpuempqzp4
==> Using cached archive: /home/jeg/spack/var/spack/cache/glib/glib-2.49.4.tar.xz
==> Staging archive: /home/jeg/spack/var/spack/stage/glib-2.49.4-cy5ldavxap62elifjpbh3ek5yhfvtj6s/glib-2.49.4.tar.xz
==> Created stage in /home/jeg/spack/var/spack/stage/glib-2.49.4-cy5ldavxap62elifjpbh3ek5yhfvtj6s
==> Applied patch no-Werror=format-security.patch
==> Building glib [Package]
==> Executing phase : 'install'
==> Successfully installed glib
  Fetch: 0.48s.  Build: 1m 22.91s.  Total: 1m 23.39s.
[+] /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/glib-2.49.4-cy5ldavxap62elifjpbh3ek5yhfvtj6s
[jeg@localhost packages]$ 
[jeg@localhost packages]$ spack find
==> 38 installed packages.
-- linux-fedora19-x86_64 / gcc@4.8.3 ----------------------------
autoconf@2.69  cbtf@1.6        dyninst@9.2.0     libdwarf@20160507    libtool@2.4.6  mrnet@5.0.1-2   pkg-config@0.29.1  xerces-c@3.1.4
automake@1.15  cbtf@1.8        gettext@0.19.8.1  libelf@0.8.13        libunwind@1.1  ncurses@6.0     python@2.7.13      xz@5.2.2
binutils@2.24  cbtf-krell@1.6  gettext@0.19.8.1  libffi@3.2.1         libxml2@2.9.4  openssl@1.0.2j  readline@6.3       zlib@1.2.8
boost@1.59.0   cbtf-krell@1.8  glib@2.49.4       libmonitor@20130218  libxml2@2.9.4  papi@5.5.0      sqlite@3.8.5
bzip2@1.0.6    cmake@3.7.1     help2man@1.47.4   libsigsegv@2.10      m4@1.4.17      pcre@8.39       tar@1.29


Building openspeedshop:

[jeg@localhost packages]$ spack uninstall -a -f glib
==> The following packages will be uninstalled : 

-- linux-fedora19-x86_64 / gcc@4.8.3 ----------------------------
cy5ldav glib@2.49.4%gcc


==> Do you want to proceed ? [y/n]
y
==> Successfully uninstalled glib@2.49.4%gcc@4.8.3 arch=linux-fedora19-x86_64-cy5ldav
[jeg@localhost packages]$ spack install openspeedshop
==> Installing openspeedshop
==> Installing flex
==> Installing bison
==> m4 is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/m4-1.4.17-knlogmwfctmzmgnyc4cwcjpo54zu2qgg
==> Using cached archive: /home/jeg/spack/var/spack/cache/bison/bison-3.0.4.tar.gz
==> Staging archive: /home/jeg/spack/var/spack/stage/bison-3.0.4-jq2ftjlbodt6737pno23ou22ncc6azqr/bison-3.0.4.tar.gz
==> Created stage in /home/jeg/spack/var/spack/stage/bison-3.0.4-jq2ftjlbodt6737pno23ou22ncc6azqr
==> No patches needed for bison
==> Building bison [Package]
==> Executing phase : 'install'
==> Successfully installed bison
  Fetch: 0.07s.  Build: 28.47s.  Total: 28.54s.
[+] /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/bison-3.0.4-jq2ftjlbodt6737pno23ou22ncc6azqr
==> gettext is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/gettext-0.19.8.1-kpdjvx6vzwdxeasrkgle7j7iid254zcu
==> help2man is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/help2man-1.47.4-7kr7qkr2uefyvifd5dtbehsn2ijv3rlq
==> Using cached archive: /home/jeg/spack/var/spack/cache/flex/flex-2.6.1.tar.gz
==> Staging archive: /home/jeg/spack/var/spack/stage/flex-2.6.1-omr4ka4jn2n3zee2yppnmktmqf64y4x7/flex-2.6.1.tar.gz
==> Created stage in /home/jeg/spack/var/spack/stage/flex-2.6.1-omr4ka4jn2n3zee2yppnmktmqf64y4x7
==> Ran patch() for flex
==> Building flex [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Executing phase : 'install'
==> Successfully installed flex
  Fetch: 0.06s.  Build: 8.97s.  Total: 9.03s.
[+] /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/flex-2.6.1-omr4ka4jn2n3zee2yppnmktmqf64y4x7
==> sqlite is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/sqlite-3.8.5-mg6dakzh7txbzqabzznzdnp7k2xsavmy
==> cmake is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/cmake-3.7.1-geecyzjf2nze6i33ccahy5qdv7vjz5jn
==> Installing qt
==> Installing glib
==> pcre is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/pcre-8.39-3tuc3fit4kgwe7sju66lz7hjrrcygqfn
==> zlib is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/zlib-1.2.8-jq4jxiutop5swxooi25tkhk7b6l6nngu
==> gettext is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/gettext-0.19.8.1-kpdjvx6vzwdxeasrkgle7j7iid254zcu
==> automake is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/automake-1.15-6at5ba6sqminp63zdojxy3cek7tyur32
==> libtool is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/libtool-2.4.6-gtrjk5mxuuii47p3wi5j5pkrajh72lto
==> libffi is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/libffi-3.2.1-c3bcrbwq6t4te4ibyyfryyofzms7scfc
==> autoconf is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/autoconf-2.69-on75dtgk5eeuqtyihtbue6mjla7bmlub
==> pkg-config is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/pkg-config-0.29.1-vssk36ly2g3exjoozghgo6lpuempqzp4
==> Using cached archive: /home/jeg/spack/var/spack/cache/glib/glib-2.49.4.tar.xz
==> Already staged glib-2.49.4-4q2h4ky5xqwrjuycecvfh4ecenz6alm6 in /home/jeg/spack/var/spack/stage/glib-2.49.4-4q2h4ky5xqwrjuycecvfh4ecenz6alm6
==> Already patched glib
==> Building glib [Package]
==> Executing phase : 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'
/home/jeg/spack/var/spack/repos/builtin/packages/glib/package.py:74, in install:
     62       def install(self, spec, prefix):
     63           autoreconf = which("autoreconf")
     64           autoreconf("--install", "--verbose", "--force",
     65                      "-I", "config",
     66                      "-I", os.path.join(spec['pkg-config'].prefix,
     67                                         "share", "aclocal"),
     68                      "-I", os.path.join(spec['automake'].prefix,
     69                                         "share", "aclocal"),
     70                      "-I", os.path.join(spec['libtool'].prefix,
     71                                         "share", "aclocal"),
     72                      )
     73           configure("--prefix=%s" % prefix)
  >> 74           make()
     75           make("install", parallel=False)

See build log for details:
  /tmp/jeg/spack-stage/spack-stage-KFr6Nk/glib-2.49.4/spack-build.out
[jeg@localhost packages]$ tail /tmp/jeg/spack-stage/spack-stage-KFr6Nk/glib-2.49.4/spack-build.out
ImportError: No module named site
make[2]: *** [glib_probes.lo] Error 1
config.status: executing glib/glibconfig.h commands
config.status: glib/glibconfig.h is unchanged
  GEN      glibconfig-stamp
config.status: creating glib/glibconfig.h.win32
make[2]: Leaving directory `/tmp/jeg/spack-stage/spack-stage-KFr6Nk/glib-2.49.4/glib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/jeg/spack-stage/spack-stage-KFr6Nk/glib-2.49.4'
make: *** [all] Error 2
[jeg@localhost packages]$

**Comment by jgalarowicz** [comment]
@adamjstewart Hi Adam - not sure who else to copy on this one.  It seems to show up on the Tri-lab machines for some reason.  I'm getting this on woodchuck at LANL.

Seeing this twice below while trying to build glib:   ImportError: No module named site

wc-fe1:/<9+>repos/builtin/packages [143] $ spack install cbtf-argonavis-gui
==> cmake is already installed in /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/cmake-3.0.2-feol6fw4vkpxr2pn5fhwb4gkpmighafp
==> libffi is already installed in /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/libffi-3.2.1-4s3dshkk5mra3bp2vdxqfasds2sxmzrp
==> pcre is already installed in /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/pcre-8.40-3jnagmpqhzjxihvnvfswurbvqwoohsyg
==> zlib is already installed in /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/zlib-1.2.11-hpdicdxfq5jn2ycttiuiu42hemg444nf
==> gettext is already installed in /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gettext-0.19.8.1-uqkuvuqfoub3vjwqw3h4df6weeg22lou
==> pkg-config is already installed in /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/pkg-config-0.29.2-ovuu7curwnaicby3lgtvruypuaiwagrf
==> Installing glib
==> Using cached archive: /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/var/spack/cache/glib/glib-2.53.1.tar.xz
==> Staging archive: /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/var/spack/stage/glib-2.53.1-4llgpajhea3ttzmd34xpcenx2aisi7ix/glib-2.53.1.tar.xz
==> Created stage in /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack/var/spack/stage/glib-2.53.1-4llgpajhea3ttzmd34xpcenx2aisi7ix
==> Applied patch no-Werror=format-security.patch
==> Building glib [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j32'

2 errors in build log:
     [ ... ]
     557   make[2]: Leaving directory `/turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack_tmp/spack-stage/spack-stage-mYAH8k/glib-2.53.1/m4macros'
     558   Making all in glib
     559   make[2]: Entering directory `/turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack_tmp/spack-stage/spack-stage-mYAH8k/glib-2.53.1/glib'
     560     GEN      glibconfig-stamp
     561     GEN      glib_probes.h
     562     GEN      glib_probes.lo
  >> 563   ImportError: No module named site
     564   make[2]: *** [glib_probes.h] Error 1
     565   make[2]: *** Waiting for unfinished jobs....
  >> 566   ImportError: No module named site
     567   make[2]: *** [glib_probes.lo] Error 1
     568   config.status: executing glib/glibconfig.h commands
     569   config.status: glib/glibconfig.h is unchanged
     570     GEN      glibconfig-stamp
     571   config.status: creating glib/glibconfig.h.win32
     572   make[2]: Leaving directory `/turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack_tmp/spack-stage/spack-stage-mYAH8k/glib-2.53.1/glib'

See build log for details:
  /turquoise/usr/projects/packages/openspeedshop/jegsgi/builds/spack_tmp/spack-stage/spack-stage-mYAH8k/glib-2.53.1/spack-build.out
wc-fe1:/<9+>repos/builtin/packages [144] $

**Comment by nazavode** [comment]
@jgalarowicz your issue is the same as #6965, caused by #7128. A reasonably quick workaround is #6968.

**Comment by alalazo** [comment]
@JavierCVilla @jgalarowicz #7493 should solve the issue with `dtrace` once and for all. 

@adamjstewart I still need to try to reproduce your issue above, will report here asap.

**Comment by adamjstewart** [comment]
I no longer have access to a Fedora machine to test this, but I haven't had any problems building glib in a long time. I'm going to assume this is no longer an issue.

**Comment by sethrj** [comment]
I got the same `ImportError: No module named site` failure trying to install `glib@2.56.4 ^python@2.7.13` on `linux-rhel7-broadwell / gcc@5.4.0` . 

The solution was to change the glib `--disable-tracing` argument (which must've been for an older version) to `--disable-dtrace`. I'm going to submit a PR.
