### ISSUE TITLE
sourceforge downloads failing

### ISSUE THREAD

**Issue by sarich** [spack/spack#1854]
I keep running into issues with spack downloading packages from sourceforge, the default mirror seems to be down a lot and the installation stops.

I know I can work around this by manually downloading each failed package directly choosing a different sourceforge mirror and putting it into a specific directory in the spack tree, and/or by setting up a site-wide mirror location, but I would hope that the manual fetch could be automated. At the very least, (copy-and-pastable?) instructions on how to do this could be printed out when a download fails.

**Comment by davydden** [comment]
I think you best bet when you hit this is google for a mirror and edit `package.py`.

**Comment by sarich** [comment]
Yes, that's another work-around, but not an obvious solution for an end-user

**Comment by citibeth** [comment]
I suggested a while back that `url_for_version()` returns a list of URLs, not just a single one.  Frequently, backup tarballs are available at various Fedora srpm repositories, and things may be fetched from Fedora if the main site is down.  But adding backup Fedora URLs in a zillion packages is not really a solution...

Maybe we need a smarter download mechanism.  If it cannot find a tarball at the default location, it can start snooping around elsewhere.  This can account for many things:
  *) Choose different SourceForge mirrors if one is down...
  *) Snoop around Fedora FTP sites if you cannot find the tarball in the main place
  *) Maybe some Spacker will maintain a publicly accessible Spack mirror where we can just go for tarballs?

**Comment by alalazo** [comment]
At present we have tarball and build caches + mirrors. I'll close the ticket, but feel free to reopen if you think it's still an issue.
