### ISSUE TITLE
Issues with matching exact version numbers vs. version ranges

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1924]
See discussion on #1920 

From @tgamblin 

> Yeah, sorry for that. That is a concretization issue. The concretizer thinks that if a package has a single version that is not a range or a list, that it's concrete, so if you say 2.7 on the command line it never gets matched against known versions. But 2.7, if compared to other versions, will be satisfied by 2.7.1, 2.7.8.1, etc.
> 
> Probably a version needs to know whether it is exact, so the concretizer doesn't have to use a kludgy test like it does. This would also be useful for users -- I have thought about allowing "exact" version literals like 2.7. (period at the end) to indicate the version is exactly v2.7 and shouldn't match anything else.

**Comment by davydden** [comment]
maybe one does not even need the logic with dots. I would do it the following way:

If the version length is smaller than other versions of the package, then it is **not exact**, otherwise it is. For example, if package has `1.2.3, 1.2.4, 1.2.5`, then `@1` and `@1.2` are not exact, whereas `@1.2.5` is.

**Comment by tgamblin** [comment]
@davydden: what if the package has `1.2` and `1.2.1`?  What's `1.2`?

**Comment by davydden** [comment]
>  what if the package has 1.2 and 1.2.1? What's 1.2?

correct, it won't work for this case. But if the package developers indeed distributed `x.y` and `x.y.z` **simultaneously**, I would wrap their `x.y` into `x.y.0`.  My understanding is that ideally version numbers should be consistent during development and I don't see any good reason for such mixed numbering  from the developer's perspective. I might be wrong, of course.

**Comment by davydden** [comment]
> what if the package has 1.2 and 1.2.1? What's 1.2?

if we go with dots, we need to do the same for ranges to distinguish between `:1.2` and `:1.2.`.

**Comment by davydden** [comment]
maybe it's easier to enforce consistent version numbering within a package than to workaround those corner cases.

**Comment by tgamblin** [comment]
It's not a hard corner case.

**Comment by alalazo** [comment]
> I don't see any good reason for such mixed numbering from the developer's perspective.

Except that the quote from blade runner : "I've seen things that you people wouldn't believe" applies almost daily in HPC. For instance : you packaged an application that required 9k lines of patches per developer suggestion :smile:

**Comment by tgamblin** [comment]
Really, the intent with Spack is NOT to require any particular versioning scheme from packages.  If the package developer releases a crazy version, Spack needs to handle it because in all likelihood some scientist wants that.  I was going to go on but @alalazo already said it better 😄

**Comment by davydden** [comment]
extra points for the quote from blade runner :smile: :+1:

**Comment by citibeth** [comment]
> maybe one does not even need the logic with dots. I would do it the following way:

I lean toward @davydden's suggestion.  How about thinking about it in a different way... in concretization, Spack reads all the KNOWN version numbers of a package.  These come from the `package.py` file, the command line, `packages.yaml`, and anywhere else there might be version info.   Spack then extends all version numbers to be as long as the longest version it observed, in one of two ways.

[For this example, suppose we've seen 1.2, 1.2.1 and 1.3.2.4]

1. If it's a pattern (constraint), it puts a * (in a wildcard sense) in every missing place.  So... if the user asked for 1.2, that becomes 1.2.*.*

2. If it's a version to matched against, Spack extends it with .0.  So.. 1.2.1 --> 1.2.1.0

Now, the user asks for '@1.2' and that turns into '@1.2.*.*'.  Which matches '1.2.1.0', and '1.2.0.0'.  The most recent version is '1.2.1.0', aka '1.2.1'.

**Comment by adamjstewart** [comment]
> But if the package developers indeed distributed `x.y` and `x.y.z` simultaneously, I would wrap their `x.y` into `x.y.0`.

@davydden Do you mean renaming the version in the `package.py`? I would not do this, as it would break fetching unless you want to add a `url_for_version` that specifies the url for `x.y.0` versions. If you mean renaming it only when trying to resolve versions, that might work. I don't think I've ever seen both `1.2` and `1.2.0` versions for the same package.

Let's try not to get bogged down too much by corner cases here. 90% of the need for this functionality is for specifying Python versions, and Python has a consistent `x.y.z` versioning scheme. Even if we had to resort to something as primitive as `@1.2` matching both `1.2` and `1.2.3`, I don't think it will affect very many packages.

But if we really want to handle all cases, I like @citibeth's latest suggestion if that's not too difficult to implement!

**Comment by davydden** [comment]
> Do you mean renaming the version in the package.py? I would not do this, as it would break fetching unless you want to add a url_for_version that specifies the url for x.y.0 versions.

yes, i meant to rename in `package.py`. It is correct that this would require a separate `url_for_version` for such packages.

**Comment by citibeth** [comment]
I think the algorithm I suggested would achieve the same results without us
having to rename versions.

**Comment by tgamblin** [comment]
Reported as early as #921

**Comment by adamjstewart** [comment]
#1035 also has some discussion on this issue.

**Comment by alalazo** [comment]
Closing, since the most up-to-date discussion on versions is #26557
