### ISSUE TITLE
Need documentation on adding unit tests

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#1935]
Could someone who has added unit tests before add documentation to the Developer Guide on how to write unit tests and run them? I think people would be a lot more likely to write them if we knew how.

**Comment by citibeth** [comment]
Regression tests too... (if they're different from unit tests).

**Comment by alalazo** [comment]
@adamjstewart This still needs documentation, but I think 5-6 years is enough to see if the issue can get any traction :laughing: Closing, but feel free to reopen.
