### ISSUE TITLE
Improve Spack issue tagging for first-time contributors.

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#1942]
We should register with sites like [up for grabs](http://up-for-grabs.net) and start tagging issues with `up-for-grabs` tags and notes about difficulty.

[Here's an example](https://github.com/devtools-html/debugger.html/issues/349) of how another project made things easy for people to jump in and contribute.

**Comment by alalazo** [comment]
@tgamblin I added a while ago the two tags `help wanted` and `good first issue` which should integrate with github. I assume we could register on up for grabs to close this (as many issues are already tagged `up-for-grabs`)?

**Comment by alalazo** [comment]
Closing as stale.
