### ISSUE TITLE
User-Based Integration Tests

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1951]
@adamjstewart 

It would be nice if we had integration tests... that is, if Spack actually tries to build THE THINGS WE NEED.  Problem is, the set of things needed by each user is different, so it's hard to know what centralized integration tests to set up.

Instead, how about user-based integration tests?  Each user (who wants to run integration tests) would provide a list of things that Spack should build, and a list of things Spack should try doing once it's build them.  These tests would be (automatically) run periodically, with results automatically posted back to GitHub when things fail.  The integration tester framework should be easy to set up, of course.

**Comment by alalazo** [comment]
I have to clean up a few details before having a structured proposal to make, but for installation I was thinking of annotating information on the builds to perform in comments at the end of the `package.py` file.

If we add a `package` sub-command to `spack test` then testing a package could be as simple as : 
```
spack test package hdf5  # will run all the tests found at the end of hdf5/package.py that could apply on this architecture
spack test package hdf5+mpi  # same as before but only if spec.satisfies('+mpi')
```

**Comment by citibeth** [comment]
1. Why does this information have to be in comments?  Why can't we put it in the "straight" part of `packages.yaml`?  These kinds of things go in comments in other systems because the syntax of the language has already been set in stone.  But we control `packages.yaml`, so there should be a way to just adding it in.

2. The command to test a single package is good.  But there also needs to be a command to test everything.

3. Once testing is running smoothly, we can think of how to report errors in a more automated way.

**Comment by alalazo** [comment]
> Why does this information have to be in comments? Why can't we put it in the "straight" part of packages.yaml? These kinds of things go in comments in other systems because the syntax of the language has already been set in stone. But we control packages.yaml, so there should be a way to just adding it in.

Fair point about not adding that in comments : I'll think about better alternatives. I wouldn't though add a CENTRALIZED way of adding tests in `packages.yaml`, rather a distributed one within every package folder in a repo.

> The command to test a single package is good. But there also needs to be a command to test everything.

Not on a regular base for packages. Having a single package is enough to script a few lines so that a CI framework could test just what changed.

We may fire a test of all packages before releases, but I wouldn't make it a possible behavior with just one cli command (installing a package is much more expensive than running a unit test)

> Once testing is running smoothly, we can think of how to report errors in a more automated way.

Yes, that should be the natural next step.

**Comment by citibeth** [comment]
> The command to test a single package is good. But there also needs to be a
> command to test everything.
>
> Not on a regular base for packages. Having a single package is enough to
> script a few lines so that a CI framework could test just what changed.
>

This needs to eventually be super-easy for users to set up, or they (we)
won't do it.  Something like:
  1. Add stuff you need to see built to `packages.yaml`
  2. Set up such-and-such certificate or what-not so it can auto-post
results back to Spack.
  3. Modify your crontab.


> We may fire a test of all packages before releases, but I wouldn't make it
> a possible behavior with just one cli command (installing a package is much
> more expensive than running a unit test)
>
Remember that USERS will be running these tests on their own machines and
reporting back to Spack.  If I have 50 packages I want to see built in a
particular configuration, I'll have no problem with setting up an automatic
process that tries to build them (on my machine) 1x/week from the latest of
the `develop` branch.

**Comment by alalazo** [comment]
Closing as #2917 (which is already in an advanced state of development) covers the same ground, but with some implementation differences.
