### ISSUE TITLE
setup_environment() is not mentioned in Packaging Guide

### ISSUE THREAD

**Issue by davydden** [spack/spack#2016]
subj. http://spack.readthedocs.io/en/latest/packaging_guide.html

**Comment by pramodk** [comment]
@davydden @alalazo : when `setup_environment` is called? after `install` or before `install` method?  I updated `tau` package with following :  

```
      def setup_environment(self, spack_env, run_env):
          pattern = join_path(self.prefix.lib, 'Makefile.*')
          files = glob.glob(pattern)
          run_env.set('TAU_MAKEFILE', files[0])
```
and my expectation was that this will be called *after* `install` method.  But currently I see that this is being called before `install`. Is this expected?

**Comment by davydden** [comment]
@pramodk 
what exactly do you need? You want some things to be setup when you do `module load` or when you build a dependent package? Before or after `install` of what?

If I am not mistake, `setup_environment()` will be also called in `module load`. Otherwise for dependent packages IIRC you need to modify `setup_dependent_environment(self, spack_env, run_env, dependent_spec):`, which IS documented http://spack.readthedocs.io/en/latest/packaging_guide.html#setup-dependent-environment .

**Comment by pramodk** [comment]
> what exactly do you need?

When we *load* `tau` package, we need to always set `TAU_MAKEFILE ` environment variable to some file. The location of that file (inside `prefix`) is dependent on `arch`. Hence I used `glob` to find the file (here is the PR #2210). 

Simple example: 

```bash

class MyPkg(Package):

    def install(self, spec, prefix):
          #some stuff

    def setup_environment(self, spack_env, run_env):
          #some stuff
           print "Setup...."
```

And currently I see: 

```bash
$ spack install  MyPkg %clang
==> Installing MyPkg
Setup...
==> Already downloaded
==> Building MyPkg [Package]
==> Executing phase : 'install'
Setup...
Setup...

# spack load doesn't call setup_environment

$ spack load MyPkg %clang


# module refresh does call setup_environemtn

$ spack module refresh -y MyPkg %clang
==> Regenerating tcl module files
Setup...
```

Going back to original requirement: I wanted to setup some `env` variable for the user. (after `install()` method, by looking at the contents of `prefix`). I was assuming that the `setup_environemnt()` is called after `install` phase. With this misunderstanding I introduced bug in #2210. I will open PR to fix it.

**Comment by alalazo** [comment]
@pramodk in the current implementation `setup_environment` is called both before and after install (when writing module files). This may be refactored in the future as just the call before install would suffice. To have an high-level idea of what it does, you may take a look at `build_environment.py`, function `setup_package`.

Basically, before package `A` is built its environment is constructed more or less in the following way:
```python
for xspec in A.spec.traverse(order='post', root=False, deptype='build'):
    xpkg = xspec.package
    # Every dependency has the opportunity to attach
    # attribute to A.module, for instance to provide
    # Executables, see `autoconf`
    xpkg.setup_dependent_package(A.module, A)
    # Every dependency can push modifications to either 
    # the build environment or the run environment (what
    # gets written in the module file), see `python`
    xpkg.setup_dependent_environment(build_env, run_env, A)
# Finally package A has the same opportunity for tis own build
# see `R`
A.setup_environment(build_env, run_env)
```

**Comment by davydden** [comment]
@pramodk : 

> spack load doesn't call setup_environment

for me `spack load` calls `setup_environement()` (with `environment-modules`):
```
$ echo $DEAL_II_DIR

$ spack load dealii
$ echo $DEAL_II_DIR
/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/dealii-develop-uqptfgknda4yudz6hm6e55yyihsvdl57
```

**Comment by alalazo** [comment]
> for me spack load calls setup_environement() (with environment-modules):

Not true. `setup_environment` is used to generate a module files at install time (or if you refresh modules).

`spack load` translates a spec to a module file name and load that module file **if** you have a proper tool available (LMod or Environment Modules).

**Comment by davydden** [comment]
> Not true.

i see, thanks for clarification.
