### ISSUE TITLE
spack compiler remove doesn't work

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2042]
```
$ spack compilers
==> Available compilers
-- gcc ----------------------------------------------------------
gcc@6.1.1
$ spack compiler remove gcc@6.1.1
==> Error: No compilers match spec gcc@6.1.1
```

**Comment by citibeth** [comment]
Why are we supporting this feature?  Why not just tell people to edit `compilers.yaml`?

**Comment by adamjstewart** [comment]
@citibeth Are you suggesting we get rid of `spack compiler find` too?

**Comment by citibeth** [comment]
I think `spack compiler find` is more useful; without it, people don't really know what to put in `compilers.yaml`.  But once one compiler has been found, it's not so hard to replicate the pattern.  So... I think `spack compilers find` is worth keeping, but is not top priority in terms of essential Spack commands.

`spack compiler remove` is less useful: it's pretty obvious to most users how to REMOVE a compiler, as long as they know they have to edit `compilers.yaml` to do it.

**Comment by tgamblin** [comment]
I'm not opposed to supporting this feature.  I don't see why it needs to be on the chopping block.

**Comment by adamjstewart** [comment]
Update: I think I know why it isn't working. Back when I first added this compiler, Spack put it in `~/.spack/compilers.yaml`. When I delete that file by hand, Spack re-adds the compiler to `~/.spack/linux/compilers.yaml`. Then, when I try `spack compiler remove gcc`, it works. Do all configuration files go in `~/.spack/linux` now, or are they expected to work in `~/.spack` too?

**Comment by tgamblin** [comment]
yeah this is an unintended consequence of arch-specific configurations -- Spack config commands get the highest-precedence scope by default and try to remove from there.

I think the config scopes are necessary.  In fact, the config scopes solve #1690 to some extent.  I haven't closed it b/c it should still actually check whether there are _any_ compilers for the current architecture, as the `/platform` directory might not be populated.

Should commands like `spack compiler remove` find the first scope where the thing referred to appears and try to remove it from there?

**Comment by adamjstewart** [comment]
> Should commands like spack compiler remove find the first scope where the thing referred to appears and try to remove it from there?

That sounds reasonable to me. How many people actually use _multiple_ scopes? 

I guess the confusing thing is if `spack compiler list` lists a compiler and `spack compiler remove` says that it doesn't exist.

**Comment by alalazo** [comment]
Closing:
```
$ spack compilers
==> Available compilers
-- clang ubuntu18.04-x86_64 -------------------------------------
clang@9.0.1  clang@8.0.0  clang@7.0.0  clang@6.0.1  clang@5.0.1  clang@4.0.1  clang@3.9.1

-- gcc ubuntu18.04-x86_64 ---------------------------------------
gcc@9.0.1  gcc@8.3.0  gcc@7.4.0  gcc@6.5.0  gcc@5.5.0  gcc@4.8

$ spack compiler remove gcc@4.8
==> Removed compiler gcc@4.8

$ spack compilers
==> Available compilers
-- clang ubuntu18.04-x86_64 -------------------------------------
clang@9.0.1  clang@8.0.0  clang@7.0.0  clang@6.0.1  clang@5.0.1  clang@4.0.1  clang@3.9.1

-- gcc ubuntu18.04-x86_64 ---------------------------------------
gcc@9.0.1  gcc@8.3.0  gcc@7.4.0  gcc@6.5.0  gcc@5.5.0
```
