### ISSUE TITLE
A proposal on treating git refs as versions

### ISSUE THREAD

**Issue by becker33** [spack/spack#20536]
## 1. Motivation

Many users pin packages to particular git commits, tags, or branches, rather than released versions. This is particularly relevant to developers, who often track several packages through their release processes simultaneously, with versions constraints that propagate through their entire DAG. Therefore, Spack should allow users to seamlessly treat git refs, and other Version Control System (VCS) references, as versions in a Spack spec, while maintaining appropriate comparisons between those versions and the versions, version ranges, and version lists used as control-flow in the Spack package.

## 2. Approach

Fetching git versions is a fundamentally easy problem -- the only difficulty there is determining to use git for packages that have both git and url download options. The difficulty is how to build from versions that are not directly comparable to the (usually semver) version constraints in the build recipe.

### 2.A Comparing Versions

For version comparisons, we need to compare a git commit to a semver version. Assuming the release versions are tagged in git, it is feasible to compare them to a git version. To compare semver S to git version G, first we compute the merge-base of S (as tagged in git) with the default branch, MS, and the merge-base of G with the default branch, MG. If MG is an ancestor of MS, G is "less than" S, and vice-versa. If MG and MS are equal, then G is "less than" S if it is an ancestor of S, and vice-versa. If MG = MS and G and S are not directly comparable, then G and S are not comparable versions, and neither is "less than" the other, but they are not equal.

If the release versions are not tagged in git, there is no automatic way to compare them to git versions. However, the package file may contain a translation from release versions to git commits, which would allow the prior algorithm to proceed for such a package.

### 2.B When to resolve comparisons

There are two primary options for when to resolve comparisons between git versions and release versions.

##### 2.B.i Compare as necessary

The easiest way to check comparisons between git versions and release versions would be to compute the comparison as necessary. This involves the least complex caching (although we may cache individual comparisons with this method).

##### 2.B.ii Compare once, use range

Initial planning for this effort focused on the possibility of computing a "range" for each git version of the closest release
versions that could be ascertained to be "less than" and "greater than" the git commit. While this method initially seemed to create fewer comparisons (and more obvious caching) than the method to compare as necessary, caching individual comparisons in the ad-hoc method should result in similar performance with less complexity of design.

### 2.C When to clone

While git versioning will be most useful to developers, it is also of use to large-scale coordination projects like the XSDK. For that reason, we will avoid relying on developer packages (specified by the `develop` key in a Spack environment) for version comparisons.

However, cloning for each comparison would be prohibitive from a performance perspective, in addition to being problematic on systems without internet access.

To resolve this, we propose to modify the structure of Spack mirrors to better support VCS softare. For each type
of VCS understood by Spack (currently `git`, `hg`, and `svn`) we propose a top-level directory under the Spack mirror which contains a single instance of the VCS repo per-package. The builtin Spack mirror (the "source cache") will attempt to pull this repo any time it encounters a git ref it cannot find, as well as any time it checks out a branch. User-made mirrors will be static, and will throw errors on git refs they cannot find, as will the builtin mirror when fetching does not resolve the issue. Spack will attempt to pull from the internet when such an error is raised, but fail gracefully if it cannot be reached.

## 3. Project Breakdown

We propose 3 separate pull requests to Spack

### 3.A Mirror VCS software separately

This PR will establish the mirror subdirectories for each VCS system, and manage when we pull/fail for unfound git refs for each type of mirror. It will leave for future work the details for non-git VCS systems, while reserving their subdirectory names for that future use.

### 3.B Automatic interpolation of git versions by FetchStrategy

This PR will allow Spack to (a) determine whether an unknown version is a git reference or an unknown release version, and (b) fetch a package based on a git reference when it is not known to the package file, even when the type of the reference (branch, tag, commit) is unknown. Other VCS systems will be left for future work.

### 3.C Automatic comparison of git versions to release versions

Implement the algorithm described in section 2.A, along with appropriate caching of results for performance.

##### 3.D.v Automatic comparison of HG versions to release versions

This will require independent research into the appropriate comparison algorithm

##### 3.D.vi Automatic comparison of SVN versions to release versions

This will require independent research into the appropriate comparison algorithm

**Comment by becker33** [comment]
@tgamblin This is the proposal for the work I want to lock myself in a room and get a jump on next week when there won't be any meetings

 @rblake-llnl I think you will find this interesting.

**Comment by adamjstewart** [comment]
Should this be a discussion instead of an issue?

**Comment by becker33** [comment]
@adamjstewart I'm not sure. Do we want to push all feature requests to discussions? If so then definitely yes.

**Comment by tgamblin** [comment]
Should we have a separate repo for proposals like this?  e.g., like k8s KEPs: https://github.com/kubernetes/enhancements.

It might be useful to add this written step to the design process for larger features, not just for discussions but to give people a chance to see the full idea. I think Spack's getting large enough that the writing will help -- there are a lot of interconnected issues for many of the features.

**Comment by adamjstewart** [comment]
Personally I think issues are fine for minor feature requests, but big changes that require discussion and planning might be better as discussions. I think a formal system for SEPs (Spack Enhancement Proposals) sounds like overkill.

Anyway, sorry for derailing this conversation. Feel free to hide these comments as off-topic once we make a decision.

**Comment by becker33** [comment]
We could call them "Spack Upgrades" just to confuse anyone who has ever used another package manager...

**Comment by becker33** [comment]
Converting this to a discussion; I agree large feature requests should be discussions.
