### ISSUE TITLE
allowing user to manuall run large test suite after spack install

### ISSUE THREAD

**Issue by BarrySmith** [spack/spack#2060]
With a PETSc -prefix install after the install is complete one can run from the PETSc build directory the entire test suite with 
PETSC_DIR=/prefix_install_location make alltests 
this uses mpiexec and can take a while to run. Note you do NOT want this run automatically with 
spack install petsc

After a 
spack install petsc
 I would like to be able to initiate the same test suite. But I don't even know where the build directory is. So do you plan to provide something like
spack alltests(use whatever name you want here) petsc 
where I would provide a function in the petsc/package.py that would be called to run the big test suite? This would be useful. All I would need available in the function I write is the petsc prefix directory and the petsc build directory.

**Comment by pramodk** [comment]
@BarrySmith : from my understanding, if we keep `build` directory using `--keep-stage`:
```bash
spack install --keep-stage my_fav_spec
```

We can do following to enter the build directory:
```bash
spack cd my_fav_spec
```
there is also `spack location ` command which we can use as:
```bash
cd $(spack location --build-dir my_fav_spec)
```

Similarly `location` command have ``--install-dir` option:
```bash
 cd $(spack location --install-dir my_fav_spec)
```
More information in [Packaging Guide](http://spack.readthedocs.io/en/latest/packaging_guide.html#interactive-shell-support).

About running tests: I have starting playing with BG-Q (other cross compiling) environment with spack and see that the some packages (like `hdf5`) try to run tests within `install` method itself and this fails. (and then there are common issues about mpi launchers mpirun, srun etc...)

**Comment by tgamblin** [comment]
@BarrySmith:
> With a PETSc -prefix install after the install is complete one can run **from the PETSc build directory** the entire test suite

Do you know if there are a lot of projects where both the build *and* install directories are required to run the test suite?  We have talked about post-build tests as well as post-install tests in #169 and #1169, but I don't think we actually talked about things that would require *both* directories.

@pramodk gives a good description of how you can do this right now, but if we want to support testing well, it looks like we actually need *three* test stages:

1. post-build tests: can be run after build if the stage is still around
1. post-install tests: can be run after install at any time while the package is installed
1. build/install tests can be run after install if the stage is still around

The problem with 1 & 3 is that Spack automatically removes the build stage by default after a successful install.  Spack also typically tries to build in a temporary filesystem because the temp filesystem is usually local or at least faster than home filesystem NFS mounts... but it might get purged if we keep it around after an install.

So...
1. How long do you think the build directory should be kept around?
1. Should packages be able to indicate that their build directories should be kept around longer for tests like this?

**Comment by BarrySmith** [comment]
Do you know if there are a lot of projects where both the build and install directories are required to run the test suite?

We may be using the term "build" directory with different meanings here.

With PETSc we don't "install" all the examples at the prefix location so we need (some how) access to the examples to run the tests. We don't neccessarily need the "build" directory but basically we need a copy of the "source" directory so our test scripts can move through the directories to compile and run the examples.  In your list of three items above I think PETSc can be thought of as being in the 2. post-install tests: can be run after install at any time, BUT I need a directory with the source code to run the tests. So 3. may not be needed.

We could have a script that "installs" all the examples in the install directory and run the tests from there but I don't think that is the best model.

**Comment by davydden** [comment]
> With PETSc we don't "install" all the examples at the prefix location so we need (some how) access to the examples to run the tests.

what if we install them manually into `prefix/share/petsc/examples/`?

**Comment by davydden** [comment]
Just to give an example of how `deal.II` works in terms of testing:

> (1.) post-build tests: can be run after build if the stage is still around

several quick tests can be run with `make test` prior of after installation within the (temporary) `build` folder.

> (2.) post-install tests: can be run after install at any time while the package is installed

the whole test suite (about 8000+ test) can be use to test the already installed library. So we won't need the build folder for this.

**Comment by BarrySmith** [comment]
"what if we install them manually into prefix/share/petsc/examples/? "

certainly can do this but

1)  they are not small (this may be ok, because now users have access to them)

2) do you really want our tests actually being compiled and run in that directory?  Or does our test suite need to copy over the examples directory from there to a "example build" directory to compile and run them? If so, it would be better if spack decided on the location of the "example build" directory and did the copy itself.

**Comment by davydden** [comment]
> 1) they are not small (this may be ok, because now users have access to them)

how big? I guess as long as they are on the order of 100Mb, should be fine.

> 2) do you really want our tests actually being compiled and run in that directory?

certainly not. I think compilation and run should be in a temporary folder, similar to the one used to build a package. 

>  If so, it would be better if spack decided on the location of the "example build" directory and did the copy itself.

I think this can all be done by Spack indeed.

Essentially, i would envision a post-isntall testing stage being similar to installation in that there is 

1. a temporary folder to work in
2. possibly dependencies ( like `cmake`) in addition to the package being tested
3. resources (test scripts in case of petsc or even the tests themself; or checkout of the github repo for deal.ii). 

The rest should be done by Spack.

**Comment by davydden** [comment]
I think @citibeth already does similar things in a _package_ which is only used to test another installed package. 

But if we can keep the `test` method within the corresponding package like in `homebrew` (e.g. [petsc](https://github.com/Homebrew/homebrew-science/blob/master/petsc.rb#L163-L242)), IMHO it would be more appropriate at least for some packages like `petsc` and `deal.ii`.

**Comment by citibeth** [comment]
> I think @citibeth already does similar things in a package which is only used to test another installed package. 

In that case, the "test" (actually example) package is a separate upstream project from the main package.  In general, the rule of (one tarball) = (one Spack package) applies.

**Comment by davydden** [comment]
>  the rule of (one tarball) = (one Spack package) applies.

agree

**Comment by BarrySmith** [comment]
"Essentially, i would envision a post-isntall testing stage being similar to installation in that there is

a temporary folder to work in
possibly dependencies ( like cmake) in addition to the package being tested
resources (test scripts in case of petsc or even the tests themself; or checkout of the github repo for deal.ii)."

   Yes, this sounds fine. So we'll add support for installing the examples, which is what we should do anyways.

**Comment by tgamblin** [comment]
> Yes, this sounds fine. So we'll add support for installing the examples, which is what we should do anyways.

Agree on all counts.  A post-install test command would provide the run directory; we just need a place for the test executables to live after `install()` completes.  `prefix` is the right place.

I don't really see a need for a size limit on the tests.  I think they can be an optional install (e.g., `petsc+tests`), and if the package only supports tests when the variant is enabled, the post-install test should complain.  Then people who don't need the tests can just disable the variant.

**Comment by tgamblin** [comment]
@BarrySmith: FYI, if you start a line with `>`, GitHub will mark it as quoted in the discussion.

**Comment by tgamblin** [comment]
I think there is a button in the WYSIWYG editor for that too...

**Comment by BarrySmith** [comment]
>we just need a place for the test executables to live after install() completes.

Hum, are you planning to compile all the test executables during "install" and then "run" them during the tests? This won't work with PETSc and static libraries. All the executables being built at the same time (say 1000) will fill the entire file system. I had been assuming that the test phase would both build the executables and execute them.

**Comment by davydden** [comment]
> we just need a place for the test executables to live after install() completes.

I agree with @BarrySmith that executables should be built during the test stage. In case of `deal.II` there is no choice as `Cmake/Ctest` is employed, which is responsible to compiling, running and testing against blessed output files.

**Comment by davydden** [comment]
btw, a relevant issue is https://github.com/LLNL/spack/issues/1279, namely we should have `test` dependency type. For example for unit tests only a package may require `numdiff` to have a better control over comparison of floating point numbers.

**Comment by tgamblin** [comment]
> Hum, are you planning to compile all the test executables during "install" and then "run" them during the tests?

@BarrySmith: I guess I missed this, but it shouldn't be a problem.  We can make the tests run in a Spack build environment so that you can build just as you would in `install()`.  If all the stuff needed to build tests is installed with the package, the source shouldn't need to be fetched again.

Are there ever going to be cases where you want the original source tarball in the test environment?

**Comment by davydden** [comment]
just saw another peculiar example: `lz4` requires `valgrind` to test in the build folder by `make('test')`. So it looks like test dependency types sometimes should also be available during `install()` phase of a package. But of course they should not influence hashes.

**Comment by tgamblin** [comment]
@davydden that's a helpful use case

**Comment by davydden** [comment]
test dependency type is merged already (thanks to @scheibelp https://github.com/LLNL/spack/pull/5132), so we are one step closer here. What is missing is a mechanism to setup and run tests post-installation. As @BarrySmith says PETSc needs

> We don't neccessarily need the "build" directory but basically we need a copy of the "source" directory so our test scripts can move through the directories to compile and run the examples.

so one should have: 

- the same environment as during the build (all dependencies, extract same sources, etc)
- know the prefix of the already installed library
- have some `post_install_tests()` method in Package class to setup and run tests (i.e. `PETSC_DIR=/prefix_install_location make alltests` for PETSc or `cmake -DDEAL_II_DIR=$(spack location -i dealii) /tests` for dealii).

In the HPC context, presumably, all that shall be done when a user reserves time/nodes in the interactive mode to test some packages.
