### ISSUE TITLE
understanding spack messages about invalid spec

### ISSUE THREAD

**Issue by BarrySmith** [spack/spack#2068]
I've been banging my head against the wall for hours over this with no progress so need some help. I cannot decipher 

$ ./spack install xsdk@0.1.0
==> Error: Invalid spec: 'trilinos@12.8.1%gcc@6.2.0+boost~debug+hdf5+hypre+metis+mumps~python+shared+suite-sparse+superlu-dist~xsdkflags arch=darwin-sierra-x86_64^boost^cmake@2.8.12%gcc@6.2.0~doc+ncurses+openssl~ownlibs~qt arch=darwin-sierra-x86_64^curl@7.50.3%gcc@6.2.0 arch=darwin-sierra-x86_64^glm@0.9.7.1%gcc@6.2.0 arch=darwin-sierra-x86_64^hdf5@1.10.0-patch1%gcc@6.2.0+cxx~debug+fortran+mpi+shared~szip~threadsafe arch=darwin-sierra-x86_64^hypre@2.11.1%gcc@6.2.0~internal-superlu~shared arch=darwin-sierra-x86_64^libsigsegv^m4@1.4.17%gcc@6.2.0+sigsegv arch=darwin-sierra-x86_64^matio@1.5.2%gcc@6.2.0 arch=darwin-sierra-x86_64^metis@5.1.0%gcc@6.2.0~debug~gdb~idx64~real64+shared arch=darwin-sierra-x86_64^mpich@3.2%gcc@6.2.0+hydra+pmi+romio~verbs arch=darwin-sierra-x86_64^mumps@5.0:+mpi+shared^netcdf@4.4.1%gcc@6.2.0~hdf4 maxdims=1024 maxvars=8192+mpi arch=darwin-sierra-x86_64^openblas@0.2.19%gcc@6.2.0+fpic~openmp+shared arch=darwin-sierra-x86_64^openssl@1.0.2j%gcc@6.2.0 arch=darwin-sierra-x86_64^parmetis@4.0.3%gcc@6.2.0~debug~gdb+shared arch=darwin-sierra-x86_64^scalapack^suite-sparse^superlu-dist@5.0.0%gcc@6.2.0 arch=darwin-sierra-x86_64^zlib@1.2.8%gcc@6.2.0 arch=darwin-sierra-x86_64'. Package trilinos requires version 12.6.2, but spec asked for 12.8.1

This is from my BarrySmith fork in the branch barry/develop

"but spec asked for 12.8.1" Well, but what spec? Could this message be more informative by indicating exactly what is requesting each version? You need more complete error messages so even and idiot like my can determine what I have done wrong. Terse error messages make users very frustrated.

As far as I know I've tried to require that Trilinos not use mumps and suite-sparse in xsdk so I am totally mystified why + for them appears in that "Invalid spec", where is that coming from?

**Comment by tgamblin** [comment]
I need to look at this one more closely.  It seems like a bug to me - the default trilinos version in there somehow but I'm not sure why.

**Comment by BarrySmith** [comment]
@tgamblin I'm going to have to beg you to try this yourself to see if you can track down the problem. I  have had no luck and don't have any idea as to what to try next to get this to work.

Currently this is blocking an further progress on the spack xSDK package so the sooner you can get to it the better.  It is the branch barry-develop in my fork. RUn with 

$ ./spack install  xsdk@0.1.0

I get 

==> Error: Invalid spec: 'trilinos@12.8.1%intel@16.0.3+boost~debug+hdf5+hypre+metis+mumps~python+shared+suite-sparse+superlu-dist~xsdkflags arch=linux-Ubuntu12-x86_64^boost^cmake@2.8.12%intel@16.0.3~doc+ncurses+openssl~ownlibs~qt arch=linux-Ubuntu12-x86_64^curl@7.50.3%intel@16.0.3 arch=linux-Ubuntu12-x86_64^glm@0.9.7.1%intel@16.0.3 arch=linux-Ubuntu12-x86_64^hdf5@1.10.0-patch1%intel@16.0.3+cxx~debug+fortran+mpi+shared~szip~threadsafe arch=linux-Ubuntu12-x86_64^hwloc^hypre@2.11.1%intel@16.0.3~internal-superlu+shared arch=linux-Ubuntu12-x86_64^libpciaccess^libsigsegv^libtool^m4@1.4.17%intel@16.0.3+sigsegv arch=linux-Ubuntu12-x86_64^matio@1.5.2%intel@16.0.3 arch=linux-Ubuntu12-x86_64^metis@5.1.0%intel@16.0.3~debug~gdb~idx64~real64+shared arch=linux-Ubuntu12-x86_64^mumps@5.0:+mpi+shared^netcdf@4.4.1%intel@16.0.3~hdf4 maxdims=1024 maxvars=8192+mpi arch=linux-Ubuntu12-x86_64^openblas@0.2.19%intel@16.0.3+fpic~openmp+shared arch=linux-Ubuntu12-x86_64^openmpi@2.0.1%intel@16.0.3~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-Ubuntu12-x86_64^openssl@1.0.2j%intel@16.0.3 arch=linux-Ubuntu12-x86_64^parmetis@4.0.3%intel@16.0.3~debug~gdb+shared arch=linux-Ubuntu12-x86_64^pkg-config@0.9.0:^scalapack^suite-sparse^superlu-dist@5.0.0%intel@16.0.3 arch=linux-Ubuntu12-x86_64^util-macros^zlib@1.2.8%intel@16.0.3 arch=linux-Ubuntu12-x86_64'. Package trilinos requires version 12.6.2, but spec asked for 12.8.1

**Comment by alalazo** [comment]
@BarrySmith So, it turns out you have a bit of syntax errors in your dependencies:
```
depends_on('petsc@3.7.4+trilinos@12.6.2+mpi+hypre+superlu-dist+metis+hdf5~mumps~boost', when='@0.1.0')
```
should read (note the `^` before trilinos)
```
depends_on('petsc@3.7.4^trilinos@12.6.2+mpi+hypre+superlu-dist+metis+hdf5~mumps~boost', when='@0.1.0')
```
I don't know how this makes the parser or the concretizer go insane, but it's worth a try fixing it.

**Comment by alalazo** [comment]
@BarrySmith Sorry for the noise before. Looking at your branch `petsc/package.py` the correct line should be:
```
depends_on('petsc@3.7.4+trilinos+mpi+hypre+superlu-dist+metis+hdf5~mumps~boost', when='@0.1.0')
```
The thing is you should not apply version to variants, as they are just boolean flags used to activate a behavior during build (even if they have the same name as a dependency).

**Comment by BarrySmith** [comment]
Thanks for the suggestion

I tried dropping the dependency and still get the same error.

./spack install  xsdk@0.1.0
==> Error: Invalid spec: 'trilinos@12.8.1%intel@16.0.3+boost~debug+hdf5+hypre+metis+mumps~python+shared+suite-sparse+superlu-dist~xsdkflags arch=linux-Ubuntu12-x86_64^boost^cmake@2.8.12%intel@16.0.3~doc+ncurses+openssl~ownlibs~qt arch=linux-Ubuntu12-x86_64^curl@7.50.3%intel@16.0.3 arch=linux-Ubuntu12-x86_64^glm@0.9.7.1%intel@16.0.3 arch=linux-Ubuntu12-x86_64^hdf5@1.10.0-patch1%intel@16.0.3+cxx~debug+fortran+mpi+shared~szip~threadsafe arch=linux-Ubuntu12-x86_64^hwloc^hypre@2.11.1%intel@16.0.3~internal-superlu+shared arch=linux-Ubuntu12-x86_64^libpciaccess^libsigsegv^libtool^m4@1.4.17%intel@16.0.3+sigsegv arch=linux-Ubuntu12-x86_64^matio@1.5.2%intel@16.0.3 arch=linux-Ubuntu12-x86_64^metis@5.1.0%intel@16.0.3~debug~gdb~idx64~real64+shared arch=linux-Ubuntu12-x86_64^mumps@5.0:+mpi+shared^netcdf@4.4.1%intel@16.0.3~hdf4 maxdims=1024 maxvars=8192+mpi arch=linux-Ubuntu12-x86_64^openblas@0.2.19%intel@16.0.3+fpic~openmp+shared arch=linux-Ubuntu12-x86_64^openmpi@2.0.1%intel@16.0.3~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-Ubuntu12-x86_64^openssl@1.0.2j%intel@16.0.3 arch=linux-Ubuntu12-x86_64^parmetis@4.0.3%intel@16.0.3~debug~gdb+shared arch=linux-Ubuntu12-x86_64^pkg-config@0.9.0:^scalapack^suite-sparse^superlu-dist@5.0.0%intel@16.0.3 arch=linux-Ubuntu12-x86_64^util-macros^zlib@1.2.8%intel@16.0.3 arch=linux-Ubuntu12-x86_64'. Package trilinos requires version 12.6.2, but spec asked for 12.8.1

I have pushed my most recent attempt here are the relevent lines

    depends_on('petsc@3.7.4+trilinos+mpi+hypre+superlu-dist+metis+hdf5~mumps~boost', when='@0.1.0')
    depends_on('petsc@develop^trilinos+mpi+hypre+superlu-dist+metis+hdf5~mumps~boost', when='@develop')


BTW: in this branch PETSc does depend on trilinos.

Also what does ^ mean ?

**Comment by alalazo** [comment]
`^` means "depens on, so this line : 
```
petsc@3.7.4+trilinos+mpi+hypre+superlu-dist+metis+hdf5~mumps~boost
```
means `petsc` at version `3.4` with variants :
- `trilinos`, `mpi`, `hypre` and anythong with `+` activated
- `mumps` and `boost` deactivated
while this one:
```
petsc@develop^trilinos+mpi+hypre+superlu-dist+metis+hdf5~mumps~boost
```
means `petsc` at version `develop` that *depends on* `trilinos with variants etc etc

**Comment by BarrySmith** [comment]
So all the stuff after trilinos is a variant of Trilinos? That is a I want a trilinos with mpi and hyper etc variants? i.e they are variants of trilinos not petsc?

**Comment by tgamblin** [comment]
@BarrySmith: the syntax is recursive, so:

```
PACKAGE [@PACKAGE_VERSION | %COMPILER[@COMPILER_VERSION] | +VARIANT | ~VARIANT ] [^DEPENDENCY_PACKAGE [same options as above] ...]

**Comment by BarrySmith** [comment]
@tgamblin Ok thanks.

In my branch I have made trilinos a variant of PETSc so I guess I should use the +trilinos. 

But I am still stuck because somehow spack is picking inconsistent versions of trilinos

Package trilinos requires version 12.6.2, but spec asked for 12.8.1

I don't understand why it is every picking 12.8.1 since PETSc and xsdk are both, in this case, saying they want 12.6.2

**Comment by tgamblin** [comment]
is your PR branch up to date?  If so I'll try it

**Comment by BarrySmith** [comment]
Yes, it is was fails for me. Thanks

**Comment by alalazo** [comment]
@tgamblin @BarrySmith Was this solved ? Otherwise I may try also to give a look at it today.

**Comment by tgamblin** [comment]
@alalazo @BarrySmith Ok, it looks like Barry is managing to find all the spots in Spack I've been putting off making smarter.  This one in particular is in the concretizer.

The concretizer needs to do better backtracking to handle all the constraints in the DAG for xSDK.  Right now it looks ahead one step, sees if things will fail, and continues if they don't fail immediately.  In this case Spack is messing up the order in which concrete versions are assigned and optional dependency constraints are merged -- the version of `trilinos` is getting concretized _before_ the optional trilinos dependency from `xsdk` is merged in.  Similar things happen along other paths in the solve for the `xsdk` spec if you fix that.

I think I can get this fixed this week.  In the meantime, @BarrySmith: can you test without the conditional dependencies in `xsdk`?  If you comment them out it should at least allow you to test difference scenarios while I'm getting this fixed.

**Comment by alalazo** [comment]
@tgamblin @BarrySmith Given the date of the last post, I argue the issue has been fixed. Please reopen if I am wrong and this still needs to be fixed.
