### ISSUE TITLE
Flux 'develop' fails to build

### ISSUE THREAD

**Issue by SteVwonder** [spack/spack#2109]
The latest version of Flux fails to build and install under Spack.  It fails to build the documentation.  Relevant log:

```
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/data/hd1/Repositories/spack/opt/spack/linux-Ubuntu16-x86_64/gcc-5.4.0/asciidoc-8.6.9-ih72kxayqymv73wtagfje4fo5ajt3gvq/etc/asciidoc/docbook-xsl/manpage.xsl" "/tmp/sherbein/spack-stage/spack-stage-5gaNjd/flux-core/doc/man1/flux-keygen.xml" returned non-zero exit status 5
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/data/hd1/Repositories/spack/opt/spack/linux-Ubuntu16-x86_64/gcc-5.4.0/asciidoc-8.6.9-ih72kxayqymv73wtagfje4fo5ajt3gvq/etc/asciidoc/docbook-xsl/manpage.xsl" "/tmp/sherbein/spack-stage/spack-stage-5gaNjd/flux-core/doc/man1/flux-snoop.xml" returned non-zero exit status 5
Makefile:672: recipe for target 'flux-keygen.1' failed
make[2]: *** [flux-keygen.1] Error 1
make[2]: *** Waiting for unfinished jobs....
```

When I run the same command with `spack env flux`, it successfully completes, so I am unsure of how to debug this issue:

```
→ ./spack env flux "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/data/hd1/Repositories/spack/opt/spack/linux-Ubuntu16-x86_64/gcc-5.4.0/asciidoc-8.6.9-ih72kxayqymv73wtagfje4fo5ajt3gvq/etc/asciidoc/docbook-xsl/manpage.xsl" "/tmp/sherbein/spack-stage/spack-stage-5gaNjd/flux-core/doc/man1/flux-keygen.xml"
Note: Writing flux-keygen.1
```

@trws, any suggestions?

EDIT: I forgot to mention that I am running into this issue with the version of Spack found in PR #2108.

Full build log: **https://gist.github.com/SteVwonder/22124fffade9ada75855809049c1ac28**

**Comment by trws** [comment]
It's almost certainly an issue with the adoc generation.  The toolchain to install xslt and all of the other dependencies for a2x is incredibly complicated, and not at all automated, so there may be a new issue in the way those packages interact.  If anyone knows a good way to package up those dependencies, I would be most appreciative to know it actually.

**Comment by trws** [comment]
Turns out pandoc is massively, and I do mean *massively*, easier to install and seems to do just as well. May be worth reworking the flux build end to use it as an option.  Thoughts @garlick?

**Comment by garlick** [comment]
Hmm!  Interesting.  On my ubuntu desktop, `apt-get install pandoc` just worked!

However, I'm not sure it groks asciidoc as input though, only output?  E.g. I'm trying something like this
```makefile
flux_respond.3: flux_respond.adoc
        pandoc -o $< $@ -f asciidoc -t man --standalone --smart
```
when you said it does just as well, what "reader" did you select?

**Comment by tgamblin** [comment]
If the docs are available online and a pain to build, would it make sense to make them an optional and default to not installing?

**Comment by garlick** [comment]
If a2x isn't found by configure, it should skip building the man pages with the following warning:
```
No a2x utility found. Manual pages will not be generated.
```
however maybe a2x is found but other components of the asciidoc tool chain are missing?  Maybe we should either test build a page in configure or add a --disable-doc option or similar.

**Comment by trws** [comment]
A `--disable-doc` option would definitely help.  When I tried pandoc it worked without specifying a reader, and generated the manpage output with just `pandoc -o flux-exec.1 flux-exec.adoc`.  Adding the specific options also worked.  Maybe the asciidoc reader isn't in the ubuntu version by default for some reason?

**Comment by trws** [comment]
Evidently this worked because it was a small file that didn't use any real asciidoc features, there is no official reader for it, just https://github.com/tarleb/huskydoc that can do a pre-conversion to pandoc json then use pandoc to generate the output.  This is the one big downside to asciidoc, it really only has one toolchain. =(

**Comment by trws** [comment]
Ok, perhaps a better backup solution.  Installed with one gem command, runs faster than a2x, and has a manpage backend: http://asciidoctor.org/

**Comment by sethrj** [comment]
It looks like this issue is long-resolved; there's a default-to-off `doc` variant  for `flux-core.
