### ISSUE TITLE
[idea] external packages via pkg-config

### ISSUE THREAD

**Issue by trws** [spack/spack#212]
Looking over PR #120, which looks great btw, it occurred to me that leveraging pkg-config might be a pretty cool way to extend this.  Specifically, I'm thinking of the fact that pkg-config files can carry arbitrary additional information, including potentially spack-compatible specs, hashes, etc.  If spack looks for a variable, say `spack-spec`, in each available pkg-config module, then loads them in much like it does for adding compilers from PATH, it could make external packages quite usable.  Especially if spack itself inserts these specs into its output, so packages installed globally that were built by a spack, but potentially not the one in use, could be picked up.

**Comment by mathstuf** [comment]
I think that modules have been decided the way to go forward with this? Not 100% sure though.

**Comment by trws** [comment]
Much as spack is designed for HPC, it's worth noting that the *vast* majority of systems do not have, or use, modules.  By the same token, nearly all unix-like systems have, and use, pkg-config even for packages that are built and installed manually outside of their built-in package system.

If the decision is to use modules alone, fair enough, but it would leave a significant body of packages unfound and unfindable on most systems.

**Comment by mathstuf** [comment]
Agreed, however OS X does *not* have `pkg-config` out-of-the-box either and since that seems to be the developer platform of choice these days, `pkg-config` doesn't help any more than modules there either.

**Comment by trws** [comment]
Quite so, but it's worth noting that it is possible to use it, and any 
packages installed through homebrew, for example, with support for it do 
install a pig-config file for it. My mac desktop has 221 pkg-config 
enabled packages on it in default paths, and exactly 0 modules.

**Comment by becker33** [comment]
To the extent this is for finding arbitrary packages, I think it is satisfied by #15158 and #16526.

To the extent this is for finding Spack packages installed by a separate instance, I think this is covered by #8772.

If you think this proposal should be considered separately from the linked issues, feel free to reopen it and ping me.
