### ISSUE TITLE
Using existing package with different compiler and multiple installations

### ISSUE THREAD

**Issue by pramodk** [spack/spack#2130]
I was wondering why I have two hdf5 packages installed with same compiler and same variant:

``` bash
spack find -v  hdf5 %gcc
==> 2 installed packages.
-- linux-redhat6-x86_64 / gcc@4.9.0 -----------------------------
hdf5@1.10.0-patch1+cxx~debug~fortran+mpi+shared~szip~threadsafe
hdf5@1.10.0-patch1+cxx~debug~fortran+mpi+shared~szip~threadsafe
```

(they have different hash though, so may not be same problem as in #2087).

As hash different, I thought there might be some changes, fine.

Now I see below:

``` bash
 spack install hdf5 +mpi %gcc
==> hdf5 is already installed in /some_path//linux-redhat6-x86_64/gcc-4.9.0/hdf5-1.10.0-patch1-gkx34kcxlc7yyy75zhgbdhtuodmm65pp

→ spack install hdf5 %gcc
==> hdf5 is already installed in /some_path//linux-redhat6-x86_64/gcc-4.9.0/hdf5-1.10.0-patch1-gkx34kcxlc7yyy75zhgbdhtuodmm65pp
```

I understand `+mpi` is `on` and hence thats the same package. Now I want to use this `hdf5` with `PGI` compiler:

``` bash
spack install mypkg %pgi ^hdf5%gcc
==> Installing mypkg
==> mvapich2 is externally installed in /some_path/mvapich2-2.0.1-nocuda-slurm-14.03.4.2/install
==> cmake is externally installed in cmake-3.6.1-gcc-4.4.7-xhpqagp
==> Installing hdf5
….
```

Why installing hdf5 again?

And then adding `+mpi` : 

``` bash
spack install mypkg %pgi ^hdf5+mpi%gcc
==> Installing mypkg
==> mvapich2 is externally installed in /some_path/mvapich2-2.0.1-nocuda-slurm-14.03.4.2/install
==> cmake is externally installed in cmake-3.6.1-gcc-4.4.7-xhpqagp
==> hdf5 is already installed in ...
```

Why adding `+mpi` variant makes difference?

**Comment by adamjstewart** [comment]
Hmm, adding `+mpi` shouldn't affect the spec because it already defaults to True for HDF5. Do you have it set to False in your `packages.yaml`? What is the output of `spack spec mypkg %pgi ^hdf5+mpi%gcc` vs `spack spec mypkg %pgi ^hdf5%gcc`?

**Comment by pramodk** [comment]
here are specs:

```bash

○ → spack spec mypkg %pgi ^hdf5%gcc
Input spec
------------------------------
  mypkg%pgi
      ^hdf5%gcc

Normalized
------------------------------
  mypkg%pgi
      ^cmake@2.8.12:
      ^hdf5%gcc
          ^zlib@1.1.2:
      ^mpi@2.2:

Concretized
------------------------------
  mypkg@develop%pgi@16.5-0~zlib arch=linux-redhat6-x86_64
      ^cmake@3.6.1%pgi@16.5-0~doc+ncurses+openssl~ownlibs~qt arch=linux-redhat6-x86_64
      ^hdf5@1.10.0-patch1%gcc@4.9.0+cxx~debug~fortran+mpi+shared~szip~threadsafe arch=linux-redhat6-x86_64
          ^mvapich2@2.0.1%pgi@16.5-0~debug~gforker~hydra~mrail~nemesis~nemesisib~nemesisibtcp~psm~remshell~slurm~sock arch=linux-redhat6-x86_64
          ^zlib@1.2.8%gcc@4.9.0 arch=linux-redhat6-x86_64


○ → spack spec mypkg %pgi ^hdf5+mpi%gcc
Input spec
------------------------------
  mypkg%pgi
      ^hdf5%gcc+mpi

Normalized
------------------------------
  mypkg%pgi
      ^cmake@2.8.12:
      ^hdf5%gcc+mpi
          ^mpi@2.2:
          ^zlib@1.1.2:

Concretized
------------------------------
  mypkg@develop%pgi@16.5-0~zlib arch=linux-redhat6-x86_64
      ^cmake@3.6.1%pgi@16.5-0~doc+ncurses+openssl~ownlibs~qt arch=linux-redhat6-x86_64
      ^hdf5@1.10.0-patch1%gcc@4.9.0+cxx~debug~fortran+mpi+shared~szip~threadsafe arch=linux-redhat6-x86_64
          ^mvapich2@2.0.1%gcc@4.9.0~debug~gforker~hydra~mrail~nemesis~nemesisib~nemesisibtcp~psm~remshell~slurm~sock arch=linux-redhat6-x86_64
          ^zlib@1.2.8%gcc@4.9.0 arch=linux-redhat6-x86_64
```

Note that if I remove `%pgi` (i.e. default `gcc`) then it doesn't try to install `hdf5`!

**Comment by pramodk** [comment]
and `packages.yaml` just has:

```bash
    hdf5:
        variants: ~fortran
```

**Comment by adamjstewart** [comment]
Ah, so you'll notice that difference in specs is that mvapich2 is built with gcc in one and pgi in the other. Does your package also depend on MPI?

**Comment by adamjstewart** [comment]
Btw, I happen to build a similar stack with GCC and PGI too. I assume the reason you are building `^hdf5+mpi%gcc` is because you were having problems building HDF5 and MVAPICH2 with PGI? I was having similar problems. PGI can't build libpciaccess or openssl, so if you're more specific about what you want to build with GCC then you might avoid the confusion. But if you're simply trying to minimize the number of reinstalls you need, good luck.

**Comment by pramodk** [comment]
>Ah, so you'll notice that difference in specs is that mvapich2 is built with gcc in one and pgi in the other. Does your package also depend on MPI?

@adamjstewart : oops! yes! I missed that completely!

**Comment by pramodk** [comment]
I have following confusion now:  I have `mypkg` depends on `mpi` and also `hdf5` depends on `mpi`. Why can’t I say :  `spack spec mypkg %pgi ^hdf5%gcc`. In this case I expected `hdf5` to be built by `mvapich%gcc` and `mypkg` with `mvapich%pgi`.

Is this for not mixing `mpi`'s built with different compilers?

**Comment by adamjstewart** [comment]
I think this is a dependency resolution bug, related to the order of when Spack determines constraints on things like compiler and variants. It's related to how `spack install hdf5 ^mpich` fails but `spack install hdf5 +mpi ^mpich` works. @tgamblin can say more about how it currently works and how it should ideally work.

**Comment by pramodk** [comment]
>Btw, I happen to build a similar stack with GCC and PGI too. I assume the reason you are building ^hdf5+mpi%gcc is because you were having problems building HDF5 and MVAPICH2 with PGI? I was having similar problems. PGI can't build libpciaccess or openssl, so if you're more specific about what you want to build with GCC then you might avoid the confusion.

Exactly! in my development environment I need parallel `hdf5`. But I am not able to build `hdf5` with `PGI`. Do you have recipe for this? (I am not building libpciaccess or openssl).

In attempt to use `hdf5` built by `GCC` I am trying below without any success: 

```bash
spack spec mypkg%pgi^mvapich2%pgi  ^hdf5+mpi%gcc^mvapich2%gcc
==> Error: Cannot depend on 'mvapich2%gcc' twice
```
this is confusing me!

>It's related to how spack install hdf5 ^mpich fails but spack install hdf5 +mpi ^mpich works.

this confuses me as well! (I was thinking to create issue)

**Comment by adamjstewart** [comment]
I've been installing `hdf5` with the following spec:
```
$ spack install hdf5 %pgi +mpi ^mvapich2 ^libpciaccess%gcc
```
So if you wanted to install `mypkg`, it would look something like:
```
$ spack install mypkg %pgi +mpi ^mvapich2 ^libpciaccess%gcc
```
But I agree that this is a bug. If this spec doesn't work, it could be a similar problem to #2068. @tgamblin Can you take a look at this issue too? I think it's a pretty common concretizer bug.

**Comment by alalazo** [comment]
(Time passes and 4 years later...) Reading through this issue to check what we can close with #19501 I think this was a misunderstanding of what the concretizer should do. In the cases above the original concretizer just refuses to bring 2 MPI providers into the same DAG, which is by design. 

The only other issue I see is mentioned in https://github.com/spack/spack/issues/2130#issuecomment-256183409 and it's already tracked by other issues.
