### ISSUE TITLE
We need instructions for using X11 fonts.

### ISSUE THREAD

**Issue by hartzell** [spack/spack#2141]
I built R with Spack's X11 libraries and everything seemed ok.

Then I ran this little snippet

``` R
png('moose.png')
boxplot(mpg~cyl,data=mtcars, main="Car Milage Data", xlab="Number of Cylinders", ylab="Miles Per Gallon")
dev.off()
```

and it generated a PNG file for me without any complaints.

But when scp'ed the file to my mac and opened  it, I discovered that all of the characters in the axes and labels  and ... had been replaced by little unfilled rectanges (presumably their bounding boxes).

I hadn't installed any fonts, so I put together this script:

``` sh
#!/bin/sh

spack install font-util
spack install encodings
spack install font-adobe-100dpi
spack install font-adobe-75dpi
spack install font-adobe-utopia-100dpi
spack install font-adobe-utopia-75dpi
spack install font-adobe-utopia-type1
spack install font-alias
spack install font-arabic-misc
spack install font-bh-100dpi
spack install font-bh-75dpi
spack install font-bh-lucidatypewriter-100dpi
spack install font-bh-lucidatypewriter-75dpi
spack install font-bh-ttf
spack install font-bh-type1
spack install font-bitstream-100dpi
spack install font-bitstream-75dpi
spack install font-bitstream-type1
spack install font-cronyx-cyrillic
spack install font-cursor-misc
spack install font-daewoo-misc
spack install font-dec-misc
spack install font-ibm-type1
spack install font-isas-misc
spack install font-jis-misc
spack install font-micro-misc
spack install font-misc-cyrillic
spack install font-misc-ethiopic
spack install font-misc-meltho
spack install font-misc-misc
spack install font-mutt-misc
spack install font-schumacher-misc
spack install font-screen-cyrillic
spack install font-sony-misc
spack install font-sun-misc
spack install font-winitzki-cyrillic
spack install font-xfree86-type1
```

These died with an assertion in database.py (#2139), but the rest installed.

```
font-adobe-utopia-type1
font-bitstream-type1
font-ibm-type1
font-misc-ethiopic
font-misc-meltho
font-xfree86-type1
```

Simply install'ing them didn't do anything useful (still got bounding boxes instead of glyphs), but that's not surprising.  Then I set to figuring out how to make X aware of them.

I ended up doing:

```
module load fontconfig
mkdir -p ~/.config/fontconfig/
vi ~/.config/fontconfig/fonts.conf
fc-cache -f
```

with a fonts.conf that looked like so:

``` xml
<?xml version="1.0"?>
      <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
      <fontconfig>
        <dir>/rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/font-util-1.3.1-6rs7qlybxshfpui546rmxoeuxkahypbv/share/fonts/X11</dir>
      </fontconfig>
```

and my PNG image had glyphs instead of bounding boxes.

The glyphs were ugly/jaggy, presumably I need to turn on anti-aliasing somewhere.

It would be nice to have some instructions about how this is supposed to work.  I'm clearly flying a bit blind, but am happy to wordsmith.

**Comment by hartzell** [comment]
Uninstalling and installing *mkfontdir* allowed me to install the fonts that had failed above (see the thread in #2139).

**Comment by hartzell** [comment]
In a bit more poking and prodding I linked the various config presets into my fontconfig directory and reran `fc-cache -f`

```bash
mkdir ~/.config/fontconfig/conf.g
for f in /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/fontconfig-2.11.1-ti2zz3wpp4yflrik6p7pt5nih7ngdhip/share/fontconfig/conf.avail/* ; do ln -s $f ~/.config/fontconfig/conf.d; done
fc-cache -f
```

Now the large text/title of the graph is smeary (subpixel rendering?) but the rest is still jaggy (missing anti-aliasing?).

**Comment by adamjstewart** [comment]
One thing worth noting about the fonts is that they don't actually install to their prefix. They install into the `font-util` installation. Other that that, I don't know anything about them, I just added the packages. I honestly never though anyone was going to use them, so I guess I'm glad I added them now. Thanks for working so hard to integrate X11 properly!

**Comment by hartzell** [comment]
> Other that that, I don't know anything about them, I just added the packages.

Oh dear.  Here I was hoping you'd tell me what to do.  :fearful:...

**Comment by citibeth** [comment]
OK, a few questions/comments here:

1. Maybe fonts should be integrated it the `font-util` installation via Spack extensions and `spack activate`, just like Python packages?

2. @hartzell was X11 already installed on this machine?  I'm asking because I want to know... do these font issues show up as soon as you use a Spack-built X?  Or only if you didn't already have the fonts installed and configured elsewhere on your machine.

3. Can you make a meta-package that installs a useful set of fonts?  See #2049

**Comment by hartzell** [comment]
> Maybe fonts should be integrated it the font-util installation via Spack extensions and spack activate, just like Python packages?

There's something that needs to be done here.  There's some magic that I still don't understand, what @adamjstewart did very closely mirrors what the linuxbrew xorg recipes do yet somehow their fonts end up "hooked up" and our don't.

I'm trying to understand why (just about to simply ask them...).  Neither project installs the fonts in any traditional location or in a directory that's arranged to be searched via the conf file.  Both projects end up with font cache files in places where you'd expect fontconfig to look at runtime (e.g. `opt/spack/linux-centos7-x86_64/gcc-5.4.0/fontconfig-2.11.1-ti2zz3wpp4yflrik6p7pt5nih7ngdhip/var/cache/fontconfig/`) and those files have references to the real locations of the fonts, so I have a hypothesis that that's how they're being discovered.  Seems fragile though, since those are *caches* that are built at install time.

Still, my real problem is that the linuxbrew setup "works" and ours "doesn't" (for the one simple test of my R plot, though come to think of it there are missing fonts in the emacs+X+gtkplus menubars too).

> @hartzell was X11 already installed on this machine?

No, to avoid confusion this droplet is set up without any X libraries.

**Comment by hartzell** [comment]
I've just created PR #2203, which fixes the immediate problem with my R plots.

The plots drawn by a linuxbrew installed R (using their xorg stuff) are still nicer than Spack's, I think it's an antialiasing issue but it could be different default fonts or ....  I'll continue to try to track it down.

**Comment by becker33** [comment]
The font-utils package has been refactored so that all of these fonts are variants instead of separate packages -- I believe this change addresses the issue here, but if I am somehow mistaken, please reopen and ping me.
