### ISSUE TITLE
Stacked Spacks

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2177]
This is similar but distinct from #2171.  The idea is, we need to have multiple Spacks administered by different people, and "stacked" on top of each other.

Sysadmins will use Spack to build a bunch of software to be shared by everyone.  Users will use a Spack "stacked" on top of the sysadmins Spack.  If required packages are already built in the sysadmin Spack, they will be used by packages in the user Spack.  But any new packages to be built will be put in the user Spack.

I'm wondering what would be involved in this... would Spack need to load and search in multiple databases?  Or just load/search multiple directories of the install trees?

**Comment by becker33** [comment]
How is this different from #642?

**Comment by citibeth** [comment]
Not much, I suppose.  I believe that more recent "spack server" proposals
supercede both.

**Comment by alalazo** [comment]
Superseded by #3156
