### ISSUE TITLE
Cannot uninstall software

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2199]
I have two versions of mvapich2 installed, 2.2b and 2.2. But I am unable to uninstall them:
```
$ spack uninstall mvapich2@2.2 %gcc@5
==> Error: mvapich2@2.2%gcc@5 matches multiple packages:

-- linux-centos6-x86_64 / gcc@5.3.0 -----------------------------
v6xdy4c mvapich2@2.2%gcc~debug~gforker+hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell~slurm~sock

m6iglhi mvapich2@2.2b%gcc~debug~gforker+hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell~slurm~sock


==> Error: You can either:
    a) Use a more specific spec, or
    b) use spack uninstall -a to uninstall ALL matching specs.
```
I'm also unable to install them by hash:
```
$ spack uninstall /v6xdy4ccf7drmudbjkxa2vu6ctovy2jj
==> Error: mvapich2@2.2%gcc@5.3.0~debug~gforker+hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell~slurm~sock arch=linux-centos6-x86_64^bison@3.0.4%gcc@5.3.0 arch=linux-centos6-x86_64^libpciaccess@0.13.4%gcc@5.3.0 arch=linux-centos6-x86_64 matches multiple packages:

-- linux-centos6-x86_64 / gcc@5.3.0 -----------------------------
v6xdy4c mvapich2@2.2%gcc~debug~gforker+hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell~slurm~sock

m6iglhi mvapich2@2.2b%gcc~debug~gforker+hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell~slurm~sock


==> Error: You can either:
    a) Use a more specific spec, or
    b) use spack uninstall -a to uninstall ALL matching specs.
```
Uninstalling them by running `rm` on the directory followed by `spack reindex` corrupts my Spack database, and I can no longer install anything:
```
$ spack install mvapich2 %gcc@5
==> Installing mvapich2
==> libpciaccess is already installed in /blues/gpfs/home/software/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-5.3.0/libpciaccess-0.13.4-tbllpvg3h4r2hgxkvzgtmgm645g777ub
Traceback (most recent call last):
  File "/soft/spack-0.9.1/bin/spack", line 203, in <module>
    main()
  File "/soft/spack-0.9.1/bin/spack", line 180, in main
    return_val = command(parser, args)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/cmd/install.py", line 342, in install
    package.do_install(**kwargs)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/package.py", line 1190, in do_install
    **kwargs
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/package.py", line 1162, in do_install
    rec = spack.store.db.get_record(self.spec)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/database.py", line 80, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/database.py", line 529, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/database.py", line 521, in _get_matching_spec_key
    match = self.query_one(spec, **kwargs)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/database.py", line 655, in query_one
    assert len(concrete_specs) <= 1
AssertionError
```
This was reported in #2123, and I have no idea what is causing it. Please help.

**Comment by adamjstewart** [comment]
Could all of these bugs be caused by the fact that Spack can't differentiate between mvapich 2.2 and 2.2b? 2.2b is no longer in the package, so that could also complicate things. @davydden @citibeth have either of you seen anything while playing around with version handling that might explain why Spack can't differentiate between 2.2 and 2.2b?

**Comment by davydden** [comment]
i think it is indeed similar to that issue with a single `python` version, namely Spack reads `@2.2` not as a concrete spec, so that both `2.2` and `2.2b` satisfy it.

**Comment by citibeth** [comment]
>
> i think it is indeed similar to that issue with a single python version,
> namely Spack reads @2.2 not as a concrete spec, so that both 2.2 and 2.2b satisfy
> it.


Maybe it would work better if Spack thought of it as version `2.2.b`
instead of `2.2b`?  Spack versions work like sets that "contain" versions
longer than them.  But since `2.2b` is the same length as `2.2`, neither
one can contain the other.

I'm not sure how Spack would view `2.2.b` at this point...  another place
where fiddling around with `Version` might be warranted, but I think we
will want pluggable version schemes so we don't break 100
packages inadvertently while fixing one.

**Comment by tgamblin** [comment]
@citibeth: That **is** how versions work.  `2.2b` and `2.2.b` are the same for comparison purposes; Spack splits on either non-alphanumeric characters *or* alpha/numeric boundaries, and compares the resulting tuples lexicographically. `Version.__contains__`:

```python
    @coerced                                                                                                            
    def __contains__(self, other):                                                                                      
        if other is None:                                                                                               
            return False                                                                                                
        return other.version[:len(self.version)] == self.version 
```

**Comment by adamjstewart** [comment]
@tgamblin If that's the case, then what is causing this problem?

**Comment by paulhopkins** [comment]
I am looking at a issue now where I can't activate / deactivate or uninstall packages by hash. It looks like this commands gets the exact spec out of the database and then later on it used to query the database and it gets multiple versions back out. Essentially the commands run:

 ```
specs = spack.cmd.parse_specs(args.spec)
spec = spack.store.db.query(specs[0])
```

If I just use `spec = spec[0]` then the rest of the command works. Really, we need to recognise that the exact package has been recovered by the parser.

**Comment by citibeth** [comment]
@tgamblin  See code below from `version.py`.  I'll be "durned", it does exactly what you said.

```
class Version(object):
    """Class to represent versions"""

    def __init__(self, string):
        string = str(string)

        if not re.match(VALID_VERSION, string):
            raise ValueError("Bad characters in version string: %s" % string)

        # preserve the original string, but trimmed.
        string = string.strip()
        self.string = string

        # Split version into alphabetical and numeric segments
        segment_regex = r'[a-zA-Z]+|[0-9]+'
        segments = re.findall(segment_regex, string)
        self.version = tuple(int_if_int(seg) for seg in segments)

        # Store the separators from the original version string as well.
        # last element of separators is ''
        self.separators = tuple(re.split(segment_regex, string)[1:-1])
```

**Comment by adamjstewart** [comment]
Isn't that how the regex works? It matches groups of alpha characters OR numeric characters and adds each group to a tuple.

**Comment by tgamblin** [comment]
I have a large PR that adds support for exact versions coming -- still debugging today.  The issue with versions is that Spack's current notion of "concrete" is "has only a single version", but that's wrong, as versions are really sets.  It will be possible to have either an exact or inexact version, and the concretizer will only mark something concrete if the version is exact.

**Comment by tgamblin** [comment]
The PR addresses the various version issues in the 0.10 release.

**Comment by citibeth** [comment]
@tgamblin Oh boy, looks like that will affect the refactoring work I've
been applying to `version.py`.  C'est la vie.  If you want to see where I'm
taking things, look at:

https://github.com/citibeth/spack/blob/efischer/161030-RefactorVersions/lib/spack/spack/version.py

Changes in that file that I think are beneficial (and have nothing to do
with the pluggable version stuff per se) include:

1. Eliminated None as a legal start/end in VersionRange; instead use
sentinels that will be bigger than everything or smaller than everything.
Simplifies the VersionRange code a lot.

2. Formalized the concept of a MetaVersion =
Version/VersionRange/VersionList.

3. Built my own dispatch for `__eq__()` and `__lt__()` for MetaVersions.
There are 16 different combinations (Version, SentinelVersion,
VersionRange, VersionList)^2, and there's (in theory) a different method
for each combination.  This should perform well and I believe is simpler in
the end then the coersion stuff going on previously.

**Comment by davydden** [comment]
i also have problems with uninstalling by hash, it used to work:
```
$ spack uninstall cairo /722bfct
==> Error: cairo matches multiple packages:

-- darwin-sierra-x86_64 / clang@8.0.0-apple ---------------------
ikhbosn cairo@1.14.0%clang

722bfct cairo@1.14.0%clang


==> Error: You can either:
    a) Use a more specific spec, or
    b) use spack uninstall -a to uninstall ALL matching specs.
```
Btw, `spack uninstall -h` should mention that you can use hashes.

**Comment by davydden** [comment]
interestingly enough it worked for another package (`cmake`).

**Comment by adamjstewart** [comment]
@davydden I've always had problems with:
```
$ spack uninstall packages /hash
```
but this generally works:
```
$ spack uninstall /hash
```
If neither work, then it sounds like you've ran into the same case as me.

**Comment by davydden** [comment]
you are right, i actually did not notice that I specified package to be uninstalled twice: with the name `cairo` and with  the hash `722bfct`. Probably that was the reason. Just confused myself :smile:

**Comment by citibeth** [comment]
That should be an easy fix...

**Comment by alalazo** [comment]
I think this has been fixed in the meanwhile. Can you confirm @adamjstewart ?

**Comment by citibeth** [comment]
Yes fixed
