### ISSUE TITLE
File Permissions for Multi-User Spack

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2211]
Not sure if this is already in Spack...

One potential issue with multi-user Spack is that different people will write files with different ownership and group permissions.  This could result in weird behavior; for example, you're unable to uninstall a package.

To solve this problem, Spack needs to ensure all files are written with proper group and umode.  By default, I would want things world-readable and group-writable.  Also, there needs to be a single group used for all Spack files, even if it's not users' default group.  These things should go in `config.yaml`, users should not have to set umode or group in their `.bashrc` to get this correct.

**Comment by alalazo** [comment]
relates to #1799

**Comment by alalazo** [comment]
Permissions are configurable since a while:

https://github.com/spack/spack/blob/8d118104c79bca646b193f84857b75b7f54359df/lib/spack/spack/schema/packages.py#L92-L108
