### ISSUE TITLE
spack load: don't load multiple variants of same packages and don't load packages that depend on different versions of already-loaded packages

### ISSUE THREAD

**Issue by mkuron** [spack/spack#2215]
Assume I have installed two versions of OpenMPI with matching versions of Boost by running the following:
```
spack install boost +mpi ^openmpi@1.10.3+slurm+verbs+pmi
spack install boost +mpi ^openmpi@1.8.8+slurm+verbs+pmi
```

Now if a user does the obvious thing
```
spack load openmpi
spack load boost
```
they end up with all matching modules loaded:
```
Currently Loaded Modulefiles:
  1) spack                              4) boost-1.62.0-gcc-4.9.4-bb3jpvq
  2) openmpi-1.8.8-gcc-4.9.4-gyda6cg    5) boost-1.62.0-gcc-4.9.4-5kz43yc
  3) openmpi-1.10.3-gcc-4.9.4-mnqdpir
```
This is of course never the intended action. To get the correct set of modules, a user will need to run commands like these instead:
```
spack load openmpi@1.10.3
spack load boost ^openmpi@1.10.3
```
`spack find --deps` can tell me what dependencies a package is linked to, but constructing dependency specs is not something you'd want to bother a novel user with if you can avoid it (also, they shouldn't need to care whether they're using OpenMPI 1.10.1 or 1.10.3). I think this could be made easier on the `spack load` level:
1. Since loading the same package in multiple versions or with multiple different dependencies never makes sense, first of all, all spack-generated module files should declare conflicts against all modules with the same name.
2. It should be possible to specify a default version that will be loaded if no version number is specified (e.g. `spack load openmpi` could translate into `spack load openmpi@1.10.3` or `spack load openmpi@1.8.8` depending on configuration). Similar to how `spack install openmpi` will always install the most recent version, except it should be configurable to a different version. Maybe _etc/spack/packages.yaml_ can already be used for this purpose.
3. If a dependency module (e.g. _openmpi@1.10.3_) is already loaded, then loading the dependent without further dependency specification (e.g. `spack load boost`) should automatically load the version of the dependent that is linked against the loaded dependency (in this example, _boost ^openmpi@1.10.3_)

**Comment by citibeth** [comment]
Try `spack module loads boost`

**Comment by mkuron** [comment]
Interesting command that could help with constructing dependency specs, if it actually showed the dependencies and not only the variants
```
$ spack module loads boost
# boost@1.62.0%gcc@4.9.4+atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math+mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave arch=linux-centos6-x86_64
module load boost-1.62.0-gcc-4.9.4-bb3jpvq
# boost@1.62.0%gcc@4.9.4+atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math+mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave arch=linux-centos6-x86_64
module load boost-1.62.0-gcc-4.9.4-5kz43yc
$ spack find --deps boost
==> 2 installed packages.
-- linux-centos6-x86_64 / gcc@4.9.4 -----------------------------
    boost@1.62.0
        ^bzip2@1.0.6
        ^openmpi@1.8.8
            ^hwloc@1.11.4
                ^libpciaccess@0.13.4
        ^zlib@1.2.8

    boost@1.62.0
        ^bzip2@1.0.6
        ^openmpi@1.10.3
            ^hwloc@1.11.4
                ^libpciaccess@0.13.4
        ^zlib@1.2.8
```

However, I still think that the suggestions I made for `spack load` in the three bullet points would be helpful in making the command easier to use and less error-prone for novice users.

**Comment by citibeth** [comment]
Sorry, I meant `spack module loads --dependencies boost`

**Comment by mkuron** [comment]
Ah yes, that essentially shows the dependency tree. So that will be quite helpful for me as the cluster admin, but it's nothing my users will probably want to bother with.
I suppose that one could manually write modulefiles to wrap Spack modulefiles to cover points 1 and 2 in my list, perhaps even 3 with some Tcl scripting, but handling these on a Spack level would be a cleaner and more convenient solution.

**Comment by citibeth** [comment]
OK, to be more clear:
```
spack module loads --dependencies boost >myenv.sh
source myenv.sh
```
Users don't want to be running Spack routinely in your `.bashrc` because it's slow.  `spack load` is good for one-offs in the shell, but not for setting up a list of modules you will load repeatedly.

The docs go into greater detail on this issue.

OK, to your points:


> Since loading the same package in multiple versions or with multiple different dependencies never makes sense, first of all, all spack-generated module files should declare conflicts against all modules with the same name.

I agree.  BUT... what if I want to load a new module explicitly to override an older module that's already loaded?  Even if they conflict, I just want the new module loaded.  I do this all the time.  So conflict declarations will only be useful if they don't impede common usage.

> It should be possible to specify a default version that will be loaded if no version number is specified (e.g. spack load openmpi could translate into spack load openmpi@1.10.3 or spack load openmpi@1.8.8 depending on configuration). Similar to how spack install openmpi will always install the most recent version, except it should be configurable to a different version. Maybe etc/spack/packages.yaml can already be used for this purpose.

Yes, this is a known weakness of `spack load`.  Spack has a great concretization algo it uses for `spack install`, but not for `spack load`, `spack find`, etc.  That's why multiple `spack load` (or `spack module loads`) commands are not a good way to set up a Spack-built environment.

Probably the best way I've found so far is to build a "bundle package" that depends on all the things you're interested in.  You do a `spack module loads` of that package, and there's your entire environment.  We're still working out the kinks, but it is something that you can do today.  Search recent PRs for "bundle package."

> If a dependency module (e.g. openmpi@1.10.3) is already loaded, then loading the dependent without further dependency specification (e.g. spack load boost) should automatically load the version of the dependent that is linked against the loaded dependency (in this example, boost ^openmpi@1.10.3)

This is not always desired, RPATH takes care of a lot of that.  See recent PR from @alalazo on how to control recursive loading of modules.

**Comment by mkuron** [comment]
Thanks for the extensive reply. Here is a bit more input from my side:

1. Regarding the conflicts: you are right about the problem of switching to a different version, but wouldn't you just want the new module to be loaded (and conversely, the old module to be unloaded)? So it should translate to `module switch modulename/newversion` if _modulename/oldversion_ is already loaded and `module load modulename/newversion` if not (dotkit probably has similar commands).

2. I understand that the bundle package approach would help here, but I'm not sure if our users would like to always need to request me to build a new bundle package before they can try out some new software. I see the weaknesses of using multiple `spack load` commands, but I guess that's exactly what a user will want (similar to `module load` when you're manually managing stuff without spack). Are there any plans for improvements here to also use the better algorithm for `spack load`?

3. You're right, I didn't consider the RPATHs. So it won't be necessary in most cases, but it is necessary in the case of OpenMPI, where both your own code and a library you use (Boost) have a common dependency (OpenMPI). So perhaps point 3 on the list in my original comment should only apply to a small list of packages (notably, all MPI implementations because you can't mix multiple versions of any of them).

Sorry for all the questions. It just seems to me that spack is the perfect solution for my problem (not wanting to manually maintain libraries on our cluster), and I'm trying to understand how to  best implement it for our users, who are used to using `module load` and then compiling their own code.

**Comment by alalazo** [comment]
@mkuron You may want to have a look at [this part](http://spack.readthedocs.io/en/latest/module_file_support.html) of the docs. Or even have a preview of the tutorial in #2228 that should guide you through an example that covers most of what you can do in terms of module file generation with the current Spack.

**Comment by citibeth** [comment]
On Thu, Nov 3, 2016 at 10:59 AM, Michael Kuron <notifications@github.com>
wrote:

> Thanks for the extensive reply. Here is a bit more input from my side:
>
>    1.
>
>    Regarding the conflicts: you are right about the problem of switching
>    to a different version, but wouldn't you just want the new module to be
>    loaded (and conversely, the old module to be unloaded)? So it should
>    translate to module switch modulename/newversion if
>    *modulename/oldversion* is already loaded and module load
>    modulename/newversion if not (dotkit probably has similar commands).
>
> I'm not a big believer in module unloading; it's a hard problem with only
minor benefits.  The easy problem is to add modules; and when you've had
enough, do a `module purge` and start over again.  Actually, I usually just
log out and in again; which is really easy with ssh connection sharing.


>
>    1.
>
>    I understand that the bundle package approach would help here, but I'm
>    not sure if our users would like to always need to request me to build a
>    new bundle package before they can try out some new software. I see the
>    weaknesses of using multiple spack load commands, but I guess that's
>    exactly what a user will want (similar to module load when you're
>    manually managing stuff without spack). Are there any plans for
>    improvements here to also use the better algorithm for spack load?
>
>
I suppose this all depends on the procedures and expectations at your
site.  Users don't HAVE to know about Spack at all.  Spack produces a bunch
of modules that they can see with `module avail`.  This will be especially
useful if you enable recursive loading of those modules.

Are you supplying a single environment for users to load and use; or a
mix-n-match set of pre-built software that they assemble into their own
environments?  I suppose the latter is a harder problem, especially to do
without users understanding Spack.

My gut feeling here is Spack needs a couple more features to make this
work.  The only question is, what?  One feature long on the the table for
the concretizer is to be able to concretize based on what's ALREADY
INSTALLED.  If we had that, then the concertizer could be used for `spack
load`, and a lot of things would become a whole lot better in this regard.
But as it is right now, `spack load` just is not very intelligent.


>    1.
>
>    You're right, I didn't consider the RPATHs. So it won't be necessary
>    in most cases, but it is necessary in the case of OpenMPI, where both your
>    own code and a library you use (Boost) have a common dependency (OpenMPI).
>    So perhaps point 3 on the list in my original comment should only apply to
>    a small list of packages (notably, all MPI implementations because you
>    can't mix multiple versions of any of them).
>
> So far I just use `spack module loads` even though I know it's overkill.


>
> Sorry for all the questions. It just seems to me that spack is the perfect
> solution for my problem (not wanting to manually maintain libraries on our
> cluster), and I'm trying to understand how to best implement it for our
> users, who are used to using module load and then compiling their own
> code.
>
 Great to hear that!  Spack is technically still Alpha, so bear with us!
But our very first numbered release is just around the corner.

**Comment by mkuron** [comment]
We provide libraries in a mix-and-match fashion and our users load whatever they need for the software they compile themselves.

After a bit of tinkering with configuration files, I think Spack will work fine for us as is. Users will not interact with the spack command at all, but instead use module load directly. By modifying the module naming scheme, I was able to get the module names unique even without looking at the hash and I was able to reduce the amount of identical packages built with different compilers by forcing the system compiler to be used unless otherwise specified.

Here's my packages.yaml:
```
packages:
  all:
    compiler: [gcc@4.4.7]
  boost:
    variants: [+mpi, +python]
    compiler: [gcc@4.9.4, gcc@5.4.0, gcc@6.2.0]
  openmpi:
    variants: [+pmi, +verbs, +slurm]
    compiler: [gcc@4.9.4, gcc@5.4.0, gcc@6.2.0]
```

And this is my modules.yaml:
```
modules:
  enable:
    - tcl
  tcl:
    naming_scheme: '${PACKAGE}/${VERSION}-${COMPILERNAME}-${COMPILERVER}'
    all:
      conflict: ['${PACKAGE}']
      suffixes:
        ^python@2.7.12: 'python-2.7'
        ^python@3.5.2: 'python-3.5'
        ^openmpi@1.6.5: 'openmpi-1.6'
        ^openmpi@1.8.8: 'openmpi-1.8'
        ^openmpi@1.10.3: 'openmpi-1.10'
        ^openmpi@2.0.0: 'openmpi-2.0'
        ^openmpi@2.0.1: 'openmpi-2.0'
    openmpi:
      environment:
        set:
          OMPI_MCA_hwloc_base_binding_policy: 'none'
          SLURM_MPI_TYPE: 'pmi2'
```

Of course, I can't easily declare complex conflicts that way (e.g. no package with _^openmpi@x_ in its spec should be loaded together with _openmpi@y_ if _x_ and _y_ are version numbers with different major or minor versions), but that shouldn't be too much of a burden on the users as my module naming scheme directly tells them the versions of dependency packages.

So thanks for helping me find out what I actually want. The only feature request I still have is a way to declare complex conflicts in modules.yaml without having to manually specify them for each pair of versions.

**Comment by alalazo** [comment]
@mkuron

> The only feature request I still have is a way to declare complex conflicts in modules.yaml without having to manually specify them for each pair of versions.

Do you have an example of such complex conflicts that comes e.g. from a use-case?

**Comment by alalazo** [comment]
@mkuron I think this is solved by using `lmod` (a.k.a. hierarchical) module files. Let me know if that would suffice to close the issue.

**Comment by mkuron** [comment]
@alalazo, sorry for the late replies...

> Do you have an example of such complex conflicts that comes e.g. from a use-case?

This is mainly a concern when you need multiple libraries (e.g. Scalapack and FFTW) that depend on a common library (e.g. MPI) or when you both need a library (e.g. Boost) and one of its dependencies (e.g. Python).
Assuming I have the following packages installed:
- `boost @1.62 +python ^python@2.7`
- `boost @1.62 +python ^python@3.4`
- `boost @1.62 +python ^python@3.5`
- `boost @1.65 +python ^python@2.7`
- `boost @1.65 +python ^python@3.5`
- `boost @1.65 +python ^python@3.6`

Then I'd like declare that each boost module conflicts with all python modules except for the one that it was built against. If I don't have these conflicts declared, then users who accidentally load `boost @1.62 +python ^python@2.7` and `python@3.6` and try to use Boost.Python in their own code get linker errors. If this was caught by the module system, the error would be clearer to the user.

Similarly, assuming I have the following packages installed:
- `netlib-scalapack ^openmpi@3`
- `netlib-scalapack ^openmpi@2`
- `fftw ^openmpi@3`
- `fftw ^openmpi@2`

Then I'd like to see an error message if `fftw ^openmpi@3` and `netlib-scalapack ^openmpi@2` are loaded together.

I guess this mostly affects Python and MPI as these don't allow you to use multiple versions of the same library from within the same process due to their complex internal state.

> I think this is solved by using lmod (a.k.a. hierarchical) module files. 

You may be right. Adding python and mpi to the hierarchy should suffice. I'm currently trying that.

**Comment by alalazo** [comment]
> python

This can't be added, only virtual deps can.

**Comment by mkuron** [comment]
> This can't be added, only virtual deps can.

What would need to be changed to support non-virtual dependencies?

**Comment by alalazo** [comment]
> What would need to be changed to support non-virtual dependencies?

I don't think it makes sense to enable hierarchies to non-virtual dependencies. The two solutions I see are:

1. `activate` the python packages you need, and generate modules only for the `python` interpreter
2. make `python` a virtual dependency (and call the `python` package `cpython`?)

I currently use 1. in production. It works well but has some limitations. 2. could be explored to enable other interpreters, like `pypy`. @adamjstewart Thoughts on this?

**Comment by mkuron** [comment]
Does number 1 even solve the problem? I'm not primarily talking about Python modules (py-numpy, etc.) but about C/C++ libraries and programs that depend on Python because they wrap or embed an interpreter (e.g. Boost, ParaView).

**Comment by alalazo** [comment]
> I'm not primarily talking about Python modules (py-numpy, etc.) but about C/C++ libraries and programs that depend on Python because they wrap the library or embed an interpreter (e.g. Boost, ParaView)

I see. My guess is that you shouldn't see issues because of `RPATH` (modulo dynamic loading if `Boost::Python` or other libraries use it). But I understand that this opens the way to have loaded in the environment an inconsistent set of modules.

**Comment by mkuron** [comment]
Boost Python is definitely an issue if you also need to make direct calls to the Python API from your code (unfortunately BP doesn‘t expose the entire Python API). Then you need to make sure to link against the same libpython that libboost_python is linked against. 

If you exclusively go through BP, I you may be right and the libraries should be fine thanks to rpaths. Headers might still be an issue though (e.g. what if libboost_python was built against Python 3.4 but the Boost headers include Python 2.7‘s headers because their module is loaded. Remember, I was talking about a mix-and-match scenario where Spack provides libraries and the users compile their own programs. If everything was built by Spack, none of these issues would exist.

**Comment by alalazo** [comment]
@mkuron I think I'll take a stab in the next few days at trying to make `python` a virtual dependency, and rename `python` to `cpython`. Maybe add [pypy](https://pypy.org/) too. I'll ping you as soon as I have a PR ready.

----

> e.g. what if libboost_python was built against Python 3.4 but the Boost headers include Python 2.7‘s headers because their module is loaded

OT: if it was like that, it would basically mean that a `(build, link)` dependency on `boost+python` injects a `(build, link)` dependency on `python`. Unfortunately, this is something we can't currently model. It may come however when we'll extend the model of compilers (as compilers are `build` dependencies that inject a `link` dependency on their run-time).

**Comment by citibeth** [comment]
Is there any demand for Python as a virtual dependency?  This really
worries me... MOST Python stuff, eg. any Python extension, will ONLY work
with CPython.  You can't just swap around CPython, Jython, PyPI, etc.

**Comment by alalazo** [comment]
@citibeth Not really, this will be just an experiment and I suspect it won't be merged soon even if it succeeds (due to all the recompilation it will involve).

**Comment by mkuron** [comment]
I guess it would be logical to have python be virtual. Alternative implementations can use all pure-Python modules and some that have C code even explicitly support PyPy (e.g. NumPy).

I agree with @citibeth though, this would likely cause all kinds of issues. Would it be easier to allow non-virtual dependencies in lmod hierarchies? Then we wouldn’t need to deal with making Python a virtual dependency.

**Comment by mkuron** [comment]
@alalazo, have you had any success making Python virtual? I decided to try if I could make Spack use the existing miniconda2 package as a replacement to CPython.

I only took a quick shot at it (rename Python to Cpython, add `python: [cpython, miniconda2]` to etc/spack/defaults/packages.yaml, add `provides`s to the miniconda2 and python packages) and noticed a few issues:
- The cpython package has some extra properties (`command`, `libs`, ...). Adding those to the miniconda2 package already allowed me to build _boost +python ^miniconda2_.
- One cannot currently extend virtual packages as the virtual dependencies appear to not have been concretized by the time the `extends` is performed. So packages like `py-numpy` fail to install (both _py-numpy ^cpython_ and _py-numpy ^miniconda2_). I don't know enough of the Spack internals to fix that myself.
- All providers of python will need to implement the `activate`/`deactivate` methods.

**Comment by alalazo** [comment]
> have you had any success making Python virtual?

@mkuron Thanks for the hints above, I'll keep them in mind when I get to this (didn't try to make python virtual yet, but will likely start something before next year). If you get there first and want to open a PR, please be my guest!. :grin:
