### ISSUE TITLE
Document how to create mock packages for unit tests

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2233]
> How do I create and use testing (mock?) packages? Just another thing that should be documented in the Developer Guide... sigh

I believe there are testing-oriented packages in the test repo.

I also have a "bundle" package (env-modele-ks) in efischer/develop on my fork (github/citibeth/spack).  It's pretty fast to install.

**Comment by citibeth** [comment]
See #2064 for an example (Thanks @davydden  )

**Comment by davydden** [comment]
> Thanks @davydden

you are welcome.

**Comment by alalazo** [comment]
Hmmm, closing since there's nothing special about using a mock package (it's just a package in a separate repository) + we have already #1935 that tracks the necessity to document how to write unit tests. Feel free to reopen if you disagree.
