### ISSUE TITLE
Consistency of Config Files

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2248]
@tgamblin @alalazo 
See #2245 

My concern here is that different config file systems, authored by different Spackers, use different conventions.  `config.yaml` uses lower-case names with dollar signs, possibly surrounded by curly braces.  Module configuration uses upper-case names with dollar signs.  There is talk about maybe just using curly braces, not dollar signs.

Whatever we decide... we should make sure that decision is implemented consistently across *all* Spack configuration files.

**Comment by tgamblin** [comment]
I agree!  At this point I think we're a little inconsistent, but do note that @scheibelp has been working on this in some of his recent PRs.  Another place where consistency is going to be important: there are a bunch of places in Spack where `packages.yaml`-like files are going to emerge.  Keeping the syntax of those things consistent is important.  @scheibelp has been working on making the configuration for generating symlink trees and module trees in #2168 consistent with `packages.yaml`.

I think post-0.10, we should revisit the variable stuff and settle on something.

**Comment by adamjstewart** [comment]
Are our config files still inconsistent?

**Comment by citibeth** [comment]
yes

**Comment by alalazo** [comment]
Can you be a bit more specific on what are the inconsistencies as of c13bc308db35928860a2d03a17f2fd432459d9ec ?
