### ISSUE TITLE
Document Locking in Spack

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2267]
@tgamblin wrote in #2189 

> You really should read the PRs about how locking is done in Spack, because it took me a long time to work out how to do that, and I think it's pretty good. On modern filesystems, it does work, with fcntl locks, for multiple users, with no special configuration. If you're skeptical, I'd encourage you to find a problem with the scheme. I don't think the solutions you're suggesting are in line with what Spack's audience is willing/able to set up.

Can this get documented?  Or collect a list of PRs from which relevant documentation could later be extracted?  I have exactly the same need elsewhere; can I just use `llnl/util/lock.py`?

**Comment by tgamblin** [comment]
Eventually in the dev guide.  For now:

- Relevant discussion in #1562.
- I also tried to [describe the approach to the fasteners developers](https://github.com/harlowja/fasteners/issues/26).  So far no response.
