### ISSUE TITLE
Spack fails to compile trilinos with intel compiler

### ISSUE THREAD

**Issue by ashkan2200** [spack/spack#2272]
Hi all,
I am trying to install Trilinos with intel 15.0.3 compiler but it fails with the error

    amesos/src/Amesos_Superludist.cpp(490): error: identifier "DOUBLE" is undefined
          DOUBLE
          ^
    
    amesos/src/Amesos_Superludist.cpp(499): error: identifier "EXTRA" is undefined
          EXTRA
          ^

I found [this git issue](https://github.com/trilinos/Trilinos/issues/195) which says something about the same issue. Is there an easy fix for this?

Note 1: I use a preinstalled compiler and `openmpi` in a cluster setting. This can't be changed since both `intel` compiler and `openmpi` have specially compiled for this cluster.

Note 2: installing `Lua` with intel compiler fails, I fixed the issue by installing `Lua` using `gcc` and setting it as default in `packages.yaml`

**Comment by davydden** [comment]
@ashkan2200 I think the best is to send this upstream to `trilinos-users@trilinos.org`. They are generally quick to reply and help. If you will find a solution or a patch, please update this issue.

**Comment by davydden** [comment]
@ashkan2200 btw, is it `superlu-dist@5.1.1` built with `intel` as well?

**Comment by davydden** [comment]
also, which version of trilinos are you building?

**Comment by ashkan2200** [comment]
Yes, 
everything except `Lua` is compiled with intel compiler. 
I am trying to compile `dealii` so everything needed for that is intalled. 

`Trilinos` version I try to install is `12.8.1` and the packages are 

    boost@1.62.0   
    hdf5@1.10.0-patch1
    hypre@2.11.1 
    metis@5.1.0
    mumps@5.0.2
    suite-sparse@4.5.3
    superlu-dist@5.1.1

**Comment by davydden** [comment]
i see... I am certainly very much interested in solving this, but I can't help much as I don't have intel compilers around... ;-(

**Comment by davydden** [comment]
The only workaround to get you going until you hear from Trilinos folks is to install `spack install dealii+mpi+trilinos ^trilinos~superlu-dist`. You could also add PR which modifies `trilinos` package to temporary thrown an error if someone tries to compile with `%intel` and `+superlu-dist`, something like
```
 if '+superlu-dist' in spec and spec.satisfies('%intel'):
     raise InstallError('Trilinos does not compile with Intel and superlu-dist!')
```
Either way, i think it's worth reporting this upstream so that it is hopefully fixed in the next release of `trilinos`.

@Rombur did you by any chance try compiling `dealii` in Spack with `intel`?

**Comment by ashkan2200** [comment]
Thanks for this. I'll try installing the way you said and report if I fail.
Meanwhile, I have submitted a report upstream and will post the answer when I get one.

**Comment by ashkan2200** [comment]
This is the response I got from Trilinos user group. I haven't tested it yet.

>   This is due to a SuperLU_Dist versioning problem. Note that as it is in the issue you refer, the mechanism we use to find which version of SuperLU-dist is used for configuration is somewhat shaky. We try and compile a small code with one version and see if it can compile at configure time. If it fails for any reason, we assume that version is not there. This is because, even if we allow it to pass at configure time, you will face the same issue later any way.

>   This shows up as a compile time error, but in truth it is something else manifesting as Trilinos error. Can you compile a small example  program with SuperLU-Dist with the same CMake variables you are providing Trilinos at configure time ?

**Comment by davydden** [comment]
i don't think it has to do with versions anyhow, i have `superlu-dist@5.1.1` and `trilinos@12.8.1` installed both on my mac (clang+gfortran) and Ubuntu16.04 (gcc5.4).  (you can mention this when you reply).

It could be though that there is something wrong with Superlu-dist or Trilinos's config when using `Intel` compilers.

I would rather investigate more the second reply:

> The most unreliable part of the configuration check comes down to linking errors.  Unfortunately it is difficult to do compilation-only checks in cmake, and given superlu_dist has a few other library/linking dependencies, the checks can sometimes fail due to linking.  You should be able to see whether this is the case in the output of the configuration check in CMakeFiles/CMakeError.log

p.s. for convenience of others, here is a thread: https://trilinos.org/pipermail/trilinos-users/2016-November/005715.html

**Comment by alalazo** [comment]
Closing as probably outdated, feel free to reopen if this is still an issue.
