### ISSUE TITLE
DOAP Records?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2282]
While digging around PyPI, I discovered DOAP records (Description of a Project).  Wondering if they would be any use to us in Spack:

https://github.com/edumbill/doap/wiki

 See, for example, at the bottom of the page:
https://pypi.python.org/pypi/matplotlib

**Comment by adamjstewart** [comment]
Very interesting. We could use these to automatically set the homepage and description for every Python package that gets created. With that, a single `spack create` could do everything needed for 95% of Python packages.

**Comment by citibeth** [comment]
We could also potentially create our own DOAP records for everything Spack
installs...

**Comment by adamjstewart** [comment]
We basically do with the `spec.yaml` and `package.py`. Do you mean this specific format, or is there something missing that you would like to keep track of?

**Comment by citibeth** [comment]
Yes, I mean this specific format.  Other things being equal, using existing
formats for something is often better than inventing your own.  Of course,
other things might not be equal here.

**Comment by alalazo** [comment]
Noted this in @1249
