### ISSUE TITLE
Does Spack hog a core?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2304]
I noticed when I run Spack that a `python` process is always using 100% CPU, even when it's spawning compilers.  Is Spack spin-waiting when it spawns subprocesses?  Or is it just being credited 100% because the things it spawned are busy?  If the former, is there another way to get the same effect without spin-waiting?
```
 5251 me  20   0  301876  85656    828 R 100.0  0.7   8:12.86 python                       
30194 me  20   0  257428 130076  10328 R 100.0  1.1   0:04.93 cc1plus                      
13944 me 20   0  158252   2692   1532 R   0.7  0.0   0:05.12 top                          
```

**Comment by alalazo** [comment]
> Is Spack spin-waiting when it spawns subprocesses? Or is it just being credited 100% because the things it spawned are busy?

My guess is that what you see is the process doing log redirection. See `log_output._spawn_writing_daemon` in module `llnl.util.tty.log`.

**Comment by eschnett** [comment]
If log redirection takes 100% CPU time, does this mean that this is the limiting factor for performance? In the sense that things would install faster without log redirection?
