### ISSUE TITLE
`depends_on(..., when="^python@:2")` does not work

### ISSUE THREAD

**Issue by krafczyk** [spack/spack#2310]
I'm creating a series of packages to get jupyter notebooks working in spack.

One such package is python tornado.

I've created this package and added the line:

`depends_on('py-backports_abc', when="^python@:3", type="nolink")`

among others.

I've created the package `py-backports_abc` as well. When I try to install py-tornado, I get the following baffling error message:

```
spack install py-tornado ^python@2.7.12
==> Error: py-tornado does not depend on py-backports_abc
```

I don't understand why spack is giving this error.

**Comment by davydden** [comment]
FYI, up-for-grabs related PRs which could save some time https://github.com/LLNL/spack/pull/2122 and https://github.com/LLNL/spack/pull/2128

**Comment by davydden** [comment]
```
depends_on('py-backports_abc', when="^python@:3", type="nolink")
```
have not seen that kind of usage of `when`, maybe it's not supported. @alalazo @tgamblin ?

**Comment by krafczyk** [comment]
My goal with this was to have a dependency which exists for python 2 but not for python 3.

**Comment by davydden** [comment]
It looks like this what you do should work, i found a few python packages which do
```
depends_on('py-ordereddict', when='^python@:2.6.999', type=nolink)
```
or
```
depends_on('py-configparser', when='^python@:3.3.999', type=nolink)
```

**Comment by adamjstewart** [comment]
I'm the one who added those dependencies, specifically for `py-flake8`, `py-enum34`, and `py-configparser`. It definitely used to work.

**Comment by adamjstewart** [comment]
But yeah, you should definitely start with #2122 and work from there. It was pretty close to completion. Just remove the changes to `py-scipy` as they are no longer relevant.

**Comment by davydden** [comment]
@krafczyk :  maybe create a work-in-progress PR where one could see those two packages and how they don't work? btw, both (!) are already here https://github.com/LLNL/spack/pull/2122 . So maybe you take those commits and work you things on top?

**Comment by krafczyk** [comment]
@davydden, I'll take a look at #2122 I didn't realize it existed. Clearly I didn't look hard enough.

**Comment by krafczyk** [comment]
@citibeth @davydden: I've used @citibeth's branch `features/numerous_py_packages` to continue my py-tornado work from #2310.

In my branch which you can find here: krafczyk@660fddb925e6dc8f1b6251a67fc8149d257e3d26, I've also added a few variants which can be turned on or off. The trouble I ran into seems to pop up when there are multiple variants which only exist for certain versions of python. In this case, for python 2, there are two modules which can optionally be included. I've included the relevant snippet below:

```
    variant('futures', default=True, description="recommended thread pool and for tornado.netutil.ThreadedResolver")
    variant('monotonic', default=True, description="enable support for a monotonic clock")
    variant('curl', default=True, description="for tornado.curl_httpclient")
    variant('twisted', default=True, description="for tornado.platform.twisted")
    
    # FIXME: Add additional dependencies if required.
    depends_on('py-setuptools', type='build')
    
    depends_on('py-singledispatch', when="^python@:2", type="nolink")
    depends_on('py-backports_abc', when="^python@:2", type="nolink")
    
    depends_on('py-futures', when="+futures^python@:2", type="nolink")
    depends_on('py-monotonic', when="+monotonic^python@:2", type="nolink")
    
    depends_on('py-pycurl', when="+curl", type='nolink')
    depends_on('py-twisted', when="+twisted", type="nolink")
```

The problem seems to occur when more than one of these variants which depend on a specific version of python exist at once. If I try to install py-tornado as above, I get the following error message:

```
spack install py-tornado ^python@2.7.12
==> Error: py-tornado does not depend on py-monotonic
```

Interestingly, if I try to build a version that depends on python 3, it works.

```
spack install py-tornado ^python@3.5.2~ucs4
==> Installing py-tornado
==> Installing py-pycurl
==> Installing python
```

To me, this indicates that at least the `^python` part of the `when` clause is working.
If I eliminate the `py-monotonic` variant and dependency, It works.

```
spack install py-monotonic ^python@2.7.12
==> Installing py-monotonic
==> Installing python
```

Any ideas on what is causing this dependency problem?

**Comment by citibeth** [comment]
Glad to know #2122 and #2128 are useful; please thank @scheibelp for his work on them.

This looks to me like a bug.  To make sure... can you try keeping the `depends_on()` stuff but remove the `when=` clauses?  Please make sure the simple case builds with Python2.

@adamjstewart Does `when="^python@:2"` work?  Or should he be using `when='^python@2:2.7'`?

PS: Thank you for putting in the effort to make this work with Python2 and Python3.

**Comment by scheibelp** [comment]
> please thank scheibelp for his work on them.

Er did you mean @jppelteret? I don't recall these

**Comment by krafczyk** [comment]
@citibeth I removed the variants and removed the `when` clauses, and py-tornado built just fine with all of it's dependencies.

**Comment by citibeth** [comment]
That's a good clue.  Can you try changing  `when="^python@:2"` to `when='^python@2:2.7'`?   Does that make any difference?

@tgamblin Do you know what's going on here?

One other thing I noticed.... it should be `type=nolink`, not `type="nolink"`.

**Comment by krafczyk** [comment]
@citibeth the change from `when="+monotonic^python@:2"` to `when='+monotonic^python@2:2.7'` makes no difference. I still get the error that py-tornado doesn't depend on py-monotonic.

**Comment by krafczyk** [comment]
I still suspect that the issue is not with the version part of the `when` clauses, but the variant part.

**Comment by citibeth** [comment]
Thanks.  It looks like a bug.  Hopefully @tgamblin will take a look.  But
that might not be until after SC '16.

In the meantime... why not just set it up to work for the version of Python
you want to use it with.

**Comment by davydden** [comment]
> Glad to know #2122 and #2128 are useful; please thank @scheibelp for his work on them.

for preliminary work credits certainly goes to @jppelteret .

**Comment by krafczyk** [comment]
For safe keeping, I've saved this work exposing this bug under the branch krafczyk@8ade5b29cd7e5f337caac6881060e05db442a8f4.

**Comment by davydden** [comment]
@krafczyk if you create a pull-request off your branch, it will be easier to discuss changes/problems, comment on code.

**Comment by jppelteret** [comment]
@krafczyk In addition to the before mentioned PRs, there's also #1297 that actually downloads and builds the Jupyter core packages and notebook as well.

**Comment by adamjstewart** [comment]
> One other thing I noticed.... it should be type=nolink, not type="nolink".

Both work.

**Comment by citibeth** [comment]
It looks like this bug is still around.  For example, try `spack spec py-pbr`.  @tgamblin ???

When it gets fixed, someone should grep for `enum34` to find places to fix up.  For example:
```
py-astroid/package.py:    depends_on('py-enum34@1.1.3:', when='^python@:3.3.99')
py-cryptography/package.py:    depends_on('py-enum34',             type=('build', 'run'), when='^python@:3.4')
py-enum34/package.py:    homepage = "https://pypi.python.org/pypi/enum34"
py-enum34/package.py:    url      = "https://pypi.io/packages/source/e/enum34/enum34-1.1.6.tar.gz"
py-flake8/package.py:    # depends_on('py-enum34', when='^python@:3.1', type=('build', 'run'))
py-flake8/package.py:    depends_on('py-enum34', type=('build', 'run'))
py-hypothesis/package.py:    depends_on('py-enum34', type=('build', 'run'), when='^python@:2')
py-llvmlite/package.py:    depends_on('py-enum34',     type=('build', 'run'), when='^python@:3.3.99')
py-pbr/package.py:    depends_on('py-enum34', type='build', when='^python@:3.3')
py-rasterio/package.py:    # Only use py-enum34 with Python2
py-rasterio/package.py:    depends_on('py-enum34', type='run', when='^python@:2.7')
py-traitlets/package.py:    # depends_on('py-enum34', when='^python@:3.3', type=('build', 'run'))
py-traitlets/package.py:    depends_on('py-enum34', type=('build', 'run'))
py-unittest2/package.py:    depends_on('py-enum34', when='^python@:3.3', type=('build', 'run'))
```
