### ISSUE TITLE
Spack doesn't treat pypi.io links properly

### ISSUE THREAD

**Issue by krafczyk** [spack/spack#2335]
While attempting to use pypi.io links as suggested here #1939, I've discovered that while spack is able to download these links when using spack install or spack create, spack checksum returns the following error:

```
spack checksum py-matplotlib
==> Error: Could not fetch any versions for py-matplotlib
```

**Comment by krafczyk** [comment]
It seems this is because the page https://pypi.io/packages/source/m/matplotlib doesn't exist. That is, pypi.io doesn't index packages in the way spack expects.

**Comment by krafczyk** [comment]
looking for a specific version fails as well.

```
spack checksum py-matplotlib 1.5.2
==> Found 1 versions of py-matplotlib
  1.5.2     https://pypi.io/packages/source/m/matplotlib/matplotlib-1.5.2.tar.gz
How many would you like to checksum? (default is 5, q to abort) 1
==> Downloading...
==> Fetching https://pypi.io/packages/source/m/matplotlib/matplotlib-1.5.2.tar.gz
==> Something failed on https://pypi.io/packages/source/m/matplotlib/matplotlib-1.5.2.tar.gz, skipping.
    (cannot concatenate 'str' and 'list' objects)
==> Error: Could not fetch any versions for py-matplotlib
```

**Comment by krafczyk** [comment]
The post directly above this one seems to have been solved since I merged the most recent develop changes. It's also possible that the internet problem I've been having has been interfering as well.

That said, the root issue with `spack checksum` still remains.

**Comment by citibeth** [comment]
See #2281.  If we head in that direction, then additional hooks could be provided to properly list and checksum available versions in PyPI.
