### ISSUE TITLE
Verbose CMake Builds Bad for `spack setup`

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2339]
I noticed the change that makes VERBOSE builds standard for CMake: @KineticTheory  #1988 

I can see the logic behind this when writing to Spack log files.  However, when using `spack setup`, the default CMake behavior is more preferable.  We need a way to do non-verbose builds in `spack setup`.  Any ideas of how...?

**Comment by tgamblin** [comment]
Why is this bad for `spack setup`

**Comment by citibeth** [comment]
Non-verbose builds is a feature of CMake --- feature, in the sense that
people went to some effort to make it happen, and set it up as the
default.  Enforcing verbose builds breaks that feature.  I already have a
fix to this Issue, will post a PR shortly.

**Comment by adamjstewart** [comment]
@citibeth is this still an issue?
