### ISSUE TITLE
checksum support related to spack mirrors

### ISSUE THREAD

**Issue by cyrush** [spack/spack#2357]
Note: We are using an old version of spack, so I am interested in learning about the current state of mirrors in the context of this issue.

We are using a mirror for the TPL source tarballs needed for our project. We had a package that did not change versions but did change checksums. (Lets not dwell on this - obviously it's not ideal but it happened and it was out of our control).

So, we updated our package.py with the new checksum.  

Each time we build we attempt to update our mirror.  When doing so, spack found the old tarball (recall the version number didn't change) and moved on.  

Then during the build phase the checksum verify failed. The only way to resolve this was to manually  remove the tarball. 

Does spack now use checksums during the mirroring process? If not, is it something we can discuss?

**Comment by scheibelp** [comment]
Looking at spack.mirror.add_single_spec it appears that the mirror creation logic assumes the checksum is good if the path already exists. It shouldn't be hard to actually check this and replace the file if the checksum is bad. It sounds like you found a workaround and that you don't have to do this a lot so I'll aim to propose a fix by next week. If this is in fact causing you a lot of trouble let me know and I can create a PR sooner

**Comment by cyrush** [comment]
Thanks! No urgent timeframe -- but it would be a great feature to add!

**Comment by alalazo** [comment]
Is this a feature we still want? As far as I remember I stumbled on something like this only once in 5 years (a NetCDF release that was updated without bumping the patch number).

**Comment by becker33** [comment]
Spack mirrors are now content-addressed for source code files, while supporting the old format for backwards compatibility. I think we just missed closing this when the PR was merged.
