### ISSUE TITLE
Compiler wrappers in spack, include path order and external packages from /usr

### ISSUE THREAD

**Issue by pramodk** [spack/spack#2374]
I was building application with spack and it was failing at runtime. The issue was following:

Suppose I have a package (with `non-standard` build process) and that invokes following compilation command from some wrapper scripts: 

```bash
mpicc -I/gpfs/some-path/hdf5-1.8.10  xyz.c
```
As `hdf5` include path is added at the beginning, the expectation is that compiler will prefer that path for header files search.

Now this package has dependency with `python` and I thought I should use system version:

```
   python:
       paths:
           python@2.6.6: /usr
       .....
```

When I was installing this application with `spack install -v`, I was seeing compilation commands as : 
```bash
mpicc -I/gpfs/some-path/hdf5-1.8.10  xyz.c
```
This looks fine. But I didn't understand **why** `hdf5-1.8.5` headers were used (which is installed user `/usr`).

Then I started looking into compiler wrappers, I see following:

```bash
# Read spack dependencies from the path environment variable
IFS=':' read -ra deps <<< "$SPACK_DEPENDENCIES"
for dep in "${deps[@]}"; do
   # Prepend include directories
   if [[ -d $dep/include ]]; then
       if [[ $mode == cpp || $mode == cc || $mode == as || $mode == ccld ]]; then
           args=("-I$dep/include" "${args[@]}")
       fi
   fi
```
So spack look at dependencies and **prepends** the header paths! With debug output I see the compilation command becomes:

```bash
mpicc -I/usr/include -I/gpfs/some-path/hdf5-1.8.10 xyz.c
```
Now curious about : 
* why the include paths are **prepended** ?
* if we explicitly specify include path using `-I`, we can't guarantee that order?

I agree this is a particular case using `hdf5` which has this header version dependency. It's clear to me now what's going on and how to workaround. But wonder if  users will be easily identify issues in such cases.

**Comment by alalazo** [comment]
I think order of include directories and similar semantic changed a few times since 2016. Closing as outdated.
