### ISSUE TITLE
Compute-Specific Architecture Chains

### ISSUE THREAD

**Issue by ax3l** [spack/spack#2379]
@alalazo I asked you that question at SC16 but did honestly forget how to exactly do the workflow or if it is already implemented (latest docs say no).

In our scenario, we have a heterogeneous cluster with 3 queues of individual compute hardware:
- login nodes (ideally as compile nodes) with AMD Opteron 6376 (gcc: `bdver2`)
- compute 1: AMD Opteron 6276 (gcc: `bdver1`)
- compute 2: Intel Xeon E5-2609 (gcc: `corei7-avx`) + K20 (nvcc: `sm_35`)
- compute 3: intel Xeon E5-2630 (gcc: `core-avx2`) + K80 (nvcc: `sm_37`)

We see dramatic performance increase in our [CPU code(s)](https://github.com/ComputationalRadiationPhysics/alpaka) if we compile on-node (interactively) with `-march=native` (queue-specific architecture flags see above).

Will there be a way to configure user-specific architectures beyond the rather coarse `x86_64` that can honor, e.g. `-march` correctly for all (cross-compile) builds, so we can generate a perfectly tailored set of vector instructions in our binaries for each of those queues?

Ideally, one might want to take GPU architectures (`sm_XY`) directly into account here, too.

CCing @tgamblin

**Comment by alalazo** [comment]
The version of `spack` we use in production is a rather old fork from last May and I still need to have a look how to do what you ask on `LLNL/develop`.

That said, what I would try to do would be to modify the code in:
```console
lib/spack/spack/platforms/linux.py
```
and extend / customize target detection.

**Comment by ax3l** [comment]
Sounds great. So one just implements a class for each queue/architecture when setting up spack for a HPC cluster.

**Comment by tgamblin** [comment]
FYI, @becker33  is working on automatically detecting compute targets for x86 and power (arm tbd).  We'll also still allow using the generic x86_64 target, but we'll probably default to something more specific like `haswell` or `power8le`

**Comment by ax3l** [comment]
Hi there, it looks like this feature already evolved! :)

I am right now reading the docs in `lib/spack/spack/architecture.py`. (Btw, that file's docstring does not explain if the *frontend* or if the *backend* refers to the "compute node", this might confuse readers.)

`linux.py` already adds `x86_64` ad `ppc64le` as *targets*, but I can't find where this is translated into, e.g., an `-march` naming for the compiler or where to add a target for the co-processors / accelerators / GPUs.

In the general front-end / back-end `Platform` members it looks to me like only one backend per platform is possible right now, so I would implement a `Platform` for each queue? On the other hand, `platforms/cray.py` seems to handle an arbitrary number of CPU targets ... but then again just one backend.

Is it planned to just add a general list of targets to the `linux.py` via the same `targets.yaml` as in cray and maybe even change the default "platform-os-target tuple" there? As it looks to me, that seems flexible since one could just name the `Target` (in `add_target`) like the queue on a cluster (if I got this right). Maybe I also just got this wrong and it's the `Platform` class that one would name after the queue.

Do you have experience where one could add the `compute architecture` of a GPU (and how do we pass it to the device compiler, nvcc or clang, in a generic way)? Maybe the new CUDA-as-a-language support in [CMake 3.8](https://cmake.org/cmake/help/v3.8/release/3.8.html) helps here, although it only supports `nvcc` yet and seems not to expose [new variables](https://cmake.org/cmake/help/v3.8/manual/cmake-variables.7.html) for the architecture.

**Comment by ax3l** [comment]
:dancer:
