### ISSUE TITLE
add NUnit support to --log-format

### ISSUE THREAD

**Issue by davydden** [spack/spack#2432]
from [this post](https://github.com/LLNL/spack/pull/2112#issuecomment-256063109) by @tgamblin 

> So, I could set up a CDash instance in EC2 so we could at least start reporting test results. It apparently has some support NUnit format so we could start by adding a few fields to the current test format. What do people think of that?

and later

> @alalazo: do you want this merged now to update NUnit later,...

I don't know about possible options  (I only have some experience with CDash for C++ project with CMake), but my understanding from the two comments above is that one `NUnit` format is supported, we could start collecting build logs in CDash.

p.s. relevant to https://github.com/LLNL/spack/issues/2014

**Comment by alalazo** [comment]
#6977 started using `jinja2` for report generation. Adding a new format should be simpler, if anybody wants to give it a try.

**Comment by alalazo** [comment]
Closing as it's a while we have CDash support in Spack.
