### ISSUE TITLE
Help re: install failure in new CMakePackage-based package that exits with status=2

### ISSUE THREAD

**Issue by hartzell** [spack/spack#2439]
I'm putting together a package for the open source [shiny server](https://github.com/rstudio/shiny-server).  It subclasses CMakePackage, sets a custom build dir and otherwise seems unremarkable, though there's still more to be done.

The install step fails thusly:

```
-- Installing: /rss/spack-20161101/opt/spack/linux-centos7-x86_64/gcc-5.4.0/shiny-server-2016-11-04-iwyadliuj7yuyoxpu5dlgneaxq3ydlkv/shiny-server/manual.test/test-serialized.js
-- Installing: /rss/spack-20161101/opt/spack/linux-centos7-x86_64/gcc-5.4.0/shiny-server-2016-11-04-iwyadliuj7yuyoxpu5dlgneaxq3ydlkv/shiny-server/manual.test/loadtest.js
-- Installing: /rss/spack-20161101/opt/spack/linux-centos7-x86_64/gcc-5.4.0/shiny-server-2016-11-04-iwyadliuj7yuyoxpu5dlgneaxq3ydlkv/shiny-server/manual.test/test-worker-registry.js
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'install'
/rss/spack-20161101/lib/spack/spack/build_systems/cmake.py:118, in install:
     115      def install(self, spec, prefix):
     116          """...and the final `make install` after cmake"""
     117          with working_dir(self.build_directory()):
  >> 118              inspect.getmodule(self).make('install')

See build log for details:
  /tmp/hartzelg/spack-stage/spack-stage-fpoltW/shiny-server/spack-build.out
```

If I check the spack-build.out file it simply dead-ends, its last line is the `-- Installing ... test-worker-registry.js` line in the console output.  The spack-build.out file is about 3700 lines, but I can share it if it's useful.  Reading through it I don't see any obvious failures upstream but....

[Here is a Gist](https://gist.github.com/hartzell/e04bb728f6c51443c2a69fc33fe68845) of the spack-build.out file after running it through `grep -v Installing`.

I'm not a cmake wiz and the google doesn't have any obvious hints what might make the install step return a status == 2.

Does it ring any bells?

**Comment by alalazo** [comment]
@hartzell I'm trying to clean up the backlog of issues. Closing this one since you ended up adding the package :slightly_smiling_face: :
```console
$ spack blame shiny-server
LAST_COMMIT  LINES  %      AUTHOR           EMAIL
a month ago  1      2.4    Todd Gamblin     <tgamblin@llnl.gov>
2 years ago  2      4.9    Adam J. Stewart  <ajstewart426@gmail.com>
2 years ago  38     92.7   George Hartzell  <hartzell@alerce.com>
                                            
a month ago  41     100.0   
```
Feel free to reopen if I missed something.
