### ISSUE TITLE
Instructions on setting up environment-modules need update for macOS

### ISSUE THREAD

**Issue by TomasPuverle** [spack/spack#2440]
I noticed that the following example in "Getting started" no longer appears to work:
```
TMP=`tempfile`
echo >$TMP
MODULE_HOME=`spack location --install-dir environment-modules`
MODULE_VERSION=`ls -1 $MODULE_HOME/Modules | head -1`
${MODULE_HOME}/Modules/${MODULE_VERSION}/bin/add.modules <$TMP
cp .bashrc $TMP
echo "MODULE_VERSION=${MODULE_VERSION}" > .bashrc
cat $TMP >>.bashrc
```
I think the problem is (at least) two fold:
1) I don't think tempfile is universaly supported 
2) I installed environment-modules using spack and the MODULE_VERSION variable just expands to 'bin', leading to a path of '..../Modules/bin/bin/add.modules', which doesn't exist. 

Thank you,

Tom

**Comment by adamjstewart** [comment]
> I don't think tempfile is universaly supported

You're right. `tempfile` doesn't exist on my macOS or on CentOS 6. From the `tempfile` manpage: "`tempfile` is deprecated; you should use `mktemp(1)` instead."

**Comment by hartzell** [comment]
At some point in my past I cargo-culted a bit of code to work around platform variations in how mktemp behaved.  [This is most likely](http://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x) where I cut-n-pasted it from (didn't write it down at the time but it's a perfect match...).

```
# platform agnostic mktemp call...
tools=$(mktemp -d 2>/dev/null || mktemp -d -t '/tmp/foo-bar.XXXXX')
```
