### ISSUE TITLE
Failure to install RHEL6 hpctoolkit

### ISSUE THREAD

**Issue by bathmatt** [spack/spack#2447]
I get an error in the install phase.  Log file attached
[speck.zip](https://github.com/LLNL/spack/files/622925/speck.zip)

**Comment by alalazo** [comment]
Closing, but couldn't help noticing that you wrote [speck](https://it.wikipedia.org/wiki/Speck_dell%27Alto_Adige_IGP) instead of `spec`.  As you'll see from the link the subject is quite more interesting than package management :smile:
