### ISSUE TITLE
Checklist for package file submission

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2461]
I find myself saying the same thing over and over again.  So here's a list of requirements for `package.py` submissions that should be added to our documentation (in no particular order):

1. At least one numeric (checksummable) version must be supplied.

2. All explicit versions in `depends_on()` statements must also be for checksummable versions.

3. If the package builds binaries... please check them with `ldd` to make sure there are no "hidden" dependencies in your package that are not listed as a `depends_on()` in `package.py`.  if you find any, please add them.

4. Does this package build static libraries?  If so, make sure there is a `+pic` variant, turned on by default, that adds the `-fPIC` flag.  (More is needed on compiler-independent ways to do this).  This allows it to be linked with shared libraries higher up the Spack DAG.

5. Does upstream provide a way to build shared or static libraries?  If so, add `+shared` and `+static` variants as appropriate.  By default, it should build a shared library (and may or may not also build static in that).

6. Does the build download stuff during the `install()` phase?  If so, please re-work things so it does not.  Usually this happens because the upstream authors wanted to auto-install dependencies.  Usually you can disable it by supplying command line options to the build that tell it where those dependencies have already been built.

7. Is your package a Python package?  If so, please indicate whether it's Python2-only (`depends_on('python@2:2.7')`), Python3-only (`depends_on('python@3:')`) or both (nothing needed).  This is in addition to the `extends('python')` declaration you've used.  (You may need a more complex version spec for `python` if you know that your package doesn't work for certain Python versions).  (Soon: please subclass from `PythonPackage`).

8. Is your package built with CMake?  If so, subclass from `CMakePackage`.

9. Is there a copyright notice at the top?

**Comment by citibeth** [comment]
See #2375 for info on adding `-fPIC` flag to compilers.

**Comment by citibeth** [comment]
See #2457 for example on using `CMakePackage`.

**Comment by tgamblin** [comment]
I think this stuff belongs in a checklist in `CONTRIBUTING.md` (then it will appear at the top of every PR as [documented here](https://github.com/blog/1184-contributing-guidelines)).

We currently have a [contributor guide](http://spack.readthedocs.io/en/latest/contribution_guide.html), but it's a bit on the long side.  I think we should make a short and sweet `CONTRIBUTING.md` file that links to the longer contribution guide.

**Comment by alalazo** [comment]
It seems to me this was fixed in #6203
