### ISSUE TITLE
Developer and Download support for Python packages.

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2462]
@adamjstewart 

The innovations in #2460 need to be factored out into a general Spack `PythonPackage` (alongside `CMakePackage`, `AutotoolsPackage`, etc).

While we're at it... we should also see a `PyPIPackage` (subclassing `PythonPackage`) along the lines of #2281

**Comment by adamjstewart** [comment]
We also need to create an `RPackage` for `r-*` files, which tend to be much more uniform (almost identical).

**Comment by citibeth** [comment]
Actually, I'd like a `spack setup` for Python, not just a `spack diy`.  Running Spack can be sloowwww.

**Comment by adamjstewart** [comment]
Something that should be added to the `PythonPackage` class is a test that tries to import the installed package. See #1305 for details.

**Comment by alalazo** [comment]
@adamjstewart Is there something missing from `PythonPackage` before we can close this?

**Comment by adamjstewart** [comment]
Nope, I think everything mentioned here has been implemented in `PythonPackage` now. I'm surprised this hasn't been closed yet.
