### ISSUE TITLE
x11 fails to build on macOS due to excessively long argument list

### ISSUE THREAD

**Issue by davydden** [spack/spack#2484]
`libx11` fails to build on macOS due to excessively long argument list
```
checking if /Users/davydden/spack/lib/spack/env/cpp requires -undef... cpp: error: can't exec '/Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cpp' (errno=Argument list too long)
/Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cpp: line 362: /usr/bin/cpp: Argument list too long
/Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cpp: line 362: /usr/bin/cpp: Undefined error: 0
/Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cpp: line 362: /usr/bin/cpp: Argument list too long
/Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cpp: line 362: /usr/bin/cpp: Undefined error: 0
configure: error: /Users/davydden/spack/lib/spack/env/cpp defines unix with or without -undef.  I don't know what to do.
```

**Comment by davydden** [comment]
@mathstuf @adamjstewart @alalazo :  anyone knows a workaround cut-down the length? 

p.s. related to https://github.com/LLNL/spack/pull/1832

**Comment by mathstuf** [comment]
Response files should help, but that's more on the build system of libx11 than spack IMO.

**Comment by davydden** [comment]
> Response files

what is that?

**Comment by mathstuf** [comment]
A file containing arguments to the command like. Depending on the tool, it can be one per line or a string which is parsed as arguments (usually Windows behavior). It is usually referenced via `@extra_args.rsp` from the command line.

**Comment by tgamblin** [comment]
@mathstuf: how well does that work across compilers?

@davydden: Are all the includes and args needed?  Could we do something like we did for transitive RPATHs?

**Comment by mathstuf** [comment]
Generally, it is `@foo.rsp`, but some compilers are different (`armcc` is different at least).

**Comment by davydden** [comment]
@tgamblin I don't think I understand your question, but my understanding that using mock up XCode in Spack (which leads to `/Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cpp`) makes config system of `X11` unhappy. If you look at `x11`, there are no arguments provided to the config but `prefix`:
```
configure('--prefix={0}'.format(prefix))
```

**Comment by adamjstewart** [comment]
This seems to have been fixed at some point. I'm able to successfully installs libx11 1.6.7 on macOS 10.15.6 with Apple Clang 11.0.3.
