### ISSUE TITLE
Proposal: Dummy Variants

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2499]
This is in reponse to #2494 and others.

Spack packages get hash codes based on the spec used to install them.  The implicit assumption is that if two install directories have the same spec, then they will have the same software inside them.  This assumption breaks down for packages that are really installers for a suite of packages.  For example:
  a) `luarocks`, `pip`, etc --- these install stuff later on, thus changing their contents
  b) Similar thing for X11 fonts?
  c) `texlive` --- this installer makes no guarantees or claims about the versions it is installing.  You just get the "latest available version" of stuff.  And like `luarocks`, the user might later change the installation.

Spack can install these installers, but they do break the assumptions of the meaning of a hash.  One partial fix would be to make sure that each installation of an installer package has a unique hash (even if it's installed with the same variants and versions as another installed version).  We could do that pretty easily by adding a "dummy" string-valued variant to the package in question.  By setting this variant, the user could install multiple meta-installers.  Management of them would now be up to the user and no longer under Spack control --- but that's the case anyway.

So... this proposal seems to be to simply add an extra dummy variant to packages that are actually installers (`luarocks`, `pip`, `texlive`, etc).

**Comment by TomasPuverle** [comment]
Interestingly, I was about to make a similar topic; What I wanted to suggest is to nuance the "variant" notion into "variants" and "features".  I've come across similar issues on the mailing list to do with too much rebuilding; and in the case of e.g. libraries which have many subcomponents, having them distinguished by variant I believe is a waste.

The difference, at least from a high level, is that a variant introduced "incompatibility", and has to be matched exactly.  A feature, on the other hand, doesn't; it only needs to obey a subset relation.  So boost+regex (where +regex is now a feature, not a variant) can be satisfied by any install for which the feature was enabled.

**Comment by adamjstewart** [comment]
@TomasPuverle You might want to take a look at #2386. @alalazo is adding better support for mutually exclusive variants.

**Comment by citibeth** [comment]
> So boost+regex (where +regex is now a feature, not a variant) can be
satisfied by any install for which the feature was enabled.
I believe that's already the way it works.

**Comment by tgamblin** [comment]
> We could do that pretty easily by adding a "dummy" string-valued variant to the package in question. By setting this variant, the user could install multiple meta-installers.

I think what you're proposing is that we allow different installs to be named.  So I could install one meta-installer for one environment and another for some other environment like:

    spack install npm name=webapp_stack_1
    spack install npm name=webapp_stack_2

And install packages in each of those separately.  Only difference being that the user picks the name.  On its face this seems reasonable to me but not something near-term.  If someone has an immediate use case, they can feel free to try this.  Or maybe we just reserve a `name` variant for anyone to use on any package -- I don't see why this applies only to meta-installers.

One other way to do this would be to just add a version suffix, kind of like you can already do with `spack diy package@4.0-special-version`.

**Comment by tgamblin** [comment]
@TomasPuverle: That is in fact how it works, logically.  `depends_on('foo+bar')` will be satisfied by *any* foo that has `+bar`, regardless of other variant options.

However you may have run into the issue that we concretize first without looking at what is installed, and then reuse by exact hash.  There are lots of discussions on that, and the plan is to try to make Spack more aggressively reuse things.

**Comment by citibeth** [comment]
> On its face this seems reasonable to me but not something near-term. If
> someone has an immediate use case, they can feel free to try this.
>
As I envisioned it, packagers would just add a `name` variant to the few
packages where it makes sense; no need to touch core Spack.

> One other way to do this would be to just add a version suffix, kind of
> like you can already do with spack diy package@4.0-special-version.
>

...but can you do this with `spack install`, not `spack diy`?

**Comment by tgamblin** [comment]
>> One other way to do this would be to just add a version suffix, kind of
 like you can already do with spack diy ***@***.***

> ...but can you do this with `spack install`, not `spack diy`?

You can't.  `diy` actually just trusts you entirely about the version.  I actually think adding a name variant is clearer.

**Comment by TomasPuverle** [comment]
Clearly, due to a combination of my preconceptions, and the observed behaviour I arrived at an incorrect conclusion.  Does the manual say anything about this "supersetting"? I have no recollection of it.  Up until the comments above, I was under the impression that a variant implied a completely incompatible version.   
But if that's the case, I don't really understand - are you saying that in general, if I build, say, only boost+debug, because I request just boost, the intended bahaviour of spack is to link with boost+debug?  Your description above seems to imply that, and I find that behaviour worrying, and wrong.

**Comment by TomasPuverle** [comment]
I've seen some of those, and perhaps that's where some of my confusion 
stems from.  Would the abstract repo ordering I suggested perhaps help 
address some of these issues?

**Comment by alalazo** [comment]
Closing as stale. Feel free to reopen if you want to continue with the discussion.
