### ISSUE TITLE
Satisfy Python build dependency with Spack's Python

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2504]
@tgamblin @adamjstewart @alalazo @davydden 

The proposal is that when Spack encounters `depends_on('python@xxx', type='build')`, that it will satisfy that dependency with the Python being used to run Spack (if the version of that Python matches the requested spec), rather than a Spack-built Python.  This will eliminate some circular dependency problems we've been having, and also eliminate the need to build a whole Python, just as a build dependency for other packages.

I'd like to know... is this something we can agree on to get implemented?  I would only work on it if we know it's something we want.

**Comment by adamjstewart** [comment]
I would be interested in a solution to the circular dependency problems I've been seeing and the Python 2 vs. 3 conflicts you've encountered. I think this part can be a little bit complicated though:

> it will satisfy that dependency with the Python being used to run Spack (if the version of that Python matches the requested spec), rather than a Spack-built Python

I have no idea how you plan to do that, but I would be interested to see what you come up with. In all honesty, I'm inclined to just remove the build dependencies and depend on system installations being picked up for things like Python and Perl. In the long run, I think getting Spack to understand that `python+tk` --> `libxcb` --> `python~tk` is ok is a more versatile solution, but I'm not sure when @tgamblin plans on allowing multiple copies of a package in the concretizer. I've also encountered this problem in other packages: `cmake+jsoncpp` --> `jsoncpp` --> `cmake~jsoncpp`, so your proposed hack wouldn't solve _all_ of our problems, just most.

**Comment by citibeth** [comment]
> I have no idea how you plan to do that

Using `sys.executable` and `sys.version`.  If `sys.version` works out, set `spec['python'].prefix` to that based on `sys.executable`.  (Actually... the `python` package should export the full pathname of the Python interpreter, like we do with LAPACK).

> In all honesty, I'm inclined to just remove the build dependencies and depend on system installations being picked up for things like Python and Perl.

That would have a similar effect and be less effort.  Or... you can just put `/usr/bin/python` and `/usr/bin/perl` in your `packages.yaml`.  Maybe that's what we should do, rather than inventing new machinery... auto-detect system versions of these things and put them in default `packages.yaml` files.

> I've also encountered this problem in other packages: cmake+jsoncpp --> jsoncpp --> cmake~jsoncpp, so your proposed hack wouldn't solve all of our problems, just most.

CMake is trickier because there are so many versions of it.  I don't think we can ASSUME that the system-supplied CMake will work.  For that, maybe we create two CMake packages.  `basic-cmake` installes CMake without any variants --- in this configuration, we know things will work.  `fancy-cmake` allows for variants, some of which ultimately depend on `basic-cmake`.

**Comment by tgamblin** [comment]
We're planning on addressing this and other concretizer issues in the coming year.  I think in the interim though, the build deps are useful because they allow you to build in multiple stages.   I believe you can build the chain you mentioned above incrementally in two steps -- just not all at once.  That's not really a solution, but at least it is a workaorund.  It is sad that a human currently has to figure that out.

**Comment by citibeth** [comment]
@tgamblin Even if we can do the theoretically correct solution, do we want to force users to build Python as a build dep, even though a perfectly good Python is already running on their system?  I believe this is the kind of thing that could turn off users.  (It's a BIG criticism of MacPorts).

**Comment by davydden** [comment]
> Even if we can do the theoretically correct solution, do we want to force users to build Python as a build dep, even though a perfectly good Python is already running on their system?

users can always setup external python in `packages.yaml`.

**Comment by adamjstewart** [comment]
> users can always setup external python in `packages.yaml`.

Users _can_, but as a pretty heavy Spack user, I _still_ don't really understand how to add external packages. All of this "`buildable=False`/fake path/fake `@system` version/version must be specified in spec and again separately" nonsense make that a real hurdle. A lot of users using this feature are just trying desperately to get Spack not to install duplicates of the same package. I think this can be evidenced by the number of Issues that have been filed relating to using external packages. Either something is majorly broken, or it is just too damn confusing.

In the long run, I think I would like to start relying heavily on system packages just to reduce the number of builds and duplicate installations until the spec-changing problems are "hashed" out (pun intended). Maybe I should just suck it up and figure out how to add external packages properly. I was hoping for an automatic way of doing this, and @tgamblin alluded to the possibility, but I'm not sure where it is on the roadmap.

**Comment by citibeth** [comment]
I've made some issues where I sketched out some automated ways.  The
problem is, it will take a lot of work to translate the output of `yum` to
Spack packages --- and will have to be done separately for each OS.

**Comment by davydden** [comment]
> All of this "buildable=False/fake path/fake @system version/version must be specified in spec and again separately" nonsense make that a real hurdle

IMHO the only hurdle is `buildable=False`, otherwise something like this
```
packages:
  openmpi:
    version: [1.8.8]
    paths:
      openmpi@1.8.8%gcc@6.2.0: /opt/openmpi-1.8.8
    buildable: False
```
makes perfect sense to me in case of `openmpi`.

> I think I would like to start relying heavily on system packages

i would not do that, otherwise Spack will quickly become a Homebrew which relise on a great number of system packages on macOS, and Linuxbrew which has hard time knowing what is actually needed. I very much like the fact that everything needed for the build is specified.

**Comment by adamjstewart** [comment]
> IMHO the only hurdle is `buildable=False`, otherwise something like this
> ```yaml
> packages:
>   openmpi:
>     version: [1.8.8]
>     paths:
>       openmpi@1.8.8%gcc@6.2.0: /opt/openmpi-1.8.8
>     buildable: False
> ```
> makes perfect sense to me in case of `openmp`i.

It makes perfect sense to you that specifying `openmpi@1.8.8` causes Spack to ignore your package, but specifying `openmpi@1.8.8` **and** `version: [1.8.8]` works? We have gotten an awful lot of issues with confused users over this. I'm not the only one who finds this complicated.

**Comment by citibeth** [comment]
I agree with @adamjstewart this is poor UI design.  In the example above,
`openmpi` is repeated 3 times and `1.1.8` another 3 times.

> i would not do that

I believe Adam was saying he wants to PERSONALLY rely on system packages,
not remove the good features of Spack that allow it to build its own
packages if needed.

**Comment by davydden** [comment]
> It makes perfect sense to you that specifying openmpi@1.8.8 causes Spack to ignore your package, but specifying openmpi@1.8.8 and version: [1.8.8] works?

oh, but this is a different issue. I agree that this is wrong and should be fixed. I am just say that external packages are not evil per-se, something just can be improved for sure.

**Comment by davydden** [comment]
> I believe Adam was saying he wants to PERSONALLY rely on system packages,
not remove the good features of Spack that allow it to build its own
packages if needed.

i must have misunderstood. Let's hope https://github.com/LLNL/spack/pull/2507 will make life easier.

**Comment by mplegendre** [comment]
As a note, that "version [1.8.8]" isn't required when specifying externals. That's telling Spack that it should prefer openmpi 1.8.8 over other versions when concretizing.

But that config just lists one external openmpi, so there's not going to be other versions.

**Comment by adamjstewart** [comment]
Is this still something worth considering? Users can now run `spack external find python` to automatically add Python to their `packages.yaml`. The new concretizer @tgamblin is working on should resolve a lot of the circular dependency issues mentioned above. Other than that, I don't see a good reason to use the instance of Python that is running Spack as a dependency.

**Comment by adamjstewart** [comment]
I think the discussion on this issue has died out. Let's close this for now. We can reopen if this is still something we want to support.
