### ISSUE TITLE
Mixed-case variants?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2547]
Now that we've made all packages lower-case, what are peoples' opinions on variants?  Should we have `mypackage+X` or `mypackage+x`?

**Comment by adamjstewart** [comment]
I vote for lowercase.

**Comment by davydden** [comment]
same here,  lowercase

**Comment by citibeth** [comment]
Lower case it is... now someone needs to submit a PR.

**Comment by citibeth** [comment]
Now that package names are all lowercase... a bit of grepping, and I found only a few non-lowercase variants:
```
EMSHELL, default=False,
FORKER, default=False,
LURM, default=False,
X
YDRA, default=False,
```
I'm 95% certain that is all; @adamjstewart would it be possible to write a test to check for non-lowercase variants?  This would allow the last 5% to be found once other changes are made...

How much interest is there in seeing this conversion done soon?

**Comment by adamjstewart** [comment]
It wouldn't be hard, but I'm no expert at writing tests.

**Comment by citibeth** [comment]
I meant, something along the lines of the check you wrote for lowercase
package names.

**Comment by adamjstewart** [comment]
I didn't write https://github.com/LLNL/spack/pull/2475/commits/0ce270033a36082c758368a9552bc146e1bc1dfe, @tgamblin did. @tgamblin, if @citibeth or I create a PR to make sure all variants are lowercase and underscored, can you write a corresponding test?

**Comment by alalazo** [comment]
Do we still want this? Or are we fine with having a few exceptions, like `+X`?

**Comment by tgamblin** [comment]
We settled unofficially on lowercase, preferring no spaces, then underscores if needed. We could gradually change holdouts like X, but I think we can close this.
