### ISSUE TITLE
Add -j support to diy

### ISSUE THREAD

**Issue by krafczyk** [spack/spack#2573]
`-j` and other install options should be available when using `spack diy`.

**Comment by citibeth** [comment]
What does `-j` do?

**Comment by krafczyk** [comment]
It allows parallel builds with a specific number of threads. This is especially useful when a diy package requires a bunch of prerequisites which all need to be compiled.

Basically, I feel that `spack diy` should behave the same way as `spack install` and take the same arguments to do the same thing. As is, `spack diy` builds packages in 'verbose' mode automatically among other things such as the fact that it doesn't listen to `-j` like I mentioned above.

**Comment by citibeth** [comment]
Thank you.  In the past, command line args have been inconsistent between Spack commands because someone added it to one command and neglected to add the same arg to others.  This is most likely what's going on here.  A `git blame` on the lines in `spack install` that implement the `-j` flag might be telling in this respect.

Does anyone know of any reason that `-j` should NOT be available for `spack diy`?

As for the verbose mode... that's something probably worth discussing further.

**Comment by citibeth** [comment]
Thank you for the contribution over at github/citibeth.  I'm now trying to
get the unit tests of the overall PR to work...

**Comment by alalazo** [comment]
This has been solved (now the command is called `dev-build`):
```
$ spack dev-build -h
usage: spack dev-build [-hinq] [-j JOBS] [-d SOURCE_PATH] [--keep-prefix]
                       [--skip-patch] [-u UNTIL] [--clean | --dirty]
                       ...

developer build: build from code in current working directory

positional arguments:
  spec                  specs to use for install. must contain package AND version

optional arguments:
  -h, --help            show this help message and exit
  -j JOBS, --jobs JOBS  explicitly set number of parallel jobs
  -d SOURCE_PATH, --source-path SOURCE_PATH
                        path to source directory. defaults to the current directory
  -i, --ignore-dependencies
                        don't try to install dependencies of requested packages
  -n, --no-checksum     do not use checksums to verify downloaded files (unsafe)
  --keep-prefix         do not remove the install prefix if installation fails
  --skip-patch          skip patching for the developer build
  -q, --quiet           do not display verbose build output while installing
  -u UNTIL, --until UNTIL
                        phase to stop after when installing (default None)
  --clean               unset harmful variables in the build environment (default)
  --dirty               preserve user environment in the spack build environment (danger!)

```
