### ISSUE TITLE
How does spack detect a failed build?

### ISSUE THREAD

**Issue by BarrySmith** [spack/spack#2585]
In the readthedocs I found

> Failing the build
> Sometimes you don’t want a package to successfully install unless some condition is true. You can explicitly cause the build to fail from install() by raising an InstallError, for example:
> 
> if spec.architecture.startswith('darwin'):
>     raise InstallError('This package does not build on Mac OS X!')

but how does spack detect errors in the make, make check make install paradigm. My make failed as did the make install but spack happily goes along thinking the install was successful.

> make[1]: *** [libpflotran.a] Error 1
> failed building pflotran, libpflotran.a, and/or libpflotranchem.a
> Installing PFLOTRAN at /Users/barrysmith/Src/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/pflotran-develop-gbnqbgxs25z4yvzi5fnnxh7spppvv34p.
> cp: /private/var/folders/c1/ldz_dt8n2r3dtwv_chp5pfr40000gn/T/barrysmith/spack-stage/spack-stage-NqfHMU/pflotran-xsdk/src/pflotran/pflotran: No such file or directory

what do I need to do in my makefiles to get spack to realize that the process failed?

Note this happens with the pflotran package so you can see what the makefile looks like currently.

**Comment by tgamblin** [comment]
Does the pilot ran makefile return an error code on failure?  Any command (spack.util.Executable)  in install() that returns an error code should raise an exception and fail the build.  

Another way the build can fail is if nothing is in the prefix after install.  And, finally, you can designate sanity check files for builds that write to the prefix (where a file present in the prefix doesn't necessarily mean success)

**Comment by BarrySmith** [comment]
I'll need to debug that, it has a base makefile that then calls the makefile that does the real work so it is possible the error code does not properly get up to the base makefile.

**Comment by tgamblin** [comment]
@BarrySmith: is this resolved?

**Comment by alalazo** [comment]
@BarrySmith Closing this as there's no reply. Feel free to reopen if still an issue.
