### ISSUE TITLE
Concretization of competing version constraints

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2632]
Just noticed this problem:
```
$ spack spec h5hut
...
==> Error: Invalid spec: 'hdf5@1.10.0-patch1%gcc@6.1.0+cxx~debug+fortran~mpi+pic+shared+szip~threadsafe arch=linux-centos6-x86_64'. Package hdf5 requires version 1.8:1.8.12, but spec asked for 1.10.0-patch1
```
This works though:
```
$ spack spec h5hut +mpi
```
This problem was uncovered by #2590, which changed the default to `+mpi`. The problem is with the following version constraints:
```python
depends_on("hdf5 @1.8:")
# h5hut +mpi uses the obsolete function H5Pset_fapl_mpiposix:
depends_on("hdf5 @:1.8.12", when="+mpi")
```
My understanding is that Spack ignores any `when=` dependencies during the first phase of concretization unless they are specified on the command line. Since I didn't specify `+mpi`, it chose the latest version of HDF5. Then, when it evaluated the default of `+mpi`, it found that the latest version of HDF5 does not satisfy `@:1.8.12`. @tgamblin

**Comment by tgamblin** [comment]
Added to the Spack `v1.0` project.  This will have to wait for the smarter concretizer.

**Comment by adamjstewart** [comment]
Just making sure we're aware of it. Ideally, the new super-fancy genius concretizer will be able to close every issue with the "concretization" label.

**Comment by tgamblin** [comment]
I hope so.  I'm sad it's not really super-fancy-genius -- It's just backtracking search.  But hey it should be pretty cool.  I want to add a `spack ways` command that shows you ALL the legal ways to build a package (not that it's guaranteed to terminate).

**Comment by davydden** [comment]
that's exactly the same issue as https://github.com/LLNL/spack/issues/1781 . For now you would need to have all `depends_on` either with or without  `when=` clause, so in this case it should changed to
```
depends_on("hdf5 @1.8:", when="~mpi")
```
so that Spack does not conretize `hdf5` before it went through the whole graph and variants.

**Comment by adamjstewart** [comment]
@davydden Unfortunately, that does not help.

**Comment by davydden** [comment]
@adamjstewart you are too quick to downvote:
```
$ spack spec h5hut
Input spec
--------------------------------
h5hut

Normalized
--------------------------------
h5hut
    ^autoconf@2.60:
        ^m4@1.4.6:
    ^automake
    ^libtool

Concretized
--------------------------------
h5hut@1.99.13%clang@8.0.0-apple+fortran+mpi arch=darwin-sierra-x86_64
    ^autoconf@2.69%clang@8.0.0-apple arch=darwin-sierra-x86_64
        ^m4@1.4.17%clang@8.0.0-apple+sigsegv arch=darwin-sierra-x86_64
            ^libsigsegv@2.10%clang@8.0.0-apple arch=darwin-sierra-x86_64
    ^automake@1.15%clang@8.0.0-apple arch=darwin-sierra-x86_64
    ^hdf5@1.8.12%clang@8.0.0-apple+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe arch=darwin-sierra-x86_64
        ^openmpi@2.0.1%clang@8.0.0-apple~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=darwin-sierra-x86_64
            ^hwloc@1.11.4%clang@8.0.0-apple arch=darwin-sierra-x86_64
                ^libpciaccess@0.13.4%clang@8.0.0-apple arch=darwin-sierra-x86_64
                    ^libtool@2.4.6%clang@8.0.0-apple arch=darwin-sierra-x86_64
                    ^pkg-config@0.29.1%clang@8.0.0-apple+internal_glib arch=darwin-sierra-x86_64
                    ^util-macros@1.19.0%clang@8.0.0-apple arch=darwin-sierra-x86_64
        ^zlib@1.2.8%clang@8.0.0-apple+pic arch=darwin-sierra-x86_64
```
with
```
diff --git a/var/spack/repos/builtin/packages/h5hut/package.py b/var/spack/repos/builtin/packages/h5hut/package.py
index a80a9e1..285f77e 100644
--- a/var/spack/repos/builtin/packages/h5hut/package.py
+++ b/var/spack/repos/builtin/packages/h5hut/package.py
@@ -41,10 +41,9 @@ class H5hut(Package):
 
     depends_on("autoconf @2.60:", type="build")
     depends_on("automake", type="build")
-    depends_on("hdf5 +mpi", when="+mpi")
-    depends_on("hdf5 @1.8:")
+    depends_on("hdf5 @1.8:", when="~mpi")
     # h5hut +mpi uses the obsolete function H5Pset_fapl_mpiposix:
-    depends_on("hdf5 @:1.8.12", when="+mpi")
+    depends_on("hdf5 @:1.8.12+mpi", when="+mpi")
     depends_on("libtool", type="build")
     depends_on("mpi", when="+mpi")
 ```
:smile:

**Comment by adamjstewart** [comment]
@davydden Interesting strategy, fighting fire with fire. But I think your understanding of the problem is wrong. The thing that got it working wasn't adding `depends_on("hdf5 @1.8:", when="~mpi")`, it was removing `depends_on("hdf5 @1.8:")`. This prevents Spack from concretizing on the latest version of HDF5 during the first pass (before considering variants), putting it off until the variants are decided upon. Your solution makes `spack spec h5hut` work, and is arguably better than the current state of affairs, but it introduces a new headache. Try any of the following commands with your new h5hut:
```
spack install h5hut ^hdf5+mpi
spack install h5hut ^hdf5@1.8.10
```
It doesn't work for the same reason that `spack install h5hut ^mvapich2` doesn't work without the `+mpi`.

**Comment by adamjstewart** [comment]
P.S. I'm working on various fixes to h5hut right now so I think I'll include your workaround for the time being.

**Comment by davydden** [comment]
> The thing that got it working wasn't adding depends_on("hdf5 @1.8:", when="~mpi"), it was removing depends_on("hdf5 @1.8:")

well, that's exactly what i suggested above in the first comment. BUT it was not enough, because apparently there was another `depends_on(hdf5 , when="+mpi")` which made problems. So it's arguable whether or not my understanding is wrong ;-)

> Try any of the following commands with your new h5hut

you can't have everything with the current conretizer, I am well aware of it. At least my patch make the whole thing comply with its limitation, whereas CLI dependecies can be specified with
```
spack install h5hut+mpi ^hdf5+mpi
```
Note, that things work OOB when you specify constraints in `packages.yaml`. That's the reason I don't use CLI much.

**Comment by bvanessen** [comment]
I think that I am hitting a problem like this too with different versions of protobuf needed by lbann and opencv:


[vanessen@flash21:build]$ spack spec lbann@develop %gcc@7.1.0 ^mvapich2@2.2
Input spec
--------------------------------
lbann@develop%gcc@7.1.0
    ^mvapich2@2.2

Normalized
--------------------------------
lbann@develop%gcc@7.1.0
    ^cmake
    ^cnpy
    ^elemental+int64+openmp_blas+shared
        ^gmp@4.3.2:
            ^autoconf
                ^m4@1.4.6:
                ^perl
                    ^gdbm
                        ^readline
                            ^ncurses
                                ^pkg-config@0.9.0:
            ^automake
            ^libtool
        ^metis+int64
        ^mpc
            ^mpfr@2.4.2:
        ^mvapich2@2.2
            ^bison
            ^libpciaccess
                ^util-macros
    ^hwloc
    ^protobuf@3.0.2:
        ^zlib

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    protobuf@3.4.0%gcc@7.1.0 build_type=RelWithDebInfo arch=linux-rhel7-x86_64 
        ^cmake@3.9.4%gcc@7.1.0~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel7-x86_64 
            ^ncurses@6.0%gcc@7.1.0~symlinks arch=linux-rhel7-x86_64 
                ^pkg-config@0.29.2%gcc@7.1.0+internal_glib arch=linux-rhel7-x86_64 
            ^openssl@1.0.2k%gcc@7.1.0 arch=linux-rhel7-x86_64 
                ^zlib@1.2.11%gcc@7.1.0+pic+shared arch=linux-rhel7-x86_64 


while trying to concretize the partial spec:

    opencv@3.3.0%gcc@7.1.0 build_type=RelWithDebInfo +core~cuda+eigen~gtk+highgui+imgproc+ipp+jasper~java+jpeg+openmp+png~python~qt+shared+tiff~vtk+zlib arch=linux-rhel7-x86_64 
        ^cmake@3.9.4%gcc@7.1.0~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel7-x86_64 
            ^ncurses@6.0%gcc@7.1.0~symlinks arch=linux-rhel7-x86_64 
                ^pkg-config@0.29.2%gcc@7.1.0+internal_glib arch=linux-rhel7-x86_64 
            ^openssl@1.0.2k%gcc@7.1.0 arch=linux-rhel7-x86_64 
                ^zlib@1.2.11%gcc@7.1.0+pic+shared arch=linux-rhel7-x86_64 
        ^eigen
        ^libjpeg-turbo@1.5.0%gcc@7.1.0 arch=linux-rhel7-x86_64 
            ^nasm
        ^libtiff@4.0.8%gcc@7.1.0 arch=linux-rhel7-x86_64 
            ^xz@5.2.3%gcc@7.1.0 arch=linux-rhel7-x86_64 


opencv requires protobuf version 3.1.0, but spec asked for 3.4.0

**Comment by scheibelp** [comment]
@bvanessen I can confirm that https://github.com/LLNL/spack/issues/2632#issuecomment-335584170 is another instance of this problem and in your case something like:

`spack spec lbann@develop ^protobuf@3.1.0`

should resolve your issue for now (while a concretizer update is pending)

**Comment by adamjstewart** [comment]
Either the error message has changed, or I've encountered a new situation in which this bug can occur. I have a package containing:
```python
    depends_on('py-pysmartdl', type=('build', 'run'))
    depends_on('py-pysmartdl@1.2.5', type=('build', 'run'), when='^python@:3.3')
    depends_on('py-pysmartdl@1.3.1:', type=('build', 'run'), when='^python@3.4:')
```
When I run:
```console
$ spack spec py-geeup
Input spec
--------------------------------
py-geeup

Concretized
--------------------------------
==> Error: Conflicting conditional dependencies for spec

	py-geeup ^gettext ^pkgconfig@0.9.0: ^py-atomicwrites@1.0: ^py-attrs@17.4.0: ^py-beautifulsoup4@4.5.1: ^py-bottleneck ^py-cachetools@2.0.0: ^py-earthengine-api@0.1.87: ^py-funcsigs ^py-future@0.16.0: ^py-futures@3.2.0: ^py-google-api-core@1.14:1.999 ^py-google-api-python-client ^py-google-auth@1.4.1:1.999 ^py-google-auth-httplib2@0.0.3: ^py-google-cloud-core@1.0:1.999 ^py-google-cloud-storage@1.1.1: ^py-google-resumable-media@0.3.1: ^py-googleapis-common-protos@1.6:1.999 ^py-httplib2@0.9.2: ^py-more-itertools@4.0.0: ^py-numexpr ^py-numpy@1.7: ^py-pandas@0.23.0: ^py-pathlib2@2.2.0: ^py-protobuf@3.6.0: ^py-psutil@5.4.5: ^py-py@1.5.0: ^py-pyasn1@0.4.6:0.4.999 ^py-pyasn1-modules@0.2.1: ^py-pytest@3.0.0: ^py-python-dateutil ^py-pytz@2017.2: ^py-requests@2.18:2.999 ^py-requests-toolbelt@0.7.0: ^py-retrying@1.3.3: ^py-rsa@3.1.4: ^py-scandir ^py-selenium@3.13.0: ^py-setuptools@38.3.0: ^py-setuptools-scm ^py-six@1.10.0:1.999 ^py-uritemplate@3.0.0: ^python@2.7:2.8,3.4:

Cannot merge constraint

	py-pysmartdl@1.3.1:

into

	py-pysmartdl@1.2.5
```
The only workaround I've found so far is to explicitly declare your Python version:
```console
$ spack spec py-geeup ^python@3:
```

**Comment by scheibelp** [comment]
@adamjstewart I think https://github.com/spack/spack/issues/2632#issuecomment-520024556 should be a new issue (I think this is a different type of issue than what is reported elsewhere in this thread):

I would characterize https://github.com/spack/spack/issues/2632#issuecomment-520024556 as a bug rather than feature request because while we can run into problems with merging constraints with different packages, we should be able to appropriately merge constraints within a package.

I suspect this occurs because we are not being strict enough about our constraint checking, which is something we may be able to address separately from the concretizer updates that would avoid conflicts that arise from greedy decisions.
