### ISSUE TITLE
Create spack-nonfree repository

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2647]
@tgamblin @adamjstewart 

The proposal, initially discussed in #2614, is to move non-free packages (which require, among other things, manual tarball downloads) into a separate `spack-nonfree` Spack repository, under a separate GitHub repo.

The GitHub repo `http://github.com/LLNL/spack-nonfree` would have a `repo.yaml` and `packages/` at its top level.  The `repo.yaml` file would specify either `builtin` or `nonfree` namespace (we need to decide this).

Existing non-free packages would be moved into this new repo: currently `matlab` and `oracle-jdk`, maybe others.

Is further discussion on this proposal needed?  Is this something that is ready for someone to implement?

**Comment by adamjstewart** [comment]
Every package containing `licensed_required = True` is licensed. Still not convinced on the argument for creating a new repo though.

**Comment by tgamblin** [comment]
I vaguely like the idea but I haven't really had time to think about this, and we have other priorities right now.  If people want to discuss, go ahead, but I don't really want to add this until it is easier to add repositories, e.g. by git URL.

**Comment by davydden** [comment]
copy-paste it here for clarification:

by @citibeth :

> Separating into non-free helps set user expectations, it does not directly address legal issues.

**Comment by alalazo** [comment]
Closing as stale. Feel free to reopen if you want to continue the discussion.
