### ISSUE TITLE
Non-downloadable packages

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2648]
Some packages cannot be auto-downloaded by Spack.  The current way to ensure that is to specify a URL like (see #1298):
```
url="file://%s/jdk-8u66-linux-x64.tar.gz" % os.getcwd()
```

We need a less obscure way to achieve the same end.

**Comment by alalazo** [comment]
Closing as almost a duplicate of #2489. Will put a note there to refer to this issue too.
