### ISSUE TITLE
Mixed Toolchains documentation out-of-date

### ISSUE THREAD

**Issue by jwillenbring** [spack/spack#2651]
The documentation in the section titled

[Mixed Toolchains](http://spack.readthedocs.io/en/latest/getting_started.html#mixed-toolchains)

refers in step 4 to the old location for the compilers.yaml file, and shows an example in the old format for an entry in that file.

**Comment by citibeth** [comment]
Thank you for bringing this to our attention.

**Comment by adamjstewart** [comment]
This is complicated, because `compilers.yaml` can be in either `~/.spack/` or in `~/.spack/linux`. So there's nothing wrong with the location. But we should probably say it can be in either directory.

**Comment by citibeth** [comment]
I'm beginning to wonder if we should get rid of one of those two
locations.  The complication has clearly caused problems.  And yet, can
someone name a use case where one would legitimately want both?

If pressed, I'd guess that we get rid of ~/.spack and keep ~/.spack/linux.

Also... even what we have now, we still don't have any way of including
OS-specific stuff --- for example, and OS-specific `packages.yaml` that
instructs Spack to use system packages.  So we need ~/.spack/linux-centos7,
etc.

**Comment by adamjstewart** [comment]
> Also... even what we have now, we still don't have any way of including OS-specific stuff --- for example, and OS-specific `packages.yaml` that instructs Spack to use system packages.  So we need ~/.spack/linux-centos7, etc.

We do have some OS-specific stuff (`etc/spack/defaults/darwin/packages.yaml`), but certainly not as fine-grained as you like. I agree that we should get down to the level of `linux-centos7-x86_64`. If we do, however, I would like to keep the default scope, as I manage two linux clusters of differing version but want to use the same compilers on both (they are mounted on GPFS, so same directory and version regardless of cluster).

**Comment by adamjstewart** [comment]
The documentation now refers to `~/.spack/darwin/compilers.yaml` as was originally brought up in this issue.

As for which scopes should or should not exist, or should be the default, I think there are other issues open for discussion on that front.
