### ISSUE TITLE
`+doc` or `+docs`?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2663]
Any opinions?  Should we standardize on a variant called `+doc` or `+docs`?  Either way, it will be turned off by default; turn it on builds docs associated with a package.

Sometimes building docs involves a lot: doxygen, even LaTeX.  And it's usually not needed in the land of the WWW.

**Comment by aprokop** [comment]
I think we should, and it's `+doc` for me.

**Comment by davydden** [comment]
Agree, also prefer '+doc'

**Comment by citibeth** [comment]
So it's agreed, we standardize on `+doc`.  Now somebody needs to change existing `+docs` to `+doc`.
