### ISSUE TITLE
Standard variant for develop / release build types

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2692]
@alalazo What do you think of a standard (multi-valued) variant called `build-type`, with the possible values `debug`, `release`, `relwithdebinfo` and `minsizerel`.  This could map directly to CMake's `CMAKE_BUILD_TYPE` variable, implemented in the `CMakePackage` superclass.

The idea is that `build-type` would not typically be set globally.  But if we think it were to be set globally, we should maybe call it `cmake-build-type`, so setting it doesn't confuse a similar build type for other build systems, but with different values.

(@tgamblin We really need to get #2386 merged...)

**Comment by alalazo** [comment]
Totally agree with it. I think I was talking about that in a PR with @adamjstewart, but I couldn't find it right now.

**Comment by citibeth** [comment]
Poll: Should it be called `build-type` or `cmake-build-type`?  I'm leaning toward the latter...

**Comment by adamjstewart** [comment]
I agree, let's name it as similarly as possible to what CMake calls the variable. Also, it should be `cmake_build_type`, not `cmake-build-type`. PEP 8.

**Comment by citibeth** [comment]
You mean that the Spack variant name should use underscores, not dashes?

**Comment by alalazo** [comment]
I would lean towards `build-type`: after all it's in the `CMakePackage` class.

**Comment by adamjstewart** [comment]
Oh sorry, didn't realize it was a variant. Even then, maybe we should use underscores, since variants can start with a dash.

I'm fine with either (build-type or cmake-build-type), (underscores or dashes)

**Comment by citibeth** [comment]
The problem with `build-type` is... what happens if someone tries to set it
globally?  If `build-type` is implemented for all build systems, it will
likely have different values for different build systems.  Autotools might
not support `relwithdebinfo`, for example.  Going with `build-type` would
effectively eliminate the possibility of setting it globally.

On the other hand, maybe we don't feel a need to set it globally, and would
prefer the simplicity of just calling it `build-type` everywhere.

**Comment by alalazo** [comment]
> On the other hand, maybe we don't feel a need to set it globally, and would
prefer the simplicity of just calling it `build-type` everywhere.

I think this will be the case. `spack info` will then give you more information on each particular package.

**Comment by alalazo** [comment]
Closing as we have:
```python
variant('build_type', default='RelWithDebInfo',
            description='CMake build type',
            values=('Debug', 'Release', 'RelWithDebInfo', 'MinSizeRel'))
```
in the `CMakePackage` class.
