### ISSUE TITLE
Downloading protocols are inconsistent for the GNU site

### ISSUE THREAD

**Issue by weijianwen** [spack/spack#2716]
In spack's packages, several protocols (ftp, http, https) are used to download tar from GNU site ftp.gnu.org. These protocols function equivelantly. However, compared to ftp, http/https are easier to set up behind a firewall via a transparent proxy, namely squid.

How about substituting all `ftp://ftp.gnu.org` with `https://ftp.gnu.org`?

**Comment by tgamblin** [comment]
That would be fine.  Feel free to submit a PR.

You could also add a test (maybe in package_sanity) to ensure that builtin packages use http(s) instead of ftp for sites where it is known to be available (like gnu.org).  That would ensure that future packages do this too.

**Comment by citibeth** [comment]
With #2718 on the horizon, maybe we should start going to town with FetchStrategy implementations.  GNUFetchStrategy would be an obvious one here: it would try `http://` or `https://`, and fall back to `ftp://` if none of those work.

We could beef up other fetch strategies as well... for example, many packages can be found at Fedora.  We could create a FetchStrategy that looks for a package at Fedora if, for whatever reason, the main website is down.  It would be instantiated as `final_fetch_strategy=FedoraBackupStrategy(basic_fetch_strategy)`.

**Comment by tgamblin** [comment]
@citibeth: too much complexity and maintenance, too little benefit.  There is no real problem fetching here like there is with Python.  We just need to change the URLs.

**Comment by citibeth** [comment]
I agree with you; fixing GNU URLs to `ftp://` should do the trick and is simpler.

[Off topic for this Issue]:
I do think that some kind of fallback for URLs would be useful.  I've run into it a few times; a website goes down and suddenly my Spack build doesn't work.  In fact, my Spack build depends on 100 websites being up when I want to build, and that is a problem.  When things went down, I manually hacked the packages in question to find it from Fedora instead.

**Comment by weijianwen** [comment]
@tgamblin I'm working on a RP including the following changes.

- Replacing all instances of 'ftp://' with 'https://' or 'http://' if possible.
- Adding a test functin named `test_http_is_favored` in `lib/spack/spack/test/package_sanity.py`. Tests fail if "ftp://" is filled while https/http is available for the download site.

Feedbacks are welcome.

**Comment by tgamblin** [comment]
@weijianwen: sounds good.  I'm assuming `test_http_is_favored` will just check a few known sites?

**Comment by weijianwen** [comment]
I plan to test connection to the specific site during tesing via `httplib`. Is it a problem for the CI system? Another approach is to maintain a list of known sites, which CI is easier to deal with.

**Comment by tgamblin** [comment]
@weijianwen It would be best if the CI didn't ping remote sites, as that can cause it to fail sporadically. I think known sites would work better.

**Comment by weijianwen** [comment]
The first PR is out #2957 . Comments are welcome.

**Comment by scheibelp** [comment]
Fixed by https://github.com/spack/spack/pull/2958 (an update of #2957)
