### ISSUE TITLE
Plans for conda/anaconda?

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2738]
I was trying to write a package for [UV-CDAT](https://github.com/UV-CDAT/uvcdat) but I discovered that the latest version actually requires conda:
```
CMake Error at CMakeLists.txt:25 (message):
  Could not locate conda, please make sure conda is installed and in your
  PATH
...
// Path to a program.
CONDA:FILEPATH=CONDA-NOTFOUND
```
Do we have any plans for how to handle packages like this?

**Comment by tgamblin** [comment]
@mathstuf: weren't you working on this?

**Comment by citibeth** [comment]
Yes... requiring Conda from your CMake is bad form.  I don't require Spack from my CMake-based packages.  Maybe we should contact the upstream authors?  This is inside LLNL...

**Comment by citibeth** [comment]
I looked a bit at the UV-CDAT CMake build... it is (to put it mildly) whacked out.  Normal CMakeLists.txt files explain how to combine source files into executables, copy to an installation directory, etc.  This one runs git three times, launches some bash scripts to install with Conda, and does all sorts of crazy stuff.

Personally... I wouldn't touch UV-CDAT until it gets a sane build.  I think it's worth reaching out to the authors on this one.

**Comment by mathstuf** [comment]
I had been, but I was trying to package it in a per-package setup, not as a monolithic project. Upstream needs to better document the packages and how they are related (I've never gotten it to compile even half way even from what they do provide, nevermind Spack). Aashish was going to discuss with the developers/maintainers about the build system, but I haven't had an update on that.

**Comment by adamjstewart** [comment]
@mathstuf I added an Anaconda package in #2741 which does the monolithic installation that you mentioned. I think it would also be good to package miniconda and get it working on a per-package basis as well.

**Comment by tgamblin** [comment]
@adamjstewart: I talked to Dean Williams (@williams13, UV-CDAT lead) at LLNL about your install issues.  He wants to get UV-CDAT into Spack so they have a good way to install it on HPC machines.  He said to talk to @doutriaux1.

@doutriaux1: @williams13 said it was possible to build UV-CDAT from scratch, without Conda.  Any chance you can help @adamjstewart out with that?

**Comment by doutriaux1** [comment]
Yes it’s not that hard to install w/o conda I think it would be awesomw to have CDAT in spack .The best would be to sit with @adamjstewart . Adam are you onsite at LLNL or remote? If on-site and not in Q area I can stop by your office anytime convenient for you. If onsite in Q then you need to come over. If offiste we can do webex.

**Comment by adamjstewart** [comment]
Hi @doutriaux1, I'm actually at ANL, so a face-to-face won't be possible. Are you saying it is possible to install the latest release without conda, or that it _could_ be possible in the future?

**Comment by doutriaux1** [comment]
It's 100% doable, that used to be the way until last spring. But conda solved all the build issues for our end-users. Let me know when would be a (few) good time(s) for you for a webex hopefully we can sync up soon.

**Comment by citibeth** [comment]
Charles,

> But conda solved all the build issues for our end-users.

I can certainly believe this!  I'm of the opinion that auto-builders are
going to be widely used in the near future.  At that point, it will be like
Linux distros; people will be able to use your software if you are
"included" in their preferred auto-builder.

There are reasons, which I won't dwell on here, to prefer Spack over Conda;
and vice versa.  I think the best advice to package authors at this point
is:

(a) Do not tie yourself to any single auto-builder

(b) Provide full support for at least one auto-builder.  (Meaning... if
someone comes with no auto-builder preferences and just wants to install
your system, this is where you point them).

(c) Be open to getting your package included in other auto-builders, if and
when someone expresses interest.

**Comment by doutriaux1** [comment]
@citibeth agreed! That's why I think it would be great to add CDAT to spack.

**Comment by doutriaux1** [comment]
@mathstuf component-based is the way to go for all the externals, that's how we did it in conda. There's a bucnh of recipes available at: https://github.com/uv-cdat/conda-recipes most of these are no longer needed as we now use conda-forge to provide most of the external dependencies. But they could be re-used by spack as a starter for everything not in spack yet

**Comment by adamjstewart** [comment]
Closing this as the discussion seems dead.
