### ISSUE TITLE
Questions about extend(..., ignore=...)?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2753]
1. The docs should make it clear that `ignore=` takes regular expressions, not glob wildcard expressions (unless we want to do the latter).

2. How do I ignore more than one thing?  kwargs cannot be repeated.  Would I do this?
```
extends('python', ignore=('a', 'b'))
```

**Comment by adamjstewart** [comment]
> How do I ignore more than one thing?

```python
ignore='a|b'
```

**Comment by adamjstewart** [comment]
It looks like this issue has already been addressed. From https://spack.readthedocs.io/en/latest/packaging_guide.html#activation-arguments:

> The only keyword argument supported by default is the ignore argument, which can take a regex, list of regexes, or a predicate to determine which files not to symlink during activation.
