### ISSUE TITLE
"Module Commands for Shell Scripts" doc is not consistent

### ISSUE THREAD

**Issue by hartzell** [spack/spack#2757]
The [Module Commands for Shell Scripts](https://spack.readthedocs.io/en/latest/module_file_support.html#module-commands-for-shell-scripts) documentation does not seem to be consistent.

The prose talks about the `--shell` flag and `spack module find`, but the examples shows output from `spack module loads --dependencies py-numpy git`.

It's not obvious to me how the prose and the output are related or if they are.

**Comment by citibeth** [comment]
@hartzell Thank you for catching this.  The syntax of the command changed, and it looks like some copy of the old syntax has not been removed.  You should use `spack module loads` or `spack module loads -r`, depending on whether you need to load transitive dependencies.
