### ISSUE TITLE
`spack activate` is not easily reversible.

### ISSUE THREAD

**Issue by hartzell** [spack/spack#2759]
I can activate `py-flake8`:

```
[hartzelg@rpbuchop001 spack-20161212]$ spack activate py-flake8
==> Activated extension py-configparser@3.5.0%gcc@5.4.0 arch=linux-centos7-x86_64-2vyc36s for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Activated extension py-enum34@1.1.6%gcc@5.4.0 arch=linux-centos7-x86_64-a5hkmca for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Activated extension py-mccabe@0.5.2%gcc@5.4.0 arch=linux-centos7-x86_64-eyrwg56 for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Activated extension py-pycodestyle@2.0.0%gcc@5.4.0 arch=linux-centos7-x86_64-5c257kg for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Activated extension py-pyflakes@1.2.3%gcc@5.4.0 arch=linux-centos7-x86_64-jx725az for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Activated extension py-flake8@3.0.4%gcc@5.4.0 arch=linux-centos7-x86_64-5wabxrq for python@2.7.12~tk~ucs4%gcc@5.4.0
```

but having done so, this doesn't work:

```
[hartzelg@rpbuchop001 spack-20161212]$ spack deactivate py-flake8
==> Deactivated extension py-flake8@3.0.4%gcc@5.4.0 arch=linux-centos7-x86_64-5wabxrq for python@2.7.12~tk~ucs4%gcc@5.4.0
```

I can use the `-a` flag:

```
[hartzelg@rpbuchop001 spack-20161212]$ spack deactivate -a py-flake8
==> Deactivating py-flake8@3.0.4%gcc@5.4.0 arch=linux-centos7-x86_64-5wabxrq and all dependencies.
==> Deactivated extension py-flake8@3.0.4%gcc@5.4.0 arch=linux-centos7-x86_64-5wabxrq for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Deactivated extension py-configparser@3.5.0%gcc@5.4.0 arch=linux-centos7-x86_64-2vyc36s for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Deactivated extension py-enum34@1.1.6%gcc@5.4.0 arch=linux-centos7-x86_64-a5hkmca for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Deactivated extension py-mccabe@0.5.2%gcc@5.4.0 arch=linux-centos7-x86_64-eyrwg56 for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Deactivated extension py-pycodestyle@2.0.0%gcc@5.4.0 arch=linux-centos7-x86_64-5c257kg for python@2.7.12~tk~ucs4%gcc@5.4.0
==> Deactivated extension py-pyflakes@1.2.3%gcc@5.4.0 arch=linux-centos7-x86_64-jx725az for python@2.7.12~tk~ucs4%gcc@5.4.0
```

but that leaves me with two nagging doubts:

- why is `activate` automagically recursive but `deactivate` is not; and
- is `deactivate -a` smart enough to not deactivate something that is also a dependency for a different top-level package (e.g. above, what would happen if another package also needed `py-enum34` activated?)?  At first glance it does not appear to be:

    ```
    [hartzelg@rpbuchop001 spack-20161212]$ spack activate py-enum34
    ==> Activated extension py-enum34@1.1.6%gcc@5.4.0 arch=linux-centos7-x86_64-a5hkmca for python@2.7.12~tk~ucs4%gcc@5.4.0
    [hartzelg@rpbuchop001 spack-20161212]$ spack activate py-flake8
    ==> Activated extension py-configparser@3.5.0%gcc@5.4.0 arch=linux-centos7-x86_64-2vyc36s for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Activated extension py-mccabe@0.5.2%gcc@5.4.0 arch=linux-centos7-x86_64-eyrwg56 for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Activated extension py-pycodestyle@2.0.0%gcc@5.4.0 arch=linux-centos7-x86_64-5c257kg for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Activated extension py-pyflakes@1.2.3%gcc@5.4.0 arch=linux-centos7-x86_64-jx725az for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Activated extension py-flake8@3.0.4%gcc@5.4.0 arch=linux-centos7-x86_64-5wabxrq for python@2.7.12~tk~ucs4%gcc@5.4.0
    [hartzelg@rpbuchop001 spack-20161212]$ spack deactivate -a py-flake8
    ==> Deactivating py-flake8@3.0.4%gcc@5.4.0 arch=linux-centos7-x86_64-5wabxrq and all dependencies.
    ==> Deactivated extension py-flake8@3.0.4%gcc@5.4.0 arch=linux-centos7-x86_64-5wabxrq for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Deactivated extension py-configparser@3.5.0%gcc@5.4.0 arch=linux-centos7-x86_64-2vyc36s for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Deactivated extension py-enum34@1.1.6%gcc@5.4.0 arch=linux-centos7-x86_64-a5hkmca for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Deactivated extension py-mccabe@0.5.2%gcc@5.4.0 arch=linux-centos7-x86_64-eyrwg56 for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Deactivated extension py-pycodestyle@2.0.0%gcc@5.4.0 arch=linux-centos7-x86_64-5c257kg for python@2.7.12~tk~ucs4%gcc@5.4.0
    ==> Deactivated extension py-pyflakes@1.2.3%gcc@5.4.0 arch=linux-centos7-x86_64-jx725az for python@2.7.12~tk~ucs4%gcc@5.4.0
    [hartzelg@rpbuchop001 spack-20161212]$
    ```

How do people use `activate` in The Real World(tm)?

**Comment by adamjstewart** [comment]
The last time I used `activate/deactivate`, there was a bug that prevented you from activating or deactivating if there were two identical installations with different hashes. `spack activate --force` wasn't working for me either. And it didn't accept hashes like `spack uninstall` did. So I stopped using it.

> why is activate automagically recursive but deactivate is not; and

Because activate is unambigous. You have to activate the dependencies for the package to work. But deactivate is ambigous. Do you want to to activate just that package or all packages that depend on it? What if other packages depend on it? What if the dependencies were explicitly activated?

We did add a flag to track whether or not packages were installed explicitly or if they were installed as dependencies. Maybe we should add this with activation as well.

> is deactivate -a smart enough to not deactivate something that is also a dependency for a different top-level package

Yes. It should be. If it isn't, then it's a bug.

**Comment by hartzell** [comment]
> So I stopped using it.

@adamjstewart: How do you wire the flake8 command into your environment?

I'm working on closing the "final mile"; trying to figure out how I should hook a tree full of stuff that I've `spack install`ed into user's environments.  `activate` doesn't quite work (e.g. issue #2760), module autoloading problematic (chatty autoload, #2760 again, I think), etc...

I feel like I'm really close but missing something....

**Comment by adamjstewart** [comment]
The alternative to using `spack activate` is to make sure your users load the modules for these packages. As long as the package is in PATH and PYTHONPATH, you don't need to activate them. This is slightly more inconvenient than activating them, but allows users to select the version of the package they want.

**Comment by hartzell** [comment]
Do you have your modulefiles set up to autoload their dependencies?

**Comment by adamjstewart** [comment]
I actually don't use modules, I use something similar called SoftEnv that was written at ANL back before Modules existed. So no. But I did create a single "module" that loads all of the modules for Python and the python packages I have installed. It really is a terrible solution, but I haven't come up with something better yet. I would much rather use `spack activate`, but... changing hashes...

**Comment by citibeth** [comment]
> How do people use activate in The Real World(tm)?

I don't, I generate scripts of `module load` commands to load all the modules I need (including transitive dependencies).  Look at `spack module loads -r`.  For a more advanced version of the same idea, see #2698 for an example of how this stuff can work.

**Comment by paulhopkins** [comment]
> How do people use activate in The Real World(tm)?
I was experimenting with activate and de-activate but I did not like the idea of changing a Python package once it had been installed with a specific hash. Instead I wanted a new package installation that included Python and all the packages activated into this new directory, and each combination of packages would have a specific hash.

I am able to do this with Spack View (using hardlinks) but I did hack the code to properly activate the extensions (a1b0371a7b32ae05409d42909e327e6e4d91c377), and I have to fix some shebang and handle module files myself. In the end I went the whole hog, and now present my entire software stack (~130 packages) as a view. This makes things simpler and removes the need for PYTHONPATH which can interfere with users' virtualenvs.

I am now looking at using a meta-package that creates views as its install method. I think this is a better way to go, as the view is recorded and treated as a normal package. I will give this a go on my production system and see how it looks.

**Comment by pramodk** [comment]
> I am now looking at using a meta-package that creates views as its install method. I think this is a better way to go, as the view is recorded and treated as a normal package. I will give this a go on my production system and see how it looks.

@paulhopkins : will be interested to hear about this, in case you have prototyped this.

**Comment by becker33** [comment]
Closing this -- `spack activate` is now deprecated
