### ISSUE TITLE
Copy config.log to install directory

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2781]
If a `config.log` file is present in the build directory, we should copy it to the installation directory where we store things like `build.out` and `build.env`. This can be restricted to `AutotoolsPackage`, or can be done for any package that produces a `config.log` file.

**Comment by citibeth** [comment]
Sounds like a decent idea, and should be restricted to `AutotoolsPackage`.  `CMakePackage` should copy `CMakeCache.txt`.
