### ISSUE TITLE
Package: "url" member always required

### ISSUE THREAD

**Issue by ax3l** [spack/spack#2788]
When defining `url_for_version` for packages and skipping to implement (the then unnecessary) default `url` member one gets:

```
=> Error: Cannot fetch versions for package {package} because it does not define any URLs to fetch.
```

Following the [Package class code documentation](http://spack.readthedocs.io/en/latest/spack.html?highlight=url_for_version#spack.package.PackageBase) I interpret that it states to require the `url` _or_ the member function:
```
Required Attributes

Aside from proper naming, here is the bare minimum set of things you need when you make a package:

[...]
url or url_for_version(self, version):
    If url, then the URL of the source archive that spack will fetch.
    If url_for_version(), then a method returning the URL required to fetch a particular version.
[...]
```

**Comment by adamjstewart** [comment]
There are actually good reasons to implement both `url` and `url_for_version`. `url_for_version` is used to download packages, but `url` is used to find new versions of the package with `spack versions` and `spack checksum`.

With that said, there are many packages like `pflotran` which only use Git for fetching (see #3788), or bundle packages that only install other packages and need no URL (see #1926). Spack should not crash just because a package does not have a URL.

I attempted to start solving this in #3161 but never really tested it. If @alalazo or anyone else wants to pick up where I left off that would be great.

**Comment by jcftang** [comment]
I ran into a similar problem with the kaldi package when I used it as a dependency. I had to add a url ="https://foo/... " for my package to work.

**Comment by adamjstewart** [comment]
@tgamblin I thought we fixed this?

**Comment by LDAmorim** [comment]
Hi, 
Thanks for explaining the issue @ax3l.

I am not sure if this is the best place to mention this (or if you prefer a separate issue).
But I just ran into the same issue (I think), when trying to install **openpmd-api**:

```console
$ spack install openpmd-api@dev  +python@3.7.6  ^hdf5+cxx+mpi+hl ^adios2~sst
...
==> Error: Can't extrapolate a URL for version 3.7.6 because package openpmd-api defines no URLs
```

I can successfully fetch the package openpmd-api.

And the package should in principle allow python bindings for that python version (that I installed via spack), I think, in line: https://github.com/spack/spack/blob/7e13c9a6a0533bcf2f6fdb4fcd42f517875c9ca1/var/spack/repos/builtin/packages/openpmd-api/package.py#L53

I am trying to learn how to add the url and fix this and will add updates here.

Cheers,
Diana

**Comment by ax3l** [comment]
> ==> Error: Can't extrapolate a URL for version 3.7.6 because package openpmd-api defines no URLs

Wow, that's super confusing. Why should the missing URL in one package (`openpmd-api`) be problematic for the fetch of a version in another (`python`)? :D

**Comment by LDAmorim** [comment]
I agree that it is confusing, and I definitely didn't understand why!

Unfortunately I have been playing around with both my spack and system configurations.
I didn't get yet to the point of installing openpmd-api so I don't know if I will be able to reproduce the issue to show you its details.

**Comment by ax3l** [comment]
The problems seams to be (upon adding a URL):
```
==> 23854: Installing openpmd-api
==> Warning: There is no checksum on file to fetch openpmd-api@3.7.6 safely.
==>   Fetch anyway? [y/N] n
```

**Comment by ax3l** [comment]
With and without URL, this works: `spack install openpmd-api@dev  +python ^python@3.7.6`.

Not sure about @jcftang 's exact problem, maybe he can also post a re-producer, but for me this seams this is not a bug.
