### ISSUE TITLE
MPI & HDF5 on Ubuntu 14.04

### ISSUE THREAD

**Issue by ax3l** [spack/spack#2791]
I found a neat linker problem on Ubuntu 14.04 with both OpenMPI 2.0.1 and MPICH 3.2 in spack.

When building a *the HDF5 Fortran library*, in my case HDF5 (1.8.X or 1.10/latest), against one of both the following default dependencies cause problems:

**Update**: the report below is caused by our system having a [`/lib64/mpi.so`](#issuecomment-271605561) and HDF5's fortran library build tools seem to be quite doubtful about which `mpi.so` to take.

***

- via `mpif90` for HDF5's Fortran lib, `-lnuma` tries to get linked but is not found (since it was taken from the system)
- I expected it to get side-pulled in via `hwloc` (in spack), but actually `libopen-pal` (from system) triggers it
- the problem is, that *only a file called* `libnuma.so.1` is available on a few debian/ubuntu (and supposedly [some redhat](http://www.shocksolution.com/2013/02/openmpi-on-redhat-5-cannot-find-lnuma/)) systems, *without a simlink* `libnuma.so -> libnuma.so`

If I replace the failing `-lnuma` to the absolute path used in `libopen-pal.so`'s `libnuma.so.1` this fixes it.

This happens when people only install the package [libnuma1](http://packages.ubuntu.com/search?mode=exactfilename&suite=trusty&section=all&arch=any&keywords=libnuma.so.1&searchon=contents) (lib) but forget to install [libnuma-dev](http://packages.ubuntu.com/search?suite=trusty&arch=any&mode=exactfilename&searchon=contents&keywords=libnuma.so) (headers & simlinks).

~~The obscure thing is now, that `hwlock` (built in spack for MPI) brings its own `libnuma` headers (`numa.h`)!~~ (*not sure if that was fully correct*) (also seems to be included in common [linux header packages](http://packages.ubuntu.com/search?mode=exactfilename&suite=trusty&section=all&arch=any&keywords=numa.h&searchon=contents)).

~~Long story short: can and should we built our own `libnuma` (and `libopen-pal`) or at least make the latter a variant?~~

**Comment by ax3l** [comment]
Actually, OPAL is one of the three [softwere layers](https://www.open-mpi.org/doc/v2.0/man1/mpic++.1.php) of OpenMPI/MPICH.
```
Open MPI is comprised of three software layers: OPAL (Open Portable Access Layer),
ORTE (Open Run-Time Environment), and OMPI (Open MPI). There are wrapper compilers for each layer; each layer’s wrapper only links in the libraries relevant for that layer. Specifically, each layer provides the following wrapper compilers [...]
```

Pretty weird, since I actualy hav a `libopen-pal.so` build in my spack `opt` but `HDF5` somehow ends up using the wrong one...

**Comment by ax3l** [comment]
Aw, I think I somehow screwed up mixing my MPIs.

**Comment by ax3l** [comment]
oh no, our system has a `/lib64/libmpi.so` -.-

**Comment by ax3l** [comment]
something is wrong in HDF5's `FCLIBS` because it seems to alternately include spack and `/lib64` libs in hdf5-source:`fortran/src/Makefile`.

**Comment by davydden** [comment]
FYI, `lib` and `lib64`, AFAICT, are addressed by https://github.com/LLNL/spack/pull/1875

**Comment by ax3l** [comment]
@davydden actually I am note sure if this *prevents* using something like `/lib64`, because in my case it seems everything is self-contained and only HDF5 decides to *sometimes* prefer a system path although it *should* have everything already in spack (or we missed a dependency in the fortran trajectory that I can not spot right now)

**Comment by davydden** [comment]
> actually I am note sure if this prevents using something like /lib64

i clearly mis-interpreted your issue. I though you want to use something system provided from `/lib64`. 

> HDF5 decides to sometimes prefer a system path although it should have everything already in spack (or we missed a dependency in the fortran trajectory that I can not spot right now)

Possible. Could also be some fancy bug or maybe some auto-detection needs to be disabled in hdf5 so that it does not try to be too smart.

**Comment by alalazo** [comment]
Closing as stale and maybe resolved by newer `hdf5`

**Comment by alalazo** [comment]
@ax3l Feel free to reopen if you think it's still important.

**Comment by ax3l** [comment]
Thanks for cleaning this up.
