### ISSUE TITLE
PYTHONSTARTUP breaks setup-env.sh

### ISSUE THREAD

**Issue by bhawkins** [spack/spack#2804]
I have a PYTHONSTARTUP file that prints some stuff to screen when I start python. Unlike "python -c expr", the command "spack-python -c expr" will run the PYTHONSTARTUP file.  I think the implementation is [here](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/cmd/python.py#L50-L54). This behavior causes all the python commands in setup-env.sh to break silently and leaves me unable to "spack load" anything.  Brief illustration:

```bash
$ export PYTHONSTARTUP='/tmp/psu' && rm -f $PYTHONSTARTUP
$ sum=$(spack-python -c 'print 1+1') && echo $sum
2
$ echo "print 'fubar'" > $PYTHONSTARTUP
$ sum=$(python -c 'print 1+1') && echo $sum
2
$ sum=$(spack-python -c 'print 1+1') && echo $sum
fubar 2
```

**Comment by citibeth** [comment]
I'll let others figure out the core issue here.  As a workaround, you can generate "environment loading" scripts with `spack module loads`; see the manual for further docs.  You might find you like this better than using `spack load` anyway.

**Comment by adamjstewart** [comment]
Spack's `setup-env.*sh` files no longer directly use `python` or `spack-python`, so I think this issue can be closed. If there is still an issue, feel free to reopen.
