### ISSUE TITLE
conflict between petsc~boost and trilinos+boost

### ISSUE THREAD

**Issue by sarich** [spack/spack#2879]
Using barry/xsdk branch

The xsdk package has dependencies:

```trilinos@develop+xsdkflags+hypre+superlu-dist+metis+hdf5~mumps+boost~suite-sparse```
and
```petsc@develop+trilinos+mpi+hypre+superlu-dist+metis+hdf5~mumps~boost```

Notice that petsc has ```~boost``` and trilinos has ```+boost```

When petsc queries the specs
```
options.append(
                '--with-{library}={value}'.format(
                    library=library, value=('1' if library in spec else '0'))
            )
```
it finds +boost and adds --with-boost=1 to the configure line
Is there a way to avoid this?

**Comment by sarich** [comment]
I think the error I'm getting is based on petsc using the wrong version of cpp, and the first test of cpp in petsc configure is with the boost headers, so petsc  configure is failing and blaming it on boost.

I still think the issue needs to be addressed, but I'm not in a hurry

**Comment by davydden** [comment]
Did u check that Petschaft indeed wrongfully add boost as a dependency? AFAICT this should not happen even in your usage case.

**Comment by alalazo** [comment]
Possibly outdated by now.
