### ISSUE TITLE
spack does not move pflotran mod files to install directory

### ISSUE THREAD

**Issue by amklinv** [spack/spack#2937]
@BarrySmith @sarich @tgamblin

Installing pflotran with spack creates three directories: bin, lib, and share.  It does not create an include directory, and the pflotran mod files are nowhere to be found.  Apparently pflotran creates the mod files within the src directory.  Pflotran probably needs to be patched to place the files somewhere in the installation directory.

**Comment by alalazo** [comment]
Apologies for the time it took to get to this! :sweat_smile: Reading the issue this looks more like a problem with the upstream code. Has it been solved in the meanwhile?

**Comment by adamjstewart** [comment]
@ghammond86 and @balay are the maintainers for this package, they can probably answer this question.

**Comment by balay** [comment]
Looks like this issue is already fixed.

```
[balay@pj01 spack]$ spack find -p pflotran
==> 1 installed package
-- linux-fedora31-skylake / gcc@9.3.1 ---------------------------
pflotran@xsdk-0.5.0  /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/pflotran-xsdk-0.5.0-gu6loeebginevne3bvv5hwbprmgee7e3
[balay@pj01 spack]$ ls /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/pflotran-xsdk-0.5.0-gu6loeebginevne3bvv5hwbprmgee7e3/
bin  include  lib  share
[balay@pj01 spack]$ ls /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/pflotran-xsdk-0.5.0-gu6loeebginevne3bvv5hwbprmgee7e3/include/*.mod |wc -l
288
[balay@pj01 spack]$
