### ISSUE TITLE
Getting Spack to use System-Installed Packages

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2979]
Many have pointed out that it would be nice if Spack used system-install packages for many things, rather than building its own.    Examples include bison, flex, gettext, ncurses, m4, libsigsegv, mpi, openssl, qt, most of x11, etc.  Unfortunately, the issue has not so far been immediately amenable to solution.  I believe the barriers are fundamentally due to lack of standardization between Linux distros and underlying packages --- and solutions will require a lot of detailed work that is specific to each distro / package.

We have discussed this issue before.  General solutions are:

1. Create (and maintain) OS-specific lists of which distros provide which Spack packages; see #2700 

2. Try to mine a distro's `yum` or `dpkg` repository for information on which Spack packages are available (or could be made available with an appropraite `yum install` command).

3. Try to auto-detect which version of a package is installed by finding and trying to execute the program (like the way configure / AutoMake do it).

All three of the above approaches are possible, but also have problems and require maintenance.  (1) isn't very flexible about allowing different users to include different packages from the system.  (2) gets into problems of identifying which Linux packages correspond to which Spack pacakges (would have to be maintained by hand).  (3) would require a different detection procedure for each Spack package, alongside the `install()` method.

All of these approaches bring up the problem that more often than not, the version supplied by the Linux distro is *older* than any of the versions currently supplied (or accounted for) by the Spack package.  This is probably a minor issue; so far, I've been working with it by adding those old versions to the Spack package.

**Comment by adamjstewart** [comment]
I like (1) because it's simple. We have 2 clusters with a shared filesystem on different versions of CentOS. I couldn't possibly have a single `packages.yaml` of external packages for both clusters. I want `linux-centos7-x86_64` and `linux-centos6-x86_64` configuration hierarchies instead of just `linux`.

> All of these approaches bring up the problem that more often than not, the version supplied by the Linux distro is older than any of the versions currently supplied (or accounted for) by the Spack package. This is probably a minor issue; so far, I've been working with it by adding those old versions to the Spack package.

What doesn't work if those versions aren't included in the Spack package?

**Comment by davydden** [comment]
I also think that (1) is relatively easy to maintain, extend and fix when needed.

**Comment by mamelara** [comment]
Something like this is definitely needed on our Cray machines since we are constantly linking to the cray provided packages. (1) looks good since Edison and Cori both have the same packages but different versions of each.

**Comment by adamjstewart** [comment]
For (1), are all CentOS 7 computers guaranteed to have the same version of a package? Or will there be minor differences in version number?

**Comment by Exteris** [comment]
There can be differences depending when there are updates.

Another point here: for many of these tools listed the compiler used is irrelevant. My Cmake can be compiled with a different gcc, clang or by hand for all I care. Could we not have a flag indicating that a package is ABI/compiler-independent?

**Comment by davydden** [comment]
> Could we not have a flag indicating that a package is ABI/compiler-independent?

i think this will be easier once https://github.com/LLNL/spack/pull/2548 is in.

**Comment by citibeth** [comment]
> What doesn't work if those versions aren't included in the Spack package?

I don't remember.  Try it, you will find out; I'm not sure the Concretizer likes it.  That's a small issue, to be debugged when it presents itself.

> There can be differences depending when there are updates.

Good point.  The question is... when packages are updated, do the distros update to a new version of the package, or is it just a bug-fix?  For CentOS, I believe they do just bug fixes.  But I'm sure the general answer for Linux distros is complicated, which would require some amount of (2) as well.

> Another point here: for many of these tools listed the compiler used is irrelevant. My Cmake can be compiled with a different gcc, clang or by hand for all I care. Could we not have a flag indicating that a package is ABI/compiler-independent?

Spack should be free to choose any compiler for build dependencies.  My assumption is this is a known issue, and will be addressed with the upcoming new concretization algo.

I suppose we could do the same thing for compiler-independent packages (i.e. those in pure C).  Let's see how the new concretizer and compilers-as-build-dependencies shapes up and then revisit this issue.

**Comment by adamjstewart** [comment]
Can this issue be closed now that `spack external find` is a feature? Users can now quickly and easily generate a `packages.yaml` for any new system they use.
