### ISSUE TITLE
Auto-Detect Module Systems

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2981]
From @Exteris

The presence of `lmod` or `environment-modules` should be auto-detected and configured the first time Spack is run; just like we currently do for compilers in `compilers.yaml`.  Similarly, there is no point in routinely generating modules for a module system the user doesn't have installed.

**Comment by alalazo** [comment]
duplicates #2924 ?

**Comment by krafczyk** [comment]
#3057 and #5955 attempt to address this issue.

**Comment by alalazo** [comment]
Added support for this in #3057 Feel free to reopen if you feel something is still missing.
