### ISSUE TITLE
Print errors in modulecmd

### ISSUE THREAD

**Issue by Exteris** [spack/spack#2983]
Right now errors in modulecmd are ignored.
It would be very useful for debugging module loads if these are printed.

**Comment by becker33** [comment]
@Exteris @adamjstewart Is this about modulefiles created through Spack or the use of modulecmd within Spack? If the latter it probably makes sense to change the assignment to me.

**Comment by Exteris** [comment]
@becker33 It is the latter case, for instance I call `module load make` to load a program, and if this command fails nothing is written.

**Comment by becker33** [comment]
@Exteris I've reworked much of our internal use of the module command, can you confirm whether this issue is still valid?

**Comment by adamjstewart** [comment]
No response since July, so I'm assuming this issue is no longer valid.
