### ISSUE TITLE
Cythonizing Spack

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2984]
@Exteris @tgamblin 

There has been talk of Cythonizing Spack.  If it were to be done, Spack would become harder to install.  Most likely, we would then have two levels of Spack --- a "slow/less capable" bootstrap Spack in pure Python, and a complete Spack that uses Cython, compiled modules, etc.  One of the first things users would need to do (or Spack would do itself) is to bootstrap up to the complete Spack from the bootstrap Spack.

This is all possible, but adds complexity.  And maybe we will do it some day.  But so far, I believe that slowness is not a core problem; although sometimes we perceive it to be.

I do think it would be worthwhile thinking through how our design would change if we had a really fast concretizer (say, sub-second performance on a 100-package DAG).

**Comment by adamjstewart** [comment]
I think the concretizer is the main source of slowness. Just try running `time spack spec r-rminer`. Got around 9-10 minutes on my laptop.

**Comment by citibeth** [comment]
Ouch... it looks like R is a whole level of complexity beyond Python.  And
that's not even taking into account `node-js`.

In that case, I believe we should consider implementing the new concretizer
in C++.  That would mean putting the main Spec data structure into C++,
writing concretizer algos that work on that, and then wrapping the data
structures and algos in Cython.

**Comment by alalazo** [comment]
```console
$ time spack spec r-rminer 
Input spec
--------------------------------
r-rminer

...


real	0m6.167s
user	0m6.060s
sys	0m0.104s
```
Closing.
