### ISSUE TITLE
CGNS -- need variant for enabling CGNS_ENABLE_SCOPING

### ISSUE THREAD

**Issue by gsjaardema** [spack/spack#2989]
When I use cgns at Sandia for IOSS library, we have the CGNS_ENABLE_SCOPING set to on.  I don't currently see this variant in the current CGNS.

I will try to send a pull-request that sets this, but since I am currently a newbie, it may take awhile. This is here in case someone else is faster and gets to it first; or if there are some guidelines on how to do it or why not to do it.

**Comment by adamjstewart** [comment]
Shouldn't be too hard. Just look at the `hdf5` variant in that package for an example.

**Comment by alalazo** [comment]
The variant has been added since a while.
