### ISSUE TITLE
mumps +shared doesn't link dependencies

### ISSUE THREAD

**Issue by zzzoom** [spack/spack#3006]
```libmumps_common.so``` or ```lib{s,d,c,z}mumps.so``` should link blas, lapack, etc to get a freestanding package. The change would require some patching to avoid ```libpord.so``` because +shared is currently implemented replacing ```ar``` with a linker for the whole package.

**Comment by v-dobrev** [comment]
@zzzoom, can you check if PR #7532 addresses this issue in a satisfactory manner?
Thanks!
