### ISSUE TITLE
site_packages_dir lacks documentation

### ISSUE THREAD

**Issue by citibeth** [spack/spack#3008]
@adamjstewart 
Search for it in the manual, it's not there...  In addition to the basic stuff, the following should be answered:

1. How does it automagically appear out of nowhere without being declared?  Under what conditions does it appear or not?  Why do some uses of it in the code base go through `spec['python'].package` while others rely on automagic?  (As before... automagic can obfuscate; especially if it's a relatively rarely-used feature that people don't have under their fingertips).

2. Does this work when using a externally-installed Python, declared in `packages.yaml`?

3. Should probably document that these are relative paths, with an implied base of `spec.prefix`.  Does that mean they're not valid `install()`, which is normally run from the stage?

**Comment by adamjstewart** [comment]
I'm not sure if this is worth documenting. It isn't a commonly needed feature, most Python packages extend the `PythonPackage` base class. For packages that have Python bindings, PR reviewers can handle mentioning this feature.
