### ISSUE TITLE
variant resolution is overly strict

### ISSUE THREAD

**Issue by trws** [spack/spack#303]
A `depends_on()` with no variants specified is concretized as requiring a version built with _exactly default variants_ because of the `concretize_variants` behavior.  I would contend that this is unnecessary, and actually unfortunate.  This is the root cause of #267 for example, and requires rebuilds to get a _less_ complete version when variants are used to enable extra features.  For example, testing the new llvm rework by adding a dependent rust compiler package, depending on `llvm` required a rebuild of llvm because the installed version had `+gold` when the default was `-gold`.

Why are variants this draconian, rather than accepting any package that matches all _specified_ variants?

**Comment by trws** [comment]
At @tgamblin 's behest I've taken a look at generating a unit test reproducer for this, and actually don't seem to have much luck getting it to show up with `spec.satisfies()`.  That said, it shows up pretty much immediately just on the command line, or with a package.  I'm fully willing to admit there may be something I'm doing wrong here, but this is what I'm seeing.

jemalloc+stats does not satisfy jemalloc:
```
scogland at rzalastor2 in ~/spack (llvm-rework●●)
$ spack install jemalloc+prof+stats
==> Installing jemalloc
==> Trying to fetch from https://github.com/jemalloc/jemalloc/releases/download/4.0.4/jemalloc-4.0.4.tar.bz2
######################################################################## 100.0%
==> Staging archive: /g/g12/scogland/spack/var/spack/stage/jemalloc-4.0.4-de2oo4f3slt2swusob4jkmolrxjupu4e/jemalloc-4.0.4.tar.bz2
==> Created stage in /g/g12/scogland/spack/var/spack/stage/jemalloc-4.0.4-de2oo4f3slt2swusob4jkmolrxjupu4e.
==> No patches needed for jemalloc.
==> Building jemalloc.
==> Successfully installed jemalloc.
  Fetch: 1.66s.  Build: 11.52s.  Total: 13.17s.
[+] /g/g12/scogland/spack/opt/spack/chaos_5_x86_64_ib/gcc-5.3.0/jemalloc-4.0.4-de2oo4f3slt2swusob4jkmolrxjupu4e

scogland at rzalastor2 in ~/spack (llvm-rework●●)
$ spack install jemalloc+prof
==> Installing jemalloc
==> Trying to fetch from https://github.com/jemalloc/jemalloc/releases/download/4.0.4/jemalloc-4.0.4.tar.bz2
######################################################################## 100.0%
==> Staging archive: /g/g12/scogland/spack/var/spack/stage/jemalloc-4.0.4-wl6eoh44fmlwt4himweeu23jjmxn7kap/jemalloc-4.0.4.tar.bz2
==> Created stage in /g/g12/scogland/spack/var/spack/stage/jemalloc-4.0.4-wl6eoh44fmlwt4himweeu23jjmxn7kap.
==> No patches needed for jemalloc.
==> Building jemalloc.
==> Successfully installed jemalloc.
  Fetch: 1.48s.  Build: 11.96s.  Total: 13.44s.
[+] /g/g12/scogland/spack/opt/spack/chaos_5_x86_64_ib/gcc-5.3.0/jemalloc-4.0.4-wl6eoh44fmlwt4himweeu23jjmxn7kap
```

A prototype rust package, which contains the line `depends_on('jemalloc')` after the above shows this behavior:
```
scogland at rzalastor2 in ~/spack (llvm-rework●●)
$ spack find jemalloc
==> 2 installed packages.
-- chaos_5_x86_64_ib / gcc@5.3.0 --------------------------------
jemalloc@4.0.4+prof~stats  jemalloc@4.0.4+prof+stats

scogland at rzalastor2 in ~/spack (llvm-rework●●)
$ spack install rust
==> Installing rust
==> python is already installed in /g/g12/scogland/spack/opt/spack/chaos_5_x86_64_ib/gcc-5.3.0/python-2.7.11-47mkfjgywa5yj5koqrwubjz3lxack7fh.
==> Installing jemalloc
==> Already downloaded /g/g12/scogland/spack/var/spack/stage/jemalloc-4.0.4-hiuikzewyiudf6c74jxvdiynfehgs3dn/jemalloc-4.0.4.tar.bz2.
==> Already staged jemalloc in /g/g12/scogland/spack/var/spack/stage/jemalloc-4.0.4-hiuikzewyiudf6c74jxvdiynfehgs3dn.
==> No patches needed for jemalloc.
==> Building jemalloc.
```

Neither jemalloc is found and used where "jemalloc" without any variants was specified.  This does not seem to conform to the model I think is intended by default.

**Comment by mathstuf** [comment]
See #839 for an outline of an algorithm to implement this.
