### ISSUE TITLE
Spack default compiler flags don't appear to work

### ISSUE THREAD

**Issue by serbanmaerean** [spack/spack#3039]
I am using the default IBM XL compiler flags, currently defined as -qzerosize.  It appears that the default flags is not added to the compiler flags when I tried to build netlib-lapack. I have to add the -qzerosize flags explicitly in the package.py file.
This used to work as recently as last week.

**Comment by becker33** [comment]
@serbanmaerean do you still see this error? In which package are you seeing this?

**Comment by alalazo** [comment]
Closing for lack of reply. Reopen if still relevant.
