### ISSUE TITLE
Spec Not Concretizing, Mysteriously

### ISSUE THREAD

**Issue by citibeth** [spack/spack#3056]
@tgamblin 

See #3055 for a change I made in my Spack (added `preferred=True` to a single version of `netcdf`).  With that PR in place, I get the following error on a clean Spack (nothing in `~/.spack`):
```
$ bin/spack spec netcdf
Input spec
--------------------------------
netcdf

Normalized
--------------------------------
netcdf
    ^hdf5
        ^zlib@1.2.5:
    ^m4

Concretized
--------------------------------
==> Error: Invalid spec: 'hdf5@1.10.0-patch1%clang@7.3.0-apple+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe arch=darwin-elcapitan-x86_64'. Package hdf5 requires version :1.8, but spec asked for 1.10.0-patch1
```

**Comment by citibeth** [comment]
Aack... too many changes slipped through in #3055.  All I meant to do was add `preferred=True` on one line.  All the other changes should not affect the bug being reported here.

**Comment by citibeth** [comment]
More info on the bug.  I removed `preferred=True` from `netcdf`, and set it in `packages.yaml` instead:
```
    netcdf:
        version: [4.4.0]
```
The same bug happened.  Then I added this to `packages.yaml` as well:
```
    hdf5:
        version: [1.8.18]
```
Now, concretization works:
```
     7y4rvr3  netcdf@4.4.0%gcc@4.9.3~cdmremote~dap~hdf4 maxdims=1024 maxvars=8192+mpi~parallel-netcdf+shared arch=linux-centos7-x86_64
     bujc7h6      ^hdf5@1.8.18%gcc@4.9.3+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe arch=linux-centos7-x86_64
[+]  2ew2gg7          ^openmpi@1.10.1%gcc@4.9.3~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-centos7-x86_64
[+]  nygoq6c              ^hwloc@1.11.4%gcc@4.9.3 arch=linux-centos7-x86_64
[+]  a6hzhtg                  ^libpciaccess@0.13.4%gcc@4.9.3 arch=linux-centos7-x86_64
[+]  q5ztpkl                      ^libtool@2.4.6%gcc@4.9.3 arch=linux-centos7-x86_64
[+]  kmufpwm                          ^m4@1.4.17%gcc@4.9.3+sigsegv arch=linux-centos7-x86_64
[+]  ytewamh                              ^libsigsegv@2.10%gcc@4.9.3 arch=linux-centos7-x86_64
[+]  zmirozy                      ^pkg-config@0.29.1%gcc@4.9.3+internal_glib arch=linux-centos7-x86_64
[+]  36ec63z                      ^util-macros@1.19.0%gcc@4.9.3 arch=linux-centos7-x86_64
[+]  xsie4hd          ^zlib@1.2.8%gcc@4.9.3+pic arch=linux-centos7-x86_64
```

**Comment by citibeth** [comment]
@davydden This is the kind of bug that we still have in our version selection / concretization logic.  I don't know if it's in the code I wrote (while fixing other bugs), or in code I didn't touch.  But this is why I am cautious to changes in that part of the code.

**Comment by davydden** [comment]
@citibeth I understand why you are cautious. i think this problem should be fairly easy to reproduce in unit tests by adding a few mockup packages in the same way as what I do for `preferred` tests in https://github.com/LLNL/spack/pull/1983 . Any solution to this specific issue **must have** unit/regression tests so that next time a new conretization algorithm is introduced, some feature is added or code is re-factored, this specific problem won't re-appear.
