### ISSUE TITLE
Standardize Spack Environment API

### ISSUE THREAD

**Issue by citibeth** [spack/spack#3114]
Add `__setitem__()` and`__getitem__()` to Spack environment class, so we don't have to use the nonstandard `env.get()` and `env.set()`.

**Comment by alalazo** [comment]
Which class are you referring to?

**Comment by citibeth** [comment]
Not sure what class.  It's the class of the arguments passed to `setup_environment()`.

**Comment by citibeth** [comment]
I want to do something like this, which is standard Python:
```
def setup_environment(spack_env, run_env):
    run_env['PATH'] = spec.prefix
```
instead of this, which is non-standard:
```
def setup_environment(spack_env, run_env):
    run_env.set('PATH', spec.prefix)
```

**Comment by alalazo** [comment]
I think you got the semantic wrong. The class is `EnvironmentModifications` and is a simple stack of commands (as in the *command* pattern) that can be either:
- inspected, transformed, etc.
- evaluated and consumed

The python line:
```python
run_env.set('PATH', spec.prefix)
```
means "push on the stack a command to set the environment variable `PATH` to the value `self.prefix`" not "set the value of the key `PATH` to `self.prefix`". There's no method `get` in the class.

**Comment by citibeth** [comment]
Ahh... very clever.  A `__setitem__()` command would still be easier to
use, since that's how we're used to setting env vars with `os.environ`.
But I also agree, it could also cause problems by making a turkey look sort
of like a duck, even though it's a turkey (see duck typing).
