### ISSUE TITLE
dyninst: failed installation on ubuntu-14.04-trusty

### ISSUE THREAD

**Issue by buaaluwentao** [spack/spack#3115]
recent, I was installing dyninst on my ubuntu-14.04-trusty(x86-64), when I install it with the cmd `spack install dyninst`, but unluckily I got this error 
```
/home/luwentao/software/spack/var/spack/repos/builtin/packages/dyninst/package.py:93, in install:
     66       def install(self, spec, prefix):
     67           if spec.satisfies('@:8.1'):
     68               configure("--prefix=" + prefix)
     69               make()
     70               make("install")
     71               return
     72   
     73           libelf = spec['libelf'].prefix
     74           libdwarf = spec['libdwarf'].prefix
     75   
     76           with working_dir('spack-build', create=True):
     77               args = ['..',
     78                       '-DBoost_INCLUDE_DIR=%s'    % spec['boost'].prefix.include,
     79                       '-DBoost_LIBRARY_DIR=%s'    % spec['boost'].prefix.lib,
     80                       '-DBoost_NO_SYSTEM_PATHS=TRUE',
     81                       '-DLIBELF_INCLUDE_DIR=%s'   % join_path(
     82                           libelf.include, 'libelf'),
     83                       '-DLIBELF_LIBRARIES=%s'     % join_path(
     84                           libelf.lib, 'libelf.so'),
     85                       '-DLIBDWARF_INCLUDE_DIR=%s' % libdwarf.include,
     86                       '-DLIBDWARF_LIBRARIES=%s'   % join_path(
     87                           libdwarf.lib, 'libdwarf.so')]
     88               if spec.satisfies('arch=linux-redhat7-ppc64le'):
     89                   args.append('-Darch_ppc64_little_endian=1')
     90               args += std_cmake_args
     91               cmake(*args)
     92               make()
  >> 93               make("install")
```
the last 20 lines of the `spack-build.out` is 
```
make[4]: Entering Directory `/tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-build/testsuite'
make[3]: Entering Directory `/tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-build'
cd /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-build && /home/luwentao/software/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/cmake-3.7.2-7m66awhkvsvaeqnunkb7uhxqto4bjztx/bin/cmake -E touch /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-stamp/LibIberty-build
[ 10%] Performing install step for 'LibIberty'
cd /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-build && install /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-build/libiberty.a /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/libiberty
cd /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-build && /home/luwentao/software/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/cmake-3.7.2-7m66awhkvsvaeqnunkb7uhxqto4bjztx/bin/cmake -E touch /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-stamp/LibIberty-install
[ 10%] Completed 'LibIberty'
/home/luwentao/software/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/cmake-3.7.2-7m66awhkvsvaeqnunkb7uhxqto4bjztx/bin/cmake -E make_directory /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/CMakeFiles
/home/luwentao/software/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/cmake-3.7.2-7m66awhkvsvaeqnunkb7uhxqto4bjztx/bin/cmake -E touch /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/CMakeFiles/LibIberty-complete
/home/luwentao/software/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/cmake-3.7.2-7m66awhkvsvaeqnunkb7uhxqto4bjztx/bin/cmake -E touch /tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build/binutils/src/LibIberty-stamp/LibIberty-done
make[2]: Entering Directory `/tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build'
[ 10%] Built target LibIberty
/tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/common/src/arch-x86.C: In static member function ‘static void NS_x86::ia32_instruction::initFlagTable(std::tr1::unordered_map<entryID, NS_x86::flagInfo>&)’:
/tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/common/src/arch-x86.C:1920:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
 void ia32_instruction::initFlagTable(dyn_hash_map<entryID, flagInfo>& flagTable)
      ^
make[2]: Entering Directory `/tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build'
make[1]: *** [common/CMakeFiles/common.dir/all] Error 2
make[1]: Entering Directory `/tmp/root/spack-stage/spack-stage-ylcQuu/dyninst/spack-build'
make: *** [all] Error 2
```
when I run `spack find` I can get this 
```
-- linux-ubuntu14-x86_64 / gcc@4.8 ------------------------------
boost@1.63.0
bzip2@1.0.6
cmake@3.7.2
libdwarf@20160507
libelf@0.8.13
ncurses@6.0
openssl@1.1.0d
perl@5.24.1
zlib@1.2.10
```
so , I can confirm that all the dependencies were installed successfully, so I do not know why the error occurred. should I install it on other unix like RH or 32bit environment?
any response welcomed, ^__^ , thanks.

**Comment by adamjstewart** [comment]
In my experience, if something fails during `make('install')`, it is often because the Makefile was poorly written and it can't handle parallel installations. Can you try running `spack install -j1 dyninst` and see if that solves your problem?

**Comment by buaaluwentao** [comment]
@adamjstewart thanks for your help , I install dyninst successfully ,again I want to install stat on my machine too, but when I run "./spack install stat" I got error as follows:
________________________________________________________________________________________________________

==> Error: Invalid spec: 'cairo@1.14.8%gcc@4.8+X arch=linux-ubuntu14-x86_64 ^autoconf@2.69%gcc@4.8 arch=linux-ubuntu14-x86_64 ^automake@1.15%gcc@4.8 arch=linux-ubuntu14-x86_64 ^bzip2@1.0.6%gcc@4.8+shared arch=linux-ubuntu14-x86_64 ^font-util@1.3.1%gcc@4.8 arch=linux-ubuntu14-x86_64 ^fontconfig@2.11.1%gcc@4.8 arch=linux-ubuntu14-x86_64 ^freetype@2.7%gcc@4.8 arch=linux-ubuntu14-x86_64 ^gettext@0.19.8.1%gcc@4.8+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu14-x86_64 ^glib@2.48.1%gcc@4.8 arch=linux-ubuntu14-x86_64 ^inputproto@2.3.2%gcc@4.8 arch=linux-ubuntu14-x86_64 ^kbproto@1.0.7%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libffi@3.2.1%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libpng@1.6.27%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libpthread-stubs@0.3%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libsigsegv^libtool@2.4.6%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libx11@1.6.3%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libxau@1.0.8%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libxcb@1.12%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libxdmcp@1.1.2%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libxext@1.3.3%gcc@4.8 arch=linux-ubuntu14-x86_64 ^libxml2@2.9.4%gcc@4.8~python arch=linux-ubuntu14-x86_64 ^libxrender@0.9.9%gcc@4.8 arch=linux-ubuntu14-x86_64 ^m4@1.4.18%gcc@4.8+sigsegv arch=linux-ubuntu14-x86_64 ^ncurses@6.0%gcc@4.8 arch=linux-ubuntu14-x86_64 ^openssl@1.1.0d%gcc@4.8 arch=linux-ubuntu14-x86_64 ^pcre@8.39%gcc@4.8+utf arch=linux-ubuntu14-x86_64 ^perl@5.24.1%gcc@4.8+cpanm arch=linux-ubuntu14-x86_64 ^pixman@0.34.0%gcc@4.8 arch=linux-ubuntu14-x86_64 ^pkg-config@0.29.1%gcc@4.8+internal_glib arch=linux-ubuntu14-x86_64 ^python@2.7.13%gcc@4.8~tk~ucs4 arch=linux-ubuntu14-x86_64 ^readline@6.3%gcc@4.8 arch=linux-ubuntu14-x86_64 ^renderproto@0.11.1%gcc@4.8 arch=linux-ubuntu14-x86_64 ^sqlite@3.8.5%gcc@4.8 arch=linux-ubuntu14-x86_64 ^tar^util-macros@1.19.1%gcc@4.8 arch=linux-ubuntu14-x86_64 ^xcb-proto@1.12%gcc@4.8 arch=linux-ubuntu14-x86_64 ^xextproto@7.3.0%gcc@4.8 arch=linux-ubuntu14-x86_64 ^xproto@7.0.29%gcc@4.8 arch=linux-ubuntu14-x86_64 ^xtrans@1.3.5%gcc@4.8 arch=linux-ubuntu14-x86_64 ^xz@5.2.3%gcc@4.8 arch=linux-ubuntu14-x86_64 ^zlib@1.2.10%gcc@4.8+pic+shared arch=linux-ubuntu14-x86_64'. Package cairo requires variant ~X, but spec asked for +X
_______________________________________________________________________________________________________________________
what should I do? ^__^, thanks.

**Comment by adamjstewart** [comment]
Glad you got `dyninst` working!

The error message you are seeing for `stat` is a known bug in our concretization algorithm (ping @tgamblin). You have two options for a workaround. From the command line, you can run:
```
$ spack install stat ^cairo+X ^gtkplus+X ^pango+X
```
Or, if you want a more permanent solution, you can edit (or create) a `~/.spack/packages.yaml` file that contains:
```yaml
packages:
  all:
    variants: [+X]
```
Then `spack install stat` should work as expected.

**Comment by buaaluwentao** [comment]
@adamjstewart I sorry to disturb   you again(^__^),I run the cmd "sudo ./spack install stat ^cairo+X ^gtkplus+X ^pango+X"as told, but when it goes to install icu4c, it occurs error as follows 
____________________________________________________________
==> Error: ProcessError: Command exited with status 2:
    'make' 'check'
_____________________________________________________________
I alse tried "sudo ./spack install -j1 stat ^cairo+X ^gtkplus+X ^pango+X" because I met the same error when installing dyninst, but it did not work(^__^), can you help me?
the last the 20 lines of the spack-build.out as follows
_____________________________________________________________
  }   /c_layout  (6ms)  
  c_paragraph  {
   GlyphToCharTest                           ---[OK]  
  }  
 }   / (./letest)  (14ms)  
 
[All tests passed successfully...]
Elapsed Time: 00:00:00.014
make[2]:正在离开目录 `/tmp/root/spack-stage/spack-stage-plo0E8/icu/source/test/letest'
-------------
| ***     FAILING TEST SUMMARY FOR:              cintltst  
/tstxtbd/cbiapts/TestBreakIteratorSuppressions
| *** END FAILING TEST SUMMARY FOR:              cintltst
---------------
ALL TESTS SUMMARY:
ok:  testdata intltest iotest letest
===== ERRS:  cintltst
make[1]: *** [check-recursive] 错误 1
make[1]:正在离开目录 `/tmp/root/spack-stage/spack-stage-plo0E8/icu/source/test'
make: *** [check-recursive] 错误 2

_____________________________________________________________
vary thank you(^__^).

**Comment by adamjstewart** [comment]
You shouldn't need to run sudo ever with Spack. I'm not sure why the tests are failing, but if you run `spack edit icu4c` and comment out `make check` you should be able to get past it.

**Comment by buaaluwentao** [comment]
@adamjstewart , thank you for your response(^__^)! I have solved the problem above by comment the "make check",and it goes smoothly until it installs stat, the error information as follows
__________________________________________________________________
==> No patches needed for stat
==> Building stat [Package]
==> Executing phase : 'install'
/home/luwentao/software/spack/var/spack/repos/builtin/packages/stat/package.py:77, in install:
     63       def install(self, spec, prefix):
     64           configure_args = [
     65               "--enable-gui",
     66               "--prefix=%s" % prefix,
     67               "--with-launchmon=%s"   % spec['launchmon'].prefix,
     68               "--with-mrnet=%s"       % spec['mrnet'].prefix,
     69               "--with-graphlib=%s"    % spec['graphlib'].prefix,
     70               "--with-stackwalker=%s" % spec['dyninst'].prefix,
     71               "--with-libdwarf=%s"    % spec['libdwarf'].prefix
     72           ]
     73           if '+dysect' in spec:
     74               configure_args.append('--enable-dysectapi')
     75           if '~examples' in spec:
     76               configure_args.append('--disable-examples')
  >> 77           configure(*configure_args)
     78   
     79           make("install")
___________________________________________________________________
and the last few lines of spack-build.out as follows 
——————————————————————————————————————
checking for /home/luwentao/software/spack/lib/spack/env/gcc/g++ option to produce PIC... -fPIC -DPIC
checking if /home/luwentao/software/spack/lib/spack/env/gcc/g++ PIC flag -fPIC -DPIC works... yes
checking if /home/luwentao/software/spack/lib/spack/env/gcc/g++ static flag -static works... yes
checking if /home/luwentao/software/spack/lib/spack/env/gcc/g++ supports -c -o file.o... yes
checking if /home/luwentao/software/spack/lib/spack/env/gcc/g++ supports -c -o file.o... (cached) yes
checking whether the /home/luwentao/software/spack/lib/spack/env/gcc/g++ linker (/home/luwentao/software/spack/lib/spack/env/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for rsh... /usr/bin/rsh
checking for python... /home/luwentao/software/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/python-2.7.13-yypjawdznorcqm34udm2vwb6apvvlsqa/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking Python include dir... /home/luwentao/software/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/python-2.7.13-yypjawdznorcqm34udm2vwb6apvvlsqa/include/python2.7
checking for swig... swig
checking for dot... /home/luwentao/software/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/graphviz-2.38.0-v56tgik46winwezj3izztua624bulrdn/bin/dot
checking for dwarf_init in -ldwarf... yes
checking for walker.h... yes
checking for libstackwalk... configure: error: libstackwalk is required.  Specify libstackwalk prefix with --with-stackwalker
———————————————————————————————————————————
I know with-stackwalker was not specified right(^__^), but you can see
____________________________________________________________________________
luwentao@luwentao:~/software/spack/bin$ ./spack find
==> 71 installed packages.
-- linux-ubuntu14-x86_64 / gcc@4.8 ------------------------------
atk@2.20.0      font-util@1.3.1               harfbuzz@0.9.37    libgpg-error@1.21     libxml2@2.9.4      py-py2cairo@1.10.0   xextproto@7.3.0
autoconf@2.69   fontconfig@2.11.1             help2man@1.47.4    libpng@1.6.27         libxrender@0.9.9   py-pygobject@2.28.3  xproto@7.0.29
automake@1.15   freetype@2.7                  icu4c@57.1         libpthread-stubs@0.3  m4@1.4.18          py-pygtk@2.24.0      xtrans@1.3.5
bison@3.0.4     gdk-pixbuf@2.31.2             inputproto@2.3.2   libsigsegv@2.10       mrnet@5.0.1-2      python@2.7.13        xz@5.2.3
boost@1.63.0    gettext@0.19.8.1              jpeg@9b            libtiff@4.0.6         ncurses@6.0        readline@6.3         zlib@1.2.10
bzip2@1.0.6     ghostscript@9.18              kbproto@1.0.7      libtool@2.4.6         openssl@1.1.0d     renderproto@0.11.1
cairo@1.14.8    glib@2.48.1                   launchmon@1.0.2    libx11@1.6.3          pango@1.40.3       sqlite@3.8.5
cmake@3.7.2     gobject-introspection@1.48.0  libdwarf@20160507  libxau@1.0.8          pcre@8.39          swig@3.0.11
dyninst@9.2.1b  graphlib@3.0.0                libelf@0.8.13      libxcb@1.12           perl@5.24.1        tar@1.29
expat@2.2.0     graphviz@2.38.0               libffi@3.2.1       libxdmcp@1.1.2        pixman@0.34.0      util-macros@1.19.1
flex@2.6.3      gtkplus@2.24.31               libgcrypt@1.6.2    libxext@1.3.3         pkg-config@0.29.1  xcb-proto@1.12
__________________________________________________________________________
dyninst is just there , what should I do(can I just do it via hard code?)?

**Comment by adamjstewart** [comment]
Looks like it's missing a dependency. You'll need to add a dependency on `libstackwalk`. If a package does not already exist, you'll need to write one. See our Packaging Guide for details on how to do that.

**Comment by alalazo** [comment]
Closing as stale for more than 2 years. Feel free to reopen if still an issue.
