### ISSUE TITLE
Document `spack diy`

### ISSUE THREAD

**Issue by citibeth** [spack/spack#3116]
`spack diy` is never directly discussed in the manual.  This needs to be fixed.

**Comment by citibeth** [comment]
To use `spack diy`:

1. Do a `git checkout` or equivalent on the package you wish to install.
2. `cd` to the top level of that package's sources
3. Run `spack diy mypackage@<version>`, where `<version>` can be anything you like.

Spack will build and install your downloaded source with that version.

**Comment by alalazo** [comment]
There's since a couple of months an entire [section of our tutorial](https://spack-tutorial.readthedocs.io/en/latest/tutorial_developer_workflows.html) that shows how to use `spack dev-build` previously known as `spack diy`.
