### ISSUE TITLE
Ncurses spack build appears to not yield `ncursesw6-config` OR Htop has a bug

### ISSUE THREAD

**Issue by TheQueasle** [spack/spack#3126]
As the name suggests, ~I'm not 100% sure if this is a bug in `spack` or `htop` but~(see EDIT) in both the **develop** and **v0.10.0** branches, `ncurses` does not use lib-suffixes when compiling version 6.0.   
Version 5.9 seems to not have this issue.

This was discovered while attempting to compile `htop ^ncurses@6.0` via spack and finding that it failed to use the located ncurses headers leading to an `htop` interface lacking in text.
```
configure: WARNING: ncursesw/curses.h: present but cannot be compiled
configure: WARNING: ncursesw/curses.h:     check for missing prerequisite headers?
configure: WARNING: ncursesw/curses.h: see the Autoconf documentation
configure: WARNING: ncursesw/curses.h:     section "Present But Cannot Be Compiled"
configure: WARNING: ncursesw/curses.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------- ##
configure: WARNING:     ## Report this to hisham@gobolinux.org ##
configure: WARNING:     ## ----------------------------------- ##
```

This appears to be due to `htop` looking for `ncurses` with the lib-suffixes, but the default spack install of `ncurses` disables this with `--disable-lib-suffixes`.  Ncurses 5.9 does not have `--disable-lib-suffixes` as an option...at least it looks that way after a quick grep of its INSTALL doc.

From ncurses 6.0 docs:
> --disable-lib-suffixes
> 
> Suppress the “w”, “t” or “tw” suffixes which normally would be added to the library names for the --enable-widec and --with-pthread options.

There is an open issue at https://github.com/hishamhm/htop/issues/573 that seems to be related to what I'm seeing here, so depending on the debate of lib-suffixes V. no lib-suffixes, this may not be something Spack will need to address.

[EDIT] Honestly, after doing more digging on this issue, it *seems* like this is more of an `htop` issue than a `spack` issue...but I figured I'd submit this to get record of this issue.  Hopefully I'm not the only one that can reproduce this issue :expressionless:

**Comment by citibeth** [comment]
Do you have suggested solutions?  Should we allow the Spack ncurses to build with lib-suffixes?

**Comment by TheQueasle** [comment]
I see three options.

1. Just let it ride until `htop` fixes the bug.
2. Add a variant to the `ncurses` spack package to allow building with lib-suffixes.
3. ~Add a dependency of `ncurses@5.9` to the `htop` spack package until it is fully compatible with an ncurses install sans lib-suffixes.~

After testing the third option, I found that `htop` still exhibited the same missing UI elements issue...so even though 5.9 built with the lib-suffixes, `htop` still had issues using the libraries for some reason.

So far, I can get spack's `htop` to build successfully by using spack's `ncurses@6.0` (with lib-suffixes enabled).

Hopefully, the author of `htop` will contact me back soonish so I can help debug this from an `htop` perspective too.

**Comment by alalazo** [comment]
@TheQueasle Any update?

**Comment by TheQueasle** [comment]
I've not heard from the htop dev and my latest `spack install htop` from a fresh clone of spack (develop branch) worked fine.

So - either the issue was completely on my end or it was fixed.

Either way I'm ok with closing this one and re-opening it if needed.
