### ISSUE TITLE
`spack versions` picking up URL from patch list

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#3129]
I'm seeing some strange behavior with the nwchem package. If you hack the package to add:
```python
url = "http://www.nwchem-sw.org/images/Nwchem-6.6.revision27746-src.2015-10-20.tar.gz"
```
and run:
```
$ spack versions nwchem
==> Error: Couldn't detect version in: http://www.nwchem-sw.org/images/Notdir_fc.patch.gz
```
This URL comes from `urls_for_patches`. Any idea why it would be picked up instead of the package-level `url`?

**Comment by davydden** [comment]
maybe @alalazo has an idea, he fixed patches in https://github.com/LLNL/spack/pull/2039

**Comment by alalazo** [comment]
Whoa, I missed this and it dates back to February! Confirmed.
