### ISSUE TITLE
Document `spack test`

### ISSUE THREAD

**Issue by citibeth** [spack/spack#3154]
The `spack test` command is completely lacking in documentation.  See #3139

**Comment by adamjstewart** [comment]
To be fair, we actually do have some basic documentation in the [Contribution Guide](http://spack.readthedocs.io/en/latest/contribution_guide.html#unit-tests), but we also need something in the [Developer Guide](http://spack.readthedocs.io/en/latest/developer_guide.html#spack-test) and instructions on how to write your own unit tests. See also: #1935.

**Comment by alalazo** [comment]
Closing as stale and we have basic docs for this. Feel free to reopen if you think something is missing.
