### ISSUE TITLE
AutotoolsPackage should recursively update config.guess and config.sub

### ISSUE THREAD

**Issue by robertdfrench** [spack/spack#3160]
Some package maintainers put `config.guess` and `config.sub` in places other than the top-level repo. This causes problems on Power systems, because subclasses of AutotoolsPackage do not update these files automatically when they are in nonstandard places.

I can submit a fix for this that recursively finds and updates those two files, but I wanted to see if anyone has any moral or philosophical objections first.

**Comment by robertdfrench** [comment]
@JRWynneIII we should pair on this if folks think it is not inherently problematic.

**Comment by adamjstewart** [comment]
Are those files located in a directory other than the one that contains the configure script? I know we already have workarounds in place for configure scripts located in a subdirectory.

**Comment by robertdfrench** [comment]
Yup! Hypre puts `configure` in `src`, but `config.guess` and `config.sub` in `src/config`. Parallel-netcdf does something similar. Can you point me do some docs or examples of the workarounds so I can educate myself?

**Comment by robertdfrench** [comment]
@mpbelhorn tagging you on this as well

**Comment by robertdfrench** [comment]
Oh, I see what you are saying @adamjstewart , the package definitions change the working directory to wherever `configure` is, and then the patching happens correctly. That makes sense. I would like the patching to descend (perhaps just one level would be sufficient) from wherever `configure` is

**Comment by alalazo** [comment]
Not sure if it is relevant, but maybe @lee218llnl may have some insight on this (see #2221)

**Comment by lee218llnl** [comment]
@alalazo The problem I mentioned in #2221 is a little different. For a package like graphviz, it was able to find and patch the config.guess just fine. The problem was that graphviz also contained source for libltdl that it was separately configuring. Short of checking every sub directory, I don't know if there is a good way to catch that particular issue.

**Comment by adamjstewart** [comment]
Alternatively, we could do something similar to what we did for `configure`, where we add an attribute that specifies the location of `config.guess` for a particular package. Of course, this assumes that there is only a single `config.guess` in a single directory. But even if we do a recursive search, it shouldn't be a big performance impact.

**Comment by adamjstewart** [comment]
@alalazo I completely forgot about this issue. A lot of newer issues/PRs are hitting this. We should fix this.

**Comment by alalazo** [comment]
Fixed in #18347
