### ISSUE TITLE
Unable to build Numpy with Intel 17

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#3204]
@davydden @glennpj @alalazo 

I'm trying to build `py-numpy` with Intel MKL, but although the build succeeds, numpy cannot be imported:
```
$ python -c 'import numpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/intel-17.0.1/py-numpy-1.12.0-r7qapsmckwr6jjvb6llkoufk36g5t36h/lib/python2.7/site-packages/numpy-1.12.0-py2.7-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/intel-17.0.1/py-numpy-1.12.0-r7qapsmckwr6jjvb6llkoufk36g5t36h/lib/python2.7/site-packages/numpy-1.12.0-py2.7-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/intel-17.0.1/py-numpy-1.12.0-r7qapsmckwr6jjvb6llkoufk36g5t36h/lib/python2.7/site-packages/numpy-1.12.0-py2.7-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/intel-17.0.1/py-numpy-1.12.0-r7qapsmckwr6jjvb6llkoufk36g5t36h/lib/python2.7/site-packages/numpy-1.12.0-py2.7-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/intel-17.0.1/py-numpy-1.12.0-r7qapsmckwr6jjvb6llkoufk36g5t36h/lib/python2.7/site-packages/numpy-1.12.0-py2.7-linux-x86_64.egg/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```
Does anyone know how to get numpy + MKL working?

P.S. My import tests from #2869 will detect this type of failed build before the installation is complete. On the current develop, I didn't notice there was a problem with numpy until I tried building scipy.

**Comment by davydden** [comment]
the hack from https://github.com/LLNL/spack/pull/2365 was to use `mkl_rt`, this should work. Do you have it in your MKL build?

**Comment by adamjstewart** [comment]
Looks like it:
```
$ find . -name '*mkl_rt*'
./compilers_and_libraries_2017.1.132/linux/mkl/lib/ia32_lin/libmkl_rt.so
./compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin/libmkl_rt.so
./compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin_mic/libmkl_rt.so
```
I'm going to follow https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl step-by-step and see where it gets me.

**Comment by davydden** [comment]
i think `MKL` is not looking inside `intel64_lin` https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/intel-mkl/package.py#L74
Probably Intel packages need to be updated for that, yet another, way to organise libs within the prefix... Why can't they just stick to one rule and use it throughout?!.

**Comment by adamjstewart** [comment]
We also aren't passing any include directories. Things are pretty broken. I'll see what I can hack together and put out a PR.

**Comment by adamjstewart** [comment]
We're adding `rpath` to the `site.cfg`, but https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl and http://www.scipy.org/scipylib/building/linux.html don't make any mention of this option. Where is this documented?

**Comment by davydden** [comment]
> We also aren't passing any include directories.

I see that Intel docu mention `include_dirs` but on scipy i see it being used with `mkl` only. 

> Where is this documented?

 `rpath` is here https://github.com/numpy/numpy/blob/master/site.cfg.example


The whole thing is a very tricky build config, I am not a big fan of it.

**Comment by davydden** [comment]
i think it's assumed to be `prefix/include`.

**Comment by adamjstewart** [comment]
Well it isn't, much like we can't assume lib is `lib` or `lib64`.

**Comment by davydden** [comment]
the problem is that 99% of sane packages have it under `prefix/include`. I think it's only Intel MKL which wants to be special. Even other blas/lapack (`openblas`, `atlas`, `netlib-lapack`) all comply with this assumption.

**Comment by adamjstewart** [comment]
I agree, Intel's hierarchy isn't fun to deal with. I was just going to add `../../include` to the end, but technically we're dealing with a possible list of directories. The fact that we allow a separate provider for blas and lapack makes things unnecessarily complicated. I wish we could just use `provides('blas-lapack')` and `depends_on('blas-lapack')` everywhere. Concretization doesn't even work if you use lapack different than blas.

**Comment by alalazo** [comment]
> I'm seeing a lot of nice support for automatically finding lib directories, but what about include directories?

That should come with #1875. I'll try to implement @tgamblin suggestions asap.

**Comment by adamjstewart** [comment]
@alalazo Cool. I'll work with the existing framework for now. If your PR gets merged before I'm done, I'll update to work with yours.

**Comment by adamjstewart** [comment]
Just tried building `py-numpy %intel +blas +lapack ^openblas` and found that it also exhibits the same problem as MKL, so the problem is not specific to MKL.

**Comment by adamjstewart** [comment]
Update: Either `rpath` isn't working at all, or we need to add the Intel compilers to the `rpath`. When I load the intel module, things magically work again.

**Comment by alalazo** [comment]
@adamjstewart FWIW, to make things compile with Intel on our clusters we had to write a [configuration file](https://software.intel.com/en-us/node/522780?language=fr) to:

1. point to the right `gcc` version (not the 4.4.7 that comes with `rhle6`)
1. `rpath` all the intel specific libraries

**Comment by adamjstewart** [comment]
@alalazo I actually followed your suggestions when setting up our Intel suite. I think the `intel-parallel-studio` does it automatically now.

Confirmed that specifying an `rpath` in `site.cfg` doesn't actually do anything:
https://github.com/numpy/numpy/issues/8653#issuecomment-282825531

**Comment by eschnett** [comment]
I see the same error on macOS Sierra with Apple's clang and OpenBLAS. It seems the problem is independent of Intel.

**Comment by s-sajid-ali** [comment]
>Confirmed that specifying an rpath in site.cfg doesn't actually do anything.

This happens because every time an intel compiler is loaded, the environment variable ```MKL_ROOT``` is also set and numpy searches the environment variables before checking the site.cfg. (@wscullin  pointed this out.)

Now, I have a numpy uses the correct blas/lapack library (I'm using Openblas) and get this error : 
```
ImportError: /home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/openblas-0.3.0-vhf45ztydok656i4lsuqhmlv2hehrbiz/lib/libopenblas.so.0: undefined symbol: for_cpystr
```
