### ISSUE TITLE
boost fails to build on Cray (Theta) with "illegal instruction"

### ISSUE THREAD

**Issue by roblatham00** [spack/spack#3209]
'spack install boost' fails trying to run 'b2 --clean' :  b2 was built with back-end instructions and so fails with 

```
 ./b2 --clean   
[1]    57337 illegal hardware instruction (core dumped)  ./b2 --clean
```
my default environment uses the intel compilers, though 'spack spec' suggests things are built with gcc-6.3.

I do not see a way to ask spack to tell boost to use "toolset=cray".  (was trying to follow advice found in https://cug.org/proceedings/cug2016_proceedings/includes/files/pap127.pdf , which did seem to work for a non-spack build)

**Comment by tgamblin** [comment]
@roblatham00: Spack knows what the default front-end compiler is, and we could expose that within the build -- we just don't currently do that.

We should probably patch the boost build so that `b2` is always built with the frontend compiler, and the other stuff is built with whatever the compiler is using.

This is related to @scheibelp's #2548, but it's a) different because `b2` isn't an explicit dependency -- it's a build tool created by a single package during its own x-compile build, and b) simpler, in that we just need to export a couple more variables to tell packages about the host compiler.

@scheibelp: do you know where in the boost build `b2` gets built and whether it would be easy to patch it as I'm describing?

**Comment by scheibelp** [comment]
> do you know where in the boost build b2 gets built and whether it would be easy to patch it as I'm describing?

b2 is built with bootstrap.sh. I suspect the solution is to invoke ```bootstrap --with-toolset=<frontend compiler toolset>``` and then write out user-config.jam with the backend compiler (and specifically to do this when the boost target does not match the frontend target). Assuming I'm right about that I think it would be fairly straightforward and I could try to get a PR out by the end of Monday 2/27.

**Comment by scheibelp** [comment]
> my default environment uses the intel compilers, though 'spack spec' suggests things are built with gcc-6.3

The best way to ensure building with intel is to include it in the spec: ```spack spec boost%intel``` or ```spack install boost%intel```

@tgamblin this suggests that this particular error message is not an issue with using the backend compiler to build b2 (although that problem may come up when spack tries to build boost with cce). In fact as of now there isn't a toolset entry for the cce compiler for boost's package.py. Once that is in place the problem you describe may come up.

**Comment by tgamblin** [comment]
@scheibelp: I think it may still be a backend issue -- gcc can still build for the backend or frontend OS on the cray... right @mamelara and @becker33?

@roblatham00 @wscullin: is the compute node arch on Theta different from the architecture on the login nodes?

**Comment by scheibelp** [comment]
> I think it may still be a backend issue -- gcc can still build for the backend or frontend OS on the cray

If that's true, then I presume it is some sort of compiler flag? In which case would a user creates two entries the same compiler paths but with different flags and targets?

> I do not see a way to ask spack to tell boost to use "toolset=cray"

Apologies as I didn't answer this one: at the moment there isn't a way. In many cases Spack picks a boost toolset based on the compiler (and there is a 1-to-1 mapping of compilers to boost toolsets). This may be a case which doesn't fit that.

**Comment by tgamblin** [comment]
@roblatham00: if you want to programmatically set `toolset=Cray`, even for intel compiler builds, you can check he platform like this:

```python
if 'platform=cray' in spec:
    # set boost args 
```

I'm still not sure boost will properly cross compile b2 if you do that, though, as on most Crays you can get away with compiling front end tools with the backend compiler, so it may not be build into their build.  But you can try that while @scheibelp is working on this...

**Comment by scheibelp** [comment]
I've requested access to a theta system so I should be able to resolve the issue. I don't think my 2/27 estimate was accurate though. I'll aim to provide an update by the end of the week (3/3).

**Comment by pramodskumbhar** [comment]
I am not sure if this is relevant for boost scenario here but if there are certain component needs to be built for front-end (in two-stage-installation), I have set cflags/cxxflags as: 

```
        if 'cray' in self.spec.architecture:
            flags = '-target-cpu=x86_64 -target-network=none'
            options.extend(['CFLAGS=%s' % flags,
                                        'CXXFLAGS=%s' % flags])
```

With this cray wrappers (`cc`, `CC`) will compile code for fronted-arch ([cray-docs](http://docs.cray.com/books/S-2801-1608/S-2801-1608.pdf)).
