### ISSUE TITLE
Unloading modules in compilers.yaml / packages.yaml

### ISSUE THREAD

**Issue by wscullin** [spack/spack#3211]
In addition to loading modules, it would be extremely useful to be able to unload modules. A use case would be removing Cray's LibSci from a PrgEnv to prevent silent linking of LibSci when another BLAS or LAPACK was intended.

**Comment by tgamblin** [comment]
@mamelara: is this related to your #3122 and should we jut be doing this automatically in the Cray build environment?

**Comment by tgamblin** [comment]
@mamelara: could we just add this `setup_platform_environment` in [`platforms/cray.py`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/platforms/cray.py#L101)?

**Comment by mamelara** [comment]
Hey Todd, yeah this is related. I thought I had the unloading of cray-libsci pushed but I must not have done it 😬 .

I'll add it to setup_platform_environment.

**Comment by alalazo** [comment]
@mamelara Any update on this? Can the issue be closed?

**Comment by alalazo** [comment]
Closing since no reply was given in the last year. Feel free to reopen if still an issue.
