### ISSUE TITLE
Spack-built Python does not have readline support

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#3269]
I noticed that the Python I built with Spack does not have readline support. Arrow keys can't be used, and the readline module can't be imported. But we have an explicit dependency on readline. Anyone know what's up?

**Comment by weijianwen** [comment]
I encountered similar readline-related issue with spack-built `python`, `r` and `octave`. `python@3` built within Spack doesn't work properly in the prompt line. Pressing `BackSpace` key does NOT delete the character, and it generates white space instead. I've tried the following builts:

```
$ spack install python@3.6.2 %gcc@5.4.0 ^readline@6.3
$ spack install python@3.6.2 %gcc@5.4.0 ^readline@7.0
```

My workaround is to use the readline library in CentOS 7. That is, define the following library in `packages.yaml`. 

```
readline:
    paths:
        readline@system: /usr
    version: [system]
    buildable: False
```

Then,

```
$ spack install python@3.6.2 %gcc@5.4.0 ^readline@system
```

**Comment by weijianwen** [comment]
The workaround above does NOT work for the octave pacakge. `BackSpace` still work inproperly in both CLI and GUI modes of octave.

The workaround is to build an octave package without dependecy of readline library.

```
spack install octave+qt~readline %gcc@5.4.0
```
