### ISSUE TITLE
How to find out how a package was built

### ISSUE THREAD

**Issue by certik** [spack/spack#3354]
Given an already built package `/chpcwgg`:
```
$ spack find -dlv /chpcwgg
==> 1 installed packages.
-- linux-ubuntu16-x86_64 / gcc@5.4.0 ----------------------------
chpcwgg    paraview@5.0.0+mpi~opengl2~osmesa~python+qt~tcl
icdmmm2        ^bzip2@1.0.6+shared
d6pxg3p        ^freetype@2.7
pey6g7a            ^libpng@1.6.27
zn23nl6                ^zlib@1.2.11+pic+shared
zswtuew        ^jpeg@9b
3wt4ges        ^libtiff@4.0.6
f4p6ysd            ^xz@5.2.3
4m6dx6f        ^libxml2@2.9.4~python
2uaqbv4        ^openmpi@2.0.2~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt
wapbsf2            ^hwloc@1.11.5
bdodwet                ^libpciaccess@0.13.4
ynzm5xe        ^qt@4.8.6~dbus~examples~gtk~krellpatch~mesa~phonon+webkit
urjozsf            ^fontconfig@2.11.1
no4jtxb                ^font-util@1.3.1
7n2gkck            ^glib@2.49.7
txkub5o                ^gettext@0.19.8.1+bzip2+curses+git~libunistring+libxml2+tar+xz
taazswe                    ^ncurses@6.0~symlinks
zpatvi2                    ^tar@1.29
jtrswbt                ^libffi@3.2.1
vw6umqx                ^pcre@8.39+utf
hhdrcae            ^gperf@3.0.4
fcftpse            ^icu4c@57.1
fre4loq            ^libmng@2.0.2
7kcrn6j                ^lcms@2.6
7mmucce            ^libxcb@1.12
uxq26an                ^libpthread-stubs@0.3
rywz5ym                ^libxau@1.0.8
3tu6t2x                ^libxdmcp@1.1.2
52wmhxm            ^openssl@1.0.2k
```
How do I find out the way it was built? In this example the answer is:
```
spack install paraview +qt ^qt +webkit %gcc@5.4.0
```
I want this so that I can build exactly the same package, but with some modification (perhaps enable Python in paraview, but keep the `qt` built exactly the way it was, and keep the compiler exactly the way it was).

Here is one way, that I am aware of, that does *not* work: you use `spack find` to nail the package, in this case here is how the session could go:
```
$ spack find paraview
==> 2 installed packages.
-- linux-ubuntu16-x86_64 / gcc@5.4.0 ----------------------------
paraview@5.0.0  paraview@5.0.0
$ spack find -dlv paraview
[...]
$ spack find -dlv paraview ^qt+webkit
==> 1 installed packages.
-- linux-ubuntu16-x86_64 / gcc@5.4.0 ----------------------------
chpcwgg    paraview@5.0.0+mpi~opengl2~osmesa~python+qt~tcl
icdmmm2        ^bzip2@1.0.6+shared
d6pxg3p        ^freetype@2.7
pey6g7a            ^libpng@1.6.27
zn23nl6                ^zlib@1.2.11+pic+shared
zswtuew        ^jpeg@9b
3wt4ges        ^libtiff@4.0.6
f4p6ysd            ^xz@5.2.3
4m6dx6f        ^libxml2@2.9.4~python
2uaqbv4        ^openmpi@2.0.2~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt
wapbsf2            ^hwloc@1.11.5
bdodwet                ^libpciaccess@0.13.4
ynzm5xe        ^qt@4.8.6~dbus~examples~gtk~krellpatch~mesa~phonon+webkit
urjozsf            ^fontconfig@2.11.1
no4jtxb                ^font-util@1.3.1
7n2gkck            ^glib@2.49.7
txkub5o                ^gettext@0.19.8.1+bzip2+curses+git~libunistring+libxml2+tar+xz
taazswe                    ^ncurses@6.0~symlinks
zpatvi2                    ^tar@1.29
jtrswbt                ^libffi@3.2.1
vw6umqx                ^pcre@8.39+utf
hhdrcae            ^gperf@3.0.4
fcftpse            ^icu4c@57.1
fre4loq            ^libmng@2.0.2
7kcrn6j                ^lcms@2.6
7mmucce            ^libxcb@1.12
uxq26an                ^libpthread-stubs@0.3
rywz5ym                ^libxau@1.0.8
3tu6t2x                ^libxdmcp@1.1.2
52wmhxm            ^openssl@1.0.2k
```
So I nailed it, except that if I try to build it (to check that I really got it):
```
$ spack install paraview ^qt+webkit
==> Error: paraview does not depend on qt
```
I see, I need to do this:
```
$ spack install paraview +qt ^qt+webkit
[...]
```
Oops, it starts building it with the wrong compiler. 

How can I make spack give me the exact spec for the package, that I can then use as a starting point for any modifications?

**Comment by tgamblin** [comment]
@certik: we don't store this right now but I would like to.

In particular, I think it would be really useful for environments.  Say the user has installed a bunch of stuff in a (notional, not implemented yet, but we're working on it) Spack environment:

```
spack install paraview ^qt+webkit
spack install fenics
spack install hdf5 +mpi
etc.
```

If you wanted to reproduce the user's build someplace, you could think about either reproducing it exactly (from the concrete spec) or functionally (from the abstract spec implied by the commands there).  The abstract spec basically tells you what the user depends on.

It would be pretty easy to add the abstract spec to the database for things that are explicitly installed -- we already track what is installed explicitly and what is only brought in as a dependency.

**Comment by citibeth** [comment]
This feeds into Spack Envrionments.  An environment will store the original spec and fully concretized spec.

The original question is somewhat ambiguous.  More than one user-supplied spec might have resulted in the same fully concretized spec getting installed.

**Comment by jrood-nrel** [comment]
I haven't thought about the implementation issues of this, but I would like to see `spack-build.out` move to the installation prefix at installation time, mainly to see the configure line.

**Comment by adamjstewart** [comment]
@jrood-nrel It already is. Check for `<prefix>/.spack/build.out`.

**Comment by alalazo** [comment]
@certik I think this is taken care of by Spack environments. In that case you have root specs in a manifest file `spack.yaml` and that's what gets built. Would that solve your issue?

**Comment by certik** [comment]
@alalazo I think so. I don't have time right now to test it, so I am going to close the issue and if there is any further problem, I can open a new one.
