### ISSUE TITLE
Docs: ways to change the build environment

### ISSUE THREAD

**Issue by citibeth** [spack/spack#3359]
From @tgamblin 

Alex:

You can!  Just set them the way you normally would in python from within the package.py file.  e.g.:

Spack adds an ‘env’ shortcut to os.environ, which you can use:

```
        def install(self, spec, prefix):
                env[‘VAR’] = “value"
```

You could just as easily use os.environ directly:

```
        import os
        ...
        def install(self, spec, prefix):
                os.environ[‘VAR’] = “value"
```

Or, if you’re using AutotoolsPackage or CmakePackage, you can use setup_environment:

```
        def setup_environment(self, spack_env, run_env):
                env[‘VAR’] = value
```

OR, equivalently:
```
        def setup_environment(self, spack_env, run_env):
                spack_env.set(‘VAR’, value)
```

There are two ways to do this because we need to store the run_env for later — that determines what goes in the module files generated for each package.  spack_env is provided for consistency but has basically the same effect as setting the environment variables directly, since setup_environment is executed before install() within the build environment.

**Comment by alalazo** [comment]
The other thing that `spack_env` provides over setting `env` directly is an analysis of what gets modified. So far it catches modifications that have no effect, like in:

- package `A` depends in some way on package `B`
- `A` wants to `unset FOO`, `B` wants to `set FOO=bar`

If you use `spack_env` you'll get a warning telling you what's happening, if you use `env` you'll just set a variable and later unset it without further clues on who did what.

**Comment by alalazo** [comment]
Closing as there's now [documentation for this](https://spack.readthedocs.io/en/latest/tutorial_advanced_packaging.html#package-s-build-environment)
