### ISSUE TITLE
trying to add IBM clang-gpu on ray.llnl.gov

### ISSUE THREAD

**Issue by JaeseungYeom** [spack/spack#3407]
This is a pre-production compiler. However, I am trying to take advantage of Spack.
So, I attempted to add it, and it did not work.
I tried it on installing Metis and failed as shown below. (Some of the characters are not correctly shown due to board limitations)
```
$ spack install metis %clang-gpu
==> Installing metis
==> Installing cmake
==> Installing ncurses
==> Using cached archive: /....../spack/var/spack/cache/ncurses/ncurses-6.0.tar.gz
==> Already staged ncurses-6.0-dmh6crdnvfnmxbdohokizawx35dtixvw in /....../spack/var/spack/stage/ncurses-6.0-dmh6crdnvfnmxbdohokizawx35dtixvw
==> Already patched ncurses
==> Building ncurses [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j160'
/....../spack/lib/spack/spack/build_systems/autotools.py:275, in build:
     270      def build(self, spec, prefix):
     271          """Makes the build targets specified by
     272          :py:attr:``~.AutotoolsPackage.build_targets``
     273          """
     274          with working_dir(self.build_directory):
  >> 275              inspect.getmodule(self).make(*self.build_targets)

See build log for details:
/var/tmp/.../spack-stage/spack-stage-3H_y8m/ncurses-6.0/spack-build.out
```
=========================================================
The last couple of lines in the file above contains the following
```
/var/tmp/.../ncurses-93ee4e.o: In function `wide_show_attr':
/var/tmp/.../ncurses-74fc3b.bc:(.text+0xefcc): undefined reference to `wattr_get'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:359: ncurses] Error 1
make[1]: Leaving directory '/var/tmp/.../spack-stage/spack-stage-3H_y8m/ncurses-6.0/test'
make: *** [Makefile:120: all] Error 2
```
========================================================
Here are the changes I made

1. modified two lines in `lib/spack/env/cc` as below:

from `cc|c89|c99|gcc|clang|icc|pgcc|xlc|xlc_r)`
to  `cc|c89|c99|gcc|clang|icc|pgcc|xlc|xlc_r|clang-gpu)`

from  `c++|CC|g++|clang++|icpc|pgc++|xlc++|xlc++_r)`
to  `c++|CC|g++|clang++|icpc|pgc++|xlc++|xlc++_r|clang++-gpu)`

2. Added a directory `spack/lib/spack/env/clang-gpu`
    and created symbolic links under the directory
```
    clang++-gpu -> ../cc
    clang-gpu -> ../cc
    f77 -> ../cc
    f90 -> ../cc
    f95 -> ../cc
    fc -> ../cc
    gfortran -> ../cc
```
3. Copied `lib/spack/spack/compilers/clang.py` to `lib/spack/spack/compilers/clang-gpu.py`
    and modified it as below:
```diff
$ diff clang-gpu.py clang.py

37c37
< class ClangGpu(Compiler):
---
> class Clang(Compiler):
39c39
<     cc_names = ['clang-gpu']
---
>     cc_names = ['clang']
42c42
<     cxx_names = ['clang++-gpu']
---
>     cxx_names = ['clang++']
51,52c51,52
<     link_paths = {'cc': 'clang-gpu/clang-gpu',
<                   'cxx': 'clang-gpu/clang++-gpu',
---
>     link_paths = {'cc': 'clang/clang',
>                   'cxx': 'clang/clang++',
55,56c55,56
<                   'f77': 'clang-gpu/gfortran',
<                   'fc': 'clang-gpu/gfortran'}
---
>                   'f77': 'clang/gfortran',
>                   'fc': 'clang/gfortran'}
158,159c158,159
<         if not self.is_apple or basename not in ('clang-gpu', 'clang++-gpu'):
<             return super(ClangGpu, self)._find_full_path(path)
---
>         if not self.is_apple or basename not in ('clang', 'clang++'):
>             return super(Clang, self)._find_full_path(path)
199c199
<         super(ClangGpu, self).setup_custom_environment(pkg, env)
---
>         super(Clang, self).setup_custom_environment(pkg, env)
240c240
<             bins = ['c++', 'c89', 'c99', 'cc', 'clang-gpu', 'clang++-gpu', 'cpp']
---
>             bins = ['c++', 'c89', 'c99', 'cc', 'clang', 'clang++', 'cpp']
```
4. Added lines to `~/.spack/linux/compilers.yaml`
```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/tcetmp/bin/clang-gpu
      cxx: /usr/tcetmp/bin/clang++-gpu
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: clang-gpu@3.8.0
    target: ppc64le
```
=========================================================
Any help would be appreciated. Thanks.

**Comment by adamjstewart** [comment]
All of the Spack changes seem correct. Are you able to build `ncurses` with `clang-gpu` on `ppc` outside of Spack? That's how I usually determine whether or not it's a Spack problem.

**Comment by adamjstewart** [comment]
@becker33 Can the parser handle compilers with a dash in the name? I wonder if this is being parsed as `metis %clang -gpu`. @JaeseungYeom Can you post the output of `spack spec metis %clang-gpu`? Do you have any other compilers in `~/.spack/linux/compilers.yaml`?

**Comment by JaeseungYeom** [comment]
I am able to build metis out of spack using clang-gpu by exporting CC=mpiclang-gpu and CXX=mpiclang++-gpu. However, I have not separately tried ncurses yet.

I only added clang-gpu to `~/.spack/linux/compilers.yaml`. The others in the file are the ones that were already in.

The attached is the output file.
[spack-build.zip](https://github.com/LLNL/spack/files/835344/spack-build.zip)

**Comment by adamjstewart** [comment]
> I am able to build metis out of spack

But what about `ncurses`?

> `CC=mpiclang-gpu` and `CXX=mpiclang++-gpu`

`mpiclang-gpu != clang-gpu`.

If you really want to tell if it's a problem with Spack, you need to do everything identically. Use `clang-gpu` to build `ncurses`, use the same flags, and run `make -j160` so that there are as few differences as possible. If there's any way to get the `ncurses` build to crash outside of Spack, then we know it isn't a Spack bug.

**Comment by JaeseungYeom** [comment]
I can confirm that I am able to build both metis-5.1.0 and ncurses-6.0 outside of spack by exporting CC=clang-gpu and CXX=clang++-gpu and `make -j160`

**Comment by adamjstewart** [comment]
Alright, we're making progress! Now, when you built it outside of Spack, did you add all of the patches in the `ncurses` package, and did you add the same configure flags? Are you sure the `pic_flag` for `clang-gpu` is the same as the one for `clang`? Did you use `CPPFLAGS=-P`? That caused problems with the Intel compilers so it was recently (today) switched to only apply to GCC. I don't think the RPATH handling would be causing problems since this package doesn't have any dependencies.

Btw, were you able to build any other packages aside from `ncurses`? That would really help to see if it is a problem with your `clang-gpu` support or if it's specific to `ncurses`.

**Comment by JaeseungYeom** [comment]
I did not apply any specific option. I simple unzip the packages downloaded by spack and built them as they are.
In config.log of ncurses, I see `ac_cv_env_CPPFLAGS_set=` and `ac_cv_env_CPPFLAGS_value=`

I am not sure about how to find out pic_flag. The below is what I see in clang-gpu.
```
#!/bin/sh
# Add path and settings in order to use IBM's OpenMP4 with GPU support
# Written by John Gyllenhaal at LLNL 1Oct2015

# These settings most likely to change with different installs
# Set CUDA_DIR based on ldd libomptarget.rtl.cuda.so (e.g., libcudart.so.7.5)
export CLANG_DIR=/usr/tcetmp/packages/clang-gpu/clang-gpu-2017-01-05-gcc-4.9.3b
export CUDA_DIR=/usr/local/cuda-8.0

# Need CUDA_DIR in path to find 'ptxas'
export PATH="${CUDA_DIR}/bin:${PATH}"
export LD_LIBRARY_PATH=${CUDA_DIR}

# Believe -lomptarget necessary to get OpenMP4 + GPU support
# Clang wrapper currently sets LIBRARY_PATH to where omptarget lives
# Don't link to -lomptarget-nvptx, causes odd link errors.
ADD_FOR_LINK=" -rpath ${CUDA_DIR}/lib64 -L${CUDA_DIR}/lib64 -L${CUDA_DIR}/nvvm/libdevice"

# Scan arguments to see if linking or compiling
for ARG in "$@"
do
  case ${ARG} in
    -c|-E)
        # Clang complains for -l, -L and -rpath if not linking
        ADD_FOR_LINK="";
  esac
done

# Execute clang wrapper with options for OpenMP4 + GPU support
exec $CLANG_DIR/bin/clang -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda --cuda-path=$CUDA_DIR "$@" $ADD_FOR_LINK
```
I was not able to build any other package. To be precise, I have not tried much.
Considering the clang-gpu restriction regarding exception throws, I first need to find the package that does not throw exception.
If you can recommend me several packages, I can try them out.

**Comment by JaeseungYeom** [comment]
Actually, I just tried out fftw.
```
./spack install fftw %clang
==> Installing fftw
==> Installing openmpi
==> Installing hwloc
==> Installing libpciaccess
==> util-macros is already installed in /usr/workspace/wsb/yeom2/ray/spack/opt/spack/linux-rhel7-ppc64le/clang-3.8.0/util-macros-1.19.1-niazltml3bdvxlivufsai6neiekns5od
==> Installing libtool
==> Installing m4
==> libsigsegv is already installed in /usr/workspace/wsb/yeom2/ray/spack/opt/spack/linux-rhel7-ppc64le/clang-3.8.0/libsigsegv-2.10-hfwcnstobk3pncqfykvf4uqays7pqiru
==> Using cached archive: /usr/workspace/wsb/yeom2/ray/spack/var/spack/cache/m4/m4-1.4.18.tar.gz
==> Already staged m4-1.4.18-kfeorc5xf7f2weswfgkffmcrecl6znq3 in /usr/workspace/wsb/yeom2/ray/spack/var/spack/stage/m4-1.4.18-kfeorc5xf7f2weswfgkffmcrecl6znq3
==> Already patched m4
==> Building m4 [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j160'
/usr/workspace/wsb/yeom2/ray/spack/lib/spack/spack/build_systems/autotools.py:275, in build:
     270      def build(self, spec, prefix):
     271          """Makes the build targets specified by
     272          :py:attr:``~.AutotoolsPackage.build_targets``
     273          """
     274          with working_dir(self.build_directory):
  >> 275              inspect.getmodule(self).make(*self.build_targets)

See build log for details:
  /var/tmp/yeom2/spack-stage/spack-stage-aERHF5/m4-1.4.18/spack-build.out
[spack-build.zip](https://github.com/LLNL/spack/files/835511/spack-build.zip)

```

**Comment by adamjstewart** [comment]
That doesn't tell me anything other than that the build crashed somewhere during `make`. So it looks like `clang-gpu` is just a wrapper around `clang`, so all of the flags should be the same. Are you able to build `ncurses` with `clang`? Can you try building a few simple packages like `zlib` or `gmp` with `clang-gpu`?

**Comment by JaeseungYeom** [comment]
I can build ncurses and zlib with clang in spack but not gmp.
I cannot build all three with clang-gpu.

**Comment by adamjstewart** [comment]
@JaeseungYeom is this still an issue?

**Comment by JaeseungYeom** [comment]
Well, I moved on. I am closing this.
