### ISSUE TITLE
/ before hash in spec causing No Such File Or Directory Error for debug log

### ISSUE THREAD

**Issue by mamelara** [spack/spack#3437]
I always see this whenever I use ``spack -vd install [package]``

```/global/u2/m/mamelara/spack/lib/spack/env/gcc/gcc: line 358: /global/u2/m/mamelara/spack-cc-libelf@0.8.13%gcc@6.1.0 arch=cray-CNL-ivybridge /x2yjrjr.in.log: No such file or directory```

**Comment by eschnett** [comment]
This is not due to the spacing, this is due to the slash `/` before the hash.

**Comment by tgamblin** [comment]
We should rename the debug logs for compilers -- the names date back to the very first versions of Spack.  They should also probably go in the build stage and not in the current working directory.

**Comment by alalazo** [comment]
> We should rename the debug logs for compilers -- the names date back to the very first versions of Spack.

Closing as this renaming has been done. @mamelara Feel free to reopen if there's anything still to be addressed
