### ISSUE TITLE
OpenMP crashes: Cannot install gcc and llvm simultaneously

### ISSUE THREAD

**Issue by eschnett** [spack/spack#3465]
I first built gcc (6.3) with a system compiler, then llvm (3.9) with that gcc, both via Spack. I then created a view that contained both gcc and llvm. My intention was to combine the respective Clang and Gfortran.

However, this lead to crashes and segfaults in applications built with that version of gcc. I tracked this down to a shared library confusion: Both gcc and llvm provide a shared library named `libgomp`. For gcc, this is the real thing, for llvm, this is a mere symbolic link to its `libomp`. (Since the two `libgomp` live in different places in the directory hierarchy of the view there is no immediate conflict.)

I can imagine several solutions:
- Remove the symbolic link for llvm
- Teach llvm to use gcc's libgomp directly (is that even possible?), as there is no need for two OpenMP implementations
- When linking applications, ensure that gcc and clang pick up the correct `libgomp`, even if used via a view, and ensure that that path is hard-coded

**Comment by alalazo** [comment]
Closing as stale. Feel free to reopen if you want to discuss this further.
