### ISSUE TITLE
Cray: Unable to target mic-knl on LANL's Trinity machine

### ISSUE THREAD

**Issue by KineticTheory** [spack/spack#3477]
Trinity has two types of back-end machines: haswell and mic-knl.  Spack works great for targeting the haswells.  When targeting the mic-knl nodes, I normally `module swap craype-haswell craype-mic-knl`, but I can't figure out how to do this with spack. BTW - All builds are done from the haswell front-end.

For example:
``` 
spack spec libelf%intel@17.0.1
...
libelf@0.8.13%intel@17.0.1 arch=cray-CNL-haswell
```

Okay that looks good for the haswells, but we want to target the mic-knl nodes:
``` 
spack spec libelf%intel@17.0.1 target=mic-knl
...
libelf@0.8.13%intel@17.0.1 arch=cray-CNL-mic-knl
```

That looks good, let's install:
``` 
spack install libelf%intel@17.0.1 target=mic-knl
...
 % spack install libelf%intel@17.0.1  target=mic-knl
==> Installing libelf
==> Error: ValueError: Can't recreate arch for spec cray-CNL-mic-knl on current arch cray-CNL-haswell; spec architecture is too different
/usr/projects/draco/vendors/spack.tt.20170316/lib/spack/spack/package.py:893, in architecture:
     887      @property
     888      def architecture(self):
     889          """Get the spack.architecture.Arch object that represents the
     890          environment in which this package will be built."""
     891          if not self.spec.concrete:
     892              raise ValueError("Can only get the arch for concrete package.")
  >> 893          return spack.architecture.arch_for_spec(self.spec.architecture)
```

Any suggestions for debugging this? How do I know that `mic-knl` is even a valid target for spack?

**Comment by pramodk** [comment]
Same issue for me (#3818).

**Comment by alalazo** [comment]
Is this still an issue (after #3206)?

**Comment by KineticTheory** [comment]
Whoa!  This is an old issue.  I'll put it on my list to check.  If it is resolved, I'll close this issue.

**Comment by alalazo** [comment]
@KineticTheory Very old indeed. I'm trying to clean up the backlog a little... Thanks for having a look at this.

**Comment by KineticTheory** [comment]
I'm no longer looking for this solution.  Not sure if it is still broken or not.
