### ISSUE TITLE
Do not use "~" in the mirror path, use the full path instead

### ISSUE THREAD

**Issue by weijianwen** [spack/spack#3493]
I followed Spack's Mirrors Guide on http://spack.readthedocs.io/en/latest/mirrors.html?highlight=mirror to configure a local mirror. After adding packages, however, curl kept complaining about failing to fetch `/spack/mirror/xxx` file which did exist there.

```
$ spack mirror add local_filesystem file://~/spack/mirror
```

It turned out that curl doesn't interprete `~` as `$HOME`. As a workaround, mirror path should be specified in full without `~`, for example

```
$ spack mirror add local_filesystem file:///home/rpm/spack/mirror
```

**Comment by adamjstewart** [comment]
That's my fault. I replaced all occurrences of `/home/username` with `~` so there wouldn't be random usernames scattered throughout the documentation.

**Comment by citibeth** [comment]
Should the docs be change back?  Or should Spack be changed to properly expand the tilde?

**Comment by alalazo** [comment]
@citibeth @adamjstewart  Or we may take common user names from other domains (like cryptography), and use "Alice" and "Bob" (or anything else we might like) all other the place.

**Comment by adamjstewart** [comment]
I would be fine with just `/home/username` everywhere.

**Comment by adamjstewart** [comment]
I believe this issue was resolved at some point. I'm not seeing any `~` in the docs anymore.
