### ISSUE TITLE
Improper ancestor depth in /usr/lib/spack/spack/__init__.py?

### ISSUE THREAD

**Issue by JohnWestlund** [spack/spack#351]
I'm not sure if this is the "right" thing to do, but out of the box running `spack list` gives the following error:

```
[root@master4-centos71 spack-0.8.17]# spack list
  File "/bin/spack", line 135, in <module>
    main()
  File "/bin/spack", line 109, in main
    return_val = command(parser, args)
  File "/usr/lib/spack/spack/cmd/list.py", line 46, in list
    pkgs = spack.db.all_package_names()
  File "/usr/lib/spack/llnl/util/lang.py", line 182, in memoizer
    cache[args] = obj(*args, **kwargs)
  File "/usr/lib/spack/spack/packages.py", line 182, in all_package_names
    for pkg_name in os.listdir(self.root):
OSError: [Errno 2] No such file or directory: '/usr/var/spack/packages'
```

Changing the following in `/usr/lib/spack/spack/__init__.py` resolves the error, but I'm not sure it's the correct solution:

```
# This lives in $prefix/lib/spack/spack/__file__
- prefix = ancestor(__file__, 4)
+ prefix = ancestor(__file__, 5)
```

**Comment by adamjstewart** [comment]
I am unable to recreate this issue. I tried the following:
```bash
git clone https://github.com/LLNL/spack.git
cd spack/bin
./spack list
```
`spack list` returns the list of installed packages, as expected. I confirmed this on both the master and develop branches. What branch are you using? Can you try uninstalling and reinstalling spack? What OS are you on?

**Comment by JohnWestlund** [comment]
Centos 7 x86_64 -- I was poking around at this a bit more and the issue is that `/bin` is a symlink pointing to `/usr/bin`. So installing `spack` into `/bin` causes it to get the ancestor depth wrong.

**Comment by adamjstewart** [comment]
Ah, that makes more sense. Not sure if that is something we can fix or not. I'll leave this for someone else to look at.

**Comment by mathstuf** [comment]
I suppose `os.path.realpath(__file__)` could be used.

**Comment by tgamblin** [comment]
I think that's actually a bad idea in this case because even though `/bin` is a symlink to `/usr/bin`, Spack is still really installed in `/`, and if `/lib` *isn't* a symlink you'd still want to put your libs there and not in `/usr/local`.

**Comment by mathstuf** [comment]
Well, I also see `--prefix=/` is a poor decision, but *shrug* :) .

**Comment by tgamblin** [comment]
yeah this is how John wants to deploy it in OpenHPC.  I talked to John and I think he would be happy if the path nastiness at the beginning of `__init__.py` were just configurable.  Then OHPC could do what it wants.

**Comment by JohnWestlund** [comment]
Right -- it's not the ideal "it just works" out of the box solution I'd like it to be. But at least it would be better exposed and documented. This solution would still break if a user starts re-ordering their path though, which is why I don't think it's the correct long term solution.

**Comment by mathstuf** [comment]
Well, systems which do the UsrMove stuff are supposed to remove `/bin` and `/sbin` from `PATH`, but that is something that I still have open bugs about against Fedora for…

**Comment by alalazo** [comment]
What's the status with this issue?

**Comment by adamjstewart** [comment]
No response to @alalazo's comment, I'm assuming that this issue is stale and closing it. Feel free to reopen if it's still an issue we need to solve.
