### ISSUE TITLE
Failed to bootstrap pkg-config with pgi compiler

### ISSUE THREAD

**Issue by weijianwen** [spack/spack#3525]
I failed to bootstrap `pkg-config` with `pgi@16.10`.  The error says "PGC-F-0249-#error --  Your platform/compiler is missing constructor support (glib-init.c: 284)". Shall I submit a bug report to `pkg-config`?

```
$ spack purge; spack clean pkg-config; spack install pkg-config %pgi@16.10
==> Installing pkg-config
==> Using cached archive: /tmp/rpm/spack_source_cache/pkg-config/pkg-config-0.29.1.tar.gz
==> Already staged pkg-config-0.29.1-acbcjyz6mwiu7fnleuuatbxolunoszhl in /home/rpm/spack/var/spack/stage/pkg-config-0.29.1-acbcjyz6mwiu7fnleuuatbxolunoszhl
==> Already patched pkg-config
==> Building pkg-config [Package]
==> Executing phase : 'install'
==> Error: ProcessError: Command exited with status 2:
    'make'
/home/rpm/spack/var/spack/repos/builtin/packages/pkg-config/package.py:63, in install:
     53       def install(self, spec, prefix):
     54           args = ["--prefix={0}".format(prefix),
     55                   "--enable-shared"]
     56           if "+internal_glib" in spec:
     57               # There's a bootstrapping problem here;
     58               # glib uses pkg-config as well, so break
     59               # the cycle by using the internal glib.
     60               args.append("--with-internal-glib")
     61           configure(*args)
     62
  >> 63           make()
     64           make("install")

See build log for details:
  /tmp/rpm/spack_stage/spack-stage/spack-stage-w24BST/pkg-config-0.29.1/spack-build.out
```

**Comment by adamjstewart** [comment]
I've ran into this bug as well but hadn't yet gotten around to submitting a bug report. You're actually better off submitting a bug report to the glibc developers. pkg-config depends on glibc, but glibc depends on pkg-config. The developers realized this would cause a circular dependency, so pkg-config contains glibc in one of its sub-directories. If the glibc developers give you a patch for glibc, you can also apply it to the pkg-config package. PGI is a much stricter compiler than GCC, so I'm not surprised it doesn't build glibc. I've found developers to be fairly responsive about PGI patches.

**Comment by rkalescky** [comment]
Just curious if a bug report was filed. This problem persists with pkg-config-0.29.2.

**Comment by adamjstewart** [comment]
I never personally filed a bug report. I recommend contacting the glibc developers.

**Comment by EmreAtes** [comment]
I managed to workaround this problem by using the system pkg-config, by adding it to the `packages.yaml` file.
```YAML
packages:
    pkg-config: 
        paths: 
            pkg-config: /usr/bin/pkg-config
        buildable: False
```

**Comment by adamjstewart** [comment]
Yes, that's what we've been doing as well. I've asked @ssergien to contact the glibc developers and get to the bottom of this.

**Comment by XL64** [comment]
Thanks for the packages.yaml trick !

**Comment by alalazo** [comment]
Any update on this?

**Comment by nicholas-sly** [comment]
Ran into this issue when trying to install `openmpi@3.1.2` with `pgi@19.10`.  I pointed spack to the system installed pkg-config (@0.27.1), but very quickly ran into another error when building `libpciaccess@0.13.5` regarding undefined references to `inw`, `outw`, `inb`, `outb`, `inl`, and `outl` in `libpciaccess.so`.  I'm not sure if this is related to using an older pkg-config or if it's completely unrelated, but it would be nice if spack was able to install pkg-config in order to help debug this issue.

**Comment by adamjstewart** [comment]
@nicholas-sly this is a known problem with the PGI compilers and libpciaccess, it has nothing to do with pkg-config. I actually reported this one back in 2016. See:

* https://bugs.freedesktop.org/show_bug.cgi?id=94398
* https://www.pgroup.com/userforum/viewtopic.php?f=4&t=5126
* https://gitlab.freedesktop.org/xorg/lib/libpciaccess/issues/7

**Comment by nicholas-sly** [comment]
@adamjstewart Wow.  You seem to have gotten a lot of response and little resolution.  

If that's the case, should Spack include an incompatibility between PGI and libpciaccess?  

Perhaps allowing for libpciaccess to be built with gcc even if it's a dependency of something else being built with PGI (as was seemingly hinted at in one of those threads)?

**Comment by adamjstewart** [comment]
> If that's the case, should Spack include an incompatibility between PGI and libpciaccess?

Yes, we should add a `conflicts('%pgi')` to the package and include those URLs in comments.

> Perhaps allowing for libpciaccess to be built with gcc even if it's a dependency of something else being built with PGI (as was seemingly hinted at in one of those threads)?

@tgamblin is currently working on a new concretizer that will allow this. Specifically, build dependencies like `pkg-config` will be built with the system default compiler (usually GCC) and conflicts will influence the concretizer's decision on which compiler to use.

**Comment by asmaahassan90** [comment]
I ran into the same issue trying to install pkg-config@0.29 with pgi@19.7. I'm using Spack 14.2.
Shall I go for the trick of directing pkg-config to use the system package or there is  another fix for it?

**Comment by adamjstewart** [comment]
As far as I know, nothing has changed. You should use an external installation of `pkgconfig` and report the build issue to the `pkgconfig` developers.

**Comment by jgalarowicz** [comment]
I'm also running into issues similar to the above when trying to build components with pgi compilers via spack.   Jim G

**Comment by adamjstewart** [comment]
Does `pkgconf` build with PGI? Has anyone contacted the `pkg-config` or `pkgconf` developers?

**Comment by nicholas-sly** [comment]
As PGI appears to be subsumed by the nvidia HPC tools set, we are probably just going to drop our support for now.  If it doesn't currently work, I'd be surprised if the `pkgconf`/`pkg-config` developers care to put any effort into this.

**Comment by adamjstewart** [comment]
@nicholas-sly I assume any patches needed for NVIDIA HPC support will be identical to those needed for PGI support. I'm not opposed to dropping support for both (and adding conflicts). The new concretizer should be smart enough to compile build-dependencies with GCC and compile the rest of your DAG with the compiler you request.

**Comment by nicholas-sly** [comment]
This is true.  We're just unsure what licensing will even look like, so we're bailing until we know more.  I think the conflicts in anticipation of the new concretizer are the way I'd like to see this dealt with.
