### ISSUE TITLE
httpie does not depend on py-argparse

### ISSUE THREAD

**Issue by hartzell** [spack/spack#3628]
httpie won't build for python 2.7.13.

```
[hartzelg@lb093login spack]$ grep python etc/spack/packages.yaml
  python:
[hartzelg@lb093login spack]$ grep -2 python etc/spack/packages.yaml
  prank:
    version: [150803]
  python:
    version: [2.7.13]
  py-flake8:
[hartzelg@lb093login spack]$ spack spec httpie
Input spec
--------------------------------
httpie

Normalized
--------------------------------
httpie
    ^py-argparse@1.2.1:
        ^py-setuptools
            ^python@2.6:2.7.99,3.3:
                ^bzip2
                ^ncurses
                    ^mawk
                    ^pkg-config
                ^openssl
                    ^perl@5.14.0:
                    ^zlib
                ^readline
                ^sqlite
    ^py-pygments@2.1.3:
    ^py-requests@2.11.0:

Concretized
--------------------------------
==> Error: httpie does not depend on py-argparse
[hartzelg@lb093login spack]$ grep argparse var/spack/repos/builtin/packages/httpie/package.py
    depends_on('py-argparse@1.2.1:', type=('build', 'run'), when='^python@:2.6,3.0:3.1')
```

It works w/ python@3..6.0

I think that this bit in the `setup.py` is what suggested the addition.

```
if 'bdist_wheel' not in sys.argv:
    try:
        # noinspection PyUnresolvedReferences
        import argparse
    except ImportError:
        install_requires.append('argparse>=1.2.1')

    if 'win32' in str(sys.platform).lower():
        # Terminal colors for Windows
        install_requires.append('colorama>=0.2.4')

```

Looking at it though, I believe that it only applies in certain (bdist_wheel...) situations.

**Comment by hartzell** [comment]
@adamjstewart -- I think that I should back out this addition.  Make sense to you?

**Comment by adamjstewart** [comment]
Ah, yes, that's a concretization problem. Can you comment it out so that we can re-add it after concretization is fixed? In the meantime, add the dependency unconditionally for all versions of Python.

**Comment by hartzell** [comment]
yep.

**Comment by adamjstewart** [comment]
This is basically the same bug as #2793. I've been commenting out these dependencies in a few packages.

**Comment by hartzell** [comment]
@adamjstewart -- should I leave this open as a reminder or close it in the name of neatness?

**Comment by adamjstewart** [comment]
Leave it open. @tgamblin can close it when his new concretizer is released.

**Comment by healther** [comment]
I thought this problem to be fixed, at least in many packages 
``` depends_on('py-foo', when='^python@3:')```
works as expected. However I just found a case, where if I include such a dependency in a metapackage it breaks concretization. 

Mainly my question is: Should this be fixed in the current concretizer and this issue just wasn't closed?

**Comment by adamjstewart** [comment]
The concretizer hasn't changed in a long time. Any open issues are still likely unresolved. Expect a big concretizer overhaul sometime in the next year.
