### ISSUE TITLE
How to control BLAS choice via preprocessor macros (HAVE_ATLAS, HAVE_OPENBLAS...)?

### ISSUE THREAD

**Issue by weijianwen** [spack/spack#3775]
In Kaldi, `kaldi-blas.h` can handle various BLAS packages' header including by defining macros like `HAVE_ATLAS`, `HAVE_OPENBLAS` etc. 

https://github.com/kaldi-asr/kaldi/blob/master/src/matrix/kaldi-blas.h

My question is, for packages depending on Kaldi (say https://github.com/Microsoft/CNTK ), where is the best practice to control the BLAS choice in accordance to Kaldi? And in Spack, how can we enhance this control?

**Comment by adamjstewart** [comment]
@weijianwen Support for this scenario will be added in #3367, which adds a `HeaderList` class that allows you to specify macros.

**Comment by davydden** [comment]
> My question is, for packages depending on Kaldi (say https://github.com/Microsoft/CNTK ), where is the best practice to control the BLAS choice in accordance to Kaldi?

i think this will be controlled automatically by Spack because when you conretize anything which uses `Kaldi`, you will have one and only one version of Blas in the graph of packages.

**Comment by alalazo** [comment]
#3367 has been merged since a while. Closing.
