### ISSUE TITLE
openblas fails when cross-compiling

### ISSUE THREAD

**Issue by berrill** [spack/spack#3792]
On Titan, openblas fails due to the check_build routine.  This is caused by the fact we are cross-compiling and the binary created is not compatible with the login node where spack is running so it fails at the
    make('tests', *self.make_defs)
line in var/spack/repos/builtin/packages/openblas/package.py.  If I remove the line, then spack can proceed.  We need a way to disable these types of tests for machines that cross-compile.

**Comment by alalazo** [comment]
Closing since this seems specific to Titan (decommissioned in 2019). The broader topic of cross-compilation will be tracked in other issues as we proceed with compilers as dependencies.
