### ISSUE TITLE
How to specify  multiple modules in modules block of packages.yaml ? 

### ISSUE THREAD

**Issue by pramodk** [spack/spack#3817]
Consider a scenario where I have to load multiple modules for a specific package : 

```
    python:
        modules:
             python@xxxx: FirstModule SecondModule
```

On Cray `daint` system that I am currently testing, in order to make `python` module `visible`, I have to first load other `prerequisite` module. How to specify this? It seems I can't specify list there.

May be I can update `compilers.yaml` with inserting`prerequisite ` module but it would be cleaner to specify that in `config.yaml`.

**Comment by KineticTheory** [comment]
+1

I need this feature for non-Cray systems.  Our sysadmins like to hide modules behind other modules.  For example, I can only access the `cmake/3.9.0` module by first loading the `friendly-testing` module.

**Comment by pramodskumbhar** [comment]
@KineticTheory : if you come across any workarounds, let me know!

**Comment by roblatham00** [comment]
I have a similar problem.  I want to declare `intel-mpi` as a system package.  To do so i need to load the intel compiler first, then the intel-mpi module

**Comment by pramodk** [comment]
@roblatham00 : in your case I typically  "workaround" by adding intel compiler module in `compilers.yaml`

**Comment by adamjstewart** [comment]
I believe this feature was added by @alalazo's #17804. Users can now do:
```yaml
cmake:
  externals:
  - spec: cmake@3.7.2
    modules:
    - gcc/6.3.0
    - CMake/3.7.2
```
