### ISSUE TITLE
Dealing with oddball package dependency source distribution

### ISSUE THREAD

**Issue by wscullin** [spack/spack#3868]
I am trying to get a local project (dxchange) into spack that's already in conda. To my chagrin, the developers borrow particular files out of other projects (which are available on github) at particular versions and treat them as projects that are independent of their parent.

Part of me says that the correct way to handle this would be to ignore the copies out of other projects in conda, add the dependencies the files are copied from (at fixed versions), then have my target package (dxchange) provide the target package as well as the target package's dependencies by copying from the actual dependencies. Still, this feels really hacky to me and I'm open to suggestions on how it should be done.

**Comment by adamjstewart** [comment]
This sounds like the `resource` directive:
http://spack.readthedocs.io/en/latest/packaging_guide.html#resources-expanding-extra-tarballs

**Comment by citibeth** [comment]
Does it grab files out of other projects' source distros, or their installed tree?

**Comment by wscullin** [comment]
It grabs files out of the source distros, then treats them as a separate package.

**Comment by citibeth** [comment]
What do you mean, that it treats them as a separate package?  If the source code for dxchange is online, can you point to where the installer does this magic?

**Comment by tgamblin** [comment]
Also, what's it using to do that?  It's not cmake external project is it?  If so, I have some code to hack around that in the features/tensorflow branch. Specifically to treat a spack dependency as an already built external project.

**Comment by wscullin** [comment]
The dxchange conda install does little of the magic itself. The developers manually do the repackaging to make things work within Conda. The [dxchange requirements file](https://github.com/data-exchange/dxchange/blob/master/requirements.txt) includes a package called edffile. When you look at the Conda package for [edffile](https://anaconda.org/conda-forge/edffile/files) you find out that it's a single file copied out [PyMca](https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaIO/EdfFile.py) with a somewhat truncated setuptools setup.py to avoid a dependency on PyMca5.

For spackification purposes, other dependencies can be worked around as there are github or pypi instances, even if the sources available through those sites aren't a perfect match for what the developers are using in Conda. EdfFile bugs me as the original developer doesn't explicitly version it separately from PyMca, the canonical version is in git, and dxchange treats it as its very own Python module.

**Comment by citibeth** [comment]
On Mon, Apr 17, 2017 at 5:20 PM, Todd Gamblin <notifications@github.com>
wrote:

> Also, what's it using to do that? It's not cmake external project is it?
> If so, I have some code to hack around that in the features/tensorflow
> branch. Specifically to treat a spack dependency as an already built
> external project.
>
Yes... people trying to be clever with dependencies in the wrong place is
the bane of our existence.  Glad you're finding a way to "disable" it.

**Comment by alalazo** [comment]
This has been stale for a while. Closing it for now. Reopen if you don't agree.
