### ISSUE TITLE
Serialized copies of specs do not correctly report is_extension

### ISSUE THREAD

**Issue by scheibelp** [spack/spack#3887]
If a spec is written to yaml and then read back, it's dependencies do not correctly report ```.is_extension```:

```
>>> from spack.spec import Spec
>>> x = Spec('git')
>>> x.concretize()
>>> y = Spec.from_dict(x.to_dict())
>>> y['libxml2'].package.is_extension
True
>>> x['libxml2'].package.is_extension
False
```

(```Spec.to_yaml``` and ```Spec.from_yaml``` use the corresponding dict functions, so this affects specs that have been read from files).

Note that using ```Spec.copy()``` does not have this problem.

Two notes:

* Specs constructed with ```Spec.from_dict``` have ```_concrete``` set to False (although ```concrete``` is true if the original Spec was concrete)
* ```Package.is_extension``` refers to ```Spec._concrete```

This suggests the following possible solutions:

* Package.is_extension uses Spec.concrete instead of Spec._concrete. This is done in https://github.com/LLNL/spack/pull/3853 and has some (IMO valid) criticisms that the repercussions need to be clarified
* ```Spec.from_dict``` should set _concrete (perhaps if it doesn't change after concretization)
* ```Spec.to_dict``` should record whether the spec was concrete

**Comment by adamjstewart** [comment]
Is this the root cause of #2895?

**Comment by scheibelp** [comment]
> Is this the root cause of #2895?

From looking into it briefly, IMO no: in this issue packages which are conditionally extensions may incorrectly be reported to extend something. In #2895 it appears that Package.extends is returning False for other reasons

**Comment by alalazo** [comment]
This has been fixed at some point:
```console
$ spack-python
Spack version 0.15.4
Python 3.7.4, Linux x86_64
>>> from spack.spec import Spec
>>> x = Spec('git')
>>> x.concretize()
>>> y = Spec.from_dict(x.to_dict())
>>> y['libxml2'].package.is_extension
False
>>> x['libxml2'].package.is_extension
False
```
I'm using 

* **Spack:** 0.15.4-613-ccf94ded6
* **Python:** 3.7.4
* **Platform:** linux-ubuntu18.04-broadwell
