### ISSUE TITLE
unify access to fortran modules (elpa, cp2k, espresso)

### ISSUE THREAD

**Issue by davydden** [spack/spack#3897]
i noticed that packages which use `elpa` need to write
1. cp2k:
```
                fcflags.extend([
                    # spec['elpa:fortran'].cppflags
                    '-I' + join_path(
                        spec['elpa'].prefix,
                        'include',
                        'elpa-{0}'.format(str(spec['elpa'].version)),
                        'modules'
                    )
                ])
```
2. espresso
```
                options.extend([
                    '--with-elpa-include={0}'.format(
                        join_path(spec['elpa'].prefix,
                                  'include',
                                  'elpa-{0}'.format(str(spec['elpa'].version)),
                                  'modules')
                        )
                ])
```
3. abinit (not implemented, but can use `elpa`)

It looks like the consensus is to use query parameters, i.e. `spec['elpa:fortran'].cppflags`. I think @adamjstewart was working on a PR with counterpart to LibraryList class? Can we also make it return the path only, without `-I`?

**Comment by adamjstewart** [comment]
Yes, that is one of the features of `HeaderList`. It has most of the same attributes as `LibraryList`.

**Comment by dev-zero** [comment]
I've implemented one simplification base on the suggestion of @scheibelp in 0a6f1ac, is that sufficient?

**Comment by adamjstewart** [comment]
The `elpa` package now defines its own custom `headers` attribute, and this attribute is used by `cp2k` and `quantum-espresso`, so I think this issue can be closed.
