### ISSUE TITLE
'spack --version' to give x.y.z-extra for non-release versions

### ISSUE THREAD

**Issue by HenrikBengtsson** [spack/spack#3944]
Don't think I did, but I'm sorry if I already brought this up previously (too many projects in parallel right now):

It is the case that:
```sh
$ spack --version
0.10.0
```
is reported also for the develop branch (and any other branches), correct?  That's what it looks like to me after coming back to Spack after several weeks, but I want to make sure that's the case.

Also, I might already have suggested to use a larger version number do indicate that's it different from the most recent release, e.g.
```sh
$ spack --version
0.10.0.9000
```
for develop branch(es).  As long as that 'extra' in x.y.z-extra is there, I am happy; I don't really need it to increase for every single commit / push as long as it's a very clear indicator that I'm running something different that stable release and that can pass a version comparison `x.y.z < x.y.z.extra < x.y.z+1`.  (The `.9000` suffix has become a de-facto standard in the R community.)

**Comment by adamjstewart** [comment]
I would also find this helpful. A lot of users clone the latest Spack release and quickly discover that they encounter bugs that have already been solved. If I could ask users what version of Spack they are running and immediately know if they are on the last release or have been keeping up with develop, it would make for much less confusion.

**Comment by alalazo** [comment]
I think this has been fixed since a long time. Spack now reports:
```console
$ spack --version
0.15.4-537-526aa3847
```
to mean we are at commit 526aa3847 and 537 commits from 0.15.4
