### ISSUE TITLE
Dependencies enabled by default=True variants cannot be configured on command line without explicitly enabling the variant

### ISSUE THREAD

**Issue by scheibelp** [spack/spack#397]
If I have a package X with variant XV1 and package Y, and X has a depends_on declaration like:

```
variant('XV1', default=True)
depends_on(Y, when="+XV1")
```

Then 

```
spack install X ^Y %gcc@4.7.4
```

Would fail with a message stating Y is not a dependency of X. Adding +XV1 would succeed.

A more concrete example is a boost install:

```
spack install boost %clang ^bzip2 %gcc
==> Error: boost does not depend on bzip2
```

Adding +iostreams (which is enabled by default and activates the dependency on bzip2) works.

**Comment by adamjstewart** [comment]
I just want to confirm that this bug is still present. I'm writing an elk package that contains:
```python
variant('mpi', default=True, description='Enable MPI parallelism')
depends_on('mpi', when='+mpi')
```
When I try specifying the virtual dependency, I get:
```bash
$ spack install elk ^mvapich2
==> Error: elk does not depend on mvapich2
```
I have to run `spack install elk +mpi ^mvapich2` to get the desired behavior.

**Comment by scheibelp** [comment]
This is fixed by https://github.com/spack/spack/pull/8162

**Comment by adamjstewart** [comment]
Does this mean we can remove http://spack.readthedocs.io/en/latest/known_issues.html#default-variants-are-not-taken-into-account-during-concretization?

**Comment by scheibelp** [comment]
Yes
