### ISSUE TITLE
Auto-check for unused library dependencies.

### ISSUE THREAD

**Issue by junghans** [spack/spack#3999]
@adamjstewart @tgamblin @davydden 

After installing a shared library we should run `scanelf -n` (from pax-utils) on the libraries and check if all dependencies listed actually show up.

If they don't show up, it might be just a build dependency or no dependency at all. We should print a maintainer message in this case.

**Comment by adamjstewart** [comment]
Duplicate of #1304. `scanelf` won't work as that isn't available on most OSes.

**Comment by junghans** [comment]
`scanelf` can be installed by spack now ;-)

It seems to me #1304, is more about under-linked libraries.

**Comment by adamjstewart** [comment]
It can be installed by Spack, but we don't want to make it a dependency of every package.

**Comment by junghans** [comment]
I would make a dependency for maintainer-mode only.

**Comment by adamjstewart** [comment]
Closing this issue as a duplicate, if there is further discussion let's continue it in #1304.
