### ISSUE TITLE
Move `llnl.util` package to `spack.util`

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#4021]
The `llnl.util` package currently in Spack was intended to be general Python stuff for Spack and other LLNL projects, but it isn't used that way.  Some of it is used by [LLNL/cram](https://github.com/LLNL/cram), but the codebases are maintained independently, and the code in Spack has moved on quite a bit from what's in `cram`.

There are some things in there, like `llnl.util.lock`, `tty.colify` (I'm not aware of another Python colifier that does variable-width columns), `tty.color`, and `tty.log` that could probably be factored out of Spack one day, but right now, for all intents and purposes, they're in Spack.  I think it would make things clearer if we moved them to `spack.util`.

@adamjstewart @alalazo: thoughts?

**Comment by tgamblin** [comment]
Attn: @IanLee1521 in case you have thoughts on this.  There might be stuff you want.  Here's [the package](https://spack.readthedocs.io/en/latest/llnl.html).

**Comment by adamjstewart** [comment]
Right after I added the docs 😆 

I agree, I'm sure it was generic at one time but now we have fairly Spack-specific things in there like `LibraryList`. Can you merge #3367 first though? I'll rebase if you think it looks good.

**Comment by alalazo** [comment]
> There are some things in there, like llnl.util.lock, tty.colify (I'm not aware of another Python colifier that does variable-width columns), tty.color, and tty.log that could probably be factored out of Spack one day, but right now, for all intents and purposes, they're in Spack. I think it would make things clearer if we moved them to spack.util.

I agree. Besides if we solve #1385 we'll be able to factor out anything that is worth generalizing and releasing separately, and then we can just make Spack depend on that package. So :+1: to move everything into `spack.util` for now.

**Comment by tgamblin** [comment]
We'd probably still vendor dependencies even if we solve #1385, but maybe just in the repo, with PyPI releases factored differently. I want #1385 so people can build on spack's dep management but I don't want to have to install the installer 😆 

Also the other spack guy hasn't responded to me so we may need to be spackpm or something on PyPI 😭 .

**Comment by citibeth** [comment]
I use `llnl.util` in a separate project, see: https://github.com/citibeth/modele-control/tree/develop/lib/llnl

My hope was that this would eventually be LESS integrated with Spack, and I wouldn't have to maintain a copy of it myself.  So the idea of renaming to `spack.util` seems like a step in the wrong direction.

**Comment by tgamblin** [comment]
The main goal was to get everything under a single namespace, to simplify a future PyPI release and to make the spack docs clearer. They'd still be functionally separate and I don't mind enforcing that the stuff in spack.util wouldn't import classes from spack. And the plan would still be to factor them out. Is that still objectionable for modele? I notice that modele also includes spack.

**Comment by citibeth** [comment]
modele-control doesn't directly call Spack, so that dependency should
probably be removed.

I still don't understand the benefit of a PyPI release for Spack.  PyPI is
a big help for libraries you want to write scripts against, or things with
a lot of dependencies.  Spack is neither.

So is the plan to permanently rename this library but move it to a
different tarball someday?  That brings up PEP420 complications.

**Comment by IanLee1521** [comment]
@tgamblin -- I'd started some work on an "hpc" python package, already have the name on PyPi (https://pypi.python.org/pypi/hpc/0.0)... I should actually get the code I started internally released and pushed out. Then I feel like this util code (or some part of it) could move into there and become a dependency for Spack, or just something that you vendor in (which could also be used elsewhere).

**Comment by tgamblin** [comment]
@IanLee1521: thanks.  There may be some stuff that belongs in HPC from Spack, but I'm not sure it's all HPC related.

@citibeth:
> I still don't understand the benefit of a PyPI release for Spack.  PyPI is a big help for libraries you want to write scripts against, or things with a lot of dependencies.  Spack is neither.

Spack isn't horribly factored at the moment, and there are folks who would like to write scripts against its internals.  As we implement the APIs we've talked about in the environments WG I think that will become more true.  I know the CERN/BNL/Fermi folks use cases in mind for that.  You can actually already write scripts against Spack using the `spack-python` python interpreter launcher that comes with Spack -- I do that frequently to debug things.  I also think library-izing things more has design benefits -- there are part of Spack right now that are probably too global, and that would be factored better with this change.  That's kind of orthogonal to the `llnl.util` thing though.

> So is the plan to permanently rename this library but move it to a different tarball someday?

Currently the `llnl.util` package doesn't exist except as part of Spack, `cram` and `modele`.  It's not on PyPI.  The idea is to move it to `spack.util`, **not** make it part of the Spack public interface, and eventually factor it out of Spack as other useful components.  If we did put Spack on PyPI I would rather not pollute everyone's namespace with a second `llnl` package in addition to the `spack` package, when `llnl` is really internal code for Spack.

Things that are in `llnl` right now:

* `llnl.util.filesystem`: This is really part of the Spack build environment.  The `spack` namespace does a `from llnl.util.filesystem import *`.  I don't think it's general or cohesive enough to be a separate library.
* `llnl.util.lang`: This is a bunch of utility functions for the Spack core.  It has some data structures, a `@key_ordering` decorator that is used all over the place to implement comparison by tuple keys, the `@memoized` decorator, and some other less general functions.  I think it probably belongs in `spack.util`.
* `llnl.util.link_tree`: Class for dealing with trees of symlinks.  This *could* be fleshed out into its own thing, but it's far from being that now.
* `llnl.util.lock`: Multi-process readers-writers byte-range lock that works on NFS, GPFS, and Lustre.  [Described here](https://github.com/harlowja/fasteners/issues/26#issuecomment-253543912).  I am thinking of contributing this one to [fasteners](https://github.com/harlowja/fasteners), which is the file lock library for Python these days (used by OpenStack)
* `llnl.util.tty`: This is what Spack uses to print console messages.  It and its submodules could probably be fleshed out into a more general command-line app toolkit.
* `llnl.util.colify`: Variable-width columnizer, like the one used by GNU ls.  AFAIK there is not another one of these available for Python; I was thinking of making this its own package.
* `llnl.util.color`: Simple, more rememberable syntax for terminal colors.  e.g. you can do things like:
    * `@g{this is green}`
    * `@G{this is bright green}`
    * `@*{this is bold}`
    * `@_{this is italic}`
    * `@*b{this is bold and blue}`
    * `@*k{this is italic and black}`
and it will be converted to appropriate console escape codes.  Currently has no support for 256-color terminals or customization, but with those I think it could be a nice library on its own.
* `llnl.util.log`: This is basically a context manager, `log_output()`, that lets you log the output of a block in Python.  We use it to log what builds do.

So the idea would be to just move this stuff to be under `spack.util` instead of `llnl.util`, not make it any more integrated with Spack, and gradually move pieces to `external` as we factor them out and vendor them.  Some parts might stay in Spack, especially if they don't seem like they'd be popular as separate libraries.

**Comment by citibeth** [comment]
>
> Spack isn't horribly factored at the moment, and there are folks who would
> like to write scripts against its internals.
>
OK yes, I see the value in that.  And I can see that people who build
Python environments with PyPI would then find that useful.  However, I use
Spack to install my Python environment, so I would want Spack to install
based on `spack/package.py`.

I believe the best way to do this is to download a new `spack.tar.gz` and
install it just like any other Python package.  However, some checksum
Jujitsu will be needed here, since Spack cannot contain its own checksum.
Maybe release each version of Spack twice: release A does not contain
checksum for itself in `spack/package.py`.  Release B contains the checksum
for release A, but is otherwise identical to release A.  Users would
typically download and run release B like they do now; and that could be
used to install release A.

> You can actually already write scripts against Spack using the
> spack-python python interpreter launcher that comes with Spack -- I do
> that frequently to debug things.
>
I agree, that's a hack good for debugging but not serious development.


> So is the plan to permanently rename this library but move it to a
> different tarball someday?
>
> Currently the llnl.util package doesn't exist except as part of Spack,
> cram and modele. It's not on PyPI. The idea is to move it to spack.util,
> *not* make it part of the Spack public interface, and eventually factor
> it out of Spack as other useful components.
>
So if it's not public, we can't use it externally?  But later it gets
factored out and made public?  In that case, I suppose there's nothing for
me to do with `modele-control` unless/until this stuff is factored out?


> If we did put Spack on PyPI I would rather not pollute everyone's
> namespace with a second llnl package in addition to the spack package,
> when llnl is really internal code for Spack.
>

You are aware of PEP 420?  It will be needed once you have two packages
(`spack` and `spack-utils`) that both put stuff into the `spack.` namespace.

https://www.python.org/dev/peps/pep-0420/

-- Elizabeth

**Comment by tgamblin** [comment]
> I believe the best way to do this is to download a new `spack.tar.gz` and
> install it just like any other Python package.  However, some checksum
> Jujitsu will be needed here, since Spack cannot contain its own checksum.

You could actually do something kind of cool with `git` and `$Format:%H$`.  See the [gitattributes] (https://git-scm.com/docs/gitattributes) docs, or the part about `$Id$`.  [in this SO answer](https://stackoverflow.com/questions/16524225/how-can-i-populate-the-git-commit-id-into-a-file-when-i-commit).

> > If we did put Spack on PyPI I would rather not pollute everyone's
> > namespace with a second llnl package in addition to the spack package,
> > when llnl is really internal code for Spack.
> 
> You are aware of PEP 420?  It will be needed once you have two packages
> (`spack` and `spack-utils`) that both put stuff into the `spack.` namespace.
> 
> https://www.python.org/dev/peps/pep-0420/

Yes, but the intent was to gradually factor things out into their own namespaces, not to keep the original namespace.  You'd need to explicitly switch your project after we start vendoring if you rely on the internal API.  e.g., I don't see why we wouldn't want `colify` to live in the `colify` namespace, kind of like how `fasteners` was originally `oslo.concurrency`.

**Comment by tgamblin** [comment]
So to be completely clear (maybe I missed this in an earlier response): we're not proposing a permanent name change.  We're proposing a temporary name change to an internal API, *then* a gradual refactoring into permanent namespaces on PyPI.

I don't think this is so hard to vendor into modele.

**Comment by ax3l** [comment]
I would love to have `spack.util.executable` as part of `llnl.util` and would like to reuse `llnl.util` without spack :) (migrated from #5155)

**Comment by adamjstewart** [comment]
I agree, the Executable module is really nifty. Release on PyPI? I think a lot of Spack modules could be of use outside of Spack. A lot of big projects will branch off submodules into separate projects. Once Spack is PyPI ready, it will be even easier to install all of Spack's dependencies with `pip` instead of vendoring them.

**Comment by alalazo** [comment]
> Once Spack is PyPI ready

Speaking of which, I'll have some time in the next months that I can use to push #1385 and #4021 forward. We just need to agree on a common way to proceed.

Maintaining more than one package (i.e. more than one `setup.py`) in the same repository might be a way to go. I'll start having a look if there are other projects that are doing this and if `tox` blends well into it for unit tests.

**Comment by tgamblin** [comment]
Have you all seen [`sh`](https://github.com/amoffat/sh)?  It's pretty similar to `Executable` (and about as old as Spack... guess someone else had the same idea).  I wonder if we should move to that.  It'd be another vendored dependency, though, and the interface isn't the same.  I'm not sure i like the `from sh import ls` better than `ls = which('ls')`, and it looks like it's a bit more fleshed out w.r.t. redirection, handling output, bg/fg exectuion, etc.  They also use [keyword arguments](http://amoffat.github.io/sh/sections/passing_arguments.html#keyword-arguments) as a shortcut for `--long-arg=value` and they prefix [special keyword arguments](http://amoffat.github.io/sh/sections/special_arguments.html) (like our `out=str`, etc.) with `_`. 

There are advantages for Spack having its own `Executable` class, though.  I am not sure the use cases are the same.  We subclass `Executable` in various places to add default arguments (like `make -jN`), and I don't think that's as easy with `sh`.

The other parts mentioned above probably could be generally useful.

**Comment by ax3l** [comment]
> Have you all seen sh?

Great recommendation, thanks!

**Comment by alalazo** [comment]
Do we have a preference here between moving `llnl.util` to `spack.util` (as the title suggests) or maintaining the two as separate packages within the same git repository?

**Comment by tgamblin** [comment]
I think the right thing to do (slowly) would be to release different pieces independently on pypi and move them gradually to externals.  I've thought about also doing this with the Spack command infrastructure.

**Comment by alalazo** [comment]
> I think the right thing to do (slowly) would be to release different pieces independently on pypi and move them gradually to externals.

@tgamblin I took a good look today at the [PyPA documentation](https://packaging.python.org/). I think  maintaining multiple packages in the same repository is doable, but I agree that it's better to slowly move independent packages (like the code under `llnl`) to another repository and package them like everybody else is doing - standard directory layout, simple `setup.py` etc.  At that point from `Spack` perspective it's just another vendored external.

> I've thought about also doing this with the Spack command infrastructure.

It might be worth looking at [click](http://click.pocoo.org/6/), to see if the nice features you added on top of `argparse` (different grouping for options, simple vs. extended help) can be integrated easily there. The package seems to be very popular these days, and if it fits our needs maybe it should be considered in the long run? Anyhow, I'll try to have a look at it, will come back at some point with more insight.

**Comment by jcftang** [comment]
click is quit good, its maintained by the people that created flask AFAIK and that is a reasonably big and popular project, click isn't going anywhere.

**Comment by adamjstewart** [comment]
@tgamblin based on our recent discussion, it seems like the plan is to release `llnl.util` packages on PyPI instead of merging them into `spack.util`? In that case, can this issue be closed?
