### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by gonsie** [spack/spack#4024]
Hi Spack team!

I am looking at creating a bot to help get on top of the large number of pull requests and issues in this project. Are there any features that you may find helpful?

Features I have in mind:
1. maintainers communicate approvals of PRs and, when certain conditions have been met, the bot automatically performs a merge
1. the bot could ensure that contributors have signed a license agreement or have signed-off on their commits
1. the bot could collect information from people who create issues or PRs and update the labels to match some predefined states

Are there other tasks that could be helped by a bot?

**Comment by tgamblin** [comment]
Hi @gonsie!

I think a bot could be pretty helpful.  RE: ideas above:

> 1. maintainers communicate approvals of PRs and, when certain conditions have been met, the bot automatically performs a merge.

This would be great.  We don't currently have a policy on stuff like this, but I think it would help.  I'd want a way to identify core maintainers and if 2 people approve a PR and the tests pass, it could be automatically merged.  We *could* additionally split the core contributors into groups by parts of the code they can merge to, but I think it's overkill -- if we give people merge privileges we already trust them enough to only merge things in the parts of the code they know well enough to review.

> 2. the bot could ensure that contributors have signed a license agreement or have signed-off on their commits

I think this could be useful, although we do not currently have a policy on what a CLA should look like.  We would need something like this if we ever wanted to make the Spack license more permissive, which we've talked about doing, but that is a longer conversation.  We should talk about this one in person, and I'd want to bring it up on the ML and have a larger conversation if we did it.

> 3. the bot could collect information from people who create issues or PRs and update the labels to match some predefined states.

I like it -- can you give some examples of bots like this?  I'd rather not require people to fill in forms or anything, but some amount of auto-labeling could be useful.


Opinions?  @scheibelp @citibeth @becker33 @alalazo @davydden @mamelara @adamjstewart others?

**Comment by citibeth** [comment]
(1) Not sure how much work it would save.  Also, there are no hard and fast rules about approvals and merging.  Often, one person will approve a PR, and then later someone else finds a serious issue.  After a bunch of back-and-forth, the PR is eventually ready to merge --- but by then, the original approver's approval is completely out of date.  Anyway, how hard is it for a real human to press the "merge" button?

(2) This should go into the Travis checks --- for example, check for appropriate copyright notices.  That would be tantamount to signing off, IMHO.

(3) I really like this, and it shouldn't be too hard.  For example, anything that touches a file named package.py should be labelled "package" --- unless it touches 100, in which it should be labelled "refactoring."  Anything introducing a new package should be labelled "new-package."  Just those two labels would be a big help, as it would segregate the constant package drumbeat from the core Spack issues; the two are now handled separately by different teams.

**Comment by adamjstewart** [comment]
Could we allow all users to add their own labels?

**Comment by tgamblin** [comment]
> Could we allow all users to add their own labels?

This would be nice. I generally try to give contributors write access so they can do this. They still can't alter master or develop as those are protected, but it would be nice to allow anyone to add labels and not just people we've explicitly added.

**Comment by citibeth** [comment]
Make a bot that gives label privileges to anyone who submits a PR.

**Comment by tgamblin** [comment]
Unfortunately there is no specific "can label" permission -- we would have to give them write access to the repo.  I don't think it's a good idea to automate that.  Currently we give it pretty liberally to people who've made contributions, but I'm not sure I want everyone to be able to push branches when they could just fork.

**Comment by adamjstewart** [comment]
One bot I just ran into is @mention-bot. Check out https://github.com/python/cpython/pull/737 for an example. It looks at the history of a package and automatically pings anyone who has edited this file in the past.

**Comment by adamjstewart** [comment]
Can we get a Slack bot that translates #4024 into a link to a GitHub issue/PR?

**Comment by tgamblin** [comment]
Is there one available?  I've wanted the same thing many times but couldn't find anything googling.

**Comment by adamjstewart** [comment]
Shouldn't be hard to write one ourselves.

**Comment by tgamblin** [comment]
There is this: https://github.com/augbog/slack-github-issue but I thought it was a bit obtrusive the way it comments the issue in.  I think I'd rather just have a link but this would do.

**Comment by alalazo** [comment]
Ok, I think we definitely need something like this:
> the bot could collect information from people who create issues or PRs and update the labels to match some predefined states

so that people can e.g. use hashtags or something similar and have their PR or issue tagged by a bot. Like:
```
#newpackage

This PR adds package 'foo' to Spack
```
or 
```
#builderror

<follows description>
```

**Comment by alalazo** [comment]
Reviewing all of the above discussion, this seems something we can now do with custom Github Actions

**Comment by adamjstewart** [comment]
I opened #15019 with some additional ideas for GitHub bots/actions we could really use.

**Comment by alalazo** [comment]
We have @spackbot !
