### ISSUE TITLE
Important function in `openmpi` package is not used any more

### ISSUE THREAD

**Issue by eschnett** [spack/spack#4110]
The function `with_or_without_verbs` in `openmpi`'s package description is not called any more. It contains important logic for setting the `verbs` option. This looks like an oversight in the recent update to use multi-valued variants.

**Comment by adamjstewart** [comment]
@alalazo

**Comment by alalazo** [comment]
I'll have a look at it later, but I suspect it's just lack of documentation. Or do you have a configure line that doesn't behave like it should? In this case can you post that as a reproducer?

**Comment by alalazo** [comment]
To explain this better:
```python
def _activate_or_not(self, active, inactive, name, active_parameters=None):
    spec = self.spec
    args = []
    # For each allowed value in the list of values
    for value in self.variants[name].values:
        # Check if the value is active in the current spec
        condition = '{name}={value}'.format(name=name, value=value)
        activated = condition in spec
        # Search for an override in the package for this value
        override_name = '{0}_or_{1}_{2}'.format(active, inactive, value)
        line_generator = getattr(self, override_name, None)
        # If not available use a sensible default
        if line_generator is None:
            def _default_generator(is_activated):
                if is_activated:
                    line = '--{0}-{1}'.format(active, value)
                    if active_parameters is not None and active_parameters(value):  # NOQA=ignore=E501
                        line += '={0}'.format(active_parameters(value))
                    return line
                return '--{0}-{1}'.format(inactive, value)
            line_generator = _default_generator
        args.append(line_generator(activated))
    return args

def with_or_without(self, name, active_parameters=None):
    """Inspects the multi-valued variant 'name' and returns the configure
    arguments that activate / deactivate the selected feature.
    :param str name: name of a valid multi-valued variant
    :param callable active_parameters: if present accepts a single value
        and returns the parameter to be used leading to an entry of the
        type '--with-{name}={parameter}
    """
    return self._activate_or_not(
        'with', 'without', name, active_parameters
    )
```
The part that searches for an override in the package should be able to find it for `verbs`. This is because `verbs` needs more customization than just `--with-verbs` or `--without-verbs` and the hook is there to permit more complex logic.

**Comment by eschnett** [comment]
I used `grep` to try and find where it would be called, and it wasn't mentioned anywhere.

I now see that Spack uses clever string manipulation to calculate function names at run time, then checks whether these exist, and then calls them! I like string concatenation as much as the next guy, but it's quite fragile, as typos are only found through testing. Personally, I would have gone for a dictionary of functions instead. This would allow some static checks as well.

More to the point -- I didn't write this code, and I didn't review it. I am now at a loss for how to understand it and use it. Is there some secret "Python IDE" that y'all are using for this? For me, `find | grep` is still the go-to tool for understanding code. Please don't break it.

In this case, a single line of comment in the package description would have done wonders for me.

This is a new feature. I checked; `with_or_without` is used in exactly one place, and it's not documented yet. Please leave comments for those less versed in Python than you. Thank you.
