### ISSUE TITLE
Error: There are no valid versions for spectrum-mpi that match ':'

### ISSUE THREAD

**Issue by junghans** [spack/spack#4119]
Working on #3852 (rebased of #4105), but now I am getting:
```
$ spack spec -t quinoa
Input spec
--------------------------------
[   ]  quinoa

Normalized
--------------------------------
[   ]  quinoa
[bl ]      ^boost
[bl ]      ^boostmplcartesianproduct
[bl ]      ^charm backend=mpi
[bl ]          ^mpi
[b  ]      ^cmake
[bl ]      ^h5part
[bl ]          ^hdf5+mpi
[bl ]              ^zlib@1.2.5:
[bl ]      ^hypre
[bl ]          ^netlib-lapack+lapacke
[bl ]      ^mad-numdiff
[bl ]      ^pegtl
[bl ]      ^pstreams
[bl ]      ^pugixml
[bl ]      ^random123
[bl ]      ^trilinos+exodus~tpetra
[bl ]          ^glm
[bl ]          ^matio
[bl ]          ^netcdf+mpi
[b  ]              ^m4
[bl ]      ^tut
[b  ]          ^python@2.5:
[bl ]              ^bzip2
[bl ]              ^ncurses
[b  ]                  ^pkg-config
[bl ]              ^openssl
[bl ]              ^readline
[bl ]              ^sqlite

Concretized
--------------------------------
==> Error: There are no valid versions for spectrum-mpi that match ':'
```

Huh?

**Comment by alalazo** [comment]
Reproducible on `develop`:
```console
$ spack spec spectrum-mpi 
Input spec
--------------------------------
spectrum-mpi

Normalized
--------------------------------
spectrum-mpi

Concretized
--------------------------------
==> Error: There are no valid versions for spectrum-mpi that match ':'
```
I assume it's related to the basence of **any** version directive in `spectrum-mpi`.

**Comment by junghans** [comment]
I see, I can work around that by adding `^openmpi`, but why did Spack pick `spectrum-mpi` as the default?

**Comment by adamjstewart** [comment]
@davydden @alalazo This sounds like the previous bug we mentioned where the default provider isn't being chosen correctly.

**Comment by alalazo** [comment]
After seeing @junghans comment I agree. At first I thought he selected on purpose `spectrum-mpi`.

**Comment by markcmiller86** [comment]
FYI...I see this new if I do spack graph fastmath (in my develop) but not if I do spack graph pestsc, or superlu-dist or anthing else. Wierd

**Comment by homerdin** [comment]
@junghans FYI, I ran into the same issue with the ecp-proxy-apps bundle package.  MPI is not depended on directly by the package.  Adding depends_on(mpi) to the ecp-proxy-apps package works around the issue if that makes sense to include in the package.   
  
I only have the default packages.yaml with `mpi: [openmpi, mpich]`

**Comment by junghans** [comment]
Hmm, I got it to, but then I ran it again and it works, so it is some sort of glitch.
```bash
while true; do
  spack install bla
done
```

**Comment by healther** [comment]
Just ran into this again. We have a complicated package and it failed already at the fetching stage (but it installed correctly). There was a change in the intermediate dependencies, which triggers this behavior now reproducible. Adding a `^python@2.7.15` allows the package to concretize again...

**Comment by raovgarimella** [comment]
Just hit this in a container build

**Comment by junghans** [comment]
Haven't seen that in a long time.
