### ISSUE TITLE
Is it possible to remove architecture and compiler flags from the SHA1 hash ?

### ISSUE THREAD

**Issue by samfux84** [spack/spack#4164]
We plan to distinguish instruction sets (sse4, avx, avx2) within a target (x86_64), such that we can have multiple installations of the same package on a shared file system, optimized for the different compute node types in our cluster (we have an inhomogeneous cluster and add on average 1 new hardware generation per year). An automounter script on the compute nodes would then be used to load the particular installation directory for a specific architecture (instruction set). There are two views in this approach. The sysadmin view (installation directories), and the user view (mountpoints).

If we for instance look at the Python 3.6.0 package, the 3 installation directories (bin directories) would then be (sysadmin view):

```
$spack/opt/spack/linux-centos7-x86_64_avx2/gcc-4.8.5/python-3.6.0-lmvbetshtmx36seaq2fbwrezrg5cn2zx/bin
$spack/opt/spack/linux-centos7-x86_64_avx/gcc-4.8.5/python-3.6.0-ehzms6e7wjfs6xl73qr6qpkl5fue32gi/bin
$spack/opt/spack/linux-centos7-x86_64_sse4/gcc-4.8.5/python-3.6.0-fyf3bemdndvyygcr6qsf7imqeelyb3t2/bin
```

The automounter script on the compute node would then mount $spack/opt/spack/PLATFORM-OS-ARCH as /cluster/apps and these 3 directories would look like (user view):

```
/cluster/apps/gcc-4.8.5/python-3.6.0-lmvbetshtmx36seaq2fbwrezrg5cn2zx/bin
/cluster/apps/gcc-4.8.5/python-3.6.0-ehzms6e7wjfs6xl73qr6qpkl5fue32gi/bin
/cluster/apps/gcc-4.8.5/python-3.6.0-fyf3bemdndvyygcr6qsf7imqeelyb3t2/bin
```

If a user is on a login node of the cluster, he needs to load modules, even though he does not know on which compute node (architecture) his job will run. The module file adds the path of the installation directory to the $PATH variable. At this point the information is incomplete, because I don't know which of the three paths (user view) should be added to the environment of the user. I would like to avoid that a user has to take a decision where his job will run, when he submits it, because the compute node should take care of mounting the proper installation directory.

The only possibility to have such a setup with incomplete information would be if the identifiers are not depending on the architecture and the compiler flags. In my opinion such a separation (excluding the architecture and the compiler flags from the SHA1 hash) would not lead to any conflict, as a compute node will only mount one installation tree (sse4, avx or avx2) at any time. 

If the unique identifier would be the same for all architectures, then the user view for the Python bin directory would be:

`/cluster/apps/gcc-4.8.5/python-3.6.0-lmvbetshtmx36seaq2fbwrezrg5cn2zx/bin`

In this case, the module would add this path to the user environment and depending on the node type, where the user job runs, the automounter would resolve this path to one of the 3 installation directories optimized for that particular architecture (a simple bash script is used to change the module file, such that it contains the path's of the user view and not the path's of the sysadmin view).

Coming back to the unique identifier. It contains information about

- The version and variant of the package to be installed
- The versions and variants of the dependencies of the package to be installed
- The architecture for which the package is installed
- The compiler flags

For distinguishing packages that only differ by the architecture and the compiler flags, there is already "arch" parameter from the "spack install" command (or the SPACK_TARGET_TYPE introduced by alalazo's      
#3754 ). If there was a way to remove the architecture and the compiler flags from the SHA1 hash, then the unique identifier would only contain information about the software and dependencies, but not of the hardware on which the software is used/installed. As described above, there would be no collisions as a compute node will only mount one installation tree (sse4, avx or avx2).

In order to test this idea, I tried to comment out the parts in the spec.py file of spack, which add the architecture and the compiler flags to the yaml_text variable:

lines 1337/1338:

```
        #if self.architecture:
        #    d.update(self.architecture.to_dict())
```

line 1351:

`        #params.update(sorted(self.compiler_flags.items()))`

Then I tried to install a package (patch) with the modified spec.py:

```
[spackapps@lo-login-02 bin]$ spack install -v patch@2.7.5 %gcc@4.8.5 arch=linux-centos7-x86_64_avx2
==> Error: Specs patch@2.7.5%gcc@4.8.5 cflags="-ftree-vectorize -O2 -march=core-avx2 -fPIC -mavx2" cppflags="-ftree-vectorize -O2 -march=core-avx2 -fPIC -mavx2" cxxflags="-ftree-vectorize -O2 -march=core-avx2 -fPIC -mavx2"  arch=linux-centos7-x86_64_avx2 and patch@2.7.5%gcc@4.8.5 have the same SHA-1 prefix!
```

I don't know why spack reports a hash collision in this case.

Any input/comment on this idea or the hash collision ?

**Comment by alalazo** [comment]
I don't see why you want to have a "user view" in the middle to complicate things. Imo you should mount / link for users just the correct set of module files, that will refer directly to the "sysadmin view". If you keep naming of module files consistent and eliminate hashes this will work transparently for them.

According to your use case, and assuming

1. You compiled `gcc@4.8.5` on every architecture, and added it to Spack compilers
1. You installed on every architecture `python@3.6`
1. You configured module files to have no hash

then your module file tree will look like:
```
|- spack/share/spack/linux-centos7-x86_64_avx2/python-3.6.0-gcc-4.8.5
|- spack/share/spack/linux-centos7-x86_64_avx/python-3.6.0-gcc-4.8.5
|- spack/share/spack/linux-centos7-x86_64_sse42/python-3.6.0-gcc-4.8.5
```
If on nodes that support `avx2` you make available the module files (i.e. automount) in:
```
spack/share/spack/linux-centos7-x86_64_avx2
```
and do similar thing on other nodes, then your users will see the module named `python-3.6-gcc-4.8.5` no matter where they are. This may require some care if you have nodes that are completely different from the others, but generally works.

> If there was a way to remove the architecture and the compiler flags from the SHA1 hash, then the unique identifier would only contain information about the software and dependencies, but not of the hardware on which the software is used/installed. As described above, there would be no collisions as a compute node will only mount one installation tree (sse4, avx or avx2).

I think this is fundamentally the wrong approach in the sense that a spec hash is the most important part in Spack, so we shouldn't be turning it upside down for the sake of parts that are just supposed to build on it (like the installation layout).

To turn the argument into an "ad absurdum ". If we do what you say we are basically saying that the platform doesn't matter and all the three python above have the same hash, hence are compared equal, hence they are the same, hence you don't need to differentiate them on `avx2`, `avx` or `sse4` in the first place :smile:

**Comment by samfux84** [comment]
@alalazo Thank you for your feedback.

We do not have separate login nodes for the different compute node types. From our "central" login nodes users can submit jobs that might run on a node that supports avx2, or they might run on a node that supports only sse4.

If a user loads a module, then he does not know if he needs to load the sse4 or the avx2 version of the module (and neither we do), because he does not know on which compute node his job will end up (the batch system will take this decision).

I fully agree with you that changing the hash would break the spack db, and that this therefore does not make sense.

But is it required that the full hash is used in the name of the installation directory ?

Because this is breaking the automounter setup, which would allow to have a single module file for all optimized Python 3.6.0 installation directories. The path that is added to $PATH would then be kind of a generic path that is then resolved by the automounter on the compute nodes.

The "user view" is only required for the automounter setup. Otherwise it does not make sense to have it and it would only complicates things as you mentioned in your comment.

**Comment by tgamblin** [comment]
@samfux84: would @scheibelp's #2168 address your issue here?  We want to keep the detailed provenance for installs, but with that PR you could project the installed packages into a per-machine view that does not depend on the arch or compiler flags.  The view would be a tree of symlinks pointing back into the Spack directory layout.

**Comment by alalazo** [comment]
@samfux84 Is this still an issue?

**Comment by samfux84** [comment]
@alalazo On our side, this is still an unresolved problem, but you can close this ticket.

To workaround this problem, I abandoned the idea of having separated installations for the different architectures. I have installed all spack packages on our system for AVX2, as in the cluster where we are using spack, all nodes support AVX2. The new compute nodes that we soon add will support AVX512, but since only a very small number of packages can benefit from the new instruction set, I will not recompile for AVX512.
