### ISSUE TITLE
Cannot download from sourceforge

### ISSUE THREAD

**Issue by AlexisPerry** [spack/spack#4212]
The install breaks down when trying to fetch matio:
      ==> Installing matio
      ==> Fetching http://downloads.sourceforge.net/project/matio/matio/1.5.9/matio-1.5.9.tar.gz
      curl: (22) The requested URL returned error: 503 Service Unavailable
      ==> Fetching from http://downloads.sourceforge.net/project/matio/matio/1.5.9/matio-1.5.9.tar.gz
failed.
      ==> Error: FetchError: All fetchers failed for matio-1.5.9-nhx6evruhcv7mdg63aws2kyabwenz4hi

If I manually change this in var/spack/repos/builtin/packages/matio/package.py to use https://github.com/tbeu/matio/releases instead of sourceforge, then the install works for matio, but then breaks for boost:
      ==> Installing boost
      ==> Fetching http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2
      curl: (22) The requested URL returned error: 503 Service Unavailable
      ==> Fetching from http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2 failed.
      ==> Could not determine url from list_url.
      ==> Error: FetchError: All fetchers failed for boost-1.63.0-cvwlpzyrr6ltgo3zadtaegwqvrkcudga

I do not know another URL besides sourceforge to use for boost.

**Comment by adamjstewart** [comment]
Hmm...
```
$ spack fetch matio
==> Fetching http://downloads.sourceforge.net/project/matio/matio/1.5.9/matio-1.5.9.tar.gz
######################################################################## 100.0%
$ spack fetch boost
==> Fetching http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2
######################################################################## 100.0%
```
What happens if you try downloading those URLs manually with `curl` and `wget`? Perhaps you need to update your SSL certs?

**Comment by AlexisPerry** [comment]
Manually downloading with wget works fine, but curl always fails.

**Comment by AlexisPerry** [comment]
This is what I get with curl for boost:

curl http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2
<html>
 <head>
  <title>302 Found</title>
 </head>
 <body>
  <h1>302 Found</h1>
  The resource was found at <a href="https://managedway.dl.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2">https://managedway.dl.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2</a>;
you should be redirected automatically.


 </body>
</html>

And then it exits without downloading anything.

**Comment by adamjstewart** [comment]
What happens when you do `curl -L`?
https://curl.haxx.se/docs/faq.html#How_do_I_tell_curl_to_follow_HTT

**Comment by AlexisPerry** [comment]
A whole bunch of garbage and I have to kill it with ctrl+C

**Comment by AlexisPerry** [comment]
Could having to go through a proxy be causing the problem?

**Comment by AlexisPerry** [comment]
Here's what happens with curl:

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"></style>
</head><body id=ERR_CONNECT_FAIL>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2">http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2</a></p>

<blockquote id="error">
<p><b>Connection to 216.34.181.59 failed.</b></p>
</blockquote>

<p id="sysmsg">The system returned: <i>(110) Connection timed out</i></p>

<p>The remote host or network may be down. Please try the request again.</p>


<br>
</div>

<hr>
<div id="footer">


</div>
</body></html>

**Comment by adamjstewart** [comment]
Oh wait, that bunch of garbage is actually the compressed file! If you use `curl -LO` it will work. Let me see if I can add that to our curl wrapper to solve this permanently.

**Comment by adamjstewart** [comment]
Hmm, it seems that we already use this flag:
https://github.com/LLNL/spack/blob/develop/lib/spack/spack/fetch_strategy.py#L228

@tgamblin You know more about `fetch_strategy` than I do.

**Comment by tgamblin** [comment]
@AlexisPerry: where are you running spack and where are you running `curl` manually?  Are those the same machines?

**Comment by AlexisPerry** [comment]
Yes, they are both on the same machine.  curl -L0 makes the garbage go away, but it still fails to connect to the URL, let alone download anything.

**Comment by tgamblin** [comment]
@AlexisPerry: it sounds like to me like your network requires a web proxy or some other setting to allow `curl` to connect outside.  Are you on an SNL machine?  Maybe @sknigh has seen this before.

**Comment by sknigh** [comment]
@AlexisPerry Try ```spack -k install matio```

**Comment by AlexisPerry** [comment]
Nope, still doesn't work:

==> Installing matio
==> Fetching http://downloads.sourceforge.net/project/matio/matio/1.5.9/matio-1.5.9.tar.gz

curl: (22) The requested URL returned error: 503 Service Unavailable
==> Fetching from http://downloads.sourceforge.net/project/matio/matio/1.5.9/matio-1.5.9.tar.gz failed.
==> Error: FetchError: All fetchers failed for matio-1.5.9-nhx6evruhcv7mdg63aws2kyabwenz4hi
/home/aperry/local/amanzi/tpls/spack/lib/spack/spack/package.py:923, in do_fetch:
     896      def do_fetch(self, mirror_only=False):
     897          """
     898          Creates a stage directory and downloads the tarball for this package.
     899          Working directory will be set to the stage directory.
     900          """
     901          if not self.spec.concrete:
     902              raise ValueError("Can only fetch concrete packages.")
     903  
     904          start_time = time.time()
     905          if spack.do_checksum and self.version not in self.versions:
     906              tty.warn("There is no checksum on file to fetch %s safely." %
     907                       self.spec.format('$_$@'))
     908  
     909              # Ask the user whether to skip the checksum if we're
     910              # interactive, but just fail if non-interactive.
     911              ck_msg = "Add a checksum or use --no-checksum to skip this check."
     912              ignore_checksum = False
     913              if sys.stdout.isatty():
     914                  ignore_checksum = tty.get_yes_or_no("  Fetch anyway?",
     915                                                      default=False)
     916                  if ignore_checksum:
     917                      tty.msg("Fetching with no checksum.", ck_msg)
     918  
     919              if not ignore_checksum:
     920                  raise FetchError("Will not fetch %s" %
     921                                   self.spec.format('$_$@'), ck_msg)
     922  
  >> 923          self.stage.fetch(mirror_only)
     924  
     925          self._fetch_time = time.time() - start_time
     926  
     927          if spack.do_checksum and self.version in self.versions:
     928              self.stage.check()
     929  
     930          self.stage.cache_local()

**Comment by AlexisPerry** [comment]
For clarity, I'm on a LANL machine called Darwin.

**Comment by tgamblin** [comment]
@junghans: I believe you are familiar with Darwin, right?

**Comment by junghans** [comment]
You need to do something like:
```
export http_proxy="http://proxyout.lanl.gov:8080"
export https_proxy="http://proxyout.lanl.gov:8080"
export no_proxy="lanl.gov"
```

**Comment by AlexisPerry** [comment]
http_proxy and https_proxy are set to the correct proxy by default on Darwin. Setting no_proxy as indicated above did not change anything.  Curl still fails to fetch from sourceforge.

**Comment by junghans** [comment]
Actually
```
curl -O http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2
```
broken for me, too, on Darwin (and on my laptop), seems to be a LANL problem.

Other locations e.g. github works:
```
curl -O https://github.com/votca/csg/releases/download/v1.4/votca-csg-manual-1.4.pdf
```

**Comment by KineticTheory** [comment]
@junghans I've had this same problem at LANL.  As a work around, I was able to download the archive via Chrome and add it to my spack mirror. Shoot me an email if you want access to my mirror at LANL.

**Comment by xywei** [comment]
Had similar issues when downloading from Sourceforge. Solved by visiting the download page via a web browser and switching to another mirror that works.

**Comment by roblatham00** [comment]
I'm having a similar problem, but not on a LANL machine.  I can 'wget' the libuuid tarball from sourceforge (wget says it had to retry), but curl (and spack) say connection reset by peer
