### ISSUE TITLE
CorruptDatabaseError: Invalid record in Spack database

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#4232]
@alalazo This seems to be an unintended consequence of the addition of multi-valued variants. I tried installing a new package to a Spack installation from before multi-valued variants existed and now I see:
```
==> Error: CorruptDatabaseError: Invalid record in Spack database: hash: plrlzuulbe7huekbvkh4vl6rruimhkpi, cause: MultipleValuesInExclusiveVariantError: multiple values are not allowed for variant "nprocs"
```
Is this another case of "Spack should use the package.py from when it was installed, not the current one"?

**Comment by adamjstewart** [comment]
Unfortunately, this doesn't work either:
```
$ spack reindex
==> Warning: Spack database was corrupt. Will rebuild. Error was:
  Invalid record in Spack database: hash: plrlzuulbe7huekbvkh4vl6rruimhkpi, cause: MultipleValuesInExclusiveVariantError: multiple values are not allowed for variant "nprocs"
    /nfs/software/spack/opt/spack/.spack-db/index.json
==> Error: Unable to read file: /nfs/software/spack/opt/spack/linux-centos7-x86_64/intel-17.0.2/npb-3.3.1-plrlzuulbe7huekbvkh4vl6rruimhkpi/.spack/spec.yaml
Cause: multiple values are not allowed for variant "classes"
```

**Comment by alalazo** [comment]
I'll try to have a look at it during the week-end. How large is the db tarball for this case? I think I need that to try reproduce the problem.

**Comment by adamjstewart** [comment]
Actually small for once: 
[spack-db.develop.1a6b4af.2017-05-12-110618.tar.gz](https://github.com/LLNL/spack/files/997329/spack-db.develop.1a6b4af.2017-05-12-110618.tar.gz)

**Comment by alalazo** [comment]
> I'll try to have a look at it during the week-end.

@adamjstewart That was a few week-ends ago, and obviously I totally forgot about this issue! I assume that by now almost everybody is using a Spack checkout with MV support. Do you think this issue is still worth looking into?

**Comment by adamjstewart** [comment]
No one else has reported it, and it only ever happened to a single Spack installation for me. Closing unless someone else reports the same problem.
