### ISSUE TITLE
extra_rpaths in compilers.yaml not working

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#4261]
In #4256, I added a package for OpenBabel. After installation, I ran `ldd -r` on the libraries and found that they were linking to the wrong `libstdc++` library:
```
$ ldd -r libopenbabel.so
libopenbabel.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by libopenbabel.so)
...
libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002b47e587d000)
```
By adding the GCC compiler to my `LD_LIBRARY_PATH`, I was able to resolve this problem. I tried making the following change in `compilers.yaml` to do this automatically:
```yaml
- compiler:
    environment: {}
    extra_rpaths:
    - /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/gcc-6.1.0-q2zosj3igepi3pjnqt74bwazmptr5gpj/lib64
    flags: {}
    modules: []
    operating_system: centos6
    paths:
      cc: /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/gcc-6.1.0-q2zosj3igepi3pjnqt74bwazmptr5gpj/bin/gcc
      cxx: /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/gcc-6.1.0-q2zosj3igepi3pjnqt74bwazmptr5gpj/bin/g++
      f77: /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/gcc-6.1.0-q2zosj3igepi3pjnqt74bwazmptr5gpj/bin/gfortran
      fc: /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/gcc-6.1.0-q2zosj3igepi3pjnqt74bwazmptr5gpj/bin/gfortran
    spec: gcc@6.1.0
    target: x86_64
```
but it appears that `extra_rpaths` isn't working. I reinstalled Open Babel but it still links to the system `libstdc++` instead of the one in `$GCC_ROOT/lib64`. Adding it manually to `LD_LIBRARY_PATH` works:
```
$ ldd -r /blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0/openbabel-2.4.1-xqe2leslpleij3g7u4dpje7joxcdydjh/lib/libopenbabel.so
...
	libstdc++.so.6 => /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/gcc-6.1.0-q2zosj3igepi3pjnqt74bwazmptr5gpj/lib64/libstdc++.so.6 (0x00002b4b18855000)
```
@scheibelp?

**Comment by adamjstewart** [comment]
Hmm, now I'm even more confused. I added debug messages to `lib/spack/spack/build_environment.py` and `lib/spack/env/cc` and confirmed that we are indeed adding `extra_rpaths` via the compiler wrappers. But it's definitely not sticking. Do we also need to add them to `-DCMAKE_INSTALL_RPATH`? I don't know enough about CMake to know why this isn't working, but I'd be curious to see if it works for non-CMake packages.

**Comment by davydden** [comment]
what if you specify explictly compiler wrappers from Spack in 
```
-DCMAKE_C_COMPILER=
-DCMAKE_CXX_COMPILER=
-DCMAKE_Fortran_COMPILER=
```
?

**Comment by davydden** [comment]
you should also see which compiler is actually called in build logs (`build.out` in the prefix).

**Comment by adamjstewart** [comment]
Oh it's definitely using the compiler wrappers. I added debug messages to the compiler wrappers and it's showing up.

**Comment by adamjstewart** [comment]
Update: It looks like `extra_rpaths` is actually working, at least for Autotools-based packages. I came up with an interesting way to test it:

Take any 2 packages where one depends on the other (I used `bzip2` and `zip` because they build quickly). If I build `zip` and run `ldd -r` on the executable, I can see that it links to Spack-built `bzip2` properly. Now, uninstall `zip`, comment out the `depends_on('bzip2')`, and reinstall `zip`. As long as you have `bzip2-devel` installed on the system, `zip` will link to the system installation. Now, add the directory containing the `bzip2` libraries to `extra_rpaths` in `compilers.yaml`. When you rebuild, you'll find that it now links to the Spack-build `bzip2` even though it's not an explicit dependency.

I'm going to test things out with a simple CMake-based package to confirm my suspicion that this is limited to CMake-based packages. We may just need to add `extra_rpaths` to `-DCMAKE_INSTALL_RPATH` to solve the original problem I was having.

**Comment by scheibelp** [comment]
I'm glad you're looking at this because I think I was checking into the wrong stuff. Nevertheless FWIW: Based on http://stackoverflow.com/questions/8482152/whats-the-difference-between-rpath-and-l I think ```extra_rpaths``` should add ```-L``` as well as ```-rpath``` (for now it is only doing the latter)

**Comment by adamjstewart** [comment]
Good point, I'll try adding that too.

**Comment by adamjstewart** [comment]
Hmm, my test didn't work like I expected. I tested with the `libssh2` package, which uses CMake to build and depends on `openssl`. I tried the same method as outlined above and found that `extra_rpaths` was sufficient for it to find the Spack-built `openssl` libraries. Not sure why OpenBabel couldn't find the right GCC libs.

Next I'll try adding `-L` in addition to `-rpath` in the compiler wrappers. If that doesn't work, I'll try adding `extra_rpaths` to `-DCMAKE_INSTALL_RPATH`.

**Comment by adamjstewart** [comment]
@scheibelp Added your suggestion but it didn't help:
```diff
diff --git a/lib/spack/env/cc b/lib/spack/env/cc
index aa3c2aa..dae67be 100755
--- a/lib/spack/env/cc
+++ b/lib/spack/env/cc
@@ -328,8 +328,10 @@ IFS=':' read -ra extra_rpaths <<< "$SPACK_COMPILER_EXTRA_RPATHS"
 for extra_rpath in "${extra_rpaths[@]}"; do
     if [[ $mode == ccld ]]; then
         $add_rpaths && args=("$rpath$extra_rpath" "${args[@]}")
+        args=("-L$extra_rpath" "${args[@]}")
     elif [[ $mode == ld ]]; then
         $add_rpaths && args=("-rpath" "$extra_rpath" "${args[@]}")
+        args=("-L$extra_rpath" "${args[@]}")
     fi
 done
```
I'll try `-DCMAKE_INSTALL_RPATH` now.

**Comment by adamjstewart** [comment]
No luck 😦 
```diff
diff --git a/lib/spack/spack/build_systems/cmake.py b/lib/spack/spack/build_systems/cmake.py
index 43d177d..933e0a3 100644
--- a/lib/spack/spack/build_systems/cmake.py
+++ b/lib/spack/spack/build_systems/cmake.py
@@ -116,8 +116,10 @@ class CMakePackage(PackageBase):
 
         # Set up CMake rpath
         args.append('-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE')
-        rpaths = ':'.join(spack.build_environment.get_rpaths(pkg))
-        args.append('-DCMAKE_INSTALL_RPATH:STRING={0}'.format(rpaths))
+        rpaths = spack.build_environment.get_rpaths(pkg)
+        rpaths.extend(pkg.compiler.extra_rpaths)
+        args.append('-DCMAKE_INSTALL_RPATH:STRING={0}'.format(
+            ':'.join(rpaths)))
         return args
 
     @property
```
I can see `/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/gcc-6.1.0-q2zosj3igepi3pjnqt74bwazmptr5gpj/lib64` at the end of my `-DCMAKE_INSTALL_RPATH`, so the changes worked, but the binaries are still linking to the system `libstdc++`. At this point I'm out of ideas.

**Comment by scheibelp** [comment]
To collect your points:

* If you build openbabel with extra_rpaths, it doesn't actually load those unless you set LD_LIBRARY_PATH before using it (to be clear, my understanding is that you didn't need to set LD_LIBRARY_PATH while building openbabel). I also want to make sure: do the produced binaries/libraries contain the rpaths (i.e. they show up in ```readelf```)?
* Other cmake-based packages (or at least one - libssh2) do load libraries referenced by extra_rpaths
* Autotools packages also load libraries referenced in extra_rpaths

Based on that my suspicion would be something that OpenBabel is doing is causing an issue. For example https://fossies.org/linux/openbabel/CMakeLists.txt contains the following which looks suspicious:

```
  405 # Some rpath handling for Linux and Mac
  406 if(UNIX AND BUILD_SHARED)
  407   if(APPLE)
  408     set(CMAKE_INSTALL_NAME_DIR ${CMAKE_INSTALL_PREFIX}/${LIB_INSTALL_DIR})
  409   else()
  410     set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/${LIB_INSTALL_DIR}"
  411         CACHE PATH "Set sane rpath")
  412     set(CMAKE_SKIP_BUILD_RPATH FALSE)
  413     set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
  414     set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
  415   endif()
  416 endif()
```

**Comment by adamjstewart** [comment]
@scheibelp Correct. Unfortunately my understanding of CMake is very limited. What do those flags do? Can we override them in `CMakePackage` or do I have to patch OpenBabel's `CMakeLists.txt`?

**Comment by scheibelp** [comment]
I also don't know much about cmake specifically. A few spack packages appear to set CMAKE_BUILD_WITH_INSTALL_RPATH, e.g. llvm: perhaps that would work here?

**Comment by adamjstewart** [comment]
@scheibelp I think those default settings actually look correct. According to https://cmake.org/Wiki/CMake_RPATH_handling:

> In many cases you will want to make sure that the required libraries are always found independent from LD_LIBRARY_PATH and the install location. Then you can use these settings:
> ```
> # use, i.e. don't skip the full RPATH for the build tree
> SET(CMAKE_SKIP_BUILD_RPATH  FALSE)
>
> # when building, don't use the install RPATH already
> # (but later on when installing)
> SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE) 
>
> SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
>
> # add the automatically determined parts of the RPATH
> # which point to directories outside the build tree to the install RPATH
> SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
> ```

**Comment by ptooley** [comment]
I've just run into this issue, and I have worked out what is going wrong for me. Tl;Dr it is a resolution order issue:

Turns out both the library path to my compiler *AND* to the system compiler were in the RPATH of my executable. In my case /usr/lib64 is validly in the RPATHs because I am using system ssl and system zlib, but it is in the list *BEFORE* the rpath to my system compiler because ``extra_rpaths`` appends to the list of rpaths.  This meant that at runtime the libstdc++ was resolving to ``/usr/lib64/libstdc++.so`` instead of ``/sw/compilers/gcc/8.2.0/lib64/libstdc++.so``

Possible solutions that I can see are:

1. `extra_rpaths` should be *PREPENDED* to the RPATH list, rather than appended.

1. Any RPATH entries beginning in `/usr` should be moved to the end of the RPATH list, to ensure spack provided libraries have the chance to be used first.

My preference would be for option 2 since I think there is the potential for a more general issue with system libraries shadowing. As a real-life for instance:

- I am currently using a system which provides both openssl and an old lapack, both in /usr/lib64. 
- I want to use system openssl, but the Spack provided lapack version. Unfortunately when my package is linked, the `RPATH=/usr/lib64` for openssl is earlier in the list than the `RPATH=~/spack/blah/lapack-blah/lib64` to the spack provided lapack. The Spack provided lapack library is then shadowed by the system lapack but because of ABI compatibility it works just fine.

Now in my case I am not too bothered since I am fairly sure I can trust the system lapack not to give me bad results, however there is real potential for subtle but nasty bugs creeping in here, with users unwittingly using an unintended library version due to this resolution order issue.

Comments? @scheibelp? @adamjstewart?

**Comment by vickiegpt** [comment]
I've got problem when compiling gromacs depending on intel@18 using script: `spack install gromacs%intel@18.0.5^m4/mkc`, which generated the error:

```bash
1 error found in build log:
     1    ==> gromacs: Executing phase: 'cmake'
     2    ==> [2020-10-16-15:35:28.826308] 'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/gromacs-2020.4-
          xel7u6e7cgvffpwyadzpzpsxtaluldid' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' '-DCMAKE_
          INSTALL_RPATH:STRING=/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/gromacs-2020.4-xel7u6e7cgvffpwyadzpzpsxtaluldid/lib;/opt/spack/opt/spack/linux-ubuntu18.
          04-x86_64/intel-18.0.5/gromacs-2020.4-xel7u6e7cgvffpwyadzpzpsxtaluldid/lib64;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/fftw-3.3.8-hkafstsory3monya57shv
          ij4bm5zu7ju/lib;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/openmpi-3.1.6-365vjbu6ba2prcdvvrulvefzs7kqtvxo/lib;/opt/spack/opt/spack/linux-ubuntu18.04-x86
          _64/intel-18.0.5/hwloc-1.11.11-wpaokkydzgt4grnoon5eovlqbqbpt3gu/lib;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/libpciaccess-0.16-pk7ermoojhlbmnrjh7mrala
          rvxmsioj7/lib;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/libxml2-2.9.10-hvmgbun2uxupiinktqusndabbnvfhjmt/lib;/opt/spack/opt/spack/linux-ubuntu18.04-x86_
          64/intel-18.0.5/libiconv-1.16-tqxfwxawi35iw4fayltpkbzyx4bvdbus/lib;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/xz-5.2.5-s3vjujl7t574nsppmpf3zqpqk27b42yj/
          lib;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/zlib-1.2.11-pdqfqecof2yqqcrhgsabh5nzeq5jk6x2/lib;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0
          .5/numactl-2.0.12-ehxzo534kee7nk7gmysv77urhp3a762m/lib' '-DCMAKE_PREFIX_PATH:STRING=/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/cmake-3.18.2-qixsmzw6m43m
          hnxpfmejiuiwc2kyk6p5;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/openmpi-3.1.6-365vjbu6ba2prcdvvrulvefzs7kqtvxo;/opt/spack/opt/spack/linux-ubuntu18.04-x8
          6_64/intel-18.0.5/fftw-3.3.8-hkafstsory3monya57shvij4bm5zu7ju;/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-18.0.5/hwloc-1.11.11-wpaokkydzgt4grnoon5eovlqbqbpt3gu'
           '-DGMX_INSTALL_LEGACY_API=ON' '-DGMX_MPI:BOOL=ON' '-DGMX_HWLOC:BOOL=ON' '-DGMX_GPU:BOOL=OFF' '-DGMX_SIMD:STRING=None' '-DGMX_USE_RDTSCP:BOOL=ON' '-DGMX_BUILD_MDRUN_ONL
          Y:BOOL=OFF' '-DGMX_OPENMP:BOOL=ON' '-DGMX_RELAXED_DOUBLE_PRECISION:BOOL=OFF' '-DGMX_FFT_LIBRARY=fftw3' '/tmp/root/spack-stage/spack-stage-gromacs-2020.4-xel7u6e7cgvffpw
          yadzpzpsxtaluldid/spack-src'
  >> 3    cmake: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
```
The solution is by [here](https://mixable.blog/spack-and-intel-parallel-studio-error-while-loading-shared-libraries-libimf-so/) to prepend `extra_rpath`. but still the same result.

I found that if spack have to deal with cmake first, the modification should lie in intel.py. However the extra_rpath in the `~/.spack/linux/compilers.yaml`  will be overwritten by [lib/spack/spack/build_systems/intel.py](https://github.com/spack/spack/blob/2ebadbc267ffb4e2c175bdd7ceea9eb20e92254f/lib/spack/spack/build_systems/intel.py#L1057)

For temporary solution is to prepend $SPACK_COMPILER_EXTRA_RPATHS in `intel.py`

**Comment by naromero77** [comment]
@adamjstewart Not sure what the original issue was about. But many compilers rely on bits of GCC, e.g. the header files or possible other things as well. Many of the vendor compilers will default to the GCC compiler in your path or can be overridden with an extra compiler-specific flag (e.g. Intel) or a compiler-specific configuration file (e.g. IBM XL).

**Comment by dev-zero** [comment]
as commented in https://github.com/spack/spack/issues/10308#issuecomment-716391950 I think the linker itself already needs `libimf.so` to run (note how it says "error while loading shared libraries" and not "cannot find -limf" which is the usual error when an object on the linker line can't be found), while the extra rpaths are taken into account only for the object to link, hence the documented way to use a `modules` file instead should ensure that the required path also ends up in the `LD_LIBRARY_PATH`
