### ISSUE TITLE
Automatically detect when a newer package version is available

### ISSUE THREAD

**Issue by eschnett** [spack/spack#429]
Spack could use its knowledge about a package's url scheme to automatically detect when a newer version than then ones listed in the package description has become available. If so, it could alert the user when the package is installed. Alternatively, there could be a command that makes Spack check all installed packages.

**Comment by mathstuf** [comment]
It might be better to work with [anyita](https://github.com/fedora-infra/anitya) and add packages to [release-monitoring.org](https://release-monitoring.org/) and have it file bugs for packages to be updated.

**Comment by mathstuf** [comment]
Actually, writing a tool to file bugs based on the output of anyita would probably be the way to go. Anyita definitely outputs information over the [fedbus](http://www.fedmsg.com/en/latest/), so listening just for package update bits shouldn't be *too* demanding.
