### ISSUE TITLE
Can't build jupyter notebook with python3 because node-js requires python2 to build

### ISSUE THREAD

**Issue by syntion** [spack/spack#4319]
I am tryed to install jupyter notebook for python 3 by running:
```
spack install --verbose py-jupyter-notebook@5.0.0 ^python@3.6.0~tk~ucs4
==> Error: Invalid spec: 'python@3.6.0~tk~ucs4'. Package python requires version 2.7:2.8, but spec asked for 3.6.0
```

The reason for this, that `node-js` depends on python2 to build:
```
depends_on('python@2.7:2.8', type='build')
```

As python2 is only required as build depency for node-js is should be possible to build node-js with python2 and use jupyter with python3. 
Is it possible to pass this to spack?

**Comment by tgamblin** [comment]
@scheibelp: does #2548 fix this?

**Comment by syntion** [comment]
Thx for the fast response. I tried it, but now I run in actually wrongly declared deps (some backport packages). I think, this will take a while to figure it out.

So the first impression is good and I will let you know how it turns out.

**Comment by scheibelp** [comment]
If you have python 2 installed on your system, a temporary solution like https://github.com/LLNL/spack/pull/4145 may also work where you remove the python dependency from node-js. Ultimately an approach like #2548 (concretizing build dependencies separately) would be the solution to this.

**Comment by syntion** [comment]
@tgamblin I applied #2548, rebased it onto master and fixed some packages dependencies (mostly now unneeded python backports) and ended up with
```
==> Error: Separate concretization of node-js produced build-time conflict
```
So this didn't work, but is there any possibility to extract a bit more information, than this message?

@scheibelp I think I have at least on person, which is using this on Arch and there the python binary  defaults to python3.

**Comment by scheibelp** [comment]
There is a case for npm analogous to https://github.com/LLNL/spack/pull/2548#issuecomment-296329214:

```
X -[b] -> npm -[b,r]-> node-js
X -[b,r] -> node-js
```

I have committed an analogous temporary hack in the case of py-jupyter-notebook (and there are also several packages in that DAG which depend on py-setuptools and I applied the hack to them too).

I also updated the error message so you can see the package that generated to two conflicting instances.

**Comment by healther** [comment]
is there any progress on this issue?

**Comment by s-sajid-ali** [comment]
Alternatively, if support for [jupyer-lab](https://github.com/jupyterlab/jupyterlab) is added this request would be redundant.

**Comment by healther** [comment]
As a stop gap measure we ended up removing the python dependency. This basically assumes that the system python is available and is a python2. 

Btw. any Arch users here? There the system python is already a python3 isn't it? How do you install node-js under these circumstances?

**Comment by s-sajid-ali** [comment]
In that case, is there an equivalent for [conda_nb_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) that allows one to switch between multiple python environments at run time ?

**Comment by adamjstewart** [comment]
Note that newer versions of node-js now support Python 3, and our Jupyter packages no longer depend on node-js. There are still a few issues in the Jupyter ecosystem that require separate concretization of build deps (different packages require incompatible versions of `py-jupyter-packaging`), but I've worked around those in #27798 by creating separate packages for different versions of `py-jupyter-packaging`. Not sure if we should close this issue since it's no longer present or keep it open since the problem still affects other packages and we still need separate concretization of build deps.

**Comment by alalazo** [comment]
Python 2 has been removed a few versions ago. Closing the issue.
