### ISSUE TITLE
mesa does not recognize libxcb version correctly

### ISSUE THREAD

**Issue by samfux84** [spack/spack#4444]
I am trying to install mesa 12.0.3 using the command:

`spack install mesa@12.0.3 ^bison@3.0.4 ^dri2proto@2.8 ^dri3proto@1.0 ^glproto@1.4.17 ^libpthread-stubs@0.3 ^libxcb@1.12 ^libxext@1.3.3 ^libxshmfence@1.2 ^pkg-config@0.29.2 ^py-mako@1.0.4 ^flex@2.6.3 ^libdrm@2.4.70 ^libx11@1.6.3 ^libxdamage@1.1.4 ^libxfixes@5.0.2 ^openssl@1.0.1e ^presentproto@1.0 ^python@2.7.13+tk %gcc@4.8.5 arch=linux-centos7-x86_64`

It fails with the following error:

```
==> Error: ProcessError: Command exited with status 1:
    '/cluster/apps/spack/var/spack/stage/mesa-12.0.3-ml7hu2oihsajd36kowkabf4d4zeo5ydm/mesa-12.0.3/configure' '--prefix=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/mesa-12.0.3-ml7hu2oihsajd36kowkabf4d4zeo5ydm'
/cluster/apps/spack/lib/spack/spack/build_systems/autotools.py:266, in configure:
     258      def configure(self, spec, prefix):
     259          """Runs configure with the arguments specified in
     260          :py:meth:`~.AutotoolsPackage.configure_args`
     261          and an appropriately set prefix.
     262          """
     263          options = ['--prefix={0}'.format(prefix)] + self.configure_args()
     264  
     265          with working_dir(self.build_directory, create=True):
  >> 266              inspect.getmodule(self).configure(*options)
```

Build logs show:

```
checking for GLPROTO... yes
checking for DRI2PROTO... yes
checking for DRI3PROTO... yes
checking for PRESENTPROTO... yes
configure: error: DRI3 requires xcb >= 1.9.3
```

but when checking the version of the xcb module with pkg-config, it finds the version that is new enough:

```
[spackapps@lo-login-02 ~]$ pkg-config --modversion xcb 
1.12
```

Anybody else experiencing the same problem ?

**Comment by samfux84** [comment]
Found a workaround:

`[spackapps@lo-login-02 scripts]$ export PKG_CONFIG_PATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libxcb-1.12-j7dszeiqq37w43g3nbfjcwnuzikzyaab/lib/pkgconfig:$PKG_CONFIG_PATH`

helps the confirgure script of mesa to find libxcb, but then mesa gets stuck at a later stage because of missing libudev:

```
checking for LIBUDEV... no
checking for GLPROTO... yes
checking for DRI2PROTO... yes
checking for DRI3PROTO... yes
checking for PRESENTPROTO... yes
checking for XCB_DRI3... yes
checking for XF86VIDMODE... no
checking for DRIGL... yes
configure: error: libudev-dev or sysfs required for building DRI
```

**Comment by samfux84** [comment]
building mesa also requires libudev + headers, expat, libomxil-bellagio, LLVM

**Comment by adamjstewart** [comment]
I tried really hard to package `systemd` which provides `libudev` but never got it working on CentOS 6. If you can find a standalone download for `libudev` that would be helpful.

**Comment by samfux84** [comment]
libudev was merged into systemd back in 2012. Already then people were not happy about it:

https://lwn.net/Articles/490413/

There is a fork from systemd-udev called eudev, which was started by gentoo developers:

Github repo:
https://github.com/gentoo/eudev

Project wiki:
https://wiki.gentoo.org/wiki/Project:Eudev

Archive with all release tarballs:
http://dev.gentoo.org/~blueness/eudev/

Maybe this could be used as alternative to systemd-udev. I compiled it just to see how the libraries and header files look like:

```
[sfux@[sfux@develop01 bin]$ ls
udevadm
develop01 lib]$ ls
libudev.a  libudev.la  libudev.so  libudev.so.1  libudev.so.1.6.3  pkgconfig  udev
[sfux@develop01 include]$ ls
libudev.h  udev.h
```

**Comment by olesenm** [comment]
I had previously found that mesa-12 (without spack) produced an installation without proper GL includes.
Mesa-11, 13 and 17 seemed to be ok. It might be worthwhile trying with a new mesa as well.

**Comment by chuckatkins** [comment]
No longer applicable after the overhaul and re-work of mesa
