### ISSUE TITLE
Inconsistent API for similar functions

### ISSUE THREAD

**Issue by alalazo** [spack/spack#4484]
While working on #4483 I noticed that in `llnl.util.filesystem`:
```python
def find(root, files, recurse=True):
    ...
```
takes root as the first argument and the list of files as the second argument, while:
```python
def find_headers(headers, root, recurse=False):
    ...

def find_libraries(libraries, root, shared=True, recurse=False):
    ...
```
do the opposite. I think one of the two must be changed for the sake of consistency, as the functions provide basically the same semantic.

**Comment by adamjstewart** [comment]
I wrote find. I went with this implementation so that it would be similar to command line find, but I'm open to changing either one to be more in line with the other.

**Comment by tgamblin** [comment]
My vote would be to make the root parameter on `find_headers` and `find_libraries` come first.

**Comment by alalazo** [comment]
> My vote would be to make the root parameter on find_headers and find_libraries come first.

So, if everyone agrees on that, I'll prepare a PR to fix the issue and change all the places where `find_libraries` and `find_headers` are called.
