### ISSUE TITLE
use ctest with cmake

### ISSUE THREAD

**Issue by lgarren** [spack/spack#4503]
cmake comes with ctest, which is used to run all tests created by cmake.   Using ctest provides more options than simply calling "make test".   I request that ctest be used in the test phase for packages built with cmake.  Note that both commands return status 0 if there are no tests to execute.  

 The main reason for this request is that ctest recognizes and uses the -jN option.  Unfortuntately, in the context of cmake, "make test -jN" simply runs the tests serially.

**Comment by mathstuf** [comment]
Note that not all CMake projects use CTest and using CTest does not imply CMake (though that is a much stronger correlation). IMO, the Spack support for CTest should be independent of CMake (though probably much easier to enable in CMake projects if there's any setup involved).
