### ISSUE TITLE
paraview build failure - weird rpath

### ISSUE THREAD

**Issue by olesenm** [spack/spack#4581]
I started encountering really a weird issue while building paraview (using the package from develop, which previous worked fined).

Everything progresses fine until the link stage, at which point spack is passing through a really weird rpath that fails:

    -rpath,/tmp/mark/spack-stage/spack-stage-vMgFh5/ParaView-v5.3.0/spack-build/lib:::::::::  ../../../lib/libvtksys-pv5.3.so.1 -lpthread -ldl

Note that the `::::::::` junk is actually about 4000 chars long, I just chopped it for display purposes.

**Comment by davydden** [comment]
@jppelteret if I recall correctly u came across the same issue of ugly broken rpaths?

**Comment by jppelteret** [comment]
@davydden Yes, I think I encountered this but I can neither remember the context nor what the cause of the problem was. I'm looking through closed issues and PR to see if I can find any information...

**Comment by olesenm** [comment]
I think that it was gone, but now it's back (or I just didn't try building for a while). Building paraview@5.9.1 on linux-opensuse42-x86_64/gcc-4.8

**Comment by luigi-calori** [comment]
Hope not to make noise:
On our cluster we have successfully built Paraview 5.4.1 based on Mesa, forcing dependency on qt4.
our package.yaml contains:

 paraview:
    variants:
    - +opengl2
    - +mpi
    - +python
    - +qt
    - +hdf5
    - +examples
  openmpi:
    variants:
    - schedulers=tm,slurm
    - fabrics=psm2
  mesa:
    variants: +llvm
  qt:
    version:
    - 4.8.6
    variants: +examples+opengl+dbus

We also used #5802

**Comment by olesenm** [comment]
The pile of `:::::::::` in the output made me wonder if there is a something silly going on the bash part of the `cc` scripts.

**Comment by olesenm** [comment]
Got hit with this again, while compiling paraview. As a workaround, I then tried with VTK and found the same thing - many entries with `::::::::::` (about 6564 each time) in the output and can't link.

Put in some debug lines into `env/cc` around line 235,
```
input_command="$@"
args=("$@")

echo "cc called with ${args[@]} args" 1>&2
for arg in "$@"; do
    if [ -n "$arg" ]
    then
        echo "is empty"  1>&2
    fi
done
```
and it reports many instances of some of the array elements being empty. May be these are doing something strange when put back together?

**Comment by alalazo** [comment]
Closing this very old issue, since it's stale and the recipe for Paraview got reworked in the last 3 years. Feel free to reopen if the issue still persist.
