### ISSUE TITLE
Alternate way to fetch from repositories

### ISSUE THREAD

**Issue by citibeth** [spack/spack#463]
I see the description at:

http://software.llnl.gov/spack/packaging_guide.html#vcs-fetch

Some cloud-based repositories (ie. GitHub and SourceForge) can provide tarballs for any branch or tag.  You just have to supply the right URL.  My experience using "spack create" in such a case was very good.  I just had to fill in the "version(...)" tag (but not the hashcode) manually.  With that, I got the following package.py:

```
from spack import *

class Blitz(Package):
    """N-dimensional arrays for C++"""
    homepage = "http://github.com/blitzpp/blitz"

# This version doesn't have the configure script generated yet.
    url      = "https://github.com/blitzpp/blitz/tarball/1.0.0"

    version('1.0.0', '9f040b9827fe22228a892603671a77af')

    # FIXME: Add dependencies if this package requires them.
    # depends_on("foo")

    def install(self, spec, prefix):
        # FIXME: Modify the configure line to suit your build system here.
        # FIXME: Spack couldn't guess one, so here are some options:
        configure('--prefix=%s' % prefix)
        # cmake('.', *std_cmake_args)

        # FIXME: Add logic to build and install here
        make()
        make("install")
```

Suggestion: add this note to the manual.

**Comment by alalazo** [comment]
@citibeth What's the status of this?

**Comment by citibeth** [comment]
Looks like it still needs to make it into the manual.  I've been
considering (in my head) an "upstream authors guide" that will include tips
on how to build your upstream package to make life easier for Spack users.

**Comment by alalazo** [comment]
Looking again at this issue. It seems to me that here the `url` is used as in any other package. Also, the community seem to have developed other idioms around Github and Sourceforge. Closing this issue for now, but feel free to reopen if you disagree.
