### ISSUE TITLE
Put package name in package.py

### ISSUE THREAD

**Issue by citibeth** [spack/spack#464]
In the repository, change `<package-name>/package.py` to `<package-name>/<package-name>.py`

Why?  Because the current scheme, where everything is called "package.py" doesn't work with standard tools.  For example:
 ^x^b in Emacs shows a sea of package.py.  You can't change from one to the other easily with ^xb
 You can't search for package.py (in a meaningful way) in SpartGit.

I'm sure the list goes on...

**Comment by tgamblin** [comment]
I know @markcmiller86 agrees with this sentiment.  I'm kind of ambivalent.  I have a hard time putting this high up on the priority list, because there are a lot of other things to change, and this also requires changing the repo layout, which I see as a little gain for a lot of trouble.

Have you tried sticking this in your `.emacs`?

```elisp
; If two files have the same name, name by enclosing-folder/filename                                                    
(toggle-uniquify-buffer-names)
```

I use that successfully with `spack` and `MacPorts`, which has a similar layout (everything there is called `Portfile`).  It makes buffer switching easy.

**Comment by eschnett** [comment]
This doesn't require changing the repo layout. You can keep the directories. One fallback compatibility option would be to have a single `include` statement in a `package.py` that includes the real package file, which is in the same directory with a package-dependent name.

**Comment by markcmiller86** [comment]
I agree with Todd.

I think it might be useful to NOT have every package's package file be named 'package.py'.

But, I am certain there are plenty of higher priorities.

Mark

**Comment by tgamblin** [comment]
@eschnett: it does in the sense that `repository.py` expects a particular structure, which includes `package.py`.  But we could make it also look for `<name>.py`. 

Supposing we made it accept either.  Which should take precedence if both are present?

**Comment by citibeth** [comment]
> Have you tried sticking this in ~/.emacs?

Thank you, I will try that.  But it only fixes one broken tool.  SmartGit is a total disaster.  If I want to find a unique filename, I just type the filename and the file pops up.  If I need to find (say) netcdf/package.py, I'm left to manually scan through all the packages in alphabetical order, and pick the right one out with a mouse.  .5s vs. 20s.

> Supposing we made it accept either. Which should take precedence if both are present?

I think that should be an error.

**Comment by alalazo** [comment]
@citibeth Do you still want this to happen ?

**Comment by citibeth** [comment]
Emacs 25 has alleviated the issue.  But working with SmartGit is still a Royal PITA.  If you want to find a `package.py` file, there is no easy way to do it, other than clicking and scrolling through 1000+ packages.  Making the change would make it easier to work with the Spack repo, using more tools.

**Comment by alalazo** [comment]
Closing as very unlikely to happen. @tgamblin please reopen if you think differently
