### ISSUE TITLE
cling package

### ISSUE THREAD

**Issue by ax3l** [spack/spack#4668]
Hi spack-team,

I would like to add a [`cling` package](https://github.com/root-project/cling) (also building a jupyter kernel) for CERN's C++ interpreter.
It looks like cling is usually based on a slightly older version of `llvm` which [also needs certain patches applied](https://root.cern.ch/cling-build-instructions). Should we add a new package for it instead of adding it to `llvm`?

In this mode, it also creates a matching `clang` if we want to. How to handle that? (`provides`?)

Do we have some way to register/handle jupyter kernels already?

Last but not least: in principle, the already existing `root` package can also create a cling executable (source: [homepage](https://root.cern.ch/cling-build-instructions)). I never tried this. Anyway, in the projects I am interested in, I just want `cling` & `clang` (and a jupyter kernel) and not the whole `ROOT` ecosystem with all its dependencies.

**Comment by davydden** [comment]
> Should we add a new package for it instead of adding it to llvm?

i would add older version of `llvm` and needed patches and do `depends_on(llvm@o.l.d)` in `cling`.

**Comment by ax3l** [comment]
Not sure if that works, llvm has this "weird" plugin structure where you build llvm and its plugins (clang, cling, ...) in the same source tree... also, how to I call the `depends_on` "variant" of llvm which has the cling patches (the base llvm codebase itself is patched)?

It might be easier treating this like a hard fork of LLVM in a cling package, but I might be wrong.

**Comment by ax3l** [comment]
@karies can you tell me if you llvm patches for cling affect any of the other llvm tools (clang, lldb, polly, gold, ...)? Why aren't they ported mainline llvm and will they ever be?

I am referring to the first two lines of your [install instructions](https://cdn.rawgit.com/root-project/cling/master/www/build.html)
```bash
git clone http://root.cern.ch/git/llvm.git src
cd src
git checkout cling-patches
cd tools
git clone http://root.cern.ch/git/cling.git
git clone http://root.cern.ch/git/clang.git
cd clang
git checkout cling-patches
```

**Comment by Axel-Naumann** [comment]
We do have patches to clang that affect clang; no llvm patches should be needed after the next upgrade to llvm 5 (i.e. they've all been upstreamed).

**Comment by ax3l** [comment]
@Axel-Naumann that's fantastic news!
I would like to install cling (and it's jupyter notebook kernel) via the spack package manager and it might be possible to integrate it.
Can you please keep us posted when the clang patches are upstreamed, too? :)

**Comment by ax3l** [comment]
uh, @tgamblin just added [dependency patching](spack.readthedocs.io/en/latest/packaging_guide.html#dependency-dependency-patching). that might be useful here!

**Comment by ax3l** [comment]
planing update: add cling as tool without the jupyter kernel and add a kernel via [xeus-cling](https://github.com/QuantStack/xeus-cling) instead (separate package).

**Comment by alalazo** [comment]
@ax3l Were you aware of #1522?

**Comment by ax3l** [comment]
thx for the ping, now I am!

**Comment by ax3l** [comment]
@alalazo no progress so far. Also #1522 seems quiet.

Admittedly, I have a hard time finding the branching-points of the CERN repos to the mainline repos for llvm and clang to properly describe and patch them (e.g. clang-5.0-cern, llvm-5.0-cern).

**Comment by ax3l** [comment]
Hurray, @Axel-Naumann just extended the docs in https://root.cern.ch/cling-build-instructions for us and other packagers :rocket: :sparkles:

**Comment by ax3l** [comment]
We now have to discuss how we should express the currently monolithic llvm-builds and clang patches in spack.

First of all, there is no need to build clang directly in the `llvm` package of spack. clang can be build stand-alone without the "check out the llvm source dir and check out tools inside the llvm source dir". Many projects do this already and it will make the build easier and more modular then our current solution.

Then, for cling 0.5 and later, we need to apply a patch to the 5.0 release of clang. This clang patch is currently +611/-840 lines and can vary between cling releases. I would like to avoid adding the patches manually to spack in order to avoid cluttering the spack repo. Maybe we can express these as remote patch file or we just add a `5.0.0-cling` version to a stand-alone (see above) clang package with the cern branch instead of the mainline branch.

**Comment by ax3l** [comment]
@adamjstewart via slack:
> Spack now supports fetching patches via URL so you don't have to commit it.

**Comment by adamjstewart** [comment]
Is this issue still active or can we close it?
