### ISSUE TITLE
Support software package citation

### ISSUE THREAD

**Issue by markcmiller86** [spack/spack#4699]
I could see it being useful to have a way for packages to identify the correct way to cite the package in literature and to have Spack be able to produce a bibtex file for a given set of packages.

```
spack -cite foo
```

Would produce a bibtex file (or equiv.) for foo and all its dependencies.

This would probably require a new package directive such as

```
citing(author = 'Jean César', title = 'An amazing title', year = '2013',
    month = 'jan', volume = '12', pages = '12--23', journal = 'Nice Journal')
```

**Comment by davydden** [comment]
that would be nice and would support developers.

However, u would need to have a Bibtex entry for each version of a package (except for develop and alike).

I also disagree that dependencies should be included automatically: say if I build deal.ii with PETSc, i am not necessarily using it. All my calculations might be using Trilinos instead. Same on PETSc side: it might be build with superlu-dist, but I may not be using direct solvers

**Comment by davydden** [comment]
Not sure how umbrella packages like Trilinos suggest citations. Say, maybe u would be asked to cite extra when certain parts are used, i.e. MueLu preconditioner package.

**Comment by aprokop** [comment]
@davydden Yeah, Trilinos is a special snowflake, and one should really cite what is being used, though most people cite just a generic Trilinos paper.

**Comment by markcmiller86** [comment]
@davydden ...I think its better to present user with *all*possible* bits of software used and let the manually eliminate those they know they did NOT use than to fail to present what they may have used. 

PETSc is able to do this at turn time which is way cool because it means users get back information on the exact set of solvers, preconditioners, time integrators, etc, actually used in a PETSc calculation

Also, I think its rare that different versions need different citations. Most major packages have a seminal paper in their history package developers use and advocate for others to also cite.

**Comment by alalazo** [comment]
Closing as stale. For what is worth I think this would be a nice [custom extension](https://spack.readthedocs.io/en/latest/extensions.html), if anybody wants to code it :slightly_smiling_face:

**Comment by tgamblin** [comment]
I think we should reopen this if anyone wants to work on it.  I think having a subcommand for citing packages in your env or in some spec would be cool.

**Comment by camillescottatwork** [comment]
I think this could be a great feature for further reproducible science objectives. I'd suggest it would be a package directive looking something like:

```python
citable("https://doi.org/10.7554/eLife.42166.001", when="@3:4")
```

With a `spack cite` command taking either a spec, or producing the DOIs for the environment roots or all dependencies in an environment. There are existing programmatic tools for pulling full citation information from DOIs -- [manubot](https://github.com/manubot/manubot#cite) is one such example -- so just having the DOIs without worrying about specific formatting would already be a useful feature.
