### ISSUE TITLE
Spack consumes stdin

### ISSUE THREAD

**Issue by woodard** [spack/spack#4744]
Why does spack consume stdin?

I did something like:
cat list | while read pkg;do spack install $pkg;done

and the loop terminated after one iteration because spack consumed all of stdin. To fix the problem I had to do:

cat list | while read pkg;do spack install $pkg </dev/null;done

Can we fix this? It is counter intuitive for someone writing scripts.

**Comment by adamjstewart** [comment]
One reason we consume stdin is so that you can toggle `v` while an installation is running to toggle verbosity. I'm not sure whether or not there is an easy way to fix this.

When I script installations, I always write something like:
```bash
packages=(
    szip
    hdf
    hdf5
    netcdf
)

for package in ${packages[@]}
do
    spack install $package
done
```
Perhaps this is an option for you.

**Comment by woodard** [comment]
Yeah but this breaks standard Unix functionality in other ways as well:
Say for example, you have a much longer list of packages in the script function that you provide and you want to break out of the script with ctrl-c you practically can't do it because spack consumed the stdin. 
I would argue that your 'v' interactive capability is not well considered. Rather than assuming you are interactive provide a --v verbose mode.

**Comment by adamjstewart** [comment]
> you want to break out of the script with ctrl-c you practically can't do it because spack consumed the stdin.

I add the following to the script to get this to work:
```bash
trap 'exit' INT
```

> I would argue that your 'v' interactive capability is not well considered. Rather than assuming you are interactive provide a --v verbose mode.

There is a `-v/--verbose` flag, but if you forget it you can toggle it with <kbd>V</kbd>.
