### ISSUE TITLE
Class constructor failed for package 'builtin.jdk'

### ISSUE THREAD

**Issue by baberlevi** [spack/spack#4756]
I am having an issue that sounds very similar to #4622 while trying to do a module refresh

We had installed jdk 8u92 prior to PR #4317 when minor_versions was introduced.  Doing a module refresh would throw:

    ==> Error: Class constructor failed for package 'builtin.jdk'.
    
    Caused by:
    ValueError: substring not found
      File "/home/baber/spack/lib/spack/spack/repository.py", line 579, in get
        self._instances[key] = package_class(copy)
      File "/home/baber/spack/lib/spack/spack/package.py", line 560, in __init__
        f = fs.for_package_version(self, self.version)
      File "/home/baber/spack/lib/spack/spack/fetch_strategy.py", line 937, in for_package_version
        url = pkg.url_for_version(version)
      File "/home/baber/spack/var/spack/repos/builtin/packages/jdk/package.py", line 64, in url_for_version
        minor_version = version[:version.index('-')]

To remedy the issue, I had to checkout dc911661ca1ea15d0e4f39ed530900dd615f2178 (the commit prior to PR #4317) then uninstall jdk8u92 and dependent packages. Then I went back to develop and reinstalled them, which used the minor_version of JDK.  After this, I was able to refresh my module files.

It seems like a package change should not be backward incompatible and require uninstall/reinstall due to versioning differences.

**Comment by alalazo** [comment]
Closing for now. Please reopen if still an issue.
