### ISSUE TITLE
Error installing Octave

### ISSUE THREAD

**Issue by kdfred** [spack/spack#4784]
```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j36'
/dat/usr/e157618/spack/lib/spack/spack/build_systems/autotools.py:273, in build:
     268      def build(self, spec, prefix):
     269          """Makes the build targets specified by
     270          :py:attr:``~.AutotoolsPackage.build_targets``
     271          """
     272          with working_dir(self.build_directory):
  >> 273              inspect.getmodule(self).make(*self.build_targets)

See build log for details:
  /tmp/e157618/spack-stage/spack-stage-cLAi_9/octave-4.2.1/spack-build.out
```

[spack-build (2).txt](https://github.com/LLNL/spack/files/1151430/spack-build.2.txt)

**Comment by adamjstewart** [comment]
I would try contacting the developers. Perhaps your compiler is too old?

> error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.

Based on [this](https://gcc.gnu.org/projects/cxx-status.html) I would guess that if you use GCC 4.7 or newer, things will work. You should also be able to get away with GCC 4.3-4.6 if you manually add `-std=gnu++0x`.

**Comment by kdfred** [comment]
I tried using gcc-5.2.0 and got a different error

spack install octave %gcc@5.2.0
==> pcre is already installed in /dat/usr/e157618/spack/opt/spack/linux-rhel6-x86_64/gcc-5.2.0/pcre-8.40-2ld54ilc4z2ahg67orjn4zbdkdnujlup
==> readline is already installed in /dat/usr/e157618/spack/opt/spack/linux-rhel6-x86_64/gcc-5.2.0/readline-7.0-g6woxzo42ypkst33fzqmdwjnlzkhp3ev
==> openblas is already installed in /dat/usr/e157618/spack/opt/spack/linux-rhel6-x86_64/gcc-5.2.0/openblas-0.2.19-ost4xsqq37524n4bigrwit5vokqxxnsx
==> pkg-config is already installed in /dat/usr/e157618/spack/opt/spack/linux-rhel6-x86_64/gcc-5.2.0/pkg-config-0.29.2-33qrgyl2hps44arbqpuj2hruamlhisyg
==> Installing octave
==> Using cached archive: /dat/usr/e157618/spack/var/spack/cache/octave/octave-4.2.1.tar.gz
==> Already staged octave-4.2.1-d3sjvqauuxcrnwufxqhib55ibxjcu2d4 in /dat/usr/e157618/spack/var/spack/stage/octave-4.2.1-d3sjvqauuxcrnwufxqhib55ibxjcu2d4
==> Already patched octave
==> Building octave [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/dat/usr/e157618/spack/var/spack/stage/octave-4.2.1-d3sjvqauuxcrnwufxqhib55ibxjcu2d4/octave-4.2.1/configure' '--prefix=/dat/usr/e157618/spack/opt/spack/linux-rhel6-x86_64/gcc-5.2.0/octave-4.2.1-d3sjvqauuxcrnwufxqhib55ibxjcu2d4' '--with-blas=-L/dat/usr/e157618/spack/opt/spack/linux-rhel6-x86_64/gcc-5.2.0/openblas-0.2.19-ost4xsqq37524n4bigrwit5vokqxxnsx/lib -lopenblas' '--with-lapack=-L/dat/usr/e157618/spack/opt/spack/linux-rhel6-x86_64/gcc-5.2.0/openblas-0.2.19-ost4xsqq37524n4bigrwit5vokqxxnsx/lib -lopenblas' '--enable-readline' '--without-arpack' '--without-curl' '--without-fftw3' '--without-fftw3f' '--without-fltk' '--without-glpk' '--without-magick' '--without-hdf5' '--disable-java' '--without-opengl' '--without-framework-opengl' '--without-qhull' '--without-qrupdate' '--without-z'
/dat/usr/e157618/spack/lib/spack/spack/build_systems/autotools.py:266, in configure:
     258      def configure(self, spec, prefix):
     259          """Runs configure with the arguments specified in
     260          :py:meth:`~.AutotoolsPackage.configure_args`
     261          and an appropriately set prefix.
     262          """
     263          options = ['--prefix={0}'.format(prefix)] + self.configure_args()
     264  
     265          with working_dir(self.build_directory, create=True):
  >> 266              inspect.getmodule(self).configure(*options)

See build log for details:
  /tmp/e157618/spack-stage/spack-stage-KsWLOp/octave-4.2.1/spack-build.out
[spack-build3.txt](https://github.com/LLNL/spack/files/1166650/spack-build3.txt)

**Comment by adamjstewart** [comment]
Based on the installation prefix, it looks like you're still using GCC 4.4.7. Or did you upload the wrong `spack-build.out`?

**Comment by kdfred** [comment]
My mistake

[spack-build.out.txt](https://github.com/LLNL/spack/files/1166970/spack-build.out.txt)

**Comment by adamjstewart** [comment]
Hmm, it quits with no error message? Can you upload the `config.log`? It should be in the same directory as the `spack-build.out`.

**Comment by kdfred** [comment]
[config.log.txt](https://github.com/LLNL/spack/files/1167661/config.log.txt)

**Comment by adamjstewart** [comment]
Here are the important error messages I'm seeing:
```
./conftest: error while loading shared libraries: libquadmath.so.0: cannot open shared object file: No such file or directory
...
configure:29324: error: your Fortran compiler must have an option to make integers the same size as octave_idx_type (int).  See the file INSTALL for more information.
```
Can you post your `~/.spack/*/compilers.yaml`?

**Comment by kdfred** [comment]
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.4.7
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: /usr/bin/gcc34
      cxx: /usr/bin/g++34
      f77: null
      fc: null
    spec: gcc@3.4.6
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: /sw/intel-ps/intel-ps-2016u3/compilers_and_libraries_2016.3.210/linux/bin/intel64/icc
      cxx: /sw/intel-ps/intel-ps-2016u3/compilers_and_libraries_2016.3.210/linux/bin/intel64/icpc
      f77: /sw/intel-ps/intel-ps-2016u3/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
      fc: /sw/intel-ps/intel-ps-2016u3/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
    spec: intel@16.0.3
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: /sw/gcc/gcc-5.2.0/bin/gcc
      cxx: /sw/gcc/gcc-5.2.0/bin/g++
      f77: /sw/gcc/gcc-5.2.0/bin/gfortran
      fc: /sw/gcc/gcc-5.2.0/bin/gfortran
    spec: gcc@5.2.0
    target: x86_64

**Comment by adamjstewart** [comment]
Okay, I'm out of ideas. Have the Octave developers gotten back to you yet? They would know a lot more than me. I don't think this is a Spack bug from what I've seen so far, but I could be wrong.

**Comment by alalazo** [comment]
Just installed octave with 951679376e1ffbfaf626625158ea9fafecec36d8 on:
```console
$ uname -a
Linux fidis 3.10.0-514.26.2.el7.x86_64 #1 SMP Fri Jun 30 05:26:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ spack find octave
==> 1 installed packages.
-- linux-rhel7-x86_64 / gcc@4.8.5 -------------------------------
octave@4.2.1
```
