### ISSUE TITLE
Help with r-ada `depends_on(r_rpart)` but rpart seems to be in the R core.

### ISSUE THREAD

**Issue by hartzell** [spack/spack#4795]
I recently added a package for *ada* that `depends_on(r-rpart)`.  I just tried to activate it and it failed.  If I understand what's happening, `rpart` is part of the R core and I should not have added a dependency for it in the package.

Is that correct?  If so I'll update the package.

**Comment by adamjstewart** [comment]
See #4516, #3031, #2951, etc.

My understanding is that some packages are built into R and cannot be updated, some (like `r-rpart`) usually come with an R installation but can be updated or not installed, and some can be installed but don't come by default. #4516 will prevent the second group of packages from being installed, thus allowing activation.

**Comment by hartzell** [comment]
@adamjstewart -- It seems like what I should do is remove the `depends_on('r-rpart')` so that it works with the current state of the world, and then ask @tmerrick1 to add the dependency in his pull request so that things continue to work in the post-merge-of-4516 world.

Does that seem right?

**Comment by adamjstewart** [comment]
Well, `spack activate` doesn't work for most R packages currently, so I would be in favor of preparing for the eventual merger of #4516 and keeping the dependency there. The last time I talked to @tmerrick1 it sounded like he was close to being done, aside from me breaking `list_url` for half of the R packages.

**Comment by hartzell** [comment]
@tmerrick1 -- Do you think you're a day, week, or month away from the merge (no rush on my part, just deciding whether to hold my breath or not).

**Comment by tmerrick1** [comment]
So how do I fix this:?

[tmerrick@hpcm packages]$ git checkout develop
error: You have local changes to 'var/spack/repos/builtin/packages/r-spatial/package.py'; cannot switch branches.

I was trying to update the develop on my site before uploading all of the pieces for a pull.

**Comment by adamjstewart** [comment]
> I was trying to update the develop on my site before uploading all of the pieces for a pull.

You can use:
```
$ git stash
$ git checkout develop
$ git pull upstream develop
$ git checkout r3031fix
$ git rebase develop
$ git stash pop
```
to update develop _before_ uploading, or use:
```
$ git commit
$ git checkout develop
$ git pull upstream develop
$ git checkout r3031fix
$ git rebase develop
```
to update develop _after_ uploading.

**Comment by tmerrick1** [comment]
I tried the first one and got the following error when trying to upload the changes:

[tmerrick@hpcm packages]$ git push origin r3031fix -u
To git@github.com:tmerrick1/spack.git
! [rejected]        r3031fix -> r3031fix (non-fast-forward)
error: failed to push some refs to 'git@github.com:tmerrick1/spack.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes before pushing again.  See the 'Note about
fast-forwards' section of 'git push --help' for details.

**Comment by adamjstewart** [comment]
Yes, since you are overwriting the history of your origin, you need to use `git push --force`.

**Comment by hartzell** [comment]
I once went to a three hour presentation titled "Git is easy"....  :scream_cat:

**Comment by adamjstewart** [comment]
This issue was fixed by adding `--without-recommended-packages` in #12015 and by explicitly listing recommend packages as dependencies in #12019 and #12005.
