### ISSUE TITLE
MVV: Need to make sure default is part of values

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#4837]
If you edit a package like `zlib` to add a fake mulit-valued variant:
```python
variant('foo', default='bar', values=('a', 'b', 'c'))
```
there is no logic in place to make sure that `default` is a member of `values`. Spack installs `zlib foo=bar` just fine. @alalazo Is this expected or is it a bug?

**Comment by mamelara** [comment]
Question about multi-valued variants. Does default take multiple values? Example:

```python
variant("libs", default="shared,static", values=("shared", "static")) 
```

Wasn't sure what are valid entries since documentation is missing.

**Comment by alalazo** [comment]
@mamelara Just posting our private conversation on slack for others to see. The following:
```python
variant("libs", default="shared,static", values=("shared","static"), multi=True)
```
is completely fine, and if done on package `foo` then the three commands:
```console
$ spack spec -l foo
...
$ spack spec -l foo libs=shared,static
...
$ spack spec -l foo libs=static,shared
...
```
**must** return the same hash.
