### ISSUE TITLE
Octave installation links to Spack compiler wrapper which is unusable outside of Spack.

### ISSUE THREAD

**Issue by paulhopkins** [spack/spack#4874]
Spack uses a wrapper script to easily switch between different compilers and to add specific flags for runtime library linking. Some applications, like Octave and Python, will record the compiler path and will use it to install sub-modules. If these compiler wrappers are used outside of Spack they will fail because they do not know how to link back to the original compiler. 

When Spack installs Python it runs a post install script on the config and Makefiles to replace any mention of the wrapper with the original compiler. However, with Octave the reference to the compiler is stored within the `mkoctfile` binary and the `liboctinterp.so` library. For example:

```
$ mkoctfile -p CXX
/home/paul/Projects/spack/lib/spack/env/gcc/g++
$ strings mkoctfile | grep g++
/home/paul/Projects/spack/lib/spack/env/gcc/g++
```

To workaround this I edited the binary file to replace the path to the wrapper with the real compiler path. I don't this should be recommend as an Octave post install step.

**Comment by tgamblin** [comment]
#4470 is about to go in -- will this help in the case of Octave?

**Comment by adamjstewart** [comment]
#4470 doesn't make any changes to the Octave package. It makes it easier to filter compiler wrappers out of text files, but that isn't the case here.

**Comment by alalazo** [comment]
> #4470 is about to go in

:sob:

**Comment by adamjstewart** [comment]
Cross-referencing a possible solution to this issue: https://github.com/spack/spack/issues/14702#issuecomment-580967373
