### ISSUE TITLE
spack setup installs package that is being setup

### ISSUE THREAD

**Issue by bvanessen** [spack/spack#4920]
When I run spack setup to create a local spack environment for building a project it will install an empty instance of the package at the end of the installation process.

**Comment by adamjstewart** [comment]
@citibeth?

**Comment by citibeth** [comment]
We need to get the setup pr merged.  Setup has fallen to bitrot.

On Jul 28, 2017 4:05 PM, "Adam J. Stewart" <notifications@github.com> wrote:
> <https://github.com/citibeth>
> @citibeth <https://github.com/citibeth>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/LLNL/spack/issues/4920#issuecomment-318749379>, or mute
the thread

**Comment by bvanessen** [comment]
Talked with @becker33 about this as well.

**Comment by becker33** [comment]
@citibeth which setup PR are you referring to?

**Comment by pramodskumbhar** [comment]
@becker33 : latest updated one is #5043
