### ISSUE TITLE
Enforcing shared variants

### ISSUE THREAD

**Issue by mamelara** [spack/spack#4921]
I'd like for package developers to start taking into consideration shared variants. With 1600+ packages, going through them and providing shared variants is going to take a long time. Maybe add a note if their package doesn't support static libs or something is fine, but I'd like to see less 
"--enable-shared" in configure lines.

**Comment by citibeth** [comment]
What is a shared variant?  Can you be more specific, please?

**Comment by alalazo** [comment]
Closing in favor of #5269
