### ISSUE TITLE
Module support for OpenFOAM is very poor

### ISSUE THREAD

**Issue by olesenm** [spack/spack#4942]
This is a placeholder issue to document the current status, but does not immediately result in a solution.

Creating a module for OpenFOAM within spack is at the moment a bit difficult.
Populating the `setup_environment` manually with environment variables is cumbersome, error-prone and *very* large. Using the `EnvironmentModifications.from_sourcing_files` seems to partly work, but can have issues if with the python versions or other things. Most of the module content seems to be generated before the software comes into its final installation directory, which makes other scripting solutions a bit of a problem too.

We currently have a [script to created a module include](https://develop.openfoam.com/Community/feature-scripts) from the OpenFOAM environment, but this is only a manual workaround.

**Comment by adamjstewart** [comment]
Check out what I'm doing for Intel: https://github.com/LLNL/spack/pull/4300/files#diff-57e7677cdc964b3262ddd8f8634a7602R446

This should work for you as well.

**Comment by olesenm** [comment]
I've been lurking on your intel thread, but waiting for the dust to settle a bit. With your changes to `from_sourcing_files`, is there a way (easy or otherwise) to manipulate the changes or the raw JSON prior to emitting? For the OpenFOAM modules, we would actually need the `FOAM_USER_APPBIN` etc to have variable contents and then also propagate that into a few other places.

For example,

    setenv FOAM_USER_APPBIN "$env(HOME)/OpenFOAM/$env(USER)-plus/platforms/linux64GccDPInt32Opt/bin"
    prepend-path PATH "$FOAM_USER_APPBIN"

.. but not entirely sure of the syntax.
Ideally, the `WM_PROJECT_DIR` would be set near the top and used to populate most of the balance of the modules env.

**Comment by adamjstewart** [comment]
Are you saying you want to change/add environment variables after sourcing the file? That's really easy to do.

**Comment by alalazo** [comment]
@olesenm Closing this. To check how to modify module content from `modules.yaml` refer to [this](https://spack.readthedocs.io/en/latest/tutorial_modules.html#add-custom-environment-modifications). If you still have issues feel free to reopen.

**Comment by olesenm** [comment]
Thanks Massimiliano - I still may need to revisit this, but I have partial workaround based loosely on a script that Ivan S. gave me, apparently originally yours from years back.

**Comment by alalazo** [comment]
@olesenm Time passes fast! I almost forgot one of my first tasks at CINECA was to compile OpenFOAM on literally every machine available. :smile:
