### ISSUE TITLE
Questions about the singularity package.

### ISSUE THREAD

**Issue by hartzell** [spack/spack#4946]
Two questions about the singularity package:

1. We're currently using the dynamically generated tarball built from a particular commit/tag on the source tree (aka [this "archive" link](https://github.com/singularityware/singularity/archive/2.3.1.tar.gz)).  This is the raw source and requires that the install run the maintainer level autotools bits (and adds prereqs to the package and etc...).

    The author's *also* upload a release tarball that contains the result of them running the maintainer steps of the autotools dance, e.g. [this "KB singularity-2.3.1.tar.gz" link](https://github.com/singularityware/singularity/releases/download/2.3.1/singularity-2.3.1.tar.gz).

    This tarball just requires running `./configure`, without the additional dependencies.

    **BUT**, this is a different tarball the diffs change.

    Diffs look like this:

    ```diff
    diff --git a/var/spack/repos/builtin/packages/singularity/package.py b/var/spack/repos/builtin/packages/singularity/package.py
    index 61acf5646..2cec1fa6e 100644
    --- a/var/spack/repos/builtin/packages/singularity/package.py
    +++ b/var/spack/repos/builtin/packages/singularity/package.py
    @@ -30,11 +30,6 @@ class Singularity(AutotoolsPackage):
            Compute'"""

         homepage = "http://singularity.lbl.gov/"
    -    url      = "https://github.com/singularityware/singularity/archive/2.3.1.tar.gz"
    +    url      = "https://github.com/singularityware/singularity/releases/download/2.3.1/singularity-2.3.1.tar.gz"

    -    version('2.3.1', '292ff7fe3db09c854b8accf42f763f62')
    -
    -    depends_on('m4',       type='build')
    -    depends_on('autoconf', type='build')
    -    depends_on('automake', type='build')
    -    depends_on('libtool',  type='build')
    +    version('2.3.1', 'd2ae1930024cfadcd472e6b7cc9e01ca')
    ```

2. We're not doing anything about making the executables setuid.  Are people installing this as root, or???  Does Spack have any hooks for supporting setuid/root-installed stuff?

**Comment by hartzell** [comment]
@akthoma -- Was excited when I saw you add this.  A couple of questions....  Thanks!

**Comment by adamjstewart** [comment]
1. This change looks good to me. Fewer dependencies is always better.

2. Does Autotools not handle that?

**Comment by adamjstewart** [comment]
Based on the current `singularity` package, it looks like both 1 and 2 have been resolved.
