### ISSUE TITLE
Unable to build qt on CentOS 7 with GCC 7.1.0

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#4961]
This one actually produced a useful error message:
```
WARNING: Could not find XKB config root, use -xkb-config-root to set a path to
XKB configuration data. This is required for keyboard input support.

ERROR: Feature 'opengl' was enabled, but the pre-condition 'features.opengl-desktop || features.opengl-dynamic || features.opengles2' failed.

ERROR: The OpenGL functionality tests failed!
```
Full [spack-build.out](https://github.com/LLNL/spack/files/1195614/spack-build.txt)

**Comment by adamjstewart** [comment]
`qt~opengl` successfully builds though! We're definitely missing a dependency for `+opengl`.

**Comment by adamjstewart** [comment]
Our `qt` build is missing more than half of its dependencies. Run:
```
$ ./configure -list-libraries
```
to see a full list of the dependencies `qt` looks for.

**Comment by adamjstewart** [comment]
I really, really don't want to go down the rabbit hole of making `qt` more robust and including all of its dependencies with variants to enable them, and then get that working for every version of `qt` we support, where the available option flags keep changing. But if someone wants to pay me to do it, we can talk.

**Comment by mjwoods** [comment]
Hi @adamjstewart , I built `qt@5.9.1` with the develop branch (at commit 761b8f76) on RHEL7 with `%gcc@7.2.0`. It worked with both `+opengl` and `~opengl`.
