### ISSUE TITLE
qt 5.3.2 failing to build with "fatal error: xcb/xcb_icccm.h: No such file or directory"

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#4966]
As mentioned in #4925 Qt 5.3.2 is failing to build for me:

```
c++ -Wl,-O1 -o xcb-xkb xcb-xkb.o   -L/nfs/tmp2/lee218/delete/spack.pr4925/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/libxcb-1.12-z4uud6ikrikj3al7dldclp2y4okz2nmi/lib -lxcb -lxcb-xkb 
xcb-xkb enabled.
xcb-syslibs auto-detection... ()
c++ -c -pipe -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -I/nfs/tmp2/lee218/delete/spack.pr4925/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/freetype-2.7.1-2zgafqed2nmxxdyxgt7wrr7mgpfkzgle/include/freetype2 -o xcb.o xcb.cpp
xcb.cpp:46:27: fatal error: xcb/xcb_icccm.h: No such file or directory
 #include <xcb/xcb_icccm.h>
```

This header appears to be in ./qtbase/src/3rdparty/xcb/include/xcb/xcb_icccm.h. I don't see it in the spack-built libxcb.

**Comment by adamjstewart** [comment]
@lee218llnl is this still an issue?

@sethrj can you take a look at this?

**Comment by sethrj** [comment]
The spack recipe has totally changed since the time this was posted, and the issue clearly predates the template that asks for spack version, package spec, platform, etc. I'm going to close this, but I'll take a look if someone reopens (and posts the necessary details).
