### ISSUE TITLE
Questions on BLAS and LAPACK

### ISSUE THREAD

**Issue by skosukhin** [spack/spack#5018]
I would like to ask several questions about 'blas' and 'lapack' virtual dependencies.

Let's start with the [documentation](http://spack.readthedocs.io/en/latest/packaging_guide.html?highlight=virtual#blas-and-lapack-libraries). It tells us that we should use blas_libs and lapack_libs properties to avoid hard-coding. 'mkl-intel' has those properties but 'openblas' doesn't (anymore). Does it mean that we still have to do hard-coding to find out whether we should get libraries from spec['blas'].libs or speck['blas'].blas_libs? Or should we just wrap openblas's libs property with blas_libs?

My second question is about C interfaces of the libraries: cblas, clapack, and lapacke (are there more)? How can I tell spack that my package needs not just 'lapack' but 'lapacke' or 'clapack'? And how do I get a list of additional libraries that enable the interface (if by any chance they are required)?

Thank you.

**Comment by davydden** [comment]
documentaiton is outdated, you should use `bl = spec[blas].libs`, `lp = spec[lapack].libs` and `sca = spec[scalapack].libs` to get LIbraryList for each one and then group them the way the package requires.
You may do `libs = sca + lp + bl` and  call `libs.ld_flags`. 

For example, `mumps` does

```
lapack_blas = (self.spec['lapack'].libs +
                       self.spec['blas'].libs)
        makefile_conf = ["LIBBLAS = %s" % lapack_blas.ld_flags]
```

and

```
            scalapack = self.spec['scalapack'].libs
            makefile_conf.extend(
                ['CC = {0}'.format(self.spec['mpi'].mpicc),
                 'FC = {0}'.format(self.spec['mpi'].mpifc),
                 "SCALAP = %s" % scalapack.ld_flags,
                 "MUMPS_TYPE = par"])
```


> C interfaces of the libraries: cblas, clapack, and lapacke

that's trickier. AFAIK Spack does not yet have special ways of treating this.

**Comment by davydden** [comment]
p.s. 

> Let's start with the documentation

feel free to submit a PR to improve it.

**Comment by davydden** [comment]
p.p.s. and yes, i think documentation should really be updated. Other contributors have the same questions, i.e. @EmreAtes https://github.com/LLNL/spack/pull/4711

**Comment by skosukhin** [comment]
@davydden thank you, but could you take a look at 'mkl-intel'. It looks like its blas_libs property does some magic to generate the list. Do you think it would be enough just to call self.spec['lapack'].libs if the provider is mkl-intel?

**Comment by alalazo** [comment]
@skosukhin Documentation is quite outdated on this topic. I need to clean-up #3377 which contains some of the information you are seeking. 

In a nutshell you shouldn't use `blas_libs` or `lapack_libs` anymore, just `libs`. This uses a chain of responsibility to look for:

1. `{virtual_name}_libs` if the name you used is that of a virtual spec
2. `libs` in the package
3. uses a default handler if nothing is found

`openblas` got its method deleted because the default handler is treating this package correctly. See `ForwardQueryToPackage` and `SpecBuildInterface` in `lib/spack/spec.py` if you are interested in the implementation details.

---

> My second question is about C interfaces of the libraries: cblas, clapack, and lapacke (are there more)?

When I implemented these build interfaces I extended the syntax you can use in subscripting a spec to support finer querying. `hdf5` could be a good example: if you `spec['hdf5:hl,cxx'].libs` you'll get the libraries to link against the highlevel c++ API. You can look into the `libs` property to see an example of implementation. Hope this may help.

**Comment by davydden** [comment]
> Do you think it would be enough just to call self.spec['lapack'].libs if the provider is mkl-intel?

i don't just think, I am absolutely certain it is :smile: Seriously, i test from time to time `dealii ^intel-mkl` which builds `petsc`,`trilinos`, `mumps` and the whole lot more. That's the whole point about the structure -- each provider is responsible to have a decent implementation. By default `libs` of package `foo` will look for `libfoo.so` in `prefix/lib`. So it works **for all** packages.

**Comment by davydden** [comment]
> hdf5 could be a good example: if you spec['hdf5:hl,cxx'].libs 

good piont @alalazo . So to cover `lapacke` interface, one needs to extend current code in blas/lapack providers to know about it and behave differently.

**Comment by skosukhin** [comment]
@davydden so we can just delete all blas_libs and lapack_libs properties from all the providers and don't lose anything? I am really confused.

**Comment by alalazo** [comment]
> @davydden so we can just delete all blas_libs and lapack_libs properties from all the providers and don't lose anything? I am really confused.

No. These are callbacks that are invoked when you refer to that package through a 'virtual name'. Example. Let's say your package `foo` depends on `intel-parallel-studio` that provides `mpi`, `lapack` and other virtual interfaces for a particular concretization. At some point in your package you'll ask:
```
l = spec['mpi'].libs
```
What happens is that:
- `spec['mpi']` returns you the current provider (`intel-parallel-studio`) and records the fact that *you asked for mpi*
- if in `intel-parallel-studio` you have a method `mpi_libs` that will be used to compute a return value for the query above

From the point of view of `foo` this happened transparently.

**Comment by davydden** [comment]
> No

:+1:

My comments above were about how to use the interface in other packages.

**Comment by davydden** [comment]
> From the point of view of foo this happened transparently.

If that would not be the case, we would eventually end up with a whole lot of code dupcilarion where each and every 'foo' needs to have a correct if/else logic based on the chosen provider. I find this a very big advantage of Spack compared to other package managers, i.e. Homebrew, to which i contributed in the past.

**Comment by skosukhin** [comment]
@alalazo, now I get it. Thanks! It's very cool actually.
@davydden sounds like contributing to Homebrew was a bad habit you have managed to get rid of =)

**Comment by davydden** [comment]
> @davydden sounds like contributing to Homebrew was a bad habit you have managed to get rid of =)

haha, yes

**Comment by skosukhin** [comment]
And what do you think about introducing virtual dependencies for cblas, clapack, and lapacke while keeping blas and lapack to represent fortran interface? A bit ugly, maybe, but I don't know another way to express that a package needs C interface of LAPACK, for example.

**Comment by davydden** [comment]
> virtual dependencies for cblas, clapack, and lapacke

i would not as this complicates things quite a lot.

> but I don't know another way to express that a package needs C interface of LAPACK, for example.

I would just follow this `spec['hdf5:hl,cxx'].libs` --> `spec['blas:c'].libs` to get correct libs. Lapack/Blas providers should then fill it appropriately or throw an error if the don't have it.

**Comment by skosukhin** [comment]
@davydden yes, it's a nice thing to get necessary libraries but the problem is in concretization. How let Spack know that we need a provider of 'blas' that also provides C interface?

**Comment by davydden** [comment]
> How let Spack know that we need a provider of 'blas' that also provides C interface?

I agree, it will allow a package to conretize but will fail during the build time. But the question is -- do we really need this? I though `openblas`, `mkl` and `atlas` have C interface.

**Comment by davydden** [comment]
> the problem is in concretization

btw, this can be fixed when https://github.com/LLNL/spack/issues/1712 is fixed. Namely, you can introduce a `variant(c_interface=True)` and then require providers to be built with them. If the can not, then one can add (pseudo) `conflict(+c_interface, when=always)`.

**Comment by alalazo** [comment]
@skosukhin Is [this](https://spack.readthedocs.io/en/latest/tutorial_advanced_packaging.html#spec-s-build-interface) good enough to close the issue?

**Comment by skosukhin** [comment]
@alalazo, sure, thank you
