### ISSUE TITLE
PAPI build failure when no fortran compiler present

### ISSUE THREAD

**Issue by sknigh** [spack/spack#5029]
PAPI's build will (cryptically) fail if a fortran compiler is not installed. Is there a good way to have the package check for a fortran compiler and create a more readable error?

**Comment by adamjstewart** [comment]
You can check to see if `self.compiler.f77` and `self.compiler.fc` are set. See `hdf5` for an example.

**Comment by alalazo** [comment]
@sknigh Care to submit a PR?
