### ISSUE TITLE
Document how to add conditional dependencies

### ISSUE THREAD

**Issue by citibeth** [spack/spack#510]
@mathstuf :
On Tue, Mar 08, 2016 at 14:27:50 -0500, Elizabeth Fischer wrote:

> Not sure if Spack can do this, I didn't find anything in the docs that says
> it can...
> 
> Suppose I have library B, which depends on A.  Different versions of B
> require specific versions of A.  For example:
> 
> ```
> B@1.0 requires A@1.1:1.3
> B@2.0 requires A@1.5:
> ```
> 
> How would I write a package.py file encoding this version-dependent
> dependency information?  The normal way these things are written, the
> depends_on() statement  is written before the B's version number is known.

Would:

```
depends_on('A@1.1:1.3', when='@1.0')
depends_on('A@1.5:', when='@2.0')
```

not work?

**Comment by citibeth** [comment]
@tgamblin:

> This (unfortunately) is not in the current documentation (but needs to
> be).  The most detailed description is here:
> 
>         https://github.com/LLNL/spack/wiki/Telcon%3A-2015-05-14
> 
> Ben's solution seems reasonable, although I might modify it to cover the
> space in between the versions too:
> 
>         depends_on('A@1.1:1.3', when='@:1.9')
>         depends_on('A@1.5:', when='@2.0:')
> 
> 
> This (unfortunately) is not in the current documentation (but needs to
> be).  The most detailed description is here:

https://github.com/LLNL/spack/wiki/Telcon%3A-2015-05-14
> 
> Ben's solution seems reasonable, although I might modify it to cover the
> space in between the versions too:
> 
>         depends_on('A@1.1:1.3', when='@:1.9')
>         depends_on('A@1.5:', when='@2.0:')
> 
>

**Comment by alalazo** [comment]
This I think is still relevant. Despite we have a lot of packages using conditional dependencies, I can't find any doc (not even in the `version` API`) with a simple example of use.
