### ISSUE TITLE
Recommended way to invoke/use spack within larger "scripts"

### ISSUE THREAD

**Issue by markcmiller86** [spack/spack#5100]
I am writing some tools that use spack to test/probe packages a slew of different ways (with various compilers, with various optimizations, with various warning flags, shared/static, compiling C code with c++ compiler, use clang static analyzer (or some other static analyzer), etc. 

Some of the aforementioned activites are just variations on invokation of `spack install <whatever>`. Others are more involved. Lets focus on the simple ones for now.

Suppose I wanna probe a package's behavior with -Wall and then, separately, -Werror. From -Wall build, I wann count and collect the warnings. From -Werror, I wanna just test if the compile succeeded or not.

What is the best way to effectively script this kind of thing up? I am thinking I would like to code everything in python and then maybe just use spack as a `module` that my python script loads and uses. However, I am not sure of that nor aware of any examples of using spack that way. Alternatively, and somewhat more conceptually simple for me, I can write shell script(s) that do this kind of thing.

I am just wondering if there is a preferred/recommended way of doing this kind of thing?

**Comment by markcmiller86** [comment]
So, I am guessing that part of the answer here, especially if using python, is to import the spack `main` module and then do things from within it as is described somewhat here...

https://spack.readthedocs.io/en/latest/spack.html#module-spack.main

**Comment by pramodskumbhar** [comment]
@markcmiller86 : not exactly what you asked but to test build with different compilers and mpi implementations, we have jenkins build that run script like below : 

```
...
# the list of packages that we want to install
dev_packages=(
    'neuronperfmodels@develop'
    'coreneuron@perfmodels ~mpi'
    'coreneuron@perfmodels +mpi
   ...
)
...
# each platform has different compilers
if [ $platform == "x86" ]
then
    # compilers on the cluster
    compilers=(
      "pgi"
      "gcc"
      "intel"
    )

    # mpi packages associated with compilers
    declare -A mpi
    mpi["pgi"]="mpich"
    mpi["gcc"]="mvapich2"
    mpi["intel"]="intelmpi"
else
    # compilers on the bg-q
    compilers=(
      "xl"
    )

    declare -A mpi
    mpi["xl"]="mpich"
fi


# for every compiler in the platform
for compiler in "${compilers[@]}"
do

    # build each package
    for package in "${dev_packages[@]}"
    do
        # spec is show just for information purpose
        spack spec $package %$compiler ^${mpi[$compiler]}

        # install package
        spack install $extra_opt $package %$compiler ^${mpi[$compiler]}

        # just to check if package installed properly
        if [[ `spack find $package %$compiler ^${mpi[$compiler]}` == *"No package matches"* ]];then
            echo "Package Installation Check Failed For $package %$compiler !"
            exit 1
        fi

        # module purge and then do spack load ....
        # run tests here
        ....
    done

done
....
```
Similarly you can add compiler specific flags on command line.

**Comment by tgamblin** [comment]
@markcmiller86: There are several ways to do this.

1. Spack ships with a `spack-python` interpreter that already has all the spack stuff added to your `PYTHONPATH`.  In addition to @pramodk's shell scripting suggestions, you can make a script that starts with:

    ```python
    #!/usr/bin/env spack-python
    import spack
    # etc.
    ```

    and write your code there.  You can either code to the internal APIs in Spack (which I like better), e.g.:

    ```python
    #!/usr/bin/env spack-python
    import spack
    pkg = spack.repo.get('some-package')
    pkg.do_install(verbose=True)
    ```

    Or you can as of fairly recently invoke commands from within Python as you would on the command line.  e.g.:

    ```python
    from spack.main import SpackCommand
    install = SpackCommand('install')
    install('--keep-stage', 'some-package')
    ```

2. You can just add a new command in `lib/spack/spack/cmd`.  Look at the existing commands for how to set that up or see [writing commands](https://spack.readthedocs.io/en/latest/developer_guide.html#writing-commands) (might be somewhat outdated).

**Comment by markcmiller86** [comment]
@tgamblin I would prefer approach 2, adding a new command. I'd like this to be part of Spack proper. That said, this is the Idea Days project stuff I mentioned a long while back (just getting to actually doing the work now). So, the question is...if I get into decent shape, is it something that might be able to get merged into develop? It would certainly still be classified as an _experimental_ capability at that time?

**Comment by tgamblin** [comment]
Onviously depends on how invasive it is and how well we can maintain it but I don't see a reason why it couldn't eventually.

**Comment by markcmiller86** [comment]
@tgamblin, FYI...

```
#!/usr/bin/env spack-python
import spack
pkg = spack.repo.get('zlib')
pkg.do_install(verbose=True)
```

Running....

```
[scratlantis:~/spack/spack] miller86% ./fitck.py
Package
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/zlib
Traceback (most recent call last):
  File "./fitck.py", line 10, in <module>
    pkg.do_install(verbose=True)
  File "/Users/miller86/spack/spack/lib/spack/spack/package.py", line 1199, in do_install
    % self.spec.name)
ValueError: Can only install concrete packages: zlib.
```

To fix, need to call `repo.git()` using a spec...

```
#!/usr/bin/env spack-python
import spack
specs = spack.cmd.parse_specs('zlib', concretize=True)
assert(len(specs)==1)
pkg = spack.repo.get(specs[0])
pkg.do_install(verbose=True)
```

**Comment by tgamblin** [comment]
or:

```python
from spack.spec import Spec
zlib = Spec('zlib').concretized()
zlib.package.do_install()
```

**Comment by markcmiller86** [comment]
Ok, I've searched around the docs and can't figure out how to do something...from within my python code, I want to set the path spack uses as the installation point for packages. I see things like `prefix`, `spack_root` and `module_path` in the spack module. I see documentation for the config.yaml file that indicates `install_tree` is the yaml config tag for where it will install and that the default is `$spack/opt/spack`. But, I don't see how to control it via python.

**Comment by tgamblin** [comment]
Look at `spack.store`, which implements the install tree and associated package database.

I suspect the [`install_mockery`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/test/conftest.py#L277) fixture might help you, too.  It sets up and tears down a mock install tree and mock DB for tests that use it.  Fixtures are a `pytest` thing.  [See here](https://docs.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code) for how to read that code.

You could pretty easily make that into a [context manager](https://jeffknupp.com/blog/2016/03/07/python-with-context-managers/) if you want to use it in your own code to set up/tear down a temporary install sandbox.

**Comment by markcmiller86** [comment]
So, [install_mockery](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/test/conftest.py#L277) is somewhat useful. Thanks for sharing. It changes the `db` and `layout` of the _install store_ (I guess thats the correct name). However, it does not change the `root`. And, when I tried same, except also changing the `root` but not the `layout`...

```
idir = '/Users/miller86/spack/spack/opt/foobar'
spack.store.root = idir
spack.store.db = spack.database.Database(idir)

specs = spack.cmd.parse_specs('zlib@1.2.8', concretize=True)
assert(len(specs)==1)
pkg = spack.repo.get(specs[0])
print pkg.build_system_class
print pkg.package_dir
pkg.do_install(verbose=True)
```

What I wound up with is that the `/Users/miller86/spack/spack/opt/foobar` db does indeed get created but zlib still wound up getting installed to `/Users/miller86/spack/spack/opt/spack`

**Comment by markcmiller86** [comment]
Ok, looks like `layout` is needed whereas I had expected just changing what it thinks `root` is would be sufficient to have desired effect. So, now, I am able to install to a wholly different dir tree. Thats great!

It did wind up, however, using the same module files...

```
chmod 644 /Users/miller86/spack/spack/opt/foobar/darwin-elcapitan-x86_64/clang-7.3.0-apple/zlib-1.2.8-qxty6kzmw4dym7s3hhzrtgqcwdpxyfuc/include/zlib.h /Users/miller86/spack/spack/opt/foobar/darwin-elcapitan-x86_64/clang-7.3.0-apple/zlib-1.2.8-qxty6kzmw4dym7s3hhzrtgqcwdpxyfuc/include/zconf.h
==> Warning: Module file already exists : skipping creation
file : /Users/miller86/spack/spack/share/spack/modules/darwin-elcapitan-x86_64/zlib-1.2.8-clang-7.3.0-apple-qxty6kz
spec : zlib@1.2.8%clang@7.3.0-apple+pic+shared arch=darwin-elcapitan-x86_64
==> Warning: Module file already exists : skipping creation
file : /Users/miller86/spack/spack/share/spack/dotkit/darwin-elcapitan-x86_64/zlib-1.2.8-clang-7.3.0-apple-qxty6kz.dk
spec : zlib@1.2.8%clang@7.3.0-apple+pic+shared arch=darwin-elcapitan-x86_64
==> Successfully installed zlib
```

So, do I also need to manipulate `spack.modules`?

**Comment by tgamblin** [comment]
The modules go under `spack.share_path` (`$prefix/share/spack`) but that's shared with other stuff too.  AFAIK there is not proper "module root" that you could change in a fixture.  

@alalazo: is it worth tweaking `modules.py` so that the various module implementations (tcl, dotkit, lmod) don't refer to `spack.share_path` directly?  e.g. stick a top-level variable in there called `spack.module_root`, which could easily be set to a sandbox location?

**Comment by markcmiller86** [comment]
@alalazo pinging above inquiry from @tgamblin

**Comment by alalazo** [comment]
@markcmiller86 Apologies for the very late response, this one really went off my radar. Anyhow, if it is true that it's better late than never the answer to the above is that one needs to monkey patch:

https://github.com/spack/spack/blob/c627e5a6fcefb44330b4980835f0cf3a34ff2944/lib/spack/spack/modules/common.py#L213-L223

which is there since #3183
