### ISSUE TITLE
Use compilers for the same Spack

### ISSUE THREAD

**Issue by ax3l** [spack/spack#5101]
Hi,

I am aware of the `spack-tools` workflow to build compilers and other tools (e.g. CMake) in a second instance of spack.

Compilers are (in my naïve world-view) bootstrapped.
I found that compiling them externally first blows up the "getting started" workflow quite a bit for users (not me personally, but *users*).

But especially for CUDA C++ programs, there are [quite some limitations](https://gist.github.com/ax3l/9489132) on which compilers we are able to use...

Is there a fundamental reason we can't mark packages "bootstrapped", such as compilers so we can use and trigger their build when requested in a spec? This would make spack so much more powerful to the average user!

```bash
spack install boost %gcc@5.3.0
# oh you don't have a GCC 5.3.0!
# I will just bootstrap one for you
# ... here we go
# ... and now I even add it to your compilers.yaml and packages.yaml lists
#      (ﾉﾟ▽ﾟ)ﾉ
```

Is this a planned feature (or did I overlook an issue for it)?

```bash
spack install gcc@5.3.0
# Can this package be bootstrapped? Yes, so I will forget its dependencies for you
# ... here we go
# huh, this is a compiler!
# ... now I even add it to your compilers.yaml and packages.yaml lists
#      (ﾉﾟ▽ﾟ)ﾉ
```

**Comment by ax3l** [comment]
ccing @tgamblin

**Comment by alalazo** [comment]
About this bit:

> I am aware of the spack-tools workflow to build compilers and other tools (e.g. CMake) in a second instance of spack.

See #4061 (which got a lot of approval, but never got merged). For what is worth, I personally never built stuff in a second instance of Spack.

**Comment by ax3l** [comment]
Interesting! How do you do that workflow then? I remember having trouble loading the modules properly when I *used spack for the first time* (TM).

**Comment by alalazo** [comment]
You mean deleting things compiled with e.g. `gcc@6.3.0` but not the compiler itself? Usually I use anonymous specs for that:
```console
$ spack uninstall -aR %gcc@6.3.0
==> The following packages will be uninstalled:

-- linux-ubuntu14-x86_64 / gcc@6.3.0 ----------------------------
5mmylm6 autoconf@2.69%gcc

66ibmpp automake@1.15%gcc

grxzl6q boost@1.63.0%gcc+atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave

bequudr bzip2@1.0.6%gcc+shared

vf327oo cmake@3.8.1%gcc~doc+ncurses+openssl+ownlibs~qt

4ia2mwb double-conversion@2.0.1%gcc

v6cvswc folly@2017.06.05.00%gcc

ftbty62 gflags@2.1.2%gcc

uxafsp5 glog@0.3.4%gcc

47u5sx7 libevent@2.0.21%gcc+openssl

7enifnh libsigsegv@2.11%gcc

n7zmbzt libtool@2.4.6%gcc

uppywnz m4@1.4.18%gcc+sigsegv

ucbhcdy ncurses@6.0%gcc~symlinks

gxgr5or openssl@1.0.2k%gcc

jpgubk3 pkg-config@0.29.2%gcc+internal_glib

7cqp6cj zlib@1.2.11%gcc+pic+shared

==> Do you want to proceed? [y/N] 
```

**Comment by ax3l** [comment]
I mean the following workflow:

A user of ours does a spack clone to start working with spack.
The system has a gcc 6 or 7 installed, but we are bound to have gcc 5 for our software chain (e.g. due to CUDA).
How do I instruct the user to build a gcc 5 (with spack) and add it to spack compilers so they can install our software? Is there anything important to take care of?

In our case, to use the software, gcc 5 also needs to be loaded at *run*time (C++ header only libs). Will this confuse anything because technically that gcc 5 will depend on the initial system compiler?

**Comment by alalazo** [comment]
Ah, ok. Then I'd say the user currently needs to do this one time thing to set up his instance of Spack:
```console
$ spack install gcc@5.4.0
$ spack load gcc@5.4.0
$ spack compiler add
# At this point the gcc@5.4.0 should be found and added to the list
```
From here on he can do:
```console
$ spack install <spec> %gcc@5.4.0
```

> In our case, to use the software, gcc 5 also needs to be loaded at runtime (C++ header only libs).

If you are relying on module file to load the software, you can configure them to autoload the `gcc@5.4.0` module. Being a compiler and not a dependency you need to put something like:
```yaml
modules:
  tcl:
    mysoftware:
      load:
        - 'gcc/5.4.0'  # Here you need to put the correct module name
```

I'll try to come up with something to make bootstrapping easier.

**Comment by ax3l** [comment]
Off-topic questions:

> If you are relying on module file to load the software [...]

Are there other ways? (Besides setting paths manually.)

> Being a compiler and not a dependency you need to put something like [...]

All right, that's a similar problem as my question [here](https://github.com/LLNL/spack/issues/2378#issuecomment-314824695): I would love to set such dependencies in one place (package.py) instead of scattering it (would mainline even accept if I modify the default `modules.yaml`?).

**Comment by alalazo** [comment]
I'll start improving module file generation once #3183 gets merged. Don't want to add other features to that big refactoring.

**Comment by svenevs** [comment]
@ax3l FWIW if you've provided your users with (e.g. from `spack`) `clang@3.9.0` or higher, your user could try avoiding (the nightmare that is) `nvcc` altogether.  Example `cmake` configs [in my confused question here](https://stackoverflow.com/q/44402222/3814202).

Some underwhelming performance benchmarks (never made public) indicate at least comparable code generation, and in some cases LLVM was strictly superior.  I mean there's a reason why MSVC even internally relies on it these days ;)

Has nothing to do with the above, but `llvm` can compile CUDA now :heart:

It's also worth mentioning that you don't actually need to use the host compilers they state.  I've discovered by accident that their version checks for `clang` are actually more permissive, so they can also try using `clang` as their host compiler instead of the system `gcc`.  Waiting for the day they finally cave and emit a warning rather than fail out.

**Comment by ax3l** [comment]
@svenevs thanks, I am aware of the CUDA support in clang :) Nevertheless, note that CUDA projects (and clang) still need a full-flavored [CUDA toolkit (and drivers)](http://llvm.org/docs/CompileCudaWithLLVM.html#prerequisites) installed. Still, the general problem that software often does not compile with the already available compilers is the general, underlying workflow-demand we try to ease.

In the danger of going OT, even the first release of clang (3.8/3.9) CUDA was already quite impressive with production codes from what we saw. For example [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu/) performance was only about 8% behind native nvcc performance (tested with ~CUDA 7).

> It's also worth mentioning that you don't actually need to use the host compilers they state

Thx, [here is my personal list](https://gist.github.com/ax3l/9489132) and how to enable more compilers :)

**Comment by svenevs** [comment]
WOOT I definitely starred that gist :smile:  Yeah I only learned of this stuff in the past couple of months, and was so surprised that I didn't know about it I felt obligated to bring it up.  Seems you already know **way** more about the best practices though!  I got really frustrated with the host compiler restriction for Fedora because

1. It's `gcc@5.3.0`.
2. They require Fedora 23.

Fedora in particular gets screwed by the NVCC compatibility matrix, because you have to remain on a distribution that often times reaches end of service life before you can update.  /rant

**Comment by ax3l** [comment]
@alalazo can't we integrate the addition of user-selected `gcc` and/org `clang` versions in the new and fantastic `spack bootstrap` process?

**Comment by ax3l** [comment]
@alalazo an other problem I just found with the workflow
```bash
$ spack install gcc@5.4.0
$ spack load gcc@5.4.0
$ spack compiler add
```

-> a `spack load gcc@5.4.0` will not load the compiler since it does not create a reference to a module in the user's `compiler.yaml`

**Comment by ax3l** [comment]
And other problem I spotted in the `spack install <compiler> - load - add` workflow:

If I am installing `clang[++]` that way, e.g. in Travis, this will not add a Fortran compiler. Ideally, we would also need a CLI option to add it, maybe `spack compiler edit --fc $(which gfortran) clang@5.0.0`.

This is a common problem for unattended install of MPI applications (that currently need an FC in spack for MPI installs).

**Comment by ax3l** [comment]
To add another perspective to this issue: why a truly bootstrapped compiler should not depend on its build-compiler in the spec:

Imagine we want to make the `spack install gcc@someVersion` step faster and set up a binary cache for it. A user with a fresh clone of spack will have *any possible* compiler on their system. How would the binary cache for a GCC 5.3.0 look like?
- `gcc@5.3.0 %clang@3.9.0`
- `gcc@5.3.0 %clang@4.0.0`
- `gcc@5.3.0 %clang@5.0.0`
- `gcc@5.3.0 %gcc@4.8.1`
- `gcc@5.3.0 %gcc@4.8.2`
- `gcc@5.3.0 %gcc@5.0`
- `gcc@5.3.0 %gcc@6.0`
- `gcc@5.3.0 %gcc@7.0`

...? They are all the same and have no dependency to their `%compiler` but still we have them in the spec.

**Comment by alalazo** [comment]
This feature has been implemented by @becker33 a while ago, look at [install missing compilers](https://spack.readthedocs.io/en/latest/config_yaml.html) in `config.yaml`. Closing, but feel free to reopen if any point here is not answered.

**Comment by ax3l** [comment]
Oh wow, this simplifies workflows a lot, such as #14011.
