### ISSUE TITLE
Version preferences in packages.yaml ignored?

### ISSUE THREAD

**Issue by pramodskumbhar** [spack/spack#5110]
Hello,

I have following in `packages.yaml`:

```
    python:
        paths:
            python@2.7.9 arch=bgq-cnk-ppc64: /soft/interpreters/python-2.7.9/powerpc64-bgq-linux/
            python@2.7.11 arch=bgq-cnk-ppc64: /gpfs/mira-fs0/pro.../python-2.7.11-bgq/
        version: [2.7.9, 2.7.11]
        buildable: False
```

Consider simple dependency in `ninja` package : 

```
    depends_on('python', type=('build', 'run'))
```

And I get:

```
spack spec ninja
Input spec
--------------------------------
ninja

Normalized
--------------------------------
ninja
    ^python
        ^bzip2
        ^ncurses
            ^pkg-config
        ^openssl
            ^zlib
        ^readline
        ^sqlite

Concretized
--------------------------------
ninja@1.7.2%xl@12.1 arch=bgq-cnk-ppc64
    ^python@2.7.11%xl@12.1+shared~tk~ucs4 arch=bgq-cnk-ppc64
```

Spack should prefer `2.7.9`  over `2.7.11`?

**Comment by scheibelp** [comment]
> Spack should prefer 2.7.9 over 2.7.11?

It definitely should. I'll be able to look at this later on today.

**Comment by scheibelp** [comment]
I haven't traced the exact logic yet, but it looks like it isn't supporting the combination of the version preferences with the externals. From what I can tell checking into it, the version preferences work fine by themselves. In other words I don't think the preferences are used to choose a preferred external.

**Comment by pramodskumbhar** [comment]
thank you @scheibelp ! I confirm the preferences are working fine without external packages.

**Comment by scheibelp** [comment]
I've looked through this more and at the moment the code doesn't support preferences among externals. It occurs to me that instead of specifying ```versions```, you could specify preferences with the externals entirely by ordering their appearance in the yaml file (to be clear, Spack doesn't support this, I'm just proposing that it could). So for example the following would be sufficient:

```
    python:
        paths:
            python@2.7.9 arch=bgq-cnk-ppc64: /soft/interpreters/python-2.7.9/powerpc64-bgq-linux/
            python@2.7.11 arch=bgq-cnk-ppc64: /gpfs/mira-fs0/pro.../python-2.7.11-bgq/
```

where python 2.7.9 is preferred because it appears first. Is that desirable? To be clear you could also include a ```version``` entry, but it wouldn't affect how externals are chosen.

Also, is this issue causing you a great deal of trouble?

**Comment by pramodskumbhar** [comment]
> where python 2.7.9 is preferred because it appears first. Is that desirable? 

yes, that would be fine!

> Also, is this issue causing you a great deal of trouble?

I won't say this is a big problem. I was wondering why this is not working as documented.
This is `good to have` feature (on cray, bg-q machines I/we typically use external packages).

**Comment by davydden** [comment]
> where python 2.7.9 is preferred because it appears first. Is that desirable? To be clear you could also include a version entry, but it wouldn't affect how externals are chosen.

frankly, i think version choice during concretization should behave exactly the same way regardless of external/interal type of packages; i.e. the rules to choose one should be the same. Otherwise IMO it adds a confusion and inconsistency.

In https://github.com/LLNL/spack/pull/1983/ (among other stuff) I add a few test to conretizer with settings in `.yaml` + `preffered=true` in `package.py`. I think this bug should be addressed in the same way -- fix and add a test to make sure external packages are chosen by the same rules as internal.

**Comment by pramodskumbhar** [comment]
> should behave exactly the same way regardless of external/interal type of packages

Agree! I forgot that for `non-external` packages one can just specify `version: [2.7.9, 2.7.11]` and then it will be not consistent.

**Comment by scheibelp** [comment]
>i think version choice during concretization should behave exactly the same way regardless of external/interal type of packages; i.e. the rules to choose one should be the same. Otherwise IMO it adds a confusion and inconsistency.

> for non-external packages one can just specify version: [2.7.9, 2.7.11] and then it will be not consistent.

Spack always replaces a package with an external when one satisfies the constraints, so there isn't a consistency error when trying to resolve preferences between externals and non-externals, if that's what you mean. It could be confusing to the user though. The rule is simple enough that IMO it wouldn't be problematic (as long as it's explained up front).

It may be possible to handle external preferences the same way as for normal concretization, but preferences as explained in http://spack.readthedocs.io/en/latest/build_settings.html are not well-defined in terms of full specs. They make it easy to choose among versions, or among compilers, but not combinations of the two (say version 1 is preferred to 2, and gcc is preferred to intel, but what about ```@1 %intel``` vs ```@2 %gcc```?). Additionally, externals aren't required to specify version or compiler (although perhaps they should be).

So for the above reasons I'd prefer to do it the way I originally proposed. If people prefer differently then I can look into that, but it will involve making decisions like the above.

**Comment by davydden** [comment]
@scheibelp I am not sure I understand completely what you are saying but 

> Additionally, externals aren't required to specify version or compiler (although perhaps they should be).

I am in favour of this one so that 
```
version: [2.7.9, 2.7.11]
```
means `2.7.9` is preferred to `2.7.11` regardless whether or not those are externally provided via
```
paths:
            python@2.7.9 arch=bgq-cnk-ppc64: /soft/interpreters/python-2.7.9/powerpc64-bgq-linux/
            python@2.7.11 arch=bgq-cnk-ppc64: /gpfs/mira-fs0/pro.../python-2.7.11-bgq/
```
or build by Spack. 

 and 

> the code doesn't support preferences among externals

is fixed.

**Comment by skosukhin** [comment]
The problem in #4956 has the same roots.

**Comment by goxberry** [comment]
I also just encountered this bug.

**Comment by haampie** [comment]
Closing since we have [package requirements](https://spack.readthedocs.io/en/latest/build_settings.html#package-requirements) now
