### ISSUE TITLE
Rose package out of date w.r.t. 0.9.7.0

### ISSUE THREAD

**Issue by ian-bertolacci** [spack/spack#5124]
This does not refer to the new 0.9.9.0 version of rose (which is addressed by #4730)
Rather the issue is that version 0.9.7 of rose has gone missing, and 0.9.7.0 has been put in its place.
([see Rose release page](https://github.com/rose-compiler/rose/releases))

There are several problems that this causes
1. URL (https://github.com/rose-compiler/rose/archive/v0.9.7.tar.gz) fails to resolve (404 error). New url is https://github.com/rose-compiler/rose/archive/v0.9.7.0.tar.gz
2. Version (0.9.7) is wrong, should be 0.9.7.0, . as also causing a 404 error.
3. Checksum now incorrect for version 0.9.7.0
3. add_spack_compiler_recognition patch fails:
```
Patching failed last time. Restaging.
==> Staging archive: /home/ian/Research/Workspace/spack_test/spack/var/spack/stage/rose-0.9.7.0-lryeemoinaapvnsw4qusqasnwliffkjw/v0.9.7.0.tar.gz
1 out of 1 hunk FAILED -- saving rejects to file config/compiler-defs.m4.rej
==> Patch add_spack_compiler_recognition.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/home/ian/Research/Workspace/spack_test/spack/var/spack/repos/builtin/packages/rose/add_spack_compiler_recognition.patch'
```

At this point I removed the patch directive, and it failed with:
```
==> Building rose [Package]
==> Executing phase : 'install'
==> Error: AttributeError: 'Rose' object has no attribute 'install'
```

I'd like to keep hacking on this, but thought I'd also raise an issue to see if this may have already been fixed somewhere, or if someone knew what the underlying problem was.

**Comment by adamjstewart** [comment]
This should be fixed by #4730.

**Comment by ian-bertolacci** [comment]
I accadentally posted the issue before completion, I am updating the issue to address the real problem.

**Comment by ian-bertolacci** [comment]
Issue updated.

Also, #4730 looks like it needs some work.

**Comment by ian-bertolacci** [comment]
Also, patch fails when installing version 'master'

**Comment by adamjstewart** [comment]
Feel free to keep hacking off of #4730 and submit a new and improved PR. I haven't gotten a response from @justintoo or @rosecompiler on #4730 in a few weeks.

**Comment by alalazo** [comment]
For the record: #4730 has been closed in favor of #5296

**Comment by justintoo** [comment]
Need some pointers on https://github.com/spack/spack/pull/5296#issuecomment-344771680.

**Comment by ian-bertolacci** [comment]
Stale issue.
