### ISSUE TITLE
A version like 2017-05-30 in packages.yaml doesn't work.

### ISSUE THREAD

**Issue by hartzell** [spack/spack#5136]
I'm not sure if this is a bug, a feature, or just an obvious fact of life that I am missing, but this works as expected:

`
spack install falcon@2017-05-30
`

This also works:

```yaml
packages:
  falcon:
    version: ['2017-05-30']
```

but if I don't quote the version string

```yaml
packages:
  falcon:
    version: [2017-05-30]
```

I get

```
[hartzelg spack-falcon]$ (module purge;spack install falcon)
==> Error: At packages:falcon:version:0: datetime.date(2017, 5, 30) is not valid under any of the given schemas
[hartzelg spack-falcon]$
```

**Comment by alalazo** [comment]
Hmmm, need to dig further into this. `datetime` should be a valid `string` as far as I understand.

**Comment by becker33** [comment]
This was fixed sometime in the past 7 years, it should have been closed at some point.
