### ISSUE TITLE
Configure as root user

### ISSUE THREAD

**Issue by ax3l** [spack/spack#5139]
Related to #4480, where running as root during partitioning is common.

New versions of some autotools configure scripts (imho rightfully) abort if they are called as super-user (root). The only way to still go on is by exporting `FORCE_UNSAFE_CONFIGURE=1`.

Shall we maybe add such an bypass to `spack` itself so (root) users are not disturbed? Maybe add an explicit switch? Did you encounter similar problems with other build systems?

As an example, compile `tar`:
```bash
$ sudo spack install -v tar
# ...
checking whether mknod can create fifo without root privileges... configure: error: in `/tmp/root/spack-stage/spack-stage-2ELK8S/tar-1.29':
configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)
See `config.log' for more details
==> Executing phase : 'configure'
```

This makes docker and singularity image setups a bit more cumbersome, since one has to add a special `spack` user to partition the images. (See my spack-powered ✨ images in https://github.com/ax3l/dockerfiles)

Example for docker:
```
# ...

# Add non-privileged, but system docker user with sudo rights
RUN        groupadd -r spack -g 901 && \
           useradd -u 901 -r -m -g spack spack && \
           echo "spack ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/spack && \
           chmod 0440 /etc/sudoers.d/spack
# this is also the user that executes all commands below
USER       spack
WORKDIR    $HOME

# ...
```

ccing @adamjstewart

**Comment by ax3l** [comment]
Now that I think about this 2 month later again, a
```docker
ENV FORCE_UNSAFE_CONFIGURE=1
```
did also solve it... (at least for autotools' configure scripts)

**Comment by alalazo** [comment]
#5582 got in. Is this issue still needed?

**Comment by ax3l** [comment]
the documentation here and in the (docker) manual is probably enough for now in case someone faces problems with installs as root user (which is generally a bad idea, but ok in Docker or virtual machines).
