### ISSUE TITLE
Installing Silo is having issues with QT

### ISSUE THREAD

**Issue by manish2479** [spack/spack#5154]
Hi 

spack/var/spack/repos/builtin/packages/silo/package.py:66, in install:
```
     49       def install(self, spec, prefix):
     50           config_args = [
     51               '--enable-fortran' if '+fortran' in spec else '--disable-fortran',
     52               '--enable-silex' if '+silex' in spec else '--disable-silex',
     53               '--enable-shared' if '+shared' in spec else '--disable-shared',
     54           ]
     55
     56           if '+silex' in spec:
     57               config_args.append('--with-Qt-dir=%s' % spec['qt'].prefix)
     58
     59           configure(
     60               '--prefix=%s' % prefix,
     61               '--with-hdf5=%s,%s' % (spec['hdf5'].prefix.include,
     62                                      spec['hdf5'].prefix.lib),
     63               '--with-zlib=%s,%s' % (spec['zlib'].prefix.include,
     64                                      spec['zlib'].prefix.lib),
     65               '--enable-install-lite-headers',
  >> 66               *config_args)
     67
     68           make()
     69           make('install')

See build log for details:
```

```
checking for Qt... yes:
    QT_CXXFLAGS=-I/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/include -I/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/include/Qt -I/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/include/QtCore -I/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/include/QtGui
    QT_DIR=/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3
    QT_LIBS=-L/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/lib -lQt5AccessibilitySupport  -lSM -lICE  -lX11 -lXext -lXmu -lXt -lXi
    QT_UIC=/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/bin/uic
    QT_MOC=/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/bin/moc
    QT_LRELEASE=/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/bin/lrelease
    QT_LUPDATE=/home1/user1/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-5.9.1-wny6h2r47ctzrum7j6iuns3mern7q4m3/bin/lupdate
checking correct functioning of Qt installation... failure
configure: error: Failed to find matching components of a complete
```

Any help would be appreciated.

Thank You,
                 Manish

**Comment by cyrush** [comment]
Including @markcmiller86 

FYI: I don't think Silo's silex tool has been tested against Qt 5.x, silex likely requires Qt 4.x.


Chances are you don't need silex (which is a UI utility for viewing the structure of silo files).
I would actually recommend not having Silo's silex option default to on, b/c building Qt for this might increase build times substantially.

Also silex support should specify only 4.x.

**Comment by manish2479** [comment]
Hi Cyrush,

I got Silo installed by adding silex=false.

`./spack install silo silex=false`

Thank You,
                 Manish

**Comment by cyrush** [comment]
@manish2479  glad that worked for you!

**Comment by markcmiller86** [comment]
Sorry about this. Silo's Qt configuration logic is badly broken and I often have to jump through hoops in terms of the configuration line I pass it to get it to work. And, as @cyrush mentions, Silo does only currently support Qt-4.

That said, I now have a question. What if I enhance Silo to support *either* Qt-4 or Qt-5? In Spack's package logic for Silo, would I use a version-**less** spec for the depends_on directives?

**Comment by tgamblin** [comment]
@markcmiller86: probably you'd want `depends_on('qt@4:')` or something like that.  Unless you build with Qt3.  I doubt anyone would try to install with Qt3, though.

**Comment by tgamblin** [comment]
Looks like this worked for @manish2479

**Comment by tgamblin** [comment]
@manish2479 or @markcmiller86: would one of you like to submit a PR making `sliex` support default to `False` in the silo build (assuming you haven't already)?

**Comment by markcmiller86** [comment]
sure. I will do that now.

**Comment by manish2479** [comment]
Hi 

I am seeing this issues with QT 4.8.6 too.

Thank You,
                 Manish
