### ISSUE TITLE
spack load: default module system

### ISSUE THREAD

**Issue by ax3l** [spack/spack#5166]
I searched the docs and `etc/` but did not find a way to do the following:

When running `spack load` and only having `lmod` configured (in `modules.yaml`), is there a way configure `spack load -m lmod` by default ~~so I don't need to pass it~~? Otherwise it will fail complaining `tcl` is not available:
```bash
$ spack load cmake
spack module loads: error: argument -m/--module-type: invalid choice: 'tcl' choose from:
    lmod
$ spack module loads cmake
# output ok, but does not load the module env
$ spack load -m lmod cmake
# nope, not an option
$ spack module loads -m lmod cmake
# output ok, but does not load the module env
```

update: oh wait, that does not seem to work with lmod at all ... (I used `module load` directly with `lmod` before).

**Comment by adamjstewart** [comment]
@alalazo

**Comment by alalazo** [comment]
`spack load` is currently based on `tcl` and it makes little sense to base it on other module systems. Actually there's an effort on-going which I fully endorse to make it module-free, see #14062 Closing

**Comment by ax3l** [comment]
Thanks, didn't know! :)
