### ISSUE TITLE
Parallel make throttle by load average

### ISSUE THREAD

**Issue by markcmiller86** [spack/spack#5208]
Spack supports and invokes parallel make, which is great. But, sometimes I'd like it to be _nicer_ about how much of a login node I am taking on a machine and, when doing long builds, have it throttle itself so as not to be too much of a resource hog. Make has the ability to specify a load average threshold...

```
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
```

above which, it will not start new jobs.

Is this something that Spack could be enhanced to pass on to make?

**Comment by KineticTheory** [comment]
👍

**Comment by adamjstewart** [comment]
You _can_ set the max level of parallelism used by `make`:
http://spack.readthedocs.io/en/latest/config_yaml.html#build-jobs

Being able to set the load average would also be cool.

**Comment by mathstuf** [comment]
I support this. I remember discussing it when `spack install -j` was added, but I can't find the discussion anymore.

**Comment by alalazo** [comment]
The default behavior now caps to a maximum of 16 cores. Closing this issue, but feel free to reopen if you think further action is needed.
