### ISSUE TITLE
NCL build fails almost silently with Intel compiler

### ISSUE THREAD

**Issue by bccomm** [spack/spack#5253]
In the middle of building ncl%intel@17.0.4, the following is logged in spack-build.out:

```
g\+\+ -qopenmp -fp-model precise -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -O     -o ncl Ncl.o io.o NclHLUObj.o NclApi.o guiFuncs.o NclDriver.o 			scanner.o parser.o MathFuncs.o NclTypedouble.o NclTypefloat.o 			NclTypeint.o NclTypelogical.o 			NclTypelong.o NclTypeobj.o 			NclTypeshort.o NclTypestring.o 			NclTypeint64.o NclTypeuint64.o 			NclTypeubyte.o 			NclTypeushort.o NclTypeuint.o NclTypeulong.o 			NclTypebyte.o NclTypechar.o TypeSupport.o 			NclMultiDValData.o AddFileFormats.o AttSupport.o DataSupport.o 			FileSupport.o Formats.o GetGrids.o 			AdvancedFileSupport.o 			NclAdvancedFile.o NclAdvancedGroup.o 			InitData.o Memory.o NclAtt.o NclCCM.o 			NclCoordVar.o NclData.o NclGroup.o NclFile.o NclFileVar.o 			NclGRIB.o NclMultiDValnclfileData.o 			NclNetCdf.o NclOneDValCoordData.o NclType.o 			NclTypelist.o NclVar.o VarSupport.o 			ctoiee.o date.o qu2reg3.o rowina3.o scm0.o ncepcode.o 			 NclHDF.o 			 NclNewHDF5.o NclHDF5.o h5reader.o h5writer.o 			 			NclNetCDF4.o 			 NclOGR.o NclAdvancedOGR.o AddBuiltIns.o AddHLUObjs.o 			AddIntrinsics.o Execute.o 			Machine.o OpsFuncs.o SrcTree.o 			Symbol.o Translate.o  			NclHLUVar.o HLUSupport.o 			NclMultiDValHLUObjData.o 			BuiltInSupport.o BuiltInFuncs.o 			javaAddProto.o javaAddFuncs.o 			userAddProto.o userAddFuncs.o 			HLUFunctions.o yywrap.o craybin.o 			complete.o editline.o sysunix.o ListSupport.o 			NclList.o NclMultiDVallistData.o 			NclProf.o NclTime.o PrintToken.o fortranio.o  -L../../.././ni/src/lib/nfp -lnfp -L../../.././ni/src/lib/nfpfort -lnfpfort -L../../.././ni/src/lib/hlu -lhlu -L../../.././ncarg2d/src/libncarg -lncarg -L../../.././ncarg2d/src/libncarg_gks -lncarg_gks -L../../.././common/src/libncarg_c -lncarg_c -L../../.././ngmath/src/lib -lngmath -L'/opt/spack/tree/intel-17.0.4/ncl-6.4.0-vl'/lib  -lnetcdf -lcurl  -lhdf5_hl -lhdf5 -lsz  -lmfhdf -ldf -ljpeg -lz -lsz -lhdf5_hl -lhdf5 -lsz -lz -lgdal -lproj -ljpeg      -lpng -lz -lcairo -lXrender -lfontconfig -lpixman-1 -lfreetype -lexpat -lpng -lz -liconv -lbz2  -L../../.././external/sphere3.1_dp -lsphere3.1_dp -L../../.././external/fftpack5_dp -lfftpack5_dp -L../../.././external/lapack -llapack_ncl -L../../.././external/blas -lblas_ncl -lX11 -lifcore -lifport -lm  -ldl  
g++: precise: No such file or directory
g++: unrecognized option '-qopenmp'
make[4]: *** [ncl] Error 1
make[4]: Leaving directory `/local/build/bvchiare/spack-stage/spack-stage-STfZ1j/ncl_ncarg-6.4.0/ni/src/ncl'
Making ./ni/src/mkwrap
```
'g\\+\\+' [sic] is mentioned in ni/src/ncl/Makefile as the value of CC_LD. As you can see, the build happily continues, but the ncl interpreter itself does not get built or installed.

**Comment by scheibelp** [comment]
Looking up the previous contributors to this package: @mjwoods, @michaelkuhn, @skosukhin 

Does this error ring any bells?

Looking at this package I notice it talks about enabling OpenMP support but doesn't declare any dependency on mpi. All the mpi implementations in Spack come with logic to augment the environment when they are declared as a dependency (which may allow it to understand ```-qopenmp```). If you don't need mpi support try adding ```~openmp``` to your spec. If you do, perhaps adding ```depends_on('mpi' when='+openmp')``` to the package.py file for ncl will work.

**Comment by bccomm** [comment]
MPICH did get pulled in implicitly because of the dependency on HDF5 and NetCDF. I'm not sure that that's supposed to work, but everything else in the package built okay. `qopenmp` is supposed to be `fopenmp` anyway for gcc.

The immediate cause of this specific error is that `-qopenmp -fp-model precise`, which are Intel-specific _compiler_ flags, are being passed to g++, here called as a _linker_. xild doesn't understand them either. Neither of them interpret `precise` as a parameter, instead it gets treated as an object to be linked in. 

There doesn't seem to be much ICC logic in the build configuration file written by spack, but I'm left wondering how this step runs at all, even without spack. Perhaps the LINUX*INTEL configurations have something subtle, since apparently _someone_ got it to build at some point.

As often happens, a user I was helping needed it right away. So I just linked it manually using almost the same command, omitting the extraneous compiler flags, and listing out the `-L/path/to/library` flags that were needed for it to link cleanly. It works fine with mpich, and comparing with [this handy official package manifest](http://www.ncl.ucar.edu/Download/files/NCL_NCARG_files.txt), the ncl binary was the only thing that was missing.

**Comment by skosukhin** [comment]
1) I am sorry, I don't understand what OpenMP has to do with MPI and why the package should depend on it.
2) NCL's building system is just bad and problems with it appear from time to time. I don't see how "official package manifest" can be handy. There should be no need for it: the building process should stop with an error if something goes wrong. Anyway, the goal was to compile the package with Intel compiler, so -qopenmp flag was chosen correctly. The question is why 'g++' got called in that scenario.

**Comment by alalazo** [comment]
Closing as stale. Feel free to reopen.
