### ISSUE TITLE
spack setup with command line compiler flags rebuilds packages

### ISSUE THREAD

**Issue by bvanessen** [spack/spack#5254]
I am using spack setup to create the environment for a software package that I am developing.  I noticed that if I pass command line compiler flags (e.g. cflags="-O3 -march=native" cxxflags="-O3 -march=native" fflags="-O3 -march=native"), spack will rebuild all of the dependent packages each time I run the setup command.  If I don't have the command line arguments it properly recognizes that the packages are built.  Note that it doesn't reinstall the modules because it recognizes that they are already installed and it doesn't create a duplicate of the package, but it does build it again. @becker33

**Comment by pramodskumbhar** [comment]
@bvanessen : could you check if you have same issue with latest PR #5043?

**Comment by bvanessen** [comment]
There is something broken with that PR and I couldn’t get very far in the build process.  I added a log file to its conversation.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by adamjstewart** [comment]
This is a limitation of Spack's concretization algorithm and has nothing to do with `spack setup`, the same issue will also occur if you use `spack install`.
