### ISSUE TITLE
Odd message while staging chombo

### ISSUE THREAD

**Issue by markcmiller86** [spack/spack#5305]
I get a confusing but benign message from spack when staging chombo...

```
[scratlantis:~/spack/spack] miller86% spack stage chombo@3.2
==> Trying to clone git repository: http://bitbucket.org/drhansj/chombo-xsdk.git at commit 71d856c
==> No checksum needed when fetching with git
==> Already staged chombo-3.2-2tfom3zbqdc24bfafe7ybfc44yftvbtc in /Users/miller86/spack/spack/var/spack/stage/chombo-3.2-2tfom3zbqdc24bfafe7ybfc44yftvbtc
```

The part that is strange is the `Already staged chombo-3.2...` message. I made sure I removed it from `cache` cdir and removed all instances of it in `stage` dir. Nonetheless, this message always comes up. I think its a bug resulting from the particular fetch strategy that Chombo uses.

**Comment by becker33** [comment]
Note: This may have to do with a symlink that is not being deleted when we clean up. I was able to reproduce it with a package with a tarball-based release.

**Comment by alalazo** [comment]
With develop at eebfb1cf0795273c4d8ee4e23af886f03f07f6c4
```console
$ spack stage chombo@3.2
==> Staged chombo in /tmp/culpo/spack-stage/spack-stage-chombo-3.2-t7babw7hy2gfbfcfmjkorpiejttnmo27
```
