### ISSUE TITLE
tcl modules question

### ISSUE THREAD

**Issue by ssergien** [spack/spack#5400]
Is there a way to add mpi version to the tcl module filename?
I found this in the documentation:
```
suffixes:
        '^openmpi': openmpi
        '^mpich': mpich
```
But what if the same software was built with a different mpi flavor.

Thanks.

**Comment by alalazo** [comment]
@ssergien The key of the `suffixes` dictionary is an anonymous spec that act as a constraint. Any spec satisfying it should have the suffix attached. Thus in principle you can do:
```yaml
suffixes:
    '^openmpi@X': openmpi-X
    '^openmpi@Y': openmpi-Y
```
to select among different versions of `openmpi`. In the expression you can use any token that is part of the spec syntax (if you can't it's a bug that needs to be fixed).

**Comment by ssergien** [comment]
I see how it can be done that way. Is there another way to do it? 
Like for example:
```
install_path_scheme: '${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}'
```
Is there a way to do something like:
```
'^openmpi@${VERSION}': openmpi-${VERSION}
```
To make it somewhat generic

**Comment by alalazo** [comment]
@ssergien Not yet. How many MPIs do you need to deal with?

**Comment by ssergien** [comment]
This the test environment that I created. But in our production we use MPICH, MVAPICH2, OpenMPI and Intel-MPI, also multiple versions of the flavors mentioned. So it can get a little tricky.

Thanks for the answers. It would be nice to have this feature in the future though.

**Comment by alalazo** [comment]
Note taken. Generalizing suffixes in `modules.yaml` is something we are also discussing with @tgamblin. Closing for now.
