### ISSUE TITLE
spack build-env is broken when used with hashes

### ISSUE THREAD

**Issue by davydden** [spack/spack#5401]
```
$ spack env /2dg4ujkb4cdwxrenustxqtwvjmyoydj7 bash
==> Error:
```
here the hash is for gcc, but it's the same for any package as far as I can say. Both macOS and Ubuntu.

**Comment by alalazo** [comment]
I don't think `spack env` is broken, it just needs `--` before the subsequent command (otherwise bash is interpreted as part of the spec, I guess). This:
```console
$ spack env /2dg4ujkb4cdwxrenustxqtwvjmyoydj7 -- bash
```
should do the trick. The error message can be improved a lot though.

**Comment by alalazo** [comment]
I removed the 'broken-develop' tag, because to me it means we have a CI issue in `develop` (besides the one we get from Travis itself of course)

**Comment by davydden** [comment]
> $ spack env /2dg4ujkb4cdwxrenustxqtwvjmyoydj7 -- bash

then something have changed, as it used to work, IIRC.

**Comment by davydden** [comment]
@alalazo no luck:
```
$ spack env /2dg4ujkb4cdwxrenustxqtwvjmyoydj7 -- bash
==> Error:
```

**Comment by davydden** [comment]
> The error message can be improved a lot though

the lack thereof :smile:

**Comment by alalazo** [comment]
The assertion maintained in #5339 is failing sometimes in `spack env`. Need to investigate why + add a decent error message there.

**Comment by alalazo** [comment]
One issue I see is somehow related to #3515. When we use a hash we are asking for the environment of a thing that has been installed already and that *in the meanwhile may have gone out of sync* with `spack.repo`. This makes me think that we want:
```python
if spec.installed:
    # just read the .spack/build.env file
else:
    build_env.setup_package(spec.package, args.dirty)
```
instead of just:
```python
build_env.setup_package(spec.package, args.dirty)
```
as the main logic for the command. Thoughts?

**Comment by tgamblin** [comment]
The former `spack env` is now `spack build-env`

**Comment by alalazo** [comment]
With develop at eebfb1cf0795273c4d8ee4e23af886f03f07f6c4:
![Screenshot from 2023-04-05 18-43-01](https://user-images.githubusercontent.com/4199709/230147870-d446a7f6-6f00-403c-aee7-3209c8ac2f99.png)
