### ISSUE TITLE
Github Archive URL checksums have changed

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#5411]
I haven't been able to download and test all of the archives, but it looks like we may be affected by homebrew/homebrew-core#18044.  See also easybuilders/easybuild#5151.

*Short story:* GitHub has changed the way they generate their release "archives". They're generated dynamically so many checksums have changed for `github.com/.../archive/` URLs.   Looks like we may have to download all these tarballs and re-checksum them.  

I count 258 packages and 728 tarballs that we'll need to deal with.  Great! 🔥 🔥 🔥 

*Long story:* See the details here:

* homebrew/homebrew-core#18044
* easybuilders/easybuild-easyconfigs#5151
* google/protobuf#3619
* bazelbuild/bazel#3722
* tensorflow/tensorflow#12979

I don't think it's that hard to do this but it's tedious.  It's also not clear to me right now whether their hashes will change back, or whether they might change again.  If they're definitely going to stay changed, I think we should take the plunge, download and checksum these (using https), and use the opportunity to start using SHA256 instead of MD5 if we're doing this anyway.

Note: The `github.com/.../release/...` URLs are apparently stable (they respect the file the author uploads, and are not dynamically generated).  It might be worth switching to those URLs where possible, but I don't think it's possible for all of our projects.

@adamjstewart @alalazo @mamelara @scheibelp @becker33 @lee218llnl @mplegendre

**Comment by davydden** [comment]
I think we need a python script to do the job (download/check/update if necessary) on the provided subset of all packages in Spack.

**Comment by tgamblin** [comment]
Mirror will actually do the download part. It just needs a few tweaks.

**Comment by alalazo** [comment]
> It's also not clear to me right now whether their hashes will change back, or whether they might change again. If they're definitely going to stay changed, I think we should take the plunge, download and checksum these (using https), and use the opportunity to start using SHA256 instead of MD5 if we're doing this anyway.

:+1:

**Comment by hartzell** [comment]
tbb seems to be broken by this.

**Comment by hartzell** [comment]
In my case it looks like someone updated the intel-tbb package with the info for `@2017_U6` and it is now no longer correct for my mirrored copy of the tarball.

**Comment by davydden** [comment]
yes, tbb is fixed already https://github.com/LLNL/spack/pull/5349

**Comment by tgamblin** [comment]
@davydden: that's an older tbb change caused by their developers. Not sure if it fixes this one -- do you know for sure?

**Comment by davydden** [comment]
> do you know for sure?

no, it just happened a few days ago and i though it's related. It could be that it's also broken indeed.

**Comment by hartzell** [comment]
> It could be that it's also broken indeed.

I think that it's likely that George is confused (and I would be the one to know...). 

It *did* break my build though.  I think "same name, different digest, I have the old tarball" is what I'm seeing.

**Comment by hartzell** [comment]
I figured out what happened to me (this is why I try not to build complicated things...).

I have a spack mirror of all my tarballs that lives in git lfs.  My build script checks it out at the beginning to build.  The mirror repo is tagged in parallel with the other repo so things should always build.

I have a remote site that can't connect to our GitHub Enterprise via http.  SSH works for normal repos, but I currently can't clone the ones that use git-lfs, so I have to copy them over by hand.

The build script has an option (`--fubar`) to look for the mirror in `~/tmp/spack-mirror` instead of cloning it.

In this case, I copied the repo to `~/spack-mirror` and Spack was happily pulling fresh tarballs from the internet

Would a PR that turned off the ability to download from the Internet and force the use of the mirror be acceptable?

**Comment by tgamblin** [comment]
> Would a PR that turned off the ability to download from the Internet and force the use of the mirror be acceptable?

I think it might make sense to rework `mirrors.yaml` so that fetching from the package's origin is part of the semantics there.  e.g.:

```yaml
mirrors:
  - $cache
  - $origin
  - file:///some/local/path/to/mirror/
  - https://internal-spack-server/mirror/
```

Currently Spack's cache and the origin (URL from package) are just implicit, but this would allow you to control when/whether Spack fetches from them.

**Comment by hartzell** [comment]
And so if I remove `$origin` it would *not* use the internet?

**Comment by hartzell** [comment]
@tgamblin -- I'll take a look at implementing that.

**Comment by alalazo** [comment]
The situation @hartzell is seeing is kind of frustrating, and it happened already a few times in the past (`netcdf` sounds familiar?). What do you think about extending `version` to optionally accept a tuple of old hashes, like:
```python
version('2.0.1', 'hash', deprecated=('old_hash', ...))
```
In this way we can handle a discrepancy between mirrors and `$origin` md5 sums gracefully, with the semantic we think it's most appropriate. For instance we could warn users that they have a mirror that is out of sync (but still "trusted"), and they need to update it.

**Comment by tgamblin** [comment]
@alalazo: I worry about deprecated hashes because I know of no other system that does that.  Seems like the solution is always to remove the old file -- why not just do that and force a re-download?  We could prompt before removing.  We could also add an option to force a new download to `spack install` and suggest it -- wouldn't those be easier?

**Comment by alalazo** [comment]
> why not just do that and force a re-download?

I am fine with this solution too, and it will for sure be easier. 

If we don't record deprecated hashes we could potentially loose a tiny bit on the reproducibility side, and maybe that could be worse for people working on air-gapped systems (if they are stuck with an old tarball and need to wait for some authorization)? 

The other thing it could enable in the future is a check at install time of the status of an installed package. That could permit warning users that the version`X.Y.Z` they are using changed in some way and maybe they want to reinstall.

All that said, nothing of the above is a game changer, and there should be a 5 min. ban from the internet for people that change a tarball without bumping at least the patch level of the version :smile: 

> We could also add an option to force a new download to spack install and suggest it -- wouldn't those be easier?

If you think it's worth it, I can implement the functionality in #5384 .

**Comment by tgamblin** [comment]
> If we don't record deprecated hashes we could potentially loose a tiny bit on the reproducibility side, and maybe that could be worse for people working on air-gapped systems (if they are stuck with an old tarball and need to wait for some authorization)?

There is always the `--no-checksum` option for people who know that the archive they have is good.  We warn people about it, but this is kind of what it's there for.

> If you think it's worth it, I can implement the functionality in #5384 .

That would be great!

**Comment by hartzell** [comment]
You can't simply remove the tarball in my case, it's committed to a mirror directory that's managed in parallel and lives in git/git-lfs.  All of my releases are tagged and known to work, when things like this happen there are just some points in time where you can't check out the trees and build.  No one ever checks out arbitrary points in time though, so it's not a show stopper.

The `deprecated` approach would avoid an element of surprise, when I see a build fail because a digest doesn't match and I wonder whether someone's been hacked or ....

I think @alalazo is being too generous with his 5-minute ban.  I'd go for a solid 15 (although in this case, GitHub did it **to** the developers...).

**Comment by naromero77** [comment]
Right now the package that I maintain is being impacted by this.

The documentation says that the Tag method:

```
version('1.0.1', git='https://github.com/example-project/example.git',
        tag='v1.0.1')
This download method is untrusted, and is not recommended.
```

However, If I understand the underlying philosophy correctly: If its not a hashable object, than there it cannot be trusted and you must do a `--nocheck-sum`?

**Comment by tgamblin** [comment]
@naromero77: you're impacted by the github hash changes (the issue at top) or by the tags?  Confused about what the issue is.

**Comment by naromero77** [comment]
@tgamblin Sorry for the confusing message. Yes, affected by the github hash changes like many others. I was just trying to understand why downloading by git tag's is not recommended? 

As I understand it, if its not hashable, it cannot be trusted.

**Comment by hartzell** [comment]
@tgamblin -- I was looking at implementing your suggestion for reworking the mirrors and how packages are fetched and avoiding the internet.

I think I know how I will/would do it, but I'm confused/curious....

It seems that [Stage.fetch()](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/stage.py#L377) already supports a `mirror_only` argument that seems like it does what I'd like.  If there were a way to set that flag and update the various places where `fetch()` were called that seems like a much less intrusive change.

The comments around [in `stage.py` around line 385](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/stage.py#L385-L387) make it sound as if there are other issues that you might want to address.  Is reworking how fetchers are specified part of that, or?

Thanks!

**Comment by adamjstewart** [comment]
Closing this as all of the GitHub checksums were fixed at some point.
