### ISSUE TITLE
on/off vs. True/False consistency in spack info output

### ISSUE THREAD

**Issue by markcmiller86** [spack/spack#5487]
Looking at this output from `spack info zlib`...

```
Variants:
    Name [Default]    Allowed values    Description
    pic [on]                  True, False          Produce position-independent code (for shared libs)
    shared [on]            True, False          Enables the build of shared libraries.
```

I notice the inconsistency between the `Default` values (on/off) and the `Allowed` values. Now, normal variants are in the python code itself set as either `True` or `False`. But, there is no need for `spack info` to use _exactly_ the same verbiage in its output. On the other hand, I think it should be consistent too.

I am happy to adjust code but don't honestly know what the preferred output would be...

```
Variants:
    Name [Default]    Allowed values    Description
    pic [on]                  on, off          Produce position-independent code (for shared libs)
    shared [on]            on, off          Enables the build of shared libraries.
```

or

```
Variants:
    Name [Default]    Allowed values    Description
    pic [True]              True, False         Produce position-independent code (for shared libs)
    shared [False]       True, False          Enables the build of shared libraries.
```

or, using just `T` or `F` saves a lot of horizontal real estate

```
Variants:
    Name [Def]    Allowed    Description
    pic [T]             T, F           Produce position-independent code (for shared libs)
    shared [F]       T, F           Enables the build of shared libraries.
```

or

```
Variants:
    Name [Def]    Allowed values    Description
    pic [+]              +, ~                 Produce position-independent code (for shared libs)
    shared [~]        +, ~                 Enables the build of shared libraries.
```

I kinda like this latter one as it uses spack command line speak.

**Comment by tgamblin** [comment]
I like `on` and `off` but we don't let you write `shared=on` on the command line (yet).  Currently we only recognize `true` and `false` (case-insensitive) and the `+`/`~` shorthand.

@alalazo: thoughts?

**Comment by alalazo** [comment]
I also like `on` and `off`. To recognize them from the command line I think we need only a couple of checks in `spec.py` (+ making sure nobody is using them in packages as values for SV variants + tests).

**Comment by markcmiller86** [comment]
Ok, sounds like consensus is `on` and `off`. That is fine. Is it ok to _just_ change output of `spack info` to use `on` and `off` (btw... `on` or `On` and `off` or `Off`) in place of `True` and `False` for now? I won't have time to change spec.py, check packages for SV variants and add tests.

**Comment by adamjstewart** [comment]
Closed by #16235

**Comment by tgamblin** [comment]
@adamjstewart: Note: you still can't write `hdf5 mpi=on` or `hdf5 mpi=off`.  You *can* write `hdf5 mpi=true` or `hdf5 +mpi`.  Adding on/off would make sense, *but* there are some complications.

We currently maintain a separation between specs and packages -- we ensure that we do *not* to require type information from packages when parsing specs.  This ensures that:
1. specs are more expressive than the current set of packages -- you can talk and reason about things that do not exist.
2. specs aren't tied to any particular version of spack -- if spack moves on, specs still make sense.

The consequence for variants is that we don't know what "type" a variant is until the spec is interpreted, e.g. when we do queries on specs.  To ask a question like `"+mpi" in Spec("hdf5")`, we need to interpret the values of variants, and right now we'll look at that and say "oh, `mpi` is set to something that looks like `"true"` or `"false"`.  We could do the same thing for `"on"` and `"off"`, but that means we really shouldn't have non-boolean variants that can have those values, or they can be interpreted the wrong way.

Currently, the `pmi` variant on `mpich` is the only one that would have this issue -- it can be `off`, `pmi`, `pmi2`, or `pmix`.  `off` would cause issues.  There are so far no variants with a possible value of `on` and no non-boolean variants with possible values of `true` or `false`, so we've mostly avoided this.

Thoughts?

**Comment by adamjstewart** [comment]
Honestly, I would be fine with dropping support for both `mpi=on` and `mpi=true` and only support `+mpi`, `-mpi`, and `~mpi`.

**Comment by markcmiller86** [comment]
When I originally submitted this, I think *my* biggest issue was the inconsistency in `spack info` output and not so much a myriad of ways of specifing what amounts  to *boolean* options. I don't see any value in supporting three different ways `+x`, `x=on`, `x=true` to do something. One is fine and even better if that *one way* is consistently parroted back from various commands such as `spack info`.
