### ISSUE TITLE
`spack.extends` best/intended practices

### ISSUE THREAD

**Issue by dlukes** [spack/spack#5559]
I'm currently trying to create a package with Python bindings, so I'm trying to figure out how the extension mechanism is supposed to work. To this end, I installed `py-six` as an "officially supported" package that extends Python (i.e. one that does the right thing™ from Spack's point of view), but after inspecting the result, I'm still a bit confused...

The documentation for the `spack.extends` directive says the following:

> Same as depends_on, but dependency is symlinked into parent prefix.
>
> This is for Python and other language modules where the module needs to be installed into the prefix of the Python installation. Spack handles this by installing modules into their own prefix, but allowing ONE module version to be symlinked into a parent Python install at a time.

Re: first paragraph -- the "parent prefix" is the prefix where the extending package is installed? Why should the dependency (the extendee, in this case Python) be symlinked into it? At any rate, at least with `py-six`, this symlinking doesn't happen:

```sh
$ tree /.../py-six-1.10.0-to3f3pygxpkyp6nfpjyt53xwyzzan3cn
/.../py-six-1.10.0-to3f3pygxpkyp6nfpjyt53xwyzzan3cn
└── lib
    └── python2.7
        └── site-packages
            ├── six-1.10.0-py2.7.egg-info
            ├── six.py
            └── six.pyc

3 directories, 3 files
```

Re: second paragraph -- this makes sense, but in my case, the symlink to `py-six` in the Python prefix doesn't get created:

```sh
$ find -L /.../python-2.7.14-qrvnbamzojaggitp2skibui3qikuzgsu -name six.py
# nothing
```

So I still need to put the `py-six` prefix on `PYTHONPATH` in order to be able to use it.

Everything clicks into place once I create a view which includes Python and the extending package (using hardlinks, because with symlinks, `sys.path` would contain the dereferenced paths into the relevant directories in the Python prefix instead of the paths in the view):

```sh
$ spack view hardlink test 'python@2.7.14%gcc@6.4.0' py-six
$ find test -name six.py
test/lib/python2.7/site-packages/six.py
$ ./test/bin/python
Python 2.7.14 (default, Sep 26 2017, 20:03:32)
[GCC 6.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>>
```

Is this the way extensions are supposed to work? Or am I missing something? If this is the way, the docstring of the `spack.extends` directive could use a little bit of clarification :)

**Comment by hartzell** [comment]
The documentation about [extends](http://spack.readthedocs.io/en/latest/packaging_guide.html?highlight=extends#extensions) and the following sub-section on activation/deactivation should help you figure this out.

Extensions are available two ways (three, if you count your `view` solution, though I haven't played with views in ages):

1. w/out activation you can use the package by setting various environment variables (you could use modulefiles to make this simple[r].  E.g. `module load py-six` (assuming you have all the modules bits set up).

2. with activation you get the package for free when you set up your environment to use the extended package (e.g.python).

The useful difference between symlinking the package (e.g. py-six) into the extendee (python) is that it is easily reversible.  Depending on your goals this may or may not be useful.  Once activated the extender (e.g. py-six) is available/inflicted on all users of that python.

If you don't activate a package, users can access multiple versions of the package from the same spack installation (e.g. `module load py-foobar/3.2` and `module load py-foobar/3.0` and etc...).

**Comment by dlukes** [comment]
This is perfect, thank you very much! This solves my immediate practical issue, but in light of this information, I would consider editing the `spack.extensd` docstring along the following lines:

> Same as depends_on, but allows installing into dependency's prefix tree.
>
> This is for Python and other language modules where the module needs to be installed into the prefix of the Python installation. Spack handles this by installing modules into their own prefix, but allowing ONE module version to be symlinked into a parent Python install at a time, using `spack activate`.

I'll leave this open in case it's something the Spack team would consider potentially useful; if not, feel free to close :)

**Comment by alalazo** [comment]
@dlukes Closing this, but feel free to submit a PR to improve the docstring.
