### ISSUE TITLE
OpenBlas doesn't need f77 it needs fc

### ISSUE THREAD

**Issue by woodard** [spack/spack#5591]
==> Installing openblas
==> Using cached archive: /home/ben/Work/spack/var/spack/cache/openblas/openblas-0.2.20.tar.gz
==> Already staged openblas-0.2.20-6rryp2gmzgl2vn36b4vfosfyi4ddkgcc in /home/ben/Work/spack/var/spack/stage/openblas-0.2.20-6rryp2gmzgl2vn36b4vfosfyi4ddkgcc
==> Already patched openblas
==> Building openblas [MakefilePackage]
==> Executing phase: 'edit'
==> Error: InstallError: OpenBLAS requires both C and Fortran compilers!
InstallError: InstallError: OpenBLAS requires both C and Fortran compilers!

/home/ben/Work/spack/var/spack/repos/builtin/packages/openblas/package.py:95, in check_compilers:
     4             # require both.
     5             if self.compiler.f77 is None:
     6                 raise InstallError(
  >> 7                     'OpenBLAS requires both C and Fortran compilers!'
     8                 )
     9             # Add support for OpenMP
     10            if (self.spec.satisfies('threads=openmp') and

See build log for details:
  /home/ben/Work/spack/var/spack/stage/openblas-0.2.20-6rryp2gmzgl2vn36b4vfosfyi4ddkgcc/OpenBLAS-0.2.20/spack-build.out

Changing /home/ben/Work/spack/var/spack/repos/builtin/packages/openblas/package.py from self.compiler.f77 to self.compiler.fc fixed the problem.

**Comment by pramodskumbhar** [comment]
@davydden : Is `f77 or fc` sufficient for OpenBLAS?

**Comment by davydden** [comment]
I think it’s a bug indeed: openblas needs FC not F77.
https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide
