### ISSUE TITLE
Issue with concretisation and external package preference ?

### ISSUE THREAD

**Issue by pramodskumbhar** [spack/spack#5651]
I have external openssl entry in `packages.yaml` as:

```
    openssl:
        paths:
            openssl@1.0.1e: /usr/local
```

In #5650 I changed node-js dependency of openssl to `1.0.2d:`. But now I am getting:

```
→ spack spec node-js
Input spec
--------------------------------
node-js

Normalized
--------------------------------
node-js
    ^pkg-config
    ^python@2.7:2.8
        ^bzip2
        ^ncurses
        ^openssl
            ^zlib
        ^readline
        ^sqlite

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    openssl@1.0.1e%clang@8.1.0-apple arch=darwin-sierra-x86_64


while trying to concretize the partial spec:

    node-js@7.1.0%clang@8.1.0-apple~debug~doc~icu4c+openssl+zlib arch=darwin-sierra-x86_64
        ^python@2.7.14%clang@8.1.0-apple+pic~shared~tk~ucs4 arch=darwin-sierra-x86_64
            ^bzip2@1.0.6%clang@8.1.0-apple+shared arch=darwin-sierra-x86_64
            ^ncurses@system%clang@8.1.0-apple~symlinks arch=darwin-sierra-x86_64
            ^openssl@1.0.1e%clang@8.1.0-apple arch=darwin-sierra-x86_64
            ^readline@7.0%clang@8.1.0-apple arch=darwin-sierra-x86_64
            ^sqlite@3.20.0%clang@8.1.0-apple arch=darwin-sierra-x86_64
            ^zlib@1.2.8%clang@8.1.0-apple+pic+shared arch=darwin-sierra-x86_64
```

Any suggestion?

**Comment by pramodskumbhar** [comment]
In the docs we explicitly suggest to use external openssl. Would be nice to have some workaround / fix.

**Comment by davydden** [comment]
i think it's the same as https://github.com/LLNL/spack/issues/5456, namely external package is chosen regardless, which is wrong. It should only be chosen if it satisfies the constraints.

**Comment by pramodskumbhar** [comment]
that was more about preference, I expect concretiser to at least pickup `minimum` version when `buildable: false`.

**Comment by scheibelp** [comment]
I would agree with @pramodskumbhar: I think this is more-related to https://github.com/LLNL/spack/issues/2632

In this case the `openssl@1.0.2d:` constraint is conditioned on a variant and is not applied until after the external is chosen. Improved concretization should handle this. In the meantime, you can bypass this issue with:

`spack spec node-js ^openssl@1.0.2d:`
