### ISSUE TITLE
Spack buildcaches don't function as documented

### ISSUE THREAD

**Issue by daveh86** [spack/spack#5676]
Have been trying to create a buildcache for portable environment and the whole buildcache functionality doesn't work as documented.

Started trying to package out boost with `spack buildcache create boost`
This fails with an error:
```==> Error: [Errno 2] No such file or directory: '<$SPACK_ROOT>/opt/spack/linux-sles12-x86_64/gcc-7.2.0/boost-1.63.0-lepwxyngcwiivbis2gvggxngkjhsjhd2'```

The error is correct as the directory `boost-1.63.0-lepwxyngcwiivbis2gvggxngkjhsjhd2` doesn't exist. Boost is installed at `boost-1.63.0-3l45zb24jjzwivmhnkgbgndoucpxohug` with a different hash.

Uninstalling and re-installing boost generates a version of boost with the expected hash. So First issue is that buildcache doesn't automatically detect installed versions based of installed hashes, it generates a hash assuming the hashes will always be the same. This is consistently an issue with every package I have installed locally, and if possible I wish to avoid recompiling everything to get the expected hashes.

Once I got the boost package installed in the buildcache, I attempted to install from it into a new location.  Adding the mirror worked, and I was able to see the contents of the buildcache with `spack buildcache list` things looked good until I ran into issues installing boost
```
spack buildcache install /wyl62l4
==> Finding buildcaches in /root/spack-mirror-2017-10-02/build_cache
==> Already downloaded /root/spack/var/spack/stage/build_cache/linux-sles12-x86_64-gcc-7.2.0-boost-1.63.0-lepwxyngcwiivbis2gvggxngkjhsjhd2.spec.yaml
==> Already downloaded /root/spack/var/spack/stage/build_cache/linux-sles12-x86_64-gcc-7.2.0-mpfr-3.1.5-sxoaffureu2zj4tjnrbbfzktl3vf32ax.spec.yaml
==> Already downloaded /root/spack/var/spack/stage/build_cache/linux-sles12-x86_64-gcc-7.2.0-gcc-7.2.0-wyl62l4lbawns6cjntruajnzatoecuvy.spec.yaml
==> Already downloaded /root/spack/var/spack/stage/build_cache/linux-sles12-x86_64-gcc-7.2.0-bzip2-1.0.6-ejldscwmg5ltjxhb4ll37bl7myybgobk.spec.yaml
==> Already downloaded /root/spack/var/spack/stage/build_cache/linux-sles12-x86_64-gcc-7.2.0-gmp-6.1.2-5wp563sq5oe7wxl4lel6y3kpanunq7mk.spec.yaml
==> Already downloaded /root/spack/var/spack/stage/build_cache/linux-sles12-x86_64-gcc-7.2.0-zlib-1.2.11-k42mytqk6ezpgtzrbh5iqmb6emp6goil.spec.yaml
==> Already downloaded /root/spack/var/spack/stage/build_cache/linux-sles12-x86_64-gcc-7.2.0-isl-0.18-r3s5yefuumrznazcclg2h5seqv6mezzd.spec.yaml
==> Already downloaded /root/spack/var/spack/stage/build_cache/linux-sles12-x86_64-gcc-7.2.0-mpc-1.0.3-dmiz2vxk276mz4m5l2tj35pe2qfjulk6.spec.yaml
==> Installing buildcache for dependency spec zlib@1.2.11%gcc@7.2.0+pic+shared arch=linux-sles12-x86_64
==> Fetching file:///root/spack-mirror-2017-10-02/build_cache/linux-sles12-x86_64/gcc-7.2.0/zlib-1.2.11/linux-sles12-x86_64-gcc-7.2.0-zlib-1.2.11-k42mytqk6ezpgtzrbh5iqmb6emp6goil.spack
curl: (37) Couldn't open file /root/spack-mirror-2017-10-02/build_cache/linux-sles12-x86_64/gcc-7.2.0/zlib-1.2.11/linux-sles12-x86_64-gcc-7.2.0-zlib-1.2.11-k42mytqk6ezpgtzrbh5iqmb6emp6goil.spack
==> Fetching from file:///root/spack-mirror-2017-10-02/build_cache/linux-sles12-x86_64/gcc-7.2.0/zlib-1.2.11/linux-sles12-x86_64-gcc-7.2.0-zlib-1.2.11-k42mytqk6ezpgtzrbh5iqmb6emp6goil.spack failed.
==> Error: Download of binary cache file for spec zlib@1.2.11%gcc@7.2.0+pic+shared arch=linux-sles12-x86_64  failed.
```

It appears that when the build caches are generated the full set of files needed for installing them isn't created.

**Comment by tgamblin** [comment]
@gartung @mathstuf

**Comment by gartung** [comment]
What command was used to create the buildcache? Were all of the files copied into the mirror path? Do all of the files have the correct permissions?

**Comment by daveh86** [comment]
To create the buildcaches I ran the following on my local (not the remote as above):
`spack buildcache create gcc@7.2.0`

This appeared to work initially and is now error-ing as below
```
$ spack buildcache create gcc@7.2.0
==> recursing dependencies
==> adding dependency gmp@6.1.2%gcc@7.2.0 arch=linux-sles12-x86_64
==> adding dependency isl@0.18%gcc@7.2.0 arch=linux-sles12-x86_64
==> adding dependency mpfr@3.1.5%gcc@7.2.0 patches=88dfefa6d39c9fd5a26a40d9bbc73df8da93f946c65c06038026261d78d919f5,dfd62a42a239c427bb44087b4a520edbcd65bae6ad1fbe07303c96ee8696afbd arch=linux-sles12-x86_64
==> adding dependency mpc@1.0.3%gcc@7.2.0 arch=linux-sles12-x86_64
==> adding dependency zlib@1.2.11%gcc@7.2.0+pic+shared arch=linux-sles12-x86_64
==> adding dependency gcc@7.2.0%gcc@7.2.0~binutils languages=all ~piclibs~strip arch=linux-sles12-x86_64
==> creating binary cache file for package mpfr@3.1.5%gcc@7.2.0 patches=88dfefa6d39c9fd5a26a40d9bbc73df8da93f946c65c06038026261d78d919f5,dfd62a42a239c427bb44087b4a520edbcd65bae6ad1fbe07303c96ee8696afbd arch=linux-sles12-x86_64
==> Error: [Errno 2] No such file or directory: '/home/david/spack/linux-sles12-x86_64/gcc-7.2.0/mpfr-3.1.5-rc3yad76366quoaladi75hs2pwjydmke'
```
Running `spack find` shows `mpfr` is installed
```
$ spack find mpfr
==> 1 installed packages.
-- linux-sles12-x86_64 / gcc@7.2.0 ------------------------------
mpfr@3.1.5
```
Running `spack locate` gives the following
```
$ spack location --install-dir mpfr
/home/david/spack/opt/spack/linux-sles12-x86_64/gcc-7.2.0/mpfr-3.1.5-sxoaffureu2zj4tjnrbbfzktl3vf32ax
```
Note the difference in hashes that buildcache is looking for compared with what is actually installed; `rc3yad76366quoaladi75hs2pwjydmke` vs `sxoaffureu2zj4tjnrbbfzktl3vf32ax`

**Comment by gartung** [comment]
Try spack find -l to get the package hash and then trun
spack buildcache create /hash
The problem might be that the default compiler changed so spack is calculating a different hash for the package.

**Comment by daveh86** [comment]
> The problem might be that the default compiler changed so spack is calculating a different hash for the package.
This has definitely happened along the way. I will test as suggested and get back to you ASAP.

**Comment by gartung** [comment]
Spack buildcache list 
will give the list of commands to install any packages it finds on the mirror. You should see that the install commands use the package hash.

**Comment by daveh86** [comment]
With the addition of a key to the build_cache and the use of the correct hashes this now looks to be working!

I believe this issue is now resolved, in terms of functionality but I think I will leverage this into a documentation change. Thanks @gartung

**Comment by tgamblin** [comment]
Should buildcache create use the matching semantics that spack uninstall used, instead of re-concretizing?

**Comment by gartung** [comment]
Sure. I kudged together what I could but I am sure you can come up with something better.

**Comment by gartung** [comment]
Found a bug making relative rpaths on linux. This fixes it.
https://github.com/LLNL/spack/pull/5726

**Comment by gartung** [comment]
Use the package hash when creating the buildcache because the concretized hash may have changed with package.py updates.
