### ISSUE TITLE
Support for Clear Linux

### ISSUE THREAD

**Issue by wscullin** [spack/spack#5679]
I had a PR ready to go, but figured There was some discussion to be had. Clear Linux increments their distro's version number with each bundle update. Right now a test image is running version 18240 and will likely be at 18270 by the time you read this. This means that the version detection in: lib/spack/spack/operating_systems/linux_distro.py isn't as useful as it is on a distro with slowly changing version numbers. They do supply an /etc/os-release file, but it trips up Spack as the id returned by distro.linux_distribution contains a string with dashes. There is a VERSION field in the /etc/os-release that doesn't seem to move quite as quickly, leading me to this abomination:

```diff
diff --git a/lib/spack/spack/operating_systems/linux_distro.py b/lib/spack/spack/operating_systems/linux_distro.py
index 7d1e3ca00..1ff309a0f 100644
--- a/lib/spack/spack/operating_systems/linux_distro.py
+++ b/lib/spack/spack/operating_systems/linux_distro.py
@@ -55,4 +55,13 @@ class LinuxDistro(OperatingSystem):
         else:
             version = version[0]
 
+        if 'clear' in distname:        
+            distname = 'clear'         
+            version = '1'
+            with open('/etc/os-release') as os_release:
+                for line in os_release:
+                    if line.startswith('VERSION='):
+                        version=line.lstrip('VERSION=')
+                        version=version.strip()
+
         super(LinuxDistro, self).__init__(distname, version)
```

does anyone have any better suggestions?

**Comment by tgamblin** [comment]
The OS versions are supposed to represent binary compatibility.  How quickly does a Clear Linux version lose binary compatibility with a prior version?  Does the version in `/etc/os-release` track that?

**Comment by wscullin** [comment]
@tgamblin So, I can say right now that from Clear 16000-ish to 19190, I haven't seen a break in binary compatibility. @fenrus75 mentioned using [abireport](https://github.com/clearlinux/abireport) but I think that's a wee-bit overkill as it hits all binary files and we'd like to have a single number that makes sense. For my local version, I'm doing a hash of the kernel major.minor + glibc major.minor and haven't hit an issue yet.

**Comment by fenrus75** [comment]
CL of course is trying extremely hard to be backwards compatible (e.g. binaries running on release X will keep running on release X+Y); compatibility in the other direction really exists nowhere; additive features/APIs happen all the time (in all distros tbh) so if something runs on version X, it's not guaranteed that it also runs on X - Y.

**Comment by adamjstewart** [comment]
Spack now uses the [distro](https://github.com/nir0s/distro) library to detect the OS version. Is this still an issue?

**Comment by becker33** [comment]
Spack now uses libc versions to model compatibility between specs from different operating systems, I believe that fixed this issue but reopen if necessary.
