### ISSUE TITLE
Make spack produce module files for all compilers it knows about

### ISSUE THREAD

**Issue by certik** [spack/spack#5684]
As an example, here are all the compilers that spack knows about on my machine:
```
$ spack compilers
==> Available compilers
-- gcc ubuntu16.04-x86_64 ---------------------------------------
gcc@7.2.0  gcc@6.3.0  gcc@6.1.1  gcc@5.4.0

-- intel ubuntu16.04-x86_64 ----------------------------------------
intel@16.0.2
```
But spack only generated module files for one compiler out of the five:
```
$ module available intel
$ module available gcc
---- /home/certik/repos/spack/share/spack/modules/linux-ubuntu16.04-x86_64 -----
gcc-7.2.0-gcc-6.3.0-sodkgqz
```
It would be nice if spack could generate module files for all four compilers, whether or not they were built by spack.

Currently spack only produces module files for compilers that it built itself. As an example, Intel compilers have a load script that I have to run by hand: `. $HOME/intel/bin/compilervars.sh intel64` when I want to use them. So I loaded them, then I did `spack compiler find`, that finds them, and then spack can use them without me having to load them using `compilervars.sh` again.

However, when I develop my own software, I load the spack built compilers using `module load`, but for Intel and other compilers I have to load them in a specific way. It would be nice if spack could (optionally) generate module files for all the compilers and then I can uniformly load them using `module load`.

**Comment by alalazo** [comment]
@certik You can add them as externals, and then 'install' them. That's what we do, for instance, for Intel on clusters.

**Comment by alalazo** [comment]
Was adding the compilers as externals working for you?

**Comment by alalazo** [comment]
Closing this, please reopen in case the solution above is not enough
