### ISSUE TITLE
julia 0.5.2 installation fails with "gtk-update-icon-cache: No theme index file"

### ISSUE THREAD

**Issue by samfux84** [spack/spack#5717]
Hi,

I am trying to install julia@0.5.2 with the following command:

`spack install julia@0.5.2+binutils+hdf5+mpi+plot+python+simd ^binutils@2.28 ^cmake@3.4.3+ncurses+openssl ^curl@7.53.1 ^m4@1.4.18 ^openssl@1.0.1e ^python@2.7.13+tk ^/fcexqkt ^py-pil@1.1.7 ^hdf5@1.10.1+cxx~debug+fortran~mpi+pic+shared+szip~threadsafe ^openmpi@2.1.0+cuda+java+sqlite3+thread_multiple+vt ^util-macros@1.19.1 ^xproto@7.0.29 ^libpthread-stubs@0.3 ^libx11@1.6.3 ^gettext@0.19.8.1+bzip2+curses+git+libunistring+libxml2+tar+xz ^libpng@1.6.27 ^freetype@2.7 %gcc@4.8.5 arch=linux-centos7-x86-64`

The compilation so far works fine, but in the installation step it always fails with:

```
gtk-update-icon-cache /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/julia-0.5.2-j4pgl2sm34cqnexwa7dc3uora4njanam/share/icons/hicolor/
gtk-update-icon-cache: No theme index file.
Makefile:332: recipe for target 'install' failed
make: [install] Error 1 (ignored)
```

This problem is discussed in

https://github.com/JuliaLang/julia/pull/8500

but they do not really provide a solution. They just say this happens if julia is not installed in the usual system location "/usr".

Did anybody else encounter this problem ? And if yes, how did you handle it ?

Best regards

Sam

**Comment by tgamblin** [comment]
@eschnett

**Comment by samfux84** [comment]
Problem is solved by the following patch:

```
--- julia/Makefile      2018-01-19 13:22:14.728845830 +0100
+++ julia/Makefile      2018-01-19 13:24:55.565567292 +0100
@@ -404,7 +404,7 @@
        mkdir -p $(DESTDIR)$(datarootdir)/icons/hicolor/scalable/apps/
        $(INSTALL_F) $(JULIAHOME)/contrib/julia.svg $(DESTDIR)$(datarootdir)/icons/hicolor/scalable/apps/
        -touch -c $(DESTDIR)$(datarootdir)/icons/hicolor/
-       -gtk-update-icon-cache $(DESTDIR)$(datarootdir)/icons/hicolor/
+       -gtk-update-icon-cache --ignore-theme-index $(DESTDIR)$(datarootdir)/icons/hicolor/
        mkdir -p $(DESTDIR)$(datarootdir)/applications/
        $(INSTALL_F) $(JULIAHOME)/contrib/julia.desktop $(DESTDIR)$(datarootdir)/applications/
        # Install appdata file
```

**Comment by alalazo** [comment]
@samfux84 Did you submit the patch upstream / as a package PR?

**Comment by samfux84** [comment]
@alalazo:  I did not submit the patch

**Comment by alalazo** [comment]
@samfux84 Do you have time to submit it upstream or as a patch to Spack? Otherwise I can try to do that (but I'll avoid taking credit, if possible, for a solution you provided :smile: )

**Comment by samfux84** [comment]
@alalazo It would be cool if you could do the PR. I can actually also not take any credit for the solution of this problem as it was proposed in an issue on the JuliaLang github repo.
