### ISSUE TITLE
perl fails to build as a dependency for HDF5

### ISSUE THREAD

**Issue by cpraveen** [spack/spack#5718]
I am doing ```spack install dealii``` on a Debian9 system. For some reason HDF5 is pulling in Perl even though I have same Perl in my Debian. But it fails like this
```
     1078  LD_LIBRARY_PATH=/tmp/praveen/spack-stage/spack-stage-nL5x6A/perl-5.24.1 ./miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>' || sh -c 'echo >&2 Failed to build miniperl.  Please run make minitest; exit 1'
     1079  Attempt to free unreferenced scalar: SV 0x55fdfd862290.
  >> 1080  Segmentation fault
     1081  Failed to build miniperl. Please run make minitest
     1082  makefile:381: recipe for target 'lib/buildcustomize.pl' failed
  >> 1083  make: *** [lib/buildcustomize.pl] Error 1
     1084  make: *** Waiting for unfinished jobs....
```
I have never seen spack trying to install perl as a dependency.
[spack-build.out.txt](https://github.com/LLNL/spack/files/1378557/spack-build.out.txt)

**Comment by davydden** [comment]
as a temporary workaround you can add to `~/.spack/packages.yaml`:
```
packages:
  intel-mkl:
    version: [5.24.1]
    paths:
      perl@5.24.1: /path/to/perl/prefix/in/your/os/
    buildable: False
```
to use externally provided `perl`.

**Comment by davydden** [comment]
you can also try 
```
packages:
  perl:
    version: [5.25.11]
```
to force building the latest available version of `perl`, which maybe have this bug fixed...

**Comment by alalazo** [comment]
Closing as not an issue anymore.
