### ISSUE TITLE
Is there a way to disable the IO fanciness so that pdb works?

### ISSUE THREAD

**Issue by hartzell** [spack/spack#5745]
I'm trying to chase down a bug and it's driving me, well, buggy.  Or perhaps batty.  Anyway....

I would *love* to drop

```python
  import pdb; pdb.set_trace()
```

just above where things go south and walk into it in the debugger, but all of the IO redirection and console magic seems to be getting in the way.  Is there a way to debug this?

As background, line 130-ish of `lib/spack/llnl/util/filesystem.py`

```python
          for line in fileinput.input(filename, inplace=True):
```

is throwing a Permission Denied exception on one of my clusters while installing perl (munging `Config.pm`).  Another nearly identical cluster works fine, as does a third slightly divergent cluster.

I've gotten this far sticking `tty.warn()` statements into the Spack code, but from here on in I'm fiddling with `/usr/bin/python` and am not a liberty to be dropping print statements there.

Otherwise my next step is to build another python (perhaps linuxbrew one) and see if a) I still have the problem and b) if I can `print()` my way into/out-of the problem there.

**Comment by hartzell** [comment]
One more observation, in case the problem tickles your fancy (or anything else), changing the call to:

```python
..., inplace=False):
```

let's it run to completion (though the editing doesn't do anything useful)

**Comment by hartzell** [comment]
Sweet.  I can:

```sh
mkdir doh
cp /usr/lib64/python2.7/fileinput.py doh
PYTHONPATH=$(pwd)/doh ./bin/spack -d install perl)
```

or perhaps "ick".....

**Comment by hartzell** [comment]
For those of you following along from home, it's dying here in `fileinput.py` (from python 2.7.5):

```python
  329                         fd = os.open(self._filename,
  330                                      os.O_CREAT | os.O_WRONLY | os.O_TRUNC,
  331                                      perm)
```

**Comment by hartzell** [comment]
Hmmm.  The mode of the original file is `0444`, so that bit of code is trying to open a file with both `os.O_WRONLY` and a mode that specifies it's only readable.

**Comment by hartzell** [comment]
Interestingly, this cluster recently moved from mounting these directories w/ NFSv3 to NFSv4.  Perl builds successfully on this system in `/tmp` (a local `xfs` filesystem).

The fix to my immediate problem is probably that the perl `Config.pm` munging code should grab the permission bits, make it writeable, then reset them.

I'd still be interested in learning if there's a way to run `spack` within the perl debugger.

**Comment by dlukes** [comment]
This would be great... It would significantly reduce the time I spend debugging packages if I could just put `import pdb; pdb.set_trace()` in a `package.py` file and explore the environment and arguments available during a phase that's causing me grief, instead of having to burrow through the documentation and repeatedly run the installation with `print(...)` sprinkled throughout the package definition.

**Comment by opadron** [comment]
So, after digging around the source, I think we already have a solution!

```
 $ spack help --all
```

Shows a not-so-widely documented option, `-D, --pdb` that seems to run spack regularly with the exception that you're dropped into a pdb session just before a little `"_main(...)"` string gets exec'd.

I tried throwing in `import pdb ; pdb.set_trace()` somewhere in zlib's package.py file.  Then, I ran `spack --pdb install zlib`, entered 'continue' in the session prompt and, sure enough, execution continued as you'd expect up until the `set_trace()` call in the package.py file, at which point I was able to debug the remaining execution as I pleased.

@hartzell, @dlukes, what do you guys think?  Have you tried using the `--pdb` option?

**Comment by dlukes** [comment]
@opadron Wow, awesome! Thank you so much! I knew about the `--pdb` option, but when I got dropped into the debugger prompt at a different location than where I put the `set_trace()` call, it didn't occur to me I might just try `continue` and see where that brings me 😅

I must get a better grip on Spack's internals one of these days, I thought package installation is run in a subprocess, so it kind of made sense to me that you can't debug across process boundaries. (Or maybe it *is* run in a subprocess, and `--pdb` is black magic...?)

At any rate, `--pdb` deserves publicity and perhaps a hint about the need to run `continue` to get to where you want.

**Comment by hartzell** [comment]
This works in some cases and not in others.  I'm working on a `package.py` that inherits from MakefilePackage and provides its own `edit` method.  Setting a tracepoint in that edit session makes everything hang.

I suspect that it's because the output is going to the log file (`lib/spack/spack/package.py:1527` or so...).
