### ISSUE TITLE
Change in compiler causes dependency calculations to miss installed packages and thus perform extra work

### ISSUE THREAD

**Issue by daveh86** [spack/spack#5775]
As I understand it, spack calculates build hashes based at least off the current default compiler (per a comment in #5676) this also seems to impact dependency calculations.

Example: 
I have boost 1.63.0 installed with a now out-of-date hash.
I run `spack install valgrind`, which depends on boost. This will try and install boost 1.65.1
Even if i modify the valgrind package to explicity `depend_on(boost@1.63.0)` this will still attempt to install a new version of `boost@1.63.0`, despite one already existing.

```
==> bzip2 is already installed in /home/david/spack/opt/spack/linux-sles12-x86_64/gcc-7.2.0/bzip2-1.0.6-ejldscwmg5ltjxhb4ll37bl7myybgobk
==> zlib is already installed in /home/david/spack/opt/spack/linux-sles12-x86_64/gcc-7.2.0/zlib-1.2.11-k42mytqk6ezpgtzrbh5iqmb6emp6goil
==> Installing boost
==> Using cached archive: /home/david/spack/var/spack/cache/boost/boost-1.63.0.tar.bz2
==> Staging archive:/home/david/spack/var/spack/stage/boost-1.63.0-akymp232kvg2bfgqwwnvbgpsbngwmja5/boost_1_63_0.tar.bz2
^C
```
And a `spack find -l boost`
```
-- linux-sles12-x86_64 / gcc@7.2.0 ------------------------------
lepwxyn boost@1.63.0
```

**Comment by alalazo** [comment]
That's a problem with concretization and repositories that change over time. More than the compiler (which seems to be the same, unless you modified its configuration), it might be the case that the `boost` package has been updated. 

Adding a new version, or a new variant, or a new dependency to a package are all modifications that will result in the current concretization algorithm making the choiche of rebuilding the package in question and everything that depends on it.

**Comment by daveh86** [comment]
I understand. Perhaps this means that there should be a way to add an override option into a build request which attempts to satisfy dependencies with whatever is on hand first. This behavior can be especially tedious when it means that you are doing several extra build steps to install/uninstall dependent libraries options needed for a given environment.

**Comment by alalazo** [comment]
Closing this as we currently have a lot of issues tracking this very same problem. Hopefully it will be solved as soon as the new concretizer will land in Spack. Feel free to reopen if you think there are points tracked only here and not elsewhere.
