### ISSUE TITLE
petsc@3.7.6 install fails with Intel compiler and Intel-mpi

### ISSUE THREAD

**Issue by ssergien** [spack/spack#5846]
```
*******************************************************************************
                    UNABLE to EXECUTE BINARIES for ./configure
-------------------------------------------------------------------------------
Cannot run executables created with FC. If this machine uses a batch system
to submit jobs you will need to configure using ./configure with the additional option  --with-batch.
 Otherwise there is problem with the compilers. Can you compile and run code with your compiler '/data/stas/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3.196/compilers_and_libraries/linux/mpi/intel64/bin/mpiifort'?
See http://www.mcs.anl.gov/petsc/documentation/faq.html#libimf
```
I installed  it manually with the same compilers and it worked ok.

**Comment by pramodskumbhar** [comment]
Could you try with dirty flag? (spack install --dirty ...)

**Comment by ssergien** [comment]
Same result.

**Comment by cnelson3** [comment]
I have the same issue @ssergien

**Comment by tgamblin** [comment]
@BarrySmith @balay: any ideas on this one?

**Comment by balay** [comment]
configure.log from the failed build would give us clues

My initial suspicion was missing LD_LIBRARY_PATH - but then --dirty should have fixed that..

**Comment by cnelson3** [comment]
Here are the configure.log, spack-build.out and spack-build.env for out installation attempt.

[configure.log.txt](https://github.com/spack/spack/files/1449805/configure.log.txt)
[spack-build.env.txt](https://github.com/spack/spack/files/1449806/spack-build.env.txt)
[spack-build.out.txt](https://github.com/spack/spack/files/1449807/spack-build.out.txt)

**Comment by balay** [comment]
attached configure.log.txt has:
```
ERROR while running executable: Could not execute "/tmp/petsc-iwEm3w/config.setCompilers/conftest":
/tmp/petsc-iwEm3w/config.setCompilers/conftest: error while loading shared libraries: libintlc.so.5: cannot open shared object file: No such file or directory
```

And I don't see LD_LIBRARY_PATH was available to configure
```
balay@asterix /home/balay/download-pine
$ grep LD_LIBRARY_PATH: configure.log.txt 
balay@asterix /home/balay/download-pine
$ 
```

Are you sure you've used `spack install --dirty` for this build?

What do you have for:
```
echo LD_LIBRARY_PATH
spack env petsc | grep LD_LIBRARY_PATH=
```

If not - can you retry with `spack install --dirty petsc`

BTW: spack now defaults to petsc-3.8.1 - and we recommend using the latest version

**Comment by cnelson3** [comment]
Hi @balay, 
The install results I posted were from a clean install.  I've just run a build with --dirty, and I get the same errors.  The new output files will be posted soon.

For info - I get the same (libintlc.so.5) errors for PetSc versions 3.6.4 and 3.7.6.

For us - this only happens for Intel and IntelMPI - if I use Intel and OpenMPI, PetSc builds perfectly through Spack.

Thanks for informing me of the update to PetSc 3.8.1 - unfortunately, I'm told that due to the continual changing nature of the PetSc API, moving our developers to the latest version isn't always possible.

**Comment by balay** [comment]
To confirm - spack (dirty) install of petsc with impi breaks - but regular (non-spack) install of petsc with impi works?

If so, it would be good to grab configure.log from both these builds and compare.

**Comment by ssergien** [comment]
[configure.log](https://github.com/spack/spack/files/1452434/configure.log) this is the manual install with Intel compilers 17.0.4 and Intel-mpi 2017.3.196
[spack-build.out.txt](https://github.com/spack/spack/files/1452497/spack-build.out.txt) this is the file from: 
```
$ spack install -v petsc@3.8.1+mpi+boost+mumps %intel@17.0.4 ^intel-mpi@2017.3 ^intel-mkl@2017.3.196
```
[spack-build.dirty.out.txt](https://github.com/spack/spack/files/1452501/spack-build.dirty.out.txt) this file is from:
```
spack install -v --dirty petsc@3.8.1+mpi+boost+mumps %intel@17.0.4 ^intel-mpi@2017.3 ^intel-mkl@2017.3.196
```
So behavior changed. I pulled the develop branch couple of times since I posted the issue and version is different. I will also try the same thing with petsc@3.7.6 and report.

**Comment by ssergien** [comment]
with petsc@3.7.6 it is the same as petsc@3.8.1 
spack install fails with:
```
*******************************************************************************
                    UNABLE to EXECUTE BINARIES for ./configure
-------------------------------------------------------------------------------
Cannot run executables created with FC. If this machine uses a batch system
to submit jobs you will need to configure using ./configure with the additional option  --with-batch.
 Otherwise there is problem with the compilers. Can you compile and run code with your compiler '/data/stas/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3.196/compilers_and_libraries/linux/mpi/intel64/bin/mpiifort'?
See http://www.mcs.anl.gov/petsc/documentation/faq.html#libimf
```
spack install --dirty fails with:
```
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
--with-hdf5-dir=/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-hzjjvx3iajr7fbhhpfob3zt3nzkosibc did not work
*******************************************************************************
```

**Comment by balay** [comment]
`spack install --dirty` failure is different - so configure.log from this failed build would be useful to identify the problem.

I suspect its due to missing zlib dependency - https://github.com/spack/spack/pull/6189 attempts to fix this.

However it would be strange for the standalone build  not require zlib but spack build to requiring it [when using the same hdf5 in both builds] - so this is just speculation.

again configure.log would provide correct info on this erorr.

**Comment by balay** [comment]
Ah - this is on LCRC/blues..

```
balay@blogin2^~ $ ls /soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl*
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl.a
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl_cpp.a
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl_cpp.la
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl_cpp.so
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl_cpp.so.100
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl_cpp.so.100.1.0
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl.la
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl.so
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl.so.100
/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-vzncl5hvkrdioypigebpug7uw3hbto5z/lib/libhdf5_hl.so.100.0.1
balay@blogin2^~ $ ls /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-hzjjvx3iajr7fbhhpfob3zt3nzkosibc/lib/libhdf5_hl*
ls: cannot access /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/hdf5-1.10.1-hzjjvx3iajr7fbhhpfob3zt3nzkosibc/lib/libhdf5_hl*: No such file or directory

```

So the working build was using `hdf5` built with `hl` - but the broken build is using one without hl.

petsc package should go through a cleanup to get as much [library] info from spack as possible - and not guess this on its own..

For now  you can try installing hdf5+hl and see if the problem goes away.

Or the following patch to petsc

```
diff --git a/config/BuildSystem/config/packages/hdf5.py b/config/BuildSystem/config/packages/hdf5.py
index ed29fe8b55..61e3774e7b 100644
--- a/config/BuildSystem/config/packages/hdf5.py
+++ b/config/BuildSystem/config/packages/hdf5.py
@@ -11,7 +11,7 @@ class Configure(config.package.GNUPackage):
 #   getpwuid from the test for ac_func in gethostname getpwuid getrusage lstat
     self.functions = ['H5T_init']
     self.includes  = ['hdf5.h']
-    self.liblist   = [['libhdf5_hl.a', 'libhdf5.a']]
+    self.liblist   = [['libhdf5_hl.a', 'libhdf5.a'], ['libhdf5.a']]
     self.complex          = 1
     self.hastests         = 1
     self.precisions       = ['single','double'];
```

**Comment by balay** [comment]
or perhaps the following change in spack will trigger hdf5+hl build - when PETSc is built [via spack]
```
diff --git a/var/spack/repos/builtin/packages/petsc/package.py b/var/spack/repos/builtin/packages/petsc/package.py
index 1262c47e3..59a23f326 100644
--- a/var/spack/repos/builtin/packages/petsc/package.py
+++ b/var/spack/repos/builtin/packages/petsc/package.py
@@ -115,7 +115,7 @@ class Petsc(Package):
     depends_on('metis@5:~int64+real64', when='+metis~int64+double')
     depends_on('metis@5:+int64', when='+metis+int64~double')
 
-    depends_on('hdf5+mpi', when='+hdf5+mpi')
+    depends_on('hdf5+mpi+hl', when='+hdf5+mpi')
     depends_on('zlib', when='^hdf5+mpi+zlib')
     depends_on('parmetis', when='+metis+mpi')
     # Hypre does not support complex numbers.
```

**Comment by cnelson3** [comment]
Hi All,
I just tried building PetSc 3.8.0 with HDF5 & hl, and I get the same error as before.
I've attached the "dirty" logs from my build (just hdf5, not hdf5+hl)
I'm thinking that there may be an issue with the intel-mpi package perhaps?
[configure-dirty.log.txt](https://github.com/spack/spack/files/1453482/configure-dirty.log.txt)
[spack-build-dirty.env.txt](https://github.com/spack/spack/files/1453484/spack-build-dirty.env.txt)
[spack-build-dirty.out.txt](https://github.com/spack/spack/files/1453485/spack-build-dirty.out.txt)

**Comment by balay** [comment]
> /tmp/petsc-YSjAyD/config.setCompilers/conftest: error while loading shared libraries: libintlc.so.5: cannot open shared object file: No such file or directory

Are you sure you used the --dirty flag for this build?  I don't see LD_LIBRARY_PATH in the attached configure-dirty.log

**Comment by cnelson3** [comment]
Hi @balay,
Yes, I built this with --dirty.  Just spent the last hour re-checking that I had compiled with --dirty, and yes, I had... I re-built it as well, resulting in the same error.

Curiously, the spack-bulid.env files are identical  - the LD_LIBRARY_PATH is set on line 53 of spack-build.env - _N.b._ this is true for other builds, not just PetSc.

**Comment by balay** [comment]
This is strange. I have no idea why LD_LIBRARY_PATH  would be available in spack-bulid.env - but disappear by the time petsc configure is run. Its not present in the configure.log you sent.

On my local build  with --dirty - I do see it.

```
balay@es^/sandbox/balay/spack/opt/spack/linux-ubuntu14.04-x86_64/intel-16.0.3/petsc-3.8.1-zvu5ng2xnjvvtm6f6nnw4ia6oeo26ile/lib/petsc/conf(xsdk-0.3.0=) $ grep ^LD_LIBRARY_PATH= configure.log
LD_LIBRARY_PATH=/soft/com/packages/intel/16/u3/lib/intel64:/soft/com/packages/intel/16/u3/mkl/lib/intel64:/soft/apps/packages/cuda-7.5/lib64:/soft/apps/packages/cuda-7.5/lib:/soft/com/packages/nag/6.1/lib:/soft/com/packages/absoft11.0/shlib64/
balay@es^/sandbox/balay/spack/opt/spack/linux-ubuntu14.04-x86_64/intel-16.0.3/petsc-3.8.1-zvu5ng2xnjvvtm6f6nnw4ia6oeo26ile/lib/petsc/conf(xsdk-0.3.0=) $ 
```
Also you've previously sent info on builds with hdf5 errors [without the corresponding configure.log files]. But for sure LD_LIBRARY_PATH was used in those builds - as it went past the LD_LIBRARY_PATH error.

So I don't understand why it now available on your current builds.

**Comment by balay** [comment]
Sorry If I'm mixing up issues/logs/responses from @cnelson3 @ssergien. 

@ssergien I see you are currently stuck at configure failure with hdf5. You can check the patch above which is now in https://github.com/spack/spack/pull/6189

@cnelson3 for some reason LD_LIBRARY_PATH is in spack-build-dirty.env.txt but not in configure-dirty.log.txt - and I don't know why.

Perhaps @tgamblin has suggestions on how to debug this. 

Until you get LD_LIBRARY_PATH available when  PETSc configure is run [and configure finds it - and logs in configure.log] - you will continue to have this error

**Comment by alalazo** [comment]
Closing as stale. Feel free to reopen if this is still relevant.
