### ISSUE TITLE
[lmod] global name 'dso_suffix' is not defined

### ISSUE THREAD

**Issue by svenevs** [spack/spack#5864]
### Problem

```console
$ spack module refresh --module-type lmod --delete-tree -y
==> Regenerating lmod module files
==> Warning: Could not write module file [/opt/spack/share/spack/lmod/linux-fedora25-x86_64/clang/3.9.0/opencv/3.3.0.lua]
==> Warning: 	--> global name 'dso_suffix' is not defined <--
==> Warning: Could not write module file [/opt/spack/share/spack/lmod/linux-fedora25-x86_64/clang/5.0.0/opencv/3.3.0.lua]
==> Warning: 	--> global name 'dso_suffix' is not defined <--
==> Warning: Could not write module file [/opt/spack/share/spack/lmod/linux-fedora25-x86_64/gcc/6.4.1/opencv/3.3.0.lua]
==> Warning: 	--> global name 'dso_suffix' is not defined <--
```

### Invalid but Functional Fix

```diff
--- a/var/spack/repos/builtin/packages/opencv/package.py
+++ b/var/spack/repos/builtin/packages/opencv/package.py
@@ -23,7 +23,7 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 ##############################################################################
 from spack import *
-
+from spack.build_environment import dso_suffix
```

It seems related to #1845, maybe `__all__` for `from spack import *` should just be modified to import that as well?  I don't really understand why it only happens with OpenCV though...

**Comment by alalazo** [comment]
@svenevs Your fix seems legit to me. `dso_suffix` is not imported as part of:
```python
from spack import *
```
but is used within the package. Do you have time to submit a PR?

**Comment by svenevs** [comment]
Well I guess the reason I was so confused was because although `dso_suffix` is used, this error only occurs with `lmod` generation.  I was installing with e.g., [`+png` which triggers the usage of `dso_suffix``](https://github.com/spack/spack/blob/05fa3026551fd1fc7895ea5cfaed001c2bb1af55/var/spack/repos/builtin/packages/opencv/package.py#L146-L154).  So I wasn't really sure what the `lmod` specific issue was...

**Comment by svenevs** [comment]
Like in other words, [since it was added to the build system](https://github.com/spack/spack/commit/c2d58d39dd40582f5b53ba6a0585f443645ab344) maybe there should (instead of adding it to the package itself) be a consistent import of this for `lmod`?

**Comment by alalazo** [comment]
> Like in other words, since it was added to the build system maybe there should (instead of adding it to the package itself) be a consistent import of this for lmod?

:+1: I linked two other issues that boil down to the same topic. Will try to provide a fix for this asap.

**Comment by svenevs** [comment]
:turkey: should be your focus right now :boom: :scream: :bangbang: :interrobang:

**Comment by alalazo** [comment]
> Will try to provide a fix for this asap.

*And then time goes by* :smile:

**Comment by svenevs** [comment]
LOL.  It's pretty minor, easy to fall of your radar :no_mouth:

**Comment by svenevs** [comment]
The rework of how `from spack import *` import magic fixed this (I believe).
