### ISSUE TITLE
Buildcache installed compilers cannot function correctly

### ISSUE THREAD

**Issue by daveh86** [spack/spack#5866]
This is a nasty gotcha for anyone looking to build a portable toolchain with a buildcache that includes a compiler. My specific case relates to GCC, but I can imagine other compilers could suffer from this.

When buildcache moves the compiler it walks through all the libraries and binaries and correctly resets their rpath to be the new install directory. However, there are a number of important files that are untouched, such as all of the `link against` or `.la` files and most importantly, the `lib/gcc/<architecture>/<compiler_version>/specs` file. These all contain the "old" path and need to be updated. 

For example, if you don't update the specs file then the "transported" GCC will add an incorrect `runpath` variable to every binary it compiles. This will mean that the linker will load the wrong library at execution time (loading the system, rather than the compiled) , which can lead to errors such as `GLIBCXX_3.4.22 not found` and potentially unexpected behavior.

The options I see going forward are to either block transport of applications that rely on the absolute pathing of their install prefix. Or to add a mechanism to list files which contain these paths and have them patched.

**Comment by gartung** [comment]
https://github.com/spack/spack/pull/6512 addresses the text relocation not working. This should help with the .la files not being changed.

**Comment by gartung** [comment]
I have found that relocation of compilers works as long as you don't use relative rpaths in creating the buildcache.
