### ISSUE TITLE
Error: AssertionError

### ISSUE THREAD

**Issue by certik** [spack/spack#5876]
Here is the full output:
```
$ spack install -j16 openmpi%intel@16.0.2 hypre@2.11.2%intel@16.0.2 ~shared yajl%intel@16.0.2 amrex@develop%intel@16.0.2 dims=2
==> openmpi is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openmpi-2.1.1-ywm4hkx6cyjqfxxwnsggbc3qaoi5ijax
==> openmpi@2.1.1 : marking the package explicit
==> Installing openblas
==> Using cached archive: /home/certik/repos/spack/var/spack/cache/openblas/openblas-0.2.20.tar.gz
==> Staging archive: /home/certik/repos/spack/var/spack/stage/openblas-0.2.20-ai7xadwhxplmf567tjdts44laxglw74a/v0.2.20.tar.gz
==> Created stage in /home/certik/repos/spack/var/spack/stage/openblas-0.2.20-ai7xadwhxplmf567tjdts44laxglw74a
==> Applied patch openblas_icc_openmp.patch
==> Applied patch openblas_icc_fortran.patch
==> Applied patch make.patch
==> Building openblas [MakefilePackage]
==> Executing phase: 'edit'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed openblas
  Fetch: 0.03s.  Build: 39m 3.69s.  Total: 39m 3.72s.
[+] /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openblas-0.2.20-ai7xadwhxplmf567tjdts44laxglw74a
==> libsigsegv is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/libsigsegv-2.11-zkzisdwphibghog63o4zhol57di6rrlg
==> m4 is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/m4-1.4.18-7dufldmzmvdnpoijdb6lqoyzi2aph44g
==> libtool is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/libtool-2.4.6-h3bpspvdgyfc5xhnmy7kbxmekqyutpdf
==> pkg-config is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/pkg-config-0.29.2-tkfiyn4pm2f7uled6z6ktkmmv7xfog7y
==> util-macros is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/util-macros-1.19.1-y3s7xvkrsd7pgjjtlm4qqzwswbtjui3b
==> libpciaccess is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/libpciaccess-0.13.5-yf2577f2imu7jdf25doy6krwvov6wydi
==> xz is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/xz-5.2.3-3k7sp3y2joy5gqakygyh26ma7fq4xw3t
==> zlib is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/zlib-1.2.11-whz3v7mejgeegpoiblv4vgkgv7dtaiqg
==> libxml2 is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/libxml2-2.9.4-j26m2sopxpelbb2vhdtbfdb7gdhczbl2
==> hwloc is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/hwloc-1.11.7-2ymnl3e3czf6hemzel7xwogxttxkkstl
==> openmpi is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openmpi-2.1.1-ywm4hkx6cyjqfxxwnsggbc3qaoi5ijax
==> Installing hypre
==> Error: AssertionError: 
AssertionError: AssertionError: 

/home/certik/repos/spack/lib/spack/spack/build_environment.py:580, in child_process:
     27    
     28                # build up some context from the offending package so we can
     29                # show that, too.
  >> 30                package_context = get_package_context(tb)
     31    
     32                build_log = None
     33                if hasattr(pkg, 'log_path'):
```
This looks like some bug in spack itself. At the very least the error message should be much clearer.

**Comment by certik** [comment]
And I am not able to reproduce it. I installed each package individually, without errors. And then the above command just works:
```
$ spack install -j16 openmpi%intel@16.0.2 hypre@2.11.2%intel@16.0.2 ~shared yajl%intel@16.0.2 amrex@develop%intel@16.0.2 dims=2
==> openmpi is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openmpi-2.1.1-ywm4hkx6cyjqfxxwnsggbc3qaoi5ijax
==> hypre is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/hypre-2.11.2-mg45ftz5dtegh5a5xxzg5xt3crez7erk
==> yajl is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/yajl-2.1.0-nlwhlwii5hbn3x4sqoexbrlfu445og5e
==> amrex is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/amrex-develop-vgs7jyjigfdgj2hcercnckzsklroftu5
```
But I am going to keep the issue open, since clearly there is a bug somewhere.

**Comment by davydden** [comment]
somewhat off-topic, but still:

> spack install -j16 openmpi%intel@16.0.2 hypre@2.11.2%intel@16.0.2 ~shared yajl%intel@16.0.2 amrex@develop%intel@16.0.2 dims=2

in spack you should not try installing dependencies one by one, just start form the root package you need and let Spack workout the rest. It is by accident that things seem to be the same for you (i.e. those `openmpi`, etc are actually going to be used in `amrex`). Otherwise, there is no guarantee (AFAIK) that whatever you type in a single `spack install` will be concretized all together. Have a look at this PR https://github.com/LLNL/spack/pull/4585 which might be closer how Hashdist works.

**Comment by certik** [comment]
I know --- I have this `packages` file:
```
$ cat ~/.spack/packages.yaml 
packages:
  openmpi:
    version: [2.1.1]
```
Which ensures a particular version of openmpi for all packages. I can omit `openmpi` from that line, but I have to keep all the other ones, since I need all those libraries to install my own software. I then use the following command to give me the `module load` lines:
```
$ spack module loads -m tcl openmpi%intel@16.0.2 hypre@2.11.2%intel@16.0.2 ~shared yajl%intel@16.0.2 amrex@develop%intel@16.0.2 dims=2
# amrex@develop%intel@16.0.2 dims=2 +mpi arch=linux-ubuntu16.04-x86_64 
module load amrex-develop-intel-16.0.2-vgs7jyj
# hypre@2.11.2%intel@16.0.2~int64+internal-superlu~shared arch=linux-ubuntu16.04-x86_64 
module load hypre-2.11.2-intel-16.0.2-mg45ftz
# openmpi@2.1.1%intel@16.0.2~cuda fabrics= ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-ubuntu16.04-x86_64 
module load openmpi-2.1.1-intel-16.0.2-ywm4hkx
# yajl@2.1.0%intel@16.0.2 build_type=RelWithDebInfo arch=linux-ubuntu16.04-x86_64 
module load yajl-2.1.0-intel-16.0.2-nlwhlwi
```
And I need to load the openmpi explicitly, otherwise things won't work. So for consistency, I use the same list of packages (including openmpi) for both `spack install` and `spack module loads`. Is there a better workflow that I could use? 

In Hashdist I just put all these packages + variants into a profile yaml file, then build it with `hit build` and load it with `hit load` and I am done.

**Comment by davydden** [comment]
> In Hashdist I just put all these packages + variants into a profile yaml file, then build it with hit build and load it with hit load and I am done.

did you check the link to the PR above?

**Comment by certik** [comment]
Yes I saw that. But since it's not merged yet, I assumed up until now people have used some other workflow.

**Comment by davydden** [comment]
> But since it's not merged yet, I assumed up until now people have used some other workflow.

sure, i just meant that this PR probably does something similar to what you want. Not sure about modules, though. 

As for 

> Is there a better workflow that I could use?

i don't know. For what I build, I only need to eventually do `spack load cmake` and do `spack location -i foo` to get prefix of a single package and I am done.

**Comment by davydden** [comment]
p.s. you know, the funny thing, i just got exactly the same error myself while trying to do `spack install foo bar baz` as a single command to build all I need 😄

**Comment by alalazo** [comment]
Anybody with a deterministic reproducer of this?

**Comment by pramodskumbhar** [comment]
I am not 100% sure but I think recently I have seen "get_package_context" related error when switching between my fork branch (which is bit old) and llnl develop branch. I typically remove .pyc and then it worked.

**Comment by acfisher** [comment]
I get a similar error install ncurses on the NERSC systems.  Maybe others can reproduce this:
[afisher@cori05 spack]$ spack install ncurses
==> Installing pkgconf
==> Fetching https://distfiles.dereferenced.org/pkgconf/pkgconf-1.3.10.tar.xz
######################################################################## 100.0%
==> Staging archive: /global/u1/a/afisher/spack/var/spack/stage/pkgconf-1.3.10-aqec4oruy24wsz6g2qd7lcyo5zr6qhlw/pkgconf-1.3.10.tar.xz
==> Created stage in /global/u1/a/afisher/spack/var/spack/stage/pkgconf-1.3.10-aqec4oruy24wsz6g2qd7lcyo5zr6qhlw
==> No patches needed for pkgconf
==> Building pkgconf [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed pkgconf
  Fetch: 0.81s.  Build: 9.39s.  Total: 10.20s.
[+] /global/u1/a/afisher/spack/opt/spack/cray-CNL-haswell/gcc-5.2.0/pkgconf-1.3.10-aqec4oruy24wsz6g2qd7lcyo5zr6qhlw
==> Installing ncurses
==> Error: SyntaxError: invalid syntax (<string>, line 425)
SyntaxError: SyntaxError: invalid syntax (<string>, line 425)

/global/u1/a/afisher/spack/lib/spack/spack/build_environment.py:680, in child_process:
     27
     28                # build up some context from the offending package so we can
     29                # show that, too.
  >> 30                package_context = get_package_context(tb)
     31
     32                build_log = None
     33                if hasattr(pkg, 'log_path'):

I tried getting rid of the pyc files to no effect.  Interestingly if I revert the last change to the ncurses package the problem goes away.

**Comment by pramodskumbhar** [comment]
Ok, I was wrong. The error for `.pyc` was different : 

```
$  spack install -v neurodamus@plasticity %gcc
==> zlib@1.2.8 : externally installed in /usr/local
==> zlib@1.2.8 : generating module file
==> Warning: Module file already exists : skipping creation
file : /Users/kumbhar/workarena/software/sources/spack/share/spack/dotkit/darwin-sierra-x86_64/zlib-1.2.8-gcc-4.9.4-uq53ezp.dk
spec : zlib@1.2.8%gcc@4.9.4+pic+shared arch=darwin-sierra-x86_64
==> zlib@1.2.8 : registering into DB
==> hdf5@1.8.17 : externally installed in /usr/local
==> hdf5@1.8.17 : generating module file
==> Warning: Module file already exists : skipping creation
file : /Users/kumbhar/workarena/software/sources/spack/share/spack/dotkit/darwin-sierra-x86_64/hdf5-1.8.17-gcc-4.9.4-u4d4dkx.dk
spec : hdf5@1.8.17%gcc@4.9.4+cxx~debug~fortran+mpi+pic+shared~szip~threadsafe arch=darwin-sierra-x86_64
==> hdf5@1.8.17 : registering into DB
==> flex@system : externally installed in /usr/local
==> flex@system : already registered in DB
==> python@3.6 : externally installed in /usr/local/opt/python3
==> python@3.6 : generating module file
==> Error: 'module' object has no attribute 'template_dirs'
```

I switched between upstream develop and my forked develop (which is bit old, before jinja stuff was added). Removing pyc solves above issue:

```
$ cd /Users/kumbhar/workarena/software/sources/spack/
 $ find . -name "*.pyc" -exec rm -f {} \;
$ spack install -v neurodamus@plasticity %gcc
.....
 => everything installing fine now...
....
```

**Comment by healther** [comment]
Can this issue be closed?

**Comment by alalazo** [comment]
Closing as stale.Feel free to reopen if this needs further investigation.
