### ISSUE TITLE
spack install: spec conflict error message is vague.

### ISSUE THREAD

**Issue by krafczyk** [spack/spack#6001]
I recently tried to install the `hoomd-blue` package on my arch machine. I got this error:

```
spack install hoomd-blue
==> Error: Conflicts in concretized spec "hoomd-blue@2.1.6%gcc@7.2.0 build_type=RelWithDebInfo +cuda~doc+mpi arch=linux-arch-x86_64 /ppp75ox"
```

How do I find out what is conflicting with what?

**Comment by scheibelp** [comment]
If you run `spack spec hoomd-blue` are there any messages about conflicts at the end of the output? For example:

```
==> Error: Conflicts in concretized spec "hoomd-blue@2.1.6%gcc@4.6.1 build_type=RelWithDebInfo +cuda~doc+mpi arch=linux-rhel6-x86_64 /e62rtl6"

List of matching conflicts for spec:

  (the full spec)
  ...

1. "%gcc@:4.6" conflicts with "hoomd-blue"
```

When I look at the `package.py` for `hoomd-blue` I notice the following `conflicts` directive:

```
conflicts('%gcc@6.0:')
```

**Comment by krafczyk** [comment]
Okay, you're right it's `gcc@7.2.0` which is conflicting based on the response form `spack spec`:

```
1. "%gcc@6.0:" conflicts with "hoomd-blue"
```

I wonder whether this kind of information could be incorporated into the Conflicts error.

**Comment by scheibelp** [comment]
I'm self-assigning this but giving it low priority because you can get more information about the conflict with `spack spec`

**Comment by healther** [comment]
@scheibelp could we put a message like "for further information use spack spec" as a stopgap measure, I ran into this a couple of times already and wasn't aware that ```spack spec``` gives different feedback than the error reported by spack install

**Comment by dyoungasc** [comment]
The confusing part about the conflict message is that it doesn't tell you if it wants a package version older than X, or newer than X
