### ISSUE TITLE
Add an option to install openmpi with ucx.

### ISSUE THREAD

**Issue by ChinouneMehdi** [spack/spack#6078]
I need to build openmpi with [ucx](https://github.com/openucx/ucx) since openshmem (in openmpi 3.0.0) requires it.
To build openmpi with ucx:
1- Build ucx
2- Configure openmpi with `--with-ucx=/path/to/ucx `

**Comment by ChinouneMehdi** [comment]
Hello! Hello!
Is someone there! Can you hear me!

**Comment by junghans** [comment]
You first have to package `ucx` in spack, see http://spack.readthedocs.io/en/latest/tutorial_packaging.html on how to get started.

**Comment by ChinouneMehdi** [comment]
One of the best things in the open source community is when you ask for a feature or report a bug they told you do it or fix it yourself.

**Comment by tgamblin** [comment]
@ChinouneMehdi: We'd gladly accept a PR for this feature!  Note that there is also a guide for [contributing to Spack](https://spack.readthedocs.io/en/latest/contribution_guide.html).

**Comment by ChinouneMehdi** [comment]
As I said before "I AM NOT A DEVELOPER!"
