### ISSUE TITLE
spack_{cc,cxx,etc} not expanded when creating module files.

### ISSUE THREAD

**Issue by underwoo** [spack/spack#6089]
While using spack to build packages and create module files (dotkit, tcl, and lmod), we found that it appears spack does not know what `spack_cc` is when creating the module files.  I appears to be related to packages that have `"CC=%s" % spack_cc` (or similar) in `def configure_args(self)`.

When spack attempts to create the module files for these packages, we get the following:

```
> spack module refresh -y -m lmod gdbm
==> Regenerating lmod module files
==> Warning: Could not write module file [/home/fms/opt/modules/linux-rhel7-x86_64/Core/gdbm/1.13.lua]
==> Warning:    --> global name 'spack_cc' is not defined <--
```

It appears, that although  `"CC=%s" % spack_cc` is expanded correctly during the configure step, that process is not occurring during the module file creation.  Or, is there something we need to do to get past this?

**Comment by alalazo** [comment]
Relates to #5864

**Comment by goxberry** [comment]
Has there been any progress on this issue? Moving the definition of `CC` in the `gdbm` package into a `setup_environment` method seems to fix the `lmod` issue, but I can't yet tell if flags are being propagated correctly, which seemed to be the reasoning behind #5893.

**Comment by alalazo** [comment]
Doesn't seem to be an issue anymore:
```console
$ spack module tcl refresh gdbm
==> You are about to regenerate tcl module files for:

-- linux-ubuntu18.04-x86_64 / gcc@8.2.0 -------------------------
gota243 gdbm@1.18.1

==> Do you want to proceed? [y/n] y
==> Regenerating tcl module files

$ spack module lmod refresh gdbm
==> You are about to regenerate lmod module files for:

-- linux-ubuntu18.04-x86_64 / gcc@8.2.0 -------------------------
gota243 gdbm@1.18.1

==> Do you want to proceed? [y/n] y
==> Regenerating lmod module files
```
