### ISSUE TITLE
spack load python does not work

### ISSUE THREAD

**Issue by robinson96** [spack/spack#6126]
On the current develop branch, spack load python does not work after a fresh install. 

bin/spack install python
==> Installing bzip2
==> Fetching http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
######################################################################## 100.0%
==> Staging archive: /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/bzip2-1.0.6-ocokiv4gyfgsngehfu2xclts4sh3az73/bzip2-1.0.6.tar.gz
==> Created stage in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/bzip2-1.0.6-ocokiv4gyfgsngehfu2xclts4sh3az73
==> Ran patch() for bzip2
==> Building bzip2 [Package]
==> Executing phase: 'install'
==> Successfully installed bzip2
  Fetch: 2.71s.  Build: 3.22s.  Total: 5.94s.
[+] /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/bzip2-1.0.6-ocokiv4gyfgsngehfu2xclts4sh3az73
==> Installing pkg-config
==> Fetching http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
######################################################################## 100.0%
==> Staging archive: /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/pkg-config-0.29.2-avgqntfh3yfb7dolax6hs7hzcvo2zusz/pkg-config-0.29.2.tar.gz
==> Created stage in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/pkg-config-0.29.2-avgqntfh3yfb7dolax6hs7hzcvo2zusz
==> No patches needed for pkg-config
==> Building pkg-config [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed pkg-config
  Fetch: 5.15s.  Build: 55.93s.  Total: 1m 1.08s.
[+] /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/pkg-config-0.29.2-avgqntfh3yfb7dolax6hs7hzcvo2zusz
==> Installing ncurses
==> Fetching http://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.0.tar.gz
######################################################################## 100.0%
==> Staging archive: /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/ncurses-6.0-2slr4wmx2yojobvn63hsk6y7azqclmvj/ncurses-6.0.tar.gz
==> Created stage in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/ncurses-6.0-2slr4wmx2yojobvn63hsk6y7azqclmvj
==> Applied patch sed_pgi.patch
==> Building ncurses [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed ncurses
  Fetch: 2.57s.  Build: 2m 10.43s.  Total: 2m 13.00s.
[+] /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/ncurses-6.0-2slr4wmx2yojobvn63hsk6y7azqclmvj
==> Installing zlib
==> Fetching http://zlib.net/fossils/zlib-1.2.11.tar.gz
######################################################################## 100.0%
==> Staging archive: /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/zlib-1.2.11-3r4cfkmx3wwfqeof4bc244yduu2mz4ur/zlib-1.2.11.tar.gz
==> Created stage in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/zlib-1.2.11-3r4cfkmx3wwfqeof4bc244yduu2mz4ur
==> No patches needed for zlib
==> Building zlib [Package]
==> Executing phase: 'install'
==> Successfully installed zlib
  Fetch: 0.90s.  Build: 2.40s.  Total: 3.30s.
[+] /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/zlib-1.2.11-3r4cfkmx3wwfqeof4bc244yduu2mz4ur
==> Installing openssl
==> Fetching http://www.openssl.org/source/openssl-1.0.2k.tar.gz
######################################################################## 100.0%
==> Staging archive: /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/openssl-1.0.2k-5c5zih4crsssf45tirewadgyw235mpf3/openssl-1.0.2k.tar.gz
==> Created stage in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/openssl-1.0.2k-5c5zih4crsssf45tirewadgyw235mpf3
==> No patches needed for openssl
==> Building openssl [Package]
==> Executing phase: 'install'
==> Successfully installed openssl
  Fetch: 5.01s.  Build: 3m 10.64s.  Total: 3m 15.66s.
[+] /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/openssl-1.0.2k-5c5zih4crsssf45tirewadgyw235mpf3
==> Installing readline
==> Fetching https://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz
######################################################################## 100.0%
==> Staging archive: /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/readline-7.0-idpg37y33iqfrzt5xgbcrli2ar5vwm32/readline-7.0.tar.gz
==> Created stage in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/readline-7.0-idpg37y33iqfrzt5xgbcrli2ar5vwm32
==> No patches needed for readline
==> Building readline [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed readline
  Fetch: 1.80s.  Build: 12.21s.  Total: 14.02s.
[+] /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/readline-7.0-idpg37y33iqfrzt5xgbcrli2ar5vwm32
==> Installing sqlite
==> Fetching https://www.sqlite.org/2017/sqlite-autoconf-3200000.tar.gz
######################################################################## 100.0%
==> Staging archive: /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/sqlite-3.20.0-4ik45j35m6f7evw2vdusiye7msrc72wg/sqlite-autoconf-3200000.tar.gz
==> Created stage in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/sqlite-3.20.0-4ik45j35m6f7evw2vdusiye7msrc72wg
==> No patches needed for sqlite
==> Building sqlite [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed sqlite
  Fetch: 2.03s.  Build: 16.20s.  Total: 18.23s.
[+] /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/sqlite-3.20.0-4ik45j35m6f7evw2vdusiye7msrc72wg
==> Installing python
==> Fetching http://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz
######################################################################## 100.0%
==> Staging archive: /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/python-2.7.14-ce6nsfnjn7orncxwtbkzaqrydqqzen5x/Python-2.7.14.tgz
==> Created stage in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/var/spack/stage/python-2.7.14-ce6nsfnjn7orncxwtbkzaqrydqqzen5x
==> Applied patch ncurses.patch
==> Ran patch() for python
==> Building python [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Warning: Patched overlong shebang in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.14-ce6nsfnjn7orncxwtbkzaqrydqqzen5x/bin/python2-config
==> Warning: Patched overlong shebang in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.14-ce6nsfnjn7orncxwtbkzaqrydqqzen5x/bin/pydoc
==> Warning: Patched overlong shebang in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.14-ce6nsfnjn7orncxwtbkzaqrydqqzen5x/bin/idle
==> Warning: Patched overlong shebang in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.14-ce6nsfnjn7orncxwtbkzaqrydqqzen5x/bin/2to3
==> Warning: Patched overlong shebang in /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.14-ce6nsfnjn7orncxwtbkzaqrydqqzen5x/bin/smtpd.py
==> Successfully installed python
  Fetch: 11.66s.  Build: 2m 47.07s.  Total: 2m 58.73s.
[+] /usr/workspace/wsrzc/probinso/mlworkflow/spack-master/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.14-ce6nsfnjn7orncxwtbkzaqrydqqzen5x
rzgenie2{probinso}183: ./bin/sp
spack*        spack-python* 
rzgenie2{probinso}183: ./bin/spack load python
==> Warning: /g/g18/probinso/.spack/compilers.yaml in out of date compilers format. Moved to /g/g18/probinso/.spack/_old_compilers.yaml. Spack automatically generate a compilers config file 
==> Error: 'module' object has no attribute 'print_help'

rzgenie2{probinso}184: ./bin/spack use python
==> Error: 'module' object has no attribute 'print_help'

**Comment by scheibelp** [comment]
You must source one of the environment setup scripts in `spack/share`, either `setup-env.sh` or `setup-env.csh` (depending on your shell), to properly define `spack use` and `spack load`. When that hasn't been done they are supposed to invoke a placeholder help function. At the moment that appears to be dangling.

More info about the environment setup script is at http://spack.readthedocs.io/en/latest/getting_started.html?highlight=setup-env#add-spack-to-the-shell

**Comment by scheibelp** [comment]
Also, once you source one of the shell integration scripts, you have to invoke spack as a shell command rather than as an executable:

`> spack use python`

vs.

`> ./bin/spack use python`

I have updated the placeholder message in #6126 to mention that.
