### ISSUE TITLE
Error with external package that depends_on('mpi'): No spec with name mpi in ...

### ISSUE THREAD

**Issue by baip** [spack/spack#6145]
Trying to build a package that depends on elpa. I was able to build elpa manually and then I added it to `packages.yaml`:

~~~yaml
elpa:
  paths:
    elpa@2016.05.004: /share/apps/elpa-2016.05.004
  buildable: False
~~~

Now when I do `spack install`, I get this error:

    ==> elpa@2016.05.004 : externally installed in /share/apps/elpa-2016.05.004
    ==> elpa@2016.05.004 : generating module file
    ==> Error: 'No spec with name mpi in elpa@2016.05.004%intel@2018.0.128.6.4.0 cflags="-fPIC -O3 -xHost" cxxflags="-fPIC -O3 -xHost" fflags="-fPIC -O3 -xHost" ~openmp arch=linux-centos6-x86_64'

Are there any other settings I should add to `packages.yaml`?

**Comment by scheibelp** [comment]
Would you be able to post the output if you run the same command but add the `-d` option? For example:

`spack -d install...`

Thanks!

**Comment by baip** [comment]
Here is the output with `spack -d install`:

> ==> Reading config file /share/apps/spack/etc/spack/defaults/packages.yaml                                                                             
==> Reading config file /share/apps/spack/etc/spack/packages.yaml                                                                                      
==> READ LOCK: /home/soft/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]                                                          
==> READ LOCK: /home/soft/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]                                                           
==> READ LOCK: /home/soft/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]                                                           
==> Reading config file /share/apps/spack/etc/spack/compilers.yaml                                                                                     
==> Reading config file /home/soft/.spack/linux/compilers.yaml                                                                                      
==> WRITE LOCK: /share/apps/spack/opt/spack/.spack-db/prefix_lock[2526723389451006899:1] [Acquiring]                                                   
==> WRITE LOCK: /share/apps/spack/opt/spack/.spack-db/prefix_lock[2526723389451006899:1] [Acquired]                                                    
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]                                                                             
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Acquired]                                                                              
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Released]                                                                              
==> WRITE LOCK: /share/apps/spack/opt/spack/.spack-db/prefix_lock[2526723389451006899:1] [Released]                                                    
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/prefix_lock[2526723389451006899:1] [Acquiring]
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/prefix_lock[2526723389451006899:1] [Acquired]
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/prefix_lock[2526723389451006899:1] [Released]
==> Installing cp2k dependencies
==> elpa@2016.05.004 : externally installed in /share/apps/elpa-2016.05.004
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> elpa@2016.05.004 : generating module file
==> SKIP: shebang filtering [external package]
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /share/apps/spack/opt/spack/.spack-db/lock[0:0] [Released]
==>     WRITE: elpa@2016.05.004%intel@2018.0.128.6.4.0~openmp arch=linux-centos6-x86_64 /h7ponpu [/share/apps/spack/share/spack/modules/linux-centos6-x86_64/elpa-2016.05.004-intel-2018.0.128.6.4.0-h7ponpu]
Traceback (most recent call last):
  File "/share/apps/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/share/apps/spack/lib/spack/spack/main.py", line 547, in main
    return _main(command, parser, args, unknown)
  File "/share/apps/spack/lib/spack/spack/main.py", line 439, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/share/apps/spack/lib/spack/spack/main.py", line 355, in _invoke_spack_command
    return_val = command(parser, args)
  File "/share/apps/spack/lib/spack/spack/cmd/install.py", line 461, in install
    install_spec(args, kwargs, spec)
  File "/share/apps/spack/lib/spack/spack/cmd/install.py", line 358, in install_spec
    package.do_install(**kwargs)
  File "/share/apps/spack/lib/spack/spack/package.py", line 1363, in do_install
    **kwargs)
  File "/share/apps/spack/lib/spack/spack/package.py", line 1329, in do_install
    return self._process_external_package(explicit)
  File "/share/apps/spack/lib/spack/spack/package.py", line 1258, in _process_external_package
    spack.hooks.post_install(self.spec)
  File "/share/apps/spack/lib/spack/spack/hooks/__init__.py", line 73, in __call__
    hook(*args, **kwargs)
  File "/share/apps/spack/lib/spack/spack/hooks/module_file_generation.py", line 48, in <lambda>
    post_install = lambda spec: _for_each_enabled(spec, 'write')
  File "/share/apps/spack/lib/spack/spack/hooks/module_file_generation.py", line 41, in _for_each_enabled
    getattr(generator, method_name)()
  File "/share/apps/spack/lib/spack/spack/modules/common.py", line 697, in write
    context = self.context.to_dict()
  File "/share/apps/spack/lib/spack/spack/tengine.py", line 85, in to_dict
    d = [(name, getattr(self, name)) for name in self.context_properties]
  File "/share/apps/spack/lib/spack/spack/modules/common.py", line 552, in environment_modifications
    self.spec.package.setup_environment(_, env)
  File "/share/apps/spack/var/spack/repos/builtin/packages/elpa/package.py", line 70, in setup_environment
    spack_env.set('CC', spec['mpi'].mpicc)
  File "/share/apps/spack/lib/spack/spack/spec.py", line 2742, in __getitem__
    raise KeyError("No spec with name %s in %s" % (name, self))
KeyError: 'No spec with name mpi in elpa@2016.05.004%intel@2018.0.128.6.4.0 cflags="-fPIC -O3 -xHost" cxxflags="-fPIC -O3 -xHost" fflags="-fPIC -O3 -xHost" ~openmp arch=linux-centos6-x86_64'

**Comment by scheibelp** [comment]
It appears that the `elpa` package.py definition attempts to refer to the `mpi` dependency regardless of whether it is external. External packages don't record their dependencies which generates the reference error here. This would likely affect any case where a `package.py` definition refers to a dependency unconditionally and that dependency is installed as an external.

I'll have to think on this and a fix will likely be delayed for a couple weeks. In the meantime conditionally accessing `mpi` from `elpa` would avoid the issue.

**Comment by alalazo** [comment]
I agree with https://github.com/spack/spack/issues/6145#issuecomment-343034226 This is a known limitation of our current model for externals that trim dependencies of the external node. As such I think it shouldn't be considered a bug. Whenever we'll improve the model for externals to account for dependencies this behavior will change.
