### ISSUE TITLE
spack reorders cflags specified in compilers.yaml making them invalid

### ISSUE THREAD

**Issue by balay** [spack/spack#6154]
```
bash-4.2$ grep cflags ~/.spack/linux/compilers.yaml
      cflags: -O3 -fp-model fast -xMIC-AVX512
bash-4.2$ spack env numactl |grep CFLAGS
CFLAGS=-O3 fast -xMIC-AVX512 -fp-model
bash-4.2$ icc -O3 -fp-model fast -xMIC-AVX512 ~/petsc/src/benchmarks/sizeof.c  && echo sucess!
sucess!
bash-4.2$ icc -O3 fast -xMIC-AVX512 -fp-model ~/petsc/src/benchmarks/sizeof.c && echo sucess!
icc: error #10236: File not found:  'fast'
icc: command line warning #10159: invalid argument for option '-fp-model'
icc: command line error: no files specified; for help type "icc -help"
bash-4.2$ 

```

**Comment by scheibelp** [comment]
From what I can tell (e.g. looking at https://software.intel.com/en-us/node/522979) you can't set options like

`-fp-model=fast`

and must set `-fp-model fast`.

@balay I'm assuming that reordering the flags is acceptable provided that `-fp-model fast` is "kept together" and in that order. So the following should work:

`-fp-model fast -O3 -xMIC-AVX512`
`-xMIC-AVX512 -O3 -fp-model fast`

**Comment by balay** [comment]
On Tue, 7 Nov 2017, scheibelp wrote:

> From what I can tell (e.g. looking at https://software.intel.com/en-us/node/522979) you can't set options like
> 
> `-fp-model=fast`
> 
> and must set `-fp-model fast`.
> 
> @balay I'm assuming that reordering the flags is acceptable provided that `-fp-model fast` is "kept together" and in that order.

Perhaps this is true - but I fear spack wouldn't want to know about all possible cflags/fflags etc combinations for all compilers. So I think a simpler solution is to not reorder or split user provided flags.

But perhaps there is a good reason for spack to attempt to reorder flags..

> So the following should work:
> 
> `-fp-model fast -O3 -xMIC-AVX512`
> `-xMIC-AVX512 -O3 -fp-model fast`

Are you refering to the above working in terms of output from spack i.e from `spack env` or input to spack - in terms of setting the options in the above order?

Ok - I tried the second case of setting cflags in compilers.yaml to the above order - that doesn't work..

**Comment by scheibelp** [comment]
> Ok - I tried the second case of setting cflags in compilers.yaml to the above order - that doesn't work.

Sorry I didn't mean to imply that you should be able to set the `cflags` entry in `compilers.yaml` such that it would work in Spack. I just meant that a compiler invocation like

`icc -fp-model fast -O3 -xMIC-AVX512 ~/petsc/src/benchmarks/sizeof.c`

would be just as good as

`icc -xMIC-AVX512 -O3 -fp-model fast ~/petsc/src/benchmarks/sizeof.c`

In other words, the order of `-O3` and `-fp-model fast` doesn't matter.

> I think a simpler solution is to not reorder or split user provided flags.

That may be a better solution. For now at https://github.com/spack/spack/pull/6169 the flag and value are kept together even when separated by a space (to be clear it doesn't specifically target the `-fp-model` flag, it just looks for cases where a flag and value are separated by a space). If you have the opportunity, does that PR resolve the issue for you?

**Comment by balay** [comment]
On Tue, 7 Nov 2017, scheibelp wrote:

> In other words, the order of `-O3` and `-fp-model fast` doesn't matter.

Perhaps in this case it doesn't matter - but I think it matters for some compilers.

I don't remember the context or compiler - but some support something like:

-Ofast might enable a bunch of optimizations like optA, optB, optC etc. So one could do:

`-Ofast -disable-optA -disable-optD` - i.e all Ofast options except optA, optD are enabled.

However reordering of the above could result in:

`-disable-optA -disable-optD -Ofast` this is equivalent to `-disable-optA -disable-optD -enable-optA -enable-optB -enable-optC` etc. i.e -enable-optA (from -Ofast) would override a previous  -disable-optA option.

> > I think a simpler solution is to not reorder or split user provided flags.
> 
> That may be a better solution. For now at https://github.com/spack/spack/pull/6169 the flag and value are kept together even when separated by a space (to be clear it doesn't specifically target the `-fp-model` flag, it just looks for cases where a flag and value are separated by a space). If you have the opportunity, does that PR resolve the issue for you?

Yes - in this case it preserves `-fp-model fast` but reorderds the others. So it does work.

```
-bash-4.2$ grep cflags ~/.spack/linux/compilers.yaml
      cflags:  "-O3 -fp-model fast -xMIC-AVX512"
-bash-4.2$ spack env pkg-config |grep CFLAGS
CFLAGS=-xMIC-AVX512 -O3 -fp-model fast
-bash-4.2$
