### ISSUE TITLE
Appending LDFLAGS to MakefilePackage

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [spack/spack#6155]
Hi

I am trying to add a new package which has a broken MakeFile.  ```LDFLAGS``` in the file must be modified before it can be compiled.  The developers have [yet to merge the fix](https://github.com/vcflib/vcflib/pull/205) yet into their project so I want to do it here in Spack.

I have tried this which does not work:

```
def setup_environment(self, spack_env, run_env):
    spack_env.append_flags('LDFLAGS', '-llzma')
    spack_env.append_flags('LDFLAGS', '-lbz2')
```

From [Packaging Guide](https://github.com/spack/spack/blob/04a4ac68d5320f02f30c4d24ff62a8322ea84dc0/lib/spack/docs/packaging_guide.rst) this does not work either:

```
def ldflags_flag_handler(self, env, flag_val):
    env.append_flags('-llzma')
    env.append_flags('-lbz2')

```

Thanks for the guidance!

**Comment by alalazo** [comment]
In general you can use `filter_file` for these kind of things + some regexes. As it appears the PR was accepted, I am closing this. Feel free to reopen if you need further help (or ask on slack :smile: ).
