### ISSUE TITLE
Central repository of spack configurations

### ISSUE THREAD

**Issue by skosukhin** [spack/spack#6172]
One of the things that I like about Spack is that it allows users to upgrade existing software stacks on different supercomputers with minimal help from system administrators. For example, a scientist got access (and computational resources) to a supercomputer (e.g one of the [PRACE](http://www.prace-ri.eu/prace-resources/) machines) she hasn't worked with before. The problem she has now is to find out which software is already installed, which compilers are available, and how to install everything that is required for the numerical experiments. Spack gives answers only to the third question and partially to the second one (in generel, Spack can't detect compilers that become available via environment modules).

My suggestion is that we organize a repository (maybe a separate git repository inside Spack organization) with configurations for particular sites: packages.yaml to describe what is already installed and compilers.yaml to tell which modules to load and additional environment variables to set. Later we could probably introduce a feature, so Spack would use corresponding configurations depending on `hostname` and some additional heuristics.

What do you think about the idea? Do you think if it's OK to make the information about installed software open?

**Comment by davydden** [comment]
i like the idea about having a central database of specific configuration examples for Spack. I think this would also help others to adapt Spack. 

Even without listing all packages, just basic MPI configuration (`packages.yaml`) and compilers (`compilers.yaml`) would good to have. Something like

```
<site>/packages.yaml
<site>/compilers.yaml
```

To make it easier to edit, one can also put it in a WiKi page(s).

**Comment by tgamblin** [comment]
I definitely think it's worth starting the repo to get the knowledge in one place.  Obviously it's up to the specific sites whether they want this information public, though, so I think it would be good to ask before contributing.

I think once we have more common configurations, it might be easier to see how best to support detecting this stuff in the core.

**Comment by alalazo** [comment]
I like the idea a lot. That will give us more insight on which externals are present at various sites, and how they are laid out on the different machines. Probably we can tune externals behavior a lot better with that knowledge. :100:

**Comment by svenevs** [comment]
If you plan on having the site configs be things people are reading README's for, it may be useful to show what the different setups look like with graphs (only high level, although I love `spack graph -d`, ... it's quite verbose).  Gravizo is my favorite, if you don't care about the label (or want to pay, but then you have to camo everything)

<p align="center">
    <img alt="Alt text" src="https://g.gravizo.com/svg?digraph%20G%20%7B%0A%20%20%20%20system%20%5Bshape%3Dbox%5D%3B%0A%20%20%20%20system%20-%3E%20compilers_system%3B%0A%20%20%20%20compilers_system%20%5Blabel%3D%22compilers%22%5D%3B%0A%20%20%20%20gcc_system%20%5Blabel%3D%22gcc%404.9.2%22%5D%3B%0A%20%20%20%20compilers_system%20-%3E%20gcc_system%3B%0A%20%20%20%20clang_system%20%5Blabel%3D%22clang%403.3.0%22%5D%3B%0A%20%20%20%20compilers_system%20-%3E%20clang_system%3B%0A%20%20%20%20%0A%20%20%20%20spack_1%20%5Bshape%3Dbox%5D%3B%0A%20%20%20%20compilers_spack_1%20%5Blabel%3D%22compilers%22%5D%3B%0A%20%20%20%20spack_1%20-%3E%20compilers_spack_1%3B%0A%20%20%20%20gcc_spack_1%20%5Blabel%3D%22gcc%22%5D%3B%0A%20%20%20%20compilers_spack_1%20-%3E%20gcc_spack_1%3B%0A%20%20%20%20gcc_spack_1_641%20%5Blabel%3D%226.4.1%22%5D%3B%0A%20%20%20%20gcc_spack_1%20-%3E%20gcc_spack_1_641%3B%0A%20%20%20%20gcc_spack_1_720%20%5Blabel%3D%227.2.0%22%5D%3B%0A%20%20%20%20gcc_spack_1%20-%3E%20gcc_spack_1_720%3B%0A%20%20%20%20%0A%20%20%20%20intel_spack_1%20%5Blabel%3D%22intel%22%5D%3B%0A%20%20%20%20compilers_spack_1%20-%3E%20intel_spack_1%3B%0A%20%20%20%20intel_spack_1_1800%20%5Blabel%3D%2218.0.0%22%5D%3B%0A%20%20%20%20intel_spack_1%20-%3E%20intel_spack_1_1800%3B%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20mpi_spack_1%20%5Blabel%3D%22mpi%22%5D%3B%0A%20%20%20%20spack_1%20-%3E%20mpi_spack_1%3B%0A%20%20%20%20intel_mpi_spack_1%20%5Blabel%3D%22intel%22%5D%3B%0A%20%20%20%20mpi_spack_1%20-%3E%20intel_mpi_spack_1%3B%0A%20%20%20%20intel_spack_1_1800%20-%3E%20intel_mpi_spack_1%20%5Bdir%3D%22back%22%5D%3B%0A%20%20%20%20%7Brank%20%3D%20same%3B%20intel_spack_1%3B%20intel_mpi_spack_1%3B%7D%0A%20%20%20%20%0A%20%20%20%20open_mpi_spack_1%20%5Blabel%3D%22OpenMPI%22%5D%3B%0A%20%20%20%20mpi_spack_1%20-%3E%20open_mpi_spack_1%3B%0A%7D">
</p>

Only if you're feeling adventurous, but it's not too bad.  I typically just write the graph online [here](https://dreampuf.github.io/GraphvizOnline/).  I didn't style the above dot graph at all, but you can.  I made a gist a while ago explaining how to [embed gravizo with direct graphs](https://gist.github.com/svenevs/ce05761128e240e27883e3372ccd4ecd).

Just thought I'd mention it's a neat resource that may be helpful in showing core setup tools available :smile:

**Comment by adamjstewart** [comment]
This now exists: https://github.com/spack/spack-configs
