### ISSUE TITLE
codecov commit status is missing

### ISSUE THREAD

**Issue by alalazo** [spack/spack#6173]
Since we moved repository we started missing the commit status from [codecov.io](https://docs.codecov.io/docs/commit-status). 

As far as I can tell we are still uploading the data correctly, and getting the coverage reports for both [develop](https://codecov.io/gh/spack/spack) and [PRs](https://codecov.io/gh/spack/spack/pulls), the only thing that seems to be missing is the commit status report on the PR page. I checked briefly the configuration we have, and it seems in order to me, so I am not sure where could be the problem.

**Comment by alalazo** [comment]
@scheibelp @tgamblin Can you do something about this?

**Comment by tgamblin** [comment]
I *believe* I fixed this by going to codecov and clicking "install codecov" for the Spack organization.  Let's see if we get statuses.  Codecov needed read access to most things, and read/write access to commit statuses and PRs.

**Comment by alalazo** [comment]
Confirmed it works -> #6417

**Comment by alalazo** [comment]
I think we have a regression on this, see for instance #6814 (or any of the PRs in the last couple of days)

**Comment by adamjstewart** [comment]
I was just about to report this. This is affecting #6809 as well.

**Comment by adamjstewart** [comment]
I'm seeing Codecov reports again.
