### ISSUE TITLE
Ubuntu 16.04, spack installed in /opt/spack, can not load modules

### ISSUE THREAD

**Issue by alexmyczko** [spack/spack#6195]
I am able to spack install hdf5, however I am not able to load any of the installed modules.
Do I need to configure spack? Does it need some special software, I know about environment-modules (https://packages.debian.org/search?keywords=environment-modules)...

me@somehost:~$ spack -V
0.10.0
me@somehost:~$ spack find
==> 12 installed packages.
-- linux-ubuntu16.04-x86_64 / gcc@5.4.0 -------------------------
hdf5@1.10.1   libpciaccess@0.13.5  libtool@2.4.6  m4@1.4.18      pkg-config@0.29.2   xz@5.2.3
hwloc@1.11.8  libsigsegv@2.11      libxml2@2.9.4  openmpi@3.0.0  util-macros@1.19.1  zlib@1.2.11
me@somehost:~$ spack load hdf5@1.10.1
spack:72: command not found: module

**Comment by tgamblin** [comment]
You do need a module system for `spack load` to work, but you can install one pretty easily, courtesy of @krafczyk:

```
$ spack bootstrap
$ . $spack_prefix/share/spack/setup_env.sh
```

**Comment by tgamblin** [comment]
FWIW, the plan is also to add virtual environments, which would require no special setup, but that is a work in progress.
