### ISSUE TITLE
spack load with absolute path: module error

### ISSUE THREAD

**Issue by ax3l** [spack/spack#6196]
### Preparation
```bash
. share/spack/setup-env.sh
```

### Issue

Loading a module via
```bash
spack load zlib
```

works, but if one adds the absolute path to the spack executable, it fails with:
```bash
$(pwd)/bin/spack load zlib
==> Error: 'module' object has no attribute 'print_help'
```

ccing @alalazo

**Comment by tgamblin** [comment]
It's not possible to fix the fact that this doesn't do what `spack load` does, as `spack load` is a shell function.  It should really fail with a better error message, though.

**Comment by ax3l** [comment]
Ah yes, the joy of shell functions. I always forget that :D

**Comment by ajitup73** [comment]
ajitup@plasma01:~/src/spack/bin> pwd
/home/ajitup/src/spack/bin
ajitup@plasma01:~/src/spack/bin> spack load gcc@5.4.0
==> Error: 'module' object has no attribute 'print_help'
ajitup@plasma01:~/src/spack/bin>

**Comment by ajitup73** [comment]
`ajitup@plasma01:~/src/spack/bin> pwd
/home/ajitup/src/spack/bin
ajitup@plasma01:~/src/spack/bin> spack load gcc@5.4.0
==> Error: 'module' object has no attribute 'print_help'
ajitup@plasma01:~/src/spack/bin> `

**Comment by tgamblin** [comment]
closing -- reopen if @scheibelp's comment doesn't help :)

**Comment by ax3l** [comment]
@scheibelp wonderful notification now, thanks! Super useful!
