### ISSUE TITLE
spack on NFS

### ISSUE THREAD

**Issue by mileschen360** [spack/spack#6197]
I installed spack on my home directory which is on a NFS. The NFS is shared by several HPC clusters. When I install packages on a cluster, it turns out it can be used by another cluster which has different OS version, eg, CentOS6 vs. CentOS7 in my case.

I have no clues how to deal with it. Can someone give me a hint or point me to the documentation?

By the way, the error messages are:
> ==> Error: No compilers found for operating system centos6 and target x86_64.
> If previous installations have succeeded, the operating system may have been updated.
> Compilers are defined for the following operating systems and targets:
>         centos7-x86_64

**Comment by tgamblin** [comment]
Spack should work fine on NFS. But it will build different versions of packages for the different operating systems.

Is there a specific problem you’re having?

**Comment by mileschen360** [comment]
From the message, it looks like spack cannot find compilers. But I did have compilers in PATH.

**Comment by mileschen360** [comment]
How does spack find the OS version of the compiler?

**Comment by mileschen360** [comment]
I think I need to ask spack to search for compilers again when I switch to another cluster, even though spack will find the same compiler.

**Comment by tgamblin** [comment]
That’s true — we separate compilers by operating system, though we should probably do a search like this automatically.
