### ISSUE TITLE
Compiler cannot find OpenMP

### ISSUE THREAD

**Issue by deOliveira-R** [spack/spack#6198]
This issue seems related to #5800 .

I'm on Mac OS. I installed clang 5.0.0 with spack and tried to install a package that depends on OpenMP with clang 5, such as kripke ( spack install kripke -mpi %clang@5.0.0 ). CMake fails to find the OpenMP C flag and exits with an error. The log is attached.

I bumped into this when trying to compile a package.py that I made and got this error, then tried a standard package to confirm. This issue seems like would affect any package using the CMake build system that uses the find_package(OpenMP) functionality to set up the compiler flags, such as:

find_package(OpenMP)
if(OPENMP_FOUND)
    set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS})
endif()

[spack-build.txt](https://github.com/spack/spack/files/1454353/spack-build.txt)

The package compiles outside of spack by loading the spack modules it depends on and building normally. Is this related to the compile wrappers?

**Comment by tgamblin** [comment]
Does this work outside of Spack?

**Comment by deOliveira-R** [comment]
Yes.

If I do a module load to add dependencies to the environment (in particular to have access to clang 5.0.0 with openmp that I compiled with spack) and compile manually in a build folder, it works normally and correctly detects the openmp C and CXX flag (and version 3.1).

If I try to compile with spack (spack install <package> %clang@5.0.0 ), cmake ends with an error:

-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) (found version "1.0")
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) (found version "1.0").

**Comment by alalazo** [comment]
Closing as stale. Feel free to reopen if this is still relevant.
