### ISSUE TITLE
Stale Package Situation

### ISSUE THREAD

**Issue by alfredo-gimenez** [spack/spack#6228]
If you do the following:

1. Install package, hash=abc
2. Package definition changes, new hash=def
3. Install new package
4. Delete new package directory (because it can't be distinguished from the old package spec)
5. Spack reindex

You get a confusing situation. I did this with `py-py` by adding a dummy dependency to change the spec:

```
(catalyst159):src$ spack find -L py-py
==> 1 installed packages.
-- linux-rhel7-x86_64 / gcc@4.9.3 -------------------------------
qmzwh2lqvftyhr3z6j6webxb2hkuwf64 py-py@1.4.33
```

```
(catalyst159):src$ spack load py-py
(catalyst159):src$ echo $PYTHONPATH
/g/g0/gimenez1/local/src/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-py-1.4.33-qmzwh2lqvftyhr3z6j6webxb2hkuwf64/lib/python2.7/site-packages
```

```
(catalyst159):src$ spack activate py-py
==> Error: Spec mb536tnj6ldwujml4flrzdm5jasxf46e not found in /g/g0/gimenez1/local/src/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-py-1.4.33-mb536tnj6ldwujml4flrzdm5jasxf46e
```

```
(catalyst159):src$ spack uninstall py-py
==> The following packages will be uninstalled:

-- linux-rhel7-x86_64 / gcc@4.9.3 -------------------------------
qmzwh2l py-py@1.4.33%gcc

==> Do you want to proceed? [y/N] y
==> Error: Spec mb536tnj6ldwujml4flrzdm5jasxf46e not found in /g/g0/gimenez1/local/src/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-py-1.4.33-mb536tnj6ldwujml4flrzdm5jasxf46e
```

```
(catalyst159):src$ spack install py-py
==> py-py is already installed in /g/g0/gimenez1/local/src/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-py-1.4.33-qmzwh2lqvftyhr3z6j6webxb2hkuwf64
```

Possible solution: add the hash as an optional spec parameter, e.g.  

```
spack activate py-py hash=qmzwh2lqvftyhr3z6j6webxb2hkuwf64

```

This should only work for resolving existing packages, i.e. not for installations, since that would require a reverse hash function to resolve... So `find`, `activate`, `load/use`, `uninstall`.

**Comment by scheibelp** [comment]
> Possible solution: add the hash as an optional spec parameter, e.g.
> `spack activate py-py hash=qmzwh2lqvftyhr3z6j6webxb2hkuwf64`

`spack activate` and most commands that accept a spec should be able to accept a hash, which is specified like:

`spack activate /qmzwh2l`

I'm assuming that was the hash for py-py. Also note you don't need to specify the full hash.

I'll get a chance to read through this more-thoroughly tomorrow - for now I'm just responding to that specific line.

**Comment by alfredo-gimenez** [comment]
Oh, I didn't realize that was possible, that's great actually. I'll keep the issue open since there seems to be a mismatch between what `spack find` is finding and what `spack activate` and `spack uninstall` are resolving.

**Comment by scheibelp** [comment]
I am able to go through the procedure outlined in https://github.com/spack/spack/issues/6228#issue-272414450 without running into the issue mentioned here. To make sure: are you using the latest Spack develop branch?

I can get an error message like the one mentioned above with the following procedure:

1. install an extension and activate it
1. manually delete the extension and reindex
1. attempt to activate the extension

I don't think there needs to be a conflicting hash. If you use `spack uninstall` it recognizes that the extension should be deactivated (whereas `reindex` does not). I'm not sure if there's a way to handle this cleanly (one of the disadvantages of writing into the original python prefix). There is currently support for views which links python and extensions into a separate prefix, and this issue would not come up.

**Comment by alfredo-gimenez** [comment]
Ah ok, I must have used activate in between the steps I outlined above. I tried again and the problem only occurs when you use `activate` and then manually delete the extension, as you said. It gets worse when you change the hash as well, since you can have a different hash activated than the current package hash, which is what I had caused earlier.

Maybe `reindex` should delete broken symlinks in the python prefix?

This also adds to my excitement for views :)

**Comment by adamjstewart** [comment]
Spack now knows how to reuse packages that are already installed, even if the spec is not an exact match or patches have been added/removed.
