### ISSUE TITLE
Failed to run `spack versions pgi`

### ISSUE THREAD

**Issue by weijianwen** [spack/spack#6234]
I want to check available versions of PGI compiler but ran into a problem when trying `spack versions pgi`. This issue can be reproduced on the latest commit (ac7f5a1af) with CentOS 7 and Mac.

```
$ bin/spack versions pgi
==> Error: <class 'spack.pkg.builtin.pgi.Pgi'>
```

**Comment by scheibelp** [comment]
The `pgi` package appears to be somewhat different from the norm in that you have to download it yourself and add it to a Spack mirror. Although the package has a `homepage`, this is not used for finding versions, and the typical URLs that would be searched (e.g. a`url` attribute on the package, or a URL associated with one of the versions in the `package.py` file) are not available.

The error message could definitely be clearer

**Comment by weijianwen** [comment]
I see. Since `version`s are listed in `pgi/package.py`, I wonder whether I can list the versions in a convenience way.

**Comment by scheibelp** [comment]
If you don't require any special formatting, the `spack info pgi` command includes the versions in the `package.py` along with all other properties of the package.

**Comment by weijianwen** [comment]
Thank you. This approach works quite well.
