### ISSUE TITLE
pkg-configu-0.29.2 fails with gcc/4.9.3

### ISSUE THREAD

**Issue by keitat** [spack/spack#6246]
On a linux machine  (3.10.0-693.2.2.el7.x86_64),  I am seeing a following error when building pkg-config.

==> '/home/knteran/spack/var/spack/stage/pkg-config-0.29.2-avgqntfh3yfb7dolax6hs7hzcvo2zusz/pkg-config-0.29.2/configure' '--prefix=/home/knteran/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/pkg-config-0.29.2-avgqntfh3yfb7dolax6hs7hzcvo2zusz' '--enable-shared' '--with-internal-glib'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: error: source directory already configured; run "make distclean" there first

**Comment by scheibelp** [comment]
The error message suggests you had a prior partially-completed install. You can run `spack install --restage pkg-config` to override that.

**Comment by keitat** [comment]
It is working fine.  Thanks.
