### ISSUE TITLE
Problem using `site_packages_dir` in package subclass

### ISSUE THREAD

**Issue by cyrush** [spack/spack#6261]
For testing -- I am inheriting existing package and making some tweaks. By inheriting the existing package, I  pick up all the depends, variants, extends etc, which is what I am after.

But I have one puzzle to solve to make this work. 

In the install of my subclass, I want to call a method in the base class that uses `site_packages_dir`
(the base class package extends python) however I cannot access `site_packages_dir` in the method defined in the base class. 

```
==> Error: NameError: global name 'site_packages_dir' is not defined
NameError: NameError: global name 'site_packages_dir' is not defined

 spack/var/spack/repos/builtin/packages/conduit/package.py:262, in create_host_config:
     92                # install module to standard style site packages dir
     93                # so we can support spack activate
     94                cfg.write(cmake_cache_entry("PYTHON_MODULE_INSTALL_PREFIX",
  >> 95                                            site_packages_dir))
     96            else:
     97                cfg.write(cmake_cache_entry("ENABLE_PYTHON", "OFF"))
     98    

```

I *can* access `site_packages_dir` is in my subclass,  and it works find when I directly install the base class, but not if I call the base class method from my subclass.

Given that `site_packages_dir` magically appears when you extend python, this probably some meta programming puzzle.

I tried several black magic python tricks (injecting things into various namespaces) but I couldn't grain ground.

**Comment by scheibelp** [comment]
I'll have a chance to look at this tomorrow (11/14)

**Comment by scheibelp** [comment]
The module variable `site_packages_dir` is set by `python` in `setup_dependent_package` (invoked by `build_environment.setup_package`. It only sets this module variable for the module of the package being installed, and does not set it for the superclass.

I think it may be possible to allow the superclass to access the same module variable if `build_environment.setup_package` could check for superclasses and invoke `setup_dependent_package` on them as well.

**Comment by cyrush** [comment]
@scheibelp thanks for the context, I know understand the mechanics. I'll poke around and see if I can get `setup_dependent_package` called on all superclasses.

**Comment by cyrush** [comment]
I tried several combos of modifying `build_environment.py:setup_package`  into call `setup_dependent_package` on lists from `pkg.__class__.__bases__` and toyed with using `parent_class_modules`.  But I couldn't get `site_packages_dir` to stick in the base class. 

Given the complexity here -- I am leaning towards a simple answer for my case:

Change the base class to not use `site_packages_dir`, but to generate the site-packages subdir path myself.

**Comment by adamjstewart** [comment]
@cyrush you should be able to use:
```python
import inspect
inspect.getmodule(self).site_packages_dir
```
in the base class. That's what the `SIPPackage` base class does.
