### ISSUE TITLE
Problem with HDF5 installation

### ISSUE THREAD

**Issue by vikramsg** [spack/spack#6263]
I was trying to install Visit, but got some errors that pointed to HDF5. When I try to install HDF5 I get the following error

```
Fetching https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz 
curl: (22) The requested URL returned error: 403 Forbidden 
Fetching from https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz failed.
Can not find version 1.10.1 in url_list
Error: FetchError: All fetchers failed for hdf5-1.10.1-ttqv45gskffsguej7rtggppd6iqmfb73

>> 28            self.stage.fetch(mirror_only) 
```

I tried to open the above links and it gave me the same error in the browser. How can I fix this?

**Comment by junghans** [comment]
HDF5's FTP Server is down!

**Comment by vikramsg** [comment]
Is there some way of forcing spack to use a downloaded tar ball instead of the link?

**Comment by tgamblin** [comment]
@vikramsg: yes, you can put the tarball in `var/spack/cache/<pkgname>/` within your spack prefix.  e.g.:

```
var/spack/cache/hdf5/hdf5-1.8.18.tar.gz
```

**Comment by tgamblin** [comment]
`var/spack/cache` is a [mirror](https://spack.readthedocs.io/en/latest/mirrors.html) that Spack maintains to cache all the downloads.

**Comment by junghans** [comment]
Use the magic of google: https://www.google.com/search?q=intitle%3A%22index+of%22+%22hdf5-1.8.18.tar.gz%22

**Comment by baberlevi** [comment]
@junghans google comment inspired me to  search for version control repos. Found this:
https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse

Seems to have all the versions tagged and be current

**Comment by tgamblin** [comment]
This is fixed.  The HDF5 guys fixed a permissions error in their FTP script.  They're working to automate their infrastructure more; this was apparently a glitch in the new setup. cc: @boegel
