### ISSUE TITLE
incorrect use of multi-line statement in directives.py

### ISSUE THREAD

**Issue by mwkrentel** [spack/spack#6299]
There are a couple places in lib/spack/spack/directives.py that
(incorrectly) try to concatenate string literals across multiple
lines, but the first line is not escaped or inside a scope.  As a
result, python treats the statement as a single line, and half of the
error message goes missing.

For example, in directives.py:

523     # Check if the path is relative
524     if os.path.isabs(destination):
525         message = 'The destination keyword of a resource directive '
526         'can\'t be an absolute path.\n'
527         message += "\tdestination : '{dest}\n'".format(dest=destination)
528         raise RuntimeError(message)

536     if test_path not in normalized_destination:
537         message = "The destination folder of a resource must fall "
538         "within the main package stage directory.\n"
539         message += "\tdestination : '{dest}'\n".format(dest=destination)
540         raise RuntimeError(message)

A simple way to trigger the problem is to set destination="/tmp" (an
illegal value) in package.py for package lua and then try to install it.

$ ./spack install lua  
==> Error: The destination keyword of a resource directive  destination : '/tmp
'

A simple fix is to put the two string literals inside a scope (or else
escape the first line).

  message = ('The destination keyword of a resource directive '
      'can\'t be an absolute path.\n')

Btw, the close quote for '{dest}' is misplaced in line 527, it should
come before \n, as in line 539.

--Mark

**Comment by scheibelp** [comment]
Thanks for reporting this!
