### ISSUE TITLE
Time for setup_env.sh

### ISSUE THREAD

**Issue by ax3l** [spack/spack#6302]
Do we know why `. spack/share/spack/setup-env.sh` takes so long?

I would like to use it in some of my `.profile` scripts but the init time for a login/new terminal/etc. is with 4-5 sec a bit too heavy.

**Comment by alalazo** [comment]
In these three lines:

https://github.com/spack/spack/blob/05fa3026551fd1fc7895ea5cfaed001c2bb1af55/share/spack/setup-env.sh#L239-L241

we start the python interpreter, which may take a while. Timing the commands from shell:
```
$ time spack-python -c 'print(spack.architecture.sys_type())'
linux-ubuntu14.04-x86_64

real	0m0.296s
user	0m0.240s
sys	0m0.044s

$ time spack-python -c "print(spack.util.path.canonicalize_path(spack.config.get_config('config').get('module_roots', {}).get('dotkit')))"
/home/mculpo/PycharmProjects/spack/share/spack/dotkit

real	0m0.309s
user	0m0.252s
sys	0m0.044s

$ time spack-python -c "print(spack.util.path.canonicalize_path(spack.config.get_config('config').get('module_roots', {}).get('tcl')))"
/home/mculpo/PycharmProjects/spack/share/spack/modules

real	0m0.308s
user	0m0.252s
sys	0m0.044s
```
they seem to take roughly 1 sec. on my machine out of:
```
$ time source share/spack/setup-env.sh 

real	0m1.230s
user	0m0.976s
sys	0m0.196s
```

**Comment by ax3l** [comment]
Thanks a lot!

Hm, it's a bit faster now with me (roughly 2.5x the timings you report) but seems to be a FS issue then.

I will report back if I see it again since I know where to look now, thanks a lot!
