### ISSUE TITLE
Spack 'bootstrap' fails to load on multi-architecture setups

### ISSUE THREAD

**Issue by modwizcode** [spack/spack#6305]
This is probably somewhat related to https://github.com/spack/spack/issues/6245, however this applies to when having used `spack bootstrap` to setup environment-modules as a local user. 

I think this is a general issue in that `spack location` doesn't seem to automatically identify the architecture by default as well. (although this is more of a feature request)

The `spack bootstrap` command fails to recognize that the packages are missing for the secondary architectures, and even when I have installed the package manually for the correct architecture, it fails to select the correct path for the installed package when loading the environment in the shell.

I haven't had time to determine if it is silently failing to load the x86 package on a powerpc system, but I'm getting `module: command not found` errors rather than architecture errors so I suspect it is not loading at all.

**Comment by junghans** [comment]
@tgamblin @scheibelp ping

**Comment by alalazo** [comment]
Outdated. The `spack bootstrap` command has been removed a long time ago and then repurposed in `v0.17`
