### ISSUE TITLE
Spec String of a None Multi Variant

### ISSUE THREAD

**Issue by ax3l** [spack/spack#6314]
I realized while loading `adios@1.10.0 %gcc@5.4.0` that variants of type "multi" with "None" default break the `str(spack.spec)` representation for commands such as `spack load`.

```
    variant(
        'staging',
        default=None,
        values=('flexpath', 'dataspaces'),
        multi=True,
        description='Enable dataspaces and/or flexpath staging transports'
    )
```

### Works fine

```bash
spack load adios@1.10.0 %gcc@5.4.0
```

### Breaks

Does nothing, returns *without* an error message:
```bash
spack load adios@1.10.0%gcc@5.4.0~bzip2~fortran~hdf5~infiniband+mpi~netcdf patches=5242cf9b3879e47672f32bb24e2f6d34153477f9cc8ed267602a1e79b4a58f3b,8ae17f655248e87cbab1d1ed794e15364a38d2f5f8d971b1086702f72d79bd42 +shared staging= +sz~szip+zfp+zlib arch=linux-ubuntu14.04-x86_64
```

(string taken from `spack spec` or in-code `str(spec)`)

the error is caused by the representation of the `staging= ` element.

One can also reduce it to:
```bash
spack load adios@1.10.0%gcc@5.4.0 staging= +sz~szip+zfp+zlib
```

ccing @alalazo in case it's spack load specific

**Comment by ax3l** [comment]
Ping: still an issue. Can we sanitize the `None` in multi-variants somehow?

**Comment by ax3l** [comment]
The same issue affects `str(spec)`s of e.g. OpenMPI with the `fabrics=` and `schedulers=` variant default:
```
openmpi@3.1.2%gcc@4.9.4~cuda+cxx_exceptions', 'fabrics=', '~java~memchecker~pmi', 'schedulers=', '~sqlite3~thread_multiple+vt', 'arch=linux-opensuse42-x86_64
```

**Comment by ax3l** [comment]
Yes, I think it's an issue in parsing multi-valued variants that are allowed to be `None` inside `lib/spack/spack/parse.py`

**Comment by alalazo** [comment]
A sensible way to sanitize this behavior might be to enforce that the default value of a multi-valued variant is among the list of allowed values and don't convert `None` to the empty string as we do in:

https://github.com/spack/spack/blob/872e3c76f66b417123a0cbf76d3d2f4a69c804a8/lib/spack/spack/directives.py#L481-L482

 Looking briefly at packages that use `None` as a default value I see mainly two cases:

1. Packages where, if nothing is specified, we let the underlying build-system use its defaults. This is for instance the case of `openmpi`. In this case we could name the default value `auto` and make it mutually exclusive with any of the other values.

2. Packages where, if nothing is specified, we don't activate any feature. This is the case of `adios`. Even in this case I would add a new value and make it mutually exclusive with any of the other values. The only difference is that for semantic reasons I would call it `none`.

Proceeding down this path would allow us not to modify the parser, as every multi-valued variant will be of the form:
```
name=value[ {,value} ]
```
and never of the form:
```
name=
```
Does this seem reasonable? If so I'll proceed with the implementation.

**Comment by ax3l** [comment]
I have to admit I am not sure of complicated the parser modification would be, but it would add another corner case I guess.

I therefore am fine to change this, but we should enforce `None` is not an allowed value anymore to avoid triggering this again.

What do you thing, @tgamblin @adamjstewart et al.?

**Comment by ax3l** [comment]
I have to admit I am not sure of complicated the parser modification would be, but it would add another corner case I guess.

I therefore am fine to change packages' multivariant values instead, but we should enforce `None` is not an allowed value anymore to avoid triggering this again.

What do you think, @tgamblin @adamjstewart et al.?

**Comment by alalazo** [comment]
> I therefore am fine to change packages' multivariant values instead, but we should enforce None is not an allowed value anymore to avoid triggering this again

A bit longer explanation: the main issue is that we are converting `None` to the empty string in the 2 lines posted above. We could just use `str(None)` instead, but at that point `'None'` would be equal to `None` for variants purposes, which looks weird to me. Also, having displayed something like:
```
openmpi fabrics=None
```
is not really meaningful in our context. Therefore the change proposed above.

**Comment by alalazo** [comment]
> Hm, but for case 2 as in adios, none would then became on of the allowed multi-variants. Isn't staging=none,flexpath,dataspaces also odd? But I could live with that, it's not too confusing.

`none` should represent the empty set. I'll try to find a way to add syntactic sugar and make writing something like this more appealing. Will post some proposal here.

**Comment by alalazo** [comment]
So, here's the first proposal on how to improve writing multi-valued variants like the above.

**Current code in packages**
```python
# Example taken from `builtin.openmpi`. 
# If the variant is not set explicitly from the command line, the package will try 
# to determine the schedulers to enable.
variant(
    'schedulers',
    description='List of schedulers for which support is enabled',
    values=('alps', 'lsf', 'tm', 'slurm', 'sge', 'loadleveler'),
    multi=True
)

# Example taken from `builtin.adios`. If no value is given explicitly then no
# support for any of these features will be activated
variant(
    'staging',
    default=None,
    values=('flexpath', 'dataspaces'),
    multi=True,
    description='Enable dataspaces and/or flexpath staging transports'
)
```
In both cases the default values are `None`, and can't be given explicitly because `None` is converted to the empty string within the `variant` directive.

**Proposed modification in packages of these kind**
With respect to the two cases above, I think we could obtain something a bit more declarative like:
```python
# `builtin.openmpi`
variant(
    'schedulers', 
    description='List of schedulers for which support is enabled',
    values=default_or_any_combination_of('alps', 'lsf', 'tm', 'slurm', 'sge', 'loadleveler')
)

# `builtin.adios`
variant(
    'staging',
    description='Enable dataspaces and/or flexpath staging transports'
    values=any_combination_of('flexpath', 'dataspaces'),
)
```
The first variant should add `auto` to the list of valid values, and make it mutually eclusive with any of the others. The second case should do the same but call the added value `none`. At that point from the command line we could simply say:
```
$ spack spec openmpi schedulers=auto
...

$ spack spec adios staging=none
...
```
and we will receive appropriate error messages in case of inconsistent input:
```
$ spack spec openmpi schedulers=auto,alps
...
==> Error: the value `auto` in the variant `schedulers` is mutually exclusive with any of the other values
```
Does this seem reasonable at a high level? Should I proceed with a PR?

**Comment by ax3l** [comment]
Love it, and
```
$ spack spec adios schedulers=none,flexpath
...
```
?

**Comment by alalazo** [comment]
@ax3l That should also trigger an error, like `auto`. The main point I wanted to make is that we should provide a bit of machinery to make the boilerplate transparent to users. I'll try to implement something in the incoming days.

**Comment by ax3l** [comment]
Related #6050?
