### ISSUE TITLE
Higher Dependency A if Dependency B at Version

### ISSUE THREAD

**Issue by ax3l** [spack/spack#6324]
In C++ header-only libraries (#2378) one often combines two libraries that do not have a common dependency. E.g. a template metaprogramming library such as `Boost::MPL` can be used inside CUDA kernels, but boost has no dependency on CUDA.

Unfortunately, there can still be downstream constrains, e.g. since headers use new or unsupported C++ keywords etc. that are not yet supported by the cuda compiler and vice versa.

Is there a way to express in a package a constrain that says:

    I depend on library A and B.
    A needs a different version if B is used in version X.

?

A package could look like this:
```python
    depends_on(
        'cuda@7.0:',
        type='link'
    )

    depends_on(
        'boost@1.56.0:',
        type='link'
    )
    depends_on(
        'boost@1.65.1:',
        type='link',
        when='^cuda@9:'  # this is not valid syntax yet but I would like to express that
                         # btw: it is accepted syntax right now, it just does not work as expected
    )
```

Do you have any idea how we can express such constrains?

**Comment by krafczyk** [comment]
I have a very similar problem.

There are some packages which depend on python either 2 or 3, but require unicode support.

In the python package, there is a variant, `+ucs4` which adds unicode support to python 2, but which isn't supported in python 3. This means when I build this package with python 2, I need `python@2+ucs4`, while when I build this package with python 3, I need `python@3~ucs4`.

`depends_on` supporting `when` would probably allow this to happen, but we'll have to be careful, because in my case, this will look something like:

```
depends_on('python+ucs4', when='^python@2')
depends_on('python~ucs4', when='^python@3')
```

This may cause some kind of loop because the depend statement is adding a python dependency, while the `when` statement changes this dependency depending on the version of python needed.

**Comment by scheibelp** [comment]
Regarding the comment in:

```
    depends_on(
        'boost@1.65.1:',
        type='link',
        when='^cuda@9:'  # this is not valid syntax yet but I would like to express that
                         # btw: it is accepted syntax right now, it just does not work as expected
    )
```

Do you get a failure like `Error: Conflicting conditional dependencies onpackage` at https://github.com/spack/spack/issues/6231 or does some other error occur?

I'm currently looking into making that work but a fix is likely on the order of a couple weeks out. More info at https://github.com/spack/spack/pull/6247#issuecomment-343630847

**Comment by ax3l** [comment]
Thx for the work on that! 

Surprisingly, this condition seems to be just fully ignored currently.

**Comment by alalazo** [comment]
@ax3l Does this unit test address your use case:

https://github.com/spack/spack/blob/05848c87c5e4a1505746643c2efd34703e438988/lib/spack/spack/test/concretize.py#L818-L837

? The root package has an entry like:
```python
depends_on('variant-on-dependency-condition-b', when='^variant-on-dependency-condition-a+x')
```
If so I would close this issue.

**Comment by tldahlgren** [comment]
@ax3l ping

**Comment by ax3l** [comment]
The unit test does not solve the original feature request but it now aborts with an error if one tries to express such a dependency.

Do we track the feature elsewhere? In that case we can close this one.

**Comment by ax3l** [comment]
@alalazo is that unit test still valid? I think we can `when` on dependencies now with `clingo`, don't we? :)
- https://github.com/spack/spack/issues/6300#issuecomment-973172729
- https://github.com/spack/spack/pull/27042#issuecomment-954465640

In case I got this correct then we can close this issue and remove the unit test.

**Comment by haampie** [comment]
This should be possible now
