### ISSUE TITLE
version('local', ...)

### ISSUE THREAD

**Issue by ax3l** [spack/spack#6325]
The docs speak several times about the possibility to install a `@local` version of a package.

I checked the buildin repo and the docs but never found a full explanation of `version(...)`. Also [spack.package](https://spack.readthedocs.io/en/latest/spack.html#spack.package.PackageBase.version) seems to skip exactly that method in the doc strings.

Is there a `version('local', 'file://~/src/myPackage')` syntax? (this fails)

I would actually like to fetch from such an URI for development :)

**Comment by davydden** [comment]
no, there is no such syntax. `local` was only a convention which we removed, but apparently not everywhere... so feel free to create a PR to clean up the docu.

p.s. if you need to install a package which can't be fetched, you can do (used-to be Intel-MKL):
```
version('11.3.2.181', '536dbd82896d6facc16de8f961d17d65',
            url="file://%s/l_mkl_11.3.2.181.tgz" % os.getcwd())
```

**Comment by davydden** [comment]
please re-open if the issue persist.
