### ISSUE TITLE
Spack meetup at SC17

### ISSUE THREAD

**Issue by krafczyk** [spack/spack#6326]
@tgamblin tells me that a bunch of folks are here!

I explicitly remember hearing about @alalazo, @adamjstewart, @mplegendre, and @becker33.

I'd like the opportunity to see people face-to-face. We should have a spack dinner or lunch Today, Thursday, or Friday.

If you know about other spack people here, loop them in!

My first proposal, is dinner tonight!

**Comment by adamjstewart** [comment]
Unfortunately, I'll be flying out this afternoon, but maybe next time!

**Comment by krafczyk** [comment]
Aww...

**Comment by tgamblin** [comment]
Hey @krafczyk @mplegendre @alalazo @becker33 @mamelara @baberlevi @DavidPoliakoff @foertter and anyone you want to invite:

Let's meet up at Freshcraft tonight at 8pm for drinks.  Two motives: 1) good beer, and 2) there's also an easybuild meeting there from 8-10, so we can meet those guys face to face 😄 .  Who's in?

**Comment by mamelara** [comment]
pinging @jrood-nrel

**Comment by tgamblin** [comment]
I knew I forgot someone!

**Comment by krafczyk** [comment]
I'll be there!

**Comment by jrood-nrel** [comment]
10-4

**Comment by DavidPoliakoff** [comment]
There in spirit. Spirits? I'm drinking, is what I'm saying. Somebody buy a person who is working on binary packaging a drink, and there'll be beers bought when they're in Livermore.

**Comment by tgamblin** [comment]
@jrood-nrel and I are in the back.

**Comment by krafczyk** [comment]
Thanks @tgamblin, @jrood-nrel, @mamelara for a great spack discussion! I think this issue is closed :)

**Comment by alalazo** [comment]
Hey guys, sorry I didn't show up, but I went really long on the Mellanox event. In any case I am around till end of the week! Cheers
