### ISSUE TITLE
Spack buildcache is too verbose

### ISSUE THREAD

**Issue by sknigh** [spack/spack#6331]
For a single package: 
``` bash
# spack buildcache list
==> Finding buildcaches in <MIRROR_ROOT>/build_cache
==> Fetching file://<MIRROR_ROOT>/build_cache/linux-centos7-x86_64-gcc-4.8.5-xextproto-7.3.0-v5vttf7jlxd4lkqhrtc4x5zflbudgpov.spec.yaml
######################################################################## 100.0%
==> Enter
spack buildcache install /v5vttf7
 to install "xextproto@7.3.0%gcc@4.8.5 arch=linux-centos7-x86_64 "
```

```buildcache list``` will print two lines for each new spec discovered, then three more lines for each package. I think a better output would look similar to ```spack find``` output. The download output isn't useful for someone that wants a list of available packages.

``` bash
# spack find -lv --show-full-compiler zlib
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
64vg6e4 zlib@1.2.11%gcc@4.8.5+optimize+pic+shared
```

**Comment by healther** [comment]
@alalazo I know you reduced cluttered output in a lot of commands, did you also address `buildcache`?

**Comment by alalazo** [comment]
@healther No. Pinging @gartung as he might be interested in this ticket.
