### ISSUE TITLE
spack does not create flake8 conformant packages

### ISSUE THREAD

**Issue by matze** [spack/spack#6338]
It should not be necessary to run `dos2unix` on newly created packages.

### Expected Result

`spack flake8` should not complain about newly created packages.

### Actual Result

`spack create` creates packages with DOS line endings. This confuses flake8 and reports errors like ` [E114] indentation is not a multiple of four (comment)`. See [here](https://travis-ci.org/spack/spack/jobs/303091232) for example. This [commit](https://github.com/spack/spack/pull/6337/commits/850e86806a38e955e489333691749208ad41be90) – I was just using `dos2unix` on the offending packages – fixed it.

### Steps to reproduce the issue

```console
$ spack create -n foo -r somerepo
$ spack flake8
```

### Information on your system

Nothing special, a regular Ubuntu 16.04 box.

**Comment by adamjstewart** [comment]
Unable to reproduce on macOS High Sierra or CentOS 6
```
$ spack create
==> Created template for example package
==> Created package file: /Users/Adam/spack/var/spack/repos/builtin/packages/example/package.py
$ spack flake8
=======================================================
flake8: running flake8 code checks on spack.

Modified files:
  var/spack/repos/builtin/packages/example/package.py
=======================================================

Flake8 checks were clean.
```
Do you have any weird configurations that could affect this? `spack create` literally prints a string to a file, nothing fancy. Perhaps your Python was built in a strange way?

**Comment by matze** [comment]
> Do you have any weird configurations that could affect this?

Maybe, maybe not. I tested and built those packages in a fresh Ubuntu 16.04 VM. I can try to reproduce this on my own machine again.

**Comment by adamjstewart** [comment]
Can you also give me the output of the following command?
```
$ python -c 'import os; print(repr(os.linesep))'
```

**Comment by alalazo** [comment]
Could it be that it's not `python`, but rather your editor configuration? The command `spack create` in the end opens the editor:
```python
# Open up the new package file in your $EDITOR
spack.editor(pkg_path)
```
If the editor itself is set to change line endings on save (which can be the case depending on your platform / settings) that would explain the behavior you see above. Just a guess though.

**Comment by matze** [comment]
Hey, thanks for the interest everyone takes in this issue and yes … after a lengthy investigation I found the culprit to be the way the editor was set up, no issue at all with Spack! Maybe I should trust my instincts first because otherwise that would have been a high impact bug and not have been gone unnoticed before.
