### ISSUE TITLE
ROOT can't build against Python3

### ISSUE THREAD

**Issue by briedel** [spack/spack#6339]
`spack install root%gcc@5.2.0 ^python@3.6.2` cannot get past CMake step because it cannot find `python` as a reference to `python@3.6.2` rather than system python. I found this on RHEL6 machine with Python2.6, which is not compatible with root 6.08.06. Where should this be fixed? Making a symlink in `python3` to `python` or inside `root`?

**Comment by alalazo** [comment]
My opinion is that it shouldn't be solved in the `python` package, but either in the `root` package or in `root` source code. 

I think this depends on whether the `CMakeLists.txt` already makes use of the [FindPythonInterp](https://cmake.org/cmake/help/v3.10/module/FindPythonInterp.html) Cmake module. If so we should modify the `package.py` to set `Python_ADDITIONAL_VERSIONS`. If not `root` build-system should be modified to use the module provided by CMake.

**Comment by briedel** [comment]
@gartung I looks like `root` is using `FindPythonInterp` from CMake. Do you know what could be the issue?

**Comment by gartung** [comment]
You have to specify the python cmake variables by hand. See
https://github.com/gartung/cmssw-spack/blob/master/packages/root/package.py#L86

**Comment by briedel** [comment]
Could we merge the default and CMS package into one? I guess we would have to add some extra options to get the C++17, etc. as an option.

**Comment by gartung** [comment]
@briedel You can submit an update to the builtin formula. The CMS version now includes creating scram toolfile's which are only used by CMS.

**Comment by alalazo** [comment]
Fixed by #8428 @vvolkl pinging you just in case
