### ISSUE TITLE
Document Best Practices for MPI

### ISSUE THREAD

**Issue by citibeth** [spack/spack#637]
@tgamblin has mentioned three common ways to create packages of MPI-based software.  Document these (or whatever best practices might be) and add to the manual.  If anyone has a quick description of what they are, it would be great if they can be added to this Issue.

**Comment by mathstuf** [comment]
I've seen a few. The easiest one is to just `depends_on('mpi')`. Others do that and then set environment variables such as `MPICC` using `mpi.prefix`. Others force the MPI compilers to be the C, C++, and Fortran compilers. The first one definitely works for CMake-based packages which don't provide their own `FindMPI`. Second one probably works with autotools, but I'm not sure. The last one is best left to hand-crafted Makefiles.

**Comment by citibeth** [comment]
Is there further information on this issue, or have updates to Spack made things "just work" better?  I don't understand fully what's needed from the description above.  But if something is needed, and we can find a more complete description, I can put it in the manual.

**Comment by davydden** [comment]
some info is here http://spack.readthedocs.io/en/latest/packaging_guide.html#message-parsing-interface-mpi
i don't think there is something else needed. Maybe only mention that Spakc's compiler wrappers are used inside MPI compiler wrappers, so all RPATHS and alike are there when we compiler something with MPI wrappers.
