### ISSUE TITLE
Support RUNPATH as well as RPATH

### ISSUE THREAD

**Issue by citibeth** [spack/spack#639]
Some users prefer RUNPATH instead of RPATH.  Make Spack support either style of adding paths to binaries.

**Comment by citibeth** [comment]
@hegner said:

> I fully agree to LD_LIBRARY_PATH being evil (or let’s say too fragile). Now the thing about RPATH is that it doesn’t allow any overriding of libraries by locally built ones. Sometimes you just want to load a different library providing the same symbols. And only if it is the same lib, with a bug fix you want to test before complete deployment… there are plenty of these cases. Thus RUNPATH seems the better option to me.

**Comment by tgamblin** [comment]
This is doable but there are linking ramifications.  You may think that `RUNPATH` is the same as `RPATH`, but with an optional override from `LD_LIBRARY_PATH`.  However, the search semantics for them are actually quite different.  Here is the lookup order, [thanks to Qt](http://blog.qt.io/blog/2011/10/28/rpath-and-runpath/):

```
Unless loading object has RUNPATH:
    RPATH of the loading object,
        then the RPATH of its loader (unless it has a RUNPATH), ...,
        until the end of the chain, which is either the executable
        or an object loaded by dlopen
    Unless executable has RUNPATH:
        RPATH of the executable
LD_LIBRARY_PATH
RUNPATH of the loading object
ld.so.cache
default dirs
```

Note that `RPATH` will search its parent objects' `RPATH`s, while `RUNPATH` will not.  The situations where this matters are complicated (see the Qt blog above), and I haven't worked out how Spack should set `RUNPATH`s.  Right now, we actually set more `RPATH`s than we need (we set `RPATH`s for the whole DAG, and could probably get away with just immediate deps).

For `RUNPATH`, I suspect that things work in most cases, but in certain cases like the one in the link above, I am not sure that we can always generate something that will run correctly *without* also relying on `LD_LIBRARY_PATH`.  This seems bad to me.

**Comment by hegner** [comment]
For the Qt case I believe setting more `RUNPATH`s thar required would be enough. In the end that's contained within a single package with locations well known at compile time.
In general, however, neither `RPATH` nor `RUNPATH` are sufficient for plugin systems. The nice thing about plugins is that one can extend a project A by plugins in another project B. And A and its plugin loader obviously don't know about B at compile time yet, thus no chance of having proper `RPATH` or `RUNPATH`. So environment variables are needed anyhow.

**Comment by citibeth** [comment]
I would suggest that we just make a simple Spack configuration parameter to
use RUNPATH instead of RPATH, and keep it on an experimental branch.  This
will provide @hegner the basic feature needed to try things out, and see if
RUNPATH works in a meaningful way in real-life situations.  We can
re-evaluate later.

-- Elizabeth
