### ISSUE TITLE
cgal 4.9.1 checksum wrong.

### ISSUE THREAD

**Issue by willfurnass** [spack/spack#6414]
Tried to install a package and the `cgal` chosen by concretisation wasn't installed as the checksum was wrong:

```sh
spack install gcc@7.2.0
spack load gcc@7.2.0
spack compilers find
spack unload gcc@7.2.0
spack install openfoam-com@1706 ^openmpi@3.0 fabrics=psm2 schedulers=sge
...
ChecksumError: ChecksumError: md5 checksum failed for /data/cs1wf/spack/var/spack/stage/cgal-4.9.1-djhtft2maevtiffwtsak5glyhlb7v7o7/CGAL-4.9.1.tar.gz
    Expected df6517df3320bf6c9de2e1b0361738b9 but got 2c427da202ea4a6f5c8c8fbc6987022e
```

Using Spack commit `1b3b2627761a1f5a792749ff9d6b9c263f5203f9` on Centos 7.4.

Get the same issue if explicitly requesting cgal 4.9 instead.

**Comment by tmarkhuang** [comment]
I contacted Laurent Rineau, release manager of the CGAL project.  The two correct URLs for downloading CGAL-4.9.1 are
https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.9.1/CGAL-4.9.1.zip
https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.9.1/CGAL-4.9.1.tar.xz

The checksums of these two files match what are listed in md5sum.txt and sha256sum.txt, under 4.9.1 release page (https://github.com/CGAL/cgal/releases/tag/releases/CGAL-4.9.1).

The tar.gz version (https://github.com/CGAL/cgal/archive/releases/CGAL-4.9.1.tar.gz) is generated by github, as a snapshot of the git repository corresponding to the release version.

In CGAL-4.11, Laurent has removed the checksums for the .tar.gz tarball, to avoid the ambiguity.

**Comment by adamjstewart** [comment]
@tmarkhuang Thanks for looking into this! Can one of you test #6511 and make sure it works for you?

**Comment by tmarkhuang** [comment]
No more checksum error on building CGAL after applying patch in #6511.
