### ISSUE TITLE
R installed from buildcache crashes

### ISSUE THREAD

**Issue by sknigh** [spack/spack#6418]
Cannot use R from buildcache unless the directory path is identical

### Expected Result

Running a buildcache-installed R should open an R shell

### Actual Result

R crashes because it hard-codes ```R_HOME``` and ```R_{HOME,SHARE,INCLUDE,DOC}_DIR``` in it's shell wrapper

### Steps to reproduce

``` bash
$ spack buildcache install /ozq2oj7 # An instance of R from buildcache
$ `spack location -i r`/bin/R
<NEW_PATH>/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/r-3.4.1-ozq2oj7bwwlhkqncnommq6yfguvovxo2/bin/R: line 238: <OLD_PATH>/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/r-3.4.1-ozq2oj7bwwlhkqncnommq6yfguvovxo2/rlib/R/etc/ldpaths: No such file or directory
```

### Information on your system
Cache created in a Centos 7.4 environment.

**Comment by sknigh** [comment]
@gartung @tgamblin Are there any thoughts on the best way to fix this? It would be really nice to have buildcache support for R.

**Comment by gartung** [comment]
Sorry. That cannot be handled because the type returned by 'file bin/R' is not text. Doing a string substitution on a binary file is dangerous.

**Comment by tgamblin** [comment]
@gartung: it looks like @sknigh is talking about a shell wrapper -- @sknigh -- what file specifically is hard-coding the paths?

If this is actually a binary patching problem, @mplegendre can probably comment on safe ways to rewrite a binary, but it may be that the easiest way to do this is to patch R.

**Comment by sknigh** [comment]
```bin/R``` is a script. If there are any binaries with hard-coded paths, then I have not gotten far enough to bump into them.

**Comment by gartung** [comment]
Here is what determines if a file can have text replacement
https://github.com/spack/spack/blob/develop/lib/spack/spack/relocate.py#L195
Can you tell me the output of 
file -b -h bin/R
If the output does not contain the string 'text', the file is not marked for relocation.

**Comment by sknigh** [comment]
```bash
# file -b -h bin/R
POSIX shell script, ASCII text executable
```

**Comment by gartung** [comment]
I see that r depends on tk. The tk package hard codes the path to its configuration file. This is where the problem most likely lies.

**Comment by sknigh** [comment]
That may be a problem, but the error above was from the shell script wrapper failing to find ```rlib/R/etc/ldpaths```

**Comment by gartung** [comment]
Check the relocates install fir for .spack/buildinfo.yaml . Is the file listed? Is the path changed in the wrapper script. I can only speculate that filter_file did not work
https://github.com/spack/spack/blob/develop/lib/spack/spack/relocate.py#L292

**Comment by gartung** [comment]
@tgamblin This is fixed in PR
https://github.com/spack/spack/pull/6498

**Comment by gartung** [comment]
@tgamblin this works without using perl

https://github.com/spack/spack/pull/6500

**Comment by gartung** [comment]
I also discovered that I  assume the default directory layout  when creating/unpacking the tarball.

**Comment by gartung** [comment]
This is address in #6512

**Comment by sknigh** [comment]
#6512 is giving me interesting results. 

R shell seems to work now.
``` bash
$ R

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> print('hello world')
[1] "hello world"
```

But Rscript does not

``` bash
$ Rscript -e "print('hello world')"
Rscript execution error: No such file or directory
```

It turns out that Rscript is a binary file. I can see with ```strings `which Rscript` ``` that it hard-codes a single path to ```<old_root>/rlib/R```. All other absolute paths are re-written (which I assume to be rpaths).

**Comment by gartung** [comment]
The PR at least fixes the text relocation. The paths compiled into Rscript will require binary patching which I don't know how to handle.

**Comment by sknigh** [comment]
I just tried ``` sed -i 's|<old-path>|<new-path>|g' Rscript ``` and it worked! I'm sure it's a bad idea in general.

**Comment by gartung** [comment]
It works as long as new-path is shorter than old-path. You risk overwriting or shifting program text if it is longer.

**Comment by sknigh** [comment]
Now that #6512 is committed, the problem I reported is solved, but R still has binary incompatibilities.

@tgamblin It would be nice if I had way to mark packages (in package.py) that are not rpath compliant enough to be moved to a new path in via buildcache.
