### ISSUE TITLE
can not specify default=None variant from the command line

### ISSUE THREAD

**Issue by davydden** [spack/spack#6426]
The issue appears when we have a variant with default being `None`, i.e.
```
variant('cuda_arch', default=None,
             description='CUDA architecture',
             values=('20', '30', '32', '35', '50', '52', '53', '60', '61',
                     '62', '70'),
             multi=True)
```
Now say a user has some settings in `packages.yaml` for this variant, for example
```
  dealii:
    version: [develop]
    variants: cuda_arch=52 +cuda
```
But he might want to override this variant to be `None` in CLI,  this appears to be not allowed:
```
$ spack spec dealii@develop~cuda cuda_arch=None
Input spec
--------------------------------
dealii@develop~cuda cuda_arch=None

Normalized
--------------------------------
==> Error: invalid values for variant "cuda_arch" in package "dealii": ['None']
```
or
```
$ spack spec dealii@develop~cuda cuda_arch=
==> Error: Unexpected end of input
```

### Expected Result

to get the following concretized spec by overriding `packages.yaml`
```
dealii@develop... ~cuda cuda_arch= +doc...
```

### Actual Result

see above.

### Steps to reproduce the issue

see above.

### Information on your system

tested on macOS and Ubuntu.

**Comment by scheibelp** [comment]
It doesn't appear to be fully specified how a variant value of `None` should be treated and handled.

@tgamblin I've created a branch at https://github.com/spack/spack/compare/develop...scheibelp:bugfix/explicit-none-variant which adds a mock package and the test `set_variant_none`. There are some questions to answer about conventions:

* For a variant which can take on the value `None` (default or not), should the user be able to test it as a truth value (e.g. `if spec.variants['v'].value` vs. `if spec.variants['v'].value == "none"`).
* Should this also apply when the user sets `variant=none`?
* Should this also apply if the allowed value is not `None` but rather `"None"` or `"none"` (i.e. a string vs. a `None`).
* Should the user be able to specify none using the syntax `variant=` vs. `variant=none`? The latter is likely easier to do.

The unit test added in that branch demonstrates some of these questions.

**Comment by alalazo** [comment]
Closing as `None` can't be used as a default in variants since #9481
