### ISSUE TITLE
Spack Profiles

### ISSUE THREAD

**Issue by citibeth** [spack/spack#643]
It think Spack profiles is what you need here.  They have been considered but not yet implemented.  Here is @tgamblin's description:

> Just a thought FYI: one thing we are thinking very strongly of implementing is a "profile" capability, which would work kind of like virtualenv or conda environments, but for anything, not just python packages. It would likely look sort of like the existing python support in Spack, where you can activate/deactivate packages and they are symlinked into a common prefix (in the current Python case, that is the interpreter prefix).
> You could do something like:
> 
> ```
> spack profile create mystack # creates a profile called `mystack` in a directory somewhere
> spack profile add <spec> # installs <spec> if needed, then links it into mystack
> spack profile remove <spec> # unlinks <spec> from mystack
> ```
> 
> ... etc ...
> spack profile activate # add mystack/bin to $PATH, add mystack to CMAKE_PREFIX_PATH, etc.
> This would make it easy to create and save environments and stacks of packages for different teams, and to get them in/out of your environment. I would likely also want to version the profiles. This feature is in package managers like nix and guix. Another nice feature is that it would allow external apps to RPATH the profile directory (or a symlink to it, to allow transactional updates), but you could do seamless upgrades of packages linked into the profile by removing them and adding a new version. 

Would this suit your needs? 

I think that comes very close… if one could a) version that and b) pre-define the profile in a file. In our use case this one is strongly connected to the bundle feature discussed below.

**Comment by citibeth** [comment]
I think that PR #721 provides Spack Profiles capabilities in a simpler-to-implement fashion.  I would make a ``make_mystack.sh`` shell script as follows:

```
# Add just these to the profile
spack module find --shell tcl spec1 spec2 ...
# Add these and all their dependencies to the profile
spack module find --dependencies --shell tcl spec3 spec4 ...
```
Then I run ``sh make_mystack.sh >mystack.sh``

Now to load the ``mystack`` profile, I do: ``source mystack.sh``
For this reason, suggest we re-open PR #721 and give it a second look.

**Comment by alalazo** [comment]
Closing stale issues. In this case I think the issue is outdated by @scheibelp environments. Feel free to reopen if you don't agree.
