### ISSUE TITLE
Package Syntax Error: Error Message

### ISSUE THREAD

**Issue by ax3l** [spack/spack#6442]
### Expected Result

Spack build recipes in a `package.py` might accidentally contain python syntax errors. This happens quickly when dealing with experimental branches or external repositories.

When trying to install such a wrongly formatted package *or even just a package that depends on it* the `spack install` error message should tell the user *which* file contains the syntax error

### Actual Result

Instead, `spack install` only returns:
```bash
spack install packageName
==> Error: invalid syntax (package.py, line 42)
```

Note: this also affects commands such as `spack spec packageName`.

### Steps to reproduce the issue

Apply the following diff to produce a failing `tar` package:
```diff
--- a/var/spack/repos/builtin/packages/tar/package.py
+++ b/var/spack/repos/builtin/packages/tar/package.py
@@ -38,5 +38,5 @@ class Tar(AutotoolsPackage):
     patch('tar-pgi.patch',    when='@1.29')
     patch('config-pgi.patch', when='@:1.29')
     patch('se-selinux.patch', when='@:1.29')
-    patch('argp-pgi.patch',   when='@:1.29')
+    patch('argp-pgi.patch',   when='@:1.29'
     patch('gnutar-configure-xattrs.patch', when='@1.28')
```

Now try to install tar:
```console
$ spack install tar
==> Error: invalid syntax (package.py, line 42)
```

huh! *which* `package.py` is ment? The one in `builtin`? The one of my second repo?

It get's even more complicated when installing a package that *depends* on `tar` but itself has correct syntax:

```console
$ spack install gettext
==> Error: invalid syntax (package.py, line 42)
```

Now one would recusively walk through all dependencies to find the failing file.

### Information on your system

A standard Debian 9.2 "stretch" and spack `develop` as of 77bfda4da6f30f06762d749e0d83854d3a34dc6d .

**Comment by healther** [comment]
see #6458

**Comment by ax3l** [comment]
hurray, thanks a lot! 🚀
