### ISSUE TITLE
Less strict dependency resolution

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#646]
Spack REALLY needs to start considering already installed packages when resolving dependencies. Here is an example of what I want to do:

``` bash
spack install szip
spack install hdf +szip
spack install hdf5 +szip
spack install netcdf -mpi +hdf4
spack install netcdf-fortran
```

The netcdf installation reinstalls hdf~szip and hdf5~szip and links to those instead. The netcdf-fortran installation reinstalls netcdf+mpi~hdf4. To get what I actually want, I have to use:

``` bash
spack install szip
spack install hdf +szip
spack install hdf5 +szip
spack install netcdf -mpi +hdf4 ^hdf+szip ^hdf5+szip
spack install netcdf-fortran ^netcdf~mpi+hdf4 ^hdf+szip ^hdf5+szip
```

This starts to get ridiculous very fast. If I want to build a parallel version of netcdf, I would have to tack on `^openmpi+tm+psm` to hdf5, netcdf, and netcdf-fortran.

I would like Spack to choose already installed packages if they satisfy the "Normalized" requirements. If someone wants to build with something other than the default, they can explicitly declare this and Spack will rebuild them.

This issue has already been brought up in #311 and #577 but nothing has been done about it. I wanted to make a new Issue to simplify the discussion and to bring it back to the surface.

**Comment by citibeth** [comment]
This issue is on file at:
   https://github.com/LLNL/spack/issues/644

Also, Issue #540 would solve your problem without looking at what's already installed.

**Comment by tgamblin** [comment]
This is on the surface and planned after we get done merging #561.

**Comment by adamjstewart** [comment]
Closing as a duplicate of #311
