### ISSUE TITLE
Fail to install r-fftwtools because fftw3.h not found.

### ISSUE THREAD

**Issue by lingnanyuan** [spack/spack#6475]
`>> 34    fftwtools.c:28:9: fatal error: fftw3.h: No such file or directory`.

**Comment by junghans** [comment]
Just add:
```
depends_on('fftw@3:')
```

**Comment by lingnanyuan** [comment]
It doesn't work, still shows the same error.

**Comment by junghans** [comment]
Try:
```
depends_on('fftw@3: double')
```

**Comment by lingnanyuan** [comment]
`==> Error: Invalid Version range: 3:double`

**Comment by junghans** [comment]
Sorry:
```
depends_on('fftw+double@3:')
```

**Comment by lingnanyuan** [comment]
It still shows the first error. I'm not sure if there is something missing in the fftw package.

**Comment by junghans** [comment]
I have a `fftw@3.3.6-pl2+double+float+long_double+mpi~openmp~pfft_patches~quad`, which has a `fftw3.h`. Can you check with `spack find -p fftw` that yours has, too?

**Comment by lingnanyuan** [comment]
I have 
`-- linux-rhel7-x86_64 / gcc@6.3.0 -------------------------------
    fftw@3.3.6-pl2  /opt/rit/app/spack/linux-rhel7-x86_64/gcc-6.3.0/fftw-3.3.6-pl2-zhjwbm6mnspdop2rwvnsncqbwrmkzhyw

-- linux-rhel7-x86_64 / gcc@7.1.0 -------------------------------
    fftw@3.3.6-pl2  /opt/rit/app/spack/linux-rhel7-x86_64/gcc-7.1.0/fftw-3.3.6-pl2-uosr7o4kxhdrc5pnbv7rpfezqloner5e
    fftw@3.3.6-pl2  /opt/rit/app/spack/linux-rhel7-x86_64/gcc-7.1.0/fftw-3.3.6-pl2-uw7a7wffvvmwxqq3dyntqxiwmdir3dcb
    fftw@3.3.6-pl2  /opt/rit/app/spack/linux-rhel7-x86_64/gcc-7.1.0/fftw-3.3.6-pl2-ptwuyfzpdupkcb5rlh7aiimxzssdfsvi
`
And I checked the fftw3.h exist, but don't know why spack cannot find it.

**Comment by junghans** [comment]
Ok, that means the fftwtools buildsystem is broken!
You should report the issue here: https://github.com/krahim/fftwtools
I think you need a patch along the lines of:
```diff
diff --git a/src/Makevars b/src/Makevars
index 341e0cc..50f87c9 100644
--- a/src/Makevars
+++ b/src/Makevars
@@ -8,7 +8,7 @@
 ## May 5th. I'm confused now as it appears this file is needed for building the package on Linux.


-PKG_CPPFLAGS=
+PKG_CPPFLAGS= $(FFTW_CFLAGS)
 PKG_LIBS= -lfftw3 -lm

 all: $(SHLIB)
```
to make their build system pickup the right `FFTW_CFLAGS`.

**Comment by lingnanyuan** [comment]
After I updated spack into newest commit, I successfully installed it.
