### ISSUE TITLE
cuda for ppc64le plataform

### ISSUE THREAD

**Issue by gilmartinez** [spack/spack#6495]
I`m trying to install cuda@9 through spack at a P100s cluster running ubuntu 16.04 (pcc64le arch). It seems that spack can only install cuda for x86_64 arch.

Is There any way to specify another architecture instead x86_64 ?

**Comment by alalazo** [comment]
Apologies for the super late reply. This has been addressed in #13912, so I'm closing the issue. Feel free to reopen if you think some further step is needed.
