### ISSUE TITLE
OSX failures on Travis

### ISSUE THREAD

**Issue by alalazo** [spack/spack#6513]
OSX jobs are failing systematically under Travis

### Expected Result

A reassuring green tick 

### Actual Result

OSX fails at "before_install" with this error:
```console
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/c++
Target /usr/local/include/c++
already exists. You may want to remove it:
  rm '/usr/local/include/c++'
To force the link and overwrite all conflicting files:
  brew link --overwrite gcc
To list all files that would be deleted:
  brew link --overwrite --dry-run gcc
Possible conflicting files are:
/usr/local/include/c++ -> /usr/local/Caskroom/oclint/0.11,15.6.0/oclint-0.11/include/c++
==> Summary
🍺  /usr/local/Cellar/gcc/7.2.0: 1,487 files, 284MB
```

### Steps to reproduce the issue

Check any of the failing build, like [this one](https://travis-ci.org/spack/spack/jobs/308674072)

**Comment by adamjstewart** [comment]
@tgamblin How far off are we from providing build caches for macOS? It would be great to kill this Homebrew dependency.
