### ISSUE TITLE
Issues implementing an 'external' variant

### ISSUE THREAD

**Issue by krafczyk** [spack/spack#6567]
As part of my on going efforts to create an interface for spack to use to access natively installed packages and packages managed by other packaging systems, I'm trying to implement an 'external' variant which is always there. i.e.

`python external=path:/path` would indicate a python installation located at `/path`.
`python external=pacman:python2` would indicate a python installation installed as package `python2` in the pacman package manager.

I tried to copy the strategy done for patches here: https://github.com/spack/spack/blob/develop/lib/spack/spack/spec.py#L1823

by implementing the `external` property for a spec like this:

```
def external(self):
    evar = self.variants.setdefault('external', MultiValuedVariant('external', ()))  
    if len(evar.value) == 0:
        return ""
    else:
        return evar.value[0]
```

However, I've been getting errors like this:

```
Error: multiple values are not allowed for variant "external"
```

This error is thrown from here: https://github.com/spack/spack/blob/develop/lib/spack/spack/variant.py#L398

Which is really weird, because I didn't create the `external` variant as a `SingleValuedVariant` but as a plain `MultiValuedVariant`.

Anybody know why this bit of code from `SingleValuedVariant` is being called?

**Comment by scheibelp** [comment]
> Anybody know why this bit of code from `SingleValuedVariant` is being called?

There are spots where Spack converts variants into other types of variants, e.g. `substitute_abstract_variants`. This is supposed to occur only for abstract types. That function skips any variant identified by `spack.directives.reserved_names` (which currently just includes "patches") so the solution may be as simple as adding `"external"` to that list.

Let me know if that doesn't work and I can think on it more. It may be useful to be able to pull your work to take a look at it.

Out of curiosity, do you have an opinion about how this approach compares to the `Opengl` system package created in https://github.com/spack/spack/pull/6551? I should admit I don't understand what role the `external` variant plays in achieving the goal you mention:

> As part of my on going efforts to create an interface for spack to use to access natively installed packages and packages managed by other packaging systems

**Comment by adamjstewart** [comment]
@krafczyk I'm going to close this. Spack now has a builtin mechanism to detect system packages and add them to `packages.yaml`. If `spack external find` is missing any features or packages you care about, please submit a PR.
