### ISSUE TITLE
Emacs build failed at different points with different versions of GCC

### ISSUE THREAD

**Issue by baip** [spack/spack#6569]
### Expected Result
I'm trying to build emacs with Spack, but failed at different points with different versions of GCC.

### Actual Result

GCC 4.4.7/5.5.0

    ==> Installing pango
    ==> Fetching http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.40.3.tar.xz
    ######################################################################## 100.0%
    ==> Staging archive: /share/apps/spack/var/spack/stage/pango-1.40.3-w33eriw7mf4wgvmonze4o2f6o3saxu76/pango-1.40.3.tar.xz
    ==> Created stage in /share/apps/spack/var/spack/stage/pango-1.40.3-w33eriw7mf4wgvmonze4o2f6o3saxu76
    ==> No patches needed for pango
    ==> Building pango [AutotoolsPackage]
    ==> Executing phase: 'autoreconf'
    ==> Executing phase: 'configure'
    ==> Executing phase: 'build'
    ==> Error: ProcessError: Command exited with status 2:
        'make' '-j24'
    
    7 errors found in build log:
         [ ... ]
         441   <unknown>:: Warning: PangoFT2: Skipping foreign identifier 'PangoFcDecoder' from namespace Pango
         442   <unknown>:: Warning: PangoFT2: Skipping foreign identifier 'PangoOTFeatureMap' from namespace Pango
         443   <unknown>:: Warning: PangoFT2: Skipping foreign identifier 'PangoFcDecoderClass' from namespace Pango
         444   <unknown>:: Warning: PangoFT2: Skipping foreign identifier 'PangoFcFont' from namespace Pango
         445   <unknown>:: Warning: PangoFT2: Skipping foreign identifier 'PangoFcFontMap' from namespace Pango
         446   <unknown>:: Warning: PangoFT2: Skipping foreign identifier 'PangoFcFontMapClass' from namespace Pango
      >> 447   /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/libpng-1.6.29-i4gwjnncgklzs554dnssmdhdmfj543zu/lib/libpng16.so: undefined reference to `inflateValidate@ZLIB_1.2.9'
      >> 448   collect2: ld returned 1 exit status
         449   linking of temporary binary failed: Command '[u'/bin/sh', u'../libtool', u'--mode=link', u'--tag=CC', u'--silent', '/share/apps/spack/lib/spack/env/gcc/gcc', u'-o', u'/tmp/soft/spack-stage/spack-stage-H8cRnK/pango-1.40.3/pango/tmp-introspectTi9iYP/PangoFT2-1.0', u'-export-dynamic', '-Wall', u'tmp-introspectTi9iYP/tmp/soft/spack-stage/spack-stage-H8cRnK/pango-1.40.3/pango/tmp-introspectTi9iYP/PangoFT2-1.0.o', '-L.', 'libpango-1.0.la', 'libpangoft2-1.0.la', u'-L/share/apps/conda/envs/conda2/lib', u'-lgio-2.0', u'-lgobject-2.0', u'-Wl,--export-dynamic', u'-lgmodule-2.0', u'-pthread', u'-lrt', u'-lglib-2.0', u'-lfreetype']' returned non-zero exit status 1
      >> 450   make[4]: *** [PangoFT2-1.0.gir] Error 1
         451   make[4]: Leaving directory `/tmp/soft/spack-stage/spack-stage-H8cRnK/pango-1.40.3/pango'
      >> 452   make[3]: *** [all-recursive] Error 1
         453   make[3]: Leaving directory `/tmp/soft/spack-stage/spack-stage-H8cRnK/pango-1.40.3/pango'
      >> 454   make[2]: *** [all] Error 2
         455   make[2]: Leaving directory `/tmp/soft/spack-stage/spack-stage-H8cRnK/pango-1.40.3/pango'
      >> 456   make[1]: *** [all-recursive] Error 1
         457   make[1]: Leaving directory `/tmp/soft/spack-stage/spack-stage-H8cRnK/pango-1.40.3'
      >> 458   make: *** [all] Error 2
    
    See build log for details:
      /share/apps/spack/var/spack/stage/pango-1.40.3-w33eriw7mf4wgvmonze4o2f6o3saxu76/pango-1.40.3/spack-build.out

GCC 6.4.0

    ==> Installing gdk-pixbuf
    ==> Fetching http://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.31/gdk-pixbuf-2.31.2.tar.xz
    ######################################################################## 100.0%
    ==> Staging archive: /share/apps/spack/var/spack/stage/gdk-pixbuf-2.31.2-olieob7lmo7tknggsqrqkzw76q3xitc4/gdk-pixbuf-2.31.2.tar.xz
    ==> Created stage in /share/apps/spack/var/spack/stage/gdk-pixbuf-2.31.2-olieob7lmo7tknggsqrqkzw76q3xitc4
    ==> No patches needed for gdk-pixbuf
    ==> Building gdk-pixbuf [AutotoolsPackage]
    ==> Executing phase: 'autoreconf'
    ==> Executing phase: 'configure'
    ==> Executing phase: 'build'
    ==> Error: ProcessError: Command exited with status 2:
        'make' '-j24'
    
    24 errors found in build log:
         [ ... ]
         433     CCLD     libpixbufloader-pcx.la
         434     CCLD     gdk-pixbuf-query-loaders
         435     CCLD     libpixbufloader-xpm.la
         436     CCLD     libpixbufloader-xbm.la
         437     CCLD     libpixbufloader-icns.la
         438     CCLD     libpixbufloader-qtif.la
      >> 439   ./.libs/.libgdk_pixbuf-2.0.so:/ .undefinedlibs /libgdk_pixbuf-2.0.so: undefined reference reference to to` libintl_gettext`'libintl_gettext
         440   '.
         441   /../libs./libslibgdk_pixbuf/-libgdk_pixbuf2.0.so-:2.0.so :undefined  undefinedreference  referenceto  to` `libintl_bind_textdomain_codeset'libintl_bind_textdomain_codeset
         442   '.
         443   /../libs./libslibgdk_pixbuf/-libgdk_pixbuf2.0.so-:2.0.so :undefined  undefinedreference  referenceto  to` libintl_bindtextdomain`'libintl_bindtextdomain
         444   '
      >> 445   collect2: error: ld returned 1 exit status
      >> 446   collect2: error: ld returned 1 exit status
      >> 447   make[4]: *** [gdk-pixbuf-pixdata] Error 1
         448   make[4]: *** Waiting for unfinished jobs....
      >> 449   make[4]: *** [gdk-pixbuf-csource] Error 1
      >> 450   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_gettext'
      >> 451   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_bind_textdomain_codeset'
      >> 452   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_bindtextdomain'
      >> 453   collect2: error: ld returned 1 exit status
      >> 454   make[4]: *** [test-gdk-pixbuf] Error 1
      >> 455   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_gettext'
      >> 456   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_bind_textdomain_codeset'
      >> 457   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_bindtextdomain'
      >> 458   collect2: error: ld returned 1 exit status
      >> 459   make[4]: *** [gdk-pixbuf-query-loaders] Error 1
      >> 460   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_gettext'
      >> 461   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_bind_textdomain_codeset'
      >> 462   ./.libs/libgdk_pixbuf-2.0.so: undefined reference to `libintl_bindtextdomain'
      >> 463   collect2: error: ld returned 1 exit status
         464   linking of temporary binary failed: Command '[u'/bin/sh', u'../libtool', u'--mode=link', u'--tag=CC', u'--silent', '/share/apps/spack/lib/spack/env/gcc/gcc', u'-o', u'/tmp/soft/spack-stage/spack-stage-EYaUqi/gdk-pixbuf-2.31.2/gdk-pixbuf/tmp-introspectpP8z9c/GdkPixbuf-2.0', u'-export-dynamic', '-O2', '-mtune=native', '-DG_DISABLE_SINGLE_INCLUDES', '-O2', '-mtune=native', '-Wall', u'tmp-introspectpP8z9c/tmp/soft/spack-stage/spack-stage-EYaUqi/gdk-pixbuf-2.31.2/gdk-pixbuf/tmp-introspectpP8z9c/GdkPixbuf-2.0.o', '-L.', 'libgdk_pixbuf-2.0.la', u'-L/share/apps/conda/envs/conda2/lib', u'-lgio-2.0', u'-lgobject-2.0', u'-Wl,--export-dynamic', u'-lgmodule-2.0', u'-pthread', u'-lrt', u'-lglib-2.0']' returned non-zero exit status 1
      >> 465   make[4]: *** [GdkPixbuf-2.0.gir] Error 1
         466   make[4]: Leaving directory `/tmp/soft/spack-stage/spack-stage-EYaUqi/gdk-pixbuf-2.31.2/gdk-pixbuf'
      >> 467   make[3]: *** [all-recursive] Error 1
         468   make[3]: Leaving directory `/tmp/soft/spack-stage/spack-stage-EYaUqi/gdk-pixbuf-2.31.2/gdk-pixbuf'
      >> 469   make[2]: *** [all] Error 2
         470   make[2]: Leaving directory `/tmp/soft/spack-stage/spack-stage-EYaUqi/gdk-pixbuf-2.31.2/gdk-pixbuf'
      >> 471   make[1]: *** [all-recursive] Error 1
         472   make[1]: Leaving directory `/tmp/soft/spack-stage/spack-stage-EYaUqi/gdk-pixbuf-2.31.2'
      >> 473   make: *** [all] Error 2
    
    See build log for details:
      /share/apps/spack/var/spack/stage/gdk-pixbuf-2.31.2-olieob7lmo7tknggsqrqkzw76q3xitc4/gdk-pixbuf-2.31.2/spack-build.out

GCC 7.2.0

    ==> Installing pango
    ==> Fetching http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.40.3.tar.xz
    ######################################################################## 100.0%
    ==> Staging archive: /share/apps/spack/var/spack/stage/pango-1.40.3-neobrmpfp5tuwu2az5r3p4pm3l4opfyl/pango-1.40.3.tar.xz
    ==> Created stage in /share/apps/spack/var/spack/stage/pango-1.40.3-neobrmpfp5tuwu2az5r3p4pm3l4opfyl
    ==> No patches needed for pango
    ==> Building pango [AutotoolsPackage]
    ==> Executing phase: 'autoreconf'
    ==> Executing phase: 'configure'
    ==> Executing phase: 'build'
    ==> Error: ProcessError: Command exited with status 2:
        'make' '-j24'
    
    11 errors found in build log:
         [ ... ]
         662      dx = b->point.x - a->point.x;
         663      ~~~^~~~~~~~~~~~~~~~~~~~~~~~~
         664   cairotwisted.c:221:42: note: âcurrent_point.point.xâ was declared here
         665      cairo_path_data_t *data, last_move_to, current_point;
         666                                             ^~~~~~~~~~~~~
         667     CCLD     cairotwisted
      >> 668   /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-7.2.0/harfbuzz-1.4.6-3a4icz3flas7hgiscrzhxufvazbqrzfc/lib/libharfbuzz.so: undefined reference to `FT_Get_Var_Blend_Coordinates'
      >> 669   collect2: error: ld returned 1 exit status
      >> 670   make[2]: *** [cairosimple] Error 1
         671   make[2]: *** Waiting for unfinished jobs....
      >> 672   /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-7.2.0/harfbuzz-1.4.6-3a4icz3flas7hgiscrzhxufvazbqrzfc/lib/libharfbuzz.so: undefined reference t
    o `FT_Get_Var_Blend_Coordinates'
      >> 673   collect2: error: ld returned 1 exit status
      >> 674   make[2]: *** [cairoshape] Error 1
      >> 675   /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-7.2.0/harfbuzz-1.4.6-3a4icz3flas7hgiscrzhxufvazbqrzfc/lib/libharfbuzz.so: undefined reference to `FT_Get_Var_Blend_Coordinates'
      >> 676   collect2: error: ld returned 1 exit status
      >> 677   make[2]: *** [cairotwisted] Error 1
         678   make[2]: Leaving directory `/tmp/soft/spack-stage/spack-stage-hF9ENB/pango-1.40.3/examples'
      >> 679   make[1]: *** [all-recursive] Error 1
         680   make[1]: Leaving directory `/tmp/soft/spack-stage/spack-stage-hF9ENB/pango-1.40.3'
      >> 681   make: *** [all] Error 2
    
    See build log for details:
      /share/apps/spack/var/spack/stage/pango-1.40.3-neobrmpfp5tuwu2az5r3p4pm3l4opfyl/pango-1.40.3/spack-build.out

### Steps to reproduce the issue

```console
$ spack install emacs %gcc@4.4.7+X
```

### Information on your system
Rocks cluster 6.2/CentOS 6.6
gcc-4.4.7 is from the OS. All the other gcc versiosn were installed by Spack.

**Comment by scheibelp** [comment]
Regarding the gcc 7.2.0 failure, would you be able to retry with `spack -d install --keep-stage...` and attach the `spack-cc-pango...out.log` file here along with the `config.log` file from pango?

As a sanity check: do you have any external packages defined in `packages.yaml`?

**Comment by baip** [comment]
I updated Spack to match the latest `develop` branch, and did `spack clean; spack -d install --keep-stage emacs %gcc@7.2.0.default+X`, but now it fails at `gdk-pixbuf` (with error messages very similar to that of GCC 6.4.0 from my original post). I've attached `spack-cc-gdk-pixbuff...out.log` and `config.log` [here](https://gist.github.com/baip/3e3899111bfc4cf96a04426d3b97ce12).

My `packages.yaml` is only lightly customized:

    packages:
      cmake:
        paths:
          cmake@3.9.4: /share/apps/cmake-3.9.4
        buildable: False
      openssl:
        paths:
          openssl@1.0.2j: /usr
        buildable: False
      perl:
        paths:
          perl@5.10.1: /usr
        buildable: False
      python:
        modules:
          python@2.7.13: [python/conda2]
        paths:
          python@2.7.13: /share/apps/conda/envs/conda2
        buildable: False

And `compilers.yaml`:

    compilers:
    - compiler:
        modules: [binutils-2.28-gcc-4.4.7-oh67qvy, gcc-7.2.0-gcc-4.4.7-d3wacuq]
        operating_system: centos6
        paths:
          cc: /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/gcc-7.2.0-d3wacuqrhhxbfkvpjbehjtkvksmm5kf2/bin/gcc
          cxx: /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/gcc-7.2.0-d3wacuqrhhxbfkvpjbehjtkvksmm5kf2/bin/g++
          f77: /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/gcc-7.2.0-d3wacuqrhhxbfkvpjbehjtkvksmm5kf2/bin/gfortran
          fc: /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/gcc-7.2.0-d3wacuqrhhxbfkvpjbehjtkvksmm5kf2/bin/gfortran
        spec: gcc@7.2.0.default
        target: x86_64

**Comment by scheibelp** [comment]
I think the external python path at `/share/apps/conda/envs/conda2` is interfering with `gdk-pixbufs` resolution of linker flags, in your `config.log` I see the following:

```
GDK_PIXBUF_DEP_LIBS='-L/share/apps/conda/envs/conda2/lib -lgmodule-2.0 -pthread -lrt -lgio-2.0 -lgobject-2.0 -lglib-2.0 -L/share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-7.2.0.default/libpng-1.6.29-yxbvqcjnqgksmbncg2onnojrzuqxza2d/lib -lpng16 -lm'
```

Whereas for my build of `gdk-pixbuf` it is:

```
GDK_PIXBUF_DEP_LIBS='-L/.../spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/glib-2.53.1-2o7xyawzjdfznidvacpls6vcuwhbamky/lib -lgmodule-2.0 -pthread -lrt -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -L/.../spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/libpng-1.6.29-6ex3sqm7l4k4lrpkh3tn5q6dsx5cusng/lib -lpng16 -lm'
```

This line in your `config.log` is missing `-lintl`, which appears to be the source of errors of the form `undefined reference reference to to libintl_gettext`.

It appears to have found some alternative in `/share/apps/conda/envs/conda2`. I'm wondering if ordering `PKG_CONFIG_PATH` entries such that external packages come last might help. I should have a chance to add a patch here later today.

**Comment by scheibelp** [comment]
> I'm wondering if ordering PKG_CONFIG_PATH entries such that external packages come last might help. I should have a chance to add a patch here later today.

I added https://github.com/spack/spack/pull/6755 to try this - would you let me know if that gets any better results?

I should also say, if you get these errors when removing the external python definition (and particularly `/share/apps/conda/envs/conda2`) then I'm likely wrong about what the error is.

**Comment by baip** [comment]
Thanks for looking into this, @scheibelp! With #6755 it still fails at the same point. However, it is indeed due to the external Python package. Once I commented out the relevant lines, `gdk-pixbuf` builds fine and the problem is back to `pango`. Please see [here](https://gist.github.com/baip/3e3899111bfc4cf96a04426d3b97ce12) with the new log files.

**Comment by scheibelp** [comment]
> Once I commented out the relevant lines, gdk-pixbuf builds fine and the problem is back to pango

I assume you mean

> /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-7.2.0/harfbuzz-1.4.6-3a4icz3flas7hgiscrzhxufvazbqrzfc/lib/libharfbuzz.so: undefined reference to `FT_Get_Var_Blend_Coordinates'

I want to make sure because that's a linker problem and the linked wrapper log stops on a `cc` call (that's not necessarily meaningful because that stream can be terminated prematurely).

Generally this error appears to relate to using an older version of freetype, but the log indicates that the newest is being used.

**Comment by baip** [comment]
Yes, that's the error; this is the same error I reported in my original post for GCC 7.2.0. Actually the `spack-cc` log file ends with a `ccld` call. The website view probably truncated it.

**Comment by scheibelp** [comment]
OK yep I missed that. I notice that `/share/apps/conda/envs/conda2/lib` is still making it into the linker lines. The `pango` configuration may be automatically adding it because it finds something it needs there, potentially by searching through environment variables. Firstly, are you using `--dirty`? Secondly, could you attach `spack-build.env` here?

I should say I won't likely get another chance to look at this until next year (Jan. 2 2018)

**Comment by baip** [comment]
I [added ](https://gist.github.com/baip/3e3899111bfc4cf96a04426d3b97ce12) `spack-build.env`. I didn't use `--dirty`, but the python interpreter for running `spack` indeed comes from `conda`.

**Comment by scheibelp** [comment]
A few things came up which sidetracked me but I plan on taking a another close look at this tomorrow

**Comment by scheibelp** [comment]
When I look at the last line of the compiler wrapper output log (https://gist.github.com/baip/3e3899111bfc4cf96a04426d3b97ce12/raw/cfcc30fdb8edcc9b7324be061ebe56c908908a6e/spack-cc-pango-zzlyszr.out.log) it is a `cc` invocation - is the error message different now?

**Comment by baip** [comment]
Thanks for looking into this again. For some reason, when I added `spack-build.env` using the gist web interface, `spack-cc-pango-zzlyszr.out.log` got truncated. I've now reverted this unintentional change from the revision history.

Also, since Spack runs on Python 2.6, I was able to use the system Python and let Spack build everything `emacs+X` needed. Unsurprisingly, it was a success (with GCC 7.2.0). In the last failed attempt (corresponding to the [logs](https://gist.github.com/baip/3e3899111bfc4cf96a04426d3b97ce12)), I activated `conda` in `.bashrc` file, and use Python from conda to run Spack. I did not use `--dirty` or had external packages though.

**Comment by alalazo** [comment]
I just verified that `emacs` builds fine at  3cd6ca02d2d58c42d6864b25ed5e4479557eaa8c I'll be closing this issue as stale and very likely tied to some customization of the environment (in particular external `python`). We should have already issues that are tracking problems with "extendable" external packages, but feel free to reopen if you feel like there's anything else to be resolved here.
