### ISSUE TITLE
Inconsistent spec parsing in `spack env`

### ISSUE THREAD

**Issue by citibeth** [spack/spack#659]
The command:

```
spack env py-numpy+blas^atlas
```

works.  The command:

```
spack env py-numpy +blas ^atlas
```

breaks with the error:

```
Traceback (most recent call last):
  File "/home/rpfische/spack/bin/spack", line 176, in <module>
    main()
  File "/home/rpfische/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/home/rpfische/spack/lib/spack/spack/cmd/env.py", line 70, in env
    os.execvp(cmd[0], cmd)
  File "/usr/lib64/python2.7/os.py", line 344, in execvp
    _execvpe(file, args)
  File "/usr/lib64/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
```

Note that on line 70 (69) of env.py, the debugging command `print cmd[0], cmd` yields:

```
+blas ['+blas', '^atlas']
```

**Comment by citibeth** [comment]
Here's another related bug in `spack diy` parsing.  The command:
```
 1119  spack spec py-giss@local^py-numpy+blas+lapack^atlas^python@3:
```
works.  But the command:
```
 1121  spack diy py-giss@local^py-numpy+blas+lapack^atlas^python@3:
```
crashes Spack.  See attached log files.

[log-spec.txt](https://github.com/LLNL/spack/files/190990/log-spec.txt)
[log-diy.txt](https://github.com/LLNL/spack/files/190991/log-diy.txt)

**Comment by adamjstewart** [comment]
@citibeth @alalazo I'm wondering if we should consider this bug to be "fixed" or not. Although:
```console
$ spack env py-numpy +blas ^atlas
```
still results in an error, the following:
```console
$ spack env py-numpy +blas ^atlas --
```
works fine. The help message for `spack build-env` also mentions the use of `--` for multi-word specs. I see that @alalazo tried another approach in #7743 but that never got merged. Maybe another technique would be to first try things as is, except OSErrors, then try parsing the entire command-line as a spec? I can submit a PR for that if that's the desired behavior.

**Comment by alalazo** [comment]
I'll close this as an issue but keep #10159 open for discussion. Feel free to undo if you disagree.
