### ISSUE TITLE
xrootd needs openssl

### ISSUE THREAD

**Issue by briedel** [spack/spack#6601]
xrootd needs openssl headers to compile for 4.6.0

**Comment by alalazo** [comment]
Just a minor comment, but personally I would prefer to see the symptoms along with the diagnosis. This facilitate reproducing the issue, confirming it and eventually solve it. 

That said, looking briefly [here](https://github.com/xrootd/xrootd/tree/v4.7.1), it seems that adding:
```python
depends_on('openssl')
```
to `xrootd` may solve the issue. Could you try it and submit a PR if it works?
