### ISSUE TITLE
[BUG] Specifying version number in extends('python')

### ISSUE THREAD

**Issue by citibeth** [spack/spack#661]
I have a Python library that requires Pyhthon3.  Here is `package.py`:

```
from spack import *

class PyGiss(Package):
    """Misc. Python Stuff."""

    homepage = "https://github.com/citibeth/pygiss"
    url      = "https://github.com/citibeth/pygiss/tarball/v0.1.0"

    version('0.1.0', '0f6b5c6d2635106963878b4d4e06169c')

    extends('python@3:')

    depends_on('py-numpy+blas+lapack')
    depends_on('py-netcdf')

    def install(self, spec, prefix):
        python('setup.py', 'install', '--prefix=%s' % prefix)
```

The command:

```
 1119  spack spec py-giss@local^py-numpy+blas+lapack^atlas
```

works, and correctly understands that we need to be using Python3.  But the command:

```
 1121  spack diy py-giss@local^py-numpy+blas+lapack^atlas
```

crashes Spack.  Same behavior on `spack install`.  See attached log files.  The workaround for now is to put `extends('python')` in `package.py`, and supply `^python@3:` on the command line.

[log-spec.txt](https://github.com/LLNL/spack/files/190990/log-spec.txt)
[log-diy.txt](https://github.com/LLNL/spack/files/190991/log-diy.txt)

**Comment by alalazo** [comment]
`py-gyss` is not in the built-in repository. `cram` does something similar to the description above and builds fine for me.
