### ISSUE TITLE
Set PYTHONNOUSERSITE?

### ISSUE THREAD

**Issue by ax3l** [spack/spack#6611]
Since Spack has control over basically any dependency that can be build inside a user's `.local/`, setting the environment var [`PYTHONNOUSERSITE`](https://docs.python.org/2/using/cmdline.html#environment-variables) (or `PYTHONUSERBASE=/dev/null`) for python installs (and loads) (Python 2.6+ feature) could help to isolate our installs better from the outside world™.

Any concerns?

ccing @tgamblin @hartzell @junghans @alalazo @adamjstewart 

Related (tricky) issues:
- https://github.com/pypa/setuptools/issues/1229
- https://github.com/spack/spack/issues/6558

**Comment by adamjstewart** [comment]
We are already running `python setup.py --no-user-cfg`. Perhaps those are equivalent?

**Comment by xjrc** [comment]
I've only had the chance to look this over for a couple of minutes, but it seems like a promising option that may help slim down the code in the Python install script.  In particular, it feels like `PYTHONUSERSITE` could be used to better and more easily control where local packages are installed, which would alleviate some of that burden from Python's `package.py`. If I'm understanding that correctly, then I'm certainly in favor of leveraging `PYTHONUSERSITE` in Spack's Python install scripts.

**Comment by ax3l** [comment]
Cool, shall we add `PYTHONNOUSERSITE` (or `PYTHONUSERBASE=/dev/null`) then? (and where?) :)

**Comment by ax3l** [comment]
The equivalent cmd line flag for our calls to `python` would be `-s`:

> -s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE

**Comment by alalazo** [comment]
Closed by #7065
