### ISSUE TITLE
spack checksum failed 

### ISSUE THREAD

**Issue by fanne-stat** [spack/spack#6637]
The package jellyfish now have all its source code files on github after version 2.0. The url is like "https://github.com/gmarcais/Jellyfish/releases/download/v2.2.7/jellyfish-2.2.7.tar.gz". 

What I was trying to do is to add this url as list_url:
```python
homepage = "http://www.cbcb.umd.edu/software/jellyfish/"
url      = "http://www.cbcb.umd.edu/software/jellyfish/jellyfish-1.1.11.tar.gz"
list_url = "https://github.com/gmarcais/Jellyfish/releases/download/"
list_depth = 2
```

But `spack checksum` cannot find those source code files:

```console
spack -k checksum jellyfish
==> Warning: You asked for --insecure. Will NOT check SSL certificates.
==> Found 1 version of jellyfish:

  1.1.11  http://www.cbcb.umd.edu/software/jellyfish/jellyfish-1.1.11.tar.gz

==> How many would you like to checksum? (default is 1, q to abort)
```

Only 1.1.11 from url is found. 

And if the old url is set to be the list_url and the url is set to jellyfish 2.2.7, then spack can find 1.1.11 and 2.2.x.

```python
homepage = "http://www.cbcb.umd.edu/software/jellyfish/"
url      = "https://github.com/gmarcais/Jellyfish/releases/download/v2.2.7/jellyfish-2.2.7.tar.gz"
list_url = "http://www.cbcb.umd.edu/software/jellyfish/"
```

```console
$ spack -k checksum jellyfish
==> Warning: You asked for --insecure. Will NOT check SSL certificates.
==> Found 8 versions of jellyfish:

  2.2.7          https://github.com/gmarcais/Jellyfish/releases/download/v2.2.7/jellyfish-2.2.7.tar.gz
  2.2.6          https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz
  2.2.5          https://github.com/gmarcais/Jellyfish/releases/download/v2.2.5/jellyfish-2.2.5.tar.gz
  2.2.4          https://github.com/gmarcais/Jellyfish/releases/download/v2.2.4/jellyfish-2.2.4.tar.gz
  2.2.3-CentOS6  https://github.com/gmarcais/Jellyfish/releases/download/v2.2.3/jellyfish-2.2.3-CentOS6.tar.gz
  2.2.3          https://github.com/gmarcais/Jellyfish/releases/download/v2.2.3/jellyfish-2.2.3.tar.gz
  2.2.0          https://github.com/gmarcais/Jellyfish/releases/download/v2.2.0/jellyfish-2.2.0.tar.gz
  1.1.11         http://www.cbcb.umd.edu/software/jellyfish/jellyfish-1.1.11.tar.gz

==> How many would you like to checksum? (default is 1, q to abort) q
``` 

So is there anything special with the url "https://github.com/gmarcais/Jellyfish/releases/download/" that makes the checksum fail?

**Comment by adamjstewart** [comment]
> So is there anything special with the url "https://github.com/gmarcais/Jellyfish/releases/download/" that makes the checksum fail?

Try visiting that URL and it should be pretty obvious what the problem is. `spack checksum` works by visiting a URL and looking for links on that webpage with names that look like tarballs of the same software. The reason it works when you put it in the `url` instead of `list_url` is because we have special logic in Spack that says "if this looks like a GitHub URL, search the releases page instead". See https://github.com/spack/spack/blob/develop/lib/spack/spack/url.py#L65 if you're curious.
