### ISSUE TITLE
Buildcache fails relocating gaudi

### ISSUE THREAD

**Issue by JavierCVilla** [spack/spack#6677]
Running `spack buildcache install gaudi`, `patchelf` fails when trying to relocate one of the files: 

### Expected Result

`gaudi` package installed and relocated in my prefix path

### Actual Result

`patchelf` command reports a `strange: no string table` error message:

```
==> Installing buildcache for spec gaudi@v28r1%gcc@6.2.0 build_type=RelWithDebInfo arch=linux-scientificcernslc6-x86_64 
==> Relocating package from
  /my/local/buildnode/spack/opt/spack to /different/node/x86_64-slc6-gcc62-opt.
strange: no string table
==> Error: Command exited with status 1:
'/different/node/opt/patchelf-0.9-zjxrrn5fdligyg263rba6uzcqrr3uyzj/bin/patchelf' '--print-rpath' '/different/node/test/x86_64-slc6-gcc62-opt/linux-scientificcernslc6-x86_64/gcc-6.2.0/gaudi-v28r1-v32rnk3hdvnjr3nyo4qt7emecdpbxbe6/lib/libPartPropSvc.so.dbg'
```

Same process works for other packages, I see this problem only with `gaudi` which spack recipe is in [hep-spack repo](https://github.com/HEP-SF/hep-spack/blob/master/packages/gaudi/package.py)

### Steps to reproduce the issue

```console
$ spack install gaudi %gcc@6.2.0 # in my case i'm building against external packages
$ spack buildcache create -d ./tarballs gaudi

# Send ./tarballs to a different node
# In that node
$ spack buildcache install $package
```
### Information on your system

 1. Platform: slc6 with gcc62
 2. Building against a bunch of packages remotely installed in a cvmfs server 

@gartung  Have you faced this problem by any chance?

**Comment by gartung** [comment]
My guess is that file libPartPropSvc.so.dbg identifies this as a binary that might need relocating but it is not a elf binary. Can you send the output of 
file -b -h libPartPropSvc.so.dbg

**Comment by JavierCVilla** [comment]
This is the output:

```console
$ file -b -h libPartPropSvc.so.dbg
ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, not stripped
```

**Comment by gartung** [comment]
Can you run patchelf or elfedit on it to see if it is a valid elf object.

**Comment by JavierCVilla** [comment]
In addition to my previous answer:

```console
$ readelf -d libPartPropSvc.so.dbg

There is no dynamic section in this file.
```

The same works for the library without `.dbg`:

```console
$ readelf -d libPartPropSvc.so

Dynamic section at offset 0x27ba0 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libGaudiKernel.so]
 0x0000000000000001 (NEEDED)             Shared library: [libGaudiPluginService.so]
 0x0000000000000001 (NEEDED)             Shared library: [libHepPDT.so]
...
```

Indeed this file is not executable:

```console
$ ls -lsa libPartPropSvc.so.dbg
1 -rw-r--r-- 1 user user 1590120 Dec 13 11:41 libPartPropSvc.so.dbg
```
`patchelf` without `--print-rpath` does nothing but it does not fail:

```console
$ patchelf libPartPropSvc.so.dbg
```

Is it necessary to relocate those dbg files?

**Comment by gartung** [comment]
https://github.com/spack/spack/blob/develop/lib/spack/spack/relocate.py#L225 

It is a very simple check. I have been meaning to add a check to see if the install path string exists in the elf object.

I will work on a fix.

**Comment by gartung** [comment]
Can you try this fix
https://github.com/spack/spack/pull/6679

**Comment by JavierCVilla** [comment]
It still fails. Already commented on #6679

**Comment by gartung** [comment]
This has been addressed.
