### ISSUE TITLE
Error using versions

### ISSUE THREAD

**Issue by kdfred** [spack/spack#6690]
If you want to report a build error for some package, or a bug in core please use the following template as a guideline:

-----

Summary

### Expected Result

Listing version of gnuplot

### Actual Result

Got error: 
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Error: 'HTTPError' object has no attribute 'reason'

### Steps to reproduce the issue

```console
$ spack versions gnuplot
```

### Information on your system

Red Hat Server

-----

**Comment by adamjstewart** [comment]
This should be fixed by #6774.
