### ISSUE TITLE
Spack cannot mirror without a compiler

### ISSUE THREAD

**Issue by sknigh** [spack/spack#6730]
### Expected Result

```spack -k mirror create --directory /mirror vim``` should add the latest vim tarball to a mirror.

### Actual Result

Spack complains that it can't find a compiler that it will never need

### Steps to reproduce the issue
``` bash
bash-4.3# spack -k mirror create --directory /mirror vim
==> Warning: You asked for --insecure. Will NOT check SSL certificates.
==> Error: Spack could not find any compilers!
```

### Information on your system

Alpine 3.6 container.

**Comment by alalazo** [comment]
This has been solved by @scheibelp in #5153, closing.
