### ISSUE TITLE
boost 1.65.1 fails to configure on Fedora Linux 27

### ISSUE THREAD

**Issue by leek2** [spack/spack#6752]
Summary

### Expected Result

boost 1.65.1 to build and install

### Actual Result

[leek2@jetjaguar spack]$ spack install boost@1.65.1
==> bzip2 is already installed in /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/bzip2-1.0.6-payuef3oghfwc6xmay2cwisxw5b4agwg
==> zlib is already installed in /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/zlib-1.2.11-5kriwfigiyx6c2pfgzgbclwthzmdou7q
==> Installing boost
==> Using cached archive: /home/leek2/spack/var/spack/cache/boost/boost-1.65.1.tar.bz2
==> Staging archive: /home/leek2/spack/var/spack/stage/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/boost_1_65_1.tar.bz2
==> Created stage in /home/leek2/spack/var/spack/stage/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6
==> Applied patch python_jam.patch
==> Building boost [Package]
==> Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    './b2' 'install' 'threading=multi' '-j' '4' 'variant=release' '-s' 'BZIP2_INCLUDE=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/bzip2-1.0.6-payuef3oghfwc6xmay2cwisxw5b4agwg/include' '-s' 'BZIP2_LIBPATH=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/bzip2-1.0.6-payuef3oghfwc6xmay2cwisxw5b4agwg/lib' '-s' 'ZLIB_INCLUDE=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/zlib-1.2.11-5kriwfigiyx6c2pfgzgbclwthzmdou7q/include' '-s' 'ZLIB_LIBPATH=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/zlib-1.2.11-5kriwfigiyx6c2pfgzgbclwthzmdou7q/lib' 'link=static,shared' '--layout=system' 'toolset=gcc'
See build log for details:
  /home/leek2/spack/var/spack/stage/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/boost_1_65_1/spack-build.out

### Information on your system

This includes:

I'm using Fedora Linux 27, Gcc, g++, and gfortran versions 7.2.1.
I cloned the git repo and just ran "spack install boost@1.65.1"  All the packages built until boost.

-----
The problem appears to be with the cc wrapper scripts.  I was able to build and install boost using the same inputs spack gave, as long as I removed /home/leek2/spack/lib/spack/env/gcc from the PATH.  Below is the output from the spack-build.out log.  You can see the configuration is completely screwed up, and it claims gcc does not support C++ programs.

### spack-build.out

==> Executing phase: 'install'
==> './bootstrap.sh' '--prefix=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6' '--with-toolset=gcc' '--with-libraries=locale,random,wave,atomic,serialization,iostreams,regex,date_time,exception,log,thread,chrono,system,timer,signals,program_options,filesystem,test,math'
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxx86_64/b2
Unicode/ICU support for Boost.Regex?... not found.
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/build/doc/html/index.html

==> './b2' '--clean'
  File "<string>", line 1
    from sys import abiflags; print(abiflags, end='')
                                                 ^
SyntaxError: invalid syntax
Performing configuration checks

    - 32-bit                   : no
    - 64-bit                   : no
    - arm                      : no
    - mips1                    : no
    - power                    : no
    - sparc                    : no
    - x86                      : no
    - combined                 : no

Building the Boost C++ Libraries.

    - symlinks supported       : yes
    - zlib                     : no
    - bzip2                    : no
    - lzma                     : no
    - iconv (libc)             : no
    - iconv (separate)         : no
    - icu                      : no
    - icu (lib64)              : no
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
    - native-atomic-int32-supported : no
    - native-syslog-supported  : no
    - pthread-supports-robust-mutexes : no
    - compiler-supports-visibility : no
    - has_icu builds           : no
    - lockfree boost::atomic_flag : no
    - gcc visibility           : no
    - long double support      : no
    - zlib                     : no
    - bzip2                    : no
    - lzma                     : no
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
...found 1 target...
...updating 1 target...
...updated 1 target...
==> './b2' 'install' 'threading=multi' '-j' '4' 'variant=release' '-s' 'BZIP2_INCLUDE=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/bzip2-1.0.6-payuef3oghfwc6xmay2cwisxw5b4agwg/include' '-s' 'BZIP2_LIBPATH=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/bzip2-1.0.6-payuef3oghfwc6xmay2cwisxw5b4agwg/lib' '-s' 'ZLIB_INCLUDE=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/zlib-1.2.11-5kriwfigiyx6c2pfgzgbclwthzmdou7q/include' '-s' 'ZLIB_LIBPATH=/home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/zlib-1.2.11-5kriwfigiyx6c2pfgzgbclwthzmdou7q/lib' 'link=static,shared' '--layout=system' 'toolset=gcc'
  File "<string>", line 1
    from sys import abiflags; print(abiflags, end='')
                                                 ^
SyntaxError: invalid syntax
Performing configuration checks

    - 32-bit                   : no  (cached)
    - 64-bit                   : no  (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : no  (cached)
    - combined                 : no  (cached)
    - symlinks supported       : yes
    - zlib                     : no  (cached)
    - bzip2                    : no  (cached)
    - lzma                     : no  (cached)
    - iconv (libc)             : no  (cached)
    - iconv (separate)         : no  (cached)
    - icu                      : no  (cached)
    - icu (lib64)              : no  (cached)
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
    - native-atomic-int32-supported : no  (cached)
    - native-syslog-supported  : no  (cached)
    - pthread-supports-robust-mutexes : no  (cached)
    - compiler-supports-visibility : no  (cached)
    - has_icu builds           : no  (cached)
    - lockfree boost::atomic_flag : no  (cached)
    - gcc visibility           : no  (cached)
    - long double support      : no  (cached)
    - zlib                     : no  (cached)
    - bzip2                    : no  (cached)
    - lzma                     : no  (cached)
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : not building
    - context                  : not building
    - coroutine                : not building
    - date_time                : building
    - exception                : building
    - fiber                    : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : building
    - locale                   : building
    - log                      : building
    - math                     : building
    - metaparse                : not building
    - mpi                      : not building
    - program_options          : building
    - python                   : not building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - signals                  : building
    - stacktrace               : not building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : building
    - type_erasure             : not building
    - wave                     : building

...patience...
...patience...
...patience...
...patience...
...patience...
...found 34226 targets...
...updating 14353 targets...
common.mkdir /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/include
common.mkdir /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/lib
common.mkdir bin.v2/libs/atomic
common.mkdir bin.v2/libs/system/build/gcc/release
common.mkdir /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/include/boost
common.mkdir bin.v2/libs/chrono
common.copy /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/include/boost/weak_ptr.hpp
common.mkdir bin.v2/libs/system/build/gcc/release/link-static
common.copy /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/include/boost/visit_each.hpp
common.mkdir bin.v2/libs/atomic/build
common.copy /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/include/boost/wave.hpp
common.mkdir bin.v2/libs/system/build/gcc/release/link-static/threading-multi
common.copy /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/include/boost/version.hpp
common.mkdir bin.v2/libs/atomic/build/gcc
common.copy /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/include/boost/variant.hpp
common.copy /home/leek2/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/boost-1.65.1-guqlwv6du3gzozhddo23k47hkyyfd7q6/include/boost/utility.hpp
gcc.compile.c++ bin.v2/libs/system/build/gcc/release/link-static/threading-multi/error_code.o
ERROR: Compiler 'gcc@7.2.1' does not support compiling C++ programs.

    "/home/leek2/spack/lib/spack/env/gcc/g++"   -O3 -finline-functions -Wno-inline -Wall -pedantic -pthread  -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_STATIC_LINK=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/system/build/gcc/release/link-static/threading-multi/error_code.o" "libs/system/src/error_code.cpp"

...failed gcc.compile.c++ bin.v2/libs/system/build/gcc/release/link-static/threading-multi/error_code.o...

**Comment by aprokop** [comment]
Weird. I assume this is Fedora 27 specific as I was able to compile boost 1.65.1 yesterday with Fedora 26 and using the same 7.2.1 gcc.

**Comment by leek2** [comment]
Well, the first time I ran spack I didn't have g++ installed yet (For some reason the machine came with gcc installed, but not g++.) .  Is it possible that the spack wrapper doesn't realize g++ exists?

**Comment by scheibelp** [comment]
> Is it possible that the spack wrapper doesn't realize g++ exists?

That could be it. Try removing `~/.spack/linux/compilers.yaml` (which if you check the entry of `gcc@7.2.1` will likely be missing a `cxx` entry) and run `spack compiler find` (which should regenerate that file for you with a `cxx` entry for `gcc@7.2.1`).

**Comment by leek2** [comment]
Ah, that's done it.  Maybe projects requiring a particular compiler should let you know if it doesn't exist, or automatically rerun the check?

Although, spack compiler find didn't pick up gfortran for some reason.  Any idea on that one?

**Comment by scheibelp** [comment]
> Maybe projects requiring a particular compiler should let you know if it doesn't exist, or automatically rerun the check?

That would be a useful for sure but currently the required compilers aren't recorded in the `package.py` for example, so determining this suggestion would require examining the error output.

> spack compiler find didn't pick up gfortran for some reason. Any idea on that one?

I'm not immediately certain: it *should* be fine adding fortran compilers. If you run `spack -d compiler find` it will include output about what compiler binaries it is checking, e.g.:

```
==> '/usr/local/bin/gfortran-4.6.1' '--version'
==> '/usr/local/bin/g++' '--version'
```

I'm curious if you see messages related to the relevant fortran compiler. That being said this is probably worthy of a new issue. The original issue in this thread appears to be solved so I will close this.
