### ISSUE TITLE
is Cython needed for mpi4py 3.0?

### ISSUE THREAD

**Issue by cyrush** [spack/spack#6760]
On mpi4py's web-page, they mention Cython is only needed when developing mpi4py, its not needed to build their releases

mpi4py's ``setup.py`` logic seems to confirm this:

```
def build_sources(cmd):
    from distutils.errors import DistutilsError
    has_src = os.path.exists(os.path.join(
        topdir, 'src', 'mpi4py.MPI.c'))
    has_vcs = (os.path.isdir(os.path.join(topdir, '.git')) or
               os.path.isdir(os.path.join(topdir, '.hg' )))
    if (has_src and not has_vcs and not cmd.force): return
    # mpi4py.MPI
    source = 'mpi4py.MPI.pyx'
    depends = ['mpi4py/MPI/*.pyx',
               'mpi4py/MPI/*.pxd',
               'mpi4py/MPI/*.pxi',]
    destdir_h = os.path.join('mpi4py', 'include', 'mpi4py')
    run_cython(source, depends, destdir_h=destdir_h,
               wdir='src', force=cmd.force, VERSION=CYTHON)
```

I checked and their source release for 3.0.0 does contain `src/mpi4py.MPI.c' see the early return:

`if (has_src and not has_vcs and not cmd.force): return`

it seems that the development ver (``develop``) would require cython, but its only being added when 3.0.0 is built:

`    depends_on('py-cython', when='@3.0.0:', type='build')`

**Comment by adamjstewart** [comment]
@shuds13 Would you like to comment on this? It looks like you added this dependency in #5798. Based on your comment "Add cython dependency for develop version" it sounds like this is really only needed for develop.

**Comment by cyrush** [comment]
thanks!
