### ISSUE TITLE
No trusted download methods for hg or svn

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#6785]
If you take a look at http://spack.readthedocs.io/en/latest/packaging_guide.html#fetching-from-code-repositories, you'll see that for Git we walk through a long list of options for fetching from Git repositories, some of which are "trusted" and some of which are "untrusted". But for Mercurial and Subversion, all options are "untrusted, and not recommended". If none of the options for fetching from Mercurial and Subversion repositories are recommended, what are packagers supposed to do? Is there really no way to fetch from these repositories using a hash or checksum?

**Comment by tgamblin** [comment]
Mercurial is like `git`.  It checks integrity using a hash, so if you provide a revision hash, you sould be able to check things.  The important thing is that the revision hash doesn't come from the source server.

To my knowledge, `svn` really doesn't have a standard way to do this.  There is no Merkle-hash like `git` and `mercurial` use, so you don't get the same guarantee.  The typical thing to do for `svn` repositories is to use `https` and rely on SSL trust, but that is not as convenient or as reliable as simply checking a hash.

As you pointed out on the mailing list, the hash is only as trustworthy as the people who provided it.  We know which github users made commits to Spack and we can at least blacklist them if we see people submitting compromises.  Also, and this is a next-year kind of thing, I would like to start scanning tarballs that people submit in Spack packages.  There are services that do this, and I think we can use them on Spack.  It's something I'm looking into.  This would be much better than just accepting PRs like we (and most other PMs) do now.

With svn, there isn't a way that I know of to say for sure that what you check out at install time is the same as what the PR author intended.
