### ISSUE TITLE
Slack channel sign-up app error

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#6799]
Sign-up link to spack slack channel leads to a page where some App error is reported. It seems sign-up thing is broken.

### Steps to reproduce the issue

Click on 'Sign-Up here' link under Slack Channel section of main README.md

### Information on your system

Firefox 57.0.1, Chrome 63.0, Linux Mint 18.2

**Comment by adamjstewart** [comment]
The Slack badge seems to be working again?

**Comment by Sinan81** [comment]
yep, it works now. Thanks.

**Comment by vdikan** [comment]
I regret to inform that the app seems broken again.
