### ISSUE TITLE
Travis CI disk quota exceeded issue

### ISSUE THREAD

**Issue by stefanosoffia** [spack/spack#6806]
Spack regression test setup based on Travis CI are failing with the error:

```
Worker information
hostname: ea47cf34-8a54-44a9-8c71-0e53a3e00d1f@1.i-0ec5403-production-2-worker-org-ec2.travisci.net
version: v3.4.0 https://github.com/travis-ci/worker/tree/ce0440bc30c289a49a9b0c21e4e1e6f7d7825101
instance: 41ad145 travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 640.402918ms
oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"
```

See for example https://travis-ci.org/spack/spack/jobs/323820365 from PR #6805.
Other PR seem to experience the same issue, see e.g. PR #6804.

**Comment by adamjstewart** [comment]
See https://github.com/travis-ci/travis-ci/issues/8991 and https://www.traviscistatus.com/incidents/yxqx6brg5nl0. They claim to have resolved the problem. I'll try restarting your jobs to see if it's fixed.

**Comment by adamjstewart** [comment]
Looks like Travis is running smoothly again, at least on those PRs. I'll close this issue, but feel free to reopen if you notice this happening again.
