### ISSUE TITLE
Travis CI infrastructure failure

### ISSUE THREAD

**Issue by stefanosoffia** [spack/spack#6821]
PR #6805 is failing Travis CI checks because of a seemingly unrelated cause:

```
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
```

Other pull requests, e.g. #6804, seem to be affected by the same issue.

**Comment by adamjstewart** [comment]
This might be related to #6806. Either way, there's not much we can do, it seems like a Travis problem.
