### ISSUE TITLE
Module generation: difference between `setup_environment` and `setup_dependent_environment`?

### ISSUE THREAD

**Issue by svenevs** [spack/spack#6825]
What method do I implement in `package.py` to add an environment definition to a generated module?  `intel-tbb` needs to be setting `TBBROOT`.  I don't understand [the docs](http://spack.readthedocs.io/en/latest/module_file_support.html#override-api-calls-in-package-py) and which one to submit in a PR.  It just says

> In both cases you need to fill `run_env` with the desired list of environment modifications.

in terms of what the difference is.

```diff
diff --git a/var/spack/repos/builtin/packages/intel-tbb/package.py b/var/spack/repos/builtin/packages/intel-tbb/package.py
index f4ed13f..5b3ab15 100644
--- a/var/spack/repos/builtin/packages/intel-tbb/package.py
+++ b/var/spack/repos/builtin/packages/intel-tbb/package.py
@@ -76,6 +76,14 @@ class IntelTbb(Package):
                     else:
                         of.write(l)
 
+    # Make sure generated modules are setting TBBROOT (expected by other Intel
+    # tools and typical FindTBB.cmake.
+    def setup_environment(self, spack_env, run_env):
+        run_env.set('TBBROOT', self.prefix)
+
+    def setup_dependent_environment(self, spack_env, run_env, dependent_spec):
+        run_env.set('TBBROOT', self.prefix)
+
     def install(self, spec, prefix):
         if spec.satisfies('%gcc@6.1:') and spec.satisfies('@:4.4.3'):
             raise InstallError('Only TBB 4.4.4 and above build with GCC 6.1!')
```

Is it always set both?  My understanding is the `setup_`**`dependent`**`_environment` is for dependent specs, so in this particular case it likely should be there (or at least would not hurt), but what is the difference?  I guess in terms of the documentation, what is the difference between "module generation" and "dependent module generation"?

**Comment by alalazo** [comment]
If in the `IntelTbb` package you have:
```python
def setup_environment(self, spack_env, run_env):
    run_env.set('TBBROOT', self.prefix)
```
any module file generated for `intel-tbb` will have `TBBROOT` set to `intel-tbb` prefix. Module files of dependent packages are not affected in any way by this function.

Now, say `foo` depends on `intel-tbb` and in the `IntelTbb` package you have only:
```python
def setup_dependent_environment(self, spack_env, run_env, dspec):
    run_env.set('TBBROOT', self.prefix)
```
In this case the module file associated with `foo` will have `TBBROOT` set to `intel-tbb` prefix, but the `intel-tbb` module file won't set this variable.

If you have both calls, you may encounter an unexpected behavior when you unload `foo` after having loaded both `intel-tbb` and `foo` - it's very likely that the module tool will unset `TBBROOT` from the environment even though `intel-tbb` is still present. 

---

That said, from my experience `setup_dependent_environment` should be used only if you need information that is in `dspec`. What I would do here is maintain only this call in `intel-tbb`:
```python
def setup_environment(self, spack_env, run_env):
    run_env.set('TBBROOT', self.prefix)
```
and write a `modules.yaml` such that any package that depends on `intel-tbb` loads it automatically.

**Comment by svenevs** [comment]
@alalazo, also known as "ModuleMan", swiftly and definitively saves the day (again)!

I'll submit a PR later tonight with the tbb fix and a small update to the docs.  I'll use tbb as an example of a package that needs an environment variable set, are there any examples you are aware of that I can add to the docs explaining when you **would** use `setup_dependent_environment`?

**Comment by svenevs** [comment]
(or do you believe the existing docs on the R packaging stuff are enough for people who actually need this?)

**Comment by svenevs** [comment]
update, i'm working out the details of `FindTBB.cmake`.  My goal here is to nail that down precisely, and then work with the CMake folks to (finally) merge that into the main suite.  I'm going to close this, as this will likely be a long road
