### ISSUE TITLE
Travis failing: Unable to locate perl command

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#6830]
Several recent PRs (including #6824, #6828, and #6829) are failing with the following error message:
```
=================================== FAILURES ===================================
_________________ TestFlagHandlers.test_no_build_system_flags __________________
self = <spack.test.flag_handlers.TestFlagHandlers object at 0x3dfaad0>
temp_env = None
    def test_no_build_system_flags(self, temp_env):
        # Test that both autotools and cmake work getting no build_system flags
        s1 = spack.spec.Spec('callpath')
        s1.concretize()
        pkg1 = spack.repo.get(s1)
>       spack.build_environment.setup_package(pkg1, False)
lib/spack/spack/test/flag_handlers.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lib/spack/spack/build_environment.py:598: in setup_package
    dpkg.setup_dependent_package(pkg.module, spec)
var/spack/repos/builtin/packages/perl/package.py:186: in setup_dependent_package
    module.perl = self.spec['perl'].command
lib/spack/spack/spec.py:824: in __get__
    value = f()
lib/spack/spack/spec.py:817: in <lambda>
    callbacks_chain.append(lambda: self.default(self, instance, cls))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
descriptor = <spack.spec.ForwardQueryToPackage object at 0x142f2d0>
spec = perl@5.24.1%gcc@4.5.0+cpanm+shared arch=test-debian6-x86_64 ^gdbm@1.13%gcc@4.5..._glib arch=test-debian6-x86_64 ^readline@7.0%gcc@4.5.0 arch=test-debian6-x86_64
cls = <class 'llnl.util.lang.Spec'>
    def _command_default_handler(descriptor, spec, cls):
        """Default handler when looking for the 'command' attribute.
    
        Tries to search for ``spec.name`` in the ``spec.prefix.bin`` directory.
    
        Parameters:
            descriptor (ForwardQueryToPackage): descriptor that triggered the call
            spec (Spec): spec that is being queried
            cls (type(spec)): type of spec, to match the signature of the
                descriptor ``__get__`` method
    
        Returns:
            Executable: An executable of the command
    
        Raises:
            RuntimeError: If the command is not found
        """
        path = os.path.join(spec.prefix.bin, spec.name)
    
        if is_exe(path):
            return Executable(path)
        else:
            msg = 'Unable to locate {0} command in {1}'
>           raise RuntimeError(msg.format(spec.name, spec.prefix.bin))
E           RuntimeError: Unable to locate perl command in /home/travis/build/spack/spack/opt/spack/test-debian6-x86_64/gcc-4.5.0/perl-5.24.1-vy4kackxsavhhr7v3vgi5emsmyygu6cw/bin
```
This appears to be intermittent, especially in the case of #6824 where only a single version of Python exhibited this error.

Pinging @alalazo to see if he has any ideas.

**Comment by adamjstewart** [comment]
I am able to reproduce this locally by running the following command:
```
$ spack test flag_handlers
```
I have a suspicion that this is related to #5188 which I merged today. It passed the tests when it was submitted, but the tests must have changed since then.

**Comment by adamjstewart** [comment]
It looks like these tests were recently added in #6415. @becker33 perhaps we should test a different package (that does not depend on Perl) or test a mock package?

**Comment by adamjstewart** [comment]
### Summary of the Incident

Timeline:

- PR #5188 was submitted on August 23, 2017 and passed all of its tests
- PR #6415 was submitted on November 22, 2017 and merged on December 20, 2017
- PR #5188 was merged on January 4, 2018
- All unit tests on develop began crashing on January 4, 2018

These two PRs were perfectly innocuous on their own, but in combination caused Travis to fail. With the addition of the `perl` dependency to `openssl`, several of the packages in the `flag_handlers` test now depend on `perl`. They call `build_environment.setup_package`, which calls `spec['perl'].command`. The `command` attribute looks for a file called `perl` in `spec['perl'].prefix.bin`. If it can't find one, it raises an error, as expected. The problem is that the unit tests don't actually install Perl, they just call the `setup_package` which fails.

### Suggested Resolutions

We have a few options to fix this

1. Revert #5188 
    - This is an immediate fix, but not a great one
2. Choose different packages to test in `flag_handlers`
    - Specifically, packages that don't depend on `perl`
    - Better solution, but still fragile in the long run
3. Test mock packages in `flag_handlers`
    - Best solution, less fragile
4. Change the behavior of `command` to not raise an error
    - Not a great solution, Spack should probably fail if there is no file found

**Comment by tgamblin** [comment]
Can we at least revert #5188 and work on a fix in the meantime?

**Comment by adamjstewart** [comment]
#5188 has been reverted until we come up with a better fix.
