### ISSUE TITLE
VTK module generation error

### ISSUE THREAD

**Issue by sknigh** [spack/spack#6850]
Generating a VTK module after installation causes an error.

VTK's package.py has this line in its cmake_args():
``` python
cmake_args = std_cmake_args[:]
```

The error would go away if I replaced the initialization with an empty list. I would submit a fix by I don't know this has side effects.

### Steps to reproduce the issue
``` console
$ spack install vtk ^qt+opengl
...
$ spack module refresh -y --module-type tcl vtk; 
==> Regenerating tcl module files
==> Warning: Could not write module file [<ROOT>/spack/share/spack/modules/linux-centos7-x86_64/vtk/7.1.0]
==> Warning: 	--> global name 'std_cmake_args' is not defined <--
```

### Information on your system
Centos 7

**Comment by adamjstewart** [comment]
Wait a minute, why in the world are we extending `std_cmake_args`? It's already extended in `CMakePackage`. That might be a holdover from before `CMakePackage` existed. Let me submit a PR to fix this.
