### ISSUE TITLE
The build time for docs needs to be reduced

### ISSUE THREAD

**Issue by alalazo** [spack/spack#6857]
Very often the documentation badge on `develop` says *failing*. The cause is the time it takes to build the docs, that may exceed the maximum allowed on readthedocs (15 min.) An example of a failing build is [here](https://readthedocs.org/projects/spack/builds/6518192/).

### Expected Result

A  documentation badge that says *passing* - in line with the "docs" unit test that passed on Travis

### Actual Result

Sometimes we have a *passing* result, sometimes a *failing*, depending whether or not readthedocs can build our documentation in less than 15 min.

**Comment by adamjstewart** [comment]
This will be difficult. We can't build in parallel as there are all kinds of cross-links everywhere. If we replaced all of the calls to `programoutput` with the expected output, it would speed things up a bit, but then things will get rapidly out of date. There's also a lot of docstrings to scrape, which I think is the bulk of the time.

**Comment by adamjstewart** [comment]
Actually, it looks like the majority of the time is spent reading `package_list.rst`. If we dropped that, we could probably save 1/3 of the time it takes to build the docs. When I build locally on my laptop, it only takes 6 minutes, so I'm surprised it's timing out. Perhaps it's just a `pip` problem like with Travis lately?

**Comment by alalazo** [comment]
>  When I build locally on my laptop, it only takes 6 minutes, so I'm surprised it's timing out. Perhaps it's just a pip problem like with Travis lately?

I don't think so. Maybe there's a way to check that, but I believe it's more likely people offering the services are somehow oversubscribing their machines to maximize the usage. It's the same thing we see (or at least I see) on Travis: unit tests on my laptop take consistently around 220sec. while on Travis there's more variance and 500sec. is not an unusual wall-clock time.

**Comment by adamjstewart** [comment]
Does anyone have any other ideas on how to speed up the documentation builds? We haven't had a single build pass in 5 days now. The best idea I've come up with so far is to drop `package_list.rst` altogether, but this is rather drastic. @tgamblin?

**Comment by adamjstewart** [comment]
> > When I build locally on my laptop, it only takes 6 minutes, so I'm surprised it's timing out. Perhaps it's just a pip problem like with Travis lately?
>
> I don't think so. Maybe there's a way to check that, but I believe it's more likely people offering the services are somehow oversubscribing their machines to maximize the usage. It's the same thing we see (or at least I see) on Travis: unit tests on my laptop take consistently around 220sec. while on Travis there's more variance and 500sec. is not an unusual wall-clock time.

The documentation tests only take 9 minutes on Travis, so I don't think it's a server problem. It looks like they run multiple commands to build the HTML docs and PDF docs, so I think that's the problem. I wonder if we can turn off the PDF generation?

**Comment by adamjstewart** [comment]
It looks like we can turn off PDF builds. Want me to try that? PDFs are cute for releases, but I don't think we need to constantly update our PDFs.

**Comment by alalazo** [comment]
> Does anyone have any other ideas on how to speed up the documentation builds? We haven't had a single build pass in 5 days now. The best idea I've come up with so far is to drop package_list.rst altogether, but this is rather drastic. @tgamblin?

Maybe we can generate it once on Travis, and deploy it somewhere?

**Comment by tgamblin** [comment]
@adamjstewart @alalazo: I rewrote `spack list` with an option to go straight to HTML.  This seems to drop the build time down to a minute or so.  Apparently Sphinx is really bad at large documents.

See #6945.

**Comment by adamjstewart** [comment]
Docs passing! It looks like we went down from 550 s to 430 s. Still close to timing out but should give us a lot more breathing room. I still contend that we should drop PDF builds.

**Comment by alalazo** [comment]
> I still contend that we should drop PDF builds.

Agree completely. Is anybody using these builds at all?

**Comment by tgamblin** [comment]
I think people do use those -- esp. people who need to transfer the docs to a separate network.  But I am not sure that everything needs to be in there.  How much time could we get by removing apidocs from the PDF?
