### ISSUE TITLE
pkgconf doesn't work on Crays

### ISSUE THREAD

**Issue by mamelara** [spack/spack#6932]
Related issues: #6861 #6864 

Looks like the fix we did to make pkg-config work on Crays (see setup_dependent_environment), needs to be applied to pkgconf. It is causing the same issue we had before.

### Expected Result

pkgconf working similar to pkg-config

### Actual Result

Errors shown in the PRs above

### Steps to reproduce the issue

```console
spack install meson
```

### Information on your system
Cray platforms
-----
I've never used pkgconf so I'm not sure if it's as easy as adding the same fix. If it is then we can make a quick fix.

**Comment by mamelara** [comment]
Looks we need to set all the environment variables the same way as pkg-config.

**Comment by mamelara** [comment]
#7171 is a possible solution

**Comment by alalazo** [comment]
#7171 has been merged a long time ago...
