### ISSUE TITLE
Wrong source url for pango when doing `spack fetch -D r` (with 2 walkarounds).

### ISSUE THREAD

**Issue by adamryczkowski** [spack/spack#6938]
When doing `spack mirror create -D r` Spack tried to download the pango 1.41 from http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.41.0.tar.xz instead of http://ftp.gnome.org/pub/GNOME/sources/pango/1.41/pango-1.41.0.tar.xz . 

```
...

Adding package gobject-introspection@1.49.2 to mirror
==> gobject-introspection@1.49.2 : already added
==> Adding package pango@1.41.0 to mirror
==> Fetching http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.41.0.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
==> Warning: Error while fetching pango@1.41.0
  Failed to fetch file from URL: http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.41.0.tar.xz
==> Adding package zlib@1.2.11 to mirror
==> zlib@1.2.11 : already added

...
```

The walkaround is to either `spack mirror create -D r ^pango@1.40` (which works correctly) or with `spack fetch pango`:

```
# spack fetch pango
spack fetch pango
==> Fetching http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.41.0.tar.xz
curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.41.0.tar.xz failed.
spack inst==> Fetching http://ftp.gnome.org/pub/gnome/sources/pango/1.41/pango-1.41.0.tar.xz
######################################################################## 100,0%
```

And after that `spack fetch -D r` works and problem heals itself automatically.

I tried to fix the seemingly trivial problem myself, but it looks like the effective pango URL is generated programmatically somewhere in the code, and at this stage I am helpless.

**Comment by adamjstewart** [comment]
This should be fixed by #6939.
