### ISSUE TITLE
gtkplus build failure on Ubuntu LTS

### ISSUE THREAD

**Issue by nazavode** [spack/spack#6940]
On a clean `Ubuntu 16.04.3 LTS` (built via [this Dockerfile](https://gist.github.com/nazavode/50c6336f73fca09cf0c4b0997747df08)) the `configure` phase of `gtkplus` fails complaining about missing `cairo-xlib`. When `gtkplus` is asked for `+X` variant, everything works as expected as `cairo-xlib` is provided by `cairo+X`. I tried to configure the source manually using `./configure --without-x` but it keeps complaining: `cairo-xlib` looks like a mandatory dependency.

### Expected Result

To have the `gtkplus` package built and installed.

### Actual Result

```
==> Error: ProcessError: Command exited with status 1:
    '/home/spack/spack/var/spack/stage/gtkplus-2.24.31-hbqdviwkldktib7stpuem5mapww527hb/gtk+-2.24.31/configure' '--prefix=/home/spack/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/gtkplus-2.24.31-hbqdviwkldktib7stpuem5mapww527hb'

1 error found in build log:
     [ ... ]
     106   checking for library containing strerror... none required
     107   checking whether make sets $(MAKE)... (cached) yes
     108   checking for pkg-config... /home/spack/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/pkgconf-1.4.0-c5lf2hilcinnqpf3nojkif3eauay2gko/bin/pkg-config
     109   checking pkg-config is at least version 0.9.0... yes
     110   checking for BASE_DEPENDENCIES... yes
     111   checking for CAIRO_BACKEND... no
  >> 112   configure: error: Package requirements (cairo-xlib >= 1.6) were not met:
     113
     114   Package 'cairo-xlib', required by 'virtual:world', not found
     115
     116   Consider adjusting the PKG_CONFIG_PATH environment variable if you
     117   installed software in a non-standard prefix.
     118
```

### Steps to reproduce the issue

```console
$ spack install gtkplus
```

### Information on your system

The system used to reproduce this issue has been built via [this Dockerfile](https://gist.github.com/nazavode/50c6336f73fca09cf0c4b0997747df08). It is an `Ubuntu 16.04.3 LTS Server` (no GUI components) running `gcc@5.4.0` and `python@2.7.12`.

**Comment by adamryczkowski** [comment]
I can reproduce this problem also on HP's HPC (and Ubuntu as well)

**Comment by nazavode** [comment]
It seems that at least one `cairo` graphical backend is needed for `gtk+` to work properly. One straightforward *solution* would be to specify the following regardless of the `+X/~X` on `gtkplus` itself:

```
depends_on("pango+X")
```

The `+X` on `pango` is needed due to the fact that `pango~X` is incompatible with `cairo+X`:

```
$ spack install gtkplus ^cairo+X
...
pango requires cairo variant ~X, but spec asked for +X
```

**Comment by michaelkuhn** [comment]
I regularly run into this problem during development before remembering to enable the `X` variant. Since `--without-x` also does not work, I guess getting rid of the `X` variant and simply enabling it all the time makes the most sense.

**Comment by nazavode** [comment]
> I guess getting rid of the X variant and simply enabling it all the time makes the most sense.

Second this. Pushing a PR in this direction soon.

**Comment by michaelkuhn** [comment]
I just saw that the cairo dependency is based on the GDK target, which can be changed with `--with-gdktarget`. However, the only alternative for Linux seems to be `directfb`, which means that we would need a version of cairo built against directfb. Not sure if this is better than simply having a hard X dependency. :-)
