### ISSUE TITLE
Startup problem on Blue Waters (Cray)

### ISSUE THREAD

**Issue by eschnett** [spack/spack#6954]
If you want to report a build error for some package, or a bug in core please use the following template as a guideline:

-----

Summary

The usual `source share/spack/setup-env.sh` fails on Blue Waters (a Cray system). 

### Expected Result

Provide a working `spack`

### Actual Result

I see an error:
```
$ source share/spack/setup-env.sh
==> Warning: Could not detect module function from bash. Trying to detect modulecmd from `which`
If '_sp_sys_type=cray-CNL-interlagos' is not a typo you can run the following command to lookup the package that contains the binary:
    command-not-found _sp_sys_type=cray-CNL-interlagos
bash: _sp_sys_type=cray-CNL-interlagos: command not found
```

The warning is actually harmless (I checked); it appears because there is a custom `module` function that wraps a `moduleraw` function, and Spack cannot parse this. Spack does find `modulecmd` just fine, so this works.

However, the Bash error points at a severe problem. Spack sets the module path incorrectly, leading to a broken module system. On a Cray, this is fatal for Spack.

The value of `_assignment_command` is
```
_sp_sys_type=cray-CNL-interlagos _sp_dotkit_root=/mnt/a/u/sciteam/eschnett/src/spack/share/spack/dotkit _sp_tcl_root=/mnt/a/u/sciteam/eschnett/src/spack/share/spack/modules
```
which looks correct. However, for some reason, the respective call to `eval` fails. I do not understand why -- calling `eval` with this argument manually on the command line works fine.

This is
```
$ echo $BASH_VERSION
3.2.51(1)-release
```

### Information on your system

Platform:
```
$ uname -a
Linux h2ologin1 3.0.101-0.47.106.8-default #1 SMP Wed Oct 11 18:58:12 UTC 2017 (4355936) x86_64 x86_64 x86_64 GNU/Linux
```
(a Cray system)
-----

We encourage you to try, as much as possible, to reduce your problem to the minimal example that still reproduces the issue. That would help us a lot in fixing it quickly and effectively!

If you want to ask a question about the tool (how to use it, what it can currently do, etc.), try the `#general` channel on our Slack first. We have a welcoming community and chances are you'll get your reply faster and without opening an issue.

Other than that, thanks for taking the time to contribute to Spack!

**Comment by matthiasdiener** [comment]
I had the same issue on Blue Waters.

It seems to be caused by python creating unprintable characters in its output, which confuses bash when running `eval`.

I was able to fix this by following this method: https://incenp.org/notes/2012/python-term-smm-fix.html

**Comment by adamjstewart** [comment]
I was also hit by this issue today on Blue Waters.

**Comment by adamjstewart** [comment]
This issue is now resolved. I regularly use `source share/spack/setup-env.sh` on BW.
