### ISSUE TITLE
USEARCH md5sum issue with unique downloads

### ISSUE THREAD

**Issue by erimar77** [spack/spack#6976]
The [USEARCH download request form](https://www.drive5.com/usearch/download.html) generates a unique download for every request of the software, embedding the requestors email address into the binary.  For example:

```
./usearch10.0.240_i86linux32
usearch v10.0.240_i86linux32, 4.0Gb RAM (32.9Gb total), 8 cores
(C) Copyright 2013-17 Robert C. Edgar, all rights reserved.
http://drive5.com/usearch

License: user@example.com
```

If initiating the download from a "trusted source," do I just use `--no-checksum` to bypass the check if installing it as an explicit package?

If not explicitly installed, how can I bypass the checksum of a dependency without ignoring checksums for the entire package?

**Comment by baberlevi** [comment]
You could install it explicitly with `--no-checksum` and then use the hash in the dependency list for dependents.

Also, you probably already know about vsearch, but we try to use that instead where possible.
