### ISSUE TITLE
Boost headers-only variant

### ISSUE THREAD

**Issue by dorier** [spack/spack#6995]
It would be very useful to have a variant of the boost package that installs only the headers.

**Comment by naromero77** [comment]
@becker33 @tgamblin @adamjstewart Are there any objections against creating a Boost headers-only variant? It is possible to achieve the same result now, but not in a user friendly and practical way. You have to do `spack install boost~A~B~C~D…~M` which is very tedious.

**Comment by naromero77** [comment]
Actually, I started looking at this and realized this is not as straight forward as I first thought. I am not aware of a way for one variant to set defaults for other variants.

**Comment by naromero77** [comment]
I was thinking about this boost headers-only variant again and was looking at some of the suggestions here.
https://github.com/spack/spack/pull/10911

I couple of thoughts for your consideration @adamjstewart 

Easiest: Write a boost headers-only package, the downside is that someone needs to maintain both the regular version and headers-only version in sync. Optionally, one can make a boost-headers-only virtual package and either regular version or the headers-only version can be a provider. This is not the prettiest solution.

Harder: Perhaps the large combination of variants can be reduced to two variants.
1. headers-only
2. library with a multi-valued variant that can take any combination of those libraries (atomic, chrono, ...)

I would have not completely analyzed if 2. is even possible, but it should be assuming there are no hard conflicts between the boost libraries.

**Comment by mdorier** [comment]
The downside of maintaining 2 distinct packages is that if you have a package `A` that has `depends_on('boost')` (i.e. no particular variant required) and a package `B` that has `depends_on('boost+x')`, we should expect that concretizing these packages together would make spack install a single `boost+x`. If we have two packages for boost (say `boost` and `boost-headers`), then the maintainer of package B will have to chose between depending on `boost` or on `boost-headers`. If someone installs distinct versions of boost and boost-headers and loads them, then the compiler may use the headers of the second to build with the libraries of the first. Also if `A` and `B` are installed in the same environment, I don't see how spack would be able to properly create symlinks to headers from both packages when creating a view without potential problems.

**Comment by naromero77** [comment]
Thank you for raising these points that I had not thought of. Do people think the latter approach would work? I often end up implementing packages and then half-way through it realize that it won't actually work, so any insight would help.

**Comment by mdorier** [comment]
I think most people who use boost in their workflow with spack will have already hardcoded the `~x` and `+y` variants that they need, not to mention all the packages that depend on Boost. Which means that changing into a multi-valued variant is going to break a lot of code bases and packages.

My two cents is that for now it's better to keep the boost package as it is; if someone needs a headers-only variant, an ok-ish way to do that is to disable all the variants (or all the variants but one -- I'm not sure boost can build when disabling all the libraries).

The ideal feature for spack to solve this would be some kind of "variant alias", i.e. a variant that automatically gets translated into something else (i.e. another set of variants, a version, etc.). This kind of thing would be especially useful to express a particular spec that people may want to enable with minimal effort in a given situation (e.g. `+theta` in a package could mean "enable all the variants that make sense for this package to run on the Theta supercomputer").

**Comment by adamjstewart** [comment]
@hainest

**Comment by hainest** [comment]
I agree 100% with @mdorier's [comment](https://github.com/spack/spack/issues/6995#issuecomment-635177485) that having a separate `boost-headers` package introduces more problems than it solves. I also don't think having a `+header_only` variant will work, either. For example, some libraries have both a header-only *and* a compiled installation (e.g., container). We'd need to very carefully track and conflict on these. Moreover, let's say that my package `A` wants to use `+header_only`, but I rely on package `B` that `depends_on('boost')` (maybe I didn't know this or it gets added after I need it as a dependency). Since the latter needs the compiled libraries, then my variant should not be used. I'm not sure what the concretizer will do in this case, but whatever reason I had for wanting header-only is now erased.

I think the real question is what does the OP mean by

>It would be very useful to have a variant of the boost package that installs only the headers.

Yes, it could be useful, but what are we trying to accomplish? Reduced build times? Fewer link dependencies? ...

**Comment by hainest** [comment]
With https://github.com/spack/spack/pull/28623, the package is header-only by default.
