### ISSUE TITLE
ncurses fails to build on Cray Cori at NERSC 

### ISSUE THREAD

**Issue by jgalarowicz** [spack/spack#7006]
Problem:  On NERSC CRAY Cori using PrgEnv-gnu with no special packages.yaml or modules involved.
When trying to do this install:  **spack install cbtf-krell +runtime os=CNL**

**I get this failure:**
```
==> Installing ncurses
==> Error: SyntaxError: invalid syntax (<string>, line 425)
SyntaxError: SyntaxError: invalid syntax (<string>, line 425)
/global/u2/j/jgalaro/spack/lib/spack/spack/build_environment.py:684, in child_process:
     27    
     28                # build up some context from the offending package so we can
     29                # show that, too.
  >> 30                package_context = get_package_context(tb)
     31    
     32                build_log = None
     33                if hasattr(pkg, 'log_path'):

I have patches to cbtf-krell, but they don't effect this issue.

**This is the full output:**

==> Installing libsigsegv
==> Using cached archive: /global/u2/j/jgalaro/spack/var/spack/cache/libsigsegv/libsigsegv-2.11.tar.gz
==> Staging archive: /global/u2/j/jgalaro/spack/var/spack/stage/libsigsegv-2.11-uvqwq5ce34balpvfluh7uvfspnbln7op/libsigsegv-2.11.tar.gz
==> Created stage in /global/u2/j/jgalaro/spack/var/spack/stage/libsigsegv-2.11-uvqwq5ce34balpvfluh7uvfspnbln7op
==> No patches needed for libsigsegv
==> Building libsigsegv [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed libsigsegv
  Fetch: 0.00s.  Build: 9.99s.  Total: 9.99s.
[+] /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/libsigsegv-2.11-uvqwq5ce34balpvfluh7uvfspnbln7op
==> Installing m4
==> Using cached archive: /global/u2/j/jgalaro/spack/var/spack/cache/m4/m4-1.4.18.tar.gz
==> Staging archive: /global/u2/j/jgalaro/spack/var/spack/stage/m4-1.4.18-c5kdyscyrgyzgfsp26ktuyxxz6u5u2jf/m4-1.4.18.tar.gz
==> Created stage in /global/u2/j/jgalaro/spack/var/spack/stage/m4-1.4.18-c5kdyscyrgyzgfsp26ktuyxxz6u5u2jf
==> Applied patch gnulib-pgi.patch
==> Building m4 [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed m4
  Fetch: 0.01s.  Build: 44.15s.  Total: 44.15s.
[+] /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/m4-1.4.18-c5kdyscyrgyzgfsp26ktuyxxz6u5u2jf
==> Installing bison
==> Using cached archive: /global/u2/j/jgalaro/spack/var/spack/cache/bison/bison-3.0.4.tar.gz
==> Staging archive: /global/u2/j/jgalaro/spack/var/spack/stage/bison-3.0.4-3x3txvairczgd3q33uksf3b5qbm6kiic/bison-3.0.4.tar.gz
==> Created stage in /global/u2/j/jgalaro/spack/var/spack/stage/bison-3.0.4-3x3txvairczgd3q33uksf3b5qbm6kiic
==> Applied patch pgi.patch
==> Building bison [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed bison
  Fetch: 0.01s.  Build: 1m 2.01s.  Total: 1m 2.02s.
[+] /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/bison-3.0.4-3x3txvairczgd3q33uksf3b5qbm6kiic
==> Installing bzip2
==> Using cached archive: /global/u2/j/jgalaro/spack/var/spack/cache/bzip2/bzip2-1.0.6.tar.gz
==> Staging archive: /global/u2/j/jgalaro/spack/var/spack/stage/bzip2-1.0.6-4yersr6oakvbug3tid6d2q4xz6jjclwr/bzip2-1.0.6.tar.gz
==> Created stage in /global/u2/j/jgalaro/spack/var/spack/stage/bzip2-1.0.6-4yersr6oakvbug3tid6d2q4xz6jjclwr
==> Ran patch() for bzip2
==> Building bzip2 [Package]
==> Executing phase: 'install'
==> Successfully installed bzip2
  Fetch: 0.00s.  Build: 3.15s.  Total: 3.15s.
[+] /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/bzip2-1.0.6-4yersr6oakvbug3tid6d2q4xz6jjclwr
==> Installing pkgconf
==> Using cached archive: /global/u2/j/jgalaro/spack/var/spack/cache/pkgconf/pkgconf-1.4.0.tar.xz
==> Staging archive: /global/u2/j/jgalaro/spack/var/spack/stage/pkgconf-1.4.0-yr3p25ycrld2ctyp2gpsnt4q7okbr74d/pkgconf-1.4.0.tar.xz
==> Created stage in /global/u2/j/jgalaro/spack/var/spack/stage/pkgconf-1.4.0-yr3p25ycrld2ctyp2gpsnt4q7okbr74d
==> No patches needed for pkgconf
==> Building pkgconf [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed pkgconf
  Fetch: 0.00s.  Build: 10.08s.  Total: 10.08s.
[+] /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/pkgconf-1.4.0-yr3p25ycrld2ctyp2gpsnt4q7okbr74d
==> Installing ncurses
==> Error: SyntaxError: invalid syntax (<string>, line 425)
SyntaxError: SyntaxError: invalid syntax (<string>, line 425)

/global/u2/j/jgalaro/spack/lib/spack/spack/build_environment.py:684, in child_process:
     27    
     28                # build up some context from the offending package so we can
     29                # show that, too.
  >> 30                package_context = get_package_context(tb)
     31    
     32                build_log = None
     33                if hasattr(pkg, 'log_path'):
```

**Comment by mamelara** [comment]
Is this with spack -d install ... ? If not mind pasting the output of that?

**Comment by jgalarowicz** [comment]
@mamelara  Here is that information.  Thanks!

spack -d install cbtf-krell +runtime os=CNL
==> Warning: Skipping package at /global/u2/j/jgalaro/spack/var/spack/repos/builtin/packages/spack-cc-readline-svnxn5d.in.log. "spack-cc-readline-svnxn5d.in.log" is not a valid Spack module name.
==> Warning: Skipping package at /global/u2/j/jgalaro/spack/var/spack/repos/builtin/packages/spack-cc-readline-mgwbfkd.in.log. "spack-cc-readline-mgwbfkd.in.log" is not a valid Spack module name.
==> Warning: Skipping package at /global/u2/j/jgalaro/spack/var/spack/repos/builtin/packages/spack-cc-openssl-aaienju.out.log. "spack-cc-openssl-aaienju.out.log" is not a valid Spack module name.
==> Warning: Skipping package at /global/u2/j/jgalaro/spack/var/spack/repos/builtin/packages/spack-cc-readline-mgwbfkd.out.log. "spack-cc-readline-mgwbfkd.out.log" is not a valid Spack module name.
==> Warning: Skipping package at /global/u2/j/jgalaro/spack/var/spack/repos/builtin/packages/spack-cc-zlib-j5ucnte.in.log. "spack-cc-zlib-j5ucnte.in.log" is not a valid Spack module name.
==> Warning: Skipping package at /global/u2/j/jgalaro/spack/var/spack/repos/builtin/packages/spack-cc-openssl-aaienju.in.log. "spack-cc-openssl-aaienju.in.log" is not a valid Spack module name.
==> Warning: Skipping package at /global/u2/j/jgalaro/spack/var/spack/repos/builtin/packages/spack-cc-readline-svnxn5d.out.log. "spack-cc-readline-svnxn5d.out.log" is not a valid Spack module name.
==> Warning: Skipping package at /global/u2/j/jgalaro/spack/var/spack/repos/builtin/packages/spack-cc-zlib-j5ucnte.out.log. "spack-cc-zlib-j5ucnte.out.log" is not a valid Spack module name.
==> Reading config file /global/u2/j/jgalaro/spack/etc/spack/defaults/packages.yaml
==> Reading config file /global/homes/j/jgalaro/.spack/cray/packages.yaml
==> READ LOCK: /global/homes/j/jgalaro/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /global/homes/j/jgalaro/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /global/homes/j/jgalaro/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /global/homes/j/jgalaro/.spack/cray/compilers.yaml
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[932754297298898237:1] [Acquiring]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[932754297298898237:1] [Acquired]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[932754297298898237:1] [Released]
==> link /global/u2/j/jgalaro/spack/var/spack/stage/cbtf-krell-1.8-dhrz4lwsocnhwpam2jcvkgnzc7qn4g7b -> /tmp/jgalaro/spack-stage/spack-stage-WP6KLN
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[932754297298898237:1] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[932754297298898237:1] [Acquired]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[932754297298898237:1] [Released]
==> Installing cbtf-krell dependencies
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[5958460468790001922:1] [Acquiring]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[5958460468790001922:1] [Acquired]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[5958460468790001922:1] [Released]
==> link /global/u2/j/jgalaro/spack/var/spack/stage/libsigsegv-2.11-uvqwq5ce34balpvfluh7uvfspnbln7op -> /tmp/jgalaro/spack-stage/spack-stage-BooiuU
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[5958460468790001922:1] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[5958460468790001922:1] [Acquired]
==> libsigsegv is already installed in /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/libsigsegv-2.11-uvqwq5ce34balpvfluh7uvfspnbln7op
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[5958460468790001922:1] [Released]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[840517421168384201:1] [Acquiring]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[840517421168384201:1] [Acquired]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[840517421168384201:1] [Released]
==> link /global/u2/j/jgalaro/spack/var/spack/stage/m4-1.4.18-c5kdyscyrgyzgfsp26ktuyxxz6u5u2jf -> /tmp/jgalaro/spack-stage/spack-stage-jDY9k6
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[840517421168384201:1] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[840517421168384201:1] [Acquired]
==> m4 is already installed in /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/m4-1.4.18-c5kdyscyrgyzgfsp26ktuyxxz6u5u2jf
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[840517421168384201:1] [Released]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7997159191745943856:1] [Acquiring]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7997159191745943856:1] [Acquired]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7997159191745943856:1] [Released]
==> link /global/u2/j/jgalaro/spack/var/spack/stage/bison-3.0.4-3x3txvairczgd3q33uksf3b5qbm6kiic -> /tmp/jgalaro/spack-stage/spack-stage-vxSVzH
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7997159191745943856:1] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7997159191745943856:1] [Acquired]
==> bison is already installed in /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/bison-3.0.4-3x3txvairczgd3q33uksf3b5qbm6kiic
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7997159191745943856:1] [Released]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[8287903849851737357:1] [Acquiring]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[8287903849851737357:1] [Acquired]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[8287903849851737357:1] [Released]
==> link /global/u2/j/jgalaro/spack/var/spack/stage/bzip2-1.0.6-4yersr6oakvbug3tid6d2q4xz6jjclwr -> /tmp/jgalaro/spack-stage/spack-stage-r0oUyU
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[8287903849851737357:1] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[8287903849851737357:1] [Acquired]
==> bzip2 is already installed in /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/bzip2-1.0.6-4yersr6oakvbug3tid6d2q4xz6jjclwr
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[8287903849851737357:1] [Released]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7078390583135658960:1] [Acquiring]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7078390583135658960:1] [Acquired]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7078390583135658960:1] [Released]
==> link /global/u2/j/jgalaro/spack/var/spack/stage/pkgconf-1.4.0-yr3p25ycrld2ctyp2gpsnt4q7okbr74d -> /tmp/jgalaro/spack-stage/spack-stage-35B77Z
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7078390583135658960:1] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7078390583135658960:1] [Acquired]
==> pkgconf is already installed in /global/u2/j/jgalaro/spack/opt/spack/cray-CNL-haswell/gcc-7.2.0/pkgconf-1.4.0-yr3p25ycrld2ctyp2gpsnt4q7okbr74d
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[7078390583135658960:1] [Released]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[2910361972238080888:1] [Acquiring]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[2910361972238080888:1] [Acquired]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[2910361972238080888:1] [Released]
==> link /global/u2/j/jgalaro/spack/var/spack/stage/ncurses-6.0-kddv3fugds3pbes6ab4sjnuefibqgk5o -> /tmp/jgalaro/spack-stage/spack-stage-SFFwtI
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[2910361972238080888:1] [Acquiring]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[2910361972238080888:1] [Acquired]
==> READ LOCK: /global/u2/j/jgalaro/spack/opt/spack/.spack-db/prefix_lock[2910361972238080888:1] [Released]
==> Installing ncurses
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'avail' '-t' 'craype-'
==> '/usr/bin/env' '-' 'USER=jgalaro' 'HOME=/global/homes/j/jgalaro' '/bin/bash' '--noprofile' '--norc' '-c' '. /etc/profile; module list -lt'
==> Found default modules:
       modules/3.2.10.6
       nsg/1.2.0
       intel/18.0.1.163
       craype-network-aries
       craype/2.5.12
       cray-libsci/17.09.1
       udreg/2.3.2-6.0.4.0_12.2__g2f9c3ee.ari
       ugni/6.0.14-6.0.4.0_14.1__ge7db4a2.ari
       pmi/5.0.12
       dmapp/7.1.1-6.0.4.0_46.2__gb8abda2.ari
       gni-headers/5.0.11-6.0.4.0_7.2__g7136988.ari
       xpmem/2.2.2-6.0.4.0_3.1__g43b0535.ari
       job/2.2.2-6.0.4.0_8.2__g3c644b5.ari
       dvs/2.7_2.2.32-6.0.4.1_7.2__ged1923a
       alps/6.4.1-6.0.4.0_7.2__g86d0f3d.ari
       rca/2.2.15-6.0.4.1_13.1__g46acb0f.ari
       atp/2.1.1
       PrgEnv-intel/6.0.4
       craype-haswell
       cray-mpich/7.6.2
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.2.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.2.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'PrgEnv-gnu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-x1'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-x2'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-cray'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-intel'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-pgi'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-pathscale'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-gnu'
==> Error: SyntaxError: invalid syntax (<string>, line 425)
SyntaxError: SyntaxError: invalid syntax (<string>, line 425)

/global/u2/j/jgalaro/spack/lib/spack/spack/build_environment.py:697, in child_process:
     27    
     28                # build up some context from the offending package so we can
     29                # show that, too.
  >> 30                package_context = get_package_context(tb)
     31    
     32                build_log = None
     33                if hasattr(pkg, 'log_path'):


Traceback (most recent call last):
  File "/global/u2/j/jgalaro/spack/lib/spack/spack/build_environment.py", line 678, in child_process
    setup_package(pkg, dirty=dirty)
  File "/global/u2/j/jgalaro/spack/lib/spack/spack/build_environment.py", line 630, in setup_package
    load_module(mod)
  File "/global/u2/j/jgalaro/spack/lib/spack/spack/util/module_cmd.py", line 134, in load_module
    error=str), '<string>', 'exec'))
  File "<string>", line 425
    rca/2.2.15-6.0.4.1_13.1__g46acb0f.ari(21):ERROR:102: Tcl command execution failed: if { [ file exists /opt/cray/rca/2.2.15-6.0.4.1_13.1__g46acb0f.ari/lib64/pkgconfig/cray-rca.pc ] } {
             ^
SyntaxError: invalid syntax

**Comment by mamelara** [comment]
pkgconf strikes again! This will definitely need to be fixed. In the mean time declare pkg-config as your preferred pkgconfig provider in packages.yaml

**Comment by jgalarowicz** [comment]
Thanks Mario!
I was looking in the documentation for the syntax of how to declare pkg-config as the preferred provider for pkgconfig (in packages.yaml), but didn't see how to specify that.   Is there an example somewhere I can look at?

**Comment by mamelara** [comment]
in packages.yaml:
```yaml
packages:
    all:
        providers:
            pkgconfig: [pkg-config]
```

**Comment by jgalarowicz** [comment]
@mamelara @alalazo @skosukhin 

Hi all - I moved over to titan at ORNL and I'm trying to build OpenSpeedShop there, but ran into the ncurses build issue - but seems to be different.   I added the work around for pkg-config, but can't build ncurses on Titan.

jgalaro@titan-ext1:~/spack/var/spack/repos/builtin/packages> cat ~/.spack/cray/packages.yaml 
packages:
   all:
      providers:
         pkgconfig: [pkg-config]
   mpich:
      buildable: False
      paths:
         mpich@7.6.3%gcc@7.1.0 arch=cray-CNL-interlagos: /opt/cray/mpt/7.6.3/gni/mpich-gnu/4.9

The spack output:

jgalaro@titan-ext1:~/spack/var/spack/repos/builtin/packages> spack install cbtf-krell +mpich+runtime os=CNL
==> libsigsegv is already installed in /autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/libsigsegv-2.11-ykaxkgr2rr24o7jrhbau2wghv6i6soxc
==> m4 is already installed in /autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/m4-1.4.18-ud6laz7goseirete2jjkdgilhzoe7l4l
==> bison is already installed in /autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/bison-2.7-6qpojyn2gcuo3zo2ustttcq5qe6lvkte
==> bzip2 is already installed in /autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/bzip2-1.0.6-ksrhxkwvpkbxd72nonh5q3coj6hh3ulr
==> Installing pkg-config
==> Using cached archive: /autofs/nccs-svm1_home1/jgalaro/spack/var/spack/cache/pkg-config/pkg-config-0.29.2.tar.gz
==> Staging archive: /autofs/nccs-svm1_home1/jgalaro/spack/var/spack/stage/pkg-config-0.29.2-wf5obgi3g6mr43ctgkbhbwqciyqni3oh/pkg-config-0.29.2.tar.gz
==> Created stage in /autofs/nccs-svm1_home1/jgalaro/spack/var/spack/stage/pkg-config-0.29.2-wf5obgi3g6mr43ctgkbhbwqciyqni3oh
==> No patches needed for pkg-config
==> Building pkg-config [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed pkg-config
  Fetch: 0.11s.  Build: 4m 25.12s.  Total: 4m 25.23s.
[+] /autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/pkg-config-0.29.2-wf5obgi3g6mr43ctgkbhbwqciyqni3oh
==> Installing ncurses
==> Using cached archive: /autofs/nccs-svm1_home1/jgalaro/spack/var/spack/cache/ncurses/ncurses-6.0.tar.gz
==> Staging archive: /autofs/nccs-svm1_home1/jgalaro/spack/var/spack/stage/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g/ncurses-6.0.tar.gz
==> Created stage in /autofs/nccs-svm1_home1/jgalaro/spack/var/spack/stage/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g
==> Applied patch sed_pgi.patch
==> Applied patch patch_gcc_5.txt
==> Building ncurses [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '../configure' '--prefix=/autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g' 'CFLAGS=-fPIC' 'CXXFLAGS=-fPIC' '--with-shared' '--with-cxx-shared' '--enable-overwrite' '--without-ada' '--enable-pc-files' '--with-pkg-config-libdir=/autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g/lib/pkgconfig' '--disable-widec' '--without-manpages' '--without-tests'

1 error found in build log:
     7     checking for package patch date... 20150808
     8     checking build system type... x86_64-unknown-linux-gnu
     9     checking host system type... x86_64-unknown-linux-gnu
     10    checking target system type... x86_64-unknown-linux-gnu
     11    Configuring for linux-gnu
     12    checking for prefix... /autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovn
           nqrvp5g
  >> 13    checking for C compiler default output... configure: error: C compiler cannot create executables

See build log for details:
  /autofs/nccs-svm1_home1/jgalaro/spack/var/spack/stage/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g/ncurses-6.0/spack-build.out
jgalaro@titan-ext1:~/spack/var/spack/repos/builtin/packages> 


jgalaro@titan-ext1:~/spack/var/spack/repos/builtin/packages> cat /autofs/nccs-svm1_home1/jgalaro/spack/var/spack/stage/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g/ncurses-6.0/spack-build.out
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> '../configure' '--prefix=/autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g' 'CFLAGS=-fPIC' 'CXXFLAGS=-fPIC' '--with-shared' '--with-cxx-shared' '--enable-overwrite' '--without-ada' '--enable-pc-files' '--with-pkg-config-libdir=/autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g/lib/pkgconfig' '--disable-widec' '--without-manpages' '--without-tests'
checking for egrep... grep -E
Configuring NCURSES 6.0 ABI 6 (Mon Feb 19 12:06:25 EST 2018)
checking for package version... 6.0
checking for package patch date... 20150808
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
Configuring for linux-gnu
checking for prefix... /autofs/nccs-svm1_home1/jgalaro/spack/opt/spack/cray-CNL-interlagos/gcc-7.1.0/ncurses-6.0-my5y4y6yeeg4y2ltdn5hpcovnnqrvp5g
checking for C compiler default output... configure: error: C compiler cannot create executables
jgalaro@titan-ext1:~/spack/var/spack/repos/builtin/packages>

**Comment by mamelara** [comment]
would #7171 help your issue?

**Comment by jgalarowicz** [comment]
@mamelara Yes, thanks!  It should help my issue.
