### ISSUE TITLE
Generate module names that contain python version as well as compiler version

### ISSUE THREAD

**Issue by adrianjhpc** [spack/spack#7029]
When using spack on a system supporting multiple python versions (i.e. both 2.7.x and 3.x) it would be very useful to be able to see the python version a particular module has been compiled against in the module name, rather than having to search through the pythonpath of that particular module. 

This would be functionality similar to the current practice of including the compiler used to build the software in the module name.

**Comment by alalazo** [comment]
Hi @adrianjhpc, did you have a look at the [tutorial](https://spack.readthedocs.io/en/latest/tutorial_modules.html#change-module-file-naming)? You should be able to do what you want with this:
```yaml
modules:
  tcl:
    all:
      '^python@2.7': 'py2.7'
      '^python@3.6': 'py3.6'
```
in you `modules.yaml`. If you confirm this works I'll close the issue.

**Comment by adrianjhpc** [comment]
Hi @alalazo,

Apologies, I'd not noticed that feature, yes this will do exactly what I want.

thanks

**Comment by alalazo** [comment]
@adrianjhpc No worries. If you want to check which features are available to customize module files you can have a look at the tutorial linked above. The docker image is a bit "heavy", but should grant you that everything works exactly as you see in the notes.
