### ISSUE TITLE
'depends_on' with 'patches' breaks with compound 'when' statement

### ISSUE THREAD

**Issue by naromero77** [spack/spack#7044]
-----

Summary

### Expected Result
The way this statement should work:
`depends_on(<dep. package variant>, patches=patch<patch arguements>, when=<variant 1, variant2>`

If I specify <variant1> and <variant2> for my package, then only when those variants are specified (either as defaults or '+') should the <dep. package variant> be installed with its patches. A negation, specified by '~', of any variant for my package should cancel this entire operation.

### Actual Result

With or without negation ('~'), Spack tries to apply the patch before downloading the package. 

Some additional observations:
1. If depends_on does *not* contain the patches=<stuff>, the correct behavior is observed.
2. If the `when` statements only has a single option as a variant, the correct behavior is observed.

### Steps to reproduce the issue
Apply this PR https://github.com/spack/spack/pull/6958 to Spack devel. In particular, this commit triggers the issue:
https://github.com/spack/spack/pull/6958/commits/a811b6daa251b0634946e3f96404dcc78e1ba64c

```
$ spack install qmcpack~qe~mpi%gcc@6.4.0 ^veclibfort

==> Staging archive: /Users/naromero/spack/var/spack/stage/qmcpack-3.3.0-yozyxvz4bk3alaezuuxlu6c6kuznm4t3/qmcpack-3.3.0.tar.gz
==> Created stage in /Users/naromero/spack/var/spack/stage/qmcpack-3.3.0-yozyxvz4bk3alaezuuxlu6c6kuznm4t3
==> Using cached archive: /Users/naromero/spack/var/spack/cache/qmcpack/add_pw2qmcpack_to_espresso-5.3.0.diff
The text leading up to this was:
--------------------------
|diff -urN espresso-5.3.0-orig/clib/make.depend espresso-5.3.0-new/clib/make.depend
|--- espresso-5.3.0-orig/clib/make.depend	2016-01-09 02:23:51.000000000 -0600
|+++ espresso-5.3.0-new/clib/make.depend	2016-08-29 20:13:54.925433086 -0500
--------------------------
File to patch:

...
```

### Information on your system

I am doing this on a Mac with gcc from Homebrew. The issue here is agnostic to either the compiler or the BLAS/LAPACK library.

-----

**Comment by davydden** [comment]
just in case this helps, this is how I use depends_on patches in [dealii](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py#L98-L107), seems to work in this scenario.

**Comment by naromero77** [comment]
@davydden Thank you for sharing that snippet of code. Its a related case, but I cannot use it because the QE variant *must* always use a patched Espresso package, no exceptions.

It might be possible to hack something like:

```
if mpi in self.spec,
depends_on('espresso@5.3.0~elpa',
               patches=patch(patch_url, sha256=patch_checksum),
               when='+qe')
else
    depends_on('espresso@5.3.0~elpa~scalapack~mpi',
               patches=patch(patch_url, sha256=patch_checksum),
               when='+qe~mpi')

```
But I think that is undesirable.

**Comment by naromero77** [comment]
@tgamblin Problem was my understanding of the correct use of the patch command/argument.

**Comment by tgamblin** [comment]
Oh!  great!  Care to elaborate?  What was the misunderstanding and how can we clarify it in the docs?

**Comment by naromero77** [comment]
@tgamblin This construction:
`depends_on(<dep. package variant>, patches=patch<patch arguements>, when=<variant 1, variant2>`

Essentially has a nested when_spec. I had assumed that the when_spec from the depends_on got forwarded to the patch function, but that is not the case. They are two independent when_specs. However, for maximum flexibility -- I think this is what you want. Probably with adding a few examples to the doc would suffice.
