### ISSUE TITLE
`spack install opengl` fails during the fetch phase when it should fail during install

### ISSUE THREAD

**Issue by goxberry** [spack/spack#7061]
# Summary

#6551 introduced a dummy `opengl` package that intends to throw an error during the `install` phase of execution with a helpful message asking a user to install OpenGL as an external package. However, this message will never throw because the URL supplied as an argument to the `version` directive is invalid, so instead, the package throws a generic error message that has nothing to do with OpenGL.

### Expected Result

```console
$ spack install opengl
==> Error: Unable to install opengl
This package is intended to be a placeholder for
system-provided OpenGL libraries from hardware vendors.  Please
download and install OpenGL drivers/libraries for your graphics
hardware separately, and then set that up as an external package.
An example of a working packages.yaml:

packages:
    opengl:
         paths:
             opengl@4.5.0: /opt/opengl
                  buildable: False

In that case, /opt/opengl/ should contain these two folders:

        include/GL/       (opengl headers, including "gl.h")
        lib               (opengl libraries, including "libGL.so")"""
```

### Actual Result

```console
$ spack install opengl
==> Error: Unable to parse extension from https://www.opengl.org/.

If this URL is for a tarball but does not include the file extension
in the name, you can explicitly declare it with the following syntax:

    version('1.2.3', 'hash', extension='tar.gz')

If this URL is for a download like a .jar or .whl that does not need
to be expanded, or an uncompressed installation script, you can tell
Spack not to expand it with the following syntax:

    version('1.2.3', 'hash', expand=False)
```

### Steps to reproduce the issue

```console
$ spack install opengl
```

### Information on your system

I think the only information needed to reproduce is a `packages.yaml` that does not contain an `opengl:` clause. My `packages.yaml` does not:

packages.yaml
```console
packages:
  perl:
    variants: +cpanm+shared
  ruby:
    variants: +openssl+readline
  pcre:
    variants: +jit+utf
  netcdf:
    variants: +mpi
  hdf5:
    variants: +mpi
  qt:
    variants: +opengl
  all:
    compiler: [clang@8.1.0-apple, clang, gcc]
    providers:
      awk: [gawk]
      blas: [openblas, atlas, intel-mkl, netlib-lapack]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas, atlas, intel-mkl, netlib-lapack]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich, intel-mpi]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack, intel-mkl]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
      cmake: [cmake%clang]
    paths: {}
    modules: {}
    buildable: true
    version: []
```

**Comment by goxberry** [comment]
I'm reading #6551, and I'm confused about why the `opengl` package exists. It was intended to fix installing VTK on Macs, and instead, it's breaking a VTK build that used to work on my Mac.

**Comment by scheibelp** [comment]
> I'm reading #6551, I'm confused about why the opengl package exists

For systems that have an opengl installation already, using that version was found to speed things up. That PR originally also updated packages.yaml to define an external entry for `opengl` but that was later removed (at my request). I missed that `~osmesa` would activate the `opengl` dependency, I should have requested that `osmesa` be on by default.

Do you get better results with https://github.com/spack/spack/pull/7060 and `spack spec visit ^vtk+osmesa`?

**Comment by goxberry** [comment]
> For systems that have an opengl installation already, using that version was found to speed things up.

I believe that. I'd like to use my system OpenGL also for similar reasons. Darwin doesn't use the directory tree schema discuss in the error message above. Rather, it would be linked via `-framework OpenGL`. Even if I supply a header directory directly, I'd have to link via flags (i.e., '-lGL`) because the headers are in a particular stub format (`tbd` suffix?) that apparently won't link using Apple Clang via absolute path. All of this information is detected automatically by CMake's `find_package`.

Was the intended use case installing OpenGL in a nonstandard path that CMake wouldn't normally search?

**Comment by goxberry** [comment]
I'm building with `spack install visit ^vtk+osmesa`, and it's building an old version of LLVM, so this installation could take a while (at least 40 minutes for LLVM alone on a 2017 quad core MacBook Pro). After it installs, I'll let you know. It might be possible to build it with Apple Clang (Xcode 8.3 roughly corresponds to Clang 3.8), which would save quite a bit of time for some users; LLVM takes a few hours to build on my old MacBook Air.

**Comment by scheibelp** [comment]
> Was the intended use case installing OpenGL in a nonstandard path that CMake wouldn't normally search?

That would be one of the benefits. Also:

* In general Spack tries to be explicit about all details of the build. In this case the benefit is that a user can specify in their `paths` entry which version of opengl is supplied, which informs the gl API version that is provided (so it is known at the spec level whether the system opengl provides the needed functionality)
* While for `visit` it generally "works out" if one were to follow the strategy of specifying mesa or not (and omitting the `opengl` package) this may be awkward for other packages that depend on gl support. Other build systems may benefit from making the possibility of other implementations explicit.

> I'm building with spack install visit ^vtk+osmesa

I also should have mentioned a way to get back to using the system opengl would be to add an entry for it in `packages.yaml`:

```
packages:
  opengl:
    paths:
      opengl@...:/usr/ #assuming libGL.so is in /usr/lib/
```

**Comment by goxberry** [comment]
> In general Spack tries to be explicit about all details of the build. In this case the benefit is that a user can specify in their paths entry which version of opengl is supplied, which informs the gl API version that is provided (so it is known at the spec level whether the system opengl provides the needed functionality)

All right, I think I have a handle on it. For reference, assuming a Mac user has an installation of XCode 5 or later, OpenGL would be installed in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework`, where `10.12` would be replaced by the appropriate OS X version for that Xcode.app version (XCode 9 uses `10.13`, even though I run 10.12.6). Supplying the prefix is apparently enough for the OpenGL CMake `find_package`; I'm less confident about how it will work for Autotools-based build systems, but the majority of packages with obvious OpenGL dependencies have CMake build systems.

I can't figure out which version of OpenGL is installed from the headers alone; searching online indicates that for my Mac model, it is version 4.1, but other models use different versions (see https://support.apple.com/en-us/HT202823).

The information was a little tricky to track down, and could be worth listing in the help message. Longer-term, an autodetect feature similar to `spack compiler find` would be great, but I imagine would be difficult to implement.

**Comment by davydden** [comment]
Thanks @goxberry for this summary, I am also interested in trying this out.

Ps. Should we have a wiki page with some brief packages.yaml configuration setup hints for different platforms?

**Comment by goxberry** [comment]
@davydden It would probably help cut down the support burden for spack to provide "suggested settings" for certain use cases. I'm not part of a computing facility support staff, so I can't say for sure whether they need configuration help, but anyone using spack for software development on a desktop or laptop is likely to want configuration advice. I'd guess that configuring `opengl` is going to trip up many Mac users unless more detailed advice is provided in the documentation.

It might also be worth putting together a troubleshooting guide for common problems in creating or installing packages. An occasional issue I run into when installing spack packages is the error message:

```console
ld: warning: ignoring file ${SOME_ARCHIVE}, file was built for archive which is not the architecture being linked (x86_64): ${SOME_ARCHIVE}
```

where `${SOME_ARCHIVE}` is either a static or dynamic library being built by spack. 99% of the time, this error occurs because `binutils` is loaded as a module, and spack calls to `ar` end up using the `ar` from `binutils`, which is different than the system `ar` on Darwin. It took me a few hours to figure it out the first time, but maybe this knowledge would save other people trouble?

**Comment by alalazo** [comment]
@v-dobrev Should we close this too as #7063 has been merged?

**Comment by v-dobrev** [comment]
I think we can close this.
