### ISSUE TITLE
R installation: tcltk capability missing

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#7072]
Summary

### Expected Result

tcltk capability should be true

### Actual Result

tcltk capability is false

### Steps to reproduce the issue

```console
$ spack install r +X
$ module load r-3.4...
$ R
$ > capabilities("tcltk")
$ FALSE
...
```
1. tcl & tk listed as dependence, so by default R should be compiled with tcltk option
2. Default installtion didn't work, so added '--with-tcltk" to config_args, still got the same result

### Information on your system

Centos 7, gcc 7.2

**Comment by hartzell** [comment]
I've fixed this in #7805.  Feedback welcome.

**Comment by Sinan81** [comment]
great! I will check it out right away.

**Comment by Sinan81** [comment]
It works! Thanks!
