### ISSUE TITLE
missing libnoxepetra.so.12

### ISSUE THREAD

**Issue by bnwind** [spack/spack#7088]
After installed trilinos on ubuntu 17.10, compiler keep saying libnoxepetra.so.12 missing. but it is there in under spack/opt/... folder. Any suggestion on linking the library?

**Comment by amklinv** [comment]
Is this a spack issue, or is this an issue with linking against an installed Trilinos?  If it's an issue with linking against an installed Trilinos, please see the documentation here: https://github.com/trilinos/Trilinos_tutorial/wiki/TrilinosHandsOnTutorial

**Comment by alalazo** [comment]
Closing as having no answer from @bnwind . please reopen if need be.
