### ISSUE TITLE
package.py hashing

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#7119]
To do release management as described in #7116 and #7117, we need to include the hash of `package.py` files in the `spec`, so that changes to builds are reflected in the Spack hash.

We have had logic to do this for a while, in the `features/package-hash` branch.  This branch canonicalizes packages by removing comments, directive metadata, and unused version-specific `@when` decorators, then it hashes what's left and factors that into the spec.

We haven't worked this into Spack proper yet, because there needs to be additional support in the concretizer to make it less disruptive.  But we'll at least need it to detect that packages have changed meaningfully since the last build.

- [x] Rebase `features/package-hash` on `develop` and get it working. (#7193)

- [x] Depending on whether the new concretizer is ready, decide whether to make the package hash part of the spec hash, or whether we should just use it for builds.
     * merge in appropriate support
     * **Decision**: we will just use this to detect builds for now.  The support for full hashing is in place, but full hashing won't be in production until we have the new concretizer.

- [x] ensure that binaries are rebuilt when changes are made to `package.py` files on a release branch, see #8387 for discussion.

**Comment by mathstuf** [comment]
Variants should probably be sorted as well (if they already aren't) to preserve some stability there as well.

**Comment by mathstuf** [comment]
I have the mentioned feature branch rebased on top of `develop` (courtesy of [`git-imerge`](https://github.com/mhagger/git-imerge)). I did squash the branch into a single commit for rebasing; I'll split it again before making a proper topic from it. Trying to get the test suite back in order now…

A note: I *highly* recommend that Spack do a sweep of `flake8` across the entire tree. Having to stop every 50 commits in a 3600 commit rebase to deal with style fixups is a PITA.

**Comment by alalazo** [comment]
> A note: I highly recommend that Spack do a sweep of flake8 across the entire tree. Having to stop every 50 commits in a 3600 commit rebase to deal with style fixups is a PITA.

In case, we can continue the discussion elsewhere, but should we reconsider [yapf](https://github.com/google/yapf)? That will make formatting equally bad for everyone, like `go fmt` does.

**Comment by mathstuf** [comment]
Yes, it's best to discuss that elsewhere. I think that `yapf` is a better approach than `autopep8`, so that'd be fine with me.

**Comment by mathstuf** [comment]
See #7193 for the associated PR for the first bit (getting a hash based on patches and `package.py`.

**Comment by tgamblin** [comment]
Fixed by #10274.
