### ISSUE TITLE
Set up a public binary mirror

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#7123]
Depends on #7116 and #7121.

#7121 set up a source mirror for Spack.  This adds to the release process so that binaries are also released.  The upload of release tarballs to an S3 store should happen once a release branch is merged to master, so that binaries are available to users and so that they can be the default install mechanism.

- [ ] Once the release is merged to master, binaries are deployed to the public S3 binary mirror.

**Comment by mathstuf** [comment]
What is going to do the GPG signing? These keys should be inaccessible from builders themselves since they're running arbitrary code. Binaries could be uploaded back to the buildbot master which could hold these keys. Though this would mean that the buildbot master would either have to reimplement the signing and packing or it'd be running some version of Spack.

**Comment by alalazo** [comment]
Apologies if this is OT here (in case I can delete and move the discussion elsewhere). I tried to produce relocatable binaries with Spack, with different configurations and OSes. No matter what, I always obtain messages like the one below:
```console
$ spack buildcache create -d /home/mculpo/production/binary-mirror/ pkgconf%gcc@8.0.1
==> adding matching spec pkgconf@1.4.2%gcc@8.0.1 arch=linux-ubuntu18.04-x86_64 
==> recursing dependencies
==> adding dependency pkgconf@1.4.2%gcc@8.0.1 arch=linux-ubuntu18.04-x86_64 
==> writing tarballs to /home/mculpo/production/binary-mirror//build_cache
==> creating binary cache file for package pkgconf@1.4.2%gcc@8.0.1 arch=linux-ubuntu18.04-x86_64  
==> Error: 
 /tmp/tmpBRgP0_/pkgconf-1.4.2-eajb4xoexry2k5ub6ywyzv52iunu2eb6/bin/pkgconf 
contains string
 /home/mculpo/PycharmProjects/spack/opt/spack 
after replacing it in rpaths.
Package should not be relocated.
 Use -a to override.
```
for most packages. I was wondering how do you plan to deal with this situation and have real relocatable binary packages (i.e. packages that I can safely reinstall into another directory, without maintaining references to the layout of the initial installation). 

Of course I could give the `-a` option and produce a binary cache, but that could in principle be safely re-installed only in the same directory tree, right? Am I missing something here?

**Comment by hartzell** [comment]
Last time I played with the relocatable stuff, I ran into what sounds like a similar problem.  It turned out that I was trying to "relocate" it back into the same directory (on a different machine) into which it was built.  There's code that checked whether before and after were different (strings on the binaries or some such) and it was failing because they weren't different.  There was a PR or two (@gartung, perhaps), but I'm not sure they were ever 
merged.

**Comment by gartung** [comment]
A placeholder string is used during creation so it has to be replaced even if you install back into the same path.

**Comment by gartung** [comment]
Strings (other than rpath, ids, etc) can be replaced with a place holder of the same length. It the replacement is longer then the text replacement risks overwriting something vital in the object file. There might be a way to do this safely but I never figured it out.

**Comment by alalazo** [comment]
> Last time I played with the relocatable stuff, I ran into what sounds like a similar problem. It turned out that I was trying to "relocate" it back into the same directory (on a different machine) into which it was built. 

I need to check the details (meaning I still need to run the same command within a debugger), but I think what happens here is slightly different. The failure for me it's when *trying to create* a binary cache, and the error message suggests me that maybe there's some string in  `.rodata` that still refers to the original installation path. 

I opened a somewhat related issue some time ago #7237, basically to suggest that we should leave "holes" in the binary cache (i.e. if a few nodes in a DAG are not relocatable, only those nodes should always be rebuilt from source). 

What I am wondering here is how many packages are non-relocatable. It seems to me that e.g. `pkgconf` and `ncurses` are not, and those are pretty basic. As we want to set-up a binary mirror I was wondering if we have some strategies to deal with packages like this (or if I was doing something wrong when creating the binary cache, which I still hope).

**Comment by hartzell** [comment]
I haven't read through the docs/experimented recently, but how tightly bound is the the "relocatable" aspect to the concept of binary caches/mirrors?  My most common use case is "slap my pre-built stuff onto a new instance", putting back into the same place would be fine.

**Comment by alalazo** [comment]
> I haven't read through the docs/experimented recently, but how tightly bound is the the "relocatable" aspect to the concept of binary caches/mirrors?

@tgamblin can say more about that, but I would suspect the answer is *a lot* if we want to provide people with public binary mirrors. One of the strong points of Spack is that you can install software anywhere in your user space, it would be a pity if we lose this feature for the public binary mirror discussed in this issue.

**Comment by opadron** [comment]
I didn't think so, Bryon was looking into most of our use of S3.

I noticed that we have an empty bucket called `spack-mirror-binary`, so I went ahead and just used that.  We should now have two new subdomains:

 - s3.spack.io - redirects to the API endpoint for the `spack-mirror-binary` bucket.  Use this sub for uploading.  Set this as the `endpoint_url` if you're using boto, or send your hand-crafted POST requests here.  Once you've created the project on `gitlab.spack.io`, I'll make sure the AWS credentials for the generic `spack` user are in place.

 - mirror.spack.io - redirects to the web endpoint for the `spack-mirror-binary` bucket.  Configure spack clients to use this sub for downloading binaries.  Make sure that, when uploading, public read access is set.

Let me know if you want to talk about the details.

P.S.: We might want to add root-level paths to distinguish between binary and source mirrors, like `mirror.spack.io/bin` vs `mirror.spack.io/src`.  Ditto for the `s3` sub if we end up using different buckets for binary vs source mirrors.  So, these url's might not be set in stone, quite yet.

**Comment by tgamblin** [comment]
The binary and source mirror layouts are designed to coexist.  We may need to add settings to Spack so that the user can decide whether to use a specific mirror for source or binary, but I think using one is fine for now.

**Comment by AStupidBear** [comment]
@tgamblin Where can I find public binary mirrors to speed up installing?

**Comment by tgamblin** [comment]
E4S (https://e4s.io, part of ECP) is running a binary mirror -- the details are here:

* https://e4s-project.github.io/download.html

See "E4S build cache", which takes you here:
* https://oaciss.uoregon.edu/e4s/e4s_buildcache_inventory.html

Our goal is to eventually consolidate that and have it track mainline Spack, but we're not there yet. You can use it in containers right now, though.

**Comment by DiegoMagdaleno** [comment]
+ 1 for this it would be very useful for users that don't have super computers and need to build compilers that take a lot of time to build.

**Comment by tgamblin** [comment]
This is done; details TBA shortly after the 0.18 release.
