### ISSUE TITLE
compiler:environment needs docs in compilers.yaml

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7141]
The following is the only docs I could find.  I understand the concept, but this doesn't show how to do it, i.e. the right syntax.  I need an example:
```
The environment field of the compiler configuration is used for compilers that require environment variables to be set during build time. For example, if your Intel compiler suite requires the INTEL_LICENSE_FILE environment variable to point to the proper license server, you can set this in compilers.yaml.
```
The other items in compilers should be checked for docs as well: extra_rpaths, operating_system, spec, target???

**Comment by cwsmith** [comment]
@jrood-nrel pointed me at an example here:
https://github.com/Exawind/build-test/blob/462bf8c56ac3905347df325ee34e93bf149a84ec/configs/machines/peregrine/compilers.yaml

**Comment by davydden** [comment]
I was scratching my head how to do it as well...  Thanks for the link, @cwsmith , this helps. 

Nonetheless, it should certainly be documented.
