### ISSUE TITLE
Problem Building OpenBLAS on macOS

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7142]
I cloned the latest Spack on macOS 10.13.2.  This had been prepared by installing the lates Xcode 9.2 and a pre-built gfortran 6.3 (it says macOS Sierra, but there was indication it works for High Sierra as well):
https://gcc.gnu.org/wiki/GFortranBinaries#MacOS

When I tried to build OpenBLAS (`spack install openblas`), I get the following error:

```
==> Installing openblas
==> Fetching http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
######################################################################## 100.0%
==> Staging archive: /Users/citibob/spack/melissa/var/spack/stage/openblas-0.2.20-a2w7heujstxj3l65sbcbonk4yh6ta55z/v0.2.20.tar.gz
==> Created stage in /Users/citibob/spack/melissa/var/spack/stage/openblas-0.2.20-a2w7heujstxj3l65sbcbonk4yh6ta55z
==> Applied patch make.patch
==> Building openblas [MakefilePackage]
==> Executing phase: 'edit'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' 'CC=/Users/citibob/spack/melissa/lib/spack/env/clang/clang' 'FC=/Users/citibob/spack/melissa/lib/spack/env/clang/gfortran' 'MAKE_NO_J=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'

4 errors found in build log:
     [ ... ]
     4808  ar  -ru ../../libopenblas_haswell-r0.2.20.a strtri_UU_single.o strtri_UN_single.o strtri_LU_single.o strtri_LN_single.o dtrtri_UU_single.o dtrtri_UN_single.o dtrtri_LU_single.o dtrtri_LN_single.o ctrtri_UU_single.o ctrtri_UN_single.o ctrtri_LU_single.o ctrtri_LN_single.o ztrtri_UU_single.o ztrtri_UN_single.o ztrtri_LU_single.o ztrtri_LN_single.o qtrtri_UU_single.o qtrtri_UN_single.o qtrtri_LU_single.o qtrtri_LN_single.o xtrtri_UU_single.o xtrtri_UN_single.o xtrtri_LU_single.o xtrtri_LN_single.o
     4809  ( cd INSTALL; /Applications/Xcode.app/Contents/Developer/usr/bin/make )
     4810  /Users/citibob/spack/melissa/lib/spack/env/clang/gfortran -O2 -m128bit-long-double -Wall -m64 -fPIC -c -o lsame.o lsame.f
     4811  /Users/citibob/spack/melissa/lib/spack/env/clang/gfortran -O2 -m128bit-long-double -Wall -m64 -fPIC -c -o lsametst.o lsametst.f
     4812  /Users/citibob/spack/melissa/lib/spack/env/clang/gfortran -O2 -m128bit-long-double -Wall -m64 -fPIC -lgfortran -o testlsame lsame.o lsametst.o
     4813  ld: library not found for -lcrt1.10.6.o
  >> 4814  collect2: error: ld returned 1 exit status
  >> 4815  make[2]: *** [testlsame] Error 1
  >> 4816  make[1]: *** [lapack_install] Error 2
  >> 4817  make: *** [netlib] Error 2
```

Searching around for this error yields gfortran problems.  The solution suggested is to add an `-L` flag to the gfortran command, to make it look deep within XCode.  I did this by adding to my `compilers.yaml` file, which now looks like:

```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: highsierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib
      fc: /usr/local/bin/gfortran -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib
    spec: clang@9.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: highsierra
    paths:
      cc: null
      cxx: null
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: gcc@6.3.0
    target: x86_64
```
Sure enough, the file `crt1.10.6.o` exists in that directory.  So I built again.  Spack clearly didn't like that try:
```
  >> 4812  /Users/citibob/spack/melissa/lib/spack/env/clang/gfortran: line 365: exec: /usr/local/bin/gfortran -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib: cannot execute: No such file or directory
```

Spack needed me to set the `flags` setting in `compilers.yaml`.  A little non-intuitive, maybe, but not the end of the world...

A few questions:

1. Why did this not happen with a Homebrew-installed `gfortran` on another system?  A: Because Homebrew built the compiler correctly to know which Xcode directory to look into.  My binary-installed `gfortran` did not know this, so I have to help it.

Summary

### Expected Result

What you expected

### Actual Result

What happened instead

### Steps to reproduce the issue

```console
$ spack <command1> <spec>
$ spack <command2> <spec>
...
```

### Information on your system

This includes:

 1. which platform you are using
 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)

-----

We encourage you to try, as much as possible, to reduce your problem to the minimal example that still reproduces the issue. That would help us a lot in fixing it quickly and effectively!

If you want to ask a question about the tool (how to use it, what it can currently do, etc.), try the `#general` channel on our Slack first. We have a welcoming community and chances are you'll get your reply faster and without opening an issue.

Other than that, thanks for taking the time to contribute to Spack!

**Comment by goxberry** [comment]
This looks like the type of issue that arises due to not installing the XCode command-line tools (CLT). Homebrew has some infrastructure that will compensate for users that install XCode, but not the CLT, and vice versa.
