### ISSUE TITLE
Fortran compiler as a dependencie of openmpi package ?

### ISSUE THREAD

**Issue by Oximore** [spack/spack#7147]
# Fortran compiler as a dependencie of openmpi package ?

https://github.com/spack/spack/blob/770100765f0ebd6943780c6cddb1dfea970dcdd6/var/spack/repos/builtin/packages/openmpi/package.py#L283

##  Issue
I got an error : 
```
==> Installing openmpi
==> Fetching http://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.bz2
######################################################################## 100.0%
==> Staging archive: /root/Spack/spack/var/spack/stage/openmpi-3.0.0-4k4itv72zq7vbpmjuhzlcedbcpc6cyju/openmpi-3.0.0.tar.bz2
==> Created stage in /root/Spack/spack/var/spack/stage/openmpi-3.0.0-4k4itv72zq7vbpmjuhzlcedbcpc6cyju
==> No patches needed for openmpi
==> Building openmpi [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Error: InstallError: OpenMPI requires both C and Fortran compilers!
InstallError: InstallError: OpenMPI requires both C and Fortran compilers!

/root/Spack/spack/var/spack/repos/builtin/packages/openmpi/package.py:289, in die_without_fortran:
     4             # avoid delayed build errors in dependents.
     5             if (self.compiler.f77 is None) or (self.compiler.fc is None):
     6                 raise InstallError(
  >> 7                     'OpenMPI requires both C and Fortran compilers!'
     8                 )

See build log for details:
  /root/Spack/spack/var/spack/stage/openmpi-3.0.0-4k4itv72zq7vbpmjuhzlcedbcpc6cyju/openmpi-3.0.0/spack-build.out


more /root/Spack/spack/var/spack/stage/openmpi-3.0.0-4k4itv72zq7vbpmjuhzlcedbcpc6cyju/openmpi-3.0.0/spack-build.out
==> Executing phase: 'autoreconf'

```

## Explanation

After installing Spack on a fresh Ubuntu 16.04 (inside a Docker) I ran :  
```bash
spack install --only=dependencies mycustomlib_that_depend_of_scotch
```
To install dependencies to my library.
I suspect that Fortran compiler is not listed as a dependencie of openmpi package.
So Fortran compiler is not installed by Spack.
But I don't know how works Spack package dependencies for compilers.

## Reproduction 
If you want to reproduce, these lines - *a bit different than mines* - should be enough.

```bash
docker pull ubuntu:16.04
docker run -it ubuntu:16.04

cd ~/
which git || ( apt-get update -y && apt-get install git -y )
which curl || ( apt-get update -y && apt-get install curl -y )
which module || ( apt-get update -y && apt-get install environment-modules -y )
which python || ( apt-get update -y && apt-get install python -y )
mkdir -p Spack && cd Spack
git clone https://github.com/llnl/spack.git
module() { eval `/usr/bin/modulecmd bash $*`; }
source spack/share/spack/setup-env.sh  

spack install --only=dependencies scotch
```

Regards,
Benjamin

**Comment by davydden** [comment]
> I suspect that Fortran compiler is not listed as a dependencie of openmpi package.

compilers are not dependencies in Spack. You need to make sure that you have `gfortran`. Get it from Ubutu package manager, delete `compilers.yaml` in `.spack` and re-run `spack compiler find`. Then double check that `cc`, `cxx`, `f77` and `fc` are set correctly in `compilers.yaml` settings. 

Please re-open if the issue persist.

**Comment by helen9813488** [comment]
@davydden I had the same issue, and followed your instructions above.  In the resulting compiler.yaml file my f77 and fc are not set.  I have:
-compiler:
  spec: gcc@7.4.0
  paths:
  cc: /usr/bin/gcc
  cxx: /usr/bin/g++
  f77:
  fc:


What should I put for f77 and fc? I saw in your tutorials "/usr/bin/gfortran" but that doesn't exist on my system.  I tried "spack install gfortran" but got back "Error: Package 'gfrotran' not found.  I searched for gfortran and found a file with that name, edited compilers.yaml, but it does not seem to be an executable:

==> Error: CompilerAccessError: Compiler 'gcc@7.4.0' has executables that are missing or are not executable: ['./spack/lib/spack/env/gcc/gfortran', './spack/lib/spack/env/gcc/gfortran']

:~> which gfortran
which: no gfortran in (/home/helen/spack/bin:/home/helen/bin:/usr/local/bin:/usr/bin:/bin)

I can't work out how to install gfortran.  It should come with gcc but I don't seem to have it!

Many thanks!

Helen
