### ISSUE TITLE
View generation sometimes ignores --ignore-conflicts (e.g. py-jupyter-notebook)

### ISSUE THREAD

**Issue by healther** [spack/spack#7159]
I spend the last hour debugging this from a colleague....

### Expected Result

Usable `jupyter notebook` after a `spack install py-jupyter-notebook` 

### Actual Result
```
$ jupyter notebook
jupyter: 'notebook' is not a Jupyter command
```

### Steps to reproduce the issue

```console
$ git clone https://github.com/spack/spack.git && cd spack && . share/spack/setup-env.sh
$ spack install py-jupyter-notebook
$ spack view --dependencies yes add --ignore-conflicts $PWD/spackview py-jupyter-notebook
==> Error: Extension blocked by file: /wang/users/wv385/cluster_home/spack_failure/spack3/spackview/lib/python2.7/site-packages/backports/__init__.pyc
$ prepend_root spackview
$ jupyter notebook
jupyter: 'notebook' is not a Jupyter command
```

The problem is that the `view` command in the current develop seems to ignore (at least sometimes) the `--ignore-conflicts` flag aborting the view generation. In our local trunk there are patches tackling that but I currently don't know exactly what they are doing (even though I apparently authored them...)

I'm not sure if its worth fixing now as #7152 is taking a larger view onto that and also actually fixing the conflicts rather than just ignore any conflicts and pray for the best (I believe that is what we are doing). 

Thoughts? Comments? @scheibelp @alalazo @obreitwi

**Comment by scheibelp** [comment]
Hmm in https://github.com/spack/spack/issues/7001 I mentioned that `--ignore-conflicts` ought to allow merging multiple namespace packages into a view, so it's unfortunate that this isn't working. 

While #7152 ought to resolve this particular instance of the issue, overall it should be possible to ignore all conflicting files. Could you add the output when you run `spack -d view...`? That may provide a hint. I would like to look into this separately but wouldn't have a chance until possibly 2/12

**Comment by healther** [comment]
Unfortunately that doesn't provide too much information either:

```
$ spack -d view --dependencies yes add --ignore-conflicts $PWD/spackview py-jupyter-notebook
==> Reading config file /wang/users/wv385/cluster_home/spack_failure/spack3/etc/spack/defaults/modules.yaml
==> READ LOCK: /wang/users/wv385/cluster_home/spack_failure/spack3/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /wang/users/wv385/cluster_home/spack_failure/spack3/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /wang/users/wv385/cluster_home/spack_failure/spack3/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /wang/users/wv385/cluster_home/spack_failure/spack3/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /wang/users/wv385/cluster_home/spack_failure/spack3/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /wang/users/wv385/cluster_home/spack_failure/spack3/opt/spack/.spack-db/lock[0:0] [Released]
==> Warning: While activating python@2.7.14%gcc@7.2.0 patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+shared~tk~ucs4 arch=linux-debian8-x86_64 /il3e37k, found conflict /wang/users/wv385/cluster_home/spack_failure/spack3/spackview/lib/python2.7/site-packages/backports/__init__.pyc
```

I can try to clean up my current trunk over the weekend, if I don't get to it, I'll just dump the relevant diff between our current trunk and develop some place

**Comment by healther** [comment]
Actually on second thought I'm not sure if #7001 is affected, b/c `spack load -r py-jupyter-notebook` works fine
