### ISSUE TITLE
libtoolize not found

### ISSUE THREAD

**Issue by f-sim** [spack/spack#7163]
I tried to install gcc on macOS high sierra. This failed when installing gmp.

It failed with the following error:
```
Error: ProcessError: /Users/<username>/Software/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/libtool-2.4.6-yjjy7rl7ow76cixrcfwg7bdqvmc3wmy6/bin/libtoolize: No such file or directory
```

Checking the path above, I found a tool ```glibtoolize``` inside the ```bin``` folder.
The issue was solved by adding a symolic link from glibtoolize to libtoolize. However, that seems to me like an odd workaround.

### Steps to reproduce the issue

```console
$ spack install gcc@7.3.0 +piclibs
```

**Comment by goxberry** [comment]
It would be helpful to see the logs. Namely, do the following:

```console
spack install gcc@7.3.0 +piclibs --keep-stage --verbose 2>&1 | tee spack-build.out
```

Then, after the installation fails:

```console
ls $(spack location -s gcc@7.3.0)
```

You should see a directory listing with one directory and one tar-xzipped file. Let the directory name you see be GCC_DIR. Send `$(spack location -s gcc@7.3.0)/${GCC_DIR}/spack-build.env`, `$(spack location -s gcc@7.3.0)/${GCC_DIR}/spack-build.log`, and `spack-build.out`. Chances are that the last file will contain the same output as the `spack-build.log` file, but sometimes, parallel invocations of GNU Make will take a while to exit after an error, so capturing output at the terminal is a good backup if you don't want to wait for that to happen.

In the future, please send these log files. It's far easier to debug a problem if the information in the logs is attached.

**Comment by f-sim** [comment]
Please find the log files attached. First of all the installation fails already when building `gmp`. Therefore, I took the log files from `ls $(spack location -s gmp)`. There was no file `spack-build.log`, but instead another `spack-build.out`. This is the file `spack-build.out2`.

[spack-build.env.txt](https://github.com/spack/spack/files/1691883/spack-build.env.txt)
[spack-build.out.txt](https://github.com/spack/spack/files/1691884/spack-build.out.txt)
[spack-build.out2.txt](https://github.com/spack/spack/files/1691885/spack-build.out2.txt)

**Comment by goxberry** [comment]
Thanks! Will take a look.

I've started working on the fixes I've proposed in #7172, and have a spack package with most of Apple's native build toolchain in #7177, so I'm hoping that will help lead to a more lasting solution, as well as some quicker short-term fixes while a more permanent solution is put in place.

**Comment by goxberry** [comment]
Okay, I was able to reproduce the issue. Try #7179, which seems to fix it.

**Comment by f-sim** [comment]
Yes, I tested it. With your PR the issue is fixed. By the way, I tested it with macOS 10.13.

**Comment by scheibelp** [comment]
#7179 is now merged so this should be resolved. Please reopen if the issue persists
