### ISSUE TITLE
self-referencing symlink failure

### ISSUE THREAD

**Issue by tagardi** [spack/spack#7174]
Summary

I'm trying to write a very simple new package for the x264 library used by ffmpeg.  The package.py file looks like this:
```python
from spack import *

class Libx264(AutotoolsPackage):
    """This installs x264, a free software library and application for encoding video streams into the H.264/MPEG-4 AVC compression format, released under the terms of the GNU GPL."""

    # FIXME: Add a proper url for your package's homepage here.
    homepage = "http://www.videolan.org/developers/x264.html"
    url      = "ftp://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20180201-2245-stable.tar.bz2"

    version('264-snapshot-20180201-2245', '8b4ccde2d6746fbb9f8672d8b41efe8e')

    # FIXME: Add dependencies if required.
    # depends_on('foo')

    def configure_args(self):
        # FIXME: Add arguments other than --prefix
        # FIXME: If not needed delete this function
        args = ['--disable-asm']
        return args
```
### Expected Result

When manually executing configure, make, etc. this code builds out of the box, so I expected this should be relatively simple.

### Actual Result

Instead, it appears that during the "autoreconf" process the Makefile is replaced by a self-referencing soft link.  This causes the "spack install libx264" command to fail with the error "make: Makefile: Too many levels of symbolic links".

### Steps to reproduce the issue

Simply adding the above package.py file in builtin/packages/libx264/package.py and executing

```console
$ spack install libx264
```
should reproduce the problem.

### Information on your system

This problem occurs on darwin, el capitan, 10.11.6

I've seen issues of this sort reported in the past.  Any thoughts on how to resolve this?
Thanks!

**Comment by scheibelp** [comment]
Setting `build_directory = 'spack-build'` like in https://github.com/spack/spack/pull/3543 may resolve the issue

**Comment by tagardi** [comment]
Thanks!  That fixed the build problem for me.

**Comment by alalazo** [comment]
Closing the issue, as it seems solved. Please reopen if I got it wrong.
