### ISSUE TITLE
Mark a package as non-relocatable

### ISSUE THREAD

**Issue by alalazo** [spack/spack#7237]
This is a feature request to add the possibility to mark packages as non-relocatable.

We have since a while the possibility to build binary caches of packages that have been installed. This enhances a lot the user the experience, as the installation time may be dramatically reduced for specs whose binary artifacts are available.

However not all the packages may be relocated. The simplest example that comes to my mind is packages that have absolute paths hardcoded somewhere (maybe in a `config.h` file that gets generated at configure or build time). 

What I propose here is to be able to mark packages as non-relocatable:
```python
class EnvironmentModules(Package):
    relocatable = False
    ...
```
and that should have the effect of skipping this node when creating the binary cache of the DAG (thus enforcing a source build).

### Expected Result

The binary cache of a dependency DAG containing nodes that are not relocatable should enforce building those nodes from sources.

### Actual Result

Sometimes we put in cache packages that are not relocatable, and that may cause failures at run-time:
```console
$ spack install --use-cache environment-modules
...
==> Installing environment-modules
==> Searching for binary cache of environment-modules
==> Installing environment-modules from binary cache
==> Fetching http://0.0.0.0:32679/build_cache/linux-ubuntu14.04-x86_64/gcc-4.8/environment-modules-3.2.10/linux-ubuntu14.04-x86_64-gcc-4.8-environment-modules-3.2.10-bwjr7qmyssvp2bjk2jnqw75c2qqedrde.spack
######################################################################## 100,0%
gpg: Signature made ven 09 feb 2018 22:03:38 CET using RSA key ID A1A440B6
gpg: Good signature from "Massimiliano Culpo (GPG created for Spack) <massimiliano.culpo@gmail.com>"
==> Relocating package from
  /home/spack/opt/spack to /home/mculpo/PycharmProjects/spack/opt/spack.
==> Successfully installed environment-modules from binary cache
[+] /home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14.04-x86_64/gcc-4.8/environment-modules-3.2.10-bwjr7qmyssvp2bjk2jnqw75c2qqedrde

$ . share/spack/setup-env.sh
$ module av
init.c(556):ERROR:161: Cannot initialize TCL
```

@gartung @tgamblin

**Comment by citibeth** [comment]
LGTM

**Comment by gartung** [comment]
The only thing I can think of is to throw an exception if the path string appears in a binary file, stopping the creation of the buildcache. Would that suffice?

**Comment by gartung** [comment]
I don't know how I would distinguish between rpaths in the binary and paths compiled in as strings.

**Comment by citibeth** [comment]
Copy the binary to a new file.  Use an RPATH-changing tool to blank out all
RPATHs.  Then grep the new binary to see if you can find the string.

**Comment by gartung** [comment]
PS I have two pull requests that have been sitting for two months that improve the preformace or relocation on macOS and generates proper error messages.

**Comment by gartung** [comment]
That could work but it adds extra time to the buildcache creation.

**Comment by citibeth** [comment]
Now you're moving the goalposts! ;-)  I don't think there's any way to
determine whether binaries contain the package string without adding extra
time to the buildcache creation.

Seriously, though... you might find it's not that much time.  Executables
aren't that big, compared to how fast modern computers can read, write and
scan them.  Especially if the copy is placed in a proper temp directory,
which should be a local FS, and it will often be cached in RAM.

**Comment by gartung** [comment]
Sure. I already make a copy of the install directory so I can add the extra files needed for relocation. I might as well replace the rpaths with placholders then and check if any install paths are left.

**Comment by gartung** [comment]
#7314 should address this.

**Comment by alalazo** [comment]
@scheibelp @gartung I see this has been closed. Can we now do something like:
```
class Foo(package):
    relocatable = False
    ...
```
? Or are you saying that theoretically every package is relocatable (so there's no need to be able to mark them as proposed above) + #7314 addresses the case of paths in the data segment? 

p.s. I didn't have time so far to look deeply into #7314, so apologies if the question is trivial.

**Comment by gartung** [comment]
That is the idea. Since install --use-cache was added by other contributers I will leave it up to them to add the code to handle that the Relocatable property.

**Comment by scheibelp** [comment]
@gartung the example here refers to `--use-cache` but I don't think that's the core issue: my understanding is that the goal here is to skip the creation of binary packages when they cannot be relocated. When I think on it more the updates in #7314 prevent creation of a binary package in this case but don't allow smoothly skipping over a package which fails to relocate, so it is less-convenient for the person creating the binary packages. Therefore it makes sense to keep this open.

A reasonable solution would be to add `--skip-non-relocatable` to `spack buildcache create` which allows skipping over dependencies that cannot be relocated.

Does that seem sensible?

**Comment by alalazo** [comment]
The purpose was to have a simple marker so that, when creating a binary cache of a complex DAG, we could skip only the nodes that are not relocatable. Later, when installing from that binary cache, the non-relocatable nodes should have been the only ones rebuilt from sources.

I proposed this approach out of ignorance on what could be the causes, other than a path in the data segment, that make a package non-relocatable. If we could detect automatically when a package is non-relocatable, I think that would be better indeed. 

Are we already skipping non-relocatable packages or is there some further action to be taken?

**Comment by gartung** [comment]
@alalzo Yes, by default they are skipped. I haven't tested what happens if you have a non-relocatable package in a DAG and don't create the tarball with the buildcache -a option.

**Comment by alalazo** [comment]
@scheibelp @gartung I'll give it a try again in the incoming days, and post results (or further questions) here. Thanks for the clarifications so far.

**Comment by gartung** [comment]
You couldn't really skip over a dependency. There would be a missing node in the DAG (if that makes sense). The best I can do is warn and warn again that the package needs manual intervention to function properly.

**Comment by alalazo** [comment]
> There would be a missing node in the DAG (if that makes sense).

That's the idea. The missing bit (and only that one) you rebuild from sources. Does it make sense?

**Comment by gartung** [comment]
I only know of three  packages where relocation is broken: tcl, environment-modules and maybe R.

**Comment by gartung** [comment]
> That's the idea. The missing bit (and only that one) you rebuild from sources. Does it make sense?

I am not sure that is possible. You are pruning the branch by not including that package. Never hurts to try though.

**Comment by gartung** [comment]
You would probably have to build the non-relocatable package first. You might be able to install its dependencies from buildcaches and install its dependents from buildcaches after that.

**Comment by alalazo** [comment]
> You would probably have to build the non-relocatable package first. You might be able to install its dependencies from buildcaches and install its dependents from buildcaches after that.

Exactly. That was the idea proposed here. The marker was just a manual way to do something that apparently can be done automatically.

**Comment by gartung** [comment]
With the merge of https://github.com/spack/spack/pull/9199 this can be close.

**Comment by alalazo** [comment]
Reopening after discussion in #11341

**Comment by vvolkl** [comment]
The `relocatable = false` proposal makes a lot of sense to me. We tried using `spack buildcache`, but dealing with the few packages that do strange things with their path has been a major headache that led to mostly abandoning the build cache. However, restricting its use to relocatable packages seems like it could become useful to us.

**Comment by alalazo** [comment]
@gartung Don't know if this is still relevant, but when was this completed?
