### ISSUE TITLE
Rebuilding modules fails for dependents of `gdbm`

### ISSUE THREAD

**Issue by goxberry** [spack/spack#7239]
### Summary

Rebuilding lmod module tree fails for dependents of `gdbm` (but succeeds for `gdbm`, and most other packages).

### Expected Result

`spack module refresh -m lmod --delete-tree -y` regenerates all Lmod modules

### Actual Result

Any module that depends on `gdbm` (e.g., `autoconf`) will throw a warning:

```console
==> Warning: Could not write module file [/Users/oxberry1/spack/share/spack/lmod/darwin-sierra-x86_64/Core/autoconf/2.69.lua]
==> Warning:    --> Cannot create a consistent method resolution
order (MRO) for bases Spec, SpecBuildInterface <--
```

### Steps to reproduce the issue

```console
$ spack install autoconf
$ spack module refresh -m lmod --delete-tree -y
...
```

### Information on your system

This includes:

 1. macOS / OS X 10.12.6
 2. I don't have any customizations related to autoconf, but would be happy to provide config files on request if they might be useful.

### History

I think this issue is a continuation of #6089 and #5864. Moving use of `spack_cc` into `setup_environment` solved issues relating to the expansion of `spack_cc`, so now instead of `gdbm` and its dependents throwing errors, only dependents of `gdbm` throw errors. The problem seemed to be introduced by #5893, and #7225 improved the situation slightly -- efore #7225, module files for `gdbm` could not be regenerated either.

### Narrowing down the problem

I tried running `spack -D module refresh -m lmod --delete-tree -y` and got as far as tracking down the error to within a method call at `spack/tengine.py:85`. Set a breakpoint at `spack/cmd/module.py:317` conditional on `'automake' in x.spec.name`. Once this breakpoint triggers, set a breakpoint in `spack/tengine.py:85`. Around the 15th-ish execution of that line (after the breakpoint in `module.py`), the method resolution order error throws. I couldn't narrow down the problem further.

### Workaround

A workaround for now is to reinstall the packages that throw warnings, because the module file written upon installation is apparently fine.

**Comment by amklinv** [comment]
I am also interested in the resolution of this issue.

**Comment by jrood-nrel** [comment]
I'm seeing this a lot now since I've been managing modules with Spack.

**Comment by alalazo** [comment]
I had some time this morning to track down the error, and have to say it's a "funny" one. The error  comes from `perl`, in particular from the line:
```python
def setup_dependent_package(self, module, dependent_spec):
    """Called before perl modules' install() methods.
        In most cases, extensions will only need to have one line:
       perl('Makefile.PL','INSTALL_BASE=%s' % self.prefix)
     """
     # perl extension builds can have a global perl executable function
     module.perl = self.spec['perl'].command # <-- ERROR
     ...
```
and is due to the fact that when building module files we pass to this function a class that *is already* a `SpecBuildInterface`, and building a `SpecBuildInterface` from another `SpecBuildInterface` creates an inconsistent MRO. 

I'll try to work on a permanent fix to this (shouldn't be a lot of lines), but a workaround for who needs it is to change:
```python
module.perl = self.spec['perl'].command # <-- ERROR
```
with
```python
module.perl = self.spec.command
```
before regenerating module files. The change must be undone before installing a new package that depends on `perl`.

**Comment by alalazo** [comment]
Can you check if #7457 solves the issue?

**Comment by luigi-calori** [comment]
I had a similar problem,
 I can confirm that:
spack module refresh -y  git
gives , under currend dev
==> Warning: 	--> Cannot create a consistent method resolution
order (MRO) for bases SpecBuildInterface, Spec <--

while checking out  #7457 solve the problem
sol
