### ISSUE TITLE
MPICH git broken; needs submodules

### ISSUE THREAD

**Issue by omor1** [spack/spack#7246]
`mpich@develop` is broken (presumably since October 30, 2017), since it now requires submodules.
The fix is to add `submodules=True` to the the `version()` command:

```diff
-version('develop', git='git://github.com/pmodels/mpich')
+version('develop', git='git://github.com/pmodels/mpich', submodules=True)
```

### Expected Result

MPICH compiles and installs correctly. 

### Actual Result

I get an error about missing submodules.

### Steps to reproduce the issue

```console
$ spack install mpich@develop
```

### Information on your system

Arch Linux x86_64, but not truly important—this is a package problem.

**Comment by citibeth** [comment]
Can you submit the PR?
