### ISSUE TITLE
Docs: in tutorial Mpileaks is inherited from AutoToolsPackage

### ISSUE THREAD

**Issue by dmitry-kabanov** [spack/spack#7249]
There is a small typo in the documentation.
In the tutorial, when different build systems are explained, there is a typo:

Mpileaks is inherited from AutoToolsPackage, should be AutotoolsPackage
Because of this, whenever I tried to install any package (a different one from mpileaks), and was getting an error 'Error: name 'AutoToolsPackage' is not defined'.

**Comment by mamelara** [comment]
sorry about that, and thanks for pointing it out

**Comment by dmitry-kabanov** [comment]
Thank you!

**Comment by mamelara** [comment]
Fixed in #7346
