### ISSUE TITLE
help-wanted vs help wanted labels

### ISSUE THREAD

**Issue by markcmiller86** [spack/spack#7262]
Happened to notice that Spack's label set includes two labels of similar name, ``help-wanted`` and ``help wanted``. I think GitHub has special sauce for the later form but not the former? In addition, the dash-form is associated with **one** Spack issue where as the non-dash-form is associated with 7, https://github.com/spack/spack/labels?page=2&sort=name-asc. I would adjust myself but am worried it'll cause other unforseen issues. But, if you go to above link, you can delete the dash-form

**Comment by markcmiller86** [comment]
@davydden...is that thumbs-up an indication you are ok with me deleting it?

**Comment by davydden** [comment]
> ..is that thumbs-up an indication you are ok with me deleting it?

I am, but let's wait for others to weight in.

**Comment by alalazo** [comment]
I am pretty sure I created the `help wanted` and `good first issue` labels a while ago, when [github started advertizing](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/) their use as a standard way to help newcomes getting started with a project.  As far as I remember `help-wanted` was already there, and I didn't delete it. 

That said, I completely agree deleting `help-wanted`, but I'd let @tgamblin do it in case the tag is there for some other reason (e.g. tools that are external to github).

**Comment by alalazo** [comment]
The `help-wanted` label has been already deleted. Closing.
