### ISSUE TITLE
spackcc assumes includes are always in <prefix>/include

### ISSUE THREAD

**Issue by junghans** [spack/spack#7268]
Looking at https://github.com/spack/spack/blob/develop/lib/spack/env/cc#L273, `spackcc` assumes that headers are always in `<prefix>/include`, which isn't always the case. Especially for external package on Debian/Ubuntu some headers live in e.g. `/usr/lib/x86_64-linux-gnu/openmpi/include/`.

See #7255 for an example.

**Comment by alalazo** [comment]
I think this can be understood as reporting 2 issues:
1. Include directories were always `<prefix>/include` (solved in #10623)
2. External packages can't set their paths at a finer grain (tracked in #6472)

As everything here seems to be already solved or tracked elsewhere I'm closing this issue, but feel free to reopen if you think there's something I didn't account for.
