### ISSUE TITLE
Intel MKL static library linking order (HPL installation failure)

### ISSUE THREAD

**Issue by pramodskumbhar** [spack/spack#7279]
I was trying to install HPL with Intel MKL as below:

```
hpl@2.2%intel@18.0.1~openmp arch=linux-rhel7-x86_64
    ^intel-mkl@2018.1.163%intel@18.0.1~ilp64~shared threads=none arch=linux-rhel7-x86_64
    ^intel-mpi@2018.1.163%intel@18.0.1 arch=linux-rhel7-x86_64
```

The installation fails with the error:

```
 /gpfs-path/intel-mpi-2018.1.163/compilers_and_libraries/linux/mpi/intel64/bin/mpiicc -DAdd_ -DF77_INTEGER=int -DStringSunStyle -DHPL_DETAILED_TIMING -DHPL_PROGRESS_REPORT -I/tmp/kumbhar/spack-stage/spack-stage-9VZvqF/hpl-2.2/include -I/tmp/kumbhar/spack-stage/spack-stage-9VZvqF/hpl-2.2/include/Linux-x86_64 -I/gpfs-path/intel-mkl-2018.1.163/include -I/gpfs-path/intel-mpi-2018.1.163/include -O3  -o /tmp/kumbhar/spack-stage/spack-stage-9VZvqF/hpl-2.2/bin/Linux-x86_64/xhpl HPL_pddriver.o         HPL_pdinfo.o           HPL_pdtest.o /tmp/kumbhar/spack-stage/spack-stage-9VZvqF/hpl-2.2/lib/Linux-x86_64/libhpl.a /gpfs-path/intel-mkl-2018.1.163/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_intel_lp64.a /gpfs-path/intel-mkl-2018.1.163/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.a /gpfs-path/intel-mkl-2018.1.163/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_sequential.a -L/gpfs-path/intel-mpi-2018.1.163/lib
/gpfs-path/intel-mkl-2018.1.163/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_sequential.a(d__trsm_seq.o): In function `mkl_blas_dtrsm':
_trsm.c:(.text+0x4c): undefined reference to `mkl_blas_xdtrsm'
/gpfs-path/intel-mkl-2018.1.163/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_sequential.a(d__gemm_seq.o): In function `mkl_blas_dgemm':
_gemm.c:(.text+0x13c): undefined reference to `mkl_serv_cpu_detect'
_gemm.c:(.text+0x283): undefined reference to `mkl_blas_xdgemm'
_gemm.c:(.text+0x3f4): undefined reference to `mkl_serv_allocate'
_gemm.c:(.text+0x473): undefined reference to `mkl_serv_deallocate
```

If we look at the order of libraries suggested by [intel-mkl-link-line-advisor](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor), it looks like:

```
 ${MKLROOT}/lib/intel64/libmkl_scalapack_lp64.a -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_cdft_core.a ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a ${MKLROOT}/lib/intel64/libmkl_blacs_intelmpi_lp64.a
```

So the `libmkl_core.a` should appear after `libmkl_sequential.a.

**Comment by davydden** [comment]
Dynamic linking also places it after:
‘’’
 -L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
‘’’

**Comment by davydden** [comment]
Need to change this line:

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/intel-mkl/package.py#L126

**Comment by karanchhabra** [comment]
Hi,

I'm trying to run HPL compiled using CUDA. 

What I have on the system:

1. Nvidia driver (TESLA DRIVER FOR LINUX RHEL 7, Version: 390.30)
2. CUDA installation toolkit (cuda-repo-rhel7-9-1-local-9.1.85-1.x86_64.rpm)
3. Mpich (mpich-3.2.1)
4. openBLAS (OpenBLAS-0.2.20)
5. HPL provided by nvidia (hpl-2.0_FERMI_v15_latest)

When I run the code it complaints about missing libmkl_intel_lp64.so but when i do ldd for xhpl, it shows no dependency on libmkl_intel_lp64.so. Moreover i've used openblas to compile HPL not sure why is it asking for an intel make library!

Any suggestions.

What I run:
/root/hpl/mpich/bin/mpirun -np 1 -hostfile nodes ./run_linpack

Error:
libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

Dependency tree:
ldd xhpl
linux-vdso.so.1 => (0x00007ffeb597c000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd1e10f4000)
libdgemm.so.1 => /root/hpl/hpl-2.0_FERMI_v15_latest/src/cuda/libdgemm.so.1 (0x00007fd1e0eeb000)
libcublas.so.9.1 => /usr/local/cuda/lib64/libcublas.so.9.1 (0x00007fd1dd954000)
libcuda.so.1 => /usr/lib64/nvidia/libcuda.so.1 (0x00007fd1dcdb4000)
libcudart.so.9.1 => /usr/local/cuda/lib64/libcudart.so.9.1 (0x00007fd1dcb45000)
libopenblas.so.0 => /root/hpl/openblas/lib/libopenblas.so.0 (0x00007fd1dbbb6000)
libmpi.so.12 => /root/hpl/mpich/lib/libmpi.so.12 (0x00007fd1db737000)
libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fd1db510000)
libc.so.6 => /lib64/libc.so.6 (0x00007fd1db14d000)
/lib64/ld-linux-x86-64.so.2 (0x00005633fe7d7000)
librt.so.1 => /lib64/librt.so.1 (0x00007fd1daf45000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007fd1dad40000)
libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd1daa38000)
libm.so.6 => /lib64/libm.so.6 (0x00007fd1da736000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd1da51f000)
libnvidia-fatbinaryloader.so.390.30 => /usr/lib64/nvidia/libnvidia-fatbinaryloader.so.390.30 (0x00007fd1da2d3000)
libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fd1d9fb1000)
libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fd1d9d74000)

*Can't see libmkl_intel_lp64.so mentioned anywhere there but still everytime i run HPL it complaints about missing libmkl_intel_lp64.so

Thanks,
Karan
