### ISSUE TITLE
Frequent errors on Travis build tests

### ISSUE THREAD

**Issue by alalazo** [spack/spack#7299]
Since we removed verbosity in build tests (#6901) we experience a high number of build errors in Travis, with this error message:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

On the other hand, Travis logs are terser so I am wondering if we should solve this issue by reverting #6901 or by using a [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) on build tests.

### Expected Result
Build tests shouldn't timeout.

### Actual Result

Build tests error frequently because of timeouts, and sometimes they need to be retriggered manually several times before they succeed.

**Comment by adamjstewart** [comment]
I vote for using `travis_wait`.

**Comment by alalazo** [comment]
@adamjstewart I share the same opinion. Will prepare a PR tomorrow.

**Comment by alalazo** [comment]
It seems `travis_wait` didn't help. I'll have a better look into it, but I think the build tests are mainly failing on network connections when trying to fetch packages. The next thing I can do is try to setup a cached mirror on Travis, which contains sources for build tests + pin the version of the packages we build (so that a new version won't compromise test success). Thoughts?

**Comment by healther** [comment]
another thing would be to give `spack install` a quiet or robust mode in which it retries to fetch sources repeatedly. I see this from time to time on our CI, there we could get around most of the fetch failures by simply putting a retry around the install command

**Comment by alalazo** [comment]
@healther I think retries are worth a PR. That + source caching + #5842 should hopefully speed-up testing and make it more robust.

**Comment by alalazo** [comment]
#7392 seems to have solved this. I'll monitor a bit more, and if Travis continue to give green light I'll close this issue.

**Comment by healther** [comment]
Just as a thought: Since #7392 removes most fetches from the CI it may be worth thinking about a regularly running job that simply tries to fetch all packages (note: I have no idea how much data we are actually talking) with the aim to at least mark urls that are broken. This would have the added benefit of us having data to decide which mirrors we prefer.

**Comment by adamjstewart** [comment]
There was talk of setting up an LLNL mirror for every Spack package at some point. Not sure what the status on that is. @tgamblin?

**Comment by alalazo** [comment]
@adamjstewart @healther see #7121 

p.s. I don't think Travis is a good fit for actually fetching all the packages...

**Comment by alalazo** [comment]
Closing this, as right now Travis builds seem alright
