### ISSUE TITLE
QUESTION: The preferred=True version elfutils doesn't build with gnu 7.2 compilers

### ISSUE THREAD

**Issue by jgalarowicz** [spack/spack#7316]
I have a question on how to handle the situation where the preferred version of elfutils gets compiler errors with gnu 7,2 compilers.   Here is how I solved it temporarily for my own purposes, but how do we handle this in general.  Someone must have wanted version .163 to be the default, but that doesn't work for all builds.   So, asking for advice on how to fix for all to be happy.

    version('0.170', '03599aee98c9b726c7a732a2dd0245d5', preferred=True)
    version('0.168', '52adfa40758d0d39e5d5c57689bf38d6')
    #version('0.163', '77ce87f259987d2e54e4d87b86cbee41', preferred=True)

**Comment by jgalarowicz** [comment]
@healther 

'''I've been experimenting with this syntax.   Would that work for you.  It eliminates users from having to alter their spack environment.

version('0.170', '03599aee98c9b726c7a732a2dd0245d5', preferred=True, when='%gcc@7.2.0:')    version('0.168', '52adfa40758d0d39e5d5c57689bf38d6')
version('0.163', '77ce87f259987d2e54e4d87b86cbee41', preferred=True)

It did the right thing for:
spack install elfutils%gcc@7.2.0
I'm trying 
spack install elfutils%gcc@4.8
and will try:
spack install elfutils
to see if it figures out when version to use for this.
'''
Jim G

**Comment by healther** [comment]
I'm not sure.. I'm not aware of a use of `when` within a `depends_on`. You could try to add a `conflicts` statement:
`conflicts('gcc@7.2.0', when='@:0.164')`
But I'm not sure how the interaction with `preferred` will shake out. Maybe @alalazo or @scheibelp has an idea

**Comment by jgalarowicz** [comment]
@healther - Yes, my change didn't work.   spack install elfutils%gcc@4.8 still used the 0.170 version.
The conflicts statement might work better.   Or maybe someone else has an idea.

**Comment by jgalarowicz** [comment]
@healther I will add a conflicts statement for gcc-7.2.0 in elfutils as you suggested.   This is in PR #7338.

**Comment by jgalarowicz** [comment]
@healther @tgamblin Hi again.   Adding the conflicts clause, doesn't really help make the automatic build of OpenSpeedShop with spack work.    In the tools world, I think there is a trend away from libdwarf and to libdw which is in elfutils.  Dyninst wants elfutils and libdw not libdwarf.   OpenSpeedShop is dependent on Dyninst and therefore elfutils and libdw, but I can't build that seemlessly with elfutils-0.163 as the preferred version.   And since this is an indirect usage for us (via Dyninst) I'm powerless to change it.   Can't the packages that need 0.163 request it explicitly?   I have to deliver a milestone that depends on this, but I can't without telling the person/lab that they have to change the elfutils package to comment on the preferred=True line.
Thanks,
Jim G

**Comment by healther** [comment]
I'm unaware of the political implications (and also don't want to know^^). You can override defaults by explicitly telling spack which versions to use. Either via the command line (`spack install <yourpackage> ^elfutils@0.170`) or via a [`package.yaml`](http://spack.readthedocs.io/en/latest/build_settings.html#concretization-preferences)
```
packages:
  elfutils:
    versions: [0.170]
```
For the latter option there are multiple configuration scopes you can choose from. (Personally I removed all configuration scopes from spack except the repository level one)

**Comment by healther** [comment]
for a complete reference look here: http://spack.readthedocs.io/en/latest/configuration.html

Basically there are (in order of decreasing precedence) `$HOME/.spack`, `$SPACK/etc/spack`, `/etc/spack`, `$SPACK/etc/spack/defaults` (all can also have additional arch, i.e. OS specific ones). 
Each folder can hold any configuration file (I guess the earlier ones extend and override the latter ones). Since I'm using multiple instances of spack I don't want to use anything that is not within the repository, therefore I removed options 1, 3 and 4.

**Comment by healther** [comment]
you can find a complete set of files in `$SPACK/etc/spack/defaults` and put these in any of the above mentioned locations. The `../linux` and `../cray` are the arch dependent ones

**Comment by jgalarowicz** [comment]
@healther Thanks for the information!    I will close this issue then and add this information into the OpenSpeedShop spack build guide.

**Comment by jgalarowicz** [comment]
Reopening because the solution I thought would work for allowing OpenSpeedShop to build doesn't seem to be working.   I put    
```
elfutils:
      version: [0.170]
```
into my $HOME/.spack/packages.yaml file in hopes it would override the frustrating preferred=True for version 0.163 of elfultils, but that didn't override it.  I'm presenting how to use spack to build OpenSpeedShop next week, but I have this issue which makes building OpenSpeedShop have a glitch (using ^elfutils@0.170) on the command line.  

Here is what I see, just trying to build with a clean command line.   See below for what I have in packages.yaml.    Does anyone see what I'm doing wrong?

```
spack install openspeedshop +openmpi
==> Error: Conflicts in concretized spec "openspeedshop@2.3.1%gcc@7.2.1 build_type=None +cbtf~crayfe~cti~cuda gui=qt3 ~mpich~mpich2~mpt~mvapich~mvapich2~offline+openmpi~runtime arch=linux-fedora27-x86_64 /fhvtmhe"
List of matching conflicts for spec:

    elfutils@0.163%gcc@7.2.1 arch=linux-fedora27-x86_64 
        ^bison@3.0.4%gcc@7.2.1 patches=b72914fe38e54a6fc25f29019e0a0786705c4f61ce20d414cc2010c8d62448c7 arch=linux-fedora27-x86_64 
            ^m4@1.4.18%gcc@7.2.1 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00 +sigsegv arch=linux-fedora27-x86_64 
                ^libsigsegv@2.11%gcc@7.2.1 arch=linux-fedora27-x86_64 
        ^flex@2.6.4%gcc@7.2.1+lex arch=linux-fedora27-x86_64 
            ^gettext@0.19.8.1%gcc@7.2.1+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-fedora27-x86_64 
                ^bzip2@1.0.6%gcc@7.2.1+shared arch=linux-fedora27-x86_64 
                ^libxml2@2.9.4%gcc@7.2.1+python arch=linux-fedora27-x86_64 
                    ^pkgconf@1.4.0%gcc@7.2.1 arch=linux-fedora27-x86_64 
                    ^python@2.7.14%gcc@7.2.1+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+shared~tk~ucs4 arch=linux-fedora27-x86_64 
                        ^gdbm@1.14.1%gcc@7.2.1 arch=linux-fedora27-x86_64 
                            ^readline@7.0%gcc@7.2.1 arch=linux-fedora27-x86_64 
                                ^ncurses@6.0%gcc@7.2.1 patches=4110a40613b800da2b2888c352b64c75a82809d48341061e4de5861e8b28423f,f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-fedora27-x86_64 
                        ^openssl@1.0.2n%gcc@7.2.1+systemcerts arch=linux-fedora27-x86_64 
                            ^zlib@1.2.11%gcc@7.2.1+optimize+pic+shared arch=linux-fedora27-x86_64 
                        ^sqlite@3.22.0%gcc@7.2.1 arch=linux-fedora27-x86_64 
                    ^xz@5.2.3%gcc@7.2.1 arch=linux-fedora27-x86_64 
                ^tar@1.29%gcc@7.2.1 patches=08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c,5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4,d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4,e34d2470461037933737c0a60fbcc5d5ea905fefb6b414b4a2e88a440fcae23a arch=linux-fedora27-x86_64 
            ^help2man@1.47.4%gcc@7.2.1 arch=linux-fedora27-x86_64 

1. "%gcc@7.2.0:" conflicts with "elfutils@0.163"
```

```
[jeg@localhost packages]$ cat ~/.spack/packages.yaml 
packages:
   #all:
   #   providers:
   #      pkgconfig: [pkg-config]
   qt:
      buildable: False
      variants: +krellpatch
      paths:
         qt@3.3.8b%gcc@7.2.1 arch=linux-fedora27-x86_64: /usr/lib64/qt-3.3
   openmpi:
      buildable: False
      paths:
         openmpi@2.0.3%gcc@7.2.1 arch=linux-fedora27-x86_64: /opt/openmpi-2.0.3
   elfutils:
      version: [0.170]
```
[jeg@localhost packages]$

**Comment by jgalarowicz** [comment]
This issue has been resolved via recent changes to the dyninst and elfutils packags.
