### ISSUE TITLE
Dependency issue with paraview~qt and libxt

### ISSUE THREAD

**Issue by BergFlo** [spack/spack#7322]
When ParaView is built without Qt support (which is the default), the dependency on `libxt` is dropped. However, CMake later complains that it cannot find `X11_Xt_LIB`.

My current workaround for the issue is to always include the Xt dependency:

```
-    depends_on('libxt', when='+qt')
+    depends_on('libxt')
```

Compilation works fine after this change. However, could there be a way to drop the Xt dependency (which needs X11) after all?

### Expected Result

Package would compile without Xt library.

### Actual Result

Xt library is still required for compilation.

```
     1229    -- Found X11: /usr/lib64/libX11.so
  >> 1230    CMake Error at VTK/Rendering/OpenGL2/CMakeLists.txt:190 (message):
     1231      X11_Xt_LIB could not be found.  Required for VTK X lib.
```

CMake finds system-wide X11 installation which is lacking Xt.

### Steps to reproduce the issue

```console
$ spack install paraview@5.3.0~qt
```

### Information on your system

I used `linux-centos7-x86_64` with `gcc@7.3.0`.

**Comment by chuckatkins** [comment]
Fixed in #5802 and #11432
