### ISSUE TITLE
Spack install openfoam fails on Mac OS 10.16.2 (Sierra/Darwin)

### ISSUE THREAD

**Issue by ziolai** [spack/spack#7340]
I am trying to install Openfoam using spack on Mac OS 10.12.6 (Sierra/Darwin). To this end I first make sure that all of the auxilary packages such as Boost install well. See #7170. Next, I encounter the difficulty that seemingly no provision has yet been made to install OpenFoam on Mac OS X using spack. The difficulty arises both the gcc and clang compilers. See below. Could you please advice?

```
==> Installing openfoam-com
==> OpenFOAM minimal env /Users/ziolai/spack/opt/spack/darwin-sierra-x86_64/gcc-4.6.4/openfoam-com-1706-ajiledeweiukg7lpiyiciffeakrkxhpf
==> Using cached archive: /Users/ziolai/spack/var/spack/cache/openfoam-com/openfoam-com-1706.tgz
==> Staging archive: /Users/ziolai/spack/var/spack/stage/openfoam-com-1706-ajiledeweiukg7lpiyiciffeakrkxhpf/OpenFOAM-v1706.tgz
==> Created stage in /Users/ziolai/spack/var/spack/stage/openfoam-com-1706-ajiledeweiukg7lpiyiciffeakrkxhpf
==> Added file spack-Allwmake
==> Added file README-spack
==> Ran patch() for openfoam-com
==> Building openfoam-com [Package]
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: InstallError: No wmake rule for darwinIntel64Gcc
InstallError: InstallError: No wmake rule for darwinIntel64Gcc

/Users/ziolai/spack/var/spack/repos/builtin/packages/openfoam-com/package.py:631, in build:
2 its environment first.
3 Only build if the compiler is known to be supported.
4 """

5 self.foam_arch.has_rule(self.stage.source_path)
6 self.foam_arch.create_rules(self.stage.source_path, self)
7
8 args = ['-silent']
See build log for details:
/Users/ziolai/spack/var/spack/stage/openfoam-com-1706-ajiledeweiukg7lpiyiciffeakrkxhpf/OpenFOAM-v1706/spack-build.out

==> Installing openfoam-com
==> OpenFOAM minimal env /Users/ziolai/spack/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/openfoam-com-1706-qtosjuuluglsuyrvkai3z7o62iddnpas
==> Fetching https://sourceforge.net/projects/openfoamplus/files/v1706/OpenFOAM-v1706.tgz
######################################################################## 100.0%
==> Staging archive: /Users/ziolai/spack/var/spack/stage/openfoam-com-1706-qtosjuuluglsuyrvkai3z7o62iddnpas/OpenFOAM-v1706.tgz
==> Created stage in /Users/ziolai/spack/var/spack/stage/openfoam-com-1706-qtosjuuluglsuyrvkai3z7o62iddnpas
==> Added file spack-Allwmake
==> Added file README-spack
==> Ran patch() for openfoam-com
==> Building openfoam-com [Package]
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: InstallError: No wmake rule for darwinIntel64Clang
InstallError: InstallError: No wmake rule for darwinIntel64Clang

/Users/ziolai/spack/var/spack/repos/builtin/packages/openfoam-com/package.py:631, in build:
2 its environment first.
3 Only build if the compiler is known to be supported.
4 """

5 self.foam_arch.has_rule(self.stage.source_path)
6 self.foam_arch.create_rules(self.stage.source_path, self)
7
8 args = ['-silent']
See build log for details:
/Users/ziolai/spack/var/spack/stage/openfoam-com-1706-qtosjuuluglsuyrvkai3z7o62iddnpas/OpenFOAM-v1706/spack-build.out
```

**Comment by davydden** [comment]
indeed, i don't think it was tested on macOS. I am afraid that you would have to dig yourself into `openfoam` make system and see what is missing to make it work on macOS. Maybe there is something in `README` or `INSTALL` on that topic. I am using macOS but I never tries building this package.

**Comment by ziolai** [comment]
Thank you for getting in touch with your advice. My very limited understanding is that spack downloads the OpenFoam source and proceeds to compile it. You seem to suggest to interlace a step in which the makefile (cmake files?) are edited. Is this correct?  How do I instruct spack to merely download the source? The auxiliary packages for OpenFoam installed ok (seemingly). How do I make sure that OpenFoam links well with these auxiliary packages? Thanks.

**Comment by davydden** [comment]
you can go to the build folder `/Users/ziolai/spack/var/spack/stage/openfoam-com-1706-qtosjuuluglsuyrvkai3z7o62iddnpas/OpenFOAM-v1706/spack-build.out` and investigate what's going on. 

The package is here https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openfoam-com/package.py but it's one of the complicated ones.

Another option is to try to build the minimial version yourself outside of Spack and see what you do different to what is done by Spack in the `package.py`.

**Comment by ziolai** [comment]
Here is my spack-build.out
Domenicos-MBP:~ ziolai$ more /Users/ziolai/spack/var/spack/stage/openfoam-com-1706-qtosjuuluglsuyrvkai3z7o62iddnpas/OpenFOAM-v1706/spack-build.out
==> Executing phase: 'configure'
==> FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_COMPILER)=.*$"]
==> FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_ARCH_OPTION)=.*$"]
==> FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_LABEL_SIZE)=.*$"]
==> FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_PRECISION_OPTION)=.*$"]
==> FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_COMPILE_OPTION)=.*$"]
==> FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_MPLIB)=.*$"]
==> FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_COMPILER)\s+.*$"]
==> FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_ARCH_OPTION)\s+.*$"]
==> FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_LABEL_SIZE)\s+.*$"]
==> FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_PRECISION_OPTION)\s+.*$"]
==> FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_COMPILE_OPTION)\s+.*$"]
==> FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_MPLIB)\s+.*$"]
==> Executing phase: 'build'

How does package.py interface with the OpenFoam native build system? Could it replaced with a version that is more verbose?

**Comment by davydden** [comment]
> How does package.py interface with the OpenFoam native build system?

I am sorry, but I don't know `openfoam` build system, so apart from the answer "spack uses openfoam build system to setup the package" I can't really say more. You would really just need to go through the code and look at `setup_environment()`, `patch()` and `configure()` in the `OpenfoamCom` class.

**Comment by ziolai** [comment]
Sincere thanks nevertheless. I will give it a look.

**Comment by adamjstewart** [comment]
@olesenm

**Comment by olesenm** [comment]
OpenFOAM isn't formally supported on Darwin, simply due to lack of demand and our inability to build and test it on those systems. The foam-extend sources however have supported it in the past (http://powerlab.fsb.hr/ped/kturbo/OpenFOAM/WorkshopZagrebJun2007/presentations/slides/slidesGschaiderZagreb2007.pdf)

If you can help us with adding Darwin support to OpenFOAM, please raise an issue on develop.openfoam.com and we can discuss it in more detail there. 
Thanks, 
/mark

**Comment by ziolai** [comment]
Thanks, I will give it a look. Best wishes, Domenico.,

**Comment by adamjstewart** [comment]
Thanks @olesenm! I'm going to close this issue as it isn't really a Spack issue, it's an OpenFOAM issue.

**Comment by olesenm** [comment]
... or a darwin issue ;)
