### ISSUE TITLE
Question about intended behavior for PETSc test

### ISSUE THREAD

**Issue by amklinv** [spack/spack#7348]
@davydden @BarrySmith @jedbrown @balay 

The PETSc package's install function includes a test commented "solve Poisson equation in 2D to make sure nothing is broken."  This test calls 
```
mpirun ex50 -da_grid_x 4 -da_grid_y 4
```
On my system, this crashes with an error message
```
Partition in y direction is too fine! 4 8
```
meaning the code is being run with too many MPI processes for such a small grid.  What is the intended behavior of this test?  How many processes should it be using?

**Comment by balay** [comment]
This runs fine for me..

balay@asterix /home/balay/petsc/src/ksp/ksp/examples/tutorials (next=)
$ mpiexec ./ex50 -da_grid_x 4 -da_grid_y 4
balay@asterix /home/balay/petsc/src/ksp/ksp/examples/tutorials (next=)
$ echo $?
0
balay@asterix /home/balay/petsc/src/ksp/ksp/examples/tutorials (next=)

mpiexec should default to '1' proc if '-n' option is not specified.

Perhaps we should list this explicitly?

mpiexec -n 1 ./ex50 -da_grid_x 4 -da_grid_y 4

**Comment by alalazo** [comment]
Seems to be answered by @balay but feel free to reopen if I'm wrong.
