### ISSUE TITLE
Python backports namespace

### ISSUE THREAD

**Issue by healther** [spack/spack#7370]
I was thinking about adding this to the discussion in #4155 but it quickly expanded in scope so I decided to open a new issue.

We ran into problems with requiring an older `py-setuptools` when installing e.g. `py-flake8`. The restriction was introduced by me in #3757. However I'm not really sure whether that approach ever actually solved the problem...
Removing the restriction in `py-backports-shutil-get-terminal-size/package.py` (i.e. building with `py-setuptools@35.0.2`) still gives a useable `ipython` (`spack load -r py-ipython && ipython` does not fail to start). 

There are a number of issues that I suspect relate to this #7001, #5908, #4154, and I suspect I didn't find all of them.
My current understanding, inferred from reading multiple discussion around problems with different failure points, is that the problem comes up if you have multiple namespace packages installed and the first one you are looking at is not the one you are looking for. I think this is the reason why a ipython-only install works (although I have as of now been unable to break it).

My current proposal would be to revert #3757 as it does not seem to do us much good. The larger problem though is still unsolved. One point where this breakage can be observed would be `py-flake8` a `spack load -r py-flake8 && flake8` fails with `ImportError: No module named backports.configparser` and even though @adamjstewart put it in the documentation it's still an unsatifying state. 
My problem is that I don't really know where to start digging as I feel quite out of my depth here. As we are only using `view`s anyway, this does not really seem to break anything in production, but that seems to be due to some `backports`-package doing the right thing and the others being able to piggy back, with me having no idea which ones we can't remove from our views.

Pinging for comments/ideas: @adamjstewart @scheibelp @luigi-calori @hartzell @lee218llnl @grondo all of you ran into similar problems

**Comment by hartzell** [comment]
> that seems to be due to some backports-package doing the right thing and the others being able to piggy back

@healther -- I'm reading up on the problems you've described with namespace packages.  In the above bit you mention well- and badly-behaving packages.  Do you referring to the behavior of the Spack packages or the underlying Python bits?

**Comment by healther** [comment]
I don't exactly remember, but that was before I started to understand the way python imports work, so what I wrote above may not be accurate (when compared to python's behaviour).

As of now I'm uncertain whether spack's install scheme of `backports` packages is valid at all (i.e. I'm not sure if there is a set of files that we could add in order to guarantee `from backports import something` or `import backports.something` to work. My problem is that I don't understand what [site.py](https://docs.python.org/2/library/site.html) is telling me.

What happens in practice is the following (or at least as far as I understand it):
- when you do `import backports.something` 
- then python searches its `sys.path` 
-- which is populated by the current folder, a number of default paths and everything on PYTHONPATH  (I think it was this order)
- for a file or folder named `backports`, it starts in the first entry and then goes to the second etc.
-- the first thing that is found will be treated as the only `backports`
- then (as it doesn't find a file `backports.py`) it goes into that folder and searches for a file named `something.py` (or a folder `something`)
- if it doesn't find it you get an ImportError

Now unless we can configure `python` not to error out when it found a `backports` folder but not a `something` folder enclosed, but rather continues searching the other entries in `sys.path` then spack's install scheme is fundamentally incompatible with python's treatment of namespace packages (which would have to be in the same folder).
Whether this is possible or not, I don't know. I suspect the answer is to be found in the `site.py` documentation from above which I have yet to understand.

`views` (which we need anyways for speed reasons) solve this problem as a side effect, so there is no particularly pressure for me to go down this rabbit hole right now, even so I'd like to know the answer :)

Regarding the `setup.py` restriction above, I think this had to do with the fact that spack (once upon a time) installed python `.egg`s and it may have been that they had to be treated differently requiring a certain version of `setuptools`. But I wasn't able to reproduce the issue that initially led me to add the restriction (and of course past-me didn't leave any documentation worth the name)

**Comment by scheibelp** [comment]
> As of now I'm uncertain whether spack's install scheme of backports packages is valid at all

Spack doesn't have a scheme for backports packages specifically (or namespace packages in general). This is managed by the python packages themselves (e.g. how they write `setup.py`).

I argued in https://github.com/spack/spack/pull/4155#issuecomment-345139362 that packages would need to define an `__init__.py` in their namespace folder to support module loading Spack python packages maintained in separate prefixes (i.e. the pkgutils approach). However,

> Now unless we can configure python not to error out when it found a backports folder but not a something folder enclosed, but rather continues searching the other entries in sys.path

suggests this will not work. I don't think managing `.pth` files will work because python only searches a fixed set of locations for them.

Of the three approaches mentioned in https://github.com/spack/spack/pull/4155#issuecomment-345139362, that leaves implicit namespaces (which I think are only available for python >= 3.3). According to https://www.python.org/dev/peps/pep-0420/ this may be possible:

> Namespace packages are designed to support being split across multiple directories (and hence found via multiple sys.path entries).

that statement is general so I'd be interested to know if you are 100% certain that the same backports directory cannot appear multiple times.

**Comment by hartzell** [comment]
Folks interested in this issue might want to follow (and/or push on) this issue in the upstream repository: https://bitbucket.org/ambv/configparser/pull-requests/2/use-the-pkgutil-style-namespace-techniques/diff

**Comment by hartzell** [comment]
When I commented yesterday, I hadn't cottoned to the fact that the package had a new maintainer.  I thought he'd just forked the project to encourage the old maintainer to move.

So, you're right, it's been merged.  Now, at some point, it'll actually be released....

I don't know if anything was ever done in Spack to work around the oddness, but if so it can be bounded by versions or backed out.

At the very least, we can close a few issues... ;)

**Comment by hartzell** [comment]
Well, perhaps now its No Longer A Problem™️

**Comment by adamjstewart** [comment]
Is this issue still present or can this be closed?

**Comment by adamjstewart** [comment]
No response so I'm guessing this is no longer an issue.
