### ISSUE TITLE
Download issue for argtable

### ISSUE THREAD

**Issue by f-sim** [spack/spack#7379]
Spack fails to install argtable.

### Expected Result
argtable is installed

### Actual Result
Instalation fails

### Steps to reproduce the issue

```console
$ spack install argtable
...
```

The output is in [spack.log](https://github.com/spack/spack/files/1776085/spack.log). It seems that the sourceforge link is somehow broken.

### Information on your system
I am using spack on macOS high Sierra

**Comment by healther** [comment]
Sourceforge currently has service outages, see e.g. https://twitter.com/sfnet_ops

For now you could work around this by manually downloading the `argtable` sources and put them in `$SPACK_ROOT/var/spack/cache/argtable-2-13/argtable2-13.tar.gz`

**Comment by alalazo** [comment]
[Sourceforge](https://twitter.com/sfnet_ops/status/970143157307559936) seems to be back online. Feel free to reopen if the issue persists.
