### ISSUE TITLE
Aarch64: Since config.guess and config.sub. included in xproto are old, configure fails without recognizing the environment

### ISSUE THREAD

**Issue by kometchtech** [spack/spack#7400]
Summary

### Expected Result
Successful build in Aarch64 environment

### Actual Result

I can not recognize the environment to build because the config.guess and config.sub entered in the tarball are out of date.

### Steps to reproduce the issue

```console
$ spack -k install xproto
==> Warning: You asked for --insecure. Will NOT check SSL certificates.
==> pkgconf is already installed in /home/yhorigome/opt/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/pkgconf-1.4.0-3gc4v5252r5tepvdi5ie22bxjls72q6x
==> util-macros is already installed in /home/yhorigome/opt/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/util-macros-1.19.1-4a2swkgq7c5skv5qauiy3i7yzdqhtvmd
==> Installing xproto
==> Using cached archive: /home/yhorigome/opt/spack/var/spack/cache/xproto/xproto-7.0.31.tar.gz
==> Staging archive: /home/yhorigome/opt/spack/var/spack/stage/xproto-7.0.31-c5dmz6buhfwk2myr4xcmq6u2scvzj6ck/xproto-7.0.31.tar.gz
==> Created stage in /home/yhorigome/opt/spack/var/spack/stage/xproto-7.0.31-c5dmz6buhfwk2myr4xcmq6u2scvzj6ck
==> No patches needed for xproto
==> Building xproto [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/home/yhorigome/opt/spack/var/spack/stage/xproto-7.0.31-c5dmz6buhfwk2myr4xcmq6u2scvzj6ck/xproto-7.0.31/configure' '--prefix=/home/yhorigome/opt/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/xproto-7.0.31-c5dmz6buhfwk2myr4xcmq6u2scvzj6ck'

1 error found in build log:
     74    /usr/convex/getsysinfo =
     75
     76    UNAME_MACHINE = aarch64
     77    UNAME_RELEASE = 4.5.0-29.el7.aarch64
     78    UNAME_SYSTEM  = Linux
     79    UNAME_VERSION = #1 SMP Mon Jul 24 15:34:27 CDT 2017
  >> 80    configure: error: cannot guess build type; you must specify one

See build log for details:
  /home/yhorigome/opt/spack/var/spack/stage/xproto-7.0.31-c5dmz6buhfwk2myr4xcmq6u2scvzj6ck/xproto-7.0.31/spack-build.out
...
```

### Information on your system
 1. which platform you are using
```console
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (AltArch)
$ uname -rm
4.5.0-29.el7.aarch64 aarch64
```

 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)
We used "var/spack/repos/builtin/packages/xproto/package.py" provided by spack using the following commit spack.
commit 96f95764264e32958342a0ef86615578ecddef8d

-----
Perhaps, I think that this problem is related. But, I do not know what kind of modification should be done to correspond to Aarch64 for "lib/spack/spack/build_systems/autotools.py". 

https://github.com/spack/spack/blob/165936cd5f59645633346db6e7c3b17b35d520c1/lib/spack/spack/build_systems/autotools.py#L105-L108

https://github.com/spack/spack/issues/5128

**Comment by wildone** [comment]
This would get it working:

`./configure --build=aarch64-unknown-linux-gnu`

**Comment by haampie** [comment]
This should be fixed for a while thanks to the `gnuconfig` dependency + patching added on aarch64 / ppc / risc-v.  Feel free to reopen if still a problem.
