### ISSUE TITLE
Building lmod with system installed  lua, lua-posix and lua-filesystem fails on RHEL7 fails 

### ISSUE THREAD

**Issue by gartung** [spack/spack#7430]
Summary

Building lmod with system installed  lua, lua-posix and lua-filesystem fails on RHEL7 fails looking for lua posix. 

### Expected Result

spack install lmod succeeds 

### Actual Result

spack install lmod
==> lua@5.3.4 : externally installed in /usr
==> lua@5.3.4 : generating module file
==> lua@5.3.4 : registering into DB
==> lua-luafilesystem@1_6_3 : externally installed in /usr
==> lua-luafilesystem@1_6_3 : generating module file
==> lua-luafilesystem@1_6_3 : registering into DB
==> lua-luaposix@33.4.0 : externally installed in /usr
==> lua-luaposix@33.4.0 : generating module file
==> lua-luaposix@33.4.0 : registering into DB
==> tcl@8.6.6 : externally installed in /usr
==> tcl@8.6.6 : generating module file
==> tcl@8.6.6 : registering into DB
==> Installing lmod
==> Using cached archive: /home/gartung/spack/var/spack/cache/lmod/lmod-7.7.13.tar.gz
==> Staging archive: /home/gartung/spack/var/spack/stage/lmod-7.7.13-ppjssi35cwscb7scrlziddr3rgaifw67/7.7.13.tar.gz
==> Created stage in /home/gartung/spack/var/spack/stage/lmod-7.7.13-ppjssi35cwscb7scrlziddr3rgaifw67
==> Ran patch() for lmod
==> Building lmod [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/home/gartung/spack/var/spack/stage/lmod-7.7.13-ppjssi35cwscb7scrlziddr3rgaifw67/Lmod-7.7.13/configure' '--prefix=/home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-6.4.0/lmod-7.7.13-ppjssi35cwscb7scrlziddr3rgaifw67'

1 error found in build log:
     51    checking for tr... /usr/bin/tr
     52    checking for luac... /usr/bin/luac
     53    checking for lua... /usr/bin/lua
     54    checking for valid Lua version... 5.1
     55    checking for lua modules: posix
     56    
  >> 57    Error: The follow lua module(s) are missing:  posix
     58    
     59    You can not run Lmod without:  posix

See build log for details:
  /home/gartung/spack/var/spack/stage/lmod-7.7.13-ppjssi35cwscb7scrlziddr3rgaifw67/Lmod-7.7.13/spack-build.out

From 
Lmod-7.7.13/config.log 

SYS_LUA_PATH='/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/home/gartung/spack/var/spack/stage/lmod-7.7.13-ppjssi35cwscb7scrlziddr3rgaifw67/Lmod-7.7.13/src/?.lua'

On RHEL7 lua is installed in /usr/lib64/lua/5.1/

### Steps to reproduce the issue

```console
$ spack install lmod
```

### Information on your system

This includes:

 1. which platform you are using
RHEL7 clone Scientific Linux 7
 
2. packages.yaml contains

  lua:
    paths:
     lua: /usr
    buildable: False
  lua-luafilesystem:
    paths:
     lua-luafilesystem: /usr
    buildable: False
  lua-luaposix:
    paths:
     lua-luaposix: /usr
    buildable: False
  tk:
    paths:
      tk: /usr
    buildable: False
  tcl:
    paths:
      tcl: /usr
    buildable: False

**Comment by gartung** [comment]
Additional detail. The system installed lua is incorrecty reporting the lua paths:

lua -e "print(package.path)"
/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/home/gartung/spack/var/spack/stage/lmod-7.7.13-ppjssi35cwscb7scrlziddr3rgaifw67/Lmod-7.7.13/src/?.lua

**Comment by gartung** [comment]
Addressed in #7434

**Comment by gartung** [comment]
In order for my fix to work I had to define the exact version of lua install on my RHEL7 system
  lua:
    paths:
     lua@5.1: /usr
    buildable: False

**Comment by scheibelp** [comment]
Closed by #7434 - thanks @gartung!
