### ISSUE TITLE
Frequent failures on python 2.7 unit tests

### ISSUE THREAD

**Issue by alalazo** [spack/spack#7488]
Since a few days we started experiencing errors on most of the unit tests job running on python 2.7. The jobs seem to hang when trying to concretize `mpileaks`:
```console
${coverage_run} bin/spack -p --lines 20 spec mpileaks
```

### Expected Result

Green light on Travis

### Actual Result

The job errors out after waiting 10 minutes without receiving any output. 

### Notes

- The error result does not happen consistently, but is indeed very frequent -  it usually takes several restarts to have a job that passes the concretization of `mpileaks`
- The error consistently happen only on python 2.7
- An example of a failing job is [here](https://travis-ci.org/spack/spack/jobs/353413242)

**Comment by healther** [comment]
what about switching the majority of the tests to python3? I think I offered it as a way to reduce the load of the MacOSX machines on Travis, back when they had load issues. (py3 tests are consistently faster than py2)

**Comment by adamjstewart** [comment]
@healther That won't help with this particular issue. There's only a single test that's failing (Python 2.7 unit tests) and we can't just not test Python 2.7. All of the other Python 2 tests pass just fine.

But we could certainly switch the flake8 and build tests to Python 3, I have no reason to be opposed to that. It just won't help here.

**Comment by alalazo** [comment]
Just wanted to report that this problem disappeared since the last ~2 days. I'll monitor the situation and if things stay the same for a while I'll close this ticket.

**Comment by adamjstewart** [comment]
I'm still seeing it occasionally but a single restart fixes the problem. If I notice it again I'll post a link here.

**Comment by adamjstewart** [comment]
Example: #7535: https://travis-ci.org/spack/spack/jobs/356039195

**Comment by adamjstewart** [comment]
@alalazo you don't need these for debugging do you? If not, I'll restart the tests on these PRs and get them merged.

**Comment by adamjstewart** [comment]
@alalazo Is this still an issue? I haven't seen any 2.7 bugs in a while.

**Comment by alalazo** [comment]
@adamjstewart Nope. Closing.
