### ISSUE TITLE
Remove edit phase from MakefilePackage

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#7513]
We should remove the `edit` phase from the `MakefilePackage` base class. It offers duplicate functionality as `patch` with no additional features. This would require replacing all `edit` function calls with `patch` in every `MakefilePackage`.

@alalazo Is there any reason we should keep `edit`?

**Comment by alalazo** [comment]
Only semantic in my opinion. `edit` is meant for Makefiles, `patch` for sources.

**Comment by alalazo** [comment]
Another thing. Without edit we lose the phase, for `MakefilePackage`, that enables the same debugging workflow as for `AutotoolsPackage` or `CMakePackage`:
```console
$ spack configure foo # <- this one won't work without edit
$ spack cd foo
$ spack env foo -- bash
```
Not sure if `spack patch` will give the same results, as it comes before in the whole installation pipeline (pre-install hooks, for instance, are now run after patch but before edit). What would be the benefit of removing the edit phase?

**Comment by adamjstewart** [comment]
I guess the only benefit of removing `edit` would be that it is currently not clear whether things should go in `patch` or `edit` since they provide similar behavior. But you make good points here. I'll leave this open for now, but I would love to hear other people comment.

**Comment by alalazo** [comment]
@adamjstewart
