### ISSUE TITLE
[Feature request] Generalize `spack dependents`

### ISSUE THREAD

**Issue by goxberry** [spack/spack#753]
Right now, `spack dependents` returns the installed packages that depend on another (presumably, the supplied spec). However, when adding, for instance, a new version of a package (see #750), it may be necessary to patch package scripts for packages that are not installed (e.g., when adding metis 4.0.3, I had to modify the `trilinos` package, which I do not have installed). In order to figure out which packages depend on `metis` -- even ones I don't have installed -- I resorted to grepping, which yields some false positives (e.g., `metis` in a comment). A command-line query through spack would be better to find all packages depending on `metis`, even those that aren't installed. For package creators and maintainers, it would also be useful to have an option to return all packages that have a given package even as an optional dependency (e.g., `metis` is often an optional dependency, but not always).

Recursive dependency queries could also be desirable, for instance, if I want to know what packages should (or in the case of recursive uninstall, will) be uninstalled if I uninstall a given package. Reverse (recursive) dependency resolution is also occasionally desirable; in the Homebrew package manager, this feature is useful to understand what packages should be recompiled if I, for instance, switch MPI implementations. Since spack's design accounts for changing MPI implementations, compilers, etc., I am not sure that reverse dependency resolution will be as useful.

**Comment by citibeth** [comment]
I suspect this feature would be not hard to implement.  Can you provide a written spec of how exactly it would work from the user's point of view?

**Comment by adamjstewart** [comment]
This sounds a lot like the --dependents/--dependencies discussion we were having with recursive uninstall. It would be nice if they behaved in the same way with the same option names.

**Comment by citibeth** [comment]
I agree, flags that control recursive walking of the DAG should be called --dependents or --dependencies.  I'm hoping the OP can provide a clear spec for the rest of how this feature would work.

**Comment by goxberry** [comment]
@citibeth The inspiration for the feature request comes from the [`brew uses` command in Homebrew](https://github.com/Homebrew/brew/blob/0382134cf87321166fb8f03223e21b1d242ad7cb/Library/Homebrew/cmd/uses.rb).

Currently, `spack dependents <spec>` returns only installed spack packages that depend on `<spec>`. I propose modifying that command to `spack dependents --installed <spec>`, so that `spack dependents <spec>` returns any spack packages that depend on `<spec>`. 

For instance, `spack dependents metis@5:` should return `superlu-dist parmetis` (in some order).

I could also see utility in having a `--optional` flag for a search of packages that depend on the spec both inside and outside of variants; then `spack dependents metis@5:` should return `superlu-dist parmetis dealii eigen mumps petsc trilinos` (in some order).

I care most these first two options (`--installed` and `--optional`) because, if implemented, they are command-line utilities that can be used by package creators and maintainers to check for potential dependency issues before they occur (as discussed in the original post).

Further flags of interest might be `--recursive` (to search the dependency DAG recursively), `--reverse` (returning the packages `<spec>` depends on; this option might better be implemented as a separate command). I know I've used similar commands in Homebrew before, but I don't know if they have use cases that are as strong as `--installed` and `--optional`.

**Comment by citibeth** [comment]
Currently, spack dependents <spec> returns only installed spack packages that depend on <spec>. I propose modifying that command to spack dependents --installed <spec>, so that spack dependents <spec> returns any spack packages that depend on <spec>. 

Not sure if this is practical.  There are exponentially many packages that depend on <spec>.

Or to be more clear... consider the set of all possible legal Spack specs.  There are exponentially many of them.  (Suppose that mpi <-- netcdf <-- myprogram.  And suppose we have nominaly 5 versions of each.  Now we have 5 specs that start with mpi, 25 starting with netcdf and 125 starting with myprogram.  The numbers only get bigger from there...)

Most of these specs are not installed, and will never be installed.  We cannot in practice enumerate the set of specs that depend on any particular spec (whether installed or not).  We CAN talk about the set of INSTALLED specs that depend on your spec (since the set of installed specs is never exponentially large).

MAYBE we can talk about the set of packages that, with the right variants, produce legal specs that depend on your spec.  But maybe not... it sounds like a pretty challenging problem.  Especially because you have to execute the package with a particular spec to find out what it depends on, or even if it's legal.

Much more practical is to talk about the set of packages that depend on a particular package --- i.e. the set of packages that have "depends_on('A')" in them.  But since dependencies are often conditional, this would not be at all foolproof.  But it might give useful information.  This is a glorified grep.

All this stuff is harder in Spack vs. Homebrew because Homebrew just installs one of every package.

> I care most these first two options (--installed and --optional) because, if implemented, they are command-line utilities that can be used by package creators and maintainers to check for potential dependency issues before they occur (as discussed in the original post).

For that, I think we just need the glorified grep.  Or just use grep itself.

> Further flags of interest might be --recursive (to search the dependency DAG recursively), --reverse (returning the packages <spec> depends on; this option might better be implemented as a separate command)

We've discussed these flags in other contexts.  The decision is that '--dependencies' searches through dependencies recursively, whereas '--dependents' goes the other direction.

**Comment by goxberry** [comment]
>>Currently, spack dependents returns only installed spack packages that depend on . I propose modifying that command to spack dependents --installed , so that spack dependents returns any spack packages that depend on .

>Not sure if this is practical. There are exponentially many packages that depend on .

>Or to be more clear... consider the set of all possible legal Spack specs. There are exponentially many of them. (Suppose that mpi <-- netcdf <-- myprogram. And suppose we have nominaly 5 versions of each. Now we have 5 specs that start with mpi, 25 starting with netcdf and 125 starting with myprogram. The numbers only get bigger from there...)

>Most of these specs are not installed, and will never be installed. We cannot in practice enumerate the set of specs that depend on any particular spec (whether installed or not). We CAN talk about the set of INSTALLED specs that depend on your spec (since the set of installed specs is never exponentially large).

This argument doesn't respond to my original use case, which was for package maintenance. If I modify a package to add a new version, as in the `metis` example I gave in the OP, I am not necessarily going to have everything that depends on `metis` installed, and I shouldn't have to.

Suppose some syntax change affects the `mpi` spec so that it has to be modified in every dependent package. (This actually happened in Homebrew, its single version restriction notwithstanding.) Then the dependency tool I am proposing would have to return all of these dependent packages, even if there are a large number of them.

> MAYBE we can talk about the set of packages that, with the right variants, produce legal specs that depend on your spec. But maybe not... it sounds like a pretty challenging problem. Especially because you have to execute the package with a particular spec to find out what it depends on, or even if it's legal.

Sure, I think that might work, if it can be implemented.

> Much more practical is to talk about the set of packages that depend on a particular package --- i.e. the set of packages that have "depends_on('A')" in them. But since dependencies are often conditional, this would not be at all foolproof. But it might give useful information. This is a glorified grep.

I have already pointed out in the OP that merely grepping -- which is what I did -- yields false positives. From the OP:

> In order to figure out which packages depend on metis -- even ones I don't have installed -- I resorted to grepping, which yields some false positives (e.g., metis in a comment).

Manually weeding out false positives in a list of 8 files is fine. In a list of 80 files, it's tedious, and because of the exponential phenomenon observed, the list of packages depending on a given spec could even be larger than that.

> All this stuff is harder in Spack vs. Homebrew because Homebrew just installs one of every package.

Package maintenance is harder in Spack vs Homebrew for similar reasons. Using your same argument, now I have to think about how changes to one package affect any number of packages that have many variant specs, and this number could grow exponentially. This more complicated reasoning led to errors in my metis 4.0.3 PR, and I could see this happening to other people, hence proposing a tool that could help me and other people reason about how their changes might affect other Spack packages, even if -- especially if -- they aren't ones installed on their system (e.g., my metis 4.0.3 PR messed up trilinos, which @davydden graciously pointed out; I did not have trilinos installed).

> For that, I think we just need the glorified grep. Or just use grep itself.

If I have a change that affects, say `cmake@2.6:3.2`, I'm not sure that grep is going to be all that helpful in spec resolution. Even in a case where grep will return all relevant results (e.g., the spec `metis`), as I pointed out, there are false positives (e.g., comments). In a manner of speaking, this dependency resolution could be a glorified grep, but then it seems to me that spec parsing has to be built in anyway, and at that point, why not just use spack's spec parsing?

**Comment by tgamblin** [comment]
This was fixed by #4478.
