### ISSUE TITLE
Cannot specify hash with spack view

### ISSUE THREAD

**Issue by kruger** [spack/spack#7548]
### Summary

I have multiple versions of hdf5 install, and I would like to create a view with just one of them.  Specifying the hash is the recommended way according to the documentation, but it does not seem to work.

### Expected Result

 I expect one of these options create a view:
Short hash:
```
spack view --verbose  symlink myview /fuqfcbe
spack view --verbose  symlink myview ^/fuqfcbe
```

Full hash:
```
spack view --verbose symlink myview /fuqfcbeakt2ecpn23xe3vcpimohc2gxe
spack view --verbose symlink myview ^/fuqfcbeakt2ecpn23xe3vcpimohc2gxe
```

### Actual Result

All permutations give the same result:
```
> spack view --verbose symlink myview ^/fuqfcbeakt2ecpn23xe3vcpimohc2gxe
==> Error: ^/fuqfcbeakt2ecpn23xe3vcpimohc2gxe matches multiple packages.
  Matching packages:
    hyfdeo5 binutils@2.29.1%clang@9.0.0-apple arch=darwin-sierra-x86_64
    uxdgzdu bison@3.0.4%clang@9.0.0-apple arch=darwin-sierra-x86_64
    5vyj7l5 bison@3.0.4%clang@9.0.0-apple arch=darwin-sierra-x86_64
    ...
```

### Steps to reproduce the issue

Any multiple versions of a package should work.  For me, I have 3 versions of hdf5 with the one I want to install being chosen because it has mpich.  `hdf5^mpich` did not work for me either.

```
> spack find --long hdf5
==> 4 installed packages.
-- darwin-sierra-x86_64 / clang@9.0.0-apple ---------------------
cdpvfjh hdf5@1.10.0-patch1  fuqfcbe hdf5@1.10.1  nfpaht4 hdf5@1.10.1  52sviwf hdf5@1.10.1
```
### System info

 1.  Darwin (MacOS 10.12.6)
 2. My version of spack is latest git develop branch.

**Comment by kruger** [comment]
I should mention that I've also tried this permutation:

```
> spack view --verbose  symlink myview hdf5^/fuqfcbe
==> Error: hdf5^/fuqfcbe matches multiple packages.
  Matching packages:
    fuqfcbe hdf5@1.10.1%clang@9.0.0-apple arch=darwin-sierra-x86_64
    nfpaht4 hdf5@1.10.1%clang@9.0.0-apple arch=darwin-sierra-x86_64
  Use a more specific spec.
```

**Comment by healther** [comment]
This looks like something we ran into sometime ago. I'll check this out later today

**Comment by healther** [comment]
Okay I fail to be able to reproduce your issue as you stated it, on the current `develop` I get:
```
$ spack view symlink myview /t74siw3
==> Error: 'Spec' object has no attribute 'name'
```

Please check whether #7573 fixes your problem

**Comment by healther** [comment]
@kruger ?

**Comment by healther** [comment]
@kruger if this does not solve your problem feel free to reopen and post a new bug report
