### ISSUE TITLE
Can a single instance of spack install  in multiple locations on same machine?

### ISSUE THREAD

**Issue by garvct** [spack/spack#7567]
Is is possible to have a single spack installation install software in multiple locations (e.g
/location1 and /location2) on the same machine without replication of the dependent software?

How can I set this up?

Thanks,

**Comment by pramodk** [comment]
Not sure if I understood correctly but look at config.yaml where you can set install prefix path. If you want to install packages at some other location, just change that path. Now spack will install all packages and dependencies in new location.

**Comment by garvct** [comment]
Yes, modifying config.yaml will allow me to install in a new location but I have to rebuild all the dependencies in the new location, even though they are build already in the other location.
e.g Want to install software in /location1 & /location2. In location1 I have already built the dependencies
(e.g mpi library). When I change my install location (config.yaml) to /location2, spack tries to rebuild my dependencies even though they already exist in /location1. 
How do I make spack aware of the software it built in /location1 so it does not have to rebuild it in /location2? One possible way would be to modify the package.yaml and define already built software as
external? Is there any other way? How can I make 'spack find', locate all the software in /location1 and /location2?
Does package.yaml have any ability to specify the install location (and module location) for each individual package?

**Comment by garvct** [comment]
Currently, there appear to be 2 ways to do this 1) stack.py and 2) via spack build cache.
Will stack.py be merged into the develop branch or is this dropped because spack build cache can be used to support the same feature?

**Comment by healther** [comment]
No these are different features. While the effect is similar (reduced rebuilds) the method and the resulting state are different. I.e. `stack` would be able to only have one install per hash, with `buildcache` you would end up having one install per hash per instance. 

The point why `stack` isn't merged is that right now there are known issues with it, that essentially render it useless aside from reducing build times. We are currently using it as we only have to build the delta when updating our setup. However to actually get usable modules the live instance needs to build the packages, as only the packages that are natively build in the stacked instance are loadable by it. For some reason (that is yet to be investigated) setting up the build environment works correctly, while setting up the run environment fails
