### ISSUE TITLE
Unable to build python3.6.x on MacOSx 

### ISSUE THREAD

**Issue by healther** [spack/spack#7589]
Summary

### Expected Result

`spack install python@3.6.4` results in an usable python3 installation.

### Actual Result

```
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4'

1 error found in build log:
     895    		rm -f ./pybuilddir.txt ; \
     896    		exit 1 ; \
     897    	fi
     898    running build
     899    running build_ext
     900    error: [Errno 2] No such file or directory: '/Users/healther/Documents/git.nosync/spack/opt/spack/darwin-highsierra-x86_64/clang-
            9.0.0-apple/python-3.6.4-j34o5jqkcypp3s7c2u5jqajutiopnjk3/include/python3.6m/pyconfig.h'
  >> 901    make: *** [sharedmods] Error 1
```

### Information on your system

current develop (-5 or so commits plus #4585 and #7204)
 ```
$ spack arch
darwin-highsierra-x86_64
```
nothing special installed (or at least visible to spack) so only the system `clang@9-apple`

I couldn't find any information only to it (@adamjstewart seems to have hit a similar problem when trying to build `boost+python@3:` but that's about it. If I read this correctly `spack` tries to access the to-be-populated prefix before actually installing stuff...

When I do
```
spack cd python@3.6.4 && spack build-env python@3.6.4 -- bash 
make
```
I see the same error, without the `build-env`, make runs through without a problem. I'm out of my depth here...

[spack-build.env.txt](https://github.com/spack/spack/files/1844527/spack-build.env.txt)
[spack-build.out.txt](https://github.com/spack/spack/files/1844528/spack-build.out.txt)

**Comment by healther** [comment]
The call that compiles the python executable looks much simpler without the spack wrappers...
```
gcc   -Wl,-stack_size,1000000  -framework CoreFoundation -o python.exe Programs/python.o libpython3.6m.a -ldl  -framework CoreFoundation  
```

Note that `gcc` is symlinked to the `clang` executable

**Comment by healther** [comment]
Okay turns out I was lying when I said, that I don't have anything special installed. I do have a couple of different "system"-level pythons. 
```
$ which python
python is /Users/healther/.pyenv/shims/python
python is /usr/local/bin/python
python is /usr/bin/python
```
where the first one comes curtesy of [pyenv](https://github.com/pyenv/pyenv), the second one is provided by home-brew and the last one is the real system python. 

In the first post I used the one from pyenv, which (in the spack folder, as peen allows choosing the link folder wise) is a 
```
$ python
Python 3.5.2 (default, Nov 24 2016, 18:07:23) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
and leads to the error mentioned in the first post.

Explicitly using a different "system"-python leads to a different error
```
$ /usr/local/bin/python
Python 2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
$ /usr/local/bin/python /Users/healther/Documents/git.nosync/spack/bin/spack install python@3.6.4
...
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4' 'install'

2 errors found in build log:
     1313    renaming build/scripts-3.6/pydoc3 to build/scripts-3.6/pydoc3.6
     1314    renaming build/scripts-3.6/idle3 to build/scripts-3.6/idle3.6
     1315    renaming build/scripts-3.6/2to3 to build/scripts-3.6/2to3-3.6
     1316    renaming build/scripts-3.6/pyvenv to build/scripts-3.6/pyvenv-3.6
     1317    ==> Executing phase: 'install'
     1318    ==> 'make' '-j4' 'install'
  >> 1319    Error: The source directory (/Users/healther/Documents/git.nosync/spack/var/spack/stage/python-3.6.4-j34o5jqkcypp3s7c2u5jqajutio
             pnjk3/Python-3.6.4) is not clean
     1320    Building Python out of the source tree (in /private/var/folders/1q/jxx1cgcx3l13d153s6_c1zc00000gn/T/pytest-of-healther/pytest-16
             /test_keep_exceptions0/tmp/spack-stage/spack-stage-a3RBp_/Python-3.6.4) requires a clean source tree (/Users/healther/Documents/
             git.nosync/spack/var/spack/stage/python-3.6.4-j34o5jqkcypp3s7c2u5jqajutiopnjk3/Python-3.6.4)
     1321    Try to run: make -C "/Users/healther/Documents/git.nosync/spack/var/spack/stage/python-3.6.4-j34o5jqkcypp3s7c2u5jqajutiopnjk3/Py
             thon-3.6.4" clean
  >> 1322    make: *** [check-clean-src] Error 1
```

I have zero idea why the error type changes based on the python interpreter used to invoke spack. I'll do a clean checkout and try this again...

**Comment by adamjstewart** [comment]
I was able to install Python 3.6.4 on macOS High Sierra 10.13.3 with Clang 9.0.0. Like you, I have several system Python installations. The one I used to run Spack was Python 3.6.4 installed by Anaconda.

**Comment by healther** [comment]
Mh that's strange, I'm on the same macOS as you are, but I'm using a `python@3.5.2` for the install. I'll try to get a `python@3.6.x` from pyenv and see if that solves the problem..
```
$ python
Python 3.5.2 (default, Nov 24 2016, 18:07:23) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

**Comment by healther** [comment]
Okay turns out with `python@3.6.5` from pyenv my install also completes without hiccup. @adamjstewart could you (or someone else with access to MacOSx) try with another `python@3`, but with a different minor version than the one you are trying to install? I'm afraid that the spack install depends on out-of-spack files...

**Comment by alalazo** [comment]
@healther Reading through the discussion it seems this was unreproducible. Can this be closed or is it still an issue for you?

**Comment by healther** [comment]
The last time I rebuild things, they worked out of the box
