### ISSUE TITLE
OSX build is failing on Travis

### ISSUE THREAD

**Issue by alalazo** [spack/spack#7593]
The latest build on OSX fails on Travis, because of a conflict when concretizing `mpileaks`:
```console
1. "%clang" conflicts with "elfutils"
```

### Expected Result

`mpileaks` concretize correctly on OSX

### Actual Result

See [here](https://travis-ci.org/spack/spack/jobs/357873755) for an example of a failed build.

**Comment by adamjstewart** [comment]
#7096 @goxberry

**Comment by alalazo** [comment]
@scheibelp I think 5e758b9 just shifted [the error](https://travis-ci.org/spack/spack/jobs/360699640):
```console
"%gcc@7.2.0:" conflicts with "elfutils@0.163"
```
