### ISSUE TITLE
Cannot install libpciaccess from binary cache

### ISSUE THREAD

**Issue by garvct** [spack/spack#7603]
Build libpciaccess binary cache
garvct@service2/hpc-common/software/spack/0.11.2/spack/var/spack/mirror> spack buildcache create -f -k 81F2F332 libpciaccess@0.13.5%gcc@5.5.0
==> adding matching spec libpciaccess@0.13.5%gcc@5.5.0 arch=linux-sles11-x86_64 
==> recursing dependencies
==> adding dependency libpciaccess@0.13.5%gcc@5.5.0 arch=linux-sles11-x86_64 
==> creating binary cache file for package libpciaccess@0.13.5%gcc@5.5.0 arch=linux-sles11-x86_64  

> spack uninstall libpciaccess%gcc@5.5.0
==> The following packages will be uninstalled:

-- linux-sles11-x86_64 / gcc@5.5.0 ------------------------------
u2yfqy7 libpciaccess@0.13.5%gcc

==> Do you want to proceed? [y/N] y
==> Successfully uninstalled libpciaccess@0.13.5%gcc@5.5.0 arch=linux-sles11-x86_64 /u2yfqy7

Attempt to install libpciaccess using binary cache.
> spack -d install --use-cache libpciaccess%gcc@5.5.0
==> Reading config file /hpc-common/software/spack/0.11.2/spack/etc/spack/defaults/packages.yaml
==> Reading config file /hpc-common/software/spack/0.11.2/spack/etc/spack/packages.yaml
==> READ LOCK: /home/garvct/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/garvct/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /home/garvct/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /hpc-common/software/spack/0.11.2/spack/etc/spack/compilers.yaml
==> Reading config file /home/garvct/.spack/compilers.yaml
==> Reading config file /home/garvct/.spack/linux/compilers.yaml
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[6005598696192687694:1] [Acquiring]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[6005598696192687694:1] [Acquired]
==> READ LOCK: /apps/local/spack/opt/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /apps/local/spack/opt/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /apps/local/spack/opt/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[6005598696192687694:1] [Released]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[6005598696192687694:1] [Acquiring]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[6005598696192687694:1] [Acquired]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[6005598696192687694:1] [Released]
==> Installing libpciaccess dependencies
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7067985372463565119:1] [Acquiring]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7067985372463565119:1] [Acquired]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7067985372463565119:1] [Released]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7067985372463565119:1] [Acquiring]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7067985372463565119:1] [Acquired]
==> libsigsegv is already installed in /apps/local/spack/opt/linux-sles11-x86_64/gcc-5.5.0/libsigsegv-2.11-yqwq47zwwijh7ejptph4y5vxdvez5cwo
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7067985372463565119:1] [Released]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7247655652124589715:1] [Acquiring]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7247655652124589715:1] [Acquired]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7247655652124589715:1] [Released]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7247655652124589715:1] [Acquiring]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7247655652124589715:1] [Acquired]
==> m4 is already installed in /apps/local/spack/opt/linux-sles11-x86_64/gcc-5.5.0/m4-1.4.18-zeu3bvhoph6smrfmqy44glvck5m5y7n3
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[7247655652124589715:1] [Released]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9078323240762093147:1] [Acquiring]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9078323240762093147:1] [Acquired]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9078323240762093147:1] [Released]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9078323240762093147:1] [Acquiring]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9078323240762093147:1] [Acquired]
==> libtool is already installed in /apps/local/spack/opt/linux-sles11-x86_64/gcc-5.5.0/libtool-2.4.6-7p4v3rxdtbolmubuyr73th4izhaaaij5
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9078323240762093147:1] [Released]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[1573454615899867481:1] [Acquiring]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[1573454615899867481:1] [Acquired]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[1573454615899867481:1] [Released]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[1573454615899867481:1] [Acquiring]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[1573454615899867481:1] [Acquired]
==> pkg-config is already installed in /apps/local/spack/opt/linux-sles11-x86_64/gcc-5.5.0/pkg-config-0.29.2-fowbcrpv2ijlh66mida5mjn6ch2xc5fp
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[1573454615899867481:1] [Released]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9045976832046734737:1] [Acquiring]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9045976832046734737:1] [Acquired]
==> WRITE LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9045976832046734737:1] [Released]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9045976832046734737:1] [Acquiring]
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9045976832046734737:1] [Acquired]
==> util-macros is already installed in /apps/local/spack/opt/linux-sles11-x86_64/gcc-5.5.0/util-macros-1.19.1-7mjyqaerdy5shisg2h6zhdwss2bda7c5
==> READ LOCK: /apps/local/spack/opt/.spack-db/prefix_lock[9045976832046734737:1] [Released]
==> Installing libpciaccess
==> Searching for binary cache of libpciaccess
==> Reading config file /home/garvct/.spack/linux/mirrors.yaml
==> Finding buildcaches in /hpc-common/software/spack/0.11.2/spack/var/spack/mirror/build_cache
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Acquiring]
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Acquired]
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Released]
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Acquiring]
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Acquired]
==> Fetching file:///hpc-common/software/spack/0.11.2/spack/var/spack/mirror/build_cache/linux-sles11-x86_64-gcc-5.5.0-util-macros-1.19.1-7mjyqaerdy5shisg2h6zhdwss2bda7c5.spec.yaml
==> '/usr/bin/curl' '-C' '-' '-o' '/hpc-common/software/spack/0.11.2/spack/var/spack/stage/build_cache/linux-sles11-x86_64-gcc-5.5.0-util-macros-1.19.1-7mjyqaerdy5shisg2h6zhdwss2bda7c5.spec.yaml.part' '-f' '-D' '-' '-L' 'file:///hpc-common/software/spack/0.11.2/spack/var/spack/mirror/build_cache/linux-sles11-x86_64-gcc-5.5.0-util-macros-1.19.1-7mjyqaerdy5shisg2h6zhdwss2bda7c5.spec.yaml' '-k' '-#'
######################################################################## 100.0%
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Released]
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Acquiring]
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Acquired]
==> WRITE LOCK: /hpc-common/software/spack/0.11.2/spack/var/spack/stage/.lock[6733663562491073450:1] [Released]
==> Installing libpciaccess from binary cache
==> Already downloaded /hpc-common/software/spack/0.11.2/spack/var/spack/stage/build_cache/linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.spack
==> /hpc-common/software/spack/0.11.2/spack/var/spack/stage/build_cache/linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.spec.yaml.asc
Traceback (most recent call last):
  File "/hpc-common/software/spack/0.11.2/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/hpc-common/software/spack/0.11.2/spack/lib/spack/spack/main.py", line 547, in main
    return _main(command, parser, args, unknown)
  File "/hpc-common/software/spack/0.11.2/spack/lib/spack/spack/main.py", line 439, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/hpc-common/software/spack/0.11.2/spack/lib/spack/spack/main.py", line 355, in _invoke_spack_command
    return_val = command(parser, args)
  File "/hpc-common/software/spack/0.11.2/spack/lib/spack/spack/cmd/install.py", line 461, in install
    install_spec(args, kwargs, spec)
  File "/hpc-common/software/spack/0.11.2/spack/lib/spack/spack/cmd/install.py", line 358, in install_spec
    package.do_install(**kwargs)
  File "/hpc-common/software/spack/0.11.2/spack/lib/spack/spack/package.py", line 1370, in do_install
    if self.try_install_from_binary_cache(explicit):
  File "/hpc-common/software/spack/0.11.2/spack/lib/spack/spack/package.py", line 1282, in try_install_from_binary_cache
    binary_spec, tarball, yes_to_all=False, force=False)
  File "/hpc-common/software/spack/0.11.2/spack/lib/spack/spack/binary_distribution.py", line 405, in extract_tarball
    raise NoVerifyException()
spack.binary_distribution.NoVerifyException

I can do a binary cache install for other packages, why does the binary cache install for libpciaccess fail?

I am using spack 0.11.2, running on SLES11SP4.

Thanks,

**Comment by adamjstewart** [comment]
@gartung

**Comment by gartung** [comment]
RTFM

**Comment by garvct** [comment]
My gpg keys are correct, I can install other packages via build cache.

Adding the -y option to install also fails.

**Comment by gartung** [comment]
What branch/version are you using?

**Comment by garvct** [comment]
spack version corresponding to tag 0.11.2

**Comment by gartung** [comment]
This is exactly where it is failing.
https://github.com/spack/spack/blob/8913c3465c2615f0d314b16e8b14cbbaec7e01d1/lib/spack/spack/binary_distribution.py#L405
Either gpg is not available or the verification is failing.

**Comment by gartung** [comment]
This is the location where gpg is called
https://github.com/spack/spack/blob/54f97d1dec8df18b3d34144f38760abd9a7cc5b4/lib/spack/spack/util/gpg.py#L112

**Comment by gartung** [comment]
I would clean out the download cache and re-download.

**Comment by garvct** [comment]
The signature file linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.spec.yaml.asc does not exist?

**Comment by garvct** [comment]
The signature file linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.spec.yaml.asc does not exist?

**Comment by garvct** [comment]
For other packages the appropriate signature file exists?

e.g
linux-sles11-x86_64-gcc-5.5.0-util-macros-1.19.1-7mjyqaerdy5shisg2h6zhdwss2bda7c5.spec.yaml.asc

**Comment by gartung** [comment]
You can verify with tar tfz filename.spack and see if the .asc file is listed.

I am able to create and install a buildcache for libpciaccess on RHEL7 using spack v0.11.2.

Try reproducing and copying the buildcache in the build_cache directory on the spack mirror.

**Comment by gartung** [comment]
The copy in this directory 
 /hpc-common/software/spack/0.11.2/spack/var/spack/mirror/build_cache
might have been created without signing.

**Comment by garvct** [comment]
It appear to be in the file.

tar tf linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.spack
linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.tar.gz
linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.spec.yaml
linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.spec.yaml.asc

**Comment by gartung** [comment]
I also recommend using 
spack buildcache install /u2yfqy7
as the spec of libpciaccess might be concretized differently if you updated spack.

**Comment by gartung** [comment]
Did you do 'spack gpg trust 81F2F332' ?

**Comment by gartung** [comment]
In fact you may have to explicitly export your key and trust it. 
spack gpg export 81F2F332
spack gpg trust 81F2F332

**Comment by garvct** [comment]
If there was an issue with my keys, then no package would install with the binary cache?
I have other packages which install fine with binary cache in the same environment?

**Comment by gartung** [comment]
I see this in your original log

Already downloaded /hpc-common/software/spack/0.11.2/spack/var/spack/stage/build_cache/linux-sles11-x86_64-gcc-5.5.0-libpciaccess-0.13.5-u2yfqy7mhj6j2aqrydg44prwonsgjj3l.spack

You can try 
spack buildcache install -f -y /u2yfqy7

**Comment by garvct** [comment]
I suspect this might by a filesystem timing issue? I am building on a shared nfs filesystem.

**Comment by gartung** [comment]
Could be. You were getting a cached version of the .spack file from somewhere.

**Comment by gartung** [comment]
I always use 
spack buildcache create -d dirname to write the build_cache directory outside of the spack install tree to a directory that is web accessable.

**Comment by garvct** [comment]
After removing spack and doing a clean install, I can now install libpciaccess from the build cache. Thank you for your help.

**Comment by gartung** [comment]
You're welcome.
