### ISSUE TITLE
Installation of package suite-sparse fail.

### ISSUE THREAD

**Issue by Oximore** [spack/spack#7610]
Installation of package suite-sparse fail.

It seems that package suite-sparse do not mention a dependance to gcc version 4.9 or greater.
See : [suite-sparse/package.py](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/suite-sparse/package.py#L47)
### Expected Result

```
spack install suite-sparse
```
Correct install.

### Actual Result
Suite-sparse installation fail with this message : 
```
1 error found in build log:
[...]
  >> 38    CMake Error at CMakeLists.txt:65 (message):
     39      gcc version must be at least 4.9
```

Complet log here :  
[spack-suite-sparse.log](https://github.com/spack/spack/files/1852009/spack-suite-sparse.log)

### Steps to reproduce the issue

```console
cd spack
git pull
spack install suite-sparse
```

### Information on your system

```
benjamin@nebulja:~/Codes/Spack $ uname -a
Linux nebulja 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
benjamin@nebulja:~/Codes/Spack $ spack arch
linux-ubuntu14.04-x86_64
benjamin@nebulja:~/Codes/Spack $ spack compilers 
==> Available compilers
-- gcc ubuntu14.04-x86_64 ---------------------------------------
gcc@4.8
```

[packages.yaml](https://github.com/spack/spack/files/1852030/packages.yaml.txt)
[compilers.yaml](https://github.com/spack/spack/files/1852032/compilers.yaml.txt)
(renamed because github won't me upload something else than .txt)

Also, I use an other personal spack repo, but I don't think this is correlated.
Because this repo only build something on top of suite-sparse.

Feel free to ask for anything I omitted.

Regards,
Benjamin

**Comment by Oximore** [comment]
@adamjstewart Thank you for your quick response.
However, after applied your [patch](https://github.com/spack/spack/pull/7612/files) locally, Spack just throw me an error.

Should I install an other GCC version on my one, then tell Spack where to find it ?
Spack goal is not to do this installation for me, in an automated way, it is ?

I know Spack compiler are not managed the same way as dependencies, but I am uncertain how it does.

Regards

**Comment by adamjstewart** [comment]
You can install a newer GCC compiler on your own or with Spack. Then, once it is installed, run `spack compiler add` on this installation prefix.

You are right that compilers are currently not treated like dependencies, which is why spack doesn't automatically install a newer compiler for you.

**Comment by Oximore** [comment]
I use a specific suite sparse version, `suite-sparse@5.1.0`, to solve this issue.
I will now close it.

If you think it need to be re-open, feel free to do.
Note : there is always [PR 7612](https://github.com/spack/spack/pull/7612) to discuss about this issue.
