### ISSUE TITLE
SCons download url 404

### ISSUE THREAD

**Issue by ch741** [spack/spack#7613]
Summary

Fetching scons-2.5.1 fails as the PyPi download url returns a 404 error.
Other packages from PyPi seem to work.
This is only in the 0.11.x versions, previous versions used a sourceforge link.

### Expected Result

Spack to download and build SCons as a dependency to another package

### Actual Result

The following error:
```
==> Fetching https://pypi.io/packages/source/s/scons/scons-2.5.1.tar.gz
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from https://pypi.io/packages/source/s/scons/scons-2.5.1.tar.gz failed.
==> Error: FetchError: All fetchers failed for scons-2.5.1-nozqwus7rirav57cibr7b4fksjivsevg
FetchError: FetchError: All fetchers failed for scons-2.5.1-nozqwus7rirav57cibr7b4fksjivsevg

/usr/local/spack/lib/spack/spack/package.py:1025, in do_fetch:
     25                                     self.spec.format('$_$@'), ck_msg)
     26    
     27            self.stage.create()
  >> 28            self.stage.fetch(mirror_only)
     29            self._fetch_time = time.time() - start_time
     30    
     31            if spack.do_checksum and self.version in self.versions:

```

### Steps to reproduce the issue

```console
$ spack install scons
```

### Information on your system

 1. Platform: CentOS 7 Singularity container
 2. GNU toolchain used

Curling [https://pypi.io/simple/scons](https://pypi.io/simple/scons) fetches the list with the working download urls, for 2.5.1 it's:
[https://pypi.python.org/packages/2c/ee/a9601b958c94e93410e635a5d67ed95300998ffdc36127b16d322b054ff0/scons-2.5.1.tar.gz#md5=3eac81e5e8206304a9b4683c57665aa4](https://pypi.python.org/packages/2c/ee/a9601b958c94e93410e635a5d67ed95300998ffdc36127b16d322b054ff0/scons-2.5.1.tar.gz#md5=3eac81e5e8206304a9b4683c57665aa4)

**Comment by adamjstewart** [comment]
I had no idea https://pypi.org/simple existed, this is a great discovery! I'll fix the scons package.
