### ISSUE TITLE
mirror.yaml tilde path not expanded

### ISSUE THREAD

**Issue by berceanu** [spack/spack#7628]
~/ is not expanded on parsing mirror.yaml

### Expected Result

~/ should be replaced by /home/[USER]/

### Actual Result

~/ is replaced by /

### Steps to reproduce the issue

Following steps in [the manual](https://spack.readthedocs.io/en/latest/mirrors.html#spack-mirror-add).

The path is properly added:
```bash
$ cat $HOME/.spack/linux/mirrors.yaml 
mirrors:
  local_filesystem: file:///home/andrei/src/spack-mirror-2018-03-28
```

but installs throw warnings such as

```
==> Installing mpfr
==> Fetching file://~/src/spack-mirror-2018-03-28/mpfr/mpfr-4.0.1.tar.bz2
curl: (37) Couldn't open file /src/spack-mirror-2018-03-28/mpfr/mpfr-4.0.1.tar.bz2
```

(note the missing ~)

### Information on your system

Ubuntu LTS 16.04
bash terminal

**Comment by adamjstewart** [comment]
Unfortunately, Bash doesn't expand tildes when they are in the middle of a string:
```
$ echo ~
/Users/Adam
$ echo foo~bar
foo~bar
```
There currently isn't any logic in Spack that expands these tildes either.

At one point I was going through the documentation and replaced all of the `/home/tgamblin` strings with `~` without checking whether `~` actually worked in that context. We should probably undo this, at least for the mirrors section.

But if you can figure out a way to expand tildes in the mirror code, that would also be useful.

**Comment by ax3l** [comment]
We did in our case also just replace `~` with `$HOME` in the `spack mirror add` command which is expanded directly in the argument and available on all systems.

We were replacing all occuarances in the docs until we saw that it also mentions to "write directly to the `mirror.yaml`" in which we had not good expression because `$HOME` is  not defined in it.

**Comment by ax3l** [comment]
I will add a PR with a fix
