### ISSUE TITLE
nasm download url dead

### ISSUE THREAD

**Issue by ch741** [spack/spack#7637]
Hi,

The nasm.us website is down so downloading nasm doesn't work. A fedoraproject.org link could be used instead.

### Expected Result

Spack to download nasm as a dependency to another package.

### Actual Result

```
==> Fetching http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.xz

curl: (7) Failed connect to www.nasm.us:80; Connection refused
==> Fetching from http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.xz failed.
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Can not find version 2.13.03 in url_list
==> Error: FetchError: All fetchers failed for nasm-2.13.03-ftouqgekcfxqxtrjrup3yhwaejor57kn
FetchError: FetchError: All fetchers failed for nasm-2.13.03-ftouqgekcfxqxtrjrup3yhwaejor57kn

/usr/local/spack/lib/spack/spack/package.py:1025, in do_fetch:
     25                                     self.spec.format('$_$@'), ck_msg)
     26    
     27            self.stage.create()
  >> 28            self.stage.fetch(mirror_only)
     29            self._fetch_time = time.time() - start_time
     30    
     31            if spack.do_checksum and self.version in self.versions:

```

### Steps to reproduce the issue

```console
$ spack install nasm
```

### Information on your system

 1. Platform: CentOS7 Singularity Container
 2. Using spack:develop

The following link could potentially be used as an alternative although it's bz2 and has a different hash.

https://src.fedoraproject.org/repo/pkgs/nasm/nasm-2.13.03.tar.bz2/sha512/d7a6b4cee8dfd603d8d4c976e5287b5cc542fa0b466ff989b743276a6e28114e64289bf02a7819eca63142a5278aa6eed57773007e5f589e15768e6456a8919d/nasm-2.13.03.tar.bz2

A slightly related question, what's the easiest way to get a dependants list/tree for a package. I'm trying to install OpenFOAM and one of the dependencies pulls in nasm, so if possible I'll try and avoid that.

**Comment by adamjstewart** [comment]
There currently isn't a way to add a backup mirror for a package. There are future plans to add a LLNL Spack mirror so that Spack by default downloads from there instead of unreliable internet downloads. We could switch the URL in the nasm package, but I'm not sure how long the website will be down for.

> what's the easiest way to get a dependants list/tree for a package

You have a few options.

### Packages that depend on `nasm`
```
$ spack dependents nasm
libjpeg-turbo
```
### Packages that `openfoam` depends on
```
$ spack dependencies openfoam
boost  flex                   kahip     openfoam-com  parmetis     spectrum-mpi
cgal   foam-extend            metis     openfoam-org  parmgridgen  zlib
cmake  intel-mpi              mpich     openmpi       python       zoltan
fftw   intel-parallel-studio  mvapich2  paraview      scotch
```
### Spec of dependencies
```
$ spack spec openfoam
```
### Graph of dependencies
```
$ spack graph openfoam
```
To get around this dependency you have 2 options
### Don't install the paraview dependency
```
$ spack install openfoam -paraview
```
### Build with libjpeg instead of libjpeg-turbo
```
$ spack install openfoam-com@1712 +paraview ^libjpeg
```

**Comment by ch741** [comment]
Great! That helps a lot, thanks!

**Comment by adamjstewart** [comment]
Looks like the nasm website is back up now.

**Comment by pat-s** [comment]
The website is down again since a few days. I edited the formula with the Fedora link from @ch741 and it built fine.
Will open a PR.
