### ISSUE TITLE
Compiler caching mechanism in compilers.__init__.py  is fragile and can produce erroneous cache hits and misses

### ISSUE THREAD

**Issue by chissg** [spack/spack#7647]
## Summary

The compiler caching mechanism in `spack.compilers.__init__.py` is fragile and prone to both erroneous hits and misses due to the fact that it uses the _address_ of the dictionary passed to `compilers.compiler_from_config_entry()` as a lookup in the cache. If `compilers.compiler_from_config_entry()` is called with two equivalent dictionaries which happen to be different objects, two cache entries will be made instead of the second call returning the cached entry from the first. Conversely (and more seriously), if the function is called twice with an object at the same address but with different content (which can happen _either_ if the dictionary object is reused by the caller, _or_ if the dictionary is function-local and garbage-collection has caused the reuse of an address previously seen by the cache), then `compilers.compiler_from_config_entry()` will return an incorrect compiler object rather than creating and caching a new one.

While it is entirely possible that the _current_ use of this function during spack initialization will only produce, at worst, a couple of unnecessary compiler object constructions, the intensive use of the compiler system that one might expect during comprehensive tests is very likely to trigger erroneous cache hits (see PR #7601, for example). Additionally, this is a massive gotcha lying in wait for any enhancement to Spack that changes the way compilers are handled during or after initialization.

### Steps to reproduce the issue

1. Download and decompress the attached python script:  [compiler-cache-fail.py.gz](https://github.com/spack/spack/files/1864126/compiler-cache-fail.py.gz)
1. Set up your favorite instance of Spack.
1. Execute the test script:
   ```console
   $ python compiler-cache-fail.py
   FF
   ======================================================================
   FAIL: test_compiler_cache_hits (__main__.TestCompilerCache)
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/greenc/compiler-cache-fail.py", line 79, in test_compiler_cache_hits
       self.assertEqual(len(spack.compilers._compiler_cache), 1)
   AssertionError: 2 != 1
   
   ======================================================================
   FAIL: test_compiler_cache_misses (__main__.TestCompilerCache)
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/greenc/compiler-cache-fail.py", line 65, in test_compiler_cache_misses
       compiler.spec.versions), spec)
   AssertionError: 'gcc@2.7.3' != 'clang@9.2-apple'
   
   ----------------------------------------------------------------------
   Ran 2 tests in 0.003s
   
   FAILED (failures=2)
   ```

### Information on your system

SLF7, Spack from develop

**Comment by scheibelp** [comment]
Hi @chissg I'm curious about your thoughts on https://github.com/spack/spack/pull/7675

It doesn't address all (or even most) aspects of fragility you mention here, namely that the cache can have essentially duplicate entries. It does however prevent false positive cache hits. I suppose I wanted to address the truly broken aspect of it, and whether or not the cache contains duplicate entries is more a matter of efficiency vs. correctness. Is that satisfactory?

**Comment by chissg** [comment]
Hi @scheibelp,

It prevents erroneous cache hits in the case of garbage collection; it does nothing to prevent them in the (perfectly legitimate) case of dictionary reuse. If someone shows you a dry-erase board with a request for form 2017 on it, and then later they show you the same board with a request for form 2018, they're going to be understandably upset if you give them form 2017 again based on the fact they used the same board as last time. If, "not using the same board for a different request" is detectable and enforceable, that's one thing ("Sorry, requests on paper only").  If it's a silent prerequisite ("Don't do that 'coz it'll hurt"), that's another. Especially since, if I'm reading the PR correctly, having the dictionary be a function-local variable of a function that's called more than once is going to qualify as, "using the same board."

I guess my TL;DR on PR #7675 is that I'm still not sure how anyone can reliably use `compilers.compiler_from_config_entry()` safely.

**Comment by scheibelp** [comment]
I've updated #7675 with the following:

* Isolated the parse-dictionary-into-compiler logic into a separate function: `compiler_from_dict`
* Do caching in a private function in the module

I think this would be satisfactory because

* The function still has strange call semantics (e.g. you'd have to provide a different dictionary) but it is hidden from the user
* You can build `Compiler` objects from dictionaries without worrying about this

Does that sound reasonable?

**Comment by chissg** [comment]
I tested it by applying PR #7601 on top of PR #7675 locally and making the obvious adjustments (removing the manual cache reset and replacing `compiler_from_config_entry()` with `compiler_from_dict()`). Upon running the unit tests multiple times, I appear to get reliably correct results. As long as the internal use of the caching has a note laying out the assumptions and rules for future maintainers, I think I'm good with this.

**Comment by scheibelp** [comment]
@chissg I was iterating on #7675 to resolve this, but has it resolved for you in the meantime without it?
