### ISSUE TITLE
treatment of externals changed recently?

### ISSUE THREAD

**Issue by davydden** [spack/spack#7653]
I have the following setup for external MPI from HPC admins:
```
  openmpi:
    version: [2.0.2]
    paths:
      openmpi@2.0.2%gcc@4.8.5: /apps/OpenMPI/2.0.2-gcc/
    buildable: False
```

### Expected Result

spack should use it in concretization (that was the behaviour from around January 2018)

### Actual Result

concretizer shows that `openmpi` will be installed
```
     dealii@develop%gcc@4.8.5~adol-c+arpack~assimp build_type=DebugRelease ~cuda cuda_arch= ~doc~gmsh+gsl+hdf5~int64+metis+mpi~nanoflann+netcdf+oce+optflags+p4est+petsc~python~scalapack+slepc~sundials+trilinos arch=linux-centos7-x86_64
         ^arpack-ng@3.5.0%gcc@4.8.5+mpi+shared arch=linux-centos7-x86_64
             ^cmake@3.11.0%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-x86_64
[+]              ^ncurses@6.0%gcc@4.8.5 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-centos7-x86_64
[+]                  ^pkgconf@1.4.0%gcc@4.8.5 arch=linux-centos7-x86_64
                 ^openssl@1.0.2n%gcc@4.8.5+systemcerts arch=linux-centos7-x86_64
[+]                  ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64
[+]          ^openblas@0.2.20%gcc@4.8.5 cpu_target= ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=linux-centos7-x86_64
             ^openmpi@2.0.2%gcc@4.8.5~cuda fabrics=verbs ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple~ucx+vt arch=linux-centos7-x86_64
```

### Steps to reproduce the issue

edit `packages.yaml` and try concretizing.

### Information on your system

CentOS

**Comment by adamjstewart** [comment]
I don't think this behavior has changed (as far as I know). If you add a new external, Spack doesn't know it is installed. Once you explicitly "install" it (or something that depends on it), it adds that external package to the database. After that, it _should_ display as being installed.

Can you run `spack install openmpi` and then try again?

**Comment by davydden** [comment]
> If you add a new external, Spack doesn't know it is installed. Once you explicitly "install" it (or something that depends on it), it adds that external package to the database.

ha, i never noticed this. You are absolutely right:

```
==> openmpi@2.0.2 : externally installed in /apps/OpenMPI/2.0.2-gcc
==> openmpi@2.0.2 : generating module file
==> openmpi@2.0.2 : registering into DB
```
