### ISSUE TITLE
Plain `spack mirror` fails with concretization error

### ISSUE THREAD

**Issue by jadoro** [spack/spack#7663]
I was recently trying to set up a full spack mirror. On the current development branch (17ace14), this fails with a concretization error in `petsc`.

Side remark: Why does spack need to concretize a tree for mirroring if no custom package set is supplied? As far as I understood that feature, it will enable the user to `spack install` _arbitrary_ configurations from the created mirror, so every defined source should be cloned.

### Expected Result

Lots of packages are downloaded.

### Actual Result

```console
$ ./spack mirror create
==> No safe (checksummed) versions for package spectrum-mpi
==> Error: An unsatisfiable variant constraint has been detected for spec:

    hdf5@1.10.1%gcc@4.9.2~cxx~debug+fortran~hl+mpi+pic+shared~szip~threadsafe arch=linux-debian8-x86_64 


while trying to concretize the partial spec:

    petsc@develop%gcc@4.9.2+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps+shared~suite-sparse+superlu-dist~trilinos arch=linux-debian8-x86_64 
        ^hypre@develop~int64~internal-superlu
            ^openblas@0.2.20%gcc@4.9.2 cpu_target= ~ilp64+pic+shared threads=none ~virtual_machine arch=linux-debian8-x86_64 
        ^sowing@1.1.23-p1%gcc@4.9.2 arch=linux-debian8-x86_64 
        ^superlu-dist@develop~int64
            ^metis@5:
                ^cmake@3.11.0%gcc@4.9.2~doc+ncurses+openssl+ownlibs~qt arch=linux-debian8-x86_64 
                    ^ncurses@6.0%gcc@4.9.2~symlinks~termlib arch=linux-debian8-x86_64 
                        ^pkgconf@1.4.0%gcc@4.9.2 arch=linux-debian8-x86_64 
                    ^openssl@1.0.2n%gcc@4.9.2+systemcerts arch=linux-debian8-x86_64 
                        ^zlib@1.2.11%gcc@4.9.2+optimize+pic+shared arch=linux-debian8-x86_64 
            ^openmpi@3.0.1%gcc@4.9.2~cuda fabrics= ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple~ucx+vt arch=linux-debian8-x86_64 
                ^hwloc@:1.999
            ^parmetis


petsc requires hdf5 variant +hl, but spec asked for ~hl
```

### Steps to reproduce the issue

```console
$ git clone https://github.com/spack/spack.git  
$ cd spack/bin
$ git rev-parse --short HEAD
17ace14
$ ./spack mirror create
```

### Information on your system

```console
$ uname -a
Linux XXX 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux
```

**Comment by davydden** [comment]
I think in nature it is the same issue as mentioned here https://github.com/spack/spack/issues/7288#issuecomment-376773145 
and here https://github.com/spack/spack/issues/5753#issuecomment-340130452

**Comment by adamjstewart** [comment]
> Side remark: Why does spack need to concretize a tree for mirroring if no custom package set is supplied? As far as I understood that feature, it will enable the user to spack install arbitrary configurations from the created mirror, so every defined source should be cloned.

Because it needs to determine which versions to download.

**Comment by jadoro** [comment]
> Because it needs to determine which dependencies and versions to download.

OK, seems like you're clearing up a major misunderstanding from my side. So the following is not possible because old source version are not mirrored (if they are not appearing as some dependency)?

```console
with-internet-machine$ spack mirror create
wiithout-internet-machine$ spack mirror add ...
wiithout-internet-machine$ spack install {PACKAGE}@{NON-DEFAULT-VERSION}
```

**Comment by tgamblin** [comment]
@jadoro: Since #12940 there is now `spack mirror create --all`, which can mirror everything without needing to concretize everything.  Concretizing is actually the wrong thing to do for `--all`, anyway, as we know statically, without concretizing, what all the possible sources are.
