### ISSUE TITLE
spack install libxml2%intel failing with intel 2017

### ISSUE THREAD

**Issue by rrobinson-RMS** [spack/spack#7670]
Hi my install of libxml2 with intel compilier is failing it work with GCC.
It doesnt seem to be able to get to the intel libraries ie libimf.so libsvml.so etc

[rrobinson@ukvmlx-ssh-02 spack]$ echo $CPATH 
/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/ipp/include:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/mkl/include:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/tbb/include:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/daal/include

[rrobinson@ukvmlx-ssh-02 spack]$ echo $LD_LIBRARY_PATH 
/mnt/opt/Centos6.4/intel_2017/itac/2017.0.020/mic/slib:/mnt/opt/Centos6.4/intel_2017/itac/2017.0.020/intel64/slib:/mnt/opt/Centos6.4/intel_2017//itac/2017.0.020/mic/slib:/mnt/opt/Centos6.4/intel_2017//itac/2017.0.020/intel64/slib:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/mpi/intel64/lib:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/mpi/mic/lib:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/ipp/lib/intel64:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.4:/mnt/opt/Centos6.4/intel_2017/debugger_2017/iga/lib:/mnt/opt/Centos6.4/intel_2017/debugger_2017/libipt/intel64/lib:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/daal/lib/intel64_lin:/mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-

Where should I have the path to the libraries ?

CPATH ?

Thanks Roger

### Information on your system

This includes:

 1. CentOS 7.4 , intel compiliers 2017

==> pkgconf is already installed in /mnt/opt/Centos7/hpc/spack/spack/opt/spack/linux-centos7-x86_64/intel-17.0.0/pkgconf-1.4.0-qfmfixfgcndtvh2ju2j6mf7mqtaqz74z
==> xz is already installed in /mnt/opt/Centos7/hpc/spack/spack/opt/spack/linux-centos7-x86_64/intel-17.0.0/xz-5.2.3-lfico6fisgwk7rvzmcisppgb4lvvnpyx
==> zlib is already installed in /mnt/opt/Centos7/hpc/spack/spack/opt/spack/linux-centos7-x86_64/intel-17.0.0/zlib-1.2.11-aqvemvpmoisxdurh3wqafsseuvslh2dc
==> Installing libxml2
==> Using cached archive: /mnt/opt/Centos7/hpc/spack/spack/var/spack/cache/libxml2/libxml2-2.9.4.tar.gz
==> Staging archive: /mnt/opt/Centos7/hpc/spack/spack/var/spack/stage/libxml2-2.9.4-ln64jgbbv4pgoypxu5ktebbgshhlwn6k/libxml2-2.9.4.tar.gz
==> Created stage in /mnt/opt/Centos7/hpc/spack/spack/var/spack/stage/libxml2-2.9.4-ln64jgbbv4pgoypxu5ktebbgshhlwn6k
==> No patches needed for libxml2
==> Building libxml2 [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12'

13 errors found in build log:
     29      checking for tar... /usr/bin/tar
     30      checking for perl... /usr/bin/perl
     31      checking for wget... /usr/bin/wget
     32      checking for xmllint... /usr/bin/xmllint
     33      checking for xsltproc... /usr/bin/xsltproc
     34      checking for pkg-config... /mnt/opt/Centos7/hpc/spack/spack/opt/spack/linux-centos7-x86_64/intel-17.0.0/pkgconf-1.4.0-qfmfixfgcndtvh2ju2j6mf7mqtaqz74z/bin/pkg-config
  >> 35      checking pkg-config is at least version 0.9.0... /mnt/opt/Centos7/hpc/spack/spack/opt/spack/linux-centos7-x86_64/intel-17.0.0/pkgconf-1.4.0-qfmfixfgcndtvh2ju2j6mf7mqtaqz74z/bin/pkg-config: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
     36      no
     37      checking how to print strings... printf
     38      checking for a sed that does not truncate output... /usr/bin/sed
     39      checking for grep that handles long lines and -e... /usr/bin/grep
     40      checking for egrep... /usr/bin/grep -E
     41      checking for fgrep... /usr/bin/grep -F

     ...

     1424    ld: warning: libsvml.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1425    ld: warning: libirng.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1426    ld: warning: libirng.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1427    ld: warning: libintlc.so.5, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1428    ld: warning: libintlc.so.5, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1429    ld: .libs/testC14N: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1430    ld: final link failed: Bad value
     1431    ld: .libs/testRelax: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1432    ld: final link failed: Bad value
     1433    make[2]: *** [Makefile:1070: testRelax] Error 1
     1434    make[2]: *** Waiting for unfinished jobs....
     1435    ld: .libs/testURI: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1436    ld: final link failed: Bad value
     1437    ld: .libs/testSAX: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1438    ld: final link failed: Bad value
     1439    make[2]: *** [Makefile:1086: testURI] Error 1
     1440    make[2]: *** [Makefile:1050: testC14N] Error 1
     1441    make[2]: *** [Makefile:1074: testSAX] Error 1
     1442    ld: .libs/xmllint: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1443    ld: final link failed: Bad value
     1444    make[2]: *** [Makefile:1118: xmllint] Error 1
     1445    ld: warning: libimf.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1446    ld: warning: libsvml.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1447    ld: warning: libirng.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1448    ld: warning: libintlc.so.5, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1449    ld: warning: libimf.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)

     ...

     1460    ld: warning: libintlc.so.5, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1461    ld: warning: libimf.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1462    ld: warning: libsvml.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1463    ld: warning: libirng.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1464    ld: warning: libintlc.so.5, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1465    ld: .libs/testXPath: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1466    ld: final link failed: Bad value
     1467    ld: .libs/xmlcatalog: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1468    ld: final link failed: Bad value
     1469    ld: .libs/testAutomata: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1470    ld: final link failed: Bad value
     1471    make[2]: *** [Makefile:1090: testXPath] Error 1
     1472    make[2]: *** [Makefile:1114: xmlcatalog] Error 1
     1473    ld: .libs/testSchemas: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1474    ld: final link failed: Bad value
     1475    ld: .libs/testThreads: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1476    ld: final link failed: Bad value
     1477    ld: warning: libimf.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1478    ld: warning: libsvml.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1479    ld: warning: libirng.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1480    ld: warning: libintlc.so.5, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1481    make[2]: *** [Makefile:1046: testAutomata] Error 1
     1482    make[2]: *** [Makefile:1078: testSchemas] Error 1
     1483    make[2]: *** [Makefile:1082: testThreads] Error 1
     1484    ld: .libs/testRegexp: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1485    ld: final link failed: Bad value
     1486    make[2]: *** [Makefile:1066: testRegexp] Error 1
     1487    ld: warning: libimf.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1488    ld: warning: libsvml.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1489    ld: warning: libirng.so, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1490    ld: warning: libintlc.so.5, needed by ./.libs/libxml2.so, not found (try using -rpath or -rpath-link)
     1491    ld: .libs/testHTML: hidden symbol `__intel_cpu_features_init_x' in /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
  >> 1492    ld: final link failed: Bad value
     1493    make[2]: *** [Makefile:1054: testHTML] Error 1
     1494    make[2]: Leaving directory '/tmp/rrobinson/spack-stage/spack-stage-d9SKXp/libxml2-2.9.4'
     1495    make[1]: *** [Makefile:1440: all-recursive] Error 1
     1496    make[1]: Leaving directory '/tmp/rrobinson/spack-stage/spack-stage-d9SKXp/libxml2-2.9.4'
     1497    make: *** [Makefile:859: all] Error 2

See build log for details:
  /mnt/opt/Centos7/hpc/spack/spack/var/spack/stage/libxml2-2.9.4-ln64jgbbv4pgoypxu5ktebbgshhlwn6k/libxml2-2.9.4/spack-build.out

### Steps to reproduce the issue

```console
$ spack <command1> <spec>
$ spack <command2> <spec>
...
```

**Comment by rrobinson-RMS** [comment]
Sorry this appears to be the same issue as this -> https://github.com/spack/spack/issues/5705

I need to load the intel module in .spack/linux/compiler.yaml

**Comment by tylerjereddy** [comment]
Yeah, I'll have to parse those out I guess since modules aren't an option for now.

**Comment by rrobinson-RMS** [comment]
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: [intel/2017]
    operating_system: centos7
    paths:
      cc: /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/icc
      cxx: /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc
      f77: /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/ifort
      fc: /mnt/opt/Centos6.4/intel_2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/ifort
    spec: intel@17.0.0
    target: x86_64

What I did was add modules: [intel/2017] this makes sure all the intel compilier env variables are set.

**Comment by rrobinson-RMS** [comment]
I guess you could put stuff in environment: {}
 ?

**Comment by certik** [comment]
@tylerjereddy, I created my own "module load intel", and in it, I set the `CC`, `CXX`, `FC` variables, `PATH` and `LD_LIBRARY_PATH`. I assume it's the `LD_LIBRARY_PATH` that must be set, otherwise it breaks.

**Comment by rrobinson-RMS** [comment]
My intel module is massive. Im not sure where I got it from. I certainly havent wrote it. Are you sure a module file isnt created when as part of the install process.

I'll have a look and see if I can find one in the intel directory.

**Comment by certik** [comment]
@rrobinson-RMS yes, the install process I think creates some module files and they were messy, so I just created a minimal version for myself, so that I know exactly what is happening.

**Comment by rrobinson-RMS** [comment]
https://software.intel.com/en-us/articles/using-environment-modules-with-the-intel-development-tools

**Comment by tylerjereddy** [comment]
None of the discussed solutions worked for me. `LD_LIBRARY_PATH` had no apparent effect, nor did sourcing the intel dotfiles that come with the compilers. I even tried replicating the module env vars set on an hpc machine when intel is loaded after cleaning out my env variables on a fresh login.

Finally, I did find a solution that worked for me though--I had to set `extra_rpaths` (in `~/.spack/linux/compilers.yaml`) to the `compilers_and_libraries/linux/lib/intel64` path, purge all intel-related packages from spack, and then reinstall openmpi w/ intel from scratch.

I see there are some open issues related to RPATH matters, and it doesn't appear that we can specify rpath directly on the command line from a `spack install` command, though I may be mistaken.

**Comment by s-sajid-ali** [comment]
I have the same issue with intel@19.0.046, 2019 preview version of intel compilers. I've tried adding modules = [intel/2019] (as @rrobinson-RMS  suggested) and that immediately breaks the package context for anything I try to install using the intel compiler. 

@tylerjereddy  What was the argument for the extra_rpaths ?

**Comment by tylerjereddy** [comment]
@s-sajid-ali the `extra_rpaths` was set to the spack intel compiler lib install location, which is something like ---- `intel@17.0.3-HASH_VALUE/compilers_and_libraries/linux/lib/intel64`

I can find a more precise path when I'm back at the lab, and I think I had a bash command to just programmatically pull out the path and append `compilers_and_libraries/linux/lib/intel64`

Basically, `spack find -p intel@17.0.3` and then add `compilers_and_libraries/linux/lib/intel64` to the end of that path I think.

**Comment by s-sajid-ali** [comment]
I installed the intel compilers using without using spack and I get this when I try finding them : 

```
[sajid@xrmlite linux]$ spack find -p intel@19.0.046
==> No package matches the query: intel@19.0.046
```

**Comment by tylerjereddy** [comment]
Ah, pretty sure my "fix" assumes that you've installed the compiler using `spack install intel@19.0.046`. One suggestion might be to create your own custom "spackage" so that you can use `spack install` even though this is a bleeding edge version you have locally or whatever.

Not sure if that is more work than you'd want; there's also a section on [handling RPATHs](http://spack.readthedocs.io/en/latest/packaging_guide.html#handling-rpaths) if you do go the route of making your own package for spack.

**Comment by s-sajid-ali** [comment]
I wanted to build my packages using intel compilers for speed and got access to the 2019 preview. I'll see if I can uninstall and re-install using spack. Thanks for the help!
