### ISSUE TITLE
lmod generation with multiple compiler definitions using same compiler path fails for first definition

### ISSUE THREAD

**Issue by gartung** [spack/spack#7679]
We have two compiler definitions for the same compiler install so that different sets of cxxflags can be used. Generating lmod files for packages built with the first compiler defintion fails.

compilers.yaml:

- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-vg3iy5rdxcj2mnnohcnn2ogioasheuos/bin/gcc
      cxx: /home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-vg3iy5rdxcj2mnnohcnn2ogioasheuos/bin/g++
      f77: /home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-vg3iy5rdxcj2mnnohcnn2ogioasheuos/bin/gfortran
      fc: /home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-vg3iy5rdxcj2mnnohcnn2ogioasheuos/bin/gfortran
    spec: gcc@6.4.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cxxflags: '-std=c++17'
    modules: []
    operating_system: rhel7
    paths:
      cc: /home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-vg3iy5rdxcj2mnnohcnn2ogioasheuos/bin/gcc
      cxx: /home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-vg3iy5rdxcj2mnnohcnn2ogioasheuos/bin/g++
      f77: /home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-vg3iy5rdxcj2mnnohcnn2ogioasheuos/bin/gfortran
      fc: /home/gartung/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-vg3iy5rdxcj2mnnohcnn2ogioasheuos/bin/gfortran
    spec: gcc@6.4.0-1
    target: x86_64

Session where error is reproduced.

[gartung@gartung ~]$ spack -d module refresh --delete-tree -m lmod patchelf
==> READ LOCK: /home/gartung/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /home/gartung/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /home/gartung/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> You are about to regenerate lmod module files for:

-- linux-rhel7-x86_64 / gcc@4.8.5 -------------------------------
xuekuii patchelf@0.9

-- linux-rhel7-x86_64 / gcc@6.4.0 -------------------------------
u54e2uh patchelf@0.9

-- linux-rhel7-x86_64 / gcc@6.4.0-1 -----------------------------
j52vdz2 patchelf@0.9

==> Do you want to proceed? [y/n] y
==> Regenerating lmod module files
==> 	WRITE: patchelf@0.9%gcc@4.8.5 arch=linux-rhel7-x86_64 /xuekuii [/home/gartung/spack/share/spack/lmod/linux-rhel7-x86_64/Core/patchelf/0.9-xueku.lua]
==> Reading config file /home/gartung/spack/etc/spack/compilers.yaml
==> 	WRITE: patchelf@0.9%gcc@6.4.0 arch=linux-rhel7-x86_64 /u54e2uh [/home/gartung/spack/share/spack/lmod/linux-rhel7-x86_64/gcc/6.4.0/patchelf/0.9-u54e2.lua]
==> Warning: Could not write module file [/home/gartung/spack/share/spack/lmod/linux-rhel7-x86_64/gcc/6.4.0/patchelf/0.9-u54e2.lua]
==> Warning: 	--> Compiler configuration contains entries with duplicate specification (gcc@6.4.0, linux-rhel7-x86_64) in the following files:
	/home/gartung/spack/etc/spack/compilers.yaml: 2 times <--
==> 	WRITE: patchelf@0.9%gcc@6.4.0-1 arch=linux-rhel7-x86_64 /j52vdz2 [/home/gartung/spack/share/spack/lmod/linux-rhel7-x86_64/gcc/6.4.0-1/patchelf/0.9-j52vd.lua]

**Comment by gartung** [comment]
@tgamblin  Who was the other person I am supposed to ping?

**Comment by gartung** [comment]
I see that it is @alalazo

**Comment by gartung** [comment]
@tgamblin I think the issue is related to this warning:
==> Warning: --> Compiler configuration contains entries with duplicate specification (gcc@6.4.0, linux-rhel7-x86_64) in the following files:
/home/gartung/spack/etc/spack/compilers.yaml: 2 times <--

spec.compiler is used in the lmod generation and is returning multiple versions because gcc@6.4.0-1 is truncated to gcc@6.4.0 somewhere.

**Comment by gartung** [comment]
I see that CompilerSpec differentiates compiler versions by the information returned from gcc --version and not the version specified in compilers.yaml.

**Comment by gartung** [comment]
Seems as though is not possible by design:

       # CompilerSpec does not have an hash, as we are not allowed to
       # use different flavors of the same compiler

https://github.com/spack/spack/blob/27b1069e0c392dbd709700e30cd51f95ae9ed84f/lib/spack/spack/modules/lmod.py#L236

**Comment by alalazo** [comment]
Seems a duplicate of #7502

**Comment by gartung** [comment]
#7502 closed
