### ISSUE TITLE
Invalid spec query resolution

### ISSUE THREAD

**Issue by v-dobrev** [spack/spack#7705]
I found an issue in the package `netlib-lapack` that may affect other packages as well.

The issue appears when `netlib-lapack` is configured with `+external-blas`: in that case the install method performs the spec query `spec['blas'].libs` here:

https://github.com/spack/spack/blob/dc8c8311c6d1c2f8989b0bac89176d48dcb59a41/var/spack/repos/builtin/packages/netlib-lapack/package.py#L163-L167

which due to incorrect resolution ends up calling `netlib-lapack`'s own `blas_libs` property which is incorrect. The incorrect resolution happens here:

https://github.com/spack/spack/blob/dc8c8311c6d1c2f8989b0bac89176d48dcb59a41/lib/spack/spack/spec.py#L2765-L2772

and it is due to the fact that `x.package.provides(name)` does not check any `when` conditions from the `provides` directives - in this case `netlib-lapack` provides `blas` only when the `external-blas` variant is disabled.

**Comment by adamjstewart** [comment]
@davydden @alalazo

**Comment by davydden** [comment]
it's bug, no idea how to fix it though. The package that is being installed should be excluded from possible providers.

**Comment by adamjstewart** [comment]
Hmm, we already have:
```python
provides('blas', when='~external-blas')                                     
provides('lapack')    
```
in the package.

**Comment by davydden** [comment]
> we already have

hm, true. Should work then ;-)
