### ISSUE TITLE
Must activating an activated package be an error?

### ISSUE THREAD

**Issue by hartzell** [spack/spack#7750]
I have a script that I run that installs all of the things that I want.  With a bit of care (e.g. not re-adding compilers) it's safe to re-run it.  My normal MO is to just add new packages to the list and fire it up, things that are already built are simply skipped over.

Now that `aspell6-en` is an extension of `aspell` I activate it as part of the script.  If I re-run the script it fails when it tries to activate it a second time:

```
-bash-4.2$ bin/spack-install.sh
==> aspell6-en is already installed in /home/hartzell/spack/opt/spack/linux-centos7-x86_64/gcc-5.5.0/aspell6-en-2017.01.22-0-2dh6xidgk2ucjcs32uc3t7pak34kl5sy
==> Error: Package aspell6-en/lc4v24f is already activated.
```

I'd like a way to 

- activate a package without causing an error if it's already activated;
- ask is a package is activated so that I can avoid reactivating it; or
- some other mechanism to have a script run idempotently.

**Comment by healther** [comment]
I'd vote for a "I know what I'm doing be quiet `spack`" flag rather than removing the error. It's likely that activating an already activated package isn't what the user intended to do.

But in general it might be useful to implement a more interactive mode of spack, i.e. instead of failing on an exception ask the user whether she wants to ignore it.

**Comment by adamjstewart** [comment]
I'd vote for removing the error altogether. This is in line with how `spack install` works. Like @hartzell, I frequently wrote scripts that would loop through a set of packages and `install` + `activate` all of them.

We should still have some output of course. Something like "foo is already activated", just like the current "foo is already installed" message. But it shouldn't have an exit code of 1.

**Comment by hartzell** [comment]
@healther -- `-f` doesn't help:

```
-bash-4.2$ ~/spack/bin/spack activate aspell6-en
==> Error: Package aspell6-en/lc4v24f is already activated.
-bash-4.2$ ~/spack/bin/spack activate -f aspell6-en
==> Error: Package aspell6-en/lc4v24f is already activated.
-bash-4.2$ echo $?
1
```
