### ISSUE TITLE
How can I manually edit spack view stuff?

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#7856]
Manually removed a spack view, spack still thinks view is there. How can I refresh spack view records or manually edit them? If so where are they?

Thanks.

**Comment by adamjstewart** [comment]
Have you tried `spack view remove`? I've never used `spack view` before so idk how much I can help.

**Comment by Sinan81** [comment]
Yep, definitely tried that but it didn't work for some reason so i decided to manually remove stuff manually.

**Comment by healther** [comment]
there is a `.spack` folder in the views. You may want to look there. But we use views in a strictly increasing fashion, when there is need to remove stuff we typically remove the whole view and recreate it afterwards. As such I never used `spack view remove` maybe @scheibelp knows more.

**Comment by scheibelp** [comment]
> Manually removed a spack view, spack still thinks view is there.

Could you mention

* What you removed
* What command you ran that didn't work

Thanks!

**Comment by Sinan81** [comment]
Thanks.

Removing ~/.spack stuff enables a fresh start. It would be useful if this is mentioned in the docs. Also in the docs, I couldn't find examples of how to remove views. It took me a while to figure out what spec in "spack view remove path spec" should be.

I was trying to remove the view in a hurry, so didn't keep track of the details of the error. next time I will provide the error message and debug information.

This ticket can be closed.

Thanks you all for your help!
