### ISSUE TITLE
Stub Packages

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7869]
@tgamblin @scheibelp @adamjstewart 

The problem here is... suppose person A has put some work into getting a package P to build.  For whatever reason, A abandons that work before it is able to be merged into Spack.  Sometime later, person B arrives, wanting that package.  *How can person B reliably be made aware of A's efforts before re-doing them??*

**Proposed Solution**: When A abandons the effort, close the PR.  In place of the real PR, merge a dummy package for P into Spack.  When someone tries to concretize with that dummy package, it would explain it is a dummy package, point to the now-closed PR with the real package's efforts, and suggest the user continue that work.

This convention could be used immediately for `ghc` and `galahad`, and probably more.  It is good because (a) it would be more reliable that what we have today at avoiding duplicate work, and (b) it would close down PRs that are not actively being worked on.

**Comment by alalazo** [comment]
Closing this as stale. Please reopen if you want to continue discussion.
