### ISSUE TITLE
Intel 2017.0.5 Stuff

### ISSUE THREAD

**Issue by jrood-nrel** [spack/spack#7871]
I was going to make a pull request that included Intel 17.0.5 stuff, but I don't understand how to get the url for the downloads correct. It looks like @davydden recently added 18.0.2, so I'm just requesting 17.0.5, or help with the urls 🙂

**Comment by davydden** [comment]
> get the url for the downloads correct

i get it from Intel's download page, but unfortunately I don't have it bookmarked as I usually just follow the link in e-mail.

**Comment by jrood-nrel** [comment]
So I might be confused anyway. It looks like the 2017.0.5 is there for the cluster edition, but maybe there isn't for intel-mkl and intel-mpi?

**Comment by mgsternberg** [comment]
The 2017 standalone MKL and MPI packages were released by Intel as 2017.0 through 2017.4 only (see snippets attached). All except MPI 2017.0 are present in the current `intel-mkl` and `intel-mpi` packages in the current `develop` branch.

The omnibus "Parallel Studio" product was, curiously, released _more often_, as 2017.0 through 2017.6, of which .0 through .5 is present in `develop` as well, along with a subset of the 2015 and 2016 releases.

![mkl releases](https://user-images.githubusercontent.com/31289496/39214748-1cff7bd8-47db-11e8-9e4a-910b7c957573.png)
![mpi releases](https://user-images.githubusercontent.com/31289496/39214749-1d0c1410-47db-11e8-8fd0-44b3f4f8a6b5.png)
![studio releases](https://user-images.githubusercontent.com/31289496/39215334-103c78fe-47dd-11e8-81a5-7dab6d65f4a2.png)

**Comment by jrood-nrel** [comment]
Thanks @mgsternberg ! So it appears Spack is up-to-date then. I was just confused and that means this issue is resolved. 👌
