### ISSUE TITLE
Spack Environments: Bogus Repos Change Hashes

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7878]
Consider the following Spack Environments example.  (I know, it's hacked.  Both with extra printout, and the '-f' (force) option, which re-concretizes everything).

The point is... when we re-concretize, the hash *of our single spec* changes!  Digging down, I discovered that is because a new `Repo` associated with the environment is added to the `RepoPath` (`spack.repo`) the second time and not the first.  When things are re-concretized, the new `Repo` (`foo`) is used for the spec instead of the `builtin` repo.

This is wrong in two ways:
1. The repo shouldn't change when one re-concretizes.
2. A spec should have the same hash whether it was concretized as part of an environment, or not.  Otherwise, there can never be any sharing of builds between environments, and you might as well have a separate Spack instance for each environment!

Questions:

1. What is the purpose of this design?  (I surmise it has something to do with saving the packages that were actually used to concretize, in a new environment?  In that case... if hashes are to remain stable, packages in the new environment have to have the same "environment" as packages in the original.)

2. What do you think is the best way to fix it?  For now, I'm going to disable calls to `prepare_repository()`.

Thanks!
-- Elizabeth

```
$ rm -rf /home2/rpfische/spack6/var/spack/environments/foo
$ spack env foo create; spack env foo add zlib
$ spack env foo concretize -f
==> Using config scope at /home2/rpfische/spack6/var/spack/environments/foo/config
('spack.repo', <class 'spack.repository.RepoPath'>, [[Repo 'foo' at '/tmp/tmptVmVZT/repo'], [Repo 'builtin' at '/home2/rpfische/spack6/var/spack/repos/builtin']])
repo_for_pkg(zlib) = builtin
('yaml_text', '{zlib: {version: 1.2.11, arch: {platform: linux, platform_os: centos7, target: x86_64}, compiler: {name: gcc, version: 4.9.3}, namespace: builtin, parameters: {optimize: true, pic: true, shared: true, cflags: [], cppflags: [], cxxflags: [], fflags: [], ldflags: [], ldlibs: []}, concrete: true}}\n')
('dag_hash', 'qln4wqdtm7blidunpoi4ceut6w6pcspj', 'qln4wqdtm7blidunpoi4ceut6w6pcspj')

$ spack env foo concretize -f
==> Using config scope at /home2/rpfische/spack6/var/spack/environments/foo/config
('spack.repo', <class 'spack.repository.RepoPath'>, [[Repo 'foo' at '/tmp/tmpVKSbjU/repo'], [Repo 'builtin' at '/home2/rpfische/spack6/var/spack/repos/builtin']])
repo_for_pkg(zlib) = foo
('yaml_text', '{zlib: {version: 1.2.11, arch: {platform: linux, platform_os: centos7, target: x86_64}, compiler: {name: gcc, version: 4.9.3}, namespace: foo, parameters: {optimize: true, pic: true, shared: true, cflags: [], cppflags: [], cxxflags: [], fflags: [], ldflags: [], ldlibs: []}, concrete: true}}\n')
('dag_hash', '5py2eqrfedid3tn6enw76cxu6py7z3i5', '5py2eqrfedid3tn6enw76cxu6py7z3i5')
```

**Comment by citibeth** [comment]
BTW... I really want to be able to re-concretize without having to destroy and re-do the whole environment.  Typical example:

1. Create env
2. Add some packages to env
3. Concretize
4. Inspect the concretization.
5. Oops!  I've got the wrong version of Python there!
6. Edit `env/config/packages.yaml` as appropriate.
7. Re-concretize
..etc...
100. Now that everything looks good, type `spack env foo install` and go have a cup of coffee!

**Comment by scheibelp** [comment]
Note: this is referring to functionality which only exists in https://github.com/spack/spack/pull/7843 (and is not yet part of Spack)

**Comment by scheibelp** [comment]
> Consider the following Spack Environments example.

@citibeth is the example missing?

**Comment by scheibelp** [comment]
> The point is... when we re-concretize, the hash of our single spec changes!

@citibeth Is this inherently wrong? I'm assuming that the change is the repo namespace (and that otherwise the specs are exactly the same). If you reconcretize from a set of user specs, it would not be guaranteed to preserve the hash anyhow (and in fact that would be one of the main reasons to reconcretize IMO).

**Comment by citibeth** [comment]
@scheibelp @tgamblin 

> @citibeth is the example missing?

It's at the bottom of the first post

> I'm assuming that the change is the repo namespace (and that otherwise the specs are exactly the same).

yes

> The point is... when we re-concretize, the hash of our single spec changes!

@citibeth Is this inherently wrong? 

> If you reconcretize from a set of user specs, it would not be guaranteed to preserve the hash anyhow (and in fact that would be one of the main reasons to reconcretize IMO).

If you reconcretize the same user specs with the same version of Spack, it should produce the same hashes.  I can see at least two reasons to re-concretize:
1. Upgraded to a new version of Spack, want to make use of new packages.
2. Fiddled with `packages.yaml`, want the changes to take effect.

I believe that (2) is going to be MUCH more common than (1).  Under the current regime, a user's experience could be as follows:

1. Build a whole environment
2. Change a single default version in `packages.yaml`
3. Re-concretize; and now watch as the ENTIRE environment is needlessly re-built.

Once this first environment-wide change of hashes is complete, hashes will be stable going forward.  However, and unfortunately, those hashes will not be shared with equivalent specs in other environments, or in "plain" specs outside of an environment.  Which kind of defeats one of the big purposes of Spack, IMHO, which is the sharing of builds between projects.

**Comment by citibeth** [comment]
OK, I commited a "fix" to the problem at  b4f3253a.  I expect this "fix" is temporary, and will probably be reverted and re-done.  However, I believe any permanent fix must have the following properties:

1. If Spack is unchanged and configs are unchanged, then `spack env concretize` should always give the same hashes.

2. `spack env concretize` should give the same hash as `spack spec` for the same user-spec with the same configs.

**Comment by scheibelp** [comment]
> Which kind of defeats one of the big purposes of Spack, IMHO, which is the sharing of builds between projects.

The main reason I create an environment-specific repository is to support this: if the spack versions for two users differ at all then the spack repositories used by each may differ. This could for example happen because the users pulled "develop" at different times, but may also differ in terms of additional commits made by users.

Perhaps this is best addressed with a different method. For example a utility script could be provide to package up the Spack repository itself along with the environment. This may have its own set of peculiarities though.

**Comment by scheibelp** [comment]
I should say: regardless of whether it remains desirable to maintain an environment-specific package repository, there could always be an option to disable it if that is required for your use case (or even if it is just convenient).

**Comment by citibeth** [comment]
In principle, I think the env-specific repository is a good feature and doesn't need to be disabled for certain use cases.  I just think we haven't quite figured out the right way for it to work yet.  But once we do, I think it will be great.

I really like the idea that I could create an environment, send it to you, and have it build as much the same as possible.  Even if we have different versions of packages in our Spacks.

**Comment by citibeth** [comment]
We have a decent handle on this issue, so I'm closing.
