### ISSUE TITLE
Many r packages are out of date

### ISSUE THREAD

**Issue by mcneish1** [spack/spack#7891]
## Please note that everything still works, as list_url is used to find the old versions. I have not checked to see if all r packages have list_url specified, however

Related: #2951

cran.r-project.org places latest versions of things in a different directory than archived versions. For example:

r-bh 1.65.0-1 used to be located at https://cran.r-project.org/src/contrib/BH_1.65.0-1.tar.gz, but it is now located at https://cran.r-project.org/src/contrib/Archive/BH/

The current version, r-bh 1.66.0-1, is only located in https://cran.r-project.org/src/contrib/ and not https://cran.r-project.org/src/contrib/Archive/BH/

This affects (at least) the following packages:
r-backports
r-checkmate
r-digest
r-lazyeval
r-mass
r-stringi
r-stringr
r-reshape2
r-viridislite
r-tibble
r-xml
r-httpuv
r-testthat
r-bh
r-plogr
r-bindrcpp
r-dbi
r-hexbin

---

Instead of separate package.py files for everything listed in cran.r-project.org, would it be possible to integrate with their distribution system directly? By this, I mean:
`spack install r-a`
would look for https://cran.r-project.org/src/contrib/a_.*.tar.gz for the most recent version and https://cran.r-project.org/src/contrib/Archive/a for older versions and (somehow) automatically pull out dependencies

If that direct use of https://cran.r-project.org/src/contrib/ isn't what you want in spack, could you instead write a script to periodically crawl it and generate package.py files for everything there?

Thanks

**Comment by citibeth** [comment]
> would it be possible to integrate with their distribution system directly?

Yes, see #1249.

> could you instead write a script to periodically crawl it and generate package.py files for everything there?

Yes, that is also possible.  Or you could update the packages you use.  In any case, PRs are appreciated.
