### ISSUE TITLE
Openblas 0.2.20 build error

### ISSUE THREAD

**Issue by leffetripel** [spack/spack#7897]
System is CentOS 7 

I am trying to install Openblas but getting this error no matter what version.
>  /usr/local/include/complex.h:10:1: error: unknown type name ‘using’

As I understand the gcc compiler is thinking the code is c rather than cpp. 
spack-build.out included. 

[pastebin](https://pastebin.com/hm3fjZsA
)

**Comment by citibeth** [comment]
What version compiler are you using?  It sounds to me like an out-of-date C++ compiler.
