### ISSUE TITLE
Spack Environments 3.0: How they should REALLY work

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7944]
@scheibelp @tgamblin 
The ideas in this Issue might get implemented, but only after the current Environnments PR (#7843) is merged.

Rather than a `spack env` command that increasingly duplicates much of Spack, Environments should be integrated into existing Spack commands.  The following commands could be "environmentized": find, all "build packages" commands, all "environment" commands (in spack help --all), module.

Commands would be run with an environment in maybe one of a few ways:
 1. `spack --env <env> command ...` --- works for all commands, but only makes a difference for commands where it makes sense.
 2. `SPACK_ENV=<env> spack command ...` --- get the current Spack env out of an env var, but otherwise similar to (1).  Nothing else is done in Spack this way, so probably not what we want.
 3. `spack command --env <env>` --- Add the `--env` flag only for commands where an environment makes a difference.
  4. Don't use any global env specifier; instead, get the required env from the specs on the command line (see below).

Suppose we have an Environment with user specs `aa`, `bb` and `cc` added to it. Then the following conventions (or something like them) can be used anywhere a spec is asked for on the command line:
1. `env:aa` refers to the `aa` user spec in the current environment.  If `aa` has been concretized, then it will be replaced with the concretized version of `aa` in the env.  NOTE: This is different from just `aa`, which does an immediate concretization.
2. `env:` expands to all user specs in env.
3. `env:aa:` expands to all specs in the `aa` DAG.
4. `env:aa:xx` refers to a spec matching `xx`, which is in the DAG of the concretized `aa` user spec.  This kind of control allows us to easily debug, rebuild, etc. individual problem packages within an environment.
5. `env::xx` refers to a spec matching `xx` anywhere in any DAG in the concretized environment.
6. `env::` expands to ALL SPECS in the environment.

IN general:
1. Anything wanting an environment has no colons.  Eg: `myenv`
2. Anything wanting a user spec, or list of user specs, or top spec in a DAG, has one colon.  Eg: `myenv:aa` or `myenv:`
3. Anything wanting any spec has two colons.  Eg: `myenv:aa:openblas`.

`spack install` would work as it currently does: it concretizes and installs all in one.  `spack install` w.r.t an env would add the user spec to the env, concretize it and then build ("install") it.  For example, `spack install c1:emacs` would add `emacs` to the `c1` environment, concretize it, and then install.

`spack add` adds user specs to an environment.  Eg: `spack add c1:emacs`

`spack concretize` concretizes one or more user specs.  Eg: `spack concretize c1:` or `spack concretize c1:aa`

`spack build` builds ("install") concretized specs in an environment (concretizing them if not already).  Eg: `spack build myenv:`, `spack build myenv:aa`, `spack build myenv:aa:openblas`.

Thus, `spack install` is equal to `spack add` + `spack concretize` + `spack build`.

`spack location`, `spack find`, `spack load`, `spack module loads` can now be used to find installed packages in a deterministic manner.  (Thus, they are no longer "broken" as a reliable way to obtain hashes of stuff you've built and now want to use).  Eg:
```
spack load -r myenv:aa   # Loads all modules in myenv:aa DAG
spack location -i myenv::openblas   # Finds the (hopefully 1) openblass in myenv
spack module loads -r myenv:   # List all modules needed to load myenv
```

Note that `spack activate` should not be used with environments.  You need to either use `spack module loads`, or `spack view`.

Thoughts?

**Comment by scheibelp** [comment]
Pointer: the current environments PR is at https://github.com/spack/spack/pull/7843

**Comment by citibeth** [comment]
[Write-up taken from the Spack mailing list]

My analysis of this situation is that Spack has many ways of doing some things; and for Python (or anything other than C/C++/Fortran), most of them are broken.  Not only that, but the most broken ways are most heavily promoted in the documentation.  I would say you have managed to try all the broken ways and observe that they don't work, while not trying the few ways that DO work.

The short answer, as Peter Scheibel said, is that Python Envrionments do what you want in a non-broken way (more on that below).  `spack module loads` is also half-non-broken.  There is zero need for Python virtualenvs.

Here's the long answer:

What Doesn't Work
===============

a) `module load` all kinds of things by trial and error,

Non-recursive `module load` is broken (as an end-user command) because it only does something useful for packages with no runtime dependencies; meaning, it is only useful for packages built with RPATH.  It is particularly NOT useful for Python environments.

`spack load` is even more broken.  In addition to having all the problems of `module load`, it is also non-deterministic; and can fail depending on what ELSE (other than what you want to load) happens to be installed in Spack.  `spack load` also does an unnecessary concretization in `.bashrc` and is therefore unnecessarily slow when it needs to be fast.
 
b) jiggling `modules.yaml` to generate modules that autoload All The
   Things and hope nothing goes wrong or

`modules.yaml` is broken, as a way to auto-load dependencies is broken because it requires users to add "customized" information that should have been encoded by the Package creator.

It is my belief that Spack packages should know what other packages' modules they need loaded to run.  For example, Python packages generally load modules for all their `run` dependencies, CMakePackages do not.  This information should be encoded as in intrinsic part of the package.py, and used when generating modules that properly load their dependencies.  The user should be able to turn this on with a simple switch; mucking around with multiple settings in `modules.yaml`, and auto-loading everything, should not be required.

It turns out, this opinion produced some vociferous disagreement.  I did not push it further, mainly because I had other ways to do what I needed that get the job done for me:  https://github.com/spack/spack/pull/3134

c) just activate the package and be done with it (and hope that nothing goes wrong).

By way of exampke, I just realized I should have flake8'ed a PR, so
ran `spack install py-flake8` and `spack load py-flake8` but when I
`spack flake8`-ed it exploded.  `spack activate py-flake8` allowed it to
work and when I `spack deactivate py-flake8` to try to see what was
going wrong it *still* worked, so blech.

`spack activate` is broken because it violates a fundamental assumption of Spack: that installed packages with the same hash are the same.  Once you start symlinking things into your Spack `python` installation, this is no longer the case, and it negates some of the main benefits of Spack --- for example, the ability to use one `python` install to work with different configurations of Python libraries.

So no surprise that you are having problems with `spack activate`.  I am close to putting together a Spack Dev environment, which will provide Spack developers with access to `flake8`, Sphinx, and other basic tools needed to work with Spack code.  But first we need to merge https://github.com/spack/spack/pull/8231

What Works Now
=============

In today's Spack, `spack module loads --dependencies` is the only reliable way to get your Python working consistently.  It still has the problem that it Loads The Whole World.  But it should generally work.

http://spack.readthedocs.io/en/latest/module_file_support.html

`spack module loads` suffers from the same problem of indeterminism than `spack load`.  But other than that it is mostly non-broken.

`spack view` is semantically equivalent to `spack module loads`; but instead of generating a list of modules to load, it symlink the required packages into a single tree.  Either way works.

What Works Real Soon Now

Peter is right, Spack Environments do what you want, and do so reliably.  I am using them to generate scripts of `module load` commands that correctly load dependencies.  The command you need is:
    spack env <envname> loads -r

You can use Spack Environments today, they are awaiting final merge:
    https://github.com/spack/spack/pull/8231

I point to an real-world example of Spack Environments in that PR thread as well.

What I Want
==========

I want Spack Environments to "generate" their environment in one of two ways:

1. Generate a single module, named after the environment, that sets all env vars required by the environment.  This is semantically equivalent to today's `spack env <envname> loads -r`; but advantages would be:
   a) No need to generate and manage a separate env loading script.  Users could just put this in their .bashrc file:
           spack env <myenv> load
   b) Even if a separate env loading script is generated, it will still load a LOT faster than running 100 individual module load commands.
   c) We can do away with individual module files with cryptic hashes in their names.  The modules loaded by users are meaningful to users --- because they're named after environments.
   d) There is no chance of failing to load dependencies.  A single `module load` on the generated environment module file would work.

2. Build a Spack View of the environment.  This would be most similar to virtualenv in the end; except it works for ALL kinds of packages, not just Python.

**Comment by citibeth** [comment]
@hartzell You might be interested in participating in this thread (please look at it on GitHub).

**Comment by healther** [comment]
> spack view is semantically equivalent to spack module loads; but instead of generating a list of modules to load, it symlink the required packages into a single tree. Either way works.

One comment here: We introduced `view` initially to speed up the finding of executables in case of a slow nfs-filesystem and a large number of packages (i.e. entries in `PATH` and co.). What we never got around to was to add the module-generation to these into spack (currently we have Jenkins deploy a "handwritten" module).
My point is this: While environments will essentially do what I expected (and still somewhat expect) `spack load` to do, I would still like to see a view implementation of them, as our initial problem was the slowness of opening 100s of `../bin` folders. 

Aside from that nitpick, I very much appreciate all the work that went into environments

**Comment by citibeth** [comment]
> I would still like to see a view implementation of them [Spack Environments]

I believe that's point (2) of "What I Want" above.  But there can be No New Features of Spack Environments until the current PR is merged.

**Comment by tgamblin** [comment]
Given that environments have been merged for 2 releases now with various innovations on these features, I'm closing this.
