### ISSUE TITLE
PETSc: MPI configuration not stored properly

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7953]
@BarrySmith @jedbrown @ckhroulev

Summary
---------

PISM fails to configure because PETSc has not stored path to MPI in its configuration files.  This is probably caused by a change in the Spack package; specifically the loss of the `--with-mpi-dir` flag from https://github.com/spack/spack/commit/d04ae9a2.

Details
--------

When PETSc builds, it creates a file `<prefix>/lib/petsc/conf/petscvariables`, containing a number of key-value pairs describing the PETSc installation.  This file is later read and relied upon by some programs that use PETSc; PISM, for example:
   https://github.com/pism/pism

PISM's CMake build looks up the PETSc variable `PETSC_CC_INCLUDES`:
   https://github.com/pism/pism/blob/master/CMake/FindPETSc.cmake#L159

It then uses this variable to construct correct command lines for small test programs used to deduce the configuration of PETSc:

https://github.com/pism/pism/blob/b17bcd0c0bce5720736e2dad8317a8c9cd7b5706/CMake/FindPETSc.cmake#L265

The Problem
-------------

At the point in the PISM CMake build where test programs are compiled, the variable `${includes}` needs to contain an `-I` flag for MPI (in my case, OpenMPI).  However, it does not.  This is traced back to `PETSC_CC_INCLUDES` not containing a `-I` flag for MPI in the PETSc file `petscvariables` (above).

It is believed that OpenMPI is not showing up in `PETSC_CC_INCLUDES` because the Spack package no longer proviedes PETSc with the flag `--with-mpi-dir` as of https://github.com/spack/spack/commit/d04ae9a2.

Proposed Fix
---------------

I will try restoring  `--with-mpi=1` and `--with-mpi-dir`, while keeping `--with-cc`, `--with-cxx` and `--with-fc` as well.  Thoughts from @jedbrown and @BarrySmith on possible effects this might have --- or whether there's a better way involving PETSc internals --- would be appreciated.  I will report back on what I find.

https://github.com/spack/spack/commit/d04ae9a2

**Comment by jedbrown** [comment]
Your PISM build should specify the appropriate MPI compilers, not rely on getting a working MPI as a side-effect of include statements.

**Comment by citibeth** [comment]
The PISM build is calling `multipass_source_runs()`, which is calling the CMake built-in `check_c_source_runs`:

https://github.com/pism/pism/blob/b17bcd0c0bce5720736e2dad8317a8c9cd7b5706/CMake/FindPackageMultipass.cmake#L97

How does one run `check_c_source_runs()` using `mpicc`?

https://cmake.org/cmake/help/v3.0/module/CheckCSourceRuns.html

**Comment by citibeth** [comment]
It looks like ParMETIS does this by adding a `find_package(MPI)` at a key point in their build:

https://github.com/elemental/Elemental/blob/master/cmake/modules/FindParMETIS.cmake#L111

**Comment by jedbrown** [comment]
There is no consensus about using FindMPI (feels more native, but has complicated logic and confusing failure modes) versus `CC=/path/to/mpicc CXX=/path/to/mpicxx cmake ..`. I find the latter much more reliable and it works even when the wrappers use a different compiler suite.

**Comment by citibeth** [comment]
So going on the hypothesis that the PISM build is wrong... I noticed that it is crashing inside `FindPETSc.cmake`.  I therefore copied the following in its place, figuring this should give me the best chance of working:
   https://github.com/jedbrown/cmake-modules/blob/master/FindPETSc.cmake

The results were the same.  It works with the old Spack and not the new.  Log files and CMake launch scripts included.


[CMakeOutput.log.bad.txt](https://github.com/spack/spack/files/1964124/CMakeOutput.log.bad.txt)
[CMakeOutput.log.good.txt](https://github.com/spack/spack/files/1964125/CMakeOutput.log.good.txt)
[setup-bad.py.txt](https://github.com/spack/spack/files/1964126/setup-bad.py.txt)
[setup-good.py.txt](https://github.com/spack/spack/files/1964127/setup-good.py.txt)

My current working theory is that in theory, packages using PETSc should not rely on MPI include path in `petscvariables`.  But in reality, PETSc + `FindPETSc.cmake` just doesn't work without the `--with-mpi` flags.

**Comment by jedbrown** [comment]
You should use the mpicc and mpicxx compilers. Also, I'm baffled by hard-coding these paths rather than using the API or `spack location -i`.

    env['CC'] = '/home2/rpfische/spack-tools/opt/spack/linux-x86_64/gcc-4.8.5/gcc-4.9.3-jfebnuuusdch34j7pvdnvlxffe2rmoe4/bin/gcc'

**Comment by citibeth** [comment]
On Tue, May 1, 2018 at 11:08 AM, Jed Brown <notifications@github.com> wrote:

> You should use the mpicc and mpicxx compilers.
>

Simple story is:
  (1) I don't know how to use the mpicc and mpicxx compilers in the context
of the CMake built-in *check_c_source_runs()*
   (2) the code that is failing to use mpicc and mpicxx was taken directly
from here, and I would have expected it to follow your recommendations:
   https://github.com/jedbrown/cmake-modules/blob/master/FindPETSc.cmake


> Also, I'm baffled by hard-coding these paths rather than using the API or spack
> location -i.
>
You're looking at a Spack-generated script.

**Comment by jedbrown** [comment]
You need to use `mpicc` (`mpicxx`) for all of PISM, not just for that one test (which uses whatever compiler has been configured -- and you wouldn't want it any other way). If you're writing a Spack file for PISM, then it should depend on MPI.

**Comment by ckhroulev** [comment]
Like @jedbrown said: please use `mpicc` and `mpicxx`.

I agree that this is a @pism bug (I'd say that this is a *documentation* bug: I need to clearly document how to build it with `mpicc` and `mpicxx`). (I've spent way too much time dealing with `FindMPI.cmake` finding the wrong thing to go back to using it in PISM.)

Running CMake like this `CC=/path/to/mpicc CXX=/path/to/mpicxx cmake ...` (i.e. defining environment variables `CC` and `CXX` for it) would make it use `mpicc` and `mpicxx` for this build, including in `check_c_source_runs()` and such. (Selecting a compiler for each language in the project is one of the first things CMake does and this decision cannot be changed: the same compiler is used for *everything*. As far as I cal tell this is why `check_c_source_runs()` does not have the compiler as an argument: you cannot start with `gcc` and then use `mpicc` to check for MPI.)

**Comment by citibeth** [comment]
@jedbrown @ckhroulev Thank you for your help.  Two wrongs don't make a right, but sometimes they do make things build.  Now I have two rights, I've added appropriate '-DCMAKE_C_COMPILERS=mpicc' flags to the PISM build:

https://github.com/spack/spack/pull/7863/commits/d8354b27ad173e6312ceaeecb807c184ec941780
