### ISSUE TITLE
openmc: needs an update

### ISSUE THREAD

**Issue by junghans** [spack/spack#7965]
Our `openmc` package points to https://github.com/ANL-CESAR/openmc, which is " 5 commits ahead, 5035 commits behind mit-crpg:develop." 

So I guess, `openmc` needs an update or needs to be purged.

Also looking at the size, I am not sure if `openmc` is a proxy app anymore.

/cc @paulromano @shikhar413

**Comment by citibeth** [comment]
Can you submit a PR?

**Comment by paulromano** [comment]
The proper repository to use is mit-crpg/openmc, not the ANL-CESAR fork. OpenMC is not a proxy app.

**Comment by junghans** [comment]
> Can you submit a PR?

I tried, but the build system has changed!

**Comment by junghans** [comment]
It is CMake now, but I couldn't get it to pick up Spack's HDF5. 

@pkondamudi wrote the original package!

We found that the current version in spack triggers an internal compiler in gfortran-7.1, details here: https://travis-ci.org/proxyapps/proxy-ci/jobs/373526711.

**Comment by paulromano** [comment]
I would be happy to submit a PR updating it, but probably won't be able to get to it for a while. @junghans OpenMC will look for HDF5 using the `HDF5_ROOT` environment variable if set, so that's one thing you might want to try.

**Comment by junghans** [comment]
> I would add a constraint to the package of %gcc@:6.9999 or whatever...

No need old version will get removed.

**Comment by junghans** [comment]
@paulromano see #7974, do a PR against the `bugfix/openmc` branch you want to add more fixes.
