### ISSUE TITLE
How to handle interactive configure?

### ISSUE THREAD

**Issue by weijianwen** [spack/spack#7983]
Some package, for example [WRF](https://www.mmm.ucar.edu/weather-research-and-forecasting-model) requires answering questions interactively during `./configure` to generate a proper config file.  EasyBuild 'emulates' to answer questions during configure http://easybuild.readthedocs.io/en/latest/Typical_workflow_example_with_WRF.html . I wonder how to  do it in Spack.

**Comment by adamjstewart** [comment]
Ah, [the dreaded WRF](https://www.youtube.com/watch?v=NSemlYagjIU). There are a few packages in Spack similar to this. Check out `fpc`, `ncl`, `perl-bio-perl`, `perl-io-socket-ssl`, `perl-net-ssleay`, `repeatmasker`, and `snphylo`. If you think there is too much repeated code here, we could consider adding a base class for interactively installed programs.

Aside from that, I like to see how other package managers install it.

### Homebrew
This looks too simple to actually work...

https://github.com/csdms/homebrew-models/blob/master/wrf.rb

### EasyBuild
It looks like there are some environment variables you can set, but you still need a way of answering questions interactively.

https://github.com/easybuilders/easybuild-easyblocks/blob/master/easybuild/easyblocks/w/wrf.py

**Comment by citibeth** [comment]
Here's another on that I did in Spack:
https://github.com/citibeth/spack/edit/efischer/180422-GALAHAD/var/spack/repos/builtin/packages/galahad/package.py?pr=/spack/spack/pull/7864
```
        with open('build_input.txt', 'w') as fout:
            fout.write('y3\nc\n6\n2\nn2\nn3\nnyydydy')
            fout.write('\n')

        install_optsuite = Executable(os.path.join(
            spec['archdefs-src'].prefix, 'install_optsuite'))

        with open('build_input.txt', 'r') as fin:
            try:
                install_optsuite(input=fin)
            except Exception as e:
                tty.warn('Ignoring error while building' +
                         ' (this is normal): %s' % str(e))
```

**Comment by MichaelLaufer** [comment]
This has been resolved in the WRF Spack package.
