### ISSUE TITLE
package that depends on nvidia-smi

### ISSUE THREAD

**Issue by fanne-stat** [spack/spack#8013]
I am trying to create a package that needs nvidia-smi during installation. Since it is part of the nvidia driver, how can I specify this dependence in spack?

**Comment by weijianwen** [comment]
Is it a in-house developed code? Since `nvidia-smi` is shipped with NVIDIA driver which is not managed by Spack, I'm afraid that `nvidia-smi` cannot be specified as a dependency in this case. A workaround is to always install NVIDIA driver before building your nvidia-smi-dependent package in Spack.

**Comment by weijianwen** [comment]
Another workaround is to try NVIDIA Management Library (NVML, shipped with CUDA) https://developer.nvidia.com/nvidia-management-library-nvml and tools built on it (https://github.com/jonsafari/nvidia-ml-py), whcih emulates features of nvidia-smi. Still, running NVML apps requires proper NVIDIA driver being setup, whcih is beyon the reach of Spack.

**Comment by fanne-stat** [comment]
Is there a way to write the recipe to check the existence of `nvdia-smi` in the machine when runing `spack install` and abort the installation when it does not exist?

**Comment by weijianwen** [comment]
I think you can place the checking in places like `edit()`, `patch()`,  `build()` or `install()`. Emitting a `SpackError` exception will terminate the installation proces.

**Comment by jcftang** [comment]
AFAIK nvml is  shipped with cuda these days

**Comment by adamjstewart** [comment]
I think this issue can now be closed, the solution is to add a dependency on cuda.
