### ISSUE TITLE
Use GitHub's API endpoint for fetching a git snapshot.

### ISSUE THREAD

**Issue by citibeth** [spack/spack#8017]
@skosukhin 
This job is analogous to #7881, but for GitHub.

GitHub snapshots can be fetched with URLs like:
```
    https://github.com/<org>/<repo>/archive/<ref/tag>.tar.gz
```

**Comment by alalazo** [comment]
Closing as stale. Also pinging @adamjstewart as our URL expert :smile:  Feel free to reopen if you want to continue the discussion on this point.
