### ISSUE TITLE
Spack can't create modules

### ISSUE THREAD

**Issue by Irekporeb** [spack/spack#8019]
Hi,
 
I am using spack 0.11.0 with OpenHPC which i resently upgraded form 0.10.0

There is a problem with module refresh. I am not sure how to fix that. 

# spack -d -v  module refresh -m tcl
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Released]
==> You are about to regenerate tcl module files for:

-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
pj7haun cmake@3.10.1  5igtfs5 fftw@3.3.7      ctwvb2m hwloc@1.11.8         qpmaxx6 libsigsegv@2.11  p7wmc5o libxml2@2.9.4  zxqghp3 ncurses@6.0    cibkbry openssl@1.0.2n  p66qdrt util-macros@1.19.1  64vg6e4 zlib@1.2.11
jdm3sce cuda@9.1.85   2takbct gromacs@2018.1  5chyfxo libpciaccess@0.13.5  bcbiddk libtool@2.4.6    jwvjtud m4@1.4.18      kilojbc openmpi@3.0.0  xiymx6n pkgconf@1.4.0   kgp7olc xz@5.2.3

==> Do you want to proceed? [y/n] y
==> Regenerating tcl module files
==>     WRITE: cmake@3.10.1%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-x86_64 /pj7haun [/opt/ohpc/admin/spack/0.11.2/share/spack/modules/linux-centos7-x86_64/cmake-3.10.1-gcc-4.8.5-pj7haun]
==> Warning: Could not write module file [/opt/ohpc/admin/spack/0.11.2/share/spack/modules/linux-centos7-x86_64/cmake-3.10.1-gcc-4.8.5-pj7haun]
==> Warning:    --> template 'modules/modulefile.tcl' was not found for 'TclModulefileWriter' <--
==>     WRITE: cuda@9.1.85%gcc@4.8.5 arch=linux-centos7-x86_64 /jdm3sce [/opt/ohpc/admin/spack/0.11.2/share/spack/modules/linux-centos7-x86_64/cuda-9.1.85-gcc-4.8.5-jdm3sce]
==> Warning: Could not write module file [/opt/ohpc/admin/spack/0.11.2/share/spack/modules/linux-centos7-x86_64/cuda-9.1.85-gcc-4.8.5-jdm3sce]
==> Warning:    --> template 'modules/modulefile.tcl' was not found for 'TclModulefileWriter' <--

During the installtion it has the same problem like something is missing or missconfigured.

==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Released]
==>     WRITE: pkgconf@1.4.0%gcc@7.2.0 arch=linux-centos7-x86_64 /wnrooin [/opt/ohpc/admin/spack/0.11.2/share/spack/modules/linux-centos7-x86_64/pkgconf-1.4.0-gcc-7.2.0-wnrooin]
==> Warning: cannot perform the requested write operation on module files [template 'modules/modulefile.tcl' was not found for 'TclModulefileWriter']
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Released]
==>     WRITE: pkgconf@1.4.0%gcc@7.2.0 arch=linux-centos7-x86_64 /wnrooin [/opt/ohpc/admin/spack/0.11.2/share/spack/lmod/linux-centos7-x86_64/gcc/7.2.0/pkgconf/1.4.0-wnrooin.lua]
==> Warning: cannot perform the requested write operation on module files [template 'modules/modulefile.lua' was not found for 'LmodModulefileWriter']
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/lock[0:0] [Released]
==>     WRITE: pkgconf@1.4.0%gcc@7.2.0 arch=linux-centos7-x86_64 /wnrooin [/opt/ohpc/admin/spack/0.11.2/share/spack/dotkit/linux-centos7-x86_64/pkgconf-1.4.0-gcc-7.2.0-wnrooin.dk]
==> Warning: cannot perform the requested write operation on module files [template 'modules/modulefile.dk' was not found for 'DotkitModulefileWriter']
==> WRITE LOCK: /opt/ohpc/admin/spack/0.11.2/opt/spack/.spack-db/prefix_lock[6463074006111189444:1] [Released]
==> WRITE LOCK: /opt/ohpc/admin/spack/0.11.2/var/spack/stage/.lock[4765096128638590954:1] [Released]
==> Successfully installed pkgconf

### Information on your system

I am using CentOS 7.4
During the troubleshoting I modify my user modules.yaml by enabling lmod and adding core_compilers:

modules:
  enable:
    - tcl
    - lmod
    - dotkit
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  lmod:
    core_compilers:
      - 'gcc@4.8.5'
    hierarchy:
      - mpi

Thanks,
Irek

**Comment by svenevs** [comment]
It seems like some files may have accidentally been deleted?  In the top level of your `spack` directory, there should be a `templates` folder:

```console
$ spack> ls templates/modules/
modulefile.dk  modulefile.lua  modulefile.tcl
```

If those files aren't there, you may be lucky enough to just get away with re-creating them.  If you run

```console
$ git status
```

it may show that those files have been deleted somehow.  I think you can restore them with just

```console
$ git checkout HEAD -- templates/modulefile.dk templates/modulefile.lua templates/modulefile.tcl
```

or alternatively just re-create them manually by re-cloning somewhere else and copying, or just manually copy the source code from [`templates/modules`](https://github.com/spack/spack/tree/develop/templates/modules) and paste them into the correctly named files yourself.

**Comment by Irekporeb** [comment]
Hi Svenevs,

You are right these files are missing. For some reason OpenHPC remmoved these files from RPM. There are not listed there at all. 

Thanks,
Irek

**Comment by svenevs** [comment]
Very interesting.  I opened a ticket with them as I believe I found a small bug in their rpm packaging script.  I think maybe they packaged `spack` before `templates/modules` existed.

So you were able to restore module functionality?  Which method was successful?

**Comment by svenevs** [comment]
Upstream pushed a fix, don't know when that will be released. Do you still need help, it can this be closed?

**Comment by alalazo** [comment]
@Irekporeb Closing this issue. Feel free to reopen in case there's still a problem.
