### ISSUE TITLE
[feature] install option for silent download option

### ISSUE THREAD

**Issue by svenevs** [spack/spack#8030]
So this is actually a bug with `cURL` (I believe).  The question is whether it warrants a bypass in `spack`, e.g. `spack install --silent-curl <pkg>`.

**I am happy to implement this if it is desired.**

### `cURL` Bug

The progress bar can get confused sometimes, and starts spitting out a bunch of `#`'s without a carriage return.  I've experienced this locally, as well as on Travis.  Locally it usually happens through `tmux`, and only on larger archives such as OpenCV.  *Maybe it's even exclusive to downloading from GitHub*.  But it's never actually been a roadblock locally.

On Travis, though, the build can get killed:

```
==> Fetching https://github.com/Itseez/opencv/archive/3.3.0.tar.gz
######################################################################## 100.0%
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
The job has been terminated
```

**Note**: my success / failure ratio is inconsistent.  Sometimes downloading OpenCV works just fine, but when I happen to be watching the build, the time when the carriage returns disappear it will always fail.

### `spack` Code Responsible

https://github.com/spack/spack/blob/0dddb988696f3c90ea3c14c48346c265d744e2f2/lib/spack/spack/fetch_strategy.py#L249-L252

On Travis, `sys.stdout` is a `tty()`, but all of the `#` signs create issues.  The idea would be to do something like

```py
if not spack.silent_curl and sys.stdout.isatty(): 
    curl_args.append('-#')  # status bar when using a tty 
else: 
    curl_args.append('-sS') # just errors when not. 
```

and add the relevant option.

### Consequences / Considerations

- Travis will kill a job [when a job produces no log output for 10 minutes](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts).  For very large downloads, this silent option may trigger a timeout.
    - But Travis has **very** fast download times (at least in my experience).
- This is different than a `-s` for silent install which has been discussed elsewhere.  This `--silent-curl` would still print out all of the normal phases and report that it was fetching, just no progress bar with `cURL`.

--------------

FWIW I reliably succeed with this very ugly (temporary) bypass:

```console
$ cat spack/lib/spack/spack/fetch_strategy.py | sed 's/        curl_args += self.extra_curl_options/        curl_args = [arg.replace("-#", "-sS") for arg in curl_args] + self.extra_curl_options/g' > tmp_fetcher
$ cat tmp_fetcher > spack/lib/spack/spack/fetch_strategy.py
$ git -C spack/ --no-pager diff
```
```diff
diff --git a/lib/spack/spack/fetch_strategy.py b/lib/spack/spack/fetch_strategy.py
index 04e42a9f0..9f1907c97 100644
--- a/lib/spack/spack/fetch_strategy.py
+++ b/lib/spack/spack/fetch_strategy.py
@@ -251,7 +251,7 @@ class URLFetchStrategy(FetchStrategy):
         else:
             curl_args.append('-sS')  # just errors when not.
 
-        curl_args += self.extra_curl_options
+        curl_args = [arg.replace("-#", "-sS") for arg in curl_args] + self.extra_curl_options
 
         # Run curl but grab the mime type from the http headers
         curl = self.curl
```

**Comment by adamjstewart** [comment]
I've encountered this cURL bug before. See #1017. I assume someone has reported this to cURL before, I'll take a look.

**Comment by adamjstewart** [comment]
I think this bug is related to #2158 and #2163. See if you can reproduce this outside of Spack on the latest cURL release. If you can, this would definitely be worth opening a bug report for. Based on those issues/PRs, they seem to be very responsive to this sort of bug.

Either way, this is a cURL bug, not a Spack bug.

**Comment by svenevs** [comment]
> Either way, this is a cURL bug, not a Spack bug.

Agreed, however the reality is that I need `spack`  be able to deal with this.  The main idea here is that `spack` requires `cURL` to be installed and uses it.  So even if it gets fixed in `cURL`, that won't fix it for `spack`.

- Yes, `spack` can install `cURL`.
- But the system `cURL` *should be* sufficient, it's just the progress bar.  Having to install `cURL` in addition to `OpenCV` is putting an even bigger load on Travis without any real reason.

I think that it is related to the other issues, but is not a duplicate -- this prevents `spack` from being able to install things in specialized environments such as Travis.  I need to silence `cURL`, not anything else.

**Comment by svenevs** [comment]
This has already been discussed in numerous places, fetching alternatives (in python) exist and could be used instead of curl.  Marking this as #not-that-important #wontfix xD
