### ISSUE TITLE
checksum error with libjpeg

### ISSUE THREAD

**Issue by ketancmaheshwari** [spack/spack#8035]
If you want to report a build error for some package, or a bug in core please use the following template as a guideline:

-----

Summary

### Expected Result

installation of libjpeg

### Actual Result

==> Installing libjpeg
==> Fetching http://www.ijg.org/files/jpegsrc.v9c.tar.gz
######################################################################## 100.0%
==> Error: ChecksumError: md5 checksum failed for /home/km0/spack/var/spack/stage/libjpeg-9c-vucrgxb5rnyn5z2vepvhhhdh55m5vs6f/jpegsrc.v9c.tar.gz
    Expected 7794e558c60605424fb1025d836fbf47 but got 93c62597eeef81a84d988bccbda1e990
ChecksumError: ChecksumError: md5 checksum failed for /home/km0/spack/var/spack/stage/libjpeg-9c-vucrgxb5rnyn5z2vepvhhhdh55m5vs6f/jpegsrc.v9c.tar.gz
    Expected 7794e558c60605424fb1025d836fbf47 but got 93c62597eeef81a84d988bccbda1e990

/home/km0/spack/lib/spack/spack/package.py:1032, in do_fetch:
     29            self._fetch_time = time.time() - start_time
     30    
     31            if spack.do_checksum and self.version in self.versions:
  >> 32                self.stage.check()
     33    
     34            self.stage.cache_local()

### Steps to reproduce the issue

```console
$ spack install libjpeg
...
```

**Comment by adamjstewart** [comment]
Can you contact the developers and ask them why their checksum may have changed? Just want to make sure they weren't hacked. That's why Spack verifies the checksum of every download.

**Comment by alalazo** [comment]
This appears to be fixed at 5eca4f14706a9590407f14c9c76e5a8bb663e9df
