### ISSUE TITLE
valgrind % gcc@8.1.0 is broken

### ISSUE THREAD

**Issue by KineticTheory** [spack/spack#8071]
### Summary

I am trying out the recently released `gcc@8.1.0`, but I can't build `valgrind@3.13.0` with it.  I'm looking for help or hints about how to debug this build issue. I'm not familiar with `usban` features in gcc.

### Actual Result

Valgrind fails to build due to errors of the form (extracted from spack-build.out):

```
mv -f .deps/memcheck_amd64_linux-mc_main.Tpo .deps/memcheck_amd64_linux-mc_main.Po
../coregrind/link_tool_exe_linux 0x580000

00 /scratch/vendors/spack.20180425/lib/spack/env/gcc/gcc     -o memcheck-amd64-linux -m64 -O2 -g -std=gnu99 -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wold-style-declaration -fno-stack-protector -fsanitize=undefined -fno-sanitize=alignment -fno-strict-aliasing -fno-builtin  -fomit-frame-pointer -O2 -static -nodefaultlibs -nostartfiles -u _start  -m64 memcheck_amd64_linux-mc_leakcheck.o memcheck_amd64_linux-mc_malloc_wrappers.o memcheck_amd64_linux-mc_main.o memcheck_amd64_linux-mc_translate.o memcheck_amd64_linux-mc_machine.o memcheck_amd64_linux-mc_errors.o ../coregrind/libcoregrind-amd64-linux.a ../VEX/libvex-amd64-linux.a -lgcc 
memcheck_amd64_linux-mc_leakcheck.o: In function `compare_MC_Chunks':
/tmp/kellyt/spack-stage/spack-stage-qiFafU/valgrind-3.13.0/memcheck/mc_leakcheck.c:254: undefined reference to `__ubsan_handle_type_mismatch_v1'
/tmp/kellyt/spack-stage/spack-stage-qiFafU/valgrind-3.13.0/memcheck/mc_leakcheck.c:256: undefined reference to `__ubsan_handle_pointer_overflow'
```

I've not encountered this error before and I haven't had much success finding relevant information about ubsan and so I am looking for any hints that other spack users can provide.  Is this related to the `sanitize` build options?

### Steps to reproduce the issue

```console
$ spack install -v valgrind % gcc@8.1.0
```

### Information on your system

* Red Hat Enterprise Linux Workstation release 7.5 (Maipo)
* [spack-build.out.txt](https://github.com/spack/spack/files/1986292/spack-build.out.txt)
* [spack-build.env.txt](https://github.com/spack/spack/files/1986293/spack-build.env.txt)

**Comment by HadrienG2** [comment]
Looking at the Valgrind package, I noticed that [UBsan integration is already disabled on OSX](https://github.com/HadrienG2/spack/blob/645c640f38ae67008eb18c79301e19ddfd39c041/var/spack/repos/builtin/packages/valgrind/package.py#L69) because it causes similar issues. Maybe we should disable this Valgrind feature for now, or hide it behind an optional variant flag, if it causes so any problems?

**Comment by KineticTheory** [comment]
I've moved my test environment to gcc@8.3.0 and valgrind@3.14.0.  This issue is no longer relevant for me.
