### ISSUE TITLE
HTTP code 302

### ISSUE THREAD

**Issue by yee379** [spack/spack#8079]
# Summary

support redirects in downloading. i was trying to install llvm:

==> Installing llvm
==> Fetching file:///afs/slac/package/spack/var/spack/manual_mirrors/llvm/llvm-5.0.1.tar.xz
curl: (37) Couldn't open file /afs/slac/package/spack/var/spack/manual_mirrors/llvm/llvm-5.0.1.tar.xz
==> Fetching from file:///afs/slac/package/spack/var/spack/manual_mirrors/llvm/llvm-5.0.1.tar.xz failed.
==> Fetching http://llvm.org/releases/5.0.1/llvm-5.0.1.src.tar.xz

curl: (7) Failed connect to llvm.org:80; Connection timed out
==> Fetching from http://llvm.org/releases/5.0.1/llvm-5.0.1.src.tar.xz failed.
==> Can not find version 5.0.1 in url_list
==> Error: FetchError: All fetchers failed for llvm-5.0.1-hetznfxw7bbbqwfnhgyhotqysga4qxmo
FetchError: FetchError: All fetchers failed for llvm-5.0.1-hetznfxw7bbbqwfnhgyhotqysga4qxmo

/afs/slac.stanford.edu/package/spack/lib/spack/spack/package.py:993, in do_fetch:
     25                                     self.spec.format('$_$@'), ck_msg)
     26
     27            self.stage.create()
  >> 28            self.stage.fetch(mirror_only)
     29            self._fetch_time = time.time() - start_time
     30
     31            if spack.do_checksum and self.version in self.versions:

# What you expected

it seems like the url is a 302:

    $ curl http://llvm.org/releases/5.0.1/llvm-5.0.1.src.tar.xz
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>302 Found</title>
    </head><body>
    <h1>Found</h1>
    <p>The document has moved <a href="http://releases.llvm.org/5.0.1/llvm-5.0.1.src.tar.xz">here</a>.</p>
    <hr>
    <address>Apache/2.4.7 (Ubuntu) Server at llvm.org Port 80</address>
    </body></html>

so spack should follow the redirect and download from the new url.

# What happened instead

spack doesn't seem to follow redirects.

**Comment by adamjstewart** [comment]
Are you sure there isn't a problem with your firewall? It works just fine for me:
```console
$ spack fetch llvm@5.0.1
==> Fetching http://llvm.org/releases/5.0.1/llvm-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/cfe-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/polly-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/lldb-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/lld-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/compiler-rt-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/openmp-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/libcxx-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/libcxxabi-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/libunwind-5.0.1.src.tar.xz
######################################################################## 100.0%
==> Fetching http://llvm.org/releases/5.0.1/clang-tools-extra-5.0.1.src.tar.xz
######################################################################## 100.0%
```
Spack just wraps around `curl` and lets `curl` handle the downloading, so if your `curl` can't download it then Spack can't either.

**Comment by alalazo** [comment]
@adamjstewart It works for me too

**Comment by yee379** [comment]
you are correct. it was a combination of the fact that i had cached downloads and that the network acl's were changed under my feet. sorry for the inconvenience!

**Comment by scheibelp** [comment]
Thanks for the update @yee379. Looks like this should be closed.
