### ISSUE TITLE
mrnet fails on macOS

### ISSUE THREAD

**Issue by mathstuf** [spack/spack#808]
The linker is not set when clang is used. Seems to be an upstream problem, but they use some non-standard autotools setup and I can't figure out where the logic to set the linker is missing from.

@lee218llnl @jgalarowicz

**Comment by mathstuf** [comment]
@robertdfrench

**Comment by lee218llnl** [comment]
@mathstuf I believe this is actually an issue within MRNet itself. The conf/configure.in file within the MRNet source has some logic to test which compiler vendor is being used. Based on that, it sets variables, including AR. If it doesn't find the compiler type, there is no "else" fall through and it just doesn't set AR. I found that it is relatively easy to add a "clang" check in there and get the code to build. I could submit this as a patch, but will first query the MRNet support folks to see if they can add clang support, since that is a better long-term solution.

**Comment by lee218llnl** [comment]
The MRNet support folks added a clang check and updated their github repo. I created PR #899, which adds this version to the MRNet Spack package. @mathstuf please take a look and let me know if it works for you.

**Comment by mathstuf** [comment]
Looks sensible; I'll try and test it here today.

**Comment by mathstuf** [comment]
Clang looks happy now; just OS X patches seem to be necessary at this point:

```
/private/var/folders/ys/5224ywdn7x7_hzvfb7brk2sh0000gq/T/kitware/spack-stage/spack-stage-l7I78y/mrnet/xplat/src/SocketUtils-unix.C:108:24: error: use of undeclared identifier 'writev'; did you mean 'write'?
        ssize_t wret = writev( s, currIov, numIovBufs );
                       ^~~~~~
                       write
```

**Comment by alalazo** [comment]
@mathstuf I am trying to clean up a bit old issues. Any update on this one?

**Comment by mathstuf** [comment]
I forget what I was doing with `mrnet` at all. I'd say close it if anyone can confirm it works on macOS (I can do it, but it won't be until next week).

**Comment by healther** [comment]
Builds on Linux for me, OSX is failing though, but that's more a upstream problem isn't it? I could add a `conficts('darwin')`

**Comment by lee218llnl** [comment]
@healther, what error messages are you getting? Perhaps @bwelton can help if you provide more information.

**Comment by bwelton** [comment]
To my knowledge we have never built MRNet on OSX and it is not on our list of supported platforms. So adding conflicts('darwin') to the spack package would likely be appropriate for the time being. 

That being said, there is no reason that it shouldn't work with some minor changes. We would have no problem taking a patch to support building on OSX but I cannot make such a patch myself (key reason being I have no access to OSX for testing). I would be happy to help guide anyone who wants to create such a patch.
