### ISSUE TITLE
LLVM fails on Linux

### ISSUE THREAD

**Issue by jrood-nrel** [spack/spack#8088]
Summary

### Expected Result

LLVM to install on Linux. I have previously done this on of few of my systems without issues.

### Actual Result

This code from #7012 is executed for me even when on Linux:
```
==> No patches needed for llvm
==> Building llvm [CMakePackage]
==> Executing phase: 'cmake'
==> Error: TypeError: 'NoneType' object is not callable
TypeError: TypeError: 'NoneType' object is not callable

....spack/var/spack/repos/builtin/packages/llvm/package.py:436, in check_darwin_lldb_codesign_requirement:
     15                               ' to build LLVM with LLDB. See https://llvm.org/'
     16                               'svn/llvm-project/lldb/trunk/docs/code-signing'
     17                               '.txt for details on how to create this identity.')
  >> 18                raise RuntimeError(explanation)
```

### Steps to reproduce the issue

```console
$ spack install llvm
```

### Information on your system

 1. CentOS 7 and GCC 6

**Comment by adamjstewart** [comment]
@goxberry

**Comment by scheibelp** [comment]
This appears to be the result of a (IMO reasonable) mis-interpretation of the applicability of `@when` so I created a PR to address this for LLVM in #8092
