### ISSUE TITLE
[libjpeg] Incorrect hash for version 9c

### ISSUE THREAD

**Issue by mcneish1** [spack/spack#8180]
Spack lists the md5 hash for libjpeg 9c as 7794e558c60605424fb1025d836fbf47, but
```
$ curl http://www.ijg.org/files/jpegsrc.v9c.tar.gz | md5sum
93c62597eeef81a84d988bccbda1e990
```
There isn't an official hash or a signature on the ijg.org website, or I would have made a pull request to fix it.

**Comment by adamjstewart** [comment]
Would you mind contacting the developers and asking them why their checksum changed? 99% of the time, it's a bugfix without a new version number. 1% of the time, the website got hacked and you're downloading a virus.

**Comment by mcneish1** [comment]
Sent an email to the jpeg-info address listed in their readme asking about a signature or hash for the archive.
