### ISSUE TITLE
How to Handle Compilers other than C/C++ and Fortran?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#8187]
@tgamblin  How do we create packages for stuff written in compiled languages other than C/C++ and Fortran?  See #8166 for example.  I'm looking for advice / best practices.

**Comment by alalazo** [comment]
I think the current practice is to treat them as virtual dependencies, like `golang` or `D`.

**Comment by citibeth** [comment]
Given that GCJ is part of GCC, can you think of a way to do this ?
