### ISSUE TITLE
Help using gpg and buildcaches, `spack gpg create ...` just sits there

### ISSUE THREAD

**Issue by hartzell** [spack/spack#8209]
I think that I need a helpful hint or two to get started playing with buildcaches.

I've read the [buildcaches doc](https://spack.readthedocs.io/en/latest/binary_caches.html) and the [FOSDEM presentation](https://fosdem.org/2018/schedule/event/llnl_spack/attachments/slides/2663/export/events/attachments/llnl_spack/slides/2663/fosdem_spack_binary_packaging.pdf) about buildcaches and am trying to work through the example in the talk.

When I run `spack gpg create ...` it seems to be waiting for something, but I'm not sure what:

```
[hartzell@bunny ~]$ spack gpg create "George Hartzell" hartzell@alerce.com
gpg: skipping control `%no-protection' ()
```

If I hit control-C, I get

```
^C

gpg: signal Interrupt caught ... exiting
==> Error: Keyboard interrupt.
[hartzell@bunny ~]$
```

I've tried control-D, on the theory that it was reading from stdin, but it didn't do anything useful.

I'm on a freshly built Digital Ocean droplet running CentOS 7, using the `gpg2` bits that are installed in the OS:

```
[hartzell@bunny ~]$ which gpg2
/usr/bin/gpg2
[hartzell@bunny ~]$ yum list | grep gpg
gpgme.x86_64                                1.3.2-5.el7                installed
libgpg-error.x86_64                         1.12-3.el7                 installed
pygpgme.x86_64                              0.3-9.el7                  installed
gpgme.i686                                  1.3.2-5.el7                base
gpgme-devel.i686                            1.3.2-5.el7                base
gpgme-devel.x86_64                          1.3.2-5.el7                base
kgpg.x86_64                                 4.10.5-4.el7               base
libgpg-error.i686                           1.12-3.el7                 base
libgpg-error-devel.i686                     1.12-3.el7                 base
libgpg-error-devel.x86_64                   1.12-3.el7                 base
maven-gpg-plugin.noarch                     1.4-11.el7                 base
maven-gpg-plugin-javadoc.noarch             1.4-11.el7                 base
[hartzell@bunny ~]$
```

What have I missed?

**THANKS**

**Comment by alalazo** [comment]
@hartzell I had the same issue, ended up writing a [small note](https://spack.readthedocs.io/en/latest/getting_started.html#spack-gpg) in the docs. Feel free to add on it if it needs to be made more general or if there's a better solution.
