### ISSUE TITLE
Lock unit test failing on Travis MacOS builder

### ISSUE THREAD

**Issue by alalazo** [spack/spack#8225]
It seems we have a failure on MacOS, started after we merged #7692 - see [here](https://travis-ci.org/spack/spack/jobs/381414674) for an example log. Not sure if the error is transient (i.e. due to Travis itself) or not, logging the failure here to have it on the records.

### Expected Result

Green light from Travis

### Actual Result

```console
____________________________ test_lock_checks_user _____________________________
tmpdir = local('/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/pytest-of-travis/pytest-0/test_lock_checks_user0')
    def test_lock_checks_user(tmpdir):
        """Ensure lock checks work."""
        path = str(tmpdir)
        uid = os.getuid()
    
        # self-owned, own group
>       tmpdir.chown(uid, uid)
lib/spack/spack/test/llnl/util/lock.py:944: 
...
<omitted>
...
E           EPERM: [Operation not permitted]: chown('/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/pytest-of-travis/pytest-0/test_lock_checks_user0', 501, 501)
lib/spack/external/py/_error.py:85: EPERM
======== 1 failed, 1035 passed, 76 skipped, 1 xfailed in 852.13 seconds ========
```

**Comment by alalazo** [comment]
I don't have access to a Mac to fix this, so pinging @tgamblin @scheibelp

**Comment by tgamblin** [comment]
@adamjstewart, @alalazo: Is it worth turning macs back on in the regular build now?  Seems like the response time is reasonably fast on mac builders, but I haven't been keeping up with travis status.
