### ISSUE TITLE
Spack compiler wrappers not used when they should be

### ISSUE THREAD

**Issue by citibeth** [spack/spack#8232]
@scheibelp @alalazo @adamjstewart 

I've encountered a build, on a particular machine, that does not use Spack's compiler wrappers.  We don't know why.  And it works, of course, on many other machines.  See #8132

**Comment by adamjstewart** [comment]
Can you post your `compilers.yaml`, at least for the compiler in question? Are you `module load`ing that compiler? I wonder if Spack is putting that path before its own compiler wrapper.

**Comment by citibeth** [comment]
> Can you post your compilers.yaml, at least for the compiler in question?

See #8132 

> Are you module loading that compiler? I wonder if Spack is putting that path before its own compiler wrapper.

Yes

**Comment by adamjstewart** [comment]
That explains it. So Spack is running the `module load` commands from your `compilers.yaml` _after_ it adds its own compilers to the environment instead of before. That could potentially break a lot of packages. We should fix this. I know where we add Spack's compiler wrapper to the path, but I'm not sure where/when the `module load` logic is run.

**Comment by citibeth** [comment]
Great diagnosis!  Who do you think we should rope in for the fix?

**Comment by adamjstewart** [comment]
I'm guessing @scheibelp is the expert on this one.

**Comment by scheibelp** [comment]
I'll look at this tomorrow (5/22)

**Comment by skosukhin** [comment]
https://github.com/spack/spack/pull/7912#issue-184330558

**Comment by citibeth** [comment]
After #8245 the build log is improved, but still the original link problem.  Because I'm getting stuff like this in the link command line:
```
-lc /usr/lib64/libxml2.so
```

**Comment by citibeth** [comment]
I'm closing this issue because it looks like the compiler wrappers have been fixed by #8245

**Comment by scheibelp** [comment]
The alternative PR https://github.com/spack/spack/pull/8346 was merged, and should also address this
