### ISSUE TITLE
Spack Mismatches OS and/or Compiler

### ISSUE THREAD

**Issue by ax3l** [spack/spack#8237]
I am running [Spack on Travis-CI](https://spack.readthedocs.io/en/latest/workflows.html#using-spack-on-travis-ci). This works splendid so far.

For some reason with a [minimal PR](https://github.com/openPMD/openPMD-api/pull/190) to add an additional dependency, spack starts to [select an OSX compiler on Ubuntu](https://travis-ci.org/openPMD/openPMD-api/jobs/381153380) and causes similar confusing runtime mismatches:
  https://travis-ci.org/openPMD/openPMD-api/builds/381153375

```
Still running (1 of 20): spack install adios ~mpi %clang@5.0.0
The command spack install adios ~mpi %clang@5.0.0 exited with 1.
Log:
==> Error: No compilers with spec clang@8.1.0 found for operating system ubuntu14.04 and target x86_64.
Run 'spack compiler find' to add compilers.
```

My config files are multi-platform:
  https://github.com/openPMD/openPMD-api/tree/dev/.travis/spack

### Expected Result

Still select the right OS and compilers.

### Actual Result

On Ubuntu 14.04 and with Clang 5.0 it suddenly tries to select clang 8.0 from OSX (which fails). Other images/configs show similar confusing output.

### Steps to reproduce the issue

Config files: (did I set something quite off here?)
  https://github.com/openPMD/openPMD-api/tree/dev/.travis/spack

Spack setup and install lines:
  https://github.com/openPMD/openPMD-api/blob/7240ebe2fc2a22f60f0f40ff7bb4329fa6224ffd/.travis.yml#L210-L297

PR that breaks compiler selection and OS detection:
  https://github.com/openPMD/openPMD-api/pull/190

### Information on your system

Travis-CI Ubuntu 14.04 and OSX images: https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System

**Comment by alalazo** [comment]
Might it be you are hit by #8082 ?

**Comment by ax3l** [comment]
I am definitely using external packages for CMake, OpenMPI and Python, yes.

**Comment by ax3l** [comment]
Can't reproduce the exact problem anymore. But #8082 is still existing as far as I can see.
