### ISSUE TITLE
spack setup does not patch overlong shebangs

### ISSUE THREAD

**Issue by mcneish1** [spack/spack#8285]
https://github.com/spack/spack/blob/3c10d160d0539c8dca2a502c2bd878fc7d9aeda3/lib/spack/spack/cmd/setup.py#L102
sys.executable is not checked for length.

I'll put together a pr Monday (ish) if nobody gets to this first.

**Comment by citibeth** [comment]
`spack setup` is dead.  It was broken a while back, and will be removed.  It is being replaced by #7846, which I welcome feedback and beta testers on.
