### ISSUE TITLE
Error: name 'CMakePackage' is not defined

### ISSUE THREAD

**Issue by junghans** [spack/spack#8292]
I getting a:
```
$ spack spec flang@develop
Input spec
--------------------------------
flang@develop

Concretized
--------------------------------
==> Error: name 'CMakePackage' is not defined
```
but only when using python3.5.5, python-2.7.14 works fine.

**Comment by healther** [comment]
You'll need to clean pythons cached files. This is a consequence of a refactoring and for some reason only happens for python3

**Comment by junghans** [comment]
Worked, thanks!

**Comment by healther** [comment]
Yeah... maybe it should go there. I agree that it should not be a permanent issue, but this is the third _separate_ issue that was opened for this problem...

**Comment by adamjstewart** [comment]
@junghans Now that #8419 has been merged, do you think it's safe to close this issue? Or should we add something to "Known Issues"? I think the number of Python 3 users is small enough that we can continue putting out fires on GitHub. I don't know how many people actually read "Known Issues" anyway.

**Comment by junghans** [comment]
Sure!

**Comment by healther** [comment]
> I think the number of Python 3 users is small enough that we can continue putting out fires on GitHub.

I had this today on a python2 based system, but I can't give you the sequence of steps to reproduce it, I just implemented the clean and washed my hands of it

> I don't know how many people actually read "Known Issues" anyway.

Yeah... I'm not sure if it's even part of the stub issue that you get if you start a new one
