### ISSUE TITLE
concretization error for python3

### ISSUE THREAD

**Issue by s-sajid-ali** [spack/spack#8301]
### Expected Result

Successful concretization of python packages 

### Actual Result

```
[sajid@apsxrmd-0001 ~]$ spack spec -I py-matplotlib
Input spec
--------------------------------
     py-matplotlib

Concretized
--------------------------------
==> Error: py-matplotlib does not depend on py-functools32 or py-subprocess32
```
This works fine if I give ```^python@3.6.5``` as an additional argument.

### Information on your system

This includes:

 1. linux-centos7-x86_64
 2. python preferred version set to 3.6.5 in packages.yaml

**Comment by citibeth** [comment]
See #8081 and follow the instructions; i.e. merge from #7926

**Comment by alalazo** [comment]
@citibeth Can we keep issues open until the corresponding fix is merged? 

P.S. It's possible to ensure that merging the fix closes all related issues automatically by adding (either in a commit or in the description of the PR) the string `fixes #<issue-number>`  for any issue that is solved by the PR. More info [here](https://help.github.com/articles/closing-issues-using-keywords/)
