### ISSUE TITLE
Make Spack Install Ignore libgpfs Library

### ISSUE THREAD

**Issue by ifelsefi** [spack/spack#8384]
Hi

Any way to make Spack ignore a particular library located within /lib64, during compile, such as **libgpfs.so**?

If so this would make installing software easier in our environment which does not have GPFS mounted everywhere.

I ran into this issue with Relion which we mainly use in our cluster.  Though some users like to run on workstations.  

As a result:

> [root@desktop ~]# ldd -r $(which relion)                                                                                                                                                                                                      
>         linux-vdso.so.1 =>  (0x00007ffce85d8000)                                                                                                                                                                                               
>         librelion_lib.so => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/relion-develop-2ilkf4r2dvy7xwvtavnj7swg7mj3xtd5/lib/librelion_lib.so (0x00007f740579f000)                                        
>         libfftw3.so.3 => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/fftw-3.3.6-pl2-yn24zhrzhnv7zs3orlq7ttjt5456sfn2/lib/libfftw3.so.3 (0x00007f74051b5000)                                              
>         libcufft.so.8.0 => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-8.0.44-qlfv2l4lqkjs55vleyvcnbj6jkfbecqe/lib64/libcufft.so.8.0 (0x00007f73fc366000)                                           
>         libmpi_cxx.so.40 => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/openmpi-3.0.0-kf3smhm24t3oczqnzfxbilm2e7g55bm6/lib/libmpi_cxx.so.40 (0x00007f73fc14b000)                                         
>         libmpi.so.40 => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/openmpi-3.0.0-kf3smhm24t3oczqnzfxbilm2e7g55bm6/lib/libmpi.so.40 (0x00007f73fbce8000)                                                 
>         libdl.so.2 => /lib64/libdl.so.2 (0x00007f73fbac7000)                                                                                                                                                                                   
>         librelion_gpu_util.so => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/relion-develop-2ilkf4r2dvy7xwvtavnj7swg7mj3xtd5/lib/librelion_gpu_util.so (0x00007f73fb678000)                              
>         libfltk_images.so.1.3 => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/fltk-1.3.3-owkbwo7azxbynypsmosvkoaq55igknr5/lib/libfltk_images.so.1.3 (0x00007f73fb43a000)                                  
>         libfltk_forms.so.1.3 => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/fltk-1.3.3-owkbwo7azxbynypsmosvkoaq55igknr5/lib/libfltk_forms.so.1.3 (0x00007f73fb233000)                                    
>         libfltk.so.1.3 => /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/fltk-1.3.3-owkbwo7azxbynypsmosvkoaq55igknr5/lib/libfltk.so.1.3 (0x00007f73faf39000)                                                
>         libX11.so.6 => /lib64/libX11.so.6 (0x00007f73fabfb000)                                                                                                                                                                                 
>         libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f73fa9df000)                                                                                                                                                                         
>         librt.so.1 => /lib64/librt.so.1 (0x00007f73fa7d6000)                                                                                                                                                                                   
>         libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f73fa4ce000)                                                                                                                                                                           
>         libm.so.6 => /lib64/libm.so.6 (0x00007f73fa1cc000)                                                                                                                                                                                     
>         libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f73f9fb5000)                                                                                                                                                                             
>         libc.so.6 => /lib64/libc.so.6 (0x00007f73f9bf2000)                                                                                                                                                                                     
>         **libgpfs.so => not found**

**Comment by JusticeForMikeBrown** [comment]
I guess nobody has an idea.
