### ISSUE TITLE
spectrum-mpi & depends_on type 'test'

### ISSUE THREAD

**Issue by ax3l** [spack/spack#8398]
The missing version in `spectrum-mpi` causes issues with MPI packages and tests.

As soon as one adds a `depends_on('anything_really', type='test')` to a package that also `depends_on('mpi')` the install with tests fails.

### Expected Result

```bash
spack install --test=root package
```
should start installing.

### Actual Result

```bash
$ spack install --test=root package
==> Error: There are no valid versions for spectrum-mpi that match ':'
```

### Steps to reproduce the issue

- take a package that depends on MPI, say `mpileaks`
- add a `test` dependency
```diff
diff --git a/var/spack/repos/builtin/packages/mpileaks/package.py b/var/spack/repos/builtin/packages/mpileaks/package.py
index 33c617205..28bf5f247 100644
--- a/var/spack/repos/builtin/packages/mpileaks/package.py
+++ b/var/spack/repos/builtin/packages/mpileaks/package.py
@@ -37,6 +37,7 @@ class Mpileaks(Package):
     depends_on("mpi")
     depends_on("adept-utils")
     depends_on("callpath")
+    depends_on("vim", type="test")
 
     def install(self, spec, prefix):
         configure("--prefix=" + prefix,
```
- run `spack install --test=root mpileaks`

### Information on your system

Spack `dev` as of 80564fae5df952eb8544272e178d283bac0c0f57 on Debian 9.4 with Python 3.6.4

**Comment by adamjstewart** [comment]
I wasn't able to reproduce this, even after blowing my `packages.yaml` away. It starts installing `boost` instead of crashing.

**Comment by ax3l** [comment]
Funny, I just updated from the reported 80564fae5df952eb8544272e178d283bac0c0f57 to the latest `dev` as of c86628880f2c19d43942721b654126b0c8bde085 and the problem is gone :-)
