### ISSUE TITLE
Most packages that depend on elf fail to concretize on macOS

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#8401]
#7939 introduced an unintended concretization bug. Now, most packages that depend on `elf` fail to concretize on macOS.

```console
$ spack spec automaded
==> Error: libelf@0.8.13%clang@9.0.0-apple arch=darwin-highsierra-x86_64 does not satisfy elf@1
$ spack spec callpath
==> Error: libelf@0.8.13%clang@9.0.0-apple arch=darwin-highsierra-x86_64 does not satisfy elf@1
$ spack spec dyninst
==> Error: libelf@0.8.13%clang@9.0.0-apple arch=darwin-highsierra-x86_64 does not satisfy elf@1
$ spack spec extrae
==> Error: libelf@0.8.13%clang@9.0.0-apple arch=darwin-highsierra-x86_64 does not satisfy elf@1
$ spack spec mitos
==> Error: libelf@0.8.13%clang@9.0.0-apple arch=darwin-highsierra-x86_64 does not satisfy elf@1
$ spack spec mpileaks
==> Error: libelf@0.8.13%clang@9.0.0-apple arch=darwin-highsierra-x86_64 does not satisfy elf@1
$ spack spec stat
==> Error: libelf@0.8.13%clang@9.0.0-apple arch=darwin-highsierra-x86_64 does not satisfy elf@1
```
This is also causing the documentation tests to fail.
```
WARNING: Unexpected return code 1 from command 'spack --profile graph dyninst'
WARNING: Unexpected return code 1 from command 'spack graph mpileaks'
WARNING: Unexpected return code 1 from command 'spack graph --deptype=all mpileaks'
WARNING: Unexpected return code 1 from command 'spack graph --dot mpileaks'
```

**Comment by scheibelp** [comment]
This similar to (1) and (5) at https://github.com/spack/spack/wiki/Issue-Disambiguation

There is *some* look-ahead logic for resolving virtuals, but it is limited and I'm not surprised it doesn't work out here (e.g. because the dyninst `elf@1` requirement is conditional).

The short-term fix will be to add more detail to the user specs. If `clang` doesn't build `elfutils` and `libelf` doesn't satisfy the latest `dyninst` then either (a) the doc examples will need a different compiler or (b) the doc examples need to specify an older version of dyninst. I'll think on whether there's another (more-satisfying) near-term solution but that's what occurs to me now.

**Comment by adamjstewart** [comment]
Yeah, I guess that means some packages simply can't be installed on macOS. That's no big deal. I think we should add conflicts for that to make it more explicit instead of the current error message.

**Comment by lee218llnl** [comment]
was a conclusion ever reached on this? Someone is trying to build STAT on their Mac and having troubles https://github.com/LLNL/STAT/issues/19.

**Comment by hainest** [comment]
Dyninst doesn't build with clang, but I'm working on it. I also have a [PR](https://github.com/spack/spack/pull/18063) for Dyninst to rely directly on elfutils instead of elf@1.

**Comment by adamjstewart** [comment]
Unfortunately this bug has gotten even worse:
```console
$ spack spec automaded
Input spec
--------------------------------
automaded

Concretized
--------------------------------
==> Error: Multiple providers found for 'elf': ['elfutils', 'libelf@0.8.13%apple-clang@12.0.0 arch=darwin-catalina-x86_64']
```
This is now (5) from https://github.com/spack/spack/wiki/Issue-Disambiguation

**Comment by adamjstewart** [comment]
The new concretizer is smarter about this. The above packages still fail to concretize, but that's because they either don't build on macOS, or depend on other packages that don't build on macOS. There are no longer any concretizer errors related to provider confusion.
