### ISSUE TITLE
boost is broken on gcc 7 and 6 with Ubuntu

### ISSUE THREAD

**Issue by davydden** [spack/spack#8437]
https://github.com/spack/spack/pull/7601 broke `boost` on `Ubuntu` with `gcc` 7 and 6.

### Expected Result

`boost` installs.

### Actual Result

```
error: "default" is not a known value of feature <cxxstd>
error: legal values: "98" "03" "0x" "11" "1y" "14" "1z" "17" "2a" "latest"
```

### Steps to reproduce the issue

```console
$ spack install boost
```

### Information on your system

Ubuntu18.04 gcc7.3.0

**Comment by chissg** [comment]
I will look into this directly. Sorry for the inconvenience.

**Comment by davydden** [comment]
@chissg 

> I will look into this directly. Sorry for the inconvenience.

see https://github.com/spack/spack/pull/8438

**Comment by chissg** [comment]
I have verified that #8438 fixes my unfortunate oversight, and indeed is exactly the fix I was testing myself independently. Once more, apologies for the error.
