### ISSUE TITLE
xsdk@develop has an unsatisfiable version constraint

### ISSUE THREAD

**Issue by davydden** [spack/spack#8460]
`xsdk@develop` has an unsatisfiable version constraint

### Expected Result

`spack spec xsdk@develop` concretizes.

### Actual Result

```
$ spack spec xsdk@develop
Input spec
--------------------------------
xsdk@develop

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    hypre@develop~int64~internal-superlu
        ^blas
        ^lapack


while trying to concretize the partial spec:

    mfem@3.3.2+examples+hypre+miniapps+mpi+petsc+sundials+superlu-dist


mfem requires hypre version 2.10.0:2.13.999, but spec asked for develop
```
That's because `xsdk` has
```
depends_on('mfem@3.3.2+mpi+hypre+superlu-dist+petsc+sundials+examples+miniapps', when='@develop')
depends_on('hypre@develop~internal-superlu', when='@develop')
```
whereas `mfem` has
```
depends_on('hypre@2.10.0:2.13.999', when='@:3.3.999+mpi')
```
The two are clearly conflicting.

### Steps to reproduce the issue

```console
$ spack spec xsdk@develop
```

Can somebody from `mfem` have a look please?
@goxberry @tzanio @markcmiller86 @acfisher @v-dobrev ping.

**Comment by balay** [comment]
I have a bunch of `xsdk@develop` fixes in `balay/xsdk-develop`

One related to is in balay/xsdk-mfem-develop

I was waiting for @acfisher to ACK it before doing a PR. I guess I could do a PR and then seek the ACK

**Comment by davydden** [comment]
>  I guess I could do a PR and then seek the ACK

yes, I think that would be quicker. You can add `dont-merge-yet` label so that the PR is not accidentally merged until @acfisher reviews it.
