### ISSUE TITLE
alquimia@develop fails to build

### ISSUE THREAD

**Issue by davydden** [spack/spack#8474]
`alquimia@develop fails to build`

### Expected Result

`spack install xsdk@develop` builds

### Actual Result

```
==> Installing alquimia
==> Trying to clone git repository: https://github.com/LBL-EESA/alquimia-dev.git 
==> No checksum needed when fetching with git
==> Already staged alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5 in /home/davydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5
==> No patches needed for alquimia
==> Building alquimia [CMakePackage]
==> Executing phase: 'cmake'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

5 errors found in build log:
     97     [ 40%] Building Fortran object alquimia/CMakeFiles/alquimia.dir/pflotran_alquimia_interface.F90.o
     98     cd /home/davydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5/alquimia-dev/spack-build/alquimia && /home/davydden/spack/opt/spack/linux-ubuntu18
            .04-x86_64/gcc-7.3.0/openmpi-3.1.0-sk3sszdaaz5rbybm5uldokyuihyulbgi/bin/mpif90 -Dalquimia_EXPORTS -I/home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/petsc-
            develop-ggptktqotpsg4jjkvc22r25yvcwzhkjg/include -I/home/davydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5/alquimia-dev/spack-build -I/home/d
            avydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5/alquimia-dev -I/home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/pflotran-de
            velop-nwzflqq6fqjvybrpsi5qjkkrafqeblct/include -I/home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/petsc-develop-ggptktqotpsg4jjkvc22r25yvcwzhkjg/include/pe
            tsc  -W -Wall -std=gnu -pedantic -Wno-unused-variable -Wno-unused-parameter -O2 -g -DNDEBUG -fPIC   -c /home/davydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3l
            trlrjuc6dvh74mlm5/alquimia-dev/alquimia/pflotran_alquimia_interface.F90 -o CMakeFiles/alquimia.dir/pflotran_alquimia_interface.F90.o
     99     /home/davydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5/alquimia-dev/alquimia/pflotran_alquimia_interface.F90:216:55:
     100    
     101       global_auxvar%den_kg = option%reference_water_density
     102                                                           1
  >> 103    Error: ‘reference_water_density’ at (1) is not a member of the ‘option_type’ structure
     104    /home/davydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5/alquimia-dev/alquimia/pflotran_alquimia_interface.F90:884:32:
     105    
     106       option%reference_water_density = 997.16
     107                                    1
  >> 108    Error: ‘reference_water_density’ at (1) is not a member of the ‘option_type’ structure
     109    alquimia/CMakeFiles/alquimia.dir/build.make:156: recipe for target 'alquimia/CMakeFiles/alquimia.dir/pflotran_alquimia_interface.F90.o' failed
  >> 110    make[2]: *** [alquimia/CMakeFiles/alquimia.dir/pflotran_alquimia_interface.F90.o] Error 1
     111    make[2]: Leaving directory '/home/davydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5/alquimia-dev/spack-build'
     112    CMakeFiles/Makefile2:90: recipe for target 'alquimia/CMakeFiles/alquimia.dir/all' failed
  >> 113    make[1]: *** [alquimia/CMakeFiles/alquimia.dir/all] Error 2
     114    make[1]: Leaving directory '/home/davydden/spack/var/spack/stage/alquimia-develop-w5oa3bnoptktw3ltrlrjuc6dvh74mlm5/alquimia-dev/spack-build'
     115    Makefile:143: recipe for target 'all' failed
  >> 116    make: *** [all] Error 2

```

### Steps to reproduce the issue

```console
$ spack install xsdk@develop
```

### Information on your system

This includes:

 1. Ubuntu 18.04
 2. gcc 7.3.0

@BarrySmith pinging as you added the package.
@balay I wonder if you have a fix for that as well in your branch :smile:

**Comment by balay** [comment]
yes - its in branch balay/xsdk-alquimia-develop [and merged to balay/xsdk-develop]

Ideally the fix should go into  https://github.com/smolins/alquimia-dev  so sent the info to @smolins to verify if the fix is correct

**Comment by balay** [comment]
@davydden, if you are looking at `spack install xsdk@develop` - you should check branch `balay/xsdk-develop`

It has a bunch more patches - (some temp fixes and others) that should go into individual package repos.

Outstanding branches are:

balay/xsdk-mfem-develop-fix-link-order [mfem devs appear to work on this fix - and its likely to be different fix - so this branch will be abandoned once its available]

balay/xsdk-trilinos-develop [part of the fix  should go into trilinos  - so waiting for response from @jwillenbring. the other part - related xsdk/package.py should be in a PR]

there is a petsc+superlu_dist workarround in balay/xsdk-develop - its hakey. It will stay this way until a superlu+superlu_dist incompatibility is fixed [and then this update will get into petsc/master]. After this - the hack can be tossed out

**Comment by davydden** [comment]
thanks for the info @balay 👍 . There is no pressing need, I was just trying to test https://github.com/spack/spack/pull/7529 . Let's hope those fixes you have will make it upstream in the near future.

**Comment by keitat** [comment]
I observed the same problem with gcc 7.2

**Comment by davydden** [comment]
> Ideally the fix should go into https://github.com/smolins/alquimia-dev so sent the info to @smolins to verify if the fix is correct

@balay have you heard back from upstream developers about this fix?

**Comment by balay** [comment]
nope - I haven't yet heard back from @smolins

**Comment by smolins** [comment]
I cannot follow what is being discussed here. Could you please summarize
the issue?
Thanks

**Comment by balay** [comment]
ok https://github.com/LBL-EESA/alquimia-dev/pull/52

**Comment by balay** [comment]
@davydden  this issue should be resolved with the latest update to alquimia master branch

**Comment by davydden** [comment]
> @davydden this issue should be resolved with the latest update to alquimia master branch

thanks, it does indeed works now!
