### ISSUE TITLE
Help passing info from dependencies up into dependents (for "Python rpaths" work)

### ISSUE THREAD

**Issue by hartzell** [spack/spack#8499]
[Plz don't get hung up on method/variable/file/... names, I still just trying to understand the wiring]

I'm working on #8436 and my Python and/or Spack architectural naivete has me stumped.  The forehead-shaped dent in my desk suggests it's time to ask for help.

In pursuit of #8436 I'd like to have dependencies like `py-configparser` to be able to communicate info (e.g. any dirs that need to be added to Python's search path) back up the dependency graph to e.g. `py-flake8` so that it can write out a `.spack-rpaths` file.

I've been trying to do it via `setup_dependent_package()`, but I'm stuck.

I *can*:

- define a method in `PythonPackage` that gets called in instances of classes that inherit from it (e.g. `PyFlake8`) and build up a list of paths in an attribute; and
- add code to the `PyFlake8` class to write it out to a file.

E.g.:

```diff
diff --git a/lib/spack/spack/build_systems/python.py b/lib/spack/spack/build_systems/python.py
index 090516279..f42f78ca5 100644
--- a/lib/spack/spack/build_systems/python.py
+++ b/lib/spack/spack/build_systems/python.py
@@ -419,3 +419,12 @@ class PythonPackage(PackageBase):

     # Check that self.prefix is there after installation
     run_after('install')(PackageBase.sanity_check_prefix)
+
+    def setup_dependent_package(self, module, dependent_spec):
+        """Add our prefix to the list of dirs that need to be added
+           to the python rpaths [SIC] file.
+        """
+
+        paths = getattr(module, 'python_rpaths', [])
+        paths.append(self.prefix)
+        setattr(module, 'python_rpaths', paths)
diff --git a/var/spack/repos/builtin/packages/py-flake8/package.py b/var/spack/repos/builtin/packages/py-flake8/package.py
index 81a583895..fdefc3851 100644
--- a/var/spack/repos/builtin/packages/py-flake8/package.py
+++ b/var/spack/repos/builtin/packages/py-flake8/package.py
@@ -76,3 +76,11 @@ class PyFlake8(PythonPackage):
     def patch(self):
         """Filter pytest-runner requirement out of setup.py."""
         filter_file("['pytest-runner']", "[]", 'setup.py', string=True)
+
+    @run_after('install')
+    def write_rpath_file(self):
+        spec = self.spec
+        mkdirp(spec.prefix.bin)
+
+        with open(spec.prefix.bin.join(".spack-rpaths-via-setup"), 'w') as the_file:
+            the_file.write("\n".join(python_rpaths) + "\n")
```

But if I move the definition of `write_rpath_file` up into `PythonPackage` or `PackageBase` it fails with something like:

```
==> Error: AttributeError: 'module' object has no attribute 'python_rpaths'
```

I more-or-less understand that I'm cramming that attribute directly into the dependent module's world, and can imagine why it wouldn't resolve for a method created up in the parent *module*, but the whole thing seems less than useful (yeah, I know, it's not *all* about me...).

As an alternative, I tried defining a property (a `[]`) up in `PackageBase` and using `module` in `setup_dependent_package` to access it, but I couldn't make up any syntax that Python thought was reasonable.

Is there a way to use `setup_dependent_package` to do what I'm trying to do or is it the wrong tool for the job?

I also explored another alternative that might be more appropriate.  The design discussed above pushes info up from the dependencies.  I also thought about having the dependencies add it as some sort of "metadata" and then pulling it out by looping over the top-level `spec.dependencies()` but I wasn't sure whether that's an approved use of the spec (let alone getting the syntax to work out).

**Comment by adamjstewart** [comment]
> But if I move the definition of write_rpath_file up into PythonPackage or PackageBase it fails with something like:
> ```
> ==> Error: AttributeError: 'module' object has no attribute 'python_rpaths'
> ```

Hmm, maybe assign it to `self.python_rpaths` instead? You may also need to use `inspect`. That's why it's scattered throughout the base classes. But I could be wrong. Just an idea.

P.S. If you haven't already found it, this block of code seems like it is similar to what you're trying to do:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py#L557,L562

**Comment by hartzell** [comment]
I've tried `self.python_rpaths` w/out any success (though I might have had other parts of the incantation out of place, so...).

Re [the code you pointed me at](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py#L557,L562), that's basically the loop that I'm doing in the PR.   I'm worried that there are packages that provide python libs and therefor need to extend python's search path but that *don't* extend/inherit from PythonPackage.  

The PR is silly, just adds anything that looks like a Python library (starts with "py-"...).  The final paragraph in my issue above is looking for a way to take the loop that you pointed at and change it to something like:

```python
python_paths = []
for d in dependent_spec.traverse(
        deptype=('build', 'run', 'test')):
    if d.package.provides_python_library:
        python_paths.append(join_path(d.prefix, self.site_packages_dir))
```

And, now that I type it out I see that (even) I can probably add that as a Boolean in PackageBase and make it all work.  I was trying to shove it into `d` but it didn't feel like the right place.

Hmmmm..

**THANKS** (though I might not get to play with it right away)

**Comment by hartzell** [comment]
Well, following the trail that @adamjstewart sent me down worked out.  I've updated the PR, PackageBase now has a Boolean indicated whether a package provides python libs and the loop that builds the ".spack-rpaths" file checks it.  More details in #8436.

If there's a Pythonic answer to my original question, I'd still welcome the explanation, but I'll close this as resolved.

**Comment by adamjstewart** [comment]
> I'm worried that there are packages that provide python libs and therefor need to extend python's search path but that don't extend/inherit from PythonPackage.
>
> The PR is silly, just adds anything that looks like a Python library (starts with "py-"...).

The packages don't need to inherit from `PythonPackage` in order for the existing logic to work, they need to `extends('python')`, which should be the case for most packages that provide Python libraries. I'm actually more concerned about your logic; there are many packages that provide optional Python libraries that don't start with `py-` (`gdal` is an example). I would stick with the existing logic if I were you, no need for any booleans.
