### ISSUE TITLE
Is there any documentation about install_tree ?

### ISSUE THREAD

**Issue by samfux84** [spack/spack#8529]
I am trying to add the mshadow package (which is a dependency of mxnet) to an older spack installation. When compiling mshadow, it results in the following error

```
==> Error: AttributeError: 'str' object has no attribute 'mshadow'
/cluster/apps/spack/var/spack/repos/hpc/packages/mshadow/package.py:40, in install:
     39       def install(self, spec, prefix):
  >> 40           install_tree('mshadow', prefix.include.mshadow)
     41           install_tree('make', prefix.make)
```

I tried to find some information about install_tree in the spack documentation, but I did not understand what the function is used for.

In https://github.com/spack/spack/pull/3579/commits/abcefd545d781a7306f0a914853b683920bf529e @adamjstewart wrote a comment:

> You can use prefix.include.mshadow and prefix.make now, no need for join_path.

I am sorry for bothering you with this issue, but I would like to ask you how the install_tree commands

```
install_tree('mshadow', prefix.include.mshadow)
install_tree('make', prefix.make)
```

can be replaced with join_path to make the package work with an older spack installation.

**Comment by adamjstewart** [comment]
`install_tree` is a function that copies a source directory to an installation directory and applies proper installation permissions. If you look at the source code:
https://github.com/spack/spack/blob/develop/lib/spack/llnl/util/filesystem.py#L252,L259
you'll see that it is mostly a wrapper around [`shutil.copytree`](https://docs.python.org/3/library/shutil.html#shutil.copytree), so you can look there for documentation. Better documentation (and an overhaul of `install_tree`) will be added in #8289.

To solve your problem, make the following change:
```python
install_tree('mshadow', join_path(prefix.include, 'mshadow'))
install_tree('make', join_path(prefix, 'make'))
```
The ability to use things like `prefix.make` was added in #4591, which means that your Spack installation is over a year behind. I would encourage you to update to the latest version of Spack if you can, although I understand that can be difficult if you are using Spack in production. Spack is still in beta, so it is evolving rapidly and features like these are being added all the time.

**Comment by samfux84** [comment]
@adamjstewart Thank you very much for pointing to the source code.

We have multiple clusters, and one SPACK installations per cluster. The one that I am referring to in this issue is the oldest one that I have. I don't want to update SPACK there to not break things that are in production (at some point I will do a new, more recent SPACK installation and setup a newer software stack). On another cluster I have a much newer SPACK installation.
