### ISSUE TITLE
Fix qhull .pc file issue for matplotlib install

### ISSUE THREAD

**Issue by s-sajid-ali** [spack/spack#8546]
Continuing the discussion in [7855](https://github.com/spack/spack/issues/7855). @scheibelp 

### Description of the issue : 
The current install recipe for py-matplotlib fails to find the .pc file for qhull and this leads to a rebuild of qhull even if qhull is already installed. Where this causes an issue is if one is using intel compilers the relevant patch doesn't get applied as explained in [8303](https://github.com/spack/spack/issues/8303).

This issue is also referenced [here](https://github.com/matplotlib/matplotlib/issues/5745).

Can this be fixed by modifying the setup.cfg file ?

**Comment by scheibelp** [comment]
I can't find any good resources on altering the `setup.cfg` file - do you know of any? If not, I'd be more-inclined to define a `.pc` file for qhull manually and see if that helps. I think I could take a crack at that by 6/28

**Comment by s-sajid-ali** [comment]
I haven't dealt with that before but I'll have a look as well.

**Comment by adamjstewart** [comment]
#12164 removed the `qhull` dependency from `py-matplotlib`. We now rely on the vendored copy of `qhull` that comes with `py-matplotlib`. I'm assuming this issue is no longer an issue.
