### ISSUE TITLE
difficult to pass OpenFOAM env to a CMakePackage

### ISSUE THREAD

**Issue by olesenm** [spack/spack#8579]
As noted by @sbna. He's trying to build a spack package as a CMakePackage as a module for OpenFOAM.  Getting the OpenFOAM environment properly initialized before the build is rather _challenging_.

Is there a spack-like or cmake-like means of sourcing a shell script prior to starting the cmake?
@alalazo - any experience there?

If not, it might be a case of generating a build wrapper ourselves and then calling that. Not really elegant, but might work reliably.

/mark

**Comment by olesenm** [comment]
Partly addressed by https://github.com/spack/spack/pull/8592

**Comment by alalazo** [comment]
> Is there a spack-like or cmake-like means of sourcing a shell script prior to starting the cmake?
@alalazo - any experience there?

Is there something wrong or missing with using `EnvironmentModifications.from_sourcing_file`?

**Comment by olesenm** [comment]
This might be a way for Simone to try. But I noticed from the catalyst package that the upstream source also wraps their cmake with a `cmake.sh` call instead, so I guess this is not exclusively an OpenFOAM issue.

Thanks for taking a look. I'll close it though.

/mark

**Comment by sbna** [comment]
> Is there something wrong or missing with using EnvironmentModifications.from_sourcing_file? @alalazo 

yes, the command that sources the openfoam bashrc environment fails. 

The command should be: ['/bin/bash', '-c', '"source <openfoam_install_path>/etc/bashrc &> /dev/null && python -c \"import os, json; print(json.dumps(dict(os.environ)))\""']

but the the bash command is not wrapped by the apexes and the backslash in the python command are missing

**Comment by sbna** [comment]
We found that the hanging is not related to the missing apexes but to the filesystem of our cluster. I close the issue.
