### ISSUE TITLE
spack clean --python-cache deletes .pyc files in installed packages

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#8608]
I just noticed that `spack clean --python-cache` deletes `.pyc` files in Spack-installed packages. If you install Python or Python-packages with Spack and then run `spack --debug clean --python-cache`, you can reproduce this.

We should probably ignore the `opt/` directory when traversing the filesystem. I don't think it will hurt anything, but it does slow down the Python installation temporarily and cause `spack clean` to take longer than it should.

Also, the `help` message for `--all` needs to be updated with the `-p` flag.

P.S. Can we finally delete https://github.com/spack/spack/blob/develop/bin/spack#L59,L81? These files haven't existed for years, and now we have a simple solution to clean them if users run into trouble.

@healther

**Comment by healther** [comment]
I can do the clean up and the documentation, but I'd still remove the `.pyc` files in the `opt` folder. The background is that I had people use packages with the system python, and I'm not certain how python reacts to mismatched `.pyc` stuff.

In my mind `spack clean -a` should be the solution for "I screwed up by having something wrong in my cache and just want to have spack clean itself up". The temporary speed loss shouldn't matter, as you are not supposed to screw up that often ;)
