### ISSUE TITLE
spack fetch does not fetch patches

### ISSUE THREAD

**Issue by zephyr111** [spack/spack#8637]
### Expected Result

The command "spack fetch [package]" fetches an archive, but not patches required for its installation.
Since some supercomputers block any direct access to the internet, the user must download each patch file manually (in addition to upload prefetched packages). Otherwise, the command "spack install" will freeze, waiting for fetching required patches.
Thus, it would be better to download patch files during a fetch (or to add an option to retrieve them).

### Steps to reproduce the issue

```console
$ spack fetch perl
==> Using cached archive: /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/cache/perl/perl-5.26.2.tar.gz
==> Using cached archive: /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/cache/perl/cpanm-5.26.2.tar.gz
$ spack install perl
==> pkgconf is already installed in /panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-6.2.0/pkgconf-1.4.2-ee3vfl4nwkiyh3d4kjxnd35g4k4iiuq2
==> ncurses is already installed in /panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-6.2.0/ncurses-6.1-ebsk7waunygpogrdjpdz66vjejqu3sym
==> readline is already installed in /panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-6.2.0/readline-7.0-be7rllfeh3aoruimktzxv57b5vsesbiv
==> gdbm is already installed in /panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-6.2.0/gdbm-1.14.1-j3hi4vxq5ftk7ablb2wftqo5di23j6tw
==> Installing perl
==> Using cached archive: /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/cache/perl/perl-5.26.2.tar.gz
==> Using cached archive: /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/cache/perl/cpanm-5.26.2.tar.gz
==> Staging archive: /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/stage/perl-5.26.2-nuce4hn4ijcs72zlhd3aaz36kctrxtsc/perl-5.26.2.tar.gz
==> Created stage in /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/stage/perl-5.26.2-nuce4hn4ijcs72zlhd3aaz36kctrxtsc
==> Staging archive: /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/stage/resource-cpanm-nuce4hn4ijcs72zlhd3aaz36kctrxtsc/App-cpanminus-1.7042.tar.gz
==> Created stage in /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/stage/resource-cpanm-nuce4hn4ijcs72zlhd3aaz36kctrxtsc
==> Moving resource stage
	source : /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/stage/resource-cpanm-nuce4hn4ijcs72zlhd3aaz36kctrxtsc/App-cpanminus-1.7042/
	destination : /panfs/panasas/cnt0041/cvt1605/jrichard/spack/var/spack/stage/perl-5.26.2-nuce4hn4ijcs72zlhd3aaz36kctrxtsc/perl-5.26.2/cpanm/cpanm
==> Fetching https://src.fedoraproject.org/rpms/perl/raw/004cea3a67df42e92ffdf4e9ac36d47a3c6a05a4/f/perl-5.26.1-guard_old_libcrypt_fix.patch
...
```

**Comment by adamjstewart** [comment]
Does `spack mirror` fetch patches? My understanding was that `spack mirror` should be used for users on air-gapped networks. I think `spack fetch` is just for testing downloads, but I could be wrong.

**Comment by healther** [comment]
> I think spack fetch is just for testing downloads, but I could be wrong.

that may have been the original idea, but a) we use it in our CI exactly as @zephyr111 tried to use it (I'm wondering why we didn't ran into this problem) and b) if it is supposed to test the downloads, shouldn't it then test ALL the necessary downloads (and ideally execute the same code as `spack install` is doing)?

Unfortunately my attempts to understand the fetching code so far proved insufficient

**Comment by zephyr111** [comment]
Ok, you are right, `spack mirror` should be used in this case.
However, `spack mirror` does not fetch patches either.

**Comment by adamjstewart** [comment]
I agree, `spack fetch` should probably fetch _everything_ that is downloaded during installation. `spack mirror` should as well.

**Comment by scheibelp** [comment]
I'll be looking into having a PR for this by Friday 7/13
