### ISSUE TITLE
add support for precice

### ISSUE THREAD

**Issue by olesenm** [spack/spack#8643]
https://www.precice.org

I've already started with a package, but need to discuss with the developers about their cmake installation before we can add it.

WIP: https://github.com/olesenm/spack/tree/precice

**Comment by adamjstewart** [comment]
No need to open an issue, we accept pull requests even if they don't close an issue.

**Comment by olesenm** [comment]
OK, I just wanted to have a place to track and cross-reference before the pull request is ready to go. And to avoid duplicate effort while a pull request matures.
