### ISSUE TITLE
OpenMPI > 1.10.x including rpath from --with-xx statements into compiler wrapper

### ISSUE THREAD

**Issue by jrood-nrel** [spack/spack#8670]
So I still have an issue of OpenMPI > 1.10.x putting `/usr/lib64` in the mpi wrappers because I am using `--with-verbs` that finds IB libraries in `/usr/lib64` and the compiler I'm using isn't in `/usr/lib64` so the executables I build with OpenMPI 3.1.0, for example have GLIBC errors at runtime. I feel like we should be putting the `extra_rpaths` into the OpenMPI wrappers with rpath as well. I'm just not sure of the best approach. Hoping to find a solution to this so I can use OpenMPI > 1.10.x without hacking the wrappers myself. It really surprises me that I seem to be the only one with this problem though.

**Comment by scheibelp** [comment]
Fixed by https://github.com/spack/spack/pull/8687

> It really surprises me that I seem to be the only one with this problem though.

The issue was a bit more specific than the title suggests - in order to run into the problem you have to:

* Be using a compiler outside of /usr
* Be using the OpenMPI wrappers outside of a Spack build

(the fix PR was more clear on the details)
