### ISSUE TITLE
broken environment configuration under tcsh

### ISSUE THREAD

**Issue by anderson2981** [spack/spack#8734]
spack fails to correctly setup the environment under tcsh with the following lines in .cshrc

setenv SPACK_ROOT /Users/mike/software/Spack
source $SPACK_ROOT/share/spack/setup-env.csh

The following error is returned when sourcing the configuration file:
    spack: Command not found.

reverting commit  06418a3dcd5dda0c45151ceec08aa91d8e3fa651 fixes this issue

**Comment by adamjstewart** [comment]
Can you see if #8732 fixes this?

**Comment by anderson2981** [comment]
I see that #8732 is merged into develop. This does not fix the error I am seeing. However, it appears it can be fixed by moving 
`_spack_pathadd PATH       "$SPACK_ROOT/bin"`
to come before the call to 
`spack --print-shell-vars csh`
in share/spack/setup-env.csh
