### ISSUE TITLE
Prepare GPG Keys for Package Signing

### ISSUE THREAD

**Issue by opadron** [spack/spack#8789]
From #8626, we still need GPG Keys for package signing.  While they are not necessary right now, we'll eventually need to work them into the package-building CI pipelines that we are working on.

**Comment by tgamblin** [comment]
@opadron: I had a discussion with LLNL folks and you should just go ahead and generate the keypair for this.

Three points:
1. I think it doesn't make sense to put either an LLNL or a Kitware signature on the binaries; we should use a cert with a name like "Spack", and the email can either be mine or we can use something like `maintainers@spack.io`.   I kind of like the latter better, as it indicates that the packages are effectively signed by the community.

2. We (LLNL) will need to get a copy of the private key so that we can archive it in a safe place.  So can you send me that securely, once you have generated a cert?

3. We should probably set an expiration date on the initial cert we generate.  1 year seems reasonable.  I *believe* that GPG can work like most code signing certs, where if the *code* is signed while the cert is valid, then the package can be verified even if the cert is still expired.  Might be good to ensure that things actually work that way.

**Comment by opadron** [comment]
Sounds good.

1. Here are the key settings that I have prepared.  Let me know if these are acceptable:

```
Key Type: RSA (sign only)
Key Length: 2048 bits
Key Expires After: 1 year (For example, Friday August 9 2019, if created today).
Real Name: Spack Maintainers
Email: maintainers@spack.io
Comment: package-signing key
Passphrase: None (left blank)
```

2. Of course!  Once we agree on the details and I make the key, we'll get in touch out-of-band for the exchange.

3. Correct, it is the date that the signature was *made*, and not that it is *checked*, that is considered when verifying.  Otherwise, the general utility of cryptographic signatures would be extremely limited.  The signing key need only be valid at the time of signing.

To be absolutely sure, however, I went ahead and tested this idea:

```
faketime '1435 minutes ago' gpg --full-generate-key
```

after which I created a key that would expire in "one day", effectively giving me a key that would *actually* expire in five minutes.

```Bash
echo Hello > message.txt
gpg --detach-sign --armor -u maintainers@spack.io message.txt
gpg --verify message.txt.asc message.txt
```
```
gpg: Signature made Thu Aug  9 11:30:50 2018 EDT
gpg:                using RSA key 17E34AA1B4553C2588A7E7811B7D0B1A24399E30
gpg:                issuer "maintainers@spack.io"
gpg: Good signature from "Spack Maintainers (package-signing key) <maintainers@spack.io>"
Primary key fingerprint: 17E3 4AA1 B455 3C25 88A7  E781 1B7D 0B1A 2439 9E30
```

after five minutes, gpg warns me that the signing key has since expired, but confirms the signature is "Good", nonetheless.

```
gpg: Signature made Thu Aug  9 11:30:50 2018 EDT
gpg:                using RSA key 17E34AA1B4553C2588A7E7811B7D0B1A24399E30
gpg:                issuer "maintainers@spack.io"
gpg: Good signature from "Spack Maintainers (package-signing key) <maintainers@spack.io>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 17E3 4AA1 B455 3C25 88A7  E781 1B7D 0B1A 2439 9E30
```

and it completely refuses to sign with an expired key, no doubt since it would produce unverifiable signatures:

```Bash
echo Hello2 > message2.txt
gpg --detach-sign --armor -u maintainers@spack.io message2.txt
```
```
gpg: skipped "maintainers@spack.io": Unusable secret key
gpg: signing failed: Unusable secret key
```

As you can see, this would have worked fine just five minutes ago!

**Comment by tgamblin** [comment]
@opadron: just to follow up on the telcon, this looks great.  I think this can be marked done as soon as you have the keys generated and the private keys checked into our secret store.

**Comment by scottwittenburg** [comment]
@opadron  I think we're ready for this now.  After our work session last week, we discovered some issues in creating keys that could be trusted by the gitlab runner user to sign packages, and I think we also left with some questions about how, precisely, we wanted to get those keys into the hands of the gitlab runner jobs anyway, though we do have at least one possible mechanism at the moment.

On my end, I worked around it for the time being by adding a WIP commit to my PR which allows installing unsigned packages, but obviously that's not what we want down the road.  Do you have any spare cycles to look into these things at the moment?

ping @aashish24

**Comment by opadron** [comment]
I went ahead and created the keys that will be used for package signing.

@tgamblin, you can find them on the kubernetes cluster ("package-signing-key" under the "spack" namespace).

@scottwittenburg, if you set up a test project on gitlab.spack.io, then I can go in and add the keys as CI secrets.  You'll need to do this since gitlab needs your github access token for the integration.  

@tgamblin, you will need to do the same once we're ready to set up the real thing -- and for the same reason.
