### ISSUE TITLE
Cmake 3.11.4 fails to install on toss_3

### ISSUE THREAD

**Issue by stephdempsey** [spack/spack#8793]
Summary
 depends_on("cmake@3.9.6:"...) grabs 3.11.4 as the latest safe version, but this version fails to build on toss_3 with intel 17.0.0

### Expected Result

successful install of cmake

### Actual Result

[  5%] Built target cmzlib
/tmp/dempsey/spack-stage/spack-stage-71vU5U/cmake-3.11.4/Utilities/cmbzip2/bzlib.c(1433): warning #266: function "fdopen" declared implicitly
        fp = fdopen(fd,mode2);
             ^

### Steps to reproduce the issue
spack install cmake%intel@17.0.0

### Information on your system

rzgenie @ llnl.  Intel 17.0.0 compiler.
rh7
todd/greg please let me know what else you're looking for from this sys info...

**Comment by tgamblin** [comment]
3.12 is out and in `develop` -- does it work?

**Comment by stephdempsey** [comment]
3.12 successfully installed with intel 17 on toss_3.

**Comment by tgamblin** [comment]
ok I suspect this is a bug in CMake that was fixed in 3.12.
