### ISSUE TITLE
How to deal with the situation when dependencies need to be in the same directory for successful installation?

### ISSUE THREAD

**Issue by fanne-stat** [spack/spack#8816]
I am trying to add a package called wrf.

http://forum.wrfforum.com/viewtopic.php?f=5&t=7099

Based on this instruction, it seems like netcdf-fortran and netcdf should be installed in the same directory to make wrf install successfully. But with spack they are in different directories. Is there a way to solve this problem?

**Comment by davydden** [comment]
> Is there a way to solve this problem?

Apart from conctacting developers, I don’t see any

**Comment by adamjstewart** [comment]
I ran into the exact same problem with #2809! Unfortunately I don't have any better advice for you that what @davydden has already said. It would be really nice if other packages respected the fact that NetCDF C and Fortran libs have split development.

**Comment by tgamblin** [comment]
I would patch WRF if at all possible.  That, or create a package just for WRF that merges the two by symlinking them into one prefix.  We could potentially try to make that easy. It would be great to get WRF in spack.

**Comment by adamjstewart** [comment]
What does EasyBuild do? They have an entire page dedicated to WRF: 
http://easybuild.readthedocs.io/en/latest/Typical_workflow_example_with_WRF.html

**Comment by citibeth** [comment]
That looks like a complicated patch.  I'd set up the patch on a GitHub branch and pester the UCAR folks to integrate it.

**Comment by baberlevi** [comment]
patch in #9851. Not sure if I'll bother trying to get it merged, I read the process for getting commits into wrf and it seems very cumbersome
