### ISSUE TITLE
Cannot build tar.xz packages

### ISSUE THREAD

**Issue by paul-chelarescu** [spack/spack#8829]
I have a build machine setup with gcc 7 which is not able to extract tar.xz packages. 
```
==> Staging archive: /var/build/paul/spack/var/spack/stage/gettext-0.19.8.1-4z3teabaygcrw6a6faq5baer2m3hilqd/gettext-0.19.8.1.tar.xz
xz: error while loading shared libraries: liblzma.so.5: cannot open shared object file: No such file or directory
/var/build/paul/spack/opt/spack/linux-scientificcernslc6-x86_64/gcc-7.3.0/tar-1.30-uhlna6sdc77pjcjhqc2er7dcfav6wkqm/bin/tar: Child returned status 127
/var/build/paul/spack/opt/spack/linux-scientificcernslc6-x86_64/gcc-7.3.0/tar-1.30-uhlna6sdc77pjcjhqc2er7dcfav6wkqm/bin/tar: Error is not recoverable: exiting now
==> Error: ProcessError: Command exited with status 2:
    '/var/build/paul/spack/opt/spack/linux-scientificcernslc6-x86_64/gcc-7.3.0/tar-1.30-uhlna6sdc77pjcjhqc2er7dcfav6wkqm/bin/tar' '-xf' '/var/build/paul/spack/var/spack/stage/gettext-0.19.8.1-4z3teabaygcrw6a6faq5baer2m3hilqd/gettext-0.19.8.1.tar.xz'
==> Error: [Errno 2] No such file or directory: '/var/build/paul/spack/var/spack/stage/gettext-0.19.8.1-4z3teabaygcrw6a6faq5baer2m3hilqd/spack-expanded-archive/spack-build.out'
```
xz is externally installed in a remote file system.
For some reason spack is unable to extract the xz archive because it fails to load the liblzma library which is inside the xz installation directory. If I manually use tar -xf to extract the archive there are no problems. Similarly, if I manually add /path/to/xz/lib to LD_LIBRARY_PATH inside compilers.yaml spack extracts the archive with no problem.

This issue seems similar to https://github.com/spack/spack/issues/315 and the only fix that I have been able to find is to switch to the gz format (https://github.com/spack/spack/pull/316).  Is it possible to submit a PR for this and switch the archive type to gz for the gettext package?

**Comment by healther** [comment]
Sure you can simply open a PR (or just change the URL for yourself), but this seems like a more fundamental problem that should be fixed.

Can you add some more context to your description of your system? Is `liblzma` on your `LD_LIBRARY_PATH` outside of `spack`?

**Comment by paul-chelarescu** [comment]
liblzma is indeed inside LD_LIBRARY_PATH outside of spack.

**Comment by tgamblin** [comment]
So I’m confused. Can you say what happens when you run the following:

* `tar` outside spack with no `LD_LIBRARY_PATH`
* `tar` outside spack with liblzma from spack in `LD_LIBRARY_PATH`

Also can you say which `xz` that is in your original build output?  Is that a system install of xz?

And finally, what tar is being run? Is it system `tar` or one of yours?

**Comment by alalazo** [comment]
@paul-chelarescu Closing as the issue has been inactive for a year and a half (and as far as I know we got no other report of `.xz` not working). Feel free to reopen if you want to reply to the questions above and continue the discussion.
