### ISSUE TITLE
documented `spack views symlink` syntax doesn't work

### ISSUE THREAD

**Issue by SteVwonder** [spack/spack#8836]
I received an error when I tried to run the code in the spack views docs: https://spack.readthedocs.io/en/latest/workflows.html?highlight=loads%20exclude#fine-grain-control

### Expected Result

```
spack view symlink --dependencies yes --exclude appsy appsy
<generating view>
```

### Actual Result

```
spack view symlink --dependencies yes --exclude appsy appsy
==> Error: unrecognized arguments: --dependencies --exclude
```

The documented command should be:
`spack view --dependencies yes --exclude appsy symlink /path/to/MYVIEW/ appsy`

Should the course of action be to change the documentation or the command?  Presumably the changes to the command were intentional and the docs are just out of date?

**Comment by healther** [comment]
You are right that the documentation is wrong there. Since the output of `spack view -h` gives the correct syntax we should just fix the docs. If you care to open a PR feel free to do so, otherwise I'll do it tomorrow.

**Comment by SteVwonder** [comment]
:+1: I can put a PR together tonight.  Thanks!
