### ISSUE TITLE
amg2013 website went offline

### ISSUE THREAD

**Issue by junghans** [spack/spack#8846]
The amg2013 website (https://codesign.llnl.gov/amg2013.php) went offline and hence we cannot fetch the tarball anymore.

So remove?

**Comment by adamjstewart** [comment]
There appear to be duplicate `amg` and `amg2013` packages. These can be merged. The new download URL is at https://github.com/LLNL/AMG.

**Comment by junghans** [comment]
@adamjstewart this is #5909 all over again ;-)
