### ISSUE TITLE
Spack doesn't find cross compiler exe

### ISSUE THREAD

**Issue by scheibelp** [spack/spack#8860]
`spack compiler find` does not find `/usr/local/bin/powerpc64-bgq-linux-gcc`. This binary does not match the naming scheme that Spack expects, in particular the prefix "powerpc64-bgq-linux-". There are likely conceptual issues to sort out here also: this compiler is available on the frontend node but compiles for the compute node, so the associated architecture should be for the compute node. At the moment I'm not sure how that would be determined other than by inferring it from the name.

See: https://github.com/spack/spack/pull/8834

### Information on your system

The vulcan system at LLNL, a BGQ OS.

**Comment by alalazo** [comment]
BGQ support has been deprecated a while ago. Closing.
