### ISSUE TITLE
Unable to download the current JDK from Oracle

### ISSUE THREAD

**Issue by hartzell** [spack/spack#8877]
Summary

I can't download the current JDK: `jdk@8u172-b11`.

### Expected Result

To be able to download (and install) the current default jdk (`jdk@8u172-b11`).

### Actual Result

Failure, see below

### Steps to reproduce the issue

I can download the previous tarball (I killed it via ^C after it ran for a bit) but the current one fails immediately.

```console
(alice)[14:20:45]spack-rpaths>>./bin/spack fetch jdk@8u141-b15
==> Fetching http://download.oracle.com/otn-pub/java/jdk/8u141-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-8u141-linux-x64.tar.gz
##                                                                         3.1%^C
==> Error: Keyboard interrupt.
(alice)[14:20:59]spack-rpaths>>./bin/spack fetch jdk@8u172-b11
==> Fetching http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.tar.gz
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.tar.gz failed.
==> Error: All fetchers failed for jdk-8u172-b11-bv2vbfc57hceiolmuhi23rmgh5sjg4to
(alice)[14:21:05]spack-rpaths>>
```

### Information on your system

This includes:

 1. Mac (shouldn't matter for the `fetch` stage).
 2. None that seem relevant (famous last words...).

**Comment by adamjstewart** [comment]
Can you try #8613?

**Comment by codecircuit** [comment]
For me it worked to update the version. I added:

`version('8u181-b13', 'ef599e322eee42f6769991dd3e3b1a31', curl_options=curl_options,
            url='http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz')`

to `package.py`.

**Comment by mmpozulp** [comment]
@codecircuit 's suggestion to add and use a different version worked for me too. Why?

**Comment by adamjstewart** [comment]
They must have deprecated that version and it is no longer available for download.

Anyway, #8613 has now been merged, and the new version of `jdk` should be available for download. Feel free to add a newer version of 1.8 if you need it.
