### ISSUE TITLE
Regression: petsc build fails on macOS 10.12.6

### ISSUE THREAD

**Issue by goxberry** [spack/spack#8882]
### Summary

As of [13cf6d55e42042a5b605c2d91c1ac68e41466164](https://github.com/spack/spack/commit/13cf6d55e42042a5b605c2d91c1ac68e41466164),

```console
$ spack install petsc
```

succeeds. But this command fails on my laptop running macOS 10.12.6 at commit [8e1cc26be7b1d6594ada6d1433ce4fa5b1bb4de1](https://github.com/spack/spack/commit/8e1cc26be7b1d6594ada6d1433ce4fa5b1bb4de1). 

### Expected Result

`spack install petsc` succeeds.

### Actual Result

`spack install petsc` fails.

Full logs (`spack-build.out`, PETSc's `configure.log`, `packages.yaml`, output of `spack find`) are at https://gist.github.com/goxberry/b1cbe35d711300cd03ff13831d41fe5d.

The specific failure inside PETSc BuildSystem appears to be 

```console
Checking for program /usr/local/Cellar/open-mpi/3.1.1/bin/mpicc...found
                Defined make macro "CPP" to "/usr/local/Cellar/open-mpi/3.1.1/bin/mpicc --use cpp32"
              Pushing language C
Executing: /usr/local/Cellar/open-mpi/3.1.1/bin/mpicc --use cpp32  -I/var/folders/37/zqjg7vn97kggmzjdbcm55j6h001b24/T/petsc-aBEbNA/config.setCompilers  /var/folders/37/zqjg7vn97kggmzjdbcm55j6h001b24/T/petsc-aBEbNA/config.setCompilers/conftest.c 
Possible ERROR while running preprocessor: exit code 256
stderr:
clang: error: unsupported option '--use'
clang: error: no such file or directory: 'cpp32'
Source:
#include "confdefs.h"
#include "conffix.h"
#include <stdlib.h>
Preprocess stderr before filtering:clang: error: unsupported option '--use'
clang: error: no such file or directory: 'cpp32'
:
Preprocess stderr after filtering:clang: error: unsupported option '--use'clang: error: no such file or directory: 'cpp32':
              Popping language C
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Cannot find a C preprocessor
```

### Steps to reproduce the issue

```console
$ cd $SPACK_ROOT
$ git fetch
$ git checkout 8e1cc26be7b1d6594ada6d1433ce4fa5b1bb4de
$ spack install petsc
```

### Information on your system

My machine is running macOs 10.12.6. A `packages.yaml` is included in the GitHub gist at https://gist.github.com/goxberry/b1cbe35d711300cd03ff13831d41fe5d.

**Comment by davydden** [comment]
could you please try `git bisect` to see which commit broke it?

**Comment by goxberry** [comment]
`git-bisect` indicates the first bad commit is [cd9691de5314fcfaf17d47a63264acef5716c0b6](https://github.com/spack/spack/commit/cd9691de5314fcfaf17d47a63264acef5716c0b6).

**Comment by davydden** [comment]
@becker33 @tgamblin ping. https://github.com/spack/spack/pull/4692

**Comment by tgamblin** [comment]
@becker33: can you look at why this fails?

**Comment by goxberry** [comment]
@tgamblin Added the output to the gist under `spack-dash-d-output.log`, and added the `spack -d install petsc` "configure.log" file to `spack-dash-d-configure.log` in the gist.

**Comment by tgamblin** [comment]
Yes
