### ISSUE TITLE
cmake build using clang fails with post 7/10/2018 branch

### ISSUE THREAD

**Issue by burgreen** [spack/spack#8887]
On MacOSX-10.13.4 and clang-9.1.0-apple compiler, an older version of spack (downloaded 7/10/2018) builds cmake-3.11.0 fine.

Using the same system with a later spack version (downloaded 8/3/2018) fails on cmake-3.11.0 build in bootstrap phase with error:

`The C++ compiler does not support C++11 (std::unique_ptr).`

The exact same package.py was used for both build processes (attached). 

[package.py.txt](https://github.com/spack/spack/files/2258686/package.py.txt)

**Comment by davydden** [comment]
Please use ‘git bisect’ to track the first commit that broke it

**Comment by burgreen** [comment]
$ git bisect bad
cd9691de5314fcfaf17d47a63264acef5716c0b6 is the first bad commit
commit cd9691de5314fcfaf17d47a63264acef5716c0b6
Author: becker33 <becker33@llnl.gov>
Date:   Wed Aug 1 15:48:00 2018 -0700

    cc: package search paths come before dependency paths (#4692)
   
    Spack currently prepends include paths, library paths, and rpaths to the compile line.  This causes problems when a header or library in the package has the same name as one exported by one of its dependencies.  The *dependency's* header will be preferred over the package's, which is not what most builds expect.  This also breaks some of our production codes.
   
    This restores the original cc behavior (from *very* early Spack) of parsing compiler arguments out by type (`-L`, `-I`, `-Wl,-rpath`) and reconstituting the full command at the end.
   
    `<includes> <other_args> <library dirs> <rpaths>`
   
    This differs from the original behavior in one significant way, though: it *appends* the library arguments so that dependency libraries do not shadow those in the build.
   
    This is safe because semantics aren't affected by *interleaving* `-I`, `-L`, and `-Wl,-rpath` arguments with others, only with each other (so the order fo two `-L` args affects the search path, but we search for all libraries on the command line using the same search path).
   
    We preserve the following:
    1. Any system directory in the paths will be listed last.
    2. The root package's include/library/RPATH flags come before flags of the same type for any dependency.
    3. Order will be preserved within flags passed by the build (except system paths, which are moved to be last)
    4. Flags for dependencies will appear between the root flags and the system flags, and the flags for any dependency will come before those for *its* dependencies (this is for completeness -- we already guarantee this in `build_environment.py`)

:040000 040000 5276ebe4fd2507993cd14a2413b3bf28a17214b2 73def5031cfee2fdfa2f3b1bf8d3043e06a7bc0c M    lib

**Comment by davydden** [comment]
@becker33 another issue related to https://github.com/spack/spack/pull/4692
