### ISSUE TITLE
Subclassing of a package fails to expose resources such as patches correctly

### ISSUE THREAD

**Issue by jcftang** [spack/spack#8908]
Summary

When subclassing a package, the resources such as  patches do not get propagated in the right way...

E.g. If I had a package like this...

```
from spack import *
from spack.pkg.builtin.kaldi import Kaldi as KaldiSpack

class Kaldi(KaldiSpack):
    version('master', git='https://github.com/kaldi-asr/kaldi.git')
```

The path to "openfst-1.4.1.patch" is incorrect, a full path would need to be provided to the patch for it to work. Currently if I want to extend an existing package I would need to copy all the resources to the extended package as well.

The above is pretty easy to reproduce reliably, just pick any package that has a patch or additional resource files and extend it.

**Comment by becker33** [comment]
@jcftang is this resolved by #12051?

**Comment by jcftang** [comment]
@becker33 I would need to verify this next week, but from eyeballing https://github.com/spack/spack/pull/12051/files it looks it's going to work.

**Comment by becker33** [comment]
@jcftang I'm pretty confident it should fix it, I'll mark that PR as closing this issue and correct me if that turns out not to be true.
