### ISSUE TITLE
Errors installing tau on linux-ubuntu18.04-x86_64

### ISSUE THREAD

**Issue by imnasnainaec** [spack/spack#8909]
I ran `spack install tau` and got the following pile of errors:

    ==> Installing tau
    ==> Using cached archive: /home/dror/spack/var/spack/cache/tau/tau-2.27.1.tar.gz
    ==> Staging archive: /home/dror/spack/var/spack/stage/tau-2.27.1-bqpht5jbgj2aao7bv3vvs7lar2lyvnbw/tau-2.27.1.tar.gz
    ==> Created stage in /home/dror/spack/var/spack/stage/tau-2.27.1-bqpht5jbgj2aao7bv3vvs7lar2lyvnbw
    ==> No patches needed for tau
    ==> Building tau [Package]
    ==> Executing phase: 'install'
    ==> Error: ProcessError: Command exited with status 2:
        'make' '-j8' 'install'

    10 errors found in build log:

     89      Copy /tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/tools/src/contrib/CubeReader.j
            ar to /home/dror/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/tau-2.27.1-bqpht5jbg
            j2aao7bv3vvs7lar2lyvnbw/x86_64/lib
     90     ====================================================
     91     ... done
     92     ***********************************************************************
    >> 93     grep: ./utils/FixMakefile.info: No such file or directory
    >> 94     grep: ./utils/FixMakefile.sed: No such file or directory
     95     NOTE: Saving configuration environment to /tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2
            .27.1/.configure_env/258794744e2942facc2c02d8985d8b39
     ...
     224    make[1]: Entering directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/example
            s/pi'
     225    Makefile:16: /tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/x86_64/lib/Makefile.tau
            -communicators-phase-mpi-pdt-openmp: No such file or directory
    >> 226    make[1]: *** No rule to make target '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1
            /x86_64/lib/Makefile.tau-communicators-phase-mpi-pdt-openmp'.  Stop.
     227    make[1]: Leaving directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/examples
            /pi'
     ...
     234    make[1]: Entering directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/example
            s/autoinstrument'
     235    Makefile:16: /tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/x86_64/lib/Makefile.tau
            -communicators-phase-mpi-pdt-openmp: No such file or directory
    >> 236    make[1]: *** No rule to make target '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1
            /x86_64/lib/Makefile.tau-communicators-phase-mpi-pdt-openmp'.  Stop.
     237    make[1]: Leaving directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/examples
            /autoinstrument'
     238    make[1]: Entering directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/example
            s/reduce'
     239    Makefile:16: /tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/x86_64/lib/Makefile.tau
            -communicators-phase-mpi-pdt-openmp: No such file or directory
    >> 240    make[1]: *** No rule to make target '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1
            /x86_64/lib/Makefile.tau-communicators-phase-mpi-pdt-openmp'.  Stop.
     241    make[1]: Leaving directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/examples
            /reduce'
     242    touch .clean
     ...
     847    make[2]: Entering directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/src/Pro
            file'
     848    Installing libTauMpi-communicators-phase-mpi-pdt-openmp.a in /home/dror/spack/opt/spack/
            linux-ubuntu18.04-x86_64/gcc-7.3.0/tau-2.27.1-bqpht5jbgj2aao7bv3vvs7lar2lyvnbw/x86_64/li
            b
     849    if [ -d /home/dror/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/tau-2.27.1-bqpht5j
            bgj2aao7bv3vvs7lar2lyvnbw/x86_64/lib ] ; then true; \
     850                       else mkdir /home/dror/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.
            3.0/tau-2.27.1-bqpht5jbgj2aao7bv3vvs7lar2lyvnbw/x86_64/lib ;fi
     851    /bin/cp libTauMpi-communicators-phase-mpi-pdt-openmp.a /home/dror/spack/opt/spack/linux-
            ubuntu18.04-x86_64/gcc-7.3.0/tau-2.27.1-bqpht5jbgj2aao7bv3vvs7lar2lyvnbw/x86_64/lib
     852    make[2]: Leaving directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/src/Prof
            ile'
    >> 853    /usr/bin/x86_64-linux-gnu-ld: cannot find -liberty
    >> 854    /usr/bin/x86_64-linux-gnu-ld: cannot find -lz
    >> 855    collect2: error: ld returned 1 exit status
     856    Makefile:403: recipe for target 'libTAUsh-communicators-phase-mpi-pdt-openmp.so' failed
    >> 857    make[1]: *** [libTAUsh-communicators-phase-mpi-pdt-openmp.so] Error 1
     858    make[1]: Leaving directory '/tmp/dror/spack-stage/spack-stage-tqsVdd/tau-2.27.1/src/Prof
            ile'
     859    Makefile:177: recipe for target 'install' failed
    >> 860    make: *** [install] Error 2

**Comment by bassenj** [comment]
I see practically the same error pattern for `spack install tau+download~mpi` on linux-sles12-x86_64.

**Comment by bassenj** [comment]
The error occurs for other versions on tau as well.

**Comment by scheibelp** [comment]
Can you add some of the details listed under the build-error issue template (see: https://github.com/spack/spack/issues/new?labels=build-error&template=build_error.md)?

Both for the install on `linux-sles12` as well as the OS you were trying with in your original post (if that was different - https://github.com/spack/spack/issues/8909#issuecomment-457247676 gave me the impression it was).

**Comment by bassenj** [comment]
I am sorry, I don't have these files any more. For the build I mentioned in https://github.com/spack/spack/issues/8909#issuecomment-457247676
I used spack on the develop branch, cloned on 12/18/2018.

After this post I updated spack to 3b1fb7d9ff35d0264eea8bf62568a1c0575b72fc.
With this version of spack, `tau+openmp~papi` builds; however, the variant with `papi` hangs in a deadlock during `install` phase of `papi`.

**Comment by hainest** [comment]
I've encountered this problem on both lassen (Power9) at Livermore and cori (x86) at NERSC. The information below is for lassen.

    $ git -C spack log -1 --oneline
       d333e1472 (HEAD -> develop, origin/develop, origin/HEAD) tests: check min required python version with vermin (#14289)

    $ spack --version
      0.13.3

    $ uname -a
      Linux lassen709 4.14.0-115.10.1.1chaos.ch6a.ppc64le #1 SMP Thu Aug 8 15:51:58 PDT 2019 ppc64le ppc64le ppc64le GNU/Linux

    $ lsb_release -d
      Description:	Red Hat Enterprise Linux Server release 7.6 (Maipo)

    $ spack compilers
      ==> Available compilers
      -- clang rhel7-ppc64le ------------------------------------------
      clang@8.0.1

      -- gcc rhel7-ppc64le --------------------------------------------
      gcc@7.3.1  gcc@4.9.3  gcc@4.8.5

      -- xl rhel7-ppc64le ---------------------------------------------
      xl@16.1

      -- xl_r rhel7-ppc64le -------------------------------------------
      xl_r@16.1

    $ spack/bin/spack spec --install-status tau
      Input spec
      --------------------------------
       -   tau

      Concretized
      --------------------------------
       -   tau@2.28.2%gcc@7.3.1~bgq+binutils~comm~craycnl~cuda+fortran~gasnet+io+libdwarf+libelf+libunwind~likwid~mpi~ompt~opari~openmp+otf2+papi+pdt~phase~ppc64le+pthreads~python~scorep~shmem~x86_64 arch=linux-rhel7-power9le
      [+]      ^binutils@2.32%gcc@7.3.1+gold+headers+libiberty~nls~plugins arch=linux-rhel7-power9le
      [+]          ^zlib@1.2.11%gcc@7.3.1+optimize+pic+shared arch=linux-rhel7-power9le
      [+]      ^libdwarf@20180129%gcc@7.3.1 arch=linux-rhel7-power9le
      [+]          ^libelf@0.8.13%gcc@7.3.1 arch=linux-rhel7-power9le
      [+]      ^libunwind@1.2.1%gcc@7.3.1~xz arch=linux-rhel7-power9le
      [+]      ^otf2@2.2%gcc@7.3.1 arch=linux-rhel7-power9le
      [+]      ^papi@5.7.0%gcc@7.3.1+example~infiniband~lmsensors~powercap~rapl arch=linux-rhel7-power9le
      [+]      ^pdt@3.25.1%gcc@7.3.1 arch=linux-rhel7-power9le

All of the dependencies have installed without issue.

    $ spack -d install -v -j1 tau >tau.log 2>&1

[tau.log](https://github.com/spack/spack/files/4000795/tau.log)

I believe the relevant entries from the log are the errors seen during configure:

    grep: ./utils/FixMakefile.info: No such file or directory
    grep: ./utils/FixMakefile.sed: No such file or directory

This suggests that `configure` was not run from the `spack location -s tau` directory. Indeed, if I change to that directory, run the configure command contained in `tau.log`, and then `make install`, I get a complete, error-free build.

Tagging tau devs @sameershende and @khuck.

**Comment by khuck** [comment]
Looking at the log, if this is on ppc64le, it shouldn't be configuring TAU with elf or dwarf.  But I don't know if that's related to the pdb build error.

Is this the latest TAU spack package?

**Comment by hainest** [comment]
@khuck

> Looking at the log, if this is on ppc64le, it shouldn't be configuring TAU with elf or dwarf. But I don't know if that's related to the pdb build error.

This is ppc64le with RHEL 7.6. Should it be using elfutils, instead?
 
> Is this the latest TAU spack package?

The HEAD I'm using is d333e1472 from Dec 24, 2019. The last change to the TAU package relative to then was ab98ef17659c413 on Nov 29, 2019.

**Comment by khuck** [comment]
Testing it myself on our system, it looks like PDT is the problem - it detects that it is on a ppc64le system and decides that the XL compilers should be used.  Let me see if I can get you a patch for the PDT spack package.

**Comment by khuck** [comment]
@hainest Here's a patch, I will submit a Spack PR (thanks for reporting this!):

```
diff --git a/var/spack/repos/builtin/packages/pdt/package.py b/var/spack/repos/builtin/packages/pdt/package.py
index 6d246a9b7..2d099b8df 100644
--- a/var/spack/repos/builtin/packages/pdt/package.py
+++ b/var/spack/repos/builtin/packages/pdt/package.py
@@ -43,6 +43,10 @@ def configure(self, spec, prefix):
             options.append('-icpc')
         elif self.compiler.name == 'pgi':
             options.append('-pgCC')
+        elif self.compiler.name == 'gcc':
+            options.append('-GNU')
+        else:
+            raise InstallError('Unknown/unsupported compiler family')
 
         configure(*options)
 
```

**Comment by khuck** [comment]
Here's the PR: https://github.com/spack/spack/pull/14590

**Comment by hainest** [comment]
@imnasnainaec @bassenj @scheibelp  Did the #14590 fix the issue for you? It did for me.

**Comment by imnasnainaec** [comment]
I'm no longer trying to use Tau. If the issues others have identified here are all resolved, this can be closed.

**Comment by alalazo** [comment]
Closing following @imnasnainaec comment
