### ISSUE TITLE
bzip.org down

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [spack/spack#8924]
![screenshot from 2018-08-09 09-37-29](https://user-images.githubusercontent.com/14250760/43902396-fe9a826a-9bb7-11e8-9097-44e40c3b65fa.png)

**Comment by JusticeForMikeBrown** [comment]
Also [hosted here](https://fossies.org/linux/misc/bzip2-1.0.6.tar.gz) with same checksum

**Comment by balay** [comment]
https://lwn.net/Articles/762264/

**Comment by hartzell** [comment]
py-flake8 depends on this...
