### ISSUE TITLE
Python package reports python not required

### ISSUE THREAD

**Issue by 23skdu** [spack/spack#8973]
Summary

### Steps to reproduce the issue

```
$ spack install py-pydf2%gcc@5.4.0^python@3.5.2+ucs4
==> Error: py-pydf2 does not depend on python
```
Other packages I needed to install, install fine...

**Comment by adamjstewart** [comment]
There is no `py-pydf2` package in Spack. Is this something you wrote yourself? If so, can you share the `package.py` file?

**Comment by alalazo** [comment]
Closing as `py-pydf2` is not a current package in Spack.
