### ISSUE TITLE
changed install_tree() from #8289 breaks at least openfoam-com and foam-extend

### ISSUE THREAD

**Issue by tz-rrze** [spack/spack#9001]
Commit 73c978dd from #8289 breaks existing packages, e.g. openfoam-com, due to the changed, more restrictive interface of `install_tree()` which now only accepts `symlinks `as optional argument but no longer `ignore `as the internally called shutil.copytree() did originally.
```
diff --git a/lib/spack/llnl/util/filesystem.py b/lib/spack/llnl/util/filesystem.py
index ace6cfd..40eb6a7 100644
-def install_tree(src, dest, **kwargs):
+def install_tree(src, dest, symlinks=True):
```

e.g.
```
==> Ran patch() for openfoam-com
==> Building openfoam-com [Package]
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Error: TypeError: install_tree() got an unexpected keyword argument 'ignore'

.../spack/var/spack/repos/builtin/packages/openfoam-com/package.py:701, in install:
        695    ignored = ['src', 'applications', 'html', 'Guides']
        696    for d in dirs:  
        697        install_tree(
        698                d,
        699                join_path(self.projectdir, d),
        700                ignore=shutil.ignore_patterns(*ignored),
  >>    701                symlinks=True)
        702
        703        etc_dir = join_path(self.projectdir, 'etc')
        704        rewrite_environ_files(  # Adjust etc/bashrc and etc/cshrc

See build log for details:
...
```

@adamjstewart: I'm not sure if the original behavior of `install_tree()` should/could be restored or if changing openfoam-com, and foam-extend, and maybe others is easier ...

**Comment by adamjstewart** [comment]
Sorry about that, I completely missed that `ignore=` argument.

How important is `ignore=` support? It looks like it is only used in the FOAM packages. It would certainly be doable, although non-trivial, to support, at least in some limited fashion. I took a look at the [source code for `shutil.copytree`](https://github.com/python/cpython/blob/master/Lib/shutil.py#L413) and it shouldn't be that hard to do.

@tgamblin Looking at the source code, it actually seems a lot more elegant and powerful than our implementation. I like the recursive calls to `copytree`, although that would interfere with our `tty.debug` messages.

**Comment by tz-rrze** [comment]
The handling of symbolic links seems to have changed, too. Relative links suddenly become absolute links!
Why is there a `os.path.abspath(target)` in `copy_tree()`?

```
        if symlinks and os.path.islink(s):
            # Note that this won't rewrite absolute links into the old
            # root to point at the new root. Should we handle that case?
            target = os.readlink(s)
            os.symlink(os.path.abspath(target), d)
```
Relative links from within the build-tree will become absolute links to the build-tree in the installation-tree; which no longer resolve once the build-tree is deleted :-(

**Comment by adamjstewart** [comment]
@tgamblin or @scheibelp may be able to comment on the absolute path problem. I added this line based off of https://github.com/spack/spack/pull/8289#issuecomment-404989757.

**Comment by tz-rrze** [comment]
No time right now to understand what they meant in that comment.

But here are two examples of the problem:

**Original install_tree() - i.e. before the commit**
lrwxrwxrwx 1 hpcins0h hpcinst 29 Aug 16 20:34 /opt/linux-centos7-x86_64/gcc-8.2.0/openfoam-com-1806-p7c5cnpxvd5nl2mhqax7lzpnj7kn2kuq/platforms/linux64GccDPInt32RpathOpt/lib/librunTimePostProcessing.so -> librunTimePostProcessing.so.8
lrwxrwxrwx 1 hpcins0h hpcinst 26 Aug 16 20:33 /opt/linux-centos7-x86_64/gcc-8.2.0/openfoam-com-1806-p7c5cnpxvd5nl2mhqax7lzpnj7kn2kuq/applications/solvers/multiphase/compressibleInterFoam/twoPhaseMixtureThermo/lnInclude/twoPhaseMixtureThermo.C -> ../twoPhaseMixtureThermo.C
**New install_tree() - i.e. after the commit** (with the ignore removed)
lrwxrwxrwx 1 hpcins0h hpcinst 93 Aug 16 22:22 /opt/linux-centos7-x86_64/gcc-8.2.0/openfoam-com-1806-p7c5cnpxvd5nl2mhqax7lzpnj7kn2kuq/platforms/linux64GccDPInt32RpathOpt/lib/librunTimePostProcessing.so -> /var/tmp/hpcins0h/spack-stage/spack-stage-yKpgZc/OpenFOAM-v1806/librunTimePostProcessing.so.8
lrwxrwxrwx 1 hpcins0h hpcinst 72 Aug 16 22:21 /opt/linux-centos7-x86_64/gcc-8.2.0/openfoam-com-1806-p7c5cnpxvd5nl2mhqax7lzpnj7kn2kuq/applications/solvers/multiphase/compressibleInterFoam/twoPhaseMixtureThermo/lnInclude/twoPhaseMixtureThermo.C -> /var/tmp/hpcins0h/spack-stage/spack-stage-yKpgZc/twoPhaseMixtureThermo.C

While the _ignore_ was a quite specific problem of FOAM only, I expect more packages to install/copy linked files ...

**Comment by scheibelp** [comment]
I'll be working on this tomorrow (8/17). I anticipate I'll have a fix ready by the end of the day.

**Comment by scheibelp** [comment]
I updated the `openfoam-*` packages (currently the only ones using the `ignore` keyword) as part of #9019 - let me know if I didn't do that right.
