### ISSUE TITLE
Error when binutils in packages.yaml

### ISSUE THREAD

**Issue by goxberry** [spack/spack#9009]
### Expected Result

With a `packages.yaml` containing

```
packages:
  binutils:
    paths:
      binutils@2.31.1 %clang@9.0.0-apple: /usr/local/Cellar/binutils/2.31.1
```

the commands `spack spec binutils` and `spack install binutils` should succeed.

### Actual Result

```
oxberry1@Uvalde:~/spack$ 3.2>spack spec binutils
Input spec
--------------------------------
binutils

Concretized
--------------------------------
==> Error: packages.yaml entries cannot be virtual packages:
  in "/Users/oxberry1/.spack/packages.yaml", line 2, column 3: binutils
oxberry1@Uvalde:~/spack$ 3.2>spack install binutils
==> Error: packages.yaml entries cannot be virtual packages:
  in "/Users/oxberry1/.spack/packages.yaml", line 2, column 3: binutils
```

### Steps to reproduce the issue

Add external install of `binutils` to `packages.yaml`.

```console
$ spack spec binutils
$ spack install binutils # probably optional
```

### Information on your system

Using macOS 10.12.6, with a minimal `packages.yaml` shown above (my actual `packages.yaml` is longer), with spack at commit `f838b5e8c093b60916beb7d62d177301688088b2` (current with `origin/develop` at time of posting). Also tried https://github.com/spack/spack/pull/9007 rebased on top of `f838b5e8c093b60916beb7d62d177301688088b2`, so adding the latest version of `binutils` to spack did not resolve this issue.

-----

**Comment by adamjstewart** [comment]
Are you sure this is the only thing in your `packages.yaml`? You didn't modify the `binutils` package to be a virtual provider did you? I'm unable to reproduce this on macOS 10.13.6:
```console
$ cat ~/.spack/packages.yaml
packages:
  binutils:
    paths:
      binutils@2.31.1 %clang@9.0.0-apple: /usr/local/Cellar/binutils/2.31.1
$ spack spec binutils
Input spec
--------------------------------
binutils

Concretized
--------------------------------
binutils@2.31.1%clang@9.0.0-apple+gold~libiberty patches=0a0ca84889b6727dc0cc88650f55fd79452dddba762674a83a153374792fdaac ~plugins arch=darwin-highsierra-x86_64 
$ spack install binutils
==> binutils@2.31.1 : externally installed in /usr/local/Cellar/binutils/2.31.1
==> binutils@2.31.1 : generating module file
==> binutils@2.31.1 : registering into DB
```

**Comment by adamjstewart** [comment]
I can't reproduce it with this `packages.yaml` either. Can you move all of your configs out of the way, create a fresh Spack clone, and try with that?

**Comment by adamjstewart** [comment]
Nope, still can't reproduce. It looks like [this line](https://github.com/spack/spack/blob/develop/lib/spack/spack/package_prefs.py#L60) is raising the error. @tgamblin wrote this function in #2699. Any ideas?

**Comment by goxberry** [comment]
I figured it out. Another branch I was working on delegated `binutils` to a virtual package provider. Virtual packages are indexed in `$HOME/.spack/cache/providers/`, and `binutils` was listed as a virtual package in `builtin-index.yaml`. Deleting the `binutils` entry in this file solved the problem.
