### ISSUE TITLE
Unexpected behaviour of 'spack mirror create'.

### ISSUE THREAD

**Issue by skosukhin** [spack/spack#9015]
There are several moments with `spack mirror create` that I would like to clarify.
1. The first question is regarding the flag `--one-version-per-spec`. As far a I understand [get_matching_versions](https://github.com/spack/spack/blob/e04fb382b17ecab15ab7dffe3f92a4a282d4a256/lib/spack/spack/mirror.py#L104-L136) recieves a list of concrete specs, which means that there is only one matching version for each spec. So, it seems that we need to pass not only concrete specs but input specs (polished with the information from `packages.yaml`) as well for the flag to make sense. Correct?
2. The second question is related to the first one. The following lines of code seem to be the reason for the flag not to work properly at all:
https://github.com/spack/spack/blob/e04fb382b17ecab15ab7dffe3f92a4a282d4a256/lib/spack/spack/mirror.py#L118-L120
As far as I understand, if we limit the number of output versions, the function stops after checking the first `num_versions` versions. The problem is that not all version among the first `num_versions` potentially satisfy our spec and the condition should be something like
    ```python
    if num_versions and len(matching_spec) >= num_versions:
        break
    ```
    You can try
    ```console
    $ spack mirror create mpich
    ```
3. The third question is regarding the fact that `spack mirror create` does not try to use `list_url`. Compare the results of
    ```console
    $ spack mirror create cdo
    ```
    and
    ```console
    $ spack fetch cdo
    ```
4. The last question is regarding the format of the command line. As far as I understand, the user can specify several specs at once. Specs can contain multivalue variants: `cdo grib2=grib-api`. Does `spack mirror create` parse several such specs correctly? For the command `spack env` we have a special separator `--` for this.

Thank you.

**Comment by scheibelp** [comment]
Regarding (3), https://github.com/spack/spack/pull/8993 should resolve it (it is focused on a different issue but should resolve this too)

Not sure about 1, 2, and 4 yet

**Comment by scheibelp** [comment]
Regarding (1)

> As far a I understand get_matching_versions recieves a list of concrete specs, which means that there is only one matching version for each spec.

That appears to be correct. I would consider it a bug. I don't immediately see a sensible way for the user to provide options that would get multiple specs. I think the easiest thing to do would be to drop the version constraint in `get_matching_versions`.

Also, `--one-version-per-spec` appears to be poorly named: it is not actually a flag but rather you specify a number of versions to download like `--one-version-per-spec=2`

Regarding (2), that does appear to be a bug

Regarding (4), `spack mirror` *should* parse multiple specs correctly.
