### ISSUE TITLE
Finalize Spack Release and PR Testing Infrastructure

### ISSUE THREAD

**Issue by opadron** [spack/spack#9018]
Following up on #8362, #7116, and #8361.

We've recently reached a major milestone in provisioning the infrastructure that will support Spack's upcoming automated release and PR testing process.  In addition to providing several new services, we've also taken the opportunity to migrate service for the main [spack.io](https://www.spack.io) website to the same infrastructure, consolidating in a single deployment.  At the present, we are hosting the following services:

 - www.spack.io: the main Spack website.
 - [gitlab.spack.io](https://gitlab.spack.io): the Gitlab instance that will power Spack's custom pipelines.  These pipelines will build, test, sign, and upload pre-compiled binaries for several of the most popular Spack packages.
 - [cdash.spack.io](https://cdash.spack.io): the CDash instance that will ingest, aggregate, and present data on the results of the above pipelines.  We'll be able to use this resource to quickly identify packages that are not building successfully and determine what changes are likely to address any issues that prevent their successful build.
 - [k8s.spack.io](https://k8s.spack.io): dashboard app for administrators of the kubernetes cluster that powers all these services.

There are a few minor matters that still need to be addressed.  This issue will track them.

- [x] The Gitlab instance is still running on Gitlab Community Edition.  We still need to secure a license for ultimate edition and migrate.
- [x] The CDash instance is running, but does not seem to be working quite right.  We'll need to investigate and fix any issues in the recently provided `kitware/cdash` docker container.
- [x] Move resource definitions from [spack/testing-sandbox](https://github.com/spack/testing-sandbox) to a more permanent home.

**Comment by tgamblin** [comment]
@opadron: minor nit: can we please get the main Spack site set up NOT to redirect [spack.io](https://spack.io) to [www.spack.io](https://www.spack.io)?  We advertise it as `spack.io`, and I think it's simpler if the `www` doesn't appear there.

**Comment by opadron** [comment]
Done.

That also reminds me: the work on the k8s resources that describe our services currently live at [spack/testing-sandbox](https://github.com/spack/testing-sandbox).  We should think about moving that work to a more permanent home, now that things are approaching stability.

**Comment by tgamblin** [comment]
@opadron: what were you thinking?  I think a repo in the Spack organization is probably the right place, but maybe it needs some polish and a new name.  What about just `spack-infrastructure`?  or `spack-kube`?

**Comment by opadron** [comment]
I think [spack/infrastructure](https://github.com/spack/infrastructure) makes sense.

Also, the CDash service should be working properly, now.

**Comment by tgamblin** [comment]
Awesome! Do you want me to move the repo?

**Comment by opadron** [comment]
Sure, that would be great!

**Comment by tgamblin** [comment]
@opadron @scottwittenburg: I moved the repo to `spack-infrastructure`.  Hope that doesn't break any scripts :).

**Comment by scottwittenburg** [comment]
Thanks for the heads up, I don't think it's going to break anything on my end yet.

**Comment by opadron** [comment]
Closing since the above points have all been addressed.
