### ISSUE TITLE
"spack test" errors in Python 3.7

### ISSUE THREAD

**Issue by scheibelp** [spack/spack#9028]
`spack test` produces errors on Python 3.7 in the Travis build

### Error Message

See: https://travis-ci.org/spack/spack/jobs/418414627 from https://github.com/spack/spack/pull/8819

### Information on your system

This occurs on Travis. I have not tested it with Python 3.7 elsewhere.

**Comment by adamjstewart** [comment]
#8289 also introduced tests that seemingly only failed on Python 3.7 but these problematic tests were reverted in #9019. I'll try to install Python 3.7 locally and investigate.

**Comment by adamjstewart** [comment]
I tried using a Spack-installed Python 3.7.0 but wasn't able to reproduce the build error.

**Comment by alalazo** [comment]
Sorry, I didn't see this before. I duplicated the issue at #9067 and fixed it in #9068

**Comment by alalazo** [comment]
@adamjstewart @scheibelp The issue wasn't python 3.7, but the fact that python 3.7 sits on a vm with a newer GNU Make.
