### ISSUE TITLE
Spack-installed curl doesn't work with git on OS X

### ISSUE THREAD

**Issue by eschnett** [spack/spack#903]
I notice that a Spack-installed curl doesn't work with git on OS X. The symptoms are the following:
- in general, using `git` to obtain a package source works fine
- when Spack uses a Spack-installed `git`, there is an error (see below)
- after removing the `curl` dependency in `git`, things work again

The error is

```
==> Trying to clone git repository:
  https://github.com/eschnett/SimulationIO.git
  on branch master
Cloning into 'SimulationIO'...
fatal: unable to access 'https://github.com/eschnett/SimulationIO.git/': SSL certificate problem: unable to get local issuer certificate
Cloning into 'SimulationIO'...
fatal: unable to access 'https://github.com/eschnett/SimulationIO.git/': SSL certificate problem: unable to get local issuer certificate
==> Fetching from [git] https://github.com/eschnett/SimulationIO.git failed.
==> Error: All fetchers failed for simulationio-master-s36kmlzps2qziewfs6qyrtr6kqmdlzcl
==> Error: Installation process had nonzero exit code.
```

**Comment by mathstuf** [comment]
Hrm, seems we need to ship a cert bundle. Or build curl properly so that it uses the system bundle.

**Comment by alalazo** [comment]
@eschnett Is this still the case?

**Comment by alalazo** [comment]
Closing for now. Please reopen if still relevant.
