### ISSUE TITLE
mpich@3.2.1 does not configure as F90 and F90FLAGS are set

### ISSUE THREAD

**Issue by wscullin** [spack/spack#9084]
### Steps to reproduce the issue

```console
$ spack install mpich@3.2.1%gcc@8.2.0 cflags="-mtune=knl -march=knl" cxxflags="-mtune=knl -march=knl" fflags="-mtune=knl -march=knl"  device=ch3 +hydra netmod=tcp +pmi+romio~verbs arch=linux-centos7-x86_64
```

produces
```
==> Error: ProcessError: Command exited with status 1:
    '/soft/packaging/spack/var/spack/stage/mpich-3.2.1-skhis6nt34sffs5ohnrv36jhjtv6um7i/mpich-3.2.1/configure' '--prefix=/soft/packaging/spack/builds/linux-centos7-x86_64/gcc-8.2.0/mpich-3.2.1-skhis6nt34sffs5
ohnrv36jhjtv6um7i' '--enable-shared' '--with-pm=hydra' '--with-pmi=yes' '--enable-romio' '--without-ibverbs' '--with-device=ch3:nemesis:tcp'

1 error found in build log:
     419    checking for type of weak symbol alias support... pragma weak
     420    checking whether __attribute__ ((weak)) allowed... yes
     421    checking whether __attribute__ ((weak_import)) allowed... yes
     422    checking whether __attribute__((weak,alias(...))) allowed... yes
     423    checking for multiple weak symbol support... yes
     424    checking for shared library (esp. rpath) characteristics of CC... done (results in src/env/cc_shlib.conf)
  >> 425    configure: error: F90 and F90FLAGS are replaced by FC and FCFLAGS respectively in this configure, please unset F90/F90FLAGS and set FC/FCFLAGS instead and rerun configure again.
```

### Platform and user environment

```commandline
$ uname -a 
Linux kingly 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.4.1708 (Core)
``` 
### Attempt at resolution

It looked like a similar configure issue in mvapich was solved in PR https://github.com/spack/spack/pull/8698. That said, attempting to do the same for mpich failed. After adding: 
```python
    def setup_environment(self, spack_env, run_env):
        # mpich configure fails when F90 and F90FLAGS are set
        spec = self.spec
        spack_env.unset('F90')
        spack_env.unset('F90FLAGS')
```
to the `package.py` failed to unset `F90` which was set by the spack produced gcc@8.2.0 module. Changing `compilers.yaml` not to use the module seemed to solve the issue, though now `F90` is unset when other packages seek it out.

**Comment by adamjstewart** [comment]
Do other packages need `F90`? We also set `F77` and `FC`. I would remove that line from the module file and see how far you get. We can always delete it from the `gcc` package.

**Comment by wscullin** [comment]
Removing it from the module file worked as well. I'm a little surprised that the `def setup_environment` didn't work though. `F90` was still set.

**Comment by scheibelp** [comment]
> I'm a little surprised that the def setup_environment didn't work though. F90 was still set.

Package environment modifications are applied before compiler environment modifications. I'll try to think up a sensible way to support customizing that by the end of this week (8/31).

**Comment by pramodk** [comment]
Encountered this issue today on our system as well.
