### ISSUE TITLE
Installation issue: nlopt - package.py thinks it is CMake, but is actually AutoTools

### ISSUE THREAD

**Issue by neilflood** [spack/spack#9109]
### Steps to reproduce the issue

```console
$ spack install nlopt 
  >> 3    CMake Error: The source directory "..../var/spack/stage/nlopt-2.4.2-roeg2gnpas2acdguelja6pfuali2i5hp/nlopt-2.4.2" does not appear to contain CMakeLists.txt.
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux athena52 4.4.132-94.33-default #1 SMP Tue May 29 20:09:56 UTC 2018 (76aae3b) x86_64 x86_64 x86_64 GNU/Linux
``` 
### Additional information

I am very puzzled. Spack is reporting that there is no CMakeLists.txt in the tar.gz for this package. It is quite correct, there is not. However, nlopt/package.py is very clear that this is a CMakePackage. The contents of the tar.gz indicate that it is actually an AutoTools package. 

The checksum for the tar.gz is identical to the one given in the package.py, so I am clearly working with the same file as the original author of the package.py, but I can't see how it could ever have worked. 

I thought I had better ask, rather than dive in and break things, in case I have missed something fundamental.

**Comment by neilflood** [comment]
OK, a bit more digging. The package.py points to both a git URL and a tar.gz URL. The two are completely incompatible. The tar.gz has a different directory layout, a different build system (configure instead of cmake), and the README inside it points to a different URL home for the software (http://ab-initio.mit.edu/nlopt instead of https://github.com/stevengj/nlopt). It does appear to be the same author, though.  

It seems that only the latest released tar.gz (2.5.0 - later than when the Spack package was created) contains the CMake build system, all earlier releases are for AutoTools. 

Unless anyone knows a clever way of making a Spack package work for both cmake and configure, I would guess we have to choose to support only the latest released tar.gz. 

I will assemble a pull request with this.

**Comment by healther** [comment]
You can look eg at #9092, I solved it by overriding all cmake methods for older versions. But @adamjstewart pointed me to other packages which derive from Package rather than any build system

**Comment by neilflood** [comment]
This has been dealt with by https://github.com/spack/spack/pull/9110
