### ISSUE TITLE
Develop Branch: Import error: Python 2.7.14 : cannot import name cmp_to_key

### ISSUE THREAD

**Issue by ptbremer** [spack/spack#9116]
On LLNLs linux clusters using a clean checkout of the develop branch I get 

[tbremer@quartz2498:spack]$ spack
Traceback (most recent call last):
 File "/usr/gapps/topology/spack/bin/spack", line 53, in <module>
    import spack.main  # noqa
  File "/usr/gapps/topology/spack/lib/spack/spack/main.py", line 36, in <module>
    import pstats
  File "/usr/tce/packages/python/python-2.7.14/lib/python2.7/pstats.py", line 28, in <module>
    from functools import cmp_to_key
ImportError: cannot import name cmp_to_key

This is using Python 2.7.14

The master branch works as expected 

### Information on your system

Replicated on 

quartz.llnl.gov Linux 
surface.llnl.gov Linux

**Comment by alalazo** [comment]
Can you try with the same python:
```console
$ python --version
Python 2.7.15rc1
$ python -c 'import pstats'
```
? Is it working?

**Comment by healther** [comment]
you should be able to find that one out by using something like
```
import functools
print(functools.__path__)
```
Putting it directly above the failing line in the spack sources should work, otherwise you need to ensure that you use the same python binary, that spack uses.

**Comment by ptbremer** [comment]
So I found the problem but I am not sure what the correct way of fixing is. Here is what happens

I checked out my fork of spack which still has "master" as the default branch. Then I execute the setup step on that (very old) checkout

. spack/share/spack/setup-env.sh

It turns out that the master used its own version of functools.py which does not contain cmp_to_key. By using the setup I create a spack/lib/spack/external/functools.pyc file

Now I switch to the develop branch. While that correctly removes 

spack/lib/spack/external/functools.py

it will leave the 

spack/lib/spack/external/functools.pyc

in place. From then on, every time you try to execute the spack/bin/spack script you will pick up this file instead of the correct functoools.py, because we explicitly add spack//lib/spack/external to the system path first (Line 50 in spack/bin/spack) 

Simply removing the offending file fixes the issue. 

The fix is to either advance the master or to somehow document that you need to clean all temporary files when you switch branches

**Comment by healther** [comment]
FYI we have a `spack clean --python-cache`, which should also take care of this. Unfortunately I have no idea where to put the documentation of this issue though...

Just out of curiosity: What is our use of `master` anyways?

**Comment by ptbremer** [comment]
Also spack clean --python-cache does not actually help you here since /bin/spack itself will not work

**Comment by healther** [comment]
> @healther removed that stuff so he should know 🤔😄

Is "@adamjstewart told me to" enough? :D 

On a more serious note: Is there a valid use case for `master`? Personally I don't see it. Either you want to stay up to date, then you basically have to use `develop` or you want to stay on a fixed version and at most manually back port single PRs, then you just take a random commit from develop and start from there. (Full disclosure, we do the latter with our system). 
I _might_ be able to be convinced of a versioning scheme, but for that to be useful we would need to track packages and core separately, and I'm not sure if this is worth the pain. So I'd vote for simply deleting `master` (unless I'm missing some obvious use case).

Regarding the documentation: I'm not sure where we would be able to document it in a way that people would find it. Can we do a general `try: ... except:` block if `spack` is invoked without the debug mode and make it produce an error which points to the docs?

**Comment by tgamblin** [comment]
`master` is the "stable" release branch... for whatever definition we have for stable.  Releases *should* start coming more quickly once we have CI set up (happening very very soon).  So, yeah the point of `master` is that there's some version we blessed out there that you could base your work on, rather than a random commit in `develop`.  Because we don't have much CI for packages right now, that doesn't mean much, but it will mean more when we do.

Yeah I'm not convinced that docs will help much.  I agree.

Two options:
1. What if we restored the orphan checks *if* the command is `clean`?  We could check that from `bin/spack`.  I think it's kind of ugly for a relatively rare issue, and it doesn't really prevent the issue.
2. We are planning on adding lazier module loading soon.  If we do that, then maybe `bin/spack clean -a` will almost always work because `functools` will never actually be imported when that command is run.  So do nothing for now, and wait for that.

**Comment by healther** [comment]
I'd vote for option 2, if it turns out that we can't get it lazy enough to guarantee to run `spack clean` we can still think about option 1

**Comment by tgamblin** [comment]
Closing in favor of option 2.
