### ISSUE TITLE
Relicense Spack from LGPL-2.1 to MIT/Apache-2.0

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#9144]
### Summary
We are working to change the license for Spack from the current [LGPL-2.1 license](https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)) , to a dual license under the widely-accepted and common [MIT License](https://tldrlegal.com/license/mit-license) and the [Apache License, version 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)), so that users may choose the appropriate license for them.

### Why MIT / Apache-2.0?
We want to make this change so that Spack can be used as widely as possible. At many organizations, it is difficult or cumbersome to use LGPL-licensed packages, but a number of those organizations have expressed interest in contributing to Spack. The Apache 2.0 license contains important protection against patent aggression, but it is not compatible with the GPL, version 2. The MIT license allows Spack to be integrated with GPLv2 projects. We believe that this combination will appeal to the broadest possible base of users and contributors, and that it will enable us to grow the Spack community most effectively.

### What do contributors need to do?
We are asking for permission from *all* contributors to change the Spack license from LGPL-2.1 to a dual MIT/Apache 2.0 license for their past contribution(s).

If you agree to have all the code that you have contributed to Spack be relicensed in this way, please copy the message below, fill in the blanks with the email addresses you used to contribute to Spack, and paste it either:
1. into a comment on Spack issue https://github.com/spack/spack/issues/9137, or
2. into an email to [maintainers@spack.io](mailto:maintainers@spack.io)

**A note on emails:** You **only** need to post emails that appear in the Spack history.  To get these, clone `https://github.com/spack/spack.git` and use `git log` to see what emails you should use.  For example, Todd Gamblin appears in the logs in the following ways:

```console
$ git clone https://github.com/spack/spack.git
$ cd spack
$ git log --format='"%an" %ae' | grep -i Gamblin | sort | uniq
"George Todd Gamblin" gamblin2@llnl.gov
"Todd Gamblin" gamblin2@llnl.gov
"Todd Gamblin" tgamblin@llnl.gov
```

You may want to search for your name and `<your github username>@noreply.github.com`, and any other names you've used.  We just need enough to associate your consent with your contributions.

Here is the message text:
> My name is _________________________, and I am a contributor to Spack. I have used or may have used the following email address(es): ______________________________. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

By granting this permission, you are confirming that you have the right to make your contribution(s) to Spack and to grant this permission, and that if you made your contribution(s) in the course of your employment, that such contributions and consent have been authorized by your employer.

If we do not hear from you, we will assume that you do not consent to the relicensing and we will not relicense your contribution(s).

### Discussion
If you have any questions or concerns, please raise them by **[commenting on issue #9145](https://github.com/spack/spack/issues/9145)**.  We have made a separate issue to avoid notification spam for participants. We will try our best to respond promptly!

We are grateful to all the contributors who have contributed to Spack and look forward to their help and support in this effort!

Thanks!

**Comment by tgamblin** [comment]
My name is Todd Gamblin, and I am a contributor to Spack. I have used or may have used the following email address(es): `tgamblin@llnl.gov`, `gamblin2@llnl.gov`. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by goxberry** [comment]
My name is Geoff Oxberry, and I am a contributor to Spack. I have used or may have used the following email address(es): goxberry@gmail.com, oxberry1@llnl.gov. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by tgamblin** [comment]
@goxberry: can you add that to #9137? I was going to keep this one free of spam for discussion.

**Comment by tgamblin** [comment]
Pinging contributors here.  I will check people off this list as we receive consent.

- [ ] @AP97
- [ ] @AndrewGaspar
- [ ] @BarrySmith
- [ ] @BenBrands
- [ ] @CamelliaDPG
- [ ] @DarylGrunau
- [ ] @EmreAtes
- [ ] @FrankD412
- [ ] @HadrienG2
- [ ] @HenrikBengtsson
- [ ] @IanLee1521
- [ ] @JSquar
- [ ] @JavierCVilla
- [ ] @JohnWestlund
- [ ] @JusticeForMikeBrown
- [ ] @KineticTheory
- [ ] @Miles-Perry
- [ ] @Muakasan
- [ ] @NasrHassanein
- [ ] @NickRF
- [ ] @PDoakORNL
- [ ] @PaulDapolito
- [ ] @RasmusWL
- [ ] @Rombur
- [ ] @Sinan81
- [ ] @SteVwonder
- [ ] @TheQueasle
- [ ] @TomTheBear
- [ ] @TomasPuverle
- [ ] @Try2Code
- [ ] @YtterbiJum
- [ ] @Zehvogel
- [ ] @acfisher
- [ ] @adamjstewart
- [ ] @adammoody
- [ ] @adamqc
- [ ] @aharrison24
- [ ] @aholler2
- [ ] @akhilpatlolla
- [ ] @alalazo
- [ ] @alanw0
- [ ] @alfredo-gimenez
- [ ] @anne-glerum
- [ ] @aprokop
- [ ] @ashkan2200
- [ ] @ax3l
- [ ] @baberlevi
- [ ] @baip
- [ ] @balay
- [ ] @bcouturi

**Comment by tgamblin** [comment]
Pinging contributors here.  If you agree to have the code that you have contributed to Spack be relicensed to MIT and Apache-2.0, please post your consent to relicense at #9137. Thanks!

- [ ] @bd4
- [ ] @becker33
- [ ] @benjaminjeliot
- [ ] @benjaminwalters
- [ ] @berrill
- [ ] @besnardjb
- [ ] @bgoglin
- [ ] @bhatele
- [ ] @boegel
- [ ] @brettviren
- [ ] @briedel
- [ ] @brobey
- [ ] @brockpalen
- [ ] @bvanessen
- [ ] @carns
- [ ] @cedricchevalier19
- [ ] @certik
- [ ] @ch741
- [ ] @charlesareynolds
- [ ] @chissg
- [ ] @christianbaensch
- [ ] @chuckatkins
- [ ] @citibeth
- [ ] @cmacmackin
- [ ] @cpraveen
- [ ] @cugni
- [ ] @cwsmith
- [ ] @cyrush
- [ ] @daboehme
- [ ] @danielsjensen1
- [ ] @darachg
- [ ] @daveh86
- [ ] @davidbeckingsale
- [ ] @davidorman
- [ ] @davydden
- [ ] @dguibert
- [ ] @dhandeo
- [ ] @diaena
- [ ] @disheng222
- [ ] @djfitzgerald
- [ ] @dlukes
- [ ] @dorier
- [ ] @dpshelio
- [ ] @drbenmorgan
- [ ] @dshrader
- [ ] @dwootton-ny
- [ ] @eklee15
- [ ] @eloygil
- [ ] @erimar77
- [ ] @eschnett

**Comment by tgamblin** [comment]
- [ ] @estebanpauli
- [ ] @f-sim
- [ ] @fanne-stat
- [ ] @floquet
- [ ] @fpruvost
- [ ] @futuretristan
- [ ] @fwang2
- [ ] @g-mathias
- [ ] @gahansen
- [ ] @gardner48
- [ ] @gartung
- [ ] @gilmartinez
- [ ] @glennpj
- [ ] @gmatteo
- [ ] @gonsie
- [ ] @goxberry
- [ ] @grondo
- [ ] @gweodoo
- [ ] @gzagaris
- [ ] @hartzell
- [ ] @hauten
- [ ] @healther
- [ ] @hegner
- [ ] @hfp
- [ ] @homerdin
- [ ] @hppritcha
- [ ] @ibaned
- [ ] @irisTa56
- [ ] @isuruf
- [ ] @iulian787
- [ ] @ivotron
- [ ] @jack-morrison
- [ ] @jadickson
- [ ] @jadoro
- [ ] @jasonfenglu
- [ ] @jayavanth
- [ ] @jcftang
- [ ] @jedbrown
- [ ] @jgalarowicz
- [ ] @jimmy04500
- [ ] @jiseung
- [ ] @jkelling
- [ ] @jlingema
- [ ] @jmjwozniak
- [ ] @johnwfinigan
- [ ] @jonwong12
- [ ] @joshuata
- [ ] @jppelteret
- [ ] @jprotze
- [ ] @jrood-nrel

**Comment by tgamblin** [comment]
Pinging contributors here. If you agree to have the code that you have contributed to Spack be relicensed to MIT and Apache-2.0, please post your consent to relicense at #9137. Thanks!

- [ ] @js947
- [ ] @jsquyres
- [ ] @jthies
- [ ] @junghans
- [ ] @jungwonkim
- [ ] @junkudo
- [ ] @karenyyng
- [ ] @katherlee
- [ ] @keitat
- [ ] @kev40293
- [ ] @khuck
- [ ] @kiwifb
- [ ] @kljohann
- [ ] @koebbe
- [ ] @kothah
- [ ] @krafczyk
- [ ] @kshitij-v-mehta
- [ ] @kylefernandes
- [ ] @ledif
- [ ] @lee218llnl
- [ ] @lgarren
- [ ] @likask
- [ ] @lingnanyuan
- [ ] @loikki
- [ ] @louisvernon
- [ ] @lpoirel
- [ ] @luca-heltai
- [ ] @lucjaulmes
- [ ] @luigi-calori
- [ ] @luigicalori
- [ ] @luszczek
- [ ] @lyon-fnal
- [ ] @maiterth
- [ ] @mamelara
- [ ] @markcmiller86
- [ ] @mathomp4
- [ ] @mathstuf
- [ ] @matteoguglielmi
- [ ] @matthiasdiener
- [ ] @matz-e
- [ ] @matze
- [ ] @maxpkatz
- [ ] @mcfadden8
- [ ] @mcneish1
- [ ] @mdavezac
- [ ] @mdevlin1
- [ ] @mfherbst
- [ ] @mgsternberg
- [ ] @mic84
- [ ] @michaelkuhn

**Comment by tgamblin** [comment]
Pinging contributors here. If you agree to have the code that you have contributed to Spack be relicensed to MIT and Apache-2.0, please post your consent to relicense at #9137. Thanks!

- [ ] @mikebentley15
- [ ] @mikedep333
- [ ] @mjwoods
- [ ] @mkstoyanov
- [ ] @mkuron
- [ ] @mmpozulp
- [ ] @mmwolf
- [ ] @mpbelhorn
- [ ] @mplegendre
- [ ] @muffgaga
- [ ] @mwilliammyers
- [ ] @mwkrentel
- [ ] @mwm126
- [ ] @naromero77
- [ ] @nazavode
- [ ] @neilflood
- [ ] @nilsdeppe
- [ ] @nolta
- [ ] @nrichart
- [ ] @nshtg
- [ ] @nvarini
- [ ] @obreitwi
- [ ] @olesenm
- [ ] @oliver-pola
- [ ] @omor1
- [ ] @opadron
- [ ] @opoplawski
- [ ] @paul-chelarescu
- [ ] @paulhopkins
- [ ] @peetsv
- [ ] @philip-davis
- [ ] @pkondamudi
- [ ] @pkoro
- [ ] @pramodk
- [ ] @pramodskumbhar
- [ ] @psaravan
- [ ] @psychocoderHPC
- [ ] @ptbremer
- [ ] @raffenet
- [ ] @rajachan
- [ ] @rajeeja
- [ ] @raznikk
- [ ] @rc
- [ ] @reidpr
- [ ] @rgmiller
- [ ] @rmsds
- [ ] @roblatham00
- [ ] @rspavel
- [ ] @rvinaybharadwaj
- [ ] @s-sajid-ali

**Comment by tgamblin** [comment]
Pinging contributors here. If you agree to have the code that you have contributed to Spack be relicensed to MIT and Apache-2.0, please post your consent to relicense at #9137. Thanks!

- [ ] @samfux84
- [ ] @samuelkgutierrez
- [ ] @sarich
- [ ] @sashanicolas
- [ ] @sbna
- [ ] @scheibelp
- [ ] @scottwittenburg
- [ ] @serbanmaerean
- [ ] @shuds13
- [ ] @simo-tuomisto
- [ ] @simonflood
- [ ] @sixy6e
- [ ] @sjtbham
- [ ] @sknigh
- [ ] @skosukhin
- [ ] @snehring
- [ ] @spakin
- [ ] @ssergien
- [ ] @stefanosoffia
- [ ] @suzannepk
- [ ] @svenevs
- [ ] @t-brown
- [ ] @tgamblin
- [ ] @thecorkscrew
- [ ] @thilinarmtb
- [ ] @timrlaw
- [ ] @tinlun
- [ ] @tjesser-ucdavis-edu
- [ ] @tjhei
- [ ] @tjstavenger-pnnl
- [ ] @tmerrick1
- [ ] @tobbez
- [ ] @toffer93
- [ ] @trmwzm
- [ ] @twang15
- [ ] @tz-rrze
- [ ] @tzanio
- [ ] @tzislam
- [ ] @ursache
- [ ] @v-dobrev
- [ ] @verolero86
- [ ] @villegar
- [ ] @vishalkenchan
- [ ] @weijianwen
- [ ] @willfurnass
- [ ] @willkill07
- [ ] @wohlbier
- [ ] @womeld
- [ ] @wrwilliams
- [ ] @wscullin

**Comment by tgamblin** [comment]
Pinging contributors here. If you agree to have the code that you have contributed to Spack be relicensed to MIT and Apache-2.0, please post your consent to relicense at #9137. Thanks!

- [ ] @xfzhao
- [ ] @xjrc
- [ ] @ygrange
- [ ] @ynanyam
- [ ] @zackgalbreath
- [ ] @zenln
- [ ] @zepx
- [ ] @zzzoom

**Comment by luca-heltai** [comment]
I agree. I'm not sure I should be considered a contributor, though. :)

**Comment by tgamblin** [comment]
@luca-heltai: we just need the consent to make licensing easier :).  Can you add a comment on #9137 with the specific language mentioned above?  We had to run all of this past LLNL legal, so the procedure is rather specific, but we've tried to make it as lightweight as possible.

**Comment by likask** [comment]
I agree.

On 31 Aug 2018, at 08:07, Todd Gamblin <notifications@github.com<mailto:notifications@github.com>> wrote:


Pinging contributors here. If you agree to have the code that you have contributed to Spack be relicensed to MIT and Apache-2.0, please post your consent to relicense at #9137<https://github.com/spack/spack/issues/9137>. Thanks!

  *    @xfzhao<https://github.com/xfzhao>
  *    @xjrc<https://github.com/xjrc>
  *    @ygrange<https://github.com/ygrange>
  *    @ynanyam<https://github.com/ynanyam>
  *    @zackgalbreath<https://github.com/zackgalbreath>
  *    @zenln<https://github.com/zenln>
  *    @zepx<https://github.com/zepx>
  *    @zzzoom<https://github.com/zzzoom>

**Comment by ashkan2200** [comment]
I agree

**Comment by tgamblin** [comment]
@ashkan2200: sorry to be a bother but can you please post at #9137 with the specific language above? We need the copy-pasted text from this issue.

**Comment by boegel** [comment]
Two questions: is there an easy way to re-check all contributions that were made, and what will happen with contributions for which no approval is received, will they be removed?

**Comment by bd4** [comment]
I agree.

**Comment by tgamblin** [comment]
@bd4: can you please post at #9137 with the specific language above? We need the copy-pasted text from this issue. We had to run all of this past LLNL legal, so the procedure is rather specific, but we've tried to make it as lightweight as possible.

**Comment by tgamblin** [comment]
@akthoma: see above -- @baberlevi noticed that the GitHub API doesn't seem to list you as a contributor anymore due to your email changing.

**Comment by tgamblin** [comment]
@TomasPuverle: I think the only email you need to provide at [#9137](https://github.com/spack/spack/issues/9137#issuecomment-417680502) is GitHub's fake one: `tomaspuverle@users.noreply.github.com`.  Can you update your comment?

**Comment by mathstuf** [comment]
My name is Ben Boeckel, and I am a contributor to Spack. I have used or may have used the following email address(es):

  - Ben Boeckel <ben.boeckel@kitware.com>
  - Ben Boeckel <mathstuf@gmail.com>
  - Ben Boeckel <mathstuf@users.noreply.github.com>

I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by tinlun** [comment]
My name is Tin Huynh, and I am a contributor to Spack. I have used or may have used the following email address(es): ahuynh@nvidia.com. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by tgamblin** [comment]
@peetsv: not sure how best to contact you, but do you mind commenting on #9137 or sending email to maintainers@spack.io?

**Comment by fedepad** [comment]
@tgamblin Done!

**Comment by tgamblin** [comment]
@miles-perry: can you please add the blurb above to #9137?

**Comment by gilmartinez** [comment]
My name is Gilberto Martinez Jr, and I am a contributor to Spack. I
have used or may have used the following email address(es):
gilberto.martinez@lnls.br<mailto:gilberto.martinez@lnls.br>. I consent to change the current license contained in the
License file at https://github.com/spack/spack/blob/develop/LICENSE from
the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect
to all of my contributions to Spack.

Thank You.


On Sep 28, 2018, at 5:34 PM, Todd Gamblin <notifications@github.com<mailto:notifications@github.com>> wrote:


@Miles-Perry<https://github.com/Miles-Perry>: can you please add the blurb above to #9137<https://github.com/spack/spack/issues/9137>?

**Comment by PaulDapolito** [comment]
My name is Paul Dapolito, and I am a contributor to Spack. I have used or
may have used the following email address(es): pdapolito@hmc.edu. I consent
to change the current license contained in the License file at
https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1
license to the MIT License and Apache License 2.0 with respect to all of my
contributions to Spack.

**Comment by tgamblin** [comment]
Hi all, here is an update on the state of Spack relicensing:

1. **We have all the consents we need to relicense the entire Spack core (134 consents!)**
2. **We have consents covering **2,815 out of 2,877 packages** (333 consents!)**

So, we're nearly done. Thanks to everyone who has commented or emailed so far!  I initially had doubts whether we'd be able to do this at all, but with your help we've been able to get nearly all of the consents in what I think is a remarkably short period of time.

At this point, we are going to go forward with relicensing the core and most of the packages.  You should expect that to happen in the next couple of weeks.  We will change the LICENSE and COPYRIGHT files, as well as file headers for all the files we have consent for.  We will also change the CONTRIBUTING file to indicate the new license for inbound code.

**If you have not commented or emailed yet, but you intend to, please do so as soon as you can**.  We would like to include as many packages as possible in the switchover, so see the top this page (https://github.com/spack/spack/issues/9144) for instructions.  We will initially leave LGPL packages in the repo, but eventually we will either remove or rewrite them so that Spack is 100% Apache2/MIT.

Thanks again for helping this tedious process go so smoothly, and thanks to everyone for your many contributions to Spack!


If your name is in the list below, we still need consent for your contributions to the packages listed:

- [ ] @AP97 (`farmhash`)
- [ ] @YtterbiJum (`tmux`)
- [ ] @adamqc (`petsc`)
- [ ] @alcharal (`abyss`)
- [ ] @christianbaensch (`suite-sparse`)
- [ ] @clementval (`claw`)
- [ ] @disheng222 (`sz`)
- [ ] @edoapra (`nwchem`)
- [ ] @f-sim (`fenics`)
- [ ] @g-mathias (`libmatheval`)
- [ ] @glentner (`hadoop`)
- [ ] @isu-rassilon (`gapfiller`)
- [ ] @iulian787 (`cgm`, `meshkit`, `moab`, `netgen`, `oce`)
- [ ] @jack-morrison (`gdb`, `hadoop`)
- [ ] @jasonfenglu (`py-yt`, `py-h5py`)
- [ ] @jimmy04500 (`charmpp`)
- [ ] @jmjwozniak (`adlbx`, `exmcutils`, `stc`, `turbine`)
- [ ] @kylefernandes (`intel-daal`, `intel-ipp`, `intel-mkl`, `intel-mpi`, `intel-parallel-studio`, `intel`)
- [ ] @mdevlin1 (`libxsmm`, `libxstream`, `hmmer`)
- [ ] @mikedep333 (`gcc`)
- [ ] @peetsv / @23skdu (`dialign-tx`, `igv`, `lftp`, `nextflow`, `perl-file-copy-recursive`, `perl-xml-libxml`, `py-cnvkit`, `py-crossmap`, `py-pybedtools`, `py-pyfaidx`, `py-pysam`, `py-pyvcf`, `py-vmd-python`, `r-cghflasso`, `r-dismo`, `r-proc`, `r-spatial`, `r-utf8`, `rsync`, `sniffles`, `vardictjava`, `viennarna`)
- [ ] @rajeeja (`meshkit`)
- [ ] @raznikk (`bamtools`)
- [ ] @rbrts (`py-ase`, `visit`)
- [ ] @rice31 (`py-pyyaml`)
- [ ] @simonflood (`ants`, `hmmer`, `trinity`)
- [ ] @thecorkscrew (`c-lime`)
- [ ] @ursache (`plumed`)

**Comment by raznikk** [comment]
My name is Barry Britt, and I am a contributor to Spack. I have used or may have used the following email address(es): bbritt@iastate.edu. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by disheng222** [comment]
My name is ________Sheng Di_________________, and I am a contributor to Spack. I have used or may have used the following email address(es): ____________disheng222@gmail.com__________________. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by iulian787** [comment]
My name is Iulian Grindeanu, and I am a contributor to Spack. I have used or may have used the following email addresses: iulian@mcs.anl.gov, iulian@anl.gov, iulian787@users.noreply.github.com. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by g-mathias** [comment]
My name is Gerald Mathias, and I am a contributor to Spack. I have used or may have used the following email address(es): Gerald.Mathias@lrz.de. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by rajeeja** [comment]
My name is Rajeev Jain, and I am a contributor to Spack. I have used or may
have used the following email address(es): rajeeja@gmail.com or jain@anl.gov
. I consent to change the current license contained in the License file at
https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1
license to the MIT License and Apache License 2.0 with respect to all of my
contributions to Spack.

_________________________________________
Rajeev

**Comment by simonflood** [comment]
My name is simonflood, and I am a contributor to Spack. I have used or may have used the following email address(es): simonflood@users.noreply.github.com. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by thecorkscrew** [comment]
My name is Daniel Bremer, and I am a contributor to Spack. I have used or may have used the following email address(es): 5bremer@informatik.uni-hamburg.de. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by DDevHan** [comment]
My name is Daniel Han, and I am a contributor to Spack. I have used or may have used the following email address(es): danhan@iastate.edu, danhans12@gmail.com. I consent to change the current license contained in the License file at https://github.com/spack/spack/blob/develop/LICENSE from the LGPL-2.1 license to the MIT License and Apache License 2.0 with respect to all of my contributions to Spack.

**Comment by tgamblin** [comment]
Hey all.  We did it!  Spack is now relicensed to Apache-2.0/MIT.  See #9450 for details, and thanks to all of you for getting your consent in so quickly!
