### ISSUE TITLE
Better bwpy (Blue Waters python) support

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#9154]
I'm trying to use Spack on Blue Waters, which rolls its own [custom Python stack](https://bluewaters.ncsa.illinois.edu/python) called `bwpy`. This issue serves as a means of tracking bugs I've encountered so far when trying to use `bwpy` as an external package.

1. The first problem is Spack's module parsing. The `bwpy` module contains:
```console
$ module show bwpy
-------------------------------------------------------------------
/sw/bw/modulefiles/bwpy/1.2.4:

conflict	 boost 
conflict	 visit 
conflict	 vtk 
conflict	 bwpy 
conflict	 cmake 
conflict	 bwpy-mpi/0.3.0 
setenv		 BWPY_VERSION 1.2.4 
setenv		 BWPY_DIR /mnt/bwpy/single 
prepend-path	 PATH /opt/bwpy/bin 
prepend-path	 PATH /sw/bw/bwpy/mnt/bin 
setenv		 BWPY_INCLUDE_PATH /mnt/bwpy/single/include 
setenv		 BWPY_LIBRARY_PATH /mnt/bwpy/single/lib:/mnt/bwpy/single/usr/lib 
setenv		 BWPY_MANPATH /mnt/bwpy/single/usr/share/man 
prepend-path	 MANPATH /mnt/bwpy/single/usr/share/man 
setenv		 BWPY_PKG_PATH /mnt/bwpy/single/usr/lib/pkgconfig 
prepend-path	 PKG_CONFIG_PATH /mnt/bwpy/single/usr/lib/pkgconfig 
setenv		 BWPY_BINARY_PATH /mnt/bwpy/single/bin:/mnt/bwpy/single/usr/bin 
prepend-path	 PATH /mnt/bwpy/single/bin:/mnt/bwpy/single/usr/bin 
setenv		 BWPY_MODULEPATH /mnt/bwpy/single/usr/share/modulefiles 
prepend-path	 MODULEPATH /mnt/bwpy/single/usr/share/modulefiles 
-------------------------------------------------------------------
```
Spack detects the installation prefix as `/opt/bwpy/`, however, the correct installation prefix is `/sw/bw/bwpy/mnt`. How does Spack determine the installation prefix? For now I'm switching to specifying the installation prefix instead of the module file name.

2. The second problem I've discovered is Spack's `spec['python'].command` support. We currently search for `python3` if we're using `python@3:`, but `bwpy` places several Python 3 executables in the same directory:
```console
$ l /sw/bw/bwpy/mnt/bin
bash-wrapped  bwpy-wrapper  ipython   jupyter           jupyter-qtconsole  pip2.7  pypy    python2    python3.4  virtualenv
bwpy-environ  eix           ipython2  jupyter-console   pip                pip3    pypy3   python2.7  python3.5
bwpy-version  env-wrapped   ipython3  jupyter-notebook  pip2               pip3.5  python  python3    python3.6
```
A better solution would be to search for `python3.6`, then `python3`, then `python` if using `python@3.6.5` in `packages.yaml`.

3. The third problem I've run into is that `spec['python'].command` returns the realpath of the executable it finds. With `bwpy`, `python` is simply a symlink to `bwpy-wrapper`, regardless of Python version. However, you can't run `bwpy-wrapper` directly, it must be invoked via `python`. The simple solution is to drop the realpath.

4. I'm trying to install `gdal+python`, but none of the Python bindings correctly RPATH to the Python libraries. Not sure if this is a GDAL bug or a `bwpy` bug. I'm leaning towards `bwpy` bug.

I can fix 2 and 3, but I'm not sure about the other two. @becker33 @scheibelp is one of you more familiar with how module files are parsed to locate the installation prefix?

**Comment by adamjstewart** [comment]
Contacted Blue Waters support about problem 4. This is their explanation about how `bwpy` works:

> To explain bwpy's configuration a bit, the files in /sw/bw/bwpy/bin are wrappers which invoke through bwpy-environ. bwpy-environ lives in /opt/bwpy since it needs to be on a filesystem which allows for its set-uid bit to be set. bwpy-environ mounts a bwpy squashfs image at /mnt/bwpy containing all the real files. When doing anything beyond simply invoking python, such as compiling stuff, you need to access more than what the convenience wrappers provide. Run bwpy-environ without any arguments and it will mount the image and run bash, entering into an environment where you have access to /mnt/bwpy. Think of bwpy as a demi-container setup. It uses mount namespaces to create separate instances but doesn't chroot like a fully containerized setup.

So it sounds like I need to run `bwpy-environ` to mount `bwpy` _before_ running Spack if I want to link to the Python libs. I'm also building with a different version of GCC than `bwpy` was built with, so I'm going to try that as well.

**Comment by sleak-lbl** [comment]
the same is true for modulefiles with `LD_LIBRARY_PATH`, eg:
```> module show intel
-------------------------------------------------------------------
/opt/modulefiles/intel/18.0.1.163:

conflict	 intel
setenv		 INTEL_PATH /opt/intel/compilers_and_libraries_2018.1.163
setenv		 INTEL_VERSION 18.0.1.163
setenv		 INTEL_MAJOR_VERSION 18
setenv		 INTEL_MINOR_VERSION 18
setenv		 MKLROOT /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl
prepend-path	 LIBRARY_PATH /opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64
prepend-path	 LD_LIBRARY_PATH /opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64
prepend-path	 CPATH /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/include
prepend-path	 MANPATH /opt/intel/compilers_and_libraries_2018.1.163/linux/man/common
prepend-path	 PATH /opt/intel/compilers_and_libraries_2018.1.163/linux/bin/intel64
prepend-path	 NLSPATH /opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64/locale/%l_%t/%N:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/locale/%l_%t/%N
module-whatis	 Intel compiler
-------------------------------------------------------------------
```
.. note that `LD_LIBARY_PATH here has two components. Then in `lib/spack/spack/util/module_cmd.py` we have:
```168 def get_path_from_module(mod):
169     """Inspects a TCL module for entries that indicate the absolute path
170     at which the library supported by said module can be found.
171     """
172     # Create a modulecmd executable
173     modulecmd = get_module_cmd()
174
175     # Read the module
176     text = modulecmd('show', mod, output=str, error=str).split('\n')
177
178     # If it sets the LD_LIBRARY_PATH or CRAY_LD_LIBRARY_PATH, use that
179     for line in text:
180         if line.find('LD_LIBRARY_PATH') >= 0:
181             path = get_argument_from_module_line(line)
182             return path[:path.rfind('/lib')]
183
```
this results in `spec['mkl'].prefix` having a string like `/path/to/intel:/path/to/intel/mkl`, which translates into a compile flag like:
`cc -I/path/to/intel:/path/to/intel/mkl/include` .. which the compiler can't find so ignores, and then complains about missing headers

My workaround is to edit `lib/spack/spack/util/module_cmd.py` with:
```    # If it sets the LD_LIBRARY_PATH or CRAY_LD_LIBRARY_PATH, use that
    for line in text:
        if line.find('LD_LIBRARY_PATH') >= 0:
            #path = get_argument_from_module_line(line)
            #return path[:path.rfind('/lib')]
            # sleak: in case we have multiple paths in LD_LIBRARY_PATH, choose the
            # first and hope its the right one:
            paths = get_argument_from_module_line(line).split(':')
            for p in paths:
                path = p[:p.rfind('/lib')]
                if path:
                    return path
```
and then code the `-I` and `-L` paths in the package.py file with the highly-suspect assumption that everybody else has the same MKL modulefile as I do ...

**Comment by alalazo** [comment]
I added the bug to the list of "Most wanted" since there are a few reports of it. @adamjstewart feel free to triage it as you see fit.

**Comment by scheibelp** [comment]
> How does Spack determine the installation prefix?

Spack will stop at the first relevant PATH/LD_LIBRARY_PATH or whatever that it finds and then attempt to "work backwards from there". E.g. if it gets LD_LIBRARY_PATH, it strips off `lib/`.

So for

```
prepend-path	 PATH /opt/bwpy/bin 
prepend-path	 PATH /sw/bw/bwpy/mnt/bin 
```

It will pull the first path. It doesn't have any logic to distinguish that the second one would be better.

**Comment by scheibelp** [comment]
> this results in spec['mkl'].prefix having a string like /path/to/intel:/path/to/intel/mkl, which translates into a compile flag like:

I'm having trouble reproducing this on the latest Spack develop, although the parsing logic is fragile so I'm not surprised if I'm looking at it wrong.

```
            #path = get_argument_from_module_line(line)
            #return path[:path.rfind('/lib')]
            # sleak: in case we have multiple paths in LD_LIBRARY_PATH, choose the
            # first and hope its the right one:
            paths = get_argument_from_module_line(line).split(':')
```

Did you insert that rfind yourself? Are you working with an older Spack? I can see how this would pull the full path with `:` and all with `rfind`, but the current `module_cmd` implementation does not use `rfind`.

**Comment by sleak-lbl** [comment]
oh .. yes I'm using the NERSC fork of Spack, which is usually a number of commits behind the main tree, so the surrounding code may have changed in the meantime. The part before `# sleak: ` came from Spack, the lines starting with `# sleak:` are what I added

I see my code snippet cut off the line with the method name, sorry about that .. it's in `get_path_from_module` in `lib/spack/spack/util/module_cmd.py`

The corresponding code in the HEAD uses `find` instead of `rfind`, so it will get the first rather than last entry. But it will be vulnerable to paths that have a string like `/lib` somewhere in the middle, eg `/opt/cray/libraries/important_library/lib` will return `/opt/cray`:

```def get_path_from_module_contents(text, module_name):
    tty.debug("Module name: " + module_name)
    pkg_var_prefix = module_name.replace('-', '_').upper()
    components = pkg_var_prefix.split('/')
    # For modules with multiple components like foo/1.0.1, retrieve the package
    # name "foo" from the module name
    if len(components) > 1:
        pkg_var_prefix = components[-2]
    tty.debug("Package directory variable prefix: " + pkg_var_prefix)

    # If it sets the LD_LIBRARY_PATH or CRAY_LD_LIBRARY_PATH, use that
    for line in text:
        pattern = r'\W(CRAY_)?LD_LIBRARY_PATH'
        if re.search(pattern, line):
            #path = get_path_arg_from_module_line(line)
            #return path[:path.find('/lib')]
            #sleak splitting the path on ':' first then using rfind seems safer:
            paths = get_argument_from_module_line(line).split(':')
            for p in paths:
                path = p[:p.rfind('/lib')]
                if path:
                    return path
```

**Comment by adamjstewart** [comment]
Discovered another problem with Spack + `bwpy`:

5. When trying to install `atk`, which depends on `glib`, I noticed the following error message:
```
==> 'ninja' '-j32' '-v'
[1/52] /mnt/bwpy/single/usr/bin/glib-genmarshal --prefix atk_marshal --output atk/atkmarshal.c --body ../atk/atkmarshal.list --include-header atkmarshal.h
FAILED: atk/atkmarshal.c
/mnt/bwpy/single/usr/bin/glib-genmarshal --prefix atk_marshal --output atk/atkmarshal.c --body ../atk/atkmarshal.list --include-header atkmarshal.h

(process:10957): GLib-Genmarshal-WARNING **: failed to open "--include-header": No such file or directory

(process:10957): GLib-Genmarshal-WARNING **: failed to open "atkmarshal.h": No such file or directory
[2/52] /mnt/bwpy/single/usr/bin/glib-genmarshal --prefix atk_marshal --output atk/atkmarshal.h --pragma-once --header ../atk/atkmarshal.list
FAILED: atk/atkmarshal.h
/mnt/bwpy/single/usr/bin/glib-genmarshal --prefix atk_marshal --output atk/atkmarshal.h --pragma-once --header ../atk/atkmarshal.list

(process:10958): GLib-Genmarshal-WARNING **: failed to open "--pragma-once": No such file or directory
[3/52] /mnt/bwpy/single/usr/lib/python-exec/python3.5/meson --internal exe /mnt/c/scratch/sciteam/stewart1/spack-stage/spack-stage-4c7ksjg9/atk-2.28.1/spack-build/meson-private/meson_exe_glib-mkenums_91fb767296e44d963297a31e7860fd705391f253.dat
ninja: build stopped: subcommand failed.
```
Spack is using the `glib-genmarshal` utility installed in the `bwpy` prefix, not the direct dependency of `atk`. It looks like our `PATH` is messed up:
```bash
export PATH="/mnt/bwpy/single/usr/bin:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/cray:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/case-insensitive:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/gcc:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/gettext-0.19.8.1-catesplk224bx4b25blj7dz34ib63qcn/bin:/mnt/bwpy/single/usr/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/ninja-1.8.2-i73dosdbqakxhsbit3kwfls5cahtaq3e/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/meson-0.49.0-o7xyxaq4kxwryur4n36kxq32a3qxqu3o/bin:/mnt/bwpy/single/usr/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/perl-5.26.2-dejuld2ambffkwheuw42pmucqv2jym7n/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/glib-2.56.3-byzsulp4pnawvtfsak7mm7kbbdiymm2h/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/pkgconf-1.5.4-smtnscq3rqjkthzhrl4o6vuw7qa2birq/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/gobject-introspection-1.49.2-nc656g2ubnrlstbu3wpb5zmph3w57k4k/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/gettext-0.19.8.1-catesplk224bx4b25blj7dz34ib63qcn/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/meson-0.49.0-o7xyxaq4kxwryur4n36kxq32a3qxqu3o/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/glib-2.56.3-byzsulp4pnawvtfsak7mm7kbbdiymm2h/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/pkgconf-1.5.4-smtnscq3rqjkthzhrl4o6vuw7qa2birq/bin:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/gobject-introspection-1.49.2-nc656g2ubnrlstbu3wpb5zmph3w57k4k/bin:/opt/gcc/7.3.0/bin:/opt/cray/pmi/5.0.10-1.0000.11050.179.3.gem/bin:/mnt/bwpy/single/bin:/mnt/bwpy/single/usr/bin:/sw/bw/bwpy/mnt/bin:/opt/bwpy/bin:/sw/EasyBuild/software/wget/1.19.4/bin:/sw/EasyBuild/software/git/2.17.0/bin:/sw/EasyBuild/software/cURL/7.59.0/bin:/sw/EasyBuild/software/OpenSSL/1.0.2m/bin:/sw/admin/scripts:/sw/user/scripts:/opt/xalt/0.7.6/sles11.3/libexec:/opt/xalt/0.7.6/sles11.3/bin:/opt/moab/9.1.2/sbin:/opt/torque/6.0.4/sbin:/opt/torque/6.0.4/bin:/opt/cray/craype/2.5.8/bin:/opt/cray/llm/default/bin:/opt/cray/llm/default/etc:/opt/cray/xpmem/0.1-2.0502.64982.7.24.gem/bin:/opt/cray/ugni/6.0-1.0502.10863.8.28.gem/bin:/opt/cray/udreg/2.3.2-1.0502.10518.2.17.gem/bin:/opt/cray/lustre-cray_gem_s/2.5_3.0.101_0.46.1_1.0502.8871.43.1-1.0502.21728.74.6/sbin:/opt/cray/lustre-cray_gem_s/2.5_3.0.101_0.46.1_1.0502.8871.43.1-1.0502.21728.74.6/bin:/opt/cray/alps/5.2.4-2.0502.9774.31.12.gem/sbin:/opt/cray/alps/5.2.4-2.0502.9774.31.12.gem/bin:/opt/cray/sdb/1.1-1.0502.63652.4.27.gem/bin:/opt/cray/nodestat/2.2-1.0502.60539.1.31.gem/bin:/opt/modules/3.2.10.5/bin:/opt/moab/9.1.2/bin:/u/sciteam/stewart1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:.:/usr/lib/qt3/bin:/opt/cray/bin:/u/sciteam/stewart1/spack/bin"
```
This begs a couple of questions. (1) `python` is a dependency of `glib`, which is a dependency of `atk`, so why would `python` be in the `PATH` at all? (2) is the `bwpy` module or `bwpy-environ` command somehow injecting this directory into the `PATH` outside of Spack's control? For now, I'm going to try building my own Python instead of using `bwpy` as an external package.

**Comment by becker33** [comment]
@sleak-lbl I think #12693 should resolve the issues you've seen with module parsing

**Comment by adamjstewart** [comment]
I've removed this from "Most Wanted" since BW will be retired at the end of the year.

**Comment by adamjstewart** [comment]
I think most of the issues related to `bwpy` as an external package have been resolved. NCSA is currently working on porting `bwpy` to Spack, so that will make things much easier to integrate in the future.
