### ISSUE TITLE
Locking problems

### ISSUE THREAD

**Issue by healther** [spack/spack#9166]
This is a fairly tricky problem to track down and I'm not particularly certain in what the actual problem is, so take this description with a grain of salt.

Our CI regularly shows errors of this kind:
```
+ spack install --source --only dependencies --show-log-on-error -j4 <spec>
==> Error: 
```

This is because either [this](https://github.com/spack/spack/blob/5e8a9ddaed478680dcd0607cfdafafa769ece6b3/lib/spack/llnl/util/lock.py#L266) or [this](https://github.com/spack/spack/blob/5e8a9ddaed478680dcd0607cfdafafa769ece6b3/lib/spack/llnl/util/lock.py#L289) assertion in `lib/spack/llnl/util/lock.py` being triggered (`spack -d` prints the stack trace to these lines). We suspect that we time out [here](https://github.com/spack/spack/blob/5e8a9ddaed478680dcd0607cfdafafa769ece6b3/lib/spack/llnl/util/lock.py#L221) due to the slow HDD.

We think the origin of this problem is the `finally` statement [here](https://github.com/spack/spack/blob/63004e3de1473254c3b2a75f1e06afaabdacd7dd/lib/spack/spack/database.py#L244) (for brevity here the copy of the function)
```
    @contextlib.contextmanager
    def prefix_read_lock(self, spec):
        prefix_lock = self.prefix_lock(spec)
        try:
            prefix_lock.acquire_read(60)
            yield self
        finally:
            prefix_lock.release_read()
```
If `prefix_lock.acquire_read` times out, this will not do `prefix_lock._reads += 1` and the `prefix_lock.release_read()` will run into `assert prefix_lock._reads > 0`. As I currently understand it, the code above seems wrong and I think the simplest solution would be to move the `prefix_lock.acquire_read(60)` out of the `try:` block. But I have no idea what kind of repercussions this would have (or even if our reasoning is solid). 

Any kind of feedback would be greatly appreciated, I'm certainly out of my depth here @tgamblin @scheibelp

**Comment by adamjstewart** [comment]
Related to #8915

**Comment by tgamblin** [comment]
@healther: you're right.  Taking the acquire out of the `try` is a good idea because if acquire fails, we shouldn't bother releasing.  It would at least give a better error message.

It wouldn't fix the problem, though.  The lock timeouts are set by default to 60 seconds.  I am tempted to say we should just turn the timeout off and ensure that things are implemented correctly with tests.

Do you know what lock is timing out here?  I'd be interested to know why it's timing out.

**Comment by healther** [comment]
Trying to track down the timeout, but unfortunately I still don't have a good reproducer (i.e. I can reproduce it once it's broken, but not the breakage itself)

Actually taking the acquire out of the try probably won't be sufficient, as there is still the point that we could receive an interrupt within the `self._debug` call, which would then leave a broken lock. I'm not sure how relevant this will be in practice, but we should keep it in mind. Currently we have:
```
try:
            prefix_lock.acquire_write(600)
            yield self
            prefix_lock.release_write()
        except Exception as e:
            if isinstance(e, LockError):
                raise e
            else:
                prefix_lock.release_write()
                raise e
```
which should be correct (famous last words and so)

**Comment by adamjstewart** [comment]
> we could receive an interrupt within the `self._debug` call, which would then leave a broken lock. I'm not sure how relevant this will be in practice, but we should keep it in mind.

Is this the exact situation I describe in https://github.com/spack/spack/issues/8915#issuecomment-417728118?

**Comment by tgamblin** [comment]
@healther:

I think you're trying to write this:

```python
        try:
            prefix_lock.acquire_write(600)
            yield self
            prefix_lock.release_write()
        except LockError:
            raise
        finally:
            prefix_lock.release_write()
```

**Comment by tgamblin** [comment]
I still think the main problem is that the lock times out in the first place... can you say more about your CI setup?

**Comment by healther** [comment]
@adamjstewart I don't think so. The situation I'm describing is e.g. if the user interrupts (via ctrl+c) while spack executes that `self._debug` call. So, at least statistically, it is rather unlikely that you managed to have the server notice your missing ssh connection at that time. That being said: Actually flushing output is _probably_ a synchronisation barrier, so it is more likely to hit there.

@tgamblin In that situation wouldn't the `finally` block also be executed in case of an `LockError`, at least that is how I read the documentation:

> A finally clause is always executed before leaving the try statement, whether an exception has occurred or not. When an exception has occurred in the try clause and has not been handled by an except clause (or it has occurred in an except or else clause), it is re-raised after the finally clause has been executed. The finally clause is also executed “on the way out” when any other clause of the try statement is left via a break, continue or return statement.

They talk about _rerasing_ the exception only if it is not handled explicitly, but `finally` should be executed either way

**Comment by healther** [comment]
> I still think the main problem is that the lock times out in the first place... can you say more about your CI setup?

Definitely! This issue is less about the locking error (though I'm grateful for any help), rather than the missing/confusing error message.

It's a Jenkins instance that `cd`s into persistent spack installations. One is a "live" version, which serves users and a second "stage" which `stack`s the "live" version as a starting point for testing (`stack` is @obreitwi's implementation of `chain`). Jenkins then executes a fairly large number of builds of largish meta-packages (again internally maintained), but essentially calls `spack install` for a couple of hours. There is also a slurm system and a separation between frontend and backend nodes involved, but everything operates on a fairly slow nfs mount. 
If it breaks it typically breaks about an hour or 2 into the process and afterwards there is a still active lock on `prefix-lock`, which then makes the next `spack install` timeout and give this assertion error (without any context, as we don't use `spack -d`). 

The confusing part is, that the stage is cleaned for any new Jenkins run, but it only works for some time. Sometimes it takes longer to break sometimes it breaks a bit earlier, but I couldn't find any indication that it will break in the logs..

**Comment by healther** [comment]
Okay another piece of the puzzle: The failing install step is always one that is run on the frontend (due to it installing tensorflow and tensorflow being a pita) AND there doesn't seem to be a locking problem when we explicitly tell spack to only use one core i.e. `spack install -j1` didn't trigger the locking problem, but `spack install -j4` did. (The latter I can reproduce, even though it worked in the distant past, the former didn't trigger on O(5) tries yesterday)

@tgamblin: Is there any reason that using `-j4` would change locking behaviour? I thought `spack` itself was strictly single threaded and only the `make` or `build` phases spawn multithreaded subprocesses?

**Comment by JusticeForMikeBrown** [comment]
I am having same issue.

Very random.

Not a issue with NFS.

```
[root@node103 ~]# spack -d uninstall /xnoykzf
==> Reading config file /pbtech_mounts/softlib001/apps/EL6/spack/etc/spack/defaults/modules.yaml
==> Reading config file /pbtech_mounts/softlib001/apps/EL6/spack/etc/spack/defaults/config.yaml
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> The following packages will be uninstalled:

-- linux-rhel6-x86_64 / gcc@4.4.6 -------------------------------
xnoykzf gcc@6.3.0%gcc+binutils~piclibs

==> Do you want to proceed? [y/N] y
==> Reading config file /pbtech_mounts/softlib001/apps/EL6/spack/etc/spack/defaults/repos.yaml
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
Traceback (most recent call last):
  File "/pbtech_mounts/softlib001/apps/EL6/spack/bin/spack", line 85, in <module>
    sys.exit(spack.main.main())
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 608, in main
    return _main(command, parser, args, unknown)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 500, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 412, in _invoke_spack_command
    return_val = command(parser, args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/uninstall.py", line 222, in uninstall
    do_uninstall(uninstall_list, args.force)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/uninstall.py", line 167, in do_uninstall
    item.do_uninstall(force=force)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/package.py", line 1965, in do_uninstall
    Package.uninstall_by_spec(self.spec, force)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/package.py", line 1923, in uninstall_by_spec
    spack.store.db.remove(specs[0])
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 93, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 776, in remove
    with self.write_transaction():
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 314, in __enter__
    if self._enter() and self._acquire_fn:
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 345, in _enter
    return self._lock.acquire_write(self._timeout)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 226, in acquire_write
    self._lock(fcntl.LOCK_EX, timeout=timeout)   # can raise LockError.
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/util/lock.py", line 50, in _lock
    super(Lock, self)._lock(op, timeout)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 138, in _lock
    raise LockError("Timed out waiting for lock.")
llnl.util.lock.LockError: Timed out waiting for lock.
```

**Comment by healther** [comment]
`-L` isn't really a fix... It just ignores the locks^^

Did you notice any kind of pattern in the randomness? Did it only happen when uninstalling packages?

**Comment by JusticeForMikeBrown** [comment]
@healther for me it happens with `uninstall`, `install`, and `reindex.`  at least `load` and `find` still work :)

**Comment by scheibelp** [comment]
I'll be able to look into this by Monday 9/10

**Comment by healther** [comment]
@scheibelp The locking problems that I have seen were all
```
WRITE LOCK: /.../spack/opt/spack/.spack-db/prefix_lock[12345:1] [Acquiring]
```

> If you have the luxury of time, I'm curious if simply waiting resolves the issue.

I'm not sure how I would do that given that we basically start each run from a clean state (up to the linked-in packages from our live instance) and it breaks within one `spack install` call. The spec has O(120) nodes and the point where it breaks is surprisingly stable...

> `-j` doesn't affect any of the multi-threading choices for Spack itself

That's what I assumed, and I also agree with the conclusion that it's probably the stressed NFS system. This is aided by the fact that restarting the NFS server helped (however that also means that I currently don't have a "broken enough" system to get new test cases). I would have written it completely off to a bad NFS server if it weren't for the surprisingly stable point of breakage somewhere in the middle of the O(120) packages...

**Comment by javdg** [comment]
> I would have written it completely off to a bad NFS server

... chiming in as this is close to the situation we've been in for a couple of weeks: we ran into locking issues occasionally when manually running multiple Spack processes on the same network file system-based install, but couldn't quite put our finger on it. This has become more prevalent --- but not deterministic, seemingly --- when parallelizing our build process (using make as a potential wrapper for Spack, but that's another story).
In our experience, NFS mounts seem to be more error prone than GPFS ones, but that's mostly a gut feeling so far. A colleague of mine has started to look into these issues more systematically last week (just around the time this issue was raised), but is now on a short holiday. If needed, I'm pretty sure we could contribute a potential test case testing environment once he is back.

**Comment by JusticeForMikeBrown** [comment]
Hi @scheibelp 

I have been installing Spack packages locally, to the XFS file system, as well as over NFS4.   I don't think problem has to do with load on the server itself or NFS.

```
[root@laplace ~]# uptime
 08:52:20 up 727 days, 17:37,  1 user,  load average: 0.13, 0.15, 0.11
```

Spack exists on /softlib filesystem.

```
[root@laplace ~]# mount | grep softlib
/dev/mapper/vg_homes-lv_softlib on /softlib001 type xfs (rw,acl)

[root@laplace ~]# which spack
/softlib001/apps/EL6/spack/bin/spack
```

Local uninstall not over NFS:

```
==> Do you want to proceed? [y/N] Y
==> Reading config file /softlib001/apps/EL6/spack/etc/spack/defaults/repos.yaml
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[8797823327999260323:1] [Acquiring]
==> WRITE LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[8797823327999260323:1] [Acquired]
==> Deleting package prefix [image-magick@7.0.5-9%gcc@6.3.0 arch=linux-rhel6-x86_64 /6qyew2d]
==> Deleting DB entry [image-magick@7.0.5-9%gcc@6.3.0 arch=linux-rhel6-x86_64 /6qyew2d]
==> WRITE LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[8797823327999260323:1] [Released]
Traceback (most recent call last):
  File "/softlib001/apps/EL6/spack/bin/spack", line 85, in <module>
    sys.exit(spack.main.main())
  File "/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 608, in main
    return _main(command, parser, args, unknown)
  File "/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 500, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 412, in _invoke_spack_command
    return_val = command(parser, args)
  File "/softlib001/apps/EL6/spack/lib/spack/spack/cmd/uninstall.py", line 222, in uninstall
    do_uninstall(uninstall_list, args.force)
  File "/softlib001/apps/EL6/spack/lib/spack/spack/cmd/uninstall.py", line 167, in do_uninstall
    item.do_uninstall(force=force)
  File "/softlib001/apps/EL6/spack/lib/spack/spack/package.py", line 1965, in do_uninstall
    Package.uninstall_by_spec(self.spec, force)
  File "/softlib001/apps/EL6/spack/lib/spack/spack/package.py", line 1955, in uninstall_by_spec
    spack.store.db.remove(spec)
  File "/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 93, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 776, in remove
    with self.write_transaction():
  File "/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 314, in __enter__
    if self._enter() and self._acquire_fn:
  File "/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 345, in _enter
    return self._lock.acquire_write(self._timeout)
  File "/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 226, in acquire_write
    self._lock(fcntl.LOCK_EX, timeout=timeout)   # can raise LockError.
  File "/softlib001/apps/EL6/spack/lib/spack/spack/util/lock.py", line 50, in _lock
    super(Lock, self)._lock(op, timeout)
  File "/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 138, in _lock
    raise LockError("Timed out waiting for lock.")
llnl.util.lock.LockError: Timed out waiting for lock.
```

**Comment by scheibelp** [comment]
> we ran into locking issues occasionally when manually running multiple Spack processes on the same network file system-based install,

If those separate processes are attempting to install the same thing, that may be a separate bug: see https://github.com/spack/spack/pull/9219#issuecomment-420491747

#9219 provides the ability to customize timeouts (and also sets the default timeout higher)

**Comment by JusticeForMikeBrown** [comment]
Hi @scheibelp 

I don't know why the lock timeout would happen in my situation as I am the only person installing packages in Spack.   There are no hung Spack install processes running anywhere whereas if I delete the lock file, re-create, then do a local install, not over NFS, the issue still arises.
