### ISSUE TITLE
Show to user which packages might be relocated

### ISSUE THREAD

**Issue by alalazo** [spack/spack#9188]
As a packager I want `spack buildcache` to be able to analyze the DAG of an installed package and show which nodes are relocatable so that I could get a quantitative idea on how many packages encode their install prefix in e.g. `.rodata`.

### Rationale

This is a follow up from https://github.com/spack/spack/issues/7123#issuecomment-417880181 and discussion below. The proposal basically boils down to have a new sub-command:
```
$ spack buildcache preview <installed package>
```
that shows to users which nodes are relocatable and which are not.

### Description

An example output might be something like:
```console
$ spack buildcache --help
usage: spack buildcache [-h] SUBCOMMAND ...

create, download and install binary packages

positional arguments:
  SUBCOMMAND  buildcache sub-commands
    create    create a binary package from an existing install
    install   install from a binary package
    list      list binary packages available from mirrors
    preview   analyzes an installed package and reports whether 
              executables and libraries are relocatable
    keys      get public keys available on mirrors

optional arguments:
  -h, --help  show this help message and exit

$ spack buildcache preview hdf5 ^mpich
Relocatable packages
--------------------------------
[+]  hdf5@1.10.3%gcc@8.0.1~cxx~debug~fortran~hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu18.04-x86_64 
[+]      ^mpich@3.2.1%gcc@8.0.1 device=ch3 +hydra netmod=tcp +pmi+romio~verbs arch=linux-ubuntu18.04-x86_64 
[-]      ^zlib@1.2.11%gcc@8.0.1+optimize+pic+shared arch=linux-ubuntu18.04-x86_64 
```
meaning that `hdf5` and `mpich` are relocatable, while `zlib` is not. *Note that the example is a mock and I didn't look for real into these three packages as I did for `pkgconf` and `ncurses`.*

### Additional information

Waiting for feedback before implementing this. Feel free to close if you consider this not necessary.

@gartung @tgamblin @scheibelp @becker33 @mathstuf @bryonbean

**Comment by tgamblin** [comment]
Wouldn’t this be better as an argument to `spac spec`?  There is already an “installed” argument there. This seems similar.

**Comment by alalazo** [comment]
> Wouldn’t this be better as an argument to spac spec? There is already an “installed” argument there. This seems similar

Sure, I don't mind having this in `spack spec` if it is clearer. The only caveat is that if you ask for this analysis, you can only give as arguments already installed packages (while usually `spack spec` takes an arbitrary spec, regardless of the install status).

**Comment by tgamblin** [comment]
@alalazo: if you pass `spack spec` a concrete spec, it can tell you about installed packages.

But to make that easier, what if we made this an argument to`spack spec` and added a `-i/--installed` option to `spack spec`, which would match already-installed packages or fail, instead of concretizing?

**Comment by alalazo** [comment]
@tgamblin 

> But to make that easier, what if we made this an argument tospack spec and added a -i/--installed option to spack spec, which would match already-installed packages or fail, instead of concretizing?

I don't think we need this extra option as it may be implicit. For instance:
```console
# Using a non-installed spec
$ spack spec --relocatable hdf5
==> Error: the --relocatable option requires to pass an already installed package.
```
Let me know what might work for you and I'll update the description above.

**Comment by tgamblin** [comment]
Ok, actually, I like the original idea to make this part of `buildcache` better.  I was thinking we could *also* do it on not-yet-installed specs, and that that would make sense, but if it's analyzing an installed thing, I think it belongs on buildcache.

So, what if we put it in `buildcache`, and just use `spec.tree()` to print it?  I think `buildcache analyze` is kind of generic -- are there other analyses this would do?

Sorry for all the confusion.

**Comment by alalazo** [comment]
No worries, I was also undecided whether to put this in `spack spec` and use functions from `buildcache.py` or put it in `spack buildcache` and use `spec.tree()`.  Would: 
```console
$ spack buildcache preview <spec>`
```
do as a name? The description might be something like *"Analyzes an installed spec and reports whether executables and libraries are relocatable."*
