### ISSUE TITLE
assimp [dependency of dealii] build error with intel compilers on KNL

### ISSUE THREAD

**Issue by balay** [spack/spack#9189]
### Steps to reproduce the issue

```console
$ spack install xsdk@develop
```

[spack-build.out.txt](https://github.com/spack/spack/files/2361261/spack-build.out.txt)

### Platform and user environment

Please report your OS here:
```commandline
bash-4.2$ uname -a
Linux isdp001.cels.anl.gov 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2$ lsb_release -d
Description:    CentOS Linux release 7.5.1804 (Core) 
bash-4.2$ 
``` 

[compilers.yaml.txt](https://github.com/spack/spack/files/2361266/compilers.yaml.txt)
[packages.yaml.txt](https://github.com/spack/spack/files/2361268/packages.yaml.txt)

### Additional information

Does this package build with intel compilers?

I guess I should build dealii without assimp for xsdk

```diff
diff --git a/var/spack/repos/builtin/packages/xsdk/package.py b/var/spack/repos/builtin/packages/xsdk/package.py
-    depends_on('dealii@develop~python~doc~slepc~gmsh+petsc+mpi+trilinos~int64+hdf5~netcdf+metis', when='@develop')
+    depends_on('dealii@develop~assimp~python~doc~slepc~gmsh+petsc+mpi+trilinos~int64+hdf5~netcdf+metis', when='@develop')

```

cc: @bangerth @Rombur @davydden

**Comment by davydden** [comment]
> Does this package build with intel compilers?

I recall having issues with `assimp` and `intel` compilers, but I thought it was me doing something wrong... I will disable it in `xsdk`...

**Comment by davydden** [comment]
p.s. @masterleinad : you build with Intel compilers, did you have issues building assimp?

**Comment by bangerth** [comment]
Can anyone show the errors? Maybe we can upstream a patch for the issue...

**Comment by bangerth** [comment]
It looks like assimp needs to be compiled with a C++11 compiler, but is not (or the compiler isn't given the appropriate C++11 flag). Is this something that can be fixed inside spack?

**Comment by balay** [comment]
I had previously added this to one of the packages..
e1661ff662944965efa54713c5db592290b32eba

 So will add this to assimp and check

**Comment by balay** [comment]
The build makes progress with this change

```diff

diff --git a/var/spack/repos/builtin/packages/assimp/package.py b/var/spack/repos/builtin/packages/assimp/package.py
index 9e3687a..90d694f 100644
--- a/var/spack/repos/builtin/packages/assimp/package.py
+++ b/var/spack/repos/builtin/packages/assimp/package.py
@@ -39,3 +39,9 @@ class Assimp(CMakePackage):
     def cmake_args(self):
         args = ['-DASSIMP_BUILD_TESTS=OFF']
         return args
+
+    def flag_handler(self, name, flags):
+        flags = list(flags)
+        if name == 'cxxflags':
+            flags.append(self.compiler.cxx11_flag)
+        return (None, None, flags)

```

But I get a different error [some sources are not compiled with -fPIC]


[spack-build.out-2.txt](https://github.com/spack/spack/files/2361794/spack-build.out-2.txt)

**Comment by masterleinad** [comment]
> p.s. @masterleinad : you build with Intel compilers, did you have issues building assimp?

I don't have any problems with `assimp-3.3.1` and `ICC 16`, `ICC 17`, `ICC 18` and `ICC 19`.

**Comment by balay** [comment]
ok - this works.

```diff
diff --git a/var/spack/repos/builtin/packages/assimp/package.py b/var/spack/repos/builtin/packages/assimp/package.py
index 9e3687a..8219e83 100644
--- a/var/spack/repos/builtin/packages/assimp/package.py
+++ b/var/spack/repos/builtin/packages/assimp/package.py
@@ -37,5 +37,15 @@ class Assimp(CMakePackage):
     depends_on('boost')
 
     def cmake_args(self):
-        args = ['-DASSIMP_BUILD_TESTS=OFF']
+        args = [
+            '-DASSIMP_BUILD_TESTS=OFF',
+            '-DBUILD_SHARED_LIBS:BOOL=%s' % (
+                'ON' if '+shared' in self.spec else 'OFF'),
+        ]
         return args
+
+    def flag_handler(self, name, flags):
+        flags = list(flags)
+        if name == 'cxxflags':
+            flags.append(self.compiler.cxx11_flag)
+        return (None, None, flags)
```

**Comment by balay** [comment]
Ok. I'll file a PR with this fix - and check a couple of builds..
