### ISSUE TITLE
Installation issue: py-spyder: The setuptools dependency causes build failure

### ISSUE THREAD

**Issue by neilflood** [spack/spack#9205]
---

### Steps to reproduce the issue

```console
$ spack install py-spyder
==> Installing py-spyder
==> Using cached archive: /opt/sw/fw/rsc/Spack/srcCache/py-spyder/py-spyder-3.1.3.tar.gz
==> Staging archive: /opt/sw/fw/rsc/Spack/spackSoftware/spack-20180706/var/spack/stage/py-spyder-3.1.3-b7euzpxm2zronjc4kmhgpskqrp4dwyyf/spyder-3.1.3.tar.gz
==> Created stage in /opt/sw/fw/rsc/Spack/spackSoftware/spack-20180706/var/spack/stage/py-spyder-3.1.3-b7euzpxm2zronjc4kmhgpskqrp4dwyyf
==> No patches needed for py-spyder
==> Building py-spyder [PythonPackage]
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/opt/sw/fw/rsc/Spack/installHome/linux-sles12-x86_64/gcc-7/python-2.7.15-hknd33vagen27gb4p7keyvx7c6i7f43e/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/opt/sw/fw/rsc/Spack/installHome/linux-sles12-x86_64/gcc-7/py-spyder-3.1.3-b7euzpxm2zronjc4kmhgpskqrp4dwyyf' '--single-version-externally-managed' '--root=/'

1 error found in build log:
     935    ==> '/opt/sw/fw/rsc/Spack/installHome/linux-sles12-x86_64/gcc-7/python-2.7.15-hknd33
            vagen27gb4p7keyvx7c6i7f43e/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'install'
            '--prefix=/opt/sw/fw/rsc/Spack/installHome/linux-sles12-x86_64/gcc-7/py-spyder-3.1.3
            -b7euzpxm2zronjc4kmhgpskqrp4dwyyf' '--single-version-externally-managed' '--root=/'
     936    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     937       or: setup.py --help [cmd1 cmd2 ...]
     938       or: setup.py --help-commands
     939       or: setup.py cmd --help
     940
  >> 941    error: option --single-version-externally-managed not recognized

```

### Platform and user environment

```commandline
$ uname -a 
Linux athena52 4.4.132-94.33-default #1 SMP Tue May 29 20:09:56 UTC 2018 (76aae3b) x86_64 x86_64 x86_64 GNU/Linux
``` 

### Additional information

The package.py has a depends_on('py-setuptools'), which is what causes it to include the switch for 
--single-version-externally-managed 
see build_systems/python.py line 253. 

However, it seems that spyder's setup.py does not actually use setuptools, and therefore does not recognise the extra option. If I comment out the dependency, then it build OK. 

I am a bit unsure how this ever worked, although since it has been there for quite some time, I presume that it did. So, I was not confident enough to suggest changing it without guidance, hence I am raising an issue, rather than a pull request. Feel free to tell me I am doing something silly.

**Comment by healther** [comment]
Seem that I screwed up the package checking and we only installed it with a pretty old version of spack (i.e. before `--single-version-externally-managed` was added). I'll have a PR in a couple of hours

**Comment by healther** [comment]
Mh this is interesting, from the `setup.py`

```
if 'setuptools' in sys.modules:
    setup_args['install_requires'] = install_requires

    setup_args['entry_points'] = {
        'gui_scripts': [
            '{} = spyder.app.start:main'.format(
                'spyder3' if PY3 else 'spyder')
        ]
    }

    setup_args.pop('scripts', None)
```

so they are not actually ever doing `import setuptools` but they are checking whether it is available... Iiuc, then without this line the `spyder` binary will not be available right? However this is only triggered if this is fulfilled
```
if any(arg == 'bdist_wheel' for arg in sys.argv):
    import setuptools     # analysis:ignore
```

I'd like someone with better knowledge of the python build eco system to take a look at that but I think removing `setuptools` is the right thing to do.

**Comment by neilflood** [comment]
Well spotted, I had not looked that far. 

I think that code seems to be for when someone is using the setup.py to create a wheel file.
https://wheel.readthedocs.io/en/stable/

If they use the bdist_wheel command to setup.py, it then imports setuptools, and uses that to create the wheel file. 

As far as I can figure, it would not affect normal building and installation in the way spack views the world. 

Does that make sense?

**Comment by healther** [comment]
That's what I figured, but it's largely conjecture.

can you take a look whether #9207 works for you?

**Comment by adamjstewart** [comment]
@healther @neilflood your analysis is correct, it looks like it only uses `setuptools` when building a wheel. This is actually pretty common, I've seen a lot of packages that do this. Removing the `setuptools` dep is the correct thing to do.
