### ISSUE TITLE
spack configure doesn't work for qt

### ISSUE THREAD

**Issue by healther** [spack/spack#9209]
While trying to fix `py-spyder` (#9205) I ran into a couple of problems (i.e. Qt, at least with version 4.8.6 doesn't build `webkit` even if asked nicely). Trying to debug this lead to the following:
```console
$ spack configure qt@4.8.6
==> Error: Package qt has no configure phase, or its configure phase is not separated from install
...
```
I think this has to do with the different overrides for different versions of Qt. Nevertheless I'd expect the command to work or at least report a truthful error message.

### Information on your system

Nothing that should be relevant for this. Can be reproduced at least on the HEAD of #9207 and the current develop (ccbff6e). I will not be able to look into this myself before the beginning of next week.

**Comment by alalazo** [comment]
Closing as outdated:
```console
$ spack configure
==> Error: configure is not a recognized Spack command or extension command; check with `spack commands`.
```
