### ISSUE TITLE
default versions for lmod modules

### ISSUE THREAD

**Issue by amklinv** [spack/spack#9305]
I appreciate that spack can generate lua module files, but I wish the module files respected the spack default version numbers.  For instance, if I define 2.7.14 to be the default python version in packages.yaml, and I install multiple pythons (because spack makes it so easy!), I'd like the default lua module for python to be version 2.7.14.  Spack doesn't seem to be assigning default versions for the lua module files.

Here's some information on what I'd like: https://lmod.readthedocs.io/en/latest/060_locating.html#marking-a-version-as-default

**Comment by amklinv** [comment]
@McClunatic

**Comment by alalazo** [comment]
Did you try:
```console
spack module lmod setdefault python@2.7.14
```
? That should do the trick.

**Comment by alalazo** [comment]
Closing as the question has been answered. Feel free to reopen if there's anything else to be discussed.
