### ISSUE TITLE
spack buildcache doesn't generate module files

### ISSUE THREAD

**Issue by Lnk2past** [spack/spack#9375]
I have encountered what I believe to be 2 bugs with the ```buildcache``` feature

- Bug 1: Cannot install dependencies from build cache
- Bug 2: Modules must be refreshed after being installed from buildcache

### Information on your system
I am running spack inside of Docker containers for SLES12 SP1. Other than what Spack needs to run, nothing else is installed in any of the containers.

### Bug 1 - cannot install from cache
Within Docker containers I have built a number of compilers using Spack (multiple versions of GCC and LLVM/Clang). For each one I created a buildcache and pushed them to a central webserver (all to the same repository, thus making me from index.html from each before uploading (otherwise we would be overwriting that file constantly).

While in another Docker container, I want to install another package that may share dependencies with some GCC or LLVM that was already built. I want to simply use whatever is in the build cache if it is there. So I add the mirror and install whatever it is I want to install.

e.g.
```
spack mirror add my_build_cache https://server/path/to/buildcache/
spack install --use-cache llvm@3.5.1
```

In this particular case, it is able to pull some packages out of the buildcache and build others that are not there, but fails with an unknown error when it tries to pull out ```bzip2@1.0.6``` from the build cache. _Nothing_ is reported, simply an ```==> Error:```

### Bug 2 - modules installed from build cache must be refreshed
After building a compiler in one Docker container and uploading it a build cache, I attempted to install it in another Docker container. I added my mirror pointing to the build cache, and simply did:

```
spack install gcc@8.2.0
```

This installation completed, but spack could not find the new compiler. I had to do the following:

```
spack module refresh gcc@8.2.0
```

At this point, spack was able to find the compiler.

**Comment by scheibelp** [comment]
> but fails with an unknown error when it tries to pull out bzip2@1.0.6 from the build cache. Nothing is reported, simply an ==> Error:

Could you redo the command with `-d`: `spack -d install --use-cache llvm@3.5.1`

> Docker container. I added my mirror pointing to the build cache, and simply did:
> `spack install gcc@8.2.0`

Without the `--use-cache` option enabled, this would have installed gcc from scratch (not that there's anything wrong with that, but FYI)

> This installation completed, but spack could not find the new compiler.

Some manual work is required to get Spack to use a compiler that is built with Spack. For example `spack compiler find` will search for compilers and automatically add them to your `compilers.yaml` file, but it will not search Spack installation prefixes by default so for example you can do `spack compiler add /path/to/spack/installed/gcc/bin/` and it should be added.

There are a few other ways to get Spack to recognize the compiler. I'm not clear on how `module refresh` by itself would expose the compiler (unless you also ran `spack compiler find` afterwards, since that searches `PATH`).

**Comment by scheibelp** [comment]
> I definitely meant `spack buildcache install ...`

`spack buildcache install` doesn't appear to do module generation, so for the time being the sequence you mentioned would be the best way to make `gcc` available. If before you did

```
spack buildcache install gcc...
spack load gcc@8.2.0
spack compiler find
```

The 2nd step would not have loaded the gcc just-installed with `spack buildcache`.

**Comment by Lnk2past** [comment]
Gotcha, should the buildcache install perform the module generation? This would be a problem for any dependencies that come in with the buildcache installation. I am still pretty new to spack, so I am not sure what the implications of that would be.

If this is something that should not be done, then the current work around (well... it is only a workaround if this is considered a bug =] ) is acceptable for my purposes and this can be closed.

**Comment by Lnk2past** [comment]
Also, thank you!

**Comment by scheibelp** [comment]
> should the buildcache install perform the module generation?

I think it should, so I'm going to update the title of this issue for clarity. I should have time to start on it next week - by 10/10

> Also, thank you!

Absolutely, you are welcome! Thanks for the report!

**Comment by Lnk2past** [comment]
This is great, thank you!
