### ISSUE TITLE
Error: SPACK_FC in spack setup

### ISSUE THREAD

**Issue by ibaned** [spack/spack#9395]
While trying to run `spack setup`, I get an error that seems to be due to `SPACK_FC` being undefined. Note that none of my software stack is written in Fortran. I'm on a Mac with no Fortran compiler.

### Steps to reproduce the issue

```console
$ spack -sd setup omega-h@local
```

### Error Message

```console
...
lib/spack/spack/cmd/setup.py:178 ==> Generating spconfig.py [omega-h@local%clang@9.0.0-apple~bounds build_type= ~examples~mpi+optimize+shared+symbols~throw+trilinos+warnings~zlib arch=darwin-sierra-x86_64 /wfri2bq]
lib/spack/llnl/util/lock.py:353 ==> WRITE LOCK: /Users/daibane/src/spack/opt/spack/.spack-db/lock[0:0] [Released]
Traceback (most recent call last):
  File "/Users/daibane/src/spack/bin/spack", line 54, in <module>
    sys.exit(spack.main.main())
  File "/Users/daibane/src/spack/lib/spack/spack/main.py", line 653, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/daibane/src/spack/lib/spack/spack/main.py", line 432, in _invoke_command
    return_val = command(parser, args)
  File "/Users/daibane/src/spack/lib/spack/spack/cmd/setup.py", line 181, in setup
    write_spconfig(package, dirty)
  File "/Users/daibane/src/spack/lib/spack/spack/cmd/setup.py", line 87, in write_spconfig
    env['FC'] = os.environ['SPACK_FC']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'SPACK_FC'
```

### Information on your system

macOS Sierra system...

**Comment by pramodk** [comment]
We need to have fortran compiler. You can safely add gfortran with clang, for example I have one from brew that I added as: 

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
```

**Comment by davydden** [comment]
Or install GCC via Spack and then add path to Fortran

**Comment by ibaned** [comment]
This seems like an unnecessary requirement... I just added an `if` statement to my local copy of Spack to omit that line of code if there is no Fortran compiler, and everything worked just fine. Why should every developer of a purely C/C++ stack have to download and compile a Fortran compiler?

**Comment by pramodk** [comment]
> This seems like an unnecessary requirement..

the issues is that setup will be fine but it will fail somewhere in the dependencies. For example, MPI packages expects working fortran compiler.
