### ISSUE TITLE
Should depends_on override version preferences?

### ISSUE THREAD

**Issue by scheibelp** [spack/spack#9414]
See: https://github.com/spack/spack/pull/9335

Spack's python package prefers installing version `2.7.15`, this takes precedence even when a dependent package requires a later version via the `depends_on`, namely `py-matplotlib`.

The proposal is that `version(..., preferred=True)` should be overridden when a dependent package specifies a later version with `depends_on`.

**Comment by alalazo** [comment]
On top of that: do we still need to say that `python@2.7.15` is the preferred one? [Clock is ticking...](https://pythonclock.org/)

**Comment by healther** [comment]
I'd strongly argue for "dependencies override defaults" but I'd be less certain about dropping the preferences. While I'm personally strongly in favour of not running out the clock, I'm relatively certain that quite a number of systems out there are still tied to 2.7 (unfortunately so is our own ...)

**Comment by adamjstewart** [comment]
Is this discussion still relevant? I think everyone agrees that `depends_on` should override preferences, but the concretizer is not currently smart enough to do that.

P.S. We now default to Python 3.7 so this particular issue is no longer present, although the question of concretization still remains.

**Comment by healther** [comment]
We switched to manually annotating most things that let to conflicts (especially wrt to py2) anyways, so feel free to close
