### ISSUE TITLE
Travis jobs update their system

### ISSUE THREAD

**Issue by healther** [spack/spack#9464]
Something weird is going on with Travis. I retriggered #9440 as one unit test timed out when it originally ran, but this time the style check took O(25) minutes. Turns out it spend most of that time performing updates to its system https://travis-ci.org/spack/spack/jobs/437672380

Is this a known problem and/or do we need to change anything in the Travis setup?

**Comment by alalazo** [comment]
Travis has had a few problems lately like: https://twitter.com/traviscistatus/status/1049709461969850368
