### ISSUE TITLE
gromacs does not resolve cmake versions over 3.9.x

### ISSUE THREAD

**Issue by briedel** [spack/spack#9488]
gromacs package resolves cmake as `3.9.6`. Trying it with `3.12.2` works. Seems like the reason is 

```
     depends_on('cmake@2.8.8:3.9.99', type='build')
     depends_on('cmake@3.4.3:3.9.99', type='build', when='@2018:')
```

that the definition only reaches `3.9.99`, should be extended to `3.19.99` to reach `3.12.2`. 

Two things to note here:

1. Undefined end does not go beyond >= 10 in the minor version, e.g. `3.10.0`
```
     depends_on('cmake@3.4.3:', type='build', when='@2018:')
```

did not work as well. It only reached `3.9.99`.

2. Somehow it the `when` statement was ignored. Not sure why

**Comment by scheibelp** [comment]
If you didn't remove the first constraint, then to be clear, all constraints are applied: both

`depends_on('cmake@2.8.8:3.9.99', type='build')`

and

`depends_on('cmake@3.4.3:', type='build', when='@2018:')`

The second has a wider range, but when you combine the constraints, you get `cmake@3.4.3:3.9.99`

Does `gromacs` fail to build with `cmake@3.9.6`? If so, an additional constraint should be added to build newer versions of `gromacs` with a newer CMake; the old constraints should likely now include a version range upper bound in their when clauses.

**Comment by briedel** [comment]
Ahh that makes sense. It works with `cmake@3.9.6`, I just don't want to install multiple cmake versions

**Comment by alalazo** [comment]
@briedel I am closing this issue as @scheibelp has answered the question. Feel free to reopen if you think there's something else that needs to be addressed.
