### ISSUE TITLE
scikit-learn with python 3.7.0 requires 0.20

### ISSUE THREAD

**Issue by briedel** [spack/spack#9490]
scikit-learn needs >= 0.20 with python 3.7.0

**Comment by healther** [comment]
Are you trying to say that `scikit-learn<0.20` doesn't work with `python@3.7.0:`?

**Comment by alalazo** [comment]
Can you submit a PR?

**Comment by briedel** [comment]
What is the canonical way to fix this? Conflict?

**Comment by healther** [comment]
I think a `depends_on('python@3.7.0:')` should work, you can also add a conflicts if you like (would probably make the error easier to parse for the user)
