### ISSUE TITLE
py-bottleneck requires update for python 3.7.0

### ISSUE THREAD

**Issue by briedel** [spack/spack#9500]
`pybottleneck@1.2.1:` when `python@3.7.0:`

**Comment by alalazo** [comment]
Can you submit a PR?

**Comment by briedel** [comment]
What is the canonical way to fix this? Conflict?

**Comment by healther** [comment]
according to their github:

> Bottleneck | Python 2.7, 3.5, 3.6; NumPy 1.12.1

**Comment by adamjstewart** [comment]
I was able to install `py-bottleneck@1.2.1` with `python@3.7.4`. Can you clarify what issues you encountered? A lot of times a package works fine in Python 3.7 but the developers haven't tested it yet or updated their PyPI page to claim Python 3.7 support.

**Comment by alalazo** [comment]
Closing as unreproducible per @adamjstewart comment. Feel free to reopen if you have a reproducer.
