### ISSUE TITLE
py-pandas requires update for Python 3.7

### ISSUE THREAD

**Issue by briedel** [spack/spack#9502]
`py-pandas@0.23.4:` needed for `python@3.7.0:`

**Comment by alalazo** [comment]
Can you submit a PR?

**Comment by healther** [comment]
And where do you get that information from? According to their website:

> Python version support
Officially Python 2.7, 3.5, 3.6, and 3.7.

They plan to drop 2.7 starting 1.1.2019

**Comment by alalazo** [comment]
Closing per @healther comment. Feel free to reopen if still an issue.
