### ISSUE TITLE
Include accurate build time in CDash report

### ISSUE THREAD

**Issue by zackgalbreath** [spack/spack#9590]
Report to CDash how long it took to install package(s)

### Rationale

Currently the CDash reporter sends up a build time of 0s to CDash.  But Spack knows how long it actually took to install a package:
```
==> Successfully installed python
  Fetch: 0.07s.  Build: 2m 33.14s.  Total: 2m 33.21s.
```
So we should be able to pass this info up to CDash.

### Description

Track the build time for each package installed by `spack install`.  Tally these values up and report the total to CDash.

**Comment by tgamblin** [comment]
Fixed by #9749.
