### ISSUE TITLE
ignore .DS_Store. 

### ISSUE THREAD

**Issue by davydden** [spack/spack#9659]
~~I don't know why or which editor creates a~~ macOS filesystem creates [.DS_Store](https://en.wikipedia.org/wiki/.DS_Store) files in folders 
```
spack/var/spack/repos/builtin/packages/.DS_Store
```
one should add this file to the ignore lists so that one does not get
```
==> Warning: Skipping package at /spack/var/spack/repos/builtin/packages/.DS_Store. ".DS_Store" is not a valid Spack module name.

**Comment by adamjstewart** [comment]
@davydden is this still an issue? I know I've seen this before, but I can no longer reproduce it with `spack list`. Maybe this has been fixed?

**Comment by davydden** [comment]
Let's close this for now.
