### ISSUE TITLE
Installation issue: py-scikit-learn

### ISSUE THREAD

**Issue by rgmiller** [spack/spack#9677]
It looks like the  `depends_on('python@2.6:2.8,3.3:')` line in the scikit-learn package is inadequate.  

scikit-learn 19.1 won't build against python 3.7.0 due to an apparent API change.  It reports lots of errors along the lines of:
>sklearn/cluster/_dbscan_inner.cpp:6034:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?

Additionally, Python 2.6 and 3.3 aren't supported by the newer versions of scikit-learn.

I think we're going to need several `depends_on(..., when='...')` lines to sort things out correctly.  While we're at it, we should probably add a `depends_on('py-setuptools')` line, since scikit-learn does use setup.py.

### Steps to reproduce the issue

```console
$ spack install py-scikit-learn@0.19.1 ^python@3.7.0 # This is just one example of mismatched dependencies
```

31 build errors.  These are just the last 3:
```console
  >> 709    sklearn/cluster/_dbscan_inner.cpp:6032:13: error: 'PyThreadState' {aka 'struc
            t _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     710         tstate->exc_type = local_type;
     711                 ^~~~~~~~
     712                 curexc_type
  >> 713    sklearn/cluster/_dbscan_inner.cpp:6033:13: error: 'PyThreadState' {aka 'struc
            t _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
     714         tstate->exc_value = local_value;
     715                 ^~~~~~~~~
     716                 curexc_value
  >> 717    sklearn/cluster/_dbscan_inner.cpp:6034:13: error: 'PyThreadState' {aka 'struc
            t _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     718         tstate->exc_traceback = local_tb;
     719                 ^~~~~~~~~~~~~
     720                 curexc_tracebackPartial import of sklearn during the build proce
            ss.
     721    

```

### Platform and user environment

Please report your OS here:
```commandline
xmr@boo4:~/git/spack_fork/var/spack/repos/builtin/packages$ uname -a
Linux boo4 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
xmr@boo4:~/git/spack_fork/var/spack/repos/builtin/packages$ lsb_release -d
Description:    Ubuntu 18.04.1 LTS
```

**Comment by rgmiller** [comment]
Pull request #9693 created.  That said, the changes in the PR introduce the same kind of open-ended dependency versions that we just fixed in issue #9667.

@ax3l - Is there a 'best-practices' for this sort of thing?  Leave them open-ended and update the package when somebody notices it's broken?  Put hard limit on the versions, but then have to update the package when a newer version of some dependency comes along?  (It seems like either way, we have to constantly maintain package dependencies... )

**Comment by ax3l** [comment]
> Is there a 'best-practices' for this sort of thing? Leave them open-ended and update the package when somebody notices it's broken?

We don't have a policy on those yet but I try to advocate for keeping them tight to tested versions of dependencies on release. The rationale is simple: if a maintainer could never have tested newer releases of dependencies, why should they work? Of course we can always increase dependency version ranges, but please after testing.

**Comment by adamjstewart** [comment]
`py-scikit-learn` has undergone quite an overhaul since this issue is opened. I now regularly build and test `py-scikit-learn` with Python 3.7.4, so I think this issue can be closed now. Feel free to reopen if you encounter any other issues.
