### ISSUE TITLE
Installation issue: glib ^python@3:

### ISSUE THREAD

**Issue by ptbremer** [spack/spack#9719]
### Steps to reproduce the issue

```console
$ spack install glib ^python@3: 
```
leads to 

==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'install'

6 errors found in build log:
     1590     /usr/bin/install -c -m 644 ./html/right.png
     1591     /usr/bin/install -c -m 644 ./html/style.css
     1592     /usr/bin/install -c -m 644 ./html/tools.html
     1593     /usr/bin/install -c -m 644 ./html/up-insensitive.png
     1594     /usr/bin/install -c -m 644 ./html/up.png
     1595    ImportError: No module named site

which seems to be an error with the python path 

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Darwin orca.llnl.gov 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
``` 
### Additional information

The same thing happens for 

```console
$ spack install glib ^python@3.6.4 
```
```console
$ spack install glib ^python@3.1.4
```

but not for the python default which is equivalent to 

```console
$ spack install glib ^python@2.7.15
```

**Comment by michaelkuhn** [comment]
FWIW: This seems to be macOS-specific because it works on my Linux machines.

**Comment by Sinan81** [comment]
seems to be the same error reported in #8058

**Comment by Sinan81** [comment]
same error shows up on linuxmint19 (and possibly on ubuntu 18.04.1)  #9769

**Comment by michaelkuhn** [comment]
@ptbremer Could you please check whether #9771 fixes this problem for you? Thanks!

**Comment by ptbremer** [comment]
@michaelkuhn Yes, #9771 does fix this. I have tried 

spack install glib ^python@3.7.0

and

spack install glib ^python@3.6.4

Both finish without problems

**Comment by michaelkuhn** [comment]
Awesome! Thanks for testing. :-)
