### ISSUE TITLE
Freetype tries to include windows.h resulting in an error

### ISSUE THREAD

**Issue by jrood-nrel** [spack/spack#9729]
I am seeing this error with Freetype 2.9.1 and I'm using binutils 2.29.1:
```
freetype-2.9.1/src/base/ftver.rc:19:20: fatal error: windows.h: No such file or directory
 #include<windows.h>
                    ^
compilation terminated.
windres: preprocessing failed.
```

I see this error reported in https://mail-index.netbsd.org/pkgsrc-users/2018/08/10/msg027329.html and https://github.com/Linuxbrew/homebrew-core/issues/7625 so I reported it to Freetype here https://savannah.nongnu.org/bugs/index.php?54967 . Posting this as an issue here in case anyone else runs into this error. Why does Freetype always have so many problems?

Edit: For me the solution has been to use freetype 2.7.1.

**Comment by adamjstewart** [comment]
I just encountered this issue as well. It looks like they wrote a [patch](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=3b6e65f7bf674601b9419d02ce0aa633e2e882fb) to fix this. Let me see if I can regenerate `configure` and patch that directly so we don't have to run `autoreconf` on installation.
