### ISSUE TITLE
Variants might be conditional on the version of the package

### ISSUE THREAD

**Issue by alalazo** [spack/spack#9740]
As a packager I want the possibility to attach variants to a spec depending on its version so that I can model in a more natural way the evolution of the features of a package over time.

### Rationale

Many packages evolve during time and they add or remove features as they see fit. As we support more and more versions of the same package we might be faced with the problem of having either to expose just the "lowest common denominator" (i.e. only the features supported by *all* the versions) or to explicitly manage conflicts among variants and package versions. A prime example of this is `boost`, for which we have an issue open since a couple of years (see #1486). If variants could depend on the package version this issue would be solved neatly.

### Description

The proposal here is to extend the allowed syntax for the variant directive to allow for a version range to be specified:
```python
class Boost(Package):
    ...
    variant('atomic', description='...', applies_to='@1.53:')
```
The directive above means that the variant `atomic` exists for the package starting at version 1.53. Any command that refers to it for a version that does not satisfy the constraint should fail with an error:
```console
$ spack spec boost@1.52.0+atomic
Input spec
--------------------------------
boost@1.52.0+atomic

Concretized
--------------------------------
==> Error: Package boost has no variant 'atomic' at version 1.52.0 [the variant starts at 1.53.0]
```
This should also affect the concretizer in the other way around (if we ask for `boost+atomic` we have an implicit constraint on `boost@1.53.0:`). Probably also `spack info` should be updated to match the new feature:
```console
$ spack info boost
...
Variants:
    Name [Default]       Allowed values      Description                    Range of validity


    atomic [on]          True, False         Compile with atomic library    @1.53.0:
    chrono [on]          True, False         Compile with chrono library
...
```

**Comment by eirrgang** [comment]
Can you clarify how this is different from https://spack.readthedocs.io/en/latest/packaging_guide.html#conflicts ?

**Comment by haampie** [comment]
Conflicts apply to the values of variants, this applies to the existence of variants.

**Comment by alalazo** [comment]
@eirrgang `conflicts` is a way to declare an invalid configuration for your spec. This proposal (which may need to be revisited in some aspects) is instead a way to express that some variants may not exist at all outside some version ranges. The idea is to be able to model packages that have a moving set of features (modeled as variants) without the current imposition that a concretized spec at version X.Y should set:
- All the features that existed and have been deprecated before X.Y
- All the features that have been added after X.Y

to false, cluttering the representation of the final spec.
