### ISSUE TITLE
OpenCV concretization error

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#9753]
Trying to build OpenCV via spack, however getting concretization error

### Steps to reproduce the issue

```console
$ spack install opencv
==> Error: An unsatisfiable version constraint has been detected for spec:

    flex@2.6.3%gcc@8.2.0+lex arch=linux-linuxmint19-x86_64 

while trying to concretize the partial spec:

    scotch


scotch requires flex version :2.6.1,2.6.4:, but spec asked for 2.6.3
....
```

### Error Message

See above.

### Information on your system

1. platform: arch=linux-linuxmint19-x86_64
2. no custom packages.yaml file
3. working with latest git pull of the develop branch

**Comment by Sinan81** [comment]
This problem can be temporarily avoided by specifying the preferred flex version either at the command line or in the packages.yaml file.
````
$ spack install opencv ^flex@2.6.4
...
````

**Comment by Sinan81** [comment]
Next error is:
````
$ spack install opencv ^flex@2.6.4 ^python@3.7.0
==> Error: Multiple providers found for 'gl@3.2:': ['mesa@18.1.2%gcc@8.2.0~hwrender~llvm+swrender arch=linux-linuxmint19-x86_64', 'opengl@4.5%gcc@8.2.0 arch=linux-linuxmint19-x86_64']
````
which implies that we should be specifying gl and opengl versions in `packages.yaml`

**Comment by Sinan81** [comment]
Removed packages.yaml, and following #9408, did
````
$ spack spec opencv ^flex@2.6.4 ^python@3.7.0 ^vtk+osmesa
Input spec
--------------------------------
opencv
    ^flex@2.6.4
    ^python@3.7.0
    ^vtk+osmesa

Concretized
--------------------------------
==> Error: Conflicts in concretized spec "opencv@3.4.3%gcc@8.2.0 build_type=RelWithDebInfo +calib3d+core+cuda+dnn+eigen~fast-math+features2d+flann+gtk+highgui+imgproc+ipp+ipp_iw+jasper+java+jpeg+lapack+ml+opencl+opencl_svm+openclamdblas+openclamdfft+openmp+png~powerpc+pthreads_pf+python~qt+shared+stitching+superres+tiff+ts+video+videoio+videostab~vsx+vtk+zlib arch=linux-linuxmint19-x86_64 /so7sqra"
...
1. "%gcc@7.2.0:" conflicts with "flex@2.6.4"
````
not sure where gcc%7.2 thing is coming from as default compiler is gcc8.2. Downgraded flex, and now concretization seems to be working:
````
$ spack spec opencv ^flex@2.6.1 ^python@3.7.0 ^vtk+osmesa
...
````

**Comment by scheibelp** [comment]
This is related to https://github.com/spack/spack/issues/2632

I have placed this under item (1) of https://github.com/spack/spack/wiki/Issue-Disambiguation

**Comment by Sinan81** [comment]
It seems a new concretisation error has appeared for opencv:
````
==> Error: An unsatisfiable variant constraint has been detected for spec:

    hdf5@1.10.5%gcc@8.2.0~cxx~debug~fortran~hl+mpi+pic+shared~szip~threadsafe arch=linux-linuxmint19-x86_64 
````
which is also reported in #11166. Following the suggestion in that issue, replaced `depends_on('hdf5')` in vtk package file with `depends_on('hdf5+hl')` after which concretization works:
````
$ spack spec opencv ^flex@2.6.1 ^python@3.7.0 ^vtk+osmesa
opencv
    ^flex@2.6.1
    ^python@3.7.0
    ^vtk+osmesa

Concretized
...
````
