### ISSUE TITLE
glib build fails (both for python2x and 3x)

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#9769]
### Steps to reproduce the issue

```console
$ spack install glib 
```
in the log we are seeing the following errors:

````
1831  /usr/bin/install -c -m 644 ./html/up-insensitive.png
1832  /usr/bin/install -c -m 644 ./html/up.png
1833 Traceback (most recent call last):
1834   File "/usr/bin/gtkdoc-rebase", line 28, in <module>
1835     from gtkdoc import common, config, rebase
1836   File "/usr/share/gtk-doc/python/gtkdoc/common.py", line 31, in <module>
1837     import six
1838 ImportError: No module named six
1839 Makefile:1034: recipe for target 'install-data-local' failed
1840 make[5]: *** [install-data-local] Error 1
1841 make[5]: Leaving directory '/tmp/sinan/spack-stage/spack-stage-9BmR48/glib-2.56.2/docs/reference/glib'
1842 Makefile:776: recipe for target 'install-am' failed
1843 make[4]: *** [install-am] Error 2
1844 make[4]: Leaving directory '/tmp/sinan/spack-stage/spack-stage-9BmR48/glib-2.56.2/docs/reference/glib'
1845 Makefile:484: recipe for target 'install-recursive' failed
1846 make[3]: *** [install-recursive] Error 1
1847 make[3]: Leaving directory '/tmp/sinan/spack-stage/spack-stage-9BmR48/glib-2.56.2/docs/reference'
1848 Makefile:485: recipe for target 'install-recursive' failed
1849 make[2]: *** [install-recursive] Error 1
1850 make[2]: Leaving directory '/tmp/sinan/spack-stage/spack-stage-9BmR48/glib-2.56.2/docs'
1851 Makefile:1279: recipe for target 'install-recursive' failed
1852 make[1]: *** [install-recursive] Error 1
1853 make[1]: Leaving directory '/tmp/sinan/spack-stage/spack-stage-9BmR48/glib-2.56.2'
1854 Makefile:1748: recipe for target 'install' failed
````
[spack-build.out.txt](https://github.com/spack/spack/files/2563044/spack-build.out.txt)

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a
Linux storm 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    Linux Mint 19 Tara
``` 
This error should be also reproduceable on Ubuntu 18.04.1

I think this is not a major problem as error has to do with the building of the documentation. If I understand correctly, glib is attempting to use already existing gtk documentation in the system.

**Comment by Sinan81** [comment]
Added a py-six dependency to glib spack file:
````
...
 depends_on('py-six', type=('build', 'run'), when='@2.53.4:')
...
````
now it seems build is working!

**Comment by Sinan81** [comment]
with python 3.7.0, we are getting "ImportError: No module named site" error.

**Comment by michaelkuhn** [comment]
@Sinan81 Could you please check whether #9771 fixes the problem for you?

**Comment by Sinan81** [comment]
It does however now I am getting "import argparse" error. I will try completely disabling gtk-doc instead via "--disable-gtk-doc" It might be useful to disable gtk-doc by default and make it variant, and when variant is selected, introduce necessary python dependencies.

**Comment by Sinan81** [comment]
`args = ['--disable-gtk-doc']` yielded the same error: "ImportError: No module named argparse"

**Comment by Sinan81** [comment]
It seems now error is not originating from gtk-doc but something else.

**Comment by michaelkuhn** [comment]
`--disable-gtk-doc` should not be necessary because it defaults to off. For some reason, only `--enable-gtk-doc-html` is set by default.

The `import argparse` errors likely originate from glib's glib-genmarshal and glib-mkenums tools, which cannot be disabled.

**Comment by michaelkuhn** [comment]
Could you please check whether your python installation contains the argparse module? Something like `find opt/spack/*/*/python* -iname '*argparse*'` should do the trick.

**Comment by michaelkuhn** [comment]
@Sinan81 I just pushed a new version of #9771 that tries to disable gtk-doc completely. Could you please give it a go? Thanks!

**Comment by Sinan81** [comment]
@michaelkuhn Among 4 installations of python i have, argparse seems to exist in all but one: python@3.1.5
````
/var/spack/opt/spack/linux-linuxmint19-x86_64/gcc-8.2.0/python-2.7.15-tt2hojvsoiriwj7rtpbxa3ahklxrz4fw/lib/python2.7/argparse.py
/var/spack/opt/spack/linux-linuxmint19-x86_64/gcc-8.2.0/python-3.4.3-glj3aysvjsucock4eu7jf6rtqn3uleyu/lib/python3.4/argparse.py
/var/spack/opt/spack/linux-linuxmint19-x86_64/gcc-8.2.0/python-3.7.0-doppeb6h67b23d2iuub43btjknasg7mh/lib/python3.7/argparse.py
````

**Comment by Sinan81** [comment]
I confirm that without gtk-doc stuff (see #9771), glib installs successfully for python versions 2.7.15, 3.2.6, 3.4.3, 3.7.0 but not 3.1.5 due to missing argparse module.

**Comment by michaelkuhn** [comment]
Awesome! I am not yet sure how we should handle python@:3.1, though.
