### ISSUE TITLE
spack install fails on macOS

### ISSUE THREAD

**Issue by davydden** [spack/spack#9787]
`spack install pkgconfig` fails with

```
==> Installing pkgconf
==> Searching for binary cache of pkgconf
==> Warning: No Spack mirrors are currently configured
==> No binary for pkgconf found: installing from source
==> Error: [Errno 13] Permission denied: '/-'
```

I have a feeling it's related to https://github.com/spack/spack/pull/9772 

@becker33 @tgamblin @scheibelp ping.

**Comment by scheibelp** [comment]
Can you rerun with `-d`?

**Comment by scheibelp** [comment]
That is, `spack -d install...`

**Comment by davydden** [comment]
```
==> Searching for binary cache of pkgconf
==> Warning: No Spack mirrors are currently configured
==> No binary for pkgconf found: installing from source
Traceback (most recent call last):
  File "/Users/davydden/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/Users/davydden/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/davydden/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/install.py", line 296, in install
    install_spec(args, kwargs, spec)
  File "/Users/davydden/spack/lib/spack/spack/cmd/install.py", line 173, in install_spec
    install(spec, kwargs)
  File "/Users/davydden/spack/lib/spack/spack/cmd/install.py", line 162, in install
    spec.package.do_install(**kwargs)
  File "/Users/davydden/spack/lib/spack/spack/package.py", line 1402, in do_install
    **kwargs)
  File "/Users/davydden/spack/lib/spack/spack/package.py", line 1511, in do_install
    spack.store.layout.create_install_directory(self.spec)
  File "/Users/davydden/spack/lib/spack/spack/directory_layout.py", line 253, in create_install_directory
    mkdirp(spec.prefix, mode=perms)
  File "/Users/davydden/spack/lib/spack/llnl/util/filesystem.py", line 435, in mkdirp
    raise e
OSError: [Errno 13] Permission denied: '/-'
```

**Comment by davydden** [comment]
this is on 236b34f3df38d0f44ada307ece354f92a96a6a91

**Comment by davydden** [comment]
here's my config
```
config:
  build_stage:
  - $spack/var/spack/stage
  checksum: true
  dirty: false
  install_tree: $spack/opt/spack
  misc_cache: ~/.spack/cache
  module_roots:
    dotkit: $spack/share/spack/dotkit
    lmod: $spack/share/spack/lmod
    tcl: $spack/share/spack/modules
  source_cache: $spack/var/spack/cache
  verify_ssl: true
```
(that I have not touched for a while).

**Comment by baberlevi** [comment]
just tested on Mac OS 10.12.6, can't seem to reproduce. Working from same spack commit.  Output of my spack debug seems to move right from `No binary...` to `Fetching...` as expected.

**Comment by scheibelp** [comment]
Does every package give you this error? Or just pkgconf?

Would you be able to add a print statement just before line 253 of `directory_layout` to print `spec.prefix`? I can also open a PR which will print out some debug info if preferred.

It appears that somehow, it is being set to include `/-` as a part of the path

**Comment by davydden** [comment]
> Does every package give you this error? Or just pkgconf?

strangely enough, certainly not every package. Say `openblas` goes on with installation...

I was trying to do `git bisect` to see which commit introduce this, **without installing pkgconf**. However something changed and I can no longer reproduce the issue. Also Spack tells me that `pkgconf` is already installed.

I am absolutely puzzled about what was going on, but I can't reproduce it anymore and I have not installed anything or edited any config file... Bizarre..

**Comment by tgamblin** [comment]
> I am absolutely puzzled about what was going on, but I can't reproduce it anymore and I have not installed anything or edited any config file... Bizarre..

Let us know if you figure this out -- I would like to ensure that this doesn't bite anyone!

**Comment by alalazo** [comment]
Just a guess, but could it be due to some outdated `*.pyc` file somewhere + changing or updating a branch?

**Comment by erimar77** [comment]
Looks like we've been hit with this too.  Installing `shortbred` errors out on the `libjpeg-turbo` installation. 
```
==> Installing libjpeg-turbo
==> Searching for binary cache of libjpeg-turbo
==> Warning: No Spack mirrors are currently configured
==> No binary for libjpeg-turbo found: installing from source
==> Error: [Errno 13] Permission denied: '/-'
```

**Comment by scheibelp** [comment]
@erimar77 is this error repeatable for you? Or is it intermittent?

What OS are you on?

Following 
https://github.com/spack/spack/issues/9787#issuecomment-437835701, does `spack clean -p` resolve the issue for you?

**Comment by erimar77** [comment]
@scheibelp Occurs on both Ubuntu 18.04 and 16.04.

**Comment by goxberry** [comment]
I ran into this earlier on macOS, and vaguely remember a reboot being helpful.

**Comment by scheibelp** [comment]
I had trouble reproducing this for `libjpeg-turbo` (mentioned in https://github.com/spack/spack/issues/9787#issuecomment-439195021) in an Ubuntu 18.04 docker image. Did the suggestion to reboot help?

**Comment by cpraveen** [comment]
I get this on mojave. Does not happen for all. Got it for mpich. So switched to openmpi which compiled. But then same error for netlib-scalapack.

**Comment by cpraveen** [comment]
Reboot did not solve this for me.

**Comment by davydden** [comment]
@cpraveen since you seem to be able to reproduce the proble, could you try https://github.com/spack/spack/issues/9874 branch with extra debug output? That could help fixing this issue

**Comment by cpraveen** [comment]
I tried this

```
git fetch origin pull/9874/head:9874
git checkout 9874
spack install -j4 --only dependencies dealii@develop
```

I dont see any more info, just this

```
==> Installing netlib-scalapack
==> Searching for binary cache of netlib-scalapack
==> Warning: No Spack mirrors are currently configured
==> No binary for netlib-scalapack found: installing from source
==> Error: [Errno 13] Permission denied: '/-'
```

**Comment by erimar77** [comment]
@scheibelp Here's the additional output using #9874
```
==> Installing jdk
==> Searching for binary cache of jdk
==> Warning: No Spack mirrors are currently configured
==> No binary for jdk found: installing from source
==> [9787] Spec prefix: /-/jdk-11.0:11.999-7a675nspoabgoxhkablthy52b36x2rde
==> [9787] permissions: 2755
==> [9787] Attempted path: /-/jdk-11.0:11.999-7a675nspoabgoxhkablthy52b36x2rde
Traceback (most recent call last):
  File "/opt/htcf/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/opt/htcf/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/htcf/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/opt/htcf/spack/lib/spack/spack/cmd/install.py", line 302, in install
    install_spec(args, kwargs, abstract, concrete)
  File "/opt/htcf/spack/lib/spack/spack/cmd/install.py", line 179, in install_spec
    install(spec, kwargs)
  File "/opt/htcf/spack/lib/spack/spack/cmd/install.py", line 168, in install
    spec.package.do_install(**kwargs)
  File "/opt/htcf/spack/lib/spack/spack/package.py", line 1402, in do_install
    **kwargs)
  File "/opt/htcf/spack/lib/spack/spack/package.py", line 1511, in do_install
    spack.store.layout.create_install_directory(self.spec)
  File "/opt/htcf/spack/lib/spack/spack/directory_layout.py", line 257, in create_install_directory
    mkdirp(spec.prefix, mode=perms)
  File "/opt/htcf/spack/lib/spack/llnl/util/filesystem.py", line 437, in mkdirp
    raise e
OSError: [Errno 13] Permission denied: '/-'
```

**Comment by erimar77** [comment]
Also, if I explicitly pass jdk, it finds the installed version and installs as expected. 

```
$ spack spec trimmomatic
Input spec
--------------------------------
trimmomatic

Concretized
--------------------------------
trimmomatic@0.36%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64
    ^jdk@11.0.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64
```


```
$ spack install trimmomatic ^jdk@11.0.1
==> jdk is already installed in /opt/htcf/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/jdk-11.0.1-efh4yky3bt3i6g3b7fdetu4nms2ahea5
==> Installing trimmomatic
==> Searching for binary cache of trimmomatic
==> Warning: No Spack mirrors are currently configured
==> No binary for trimmomatic found: installing from source
==> Using cached archive: /opt/htcf/spack/var/spack/cache/trimmomatic/trimmomatic-0.36.zip
==> Staging archive: /opt/htcf/spack/var/spack/stage/trimmomatic-0.36-qt4qmt64sfuecpvt2vrxarziihjdwont/Trimmomatic-0.36.zip
==> Created stage in /opt/htcf/spack/var/spack/stage/trimmomatic-0.36-qt4qmt64sfuecpvt2vrxarziihjdwont
==> No patches needed for trimmomatic
==> Building trimmomatic [Package]
==> Executing phase: 'install'
==> Successfully installed trimmomatic
  Fetch: 0.00s.  Build: 0.50s.  Total: 0.50s.
[+] /opt/htcf/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/trimmomatic-0.36-qt4qmt64sfuecpvt2vrxarziihjdwont
```

Using the java provider does not:
```
spack install trimmomatic ^java
==> Installing jdk
==> Searching for binary cache of jdk
==> Warning: No Spack mirrors are currently configured
==> No binary for jdk found: installing from source
==> Error: [Errno 13] Permission denied: '/-'
```

**Comment by scheibelp** [comment]
Thanks for the reports!

It looks like this is affecting providers of virtual packages. I have a notion of why and should be able to resolve it by the end of today.

**Comment by koebbe** [comment]
FWIW, I removed `.misc_cache/providers/builtin-index.yaml`  and re-ran `spack install java` (which had failed previously with the same type of error).  After removing that, the java install worked (meaning spack recognized that jdk was already installed).

**Comment by scheibelp** [comment]
It turns out that removing this file as @koebbe suggests should permanently resolve the issue. Although I don't see that exact path, rather I see `~/.spack/cache/providers/builtin-index.yaml`

Spack will regenerate this file once you remove it, but when the file is regenerated it will have the correct values and so the problem will not come up again.

In more detail:

This was introduced by https://github.com/spack/spack/commit/562482d9cc47b2b689a3540538942d35e7c60f53, which modified how specs were read from and written to yaml. The commit started recording whether the Spec was concrete in the Spec dictionary, but only in certain cases (to avoid changing hashes for all packages universally). The commit assumes that Spec dictionaries without this property are concrete. This creates an issue for provider index caches which were created prior to the commit.

**Comment by scheibelp** [comment]
`spack clean -m` will also resolve this issue.

**Comment by davydden** [comment]
Thanks @scheibelp . Given that this is not an issue for a fresh Spack install, should we close this?
