### ISSUE TITLE
travis build fails to upgrade pip

### ISSUE THREAD

**Issue by opadron** [spack/spack#9806]
Original issue identified in #9658.

The travis build seems to fail when upgrading pip due to what appears to be a permissions issue.

See https://travis-ci.org/spack/spack/jobs/446971259 for an example job that demonstrates the issue.

**Comment by opadron** [comment]
Taking a look at #9776 and #9815, this appears to be a known issue that we're sidestepping for the time being.  Is that right?  Should I rebase my docker fixes (#9805) and try again?  Sorry for any extra noise.

@tgamblin, @becker33

**Comment by alalazo** [comment]
@opadron Do we need to keep track of this issue or is it fine to close it?

**Comment by opadron** [comment]
Closing.  This doesn't appear to be an issue, anymore.
