### ISSUE TITLE
version(git=..., ...) vs. git=... version(...)

### ISSUE THREAD

**Issue by dokempf** [spack/spack#9833]
There is currently to possible ways to pass the repo URL to the GitFetchStrategy:

```
class MyPackage(Package):
    git="https://whatsoever.org"
    version("master", branch="master")
```
and
```
class MyPackage(Package):
    version("master", git="https://whatsoever.org", branch="master")
```

I would have believed that the first is a sort of shortcut for the latter in the presence of many versions. Unfortunately, they behave differently. If you come through a code path that needs to select a fetch strategy for a version (e.g. in `spack.fetch_strategy.for_package_version`), the required attributes for the git strategy are not matched for the first version, but are for the latter. This leads to weird mistakes.

Documentation only explains the first one.

I am not sure what is the correct way to fix this inconsistency. Possible ways:
* Document the behaviour
* Deprecate the first behaviour
* Include the packages `git` field into the version in the first case to make it work identical (no idea whether its possible)

**Comment by adamjstewart** [comment]
Both of these forms should be equivalent. Are you on the latest develop branch? This feature was added fairly recently. If so, can you provide an example package to reproduce the problem? I am not able to reproduce the problem with the first example you list.

**Comment by dokempf** [comment]
Maybe it is relevant, that I was experiencing this problem while testing #7830?

**Comment by adamjstewart** [comment]
Yes, that pull request branch is 7 months old, before the new git feature was added. Let me know if you're able to reproduce this bug on the latest develop branch.

**Comment by adamjstewart** [comment]
I'm guessing this issue is no longer relevant, reopen if I'm wrong.
