### ISSUE TITLE
Issues sourcing setup-env.sh on macOS

### ISSUE THREAD

**Issue by mathomp4** [spack/spack#9841]
All, I'm coming back to trying `spack` after a long time away with a goal to getting a working ESMF build for GEOS, a model I help maintain, after attending some SC18 sessions. All the new features look amazing!

So, before, I was using `spack` with `tcsh` and I even contributed some code for the `setup-env.csh` script. But I've migrated to use `bash` on my macOS laptop because `bash` is infinitely better. However, I seem to be stuck at, oh, the second step of installation after cloning. My guess is it's due to my current macOS + Homebrew + lmod setup, but I'm not sure what I did.  My prompt? I'm baffled. To wit:

### Steps to reproduce the issue

```console
[mathomp4:~/spack] develop 3m30s ± . share/spack/setup-env.sh
usage: dirname path
usage: dirname path
bash: total: No such file or directory
```

Well, that's not great. But I've [seen issues like that on macOS before](https://stackoverflow.com/questions/1308823/os-x-bash-dirname). So, my first thought is I should try using GNU `dirname` instead of the macOS BSD `dirname`. I link the `gdirname` from Homebrew into `~/bin/dirname` and:

```console
[mathomp4:~/spack] develop 3m1s ± . share/spack/setup-env.sh
dirname: invalid option -- 'r'
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
bash: total: No such file or directory
```
Well, nuts. Obviously I've done something very bad to my bash environment, but I'm not sure what. Any ideas?

### Information on your system

OS: macOS 10.13.6
Shell: bash GNU bash, version 4.4.23(1)-release

Also: I moved away my (I'm guessing) old `.spack` directory which had `packages.yaml` and `modules.yaml` just in case it was the issue.

**Comment by adamjstewart** [comment]
> I'm coming back to trying spack after a long time away with a goal to getting a working ESMF build for GEOS

Welcome back! I would love to see a working ESMF build. I wrote the original ESMF package in #2831, but ran into problems since NetCDF-C and Fortran had been split and ESMF didn't like them installed in separate directories. I've also contributed to the GEOS package before (was working on a more fully-featured GDAL package), so ping me when you finish and I can review/merge.

I'm also using Spack on macOS with a Homebrew-installed Bash 4.4, although I'm not using LMod locally. I don't have any trouble sourcing the shell script, so it's definitely a problem specific to your machine. For debugging purposes, can you give me the output of the following command?
```console
$ set -x
$ . share/spack/setup-env.sh
$ set +x
```
This should tell me where the script is failing.

**Comment by mathomp4** [comment]
It was...a lot of lines, so here is [spack_echo.txt](https://github.com/spack/spack/files/2590611/spack_echo.txt)

I'm guessing I'm doing something stupid with bashrc, so here is [mybashrc](https://github.com/spack/spack/files/2590616/mybashrc.txt)

Also, my GEOS is not that GEOS. That GEOS is a much easier build. :)

**Comment by mathomp4** [comment]
> Of course, we could add `builtin` before every system command in every shell script, but I think it's not unreasonable to expect that `cd` behaves the way it is expected to.

Well, I wouldn't mind you doing that. :) I tried looking around on Bash documents for a bit of text that said "One shall always use builtin in scripts" but couldn't find it.

But for now, I can comment that out for testing purposes. Worse comes to worse, I can always edit the setup script locally.
