### ISSUE TITLE
Support more development use cases in "spack diy"

### ISSUE THREAD

**Issue by HadrienG2** [spack/spack#9855]
While the main goal of spack should probably remain installation of production-quality software, over time I've come to appreciate its usefulness for configuration and dependency management in software development. For full support of this use case, however, `spack diy` could use more flexibility.

### Rationale

Software that is painful to install due to an excessively convoluted dependency setup is also painful to work on as a software developer. Spack can help here by collecting the needs of software projects and managing the installation of "uninteresting" dependencies, leaving the developer free to focus on the "interesting" software project at hand. Basically, it quickly gets you to the point where you have a working build of your software project, and then you can enter the usual read-edit-compile cycle.

The way I currently do this is to setup a git repo on my development system in the usual way (upstream repo + fork), then do a `spack diy <project>@develop <options>` to configure a build, kill it after configuration (I'll explain why in a minute), and trigger further work with a `spack build-env <project>@develop <command>`. For example, on a CMake-based project, the cycle `spack build-env <project>@develop make -j8 && spack build-env <project>@develop ctest -j8` is common.

Obviously though, the whole process is hacky, especially the "starting the diy and killing it in the middle" part, and I'm wondering how I could do this better.

### Description

To make the workflow above more convenient, I would need two things:

1. A way to make "spack diy" stop after the configuration or the build instead of installing
2. A way to permanently load the build environment of a project so as not to type "build-env" over and over again.

I suspect that the recently introduced spack features such as advanced module usage or environments might help with point 2. I need to look into that. However, as far as I know, nobody is currently exploring point 1 (making spack diy more flexible), which is why I'm opening a ticket to discuss it.

**Comment by healther** [comment]
> A way to permanently load the build environment of a project so as not to type "build-env" over and over again.

Why does `spack build-env <spec> bash` (or equivalent for your shell) not work for you?

**Comment by HadrienG2** [comment]
Because I did not think about it! :smile: Thanks for the suggestion.

I guess this only leaves my request for a form of `spack diy` which does not install the package at the end (i.e. is to regular `spack diy` what `spack build` is to `spack install`).

**Comment by citibeth** [comment]
Do you think this is already covered by #7846?  Now that Spack Environments have been merged, we should be able to (finally at long last) get this one in too!

**Comment by HadrienG2** [comment]
@citibeth As far as I am concerned, it is hard to answer the question, as it is not 100% clear to me what the linked PR does. Perhaps you have some higher-level documentation available in a ticket somewhere that I could study?

**Comment by HadrienG2** [comment]
Ah, nevermind, I found something in the PR linked in the description of that PR. Yes, it seems like it could address this use case quite well.

**Comment by citibeth** [comment]
On Wed, Jan 30, 2019 at 2:28 PM Robert Blake <notifications@github.com>
wrote:

> I too would also like this. Now that #7846
> <https://github.com/spack/spack/pull/7846> has been deprecated, how
> should we go about this?
>

#10403 will be merged soon.


> To use an analogy, "spack install" is to "spack diy" as "spack build" is
> to ????? Is there a "spack diy --build" equivalent?
>
What is "spack build", and what would "spack diy --build" do?

**Comment by rblake-llnl** [comment]
Is there a clear explanation of spack setup and spack install --setup ?  Perhaps these already do what I want.  I read through the attached PRs but can't puzzle things out.

I would like to use spack in a development environment. Ideally, "spack diy --build spec" would

- install all the dependencies for spec 
- run the configure/build steps for the root spec using the current directory
- skip the installation of spec

@HadrienG2 's original post above describes my needs exactly.  As it exists now, I can use diy provided that I kill the build before spack runs the installation.  This feels hacky.

**Comment by citibeth** [comment]
On Wed, Jan 30, 2019 at 3:59 PM Robert Blake <notifications@github.com>
wrote:

> Is there a clear explanation of spack setup and spack install --setup ?
> Perhaps these already do what I want. I read through the attached PRs but
> can't puzzle things out.
>
There will be once we add docs to the PR.


> I would like to use spack in a development environment. Ideally, "spack
> diy --build spec" would
>
>    - 1. install all the dependencies for spec
>    - 2. run the configure/build steps for the root spec using the current
>    directory
>    - 3. skip the installation of spec
>
>
Spack setup does (1), and generates a script that does (2).  When you
change your CMake build, you re-run (2).  You only have to re-run Spack if
depndencies change.


>
>
> @HadrienG2 <https://github.com/HadrienG2> 's original post above
> describes my needs exactly. As it exists now, I can use diy provided that I
> kill the build before spack runs the installation. This feels hacky.
>
 Right now, Spack Setup only works with CMake.  I think we can/should
create a generalization that works for all build systems.  But Spack Setup
has been created and then not merged so many times; I'd like to see what we
have get merged first, before we re-factor it (again).

-- Elizabeth

**Comment by rblake-llnl** [comment]
What directory does setup use?  If I'm developing custom source code, does that code have to live within the main spack directory?  

I just took setup for a spin, and that's what it seemed to do by default.

**Comment by alalazo** [comment]
@HadrienG2 Looking at your 2 requests in this old discussion:

> To make the workflow above more convenient, I would need two things:
>
> 1. A way to make "spack diy" stop after the configuration or the build instead of installing
> 2. A way to permanently load the build environment of a project so as not to type "build-env" over and over again.

it seems to me they are already taken care by [spack dev-build](https://spack-tutorial.readthedocs.io/en/latest/tutorial_developer_workflows.html). Are the capabilities shown in the tutorial enough to close this issue?

**Comment by HadrienG2** [comment]
Indeed, with spack's new capabilities and improved documentation, I consider this issue to be resolved.
