### ISSUE TITLE
gtk-docs related "ImportError: no module named six/site" errors

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#9894]
This error shows up in installation of quite a few packages related to the GTK stuff.
glib, gdk-pixbuf, harfbuzz (and more ...) as discussed in #9879 #9769 #9885 #9771.

If i understand it correctly, the error originates from the fact that these packages automatically detect gtk-doc installations in the system which have python dependencies that aren't matched by the python provided by Spack.

```commandline
$ uname -a 
Linux somehost 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description: Linux Mint 19 Tara (=
Ubuntu 18.04.1 LTS)
```

**Comment by Sinan81** [comment]
For the above mentioned packages, PRs have already been submitted. And PRs for the following packages will be submitted soon:
- pango
- gtkplus

**Comment by alalazo** [comment]
@Sinan81 Is there anything still to be done before we close this issue?

**Comment by Sinan81** [comment]
It can be closed. Thanks
