### ISSUE TITLE
installation issue: openmpi-4.0.0

### ISSUE THREAD

**Issue by gsjaardema** [spack/spack#9917]
```console
$ spack install exodusii 

==> Installing openmpi
==> Searching for binary cache of openmpi
==> Warning: No Spack mirrors are currently configured
==> No binary for openmpi found: installing from source
==> Using cached archive: /Users/gdsjaar/src/spack/var/spack/cache/openmpi/openmpi-4.0.0.tar.bz2
==> Staging archive: /Users/gdsjaar/src/spack/var/spack/stage/openmpi-4.0.0-prj2nklqcwsojrtgpo4g4jwpdjqbdvg4/openmpi-4.0.0.tar.bz2
==> Created stage in /Users/gdsjaar/src/spack/var/spack/stage/openmpi-4.0.0-prj2nklqcwsojrtgpo4g4jwpdjqbdvg4
==> No patches needed for openmpi
==> Building openmpi [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

5 errors found in build log:
     9490    Making all in mpi/fortran/mpiext-use-mpi
     9491      PPFC     mpi-ext-module.lo
     9492    mpi-ext-module.F90:29:132:
     9493
     9494           include '/Users/gdsjaar/src/spack/var/spack/stage/openmpi-4.0.0-prj2nklqcwsojrtgpo4g4jwpdjqbdvg4/openmpi-4.0.0/ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpi
             fh.h'
     9495                                                                                                                                        1
  >> 9496    Error: Line truncated at (1) [-Werror=line-truncation]
     9497    mpi-ext-module.F90:29:6:
     9498
     9499           include '/Users/gdsjaar/src/spack/var/spack/stage/openmpi-4.0.0-prj2nklqcwsojrtgpo4g4jwpdjqbdvg4/openmpi-4.0.0/ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpi
             fh.h'
     9500          1
  >> 9501    Error: Unclassifiable statement at (1)
     9502    f951: some warnings being treated as errors
  >> 9503    make[2]: *** [mpi-ext-module.lo] Error 1
  >> 9504    make[1]: *** [all-recursive] Error 1
  >> 9505    make: *** [all-recursive] Error 1``
```

Please report your OS here:
```commandline
$ uname -a 
Darwin s1018191 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64
```

**Comment by ben-s-southworth** [comment]
I have a similar problem. I tried to install armadillo, and spack was installing openmpi-4.0.0 as a dependency when I got the error

`make[2]: Entering directory `/tmp/bs/spack-stage/spack-stage-L5B6az/openmpi-4.0.0/ompi/mpi/fortran/mpiext-use-mpi'
  PPFC     mpi-ext-module.lo
mpi-ext-module.F90:29.6:

      include '/g/g19/bs/spack/var/spack/stage/openmpi-4.0.0-lrvs2hbgqmwisjrdlgdreu3blp6yhaeu/openmpi-4.0.0/ompi/mpiext/pcollreq/mpi
      1
Error: Unclassifiable statement at (1)
make[2]: *** [mpi-ext-module.lo] Error 1
make[2]: Leaving directory `/tmp/bs/spack-stage/spack-stage-L5B6az/openmpi-4.0.0/ompi/mpi/fortran/mpiext-use-mpi'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/bs/spack-stage/spack-stage-L5B6az/openmpi-4.0.0/ompi'
make: *** [all-recursive] Error 1`

OS:
`Linux quartz18 3.10.0-862.14.4.1chaos.ch6.x86_64 #1 SMP Wed Sep 26 12:27:08 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by thelfer** [comment]
The same error occurs on Debian stretch.

**Comment by thelfer** [comment]
As the error message states, the issue is about a file path which is too long.
It seems that the path is relative when building out of spack, and absolute when building in the spack environment.

mpi-ext-module.f90 out of spack:

~~~~
!     Enabled Extension: pcollreq
!
      include '../openmpi-4.0.0/ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpifh.h'
#include "../openmpi-4.0.0/ompi/mpiext/pcollreq/use-mpi/mpiext_pcollreq_usempi.h"
~~~~

mpi-ext-module.f90 in spack:

~~~~
      include '/tmp/spack/var/spack/stage/openmpi-4.0.0-dbiwp3ertuxqtwu7oualhe26j4utf4u2/openmpi-4.0.0/ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpifh.h'
#include "/tmp/spack/var/spack/stage/openmpi-4.0.0-dbiwp3ertuxqtwu7oualhe26j4utf4u2/openmpi-4.0.0/ompi/mpiext/pcollreq/use-mpi/mpiext_pcollreq_usempi.h"
~~~~

This line is generated by ompi_ext.m4. In both cases, the path is deduced from the `${srcdir}` variable.  Known the question is to know why the variable is relative in one case and absolute in the other.

**Comment by adamjstewart** [comment]
OpenMPI 4 is no longer the default. If you update your Spack to the latest develop, it should install OpenMPI 3 for you without any problems.
